### ISSUE TITLE
LOADING_SOURCE_CODE

### ISSUE THREAD

**Issue by yuanman0109** [umijs/qiankun#100]
## What happens?
本地启动了例子中的main项目，改了第一个enter指向到我其他项目，其他项目已经配置了umd，但是依然报：Uncaught react app: Application 'react app' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in react app entry；看了下正常的项目打出来的js是带有async的钩子函数，
![image](https://user-images.githubusercontent.com/22994293/66381194-6c980800-e9eb-11e9-9786-2e4459b65921.png)；但是我自己的项目打出来的并不是这样：
![image](https://user-images.githubusercontent.com/22994293/66381256-8e918a80-e9eb-11e9-8890-a5b2d72687c4.png)；是否是因为被babel转了导致的这个问题呢？

**Comment by yuanman0109** [comment]
是否是因为async转换成es5后导致识别不了？

**Comment by kuitos** [comment]
@yuanman0109 不会

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by yuanman0109** [comment]
@kuitos https://github.com/yuanman0109/test-qiankun

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/66478417-f1a71e00-eacc-11e9-81fd-4d578862c72b.png)

多 entry 的时候配置成这样

**Comment by yuanman0109** [comment]
tks，的确好了
