### ISSUE TITLE
子应用有动态路由时无法正确显示，但是提前定义好的静态路由可以正确加载

### ISSUE THREAD

**Issue by GonyMaster** [umijs/qiankun#1000]
## What happens?
通过主应用访问子应用 当子应用有动态路由时无法正确加载动态路由 但是提前定义好的静态路由可以正确加载

直接访问子应用正常

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.0.25
- **Platform Version**:win10
- **Browser Version**:chrome

**Comment by gongshun** [comment]
试了下，vue-router 动态添加的路由，页面可以正确加载。给个demo看看？

**Comment by GonyMaster** [comment]
@gongshun  最后我这边把动态获取的路由改成同步获取的方式来解决的

**Comment by guopz** [comment]
怎么同步的，第一次正常，关闭再打开其他子应用路由，还停留在上一次

**Comment by 414022688** [comment]
子应用动态路由第二次进去 不能正常加载，从主应用点击进入子应用 子应用动态获取路由 能正常正常加载， 然后点击跳回主应用，再进入子应用就无法正确加载路由，

**Comment by 414022688** [comment]
子应用动态路由第二次进去 不能正常加载，从主应用点击进入子应用 子应用动态获取路由 能正常正常加载， 然后点击跳回主应用，再进入子应用就无法正确加载路由，
