### ISSUE TITLE
[Bug]子应用中使用canvg.js，加载报错

### ISSUE THREAD

**Issue by GabrielchenCN** [umijs/qiankun#1001]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

子项目加载该组件报错

https://github.com/canvg/canvg

https://unpkg.com/canvg@3.0.4/lib/umd.js

![image](https://user-images.githubusercontent.com/11185797/96119788-10ca5e00-0f20-11eb-9497-1456e68547d4.png)
![image](https://user-images.githubusercontent.com/11185797/96120392-052b6700-0f21-11eb-9600-79e70ba15f55.png)

## 最小可复现仓库

任何子项目在入口html中引入

<script src="https://unpkg.com/canvg@3.0.4/lib/umd.js"></script>

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**

- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
用 react15 的 demo 跑了一遍，无法复现

**Comment by GabrielchenCN** [comment]
在项目内部中重新打包就可以
