### ISSUE TITLE
[import-html-entry]: error occurs while executing entry script

### ISSUE THREAD

**Issue by huangche007** [umijs/qiankun#1004]
## What happens?

在主应用和子应用中使用babel-polyfill，出现了下面的问题。

 [import-html-entry]: error occurs while executing entry script http://localhost:8081/static/js/main.js

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.0.26
- **VueJS Version**:2.6.10

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/947
