### ISSUE TITLE
引用qiankun框架报错，Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by CIGE-Vince** [umijs/qiankun#1009]
引用qiankun框架报错，网上查了是插件报错，这是为什么有大佬知道吗
![图片](https://user-images.githubusercontent.com/25953903/96662088-2c01f700-1380-11eb-8488-7a34b29f9537.png)
![图片](https://user-images.githubusercontent.com/25953903/96662106-358b5f00-1380-11eb-986c-310b84d9537c.png)

**Comment by CIGE-Vince** [comment]
qiankun 的版本是2.0.16

**Comment by lijing666** [comment]
> 引用qiankun框架报错，网上查了是插件报错，这是为什么有大佬知道吗
> ![图片](https://user-images.githubusercontent.com/25953903/96662088-2c01f700-1380-11eb-8488-7a34b29f9537.png)
> ![图片](https://user-images.githubusercontent.com/25953903/96662106-358b5f00-1380-11eb-986c-310b84d9537c.png)

@CIGE-Vince qiankun是微前端框架和vue框架无关的，不是vue插件，当然不可以Vue.use

**Comment by CIGE-Vince** [comment]
> 
> 
> > 引用qiankun框架报错，网上查了是插件报错，这是为什么有大佬知道吗
> > ![图片](https://user-images.githubusercontent.com/25953903/96662088-2c01f700-1380-11eb-8488-7a34b29f9537.png)
> > ![图片](https://user-images.githubusercontent.com/25953903/96662106-358b5f00-1380-11eb-986c-310b84d9537c.png)
> 
> @CIGE-Vince qiankun是微前端框架和vue框架无关的，不是vue插件，当然不可以Vue.use

好的

**Comment by CIGE-Vince** [comment]
> 
> 
> > > 引用qiankun框架报错，网上查了是插件报错，这是为什么有大佬知道吗
> > > ![图片](https://user-images.githubusercontent.com/25953903/96662088-2c01f700-1380-11eb-8488-7a34b29f9537.png)
> > > ![图片](https://user-images.githubusercontent.com/25953903/96662106-358b5f00-1380-11eb-986c-310b84d9537c.png)
> > 
> > 
> > @CIGE-Vince qiankun是微前端框架和vue框架无关的，不是vue插件，当然不可以Vue.use
> 
> 好的

谢谢
