### ISSUE TITLE
You are loading the CommonJS build of React Router on a page that is already running the ES modules build, so things won't work right.

### ISSUE THREAD

**Issue by yuanguandong** [umijs/qiankun#1011]
## What happens?
父应用是umi工程
我的子应用的umi版本是2.x, 子应用是用的 umi-plugin-qiankun ，
在run的时候出现这个报错，
![image](https://user-images.githubusercontent.com/13197560/96693690-1f01f980-13ba-11eb-8592-74c1d40e4342.png)

是什么原因呢？

**Comment by kuitos** [comment]
https://www.google.com/search?q=You+are+loading+the+CommonJS+build+of+React+Router+on+a+page+that+is+already+running+the+ES+modules+build%2C+so+things+won%27t+work+right&oq=You+are+loading+the+CommonJS+build+of+React+Router+on+a+page+that+is+already+running+the+ES+modules+build%2C+so+things+won%27t+work+right

**Comment by junjie-lean** [comment]
@yuanguandong 哥们儿解决了吗，我也遇到这个问题了！
