### ISSUE TITLE
global遍历顺序变化，导致子应用entry无法找到导出的生命周期函数

### ISSUE THREAD

**Issue by imshenshen** [umijs/qiankun#1013]
## What happens?
（import-html-entry没找到issue入口，先提到这了）

### 先说问题

https://github.com/kuitos/import-html-entry/blob/master/src/utils.js#L65

如 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in 所写，for...in无法保证迭代对象key时的顺序。通过lastkey确定导出的Name，有可能不是预期的，建议有个配置来标明子应用导出的入口。

### 再说现象（这个现象和qiankun的版本***应该是***没关系的，但是目前还没时间查为什么版本和版本有关）
前提：我的子应用没变化、没编译、入口JS维持不变；只改变主App使用的qiankun版本；

当我使用`qiankun@2.0.20`版本时：可以识别出entry: `wht-app`
1. `import-html-entry`执行`noteGlobalProps`后，$index_first = `window` , $index_last = `webpackHotUpdatewht__name_`
2. `import-html-entry`执行`geval( getExecutableScript() )`后，$index_first = `window`, $index_last = `wht-app`

当我升级`qiankun@2.2.0`版本时：无法识别出entry: `myMicroAppName`（因为遍历的第一个key是`parseFloat`，$index_first已经不是快照时的第一个值window了）
1. `import-html-entry`执行`noteGlobalProps`后，$index_first = `window` , $index_last = `webpackHotUpdatewht__name_`
2. `import-html-entry`执行`geval( getExecutableScript() )`后，$index_first = `parseFloat`, $index_last = `wht-app`

## Mini Showcase Repository(REQUIRED)

无法提供

## Context

- **qiankun Version**: 2.2.0
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
获取生命周期函数有兜底方案: https://github.com/umijs/qiankun/blob/3d89ed170a6428b072ef78e7d867d9978bb81e66/src/loader.ts#L220  子项目 webpack 打包的 library 项的值与子项目的 name 一致，就可以保证主项目能获取到子项目导出的生命周期函数。

**Comment by imshenshen** [comment]
> 获取生命周期函数有兜底方案:
> 
> https://github.com/umijs/qiankun/blob/3d89ed170a6428b072ef78e7d867d9978bb81e66/src/loader.ts#L220
> 
> 子项目 webpack 打包的 library 项的值与子项目的 name 一致，就可以保证主项目能获取到子项目导出的生命周期函数。

你的意思是以后也不考虑`「export的包名和子App的name一致」为默认匹配，同时提供「某个配置来」设定子App入口`这样的方式，而是会一直把`「export的包名和子App的name一致」`当成一种fallback吗？

**Comment by fantasyroot** [comment]
> 获取生命周期函数有兜底方案:
> 
> https://github.com/umijs/qiankun/blob/3d89ed170a6428b072ef78e7d867d9978bb81e66/src/loader.ts#L220
> 
> 子项目 webpack 打包的 library 项的值与子项目的 name 一致，就可以保证主项目能获取到子项目导出的生命周期函数。

是识别错了，不是识别不到。 如果识别不到，会有兜底，但如果识别错了，错误的对象上是没有挂生命周期方法的

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/485#issuecomment-617677419
