### ISSUE TITLE
application 'vue-app' died in status LOADING_SOURCE_CODE: Illegal invocation

### ISSUE THREAD

**Issue by CIGE-Vince** [umijs/qiankun#1014]
主应用：nuxt
子应用：vue-cli

可以确定vue-cli 可用，因为接入另外一个主应用成功

在配置主应用时出现以下问题：
![图片](https://user-images.githubusercontent.com/25953903/96809103-cd567f00-144c-11eb-93d1-57fc85b9229c.png)

**Comment by CIGE-Vince** [comment]
有大佬能帮忙看看为什么吗

**Comment by caoyong195** [comment]
我也是 在打包部署后 出现的

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/1046#discussion_r517842341

**Comment by kuitos** [comment]
提供可复现仓库后可以自己 reopen
