### ISSUE TITLE
[Bug]从v2.0.16升级到v2.2.0后__POWERED_BY_QIANKUN__标识is not defined的问题

### ISSUE THREAD

**Issue by fe-cookbook** [umijs/qiankun#1017]
# 从v2.0.16升级到v2.2.0后__POWERED_BY_QIANKUN__标识is not defined的问题

## 相关环境信息

- **qiankun 版本**：v2.2.0
- **浏览器版本**：版本 85.0.4183.121（正式版本） （64 位）
- **操作系统**：mac 10.14.6 (18G95)

**Comment by kuitos** [comment]
官方 demo 没有复现，提供可复现仓库后可以自己 reopen
