### ISSUE TITLE
react-router-dom v6 路由异常

### ISSUE THREAD

**Issue by WinmezzZ** [umijs/qiankun#1019]
## What happens?

使用 v6 版本的 `react-router-dom` 渲染异常  

除了初始路由渲染正常，点击 Link 按钮或者路由 navigate 方法后直接覆盖 basename

如： 原本是 localhost:3000/project-a，调用 `navigate('/about') ` 或者点击 `<Link to="/about">About</Link>`  之后地址就变  localhost:3000/about，预想的应该是 localhost:3000/project-a/about

## Mini Showcase Repository(REQUIRED)

```tsx
export default function App() {
  return (
    <BrowserRouter>
      <Routes basename={window.__POWERED_BY_QIANKUN__ ? '/project-a' : '/'}>
        <nav>
          <Link to="/">Home</Link>
          <Divider type="vertical" />
          <Link to="/about">About</Link>
        </nav>
        <Suspense fallback={null}>
          <Route path="/" element={<Home/>} />
          <Route path="/about" element={<About/>} />
        </Suspense>
      </Routes>
    </BrowserRouter>
  );
}
```

## How To Reproduce

**Steps to reproduce the behavior:** 使用上述代码

**Expected behavior** 路由正常渲染

## Context

- **qiankun Version**: 2.2.0 
- **Platform Version**: Windows 10
- **Browser Version**: Chrome 84.0.4147.105

**Comment by WinmezzZ** [comment]
@kuitos 有解决方案吗

**Comment by kuitos** [comment]
这个跟 qiankun 没啥关系，你需要去 react-router-dom 社区找答案

**Comment by WinmezzZ** [comment]
> 这个跟 qiankun 没啥关系，你需要去 react-router-dom 社区找答案

有依据吗

**Comment by kuitos** [comment]
你单独打开子应用看有没有问题就知道了

**Comment by wibed** [comment]
@WinmezzZ 
you can work around it by manually setting a basename like this:
```
export default function App() {
  const basename = "/project-a"
  return (
    <BrowserRouter>
      <Routes basename='/'>
        <nav>
          <Link to="/">Home</Link>
          <Divider type="vertical" />
          <Link to="/about">About</Link>
        </nav>
        <Suspense fallback={null}>
          <Route path={`${basename}/`} element={<Home/>} />
          <Route path={`${basename}/about`} element={<About/>} />
        </Suspense>
      </Routes>
    </BrowserRouter>
  );
}
```
