### ISSUE TITLE
[咨询]怎么让开发更顺畅？

### ISSUE THREAD

**Issue by CodeLittlePrince** [umijs/qiankun#102]
## 遇到问题?

从demo使用方式来看，子应用通过实现生命周期中的moun来挂载渲染dom。所以本地开发子应用不得不先启整个主应用，然后才能开发。不然就是手动在子应用的入口文件先执行挂载dom相关代码，然后上线的时候再删除。

## 疑问
那就好奇这个框架作者自己再蚂蚁用的时候是怎么个开发方式呢？

**Comment by leimingzhang** [comment]
同样好奇，请问你搞懂了吗

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#how-to-make-sub-app-to-run-independently
