### ISSUE TITLE
请问跟技术栈无关，那可以加载jsp的项目作为子应用吗？

### ISSUE THREAD

**Issue by wxwzl** [umijs/qiankun#1022]
请问跟技术栈无关，那可以加载jsp的项目作为子应用吗？

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F

**Comment by wxwzl** [comment]
不行啊，挂载逻辑呢，jsp页面是已经写好的了，既有静态的dom节点在html页面里，又有动态的js生成的节点，而静态的dom节点是要html页面在浏览器执行完才能知道的
