### ISSUE TITLE
主应用使用嵌套路由加载子应用无法显示

### ISSUE THREAD

**Issue by n3taway** [umijs/qiankun#1023]
## 最小可复现仓库
[仓库地址](https://github.com/n3taway/qiankun-not-load-micro-fe.git)

## 复现步骤，错误日志以及相关配置
主应用和子应用都是使用以下命令初始化的
`yarn create @umijs/umi-app`
`yarn add @umijs/plugin-qiankun -D`

主应用和子应用都是使用的hash路由
主应用使用 `<MicroApp/>` 组件形式加载的子应用

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：chrome  86.0.4240.111（正式版本） (x86_64)
- **操作系统**：macos 10.15.6

**Comment by kuitos** [comment]
子应用配的路由只会匹配到 `/` 路径，非 '/' 路径自然加载不到 https://github.com/n3taway/qiankun-not-load-micro-fe/blob/master/sub/.umirc.ts#L12
