### ISSUE TITLE
请问跟技术栈无关，那可以加载jsp的项目作为子应用吗？

### ISSUE THREAD

**Issue by wxwzl** [umijs/qiankun#1026]
我看乾坤子应用的加载逻辑，首先需要拿到页面的整个dom结构，但在jsp页面里怎么拿到整个完整的dom结构，jsp页面里既有静态的dom片段又有js动态生成的dom片段，它们不想vue或react，页面的整个dom片段都是通过js渲染函数渲染出来的，甚至所有的css样式和图片等静态资源都是通过js管理。

**Comment by kuitos** [comment]
> jsp页面里既有静态的dom片段又有js动态生成的dom片段，它们不想vue或react，页面的整个dom片段都是通过js渲染函数渲染出来的，甚至所有的css样式和图片等静态资源都是通过js管理。

vue/react 本地开发时通常都是 js 动态加载的

建议跑下 example 看下原理

**Comment by KellenHe** [comment]
jsp属于后端渲染，应该是接入不了qiankun的。

**Comment by iplus26** [comment]
其实可以，我们这里接入了 ssr 架构的项目作为子项目。

**Comment by huqiliang** [comment]
应该可以的 我一直有个困惑 子应用为什么一定要导出生命周期？？？约定没有不是更不容易侵入子应用么

**Comment by liuwu1211** [comment]
> 其实可以，我们这里接入了 ssr 架构的项目作为子项目。

都ssr了，还用微前端吗，Nginx路由分发不就行了

**Comment by lz-lee** [comment]
> 其实可以，我们这里接入了 ssr 架构的项目作为子项目。

请问你们的 ssr 是基于 Next.js 或者 Nuxt.js 的吗？尝试用 Next.js 作为主/子应用来接入 qiankun 发现都会报 window is not defined 这个错，猜测是服务端预渲染生成 html 时跑 qiankun 的代码找不到 window 报的。

**Comment by Vera1128** [comment]
> > 其实可以，我们这里接入了 ssr 架构的项目作为子项目。
> 
> 请问你们的 ssr 是基于 Next.js 或者 Nuxt.js 的吗？尝试用 Next.js 作为主/子应用来接入 qiankun 发现都会报 window is not defined 这个错，猜测是服务端预渲染生成 html 时跑 qiankun 的代码找不到 window 报的。

同问，这个问题解决了吗，我这边也是打算使用Next.js作为子应用

**Comment by Guo-dalu** [comment]
+1

**Comment by jefferyjob** [comment]
+1

**Comment by Vera1128** [comment]
这是一封自动回复邮件。您好，你的邮件我已收到，会尽快给您回复，祝您生活愉快！
