### ISSUE TITLE
求答疑：主应用为antd-pro，微应用为vue，微应用的二级页面在主应用刷新时，报404

### ISSUE THREAD

**Issue by zsfish** [umijs/qiankun#1027]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
主应用为antd-pro，微应用为vue，微应用的二级页面在主应用刷新时，报404。求问是需要额外配置什么吗

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置

主应用用的是antd-pro，微应用用的是vue。
主应用的是hash模式，微应用也在所有路由前面加了前缀。主应用只配置了微应用顶层的路由作为入口
在主应用内，从微应用首页进入二级页面，可正常显示。但在主页面刷新后，二级页面会显示404。通过打印，得知二级页面刷新时，未进入mounted生命周期内，未触发render

## 相关环境信息

- **qiankun 版本** 2.2.1
- **浏览器版本**： chrome 86.0.4240.111
- **操作系统**：windows 10

**Comment by gongshun** [comment]
看一下你注册子应用时的 activeRule 是怎么写的。

你的容器是否写在了某个路由页面，如果是，你配置路由时需要加一个*。例如，你的子应用都在 `#/child/` 页面，你主项目配置路由时，`path`必须写`/child/*`

**Comment by zsfish** [comment]
activeRule是这么写的：
 genActiveRule(routerPrefix) {
    return () => this.routerConfig && this.props.location.pathname.startsWith(routerPrefix);
  }
routerPrefix即为注册的微应用的前缀,假设为child

容器不是写在某个路由页面里的，是直接在antd-pro的basicLayout里进行注册，然后渲染。我是把子应用的入口写在了router.config.js里，如下：
const routes = [
...
 {
    path: '/',
    component: '../layouts/basicLayout',
    routes: [
      // 子应用路由,同一个子应用，主应用提供两个入口
       {
           path: '/child/componentMgt',
           routes: [
             { path: '/child/componentMgt/operate' }
             component: './subpage', // subpage就是一个函数式组件，返回一个空的div用来渲染
           ]
       },
      {
          path: '/child/dataMgt',
           routes: [
             { path: '/child/dataMgt/operate' }
             component: './subpage', // subpage就是一个函数式组件，返回一个空的div用来渲染
           ]
      }
    ]
 }
...
]

这样写的话，主应用刷新子应用的二级路由页面时，主页面不会报404，但是会一直显示加载中，因为二级路由进不了vue的mounted函数

**Comment by gongshun** [comment]
你的主子项目都是 `hash` 模式，你为啥用 `pathname` 来判断 `activeRule` 呢，

**Comment by zsfish** [comment]
因为只有这个有当前的url信息，已确定主应用确实是使用的hash模式。也确定该判断条件返回为true。当刷新主应用，访问子应用二级页面时，微应用main.js全局的打印语句也生效。

**Comment by gongshun** [comment]
提供个demo吧

**Comment by zsfish** [comment]
感谢回复，我在写demo的时候，发现activeRule的判断在刷新后不成立，改下就可以了。
