### ISSUE TITLE
求答疑: 子应用独立运行场景访问另一个子应用

### ISSUE THREAD

**Issue by xoptimal** [umijs/qiankun#1029]
搭建主应用, 基于ant-pro 具备登录, 权限相关的校验功能, 嵌套子应用 (已实现) , 这是只有一个地址的情况下,

疑问1; 当子应用需要作为独立存在, 没有打开主应用的情况, 如何保留主应用的功能呢, 除了移植主应用代码外, 请问有什么方法 ?

疑问2: 子应用在不打开主应用的情况下, 子应用可以推送消息到另一个子应用吗 (当前浏览器标签打开2个子应用)?

我的场景应该是有5个子应用, 都能独立运行, 但是想相互推送消息, 我这个主应用应该搭建 , 5个应用自己就是主应用, 也是子应用 ?

**Comment by gongshun** [comment]
> 疑问1; 当子应用需要作为独立存在, 没有打开主应用的情况, 如何保留主应用的功能呢, 除了移植主应用代码外, 请问有什么方法 ?

没办法

>疑问2: 子应用在不打开主应用的情况下, 子应用可以推送消息到另一个子应用吗 (当前浏览器标签打开2个子应用)?

不可以

> 我的场景应该是有5个子应用, 都能独立运行, 但是想相互推送消息,

部署到同一域名下，`localStorage` 不就可以互相推送消息吗
