### ISSUE TITLE
[Feature Request] 关于子应用嵌套和子应用并行

### ISSUE THREAD

**Issue by chairui2001** [umijs/qiankun#103]
## Background

微前端宣传图片上提到：子应用嵌套和子应用并行两种进阶用法，但是没找到相关文档和demo

## Proposal

对这一块儿很感兴趣，能否抽时间整理点文档和demo

## Additional context

>  子应用嵌套 和 子应用并行 是微前端的进阶应用，在某些场景下会用到。

**Comment by kuitos** [comment]
这个是2.0里会支持的能力，可以watch一下项目保持关注

**Comment by JqiangLiu** [comment]
@kuitos 问个问题,旧项目迁移整合(多个vue单页面项目整合),做成一个类单页面应用.把导航栏(路由)提取做一个独立子项目.旧项目都包含不止一个路由,提取后是不是所有的路由都要在入口进行注册?
