### ISSUE TITLE
能够动态增加子应用吗？

### ISSUE THREAD

**Issue by wisdomG** [umijs/qiankun#1030]
有个场景是这样的，用户在主应用中启动了一个容器，我想把这个容器提供的服务作为一个子应用插入到主应用中。

我看文档上说的动态配置子应用也是在主应用启动的时候把所有的子应用配置都获取下来，并没有提到是否能在不重载主应用的前提下动态增加子应用，想问下有这方面的实现吗？

**Comment by gongshun** [comment]
可以的，registerMicroApps 可以调用多次
