### ISSUE TITLE
[Bug]应用来回切换样式丢失

### ISSUE THREAD

**Issue by tree0313** [umijs/qiankun#1032]
## What happens?

应用来回切换样式丢失

## 最小可复现仓库

官网examples

## 复现步骤，错误日志以及相关配置

1.基于qiankun官网examples复现；
2.无报错，注意观察vue/vue3 about页面字体颜色。

npm examples:install
npm examples:start

qiankun examples 单实例运行，按如下顺序切换页面必现问题
vue home
vue3 home
vue home
vue about
vue3 home
vue3 about
vue home
vue about
vue3 home
vue3 about
vue home
vue about
vue3 home
vue3 about
... ...

会发现Vue about及Vue3 about页面样式丢失

注：目前只在Vue子应用中发现，不确定其余技术栈子应用是否有样式丢失问题

## 相关环境信息

- qiankun 2.2.2
- chrome 86
- macOS 10.15.7

**Comment by alkalixin** [comment]
同求，目前遇到了同样的bug。父应用用的组件传给子应用，然后在应用切换时偶尔会出现父应用中的组件样式丢失。

**Comment by XavierShi** [comment]
同求，父应用在一个页面启动了子应用，然后切换父应用路由到另一个页面的时候，父应用页面出现了样式丢失
