### ISSUE TITLE
[qiankun] You need to export lifecycle functions in xxx

### ISSUE THREAD

**Issue by nossika** [umijs/qiankun#1033]
## What happens?

依照官网快速上手的例子，在切换到微应用时出现报错。
![image](https://user-images.githubusercontent.com/17478591/97442248-990b2300-1964-11eb-9922-d4457d0746f1.png)

## 最小可复现仓库

https://github.com/nossika/qiankun-demo

## 复现步骤，错误日志以及相关配置

```
npm i
node server.js
```

打开 http://localhost:8080 加载主应用，页面正常显示。

打开 http://localhost:8080/micro-react-app 加载micro-react-app微应用，页面出现报错You need to export lifecycle functions。

![image](https://user-images.githubusercontent.com/17478591/97442610-0028d780-1965-11eb-98bd-d074b4aa4a95.png)

但测试了微应用的umd包，可以看到lifecycle都是正常导出的 （可以打开 http://localhost:8080/test-micro-react.html 查看控制台）

![image](https://user-images.githubusercontent.com/17478591/97443137-9e1ca200-1965-11eb-8b8a-8cddaca052ab.png)

试过FAQ里提供的解决方式，把registerMicroApps的name跟微应用导出的library手动保持一致，都是micro-react-app，依然没有解决。

尝试debug，对qiankun/es/loader.js这里的global做了for in查看属性，似乎没看到任何关于micro-react-app的字段

![image](https://user-images.githubusercontent.com/17478591/97444223-dbcdfa80-1966-11eb-82d4-cc1e5d3261e7.png)

不知道加载微应用时把micro-react-app加载到哪了。

## 相关环境信息

- **qiankun 版本**: 2.2.2
- **浏览器版本**：版本 86.0.4240.80（正式版本） (x86_64)
- **操作系统**：macOS 10.15.7

**Comment by gongshun** [comment]
https://github.com/nossika/qiankun-demo/blob/399bd3d41be8db0613a6f021d998935989d975e2/main/index.js#L7

如果你要用 `JS entry`，你需要这样写：
```js
entry: {
      scripts: ['//localhost:8080/micro-react/dist/main.js']
 }
```

**Comment by ChenYCL** [comment]
![image](https://user-images.githubusercontent.com/25706676/112101905-68ad7500-8be2-11eb-8e25-929f750da377.png)
这种写法是读的什么js作为entry js文件呢

**Comment by gongshun** [comment]
> ![image](https://user-images.githubusercontent.com/25706676/112101905-68ad7500-8be2-11eb-8e25-929f750da377.png)
> 这种写法是读的什么js作为entry js文件呢

先获取 `index.html` ，路径是 `//127.0.0.1:3001/sys-org/manage/index.html`，如果你这个 html 里面有 `<script>` 标记为entry，那么这个 js 就是 entry js

![image](https://user-images.githubusercontent.com/29347231/112104900-b2985a00-8be6-11eb-8c96-744598fc66fb.png)

没有标记，默认取最后一个 `<script>`

![image](https://user-images.githubusercontent.com/29347231/112104990-d22f8280-8be6-11eb-9589-ac97c610f7a3.png)
