### ISSUE TITLE
开发环境下 子应用热更新 主应用怎么同步更新内嵌的子应用?

### ISSUE THREAD

**Issue by zcc19910524** [umijs/qiankun#1034]
主应用是react, 子应用是umi, 加载子应用后 顶部一直显示 Disconnected from the devServer, trying to reconnect...

**Comment by conghuhu** [comment]
我也遇到了同样的问题，求解

**Comment by Leo-July** [comment]
> 我也遇到了同样的问题，求解

问题解决没。我是解决了。但是感觉有点奇怪
必须是在启动命令里配置 port
![image](https://user-images.githubusercontent.com/34851522/165920549-7b14f1f1-8dbd-49a7-a6da-0a9810440366.png)
 在config文件里配置，虽然启动端口都一样，但就会报 Disconnected错误
` devServer: {
    port: 9539,
  },`

**Comment by liangchaofei** [comment]
> > 我也遇到了同样的问题，求解
> 
> 问题解决没。我是解决了。但是感觉有点奇怪 必须是在启动命令里配置 port ![image](https://user-images.githubusercontent.com/34851522/165920549-7b14f1f1-8dbd-49a7-a6da-0a9810440366.png) 在config文件里配置，虽然启动端口都一样，但就会报 Disconnected错误 ` devServer: { port: 9539, },`

这个的解决办法是？
