### ISSUE TITLE
[Bug]直接 loadMicroApp 成功，5 秒后 single-spa 打印报错

### ISSUE THREAD

**Issue by lomocc** [umijs/qiankun#1036]
## What happens?

https://qiankun.umijs.org/ 按照 Getting Started 代码，运行之后可以加载模块，但是 singleSpa 报错了
```
singleSpa.start() has not been called, 5000ms after single-spa was loaded.
```

## 复现步骤，错误日志以及相关配置

```js
import { loadMicroApp } from 'qiankun';
// load micro app
loadMicroApp({
  name: 'reactApp',
  entry: '//localhost:7100',
  container: '#container',
  props: {
    slogan: 'Hello Qiankun'
  },
});
```

```js
if (isInBrowser) {
  setTimeout(() => {
    if (!started) {
      console.warn(
        formatErrorMessage(
          1,
          __DEV__ &&
            `singleSpa.start() has not been called, 5000ms after single-spa was loaded. Before start() is called, apps can be declared and loaded, but not bootstrapped or mounted.`
        )
      );
    }
  }, 5000);
}
```
## 相关环境信息

- **qiankun 版本** 2.0.26

**Comment by yaoyao0127** [comment]
这个应该就是因为你的start方法没有被执行吧

**Comment by lomocc** [comment]
>额，我手动加载，`start` 有什么用？
看了源码也是不需要的，如果是需要 `start` 那这个页面文档（https://qiankun.umijs.org/ ）为什么没说呢？
归根结底这个应该是 `single-spa` 的锅。

>`qiankun` 里的坑太多了。我估计很多人都不知道各个子模块是怎么暴露出自己的声明周期的。看了源码你会吓得哭。
感谢所有开源贡献者的付出，但是建议不要把有风险的接口带给大家，比如如果浏览器修改了对象的属性遍历顺序规则，就会蹦。

对比了几个月了，大家来用 `Webpack 5` 吧 https://github.com/module-federation/module-federation-examples ，作者别打我。

**Comment by kuitos** [comment]
> 看了源码你会吓得哭

多看看源码你就不会被吓哭，比如看看 system.js 是怎么处理的

> 比如如果浏览器修改了对象的属性遍历顺序规则

浏览器这么随意修改规则，当 ecmascript 规范不存在么😑

**Comment by lomocc** [comment]
*Note:* for...in should not be used to iterate over an Array
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array>
where
the index order is important.

Array indexes are just enumerable properties with integer names and are
otherwise identical to general object properties. There is no guarantee
that for...in will return the indexes in any particular order. The
for...in loop
statement will return all enumerable properties, including those with
non–integer names and those that are inherited.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in


Kuitos ***@***.***>于2021年4月26日 周一18:02写道：

**Comment by lomocc** [comment]
1. ES 规范并没有说保证这个顺序，你才是把谷歌浏览器当做了唯一实现。  
1. 就算有这个规范，如果在启动过程有别的代码污染了 window ，还是会有找不到模块的 bug 。

**Comment by kuitos** [comment]
推荐阅读 https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys ，里面有详细的对象属性遍历规则算法

当然不支持 es2015 的浏览器可能不按这个规范来实现，毕竟这个规范是在 es2015 才加入的，但是你不能说，只有 chrome 是唯一实现😑
