### ISSUE TITLE
使用entry scripts模式加载应用，Target container 报错

### ISSUE THREAD

**Issue by zhujun24** [umijs/qiankun#1038]
## What happens?

使用两个相同的极其精简的React项目分别作为主/子应用，按照文档调整子应用 webpack 配置和导出生命周期函数、主应用按照 entry: { scripts: [xxx] } registerMicroApps 注册&启动应用，显示 `died in status SKIP_BECAUSE_BROKEN: Target container is not a DOM element.`，实际上 container 在整个生命周期内都是存在的，直接写在主应用的 HTML 里。

原先未能成功运行的配置如下
```js
{
    name: 'sub-app-1',
    entry: { scripts: ['/7001/main.js'] },
    container: '#sub-app-1',
    activeRule: '/sub-app-1',
}
```

查阅 [Single-SPA 快速开始](https://zh-hans.single-spa.js.org/docs/getting-started-overview) 文档后，在子应用的 bootstrap 函数里面手动创建 div#sub-app-1 就可以了，注册子应用的时候，可以将 container 设置为空的 HTML 元素。

调整后能成功运行的配置如下
```js
{
    name: 'sub-app-1',
    entry: { scripts: ['/7001/main.js'] },
    container: document.createElement('div'),
    activeRule: '/sub-app-1',
}
```
对应子应用的 bootstrap 方法如下
```js
let domEl

const createContainer = () => {
  domEl = document.createElement('div');
  document.body.appendChild(domEl)
}

const render = () => ReactDOM.render(<App />, domEl)

if (!window.__POWERED_BY_QIANKUN__) {
  createContainer()
  render()
}

export async function bootstrap(props) {
  createContainer()
  console.log('react app bootstraped');
}
```

不知道为什么一开始在注册子应用的时候，设置的 container 不能成功运行？

## Mini Showcase Repository(REQUIRED)

https://github.com/zhujun24/zoo

## How To Reproduce

1 按照仓库内 nginx.conf 配置，并添加 host
2 分别进入main-app & defzult-app 目录, `npm start`

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.2.2
- **Platform Version**: macOS 10.15.7 (19H2)
- **Browser Version**: Chrome 86.0.4240.111 (Official Build) (x86_64)

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8-config-entry-%E6%97%B6%E5%BE%AE%E5%BA%94%E7%94%A8%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1

**Comment by justable** [comment]
@zhujun24 按照你的思路应该是这样写，但是不推荐。
```js
let domEl
export async function mount(props) {
  domEl = document.createElement('div')
  props.container.appendChild(domEl)
  ReactDOM.render(<App />, domEl)
}
```
