### ISSUE TITLE
[问题]关于跨域问题，主应用调用子应用的请求

### ISSUE THREAD

**Issue by wangfulaialan** [umijs/qiankun#1040]
## 背景

基于qiankun 使用手动加载方式调用，子应用为vue多页面，并且已部署到docker环境，nginx也参照官网链接设置了跨域请求（代码下图粘贴），vue主应用本地启动调用子应用依然显示跨域，请教下是否有相关解决方案

## 信息
下图为nginx配置：
![image](https://user-images.githubusercontent.com/40398699/97719300-e1ac1300-1b01-11eb-980e-3b73503d02f7.png)
下图为主应用调用子应用报错信息：
`Access to fetch at 'http://172.18.15.163:30321/wslb.html' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`index.js?88a9:244 GET http://172.18.15.163:30321/wslb.html net::ERR_FAILED`
`Uncaught (in promise) TypeError: Failed to fetch`

**Comment by gongshun** [comment]
允许跨域的请求头配置写到 `server` 里面，你这样写，只允许了 `http://172.18.15.163:30321/index.html` 的跨域

**Comment by PHenryy** [comment]
使用 nginx 可以这样处理 OPTIONS 请求，但是现在测试环境一般都是开的 node 服务，这个 OPTIONS 请求该如何处理呢，像 Vue Cli，没有可以配置 express 中间件的地方 @gongshun

**Comment by gongshun** [comment]
> 使用 nginx 可以这样处理 OPTIONS 请求，但是现在测试环境一般都是开的 node 服务，这个 OPTIONS 请求该如何处理呢，像 Vue Cli，没有可以配置 express 中间件的地方 @gongshun

vue-cli 本身也处理不了请求啊，顶多做一个代理，转发请求

**Comment by PHenryy** [comment]
那你建议开发环境该如何处理呢，尽量不修改后端代码

**Comment by gongshun** [comment]
> 那你建议开发环境该如何处理呢，尽量不修改后端代码

子应用的请求的url使用绝对路径，主项目中加载子项目，子项目的请求会被子项目自己的 proxy 代理

**Comment by PHenryy** [comment]
现在就是这样配的，但是后端没处理 OPTIONS , 通过主应用访问子应用的时候，会发 OPTIONS 这个预检请求，导致跨域：
Access to XMLHttpRequest at 'http://localhost:9101/api/xxx from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

8080 是主应用端口，9101是子应用端口， 子应用 axios 已经配了 baseUrl

**Comment by PHenryy** [comment]
在 firefox 中可以看到这个 OPTIONS 返回的状态码是 403，本人对这些不是很懂，求赐教

**Comment by gongshun** [comment]
> 在 firefox 中可以看到这个 OPTIONS 返回的状态码是 403，本人对这些不是很懂，求赐教

子应用的proxy可以拦截 options ，直接返回 200

**Comment by PHenryy** [comment]
> > 在 firefox 中可以看到这个 OPTIONS 返回的状态码是 403，本人对这些不是很懂，求赐教
> 
> 
> 
> 子应用的proxy可以拦截 options ，直接返回 200

我也是这么想的，但是vue cli 的devServer 没有这个配置项...

**Comment by gongshun** [comment]
>我也是这么想的，但是vue cli 的devServer 没有这个配置项...

怎么会不支持呢

![image](https://user-images.githubusercontent.com/29347231/112117811-b6cc7380-8bf6-11eb-994b-9807a4a182dc.png)

https://webpack.js.org/configuration/dev-server/#devserverproxy

![image](https://user-images.githubusercontent.com/29347231/112117782-acaa7500-8bf6-11eb-94aa-da5a93816b47.png)

**Comment by PHenryy** [comment]
首先感谢 @gongshun 的回复

-------------

试了好多种方式终于达到效果了
```js
devServer: {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "*",
      "Access-Control-Allow-Headers": "*"
    },
    proxy: {
      'xxx': {
        target: 'xxx',
        bypass: function (req, res, proxyOptions) {
          if (req.method === 'OPTIONS') {
            res.statusCode = 204
            return 'a'  // <----  这个a我也不知道干嘛的
          }
        },
      }
    },
  },
```

根据文档，bypass 只能返回 null, undefined, false, path, 但是 null 和 undefined 会继续走 proxy, false 会直接返回 404，path 感觉又和我的需求不符, 最后试了直接返回 ```a```, 既返回了 204，又不会接着走 proxy，完美解决了这个问题。

**Comment by lostlz** [comment]
> 首先感谢 @gongshun 的回复
> 
> 试了好多种方式终于达到效果了
> 
> ```js
> devServer: {
>     headers: {
>       "Access-Control-Allow-Origin": "*",
>       "Access-Control-Allow-Methods": "*",
>       "Access-Control-Allow-Headers": "*"
>     },
>     proxy: {
>       'xxx': {
>         target: 'xxx',
>         bypass: function (req, res, proxyOptions) {
>           if (req.method === 'OPTIONS') {
>             res.statusCode = 204
>             return 'a'  // <----  这个a我也不知道干嘛的
>           }
>         },
>       }
>     },
>   },
> ```
> 
> 根据文档，bypass 只能返回 null, undefined, false, path, 但是 null 和 undefined 会继续走 proxy, false 会直接返回 404，path 感觉又和我的需求不符, 最后试了直接返回 `a`, 既返回了 204，又不会接着走 proxy，完美解决了这个问题。

这种方式请求接口时登录态跨域cookie带不上了
