### ISSUE TITLE
webpack 打包子应用，使用代码分片，加载子应用的时候报错ChunkLoadError: Loading chunk 15 failed 如何解决

### ISSUE THREAD

**Issue by suchengyong** [umijs/qiankun#1041]
<script>
      if(window.__POWERED_BY_QIANKUN__){
        __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
      }
</script>
同时设置
`runtimePublicPath: false`，可以解决该问题。
只是代码中有注释，runtimePublicPath设置为false，可能会 dynamic import 方式引入的文件资源路径生效。

问题是不知道在哪里配置：`runtimePublicPath: false` 求知道的大神帮忙看一下，

**Comment by hjklink** [comment]
设置主应用注册子应用的entry为你子应用完整的url, 最后要带/
然后设置
```
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
```
在入口文件，或者qiankun注册的文件中引入执行。
![捕获](https://user-images.githubusercontent.com/47598373/98065840-57143c80-1e90-11eb-9262-24c66798d76c.PNG)
![捕获1](https://user-images.githubusercontent.com/47598373/98065845-5a0f2d00-1e90-11eb-842c-f57a13237349.PNG)

**Comment by Gxxxxxer** [comment]
并不能解决  还是有这个问题

**Comment by kuitos** [comment]
提供可复现仓库后可以自己 reopen

**Comment by Jerry-yx** [comment]
麻烦问一下runtimePublicPath: false这个是在哪个文件里设置呀？
