### ISSUE TITLE
[Bug]qiankun无法在Edge浏览器正常运行

### ISSUE THREAD

**Issue by wwhyes** [umijs/qiankun#1043]
# What happens?
如题：qiankun无法在Edge浏览器正常运行

## 最小可复现仓库
https://github.com/wwhyes/qiankun-demo

## Edge控制台报错
```
Unhandled promise rejection TypeError: Invariant check failed for ownKeys proxy trap
```

## 相关环境信息

- **qiankun 版本**：2.2.2
- **浏览器版本**：Microsoft Edge 44.17763.1.0
- **操作系统**：Window10 专业版 64位操作系统

**Comment by teenth** [comment]
升级ie版本就可以

**Comment by gongshun** [comment]
从代码上看，是这三行代码不兼容：

![image](https://user-images.githubusercontent.com/29347231/98561792-432f6700-22e4-11eb-9bda-b66629d9182c.png)

会让沙箱变成：

![image](https://user-images.githubusercontent.com/29347231/98561891-5cd0ae80-22e4-11eb-821a-f4a1f45d1ef0.png)

从而报错，正常情况沙箱是这样的：

![image](https://user-images.githubusercontent.com/29347231/98562011-7ffb5e00-22e4-11eb-8827-c9d78b215872.png)

怎么兼容，暂时没想到

**Comment by gongshun** [comment]
找到问题原因了，proxySandbox.ts 里面的 uniq 函数判断有问题

![yuanma](https://user-images.githubusercontent.com/29347231/98683804-6f102280-23a0-11eb-9272-5eced8101a78.png)

Chrome上的表现：

![panduan-chrome](https://user-images.githubusercontent.com/29347231/98683877-82bb8900-23a0-11eb-8883-f37d4f8a5e22.png)

edge上的表现：

![panduan](https://user-images.githubusercontent.com/29347231/98683925-8f3fe180-23a0-11eb-9fb3-4a84872f7fba.png)
