### ISSUE TITLE
主应用可以像下传递function吗

### ISSUE THREAD

**Issue by Swings12138** [umijs/qiankun#1044]
Q1：现在的项目模块有很多个子模块，耦合在一个项目中
现在想把他分为各个微应用
但是想把公共方法提出来，类似于java的libary
各个子项目可以引用这种，有什么好的建议吗
Q2:并且 对于加解密和埋点，这种公共方法 主项目可以向下传递吗??
Q3：各个模块都需要安装类似于 vue-router 这种依赖 有什么好的办法解决吗

Thanks

**Comment by howel52** [comment]
这三个问题应该都可以用 package + external 的思路解

**Comment by Swings12138** [comment]
老哥，能给个具体思路吗? 我试一下，之前没用过这个，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 晚上8:09
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"Dude"<1219649500@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun] 主应用可以像下传递function吗 (#1044)





 
这三个问题应该都可以用 package + external 的思路解

**Comment by gongshun** [comment]
Q1：https://juejin.im/post/6872132988780412935#heading-3
Q2：公共方法，可以通过props向下传递，也可以通过挂在主项目的window上，向下传递
Q3：https://juejin.im/post/6856569463950639117#heading-15
