### ISSUE TITLE
开启{ strictStyleIsolation: true }。angular子应用报错。

### ISSUE THREAD

**Issue by yxxuweb** [umijs/qiankun#1047]
## What happens?

手动加载angular子应用时，开启沙盒模式，报错无法找到angular子应用的root

![image](https://user-images.githubusercontent.com/32837652/98089660-0582a680-1ebe-11eb-85ae-00d0be0bb3c2.png)

看了报错信息，应该是angular框架内部在渲染的时候是通过document.querySelecter(‘app-root’)来查找节点。开启了沙盒。获取不到了。
![image](https://user-images.githubusercontent.com/32837652/98090120-96598200-1ebe-11eb-9c18-748603354918.png)

## Context

- **qiankun 2.2.2**:
- **Platform windows**:
- **Browser chrome**:

**Comment by yxxuweb** [comment]
vue，react可以通过手动传入节点，但是angular渲染被封装在框架里。qiankun能给出这样的解决方案。

**Comment by gongshun** [comment]
你看他的命名：`selectorOrNode`，参数可以直接传入`node`节点。参考vue的写法：

![image](https://user-images.githubusercontent.com/29347231/98189971-0284c600-1f51-11eb-806f-55fb902a4652.png)
