### ISSUE TITLE
Uncaught (in promise) TypeError: window.initAMapUI is not a function     at eval

### ISSUE THREAD

**Issue by siu666** [umijs/qiankun#1048]
import VueAMap from 'vue-amap'

Vue.use(VueAMap)

VueAMap.initAMapApiLoader({
  key: '****',
  plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor',
    'AMap.Geolocation', 'AMap.weather', 'AMap.Geocoder'],
  v: '1.4.4'
})

报错信息如下：
    1、、、、index.js:1 Uncaught (in promise) TypeError: window.initAMapUI is not a function
    at eval (index.js:1)
    2、、、TypeError: Cannot read property 'appWrapperGetter' of undefined
    at common.js:303
    at HTMLBodyElement.removeChild (common.js:263)
    at e (VM157 maps:387)
    at window.<computed> (VM157 maps:388)
    at init?s=rsv3&product=JsInit&key=***&t=1604538261199&resolution=375*667&mob=1&vt=1&dpr=2.0000000298023224&scale=1&detect=true&callback=jsonp_255987_&platform=JS&logversion=2.0&appname=http%3A%2F%2Flocalhost%3A9527%2F%23%2Fattendance%2Fbase%2Foffice%2Flist&csid=FCC5844A-BAF7-479A-8EB9-10BFB4F5489D&sdkversion=1.4.15:1

----------------------
单独打开各自子应用不会报错且能正常使用，但是在qiankun从主应用跑到子应用就会报错

**Comment by siu666** [comment]
版本已经是最新

**Comment by 123303841** [comment]
遇到了同样的问题，请问是怎么解决的？
查看代码发现main.async.js被包多一层，导致window下找不到initAMapUI.

**Comment by esymeptoo** [comment]
可以先用legacySandbox临时解决一下

**Comment by acejs** [comment]
同样的问题，现在默认使用的是ProxySandbox，可以在start启动的时候传入 sandbox: { loose: true } ，使用LegacySandbox

**Comment by esymeptoo** [comment]
> 同样的问题，现在默认使用的是ProxySandbox，可以在start启动的时候传入 sandbox: { loose: true } ，使用LegacySandbox

有解决方案吗 proxySandbox会导致 removeChild阶段拿不到 子应用实例 我怀疑是和amap内部的请求顺序有关

**Comment by poppyLuo** [comment]
> > 同样的问题，现在默认使用的是ProxySandbox，可以在start启动的时候传入 sandbox: { loose: true } ，使用LegacySandbox
> 
> 有解决方案吗 proxySandbox会导致 removeChild阶段拿不到 子应用实例 我怀疑是和amap内部的请求顺序有关

遇到相同问题，有解决方案吗？
