### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by xun1224** [umijs/qiankun#1049]
![image](https://user-images.githubusercontent.com/30586336/98194424-5a73fa80-1f5a-11eb-8bbf-2766cabca9da.png)

部署的时候，采用的是子系统静态部署的，不是配置server那种，这样访问的时候会出现304跳转。
这样在ip访问没问题
但是http访问 尤其是https访问会报cors问题

**Comment by gongshun** [comment]
你的子项目在二级目录，`entry` 应该是 `http://cloud-dev.ifytek.com:8999/bar/`，最后面有一个/，不可省略
