### ISSUE TITLE
关于 React Dva 项目 LOADING_SOURCE_CODE 问题

### ISSUE THREAD

**Issue by nealjin** [umijs/qiankun#105]
主框架搭起来以后，想接入一个 Dva 的 React 项目，按文档在 webpack 配置导出生命周期函数，入口文件也按一个 issue 里指导的做了改动，不过还是一直报错，不知道为什么？请指导一下，谢谢~

入口文件
![image](https://user-images.githubusercontent.com/1404759/66700942-1c8dae00-ed29-11e9-9b40-ff5b3f8c2b8b.png)

webpack 配置
![image](https://user-images.githubusercontent.com/1404759/66700961-43e47b00-ed29-11e9-9afe-605181698bb2.png)

主入口
![image](https://user-images.githubusercontent.com/1404759/66701003-7db58180-ed29-11e9-812f-400d36b9da8b.png)

报错信息
![image](https://user-images.githubusercontent.com/1404759/66700913-b739bd00-ed28-11e9-894d-6129c94e456d.png)

**Comment by nealjin** [comment]
之前close的一个相关issue  #18

**Comment by kuitos** [comment]
提供可复现的参考

**Comment by yitjhy** [comment]
麻烦问下是如何将dva作为qiankun主应用的么
