### ISSUE TITLE
子项目为umi，首次加载正常，再次进入白屏，也不会报错

### ISSUE THREAD

**Issue by zhangzhaoxu** [umijs/qiankun#1050]
主项目常规react应用，子项目有个为umi 2.x，线上环境首次加载正常，再次进入白屏，也不会报错。umi子项目开发环境不会出现，有人碰到吗

### 相关环境信息
- **@umijs/plugin-qiankun**: 1.5.5
- **qiankun**: :2.2.3
- **浏览器版本**：chrome 87
- **操作系统**: macos

**Comment by WuBin88996** [comment]
子应用脚本没有被初始化 我也遇到了这个问题 请问解决了吗

**Comment by doubone** [comment]
有人解决了这个问题吗
