### ISSUE TITLE
Webpack5 chunkLoadingGlobal 导致加载失败

### ISSUE THREAD

**Issue by zhujun24** [umijs/qiankun#1051]
## What happens?

由于 Webpack5 移除了output.jsonpFunction 配置，需要使用 chunkLoadingGlobal 代替，但是导致子应用加载报错。
```
loader.js:211 Uncaught Error: application 'default-app' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in default-app entry
```

**Comment by Measy** [comment]
@zhujun24 你好 请问解决了吗？

**Comment by zhujun24** [comment]
@Measy 解决了，不是这儿的问题

**Comment by cloydlau** [comment]
@zhujun24 请问下是如何解决的 遇到相同问题

**Comment by cyzaoj** [comment]
+ 1

**Comment by cyzaoj** [comment]
+1

**Comment by lovefishs** [comment]
@zhujun24 
您好，我现在也遇到了这个问题。
webpack 从 v4 升级到 v5 之后，webpack 配置 `output.jsonpFunction` 修改为 `output. chunkLoadingGlobal`，其他代码没有变动，然后出现微应用无法载入的情况，报错也和你的一样。
请问一下，您是如何解决的呢？
