### ISSUE TITLE
apache 部署主入口、微应用， 设置默认微应用，页面空白

### ISSUE THREAD

**Issue by luyaohua2011** [umijs/qiankun#1058]
我的配置文件

![image](https://user-images.githubusercontent.com/4536586/98382438-2bf33e00-2086-11eb-9a48-029165fce56b.png)

设置默认微应用
![image](https://user-images.githubusercontent.com/4536586/98382403-1f6ee580-2086-11eb-8aec-ae340c8a130d.png)

效果空白，也没有报错
![image](https://user-images.githubusercontent.com/4536586/98382495-3c0b1d80-2086-11eb-912b-e197b5cbb1ec.png)

**Comment by gongshun** [comment]
看一下页面 dom，白屏可能是主项目没有匹配到任何路由页面，而你的子项目注册写在某个路由页面

**Comment by hechanghong** [comment]
> 我的配置文件
> 
> ![image](https://user-images.githubusercontent.com/4536586/98382438-2bf33e00-2086-11eb-9a48-029165fce56b.png)
> 
> 设置默认微应用
> ![image](https://user-images.githubusercontent.com/4536586/98382403-1f6ee580-2086-11eb-8aec-ae340c8a130d.png)
> 
> 效果空白，也没有报错
> ![image](https://user-images.githubusercontent.com/4536586/98382495-3c0b1d80-2086-11eb-912b-e197b5cbb1ec.png)

请问Apache不是的问题解决了吗？我也遇到 类似的问题 ，Nginx不是没问题，Apache部署就报404，请分享你的经验。
