### ISSUE TITLE
nuxt子应用，部署nginx，报错

### ISSUE THREAD

**Issue by CIGE-Vince** [umijs/qiankun#1062]
ChunkLoadError: Loading chunk 5 failed.
7a87ec1.js:formatted:85514 [import-html-entry]: error occurs while executing normal script
7a87ec1.js:formatted:85541 Uncaught SyntaxError: Unexpected token '<'

主应用是nuxt

子应用也是nuxt

如果我子应用是vue却没有问题

有大佬知道是为什么吗

--package.json
`{
  "name": "nuxt-subapp",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "cross-env PORT=7102 nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/router": "^1.5.0",
    "nuxt-edge": "latest"
  },
  "devDependencies": {
    "@femessage/nuxt-micro-frontend": "^1.6.0",
    "cross-env": "^7.0.2"
  }
}
`

--nuxt.config.js
`
export default {
/*
** Nuxt rendering mode
** See https://nuxtjs.org/api/configuration-mode
/
mode: 'spa',
/
** Nuxt target
** See https://nuxtjs.org/api/configuration-target
/
target: 'server',
/
** Headers of the page
** See https://nuxtjs.org/api/configuration-head
/
head: {
title: process.env.npm_package_name || '',
meta: [
{ charset: 'utf-8' },
{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
{ hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
],
link: [
{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
]
},
/
** Global CSS
/
css: [
],
/
** Plugins to load before mounting the App
** https://nuxtjs.org/guide/plugins
/
plugins: [
],
/
** Auto import components
** See https://nuxtjs.org/api/configuration-components
/
components: true,
/
** Nuxt.js dev-modules
/
buildModules: [
[
'@nuxtjs/router',
//
{ keepDefaultRouter: true, path: './router', fileName: 'index.js' },
],
],
/
** Nuxt.js modules
*/
modules: [
'@femessage/nuxt-micro-frontend',
],

MFE: {
force: true
},
/*
** Build configuration
** See https://nuxtjs.org/api/configuration-build/
*/
build: {
}
}
`

**Comment by gongshun** [comment]
> Uncaught SyntaxError: Unexpected token '<'

一般这种报错，是因为请求的是 js ，返回了 html 。你可以看下浏览器控制台的 network 

那么为什么请求的是 js，返回的却是是 html 呢，是因为你的 nginx 配置了 404 请求返回 index.html。所以真正原因就是这个 js 的路径不对，404了，那么为什么按需加载的 js 路径不对呢，可能是因为你没有动态设置 publicPath 。参考 https://github.com/umijs/qiankun/blob/e537996b481cf88caffe4b6116c3a865f3c3c9a9/examples/vue/src/main.js#L1

**Comment by CIGE-Vince** [comment]
> > Uncaught SyntaxError: Unexpected token '<'
> 一般这种报错，是因为请求的是 js ，返回了 html 。你可以看下浏览器控制台的 network
> 那么为什么请求的是 js，返回的却是是 html 呢，是因为你的 nginx 配置了 404 请求返回 index.html。所以真正原因就是这个 js 的路径不对，404了，那么为什么按需加载的 js 路径不对呢，可能是因为你没有动态设置 publicPath 。参考

——————

**Comment by CIGE-Vince** [comment]
> > Uncaught SyntaxError: Unexpected token '<'
> 
> 一般这种报错，是因为请求的是 js ，返回了 html 。你可以看下浏览器控制台的 network
> 
> 那么为什么请求的是 js，返回的却是是 html 呢，是因为你的 nginx 配置了 404 请求返回 index.html。所以真正原因就是这个 js 的路径不对，404了，那么为什么按需加载的 js 路径不对呢，可能是因为你没有动态设置 publicPath 。参考
> 
> https://github.com/umijs/qiankun/blob/e537996b481cf88caffe4b6116c3a865f3c3c9a9/examples/vue/src/main.js#L1

————
对，确实是这样的，本应该请求js却返回了html。我又深入看了下，原因是这样的：
我的主应用是nuxt框架，端口7000，子应用也是nuxt框架，端口号是7002。“85f5ac0.js”这个js是7002的页面打包js，请求的话应该是通过7002端口请求，然而现状是通过7000去请求了。
我通过调试工具，在过程中改变了这个请求端口号7000=>7002，就成功了，不会再有报错了。证明应该是父子应用之间没有隔离好，但是我不知道该怎么做才能让它正确请求，请大佬帮忙看看

**Comment by gongshun** [comment]
并不是没隔离好，是 publicPath 没有配置

**Comment by CIGE-Vince** [comment]
> > > Uncaught SyntaxError: Unexpected token '<'
> > 
> > 
> > 一般这种报错，是因为请求的是 js ，返回了 html 。你可以看下浏览器控制台的 network
> > 那么为什么请求的是 js，返回的却是是 html 呢，是因为你的 nginx 配置了 404 请求返回 index.html。所以真正原因就是这个 js 的路径不对，404了，那么为什么按需加载的 js 路径不对呢，可能是因为你没有动态设置 publicPath 。参考
> > https://github.com/umijs/qiankun/blob/e537996b481cf88caffe4b6116c3a865f3c3c9a9/examples/vue/src/main.js#L1
> 
> ————
> 对，确实是这样的，本应该请求js却返回了html。我又深入看了下，原因是这样的：
> 我的主应用是nuxt框架，端口7000，子应用也是nuxt框架，端口号是7002。“85f5ac0.js”这个js是7002的页面打包js，请求的话应该是通过7002端口请求，然而现状是通过7000去请求了。
> 我通过调试工具，在过程中改变了这个请求端口号7000=>7002，就成功了，不会再有报错了。证明应该是父子应用之间没有隔离好，但是我不知道该怎么做才能让它正确请求，请大佬帮忙看看

请求js却返回html的原因是，nginx中当找不到这个文件时会重定向回index.html。因为“85f5ac0.js”这个js根本不属于主应用的7000端口下文件，属于子应用7002，因此找不到。

**Comment by CIGE-Vince** [comment]
> publicPath

nuxt配置public-path吗？我尝试一下

**Comment by gongshun** [comment]
子项目可以写死 webpack 的 publicPath，也可以参考这个文件动态修改：https://github.com/umijs/qiankun/blob/e537996b481cf88caffe4b6116c3a865f3c3c9a9/examples/vue/src/public-path.js

**Comment by CIGE-Vince** [comment]
我尝试了三种种方式引用publicPath均失败。报错依旧，没有改变。能帮我看看吗？是不是写的方式有问题，我没有使用webpack。

方式一：（增加public-path.js文件，在nuxt.config.js通过全局js方式引用）
![image](https://user-images.githubusercontent.com/25953903/98643009-56384a80-2369-11eb-9f24-d0073533d134.png)

---public-path.js
![image](https://user-images.githubusercontent.com/25953903/98642987-49b3f200-2369-11eb-9d97-4fbbabab3a24.png)



方式二：（增加public-path.js文件，在nuxt.config.js通过插件方式引用）
  plugins: [
    { src: './public-path.js', ssr: false }
  ],

---public-path.js
![image](https://user-images.githubusercontent.com/25953903/98642956-3f91f380-2369-11eb-9e5e-0ec2ef28f523.png)


方式三：在暴露生命周期的地方直接写死publicPath
![image](https://user-images.githubusercontent.com/25953903/98642905-2ab56000-2369-11eb-948f-e75ed896546f.png)

**Comment by CIGE-Vince** [comment]
> 子项目可以写死 webpack 的 publicPath，也可以参考这个文件动态修改：https://github.com/umijs/qiankun/blob/e537996b481cf88caffe4b6116c3a865f3c3c9a9/examples/vue/src/public-path.js

请教一下，如何直接写死publicPath呢？
publicPath: window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__
————
这样吗？

**Comment by gongshun** [comment]
> 请教一下，如何直接写死publicPath呢？
> publicPath: window.**INJECTED_PUBLIC_PATH_BY_QIANKUN**
> ————
> 这样吗？

https://www.nuxtjs.cn/api/configuration-build#publicpath

publicpath 写死必须写ip地址，不能用变量。publicpath: 'http://localhost:8080'

**Comment by CIGE-Vince** [comment]
> > 请教一下，如何直接写死publicPath呢？
> > publicPath: window.**INJECTED_PUBLIC_PATH_BY_QIANKUN**
> > ————
> > 这样吗？
> 
> https://www.nuxtjs.cn/api/configuration-build#publicpath
> 
> publicpath 写死必须写ip地址，不能用变量。publicpath: 'http://localhost:8080'

非常感谢！解决了。还有一个问题，能否帮我解答一下，qiankun微前端部署方式，区别应用之间，只能用端口区分吗？能否用二级路由去区分？

**Comment by zerobin** [comment]
我这边也有这种场景：vue2 动态组件加载，因为灰度方式采用请求头中带有自定义标识，动态组件webpack 文件切割后台，请求这个chunk文件，请求时没有带上灰度标识，所有找不到文件，返回到了nginx设置的index.html文件。 组件方式采用普通加载就没这个问题，目前也只能这么改了

**Comment by hpy-lhj** [comment]
能看下主项目与Nuxt项目，部署时包时怎么放的吗
