### ISSUE TITLE
怎么暴露antd pro项目的生命周期函数给主应用

### ISSUE THREAD

**Issue by chenqk1234** [umijs/qiankun#1063]
## Background

当我使用qiankun作为微前端的主框架的时候，我的子应用是基于umi的antd pro架构，在主应用中配置好子应用(微应用)的路由配置，当我把子应用接入到主应用时，官方给出的文档是必须暴露子应用的生命周期函数给主应用，一般需要在子应用的webpack（entry js）中对外暴露。但是我发现在antd pro的架构下，并没有主入口文件也没有对应的webpack配置文件，所以无法对外暴露生命周期函数，总是会出现下面这种错误：
![image](https://user-images.githubusercontent.com/74222712/98621370-0db96680-2342-11eb-85ec-3c86725ca1e4.png)
查看了一下qiankun官网给出的解决办法，发现在我项目中并没有主入口文件以及webpack的配置。

在网上搜到的资料是umi会自动生成入口文件，而不是通过配置。qiankun官网只是提到了对存在主入口文件的子应用如何暴露生命生命周期函数，并没有提到不存在主入口文件的子应用如何对外暴露生命周期函数。

所以在这里想问一下同样是底层基于umi的(antd pro和qiankun)，是不是有对应的处理，还请官方给出解决办方案？

**Comment by gongshun** [comment]
https://umijs.org/zh-CN/plugins/plugin-qiankun#%E7%AC%AC%E4%B8%80%E6%AD%A5%EF%BC%9A%E6%8F%92%E4%BB%B6%E6%B3%A8%E5%86%8C%EF%BC%88configjs%EF%BC%89
