### ISSUE TITLE
配置qiankun子应用出现一个loading占据页面，请求回来的内容显示在loading动画下，怎么去除这个loading动画？

### ISSUE THREAD

**Issue by hl226** [umijs/qiankun#1066]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:最新版
- **Platform Version**:最新版
- **Browser Version**:最新版

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles

![image](https://user-images.githubusercontent.com/29347231/98758234-3eb09e80-2409-11eb-8eb4-59fb1e7df80b.png)

**Comment by bytrix** [comment]
> https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles
> 
> ![image](https://user-images.githubusercontent.com/29347231/98758234-3eb09e80-2409-11eb-8eb4-59fb1e7df80b.png)

在umi应用下这个loading动画无法去除，autoSetLoading=false也无效

**Comment by gongshun** [comment]
那就应该是你自己写的 loading，而不是 umi-qiankun 的

![image](https://user-images.githubusercontent.com/29347231/99939929-2300ad00-2da6-11eb-882e-586387edef7d.png)

**Comment by windyzoe** [comment]
应该是容器id配置的问题

**Comment by jqxismygit** [comment]
应该是umi开启了dynamicImport导致的，可以装一下这个包能解决这个问题umi-plugin-route-loading

**Comment by Himangguo** [comment]
我也遇到这个问题了，请问这个问题最后解决吗
