### ISSUE TITLE
请问是否有父应用包含子应用，子应用包含孙应用的案例？或者是否支持父子孙这样的使用？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/qiankun#1067]
请问是否有父应用包含子应用，子应用包含孙应用的案例？qiankun目前是否支持父子孙这样的使用？？如果支持需要做怎样的改造可以实现父-子-孙情况？

**Comment by zhilianbi520** [comment]
https://github.com/umijs/qiankun/issues/960 找到一个关联的，有对应的demo可提供借鉴的嘛？

**Comment by gongshun** [comment]
https://juejin.im/post/6856569463950639117#heading-29
