### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by JonesAtom** [umijs/qiankun#1068]
## What happens?
配置的的__webpack_public_path__ 没生效，主应用打开子应用时报错
`[import-html-entry]: error occurs while executing entry script http://xxxx.com/js/app.bf781e67.js`
请大佬指教

## 相关环境信息
public-path.js
```
if (window.__POWERED_BY_QIANKUN__) {
  __webpack_public_path__ = window.__POWERED_BY_QIANKUN__
}

vue.config.js
`publicPath: process.env.NODE_ENV === 'production' ? '/marketingCenter/' : '/',`

- **qiankun 版本**: "^2.3.0"
- **浏览器版本**：chrome
- **操作系统**：mac

**Comment by gongshun** [comment]
这是 js 执行报错，不是加载报错，publicPath只与加载路径有关

**Comment by JonesAtom** [comment]
哦哦，怎样做能优化掉这个报错呢？
