### ISSUE TITLE
[Bug]setDefaultMountApp没效果

### ISSUE THREAD

**Issue by myeveryheart** [umijs/qiankun#107]
## What happens?

example里面，setDefaultMountApp没效果

## 复现步骤，错误日志以及相关配置

不修改example里面任何代码，只把
setDefaultMountApp('/react');
改成
setDefaultMountApp('/vue');

但是首先启动的子应用依旧是react

## 相关环境信息

- **浏览器版本**：Google Chrome版本 77.0.3865.90（正式版本） （64 位）
- **操作系统**：MacOS
- **Node 版本**：v10.15.2

**Comment by kuitos** [comment]
本地跑了一下正常的。

setDefaultMountApp 启动时如果不匹配到任何应用，默认会跳转到哪个应用。
比如 `setDefaultMountApp('/vue')` 时访问 `http://localhost:7099` 会默认跳转到 `http://localhost:7099/vue` 从而启动 vue app

**Comment by myeveryheart** [comment]
找到原因了，必须重新启动的时候，改动才会生效。

**Comment by yangangzhang** [comment]
@kuitos 如果当前页面是某一项目的子路由，那么刷新的时候回渲染setDefaultMountApp()设置的默认路由，而不是当前的子路由
![image](https://user-images.githubusercontent.com/20433039/67262869-dd095380-f4d8-11e9-83ba-c591d31119b4.png)

**Comment by kuitos** [comment]
提供可复现的仓库
