### ISSUE TITLE
loadMicroApp 手动加载子项目切换路由页面不会跳转

### ISSUE THREAD

**Issue by MiracleWan** [umijs/qiankun#1070]
使用 loadMicroApp 手动加载子项目后切换路由子项目不会根据路由进行页面跳转

发现应该single-spa 版本有关，锁死single-spa@5.8.1 时页面正常，single-spa@5.8.2有问题

麻烦看下是否跟这个commit有关https://github.com/single-spa/single-spa/pull/660

## 相关环境信息

- **qiankun 版本**
      2.3.0
- **浏览器版本**：
      Chrome 86.0.4240.183
- **操作系统**：
     MAC

**Comment by kuitos** [comment]
released v2.3.1

**Comment by Raylayll** [comment]
同遇到这个问题，更新到2.3.1仍然不ok

**Comment by bluehymn** [comment]
跟这个issue有关 https://github.com/single-spa/single-spa/issues/761
