### ISSUE TITLE
关于nginx部署方式，能否通过二级路由的方式部署，不占用这么多端口

### ISSUE THREAD

**Issue by CIGE-Vince** [umijs/qiankun#1072]
关于nginx部署方式，能否通过二级路由的方式部署，不占用这么多端口。

当前部署方式是每个应用占用一个端口，由主应用端口分发至各个端口，这样端口占用量有点多，每增加一个应用就要增加一个端口配置，不是很方便。请问能否通过同一个端口，二级路由的方式标识子应用？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/400#issuecomment-676947927

**Comment by hql7** [comment]
@CIGE-Vince https://juejin.cn/post/6844904143413313549#heading-22 简单快速调整为双端口方案
