### ISSUE TITLE
[Bug]页面刷新会出现内存泄露

### ISSUE THREAD

**Issue by Luin-Li** [umijs/qiankun#1073]
使用[官方实例](https://github.com/gongshun/qiankun-vue-demo)就可以复现。

复现步骤：加载微应用--》卸载子应用 --》 切换回主应用 --》再次加载同一微应用（此时复用之前加载的微应用js,这不是内存泄露，没有问题）（图一）--》但是，点击浏览器**刷新**按钮，再次加载微应用，此时会重新加载一遍微应用的js，但是部分遗留的微应用js并没有被清理干净，此时出现 **内存泄露**。（见图二和图三）

图一
![微信截图_20201112135744](https://user-images.githubusercontent.com/23295360/98902494-cf15de80-24f0-11eb-8d06-6423974bfe41.png)

图二
![微信截图_20201112140010](https://user-images.githubusercontent.com/23295360/98902497-d0470b80-24f0-11eb-899d-50f987ae6926.png)

图三
![微信截图_20201112140132](https://user-images.githubusercontent.com/23295360/98902506-d2a96580-24f0-11eb-935a-f0c73fb1baa6.png)

----
以下为题外话：
在实际项目实践中，其实有些微应用还是比较重的，希望qiankun能提供 destroy的接口。[#715 ](https://github.com/umijs/qiankun/pull/715#discussion_r449431189)

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/832

**Comment by Luin-Li** [comment]
> duplicated with #832
我有看到这个，但是我本地自己用最简单的`eval`函数测试了一下，没有这个问题呀

**Comment by Luin-Li** [comment]
> duplicated with #832

我有看到这个，但是我本地自己用最简单的eval函数测试了一下，没有这个问题呀

**Comment by Luin-Li** [comment]
@kuitos 解决了。主项目入口js引入`zone.js`就可以了，在我自己的项目和上面这个[官方示例](https://github.com/gongshun/qiankun-vue-demo)都试过没问题了。

发现源代码的example跑起来没有这个问题，经过对比，是因为引入了`zone.js`。
（具体原因还未分析，虽然example注释那里写了zone.js是为`angular`微应用引入的，找了半天，终于发现问题）

**Comment by huangche007** [comment]
@Luin-Li 引入zone.js，适用于vuejs的项目吗？

**Comment by Luin-Li** [comment]
> @Luin-Li 引入zone.js，适用于vuejs的项目吗？

可以，我的项目就是父子应用都是vue，测试过，可以解决的

**Comment by huangche007** [comment]
@Luin-Li Tanks man，ie兼容性怎样

**Comment by liuwc121709** [comment]
@Luin-Li 我添加了，也不行啊。 这个有办法解决吗？ 页面引入16个子应用，刷新个四五次，内存就过200了，这个有解决方案吗？@kuitos

**Comment by guguji5** [comment]
插个眼

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/100961836-1e828400-355e-11eb-8d7d-122e3f5cfc25.png)

开发者工具打开的情况下才会有这个问题

**Comment by jiangyh1024** [comment]
@Luin-Li  react项目 也是引入zone.js??

**Comment by jiangyh1024** [comment]
@liuwc121709  你解决了这个问题了吗？？？ 
@guguji5 @huangche007

**Comment by innocces** [comment]
> @kuitos 解决了。主项目入口js引入`zone.js`就可以了，在我自己的项目和上面这个[官方示例](https://github.com/gongshun/qiankun-vue-demo)都试过没问题了。
> 
> 发现源代码的example跑起来没有这个问题，经过对比，是因为引入了`zone.js`。 （具体原因还未分析，虽然example注释那里写了zone.js是为`angular`微应用引入的，找了半天，终于发现问题）

这个只适用于手动加载的情况。
