### ISSUE TITLE
angular子应用无法访问全局引入的第三方js方法

### ISSUE THREAD

**Issue by wudith** [umijs/qiankun#1083]
子应用开启沙箱，通过proxy代理封装后，通过declare无法读取。子应用独立运行时能正常调用。
function(window, self) {
    子应用js代码
}(window,proxy, window.proxy)

复现方式——

1、比如在子应用的index.html的head引入es5的公共方法文件 
 <script src="/common/js/util.min.js" ></script>
function framework_func1（）{ }

2、在angular子应用的ts文件引入全局方法：
declare var framework_func1: any;

报错：ERROR ReferenceError: ict_framework_func1 is not defined

请教应该如何访问？

**Comment by gongshun** [comment]
子应用的全局函数和变量必须显式的挂载到 `window` 上，直接 `function` 声明不是全局的函数了，例如 `window.fun = () => {}`，使用时也得 `window.fun()`。沙箱设计如此

**Comment by wudith** [comment]
> 子应用的全局函数和变量必须显式的挂载到 `window` 上，直接 `function` 声明不是全局的函数了，例如 `window.fun = () => {}`，使用时也得 `window.fun()`。沙箱设计如此

谢谢大佬
