### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by winneyLin** [umijs/qiankun#1084]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

开启沙箱模式，子应用中element-ui 的select报 ‘Failed 通execute getComputedStyle on Window ’: paramter 1 is not of type Element
## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/634 重复
