### ISSUE TITLE
registerMicroApps方式在地址拦随意输入不存在的应用，控制台会报Failed to fetch（无法获取）

### ISSUE THREAD

**Issue by king0817** [umijs/qiankun#1085]
## What happens?
registerMicroApps方式在地址拦随意输入不存在的应用，控制台会报Failed to fetch（无法获取）

## Mini Showcase Repository(REQUIRED)
官方例子
> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
提供个复现 demo ? 你的子项目的 entry 是怎么写的？

**Comment by king0817** [comment]
> 提供个复现演示？你的子项目的条目是怎么写的？
没有进入子项目，和子项目没关系，在你的乾坤项目跳转，比如history.pushState(null,null,"/abc")，找不到这个应用就会报这个错，这个abc是随便写的，不是应用名字

**Comment by king0817** [comment]
![image](https://user-images.githubusercontent.com/30648041/99939180-71ad4780-2da4-11eb-88bf-c309c05b7f8f.png)

**Comment by gongshun** [comment]
这个报错是预请求，而你没有启动其他的子项目导致的

**Comment by blueju** [comment]
> 这个报错是预请求，而你没有启动其他的子项目导致的

那请问我应该如何进行拦截这个错误，并给出提示？
貌似可以用自定义Fetch，但我使用的umi-qiankun插件，该部分文档中并未详细介绍

**Comment by cx91** [comment]
> > 这个报错是预请求，而你没有启动其他的子项目导致的
> 
> 那请问我应该如何进行拦截错误，并给出提示 可以用这个自定义Fetch，但我使用的umi-qiankun插件，该部分文档中的详细介绍

你好，你这个问题解决没呢？我现在也遇到这个问题了，谢谢

**Comment by cx91** [comment]
@king0817 你好，你解决这个问题没呢？我们项目现在也需要解决这个问题
