### ISSUE TITLE
yarn examples:install报错

### ISSUE THREAD

**Issue by sylyie** [umijs/qiankun#1087]
执行yarn examples:install报错

**Comment by king0817** [comment]
我改了点东西，成功了，examples\main\index.js把../../es改成qiankun

**Comment by chaserstrong** [comment]
@king0817 我改了也还是不行。 而且../../es 这个路径在哪里？完全没找到

**Comment by gongshun** [comment]
> @king0817 我改了也还是不行。 而且../../es 这个路径在哪里？完全没找到

![image](https://user-images.githubusercontent.com/29347231/100173176-f31beb80-2f04-11eb-91cc-6177fc0a9d5f.png)

../../es 这个路径是 `build` 之后生成的文件，昨晚 `build` 确实报错，https://github.com/umijs/qiankun/pull/1096 已经修复了，重新拉取一下代码，应该能正常执行 `yarn examples:install`

**Comment by yidong002** [comment]
![image](https://user-images.githubusercontent.com/46306435/110052826-305d0880-7d93-11eb-8016-a04412d61d78.png)
我的也修改了build 但是执行 yarn examples:install 的时候还是 会出错
