### ISSUE TITLE
create-react-app项目当前路由刷新会加载失败

### ISSUE THREAD

**Issue by yuanman0109** [umijs/qiankun#109]
## What happens?

项目在当前路由刷新会报错

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

**Comment by yuanman0109** [comment]
git地址： https://github.com/yuanman0109/test-qiankun

**Comment by yuanman0109** [comment]
![image](https://user-images.githubusercontent.com/22994293/66997996-08212b00-f106-11e9-9228-85b75acead50.png)

**Comment by yuanman0109** [comment]
子模块是直接启动example中的三个项目，框架项目是create-react-app创建了，然后安装了qiankun，改了下入口文件，其他什么都没有

**Comment by kuitos** [comment]
应该跟这个问题有关 https://github.com/kuitos/import-html-entry/issues/6

子应用用一个标准的 webpack 应用把，parcel 的看上去对主应用有要求

**Comment by kuitos** [comment]
参考最新 demo
