### ISSUE TITLE
yarn examples:install一直报错：TypeScript: Compilation failed

### ISSUE THREAD

**Issue by wood3n** [umijs/qiankun#1090]
## What happens?

clone项目到本地以后，执行`yarn examples:install`报错，我看了这个issue —— https://github.com/umijs/qiankun/issues/157#issue-526425441
底下也没给出解决方法

![image](https://user-images.githubusercontent.com/31716713/100040176-b76c1d80-2e41-11eb-8363-5d0aaf8d0034.png)

**Comment by fuyunzhishang** [comment]
同样的问题，跑步起来

**Comment by AFine970** [comment]
+1
跑不起来，入门即放弃

**Comment by hellobili** [comment]
先build下 然后yarn换npm可以

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1093#issuecomment-732981000

**Comment by liutian** [comment]
跑不起来，入门即放弃

**Comment by 100001** [comment]
我也遇到同样的问题，原因是yarn的版本太低v0.19.1，升级到1.22.10后再重装一次就ok了

**Comment by Marcuslyj** [comment]
> 我也遇到同样的问题，原因是yarn的版本太低v0.19.1，升级到1.22.10后再重装一次就ok了

1.22.17重新安装都不行呢

**Comment by secmax** [comment]
跑不起来

**Comment by CHENJIAMIAN** [comment]
`npm i` 安装依赖的方式会出错

删除`node_modules`后

用`yarn`安装依赖, 不出错
