### ISSUE TITLE
vue项目，主应用会报路由警告

### ISSUE THREAD

**Issue by weizaily** [umijs/qiankun#1091]
1.目前创建了2个vue项目，一个作为主应用，一个作为子应用。目前都配置完毕了，是可以正常跳转的。
2.但是主应用跳转到子应用的路由的时候，会报路由警告，具体是找不到定义的该路由，但是又可以正常跳转。
这该如何解决？

**Comment by CIGE-Vince** [comment]
同一个问题，会中间过度一个page 404 的提示。 @gongshun @weizaily 有解决方案吗

**Comment by django-d** [comment]
me to, 我也有这样的 疑问

**Comment by zychome** [comment]
遇到了同样的问题，求解
