### ISSUE TITLE
yarn examples:install 安装报错

### ISSUE THREAD

**Issue by chaserstrong** [umijs/qiankun#1093]
## What happens?
通过github中下载zip包下载项目，在本地目录下执行了yarn install，在执行yarn examples:install 时，报错，错误信息如图：
![WeChat08f244548474c5de76b9d5ae0cb980ca](https://user-images.githubusercontent.com/18061322/100064152-1b580b80-2e6d-11eb-83b5-582f0cc65289.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

看了下issues里，感觉应该很多人都会遇到，截图中的chencheng这个路径，是被写死了？

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by chaserstrong** [comment]
![WeChat08f244548474c5de76b9d5ae0cb980ca](https://user-images.githubusercontent.com/18061322/100064505-93263600-2e6d-11eb-84ae-6f80e8f41d73.png)

**Comment by chaserstrong** [comment]
@gongshun

**Comment by kuitos** [comment]
see https://github.com/ant-design/babel-plugin-import/issues/554#issuecomment-732729230

**Comment by chaserstrong** [comment]
@kuitos 感谢，根据链接改了之后，后续还有错：Error: TypeScript: Compilation failed。又根据这个链接解决了
https://github.com/umijs/qiankun/issues/157

**Comment by chaserstrong** [comment]
@kuitos 还是不行，还是报这个错。 我看package.json里已经改了"@types/vfile-message": "1.x"； 不知道是哪个包里还有引用；
![image](https://user-images.githubusercontent.com/18061322/100094289-be238080-2e93-11eb-8978-fd771959420c.png)

**Comment by gongshun** [comment]
是 build 报错

![image](https://user-images.githubusercontent.com/29347231/100096633-3f304700-2e97-11eb-8426-326e924e767a.png)

**Comment by gongshun** [comment]
`src/utils.ts`文件第85行

参数类型改成 `any` ： `resolve!: (value?: any) => void;` 然后再 `yarn examples:install` 就可以了

![image](https://user-images.githubusercontent.com/29347231/100101864-c54f8c00-2e9d-11eb-9d74-00fc33d30e04.png)

**Comment by chaserstrong** [comment]
> `src/utils.ts`文件第85行
> 
> 参数类型改成 `any` ： `resolve!: (value?: any) => void;` 然后再 `yarn examples:install` 就可以了
> 
> ![image](https://user-images.githubusercontent.com/29347231/100101864-c54f8c00-2e9d-11eb-9d74-00fc33d30e04.png)

起来了，感谢

**Comment by Seventysevendays** [comment]
this problem still exists

**Comment by zhangxinxing59** [comment]
还是有这个问题，改类型不管用

**Comment by zhangxinxing59** [comment]
![image](https://user-images.githubusercontent.com/12707010/100991274-c794a300-358d-11eb-8cc3-6c6c4e41806b.png)

**Comment by Marcuslyj** [comment]
崩溃，问题还在

**Comment by summerscar** [comment]
+1

**Comment by LittlehorseXie** [comment]
> ![image](https://user-images.githubusercontent.com/12707010/100991274-c794a300-358d-11eb-8cc3-6c6c4e41806b.png)

![image](https://user-images.githubusercontent.com/39767742/152913182-a2c9d3db-2b45-418d-a61d-de9ee2afa4f8.png)
试试把mightFinish的抛错注释掉 我这边用这种方式解决了

**Comment by thinkive** [comment]
npm update 之后重新npm i，重新npm run examples:install，仍然报错chencheng路径都上来了
