### ISSUE TITLE
子应用window监听 在子应用相互切换时 qiankun 移除了子应用监听 再切换回来的时候却没有再添加上

### ISSUE THREAD

**Issue by 1091785626** [umijs/qiankun#1094]
![image](https://user-images.githubusercontent.com/29907950/100075230-a8ee2800-2e7a-11eb-9c50-38b6cfe2457d.png)

**Comment by dlchun** [comment]
我最近使用qiankun的时候也出现了监听事件失效的情况, 你是怎么解决的,
