### ISSUE TITLE
使用webpack打包自己项目后，通过qiankun来注册时遇到的一些问题

### ISSUE THREAD

**Issue by wbbw007** [umijs/qiankun#11]
在我使用webpack打包我的项目后，加入到qiankun并通过端口进行注册之后，发现非入口的js文件会报错，不知道是什么原因导致的。
![image](https://user-images.githubusercontent.com/37614735/60171434-34562a80-983d-11e9-9a9f-e0fa7fa76b78.png)

我正常访问该项目是可以正常渲染的。

**Comment by kuitos** [comment]
使用了 dynamic import 么？

**Comment by wbbw007** [comment]
> 使用了 dynamic import 么？

没有使用 dynamic import

**Comment by kuitos** [comment]
来个可重现的 demo 吧 https://codesandbox.io/

**Comment by wbbw007** [comment]
https://codesandbox.io/s/ewzm0 
我发现应该是我在使用react-router 3.2.0版本时 进行路由跳转时，导致报错，但是我不知道是什么原因导致 @kuitos

**Comment by kuitos** [comment]
你用了 dynamic import，目前需要配置完整的 publicPath 地址，如：
```js
{
  publicPath: 'http://localhost:7001/'
}
```

后续 qiankun 会做相应支持

**Comment by wbbw007** [comment]
thx，这解决了报错问题

**Comment by yangangzhang** [comment]
> ```js
> publicPath: 'http://localhost:7001/'
> ```

您好，这个问题解决了吗？还是需要配置publicPath: 'http://localhost:7001/'，子项目图片，路由懒加载的js路径正确
