### ISSUE TITLE
开启沙箱模式会导致子应用的全局事件监听丢失，比如子项目需要监听url地址变更pushstate事件等。

### ISSUE THREAD

**Issue by Hades-li** [umijs/qiankun#110]
## 开启沙箱模式会导致子应用的全局事件监听丢失，比如子项目需要监听url地址变更pushstate事件等。

1.首先沙箱模式貌似在development模式下默认是关闭的，因为这个问题发生在我将代码打包上传到生产时发生，在开发环境下没有。这个需要确认一下。虽然我从源码当中并没有找到这样的判断。

2.子项目在首次挂载进来时，全局监听事件是可以被监听的。但二次唤醒时，事件监听就丢失了。

3.关闭沙箱模式，此问题则不存在。

想知道，如何解决这个问题。

## 相关环境信息

- **浏览器版本**：chorme 7x
- **操作系统**：win10
- **Node 版本**：10.15.3

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by Hades-li** [comment]
> 提供可复现的仓库

https://github.com/Hades-li/qiankun-vue

这是个基于vue-cli3.x构建的简易项目。在开发环境下，开启沙盒和不开启沙盒就可以很明显的出现我所描述的问题。顶部的导航栏app1,app2为主框架切换子项目路由。

**Comment by kuitos** [comment]
复现步骤，子应用在哪里监听事件的都提供一下

**Comment by Hades-li** [comment]
> 复现步骤，子应用在哪里监听事件的都提供一下
我又更新了一下代码。麻烦拉一下。步骤，首先将项目打包发服务器nginx环境，因为在生产环境下的现象必定出现。然后打开网址，输入http://localhost:9100/#/vue1，进入app1子项目的home页。然后点击app1->about，再点击app2->home，然后点击app2-about,此时，再次点击app1->home,和app1->about页面。会发现，页面已经不跳转了。
监听事件有点麻烦，因为是写在vue-router这个第三方库源代码里面。监听的加载是vue首次实例化时加入的，并且都是由这个第三方库封装好的。无法自定义。具体代码，应该是在
https://github.com/vuejs/vue-router/blob/23d87d8a7e85d0b54345b812e6863e8d23359051/src/history/hash.js#L31

**Comment by kuitos** [comment]
无法复现，我这里跑起来正常的

**Comment by kuitos** [comment]
![Kapture 2019-10-22 at 15 25 13](https://user-images.githubusercontent.com/5206843/67265417-417be100-f4e0-11e9-9b87-4ab12d5e649e.gif)

**Comment by Hades-li** [comment]
> 无法复现，我这里跑起来正常的

只有在生产环境下才会出现，本地开发环境是没有这种问题的。就是要打包发到服务器去跑才会出现。

**Comment by kuitos** [comment]
build 完后放到容器里跑依然无法重现。

sandbox 是否开启是调 start 方法时写的，不会根据环境自己切换..

**Comment by kuitos** [comment]
看了下你的仓库，子应用 unmount 时并没有卸载 vue 实例，如果有问题大概率是这个导致的，具体做法参考 example https://github.com/umijs/qiankun/blob/master/examples/vue/index.js#L28

**Comment by Hades-li** [comment]
> 看了下你的仓库，子应用 unmount 时并没有卸载 vue 实例，如果有问题大概率是这个导致的，具体做法参考 example https://github.com/umijs/qiankun/blob/master/examples/vue/index.js#L28

好吧，这问题我只能自己研究了。vue没卸载的原因是目前我在用qiankun开发一个基于vue-admin-element框架的项目，各种子项目的实例不能被卸载，只能一次性实例化常驻。

**Comment by kuitos** [comment]
为什么不能卸载？

**Comment by kuitos** [comment]
状态脱离 vue 组件实例去管理，全局事件之类的不销毁肯定会出问题

**Comment by Hades-li** [comment]
这个业务要求，必须缓存每个项目的每个页面状态。没办法。另外，还有个问题。子项目全局事件监听其实是会跑在unmount函数调用之前的。也就说，项目切换时，子项目的全局监听事件最后还是会运行一次。然后才会触发unmount回调函数。
所以，并不能做到，当路径改变时，立即就能把子项目给完全卸载掉，至少还是会触发一次子项目的监听事件。

**Comment by kuitos** [comment]
> 这个业务要求，必须缓存每个项目的每个页面状态
缓存状态是可以的，别缓存在组件实例里就行，比如借助 vuex、redux 等三方库就可以搞，甚至你存到一个单独的脱离 vue 的模块里都行

> 子项目全局事件监听其实是会跑在unmount函数调用之前的。。。
不会，顺序是受控的，如果出现了那就是有 bug

**Comment by Hades-li** [comment]
> 这个业务要求，必须缓存每个项目的每个页面状态
> 
> 缓存状态是可以的，别缓存在组件实例里就行，比如借助 vuex、redux 等三方库就可以搞，甚至你存到一个单独的脱离 vue 的模块里都行
> 
> 子项目全局事件监听其实是会跑在unmount函数调用之前的。。。
> 
> 不会，顺序是受控的，如果出现了那就是有 bug

你指的顺序受控是打开沙盒功能才有受控，不打开就没有是这样吗？

**Comment by kuitos** [comment]
是的，不开沙箱不会处理任何副作用

**Comment by CurryChou777** [comment]
我也是基于vue-admin-element使用的qinkun使用时报了如下错误。
![image](https://user-images.githubusercontent.com/22877154/96209704-d1912100-0fa2-11eb-9f1c-5bdad8959e3e.png)
使用方式是，在左侧菜单栏中新增一个菜单项，并单独设置为一个微应用跳转类型，绑定跳转方法`history.pushState(null, null, href)`
点击后就会出现如上图错误，请问这是什么原因呢？
