### ISSUE TITLE
通过MicroAppWithMemoHistory引入的某项目的某页面，在该页面内跳转至某项目的另一个页面地址栏没有变化？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/qiankun#1100]
父应用引入子应用，子应用通过MicroAppWithMemoHistory引入孙应用的某个页面，在该页面中跳转至其他孙应用的另一个页面，在当前情况下，在孙应用中另一个页面如何获取到通过history.push("/另一个页面?abd=xxx")的参数。。

- **qiankun Version**: 2.17.3
- **Platform Version**: mac
- **Browser Version**: chrome 86

**Comment by kuitos** [comment]
memory history 本身就不会反映到地址栏，需要反馈到地址栏用 MicroApp 组件，具体看 react router memory history 原理。

如果还有问题，提供可复现仓库跟复现步骤，reopen issue 即可

**Comment by zhilianbi520** [comment]
> memory history 本身就不会反映到地址栏，需要反馈到地址栏用 MicroApp 组件，具体看 react router memory history 原理。
那么使用MicroApp 组件的话会允许两个应用同时存在嘛？
