### ISSUE TITLE
React+ts技术栈作为子应用，加载的时候主应用崩掉

### ISSUE THREAD

**Issue by Zql-mll** [umijs/qiankun#1101]
## What happens?
主应用是vue+ts技术栈，子应用是react脚手架+ts，react版本17，跳转到react子应用的时候，子应用能正常加载，但是加载完之后，主应用就会崩掉。
![image](https://user-images.githubusercontent.com/44664780/100415477-3027df80-30b7-11eb-8809-c2e94925220e.png)

**主应用控制台信息：**

![image](https://user-images.githubusercontent.com/44664780/100415896-22bf2500-30b8-11eb-9606-6ce4027de9f6.png)

## Mini Showcase Repository(REQUIRED)

React配置：
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import "./public-path";
function render(props: any = {}) {
  ReactDOM.render(<App />, document.getElementById("root"));
}
if (!window.__POWERED_BY_QIANKUN__) {
  render();
}

export async function bootstrap(): Promise<void> {
  console.log("react app bootstraped");
}

export async function mount(props: []): Promise<void> {
  console.log("reactApp mount", props);
  render(props);
}

export async function unmount(): Promise<void> {
  console.log("react unmount");
  const RootNode = document.getElementById("root");
  if (RootNode) {
    ReactDOM.unmountComponentAtNode(RootNode);
  }
}
```
webpack配置：
```
const path = require("path");
const { name } = require("./package");
module.exports = {
  webpack: (config) => {
    config.output.library = `${name}`;
    config.output.libraryTarget = "umd";
    config.output.jsonpFunction = `webpackJsonp_${name}`;
    config.output.globalObject = "window";

    config.resolve.alias = {
      ...config.resolve.alias,
      "@": path.resolve(__dirname, "src"),
      "@core": path.resolve(__dirname, "src/core"),
      "@/pages/*": path.resolve(__dirname, "src/pages"),
      "@components/*": path.resolve(__dirname, "src/components"),
    };
    return config;
  },
  devServer: function (configFunction) {
    return function (proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
      config.disableHostCheck = true;
      config.headers = {
        "Access-Control-Allow-Origin": "*"
      };
      config.historyApiFallback = true;
      return config;
    };
  },
};

```

## Context

- **qiankun Version**: 2.3.2
- **Browser Version**: chrome86

**Comment by Zql-mll** [comment]
想知道除了关掉热重载还有什么办法吗？

**Comment by yangbin932** [comment]
请问解决了吗

**Comment by Zql-mll** [comment]
> 请问解决了吗
[#340 ](https://github.com/umijs/qiankun/issues/340#issuecomment-619641651)
先关闭了热重载，不知道qiankun后期会不会出方案。react-scripts我降到了3.4.4，不然会报config.entry.filter is not a function
![image](https://user-images.githubusercontent.com/44664780/101738024-8f96de00-3b00-11eb-9e6e-02cc5fa0fa21.png)

**Comment by ruoruoji** [comment]
> 想知道除了关掉热重载还有什么办法吗？

![image](https://user-images.githubusercontent.com/30526662/106610760-17014a80-65a2-11eb-91a0-b75c6b59388c.png)
![image](https://user-images.githubusercontent.com/30526662/106610777-1d8fc200-65a2-11eb-9c14-1e1c5a337cde.png)
"start": "cross-env PORT=9090 WDS_SOCKET_PORT=9090 这样启动开发就可以了

**Comment by Zql-mll** [comment]
> > 想知道除了关掉热重载还有什么办法吗？
> 
> ![image](https://user-images.githubusercontent.com/30526662/106610760-17014a80-65a2-11eb-91a0-b75c6b59388c.png)
> ![image](https://user-images.githubusercontent.com/30526662/106610777-1d8fc200-65a2-11eb-9c14-1e1c5a337cde.png)
> "start": "cross-env PORT=9090 WDS_SOCKET_PORT=9090 这样启动开发就可以了

十分感谢，试过了，是可以的。
