### ISSUE TITLE
[Bug]jquery的slideUp方法会导致qiankun的清除定时器的方法疯狂报错，谷歌下不报错，只在ie下报错

### ISSUE THREAD

**Issue by zzy0912** [umijs/qiankun#1102]
## What happens?

使用jquery的slideUp方法，再ie11下会造成控制台的重复报错，如下图所示

![image](https://user-images.githubusercontent.com/43559084/100426863-82bfc680-30cc-11eb-8caf-b25a14cca2e2.png)
![image](https://user-images.githubusercontent.com/43559084/100426880-88b5a780-30cc-11eb-9d53-0da7c8d36451.png)

## 相关环境信息

- **qiankun 版本**：2.0.16
- **浏览器版本**：ie11
- **操作系统**：windows

**Comment by anymouschina** [comment]
对应的babel.config.js和vue.config.js有吗

**Comment by zzy0912** [comment]
> 对应的babel.config.js和vue.config.js有吗

有的
![image](https://user-images.githubusercontent.com/43559084/103052216-8cf1b980-45d3-11eb-900a-18289af5f5bc.png)


![image](https://user-images.githubusercontent.com/43559084/103052197-8105f780-45d3-11eb-9b2e-ca9d51d0aba6.png)
