### ISSUE TITLE
chrome加载子应用资源无法缓存

### ISSUE THREAD

**Issue by lalaze** [umijs/qiankun#1104]
翻了翻issue大部分问题都是不想要浏览器缓存，而我的问题相反，我想要**浏览器缓存**

新建了一个父子应用按照文档引入qiankun，子应用开启跨域

![image](https://user-images.githubusercontent.com/50040779/100546125-8bfe8e00-329a-11eb-9856-316749ca4984.png)

使用chrome从父应用加载子应用，子应用资源无法强缓存或者304（Disable cache没勾）

![image](https://user-images.githubusercontent.com/50040779/100546180-d253ed00-329a-11eb-9799-db9428953404.png)

chrome 版本 86.0.4240.198

而在firefox上是可以304的，试了另外一个chrome的版本也不可以

![image](https://user-images.githubusercontent.com/50040779/100546337-d6343f00-329b-11eb-8141-1ce74147c907.png)

生产环境同域也是一样的问题

请问如何解决这个问题呢，求解答，感谢！

**Comment by lalaze** [comment]
补一张请求响应头
![image](https://user-images.githubusercontent.com/50040779/100563044-6607d680-32f8-11eb-85f2-74c4bc7ce46d.png)
降级版本到85，也一样

**Comment by gongshun** [comment]
显式的添加缓存响应头看下 

![image](https://user-images.githubusercontent.com/29347231/100563834-62754f00-32fa-11eb-8d6c-5ebfcb0756a0.png)

**Comment by lalaze** [comment]
@gongshun 解决了，86应该是新的缓存分区问题，降级然后加显示缓存头解决，谢谢
