### ISSUE TITLE
[Bug]antdpro主应用，两个菜单对应一个vue子应用的两个路径，切换报错

### ISSUE THREAD

**Issue by sunyum** [umijs/qiankun#1105]
## What happens?
antd pro项目使用plugin-qiankun插件配置了一个vue3.0的子应用，主应用和子应用路由都是hash模式
``` js
qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'vue', // 唯一 id
          entry: '//localhost:8001', // html entry
        },
      ],
    },
  },
```
主应用路由配置为：
``` js
routes = [
  {
    path: '/index',
    name: '首页',
    component: './Index',
  },
  {
    path: '/home',
    name: 'home',
    microApp: 'vue',
  },
  {
    path: '/about',
    name: 'about',
    microApp: 'vue',
  },
```
如上，antdpro的两个菜单分别对应子应用的两个路由

菜单点击顺序：
1. index->home->index->about ，此时没有任何问题，都能正常显示
2. index->home->about ，则控制台报错 parcel 'vue_1606727082194_357' died in status SKIP_BECAUSE_BROKEN: [qiankun] Wrapper element for vue with instance vue_1606727082194_357 is not existed!

                  
 

## 相关环境信息

- **qiankun 版本**：2.18.0
- **浏览器版本**：qq浏览器
- **操作系统**：win10

**Comment by gongshun** [comment]
一般报 Wrapper element xxx is not existed!原因有两个：
1. 微应用加载之后快速的触发了卸载，参考https://github.com/umijs/qiankun/issues/1089
2. 2.x版本的 `registerMicroApps` 函数使用了1.x版本的 render 写法

**Comment by 690591397** [comment]
> 一般报 Wrapper element xxx is not existed!原因有两个：
> 
> 1. 微应用加载之后快速的触发了卸载，参考#1089
> 2. 2.x版本的 `registerMicroApps` 函数使用了1.x版本的 render 写法

请问还有解决办法了么，参考了#947 ，并不适用；
适用方式和题主的一样。
因为会有自带菜单路由的旧项目被接入，个人认为由主应用接管了才菜单比较合适。

或者可以子应用去监听主应用的菜单事件，由子应用的router来触发跳转？

**Comment by 690591397** [comment]
> > 一般报 Wrapper element xxx is not existed!原因有两个：
> > 
> > 1. 微应用加载之后快速的触发了卸载，参考#1089
> > 2. 2.x版本的 `registerMicroApps` 函数使用了1.x版本的 render 写法
> 
> 请问还有解决办法了么，参考了#947 ，并不适用；
> 适用方式和题主的一样。
> 因为会有自带菜单路由的旧项目被接入，个人认为由主应用接管了才菜单比较合适。
> 
> 或者可以子应用去监听主应用的菜单事件，由子应用的router来触发跳转？

可以使用自定义的菜单跳转，确保只加载一次子项目

**Comment by 690591397** [comment]
可以试试
```
// instance = new Vue...

export const unmount = async () => {
    instance.$destroy();
    instance.$el.innerHTML = "";
    instance = null;
    // router = null;
}
```

**Comment by Tammeny** [comment]
@gongshun遇到同样的问题，求解。我用的是是react umi

**Comment by jeff6957** [comment]
@gongshun 遇到同样的问题，何时有解

**Comment by gongshun** [comment]
umi 项目出现这个报错就是因为你注册了两次子应用，从而触发了这个

> 微应用加载之后快速的触发了卸载，参考#1089

子应用只需要注册一次，菜单可以写多个。就拿这个 issue 的路由来说，注册时这样写：

```js
routes = [
  {
    path: '/index',
    name: '首页',
    component: './Index',
  },
  {
    path: '/vue',
    name: 'vue',
    microApp: 'vue',
  },
```

你的菜单：

```
<Link to="/vue/home">vue about</Link>
<Link to="/vue/about">vue home</Link>
```

而 Ant Design Pro 的路由和菜单是强绑定的，需要处理下

![image](https://user-images.githubusercontent.com/29347231/116182805-714c1a80-a74f-11eb-93f9-dbb92efcb534.png)

**Comment by HLDipsy** [comment]
> @gongshun遇到同样的问题，求解。我用的是是react umi

请问解决了吗
