### ISSUE TITLE
仓库demo跑不起来

### ISSUE THREAD

**Issue by victorykong** [umijs/qiankun#1108]
![image](https://user-images.githubusercontent.com/50655436/100690600-d62e5f00-33c1-11eb-8b83-1cc4707a599c.png)

`$ cd examples/main && yarn
warning package.json: No license field
error An unexpected error occurred: "Cannot create property '-registry-npm-taobao-org-' on string '{\"-registry-npm-taobao-org-\":\"\"}'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/victorykong/Desktop/victorykong-study/微前端/qiankun/examples/main/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "install:main" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by gongshun** [comment]
https://www.google.com/search?q=Cannot+create+property+%27-registry-npm-taobao-org-%27+on+string+%27%7B%5C%22-registry-npm-taobao-org-%5C%22%3A%5C%22%5C%22%7D&oq=Cannot+create+property+%27-registry-npm-taobao-org-%27+on+string+%27%7B%5C%22-registry-npm-taobao-org-%5C%22%3A%5C%22%5C%22%7D&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8
