### ISSUE TITLE
[Feature Request] loadMicroApp是否支持在同一个子应用进行加载卸载

### ISSUE THREAD

**Issue by czz362100** [umijs/qiankun#1109]
## Background

业务背景：主应用中的业务数据需要在某个业务模块中被复用，所以把主应用作为子应用加载进来，即现在子应用的配置和主应用是一致的。只是路由模式在子应用加载的时候切换成了hash模式。但现在在主应用中点击不同的关联数据想让子应用重新加载一遍，所以用到了loadMicroApp，但是看到官方api文档写着子应用的名字需要唯一。
![image](https://user-images.githubusercontent.com/37129738/100692139-26f38700-33c5-11eb-9ec7-2c114abf00a8.png)
目前报的错误是这个。

## Proposal

想说loadMicroApp是否可以支持一下主应用作为子应用的场景

**Comment by gongshun** [comment]
父项目为啥要自己加载自己呢，父项目的数据和组件都可以通过 props 或者挂在 window 上共享给子项目

**Comment by czz362100** [comment]
不行的，业务场景不符合。不然都不用这么麻烦了

**Comment by lijing666** [comment]
@czz362100 乾坤并没有限制只可以加载一个地址的应用一次，你可以使用不同的name，但是entry是一样的，把他们当成两个不同的子应用加载；另外主应用最好独立，将共享应用拆分成两个独立的子应用加载，所有通讯通过主应用进行；
