### ISSUE TITLE
[Bug]qiankun + vue3 + antd2 select组件卡顿

### ISSUE THREAD

**Issue by L-orz** [umijs/qiankun#1110]
## What happens?

qiankun + vue3 + antd2 select组件卡顿(虚拟列表)，单独运行流畅，接入qiankun卡顿。
table组件在切换pageSize时( 30 -> 200 -> 30)有同样的卡顿问题。

## Mini Showcase Repository(REQUIRED)

https://github.com/xiaoLus/qiankun-vue3-antd2

### 运行

main 为基座，subapp 为微应用  
分别 yarn && yarn serve 之后  
主项目访问地址 <http://localhost:10010/>  
微应用直接地址为 <http://localhost:10011/>

### 复现

使用 ant-design-vue@2.0.0 官方文档 select组件的 big data 功能。  
微应用单独启动时非常流畅，  
嵌入 qiankun基座 中非常卡。  
<https://2x.antdv.com/components/select-cn/#components-select-demo-big-data>

**Expected behavior** 
select组件滚动流畅无卡顿

## Context

- **qiankun Version**: 2.3.2
- **Platform Version**: win10 & macOS catalina
- **Browser Version**: chrome 87

**Comment by kawhi66** [comment]
可能遇到了类似的问题，我的情况是主子系统都是基于 vue@2 实现的，qiankun@2.3.2。当打开 Crome devtool 调试时有内存泄漏的情况，关闭 devtool 之后内存表现正常。我的排查结果显示可能与 zone.js 的处理有关，当我在 主应用里面引入 zone.js 之后，表现正常。

**Comment by xiaoLus** [comment]
@kawhi66 我试过在主应用入口文件引入'zone.js'，但是依旧卡顿( select虚拟列表 3fps， 单独启动有40fps)

**Comment by kawhi66** [comment]
> @kawhi66 我试过在主应用入口文件引入'zone.js'，但是依旧卡顿( select虚拟列表 3fps， 单独启动有40fps)

可能跟我遇到的问题不太一样，但沙盒对应用性能是有影响的，某些场景下的内存开销可能会翻倍

**Comment by kawhi66** [comment]
> @kawhi66 我试过在主应用入口文件引入'zone.js'，但是依旧卡顿( select虚拟列表 3fps， 单独启动有40fps)

可以关掉沙盒试一下

**Comment by xiaoLus** [comment]
@kuitos 请问对于dom操作，有什么优化方法吗？现在antd-vue的组件库在qiankun内性能非常差。

**Comment by ChinaShrimp** [comment]
遇到了同样的问题，等待官方回复。

**Comment by lihuangshuaige** [comment]
官方回复一下吧

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
