### ISSUE TITLE
[Bug]父应用加载子应用的过程中，子应用内的样式突然乱掉。 

### ISSUE THREAD

**Issue by Rabbitzzc** [umijs/qiankun#1111]
## What happens?

父应用（Vue）加载子应用（React）的过程中，子应用内的样式突然乱掉。原因是子应用加载的<style>标签少了，导致遗失了样式。

我们在代码中接入了很多子应用，都是通过 Vue 接入 Vue 的，没有发现会丢失 `style` 标签。在最近一次尝试接入 React 子应用时，发现 `style` 标签少了一个。因此想了解一下为何会出现 style 丢失的情况。

## 最小可复现仓库

因为是公司内部代码，暂时无法给到。

## 相关环境信息

- **qiankun 2.x**
- **chrome 80 +**：
- **Mac OS**：

**Comment by gongshun** [comment]
升级到最新版本看下 https://github.com/umijs/qiankun/issues/1032

**Comment by Rabbitzzc** [comment]
这个没啥用，具体原因还得排查排查

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/100894942-ff510b80-34f7-11eb-8bfa-ca5c171f7860.png)

**Comment by AntiMoron** [comment]
很明显你子应用的css和主应用命名不规范有样式污染，比如主应用有个 .app {xxx}

子应用上来又定义一个.app {xxx}。直接给主应用的样式覆盖了

**Comment by Rabbitzzc** [comment]
> 很明显你子应用的css和主应用命名不规范有样式污染，比如主应用有个 .app {xxx}
> 
> 子应用上来又定义一个.app {xxx}。直接给主应用的样式覆盖了

这个是一点，React 用 module 哈希名称了，可以解决。实际上我犯的一个更大的错误是直接将 React 子项目挂载了全局的 `app` DOM 上，后续改了以后又挂载在了子应用暴露的 container 中，因此出现了这个问题。

很感谢大家回答！

**Comment by zegezs** [comment]
> > 很明显你子应用的css和主应用命名不规范有样式污染，比如主应用有个 .app {xxx}
> > 子应用上来又定义一个.app {xxx}。直接给主应用的样式覆盖了
> 
> 这个是一点，React 用 module 哈希名称了，可以解决。实际上我犯的一个更大的错误是直接将 React 子项目挂载了全局的 `app` DOM 上，后续改了以后又挂载在了子应用暴露的 container 中，因此出现了这个问题。
> 
> 很感谢大家回答！

方便问一下你是怎么处理的吗？

**Comment by Rabbitzzc** [comment]
> > > 很明显你子应用的css和主应用命名不规范有样式污染，比如主应用有个 .app {xxx}
> > > 子应用上来又定义一个.app {xxx}。直接给主应用的样式覆盖了
> > 
> > 
> > 这个是一点，React 用 module 哈希名称了，可以解决。实际上我犯的一个更大的错误是直接将 React 子项目挂载了全局的 `app` DOM 上，后续改了以后又挂载在了子应用暴露的 container 中，因此出现了这个问题。
> > 很感谢大家回答！
> 
> 方便问一下你是怎么处理的吗？

离职了，没有印象了
