### ISSUE TITLE
同时存在2个相同的微服务，样式加载和销毁问题？

### ISSUE THREAD

**Issue by Easy-Martin** [umijs/qiankun#1113]
## What happens?

微服务非单例模式下，同时存在2个相同的微服务，基于React.lazy懒加载时，微服务卸载时，影响未卸载微应用的样式，怀疑是import-html-entry销毁了相同地址的样式表

## Context

- **qiankun Version**:2.x
- **Platform Version**:windows
- **Browser Version**:chrome80+

**Comment by yurizhang** [comment]
我也遇到了~~不知道 怎么办
