### ISSUE TITLE
master分支代码拉下来，ts编译报错

### ISSUE THREAD

**Issue by poppyLuo** [umijs/qiankun#1114]
## What happens?

master代码拉下来，跑yarn examples:install 报错，node版本v10.23.0

## Mini Showcase Repository(REQUIRED)

![image](https://user-images.githubusercontent.com/9317014/100870917-6069e680-34da-11eb-8ac6-c01e390169a9.png)

![image](https://user-images.githubusercontent.com/9317014/100870892-55af5180-34da-11eb-9aec-8856c1df4bdf.png)

## How To Reproduce

**clone master代码后yarn install之后跑yarn examples:install命令可以复现** 

## Context

- **qiankun版本：2.3.2**
- **操作系统：mac**

**Comment by vnues** [comment]
我发现我也是同样的问题

**Comment by vnues** [comment]
![image](https://user-images.githubusercontent.com/44258525/100972961-a5daf200-3574-11eb-961a-e8c51613aaff.png)

他这个框架检测ts比较严格，看报错信息， 但是在这个目录下出现了ts报错问题 ，我暂时改为any就可以了，不然编译不通过
