### ISSUE TITLE
yarn examples:install error

### ISSUE THREAD

**Issue by zhangxinxing59** [umijs/qiankun#1119]
从Git上clone下来的代码yarn install成功，但是
yarn examples:install error

![image](https://user-images.githubusercontent.com/12707010/100991565-1a6e5a80-358e-11eb-80b5-b264baaf82b9.png)

yarn 版本1.17.3
node版本12.18.3
Windows7
qiankun Version： 2.3.2

**Comment by Bigfish-Alex** [comment]
+1
