### ISSUE TITLE
[Bug]Safari不支持Proxy中的属性访问，报错 getter can only be used on instances of Window

### ISSUE THREAD

**Issue by imwtr** [umijs/qiankun#1122]
## What happens?
在Safari 13.0.5 ,可能其他浏览器也会出现，提示，很多window的变量无法获取，直接报错
TypeError: The Window.innerHeight getter can only be used on instances of Window
![image](https://user-images.githubusercontent.com/11251240/101267540-c1244800-3794-11eb-918e-1a17dfbd2242.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

可以直接在Safari中运行这个函数，就能看到
```javascript
function testAccessGetterInWindowProxy(){

    function createFakeWindow(global) {
    // map always has the fastest performance in has check scenario
    // see https://jsperf.com/array-indexof-vs-set-has/23
    var propertiesWithGetter = new Map();
    var fakeWindow = {};
    /*
    copy the non-configurable property of global to fakeWindow
    see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getOwnPropertyDescriptor
    > A property cannot be reported as non-configurable, if it does not exists as an own property of the target object or if it exists as a configurable own property of the target object.
    */

    Object.getOwnPropertyNames(global).filter(function (p) {
        var descriptor = Object.getOwnPropertyDescriptor(global, p);
        return !(descriptor === null || descriptor === void 0 ? void 0 : descriptor.configurable);
    }).forEach(function (p) {
        var descriptor = Object.getOwnPropertyDescriptor(global, p);

        if (descriptor) {
        var hasGetter = Object.prototype.hasOwnProperty.call(descriptor, 'get');
        /*
        make top/self/window property configurable and writable, otherwise it will cause TypeError while get trap return.
        see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/get
        > The value reported for a property must be the same as the value of the corresponding target object property if the target object property is a non-writable, non-configurable data property.
        */

        if (p === 'top' || p === 'parent' || p === 'self' || p === 'window' && (p === 'mockTop' || p === 'mockSafariTop')) {
            descriptor.configurable = true;
            /*
            The descriptor of window.window/window.top/window.self in Safari/FF are accessor descriptors, we need to avoid adding a data descriptor while it was
            Example:
            Safari/FF: Object.getOwnPropertyDescriptor(window, 'top') -> {get: function, set: undefined, enumerable: true, configurable: false}
            Chrome: Object.getOwnPropertyDescriptor(window, 'top') -> {value: Window, writable: false, enumerable: true, configurable: false}
            */

            if (!hasGetter) {
            descriptor.writable = true;
            }
        }

        if (hasGetter) propertiesWithGetter.set(p, true); // freeze the descriptor to avoid being modified by zone.js
        // see https://github.com/angular/zone.js/blob/a5fe09b0fac27ac5df1fa746042f96f05ccb6a00/lib/browser/define-property.ts#L71

        var rawObjectDefineProperty = Object.defineProperty;
            rawObjectDefineProperty(fakeWindow, p, Object.freeze(descriptor));
        }
    });
    return {
        fakeWindow: fakeWindow,
        propertiesWithGetter: propertiesWithGetter
    };
    }

    var _createFakeWindow = createFakeWindow(window),
        fakeWindow = _createFakeWindow.fakeWindow,
        propertiesWithGetter = _createFakeWindow.propertiesWithGetter;


    var proxy = new Proxy(fakeWindow,{
        get(target,p) {
            console.log('get', target[p])
        }
    });

    console.log(proxy);
    console.log(proxy.document);
    console.log(proxy.pageYOffset);

    return proxy;

}
testAccessGetterInWindowProxy()
```
![image](https://user-images.githubusercontent.com/11251240/101267587-3e4fbd00-3795-11eb-8666-95b0eb9c5f89.png)
不确定是不是兼容性问题，实际项目中safari直接报错
在chome中直接调用会报这个，但是实际项目没有报错
![image](https://user-images.githubusercontent.com/11251240/101267625-aacabc00-3795-11eb-8231-abf0d18556ee.png)

目前不好解决，调试发现只有 `SnapshotSandbox`模式正常，其他两个出错
所以看看能否定位兼容一下~~ 或者提供参数，让外部选择使用何种沙箱模式~~
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
example 中未复现，提供可复现仓库后可自行 reopen

**Comment by imwtr** [comment]
试了下例子修改一丢丢就能重现~~ 重现方式也比较简单，在`examples/vue`例子改两个文件即可
1. `package.json` 添加 `"highcharts": "^6.1.0"`  然后安装
2. `examples/vue/src/views/Home.vue` 引入 `highcharts`，放到data中
![image](https://user-images.githubusercontent.com/11251240/101664573-faa3ce80-3a86-11eb-8e1e-47c36018745d.png)
然后重新运行，我这边的 `MacOS 10.15.3`， `Safari 13.0.5` 是会报错， 把data中的Highcharts去掉就不会报错~~
![image](https://user-images.githubusercontent.com/11251240/101664719-24f58c00-3a87-11eb-92fb-351d66904dea.png)


附上`Home.vue`文件
```html
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png"/>
    <HelloWorld msg="Vue.js Demo"/>

    <el-button @click="dialogVisible = true" type="text">Open Dialog</el-button>

    <el-dialog
      :before-close="handleClose"
      :visible.sync="dialogVisible"
      title="Dialog"
      width="30%">
      <span>dialog message</span>
      <span class="dialog-footer" slot="footer">
        <el-button @click="dialogVisible = false">cancel</el-button>
        <el-button @click="dialogVisible = false" type="primary">ok</el-button>
      </span>
    </el-dialog>
  </div>

</template>

<script>
  // @ is an alias to /src
  import HelloWorld from '@/components/HelloWorld.vue';
  import Highcharts from "highcharts";

  export default {
    name: 'home',
    components: {
      HelloWorld,
    },
    data() {
      return {
        Highcharts,
        dialogVisible: false,
      };
    },
    methods: {
      handleClose(done) {
        this.$confirm('Sure to close？')
          .then(_ => {
            done();
          })
          .catch(_ => {
          });
      },
    },
  };
</script>

```

**Comment by imwtr** [comment]
@kuitos 艾特一下哈~~这边好像木有权限 reopen issue的

**Comment by kuitos** [comment]
能不能直接加一段自己的代码复现？而不是引一个三方库进来

**Comment by TheYuuu** [comment]
@imwtr @kuitos 
您好，我在项目中存在一个不规范的写法：在vue页面变量里引用window=window，希望在模板里访问window变量，在其他浏览器中页面正常运行，但是在ios13 safari中页面会报错： The Window.xxx getter can only be used on instances of Window
我在排查过程中，发现这个issues，上面中问题描述的代码块我用xocde模拟在ios13.6 safari中稳定复现，其他系统正常，查找了很久不明白根本原因是什么，希望能够获得各位老师解答。
`function testAccessGetterInWindowProxy(){

    function createFakeWindow(global) {
    // map always has the fastest performance in has check scenario
    // see https://jsperf.com/array-indexof-vs-set-has/23
    var propertiesWithGetter = new Map();
    var fakeWindow = {};
    /*
    copy the non-configurable property of global to fakeWindow
    see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getOwnPropertyDescriptor
    > A property cannot be reported as non-configurable, if it does not exists as an own property of the target object or if it exists as a configurable own property of the target object.
    */

    Object.getOwnPropertyNames(global).filter(function (p) {
        var descriptor = Object.getOwnPropertyDescriptor(global, p);
        return !(descriptor === null || descriptor === void 0 ? void 0 : descriptor.configurable);
    }).forEach(function (p) {
        var descriptor = Object.getOwnPropertyDescriptor(global, p);

        if (descriptor) {
        var hasGetter = Object.prototype.hasOwnProperty.call(descriptor, 'get');
        /*
        make top/self/window property configurable and writable, otherwise it will cause TypeError while get trap return.
        see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/get
        > The value reported for a property must be the same as the value of the corresponding target object property if the target object property is a non-writable, non-configurable data property.
        */

        if (p === 'top' || p === 'parent' || p === 'self' || p === 'window' && (p === 'mockTop' || p === 'mockSafariTop')) {
            descriptor.configurable = true;
            /*
            The descriptor of window.window/window.top/window.self in Safari/FF are accessor descriptors, we need to avoid adding a data descriptor while it was
            Example:
            Safari/FF: Object.getOwnPropertyDescriptor(window, 'top') -> {get: function, set: undefined, enumerable: true, configurable: false}
            Chrome: Object.getOwnPropertyDescriptor(window, 'top') -> {value: Window, writable: false, enumerable: true, configurable: false}
            */

            if (!hasGetter) {
            descriptor.writable = true;
            }
        }

        if (hasGetter) propertiesWithGetter.set(p, true); // freeze the descriptor to avoid being modified by zone.js
        // see https://github.com/angular/zone.js/blob/a5fe09b0fac27ac5df1fa746042f96f05ccb6a00/lib/browser/define-property.ts#L71

        var rawObjectDefineProperty = Object.defineProperty;
            rawObjectDefineProperty(fakeWindow, p, Object.freeze(descriptor));
        }
    });
    return {
        fakeWindow: fakeWindow,
        propertiesWithGetter: propertiesWithGetter
    };
    }

    var _createFakeWindow = createFakeWindow(window),
        fakeWindow = _createFakeWindow.fakeWindow,
        propertiesWithGetter = _createFakeWindow.propertiesWithGetter;


    var proxy = new Proxy(fakeWindow,{
        get(target,p) {
            console.log('get', target[p])
        }
    });

    console.log(proxy);
    console.log(proxy.document);
    console.log(proxy.pageYOffset);

    return proxy;

}
testAccessGetterInWindowProxy()`
