### ISSUE TITLE
[Feature Request] 多子应用共存，各自独立路由

### ISSUE THREAD

**Issue by kulukyo** [umijs/qiankun#1125]
## Background

一个主应用页面，动态加载(loadMicroApp)多个子应用，每个子应用有各自独立的路由，在操作某个子应用时，主应用、其他子应用维持不变，期望此场景下能够正常工作。参考iframe

## Proposal

操作子应用时（切换路由等），对主应用的url无要求（可以变化也可以保持不变）。

**Comment by kuitos** [comment]
应用自己使用 memory history 或者其他等价方案即可

**Comment by kulukyo** [comment]
> 应用自己使用 memory history 或者其他等价方案即可

已使用memory history方案，感谢

**Comment by qtpalmtop** [comment]
> > 应用自己使用 memory history 或者其他等价方案即可
> 
> 已使用memory history方案，感谢

@kulukyo 请教下具体方案可以吗

**Comment by kulukyo** [comment]
> > > 应用自己使用 memory history 或者其他等价方案即可
> > 
> > 
> > 已使用memory history方案，感谢
> 
> @kulukyo 请教下具体方案可以吗

子应用里面加个判断，如果是被qiankun加载的，将router的模式设置为memory。
这样在子应用里面切换路由的时候，就不会改变浏览器url。

**Comment by nailuox** [comment]
> 应用自己使用 memory history 或者其他等价方案即可

动态加载(loadMicroApp)时，子应用 用memory history，在父应用中切换子应用的路由时会响应不到。请教下怎么处理。。

**Comment by lvboda** [comment]
> > > > 应用自己使用 memory history 或者其他等价方案即可
> > > 
> > > 
> > > 已使用memory history方案，感谢
> > 
> > 
> > @kulukyo 请教下具体方案可以吗
> 
> 子应用里面加个判断，如果是被qiankun加载的，将router的模式设置为memory。 这样在子应用里面切换路由的时候，就不会改变浏览器url。

您好 想请教一下在运行时改 umi 的 history 配置的这一步是怎么做的
