### ISSUE TITLE
基座、子应用都是后台管理系统，嵌套的时候怎么避免出现多重菜单问题

### ISSUE THREAD

**Issue by liuerwa** [umijs/qiankun#1126]
基座、子应用都是后台管理系统，嵌套的时候怎么避免出现多重菜单问题

**Comment by gongshun** [comment]
`window.__POWERED_BY_QIANKUN__` 可以用来区分是否被嵌套，嵌套的时候隐藏掉子应用的菜单就可以了

**Comment by liuerwa** [comment]
> `window.__POWERED_BY_QIANKUN__` 可以用来区分是否被嵌套，嵌套的时候隐藏掉子应用的菜单就可以了

好的 我试试  谢谢哦
