### ISSUE TITLE
[Feature Request] 能否支持让主应用获取到Fetch的原始返回体呢

### ISSUE THREAD

**Issue by imwtr** [umijs/qiankun#1127]
## Background

目前fetch资源之后是直接走的内部获取内容逻辑，但一个子应用有很多资源，只要其中一个出问题，整个子应用就加载失败
而这个时候，框架层只会提示一个“加载错误”
![image](https://user-images.githubusercontent.com/11251240/101313178-95868800-3890-11eb-87ed-e53de1c374dc.png)

主应用不知道具体Fetch出错在哪里，跨域错误了，或者404，或者302跳转等等
![image](https://user-images.githubusercontent.com/11251240/101312858-ca460f80-388f-11eb-945f-b443062f1e3c.png)

## Proposal

如果能将原始返回提体，返回给主应用，由主应用做精细化的错误处理，比如可检测到fetch redirect manual的302跳转，
主应用能够手动调用 location去做一些处理
或者在自定义fetch方法时，能够继续调用原生的then和catch方法，目前看起来是不能这么链式调用起来的
![image](https://user-images.githubusercontent.com/11251240/101313249-c4046300-3890-11eb-8082-31f3618d5f3e.png)

**Comment by kuitos** [comment]
用自定义 fetch 就可以了。

302 状态 fetch 是捕获不到的，404 对于 fetch 而言不是异常不会走到 catch 逻辑 https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch
