### ISSUE TITLE
[Bug]第二次从主应用菜单切换到子应用菜单后，当前子应该之间的菜单无法切换

### ISSUE THREAD

**Issue by s980711272** [umijs/qiankun#1128]
## What happens?
bug: 第二次从主应用菜单切换到子应用菜单后，当前子应该之间的菜单无法切换

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
主应用:https://github.com/s980711272/qiankun-Main.git
子应用1:https://github.com/s980711272/qiankun-child1.git
子应用2:https://github.com/s980711272/qiankun-child2.git

## 复现步骤，错误日志以及相关配置
1.先点击home,
2.点击A应用合规，点击A应用数据库，
3.切换到home
4.再次点击A应用合规，点击A应用数据库(这时候会出现Bug)

## 相关环境信息

- **qiankun 版本** 
2.0.25
- **浏览器版本**：
Google 83
- **操作系统**：
windows 64

**Comment by gongshun** [comment]
复现仓库是空的

**Comment by s980711272** [comment]
> 复现仓库是空的

主应用:https://github.com/s980711272/qiankun-Main.git
子应用1:https://github.com/s980711272/qiankun-child1.git
子应用2:https://github.com/s980711272/qiankun-child2.git

**Comment by gongshun** [comment]
子应用没有销毁 `vue` 实例导致的，你每次加载都会 `new Vue`，导致 `router` 有两个 `app` 实例，https://github.com/s980711272/qiankun-child1/blob/bac462e99e69a465d7673b9ffed43830049de8da/src/main.js#L47

![image](https://user-images.githubusercontent.com/29347231/101319513-15b2ea80-389d-11eb-81ba-d759f05020f2.png)

打开注释

**Comment by s980711272** [comment]
如果需要使用缓存，https://juejin.cn/post/6856569463950639117#heading-14 第三条已测可用
