### ISSUE TITLE
[Bug]npm run examples:install 报错(2020-12-7从仓库下载demo)

### ISSUE THREAD

**Issue by HiNaruta** [umijs/qiankun#1131]
## What happens?
npm run examples:install 报错

## 错误日志
1. C:/code/qiankun/node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2982,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'. (单独一个)
2. C:/code/qiankun/node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2995,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.(大量)

## 最小可复现仓库
https://github.com/umijs/qiankun.git

## 复现步骤，错误日志以及相关配置
git clone https://github.com/umijs/qiankun.git
cd qiankun
npm i
npm run examples:install

## 尝试过的操作
1. 删除node_moudle, npm重新下载, 再次运行 
2. src/utils 85 行变更为resolve!: (value?: any) => void;

## 相关环境信息
- **qiankun 版本**: qiankun@2.3.2
- **浏览器版本**：node v14.15.1
- **操作系统**：win10

**Comment by kuitos** [comment]
用 yarn 不要用 npm https://github.com/umijs/qiankun#-getting-started
