### ISSUE TITLE
父应用调用setGlobalState，父应用能通过onGlobalStateChange监听到state变化，但是子应用不能，是设计如此还是一个bug，还是我配置问题

### ISSUE THREAD

**Issue by 1620165757** [umijs/qiankun#1142]
qiankun 版本：2.3.2
浏览器版本：google 87.0.4280.88
操作系统：mac
node：14.3.0

**Comment by gongshun** [comment]
是不是 setGlobalState 调用时机不对，子应用还没注册监听父应用就调用了 setGlobalState

https://qiankun.umijs.org/zh/api#initglobalstatestate

**Comment by 1620165757** [comment]
> 是不是 setGlobalState 调用时机不对，子应用还没注册监听父应用就调用了 setGlobalState
> 
> https://qiankun.umijs.org/zh/api#initglobalstatestate
![image](https://user-images.githubusercontent.com/22805742/101610089-bee71580-3a42-11eb-8316-8f91a652c081.png)
我是在子应用mount的时候注册监听的，第一个log都有打印，但是监听里面的log没有打印。

**Comment by gongshun** [comment]
第二个参数，设置为true

![image](https://user-images.githubusercontent.com/29347231/101610865-c22ed100-3a43-11eb-88c8-fe4203162abd.png)
