### ISSUE TITLE
子应用跳转到主应用失败,主应用路由跟随在子项目路由后

### ISSUE THREAD

**Issue by WangLucy** [umijs/qiankun#1143]
## What happens?
子应用跳转到主应用失败,主应用路由跟随在子项目路由后。

## 最小可复现仓库
主应用：https://github.com/WangLucy/qk-main
子应用：https://github.com/WangLucy/vue3

1：先从主项目进入到子项目，2:再从子项目返回到主项目失败，失败原因是主项目的路由（http://localhost:8001/apps）跟随在子项目路由后（http://localhost:7105/vue3/apps）；尝试过qiankun官网的2种跳转方法后均没能实现，子项目vue3是官网案例，因为要实现进入子项目后路由是后台动态获取，需要配合路由守卫，所以把官网的vue3的项目稍作小改。

## 相关环境信息

- **qiankun 版本**
^2.3.2
-** vue 版本
vue: ^3.0.4
- **浏览器版本**：

- **操作系统**：

**Comment by WangLucy** [comment]
看了官网的案例是把createRouter 创建的路由实例放在了入口main.js 中，从子项目跳转到主项目是可以的，但是这里的路由也只能是静态的或者从主项目的路由传过来，不能实现进入到子项目后动态从后台获取。

**Comment by gongshun** [comment]
主项目的路由实例通过 props 传过去，可以跳转，没问题。

> 但是这里的路由也只能是静态的或者从主项目的路由传过来，不能实现进入到子项目后动态从后台获取。

至于这个问题，你的 render 函数里面也可以掉接口，路由数据同样可以从后台获取

**Comment by WangLucy** [comment]
> 主项目的路由实例通过 props 传过去，可以跳转，没问题。
> 
> > 但是这里的路由也只能是静态的或者从主项目的路由传过来，不能实现进入到子项目后动态从后台获取。
> 
> 至于这个问题，你的 render 函数里面也可以掉接口，路由数据同样可以从后台获取

我试过你说的在render函数里调用接口，还是不行，我主应用用的是vue3.0的。我用vue2.6写的主应用的例子是可以跳转的，3.0的跳转不行。

**Comment by gongshun** [comment]
> 我试过你说的在render函数里调用接口，还是不行，我主应用用的是vue3.0的。我用vue2.6写的主应用的例子是可以跳转的，3.0的跳转不行。

需要传递的是路由实例，而不是路由数据

https://github.com/WangLucy/qk-main/blob/9522ffd8f1b2e828abff10eaf56e0ff22b6aa70a/src/layout/appMain.vue#L25

这个地方，改为 `appRouters: router`

**Comment by WangLucy** [comment]
> > 我试过你说的在render函数里调用接口，还是不行，我主应用用的是vue3.0的。我用vue2.6写的主应用的例子是可以跳转的，3.0的跳转不行。
> 
> 需要传递的是路由实例，而不是路由数据
> 
> https://github.com/WangLucy/qk-main/blob/9522ffd8f1b2e828abff10eaf56e0ff22b6aa70a/src/layout/appMain.vue#L25
> 
> 这个地方，改为 `appRouters: router`

非常感谢，你提供的方法解决了我的问题！！！
