### ISSUE TITLE
[Feature Request] 脚本执行及微应用全局属性定制化支持

### ISSUE THREAD

**Issue by SoldierAb** [umijs/qiankun#1144]
## Background

- 期望支持脚本执行的定制化处理
- 支持微应用全局属性拦截定制处理

## Proposal

- Start Opts 添加 execScriptsHooks 
    
![image](https://user-images.githubusercontent.com/33128022/101711604-d79d0d00-3ace-11eb-90b5-0d38b24f348b.png)

![image](https://user-images.githubusercontent.com/33128022/101711776-35315980-3acf-11eb-90bc-604e655007ad.png)

- Start Opts 添加 customizeProxyProperty 
  
![image](https://user-images.githubusercontent.com/33128022/101711894-6c076f80-3acf-11eb-8c68-58baf1560784.png)

![image](https://user-images.githubusercontent.com/33128022/101712036-a8d36680-3acf-11eb-897b-b1dda6d5b580.png)

## Additional context
![image](https://user-images.githubusercontent.com/33128022/101712842-6579f780-3ad1-11eb-857c-78346426ffbf.png)

alpha-link : https://github.com/SoldierAb/qiankun 

[Pull Request]:  https://github.com/umijs/qiankun/pull/1145

**Comment by enhezzz** [comment]
up↑

**Comment by kuitos** [comment]
> 期望支持脚本执行的定制化处理

可以描述下你的场景跟诉求

> 支持微应用全局属性拦截定制处理

这个是计划在 qiankun3 里以插件的形式支持的，形式不仅是现在这种支持对 getter 的拦截，set、iteration 等各种 hook 都需要考虑一下

**Comment by SoldierAb** [comment]
> > 期望支持脚本执行的定制化处理
> 
> 可以描述下你的场景跟诉求
> 
> > 支持微应用全局属性拦截定制处理
> 
> 这个是计划在 qiankun3 里以插件的形式支持的，形式不仅是现在这种支持对 getter 的拦截，set、iteration 等各种 hook 都需要考虑一下

场景是微应用挂载时， 需针对要解析的js脚本做执行上下文的指定 以及可能需要对脚本的解析做特殊处理，所以加了execScriptsHooks，目前来看是满足的；
其次 很期待 qiankun3 沙箱定制化 的插件支持。

**Comment by kuitos** [comment]
> 需针对要解析的js脚本做执行上下文的指定 以及可能需要对脚本的解析做特殊处理

给一个具体的案例吧，比如你需要做什么操作

**Comment by SoldierAb** [comment]
> > 需针对要解析的js脚本做执行上下文的指定 以及可能需要对脚本的解析做特殊处理
> 
> 给一个具体的案例吧，比如你需要做什么操作

https://github.com/SoldierAb/qiankun/tree/master/examples/main-vue 这边有个简单的demo , 主要做的事情就是指定下sdk挂载的上下文，避免挂载到全局window上；脚本解析处理的话，暂时没有加上hook，仍在测试阶段

**Comment by kuitos** [comment]
现在可以在 beforeMount 这些钩子里处理，第二个入参是 global

**Comment by SoldierAb** [comment]
> 现在可以在 beforeMount 这些钩子里处理，第二个入参是 global



> 现在可以在 beforeMount 这些钩子里处理，第二个入参是 global

能否透露下 qiankun3 预计啥时候发布

**Comment by SoldierAb** [comment]
> 现在可以在 beforeMount 这些钩子里处理，第二个入参是 global

👌

**Comment by SoldierAb** [comment]
> 现在可以在 beforeMount 这些钩子里处理，第二个入参是 global

但是 execScripts 【loader.ts】 在生命周期beforeMount调用前已经做解析了，不满足目前的场景 —— 需要scripts 脚本解析前指定 脚本中的全局变量。所以可否考虑提供类似 execScriptsHooks 的 API

**Comment by kuitos** [comment]
beforeLoad

**Comment by kuitos** [comment]
execScriptsHooks 感觉不必要，用户不应该关注里面的实现细节，只需要关注沙箱环境的生命周期就可以了

**Comment by SoldierAb** [comment]
> execScriptsHooks 感觉不必要，用户不应该关注里面的实现细节，只需要关注沙箱环境的生命周期就可以了

嗯， 好的。 官方文档应该需要同步下

**Comment by kuitos** [comment]
近期 bugfix 为准，后面的大的 feature 迭代会同步到 https://github.com/umijs/qiankun/projects

**Comment by SoldierAb** [comment]
> 近期 bugfix 为准，后面的大的 feature 迭代会同步到 https://github.com/umijs/qiankun/projects

💖
