### ISSUE TITLE
[Bug]ie11下manualInvokeElementOnLoad方法报错

### ISSUE THREAD

**Issue by ilovejlj** [umijs/qiankun#1146]
# [Bug]ie11下manualInvokeElementOnLoad方法报错

## What happens?

ie11下manualInvokeElementOnLoad方法报错

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置

`manualInvokeElementOnLoad`这个方法里使用了`new CustomEvent('load')`来生成一个load事件，看了下caniuse上的介绍，说ie11下不能`new CustomEvent`，需要`e = document.createEvent('CustomEvent')`然后`e.initCustomEvent(...)`

## 相关环境信息

- **qiankun 版本**: 2.3.1
- **浏览器版本**：ie11
- **操作系统**：windows

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%BB%99-ie-%E6%89%93%E8%A1%A5%E4%B8%81%EF%BC%9F

![image](https://user-images.githubusercontent.com/29347231/101737020-3bd7c500-3aff-11eb-9ff3-c88eee7fb308.png)
