### ISSUE TITLE
可以提供一个UNPKG的产出吗？

### ISSUE THREAD

**Issue by gxy01** [umijs/qiankun#1147]
## 背景

用老系统加载新的子系统，在老系统里需要引入乾坤。老系统里，显然是没有打包啥的。那么一个script标签引入就很方便。

**Comment by jishuke** [comment]
https://unpkg.com/browse/qiankun@2.5.1/dist/index.umd.min.js
老项目是php模版渲染的，服务是用docker 起的，以php项目为父应用，请问怎么配置。可以使用这个
