### ISSUE TITLE
webpack4+vue项目使用乾坤项目报died in status LOADING_SOURCE_CODE

### ISSUE THREAD

**Issue by CodeLittlePrince** [umijs/qiankun#115]
乾坤从demo来看很棒，但是我用自己的vue项目来结合乾坤，弄了好久还是整不通，一直报：

index.esm.js:638 Uncaught game: Application 'game' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in game entry
image
用的是webpack 4，也完全按照文档修改了对应的文件（webpack的umd+项目入口文件暴露三个接口），最终失败，请问是哪里出问题了？
项目地址：https://github.com/CodeLittlePrince/qiankun-test

**Comment by kuitos** [comment]
多 entry 场景下这里改成 `'[name]'`  https://github.com/CodeLittlePrince/qiankun-test/blob/master/examples/game/webpack/webpack.config.dev.js#L21

**Comment by CodeLittlePrince** [comment]
@kuitos 改了依然报错哦，如下图：
![image](https://user-images.githubusercontent.com/17001245/67269001-696f4280-f4e8-11e9-9398-8009a1552b12.png)
Uncaught game: Application 'game' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in game entry
代码已更新

**Comment by wusp1994** [comment]
我也是报这个错，webpack的vue项目.需要做成什么样的 output 呢？

**Comment by wusp1994** [comment]
已解决，子项目里的main.js 没有暴露周期钩子函数，仿照 案例，写入周期函数，把new Vue()包裹进去就好了

**Comment by CodeLittlePrince** [comment]
> 已解决，子项目里的main.js 没有暴露周期钩子函数，仿照 案例，写入周期函数，把new Vue()包裹进去就好了

@wusp1994 我的项目中有暴露周期钩子函数。你应该是用了vue-cli吧？

**Comment by wusp1994** [comment]
> > 已解决，子项目里的main.js 没有暴露周期钩子函数，仿照 案例，写入周期函数，把new Vue()包裹进去就好了
> 
> @wusp1994 我的项目中有暴露周期钩子函数。你应该是用了vue-cli吧？

嗯，我使用vue cli3 创建的项目。

**Comment by cshsh** [comment]
@CodeLittlePrince 你解决了吗， 我用 webpack 4 也是报同样的错

**Comment by CodeLittlePrince** [comment]
> @CodeLittlePrince 你解决了吗， 我用 webpack 4 也是报同样的错

没有，已放弃治疗

**Comment by wusp1994** [comment]
看我案例 https://github.com/wusp1994/qiankunTestByWu.git 可以的

**Comment by cshsh** [comment]
@wusp1994  ，你的例子是vue cli3 创建的项目， 使用webpack4创建报这个错，打算放弃

![image](https://user-images.githubusercontent.com/12389638/68391116-d437a380-01a1-11ea-9c73-5ffccb3a8bc9.png)

**Comment by kuitos** [comment]
https://github.com/CodeLittlePrince/qiankun-test/blob/master/examples/game/webpack/dev.js#L23-L28
往 entry 里加这些东西会导致你的 umd 包无法 export 变量。
btw，webpack 现在已经不需要这样去配置 hot reload 了。

**Comment by CodeLittlePrince** [comment]
> https://github.com/CodeLittlePrince/qiankun-test/blob/master/examples/game/webpack/dev.js#L23-L28
> 往 entry 里加这些东西会导致你的 umd 包无法 export 变量。
> btw，既然你都用 webpack-dev-server 了，就不需要再这样去配置 hot reload 了。

其实之前我把hot reload直接干掉试过，的确不在报`died in status`了。不过，还是出现新的问题，就是hot reload功能没了无法接受，再是按路由分的按需加载无法正常加载。
你说`webpack-dev-server`不需要这样匹配hot reload的话那我再试试。不过按需加载还是得想办法解决。
最后建议出一个webpack4+按需加载的demo，遇到这问题的人太多了，而且解决起来非常耗时间。

**Comment by wusp1994** [comment]
> > https://github.com/CodeLittlePrince/qiankun-test/blob/master/examples/game/webpack/dev.js#L23-L28
> > 往 entry 里加这些东西会导致你的 umd 包无法 export 变量。
> > btw，既然你都用 webpack-dev-server 了，就不需要再这样去配置 hot reload 了。
> 
> 其实之前我把hot reload直接干掉试过，的确不在报`died in status`了。不过，还是出现新的问题，就是hot reload功能没了无法接受，再是按路由分的按需加载无法正常加载。
> 你说`webpack-dev-server`不需要这样匹配hot reload的话那我再试试。不过按需加载还是得想办法解决。
> 最后建议出一个webpack4+按需加载的demo，遇到这问题的人太多了，而且解决起来非常耗时间。
脚手架的也是webpack 啊，只不过是封装了一些东西，况且提供了更细粒度的webpack配置入口，有什么区别吗？你按我配置来不就行了

**Comment by wusp1994** [comment]
@cshsh  脚手架 vue-cli 就是webpack4. 他不过是 装默认了一些配置，里面都可以 配更细粒度的webpack4，没有什么不同的

**Comment by kuitos** [comment]
@CodeLittlePrince 按需加载的问题这样解决 https://github.com/umijs/qiankun/wiki/FAQ#why-dynamic-imported-assets-missing

本周会完善相关 demo 及文档
