### ISSUE TITLE
[Bug]从应用跳转到子应用后、后退页面无法自动刷新

### ISSUE THREAD

**Issue by dounine** [umijs/qiankun#1155]
## 最小可复现仓库

https://github.com/dounine/qiankun-router-error3

## 复现步骤，错误日志以及相关配置
root模块作为入口、children为子应用、跳转到子应用后、点浏览器后退按钮、无法正常后退。显示的还是上一个路由的内容
vue2可以、vue3版本不行。
qiankun所演示的vue3 demo也不行、只要来回点击home与about后、就不能正常后退了。

## 相关环境信息

- **qiankun 版本**: 2.3.3
- **浏览器版本**: chrome 87.0.4280.88
- **操作系统**: centos7

## 演示过程
主应用
```
cd root
npm install
npm run serve
```
子应用
```
cd children
npm install
npm run serve
```
访问 [http://localhost:8081](http://localhost:8081)

**Comment by dounine** [comment]
# 已解决
解决方案如下、主应用跳转到微应用不能使用主应用的vue-router方式进行跳转、需要使用`history.pushState`方式。

**Comment by xiaoLus** [comment]
主应用使用vue2，子应用vue3，两个router还是会冲突，点击浏览器返回按钮，匹配不到对应路由。
