### ISSUE TITLE
[Feature Request] 修复angular子应用中rxjs异步后视图不及时刷新

### ISSUE THREAD

**Issue by doxingg** [umijs/qiankun#1157]
## Background

在使用angular9作为子应用时，如果使用了rxjs的异步，在异步的订阅中，NgZone.isInAngularZone()值是false，结果就是视图不会及时刷新

## Proposal

需要将主应用的引入zone.js的方式修改一下

不能在主应用index.js中使用`import 'zone.js'`;方式引用，应该修改为在index.html中用`<script src="/assets/js/zone.js"></script>`方式引用

## Additional context

Repo地址[repo](https://github.com/doxingg/qiankun.git)

repo中修改了主应用zone.js引用方式，并且在angular9子应用`AppComponent`中添加了示例

可以尝试在不同zone.js引用方式下，查看angular9子应用中的输出的日志和视图中title的显示情况

**Comment by gongshun** [comment]
与引入方式无关，与引入位置有关，参考 https://github.com/umijs/qiankun/pull/1178 ，将 `import 'zone.js'`放到 `import  qiankun` 上面即可
