### ISSUE TITLE
[Bug]子应用为动态路由，如何缓存页面数据

### ISSUE THREAD

**Issue by lifei-coco** [umijs/qiankun#1158]
子应用为动态理由，创建了一个多tab的效果
在同一个应用的tab切换的时候，页面都被清空了 
如何保持页面不被清空，页面数据缓存（例如：列表数据，表单数据）

**Comment by gongshun** [comment]
参考 https://github.com/umijs/qiankun/issues/361

`keep-alive` 效果与动态路由无关，动态路由一样可以实现。

**Comment by kuaifengle** [comment]
参考演示地址: https://github.com/kuaifengle/qiankun-vue3-tabsPage
