### ISSUE TITLE
注册 angular 子项目报错

### ISSUE THREAD

**Issue by succulen-plants** [umijs/qiankun#116]
## What happens?
**Uncaught angular: Application 'angular' died in status LOADING_SOURCE_CODE: Cannot set property 'observe' of undefined**

```
registerMicroApps(
  [
    { name: 'react app', entry: '//localhost:7100', render, activeRule: genActiveRule('/react') },
    { name: 'react15 app', entry: '//localhost:7102', render, activeRule: genActiveRule('/15react15') },
    { name: 'vue app', entry: '//localhost:7101', render, activeRule: genActiveRule('/vue') },
    { name: 'react webpack', entry: '//localhost:8000', render, activeRule: genActiveRule('/yapi') },
    { name: 'angular', entry: '//localhost:4200', render, activeRule: genActiveRule('/angular') },
  ],
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**:
- **Browser Version**:
- **Node Version**:

**Comment by BoneShooter** [comment]
Angular子项目目前不能接入的原因：

1. qiankun在加载子应用前，会使用es6的Proxy方法，在window上创建一份proxy（也就是所谓的jsSandbox），让子应用实际运行在proxy中，以此来监听子应用做出的对window修改并能在卸载应用时还原。简单来说，就是当前的proxy的与Angular所依赖的zone.js不兼容，导致在加载Angular子应用时直接报错。
2. 当前qiankun进行子应用的模块导入时，会查找最后一个添加到window上的全局变量作为需要umd的变量。而Angular 6.x以上版本会在全局创建ngDevMode等全局变量，导致qiankun寻找到的的export变量为ngDevMode。最后导致qiankun进行模块查找时出现错误。
```
// 原来的代码
var exports = proxy[(0, _utils.getGlobalProp)()] || {};
resolve(exports);
```
3. qiankun的子路由导航基于single-spa实现，而当前single-spa最新版本（4.4.1）与Angular的部分情况路由策略（onSameUrlNavigation: 'reload' ）存在兼容性问题，会存在路由死循环。
```
// 如下配置有问题
RouterModule.forRoot(appRoutes, {
    useHash: true,
    onSameUrlNavigation: 'reload',
}),
```
4. qiankun基于single-spa实现，single-spa官网明确说明，一个项目的zone.js只能存在一份实例，所以不要在子项目中引入zone.js。



解决方案：

1. 
临时解决：主项目全局引入zone.js，Angular子项目去掉zone.js依赖
后续方案：我有空会提个pr，把zone.js的兼容性问题解决下

2. 建议在registerMicroApps时，每一项的props中传入appEntryName配置。然后在创建sandbox时，传入props。然后在sandbox中定义一个特殊变量__app_entry_name__给 import-html-entry 使用。
大致解决思路是这样，有更优秀的解决方案欢迎讨论。（已提了个初步的pr给作者）
解决思路如下：
examples/main/index.js
```
{ name: 'angular8 app', entry: '//localhost:7103', render, activeRule: genActiveRule('/angular8'), props: { appEntryName: 'ngTestApp' } }
```
src/index.ts
```
const sandbox = genSandbox(appName, props);
```
src/sandbox.ts
```
const sandbox = genSandbox(appName, props);
```
get(target: Window, p: PropertyKey) {
      if (p === '__app_entry_name__') {
        return props.appEntryName || undefined;
      }
      ...
}
```
import-html-entry中获取入口时，改为先判断sandbox上的__app_entry_name__属性
```
// get custom 'app_entry_name' if user have assigned.
const __app_entry_name__ = proxy.__app_entry_name__;
if (__app_entry_name__ === undefined || __app_entry_name__ === null || __app_entry_name__ === '') {
    __app_entry_name__ = getGlobalProp();
}
const exports = proxy[__app_entry_name__] || {};
resolve(exports);
```
3. Angular子项目路由策略不要配置为: onSameUrlNavigation: 'reload'
4. 主项目全局引入zone.js，Angular子项目去掉zone.js依赖
5. Angular子项目做一些改造：
    a. 支持生命周期钩子
    b. 去掉zone.js（有点尴尬，dev模式就不能调了）
    c. webpack的output配置增加umd
    d. 参考已提Angular8 demo的pr例子

**Comment by howel52** [comment]
>    b. 去掉zone.js（有点尴尬，dev模式就不能调了）

externals 的话调还是能调的吧

**Comment by BoneShooter** [comment]
@howel52 

> 如果只是 zone.js 的原因，externals 的话调还是能调的吧

子应用需要去掉zone.js的依赖，那么子应用只能在主应用中跑。
-----------------
当然，也可以通过一些hack的手段，让子应用可以独立跑起来调试，举个栗子：
先判断一下当前子应用是否运行在【微前端】环境中，
如果是，则不加载zone.js依赖，以及不主动掉用子应用的mount方法；
如果不是，则加载zone.js依赖，以及主动掉用子应用的mount方法，让子应用独立跑起来。

**Comment by succulen-plants** [comment]
然后在sandbox中定义一个特殊变量__app_entry_name__给 import-html-entry 使用, getGlobalProp() 在哪里定义的， 能不能给一个具体的例子，

**Comment by succulen-plants** [comment]
已经将子项目的 zone卸载， 但是 总项目上面有报：
VM1091:239 Error: In this configuration Angular requires Zone.js
index.esm.js:674 Uncaught angular: Application 'angular' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in angular entry

**Comment by BoneShooter** [comment]
@succulen-plants 
> 然后在sandbox中定义一个特殊变量__app_entry_name__给 import-html-entry 使用, getGlobalProp() 在哪里定义的， 能不能给一个具体的例子，

作者已经修改了代码。采用了appName作为umd export变量解析失败时的fallback，我看前两天已经更新了。因此无需再额外使用__app_entry_name__配置。

关于demo：
移除子项目的zone.js依赖后，需要在主应用中import zone.js。不着急的话，过段时间我把angular使用demo改一下再加上。(如果后面作者对zone.js做好了兼容，会更方便一些)

你有兴趣话，可以先看下这几天我和作者的讨论：https://github.com/umijs/qiankun/pull/130

**Comment by PolanZ** [comment]
@BoneShooter 
加载ng子项目时，出现了生命周期抛出不对，我打印了下看到没有抛出生命周期函数
![image](https://user-images.githubusercontent.com/8565486/71790844-863dff80-306d-11ea-9f3c-eeed359e8ee0.png)

但在ng项目的main.ts里面已经加了
```js
export async function bootstrap() {
  console.log('angular app bootstraped');
}

export async function mount(props) {
  console.log('angular app mount', props);
  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.error(err));
}

export async function unmount() {
  platformBrowserDynamic().destroy();
}

if (environment.production) {
  enableProdMode();
}
```

知道怎么回事吗？

**Comment by kuitos** [comment]
@PolanZ see https://github.com/umijs/qiankun/wiki/FAQ#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by tinet-xiaoyang** [comment]
这个问题在最新的 examples 里面仍然存在啊，应该怎么解决？
