### ISSUE TITLE
主应用路由跳转不能自动帮助子应用进行跳转

### ISSUE THREAD

**Issue by django-d** [umijs/qiankun#1160]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?
主应用使用vue3, 集成乾坤. 使用vite 进行打包, 使用了 vue-router 4.0.1 
问题: 子应用如果也是vue3 并且也是 vue router4.0.1 主应用路由跳转不能自动帮助子应用进行跳转

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** : 2.3.2
- **浏览器版本**： chrome 87.0.4280.88（正式版本)
- **操作系统**：macos windows

**Comment by XingXiaoWu** [comment]
老哥有没有遇到子应用不响应浏览器的第一次后退
