### ISSUE TITLE
想在主应用的模块加载子应用，但子应用的location.href改变了整个项目的域名，这个怎么处理诶

### ISSUE THREAD

**Issue by Evis5** [umijs/qiankun#1163]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8
