### ISSUE TITLE
question: dumi

### ISSUE THREAD

**Issue by wibed** [umijs/qiankun#1164]
combine dumi with qiankun

how would one handle sub-routes of dumi
without the sub application taking over the page?

is there an example?

**Comment by gongshun** [comment]
dumi is a Umi-based doc tool https://d.umijs.org/guide#%E4%BB%80%E4%B9%88%E6%98%AF-dumi%EF%BC%9F 😂 do you meaning umi ?

**Comment by wibed** [comment]
I mean:
- / (qiankun)
  - /subapp1/ (dumi)
    - /subapp1/doc subroute1
    - /subapp1/guide subroute2
    
I want to access /subapp1/doc inside qiankun container

**Comment by kuitos** [comment]
Can't get your point, could you pls provide an example to introduce what your requirement?

**Comment by wibed** [comment]
I have made a mistake.
I used hydrate instead of render which broke the application. thank you for your help
