### ISSUE TITLE
在vue-router 生成的嵌套路由中的子路由页面中，加载子应用，初次加载正常，再次加载失败，刷新浏览器，重新恢复正常加载

### ISSUE THREAD

**Issue by HuRuilin** [umijs/qiankun#1169]
## What happens?
主应用和子应用都采用vue 框架，主应用路由方式设定为history模式，子应用路由方式设定为hash模式，需求是在使用vue-router生成的嵌套路由的子路由页面中加载微应用，通过点击左侧菜单访问目标路由页面，第一次微应用正常加载显示，切换其他路由后，再切回目标路由页面，报错
```
Target container with #micro-app not existed while microApp-A mounting!
```
手动刷新浏览器页面后，微应用又能正常加载出来

## 最小可复现仓库
主应用地址： https://github.com/HuRuilin/qiankun-main.git

子应用地址：https://github.com/HuRuilin/qiankun-micro.git

## 复现步骤，错误日志以及相关配置

1、分别启动主应用、子应用
```
npm install
npm run dev
```
2、使用默认账号、密码分别登录主、子应用

3、点击主应用左侧  【微应用A】菜单,此时微应用正常加载，显示 “您好，欢迎您进入微应用A的世界”

4、点击【Dashboard】菜单，切换路由后，再切回【微应用A】菜单 ,控制台报错 "Target container with #micro-app not existed while microApp-A mounting!"

5、使用浏览器提供的刷新功能，重新加载当前路由(即【微应用A】对应的路由页面)，微应用正常加载出内容

## 相关环境信息

- **qiankun 版本**
v 2.3.4
- **浏览器版本**：
google   87.0.4280.88
- **操作系统**：
win10 64位

**Comment by qq1198437442** [comment]
宝贝，我也遇到了，而且发现是因为：上一个微应用实例在切换路由时没有销毁，所以，重新进来时没有再次加载微应用。

**Comment by HuRuilin** [comment]
> 宝贝，我也遇到了，而且发现是因为：上一个微应用实例在切换路由时没有销毁，所以，重新进来时没有再次加载微应用。

不应该啊，我有在unmount()函数里做销毁操作哦
```
/**
 * 应用每次 切出/卸载 会调用的方法，通常在这里我们会卸载微应用的应用实例
 */
export async function unmount() {
  console.log('VueMicroApp unmount')
  instance.$destroy()
  instance = null
}
```

**Comment by gongshun** [comment]
很明显你的路由不对啊，当你这样配置路由时，你菜单和 `activeRule` 应该是 `iframeBox/iframeBox`  

![image](https://user-images.githubusercontent.com/29347231/102778609-dcff2f00-43cd-11eb-92dd-4b44c39a768f.png)

https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by HuRuilin** [comment]
如果是路由配置不对，那给出的也应该是路由配置的建议啊，我之所以配置成这样，就是因为文档表述真的是让人费解，可能给你们自己人看的吧，我认真按照你们的issue要求提问，问题没有经过验证，问题怎么就关闭了呢

**Comment by gongshun** [comment]
不要把菜单和路由用一份数据，路由注册不变的话，`activeRule` 应该是 `/iframeBox/iframeBox`，然后新增一个菜单：`<el-menu-item index="/iframeBox/iframeBox">子应用</el-menu-item>`，点击这个菜单就可以了

**Comment by qq1198437442** [comment]
> > 宝贝，我也遇到了，而且发现是因为：上一个微应用实例在切换路由时没有销毁，所以，重新进来时没有再次加载微应用。
> 
> 不应该啊，我有在unmount()函数里做销毁操作哦
> 
> ```
> /**
>  * 应用每次 切出/卸载 会调用的方法，通常在这里我们会卸载微应用的应用实例
>  */
> export async function unmount() {
>   console.log('VueMicroApp unmount')
>   instance.$destroy()
>   instance = null
> }
> ```

很难说，我这边也是有销毁的。可实际上每次切出之后再切入，props里边的东西就没有再次执行。实际上我的props传递的是leaflet图层，以及map实例，可是再次切入后，props里边的回调函数没有再次执行，然而页面居然还显示图层。推测可能就是因为来回切换，传递的内容残存，所以没有再次执行props里边的回调。

**Comment by qq1198437442** [comment]
> 不要把菜单和路由用一份数据，路由注册不变的话，`activeRule` 应该是 `/iframeBox/iframeBox`，然后新增一个菜单：`<el-menu-item index="/iframeBox/iframeBox">子应用</el-menu-item>`，点击这个菜单就可以了

麻烦问一哈，我这边可奇怪了，在子应用里边，切出之后再切入，会再次创建微应用实例，但是props里边的回调不会再次执行。因为按照自己的想法，每次创建微应用实例，都应该执行props传递的回调接口才对。而且发现，来回切换路由，其他东西都是会销毁的，但是props里边传递的东西并没有销毁。

**Comment by gongshun** [comment]
> 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：<el-menu-item index="/iframeBox/iframeBox ">子应用</el-menu-item>，点击这个菜单就可以了

补充和更正一下：
1.  activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`

    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)

2.  对应菜单为：

    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)

3.  造成报错的主要原因是路由过渡写的有问题，需要去掉
   
    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)

![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)

**Comment by gongshun** [comment]
> 麻烦问一哈，我这边可奇怪了，在子应用里边，切出之后再切入，会再次创建微应用实例，但是props里边的回调不会再次执行。因为按照自己的想法，每次创建微应用实例，都应该执行props传递的回调接口才对。而且发现，来回切换路由，其他东西都是会销毁的，但是props里边传递的东西并没有销毁。

每次切换子应用会销毁 props 监听事件，所以每次都需要重新监听

![image](https://user-images.githubusercontent.com/29347231/102841924-cd6cfe00-4440-11eb-935e-065a93b2bb55.png)

**Comment by qq1198437442** [comment]
> > 麻烦问一哈，我这边可奇怪了，在子应用里边，切出之后再切入，会再次创建微应用实例，但是props里边的回调不会再次执行。因为按照自己的想法，每次创建微应用实例，都应该执行props传递的回调接口才对。而且发现，来回切换路由，其他东西都是会销毁的，但是props里边传递的东西并没有销毁。
> 
> 每次切换子应用会销毁 props 监听事件，所以每次都需要重新监听
> 
> ![image](https://user-images.githubusercontent.com/29347231/102841924-cd6cfe00-4440-11eb-935e-065a93b2bb55.png)

辛苦辛苦，我试试哈

**Comment by HuRuilin** [comment]
> > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> 
> 补充和更正一下：
> 
> 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
>    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> 2. 对应菜单为：
>    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
>    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> 
> ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)

感谢，辛苦，下班后，再重新试试

**Comment by lvsonghan** [comment]
> > > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> > 
> > 
> > 补充和更正一下：
> > 
> > 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
> >    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> > 2. 对应菜单为：
> >    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> > 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
> >    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> > 
> > ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)
> 
> 感谢，辛苦，下班后，再重新试试

请问下这个问题解决了吗？

**Comment by HuRuilin** [comment]
> > > > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> > > 
> > > 
> > > 补充和更正一下：
> > > 
> > > 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
> > >    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> > > 2. 对应菜单为：
> > >    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> > > 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
> > >    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> > > 
> > > ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)
> > 
> > 
> > 感谢，辛苦，下班后，再重新试试
> 
> 请问下这个问题解决了吗？

前面忙，把这事儿都给忘了，单不说，能不能解决问题，单就 第三点  去掉 <router-view :key="key" /> ，这个解决方案就没办法，我业务场景是嵌套路由，删掉这个，就没法儿渲染嵌套路由中得子路由了，答主点击菜单演示得时候，刚好点击得就不是嵌套路由，所以只是避开了问题而已，不过还是感谢答主得耐心解答

**Comment by lvsonghan** [comment]
> > > > > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> > > > 
> > > > 
> > > > 补充和更正一下：
> > > > 
> > > > 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
> > > >    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> > > > 2. 对应菜单为：
> > > >    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> > > > 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
> > > >    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> > > > 
> > > > ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)
> > > 
> > > 
> > > 感谢，辛苦，下班后，再重新试试
> > 
> > 
> > 请问下这个问题解决了吗？
> 
> 前面忙，把这事儿都给忘了，单不说，能不能解决问题，单就 第三点 去掉
> 
> ```
> <router-view :key="key" />
> ```
> 
> ，这个解决方案就没办法，我业务场景是嵌套路由，删掉这个，就没法儿渲染嵌套路由中得子路由了，答主点击菜单演示得时候，刚好点击得就不是嵌套路由，所以只是避开了问题而已，不过还是感谢答主得耐心解答

请问下那您目前是怎么处理的这种嵌套路由展示子应用呀？

**Comment by HuRuilin** [comment]
> > > > > > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> > > > > 
> > > > > 
> > > > > 补充和更正一下：
> > > > > 
> > > > > 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
> > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> > > > > 2. 对应菜单为：
> > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> > > > > 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
> > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> > > > > 
> > > > > ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)
> > > > 
> > > > 
> > > > 感谢，辛苦，下班后，再重新试试
> > > 
> > > 
> > > 请问下这个问题解决了吗？
> > 
> > 
> > 前面忙，把这事儿都给忘了，单不说，能不能解决问题，单就 第三点 去掉
> > ```
> > <router-view :key="key" />
> > ```
> > 
> > 
> > ，这个解决方案就没办法，我业务场景是嵌套路由，删掉这个，就没法儿渲染嵌套路由中得子路由了，答主点击菜单演示得时候，刚好点击得就不是嵌套路由，所以只是避开了问题而已，不过还是感谢答主得耐心解答
> 
> 请问下那您目前是怎么处理的这种嵌套路由展示子应用呀？

我也只是做简单的技术调研，公司目前不大可能轻易引进新的技术概念，所以也是浅尝辄止，没有再继续深入。

**Comment by gongshun** [comment]
我没有叫你去掉嵌套路由 :joy:

可能是我的截图误导了你，我只是让你去掉路由过渡而已。路由嵌套没变，去掉路由过渡（transition标签）就行了

实际上路由过渡也不是不能用，有几个特殊的过渡效果会报错，其他的都能用。

![image](https://user-images.githubusercontent.com/29347231/104576819-a4ccd280-5693-11eb-8272-2e4152af3016.png)

**Comment by lvsonghan** [comment]
> 我没有叫你去掉嵌套路由 😂
> 
> 可能是我的截图误导了你，我只是让你去掉路由过渡而已。路由嵌套没变，去掉路由过渡（transition标签）就行了
> 
> 实际上路由过渡也不是不能用，有几个特殊的过渡效果会报错，其他的都能用。
> 
> ![image](https://user-images.githubusercontent.com/29347231/104576819-a4ccd280-5693-11eb-8272-2e4152af3016.png)

您发的图看不到啊

**Comment by lvsonghan** [comment]
> > > > > > > 不要把菜单和路由用一份数据，路由注册不变的话，activeRule 应该是 /iframeBox/iframeBox，然后新增一个菜单：子应用，点击这个菜单就可以了
> > > > > > 
> > > > > > 
> > > > > > 补充和更正一下：
> > > > > > 
> > > > > > 1. activeRule 可以是 /iframeBox/iframeBox，但是如果再加一个子应用，就不好处理，建议是 `/iframeBox/iframeBox/app1`
> > > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840474-f049e300-443d-11eb-963e-052ddd08501c.png)
> > > > > > 2. 对应菜单为：
> > > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840530-11aacf00-443e-11eb-8a1a-89a6233205e4.png)
> > > > > > 3. 造成报错的主要原因是路由过渡写的有问题，需要去掉
> > > > > >    ![image](https://user-images.githubusercontent.com/29347231/102840650-49197b80-443e-11eb-8725-3269bd2351e0.png)
> > > > > > 
> > > > > > ![2](https://user-images.githubusercontent.com/29347231/102840601-32732480-443e-11eb-9557-71ffcd699e81.gif)
> > > > > 
> > > > > 
> > > > > 感谢，辛苦，下班后，再重新试试
> > > > 
> > > > 
> > > > 请问下这个问题解决了吗？
> > > 
> > > 
> > > 前面忙，把这事儿都给忘了，单不说，能不能解决问题，单就 第三点 去掉
> > > ```
> > > <router-view :key="key" />
> > > ```
> > > 
> > > 
> > > ，这个解决方案就没办法，我业务场景是嵌套路由，删掉这个，就没法儿渲染嵌套路由中得子路由了，答主点击菜单演示得时候，刚好点击得就不是嵌套路由，所以只是避开了问题而已，不过还是感谢答主得耐心解答
> > 
> > 
> > 请问下那您目前是怎么处理的这种嵌套路由展示子应用呀？
> 
> 我也只是做简单的技术调研，公司目前不大可能轻易引进新的技术概念，所以也是浅尝辄止，没有再继续深入。

为什么我们公司要深入用了，愁人

**Comment by andyhuai** [comment]
> 我没有叫你去掉嵌套路由 😂
> 
> 可能是我的截图误导了你，我只是让你去掉路由过渡而已。路由嵌套没变，去掉路由过渡（transition标签）就行了
> 
> 实际上路由过渡也不是不能用，有几个特殊的过渡效果会报错，其他的都能用。
> 
> ![image](https://user-images.githubusercontent.com/29347231/104576819-a4ccd280-5693-11eb-8272-2e4152af3016.png)

路由和菜单在一起就不行吗？因为菜单路由是后端下发的，所以一起处理了

**Comment by PickACatName** [comment]
请问在这个例子中，微应用如果也为history模式应该怎么配置？

**Comment by YuhuiRainie** [comment]
> 很明显你的路由不对啊，当你这样配置路由时，你菜单和 `activeRule` 应该是 `/iframeBox/iframeBox`
> 
> ![image](https://user-images.githubusercontent.com/29347231/102778609-dcff2f00-43cd-11eb-92dd-4b44c39a768f.png)
> 
> https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8
你好，按照官方的教程，我配置出了这样的问题，


element-ui.common.js?5c96:3378 RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at matchRoute (vue-router.esm.js?8c4f:1604)
    at match (vue-router.esm.js?8c4f:1486)
    at redirect (vue-router.esm.js?8c4f:1546)
    at _createRoute (vue-router.esm.js?8c4f:1585)
    at match (vue-router.esm.js?8c4f:1487)
    at redirect (vue-router.esm.js?8c4f:1546)
    at _createRoute (vue-router.esm.js?8c4f:1585)

这是我的主应用vue/router/index.js
` {
                    path:'/react/*',
                    name:'react',
                    component:()=>import('@/components/page/React.vue'),
                    meta:{
                        title: 'react app'
                    },`

这是我主应用vue 的main.js
`const getActiveRule = hash => location => location.hash.startsWith(hash);
const apps = [
    {
        name:'reactApp',
        entry:'http://localhost:10000',
        container:'#react',
        activeRule:getActiveRule('#/react'),
        props: {
            slogan: 'Hello Qiankun'
        }
    }
]`

这是我子应用react
`function App({props}) {                                                    
   const reciever = props                                                  
    const BASE_NAME = window.__POWERED_BY_QIANKUN__ ? "/react" : "";       
  return (                                                                 
    <div className="App">                                                  
         <HashRouter basename={BASE_NAME}>                                 
            <Header />                                                     
            <Suspense fallback={null}>                                     
                <Switch>                                                   
                    <Route exact path='/' component={Home} />              
                    <Route exact path='/app1' component={App1} />          
                    <Route exact path='/app2' component={App2} />          
                </Switch>                                                  
            </Suspense>                                                    
         </HashRouter>                                                     
    </div>                                                                 
  );                                                                       
}                                                                          
                                                                           
export default App;                                                        
                                                                           `

**Comment by gongshun** [comment]
> ![image](https://user-images.githubusercontent.com/29347231/112566265-98928d80-8e19-11eb-81d3-ac85195c5906.png)

@YuhuiRainie 这应该是你自己写了路由钩子，循环跳转页面导致的

**Comment by YuhuiRainie** [comment]
> > ![image](https://user-images.githubusercontent.com/29347231/112566265-98928d80-8e19-11eb-81d3-ac85195c5906.png)
> 
> @YuhuiRainie 这应该是你自己写了路由钩子，循环跳转页面导致的

![image](https://user-images.githubusercontent.com/48782788/112585398-d5787780-8e4d-11eb-8e26-145e6687c5c7.png)

在基座里面把react子应用的所有的路由都写完才没有bug，
我没有加router hooks.

**Comment by limzgiser** [comment]
这个问题解决了嘛？我也是在子路由中配置子应用，我也是第一次进入没问题，退出登录，再进来就报这个错误。需要刷新登录页面，在登陆就可以。

**Comment by limzgiser** [comment]
这个问题解决了嘛？我也是在子路由中配置子应用，我也是第一次进入没问题，退出登录，再进来就报这个错误。需要刷新登录页面，在登陆就可以。 @HuRuilin @gongshun

**Comment by gongshun** [comment]
> 这个问题解决了嘛？我也是在子路由中配置子应用，我也是第一次进入没问题，退出登录，再进来就报这个错误。需要刷新登录页面，在登陆就可以。 @HuRuilin @gongshun

https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-while-xxx-mounting

**Comment by rida233** [comment]
同样存在这个问题，在chrome浏览器中没问题，在IE11浏览器中，用官方给的兼容方法可以打开，但是第二次加载同一个子应用是会报这个错误，刷新浏览器就可以正常加载。已检查路由没有过渡动画 @gongshun @HuRuilin

**Comment by gongshun** [comment]
> 同样存在这个问题，在chrome浏览器中没问题，在IE11浏览器中，用官方给的兼容方法可以打开，但是第二次加载同一个子应用是会报这个错误，刷新浏览器就可以正常加载。已检查路由没有过渡动画 @gongshun @HuRuilin

另外开一个issue，并提供复现仓库。当前issue的问题已解决

**Comment by Young0510** [comment]
感谢这个issuse，我开始遇到了`Target container with #container not existed while xxx mounting!` 这个报错   通过官方常见问题去掉路由过渡解决了。我也是嵌套路由
![image](https://user-images.githubusercontent.com/44191856/116501555-a5584480-a8e3-11eb-904c-26fa2c78c995.png)
官方回答的没问题
![image](https://user-images.githubusercontent.com/44191856/116501608-d0429880-a8e3-11eb-82e0-0eeb9baffb97.png)确实activeRule最好是你要访问的path
再次是遇到第一次刷新能加载微应用第二次访问不到的问题，通过控制台打印发现微应用进了两次mounted，发现是子应用写了重定向导致主应用路由变化重新挂载了
![image](https://user-images.githubusercontent.com/44191856/116501791-5232c180-a8e4-11eb-9c48-aeb32bc10ee0.png)
最后解决要么把重定向去掉，子应用留下path: “/”（不太合理）；要么在主应用预先设置子应用路由
![image](https://user-images.githubusercontent.com/44191856/116501959-c9685580-a8e4-11eb-8304-09eb00c78f13.png)
最后，感谢qiankun团队，希望未来能支持vite
