### ISSUE TITLE
[Bug]Vue项目中 router-view 无法正常显示

### ISSUE THREAD

**Issue by Veath** [umijs/qiankun#117]
## What happens?

* Portal项目中引入Element-ui，Children项目中也引入了Element-ui。
* Portal项目使用el-container组件或者任何提供了slot的组件。
* 在slot中放router-view组件
*  **Portal跳转Children A页面后（正常显示）, 再跳转Children B, 无法正常显示**

## 最小可复现仓库
https://github.com/Veath/micro-frontend-qiankun

## 复现步骤，错误日志以及相关配置

* 启动Portal、Micor-A项目
*  依次点击导航跳转 home | micro-a | micro-a-about 
* micor-a-about 显示空白

## 临时解决办法
通过CDN引入，但有版本控制的情况下就.....

**Comment by wusp1994** [comment]
可以参照我的微前端解决方案qiankun测试用例，主应用及子应用均为vue-cli 3 构建 https://github.com/wusp1994/qiankunTestByWu.git

**Comment by Veath** [comment]
定位出问题了。
并不是slot造成的问题。
不能同时在portal 和 subproject 同时使用router-view 组件。
**原因是 router-view 会触发route watcher** 
portal 和 subproject 先后都会触发 watcher, protal会重置 v-html 指令的内容，导致subproject 拿不到重置前的 $el

**Comment by screetBloom** [comment]
咨询一下，有什么可行方案去解决吗
@Veath
