### ISSUE TITLE
[Bug]微应用js中用var声明的全局变量或function全局声明函数，无法暴露在微应用作用域window.proxy上，导致使用这些变量时报错：ReferenceError: xxx is not defined

### ISSUE THREAD

**Issue by qtpalmtop** [umijs/qiankun#1170]
## What happens?

除了 `SnapshotSandbox` 模式，微应用 `js` 中用**var声明的全局变量**或**function全局声明函数**，比如在 `a.js` 中 `var message = 'hello qiankun';function sayHello() { alert(message); }` 在 `b.js` 中调用 `message` 和 `sayHello`就会报错 `Uncaught ReferenceError: message is not defined` `Uncaught ReferenceError: sayHello is not defined`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

[复现仓库地址](https://github.com/qtpalmtop/qiankun/tree/bug/global-variable-declaration)

## How To Reproduce

修改 `umijs/qiankun` 中的 `examples/purehtml` ，新增 `hello.js` 、`sayHello.js` 并在`html`中导入这些 `js`

**Steps to reproduce the behavior:** 1. **examples/purehtml/index.html**
![example-1.png](http://www.chuantu.vip/2020/12/21/1968861a1c920.png)

**Steps to reproduce the behavior:** 2. `examples/purehtml/hello.js` 用 `var` 和 `function` 全局声明变量 `message` 和函数 `sayHello`
![example-2.png](http://www.chuantu.vip/2020/12/21/0798f50f2224b.png)

**Steps to reproduce the behavior:** 3. `examples/purehtml/sayHello.js` 调用hello.js中声明的变量 `message` 和函数 `sayHello`
![example-3.png](http://www.chuantu.vip/2020/12/21/3ee77e09dfff4.png)

**Steps to reproduce the behavior:** 4. `examples/purehtml` 中运行 `npm run start`，独立运行时能正常访问 **var 和 function 全局声明的变量和函数**
![example-4.png](http://www.chuantu.vip/2020/12/21/502c9b1ce9036.png)

**Steps to reproduce the behavior:** 5. `examples/main` 中运行 `npm run start:multiple`，启动基座运行上面的微应用，报错如下图，识别 `hello.js` 中声明的变量 `message` 和函数 `sayHello` 为 `undefined`，其原因在于 `Proxy` 中通过 **var 和 function 全局声明的变量和函数**无法触发 `proxy` 的 `set` 钩子函数，导致未能将变量设置到微应用作用域 `window.proxy` 中。
![example-5.png](http://www.chuantu.vip/2020/12/21/27e73a65311d1.png)
![example-6.png](http://www.chuantu.vip/2020/12/21/7219c087258ca.png)

**Expected behavior:** 6. `examples/purehtml/hello.js` 中只有通过红框中的方式声明全局变量和函数声明时，微应用作用域 `window.proxy` 能**正常识别**这些变量和函数，并且运行基座能**达到预期结果**
![example-8.png](http://www.chuantu.vip/2020/12/21/14ee4bd56da02.png)
![example-7.png](http://www.chuantu.vip/2020/12/21/160d73b885d10.png)

## Context

- **qiankun Version**: 2.3.4
- **Platform Version**: 
- **Browser Version**: Chrome 87.0.4280.88（正式版本） (x86_64)

**Comment by kuitos** [comment]
SnapshotSandbox 不支持这种场景

**Comment by qtpalmtop** [comment]
@kuitos 既然ProxySandBox也没办法处理这个问题，那我们还是内部自己规范写法吧。

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/380 同样的问题

**Comment by kuitos** [comment]
ProxySandBox 应该是可以的吧？

**Comment by poppyLuo** [comment]
> ProxySandBox 应该是可以的吧？

不支持
