### ISSUE TITLE
[BUG] getTargetValue的缓存机制导致window上函数的this指向错误

### ISSUE THREAD

**Issue by Orange-C** [umijs/qiankun#1174]
## What happens?
![image](https://user-images.githubusercontent.com/8469262/102879082-35910380-4484-11eb-9dc9-037ebe246d94.png)
![image](https://user-images.githubusercontent.com/8469262/102879058-2d38c880-4484-11eb-973b-7ed61e8209cd.png)

getTargetValue和isConstructable的缓存机制导致获取window上的某些函数时，在应该返回没有bind过的函数时返回了bind过的函数。复现条件具体细节不明，但是在我们业务中使用jsplumb的地方就会出现这个bug，我已经在qiankun的example里面复现了这个case。这个bug在我们使用2.0.24的qiankun时是没有的，我在排查后发现了这两处改动，我目前是在本地直接去除了缓存逻辑，希望尽快修复。

## Mini Showcase Repository(REQUIRED)

https://github.com/Orange-C/qiankun
error-case 分支

## How To Reproduce

1. yarn
2. yarn example:install
3. yarn example:start
4. 打开react16的页面

## Context

- **qiankun Version**: 2.3.2
- **Platform Version**: windows10
- **Browser Version**: chrome

**Comment by Orange-C** [comment]
@kuitos 之前在群里反馈过的问题

**Comment by weihaonan** [comment]
请问如何去除本地缓存逻辑

**Comment by Orange-C** [comment]
> 请问如何去除本地缓存逻辑

注释掉两个图中红框的内容即可，请问你也遇到这个问题了吗？

**Comment by weihaonan** [comment]
@Orange-C 对  项目中用的jsplumb

**Comment by direcee** [comment]
> @Orange-C 对 项目中用的jsplumb

请问有解决方案么，我也遇到了这个问题

**Comment by zhenxin111** [comment]
同样的问题

**Comment by henryxie2093** [comment]
同样在引用 jsplumb是出现了这个问题，一个比较tricky的做法：

子应用中将jsplumb 在webpack中 externals 引入
在壳应用中将jsplumb通过cdn引入

**Comment by HiNaruta** [comment]
> 同样在引用 jsplumb是出现了这个问题，一个比较tricky的做法：
> 
> 子应用中将jsplumb 在webpack中 externals 引入
> 在壳应用中将jsplumb通过cdn引入

可以详解一下, 上个代码什么的吗?

**Comment by foxFallingSkies** [comment]
可解决了。。头疼这个问题哦

**Comment by foxFallingSkies** [comment]
4个月了。。官方可解决了。。。。

**Comment by foxFallingSkies** [comment]
看了下。现在的版本是1.5.。。那到底是用2.4还是用1.5

**Comment by direcee** [comment]
这版本号更新的有问题吧...

**Comment by kuitos** [comment]
这个修复还没发版呢，看版本发布时间就知道了😑

1.x 我们也在维护，所以 github release log 上有发布记录，看 npm dist tag 去 npm 仓库 https://www.npmjs.com/package/qiankun

**Comment by foxFallingSkies** [comment]
> 这个修复还没发版呢，看版本发布时间就知道了😑
> 
> 1.x 我们也在维护，所以 github release log 上有发布记录，看 npm dist tag 去 npm 仓库 https://www.npmjs.com/package/qiankun

具体什么时候会在2.x版本上上上去，可有计划
