### ISSUE TITLE
[Feature Request] 在沙盒里面对 document 也做代理会不会更好？

### ISSUE THREAD

**Issue by kawhi66** [umijs/qiankun#1175]
## Background

大概从 qiankun@2.1.0 以后，以 proxySandbox 作为默认的沙盒，并且默认开启 strickGlobal 特性，基于 with 语句执行子应用脚本。我们的测试结果显示，在这种模式下，单纯的脚本执行性能还可以，但是一旦涉及到操作 DOM 时，性能就会严重下降，大概会差 10 倍以上。

## Mini Showcase Repository

[https://gitee.com/kawhi66/test/tree/master/qiankun@2.3.4](https://gitee.com/kawhi66/test/tree/master/qiankun@2.3.4)

## Proposal

一个想法，既然沙盒可以提供独立的 window 实例，是否也应该提供独立的 document 实例 ？

## Additional context

我们做了简单的验证，在 import-html-entry 里面做如下的修改：

```js
// src/index.js
function getExecutableScript(scriptSrc, scriptText, proxy, strictGlobal) {
	const sourceUrl = isInlineCode(scriptSrc) ? '' : `//# sourceURL=${scriptSrc}\n`;

	// 通过这种方式获取全局 window，因为 script 也是在全局作用域下运行的，所以我们通过 window.proxy 绑定时也必须确保绑定到全局 window 上
	// 否则在嵌套场景下， window.proxy 设置的是内层应用的 window，而代码其实是在全局作用域运行的，会导致闭包里的 window.proxy 取的是最外层的微应用的 proxy
	const globalWindow = (0, eval)('window');
	globalWindow.proxy = proxy;
	// TODO 通过 strictGlobal 方式切换切换 with 闭包，待 with 方式坑趟平后再合并
	return strictGlobal
                // 修改的地方在这里，with 语句将 document 也加进去
		? `;(function(window, self, document){with(window, document){;${scriptText}\n${sourceUrl}}}).bind(window.proxy)(window.proxy, window.proxy, window.document);`
		: `;(function(window, self){;${scriptText}\n${sourceUrl}}).bind(window.proxy)(window.proxy, window.proxy);`;
}
```

测试结果显示，在操作 DOM 时，性能会提升不少，大概会好 60%，虽然还是会慢，但会好很多。

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/846

**Comment by kawhi66** [comment]
> #846

嗯，我相信 qiankun 一定有足够的理由这么做，但是 with 语句造成的性能问题是真实存在的，而且比较严重

**Comment by liubiggun** [comment]
> > #846
> 
> 嗯，我相信 qiankun 一定有足够的理由这么做，但是 with 语句造成的性能问题是真实存在的，而且比较严重

当子应用懒加载一个大的模块时，如果涉及到dom操作会导致明细卡顿，fps直接为0了，  @kawhi66  请问你们也是这种情况吗？

**Comment by kawhi66** [comment]
> > > #846
> > 
> > 
> > 嗯，我相信 qiankun 一定有足够的理由这么做，但是 with 语句造成的性能问题是真实存在的，而且比较严重
> 
> 当子应用懒加载一个大的模块时，如果涉及到dom操作会导致明细卡顿，fps直接为0了， @kawhi66 请问你们也是这种情况吗？

嗯，可能是类似的，我们的情况倒不至于造成页面假死，但性能确实很差

**Comment by kuitos** [comment]
给个代码例子吧，什么操作会导致性能大幅降低

document 加到 with 里肯定是不行的，太容易误伤，比如 window 上也有个变量 title，那么我这么写，到底应该取哪个呢

```js
with(window, document) {
  console.log(title)
}
```

**Comment by kawhi66** [comment]
> 给个代码例子吧，什么操作会导致性能大幅降低
> 
> document 加到 with 里肯定是不行的，太容易误伤，比如我尝试去取 title 这个全局变量(window 上不一定有)，那么我这么写，得到的值就永远是 true 了
> 
> ```js
> with(window, document) {
>   console.log(title !== undefined)
> }
> ```

嗯，我补充一下

**Comment by kawhi66** [comment]
> 给个代码例子吧，什么操作会导致性能大幅降低
> 
> document 加到 with 里肯定是不行的，太容易误伤，比如我尝试去取 title 这个全局变量(window 上不一定有)，那么我这么写，得到的值就永远是 true 了
> 
> ```js
> with(window, document) {
>   console.log(title !== undefined)
> }
> ```

示例仓库地址 https://gitee.com/kawhi66/test/tree/master/qiankun@2.3.4

**Comment by xiaoLus** [comment]
> > > #846
> > 
> > 
> > 嗯，我相信 qiankun 一定有足够的理由这么做，但是 with 语句造成的性能问题是真实存在的，而且比较严重
> 
> 当子应用懒加载一个大的模块时，如果涉及到dom操作会导致明细卡顿，fps直接为0了， @kawhi66 请问你们也是这种情况吗？

我这里也是，一旦涉及dom操作。fps直接到个位数。40fps -> 4fps

**Comment by BrianWalkerToretto** [comment]
我有一个很好的思路，你根据你的想法修改来的。性能很快，也没有了with(window, document)产生的问题
[https://github.com/umijs/qiankun/issues/1555](https://github.com/umijs/qiankun/issues/1555)

**Comment by wudith** [comment]
这个问题我们也遇到了，官方不打算修复了吗

**Comment by yiludege** [comment]
这个可以参考京东的方案：

**Comment by yiludege** [comment]
这个可以参考京东的方案：

**Comment by yiludege** [comment]
这个可以参考京东 micro-app的方案：

将需要的全局变量缓存起来，这样在大量的dom操作情况下，不用每次从with作用域去读，省去了大量的查找时间，性能接近原生了

`;(function(proxyWindow){with(proxyWindow){(function(${globalKeyToBeCached}){;${code}\n}).call(proxyWindow,${globalKeyToBeCached})}})(proxyWindow);`

const globalKeyToBeCached = 'window,self,globalThis,Array,Object,String,Boolean,Math,Number,Symbol,Date,Promise,Function,Proxy,WeakMap,WeakSet,Set,Map,Reflect,Element,Node,Document,RegExp,Error,TypeError,JSON,isNaN,parseFloat,parseInt,performance,console,decodeURI,encodeURI,decodeURIComponent,encodeURIComponent,location,navigator,undefined'

**Comment by lishaobos** [comment]
> 这个可以参考京东 micro-app的方案：
> 
> 将需要的全局变量缓存起来，这样在大量的dom操作情况下，不用每次从with作用域去读，省去了大量的查找时间，性能接近原生了
> 
> `;(function(proxyWindow){with(proxyWindow){(function(${globalKeyToBeCached}){;${code}\n}).call(proxyWindow,${globalKeyToBeCached})}})(proxyWindow);`
> 
> const globalKeyToBeCached = 'window,self,globalThis,Array,Object,String,Boolean,Math,Number,Symbol,Date,Promise,Function,Proxy,WeakMap,WeakSet,Set,Map,Reflect,Element,Node,Document,RegExp,Error,TypeError,JSON,isNaN,parseFloat,parseInt,performance,console,decodeURI,encodeURI,decodeURIComponent,encodeURIComponent,location,navigator,undefined'

对于上面提出的测试仓库，主应用中性能差距 10 倍，加入上述缓存，差距还有 5 倍，如果加入 document 缓存，性能和子应用无差异，micro-app 没有加入 document，是因为之前版本没有做 proxyDocument

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
