### ISSUE TITLE
开启strictStyleIsolation的ShadowDOM导致angular子应用样式丢失

### ISSUE THREAD

**Issue by wudith** [umijs/qiankun#1176]
配置开启strictStyleIsolation后，导致加载的angular子应用的原有样式丢失，请教这个配置对angular子应用无效不能使用吗？还是需要有其他补充配置？

start({
  sandbox:{
    strictStyleIsolation:true
  } 
});

复现方式直接官网例子的start方法加上此配置，访问angular9子应用即可

**Comment by gongshun** [comment]
这里有两个问题：
1.  `ShadowDOM` 导致 `dom` 不通，`angular` 获取不到容器里面的 `<app-root>`，而 `single-spa-angualr` 插件会给 `body` 里面插入一个`<app-root>`，导致的问题就是实例化时，实例化到 `single-spa-angualr` 插件加的 `<app-root>`里面了，样式却在在容器里面，所以样式不生效。

![image](https://user-images.githubusercontent.com/29347231/102952081-45066000-4509-11eb-9ab5-c361aa7707c7.png)

 `<app-root>` 如果能限制查找范围，就没有这个问题了，实际上这样不行。

![image](https://user-images.githubusercontent.com/29347231/102952787-ec37c700-450a-11eb-91cb-91f8bc2f2cab.png)

2.  `ShadowDOM` 的适用范围很小，隔离效果虽好，但是有一大堆问题，例如字体文件，svg，插入到 body 的弹窗样式等

**Comment by wudith** [comment]
> 这里有两个问题：
> 
> 1. `ShadowDOM` 导致 `dom` 不通，`angular` 获取不到容器里面的 `<app-root>`，而 `single-spa-angualr` 插件会给 `body` 里面插入一个`<app-root>`，导致的问题就是实例化时，实例化到 `single-spa-angualr` 插件加的 `<app-root>`里面了，样式却在在容器里面，所以样式不生效。
> 
> ![image](https://user-images.githubusercontent.com/29347231/102952081-45066000-4509-11eb-9ab5-c361aa7707c7.png)
> 
> `<app-root>` 如果能限制查找范围，就没有这个问题了，实际上这样不行。
> 
> ![image](https://user-images.githubusercontent.com/29347231/102952787-ec37c700-450a-11eb-91cb-91f8bc2f2cab.png)
> 
> 1. `ShadowDOM` 的适用范围很小，隔离效果虽好，但是有一大堆问题，例如字体文件，svg，插入到 body 的弹窗样式等

谢谢大佬

**Comment by Aurora04** [comment]
请问 怎么解决的呢 大佬能说一下么
