### ISSUE TITLE
You are loading the CommonJS build of React Router on a page that is already running the ES modules build, so things won't work right.

### ISSUE THREAD

**Issue by lxkun** [umijs/qiankun#1181]
## What happens?
1. 当主应用为umi项目，通过umi-qiankun插件注册子应用。
2.子应用是webpack 打包的react项目，路由使用的是 react-router-dom。
3.当启动加载时发现控制台报错。
![image](https://user-images.githubusercontent.com/25296719/103081873-db26ad00-4613-11eb-9efe-997e3c82e378.png)

通过搜索发现是因为路由加载不一致引起的，是存在这个bug还是需要配置有问题。
![image](https://user-images.githubusercontent.com/25296719/103082089-4cfef680-4614-11eb-85b9-2596cccb8037.png)

https://github.com/ReactTraining/react-router/issues/6361

## Context

- **qiankun Version**: ^2.3.4
- **Platform Version**: mac 11.0.1
- **Browser Version**: chrome 87.0.4280.88

**Comment by gongshun** [comment]
duplicated with https://github.com/umijs/qiankun/issues/1011 这种问题自己百度吧，https://github.com/supasate/connected-react-router/issues/292
