### ISSUE TITLE
qiankun  http嵌套https(https嵌套http)的问题

### ISSUE THREAD

**Issue by Self-taught-lian** [umijs/qiankun#1182]
qiankun  主应用http/https嵌套子应用https/http,直接报错。

**Comment by kuitos** [comment]
https 站点本身就不允许引用 http 资源，这个跟 qiankun 没关系

**Comment by gongshun** [comment]
> https 站点本身就不允许引用 http 资源

Chrome 86才阻止的，之前版本是允许的 :joy:
