### ISSUE TITLE
[Bug]umi3.x + @umijs/plugin-qiankun2.18.3 子应用react组件报内存泄漏警告

### ISSUE THREAD

**Issue by 942368681** [umijs/qiankun#1186]
#### 问题描述
第一次点击子应用tab进入子应用后，点击浏览器回退回到主应用，react组件报错，报错信息如下：
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Router (created by RouterComponent)
    in RouterComponent
    in Provider (created by _DvaContainer)
    in _DvaContainer
    in Unknown
    in Unknown`
再次点击该子应用tab进入该子应用，依然报错，报错信息如下：
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in _default (at Provider.tsx:30)
    in Unknown`
然后再次循环上述操作（进出该子应用）就不会再报错了。
#### 问题分析
该报错信息是react组件卸载之后仍存在更新状态的操作导致的警告，但是我的子应用没有更新state或store的操作，就是一个简单的函数组件，无状态。
#### 版本信息
主子应用都是以下版本

"umi": "^3.3.3"
"@umijs/plugin-qiankun": "^2.18.3"
#### 可复现该问题的代码仓库
https://github.com/942368681/umi-qiankun-demo

### 望解答，谢谢！

**Comment by qiutian00** [comment]
刚开始用，遇到上述相同问题 `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. in _default (at Provider.tsx:30) in Unknown`。

**Comment by 942368681** [comment]
> 刚开始用，遇到上述相同问题 `devScripts.js:6523 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`。

应该是js隔离的问题

**Comment by qiutian00** [comment]
> > 刚开始用，遇到上述相同问题 `devScripts.js:6523 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`。
> 
> 应该是js隔离的问题

有参考地方可以解决么？ 
![4R_ }6$LDG3EJRTFLGC5KM9](https://user-images.githubusercontent.com/24382500/122743405-89f13080-d2b9-11eb-966a-2e02cd46edb9.png)

**Comment by 942368681** [comment]
> > > 刚开始用，遇到上述相同问题 `devScripts.js:6523 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`。
> > 
> > 
> > 应该是js隔离的问题
> 
> 有参考地方可以解决么？
> ![4R_ }6$LDG3EJRTFLGC5KM9](https://user-images.githubusercontent.com/24382500/122743405-89f13080-d2b9-11eb-966a-2e02cd46edb9.png)

目前没有解决，但部署后并不会有该问题，先这样吧

**Comment by qiutian00** [comment]
![)M14SEALAJW$TP)X%O~E)~P](https://user-images.githubusercontent.com/24382500/122848099-78506d00-d33b-11eb-816a-b84f93705ab8.png)

**Comment by 942368681** [comment]
随时关注下这个吧

**Comment by 942368681** [comment]
随时关注下这个吧

**Comment by 942368681** [comment]
随时关注下这个吧
https://github.com/umijs/plugins/issues/494
