### ISSUE TITLE
子应用使用webpack5的dev-server时，qiankun会报错找不到lifecycle

### ISSUE THREAD

**Issue by nossika** [umijs/qiankun#1191]
## What happens?

子应用使用webpack5，启动webpack-dev-server。qiankun在加载子应用时，会报错You need to export lifecycle functions。

若切换到webpack4.44.2，启动webpack-dev-server，是正常的。

若使用webpack5，先build成静态资源再加载，也是正常的。

仅在使用webpack5且使用webpack-dev-server时出现。

## 最小可复现仓库

已经写了个最简可复现的demo。

https://github.com/nossika/qiankun-demo-webpack5-dev

子应用：

![image](https://user-images.githubusercontent.com/17478591/103355596-92766480-4ae9-11eb-8f32-74cb1b90b3c7.png)

webpack配置：

![image](https://user-images.githubusercontent.com/17478591/103355652-bc2f8b80-4ae9-11eb-8f89-9ba0d6dc949d.png)

## 复现步骤，错误日志以及相关配置

```
npm i
npm run dev:main
npm run dev:sub
```

然后打开 http://localhost:8080 ，点击load，即可复现。

![image](https://user-images.githubusercontent.com/17478591/103355233-b7b6a300-4ae8-11eb-9986-420ca5238267.png)

但如果把webpack版本改为4.44.2，其他都不变。

```
npm i webpack@4
```

再重复上述步骤，则一切正常。

![image](https://user-images.githubusercontent.com/17478591/103355321-ea609b80-4ae8-11eb-98fd-dfc56cf3eee7.png)

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1092 重复了, 在 https://github.com/umijs/qiankun/issues/1092 中追踪解决办法，这个先关闭了
