### ISSUE TITLE
关于使用setDefaultMountApp之后,主应用路由跳转,会跳转到默认微应用的问题

### ISSUE THREAD

**Issue by matteao03** [umijs/qiankun#1194]
## 问题

- 当主应用中设置了默认微应用`setDefaultMountApp`, 会在主应用的切换中,发生跳转异常, 会跳转到默认微应用(只在第一次进入时); 
- 当主应用不设置默认微应用`setDefaultMountApp`, 则路由一切正常

## 最小复现仓库
[qiankun-test 问题复现仓库: https://github.com/matteao03/qiankun-test](https://github.com/matteao03/qiankun-test)

### 路由错误,跳转默认微应用的的问题
- 项目启动后, 默认会进入`/#/login`, 点击 "登录" 按钮
- 此时位于 `/#/home`页面, 点击 "手册" 按钮
- 预期进入 `/#/guide` 页面, 却进入了 `/#/login`  (推测是 `setDefaultMountApp`的影响)

### 重复以上步骤,路由又恢复正常的问题
- 重复1,2 步骤, 此后正常进入 `/#/guide`(路由又恢复正常了)
- 后续路由切换,一切正常. 

**如果想再次复现,需要在/#/layout/data 点击"退出" 按钮 (或者清除登录痕迹, 即清除localStorage), 然后在 '/#/login/ ' 页面刷新浏览器.'**

## 环境
- **qiankun**: 2.3.5
- **Platform Version**: 8.11.4 及 之上 (我的nodejs 版本是:8.11.4)
- **浏览器版本**: chrome (我的浏览器是chrome 最新版本)

**Comment by esymeptoo** [comment]
提供一个简单的解决方案 给你的主应用也提供一个baseUrl 然后初始化乾坤的时候判断一下 当前的url是否处于主应用的路由内 如果是就不用设置默认子应用 如果不是再进行设置即可

**Comment by kuitos** [comment]
By design, setDefaultMountApp 的作用就是当没有匹配到任何微应用时，会跳转到你设置的微应用

**Comment by githuber0007** [comment]
`0 const routes = [`
`1　{`
`2　　 path: '/',`
`3　　 redirect: '/home'`
`4　 },`
`5　 {`
`6　　 path: '/home',`
`7　　 name: 'home',`
`8　　 component: () => import('@/views/Home.vue'),`
`9　　 children: [`
`10　　　 {`
`11　　　　 path: '',`
`12　　　　 component: () => import('@/views/HomeContent.vue')`
`13　　　 }`
`14　　 ]`
`15　 },`
`16　 {`
`17　　 path: '/guide',`
`18　　 name: 'guide',`
`19　　 component: () => import('@/views/Guide.vue')`
`20　 }`
`21 ]`

* 你的路由表`/main/src/router/index.js`里面定义根路径——`/ `匹配的组件为异步组件（以上第8行），修改为同步组件就可以正常跳转了。

* 可能是因为Vue异步组件和setDefaultMountApp里面的事件触发有异步时机上的冲突，不可以在需要跳转默认微应用的路由地址下使用异步组件，只能等官方提出正式的解决方案。
