### ISSUE TITLE
加载子应用正常，但主应用切换路由，子应用不跳转，浏览器返回前进可触发子应用跳转

### ISSUE THREAD

**Issue by jingshanchen** [umijs/qiankun#1199]
## What happens?

主应用是vue2，首页有2个路由，分别对应子应用（react、umijs）的2个路由：
<router-link to="/child-app/index">子应用index</router-link> 
<router-link to="/child-app/about">子应用about</router-link>
主子应用路由都是hash模式

首次点击子应用index路由，能正常加载子应用index页面；
再点击子应用about路由，却无法正常跳转，页面还是子应用index，可浏览器url hash值已更换成about；
后续对浏览器前进返回键操作，这可以正常跳转：
浏览器回退，跳转至子应用index正常，浏览器前进，hash为about，页面正常跳转为about

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.

代码示例地址
https://github.com/jingshanchen/qiankun-example.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.3.5
- **Platform Version**: macOs
- **Browser Version**:chrome  87
- **vue Version**:v2.X
- **umijs Version**:3.3.3
- **umijs/plugin-qiankun Version**:2.18.3

https://user-images.githubusercontent.com/23496081/103722804-c0890680-500b-11eb-8b58-ddf39718dcdf.mp4

**Comment by gongshun** [comment]
react-router 的 hash 模式特性如此，主应用直接跳转路由，子应用不会响应 :joy: history 模式就可以了

**Comment by jingshanchen** [comment]
> react-router 的 hash 模式特性如此，主应用直接跳转路由，子应用不会响应 😂 history 模式就可以了

感谢答复！另外请教一下，子应用history模式，主应用可以是hash模式吗？我试了一下貌似不行。

**Comment by gongshun** [comment]
> 子应用history模式，主应用可以是hash模式吗？我试了一下貌似不行。

![image](https://user-images.githubusercontent.com/29347231/103747952-5c336a80-503e-11eb-9adb-15117230bc23.png)

**Comment by jingshanchen** [comment]
> > 子应用history模式，主应用可以是hash模式吗？我试了一下貌似不行。
> 
> ![image](https://user-images.githubusercontent.com/29347231/103747952-5c336a80-503e-11eb-9adb-15117230bc23.png)
你这个截图，网络原因我看不到。烦请发文字哈哈，跪谢了。

**Comment by gongshun** [comment]
https://juejin.cn/post/6856569463950639117#heading-23

**Comment by jingshanchen** [comment]
> https://juejin.cn/post/6856569463950639117#heading-23

非常感谢！

**Comment by nondanee** [comment]
试试在主应用里监听路由变化，手动触发一个 hashchange 事件 (single-spa 会监听)
```
const event = new Event('hashchange')
window.dispatchEvent(event)
```

**Comment by Clive-Wang** [comment]
主子应用路由都是hash模式，路由要怎么配置？我现在切换路由会错乱。能提供个例子给我看看吗

**Comment by djlxiaoshi** [comment]
> 试试在主应用里监听路由变化，手动触发一个 hashchange 事件 (single-spa 会监听)
> 
> ```
> const event = new Event('hashchange')
> window.dispatchEvent(event)
> ```

这个有用

**Comment by kuitos** [comment]
原因是 vue-router 3.x 在 hash 模式下，会判断当前浏览器是否支持 pushState，如果支持的话会将 hash 变更转换成 history.pushState 的方式进行变更 https://github.com/vuejs/vue-router/blob/f597959b14887cf0535aa895b6325a2f9348c5cf/src/history/hash.js#L138-L144 ，而不是通过 location.url 这种可以触发 hashchange 事件的方式。

而在 react-router 依赖的 history 的实现里，hash 模式下只监听了 hashchange 事件，也就是 react-router 只会响应能触发 hashchange 的 url 变更 https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createHashHistory.js#L308
PS ，history v5 版本已经[增加了 hash 模式下对 popstate 事件的监听](https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L684)，不过 react-router 依赖的 history 版本还停留在 v4

目前可用的解决方案：
1. 将 vue 主应用中的 Link 超链方式替换成原生的 a 标签，从而触发浏览器的 hashchange
2. 主应用手动监听路由变更，同时手动触发 hashchange 事件
3. 主应用跟子应用都改用 browser history 模式

这个问题跟 qiankun 无关，先 close 了

**Comment by JuSanZhi** [comment]
主应用跟子应用都是vue，主应用hash模式，子应用history模式，发现无法跳转，子应用的 router 的base 应该如何设置？

**Comment by haixiangyan** [comment]
目前发现 React 作为主应用也是会有这样的问题，最小实现：https://github.com/haixiangyan/qiankun-bigass-app/tree/routes

但是 kuitos 说的解决方法都是OK的。
