### ISSUE TITLE
建议example增加create-react-app建子应用，这样更有实际意义

### ISSUE THREAD

**Issue by jiachaosun** [umijs/qiankun#12]
建议example用create-react-app建子应用，并且至少要有code split dynamic import，hot reload，router等功能，这样更有实际意义~

**Comment by kuitos** [comment]
pr is welcome😀

**Comment by leon0707** [comment]
https://github.com/umijs/qiankun/pull/97
add react route

**Comment by wusp1994** [comment]
vue cli的在此，微前端解决方案qiankun测试用例，主应用及子应用均为vue-cli 3 构建 https://github.com/wusp1994/qiankunTestByWu.git

**Comment by kuitos** [comment]
参考最新 example
