### ISSUE TITLE
子应用是一个基于layui开发的多页面项目，基座的entry该如何配置

### ISSUE THREAD

**Issue by bujidao** [umijs/qiankun#1200]
子应用是一个基于layui开发的多页面项目，或者一个很简单的页面，如何配置entry

比如: 
http://www.example.com/index.html
http://www.example.com/about.html
http://www.example.com/news.html

网上看了很多例子：
配置entry的name的时候，必须在微应用中output/library配置相同的名字，但是这个配置在spa很常见，文档给出的范例也是基于vue和react，可是在某些场景只是一个简单的页面，或者用类似layui这样写出来的，这些项目并不需要这个配置文件，也不存在这个文件，请问这种情况该如何处理？？

**Comment by gongshun** [comment]
每一个 html 都是一个子应用，entry 就是 html 的访问地址，至于 `output/library` ，如果你的项目无法分开配置，你可以不配置。参照 jQuery 项目，在每一个页面的 entry  js 里面，直接把生命周期函数挂载到 window 上即可 `window['app-about'] = { bootstrap, mount, unmount }`

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/943 重复了，如果还不能解决，在 https://github.com/umijs/qiankun/issues/943 追踪
