### ISSUE TITLE
[Bug]子应用切换时，会出现短暂的子应用样式失效

### ISSUE THREAD

**Issue by fengbozhi** [umijs/qiankun#1201]
![image](https://user-images.githubusercontent.com/19235574/103754985-111e5500-5048-11eb-9686-e2b179d64679.png)
由于子应用样式通过外联方式，存放在子应用dom底部，导致页面解析dom时无样式，子应用页面样式错乱。有解决方案吗？

**Comment by gongshun** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/219
