### ISSUE TITLE
[Bug]1.高德地图无法加载  2.子应用使用svg图标，在qiankun中无法显示。两个问题都没有报错，并且子应用独自打开的时候是正常的

### ISSUE THREAD

**Issue by skyofbluesky** [umijs/qiankun#1202]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by skyofbluesky** [comment]
代码地址：https://github.com/skyofbluesky/qiankun_test
使用命令“npm run dev”，打开main和center-controller

**Comment by skyofbluesky** [comment]
通过跟踪，发现在qiankun中，子页面加载时，没有获取到dom元素

**Comment by gongshun** [comment]
样式严格隔离模式，使用的是 ShadowDOM ，这会带来新的问题 https://juejin.cn/post/6872132988780412935#heading-8（包括你说的svg问题），适用情况很少，一般不建议用

![image](https://user-images.githubusercontent.com/29347231/103983516-536aa200-51c0-11eb-892e-08305e735ea9.png)

**Comment by mk965** [comment]
请问高德地图的问题解决了吗
