### ISSUE TITLE
[Bug]子应用使用的组件库部分组件样式受影响问题

### ISSUE THREAD

**Issue by sufengyong** [umijs/qiankun#1204]
## What happens?

主应用使用 element 2.x，子应用使用 elementplus，子应用的 element 部分组件插入到了 主应用的 body 元素下，样式受到了主应用 element2.x 的影响（对这类组件配置不插入 body 也会出现其他问题，例如受父类组件影响导致被 overflow: hidden 隐藏等）；各位有遇到类似问题吗，有什么好的建议

## 复现步骤，错误日志以及相关配置
1、主应用使用 vue2,x + element 2.x
2、子应用使用 vue3 + elementplus
3、子应用使用组件 el-select，组件被插入主应用的 body，样式受到主应用 element 影响，开启样式隔离未能解决该问题

## 相关环境信息

- **qiankun 版本**
- 2.3.5
- **浏览器版本**：
- chrome85+
- **操作系统**：
- win10

**Comment by dongongfeiyu** [comment]
有解决吗？被同样的问题困扰

**Comment by EveChee** [comment]
炸裂，同样碰到这个问题 不过我是主应用plus,子应用element-ui。并且只有部分子应用会影响到plus的select 目前没有查看到区别。这种场景第一非常少见。第二项目太过庞大和隐私。无法提供具体复现例子。
