### ISSUE TITLE
主应用访问不到子应用的样式（页面自定义的也访问不到）

### ISSUE THREAD

**Issue by phoxlin** [umijs/qiankun#1205]
## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

[](url)
## 复现步骤，错误日志以及相关配置

1、主应用可以访问到子应用页面，但子应用页面上的样式加载不了，没有404，没有错误提示；
2、子应用单独访问时页面字体大小颜色都正常，主应用访问子应用相同页面连页面字体大小颜色都没加载；
3、子应用的打包配置 vue.config.js 如下：
'use strict'
const path = require('path')
const defaultSettings = require('./src/settings.js')
 const CompressionWebpackPlugin = require('compression-webpack-plugin')
const { name } = require('./package.json')
 const webpack = require('webpack')
 const productionGzipExtensions = ['js', 'css']
function resolve(dir) {
  return path.join(__dirname, dir)
}
const title_name = defaultSettings.title || name // page title
const port = process.env.port || process.env.npm_config_port  || 9528 // dev port
const isProduction = process.env.NODE_ENV === 'production'
module.exports = {
  runtimeCompiler: true,
  publicPath: isProduction ? '/propety' : `//localhost:${port}`,
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: false,
  productionSourceMap: false,
  filenameHashing: true,
  devServer: {
    hot: true,
    disableHostCheck: true,
    historyApiFallback: true,//添加 重点
    port: port,
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },
    before: require('./mock/mock-server.js'),
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
  },
    pluginOptions: {
        'style-resources-loader': {//https://github.com/yenshih/style-resources-loader
            preProcessor: 'scss',//声明类型
            'patterns': [
                //path.resolve(__dirname, './src/assets/scss/_common.scss'),
            ],
            //injector: 'append'
        }
    },
  configureWebpack: {
    // provide the app's title in webpack's name field, so that
    // it can be accessed in index.html to inject the correct title.
    name: title_name,
    resolve: {
      alias: {
        vue:"vue/dist/vue.esm.js",
        '@': resolve('src')
      }
    },
    plugins:[
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        new webpack.SourceMapDevToolPlugin({
            filename: '[name].js.map',
            exclude: ['vendor.js'],
            append: "\n//# sourceMappingURL=http://example.com/sourcemap/[url]"
        }),
      // 下面是下载的插件的配置
      new CompressionWebpackPlugin({
        algorithm: 'gzip',
        test: new RegExp('\\.(' + productionGzipExtensions.join('|') + ')$'),
        threshold: 10240,
        minRatio: 0.8
      }),
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 5,
        minChunkSize: 100
      })

    ],
    output: {
      library: `${name}-[name]`,
      libraryTarget: 'umd',
      jsonpFunction: `webpackJson_${name}`
    }
  },
  chainWebpack(config) {
    // it can improve the speed of the first screen, it is recommended to turn on preload
    config.plugin('preload').tap(() => [
      {
        rel: 'preload',
        // to ignore runtime.js
        // https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/config/app.js#L171
        fileBlacklist: [/\.map$/, /hot-update\.js$/, /runtime\..*\.js$/],
        include: 'initial'
      }
    ])

    // when there are many pages, it will cause too many meaningless requests
     config.plugins.delete('prefetch')
    // set svg-sprite-loader
    config.module
      .rule('svg')
      .exclude.add(resolve('src/icons'))
      .end()
    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(resolve('src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
      .end()

    config
      .when(process.env.NODE_ENV !== 'development',
        config => {
          config
            .plugin('ScriptExtHtmlWebpackPlugin')
            .after('html')
            .use('script-ext-html-webpack-plugin', [{
            // `runtime` must same as runtimeChunk name. default is `runtime`
              inline: /runtime\..*\.js$/
            }])
            .end()
          config
            .optimization.splitChunks({
              chunks: 'all',
              cacheGroups: {
                libs: {
                  name: 'chunk-libs',
                  test: /[\\/]node_modules[\\/]/,
                  priority: 10,
                  chunks: 'initial' // only package third parties that are initially dependent
                },
                elementUI: {
                  name: 'chunk-elementUI', // split elementUI into a single package
                  priority: 20, // the weight needs to be larger than libs and app or it will be packaged into libs or app
                  test: /[\\/]node_modules[\\/]_?element-ui(.*)/ // in order to adapt to cnpm
                },
                commons: {
                  name: 'chunk-commons',
                  test: resolve('src/components'), // can customize your rules
                  minChunks: 3, //  minimum common number
                  priority: 5,
                  reuseExistingChunk: true
                }
              }
            })
          // https:// webpack.js.org/configuration/optimization/#optimizationruntimechunk
          config.optimization.runtimeChunk('single')
        }
      )
  }
}

## 相关环境信息

- **qiankun 版本：2.3.5**
- **浏览器版本：chrome 87.0.4280.141**：
- **操作系统 ：win10 64**：

**Comment by kuitos** [comment]
给复现仓库链接
