### ISSUE TITLE
[Bug]使用 vue-cli 创建的主和子应用，按照样例配置无法成功运行

### ISSUE THREAD

**Issue by kybetter** [umijs/qiankun#121]
## What happens?
使用 vue-cli 创建了两个应用，一个想做为主应用，一个想做为子应用。

目录结构大致如下：
```
child-app/
main-app/
```
我在官方仓库的 examples 目录里面参考了主子应用的配置，然后分别配置到我的这两个应用中了，

为了能够使用 `index.esm.js` 文件，我还把官方库构建好的那个 dist 目录也挪进了主应用里面。

启动命令是：`vue-cli-service serve`，结果发现没有像预期那样成功运行。

我在想是不是只能使用 parcel 来启动呢？
我看示例都是在开发环境下运行的，那构建又是如何构建的呢？是只能用 father 吗？

## 最小可复现仓库

https://github.com/kybetter/qiankun-error-sample

## 复现步骤，错误日志以及相关配置

把上面提供的仓库克隆下来分别进入 main-app 和 child-app 中，执行 `yarn`，然后执行`yarn serve`，
访问主应用服务。

这是访问主应用服务时，控制台报的错：
![20191029174344](https://user-images.githubusercontent.com/12093502/67755784-b072b000-fa73-11e9-9b04-91a3e8420fd9.jpg)

## 相关环境信息

- **浏览器版本**：chrome 最新版
- **操作系统**：mac 最新系统
- **Node 版本**：10.16

**Comment by CradelLau** [comment]
index.esm.js是作者引用自己库用的 你按照readme引用qiankun的包就行了

**Comment by kybetter** [comment]
好的，我试试看换成npm包，按照你那个配一下看看能不能成功运行。也不知道问题出在哪。

**Comment by kybetter** [comment]
终于找到原因了，是子应用的 webpack 配置得加上这两项，把子应用打包成 umd 库格式的：
```
config.output.set('library', `${packageName}-[name]`)
config.output.set('libraryTarget', 'umd')
```

**Comment by wusp1994** [comment]
https://github.com/wusp1994/qiankunTestByWu.git 感谢，也解决了我的问题
