### ISSUE TITLE
[BUG] qiankun v2.0.26 以上版本， 低版本chrome 加载子应用报错

### ISSUE THREAD

**Issue by Ifengmuqing** [umijs/qiankun#1213]
## What happens?

qiankun v2.0.26 以上版本， 低版本chrome 加载子应用报错

 [import-html-entry]: error occurs while executing entry script 
 TypeError: application 'VueMicroApp' died in status LOADING_SOURCE_CODE: Illegal invocation

## Mini Showcase Repository(REQUIRED)

https://gitee.com/xiaoiqing/micro-test.git

## Context

- **qiankun Version**: v2.3.5
- **Platform Version**: windows
- **Browser Version**: chrome v59

**Comment by xiaohuihui1314** [comment]
华为Honor Play 原生浏览器也用不了qiankun,调试的时候发现import-html-entry 的162行的 (0,eval)(code) 出现了 TypeError: Illegal invocation
