### ISSUE TITLE
url中含有中文问题咨询

### ISSUE THREAD

**Issue by caogy1987** [umijs/qiankun#1215]
在window.location.href方式打开url，如果url中含有中文，则无法加载页面，页面卡死。
请问是url中含有中文是无法进行路由吗？

**Comment by gongshun** [comment]
url 含有中文并不会卡死，你可以在  https://github.com/umijs/qiankun/issues 页面的控制台输入如下代码：`window.location.href = 'https://github.com/umijs/qiankun/issues?q=is%3Aissue+is%3Aopen+测试'`

url含有中文参数，或者数字类型的参数，vue-router有些版本的确会导致死循环，你给url编码一下就可以了https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
