### ISSUE TITLE
ant-design-pro 集成@umijs/plugin-qiankun插件,出现布局错乱

### ISSUE THREAD

**Issue by lecd** [umijs/qiankun#1217]
使用ant-design-pro 集成@umijs/plugin-qiankun插件,出现布局错乱

步骤：按官方https://umijs.org/zh-CN/plugins/plugin-qiankun

在配置config.ts
  qiankun: {
    master: {
      sandbox:true,
      apps: [
        {
          name: 'app1',
          entry: '//localhost:8000',
        },
      ],
    },
  },

© 版本信息

Ant Design Pro 版本: Ant Design Pro 5.0.0
umi 最新版本
qiankun: 2.3.5
plugin-qiankun：2.19.0
开发环境 [e.g. mac OS]

问题图片
![image](https://user-images.githubusercontent.com/17017158/104871086-21f29300-5985-11eb-80d6-a025c089ad79.png)
![image](https://user-images.githubusercontent.com/17017158/104871321-b957e600-5985-11eb-95d0-8b1d8fd615c7.png)

**Comment by luoheix** [comment]
删除主应用 pages/document.ejs下的 `<div id="root"></div>` 内容即可，配置 qiankun 后会自动生成  `<div id="root-master"></div>`。
![qiankun](https://user-images.githubusercontent.com/39179889/105683821-09f3b400-5f2f-11eb-89cb-4964e3a1200b.png)

**Comment by ChenYCL** [comment]
我的解决方案是删了root节点.. 同时global.less里面html,body,#root {width:100%,height:100%}删除,但是急需一个mountId的可选挂载位置
