### ISSUE TITLE
微应用启用报错，You need to export lifecycle functions in app1 entry

### ISSUE THREAD

**Issue by xiaoxiao0203** [umijs/qiankun#1218]
Error: application 'app1' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in app1 entry

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
