### ISSUE TITLE
[Bug] 从子应用路由返回根路由时， Vue 子应用的内容没有被清空

### ISSUE THREAD

**Issue by kybetter** [umijs/qiankun#122]
## What happens?

从 Vue 子应用路由返回根路由时，内容没有清空

## 最小可复现仓库
官方examples

## 复现步骤，错误日志以及相关配置

官方examples 的 Framework.jsx 中加入一个跳转到 home 的链接：
```html
<li><a onClick={() => goto('Home', '/')}>Home</a></li>
```
点击其它子应用链接后再点这个链接后，只有 React 子应用会清空内容，Vue 的不会清空，但是 Vue 子应用里面已经把实例销毁了，就导致了呈现出来了一个假页面。

请问如何在主应用里面清空子应用的内容呢？

## 相关环境信息

- **浏览器版本**：chrome
- **操作系统**：mac
- **Node 版本**：10.16

**Comment by kybetter** [comment]
解决了，在 afterUnmount 方法里面调用 render，手动清空内容：
```js
afterUnmount: app => {
    console.log('afterUnmount', app);
    app.render({appContent: '', loading: false});
},
```

**Comment by kuitos** [comment]
这个应该框架来处理比较合适

**Comment by CradelLau** [comment]
这个好 也解决了我的问题 同学你用的是hash路由还是history路由啊 感觉hash路由的css隔离还是有点问题

**Comment by kybetter** [comment]
history 和 hash 都试过了，全局的 css 都是会冲突的，可以使用 scoped 或者使用 css-module 来解决样式冲突问题

**Comment by kuitos** [comment]
子应用之间是可以确保隔离的，主应用跟子应用之间的冲突要自己解决一下，看这里 https://github.com/umijs/qiankun/wiki/FAQ#how-to-guarantee-the-main-app-stylesheet-isolated-with-sub-apps
