### ISSUE TITLE
[Bug]angular lazy loading 无法正确加载路径

### ISSUE THREAD

**Issue by tinet-xiaoyang** [umijs/qiankun#1220]
## What happens?

angular lazy loading 无法正确加载路径

## 最小可复现仓库

https://github.com/mikexfreeze/micro-front-example
git@github.com:mikexfreeze/micro-front-example.git

## 复现步骤，错误日志以及相关配置

lazy loading 路由在 build 之后无法正确加载

怀疑跟 https://github.com/angular/angular-cli/issues/13894 这个问题相关联。

![image](https://user-images.githubusercontent.com/76934772/104887344-14013a00-59a6-11eb-895a-e7b8ee5764f7.png)

如图所示，lazyloadng 路由路径上只有 subapp 没有 angular9

可否提供解决思路

## 相关环境信息

- **qiankun 版本** 2.3.5
- **浏览器版本**：85
- **操作系统**：win10

**Comment by gongshun** [comment]
原因就是：https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F

解决办法：
办法1. 和 demo 一样，写死打包时的 `publicPath`

https://github.com/umijs/qiankun/blob/007f7c5b0f599fee1b9f3a9e886f0a0380e94037/examples/angular9/package.json#L11

办法2：动态修改运行时的 `publicPath`：https://qiankun.umijs.org/zh/guide/tutorial#angular-%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by tinet-xiaoyang** [comment]
> 原因就是：https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F
> 
> 解决办法：
> 办法1. 和 demo 一样，写死打包时的 `publicPath`
> 
> https://github.com/umijs/qiankun/blob/007f7c5b0f599fee1b9f3a9e886f0a0380e94037/examples/angular9/package.json#L11
> 
> 办法2：动态修改运行时的 `publicPath`：https://qiankun.umijs.org/zh/guide/tutorial#angular-%E5%BE%AE%E5%BA%94%E7%94%A8

两种方法都试过了
```
["build": "ng build --deploy-url /subapp/angular9/",](https://github.com/mikexfreeze/micro-front-example/blob/master/angular9/package.json)
```

```
import ['./public-path';](https://github.com/mikexfreeze/micro-front-example/blob/master/angular9/src/main.ts)
```

还是不行

**Comment by gongshun** [comment]
两个问题：
1. build 时 --deploy-url 应该是完整路径，例如 `http://www.abc.com/subapp/angular9/` ， `/subapp/angular9/` 这样写肯定不行的。
2. entry 值不对，`entry` 后面应该有一个/，entry 指的是子项目的 `index.html` 的路径，完整应该是 `/subapp/angular9/index.html`，简写是 `/subapp/angular9/`，而不是 `/subapp/angular9`，entry值正确，方法二是可行的。

https://github.com/mikexfreeze/micro-front-example/blob/edda73450facc9a4cc2318e83b9f5851991351a5/index.js#L11

**Comment by tinet-xiaoyang** [comment]
> 两个问题：
> 
> 1. build 时 --deploy-url 应该是完整路径，例如 `http://www.abc.com/subapp/angular9/` ， `/subapp/angular9/` 这样写肯定不行的。
> 2. entry 值不对，`entry` 后面应该有一个/，entry 指的是子项目的 `index.html` 的路径，完整应该是 `/subapp/angular9/index.html`，简写是 `/subapp/angular9/`，而不是 `/subapp/angular9`，entry值正确，方法二是可行的。
> 
> https://github.com/mikexfreeze/micro-front-example/blob/edda73450facc9a4cc2318e83b9f5851991351a5/index.js#L11

好的，非常感谢
