### ISSUE TITLE
关于entry的配置的问题和需求

### ISSUE THREAD

**Issue by leohihimax** [umijs/qiankun#1222]
关于entry的配置，文档https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles
![image](https://user-images.githubusercontent.com/3620343/104914536-402eb200-59ca-11eb-9280-bcf36abfe0bd.png)
1. 根据文档，以为是可以只配置 entry.html, 不用配置 entry.scripts 和 entry.styles, 发现不行，看了下代码，发现是必须配置 scripts 或者 styles 才可以进入相应的逻辑 
https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L296
2. entry 为对象的时候，能否将子应用完整的HTML 配置在 entry.html 上？
目前我自己试的话是不行的，会报错：Error: [qiankun] You need to export lifecycle functions in XXX entry，看了下应该是不会像importHTML 那样去解析这个HTML，所以找不到 entry js 报错

qiankun 能否支持这种静态的全 HTML 配置？通过解析 entry.html 就可以获取子应用的全部HTML，用起来跟 entry 配置成子应用 URL 一样？

为什么要这么做？
想减少一次HTTP请求提高一些性能

**Comment by gongshun** [comment]
entry.scripts 是必须的，因为要拿到生命周期函数。entry.styles 可以是空数组。

entry.html 就是子应用完整的 HTML 字符串

![image](https://user-images.githubusercontent.com/29347231/104982150-051d9480-5a45-11eb-9863-b9566f357287.png)

**Comment by leohihimax** [comment]
@gongshun 如果 entry.html 可以是子应用完整的HTML，那这个 HTML 应该是包含 entry js 的配置的，qiankun应该可以从 HTML 里面解析出 entry js，就像使用 importHTML 一样，不用再单独配置 scripts 这个数组了

**Comment by gongshun** [comment]
如果还需要去解析一遍 HTML ，那么 entry.scripts 和 entry.styles 这两个参数就毫无意义了

**Comment by leohihimax** [comment]
@gongshun html/scripts/styles 参数本来就是为了让用户更灵活的使用 qiankun 吧
期望这样做的原因：
1. 减少一次 http 请求的时间，提高首屏渲染的性能
2. 依然保持主子应用的完全解藕，这样主子应用的使用方式跟 entry 配置成 URL string 基本一致

**Comment by gongshun** [comment]
如果按你说的，entry.scripts 和 entry.styles 都不需要了，只需要 entry.html，值为子应用的 HTML 内容字符串。和 entry 配置成 URL string 相比，也就是省了一次 http 请求。其实 spa 应用的 index.html 一般非常小，并且 qiankun 还有预请求，配合 http 缓存，省这一次请求作用忽略不计的。

**Comment by kuitos** [comment]
支持 @gongshun 的观点。
如果 entry.html 配置的行为跟 entry: string 的行为一致的，那 entry.string 我觉得就没有意义了。而且 qiankun 推荐的也是 html entry 的微前端接入方式，config entry 纯粹是为了兼容一些 edge case，不建议当成常规方式使用。
