### ISSUE TITLE
[Feature request]执行代码过慢

### ISSUE THREAD

**Issue by zry754331875** [umijs/qiankun#1223]
umi这个模块执行大概要1s，有什么方式可以去优化的呢？拆包吗？？
![image](https://user-images.githubusercontent.com/11375115/105002348-1332db80-5a6c-11eb-958e-3e42b662d168.png)

**Comment by zry754331875** [comment]
整个执行的过程较慢，包括eval模块代码，包括initialValue过程

**Comment by django-d** [comment]
geval 这个方法太卡了 非常耗时

**Comment by zry754331875** [comment]
> geval 这个方法太卡了 非常耗时

是的，我现在放到宏任务里去执行了

**Comment by lihongbin100** [comment]
eval 由于不能做到在闭包场景下的作用域链的内存优化，所以会很卡，官方得想想无 eval 的方法啦

**Comment by kuitos** [comment]
目前的执行存在一定优化空间，可以在 prefetch 阶段提前解析 js，mount 时再执行，具体能优化多少需要测试一下

ref https://github.com/kuitos/import-html-entry/pull/71

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
