### ISSUE TITLE
1.百度地图无法加载 2.在qiankun中无法显示。子应用独自打开的时候是正常的

### ISSUE THREAD

**Issue by firecodes** [umijs/qiankun#1224]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库
https://github.com/firecodes/vue-qiankun-demo
百度地图 主项目打开不显示，被沙箱拦截
https://echarts.apache.org/next/examples/zh/editor.html?c=lines-bmap-bus
## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
你的用法有问题：https://github.com/firecodes/vue-qiankun-demo/blob/597e68768d1cb87dfe14879ef524d723e8d68a99/sub-vue/src/main.js#L8

参考ECharts官网：https://echarts.apache.org/zh/tutorial.html#%E5%9C%A8%E6%89%93%E5%8C%85%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8%20ECharts

将`import echarts from "echarts" ` 改成  `import * as echarts from "echarts"` 就可以了
