### ISSUE TITLE
[Bug]子应用如果初始时异步添加<style>，多次mount，都会不断地添加<style>

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#1226]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

子应用如果初始时异步添加<style>，多次mount，都会不断地添加<style>，导致<style>这个dom元素越来越多。

forLooseSandbox.ts中rebuild中const appWrapper = appWrapperGetter();这里拿到的是初始的index.html，所以if (!appWrapper.contains(stylesheetElement)) {一直返回true。

我估计每次unmount时，qiankun都会记住dom元素，所以再次mount时，导致<style>不断地添加。

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.3.3
- **浏览器版本**：chrome 88
- **操作系统**：window 10

**Comment by waltbest2** [comment]
qiankun开放一个开关，子应用的<style>都挂在主html上。
或者 isHijackingTag这个方法里能控制添加或删除哪些标签。

**Comment by jxbb** [comment]
我们也遇到这个问题，数据多的列表页，style很快会堆积到几千个

**Comment by Cyxwmm** [comment]
这个问题解决了嘛？
