### ISSUE TITLE
主应用加载子应用的页面后，动态生成路由，主应用无法加载

### ISSUE THREAD

**Issue by loioce** [umijs/qiankun#1227]
## What happens?
主应用加载子应用的页面后，页面在子应用动态生成路由，主应用无法加载

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**1.主应用加载子应用a页面

**2.子应用a页面点击事件，调用router.addRoutes新增路由
**3.子应用调用父应用访问页面方法，访问子应用路由；
**4.浏览器中提示：DevTools failed to load SourceMap: Could not load content for http://localhost:8102/index.743b754a.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
**4 ：请问qiankun无法动态加载子应用的动态路由么？如果能，麻烦指导一下
## Context

- **qiankun Version**: 2.3.4
- **Platform Version**: vue2.6.10
- **Browser Version**: chrome版本 86.0.4240.198

**Comment by gongshun** [comment]
动态路由没问题的，请提供 demo，然后才能知道你哪里不对

**Comment by limzgiser** [comment]
暂时，我这边是在script 标签中引入zone.js就可以的。
