### ISSUE TITLE
如何实现单一组件在多个子应用中复用？

### ISSUE THREAD

**Issue by goodchax** [umijs/qiankun#1228]
## Background

我司做的是一个SaaS系统，多个子应用中都需要使用企业成员选择器，现在是在多个应用中冗余代码实现，请问qiankun可以解决类型问题嘛？

**Comment by gongshun** [comment]
办法1. 这个组件上传到私有 npm
办法2. 这个组件打包成 js，主项目引入，子项目直接用
办法3. 这个组件放到主项目，然后挂在 window 上，子项目直接从 window 上取
