### ISSUE TITLE
请问下，如果主工程异步添加<style>作为公共样式，这时候可能被加入到正在打开的子应用里面，如果再unmount，公共样式就会丢掉，这个如何解决

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#1229]
## Background

请问下，如果主工程异步添加<style>，这时候可能被加入到正在打开的子应用里面，如果再unmount，公共样式就会丢掉，这个如何解决
## Proposal

现在link和script可以通过excludeAssetFilter排除，但是<style>好像不行，请问有没有办法区分主工程的<style>还是子工程的<style>

**Comment by gongshun** [comment]
试了下，主工程动态添加的 `<style>` 标签并没有放到子应用里面，你是最新版 qiankun 吗？

老版本的确有这个bug：https://github.com/umijs/qiankun/issues/578

**Comment by waltbest2** [comment]
> 试了下，主工程动态添加的 `<style>` 标签并没有放到子应用里面，你是最新版 qiankun 吗？
> 
> 老版本的确有这个bug：#578

打开的页面url是子工程的，但是主工程作为框架会做一些公共能力，这时候如果异步添加<style>，就会被加到qiankun里面。

**Comment by gongshun** [comment]
给个demo看看？我这边是正常的
