### ISSUE TITLE
这个只支持编译项目吗？

### ISSUE THREAD

**Issue by xy163** [umijs/qiankun#123]
我没完全想通工作流程，你们可以当我自言自语。
      最开始以为是编译后又加了一层路由引导，后来听别人介绍好像并不是那样。
如果JQ，vue,react,angular,全都包在一起，需要什么插件就用什么微组件，感觉要是那样，要疯啊，可能会爽爆很多开发者。比如拖拽，在vue和react中NG有些插件很少能完全满足。需要手写原生，或者直接用JQ.dad()一个函数就完事了。 集百家之长，融万世乾坤。加油哦！！！

**Comment by Hades-li** [comment]
你可以把它理解成iframe。只是这种iframe不会有doc请求。

**Comment by xy163** [comment]
好的

**Comment by kuitos** [comment]
2 楼正解，用法跟 iframe 一样，只不过不是 iframe
