### ISSUE TITLE
是否支持主应用静态加载？ 不起nginx，直接加载index.html，适配端侧的场景

### ISSUE THREAD

**Issue by HWliwenyong** [umijs/qiankun#1230]
## Background

目前有一类似于Electron的PC侧应用
主页是本地Jcef直接加载的本地index,html如：file:///D:/temp/index.html，

打包方式如下：
![image](https://user-images.githubusercontent.com/42129564/105464574-c6017480-5ccc-11eb-8eca-f2f2b480cd40.png)
使用的html entry
配置为：activeRule: '/#/app-vue-hash'
![image](https://user-images.githubusercontent.com/42129564/105465078-740d1e80-5ccd-11eb-9896-446a22679e34.png)

目前在 不起nginx的情况下，直接加载主应用，访问子应用无反应：file:///D:/temp/index.html#/app-vue-hash/

请问qiankun是否支持主应用这种加载方式？

**Comment by gongshun** [comment]
自定义fetch就可以了 https://github.com/umijs/qiankun/issues/955#issuecomment-705955011

**Comment by HWliwenyong** [comment]
![image](https://user-images.githubusercontent.com/42129564/105712339-982e6100-5f54-11eb-8067-eeb6ac65f413.png)

fetch不支持file://的形式，还是要起http服务
不知道你说的自定义fetch是哪种方式，fs读本地文件吗？也不行啊

**Comment by gongshun** [comment]
原生的 fetch 是不行的，它必须要起http服务。自定义 fetch 可以是 fs 读本地文件

**Comment by Cyxwmm** [comment]
> ![image](https://user-images.githubusercontent.com/42129564/105712339-982e6100-5f54-11eb-8067-eeb6ac65f413.png)
> 
> fetch不支持file://的形式，还是要起http服务
> 不知道你说的自定义fetch是哪种方式，fs读本地文件吗？也不行啊

大佬，主应用静态加载能否支持？我的主应用也是通过fiel协议访问的，连接主应用根本没有任何反应，不知道什么情况？请问一下，有什么解决方案吗？
