### ISSUE TITLE
[Feature Request]  在多子应用模式下 Element、ant Design 等UI组件，z-index同步问题

### ISSUE THREAD

**Issue by hjklink** [umijs/qiankun#1231]
## Background

我们公司项目会使用多个子应用，如IM为一个子应用，商户管理是个子应用。
商户管理的Dialog 向IM子应用发消息，唤醒IM弹窗。
由于IM与商户管理子应用的z-index计算不同步，导致商户管理的Dialog遮挡了IM的Dialog。

## Proposal

无

## Additional context

无

**Comment by gongshun** [comment]
elementUI支持全局设置z-index，当你唤起另一个子应用的弹窗时，你可以传个参数进去，将初始的z-index设置大一些就可以了

https://element.eleme.cn/#/zh-CN/component/quickstart#quan-ju-pei-zhi

**Comment by hjklink** [comment]
> elementUI支持全局设置z-index，当你唤起另一个子应用的弹窗时，你可以传个参数进去，将初始的z-index设置大一些就可以了
> 
> https://element.eleme.cn/#/zh-CN/component/quickstart#quan-ju-pei-zhi

这样会导致我必须在唤醒另一个子应用弹窗的时候重新设置他的z-index初始值

**Comment by gongshun** [comment]
这个问题其实没啥好办法。要么就使用同一套组件库，主项目引入，子项目共享。要么自己记录下当前的 z-index，然后动态设置 z-index
