### ISSUE TITLE
ChunkLoadError: Loading chunk fail failed 解决思路

### ISSUE THREAD

**Issue by 121595113** [umijs/qiankun#1232]
## What happens?

在子应用嵌套子应用场景中，孙子应用调用乾坤loadMicroApp方法，下面代码在各自的作用域中
```javascript
// /src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
let bootstrappingPatchCount = 0;
let mountingPatchCount = 0;
```
当其中一个子应用结束生命周期，会执行下面代码：
```javascript
return function unpatch() {
    Document.prototype.createElement = rawDocumentCreateElement;
}

return function unpatch() {
    HTMLHeadElement.prototype.appendChild = rawHeadAppendChild;
    HTMLHeadElement.prototype.removeChild = rawHeadRemoveChild;
    HTMLBodyElement.prototype.appendChild = rawBodyAppendChild;
    HTMLBodyElement.prototype.removeChild = rawBodyRemoveChild;

    HTMLHeadElement.prototype.insertBefore = rawHeadInsertBefore;
}
```
将原生方法改回去。

这个时候如果在当前应用下，异步加载路由组件就会报ChunkLoadError: Loading chunk fail failed错误如下

![](https://user-images.githubusercontent.com/9549500/85287331-aef46d00-b4c6-11ea-9b95-c372d3f7ab3d.png)

## 原因

loadMicroApp方法不是全局唯一

## 解决思路
建议乾坤源码里把loadMicroApp注册成全局唯一(单例)方法，供子应用调用注册孙子应用。

目前我司解决方案：

- 主应用挂载在window上`window.loadMicroApp = window.loadMicroApp || loadMicroApp`
- 子应用中`const loadMicroApp = (window.globalThis || Function('return this')()).loadMicroApp || require('qiankun').loadMicroApp`

## 相关环境信息

- **qiankun 2.3.6可复现**

**Comment by ZxBee** [comment]
你的publicPath 和 router base 信息 是否是对应上的 看下

**Comment by xrds** [comment]
https://github.com/umijs/qiankun/issues/1929#issuecomment-1477297769
