### ISSUE TITLE
qiankun  自己创建的最外层div  样式

### ISSUE THREAD

**Issue by myNameCao** [umijs/qiankun#1233]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

  使用  `qiankun` 创建的 子应用   会嵌套在一个 div 中，  ID  为`__qiankun_microapp_wrapper_for_vueapp_2_1611391007630_807__`

**怎样 设置它的样式** 

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
`#container>div` 或者属性选择器

**Comment by myNameCao** [comment]
> `#container>div` 或者属性选择器

非常感谢
