### ISSUE TITLE
qiankun开放一个开关，子应用的<style>都挂在主html上。 或者 isHijackingTag这个方法里能控制添加或删除哪些标签。

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#1235]
## Background

现在主工程和子工程同时添加<style>，qiankun无法知道添加到主的还是子的dom里，所以能否添加配置能力。

## Proposal

qiankun开放一个开关，子应用的<style>都挂在主html上。
或者 isHijackingTag这个方法里能控制添加或删除哪些标签。

**Comment by gongshun** [comment]
`document.head.appendChild`  往 head 标签里面添加 style 就可以正确区分主应用和子应用，与 https://github.com/umijs/qiankun/issues/1229 重复
