### ISSUE TITLE
父应用获取子应用入口文件没有做跨域请求配置，导致请求被跨域拦截

### ISSUE THREAD

**Issue by hskww** [umijs/qiankun#1236]
父应用获取子应用入口文件没有做跨域请求配置，导致请求被跨域拦截。

kuitos/import-html-entry

这个方法，里的fetch请求没有设置credentials：include， 导致没有带cookie导致子应用服务器端(需要从cookie获取用户身份信息)认为是非法请求

**Comment by gongshun** [comment]
自定义 fetch 就可以了，你把原生的 fetch 包装一层就行。

![image](https://user-images.githubusercontent.com/29347231/105844688-962bd700-6014-11eb-8258-ba0d4d08a905.png)
