### ISSUE TITLE
主项目生成script标签后移除这个标签, 控制台会弹出一个警告, 我希望知道应该如何避免出现这个警告

### ISSUE THREAD

**Issue by my-is-zhang** [umijs/qiankun#1238]
# 主项目生成script标签后移除这个标签, 控制台会弹出一个警告, 我希望知道应该如何避免出现这个警告

## 最小可复现仓库

```
git clone https://github.com/my-is-zhang/qiankun-console-warn-test.git
```

## 复现步骤，错误日志以及相关配置

在主项目的main.js中使用 loadMicroApp 配置参数后, 在app.vue中创建一个按钮, 点击按钮后会在body标签中创建一个script的标签, 随后移除这个script标签, 然后控制台就会出现这个警告

## 相关环境信息

- **qiankun 版本**: "^2.3.6"
- **浏览器版本**：谷歌浏览器 83.0.4103.97（正式版本） （64 位）
- **操作系统**：win7家庭普通版 64位

**Comment by GOGOGOSIR** [comment]
我也出现的问题，在引入百度地图后就会出现这个问题

**Comment by HuDemo** [comment]
我也遇到了同样的问题，在h5子应用内引入mathjax进行数学公式翻译的时候会出现这个问题

**Comment by peakcool** [comment]
关注

**Comment by Orange-C** [comment]
关于这个问题，我做了一些调研

TypeError: Cannot read property 'appWrapperGetter' of undefined 的warning来源是remove元素过程中，试图获取元素的容器config。但是元素创建时没有被qiankun劫持，所以获取失败。

没有被劫持的原因可能是配置自带的excludeAssetFilter导致，也可能是劫持规则bug。

qiankun用try catch包裹了这个过程，抛出warning之后执行了原始的remove函数。

最终逻辑是如果元素被劫持了，qiankun会判断是否在容器内部，在容器内部才会执行删除。如果没有被劫持，一定会被删除。

所以如果warning的来源是自己配置的excludeAssetFilter的话，不用担心。

**Comment by 0undefined0** [comment]
这个会在低版本浏览器直接卡死chrome65必现 @kuitos @gongshun

**Comment by peade** [comment]
有解决方法没？

**Comment by infinityXN** [comment]
> 我也出现的问题，在引入百度地图后就会出现这个问题

我也是引入百度地图，就有这个问题，解决了没
