### ISSUE TITLE
[Bug] Session Storage 或 Local Storage

### ISSUE THREAD

**Issue by luocong2016** [umijs/qiankun#1239]
## What happens?
两个相同脚手架的项目，其中里面的 Storage (Session | Local) 存在串联。这个怎么解决

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
这个只能自己加命名空间了，把 storage 封装一下
