### ISSUE TITLE
qiankun引入superset跨域

### ISSUE THREAD

**Issue by weihaonan** [umijs/qiankun#1240]
sueprset设置了cors后，用qiankun引入一个主应用中，entry路径设置的是http://127.0.0.1:5000/login/?REMOTE_USER=admin，superset跳转到http://127.0.0.1:5000后报跨域了，有哪位大神知道如何解决

**Comment by gongshun** [comment]
子应用的服务器配置允许跨域就行了，怎么允许跨域自己百度吧

**Comment by AnberLu** [comment]
@weihaonan  你将superset 嵌套进qiankun 里面，成功了不？
