### ISSUE TITLE
切换子应用时, 页面卡顿停滞问题是如何解决?以及loading只显示出一次

### ISSUE THREAD

**Issue by HiNaruta** [umijs/qiankun#1241]
# 切换子应用时, 页面出现卡顿停滞现象, 然后才加载出新的子应用

## What happens?

1. 场景 : 通过变更hash切换子应用
2. 问题:  
  1. 仅仅从主应用导航进入第一个子应用时出现了loading
  2. 然后通过顶部主应用导航切换到第二个子应用, 页面会停滞, 给人一种卡住的感觉, 然后不经过loading直接渲染第二个子应用
3. 大致loading代码
  ```
import { Loading } from 'element-ui';
let loadingInstance;
registerMicroApps(apps, {
  beforeLoad: (app) => {
    loadingInstance = Loading.service({
      target: '#microFrame'
    });
    console.log("********乾坤钩子 - 加载前*****")
    return Promise.resolve();
  },
afterMount: (app) => {
    console.log("*******乾坤钩子 - 挂载后*******);
    loadingInstance.close();
    return Promise.resolve();
  }
});
```
即使实例化loading的时候放到beforeMount 生命周期中, loading效果依然不出现,  只是里面的打印每次都执行了
现象是: 导航切换子应用1 ->容器区空白->子应用1出现 -> 点击导航切换子应用2 -> 容器区空白->子应用2出现
现在beforeLoad里, 第一次切换的时候有loading, 不过子应用出来前那一下, loading也会被卡住

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles

用参数这个来设置loading状态

![image](https://user-images.githubusercontent.com/29347231/106096914-5c241780-6171-11eb-91fc-c31e4f93abf8.png)

**Comment by HiNaruta** [comment]
> https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles
> 
> 用参数这个来设置loading状态
> 
> ![image](https://user-images.githubusercontent.com/29347231/106096914-5c241780-6171-11eb-91fc-c31e4f93abf8.png)

```
   {
    name: "modelApp",
    entry: 'http://localhost:9000',
    container: "#microFrame",
    activeRule: getActiveRule("model"),
    props: {
      shared, //将数据以类的方式传递
    },
    loader: loading =>loading  && ( loadingInstance = Loading.service({ target: '#microFrame'}) )
  }
```
假设我在loader里加上如上loading代码;
```
loadingInstance.close();
```
那这段关闭loading的代码应该写在何处呢? 意思是loader可以再写个false的情况关闭掉?

**Comment by HiNaruta** [comment]
试验了一下
```
import { Loading } from 'element-ui';
let loadingInstance;
const loader = loading => {
  if(loading){
  console.log('loading',loading)
  loadingInstance = Loading.service({
      target: '#microFrame'
    });
  } else {
    console.log('loaded',loading)
    loadingInstance.close();
  }
}
```
这个loading效果不出现, 打印倒是打印出来了, 效果就类似于容器里空白停顿,然后渲染出子应用, 好像子应用加载出来前都会变成这样?

**Comment by HiNaruta** [comment]
1. 在从子应用1切换路由到子应用2的瞬间 , 容器的data-name已经变更为子应用2的name
2. 经过断点,loading实际上是有的, 但是瞬间执行到了关闭, 此时loader已经执行完毕
3. 经过以上, 还要等一会才渲染出子应用2的内容, 所以给人的感觉就是无loading且页面卡顿停滞
4. 请问你们是怎么解决卡顿停滞这个问题? @gongshun

**Comment by gongshun** [comment]
loading 结束的时候，子应用的 mount 函数已经执行完了，也就是说剩下的  loading 效果应该由子应用自己来实现

**Comment by kuitos** [comment]
loading 状态很快就没了，说明你的子应用本身渲染出第一屏的有效内容就很慢，你需要看看怎么去优化子应用

**Comment by xiaoqiangz** [comment]
请问下解决了吗？

**Comment by HiNaruta** [comment]
> loading 状态很快就没了，说明你的子应用本身渲染出第一屏的有效内容就很慢，你需要看看怎么去优化子应用

1. 可是作为独立应用的时候, 打开的时候都快的飞起,没这种情况?
2. 子应用1和子应用2合成一个应用的时候, 切换也不会出现这个问题, 也非常的快

**Comment by HiNaruta** [comment]
> loading 状态很快就没了，说明你的子应用本身渲染出第一屏的有效内容就很慢，你需要看看怎么去优化子应用

而且上面第3点的情况是:
1 . qiankun容器里的data-name等属性已经切换成子应用2的了
2. 页面内容还停留在子应用1的内容上
3. 约等个差不多1秒, 开始出现子应用2页面的内容, 即列表请求loading之类的内容

**Comment by HiNaruta** [comment]
> > loading 状态很快就没了，说明你的子应用本身渲染出第一屏的有效内容就很慢，你需要看看怎么去优化子应用
> 
> 而且上面第3点的情况是:
> 1 . qiankun容器里的data-name等属性已经切换成子应用2的了
> 2. 页面内容还停留在子应用1的内容上
> 3. 约等个差不多1秒, 开始出现子应用2页面的内容, 即列表请求loading之类的内容
```
<template>
  <div id="app" v-loading="loading">
    <router-view v-if="!loading"></router-view>
  </div>
</template>
```
```
data () {
   return {
      loading: true
    }
  }
mounted () {
  setTimeout(() => self.loading = false, 500)
}
```
即便改成这样, 在第一次切换应用的时候, 也会停在子系统1一会, 才出现子系统2的loading

**Comment by HiNaruta** [comment]
> loading 状态很快就没了，说明你的子应用本身渲染出第一屏的有效内容就很慢，你需要看看怎么去优化子应用

```
<template>
  <div id="app" v-loading="loading">
    <router-view v-if="!loading"></router-view>
  </div>
</template>
```
```
data () {
   return {
      loading: true
    }
  }
mounted () {
  setTimeout(() => self.loading = false, 500)
}
```
即便改成这样, 在第一次切换应用的时候, 也会停在子系统1一会, 才出现子系统2的loading

**Comment by HiNaruta** [comment]
> 请问下解决了吗？

没有

**Comment by Clive-Wang** [comment]
我也是这样的问题，来回切换特别卡，不知道为什么。单独运行特别快。

**Comment by Italic-2012** [comment]
我也出现了同样的问题，大概耗时4s左右

**Comment by yangdongMC** [comment]
也出现了同样的问题，大概耗时4s左右,如果开启了预加载，则是点击菜单时卡顿，使用<MicroApp/>点击是秒开，但是子应用里面有其他路由就要单独处理

**Comment by dengshenkk** [comment]
我也出现了同样的问题，大概耗时2s左右

**Comment by peakcool** [comment]
同样问题，大概2s-3s左右

**Comment by Jiyr0119** [comment]
https://github.com/umijs/qiankun/issues/1457 看看这个可以帮到你么

**Comment by HiNaruta** [comment]
> #1457 看看这个可以帮到你么

谢谢, 不过子应用的路由并没有拿到主应用去注册, 项目也没有报错, 只是单纯第一次加载的时候很慢

**Comment by gnollmarauder-hub** [comment]
你们没看你们页面js加载的速度吗

**Comment by LbhFront-end** [comment]
请问有解决方案了吗

**Comment by kuxuee** [comment]
请问有解决方案了吗

**Comment by qct5566** [comment]
同问，遇到相同的问题了，目前的解决方式是先打开父应用的loading，再延迟执行跳转操作，由子应用在同位置触发相同的loading等待loader返回false后关闭，但是如果用户直接操作浏览器地址时就没办法了，如果是首屏资源问题的话，那得去想办法解决所有子应用的首屏资源问题了，工作量比较大，有更好的解决方案嘛？

**Comment by li9269391** [comment]
同样的问题，由于子应用较大，打开新的子应用要 6s-8s左右

**Comment by John60676** [comment]
目前解决方案也是在路由跳转前，先把 loading 渲染出来，否则等到子应用执行渲染时，主应用的 loading 就没法渲染出来了

提供一段简易代码， `subAppLoading` 绑定 `loader` 里面的 `loading`

<img width="535" alt="image" src="https://user-images.githubusercontent.com/21698973/216511829-64886996-f2b9-4c23-94e7-e026f1acaff9.png">

**Comment by 961998264** [comment]
其实大家思考的是为什么子应用内嵌在主应用的时候会那么慢。我的字应用单独打开是7s,内嵌的时候是20s
