### ISSUE TITLE
两个不同的container算出来的xpath一样直接取了缓存，导致直接渲染了旧页面

### ISSUE THREAD

**Issue by zry754331875** [umijs/qiankun#1242]
可能是两个容器节点的层级结构一致导致的？
看源码得出的结论，不知道是否正确

**Comment by gongshun** [comment]
你是什么场景下渲染了旧页面？

**Comment by zry754331875** [comment]
> 你是什么场景下渲染了旧页面？

在一个模态框里，第一次执行了loadApp后是正确的，第二次xpath一致直接从缓存里取的parcelConfigGetterPromise，然后子应用拿到的useModel('@@qiankunStateFromMaster')就是第一次的props。但是在子应用里的mount生命周期函数中可以拿到最新的props

**Comment by Newway1997** [comment]
楼主解决了吗，我也遇到了
