### ISSUE TITLE
[Bug]主应用访问基于vue-element-admin搭建的微应用是部分资源出现We're sorry but XXX doesn't work properly without JavaScript enabled. Please enable it to continue

### ISSUE THREAD

**Issue by jidaqi** [umijs/qiankun#1243]
## What happens?

在微应用为基于vue-element-admin搭建的vue后台时，主应用访问微应用部分资源会出现 ’We're sorry but XXX doesn't work properly without JavaScript enabled. Please enable it to continue.‘ 的错误
![image](https://user-images.githubusercontent.com/50898258/106122038-1afa1c00-610d-11eb-92ec-a93369abc640.png)
![image](https://user-images.githubusercontent.com/50898258/106121986-0ae23c80-610d-11eb-8c63-bb922387bb80.png)

## 最小可复现仓库
https://github.com/jidaqi/qiankun-demo.git

## 复现步骤，错误日志以及相关配置
```
// 开启主应用
cd main
npm i
npm run serve

// 开启微应用
cd vue-element-admin
npm i
npm run dev
```

1. 访问 http://localhost:8080/
2. 查看控制台network
3. 点击 [admin-test]

部分资源出现 'We're sorry but hello-qiankun doesn't work properly without JavaScript enabled. Please enable it to continue.'

## 相关环境信息

- **qiankun 版本**: 2.3.6
- **浏览器版本**：Google Chrome 版本 88.0.4324.104
- **操作系统**：win10 64位

**Comment by gongshun** [comment]
你要点开这里，看到的才是请求返回的内容，preview是被解析后的内容

![image](https://user-images.githubusercontent.com/29347231/106144307-fbb3cb00-61ae-11eb-8534-1855ec54d61b.png)

**Comment by jidaqi** [comment]
> 你要点开这里，看到的才是请求返回的内容，preview是被解析后的内容
> 
> ![图片](https://user-images.githubusercontent.com/29347231/106144307-fbb3cb00-61ae-11eb-8534-1855ec54d61b.png)

但是他说JavaScript无法正常启用，而且单独打开微应用能正常渲染，但是在主应用下打开却出现了这个问题，我google过有可能是路由的问题

**Comment by gongshun** [comment]
这是浏览器解析了你的子项目的index.html，你看到的这句内容就是你的子项目的 index.html 里面的一个标签：
```html
<noscript>
      <strong>We're sorry but hello-qiankun doesn't work properly without JavaScript enabled. Please enable it to continue</strong>
</noscript>
```

这并不是 js 无法正常启用，response面板才是真正的返回内容，preview是解析后的内容

**Comment by PurpleDandelion** [comment]
@jidaqi 解决了吗，我也遇到了这个问题

**Comment by jidaqi** [comment]
> @jidaqi解决了吗，我也遇到了这个问题

似乎是因为代理的原因，目前没有找到比较好的解决办法
