### ISSUE TITLE
[Bug]主应用无法获取子应用export的数据

### ISSUE THREAD

**Issue by maxmeng93** [umijs/qiankun#1247]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?
主应用无法获取子应用export的数据。
qiankun@2.0.16时，还可以在主应用通过 window['micro-app'] 获取子应用导出的数据

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
为啥要通过 export 导出数据呢，props 传递就可以了呀 https://qiankun.umijs.org/zh/api#initglobalstatestate
