### ISSUE TITLE
如何实现添加子项目时不需要更新发布主系统

### ISSUE THREAD

**Issue by Bennyliu701** [umijs/qiankun#1250]
## 如何实现添加子项目时不需要更新发布主系统

主系统只用来提供主框架相关配置服务与子应用入口，目前是通过添加新增子系统入口地址来解决该问题，但是需要更新发布代码。请问如何避免这种情况呢？

## 复现步骤，错误日志以及相关配置
1.创建独立子系统
2.本地开发，独立部署
3.解析测试域名（线上环境改为正式域名）
4.将测试域名（线上环境改为正式域名）添加到registerMicroApps的entry参数
5.发布主系统
## 相关环境信息

- **qiankun 版本**：2.3.5
- **浏览器版本**：88.0.4324.96
- **操作系统**：macOS 10.15.7 (19H512)

**Comment by seainhand** [comment]
主项目用配置文件或者后端接口获取子应用配置

**Comment by Bennyliu701** [comment]
> 配置文件
“配置文件”指的是线上的cdn地址指向的json文件吧
