### ISSUE TITLE
[Bug]sandbox\patchers\dynamicAppend\common.js添加style时会dynamicStyleSheetElements.push(stylesheetElement);，但是remove时，并没有清理这个数组，请问这是为什么

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#1254]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

[Bug]sandbox\patchers\dynamicAppend\common.js添加style时会dynamicStyleSheetElements.push(stylesheetElement);，但是remove时，并没有清理这个数组，请问这是为什么

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.3.3
- **浏览器版本**：chrome88
- **操作系统**：window 10

**Comment by kuitos** [comment]
下次 remount 的时候还需要从这个数组里 rebuild css
