### ISSUE TITLE
当子系统中的html里有script时，会被import-html-entry替换   子页面 script  引入的东西 失效

### ISSUE THREAD

**Issue by myNameCao** [umijs/qiankun#1260]
## What happens?

 子系统中的html里有script时，会被import-html-entry替换   子页面 script  引入的东西 失效
## How To Reproduce

1. 在子页面index.html  页面 引入富文本编辑器的功能 ，使用的是 `script` 标签 引用的是本地的文件 
2.  在子页面 index.html   页面   使用` script ` 标签 引入外部的链接 
如图
![image](https://user-images.githubusercontent.com/23721492/107135395-3c40e080-6935-11eb-956e-0cdb66a4c364.png)
在主项目浏览器中显示 见代码为 如图
![image](https://user-images.githubusercontent.com/23721492/107135415-79a56e00-6935-11eb-871b-f7e64cf11f02.png)

3  在主项目中 外部引入 的链接并没有产生引入后的效果

##  issues
问题一：在子应用中   index.html  引入 的 外部 资源  被 `qiankun `   replaced by  import-html-entry  在 子引用中怎么样使用
问题二：在子应用挂在到 window 中的一些属性   在 主应用显示  不 能在window  访问  

## Context

 + `qiankun`  ^2.4.0
 +  vue 2.X
+ vue cli 3.X

# 再次表示非常感谢

**Comment by gongshun** [comment]
> 问题一：在子应用中 index.html 引入 的 外部 资源 被 qiankun replaced by import-html-entry 在 子引用中怎么样使用

import-html-entry 框架注释掉 script 标签后，会先用 fetch 请求到内容，然后使用 eval 执行内容，不影响子应用其他地方的使用。但是需要注意的是，这个 js 里面使用 var 声明的“全局变量”，其他的地方将无法访问到，必须要挂在 window 上才是全局变量。

> 问题二：在子应用挂在到 window 中的一些属性 在 主应用显示 不 能在window 访问

https://github.com/umijs/qiankun/pull/130#issuecomment-549847590

**Comment by myNameCao** [comment]
> > 问题一：在子应用中 index.html 引入 的 外部 资源 被 qiankun replaced by import-html-entry 在 子引用中怎么样使用
> 
> import-html-entry 框架注释掉 script 标签后，会先用 fetch 请求到内容，然后使用 eval 执行内容，不影响子应用其他地方的使用。但是需要注意的是，这个 js 里面使用 var 声明的“全局变量”，其他的地方将无法访问到，必须要挂在 window 上才是全局变量。
> 
> > 问题二：在子应用挂在到 window 中的一些属性 在 主应用显示 不 能在window 访问
> 
> [#130 (comment)](https://github.com/umijs/qiankun/pull/130#issuecomment-549847590)
非常感谢您的回复

**Comment by myNameCao** [comment]
@gongshun   首先 非常感谢您的回复 

现在我 微应用中  引入的外部 链接 只有添加 gnore  才能正常的使用 
如
```js
<script
    ignore
    type="text/javascript"
    charset="utf-8"
    src="/UEditor/kityformula-plugin/defaultFilterFix.js"
  ></script>
```
但是 我微应用只引入的 外部链接 
内部代码 
```js
UE.I18N['zh-cn'] ={}
```
单独 运行微应用时正常 使用 

在 主应用 中  提示 `UE  is not defined`

**Comment by gongshun** [comment]
不能添加 ignore 属性，添加 ignore 表示在主应用中会忽略这个标签（不会加载和执行）

至于`UE is not defined`这个报错，上面已经说了：使用 var 声明的“全局变量”，其他的地方将无法访问到，必须要挂在 window 上才是全局变量。

**Comment by myNameCao** [comment]
@gongshun  明白了

**Comment by yurizhang** [comment]
> @gongshun 非常感谢 ！！！我明白了

请问你解决这个问题了吗？

**Comment by yurizhang** [comment]
当在一个页面上加载这2个相同的应用就没有办法了，只有一个起作用。

**Comment by XingXiaoWu** [comment]
> 当在一个页面上加载这2个相同的应用就没有办法了，只有一个起作用。

为啥会加载两个相同的应用呢

**Comment by yurizhang** [comment]
> > 当在一个页面上加载这2个相同的应用就没有办法了，只有一个起作用。
> 
> 为啥会加载两个相同的应用呢

Dashboard Widget
![image](https://user-images.githubusercontent.com/20555332/108587748-5dbbb680-7390-11eb-9485-635ec974fada.png)
