### ISSUE TITLE
vue的主项目和子项目之间如何通过路由传参数?

### ISSUE THREAD

**Issue by bingxueyinlian** [umijs/qiankun#1263]
# vue的主项目和子项目之间如何通过路由传参数?

## vue主项目通过路由传参数给子项目，子项目接收不到.

主项目和子项目都是vue，菜单统一由主项目管理。点菜单的时候，需要给子页面传参数。
主项目和子项目独立运行，不在同一个域。

## 复现步骤
1.主项目通过路由push打开子页面，代码如下：
```
let { path, params, query } = {};
params = {
        ppp: "1111"
};
query = { qq: "2222" };

console.log("AAA-params", params);
console.log("AAA-query ", query );

this.$router.push({
        path,
        params,
        query,
      });
```
2.子项目在按钮点击事件中通过this.$route.params和this.$route.query都取不到传过来的数据
```
console.log("this.$route.params", this.$route.params);
console.log("this.$route.query", this.$route.query);
```
3.日志结果输出如下：
```
AAA-params {ppp: "1111"}
AAA-query  {qq: "2222"}
this.$route.params {}
this.$route.query {}
```
## 相关环境信息

- **qiankun 版本**：2.3.6
- **浏览器版本**：Google Chrome 88.0.4324.150（正式版本） （64 位）
- **操作系统**：windows 10 企业版 ，版本号：2004

请问大佬们：这种场景，主项目的菜单应该如何给子项目的页面传参数？（页面级的参数）

**Comment by bingxueyinlian** [comment]
query参数能传了，params 参数还传不了。查了一下，说是params参数push时必须使用name才行。但是主项目push用name一直提示找不到路由名。

**Comment by gongshun** [comment]
因为主子应用不是同一个路由实例，这种情况，你要么把路由实例传给子应用，要么自己从 `location` 对象取下来
