### ISSUE TITLE
angular  子应用第二次进入后  zone.js  中报错 `Target container with #content not existed while test mounting`

### ISSUE THREAD

**Issue by myNameCao** [umijs/qiankun#1264]
## What happens?
 在主项目  第二次点击进入 子应用  ，在主应用 的 zone.js 文件 报错 提示 `Target container with #outApp not existed while answersheet mounting!`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

1.   在主项目中  
```js
template>
  <div id="outApp"></div>
</template>
<script>
  import 'zone.js'
  import { start, registerMicroApps } from 'qiankun'
  registerMicroApps([
    {
      name: 'question',
      entry: process.env.VUE_APP_importGrades,
      container: '#outApp',
      activeRule: '/app/importGrades'
    }, // 成绩导入
    {
      name: 'xyexam',
      entry: '//localhost:8081' || process.env.xyexam,
      container: '#outApp',
      activeRule: '/app/xyexam'
    }, // 题库
    {
      name: 'answersheet',
      entry: process.env.VUE_APP_answersheet,
      container: '#outApp',
      activeRule: '/app/answersheet'
    } //答题卡
  ])
  export default {
    name: '',
    mounted() {
      if (!window.qiankunStarted) {
        window.qiankunStarted = true
        console.log(111)
        start()
      }
    }
  }
</script>
<style lang="less" scoped>
  #outApp {
    width: 100%;
    height: 100%;
  }
</style>
```
2  第二次进入 一个 angular 子项目  保错 提示   `Target container with #outApp not existed while answersheet mounting!`

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by waltbest2** [comment]
#outApp，你这个槽位最好放在index.html中，固定存在，不要动态生成，否则时序性会导致找不到这个槽位，没法渲染子应用。

**Comment by myNameCao** [comment]
@waltbest2   首先非常感谢你的回复   
 因为 我是想在 某一个子路由页面  嵌入 几个项目  在 接入两个  `vue` 项目的 的时候  是没有问题 的 只要 嵌入angular 子项目 就报错，因为 官方文档说:在 主应用在 引入`qiankaun`前   要引入`zone.js ` ，只要 引入 它 就会有这个错误 。感觉是 zone.js 的问题

**Comment by gongshun** [comment]
去掉主项目的路由过渡就可以了，或者换成其他的过渡效果

**Comment by myNameCao** [comment]
> 去掉主项目的路由过渡就可以了，或者换成其他的过渡效果
意思是目前是不能 使用 路由页面 嵌入 angular 项目？

**Comment by gongshun** [comment]
> 意思是目前是不能 使用 路由页面 嵌入 angular 项目？

可以嵌入啊，路由过渡有些不兼容而已，路由过渡去掉又不影响

**Comment by hanalice** [comment]
我的angular 项目中并没有显示的设置路由过渡，也出现了这个问题 @gongshun
