### ISSUE TITLE
[Bug]使用Vue3作为主应用，setDefaultMountApp后url没有变化

### ISSUE THREAD

**Issue by GooniL** [umijs/qiankun#1265]
## What happens?

使用vue3作为主应用时，setDefaultMountApp设置默认应用后，url不会跳转

## 最小可复现仓库

主应用：https://github.com/GooniL/vue3-base.git
子应用：https://github.com/GooniL/vue3-child.git
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
必现。
子应用会加载，单因为url没有跳转，只加载了子项目，没有加载子项目的路由

## 相关环境信息

- **qiankun 版本**：2.4.0
- **浏览器版本**：chrome 88.0.4324.146
- **操作系统**：macOS

**Comment by kuitos** [comment]
被主应用路由重新改回了 '/' 导致的，你可以给主应用加个 '/vue3' 的空路由试试
