### ISSUE TITLE
[Bug]微应用中在异步回调中动态插入的脚本，无法正确地被沙箱代理

### ISSUE THREAD

**Issue by y8n** [umijs/qiankun#1266]
## What happens?

微应用的脚本中如果有在异步回调中动态插入脚本，而且在document 对象被临时变量缓存的话，此时动态插入的脚本执行环境并不在沙箱中，而是外层window。伪代码如：

```
// entry.js
let doc = window.document;
Promise.resolve().then(() => {
  let script = doc.createElement('script');  // 这个script的执行环境并不在沙箱中
 // some code  
 doc.head.appendChild(script);
});
```

疑似原因为：proxySandBox中，通过document 的 getter设置当前运行沙箱 currentRunningSandboxProxy ，并在被劫持的createElement方法中获取该沙箱，但是因为document 的 getter中又用 nextTick 对currentRunningSandboxProxy进行重置，导致如果微应用中触发getter和使用createElement并不是同步的话，就会在下一个异步执行时，获取到重置以后的currentRunningSandboxProxy，也即是null，导致createElement、appendElement的时候，无法正确被代理。

关联PR：https://github.com/umijs/qiankun/pull/846

## 最小可复现仓库

代码演示：https://stackblitz.com/edit/qiankun-demo?file=src/main.js
微应用代码示例：https://gist.github.com/y8n/4ee7013a546eff1892caaf1072eccd6d

### 为什么不使用示例代码中的方法一或方法三？
因为示例中[L4-L17](https://gist.github.com/y8n/4ee7013a546eff1892caaf1072eccd6d#file-entry-L4-L17)是微应用中引入的某SDK的代码，不受微应用控制，无法控制执行顺序。

项目中真实的代码如下

```
// index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>App</title>
</head>
<body>
  <div id="app"></div>
  <script src="//cdn.com/sdk.js"></script>   // SDK中动态插入了脚本，不受entry控制。entry中调用SDK的某方法时触发动态脚本获取等行为
  <script src="//cdn.com/entry.js"></script>
</body>
</html>

```

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/8521368/107840992-35f9ab00-6df2-11eb-9bed-e442a796000b.png)

## 相关环境信息

- **qiankun 版本**： 2.4.0
- **浏览器版本**：88.0.4324.150
- **操作系统**：OSX

**Comment by zhoutengjiao** [comment]
确实，我也遇到这个问题了，楼主咋解决的

**Comment by y8n** [comment]
@zhoutengjiao  我是将SDK在外层主应用中引入，然后把外层的window传给沙箱里的window进行调用。

```
//  伪代码
// 主应用
<script src="//cdn.com/sdk.js"></script>
window.__RAW_WINDOW_ = window;

// 微应用
const rawWindow = window.__RAW_WINDOW_;
rawWindow.sdkMethod();
```

**Comment by ruanlin-kylin** [comment]
我好像也遇到了这个问题，我用document.addEventListener监听事件异步渲染了一个dom，本来第一次渲染出来了，被nextTick 对currentRunningSandboxProxy进行重置后，dom又没了。用了楼主的方案，使用主应用的window去监听，但是没用，有没有其他的思路。
