### ISSUE TITLE
webpack5+vue3接入qiankun报错

### ISSUE THREAD

**Issue by duanshanghanqing** [umijs/qiankun#1267]
使用webpack5+vue3构建项目，独立访问没问题。由于webpack5 将 output.jsonpFunction 删除了，导致在接入qiankun报错。
Error: application 'webpack5-vue3' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in webpack5-vue3 entry

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1092 重复
