### ISSUE TITLE
子应用包含多个script，其中有些是公共方法，其他js使用的时候提示找不到方法

### ISSUE THREAD

**Issue by XingXiaoWu** [umijs/qiankun#1272]
## What happens?
子应用html引入两个js，first.js和second.js

second.js调用first.js中的方法报错

## Mini Showcase Repository(REQUIRED)

https://github.com/XingXiaoWu/qiankun-error

## How To Reproduce

直接从官方demo中添加俩个js复现该情况
https://github.com/XingXiaoWu/qiankun-error/tree/master/examples/purehtml

**Steps to reproduce the behavior:** 1. 2.

```
cd 根目录
yarn install:main
yarn install:purehtml
yarn start:main
yarn start:purehtml
```
1.直接访问purehtml起的微应用，可以正常执行function aa()
2.通过乾坤起的主应用访问purehtml，找不到function aa()

**Expected behavior** 1. 2.
预期通过qiankun主应用访问purehtml可以正常调用function aa()
## Context

- **qiankun Version**:2.4.0
- **Platform Version**:
- **Browser Version**:Microsoft Edge 88.0.705.74 (官方内部版本) (64 位)

主要添加代码如下
https://github.com/XingXiaoWu/qiankun-error/blob/master/examples/purehtml/index.html
```
<body>
  <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
    Purehtml Example
  </div>
  <div id="purehtml-container" style="text-align:center"></div>
  <script src="./first.js"></script>
  <script src="./second.js"></script>
  <script src="//localhost:7104/entry.js" entry></script>
</body>
```

https://github.com/XingXiaoWu/qiankun-error/blob/master/examples/purehtml/first.js

https://github.com/XingXiaoWu/qiankun-error/blob/master/examples/purehtml/second.js

![image](https://user-images.githubusercontent.com/22769131/108587986-b9d30a80-7391-11eb-8953-a500268df795.png)

**Comment by XingXiaoWu** [comment]
https://github.com/umijs/qiankun/issues/966#issuecomment-700387279
找到了。。要显式赋值。。项目迁移要改到死。。。

**Comment by SmiMi** [comment]
> [#966 (comment)](https://github.com/umijs/qiankun/issues/966#issuecomment-700387279)
> 找到了。。要显式赋值。。项目迁移要改到死。。。

请教一下，显式赋值是啥意思？我们也有类似的问题

**Comment by XingXiaoWu** [comment]
> > [#966 (comment)](https://github.com/umijs/qiankun/issues/966#issuecomment-700387279)
> > 找到了。。要显式赋值。。项目迁移要改到死。。。
> 
> 请教一下，显式赋值是啥意思？我们也有类似的问题

打开我上面的链接，定位到的消息就是
