### ISSUE TITLE
手动加载应用， 二次加载时，未发起请求?

### ISSUE THREAD

**Issue by H-copy** [umijs/qiankun#1273]
我希望在本地页面内嵌套子应用，在页面渲染时手动加载子应用，初始加载时正常，但是二次加载时，未看到发起新的请求拉取子应用, 请问如何重新加载子应用？

![image](https://user-images.githubusercontent.com/27235325/108590126-dd4f8280-739c-11eb-9418-bb2bd7045dbd.png)

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/986

**Comment by yurizhang** [comment]
> 我希望在本地页面内嵌套子应用，在页面渲染时手动加载子应用，初始加载时正常，但是二次加载时，未看到发起新的请求拉取子应用, 请问如何重新加载子应用？
> 
> ![image](https://user-images.githubusercontent.com/27235325/108590126-dd4f8280-739c-11eb-9418-bb2bd7045dbd.png)

楼主你解决了，我也遇到了~

**Comment by yurizhang** [comment]
@H-copy 我也遇到了，楼主解决了吗

**Comment by H-copy** [comment]
![image](https://user-images.githubusercontent.com/27235325/108693403-c2b21080-7538-11eb-94b2-6a0659d5239c.png)
 我是手动加载的，所以重载时，更新了请求地址，触发二次加载
![image](https://user-images.githubusercontent.com/27235325/108693591-f42adc00-7538-11eb-989a-85376a9cddc4.png)

**Comment by yurizhang** [comment]
谢谢你的回答，但我没有明白#986是什么 意思 。
我需要页面强制的刷新拉取最新的请求，就像是(location.reload)
