### ISSUE TITLE
子应用为vue 的老项目，静态资源是放在阿里云上面，publicPath应该如何配置

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1276]
## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：
![image](https://user-images.githubusercontent.com/24559368/108683271-5c26f580-752c-11eb-9477-993ff01213cc.png)

![image](https://user-images.githubusercontent.com/24559368/108679422-78746380-7527-11eb-8efb-6c82bd296fc1.png)

**Comment by gongshun** [comment]
直接把子项目的打包的 `publicPath` 写死就行了（地址就是你阿里云的地址），并且不需要动态修改 `publicPath`

https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8

![Uploading image.png…]()

**Comment by JuSanZhi** [comment]
![image](https://user-images.githubusercontent.com/24559368/108813366-d79bac00-75eb-11eb-99ea-9f3ec1767089.png)
这种是什么问题导致的
