### ISSUE TITLE
php项目可以用于qiankun中吗？

### ISSUE THREAD

**Issue by Simmon12** [umijs/qiankun#1277]
qiankun文档中提到无关技术栈，那想请教下，对于那些php前后端未分离的项目可以作为主应用，或者微应用吗？

**Comment by gongshun** [comment]
可以的，参考jQuery项目

**Comment by Simmon12** [comment]
> 可以的，参考jQuery项目
好的，请问有jQuery项目的项目例子吗，我看examples里只有purehtml的

**Comment by gongshun** [comment]
> 我看examples里只有purehtml的

那就是jQuery项目
