### ISSUE TITLE
[Feature Request] experimentalStyleIsolation模式下子应用样式渲染慢

### ISSUE THREAD

**Issue by zry754331875** [umijs/qiankun#1278]
子应用大概需要花费0.6s才能计算好样式
![image](https://user-images.githubusercontent.com/11375115/108932853-031ea500-7685-11eb-9eb4-8f390c5122f2.png)

**Comment by Cyxwmm** [comment]
我这里也有这个问题，发现切换应用后，qiankun-head 里面的style标签数量 每次都会增加一倍。不知道为什么
