### ISSUE TITLE
微应用apollo项目

### ISSUE THREAD

**Issue by luocong2016** [umijs/qiankun#1279]
## 微应用apollo项目【实现过程记录】

我想接入微应用 apollo, https://github.com/ctripcorp/apollo
一、多页面要怎么配置？
我尝试给所有的 html 配置 entry.js
```js
/* qiankun start */
function render($) {
    debugger
}

(function(global) {
    global["apollo"] = {
        bootstrap: function() {
            debugger
            return Promise.resolve();
        },
        mount: function () {
            return render($);
        },
        unmount: function () {
            debugger
            return Promise.resolve();
        }
    };
})(window);
/* qiankun end */
```

但是报错
```sh
Uncaught TypeError: Failed to fetch      single-spa.min.js?25a2:2
```
![image](https://user-images.githubusercontent.com/25705196/108934054-2a767180-7687-11eb-9974-96d40a0e86aa.png)

二、form 跳转怎么设置？
![image](https://user-images.githubusercontent.com/25705196/108942430-f3598d80-7691-11eb-9e88-e10c18baf418.png)

## 相关环境信息
qiankun: "^2.0.22",
chrome 版本 85.0.4183.102（正式版本） （64 位）
win 7

**Comment by gongshun** [comment]
> Failed to fetch  

说明服务没跑起来，或者子项目的地址有问题

**Comment by luocong2016** [comment]
第一个原因,服务跑起来了， 代理配置 localhost:8070/apollo 是错误的
```
VUE_APP_APOLLO=//localhost:8070/

 {
    project: '配置中心',
    name: 'apollo',
    entry: process.env.VUE_APP_APOLLO,
    activeRule: '/xxapollo'
  }
```

**Comment by gongshun** [comment]
> ![image](https://user-images.githubusercontent.com/29347231/108967318-552ded80-76ba-11eb-9fb2-80ac6078cb3d.png)

这种报错，第一行错误是提示代码出错位置，第二行错误才是真正的错误，

应该是沙箱导致你的全局变量变成了局部变量，只有显式的挂在window上才是全局变量，其他的js才能获取到

**Comment by luocong2016** [comment]
我想知道项目中 form action 跳转成html 能解决？ 卡这里了

**Comment by gongshun** [comment]
登陆完了主页面也是一个子应用，你直接跳转路由就行了，但是你想跳转HTML，这不行

**Comment by luocong2016** [comment]
问题是apollo 里面是跳转 html。
是不是把每个html 都注册到微应用

**Comment by huskylengcb** [comment]
请问问题解决了吗？我们项目也用的apollo，所有的apollo接口都返回undefined，没有去请求

**Comment by PHenryy** [comment]
求 apollo 配置方案～～～
非常感谢～～～
