### ISSUE TITLE
主应用加载子应用以后，在子页面中使用了子页面的router进行了一次页面跳转，子路由无法监听第一次浏览器的返回按钮引起的path变更

### ISSUE THREAD

**Issue by XingXiaoWu** [umijs/qiankun#1280]
## What happens?

主应用使用Vue3，history模式
子应用使用Vue3，history模式

主应用加载子应用页面，子应用使用子应用的router进行一次子应用内的页面跳转。
在第一次使用浏览器的回退键的时候，子应用的router无法监听到path变更，主应用可以监听到path变更。
再次使用前进后退，子应用的router按键正常。

## Mini Showcase Repository(REQUIRED)

https://github.com/XingXiaoWu/error2

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.拉依赖
```
cd main
yarn
yarn serve
```
```
cd sub-login
yarn
yarn serve
```
2.访问`localhost:3000/login`
3.点击用户自注册按钮
4.点击浏览器的返回按键

录屏如下：

https://user-images.githubusercontent.com/22769131/108942814-a0340a80-7692-11eb-91f3-f446e9f77b73.mp4

**Expected behavior** 1. 2.
子应用页面能正常回退到上一页面（即登陆页面）
## Context

使用history进行跳转正常。来自： https://github.com/umijs/qiankun/issues/1155 但是这样就无法使用项目框架自带的路由了。

如果使用hash模式可能使用 https://github.com/umijs/qiankun/issues/1199#issuecomment-757596305 添加`hashchange `事件可以达成目标（未尝试），但使用的是history模式。

- **qiankun Version**:^2.4.0
- **Platform Version**:MAC OS
- **Browser Version**:Chrome 版本 88.0.4324.192（正式版本） (x86_64)；Microsoft Edge 版本 88.0.705.74 (官方内部版本) (64 位)；

**Comment by XingXiaoWu** [comment]
我这个问题没有老哥碰到吗

**Comment by GOGOGOSIR** [comment]
你回退到2.0.26试试

**Comment by XingXiaoWu** [comment]
> 你回退到2.0.26试试

是指qiankun版本还是vue版本还是vue-router版本

**Comment by XingXiaoWu** [comment]
> 你回退到2.0.26试试

尝试了qiankun回退到2.0.26，无效

**Comment by marginxxx** [comment]
+1，也遇到了这个问题，不知道怎么解决。

在主应用使用router-link跳转到/subapp，
然后subapp里使用router-link到/subapp/a浏览器url栏及页面内容正常，
然后点击返回，浏览器url栏由/subapp/a变为/subapp，但是页面内容仍为/subapp/a的内容
点击前进，浏览器url栏由/subapp变为/subapp/a，页面内容为/subapp/a的内容
点击后退，浏览器url栏由/subapp/a变为/subapp，页面内容为/subapp的内容。

与issue描述和视频演示相同。

**Comment by XingXiaoWu** [comment]
> +1，也遇到了这个问题，不知道怎么解决。
> 
> 在主应用使用router-link跳转到/subapp，
> 然后subapp里使用router-link到/subapp/a浏览器url栏及页面内容正常，
> 然后点击返回，浏览器url栏由/subapp/a变为/subapp，但是页面内容仍为/subapp/a的内容
> 点击前进，浏览器url栏由/subapp变为/subapp/a，页面内容为/subapp/a的内容
> 点击后退，浏览器url栏由/subapp/a变为/subapp，页面内容为/subapp的内容。
> 
> 与issue描述和视频演示相同。

你如果也是vue3+history模式，目前看来好像无解，只能使用history做子应用内的跳转

**Comment by marginxxx** [comment]
使用vuecli创建了一个vue2的项目（vue@2.6.11&vue-router@3.2.0），hash和history模式下都没有这个问题

**Comment by XingXiaoWu** [comment]
> 使用vuecli创建了一个vue2的项目（vue@2.6.11&vue-router@3.2.0），hash和history模式下都没有这个问题

仅vue-router@4.x下存在此问题

**Comment by JiangHao01** [comment]
我的场景是vue2的主应用，指定路由添加微应用，子应用是vue3+vue-router4，列表跳转详情，子应用bootstrap钩子会触发一次，子应用beforeEach触发多次，详情回退上一页直接undefined，与文档中描述的bootstrap只触发一次描述不一致，自应用使用vue2+vue-router3没有该问题

**Comment by XingXiaoWu** [comment]
经尝试，hash模式触发hashchange事件也是不行的

**Comment by GOGOGOSIR** [comment]
> 经尝试，hash模式触发hashchange事件也是不行的

我用的vue2.0，目前没哟问题，

**Comment by kuitos** [comment]
原因是 vue-router 3.x 在 hash 模式下，会判断当前浏览器是否支持 pushState，如果支持的话会将 hash 变更转换成 history.pushState 的方式进行变更 https://github.com/vuejs/vue-router/blob/f597959b14887cf0535aa895b6325a2f9348c5cf/src/history/hash.js#L138-L144 ，而不是通过 location.url 这种可以触发 hashchange 事件的方式。

而在 react-router 依赖的 history 的实现里，hash 模式下只监听了 hashchange 事件，也就是 react-router 只会响应能触发 hashchange 的 url 变更 https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createHashHistory.js#L308
PS ，history v5 版本已经[增加了 hash 模式下对 popstate 事件的监听](https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L684)，不过 react-router 依赖的 history 版本还停留在 v4

目前可用的解决方案：
1. 将 vue 主应用中的 Link 超链方式替换成原生的 a 标签，从而触发浏览器的 hashchange
2. 主应用跟子应用都改用 browser history 模式

**Comment by XingXiaoWu** [comment]
***@***.***下的问题，不是3.x下的问题。因为我不清楚原因，所以无法给vue-router团队提issuse，如果老哥了解详情，能否往相关团队提issuse方便问题追踪。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月13日(星期二) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/qiankun] 主应用加载子应用以后，在子页面中使用了子页面的router进行了一次页面跳转，子路由无法监听第一次浏览器的返回按钮引起的path变更 (#1280)





 
原因是 vue-router 3.x 在 hash 模式下，会判断当前浏览器是否支持 pushState，如果支持的话会将 hash 变更转换成 history.pushState 的方式进行变更 https://github.com/vuejs/vue-router/blob/f597959b14887cf0535aa895b6325a2f9348c5cf/src/history/hash.js#L138-L144 ，而不是通过 location.url 这种可以触发 hashchange 事件的方式。
 
而在 react-router 依赖的 history 的实现里，hash 模式下只监听了 hashchange 事件，也就是 react-router 只会响应能触发 hashchange 的 url 变更 https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createHashHistory.js#L308
 PS ，history v5 版本已经增加了 hash 模式下对 popstate 事件的监听，不过 react-router 依赖的 history 版本还停留在 v4
 
目前可用的解决方案：
  
将 vue 主应用中的 Link 超链方式替换成原生的 a 标签，从而触发浏览器的 hashchange
 
主应用跟子应用都改用 browser history 模式

**Comment by XingXiaoWu** [comment]
> > 使用vuecli创建了一个vue2的项目（vue@2.6.11&vue-router@3.2.0），hash和history模式下都没有这个问题
> 
> 仅[vue-router@4.x](mailto:vue-router@4.x)下存在此问题

@kuitos 阐述的问题是vue-router@4.x下发生的，我没有使用vue-router3.x版本，你在邮件中提到的方式方法我在翻阅本项目的issuse中已经看到过了 https://github.com/umijs/qiankun/issues/1199#issuecomment-757596305 。主要是4.x下的问题似乎没有可用于追踪的issuse

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1339 同一个问题，v2.4.1已解决 https://github.com/umijs/qiankun/pull/1414

**Comment by XingXiaoWu** [comment]
> #1339 同一个问题，v2.4.1已解决 #1414

thx,我等会就更新测试一下

**Comment by XingXiaoWu** [comment]
正常了，棒

**Comment by choukui** [comment]
> 我的场景是vue2的主应用，指定路由添加微应用，子应用是vue3+vue-router4，列表跳转详情，子应用bootstrap钩子会触发一次，子应用beforeEach触发多次，详情回退上一页直接undefined，与文档中描述的bootstrap只触发一次描述不一致，自应用使用vue2+vue-router3没有该问题

我也遇到同样的问题。子应用beforeEach触发多次。主应用进到列表页，从列表页进入详情页，从详情页goback回退时。路由出现undefined，请问您是怎么解决的？

**Comment by XingXiaoWu** [comment]
> > 我的场景是vue2的主应用，指定路由添加微应用，子应用是vue3+vue-router4，列表跳转详情，子应用bootstrap钩子会触发一次，子应用beforeEach触发多次，详情回退上一页直接undefined，与文档中描述的bootstrap只触发一次描述不一致，自应用使用vue2+vue-router3没有该问题
> 
> 我也遇到同样的问题。子应用beforeEach触发多次。主应用进到列表页，从列表页进入详情页，从详情页goback回退时。路由出现undefined，请问您是怎么解决的？

咱们u1s1，我是不触发，不是触发多次或者undefined，这两个场景是不一样的。

你这两个场景我也没遇到过，估计你代码写的有点问题吧。。

**Comment by 0x1af2aec8f957** [comment]
多次操作后历史记录的url后面加了个undefined？

**Comment by zdpeazy** [comment]
> 

这个问题您解决了不

**Comment by zdpeazy** [comment]
> 我的场景是vue2的主应用，指定路由添加微应用，子应用是vue3+vue-router4，列表跳转详情，子应用bootstrap钩子会触发一次，子应用beforeEach触发多次，详情回退上一页直接undefined，与文档中描述的bootstrap只触发一次描述不一致，自应用使用vue2+vue-router3没有该问题

子应用使用vue3，这个问题您解决了不？

**Comment by cuijiudai** [comment]
> 多次操作后历史记录的url后面加了个undefined？

我遇到了，解决没？

**Comment by XingXiaoWu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
好嘞~邮件我受到了~谢啦~

**Comment by Nauxscript** [comment]
> > 多次操作后历史记录的url后面加了个undefined？
> 
> 我遇到了，解决没？

我也遇到了类似的情况，在 `father` 中进入 `child` 的页面，如 `/child/a`，然后从 `/child/a` 通过 `child` 自己的 `router` 跳转，即 `router.push({path: '/b'})` 跳转到 `/child/b` 页面，这时在 `/child/b` 使用 `router.back()` 方法，会跳转到空白页面，地址栏显示的地址为 `/childundefined`

child: vue 3.2  / vue-router 4.x
father: vue 2.6.x / qiankun 2.4.8

**Comment by Alone-2** [comment]
> > > 多次操作后历史记录的url后面加了个undefined？
> > 
> > 
> > 我遇到了，解决没？
> 
> 我也遇到了类似的情况，在 `father` 中进入 `child` 的页面，如 `/child/a`，然后从 `/child/a` 通过 `child` 自己的 `router` 跳转，即 `router.push({path: '/b'})` 跳转到 `/child/b` 页面，这时在 `/child/b` 使用 `router.back()` 方法，会跳转到空白页面，地址栏显示的地址为 `/childundefined`
> 
> child: vue 3.2 / vue-router 4.x father: vue 2.6.x / qiankun 2.4.8

hello,这个问题有解决吗
