### ISSUE TITLE
ie11下子应用路由无法加载问题，chrome正常，求解答

### ISSUE THREAD

**Issue by chenxing1991** [umijs/qiankun#1281]
## What happens?
谷歌正常
![image](https://user-images.githubusercontent.com/18613090/108944782-6ebd3e00-7696-11eb-9401-e4b0062ef827.png)

ie按照以下方法配置后
![image](https://user-images.githubusercontent.com/18613090/108944642-1c7c1d00-7696-11eb-85b5-17862ceb78bb.png)

ie11下主应用可以正常加载，子应用菜单可以加载，路由内容无法加载
![image](https://user-images.githubusercontent.com/18613090/108944812-7e3c8700-7696-11eb-8261-0f13511a7c1a.png)

## 最小可复现仓库
公司内部无法上传代码

## 复现步骤，错误日志以及相关配置

配置正常

## 相关环境信息

- **qiankun 版本**"qiankun": "^2.4.0",
- **浏览器版本**：ie11
- **操作系统**：windows

**Comment by gongshun** [comment]
报错不是已经很明显了，子项目的这个路由页面写了IE不兼容的代码

![Uploading image.png…]()

**Comment by chenxing1991** [comment]
> 报错不是已经很明显了，子项目的这个路由页面写了IE不兼容的代码，应该可以直接点进去看到报错的代码
> 
> ![image](https://user-images.githubusercontent.com/29347231/108968030-367c2680-76bb-11eb-90c0-7fd6803d2986.png)

大佬  这个子应用单独启动在ie下正常，通过乾坤加载就报这个错，有什么解决办法吗

**Comment by chenxing1991** [comment]
> 报错不是已经很明显了，子项目的这个路由页面写了IE不兼容的代码，应该可以直接点进去看到报错的代码
> 
> ![image](https://user-images.githubusercontent.com/29347231/108968030-367c2680-76bb-11eb-90c0-7fd6803d2986.png)
这是我路由文件代码
![image](https://user-images.githubusercontent.com/18613090/108981926-333b6780-76c8-11eb-8679-26415681e955.png)
改成如下方式确实可行，但是不知道为什么
![image](https://user-images.githubusercontent.com/18613090/108982060-57974400-76c8-11eb-9868-9d47efbde870.png)

**Comment by gitzhaochen** [comment]
> > 报错不是已经很明显了，子项目的这个路由页面写了IE不兼容的代码，应该可以直接点进去看到报错的代码
> > ![image](https://user-images.githubusercontent.com/29347231/108968030-367c2680-76bb-11eb-90c0-7fd6803d2986.png)
> > 这是我路由文件代码
> > ![image](https://user-images.githubusercontent.com/18613090/108981926-333b6780-76c8-11eb-8679-26415681e955.png)
> > 改成如下方式确实可行，但是不知道为什么
> > ![image](https://user-images.githubusercontent.com/18613090/108982060-57974400-76c8-11eb-9868-9d47efbde870.png)

我也遇到同样的问题，路由异步组件改成同步引用就可以，还没找到原因

**Comment by gongshun** [comment]
给个复现demo看看？我这边正常 https://github.com/gongshun/qiankun-vue-demo

![1](https://user-images.githubusercontent.com/29347231/109251766-02be0f80-7827-11eb-9f90-0d1b91532b0b.gif)

**Comment by gitzhaochen** [comment]
> 给个复现demo看看？我这边正常 https://github.com/gongshun/qiankun-vue-demo
> 

@chenxing1991 @gongshun 我这边问题解决了，步骤如下：

1. ie11下start不能用experimentalStyleIsolation
2. main.js入口增加这个currentScript的[polyfill](https://github.com/amiller-gh/currentScript-polyfill)，而且改它的configurable:true

**Comment by chenxing1991** [comment]
@gitzhaochen 这个是加在主应用吗？具体怎么修改能否截个图，谢谢
> 1. ie11下start不能用experimentalStyleIsolation
> 2. main.js入口增加这个currentScript的[polyfill](https://github.com/amiller-gh/currentScript-polyfill)，而且改它的configurable:true

**Comment by gitzhaochen** [comment]
> @gitzhaochen 这个是加在主应用吗？具体怎么修改能否截个图，谢谢
![image](https://user-images.githubusercontent.com/22151961/109488605-bf7ecd80-7ac0-11eb-8bc1-700b364c3ef0.png)
![image](https://user-images.githubusercontent.com/22151961/109488677-d3c2ca80-7ac0-11eb-8cd2-2905e9ac400e.png)

**Comment by guokewei** [comment]
@gongshun  IE11 没问题，IE10，IE9 在你那里能兼容吗？

**Comment by gongshun** [comment]
> @gongshun IE11 没问题，IE10，IE9 在你那里能兼容吗？

我没试过，不清楚

**Comment by aique127** [comment]
意思是experimentalStyleIsolation: true不兼容ie吗

**Comment by aique127** [comment]
> @gitzhaochen 这个是加在主应用吗？具体怎么修改能否截个图，谢谢
> 
> > 1. ie11下start不能用experimentalStyleIsolation
> > 2. main.js入口增加这个currentScript的[polyfill](https://github.com/amiller-gh/currentScript-polyfill)，而且改它的configurable:true

你好，意思是experimentalStyleIsolation: true不兼容ie11吗，我遇到了类似问题，设置样式隔离，在ie11加载不出子应用
