### ISSUE TITLE
[Bug] yarn examples:install报循环依赖

### ISSUE THREAD

**Issue by yuki070** [umijs/qiankun#1282]
## What happens?

`yarn examples:install`出现循环依赖的告警

![image](https://user-images.githubusercontent.com/656768/108955156-a6cd7c80-76a8-11eb-8eeb-5c1bd500b46f.png)

## 最小可复现仓库

```
# clone qiankun 代码库，按照官网执行

$ yarn examples:install
```

## 相关环境信息

- **qiankun 版本**：2.4.0
- **浏览器版本**：无
- **操作系统**：Windows

**Comment by gongshun** [comment]
的确存在文件循环引用，不过不影响使用

**Comment by fanguangjian** [comment]
![image](https://user-images.githubusercontent.com/26645436/121640581-74b61e00-cad1-11eb-8c21-d336dcf9f1ff.png)

yarn examples:install
yarn run v1.22.10
$ npm-run-all --serial build install:*
/bin/sh: npm-run-all: command not found
error Command failed with exit code 127.
