### ISSUE TITLE
进入微应用后，url不能输入中文，输入后主应用就奔溃了

### ISSUE THREAD

**Issue by chenzhenjin** [umijs/qiankun#1285]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by chenzhenjin** [comment]
开发环境可以，但是打包环境下不行

**Comment by chenzhenjin** [comment]
能否私聊下，主要是公司项目不允许上传，我可以提供链接，我看到devtools报警告是由于路由陷入循环，浏览器被挂起，以下是警告信息：Throttling navigation to prevent the browser from hanging. See <URL>. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection

**Comment by gongshun** [comment]
有没有用 vue-router ， vue-router 某些版本的确存在这个 bug，更换其他版本或者输入url之前转码一下

**Comment by chenzhenjin** [comment]
有的，我试试排查下

**Comment by chenzhenjin** [comment]
谢谢大佬，排查出来了，vue-router3.0.1有问题，升级到3.0.6就好了
