### ISSUE TITLE
父应用集成多个子应用路由配置疑惑

### ISSUE THREAD

**Issue by xiaoqiangz** [umijs/qiankun#1286]
请教下： 目前是多个子应用集成至基座里，基座里左侧会有统一的菜单栏，子应用内容会展示在右侧区域。
                 那么所有子应用的路由是否都得在基座里全部配置一遍呢？如果不是想请教下是如何做的。 
                                                                                                                                                                          谢谢！

**Comment by gongshun** [comment]
不需要，参考 https://github.com/gongshun/qiankun-vue-demo/blob/feature/keep-alive/main/src/App.vue

**Comment by PHenryy** [comment]
https://github.com/PHenryy/qiankun-template

**Comment by q350241636** [comment]
> 不需要，参考 https://github.com/gongshun/qiankun-vue-demo/blob/feature/keep-alive/main/src/App.vue

意思是只需要配置菜单，不需要配置路由中是吗
