### ISSUE TITLE
angular10作为主应用页面如果切换的比较快会出现路由不停的跳转进入死循环

### ISSUE THREAD

**Issue by hanyi0121** [umijs/qiankun#1291]
## What happens?

 路由不停跳转，进入死循环状态，刷新页面才能停止页面不停跳转

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.4.0
- **Platform Version**: angular10
- **Browser Version**:10.0.5

**Comment by jwangkun** [comment]
我的也是

**Comment by wudith** [comment]
angular9也有这个问题，我们是采用防抖来规避，但还是希望官方定位原因

**Comment by hanyi0121** [comment]
> angular9也有这个问题，我们是采用防抖来规避，但还是希望官方定位原因

怎么防抖的教教我呗

**Comment by hanyi0121** [comment]
> Hello @hanyi0121. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @hanyi0121, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

微应用还没调用，angular普通的脚手架建的项目，只要代码里引了qiankun就会出这个问题

**Comment by hanyi0121** [comment]
已解决

**Comment by bluehymn** [comment]
遇到同样的问题，怀疑跟zone有关系

**Comment by bluehymn** [comment]
升级了 single-spa 问题解决了

**Comment by yxxuweb** [comment]
> 已解决

请问下怎么解决？

**Comment by Xiaoxiasuper** [comment]
> angular9也有这个问题，我们是采用防抖来规避，但还是希望官方定位原因

浏览器前进后退也有同样问题，请问有好的解决办法吗

**Comment by gongshun** [comment]
> 浏览器前进后退也有同样问题，请问有好的解决办法吗

前进后退，应该和这个是一样的原因 https://github.com/umijs/qiankun/issues/1339

**Comment by hanyi0121** [comment]
> > 已解决
> 
> 请问下怎么解决？

我这边是加了这个方法解决的

**Comment by Ivy1994** [comment]
我的代码里面之前就有这部分import { getSingleSpaExtraProviders } from 'single-spa-angular';
platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule)
.catch(err => console.error(err));
但是快速切换的时候，依然会跳入死循环。请问，你还做了其他修改吗？

**Comment by Tinet-zhangmd** [comment]
> 已解决

请问怎么解决的？

**Comment by Tinet-zhangmd** [comment]
> 我的代码里面之前就有这部分import { getSingleSpaExtraProviders } from 'single-spa-angular'; platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule) .catch(err => console.error(err)); 但是快速切换的时候，依然会跳入死循环。请问，你还做了其他修改吗？

请问最后解决了么

**Comment by lionzhong** [comment]
压根就没解决
