### ISSUE TITLE
希望生命周期函数增加 挂载微应用失败的钩子函数

### ISSUE THREAD

**Issue by rawKylin** [umijs/qiankun#1293]
希望大佬增加挂载失败的钩子函数，类似beforeUnmount，在该回调中，前端可以跳转404页面或者做其他操作。

**Comment by gongshun** [comment]
为什么会挂载微应用失败呢？如果是请求出错，自定义 fetch 可以处理错误。能举两个实际场景吗

**Comment by PanYX** [comment]
我这边也有一些场景希望能增加一些钩子，希望能在卸载应用时做些检查。大概的场景有点类似浏览器标签页，需要手动管理微应用的场景下，如果用户点击一个按钮关闭一个微应用，主应用在卸载前需要微应用自己的逻辑先check是否符合关闭应用的条件，如果符合则由主应用继续卸载，如果不符合，则弹窗告知用户，并停止卸载应用。
目前我这边通过在unmount钩子里返回 reject来测试，发现可以阻止卸载应用，但再手动卸载就不生效了，需要先手动mount才能卸载。
所以希望能想问问这种场景目前有什么办法可以解决吗？如果没有，能不能考虑下增加自定义钩子的注册，或者通过在现有钩子返回 reject 这种形式中断原来的流程？

**Comment by PanYX** [comment]
> 为什么会挂载微应用失败呢？如果是请求出错，自定义 fetch 可以处理错误。能举两个实际场景吗

我这边也有一些场景希望能增加一些钩子，希望能在卸载应用时做些检查。大概的场景有点类似浏览器标签页，在手动管理微应用的场景下，如果用户点击一个按钮关闭一个微应用，主应用在卸载前需要微应用自己的逻辑先check是否符合关闭应用的条件，如果符合则由主应用继续卸载，如果不符合，则弹窗告知用户，并停止卸载应用。
目前我这边通过在unmount钩子里返回 reject来测试，发现可以阻止卸载应用，但再手动卸载就不生效了，需要先手动mount才能卸载。
所以想问问这种场景目前有什么办法可以解决吗？如果没有，能不能考虑下增加自定义钩子的注册，或者通过在现有钩子返回 reject 这种形式中断原来的流程？

**Comment by bravepg** [comment]
> > 为什么会挂载微应用失败呢？如果是请求出错，自定义 fetch 可以处理错误。能举两个实际场景吗
> 
> 我这边也有一些场景希望能增加一些钩子，希望能在卸载应用时做些检查。大概的场景有点类似浏览器标签页，在手动管理微应用的场景下，如果用户点击一个按钮关闭一个微应用，主应用在卸载前需要微应用自己的逻辑先check是否符合关闭应用的条件，如果符合则由主应用继续卸载，如果不符合，则弹窗告知用户，并停止卸载应用。 目前我这边通过在unmount钩子里返回 reject来测试，发现可以阻止卸载应用，但再手动卸载就不生效了，需要先手动mount才能卸载。 所以想问问这种场景目前有什么办法可以解决吗？如果没有，能不能考虑下增加自定义钩子的注册，或者通过在现有钩子返回 reject 这种形式中断原来的流程？

可以贴个代码看看你现在的使用姿势么？

「如果用户点击一个按钮关闭一个微应用」在这种场景下，我理解如果 check 不符合的话，直接 return，不走之后的卸载逻辑就行了吧。

**Comment by PanYX** [comment]
`https://codesandbox.io/p/github/PanYX/qiankun/master?file=%2Fexamples%2Freact15%2Findex.js%3A43%2C11&workspaceId=7be03a1d-a42a-437e-95e9-33f6b0ef6282`  这里有一个codesandbox，不知道你能不能访问？`https://p7whys-7099.csb.app/` 这个地址可以看效果，卸载两次就可以看到卸载无效了。
改动的地方在这里：
<img width="1920" alt="image" src="https://github.com/umijs/qiankun/assets/9074364/f1a3f516-c463-4e18-a612-f4f5357fa950">

我试过直接return，这时qiankun是默认unmount没有发生错误，会直接走后面的卸载逻辑的

**Comment by bravepg** [comment]
> [codesandbox](https://codesandbox.io/p/github/PanYX/qiankun/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls6vexus0006356h8omzuhdz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls6vexus0002356hegc83z66%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0001356ho79x8oip%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0001356ho79x8oip%2522%257D%252C%2522cls6vexus0005356h0mjva1ix%2522%253A%257B%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%252C%2522activeTabId%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7099%252C%2522id%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7102%252C%2522id%2522%253A%2522cls6vi5le0080356hx5azwhl9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7101%252C%2522id%2522%253A%2522cls6vi710009n356h2phr8cse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls6vexus0004356hszsq8vaj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls1mz3p30006dqikfgsk9434%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10.7421875%257D) 这里有一个codesandbox，不知道你能不能访问？`https://p7whys-7099.csb.app/` 这个地址可以看效果，卸载两次就可以看到卸载无效了。 改动的地方在这里： <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/9074364/302072826-f1a3f516-c463-4e18-a612-f4f5357fa950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTk5NzQsIm5iZiI6MTcwNzA5OTY3NCwicGF0aCI6Ii85MDc0MzY0LzMwMjA3MjgyNi1mMWEzZjUxNi1jNDYzLTRlMTgtYTYxMi1mNGY1MzU3ZmE5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDIyMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI5MzNmM2Y4NzJhYjY1ODFlYjJhZjQ5ZTZmNTg5MGFlNDM0Y2JhNWZiMjkxZGEzNDdlNDY2NWY2MWI0NjBkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RRUHbCffRmaNg6imqemjunVGLpZjs3UWX1zhXNQKD1s">
> 
> 我试过直接return，这时qiankun是默认unmount没有发生错误，会直接走后面的卸载逻辑的


虽然你 return 了，但是底层其实还是走了 qiankun 的 unmount 机制，你可以打印 `console.log(app.mount)` 来验证下。

合理的阻止 unmount 的方式应该是「左侧主应用不调用 app.unmount()」
![image](https://github.com/umijs/qiankun/assets/22069371/73ed22bf-6b53-4b59-8712-61acb173fbdf)

**Comment by PanYX** [comment]
是的，unmount的时候还是调用了底层的unmount逻辑。我期望的效果其实就是像浏览器标签页关闭之前有个beforeunload 类似的机制，感觉也符合微应用的功能吧？还是说这种逻辑对于qiankun来说实现成本较大，不会考虑增加？

如果确实不好实现，我感觉只能主应用卸载前先postmessage通知微应用自行check了

**Comment by PanYX** [comment]
> > [codesandbox](https://codesandbox.io/p/github/PanYX/qiankun/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls6vexus0006356h8omzuhdz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls6vexus0002356hegc83z66%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0001356ho79x8oip%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0001356ho79x8oip%2522%257D%252C%2522cls6vexus0005356h0mjva1ix%2522%253A%257B%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%252C%2522activeTabId%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7099%252C%2522id%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7102%252C%2522id%2522%253A%2522cls6vi5le0080356hx5azwhl9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7101%252C%2522id%2522%253A%2522cls6vi710009n356h2phr8cse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls6vexus0004356hszsq8vaj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls1mz3p30006dqikfgsk9434%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10.7421875%257D) 这里有一个codesandbox，不知道你能不能访问？`https://p7whys-7099.csb.app/` 这个地址可以看效果，卸载两次就可以看到卸载无效了。 改动的地方在这里： <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/9074364/302072826-f1a3f516-c463-4e18-a612-f4f5357fa950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTk5NzQsIm5iZiI6MTcwNzA5OTY3NCwicGF0aCI6Ii85MDc0MzY0LzMwMjA3MjgyNi1mMWEzZjUxNi1jNDYzLTRlMTgtYTYxMi1mNGY1MzU3ZmE5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDIyMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI5MzNmM2Y4NzJhYjY1ODFlYjJhZjQ5ZTZmNTg5MGFlNDM0Y2JhNWZiMjkxZGEzNDdlNDY2NWY2MWI0NjBkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RRUHbCffRmaNg6imqemjunVGLpZjs3UWX1zhXNQKD1s">
> 
> > 
> 
> > 我试过直接return，这时qiankun是默认unmount没有发生错误，会直接走后面的卸载逻辑的
> 
> 
> 
> 
> 
> 虽然你 return 了，但是底层其实还是走了 qiankun 的 unmount 机制，你可以打印 `console.log(app.mount)` 来验证下。
> 
> 
> 
> 合理的阻止 unmount 的方式应该是「左侧主应用不调用 app.unmount()」
> 
> ![image](https://github.com/umijs/qiankun/assets/22069371/73ed22bf-6b53-4b59-8712-61acb173fbdf)
> 
> 

是的，unmount的时候还是调用了底层的unmount逻辑。我期望的效果其实就是像浏览器标签页关闭之前有个beforeunload 类似的机制，感觉也符合微应用的功能吧？还是说这种逻辑对于qiankun来说实现成本较大，不会考虑增加？

如果确实不好实现，我感觉只能主应用卸载前先postmessage通知微应用自行check了

**Comment by bravepg** [comment]
> > > [codesandbox](https://codesandbox.io/p/github/PanYX/qiankun/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls6vexus0006356h8omzuhdz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls6vexus0002356hegc83z66%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0001356ho79x8oip%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0002356hegc83z66%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0001356ho79x8oip%2522%257D%252C%2522cls6vexus0005356h0mjva1ix%2522%253A%257B%2522id%2522%253A%2522cls6vexus0005356h0mjva1ix%2522%252C%2522activeTabId%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7099%252C%2522id%2522%253A%2522cls6vi5jb006x356h5ivee2mt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7102%252C%2522id%2522%253A%2522cls6vi5le0080356hx5azwhl9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A7101%252C%2522id%2522%253A%2522cls6vi710009n356h2phr8cse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls6vexus0004356hszsq8vaj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls1mz3p30006dqikfgsk9434%2522%257D%255D%252C%2522id%2522%253A%2522cls6vexus0004356hszsq8vaj%2522%252C%2522activeTabId%2522%253A%2522cls6vexus0003356hksu4wkqt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10.7421875%257D) 这里有一个codesandbox，不知道你能不能访问？`https://p7whys-7099.csb.app/` 这个地址可以看效果，卸载两次就可以看到卸载无效了。 改动的地方在这里： <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/9074364/302072826-f1a3f516-c463-4e18-a612-f4f5357fa950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTk5NzQsIm5iZiI6MTcwNzA5OTY3NCwicGF0aCI6Ii85MDc0MzY0LzMwMjA3MjgyNi1mMWEzZjUxNi1jNDYzLTRlMTgtYTYxMi1mNGY1MzU3ZmE5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDIyMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI5MzNmM2Y4NzJhYjY1ODFlYjJhZjQ5ZTZmNTg5MGFlNDM0Y2JhNWZiMjkxZGEzNDdlNDY2NWY2MWI0NjBkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RRUHbCffRmaNg6imqemjunVGLpZjs3UWX1zhXNQKD1s">
> > 
> > 
> > > 
> > 
> > 
> > > 我试过直接return，这时qiankun是默认unmount没有发生错误，会直接走后面的卸载逻辑的
> > 
> > 
> > 虽然你 return 了，但是底层其实还是走了 qiankun 的 unmount 机制，你可以打印 `console.log(app.mount)` 来验证下。
> > 合理的阻止 unmount 的方式应该是「左侧主应用不调用 app.unmount()」
> > ![image](https://private-user-images.githubusercontent.com/22069371/302160524-73ed22bf-6b53-4b59-8712-61acb173fbdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDI0ODMsIm5iZiI6MTcwNzEwMjE4MywicGF0aCI6Ii8yMjA2OTM3MS8zMDIxNjA1MjQtNzNlZDIyYmYtNmI1My00YjU5LTg3MTItNjFhY2IxNzNmYmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAzMDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OWJlNzFkYTRkMWYwMmFlODlhZWM4YmQ3YThhZTYxODdlY2FhZTBkYTI4MzYzMWQ4MWJjMjU0Y2EzZGQ2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LxN4VGGL8tcYh1tqR0W69QsmNyRdzBN02M_CGlFAm2c)
> 
> 是的，unmount的时候还是调用了底层的unmount逻辑。我期望的效果其实就是像浏览器标签页关闭之前有个beforeunload 类似的机制，感觉也符合微应用的功能吧？还是说这种逻辑对于qiankun来说实现成本较大，不会考虑增加？
> 
> 如果确实不好实现，我感觉只能主应用卸载前先postmessage通知微应用自行check了

好像是个合理的诉求，你觉得呢？@kuitos 

目前插件都是顺序执行的，没有感知到上一个的结果。可以搞成 tapable 那种感知结果的能力？
![image](https://github.com/umijs/qiankun/assets/22069371/126cd13f-5cc6-48d1-810d-8501b00cb38f)

**Comment by kuitos** [comment]
> 如果用户点击一个按钮关闭一个微应用，主应用在卸载前需要微应用自己的逻辑先check是否符合关闭应用的条件，如果符合则由主应用继续卸载，如果不符合，则弹窗告知用户，并停止卸载应用。

这个职责划分就不合理，就跟你要关闭一个弹框，却让弹框自己做一些检查阻止关闭；跳转路由，却让跳转后的路由页面来阻止跳转一样。

正确的做法应该是谁触发谁检查，检查通过了才去做后续操作。如果你期望检查操作是在子应用中定义实现的，那可以走通信方案，子应用注册一个 precheck 方法给主应用，但是调用还是由主应用触发。

**Comment by PanYX** [comment]
> > 如果用户点击一个按钮关闭一个微应用，主应用在卸载前需要微应用自己的逻辑先check是否符合关闭应用的条件，如果符合则由主应用继续卸载，如果不符合，则弹窗告知用户，并停止卸载应用。
> 
> 
> 
> 这个职责划分就不合理，就跟你要关闭一个弹框，却让弹框自己做一些检查阻止关闭；跳转路由，却让跳转后的路由页面来阻止跳转一样。
> 
> 
> 
> 正确的做法应该是谁触发谁检查，检查通过了才去做后续操作。如果你期望检查操作是在子应用中定义实现的，那可以走通信方案，子应用注册一个 precheck 方法给主应用，但是调用还是由主应用触发。

我的想法也是谁触发谁检查，所以一开始想在微应用挂类似beforeunmount之类的钩子，主应用在unmount之前去app.beforeunmount，但目前看应该是不支持自定义钩子，也不允许调用app.unmount后中断unmount流程

**Comment by kuitos** [comment]
不应该调生命周期钩子应该走通信方案，甚至严格来说，precheck 逻辑写到子应用里其实就是有问题的(想象一下你会在弹框里写阻止弹框的检查逻辑吗)
