### ISSUE TITLE
【求助】主应用svelteJS+子应用Vue

### ISSUE THREAD

**Issue by kelly138** [umijs/qiankun#1294]
# 问题概述
主应用是svelteJS，子应用是Vue，主应用不知到该怎么配置
# 代码片段
```js
// 主应用的main.js
import App from './App.svelte';

const app = new App({
	target: document.body,
});

export default app;
```
# 相关版本
- qiankun Version: v2.3.6
- svelte Version: v3.31.2
- vue Version: v2.6.12
# 另
第一次在github上问问题，有不对的地方还请包容下。
主应用配置的问题还请各位指点一下

**Comment by gongshun** [comment]
主应用不需要配置呀，直接引入qiankun，然后注册子应用就行了

https://qiankun.umijs.org/zh/guide/tutorial#%E4%B8%BB%E5%BA%94%E7%94%A8

**Comment by kelly138** [comment]
> 主应用不需要配置呀，直接引入qiankun，然后注册子应用就行了
> 
> https://qiankun.umijs.org/zh/guide/tutorial#%E4%B8%BB%E5%BA%94%E7%94%A8

感谢指点~

我试了下直接引入使用，但是会报错
![image](https://user-images.githubusercontent.com/40594275/109781795-2a581200-7c43-11eb-8296-8fe2cbb33264.png)

是我哪个地方写错了嘛？

main.js引入代码如下：
```js
import App from './App.svelte';
import { registerMicroApps, start } from 'qiankun';

const app = new App({
	target: document.body,
});

registerMicroApps([
  {
    name: 'dataAudit',
    entry: '//localhost:6882',
    container: '#yourContainer', // 这个地方是在引入的App.svelte里面写了一个id是yourContainer的div容器
    activeRule: '/data-audit',
  }
]);
// 启动 qiankun
start();

export default app;

```

**Comment by kelly138** [comment]
> 主应用不需要配置呀，直接引入qiankun，然后注册子应用就行了
> 
> https://qiankun.umijs.org/zh/guide/tutorial#%E4%B8%BB%E5%BA%94%E7%94%A8

找到了那个错误了，由于主应用是rollup打包，所以自己需要在打包配置里加一个process,然后加到bundle.js文件里~
```js
const Global = `var process = {
  env: {
    NODE_ENV: 'production'
  }
};`
...
export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js',
		banner: Global
	},
...
}
...
```
