### ISSUE TITLE
两个vue的独立app app1和app2的组件命名一样 组件内的scpoe样式会被复用

### ISSUE THREAD

**Issue by Power-kxLee** [umijs/qiankun#1295]
## What happens?

两个vue独立运行的app ，主应用是app1 微应用是app2 
app1 和 app2 分别都有一个组件 命名为helloword.vue 
微应用app2的helloword组件 我添加样式
```
<style lang="scss" scoped >
.hello {
  &::before{
    content: "";
    display: block;
    height: 2px;
    width: 100%;
    background: black;
  }
}
```
那么 我app1下的helloword组件有类名是`.hello`的时候 也会一样有效

我看了下页面挂载后的代码 两个helloword组件下的scope的命名都是一样的
![image](https://user-images.githubusercontent.com/13028354/109745109-54dba800-7c0e-11eb-9e55-b789ef734368.png)

理想的情况：
就是两个独立项目的相同命名组件 样式不被复用
请问有什么解决办法吗

## 相关环境信息

- **qiankun 版本**: 2.4
- **浏览器版本**： chorme71
- **操作系统**：win10

**Comment by johnbian** [comment]
+1

**Comment by poorli** [comment]
https://github.com/umijs/qiankun/issues/1318#issuecomment-798521078

文档里面有样式隔离方案，可以使用啊

**Comment by gongshun** [comment]
这是 `vue-loader` 自己的机制问题，两个组件的引用路径相同时，hash 值也是相同的。

所以你要么将文件名称或者文件夹名称修改一下，让他们的引用路径不同，要么修改 `vue-loader` 的代码中 hash 值的生成方式

![image](https://user-images.githubusercontent.com/29347231/112286976-d7fc9500-8cc6-11eb-8682-3ed4524ed803.png)
