### ISSUE TITLE
主项目使用vue3.0 ， 子项目使用ts+react  ， 刷新报错

### ISSUE THREAD

**Issue by yulintianxia** [umijs/qiankun#1299]
主项目使用vue3.0，子项目使用ts+react，使用create-react-app脚手架，而后使用react-app-rewired命令时，看了issure，将
![image](https://user-images.githubusercontent.com/44962371/109928852-d7449480-7d00-11eb-8aef-64e821ac857c.png)
取消了热更新，项目刷新就报错，
![image](https://user-images.githubusercontent.com/44962371/109929030-107d0480-7d01-11eb-88a1-71169b54225a.png) 这样修改报错，config.entry.filter 不是一个function，
![image](https://user-images.githubusercontent.com/44962371/109929271-3f937600-7d01-11eb-853a-7d35388e9aff.png)打印发现不是一个数组，但是去掉这句话，react项目刷新报错

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/340#issuecomment-750745690

**Comment by yulintianxia** [comment]
把端口写进去也不行，感觉应该是版本的问题，我的vue 3.0+ts是最新的版本，react 项目使用的creat-react-app + ts官方脚手架，最新版本17，安装最新的react-app-rewired 可能最新版本改动，按照const { name } = require("./package.json");
const ReactRefreshPlugin = require("@pmmmwh/react-refresh-webpack-plugin");
const webpack = require("webpack");

module.exports = {
webpack: function override(config, env) {
config.output.library = ${name}-[name];
config.output.libraryTarget = "umd";
config.output.jsonpFunction = webpackJsonp_${name};

// Remove 'react-refresh' from the loaders.
for (const rule of config.module.rules) {
  if (!rule.oneOf) continue;

  for (const one of rule.oneOf) {
    if (one.loader && one.loader.includes("babel-loader") && one.options && one.options.plugins) {
      one.options.plugins = one.options.plugins.filter(
        (plugin) => typeof plugin !== "string" || !plugin.includes("react-refresh")
      );
    }
  }
}

config.plugins = config.plugins.filter(
  (plugin) => !(plugin instanceof webpack.HotModuleReplacementPlugin) && !(plugin instanceof ReactRefreshPlugin)
);

return config;
},
devServer: (configFunction) => {
return function (proxy, allowedHost) {
const config = configFunction(proxy, allowedHost);
config.open = false;
config.hot = false;
config.headers = {
"Access-Control-Allow-Origin": "*",
};
return config;
};
},
}; 这个写法就Ok了
