### ISSUE TITLE
关于父子系统的样式隔离

### ISSUE THREAD

**Issue by ibufu** [umijs/qiankun#13]
有没有什么方法做到父子系统的样式隔离呢？

**Comment by daihaoxin** [comment]
https://github.com/umijs/qiankun/issues/7

**Comment by kuitos** [comment]
思路就是主应用确保自己的样式表足够 specific，且尽量不要依赖 body 这些全局样式

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#how-to-guarantee-the-main-app-stylesheet-isolated-with-sub-apps
