### ISSUE TITLE
微应用内部路由切换，DOM渲染慢，页面呈现卡顿现象，但是微应用独立运行时切换速度正常

### ISSUE THREAD

**Issue by DoloresY** [umijs/qiankun#1301]
微应用独立启动运行时，切换路由，页面切换速度正常。但是放到主应用中进行微应用内部的路由切换，路由变化很快，但是DOM要过3s左右的时间才渲染上。
麻烦知道的大神指教指教，多谢！

**Comment by coalo** [comment]
有线上访问地址吗？

**Comment by Clive-Wang** [comment]
`<keep-alive>
			<router-view />
		</keep-alive>`

**Comment by DoloresY** [comment]
> `<keep-alive> <router-view /> </keep-alive>`

这样的话页面就不在重新请求了

**Comment by LemonBabyluo** [comment]
我也遇到了这个问题，跟标题描述的一模一样！请问有解决办法吗？

**Comment by web-wgf** [comment]
+1

**Comment by Clive-Wang** [comment]
> `<keep-alive> <router-view /> </keep-alive>`

我也是同样的问题，来回切换的时候特别卡。

**Comment by DoloresY** [comment]
希望官方能够尽快解决这个问题，现在项目都无法向前推进了

**Comment by ShanaFang00** [comment]
dom多的时候，首次渲染很慢；还有dom交互很多的时候，卡顿特别明显；单独运行时速度会正常很多，官方有解决方案不？

**Comment by DoloresY** [comment]
> dom多的时候，首次渲染很慢；还有dom交互很多的时候，卡顿特别明显；单独运行时速度会正常很多，官方有解决方案不？

希望官方早点出解决方案

**Comment by Aaronlamz** [comment]
遇到同样的问题，简直无法使用了。

**Comment by LegendTian** [comment]
这个问题大家都怎么解决的，我也遇到同样问题。。。。
