### ISSUE TITLE
[Bug]所有微应用采用hash模式，无法准确区分activeRule

### ISSUE THREAD

**Issue by mybedhome** [umijs/qiankun#1307]
## What happens?

主应用和微应用均采用hash模式的微应用之间跳转问题，比如从微应用/#/app1/about页面跳转到另一个微应用页面时，路由变成了这样/#/app1/app2；跳转代码是这样的`history.push('/app2')`；因为微应用都设置了`base`，所以在跳转前会自动加上当前微应用的`base`前缀；这样没法准确区分`activeRule`，请问这种问题怎么处理？

## 相关环境信息

- **qiankun 版本**: 2.4.0
- **浏览器版本**：chrome 88.0.4324.190
- **操作系统**：win10家庭版

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BD%AC%EF%BC%9F

**Comment by hanalice** [comment]
@mybedhome 后面是如何解决的呢？

**Comment by mybedhome** [comment]
> @mybedhome 后面是如何解决的呢？

3年前的事了，忘记了
