### ISSUE TITLE
请问qiankun现阶段版本能支持一个父view同时展示多个子应用view吗？如果不能支持，后续会增加这个功能吗？

### ISSUE THREAD

**Issue by a052022215** [umijs/qiankun#1310]
例如：有一个父页面，左边是菜单列表，右边上半部分是子项目A的展示区域，右边下半部分是子项目B的展示区域。而且A、B是同时呈现在父页面中的。

**Comment by gongshun** [comment]
- 办法1：registerMicroApps 注册时两个子应用使用相同的activeRule，但使用不同的 container，并且设置 singular 值为 false
```
registerMicroApps([
  { 
    name: 'app1', 
    entry: 'http://localhost:1111', 
    container: '#container1', 
    activeRule: '/app1', 
  },
  { 
    name: 'app2',
    entry: 'http://localhost:2222', 
    container: '#container2', 
    activeRule: '/app1',
  },
]);

start({singular: true});
```
![image](https://user-images.githubusercontent.com/29347231/110564514-ece60e00-8187-11eb-9de2-45b04694470a.png)

- 办法2：直接使用两次 loadMicroApp ，使用不同的 container 分别加载两个子应用

其他注意的点：

![image](https://user-images.githubusercontent.com/29347231/110564647-2a4a9b80-8188-11eb-88b3-c807b121fbd7.png)
