### ISSUE TITLE
[RFC] 一主多子应用通信问题

### ISSUE THREAD

**Issue by amsterdam-littlehill** [umijs/qiankun#1311]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址
问题1：状态共享，多个应用之间存在数据耦合

主应用创建共享状态：

```ts
import { initGloabalState } from 'qiankun';

initGloabalState({ user: 'kuitos' });
```

微应用通过 props 获取共享状态并监听：

```ts
export function mount(props) {
  props.onGlobalStateChange((state, prevState) => {
    console.log(state, prevState);
  });
};
```

问题2：一个子应用修改全局state，父应用监听器多次触发

![image](https://user-images.githubusercontent.com/13325067/110564649-2c145f00-8188-11eb-9118-9313a8c28fc7.png)

问题3：一个主应用使用initGlobalState初始化状态，手动加载多个子应用并使用setGlobalState修改状态，主应用中如何区分是谁修改的。

问题4：一个主应用，手动加载多个子应用，子应用如何调用父应用的函数？–同问题3
## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by poorli** [comment]
问题1：状态共享，多个应用之间存在数据耦合

目前通信机制，通过数据共享来解决通信问题，没太理解你说的数据耦合。

问题2：一个子应用修改全局state，父应用监听器多次触发

没发现多次触发啊，是不是写的有问题，你是怎么写的

问题3：一个主应用使用initGlobalState初始化状态，手动加载多个子应用并使用setGlobalState修改状态，主应用中如何区分是谁修改的。

你可以把 user 当成一个标识，每个子应用定义唯一标识，这样就知道是哪个子应用发的消息

问题4：一个主应用，手动加载多个子应用，子应用如何调用父应用的函数？–同问题3

通过 setGlobalState 把需要用的方法放 state 里面传给子应用，子应用就能使用了。

**Comment by 16slowly** [comment]
请问问题2、3 是怎么做到的，现在项目里子应用使用 setGlobalState 修改状态，父应用的 onGlobalStateChange 监听不到

**Comment by poorli** [comment]
> 请问问题2、3 是怎么做到的，现在项目里子应用使用 setGlobalState 修改状态，父应用的 onGlobalStateChange 监听不到

你跑下官方的 demo

**Comment by miroku-y** [comment]
> > 请问问题2、3 是怎么做到的，现在项目里子应用使用 setGlobalState 修改状态，父应用的 onGlobalStateChange 监听不到
> 
> 你跑下官方的 demo

官方能否给一个子应用之间的通信demo ,如：
1.将官方demo 的React 15 作为一个公共头部，它不在是一个菜单子项，而是作为一个所有菜单公共的header；
2.此时在vue3 应用中去和React15 应用进行通信 ；

**Comment by poorli** [comment]
> > > > 请问问题2、3 是怎么做到的，现在项目里子应用使用 setGlobalState 修改状态，父应用的 onGlobalStateChange 监听不到
> > > 
> > > 
> > > 你跑下官方的 demo
> > 
> > 
> > 官方能否给一个子应用之间的通信demo ,如： 1.将官方demo 的React 15 作为一个公共头部，它不在是一个菜单子项，而是作为一个所有菜单公共的header； 2.此时在vue3 应用中去和React15 应用进行通信 ；
> 
> 同求

你是遇到什么问题了吗？

**Comment by poorli** [comment]
> > > 请问问题2、3 是怎么做到的，现在项目里子应用使用 setGlobalState 修改状态，父应用的 onGlobalStateChange 监听不到
> > 
> > 
> > 你跑下官方的 demo
> 
> 官方能否给一个子应用之间的通信demo ,如： 1.将官方demo 的React 15 作为一个公共头部，它不在是一个菜单子项，而是作为一个所有菜单公共的header； 2.此时在vue3 应用中去和React15 应用进行通信 ；

demo 里面这个就是啊。子应用调用 setGlobalState，主应用和其他子应用都能收到

function storeTest(props) {
  props.onGlobalStateChange &&
    props.onGlobalStateChange(
      (value, prev) => console.log(`[onGlobalStateChange - ${props.name}]:`, value, prev),
      true,
    );
  props.setGlobalState &&
    props.setGlobalState({
      ignore: props.name,
      user: {
        name: props.name,
      },
    });
}
