### ISSUE TITLE
import defer script in head maybe err:[qiankun] You need to export lifecycle functions in *** entry.

### ISSUE THREAD

**Issue by rawKylin** [umijs/qiankun#1312]
## What happens?

I had created an usable subApp ,and worked in baseApp. But after I used webpack5 ModuleFederationPlugin, qiankun err msg noticed me "Uncaught Error: application '***' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in *** entry". I find when I use ModuleFederationPlugin, the index.html head will add a script that remoteEntry.js, delete the script, subApp still useable in baseApp. It works, but not flexable. 
Do you have more flexable methods 

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.3.5
- **Platform Version**: macOS Big Sur 11.2
- **Browser Version**: chrome 89

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1092#issuecomment-794755821
