### ISSUE TITLE
[Bug]微应用加载失败时会不停加载死循环

### ISSUE THREAD

**Issue by BiliBiliWTP** [umijs/qiankun#1315]
## What happens?
在同服务器部署前提下，主应用去打开一个尚未部署的微应用，如访问 /micro/app1，如果app1微应用尚未部署，页面就会不停重载

**Comment by gongshun** [comment]
这是你的服务器配置问题，这个应用未部署，也就是404，但是你配置了404返回 index.html

**Comment by mizhon** [comment]
> 这是你的服务器配置问题，这个应用未部署，也就是404，但是你配置了404返回 index.html

不太理解这个服务器配置问题的具体含义，我也遇到相同的问题，比如在未接入微应用的前提下只调试主框架如何处理呢？
