### ISSUE TITLE
关于样式隔离的疑问——开启沙箱后，子应用中挂载到ducument.body的组件样式无法生效

### ISSUE THREAD

**Issue by PickACatName** [umijs/qiankun#1316]
关于样式隔离的疑问——开启了沙箱后，当子应用中使用了类似element的dialog,drawer等挂在document.body上的组件时，子应用中组件内嵌页面的样式无法生效，有什么好的解决方案么？

**Comment by poorli** [comment]
![image](https://user-images.githubusercontent.com/14001823/111034506-ff469d00-8450-11eb-9dce-30799939dce5.png)

https://qiankun.umijs.org/zh/api api 里面对样式基于 ShadowDOM 的严格样式隔离有说明

首先说下为什么不生效：
你说的 dialog 组件 DOM 是挂载在主应用的 document.body 
但是样式加载在子应用的 ShadowDOM 里面，ShadowDOM 里的样式不会在主应用中生效

如何解决：
你需要看下组件能否挂载在子应用的 DOM 元素上，不要挂载在 document.body

vant 的 toast 有类似能力
```
import { Toast } from 'vant';

Vue.use(Toast);

Toast.setDefaultOptions({ getContainer: () => container}); // 挂载在子应用的 container 上
```

**Comment by PickACatName** [comment]
好的，感谢，已解决

**Comment by haitaodesign** [comment]
> 好的，感谢，已解决

你的解决方案是怎么，element-ui 的？

**Comment by PickACatName** [comment]
#好的，感谢，已解决

你的解决方案是什么，element-ui 的？

**Comment by realhao** [comment]
> 好的，感谢，已解决

请问如何解决的？

**Comment by realhao** [comment]
主应用 vue2，子应用 vue3，隔离 ok
main.ts
`
export async function mount(props: any) {
  const { container } = props;
  const app = await startup(props, container);
  if (app) {
    // eslint-disable-next-line
    app.config.globalProperties.mainAppConfig= props;
 }
}
`

App.vue
`
<template>
  <a-config-provider :locale="locale" :getPopupContainer="getPopupContainer">
    <router-view />
  </a-config-provider>
</template>
<script>
import { getCurrentInstance } from 'vue';
import zhCN from '@xes/ant-design-vue/es/locale/zh_CN';

export default {
  setup() {
    const getPopupContainer = (el) => {
      const vueActiveInstance = getCurrentInstance();
      if (!vueActiveInstance) {
        console.log(`未找到 vue 激活实例，使用 document.body`);
        return document.body;
      }
      const { appContext } = vueActiveInstance;
      const didaConfig = appContext.app?.config?.globalProperties?.[自定义挂载变量];
      const container = didaConfig?.mainAppConfig?.container;
      console.log('getPopupContainer', el, container);
      if (typeof container?.querySelector === 'function') {
        const wrap = container?.querySelector('#__dida_popup_container__');
        console.log('getPopupContainer', wrap);
        return wrap;
      }
      console.log('getPopupContainer 使用 document.body');
      return document.body;
    };

    return {
      locale: zhCN,
      getPopupContainer,
    };
  },
};
</script>
`

**Comment by PickACatName** [comment]
> > 好的，感谢，已解决
> 
> 你的解决方案是什么，element-ui 的？

弹窗抽屉之类的组件使用了v-transfer-dom指令挂载到子应用的DOM元素上，像el-popover之类的组件目前暂时用了行内样式

**Comment by realhao** [comment]
解决思路：ShadowDOM + popup 类组件挂载到子应用某个节点里
解决步骤：
1、主应用 vue2，开启 ShadowDOM 沙箱
```
start({
    sandbox: {
        strictStyleIsolation: true,
    }
})
```

2、子应用 public/index.html，增加容器节点
```
<div id="microAppPopup"></div>
```

3、子应用 vue3，入口暴露生命周期获取子应用 container
```
export async function mount(props: any) {
  const { container } = props;
  const app = await startup(props, container);
  if (app) {
    app.config.globalProperties.mainAppConfig = props;
  }
}
```

4、App.vue 里查询子应用的 popup 类组件容器节点
```
<template>
  <a-config-provider :locale="locale" :getPopupContainer="getPopupContainer">
    <router-view />
  </a-config-provider>
</template>
<script>
import { getCurrentInstance } from 'vue';
import zhCN from '@xes/ant-design-vue/es/locale/zh_CN';
export default {
  setup() {
    const getPopupContainer = (el) => {
      const vueActiveInstance = getCurrentInstance();
      if (!vueActiveInstance) {
        console.log(`未找到 vue 激活实例，使用 document.body`);
        return document.body;
      }
      const { appContext } = vueActiveInstance;
      const didaConfig = appContext.app?.config?.globalProperties?.__dida_global_config__;
      const container = didaConfig?.mainAppProps?.container;
      console.log('getPopupContainer', el, container);
      if (typeof container?.querySelector === 'function') {
        const wrap = container?.querySelector('#microAppPopup');
        console.log('getPopupContainer', wrap);
        return wrap;
      }
      console.log('getPopupContainer 使用 document.body');
      return document.body;
    };
    return {
      locale: zhCN,
      getPopupContainer,
    };
  },
};
</script>
```

**Comment by realhao** [comment]
解决思路：ShadowDOM + popup 类组件挂载到子应用某个节点里
解决步骤：
1、主应用 vue2，开启 ShadowDOM 沙箱
```
start({
    sandbox: {
        strictStyleIsolation: true,
    }
})
```

2、子应用 public/index.html，增加容器节点
```
<div id="microAppPopup"></div>
```

3、子应用 vue3，入口暴露生命周期获取子应用 container
```
export async function mount(props: any) {
  const { container } = props;
  const app = await startup(props, container);
  if (app) {
    app.config.globalProperties.mainAppConfig = props;
  }
}
```

4、App.vue 里查询子应用的 popup 类组件容器节点
```
<template>
  <a-config-provider :locale="locale" :getPopupContainer="getPopupContainer">
    <router-view />
  </a-config-provider>
</template>
<script>
import { getCurrentInstance } from 'vue';
import zhCN from 'ant-design-vue/es/locale/zh_CN';
export default {
  setup() {
    const getPopupContainer = (el) => {
      const vueActiveInstance = getCurrentInstance();
      if (!vueActiveInstance) {
        console.log(`未找到 vue 激活实例，使用 document.body`);
        return document.body;
      }
      const { appContext } = vueActiveInstance;
      const didaConfig = appContext.app?.config?.globalProperties?.mainAppConfig;
      const container = didaConfig?.mainAppConfig?.container;
      console.log('getPopupContainer', el, container);
      if (typeof container?.querySelector === 'function') {
        const wrap = container?.querySelector('#microAppPopup');
        console.log('getPopupContainer', wrap);
        return wrap;
      }
      console.log('getPopupContainer 使用 document.body');
      return document.body;
    };
    return {
      locale: zhCN,
      getPopupContainer,
    };
  },
};
</script>
```

**Comment by lovedaan** [comment]
点击date-pinker文本框获得焦点，date-picker面板会闪动然后马上消失，不知道什么原因，审查元素看date-picker元素被添加到父应用的body同层，但是即使我代理document.body的appendChild方法到子应用的容器内，还是有这个闪动问题，感觉跟楼主这个问题不是同一个

**Comment by songyazhao** [comment]
vue2版本，element-ui，我暂时通过以下方式解决了，应该也适用于其他UI组件库

```js
const proxy = ({ container }) => {
  if (document.body.appendChild.__isProxy__) return
  revocable = Proxy.revocable(document.body.appendChild, {
    apply(target, thisArg, [node]) {
      if (container) {
        container.appendChild(node)
      } else {
        target.call(thisArg, node)
      }
    }
  })
  document.body.appendChild = revocable.proxy
  document.body.appendChild.__isProxy__ = true
}

export const mount = async props => {
  proxy(props)
  ...
}

export const unmount = async () => {
  ...
  revocable.revoke()
  revocable = null
}
```

**Comment by litandota** [comment]
> vue2版本，element-ui，我暂时通过以下方式解决了，应该也适用于其他UI组件库
> 
> ```js
> const proxy = ({ container }) => {
>   if (document.body.appendChild.__isProxy__) return
>   revocable = Proxy.revocable(document.body.appendChild, {
>     apply(target, thisArg, [node]) {
>       if (container) {
>         container.appendChild(node)
>       } else {
>         target.call(thisArg, node)
>       }
>     }
>   })
>   document.body.appendChild = revocable.proxy
>   document.body.appendChild.__isProxy__ = true
> }
> 
> export const mount = async props => {
>   proxy(props)
>   ...
> }
> 
> export const unmount = async () => {
>   ...
>   revocable.revoke()
>   revocable = null
> }
> ```

这样做后会有报错，请教大佬是为什么呢？
![image](https://user-images.githubusercontent.com/10540308/177558423-12347c69-9be8-49ef-a268-65b211691b4d.png)

**Comment by Caveolaes** [comment]
> 

点击其他的路由，再点击回子应用的路由，会报错，页面为空白，重新刷新页面才可以

**Comment by Ec2-slj** [comment]
> > > 好的，感谢，已解决
> > 
> > 
> > 你的解决方案是什么，element-ui 的？
> 
> 弹窗抽屉之类的组件使用了v-transfer-dom指令挂载到子应用的DOM元素上，像el-popover之类的组件目前暂时用了行内样式

v-transfer-dom指令的代码方便展示下吗

**Comment by Rahim-Chan** [comment]
> ![image](https://user-images.githubusercontent.com/14001823/111034506-ff469d00-8450-11eb-9dce-30799939dce5.png)
> 
> https://qiankun.umijs.org/zh/api api 里面对样式基于 ShadowDOM 的严格样式隔离有说明
> 
> 首先说下为什么不生效： 你说的 dialog 组件 DOM 是挂载在主应用的 document.body 但是样式加载在子应用的 ShadowDOM 里面，ShadowDOM 里的样式不会在主应用中生效
> 
> 如何解决： 你需要看下组件能否挂载在子应用的 DOM 元素上，不要挂载在 document.body
> 
> vant 的 toast 有类似能力
> 
> ```
> import { Toast } from 'vant';
> 
> Vue.use(Toast);
> 
> Toast.setDefaultOptions({ getContainer: () => container}); // 挂载在子应用的 container 上
> ```

https://juejin.cn/post/7205585832232501309/ 这里好像可以解决这个问题呢

**Comment by Rahim-Chan** [comment]
https://juejin.cn/post/7205585832232501309/

> 关于样式隔离的疑问——开启了沙箱后，当子应用中使用了类似element的dialog,drawer等挂在document.body上的组件时，子应用中组件内嵌页面的样式无法生效，有什么好的解决方案么？

我把元素方法patch了可以不用影响到子应用的改造
https://juejin.cn/post/7205585832232501309/

**Comment by Rahim-Chan** [comment]
> > 好的，感谢，已解决
> 
> 你的解决方案是什么，element-ui 的？

我把元素方法patch了可以不用影响到子应用的改造
https://juejin.cn/post/7205585832232501309/

**Comment by Rahim-Chan** [comment]
> 关于样式隔离的疑问——开启了沙箱后，当子应用中使用了类似element的dialog,drawer等挂在document.body上的组件时，子应用中组件内嵌页面的样式无法生效，有什么好的解决方案么？

https://github.com/Rahim-Chan/qiankun-rewrite我给方法上做了一层代理，希望能满足你的需求

**Comment by Rahim-Chan** [comment]
> > 好的，感谢，已解决
> 
> 你的解决方案是什么，element-ui 的？
要不要尝试我的重写的包
https://github.com/Rahim-Chan/qiankun-rewrite

**Comment by Rahim-Chan** [comment]
> 要不要尝试我的重写的包
> https://github.com/Rahim-Chan/qiankun-rewrite

要不要尝试我的重写的包，可以完美解决这个问题
https://github.com/Rahim-Chan/qiankun-rewrite

**Comment by aique127** [comment]
> > vue2版本，element-ui，我暂时通过以下方式解决了，应该也适用于其他UI组件库
> > ```js
> > const proxy = ({ container }) => {
> >   if (document.body.appendChild.__isProxy__) return
> >   revocable = Proxy.revocable(document.body.appendChild, {
> >     apply(target, thisArg, [node]) {
> >       if (container) {
> >         container.appendChild(node)
> >       } else {
> >         target.call(thisArg, node)
> >       }
> >     }
> >   })
> >   document.body.appendChild = revocable.proxy
> >   document.body.appendChild.__isProxy__ = true
> > }
> > 
> > export const mount = async props => {
> >   proxy(props)
> >   ...
> > }
> > 
> > export const unmount = async () => {
> >   ...
> >   revocable.revoke()
> >   revocable = null
> > }
> > ```
> 
> 这样做后会有报错，请教大佬是为什么呢？ ![image](https://user-images.githubusercontent.com/10540308/177558423-12347c69-9be8-49ef-a268-65b211691b4d.png) @songyazhao

你好，这个方式重写body.appendChild方法会把主应用和其它子应用(同时激活多个子应用)的也重写了，导致主应用的弹窗加到了这个子应用里。

**Comment by aique127** [comment]
> vue2版本，element-ui，我暂时通过以下方式解决了，应该也适用于其他UI组件库
> 
> ```js
> const proxy = ({ container }) => {
>   if (document.body.appendChild.__isProxy__) return
>   revocable = Proxy.revocable(document.body.appendChild, {
>     apply(target, thisArg, [node]) {
>       if (container) {
>         container.appendChild(node)
>       } else {
>         target.call(thisArg, node)
>       }
>     }
>   })
>   document.body.appendChild = revocable.proxy
>   document.body.appendChild.__isProxy__ = true
> }
> 
> export const mount = async props => {
>   proxy(props)
>   ...
> }
> 
> export const unmount = async () => {
>   ...
>   revocable.revoke()
>   revocable = null
> }
> ```

你好，这个方式重写body.appendChild方法会把主应用和其它子应用(同时激活多个子应用)的也重写了，导致主应用的弹窗加到了这个子应用里。

**Comment by gansong99** [comment]
> > vue2版本，element-ui，我暂时通过以下方式解决了，应该也适用于其他UI组件库
> > ```js
> > const proxy = ({ container }) => {
> >   if (document.body.appendChild.__isProxy__) return
> >   revocable = Proxy.revocable(document.body.appendChild, {
> >     apply(target, thisArg, [node]) {
> >       if (container) {
> >         container.appendChild(node)
> >       } else {
> >         target.call(thisArg, node)
> >       }
> >     }
> >   })
> >   document.body.appendChild = revocable.proxy
> >   document.body.appendChild.__isProxy__ = true
> > }
> > 
> > export const mount = async props => {
> >   proxy(props)
> >   ...
> > }
> > 
> > export const unmount = async () => {
> >   ...
> >   revocable.revoke()
> >   revocable = null
> > }
> > ```
> 
> 你好，这个方式重写body.appendChild方法会把主应用和其它子应用(同时激活多个子应用)的也重写了，导致主应用的弹窗加到了这个子应用里。

你解决了嘛，大佬

**Comment by zerotower69** [comment]
我在vite+vue3的项目接入qiankun时，也碰到了vant的弹出层样式丢失的问题。
核心是重写弹出层组件的teleport属性，可参考的代码如下。

```ts
import { NodeTransform, ElementNode,NodeTypes, AttributeNode, TextNode,SourceLocation} from '@vue/compiler-core'

// qiankun 挂载节点选择器
const $qiankunEl = '#red-packet-root'


// 指定vant弹出层组件的挂载位置
const transformVantPopup: NodeTransform = (node) => {
  if (node.type === 1 /* NodeTypes.ELEMENT */) {
    const el = node as ElementNode;

    // 精确匹配 Vant 弹出层组件
      if (["van-popup", "VanPopup",'van-popover','VanPopover'].includes(el.tag)) {
        console.log("popup",node)
      // 类型守卫：确保是标准属性节点
      const isTeleportAttr = (p: any): p is AttributeNode =>
        p.type === NodeTypes.ATTRIBUTE /* NodeTypes.ATTRIBUTE */ && p.name === "teleport";

      // 查找现有 teleport 属性
      const teleportAttr = el.props.find(isTeleportAttr);

      // 创建符合规范的 TextNode
      const teleportValueNode: TextNode = {
        type: NodeTypes.TEXT, // NodeTypes.TEXT
        content: $qiankunEl, // 子应用容器ID
        loc: createDummyLocation(el.loc)
      };

      // 创建/更新 AttributeNode
      const newTeleportAttr: AttributeNode = {
        type: NodeTypes.ATTRIBUTE, // NodeTypes.ATTRIBUTE
        name: "teleport",
        nameLoc: createDummyLocation(el.loc),
        value: teleportValueNode,
        loc: el.loc,
      };

      if (teleportAttr) {
        // 更新现有属性值
        teleportAttr.value = teleportValueNode;
      } else {
        el.props.push(newTeleportAttr);
      }
    }
  }
};

// 生成符合 SourceLocation 结构的虚拟位置
const createDummyLocation = (parentLoc: SourceLocation): SourceLocation => ({
  start: { line: parentLoc.start.line, column: parentLoc.start.column, offset: parentLoc.start.offset },
  end: { line: parentLoc.end.line, column: parentLoc.end.column, offset: parentLoc.end.offset },
  source: parentLoc.source
})

export default defineConfig({
    plugins:[
       vue({
        template: {
          compilerOptions: {
            nodeTransforms: [transformVantPopup],
          },
        },
      }),
    ]
})
```

**Comment by moluoxixi** [comment]
vue3应该如何做,我使用如下代码,el-drawer仍然样式丢失了
const proxy = (container) => {
  if (document.body.appendChild.__isProxy__) return
  const revocable = Proxy.revocable(document.body.appendChild, {
    apply(target, thisArg, argArray) {
      const [node] = argArray
      console.log('apply',node,argArray,container,target)
      if (container) {
        container.appendChild(node)
      } else {
        target.call(thisArg, node)
      }
    }
  })
  if (revocable.proxy) {
    document.body.appendChild = revocable.proxy
  }
  document.body.appendChild.__isProxy__ = true
}
