### ISSUE TITLE
手动加载微应用时，主应用怎么监听子应用是否加载成功

### ISSUE THREAD

**Issue by Clive-Wang** [umijs/qiankun#1317]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

手动加载微应用时，主应用怎么监听子应用是否加载成功

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by poorli** [comment]
文档 API 里面有说明：https://qiankun.umijs.org/zh/api#loadmicroappapp-configuration

loadMicroApp 后，会返回 MicroApp ，可以拿到子应用状态。

建议通读下官网上面的所有内容

![image](https://user-images.githubusercontent.com/14001823/111035356-18e9e380-8455-11eb-9431-f3c763dfaaeb.png)
