### ISSUE TITLE
父子应用,子应用之间的样式没有隔离?

### ISSUE THREAD

**Issue by Rain20199** [umijs/qiankun#132]
## What happens?
vue-cli3创建了3个vue应用  mainapp里有一个.home样式,child1应用，child2应用也有.home样式
样式会生成在主应用的style标签里，影响到全局的
![image](https://user-images.githubusercontent.com/56431955/68182662-fa5c1880-ffd4-11e9-886b-4f4477bf92e6.png)

**Comment by kuitos** [comment]
vue 子应用之间样式问题已修复，升级到 v1.3.0
主应用跟子应用之间的隔离需要自己去确保，see https://github.com/umijs/qiankun/wiki/FAQ#how-to-guarantee-the-main-app-stylesheet-isolated-with-sub-apps
