### ISSUE TITLE
接入qiankun 框架后,卡顿现象凸显的问题

### ISSUE THREAD

**Issue by matteao03** [umijs/qiankun#1320]
## 现状

1. 微应用独立运行时，有轻微卡顿现象
2. 引入qiankun 框架后，卡顿现象明显，性能问题凸显

## 最小复现仓库

![qiankun-better 问题demo](https://github.com/matteao03/qiankun-better)

#### 访问项目
- 在qiankun 框架内访问卡顿页面： http://localhost:8080/#/data  
- 独立访问微应用卡顿页面：http://localhost:8082/#/data
- 
#### 操作步骤
- 点击表头　“操作”　列，弹出复选框，控制表格列的动态显示

#### 卡顿表现
- 独立访问微应用，表格列的显示过程有轻微卡顿
- qiankun 框架访问, 表格列的显示过程卡顿明显, 延迟时间长
** (1. 直观操作感觉, 2 .通过 devtools  performence 性能分析,  summary  统计时长得出的)**

## 环境

- **qiankun Version**: 2.3.5 及以上
- **Platform Version**:  nodejs 环境 10.13.0 (nodejs 版本在 8.11 以上即可)
- **Browser Version**: chrome 88 ( 对chrome 版本没要求, 常用版本即可)

**Comment by ac51300696** [comment]
同样遇到了这个问题，首先是沙盒模式带来的性能问题，代理了window上的vue，可以先通过关闭sandbox来提高一部分
然后同样是vue，发现子服务单独运行和基座服务里运行是，render的节点数不一致，怀疑是vuediff算法因为qiankun的一些影响失效的原因，每次都是全量渲染
这部分的内容还没找到原因，希望有人能帮忙一下

**Comment by fsyldn** [comment]
我这也发现一个问题，沙箱模式，切换子应用，虽然销毁了vue实例，但是内存不断在增加，每切换一次就增加一次
，暂时没找到解决方案

**Comment by Aaronlamz** [comment]
也是遇到同样的问题，部署到线上时切换路由会卡顿，完全无法使用。本地运行则无这个问题。有人解决一下吗

**Comment by Liaozzzzzz** [comment]
同遇到这个问题

**Comment by lucaslz2020** [comment]
同遇到这个问题

**Comment by canyuegongzi** [comment]
同样问题

**Comment by jiangyh1024** [comment]
请问如何解决卡顿问题  无语。。。。

**Comment by canyuegongzi** [comment]
> 请问如何解决卡顿问题  无语。。。。
> 
> 我用的是 antd 的tab  每个tab 显示的内容对应路由
> 
> 切换的时候 调用了 app.unmount() 方法
> 
> 导致会卡5-10秒的样子
> 
> 不调用app.unmount() 就不卡
> 
> 但是 不调用app.unmount()  会导致加载的应用重复调用应用中页面的api

关于tab可以缓存实例的，有类似的问题。

**Comment by Ghjsw** [comment]
同样问题  独立运行正常   子系统下    切换动画 路由,都会明显慢一拍

**Comment by liwenda122** [comment]
性能确实不太好，兼容性也不行。

**Comment by byMoya** [comment]
同上 umi+qiankun开启sandbox 子应用UI操作、渲染会卡顿 暂时关闭了

**Comment by astadon** [comment]
同样的问题，页面的dom稍微多一些，就能感觉慢了好多

**Comment by lihuangshuaige** [comment]
同样的问题 ，解决了吗？

**Comment by Tinet-zhangmd** [comment]
angular作为主子应用，页面渲染元素一多，cpu就上来了，且页面渲染结束后cpu也不下降

**Comment by liwenda122** [comment]
阿里系的轮子特点就是 KPI拿到之后就不维护了，又一个玩具项目凉凉。

**Comment by jiangyh1024** [comment]
@fsyldn 有解决吗，我也是遇到这个内存问题，卸载了子应用，内存没有被释放，一直增加

**Comment by jiangyh1024** [comment]
@canyuegongzi @lucaslz2020 各位解决了吗？求助，内存飚升，卸载子应用 无效

**Comment by lucaslz2020** [comment]
@jiangyh1024 我在等官方的解决方案~

**Comment by jiangyh1024** [comment]
哎，好久了 好没解决

**Comment by canyuegongzi** [comment]
> @canyuegongzi @lucaslz2020 各位解决了吗？求助，内存飚升，卸载子应用 无效

> 

这个去年用乾坤时就有这个问题，当时我记得把沙箱直接关闭后稍微好一些，沙箱中 js 性能相差不多，还行，主要是 dom 操作；子应用尽量不要直接操作 dom， 也会有一定改善, 京东出过个基于 webComponent 的微前端的框架MicroApp， 相较于可能会稍微好一些。

丢个链接，关于性能的讨论issues     [性能](https://github.com/umijs/qiankun/issues/1555)

可以根据讨论中方法魔改一下。

**Comment by yuleiQ** [comment]
> @canyuegongzi @lucaslz2020 各位解决了吗？求助，内存飚升，卸载子应用 无效

各位解决了么 我到线上直接卡到不行 仅在谷歌下

**Comment by Aaron52077** [comment]
爆肝一个月完善https://wuli-admin.gitee.io/react-mat-pro/#/dashboard 切换主子应用时候也有一丢丢卡顿

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。

**Comment by zhanyoulin456** [comment]
> 爆肝一个月完善https://wuli-admin.gitee.io/react-mat-pro/#/dashboard 切换主子应用时候也有一丢丢卡顿

你这个项目的源码看得到么老哥

**Comment by Aaron52077** [comment]
> > 爆肝一个月完善https://wuli-admin.gitee.io/react-mat-pro/#/dashboard 切换主子应用时候也有一丢丢卡顿
> 
> 你这个项目的源码看得到么老哥

没开源

**Comment by QiangTian1993** [comment]
所以这个问题解决了吗，怎么关闭了

**Comment by Lemonreds** [comment]
还是卡，还有优化空间么

**Comment by gitEverytime** [comment]
开了speed：true,照样进行脏值检查，然后导致切换卡顿，说好的3.0呢
