### ISSUE TITLE
qiankun和swagger-ui一起使用a标签需要点击两下才能切换路由，全局点击监听事件是不是有冲突

### ISSUE THREAD

**Issue by hanyi0121** [umijs/qiankun#1324]
## What happens?

qiankun和swagger-ui一起使用a标签需要点击两下才能切换路由，全局点击监听事件是不是有冲突
正常点击一下就能切换菜单，只要这两个一起使用就会a标签异常，刷新页面第一次点两下才能进入其他页面，第二次再点就好了
每次重刷页面都有这个问题

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.4.0
- **Platform Version**:angular10
- **Browser Version**:

**Comment by gongshun** [comment]
可以尝试下关闭沙箱，再看看有没有问题

**Comment by hanyi0121** [comment]
关闭沙箱也不好使，好像是这个window上的方法引起的，手动浏览器remove掉就好了，不知道该怎么办
![image](https://user-images.githubusercontent.com/59952880/111261995-5f5e5e80-865e-11eb-82eb-697657270e7f.png)

**Comment by hanyi0121** [comment]
![image](https://user-images.githubusercontent.com/59952880/111266054-f5958300-8664-11eb-9457-ae360a0ed90c.png)
