### ISSUE TITLE
[Feature Request] 沙箱定制化

### ISSUE THREAD

**Issue by karzanOnline** [umijs/qiankun#1326]
## 背景

在 CCO 业务 Xspace 后台场景比较特殊，它需要在模块化动态加载的同时再去加载微前端应用。平台本身是基于模块化做的一套动态加载业务单元的能力，本质是也是请求 `CDN` 静态资源地址，解析后通过 `require.js` 加载。这里的处理逻辑与 qiankun 的解析大致一致，区别的点是在一个是基于 `amd` 一个是 `umd`。这里的特殊点是先去做了动态的模块加载， `window.define.amd` 是存在的，也就意味着微应用的静态资源解析会按照 `amd`  加载方式去处理，最终导致加载失败。

## 思路
处理方式是不是可以优化成在 `loadApp` 函数中 运行 `execScripts` 时，可以从 `config` 中获取是否需要 `window` 注入，这种场景是需要关闭 `sandbox` 将沙箱交给外部处理。伪代码如下：

```js
// 从配置中判断是否需要获取传入的 window
let global = config.global || window;

const scriptExports: any = await execScripts(global, !useLooseSandbox);
```

这种方式安全性会降低，但算是比较快的解决方案。

如果仍然需要开启沙箱则，需要从 `ProxySandbox` 里面做手动传入的 `window` 的代理。当然这种方案没有意义...

```js

createSandboxContainer(..., handleWindow);

createSandboxContainer() {
    new ProxySandbox(appName, handleWindow);
}

```

## 其他解法

其他的方式在微前端的外层再做一层 sandbox 倒是可以解这种问题。劣势是这种方案解的有点太定制化。

**Comment by karzanOnline** [comment]
额~ 我想了一下还有一种比较简单的方法是把 `sandbox` 的 `set` 和 `get` 方法透出到 `config` 层。交给开发者自己去拦截，也可以解这个问题。

**Comment by Deturium** [comment]
@kuitos 奎爷怎么看？如果只是简单凿穿 sandbox 让用户传 global/window 总觉得对开发者不友好，如果打补丁的话补丁的位置也很难选


还是比较想把沙箱独立出来，如果把沙箱独立出来的，那确实可以满足这里自定义的需求，API 可能会这样？

```ts
import { MicroApp  } from '@qiankun/qiankun'
import { Sandbox  } from '@qiankun/sanbox'
import { loadApp } from '@qiankun/app-loader'

const sandbox = new Sandbox({
  global: {
    // here are your costum code
  },
  plugins: [],
})

const microApp = new MicroApp({
  name: 'app1',
  app: loadApp('http://app1.umi.org')
  sandbox,
})
```

那无论在 loadApp （execScripts）阶段 还是 在 sandbox 阶段都可以交给开发者自己拦截（其实两个是一致的，同一个东西）

**Comment by kuitos** [comment]
独立沙箱目前肯定是没法支持的，要 3.0 才可以了。
当前这个问题最简单有效的解决方案是在 beforeLoad 这些 hook 里改写 proxy window，从而达到让微应用的 AMD define 失效：
```js
beforeLoad(app, global) {
  // 重置 window.define
  global.define = {};
}
```

**Comment by karzanOnline** [comment]
> 独立沙箱目前肯定是没法支持的，要 3.0 才可以了。
> 当前这个问题最简单有效的解决方案是在 beforeLoad 这些 hook 里改写 proxy window，从而达到让微应用的 AMD define 失效的目的：
> 
> ```js
> beforeLoad(app, global) {
>   // 重置 window.define
>   global.define = {};
> }
> ```

额~ 是的。 这个看起来是更快更省力的解法
