### ISSUE TITLE
ChunkLoadError: Loading chunk failed (Has Reproduction)

### ISSUE THREAD

**Issue by guibwl** [umijs/qiankun#1327]
## What happens?

两个应用切换时，本该由 qiankun 请求的 chunk 变成了挂载在 head 中的 `<script charset="utf-8" src="/chunk.js"></script>`
导致了，Webpack 报错 `ChunkLoadError: Loading chunk failed.`。

## Mini Showcase Repository(REQUIRED)
https://github.com/guibwl/qiankun-ChunkLoadError

## How To Reproduce
子应用 app1、app2 都使用了路由懒加载，各有 A、B 两个页面。
1. 当 app1 的 A 页面加载后，通过左菜单切换 app2 的 A 或 B 页面，此时 app2 加载。
2. 切换回 app1 的 B 页面，此时会产生报错：
```js
ChunkLoadError: Loading chunk B failed.
```

#### 主应用:
    "qiankun": "^2.4.0"
    "umi": "^3.4.2"
#### 子应用:
    "vue": "^3.0.5"
    "@vue/cli-*": " ~4.5.0"

**Comment by gongshun** [comment]
你的子应用缺少这个文件 https://github.com/umijs/qiankun/blob/master/examples/vue3/src/public-path.js

你用了路由懒加载，就必须写死 publicPath，或者动态修改 publicPath

https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by guibwl** [comment]
就只是添加 public-path.js 就可以了吗？
我添加到了代码里面，但是我这儿还是报错，不知道是不是哪里写的有问题；

我把我修改的上传了，这个是 commit，能帮我看看吗？感谢！
https://github.com/guibwl/qiankun-ChunkLoadError/commit/99423bcd078a5d29d496382316a6d37b1b41e219

![20210319_102938 _1_ _1_.gif](https://i.loli.net/2021/03/19/tyYXPObMa9FgfDh.gif)

**Comment by gongshun** [comment]
你没有按照 vue3 的 demo 示例，销毁路由。https://github.com/umijs/qiankun/blob/master/examples/vue3/src/main.js#L13

**Comment by guibwl** [comment]
我修复好了，除了你说的这几点，还有一点，mount 生命周期里，一定要重新创建 vue、router 实例：
```js
  router = createRouter(); // 缺少这一步，导致报错
  vueApp = createVueApp();
```
还是自己粗心没有仔细参照官方的 demo 啊。

感谢 @gongshun 的耐心帮助。
