### ISSUE TITLE
[Bug] 存储的weakMap元素在切换后并没有被回收，导致内存泄漏

### ISSUE THREAD

**Issue by Orange-C** [umijs/qiankun#1332]
## What happens?

来回切换子应用时，weakMap中的元素一直在增加，没有被回收，反复多次后导致崩溃卡死。

代码位置：
https://github.com/umijs/qiankun/blob/73283c8ad3d3d252fe806a756988d46537a4ee48/src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts#L20

## How To Reproduce

切换子应用

## Context

- **qiankun Version**: 2.4.0

**Comment by gongshun** [comment]
是开启了样式严格隔离模式？我试了下，没发现内存泄露，weakMap本身就是防止内存泄露的，https://es6.ruanyifeng.com/#docs/set-map#WeakMap-%E7%9A%84%E7%94%A8%E9%80%94

https://github.com/umijs/qiankun/issues/1140#issuecomment-755960232

**Comment by Orange-C** [comment]
@gongshun 
我们内部改了一些qiankun的逻辑，增加了div节点的劫持，所以某些极端时候这个map里面会一次性增加上千元素。
其实我也觉得奇怪weakMap本应该防止泄露，实测的时候dev tools里面发现weakMap里面的节点已经不在页面了但还是在map中，来回切换反复添加导致卡死。

**Comment by Orange-C** [comment]
先暂时关闭我再排查一下吧

**Comment by bulaye** [comment]
我这也是weakMap中元素不断增加。。
