### ISSUE TITLE
qiankun 有计划支持父子通信，子传父，子传子的统一方案吗？

### ISSUE THREAD

**Issue by yulintianxia** [umijs/qiankun#1333]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
目前的方案：https://qiankun.umijs.org/zh/api#initglobalstatestate

**Comment by yulintianxia** [comment]
当前官方文档太简单了，不适合复杂情况，很多时候需要在子应用之间通信，官方文档没具体说明好的解决方案。
