### ISSUE TITLE
关于在jquery子应用中刷新页面，在切换到react子应用报错的问题

### ISSUE THREAD

**Issue by gaoxiaosong1113** [umijs/qiankun#1334]
我在一个react主项目中集成了一个react项目和一个jquery项目，配置如下：

```
registerMicroApps([
  {
    // 这个是一个react项目
    name: 'base',
    entry: '//localhost:3001',
    container: '#stretch',
    loader,
    activeRule: '/base',
  },
  {
    // 这个是一个jquery项目
    name: 'webapp',
    entry: '//localhost:3003/views/',
    container: '#stretch',
    loader,
    activeRule: '/webapp',
  },
])

```
当react子应用首次加载时：

![企业微信截图_16164034529769](https://user-images.githubusercontent.com/16183057/111965122-583cc200-8b30-11eb-817b-2d5bdfabac14.png)

切换到jquery子应用时

![企业微信截图_16164035491263](https://user-images.githubusercontent.com/16183057/111965162-668ade00-8b30-11eb-96d7-a830df0a544d.png)

当在jquery子应用刷新页面后切换到react子应用时
![企业微信截图_16164035947919](https://user-images.githubusercontent.com/16183057/111965214-74d8fa00-8b30-11eb-9d29-3bbb721e9096.png)

这个问题导致：
```
application 'base' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in base entry
```
当然我确认webpack之类的配置是没有问题的！！！

直接打开react子项目没有问题，问题出现在react项目中刷新以后，在切换到react项目中！！！

react微应用加载时使用的是library的名称 。
jquery微应用跳转到react微应用使用的是jsonpFunction的名称。

请问能帮忙看一下是什么问题导致的么？

**Comment by gaoxiaosong1113** [comment]
https://github.com/gaoxiaosong1113/qiankun-react

dome地址

**Comment by gaoxiaosong1113** [comment]
还有就是
```js

console.log(require)
// ƒ () { [native code] }  这里的require跟下面的require不是一个东西
require(['jquery'], function ($) {
  console.log(require)
  // {bootstrap: ƒ, mount: ƒ, unmount: ƒ}
  console.log(1222)
  $('#jd').html('Hello, render with jQuery')
})
```

**Comment by wh1teYu** [comment]
@xiaoosnggao  你好，我也越到这个问题了，麻烦问一下，解决了吗

**Comment by wh1teYu** [comment]
解决了
