### ISSUE TITLE
umi 项目在未安装@umijs/plugin-qiankun依赖时启动没有问题，安装依赖该依赖后，启动浏览器提示调试服务断开

### ISSUE THREAD

**Issue by zhangyoof** [umijs/qiankun#1335]
## What happens?

umi 项目在未安装@umijs/plugin-qiankun依赖时启动没有问题，安装依赖该依赖后，启动浏览器提示调试服务断开

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/zhangyoof/qk-part3.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
第一步 ：在package.json文件devDependencies未添加@umijs/plugin-qiankun时启动是没有任何问题的
第二部：在未安装依赖启动正常情况下安装@umijs/plugin-qiankun依赖，启动后浏览器会提示Disconnected from the devServer,
## Context

- **qiankun Version**: ^2.24.1
- **Platform Version**:windows 10
- **Browser Version**:  Google Chrome    版本 89.0.4389.90（正式版本） （64 位）

**Comment by gongshun** [comment]
新增环境变量，指定端口即可 https://github.com/umijs/umi-plugin-qiankun/blob/master/examples/app1/.env

**Comment by zhangyoof** [comment]
> 新增环境变量，指定端口即可https://github.com/umijs/umi-plugin-qiankun/blob/master/examples/app1/.env

这个是在项目下新建个.evn的文件然后按照你这个操作来吗，我刚试了下不行
