### ISSUE TITLE
[Bug]当父应用的router有全局钩子时，子应用执行跳转，浏览器返回需要点击2次

### ISSUE THREAD

**Issue by lixioo** [umijs/qiankun#1336]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

父子应用都是vue项目时，2个vue-router都会修改History的记录，导致浏览器的返回要2次才能生效
详细情况:
1.父应用的vue-router设置一个全局路由钩子，beforeEach，用来在Url上始终注入id信息
示例: if(!to.query.id&&from.query.id){
to.query.id=from.query.id
next(to)
}
2.子应用从/home页面，执行this.$router.push('/about')  

子应用完成跳转后，会pushstate一条/about的记录，触发父应用的vue-router事件监听
父应用前往/about?id=xxx ，再次pushstate一条记录

3.需要在浏览器上点2次返回上一页才能返回到/home页面

期望：从/home页面跳转到/about页面后，点击返回上一页，回到/home页面

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
https://github.com/lixioo/qiankun-demo.git

## 复现步骤，错误日志以及相关配置

1.项目启动后点击子应用01
2.点击home
3.点击返回，仍然处于/home，再次点击返回，返回到/

## 相关环境信息

- **qiankun 版本** 2.4.0
- **浏览器版本**：chrome 89
- **操作系统**：

**Comment by Li-DaDa** [comment]
我也遇到这个问题了，但是我的是初始进入项目会触发两次全局路由钩子，然后点击跳转一次路由，会触发三次全局路由钩子，点击浏览器返回要点3次，才会返回上一页，前两次返回页面组件没有变化，但是地址栏里url在变化

**Comment by gongshun** [comment]
应该是同一个问题 https://github.com/umijs/qiankun/issues/1339
