### ISSUE TITLE
[Bug]safari 13.0.5下白屏,14.0.5下正常显示

### ISSUE THREAD

**Issue by ChenYCL** [umijs/qiankun#1337]
## What happens?

使用umi3和@umijs/plugin-qiankun,挂载子应用控制台爆警告
`start.js:24 single-spa minified message #1: See https://single-spa.js.org/error/?code=1`
![image](https://user-images.githubusercontent.com/25706676/112247520-66552480-8c8f-11eb-8ef6-f4ca79c5bd04.png)

且在safari 13.0.5上加载子应用白屏,safari 14.0.5正常

## 相关环境信息

- **qiankun 插件版本**:"@umijs/plugin-qiankun": "^2.17.5",
- **浏览器版本**：big sur 11.2.3
- **操作系统**： macos

**Comment by gongshun** [comment]
> single-spa minified message #1: See https://single-spa.js.org/error/?code=1

忽略这个警告，

应该是路由没有正确识别所以白屏

**Comment by ChenYCL** [comment]
@gongshun 应该是兼容问题,测试了14版本正常的
