### ISSUE TITLE
主应用如何将路由实例通过 props 传给微应用

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1338]
![image](https://user-images.githubusercontent.com/24559368/112295970-64ab5100-8ccf-11eb-8304-cbdf09226a7a.png)
![image](https://user-images.githubusercontent.com/24559368/112295990-6b39c880-8ccf-11eb-9fa4-f6a89dca2a27.png)

**Comment by gongshun** [comment]
参考 https://github.com/gongshun/qiankun-vue-demo/blob/f8a852999cc6df6b2c47b52ce210cfd1be5b6359/main/src/main.js#L27
