### ISSUE TITLE
微应用为 Vue3 时，history.back() 异常（Has Reproduction）

### ISSUE THREAD

**Issue by guibwl** [umijs/qiankun#1339]
## What happens?

子应用是 Vue3 时，history.back() 后不重新 render。

## Mini Showcase Repository(REQUIRED)
官方 demo 可以重现：
https://github.com/umijs/qiankun/tree/master/examples

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
qiankun 中，点击 About 后点击浏览器返回按钮，页面没有重新 Render（见下图）:
![inQinKun.gif](https://i.loli.net/2021/03/24/T89qfh4klnFOAwt.gif)

**Expected behavior** 1. 2.
直接访问微应用，点击 About 后点击浏览器返回按钮，页面重新 Render（见下图）:
![Vue3.gif](https://i.loli.net/2021/03/24/qPiLxbhtESmzJoU.gif)

## Context

- **qiankun Version**:2.4.0
- **Platform Version**: MacOs 11.2.3
- **Browser Version**: Chrome 89.0.4389.90

**Comment by kuitos** [comment]
@gongshun 看下？

**Comment by iqingting** [comment]
遇到了同样的问题

**Comment by gongshun** [comment]
打断点看了下，在 qiankun 中，vue-router 的路由跳转触发了两次 popstate 事件，第一次的 path 是正确的，第二次是重复的path，导致 vue-router 的错误捕获记录了这次的 path，然后点击浏览器的后退按钮，vue-router 判断 path 和上一次出错的 path 相同，直接 return 了。而独立运行时，路由跳转不会触发 popstate 事件。

https://user-images.githubusercontent.com/29347231/114846019-daa66200-9e0e-11eb-95db-60604564c8ad.mp4

bug 原因就是 popstate 事件触发了两次，至于为啥触发了两次，还在排查中。

 https://github.com/umijs/qiankun/issues/1184 应该是类似的问题

**Comment by kuitos** [comment]
start 方法调用时配置下 `start({urlRerouteOnly: true})` 试试

**Comment by gongshun** [comment]
> start 方法调用时配置下 `start({urlRerouteOnly: true}) `

可以了，加这个配置就没问题了

https://user-images.githubusercontent.com/29347231/114854525-7dfb7500-9e17-11eb-8f5f-002e926a1dd7.mp4

**Comment by kuitos** [comment]
@gongshun 解决方案加到 faq 里？
或者 qiankun 这边默认启用 urlRerouteOnly ？

**Comment by gongshun** [comment]
> @gongshun 解决方案加到 faq 里？
> 或者 qiankun 这边默认启用 urlRerouteOnly ？

@kuitos 默认启用 urlRerouteOnly 吧，这都影响正常使用了

**Comment by kuitos** [comment]
需要测一下默认启用会不会造成造成其他问题，毕竟 single-spa 也没有默认启用。

**Comment by gongshun** [comment]
> 需要测一下默认启用会不会造成造成其他问题，毕竟 single-spa 也没有默认启用。

好的，周末我详细测试下

**Comment by gongshun** [comment]
@kuitos 把 angular7、angular9，vue2、vue3，react16 的 hash/history 主子应用都测试了下，都正常。

看了下 single-spa 的代码，这个 urlRerouteOnly 的主要作用，是控制调用 history.pushState 和  history.replaceState 时是否触发一个 popstate 事件

源代码链接：

https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/navigation/navigation-events.js#L174

https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/navigation/navigation-events.js#L100

https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/navigation/navigation-events.js#L105

https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/navigation/navigation-events.js#L120

而根据 mdn 的描述，https://developer.mozilla.org/zh-CN/docs/Web/API/Window/popstate_event

![image](https://user-images.githubusercontent.com/29347231/115108966-cfd20580-9fa5-11eb-9545-ce710a0af1e2.png)

所以 single-spa 触发的 popstate 事件不是必要的。

**Comment by Xiaoxiasuper** [comment]
> 认启用

启用后子应用history.back()卡顿

**Comment by Xiaoxiasuper** [comment]
> 需要测一下默认启用会不会造成造成其他问题，毕竟 single-spa 也没有默认启用。

启用后angular子应用history.back()有卡顿问题。
