### ISSUE TITLE
主应用加载一个3D的微应用时，3D微应用的性能会降低到原来的五六分之一

### ISSUE THREAD

**Issue by aiyoudiao** [umijs/qiankun#1340]
### 问题描述

我有一个后台，用它作为主应用，然后我将一个3D机房的项目作为微应用。一切都很正常。

但是3D机房的项目独立运行时是这样的：
![image](https://user-images.githubusercontent.com/60660505/112410810-c8c52800-8d56-11eb-8aa4-c81d4018ee9e.png)

作为微应用挂载到主应用中时是这样的：
![image](https://user-images.githubusercontent.com/60660505/112410732-a7fcd280-8d56-11eb-879d-914f2ca904c6.png)

80端口的是主应用
![image](https://user-images.githubusercontent.com/60660505/112410863-de3a5200-8d56-11eb-8834-ae3f2db5ce35.png)

8887端口的是3D的微应用
![image](https://user-images.githubusercontent.com/60660505/112410914-f8743000-8d56-11eb-9675-d7add4d924c5.png)

主应用的性能监测是这样的
![image](https://user-images.githubusercontent.com/60660505/112410963-0de95a00-8d57-11eb-8763-ec1aaccd6f81.png)

3D的微应用性能监测是这样的
![image](https://user-images.githubusercontent.com/60660505/112410989-1b064900-8d57-11eb-890b-707abc632c79.png)

**性能差的好远噢**

### 问题剖析

然后我对比分析了一下
3D 微应用这里只调用了一个three.js的 renderObjects 和 renderObject，renderObjects() 是three.js中渲染所有对象的方法。
![image](https://user-images.githubusercontent.com/60660505/112411080-40935280-8d57-11eb-9ad8-daa016a8224d.png)

而 在主应用中这里却调用了三次renderObjects，并且 renderObject调用了几十次。
![image](https://user-images.githubusercontent.com/60660505/112411215-7f290d00-8d57-11eb-9bfd-7bb2928250d8.png)
![image](https://user-images.githubusercontent.com/60660505/112411227-86501b00-8d57-11eb-94b1-c6d65b5424e3.png)
![image](https://user-images.githubusercontent.com/60660505/112411235-8bad6580-8d57-11eb-985e-f10198e85b13.png)

### 结论

微应用独立运行的时候没有这个问题，把微应用加载到主应用中时就会这样。

**Comment by uWydnA** [comment]
你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题

**Comment by aiyoudiao** [comment]
> 你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题

嗯，话虽有道理，但是子应用独立运行时正常，用qiankun正常挂载后，就运行不正常了，您有啥指教吗？我这几天就有在看single-spa和qiankun的源码。

**Comment by aiyoudiao** [comment]
> 你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题
只用single-spa，也是正常的噢。这也许是qiankun的一个bug。
![image](https://user-images.githubusercontent.com/60660505/112795170-b3c00000-909a-11eb-9868-5ffc75cfeca0.png)

**Comment by eightHundreds** [comment]
把沙箱关掉就快了

**Comment by sukai-cheng** [comment]
为什么感觉前端比后端难得多

**Comment by zhutou1280** [comment]
> > 你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题
> > 只用single-spa，也是正常的噢。这也许是qiankun的一个bug。
> > ![image](https://user-images.githubusercontent.com/60660505/112795170-b3c00000-909a-11eb-9868-5ffc75cfeca0.png)

大哥解决了吗，我这边搞3D也出现了这个问题，用loadMicroAPP设置sandbox为false也不行，只有注册方式，并且设置sandBox为false才不卡顿。

**Comment by z-9527** [comment]
> > > 你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题
> > > 只用single-spa，也是正常的噢。这也许是qiankun的一个bug。
> > > ![image](https://user-images.githubusercontent.com/60660505/112795170-b3c00000-909a-11eb-9868-5ffc75cfeca0.png)
> 
> 大哥解决了吗，我这边搞3D也出现了这个问题，用loadMicroAPP设置sandbox为false也不行，只有注册方式，并且设置sandBox为false才不卡顿。

一样遇到了卡顿的问题，用loadMicroAPP设置sandbox为false也不行，只有注册方式，把沙箱关掉就好了一点，但是又遇到了样式冲突的问题，唉，头疼

**Comment by GitHubJackson** [comment]
> > 你应该自己解决作为该3D子应用被加载到主应用以后，出现的renderObject被触发多次的问题
> 
> 嗯，话虽有道理，但是子应用独立运行时正常，用qiankun正常挂载后，就运行不正常了，您有啥指教吗？我这几天就有在看single-spa和qiankun的源码。

大佬最终有什么解决思路么？同样遇到这个问题，难受
