### ISSUE TITLE
[Bug]在微应用上应用font-awesome字体时会出问题。

### ISSUE THREAD

**Issue by MrSeaWave** [umijs/qiankun#1343]
## What happens?

当在微应用的html中引用第三方css如`https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.css` 时，会出错。

## 最小可复现仓库

使用官网仓库即可

## 复现步骤，错误日志以及相关配置

1. [官网`examples/react16/public/index.html`](https://github.com/umijs/qiankun/blob/master/examples/react16/public/index.html) 中增加`<link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3/css/all.css"/>`
如
![image](https://user-images.githubusercontent.com/21967852/112587142-05b51b80-8e38-11eb-996d-98f16f0d0668.png)
2. [官网`examples/react16/src/pages/Home.js`](https://github.com/umijs/qiankun/blob/master/examples/react16/src/pages/Home.js) 替换成
```jsx
import React from 'react';

export default function() {
  return (
    <>
    <h2 className="app-nav-item" style={{ borderColor: 'red' }}>
      Home
    </h2>
    <i class="fab fa-accessible-icon"></i>
    </>
  );
}
```
其他不作任何修改。

3. 运行`npm run start:main` 和`npm run start:react16"`

如果只打开`react16`即`http://localhost:7100/`则图标正常展示出来。如：
![image](https://user-images.githubusercontent.com/21967852/112587654-f4b8da00-8e38-11eb-808a-0c2a3a6e3175.png)

如果在主应用`main`的界面`http://localhost:7099/react16`查看`react16`微应用的界面，发现图标不会展示。

![image](https://user-images.githubusercontent.com/21967852/112587964-8c1e2d00-8e39-11eb-8bde-3d4100f4d78f.png)

**错误提示**

font资源加载主应用的。实际上需要去加载`https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.3`
![image](https://user-images.githubusercontent.com/21967852/112588052-ba037180-8e39-11eb-80dd-e8d00c2ec9ec.png)

## 相关环境信息

- **qiankun 版本**: `2.4.0`
- **浏览器版本**：谷歌浏览器`版本 89.0.4389.90（正式版本） (x86_64)`
- **操作系统**：Mac

**Comment by MrSeaWave** [comment]
问题和 #981 差不多

**Comment by dovahkiin-p** [comment]
"小的文件（图片、字体等）直接转成 base64 打进 js"
(⑉･̆-･̆⑉)

**Comment by kuitos** [comment]
duplicated with #981
