### ISSUE TITLE
微应用本地开发方式

### ISSUE THREAD

**Issue by ppxu** [umijs/qiankun#1344]
假如项目是1个主应用+10个子应用组成的，本地开发的时候要想看到完整的效果，是不是要开启11个本地服务，还是有什么更便捷的方法

**Comment by gongshun** [comment]
可以把一部分子应用部署好，切换 entry 即可

**Comment by carvinlo** [comment]
我理解微前端需要的开发调试场景有：
主应用（开发）调试子应用（本地服务或测试环境）
子应用（开发）调试主应用（单仓库模式或调试包）与子应用（本地服务或测试环境）

主应用：单仓库模式、调试包（离线包或 npm registry）、线上服务（测试环境与生产环境）
子应用：单仓库模式、本地服务、线上服务（测试环境与生产环境）

@ppxu 你需要的是本地服务吧，可以本地 node 搭建个 service，然后（单仓库模式）批量发布到本地服务上去，然后开启主（子）应用调试模式，联调各个子应用。
