### ISSUE TITLE
首次访问子应用路由时正常，二次访问时报异常：Uncaught Error: application 'sub-app' died in status NOT_MOUNTED: [qiankun] Target container with #qiankun not existed while sub-app mounting!

### ISSUE THREAD

**Issue by wanghongjiajijingjing** [umijs/qiankun#1347]
![image](https://user-images.githubusercontent.com/20553130/112715825-a92c2c00-8f1d-11eb-9238-209f427db47e.png)
![image](https://user-images.githubusercontent.com/20553130/112715833-b1846700-8f1d-11eb-84e6-7ba581b6d297.png)

这几种方式都试过，依然没解决

**Comment by gongshun** [comment]
![image](https://user-images.githubusercontent.com/29347231/112740410-60bd4e80-8faf-11eb-86e8-1ac5217b5f1d.png)

**Comment by wanghongjiajijingjing** [comment]
我的主应用是react，也没有使用什么过度效果，
![image](https://user-images.githubusercontent.com/20553130/112783870-e0681d80-9082-11eb-89f1-2efd813b978d.png)
![image](https://user-images.githubusercontent.com/20553130/112783908-f5dd4780-9082-11eb-9cee-901bd94c0d46.png)

**Comment by houzhitaohzt** [comment]
这个问题解决了么？@wanghongjiajijingjing

**Comment by cuixi** [comment]
> 我的主应用是react，也没有使用什么过度效果， ![image](https://user-images.githubusercontent.com/20553130/112783870-e0681d80-9082-11eb-89f1-2efd813b978d.png) ![image](https://user-images.githubusercontent.com/20553130/112783908-f5dd4780-9082-11eb-9cee-901bd94c0d46.png)

同问，react子路由碰到这个问题，没有使用过渡效果，有解决办法吗 @gongshun

**Comment by gongshun** [comment]
> 同问，react子路由碰到这个问题，没有使用过渡效果，有解决办法吗 @gongshun

https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-after-xxx-mounted 子应用有 document.write 也可能会导致这个报错，其他的原因，暂时没发现，没有人提供复现demo
