### ISSUE TITLE
接入React微应用 antd message 组件失效

### ISSUE THREAD

**Issue by authetic-x** [umijs/qiankun#1349]
## What happens?

主应用为 Vue，接入React+Ant Design 微应用后，微应用中的 message 全局提示组件失效了

## 原因
这里翻阅antd message 组件文档时，初步觉得是以下问题，大牛们有什么好的解决办法吗？
<img width="1350" alt="message-error" src="https://user-images.githubusercontent.com/35717670/112817179-bc253480-90b4-11eb-8a84-057af86103bd.png">

**Comment by mcmicahelchan** [comment]
> ## What happens?
> 主应用为 Vue，接入React+Ant Design 微应用后，微应用中的 message 全局提示组件失效了
> 
> ## 原因
> 这里翻阅antd message 组件文档时，初步觉得是以下问题，大牛们有什么好的解决办法吗？
> <img alt="message-error" width="1350" src="https://user-images.githubusercontent.com/35717670/112817179-bc253480-90b4-11eb-8a84-057af86103bd.png">

你好，请问你找到解决方案了吗？

**Comment by gyt95** [comment]
我也是，唯独这个message组件的样式失效了。
![1637031677(1)](https://user-images.githubusercontent.com/23090676/141888120-902f5141-e7f1-435f-8a89-6e740eb31b68.png)

**Comment by laommmm** [comment]
> > > ## What happens?
> > > 主应用为 Vue，接入React+Ant Design 微应用后，微应用中的 message 全局提示组件失效了
> > > ## 原因
> > > 这里翻阅antd message 组件文档时，初步觉得是以下问题，大牛们有什么好的解决办法吗？
> > > <img alt="message-error" width="1350" src="https://user-images.githubusercontent.com/35717670/112817179-bc253480-90b4-11eb-8a84-057af86103bd.png">
> > 
> > 
> > 你好，请问你找到解决方案了吗？
> 
> 没找到问题的原因。解决方案是主应用在qiankun的生命周期钩子中提供一个对象，该对象封装主应用的提示组件。

最后怎么解决的？重新封装Message？

**Comment by authetic-x** [comment]
我当时的解决方案是让主应用暴露Element UI的 toast组件，在qiankun生命周期方法里拿到，没有再使用message组件了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 接入React微应用 antd message 组件失效 (#1349)





    
What happens?
 
主应用为 Vue，接入React+Ant Design 微应用后，微应用中的 message 全局提示组件失效了
 
原因
 
这里翻阅antd message 组件文档时，初步觉得是以下问题，大牛们有什么好的解决办法吗？
 
  
你好，请问你找到解决方案了吗？
  
没找到问题的原因。解决方案是主应用在qiankun的生命周期钩子中提供一个对象，该对象封装主应用的提示组件。
  
最后怎么解决的？重新封装Message？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
