### ISSUE TITLE
[RFC] 部署 nginx配置问题

### ISSUE THREAD

**Issue by panasamsara** [umijs/qiankun#1350]
## 问题

> https://qiankun.umijs.org/zh/cookbook 官方教程中，部署方案1：微应用都放在在一个特殊名称，nginx配置问题

## 解决方式

> 此时nginx不用配置子项目，否则nginx会报：rewrite or internal redirection cycle （nginx错误日志）
浏览器network 500，拿不到资源，导致子项目渲染不出来

**Comment by gongshun** [comment]
啥问题？能否录个屏看一下？

**Comment by panasamsara** [comment]
https://v.youku.com/v_show/id_XNTEzMDAxNDQ2OA==.html    录屏传了优酷，就是nginx配置了子项目之后 拿不到子项目资源
