### ISSUE TITLE
angular7子应用采用懒加载时，初次加载该模块，需要重复点击a标签

### ISSUE THREAD

**Issue by yizeshun** [umijs/qiankun#1351]
## What happens?
主应用、子应用都是angular7，当子应用某些模块采用懒加载模式且该模块比较臃肿时，会出现导航到子应用时，需要点击a标签多次的问题。排查发现，第一次点击是加载了子应用的懒加载模块，浏览器路由没有跳转（准确的说是跳转返回了），第二次点击或者第三次点击后，浏览器路由才会正常跳转并渲染对应的子应用的模块。该现象只在第一次加载的时候出现。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by ycpaladin** [comment]
我遇到过这种情况， 你是不是通过 history.pushState({}, '', '')  的方式访问子应用的？
如果是的话，观察network，点击第一次浏览器会加载该模块相关的js文件，不会跳转，点第二次的时候，由于第一次已经下载过文件了，就可以跳转了。



建议使用ng内置的 routerLink 指令跳转， 或者 router.navigate() 或者router.navigateByUrl(‘’) 跳转
