### ISSUE TITLE
请问现在支持子应用单独配置layout么

### ISSUE THREAD

**Issue by jinghh** [umijs/qiankun#1353]
子应用的一些页面不想要主应用的，页头和侧边栏，这个该怎么配？

**Comment by jinghh** [comment]
还有钉钉群已经满了，可以开个新群么

**Comment by gongshun** [comment]
可以把 隐藏/展示 侧边栏和页头的数据放在路由上，然后子应用配置路由钩子函数，props给父应用传数据，父应用隐藏掉

**Comment by gongshun** [comment]
> 还有钉钉群已经满了，可以开个新群么

钉钉群二维码已更新

**Comment by jinghh** [comment]
> > 还有钉钉群已经满了，可以开个新群么
> 
> 钉钉群二维码已更新

好的，3q
