### ISSUE TITLE
浏览器刷新导致js文件加载错误

### ISSUE THREAD

**Issue by ermu592275254** [umijs/qiankun#1355]
## What happens?
部署到测试环境后，能正常访问主应用和子应用但是在刷新时会出现chunk-vendors.js文件拉取错误，拉取到的资源为index.html文件的内容
![image](https://user-images.githubusercontent.com/16870968/113236588-bc514a00-92d7-11eb-9bb6-2616b0929e0b.png)
![image](https://user-images.githubusercontent.com/16870968/113236637-d723be80-92d7-11eb-9c2f-becaabee3103.png)

## Mini Showcase Repository(REQUIRED)
这是我的打包配置

vue.config.js
```
module.exports = {
  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'development',
  // .....后面为开发配置
}
```
nginx.config
```
server {
    listen 80;
    server_name localhost;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location ^~ /intelligent-station-authority {
        proxy_pass http://10.255.50.129:31931;
    }
    location ^~ /intelligent-station-sidedoor {
        proxy_pass http://10.255.50.62:31932;
    }
}
```
主应用和子应用时分开部署的，其中主应用使用history路由模式，子应用使用hash模式

最新发现，正常访问的静态资源路径时有static的
![image](https://user-images.githubusercontent.com/16870968/113238262-012ab000-92db-11eb-90ec-7c00b53b3ed8.png)
但是刷新后请求静态资源的路径中static消失了
![image](https://user-images.githubusercontent.com/16870968/113238329-25868c80-92db-11eb-8a82-6cff85d7aa68.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:  ^2.4.0
- **Platform Version**:  any
- **Browser Version**: any

**Comment by shangyunsi** [comment]
感觉像是nginx或者路由的问题呢

**Comment by masansi** [comment]
请问问题解决了吗
