### ISSUE TITLE
微应用使用position:fixed；left:0;top:0后跳到页面最顶端

### ISSUE THREAD

**Issue by yang200258** [umijs/qiankun#1357]
<img width="1434" alt="截屏2021-04-01 下午12 22 59" src="https://user-images.githubusercontent.com/38518538/113243129-0260da80-92e5-11eb-90cf-b9e2b2e2c15f.png">
如图，红色框是属于微应用的，但是设置样式为position:fixed；left:0;top:0后，跨过微应用的容器边界了。
我也设置sandbox:{strictStyleIsolation: true, experimentalStyleIsolation: true}了，
请问如何解决？

**Comment by gongshun** [comment]
样式本来就是相通的，因为属于同一个document，这种问题无法解决

`trictStyleIsolation: true` 使用 shadow dom，dom 会分隔开，但是会带来新的问题

**Comment by yang200258** [comment]
> 样式本来就是相通的，因为属于同一个document，这种问题无法解决
> 
> `trictStyleIsolation: true` 使用 shadow dom，dom 会分隔开，但是会带来新的问题

什么新的问题？

**Comment by gongshun** [comment]
> 什么新的问题？

![image](https://user-images.githubusercontent.com/29347231/113291795-1da00a00-9326-11eb-8ca3-af2b3bac9abf.png)

**Comment by yang200258** [comment]
解决

**Comment by yang200258** [comment]
> > 什么新的问题？
> 
> ![image](https://user-images.githubusercontent.com/29347231/113291795-1da00a00-9326-11eb-8ca3-af2b3bac9abf.png)

这种情况下，请问我用umi，该怎么修改查找根节点的位置？

**Comment by liulianjunqaq** [comment]
> 解决

您好，请问这个问题有解决吗？怎么解决的啊
