### ISSUE TITLE
子应用加载三方js，url中带&参数会被import-html-entry 转义为&amp;导致fetch到的js功能不全（高德地图）影响使用

### ISSUE THREAD

**Issue by Chinalink** [umijs/qiankun#1359]
### 问题现象：

子应用有配置如下script

`https://webapi.amap.com/maps?v=1.4.15&amp;key=1234567890&amp;plugin=AMap.Driving`

被import-html-entry时，将`&`转义为了`&amp;`

`https://webapi.amap.com/maps?v=1.4.15&amp;key=1234567890&amp;plugin=AMap.Driving replaced by import-html-entry`

导致类似高德地图，百度地图等依赖key才有的功能，全部失效

**Comment by gongshun** [comment]
我试了下，没问题啊

子应用中的 js

![image](https://user-images.githubusercontent.com/29347231/113371722-9ee4b480-9399-11eb-95a2-08e712488f7b.png)

主应用中的dom

![image](https://user-images.githubusercontent.com/29347231/113371772-b3c14800-9399-11eb-94db-3447af4a80ce.png)

主应用发起的请求

![image](https://user-images.githubusercontent.com/29347231/113371789-bd4ab000-9399-11eb-80da-d94e4b67ddbe.png)

**Comment by lilixiang5473** [comment]
我也是，fetch第三方百度地图的Link和Script的内容，cors跨域，导致乾坤直接崩掉，怎么解决？

**Comment by northdrift** [comment]
> 
可以在主应用中配置getTemplate将&amp;转回成&。

**Comment by a15218378694** [comment]
> 我也是，fetch第三方百度地图的Link和Script的内容，cors跨域，导致乾坤直接崩掉，怎么解决？

同问
