### ISSUE TITLE
umi搭建微应用在不同主应用上表现不同

### ISSUE THREAD

**Issue by yang200258** [umijs/qiankun#1360]
你好！使用umi作为微应用，主应用分别上**purehtml**（**正常表现**）和**fish**搭建的portal项目（**无法读取入口文件）**
1、微应用使用umi，配置如下：
<img width="477" alt="截屏2021-04-02 上午9 19 20" src="https://user-images.githubusercontent.com/38518538/113369706-832adf80-9394-11eb-9cd3-cd571b856267.png">
入口文件src/app.js：
<img width="435" alt="截屏2021-04-02 上午9 19 57" src="https://user-images.githubusercontent.com/38518538/113369739-99d13680-9394-11eb-913e-f02fc28eae00.png">
2、purehtml主应用入口文件及目录结构（**在此应用下表现正常**）：
<img width="439" alt="截屏2021-04-02 上午9 40 52" src="https://user-images.githubusercontent.com/38518538/113370864-870c3100-9397-11eb-9584-96a11c362a52.png"><img width="160" alt="截屏2021-04-02 上午9 41 10" src="https://user-images.githubusercontent.com/38518538/113370888-8ffd0280-9397-11eb-9b7b-a5d190a0735d.png">
3、fish框架下配置及入口文件：（**无法读取微应用下入口文件**）
<img width="1426" alt="截屏2021-04-02 上午9 45 30" src="https://user-images.githubusercontent.com/38518538/113371136-2d583680-9398-11eb-8dc8-309861fc2db7.png">
<img width="561" alt="截屏2021-04-02 上午9 45 55" src="https://user-images.githubusercontent.com/38518538/113371147-3a752580-9398-11eb-8ae4-68b77dd2d9ec.png">
<img width="809" alt="截屏2021-04-02 上午9 47 03" src="https://user-images.githubusercontent.com/38518538/113371209-6395b600-9398-11eb-80be-b89ef4df993d.png">

目前找不到原因，也根据官网出现的问题一一排查，发现并没有错误，请问该如何解决这个问题，或者排查的方向在哪里？不知道qiankun是如何读取微应用的入口文件的。。。
多谢🙏

**Comment by yang200258** [comment]
这种异常情况中，页面表现是：不会出现#root里面的元素
<img width="954" alt="截屏2021-04-02 上午9 50 02" src="https://user-images.githubusercontent.com/38518538/113371454-fc2c3600-9398-11eb-9598-fa95e21e596f.png">

**Comment by yang200258** [comment]
发现问题所在，主应用文件中引入了一个fish-desktop-require.js，不知道是不是因为采用了AMD模块化规范导致的问题

**Comment by yang200258** [comment]
引入的fish-desktop-require定义了define
<img width="547" alt="截屏2021-04-02 上午11 32 46" src="https://user-images.githubusercontent.com/38518538/113377542-284eb380-93a7-11eb-8f78-765573c0f9eb.png">
但是打包的入口文件也定义了define：
<img width="623" alt="截屏2021-04-02 上午11 33 25" src="https://user-images.githubusercontent.com/38518538/113377575-3f8da100-93a7-11eb-88e1-6eed45d1141b.png">
会不会是这个原因导致的？

**Comment by gongshun** [comment]
在 https://github.com/umijs/qiankun/issues/1362 解决，这个先关闭了
