### ISSUE TITLE
主应用和微应用同时加载定义了define导致无法获取微应用入口文件

### ISSUE THREAD

**Issue by yang200258** [umijs/qiankun#1362]
主应用中引入的fish-desktop-require定义了define
<img width="547" alt="截屏2021-04-02 上午11 32 46" src="https://user-images.githubusercontent.com/38518538/113377542-284eb380-93a7-11eb-8f78-765573c0f9eb.png">
但是微应用打包的入口文件也定义了define：
<img width="623" alt="截屏2021-04-02 上午11 33 25" src="https://user-images.githubusercontent.com/38518538/113377575-3f8da100-93a7-11eb-88e1-6eed45d1141b.png">

请教这个如何解决？

**Comment by gongshun** [comment]
参考这个 https://github.com/umijs/qiankun/issues/1216#issuecomment-762579410

**Comment by yang200258** [comment]
已解决

**Comment by LegendTian** [comment]
> 已解决

请问咋解决的？

**Comment by xiaoxiaofei2016** [comment]
> 已解决

同问，怎么解决的

**Comment by LegendTian** [comment]
您好，您的来信已收到，我将在最短时间内给你回复。谢谢！

**Comment by yang200258** [comment]
> > 已解决
> 
> 请问咋解决的？

<img width="469" alt="image" src="https://user-images.githubusercontent.com/38518538/219359033-401ed245-3046-45e7-bdd7-e8829195a886.png">

**Comment by yang200258** [comment]
> > 已解决
> 
> 同问，怎么解决的

<img width="469" alt="image" src="https://user-images.githubusercontent.com/38518538/219359064-c5dcb909-a8b9-458f-a00c-7a7fd971246d.png">

**Comment by xiaoxiaofei2016** [comment]
> > > 已解决
> > 
> > 
> > 同问，怎么解决的
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/38518538/219359064-c5dcb909-a8b9-458f-a00c-7a7fd971246d.png">

感谢，我去试一下
