### ISSUE TITLE
[RFC] 问题请教，主应用子应用都有大量菜单，都在左侧，需要把子应用的路由都配置到主应用里面吗

### ISSUE THREAD

**Issue by victorWuxz** [umijs/qiankun#1367]
## 背景

> 主应用子应用都有大量菜单，都在左侧，目前可以判断子应用是不是在微前端模式下隐藏自己的菜单，但需要把子应用所有的菜单配置到主应用么

## 思路

> 主应用子应用都有大量菜单，都在左侧，目前可以判断子应用是不是在微前端模式下隐藏自己的菜单，但需要把子应用所有的菜单配置到主应用么

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by gongshun** [comment]
你可以把菜单数据由子应用传给主应用

**Comment by victorWuxz** [comment]
谢谢

**Comment by changeLong** [comment]
> 你可以把菜单数据由子应用传给主应用

这样得先加载子应用把
