### ISSUE TITLE
微应用嵌入框架后，导致内存占用增加，出现卡顿，独立运行没有问题

### ISSUE THREAD

**Issue by AloneZL** [umijs/qiankun#1368]
微应用单独启动没有问题，一旦嵌入到qiankun中就会出现多次渲染，内存增加的情况，考虑是否是引用single-spa的时候出现问题，希望官方重视下性能问题，已经严重影响到框架的使用

**Comment by Tinet-zhangmd** [comment]
> 微应用单独启动没有问题，一旦嵌入到qiankun中就会出现多次渲染，内存增加的情况，考虑是否是引用single-spa的时候出现问题，希望官方重视下性能问题，已经严重影响到框架的使用

请问您这边怎么处理的？

**Comment by jiangyh1024** [comment]
@AloneZL 请问 你解决这个问题了吗？ 我也遇到了
