### ISSUE TITLE
Set window.event while sandbox destroyed or inactive in XXX

### ISSUE THREAD

**Issue by yang200258** [umijs/qiankun#1369]
在使用umi3作为子应用，purehtml作为主应用情况下，umi中配置：memo.output.libraryTarget('window');
入口文件：
<img width="454" alt="截屏2021-04-07 上午10 39 15" src="https://user-images.githubusercontent.com/38518538/113802569-81468f00-978d-11eb-97e4-4fa769fb1c4b.png">
但是并没有触发入口文件的函数，切换到别的应用后报错：
<img width="840" alt="截屏2021-04-07 上午10 39 59" src="https://user-images.githubusercontent.com/38518538/113802636-9f13f400-978d-11eb-8701-c1078a20c3fe.png">

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1431#issuecomment-833274000

**Comment by MarceCandil** [comment]
Have you guys found any solution for this case?

**Comment by ccysmd** [comment]
老哥解决方案分享一下嘞

**Comment by GreatAuk** [comment]
+1
