### ISSUE TITLE
使用 create-react-app 创建出来的子项目，如果有 code split，子项目的 js 加载路径出错

### ISSUE THREAD

**Issue by jkchao** [umijs/qiankun#137]
## What happens?

在示例中，点击 app2 的子路由，会出现加载 js 文件出错的提示

## Mini Showcase Repository(REQUIRED)

https://github.com/jkchao/qiankun-error

## How To Reproduce

app-root 是主应用，安装包，启动子项目与主项目后，点击 app2 -> app2 的子路由，出现报错

## Context

- **Platform**: macOS
- **Browser Version**:  chrome 78
- **Node Version**: 10.15

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#why-dynamic-imported-assets-missing

**Comment by jkchao** [comment]
本地可以这么解决，生产环境不能这么玩吧，难到要给不同的生产环境（测试，预发，正式等）配置不同的 publicPath 吗，而且我们测试都有 6 个环境

**Comment by kuitos** [comment]
生产环境建议静态资源上 cdn。
如果不能 cdn，不同环境部署时注入不同的环境变量，这个应该是 CI 工具的基本能力吧

**Comment by kuitos** [comment]
想了一下，qiankun 可以提供配合 webpack 提供运行时 publicPath 注入，这几天会支持掉

**Comment by jkchao** [comment]
现在我的解决办法是，在 bootstrap 生命周期动态注入 __webpack_public_path__，这种办法是可以的，但是我觉得在每个子应用里面修改，成本有点大，在 qiankun registerMicroApps 里动态注入每个子应用的 __webpack_public_path__ 似乎是一种更合适的方法。

**Comment by kuitos** [comment]
是的，本周会支持掉，可以watch 一下 release 公告

**Comment by yangangzhang** [comment]
> 现在我的解决办法是，在 bootstrap 生命周期动态注入 **webpack_public_path**，这种办法是可以的，但是我觉得在每个子应用里面修改，成本有点大，在 qiankun registerMicroApps 里动态注入每个子应用的 **webpack_public_path** 似乎是一种更合适的方法。

您好，能说的具体点吗？子应用bootstrap的钩子注入webpack_public_path？这个如何定义呢？

**Comment by jkchao** [comment]
```ts
export async function bootstrap() {
    __webpack_public_path__ =  'xxx';
    // 其他代码
}

```

**Comment by yangangzhang** [comment]
> ```ts
> export async function bootstrap() {
>     __webpack_public_path__ =  'xxx';
>     // 其他代码
> }
> ```

明白了，感谢

**Comment by kuitos** [comment]
@jkchao @yangangzhang qiankun 已自动注入 publicPath，在 entry js 入口处加入如下代码即可：
```js
__webpack_public_path__ = window. __INJECTED_PUBLIC_PATH_BY_QIANKUN__
```

**Comment by jkchao** [comment]
`__webpack_public_path__` 的值应该是以 `/` 结尾的。

从源码来看[import-html-entry](https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L151) ，__INJECTED_PUBLIC_PATH_BY_QIANKUN__ 是获取的 domain，这样会有路径问题，如子应用是 `//localhost:8080`，那么请求相应文件的时候的路径是 `//localhost:8080static/xxx`
