### ISSUE TITLE
主应用采用umijs/qiankun-plugin,注册的container有解决方案么,mountElementId已废弃

### ISSUE THREAD

**Issue by ChenYCL** [umijs/qiankun#1374]
子应用注册需要指定id为app的节点,增加后,默认引入还是会有root-master这个下方节点,会导致很大一片空白区域
![image](https://user-images.githubusercontent.com/25706676/113829532-2ece9800-97b8-11eb-9127-d10a3d487326.png)

![image](https://user-images.githubusercontent.com/25706676/113829339-f9c24580-97b7-11eb-9765-28452f09efa4.png)

![image](https://user-images.githubusercontent.com/25706676/113829251-dac3b380-97b7-11eb-8934-889bc4fdaa25.png)

![image](https://user-images.githubusercontent.com/25706676/113829754-72290680-97b8-11eb-81a3-9528a127907f.png)

期望:
#app挂载在root-master > main节点下

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1217

**Comment by ChenYCL** [comment]
勉强删了root节点 ejs模版
