### ISSUE TITLE
[Feature Request] qiankun.start()是否可以在子应用启动后增加回调函数

### ISSUE THREAD

**Issue by junjie-lean** [umijs/qiankun#1375]
## Background

在项目中，调用start函数后，会立即跳转到一个页面，该页面引用了到了qiankun子应用，在到该页面的时候，会等到fetch完毕后才能渲染页面。

## Proposal

现在的解决办法是：

1. 在执行完start后，延迟跳转页面。
2. 在跳转后的页面增加loading动效，利用`MutationObserver`对象监听跳转后子应用加载完毕后，撤除loading。

如果增加了start的回调函数，并且对perfetch做出处理，则该问题迎刃而解。

**Comment by gongshun** [comment]
start 是同步函数，增加回调没必要吧？

> 调用start函数后，会立即跳转到一个页面

调用 start 为啥会跳转路由？

**Comment by junjie-lean** [comment]
> start 是同步函数，增加回调没必要吧？
> 
> > 调用start函数后，会立即跳转到一个页面
> 
> 调用 start 为啥会跳转路由？

不管函数是同步还是异步，start() 后会加载子应用资源，这个网络请求过程是异步的。跳转路由是业务需求，和技术栈无关。

**Comment by gongshun** [comment]
你是需要一个loading ？ https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles

![image](https://user-images.githubusercontent.com/29347231/117388207-e91eff80-af1c-11eb-8cb0-2fa4c984de00.png)
