### ISSUE TITLE
[RFC] 使用loadMicroApp手动加载多个应用时存在性能问题，求优化

### ISSUE THREAD

**Issue by nlsy520** [umijs/qiankun#1380]
### 背景：

当在一个页面使用loadMicroApp手动加载应用时，无论这个应用如何简单，都需要消耗至少200ms-400ms（平均在300ms左右）的微前端执行时间，才能执行到应用中的代码。
由于js是单线程执行，如果加载了10个应用，那么这个耗时在2-4s，应用越多，时间越长。
当前我们的项目中就是这种场景，导致首屏渲染性能很差。所以希望能对手动加载多个应用进行优化，减少这一过程的消耗时间。

**Comment by kuitos** [comment]
300ms 这个耗时是无法避免的，你可以单独窗口打开一个微应用看下 performance，基本上仅是解析 html 耗时就差不多 300ms了，还不算之后的 evaluate script。
![image](https://user-images.githubusercontent.com/5206843/114350992-93b13600-9b9c-11eb-9eb1-5b8090f0705d.png)

你需要解决的应该是在这种大量应用同时加载的情况下，然后加一些过渡动画或者其他的优化手段，让网站「看起来」打开的更快一点~

**Comment by dovahkiin-p** [comment]
我觉得前端的性能优化主要可以围绕加载和渲染这两个维度来，具体到首屏优化，如果前两个维度已经尝试过了，如楼上所言，还可以在交互上上手，“让网站「看起来」打开的更快一点~”。
加载多个子应用，这个性能很难去避免。
