### ISSUE TITLE
请问有交流群吗？希望与各位使用qiankun框架的大佬一起交流学习

### ISSUE THREAD

**Issue by Sincerity7788** [umijs/qiankun#1387]
期待可以得到官方的回复以及提供一些交流社区和资源
也很期待各位用qiankun框架大佬的朋友一起有个好的交流
我的微信： Accompany_life520
期待各位大佬的加入

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh

![image](https://user-images.githubusercontent.com/29347231/114659890-f46c7a00-9d26-11eb-9228-29e286044f58.png)

**Comment by ruizhengyun** [comment]
> 期待可以得到官方的回复以及提供一些交流社区和资源
> 也很期待各位用qiankun框架大佬的朋友一起有个好的交流
> 我的微信： Accompany_life520
> 期待各位大佬的加入

可以看官网 https://qiankun.umijs.org/zh，有钉钉群二维码

**Comment by zhuijing** [comment]
@gongshun 大佬，群已经满了，有新群吗？🙏
