### ISSUE TITLE
[Bug]使用npm安装 build无法输入es文件夹 报错

### ISSUE THREAD

**Issue by 3potato** [umijs/qiankun#1389]
使用npm命令代替yarn 执行build会报错
更换成yarn 可以解决
请问是什么原因导致的啊？

**Comment by gongshun** [comment]
安装依赖需要用yarn install ，打包可以用npm

![QQ图片20210414205728](https://user-images.githubusercontent.com/29347231/114714119-62836200-9d64-11eb-93a2-dd2339dd1baa.png)
