### ISSUE TITLE
vue主应用，引入zone.js添加angular8子引用。Target container with #appContainer not existed while catalog mounting!

### ISSUE THREAD

**Issue by limzgiser** [umijs/qiankun#1391]
主应用使用vue+ts实现，子应用需要接入angular8的系统。引入zone.js。发现，我第一次登录进入系统，子应用可以正常访问。只要我退出登录，再登录，就报错。zone.js?4027:182 Uncaught Error: [qiankun] Target container with #appContainer not existed while catalog mounting!。去掉zone.js不报错，但是angular8的子应用就无法加载。
![image](https://user-images.githubusercontent.com/27998168/114959193-269ce980-9e97-11eb-98d5-bd8783f85d20.png)

**Comment by deepthan** [comment]
Hi @limzgiser  我也在集成angular8，目前在往angular8切换的时候会卡顿，你有这种情况吗？
