### ISSUE TITLE
experimentalStyleIsolation进行样式隔离-对话框问题

### ISSUE THREAD

**Issue by bingxueyinlian** [umijs/qiankun#1395]
# 使用experimentalStyleIsolation进行样式隔离时，自定义的对话框样式失效。

## 引起该问题的原因
配置了experimentalStyleIsolation后，qiankun给自定义的子应用div加上了data-qiankun="xxx"的属性，样式也被自动添加了相应的前缀。而子应用的对话框是直接添加到了body标签下，而不在data-qiankun="xxx"的div下。

如果对话框挂到data-qiankun="xxx"的div下时，样式是生效的，但是模态对话框没法全屏遮罩，所以对话框还只能加到body标签下。

由于使用的第3方组件库的对话框，没法自己给body下这个挂对话框的div自动加上data-qiankun="xxx"的属性，因为这个div是自动生成的。也不能用js暴力添加，因为主应用也有用这个对话框的地方（主应用的对话框div是不需要添加data-qiankun="xxx"属性的）。而且从标签上无法区分是主应用的对话框还是子应用的对话框。

请问各位大神：这种问题在样式隔离的前提下，该如何解决？

## 相关环境信息

- **qiankun 版本**
2.4.0
- **浏览器版本**：
Chrome 90.0.4430.72
- **操作系统**：
Windows 10 2004

**Comment by kuitos** [comment]
组件库配置将弹框这类 div 插入到应用自己的容器里，而不是插入到 body，如 [antd 里的全局 getPopupContainer 配置](https://ant.design/components/config-provider-cn/#API)

**Comment by jojo-1995** [comment]
在该模式下遇到相同问题（experimentalStyleIsolation），放在自己的容器中，样式遮罩是局部的，没有全框，怎么解决

**Comment by 00ming** [comment]
插入到自己容器里面  遮罩会有层级问题 大佬们这个怎么解决

**Comment by zhuanghongbin** [comment]
@jojo-1995 请问最后怎么解决的？

**Comment by Dashuai-Black** [comment]
这个具体应该怎么解决 看1061的回答有点摸不到头脑 有人有具体方案么

**Comment by Rahim-Chan** [comment]
> 组件库配置将弹框这类 div 插入到应用自己的容器里，而不是插入到 body，如 [antd 里的全局 getPopupContainer 配置](https://ant.design/components/config-provider-cn/#API)

感觉这种挺难的，因为实际业务开发排期约束很多，子应用有自己的独立开发排期，跟主应用策略不能同步

**Comment by Hew007** [comment]
> 1061
解决了吗？

**Comment by Hew007** [comment]
> 将弹框这类 div 插入到应用自己的容器里，而不是插入到 body

怎么解决得

**Comment by Mr-Song-Yu** [comment]
可以通过webpack配置第三方库的前缀，比如ant design，可以通过loader配置@ant-prefix来实现这种样式的隔离

**Comment by Hew007** [comment]
> 可以通过webpack配置第三方库的前缀，比如ant design，可以通过loader配置@ant-prefix来实现这种样式的隔离

你说的只是样式隔离的问题，现在是开启了隔离，内部浮窗不能超过子应用容器（也就是shadow dom的范围）
