### ISSUE TITLE
关于微应用第一次激活时，主应用的 beforeLoad 钩子到微应用的 bootstrap 钩子执行耗时的问题

### ISSUE THREAD

**Issue by matteao03** [umijs/qiankun#1396]
## 现状
-  在生产环境下，微应用的包体积也会比较大。 微应用在第一次激活时，从主应用的 `beforeLoad` 钩子到微应用的`bootstrap`钩子执行完毕，大概会需要 3s~ 4s 左右，页面会出现空白区域，给用户一种不好的体验。
- 微应用中有 `position:fixed` 的 dom 时， 会和主应用的根节点平级，并插入在主应用的根节点前面。 这个问题，官方有规避的方案吗？

## 设想
可不可以在用户开始访问项目时，预执行一下微应用的`bootstrap`钩子。 用户有耐心等待第一个页面，却无耐心等待微应用的页面加载。

## 最小可复现仓库
[qiankun-need](https://github.com/matteao03/qiankun-need)

## 复现步骤，错误日志以及相关配置
**主应用的访问路径为： http://localhost:8080, 微应用的访问路径为：http://localhost:7100**
- 按照README.md 启动主应用和微应用， 访问主应用，点击**login**， 进入dashboard 页
- 点击左侧栏**子应用**， 访问子应用
- F12 打开chrome 调试工具，可以看到如下信息
```
before load sub-app
 ***************乾坤钩子 - 加载前***************
1618753759483
***************微应用 - bootstrap***************
1618753761887
before mount sub-app
***************乾坤钩子 - 渲染前*************** Object

```
- 结论：主应用的 `beforeLoad` 钩子到微应用的`bootstrap`钩子执行完毕，比较耗时。
## 相关环境信息

- **qiankun 版本**： 2.4.0
- **浏览器版本**：chrome (版本高一点，无特殊要求)
- **nodejs**： 10.13.0

**Comment by kuitos** [comment]
目测是子应用本身 js 过大，导致 js 解析比较耗时，这种情况要么考虑通过拆包优化子应用首屏资源大小，要么在交互上改善「慢」的问题。

> 可不可以在用户开始访问项目时，预执行一下微应用的bootstrap钩子。 用户有耐心等待第一个页面，却无耐心等待微应用的页面加载。

不太行，preload 不同于 prefetch，会抢占 js 线程，做了这个之后很可能变成负优化，导致整站首屏都变慢，而且还有沙箱的问题也需要考虑。

**Comment by shichuanpo** [comment]
> 目测是子应用本身 js 过大，导致 js 解析比较耗时，这种情况要么考虑通过拆包优化子应用首屏资源大小，要么[在交互上改善「慢」](https://github.com/umijs/qiankun/issues/1380#issuecomment-817530546)的问题。
> 
> > 可不可以在用户开始访问项目时，预执行一下微应用的bootstrap钩子。 用户有耐心等待第一个页面，却无耐心等待微应用的页面加载。
> 
> 不太行，preload 不同于 prefetch，会抢占 js 线程，做了这个之后很可能变成负优化，导致整站首屏都变慢，而且还有沙箱的问题也需要考虑。

那如何获取子应用的一些配置信息（如：子应用抛出一些业务模块组件，或者路由信息）

**Comment by matteao03** [comment]
>目测是子应用本身 js 过大，导致 js 解析比较耗时，这种情况要么考虑通过拆包优化子应用首屏资源大小，要么在交互上改善「慢」的问题。

从减小子应用打包的体积的角度考虑，我们希望可以复用公共依赖。 对于主应用和多个子应用都需要引入的公共依赖（私有的业务组件库），我们考虑采用主应用加载公共依赖，然后挂载到window 对象上, 子应用直接从window上取值使用，避免打包。对于这种方案的复用依赖，有没有副作用？有其他可选方案吗？

**Comment by peakcool** [comment]
同关注这个问题，在官网上只看到以下信息，如图：
![image](https://user-images.githubusercontent.com/14804014/117425059-0374cf80-af55-11eb-9fa9-944b7e677d90.png)

`external `有尝试过，不确定官方在2.0版本中是否有更好的方案来解决复用依赖问题
