### ISSUE TITLE
如何挂载angular子应用的单个模块？

### ISSUE THREAD

**Issue by ColaLovingCat** [umijs/qiankun#1397]
在挂载基于angular框架的子应用时，不希望把 菜单/标题等 位于app.component里面的元素挂载上去，只需要挂载路由中调用的component或模块，请问有什么解决方法吗？

**Comment by gongshun** [comment]
props 可以动态传递数据，通知子应用隐藏，或者你直接判断是否在 qiankun 中

**Comment by ColaLovingCat** [comment]
> props 可以动态传递数据，通知子应用隐藏，或者你直接判断是否在 qiankun 中

在主应用的loadMicroApp中已经添加了props，但是angular子应用在何处和如何接收这些数据？同时子应用要如何判断自身在qiankun的模式中呢？谢谢

**Comment by ColaLovingCat** [comment]
> > props 可以动态传递数据，通知子应用隐藏，或者你直接判断是否在 qiankun 中
> 
> 在主应用的loadMicroApp中已经添加了props，但是angular子应用在何处和如何接收这些数据？同时子应用要如何判断自身在qiankun的模式中呢？谢谢

判断 (window as any).__POWERED_BY_QIANKUN__ 好像是可以的，不过还是想问：angular子应用在何处和如何接收主应用props的数据

**Comment by gongshun** [comment]
> angular子应用在何处和如何接收主应用props的数据

看文档，https://qiankun.umijs.org/zh/api#initglobalstatestate

**Comment by hanalice** [comment]
@gongshun any other solution in mount a seperate elements or module in host app?
