### ISSUE TITLE
Styles and scripts are removed from the DOM if the micro app being loaded has any redirects.

### ISSUE THREAD

**Issue by sesanchit** [umijs/qiankun#1398]
I am integrating different Angular projects in my Qiankun application. In case if any micro app has redirects, my original scripts, styles or infact entire index.html file contents of the main app is removed from the DOM.
Please, let me know if anyone is aware of how to handle this.

In case of rendering I have handled it like this. 

ReactRender.jsx

export default function render({ loading }) {
  let subappContainer;
  const container = document.getElementById('subapp-container');
  if (container == null) {
    subappContainer = document.createElement('main');
    subappContainer.setAttribute('id', 'subapp-container');
    document.body.appendChild(subappContainer);
  }
  ReactDOM.render(<Render loading={loading} />, container || subappContainer);
}

Because of refresh the subapp-container element is removed from DOM. I reconstruct it and my micro app is able to load. But, original scripts, styles from main application is not retained.

**Comment by maurer2** [comment]
You could just keep the empty subapp-container in the html template rather than creating it on the fly.
If you don't want it to take up any space, you can just hide the empty wrapper via

```
.subapp-container:empty {
    display: none;
}
```

**Comment by sesanchit** [comment]
Hi @maurer2 - In most cases, it works fine for me. What happens is in certain cases the subapp-container is not present in the DOM. Therefore, we are not able to render the micro app. For that, I figured out the hack and added the earlier mentioned code. 

ReactRender.jsx

export default function render({ loading }) {
let subappContainer;
const container = document.getElementById('subapp-container');
if (container == null) {
subappContainer = document.createElement('main');
subappContainer.setAttribute('id', 'subapp-container');
document.body.appendChild(subappContainer);
}
ReactDOM.render(, container || subappContainer);
}

From the code above, I just reconstuct the subapp-container element and micro app is able to load. But, the main thing is any prior <link>, <script> <style> , etc. tags present on the conatiner or main app index.html gets removed from the DOM. This is where I need help. Why it gets removed and how can I make it reload?
I even tried to use React styled-components. It has also the same behavior, the style section is missing from the DOM.
Please assist.

**Comment by sesanchit** [comment]
Hi @maurer2  - I will try to reproduce the issue and submit a sample repo to test. Meanwhile, I have created this PR which fixes an essential rendering issue. Kindly review - https://github.com/umijs/qiankun/pull/1401

**Comment by sesanchit** [comment]
Hi @maurer2 and @kuitos - I have reproduced this issue here - https://github.com/sesanchit/qiankun
Please have a look. Let me know if you have the access or need one. 

Basically, here I am just modifying React 15 app with this change

  componentDidMount() {
    document.body.innerHTML = "";
  }
  
This will remove the subapp-container so the app would not render after mount. This is just a hack. But, this is similar to what I am facing in real application. Basically, I don't know exactly in one of our apps is there a redirection or some script is causing DOM to be removed. For that, I added this code in ReactRender.jsx to handle. But, my original HTML is lost. How can I rebuild my container / main or root app HTML from ReactRender.jsx. My app is able to mount and render but all my scripts and styles in the main gets lost. 

export default function render({ loading }) {
  let subappContainer;
  const container = document.getElementById('subapp-container');
  if (container == null) {
    subappContainer = document.createElement('main');
    subappContainer.setAttribute('id', 'subapp-container');
    document.body.appendChild(subappContainer);
  }
  ReactDOM.render(<Render loading={loading} />, container || subappContainer);
}

**Comment by kuitos** [comment]
You can try to add a dom breakpoint to find who removed your container element like this:
![image](https://user-images.githubusercontent.com/5206843/115722850-fc28c000-a3b1-11eb-819d-e7a2695db890.png)

If your application did something to remove the container element, it must be crashed even it runs along, while without any micro frontend context.

If that‘s true, you have to find and resolve your application bug firstly.

**Comment by sesanchit** [comment]
Sure @kuitos I will give it a try. And one thing is Qiankun limited to JS apps or can it be used to load an ASP .NET app as well. One of our apps is an ASP .NET app. Not sure if we can handle it directly. We are planning to load it in an iframe otherwise.

**Comment by kuitos** [comment]
I am not familiar to ASP.NET, it also a server side rendering way like jsp?

If so you could check [this doc](https://qiankun.umijs.org/guide/tutorial#micro-app-built-without-webpack) to see if it's helpful.
