### ISSUE TITLE
service-worker使用问题

### ISSUE THREAD

**Issue by ppxu** [umijs/qiankun#1399]
之前项目中使用service-worker缓存静态资源，做了微前端拆分后现在每个应用打包的时候都会生成一份sw文件，但是整体访问的时候只有主应用的sw生效了，子应用如果单独访问的话sw也是有效的，集成到主应用里就不行，请问有没有办法能让主子应用都能使用sw缓存各自的静态资源

**Comment by kuitos** [comment]
没有办法。see https://github.com/umijs/qiankun/issues/908

**Comment by ywj87132749** [comment]
不用看了，集成后，sw不会生效的
