### ISSUE TITLE
各个子项目是否支持独立部署，独立运行？

### ISSUE THREAD

**Issue by mlqgg** [umijs/qiankun#14]
旧的react项目接入到主项目中去，需要在入口文件处导出生命周期，这样挂载的过程就被放到了mount周期中去，导致子项目无法独立运行，只有通过主项目的入口才能正常访问。有没有办法可以保证既能顺利接入到主项目中，又能够作为一个独立的项目继续运行？

**Comment by kuitos** [comment]
2 种方式：
1. 编译期通过环境变量打出两份包，一份含生命周期等钩子一份不含
2. 主工程中提供运行时全局变量，子应用通过这个全局变量判断要以那种方式启动

**Comment by gaorubin1990** [comment]
是否可以在子应用添加生命周期函数，然后生命周期js文件直接执行mount()函数。解决这个问题？

**Comment by kuitos** [comment]
@gaorubin1990 需要判断下当前在哪个环境，不然在集成模式下会执行两次

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#how-to-make-sub-app-to-run-independently
