### ISSUE TITLE
路由采用hash模式（均为vue工程），主应用路由中打开子应用，首次成功，切换页面后报错Uncaught Error: application 'vue' died in status SKIP_BECAUSE_BROKEN: [qiankun] Target container with #subapp-container not existed while vue mounting!

### ISSUE THREAD

**Issue by zhangxue12345** [umijs/qiankun#1400]
**主应用注册子应用：**
registerMicroApps(
  [
    [{](url)
      name: 'vue',
      entry: '//localhost:7101',
      container: '#subapp-container',
      activeRule: '/#/subapp',
    }
  ],
  {
    beforeLoad: [
      app => {
        console.log('[LifeCycle] before load %c%s', 'color: green;', app.name);
      },
    ],
    beforeMount: [
      app => {
        console.log('[LifeCycle] before mount %c%s', 'color: green;', app.name);
      },
    ],
    afterUnmount: [
      app => {
        console.log('[LifeCycle] after unmount %c%s', 'color: green;', app.name);
      },
    ],
  },
);
**主应用路由配置：**
{
    path: '/subapp',
    component: Layout,
    children: [
      {
        path: 'about',
        component: () => import('@/views/test/myvue.vue'),
        name: 'subapp',
        meta: { title: 'subapp', icon: 'subapp', affix: true }
      }
    ]
  }
**myvue页面**（PS：如果将id="subapp-container"放在APP.vue中则无此问题）
template中：div id="subapp-container"></div

mounted:
mounted () {
    if(!window.qiankunStarted) {
      window.qiankunStarted = true
      start()
    }
  }

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-while-xxx-mounting

**Comment by Cyxwmm** [comment]
你好，请问这个问题解决了吗？

**Comment by chengkai2022** [comment]
我是主应用history模式。子应用hash和history都有这个问题，你解决了吗

**Comment by qw789** [comment]
最后咋解决的？

**Comment by chengkai2022** [comment]
> 最后咋解决的？

我的是界面的渐入不能有 ，mode="out-in"去掉就行了

**Comment by lijiapeng0302** [comment]
> > 最后咋解决的？
> 
> 我的是界面的渐入不能有 ，mode="out-in"去掉就行了

找了两个小时  靠谱
