### ISSUE TITLE
ie11、win7，子应用无法加载出来，控制台也没报错。win10，ie11是正常的

### ISSUE THREAD

**Issue by luhuaxin** [umijs/qiankun#1402]
## What happens?

ie11、win7，子应用无法加载出来，控制台也没报错。win10，ie11是正常的

## 最小可复现仓库

官方demo

## 相关环境信息

ie版本：11.0.9600.16428  
操作系统：win7 64x  
qiankun：2.4.0

**Comment by kuitos** [comment]
@gongshun 你那边有 win7, ie11 的测试环境吗

**Comment by gongshun** [comment]
> @gongshun 你那边有 win7, ie11 的测试环境吗

我这边电脑是win10的，我感觉和win7/win10没有关系，应该和IE11和版本有关。

**Comment by kuitos** [comment]
issue 里说的那个版本能搞到不？

**Comment by luhuaxin** [comment]
> issue 里说的那个版本能搞到不？
这里有个 http://xiazai.sogou.com/detail/34/8/-6317619799740042012.html?uID=A29C6C71E33D990A000000006076BEC7

**Comment by gongshun** [comment]
> issue 里说的那个版本能搞到不？

找到了对应的版本，http://baoku.360.cn/soft/show/appid/103511066，但是安装不了，我再研究一下

![image](https://user-images.githubusercontent.com/29347231/116551900-fccdd300-a92a-11eb-8f92-d9cf6f6e3ece.png)

**Comment by gongshun** [comment]
我在IE10上重新了你的场景：跳转路由，子应用无法加载出来，控制台也没报错。稍后排查下原因

![ie](https://user-images.githubusercontent.com/29347231/116564967-027de580-a938-11eb-988b-4a2cdef69848.gif)

**Comment by gongshun** [comment]
打 debug 发现 single-spa 有这么一段代码：https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/applications/apps.js#L419

![image](https://user-images.githubusercontent.com/29347231/116571177-6bb42780-a93d-11eb-8ce5-db5ee38a92e9.png)


而在IE10下，`location.origin` 是undefined，导致后面的正则匹配返回 false，所以子应用没有激活。mdn 兼容性说明 ：https://developer.mozilla.org/en-US/docs/Web/API/Location/origin#browser_compatibility

所以只需要让IE10支持 `location.origin` 即可，在主项目入口文件 import 兼容文件，内容如下（记得单独一个文件）：

```js
if (!window.location.origin) {
    window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
}
```

效果如下，

![IE10](https://user-images.githubusercontent.com/29347231/116571044-50e1b300-a93d-11eb-9ffa-b79d5ef4337e.gif)

IE10能加载出来，我相信，你这个版本的IE11肯定可以

**Comment by kuitos** [comment]
是不是可以给 single-spa 提供 pr 兼容一下？

**Comment by luhuaxin** [comment]
> 打 debug 发现 single-spa 有这么一段代码：https://github.com/single-spa/single-spa/blob/f28b5963be1484583a072c8145ac0b5a28d91235/src/applications/apps.js#L419
> 
> ![image](https://user-images.githubusercontent.com/29347231/116571177-6bb42780-a93d-11eb-8ce5-db5ee38a92e9.png)
> 
> 而在IE10下，`location.origin` 是undefined，导致后面的正则匹配返回 false，所以子应用没有激活。mdn 兼容性说明 ：https://developer.mozilla.org/en-US/docs/Web/API/Location/origin#browser_compatibility
> 
> 所以只需要让IE10支持 `location.origin` 即可，在主项目入口文件 import 兼容文件，内容如下（记得单独一个文件）：
> 
> ```js
> if (!window.location.origin) {
>     window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
> }
> ```
> 
> 效果如下，
> 
> ![IE10](https://user-images.githubusercontent.com/29347231/116571044-50e1b300-a93d-11eb-9ffa-b79d5ef4337e.gif)
> 
> IE10能加载出来，我相信，你这个版本的IE11肯定可以

好的，非常感谢！

**Comment by kuitos** [comment]
single-spa released v5.9.3 and fixed it
