### ISSUE TITLE
国际化项目，主应用切换语言时，子应用无效

### ISSUE THREAD

**Issue by shaoqiwang-fe** [umijs/qiankun#1403]
## What happens?

国际化项目，主应用切换语言时，子应用无效

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: @umijs/plugin-qiankun": "^2.24.1"
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api#initglobalstatestate 通知一下子应用切换语言

**Comment by gongshun** [comment]
参考demo https://github.com/gongshun/qiankun-vue-demo/tree/feature/share-dependencies

**Comment by shaoqiwang-fe** [comment]
> 参考demo https://github.com/gongshun/qiankun-vue-demo/tree/feature/share-dependencies

子应用使用这个setLocale(globalState?.locale, false);无效

**Comment by gongshun** [comment]
https://github.com/gongshun/qiankun-vue-demo/blob/8f1debca512f660cfe1e9d7490bd3ca9b440d2c0/app-vue-history/src/main.js#L40

不同的版本 i18n 可能有一些差异
