### ISSUE TITLE
[Bug] loadMicroApp如何直接打开一个APP的特定页面

### ISSUE THREAD

**Issue by blessing-gao** [umijs/qiankun#1404]
需求：使用loadMicroApp打开子应用的特定页面，渲染在父应用的特定地址
现象：通过loadMicroApp只能打开子应用首页

**Comment by gongshun** [comment]
entry 仅仅是为了拿子应用的 index.html，无法指定路由的。

如果你想加载指定的页面，你需要先加载子应用，然后跳转到对应的路由。至于怎么跳转，取决于你的子应用使用何种路由模式

**Comment by yehaikuo** [comment]
> 需求：使用loadMicroApp打开子应用的特定页面，渲染在父应用的特定地址
> 现象：通过loadMicroApp只能打开子应用首页

通过props传参过去，让子应用打开特定页面

**Comment by chaolei** [comment]
> > 需求：使用loadMicroApp打开子应用的特定页面，渲染在父应用的特定地址
> > 现象：通过loadMicroApp只能打开子应用首页
> 
> 通过props传参过去，让子应用打开特定页面

请问一下，这样操作，会影响地址栏里的路由吗？

**Comment by chaolei** [comment]
> entry 仅仅是为了拿子应用的 index.html，无法指定路由的。
> 
> 如果你想加载指定的页面，你需要先加载子应用，然后跳转到对应的路由。至于怎么跳转，取决于你的子应用使用何种路由模式

请问一下，这样操作，会影响地址栏里的路由吗？我们现在的需求是浏览器里的地址栏地址不要变，然后子应用里的路由可以跳转

**Comment by gongshun** [comment]
> 请问一下，这样操作，会影响地址栏里的路由吗？我们现在的需求是浏览器里的地址栏地址不要变，然后子应用里的路由可以跳转

![image](https://user-images.githubusercontent.com/29347231/124429474-8329e980-dda0-11eb-95e9-a7365455ca37.png) @chaolei

**Comment by Mrtaochen** [comment]
> > 请问一下，这样操作，会影响地址栏里的路由吗？我们现在的需求是浏览器里的地址栏地址不要变，然后子应用里的路由可以跳转
> 
> 子应用使用特殊的路由模式就行了 ![image](https://user-images.githubusercontent.com/29347231/124429474-8329e980-dda0-11eb-95e9-a7365455ca37.png) @chaolei

为什么react-router的hash模式不支持呢 @gongshun

**Comment by gongshun** [comment]
> 为什么react-router的hash模式不支持呢 @gongshun

https://github.com/umijs/qiankun/issues/1199#issuecomment-818740774

**Comment by hanalice** [comment]
> > 请问一下，这样操作，会影响地址栏里的路由吗？我们现在的需求是浏览器里的地址栏地址不要变，然后子应用里的路由可以跳转
> 
> 子应用使用特殊的路由模式就行了 ![image](https://user-images.githubusercontent.com/29347231/124429474-8329e980-dda0-11eb-95e9-a7365455ca37.png) @chaolei

2023/11 现在angular-router 支持了嘛？需求一样，需要浏览器里的地址栏，但是子应用里面路由跳转。

具体场景是，我们的子应用的某个页面是主应用的一部分，所以需要保持浏览器地址栏是主应用的地址，但是这个页面里面的一部分需要加载子应用的某一个页面

@gongshun @kuitos

**Comment by lmqian** [comment]
我使用vue2+vue-router3+qianjun2遇到了相同的问题，经过一番查找：

1. 似乎vue-router4 的createMemoryHistory可以解决这个问题，但是还未验证。
2. 使用loadMicroApp，通过props将要加载的子应用路由传递到子应用，然后子应用中初始化vue实例前根据主应用当前路由修改routes数据，试了下效果可以达到，但为深究其潜在隐患。如下：

- 主应用：
```
this.microApp = loadMicroApp({
    name: "vue2-sub",
    entry: "http://localhost:8081",
    container: "#mix_sub_container",
    props: { from: this.$router.currentRoute.path, to: "/some" },
  });
```
子应用：
```
function render(props = {}) {
  ...
  if (props && props.from && props.to) {
    let targetRoute = findRoute(routes, "", props.to)
    if (targetRoute) {
      targetRoute.path = props.from;
    }
  }
  ...
}

function findRoute(routes, parentPath, findPath) {
  for(const route of routes) {
    let path = route.path;
    if(!path.startsWith("/")) {
      path = parentPath + "/" + path;
    }
    if(path == findPath) {
      return route;
    }
    if(route.children && route.children.length > 0) {
      let foundRoute = findRoute(route.children, path, findPath);
      if(foundRoute) {
        return foundRoute;
      }
    }
  }
  return null;
}
```
