### ISSUE TITLE
[Bug] 使用loadMicroApp加载一个子应用时，卸载的时机太晚，会导致子应用先监听到路由变化

### ISSUE THREAD

**Issue by csu-feizao** [umijs/qiankun#1405]
## What happens?

主应用使用loadMicroApp加载一个子应用时，当主应用的路由改变，子应用卸载的时机太晚，会导致子应用先监听到路由变化

### 现状
在主应用的 App.tsx 组件使用 `loadMicroApp` 加载了子应用，当主应用从 App 切换到 Main 时，会手动调用子应用的 unmount。
但是因为调用 unmount 的时机太晚，在子应用卸载之前，子应用里面先监听到路由的变化，进入到一个错误的路由。

我尝试利用 `single-spa` 触发的事件如 `single-spa:before-routing-event` 来实现主应用监听路由变化，但是主应用没能成功监听到这些事件

### 期望
`loadMicroApp` 能够提供一个办法让主应用能在子应用之前先监听到路由的改变，及时卸载子应用

#### 主应用
![image](https://user-images.githubusercontent.com/14802930/115651288-74b16180-a35d-11eb-8aae-55799be08ae3.png)

#### 子应用
![image](https://user-images.githubusercontent.com/14802930/115651219-564b6600-a35d-11eb-8e07-e750752987ee.png)

#### 录屏
子应用进入到一个非预期路由时，控制台会打印一个 `detail mount 非预期`

[录屏](https://github.com/csu-feizao/qiankun-demo#%E5%BD%95%E5%B1%8F)

## 最小可复现仓库

https://github.com/csu-feizao/qiankun-demo

## 复现步骤，错误日志以及相关配置

来回切换主应用的路由

## 相关环境信息

- **qiankun 版本** 最新
- **浏览器版本**：chrome
- **操作系统**：mac

**Comment by kuitos** [comment]
unmount 是你的代码手动调用触发的，所以这个时机需要你自己来控制

**Comment by csu-feizao** [comment]
> unmount 是你的代码手动调用触发的，所以这个时机需要你自己来控制

嗯嗯，是需要自己来控制，但是目前主应用无法在子应用之前监听到路由变化，期望能够提供一个类似`single-spa:before-routing-event`的事件来让主应用能够在子应用变化之前搞事情

**Comment by kuitos** [comment]
loadMicroApp api 都是走手动调用模式的，不会去做路由监听和匹配的事情，你可能性需要自己去通过 react-router 的一些功能做这类事情

**Comment by csu-feizao** [comment]
> loadMicroApp api 都是走手动调用模式的，不会去做路由监听和匹配的事情，你可能性需要自己去通过 react-router 的一些功能做这类事情

好吧，目前打算在主应用通过拦截掉全局的 `addEventListener` 和 `popstate` 事件来解决这个问题

**Comment by fyzwjd** [comment]
非手动方式load也会有这个问题：前提子应用加载资源很慢，在子应用激活状态下刷新页面，（子应用尚未加载完）然后切换到主应用页面，待子应用加载完后，页面路由会自动切回子应用

**Comment by yanglisunny** [comment]
怎么处理呢

**Comment by AprilXtt** [comment]
> 非手动方式load也会有这个问题：前提子应用加载资源很慢，在子应用激活状态下刷新页面，（子应用尚未加载完）然后切换到主应用页面，待子应用加载完后，页面路由会自动切回子应用

我遇到这个问题了 请问怎么解决
