### ISSUE TITLE
部分手机无法在 微信环境下加载 子应用

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1412]
子应用是vue-cli3 + vue2 搭建的老项目。qiankun 是vue-cli4 +vant+ ts的。主应用跟主应用在不同服务器，nginx 已经代理。目前发现小米cc9 这款手机在微信环境下无法正常加载子应用

在微信环境下，无法加载子应用，报错如下：
Uncaught TypeError: application 'report-app' died in status LOADING_SOURCE_CODE: Failed to fetch
/qiankun/share-app/js/chunk-vendors.b1d8f473.js:1:38472 TypeError: application 'report-app' died in status LOADING_SOURCE_CODE: Failed to fetch

然后用手机的浏览器跟企业微信，均正常打开

## 相关环境信息

- **qiankun 版本**2.4.0
- **浏览器版本**：微信8.0.2
- **操作系统**：MI CC9 Pro 版本：MUI 11.2 ｜稳定版

**Comment by JuSanZhi** [comment]
现在将主应用的静态资源放到oss 上面，然后报了这个错

抓包发现，其实已经加载了子应用的域名了，但是之后就没有进行下一步请求了。求助

**Comment by JuSanZhi** [comment]
@gongshun

**Comment by gongshun** [comment]
这个报错就是文件没有请求到，可能的原因：
1. 跨域被阻止
2. 文件的确不存在，检查是否是缓存了index.html，导致 js 路径错了
3. 网络不通

**Comment by JuSanZhi** [comment]
> 这个报错就是文件没有请求到，可能的原因：
> 
> 1. 跨域被阻止
> 2. 文件的确不存在，检查是否是缓存了index.html，导致 js 路径错了
> 3. 网络不通

问题就在于，目前只有少数手机会这样，而且只在微信环境有这个问题，尝试清除微信缓存，但还是很难定位问题

**Comment by gongshun** [comment]
> qiankun/share-app/js/chunk-vendors.b1d8f473.js

这个文件路径是否正确？

**Comment by JuSanZhi** [comment]
> > qiankun/share-app/js/chunk-vendors.b1d8f473.js
> 
> 这个文件路径是否正确？

路径是正确的，但目前已经没有这个路径了，除了index。html 静态资源全部放在oss 上了，所以目前只会报了 script error

**Comment by JuSanZhi** [comment]
@gongshun 
![image](https://user-images.githubusercontent.com/24559368/121794203-0a1ff200-cc39-11eb-9f3e-8f6acdc39f60.png)

**Comment by Ljay92** [comment]
留个爪，我这边也一样这种情况

**Comment by gucovip** [comment]
+1
