### ISSUE TITLE
[Bug/Feature Request]strictStyleIsolation: true下子应用使用iconfont.js引入的图标丢失

### ISSUE THREAD

**Issue by buhichan** [umijs/qiankun#1419]
## Background

当sandbox内为strictStyleIsolation时, iconfont上下载的iconfont.js不可用, 是由于iconfont使用了SVGUseElement + SVGSymbolElement, 而qiankun不拦截svg元素. svg相关issue: https://github.com/umijs/qiankun/issues/736, https://github.com/umijs/qiankun/issues/1202, 

我现在的解决办法就是我自己又去劫持了一遍HTMLBodyElement.prototype.insertBefore, 比较麻烦, 希望qiankun可以原生支持.

Reproduction: https://github.com/buhichan/qiankun_iconfont_issue  `yarn && yarn dev`

## Proposal

能否在sandbox上增加一个这样的api, 返回true表示自动劫持这个元素然后移动到对应的shadowRoot下面, 返回新HTMLElement则表示将新元素替代原有元素移动到shadowRoot下面.

```ts
import {start} from "qiankun"

type RemoveHijacking = ()=>void
type CustomHijackingLogic = ()=>RemoveHijacking
let customHijackElement: (el: HTMLElement, mountDom: Node)=>boolean | HTMLElement | CustomHijackingLogic

start({
      sandbox: {
           customHijackElement,
           strictStyleIsolation: true,
      }
})
```

## Additional context

如果上述API不太能加入qiankun的话, 那推荐的解决办法是什么? 推荐不用shadowDom模式?

我注意到sandbox有个[patchers](https://github.com/umijs/qiankun/blob/4e3e36c579e8a6ac0f882763379ec10103caaf74/src/interfaces.ts#L77)属性, 不过文档和代码里并没有用到这个属性, 也没标上`@deprecated`, 这是什么?

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/1061

**Comment by buhichan** [comment]
好的, 既然目前还没有能开箱即用的方案, 还是自己打补丁解决好了

**Comment by syvn** [comment]
> 好的, 既然目前还没有能开箱即用的方案, 还是自己打补丁解决好了

怎么进行补丁?
