### ISSUE TITLE
[Bug]动态样式清理出错

### ISSUE THREAD

**Issue by soulwu** [umijs/qiankun#142]
## What happens?

最新版本在切换子应用的时候，对动态样式的清理有可能出错，报
**Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.**

是不是应该在这里做一下保护会比较好

## 相关环境信息

- **浏览器版本**：
- **操作系统**：
- **Node 版本**：

**Comment by kuitos** [comment]
能提供一个可复现repo么

**Comment by soulwu** [comment]
> 能提供一个可复现repo么

问题是出现在我们完整项目中，还没有排查到具体的最小影响点。目前回滚到了1.1.5版本先恢复了。
当前初步猜测可能和引入了乐高的依赖有关系
