### ISSUE TITLE
qiankun部署问题

### ISSUE THREAD

**Issue by gitzhuyongfu** [umijs/qiankun#1420]
# 部署问题

## 问题如下

使用k8s部署主应用和微应用

部署方式如下：
 ingress ==>主应用（a:8000）==>微应用（b:10000）
出现的问题如下：
a访问b的时候出现跨域问题，但已经在devServer中配置了headers

  devServer: {
    disableHostCheck: true,
    port: port,
    headers: {
      'Access-Control-Allow-Origin': '*',
	  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'  
    },

但是主应用跟微应用之间通信都是正常的，主应用请求微应用，或者应用之间访问出现跨域，请问这种问题如何处理。

- **qiankun 版本**
"qiankun": "^2.0.16"

- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
devServer是开发环境的服务器，部署之后跨域，还得看你们用的啥服务器

**Comment by gitzhuyongfu** [comment]
你好，我们想实现的是docker环境部署，然后各个组件之间为单个容器，我通过主机+端口访问从而出现的跨域，这个需要怎么解决？

**Comment by haitaodesign** [comment]
> 你好，我们想实现的是docker环境部署，然后各个组件之间为单个容器，我通过主机+端口访问从而出现的跨域，这个需要怎么解决？

容器里面的 nginx 配置跨域就可以哦

**Comment by gitzhuyongfu** [comment]
你好，我这里的主容器和微应用都是通过npm run dev运行的，nginx通过proxy_pass转发到主容器，然后主容器跟微应用之间通信通过host:port方式就出现了跨域问题。

**Comment by haitaodesign** [comment]
> 你好，我这里的主容器和微应用都是通过npm run dev运行的，nginx通过proxy_pass转发到主容器，然后主容器跟微应用之间通信通过host:port方式就出现了跨域问题。

那你这个操作有点绕哦，直接支持跨域就可以了，干嘛要代理转发呀

**Comment by gitzhuyongfu** [comment]
已经设置了，devServer 上配置了主应用和微应用之间访问的跨域，但是不生效

**Comment by gongshun** [comment]
跨域问题实在解决不了，就让你们的运维来处理
