### ISSUE TITLE
子应用里路由跳转时对应组件执行两次render

### ISSUE THREAD

**Issue by zhaoky** [umijs/qiankun#1423]
## What happens?

点击对应路由跳转执行两次render，但当单独打开react16项目时，就只执行一次render

![image](https://user-images.githubusercontent.com/10738770/116088558-8fc10000-a6d4-11eb-91bf-2c1cb993dd2a.png)
![image](https://user-images.githubusercontent.com/10738770/116088514-83d53e00-a6d4-11eb-86b2-f77254728447.png)

## How To Reproduce

基于 https://github.com/umijs/qiankun/tree/master/examples

```js examples/react16/src/pages/Home.js
import React from 'react';

export default function() {
  console.log('home');
  return (
    <h2 className="app-nav-item" style={{ borderColor: 'red' }}>
      Home
    </h2>
  );
}

```
 examples/react16/src/pages/About.js 同上render里加了一个console

## Context

- **qiankun Version**: 2.4.1
- **Browser Version**: chrome 90.0.4430.85

**Comment by kuitos** [comment]
这个是 single-spa 的 「feature」 了，目前无解
see https://single-spa.js.org/docs/api#popstateevent https://github.com/single-spa/single-spa/pull/291#issuecomment-481472210

**Comment by hansonfang** [comment]
> > > 这个是 single-spa 的 「feature」 了，目前无解
> > > see
> > > 
> > > * https://single-spa.js.org/docs/api#popstateevent
> > > * [ Forcibly firing popstate event when pushState is called. Resolves #224.  single-spa/single-spa#291 (comment)](https://github.com/single-spa/single-spa/pull/291#issuecomment-481472210)
> > 
> > 
> > 你好，在引入乾坤并调用 start 方法时， vue-router4.x 的路由钩子会触发两次。 我看到qiankun 2.4.6 在 start 方法已经将 urlRerouteOnly 设置为 true 了， 但在single-spa 5.9.2 中 ![image](https://user-images.githubusercontent.com/26272801/129043731-765eef82-ba6c-4b15-8d87-6f253bc2c4ce.png) 通过vue-router 跳转后，这个方法被执行时，urlBefore !== urlAfter 这个条件始终为 true， 也就使 createPopStateEvent 被调用，最终导致 vue-router4.x 的钩子被触发两次，请问，像这种情况有什么好的方案吗
> 
> 遇到相同的问题，目前采用曲线救国的方式实现通过路径匹配进行相关逻辑处理： 在主应用router下index文件中添加popstate事件监听
> 
> ```js
> window.addEventListener('popstate', (event) => {
>   // 这里进行逻辑处理
>   // 可获取当前路由路径 event.state.current 上一个访问路径event.state.back
> })
> 
> 只对通过路由跳转的方式有效，a链接href访问的方式无效
> ```

没太明白监听popState事件可以做什么呢

**Comment by Angelnashuai** [comment]
> > > > 这个是 single-spa 的 「feature」 了，目前无解
> > > > see
> > > > 
> > > > * https://single-spa.js.org/docs/api#popstateevent
> > > > * [ Forcibly firing popstate event when pushState is called. Resolves #224.  single-spa/single-spa#291 (comment)](https://github.com/single-spa/single-spa/pull/291#issuecomment-481472210)
> > > 
> > > 
> > > 你好，在引入乾坤并调用 start 方法时， vue-router4.x 的路由钩子会触发两次。 我看到qiankun 2.4.6 在 start 方法已经将 urlRerouteOnly 设置为 true 了， 但在single-spa 5.9.2 中 ![image](https://user-images.githubusercontent.com/26272801/129043731-765eef82-ba6c-4b15-8d87-6f253bc2c4ce.png) 通过vue-router 跳转后，这个方法被执行时，urlBefore !== urlAfter 这个条件始终为 true， 也就使 createPopStateEvent 被调用，最终导致 vue-router4.x 的钩子被触发两次，请问，像这种情况有什么好的方案吗
> > 
> > 
> > 遇到相同的问题，目前采用曲线救国的方式实现通过路径匹配进行相关逻辑处理： 在主应用router下index文件中添加popstate事件监听
> > ```js
> > window.addEventListener('popstate', (event) => {
> >   // 这里进行逻辑处理
> >   // 可获取当前路由路径 event.state.current 上一个访问路径event.state.back
> > })
> > 
> > 只对通过路由跳转的方式有效，a链接href访问的方式无效
> > ```
> 
> 没太明白监听popState事件可以做什么呢
我使用的场景目的是避免 beforeEach 钩子中上报请求重复执行，因当时在beforeEach 中进行判断依旧无效

**Comment by MaTonna** [comment]
> > > > > 这个是 single-spa 的 「feature」 了，目前无解
> > > > > see
> > > > > 
> > > > > * https://single-spa.js.org/docs/api#popstateevent
> > > > > * [ Forcibly firing popstate event when pushState is called. Resolves #224.  single-spa/single-spa#291 (comment)](https://github.com/single-spa/single-spa/pull/291#issuecomment-481472210)
> > > > 
> > > > 
> > > > 你好，在引入乾坤并调用 start 方法时， vue-router4.x 的路由钩子会触发两次。 我看到qiankun 2.4.6 在 start 方法已经将 urlRerouteOnly 设置为 true 了， 但在single-spa 5.9.2 中 ![image](https://user-images.githubusercontent.com/26272801/129043731-765eef82-ba6c-4b15-8d87-6f253bc2c4ce.png) 通过vue-router 跳转后，这个方法被执行时，urlBefore !== urlAfter 这个条件始终为 true， 也就使 createPopStateEvent 被调用，最终导致 vue-router4.x 的钩子被触发两次，请问，像这种情况有什么好的方案吗
> > > 
> > > 
> > > 遇到相同的问题，目前采用曲线救国的方式实现通过路径匹配进行相关逻辑处理： 在主应用router下index文件中添加popstate事件监听
> > > ```js
> > > window.addEventListener('popstate', (event) => {
> > >   // 这里进行逻辑处理
> > >   // 可获取当前路由路径 event.state.current 上一个访问路径event.state.back
> > > })
> > > 
> > > 只对通过路由跳转的方式有效，a链接href访问的方式无效
> > > ```
> > 
> > 
> > 没太明白监听popState事件可以做什么呢
> > 我使用的场景目的是避免 beforeEach 钩子中上报请求重复执行，因当时在beforeEach 中进行判断依旧无效

请问有解决这个问题吗，我是子应用跳父应用的其他路由给我拼上了hash，看了下是子应用unmount之后又重新激活了一次
