### ISSUE TITLE
script动态标签造成代码逃逸

### ISSUE THREAD

**Issue by StarFishing** [umijs/qiankun#1424]
## What happens?

通过script标签创建的代码会穿过代理层到达主应用的环境造成变量污染

## Mini Showcase Repository(REQUIRED)
`    const script = document.createElement('script');
    script.innerText = 'console.log(window)';
    var firstScript = document.getElementsByTagName('script')[0];
    firstScript.parentNode.insertBefore(script, firstScript);`

## Context

- **qiankun Version latest:
- **Platform Version mac:
- **Browser Version chrom lates:

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1207 重复
