### ISSUE TITLE
样式隔离experimentalStyleIsolation:true时，style-component添加的动态样式丢失

### ISSUE THREAD

**Issue by jianyuxudeng** [umijs/qiankun#1426]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

通过experimentalStyleIsolation:true做样式隔离时，style-component添加动态样式，导致样式无法添加到对应的节点，样式丢失

## 最小可复现仓库
2.2.1版本发现该问题

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by AIEPhoenix** [comment]
可以尝试参照https://styled-components.com/docs/api 在子应用的入口使用StyleSheetManager 把样式的挂载节点放到乾坤的挂载容器上

**Comment by dleged** [comment]
设置 styled-components 加载方式，默认情况下生产环境是使用 CSSOMTag 的方式动态插入样式规则的，与 qiankun 的结合使用会存在问题；
只要关闭 CSSOMTag 的插入方式，使用 TextTag 插入的方式即可：
`<StyleSheetManager disableCSSOMInjection={true}> //你的应用代码 <StyleSheetManager/>`
