### ISSUE TITLE
希望能出一个dva做为主应用的demo；dva作为主应用，应用一直崩溃

### ISSUE THREAD

**Issue by yitjhy** [umijs/qiankun#1428]

**Comment by gongshun** [comment]
是热更新的问题？

**Comment by yitjhy** [comment]
> 是热更新的问题？
开发环境下只要在dva应用里start(),项目就会崩溃

入口文件：
`
import dva from 'dva';
import './index.css';
import { createBrowserHistory as createHistory } from 'history';
const app = dva({
  history: createHistory()
});

app.router(require('./router').default);

app.start('#root67');
`
router.js
`
import React from 'react';
import { Router, Route, Switch } from 'dva/router';
import IndexPage from './routes/IndexPage';
function RouterConfig({ history }) {
  return (
    <div>
      <Router history={history}>
        <Switch>
          <Route path="/baseHome" component={IndexPage} />
        </Switch>
      </Router>
    </div>
  );
}

export default RouterConfig;
`
IndexPage.js
`
import React, {useEffect} from 'react';
import { connect } from 'dva';
import styles from './IndexPage.css';
import {registerMicroApps, start} from "qiankun";

function IndexPage() {
  useEffect(() => {
    registerMicroApps([
      {
        name: "micro-app-react-1",
        entry: "//localhost:3001",
        container: "#frame",
        activeRule: "/baseHome/micro-app-react-1",
      },
    ]);
    start();
  })
  return (
    <div className={styles.normal}>
      <div className={styles.welcome} />
      <div id="frame">
        content
      </div>
    </div>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);
`
只要一进应用项目就崩溃
浏览器devtools报错：
`
webpackHotDevClient.js:60 WebSocket connection to 'ws://localhost:8000/sockjs-node' failed: `
打包node报错：
`
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
`
看起来像是热更新问题，但是不知道怎么解决，希望能出一个dva作为主应用的demo，希望帮忙解决下，🙏🙏

**Comment by yitjhy** [comment]
> 是热更新的问题？

### 开发环境下只要在dva应用里start(),项目就会崩溃



> 入口文件：

```
import dva from 'dva';
import './index.css';
import { createBrowserHistory as createHistory } from 'history';
const app = dva({
  history: createHistory()
});

app.router(require('./router').default);

app.start('#root');
```

> router.js

```
import React from 'react';
import { Router, Route, Switch } from 'dva/router';
import IndexPage from './routes/IndexPage';
function RouterConfig({ history }) {
  return (
    <div>
      <Router history={history}>
        <Switch>
          <Route path="/baseHome" component={IndexPage} />
        </Switch>
      </Router>
    </div>
  );
}

export default RouterConfig;
```

> IndexPage.js

```
import React, {useEffect} from 'react';
import { connect } from 'dva';
import styles from './IndexPage.css';
import {registerMicroApps, start} from "qiankun";

function IndexPage() {
  useEffect(() => {
    registerMicroApps([
      {
        name: "micro-app-react-1",
        entry: "//localhost:3001",
        container: "#frame",
        activeRule: "/baseHome/micro-app-react-1",
      },
    ]);
    start();
  })
  return (
    <div className={styles.normal}>
      <div className={styles.welcome} />
      <div id="frame">
        content
      </div>
    </div>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);
```
只要一进应用项目就崩溃
浏览器devtools报错：
```
webpackHotDevClient.js:60 WebSocket connection to 'ws://localhost:8000/sockjs-node' failed: `

```
打包node报错：
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
```
看起来像是热更新问题，但是不知道怎么解决，希望能出一个dva作为主应用的demo，希望帮忙解决下，🙏🙏

**Comment by CJY0208** [comment]
昨天遇到了相同问题，解决了

主要原因是子应用的热更新 socket 连到了基座上，导致基座崩溃

如下图，子应用 socket 默认指向 `${location.hostname}:${location.port}`，在基座模式下，子应用的 socket 指向了基座服务的地址，

![image](https://user-images.githubusercontent.com/18415774/122326414-da395d00-cf5e-11eb-86ee-89242b89baf0.png)


解决方案为：3001 子应用的 socket 端口需要显示指定 WDS_SOCKET_PORT 参数为 3001

下图参考 cra 建立的子应用 dev 命令

![image](https://user-images.githubusercontent.com/18415774/122326793-69467500-cf5f-11eb-8c2c-d1bd6916b1cc.png)

**Comment by kuangyedexiaomaolv** [comment]
> 昨天遇到了相同问题，解决了
> 
> #### 先列解决方案：**子应用的 socket 端口需要显式指定 WDS_SOCKET_PORT 参数**
> 以下问题流程做参考
> 
> * 基座：vue-cli 4.x
> * 子应用：create-react-app
> 
> 主要原因是 CRA 建立的子应用，其热更新 socket 连到了基座上，导致基座崩溃
> 
> 如下图，子应用 socket 默认指向 `${location.hostname}:${location.port}`，在基座模式下，子应用的 socket 指向了基座服务的地址，
> 
> ![image](https://user-images.githubusercontent.com/18415774/122326414-da395d00-cf5e-11eb-86ee-89242b89baf0.png)
> 
> 解决方案为：3001 **子应用的 socket 端口需要显式指定 WDS_SOCKET_PORT 参数**为 3001
> 
> 下图参考 cra 建立的子应用 dev 命令
> 
> ![image](https://user-images.githubusercontent.com/18415774/122326793-69467500-cf5f-11eb-8c2c-d1bd6916b1cc.png)

有用可以的
