### ISSUE TITLE
[Feature Request] 子项目中嵌套子项目

### ISSUE THREAD

**Issue by QxQstar** [umijs/qiankun#143]
## Background

我需要实现如下图所示的页面结构
![Lark20191111180034](https://user-images.githubusercontent.com/17845091/68579504-40225080-04af-11ea-9a88-7f6782be7e21.png)
顶部导航和左侧导航属于同一个项目（命名为fixed-project），它需要一直显示在界面中，项目fixed-project除了包含导航，还有自己的业务界面。红线框部分是另一个项目（命名为customers）,customers的装载点位于fixed-project中。fixed-project和customers是通过另一个项目（命名为基座）注册，加载的，基座中不写业务代码。

## Proposal
fixed-project的装载点在基座中，customers的装载点在fixed-project中，fixed-project需要一直显示。
这样的项目结构用qiankun可以实现吗？

**Comment by kuitos** [comment]
1.x 不支持，2.x 提供相应能力，可以先 watch 一波:smile:

**Comment by pool611** [comment]
有官方的例子么？子应用多层嵌套的例子
