### ISSUE TITLE
React主应用，在一个路由页面加载子应用，切换主应用路由，控制台警告

### ISSUE THREAD

**Issue by Cyxwmm** [umijs/qiankun#1431]
## React主应用，在一个路由页面加载子应用后，切换主应用路由，应该会执行子应用的unmount方法

当unmount方法为这样时
```ts
  export async function unmount(props) {
    // 这里没有做组件挂载操作，退出登录时，子应用容器已经销毁了
    const { container } = props;
      ReactDOM.unmountComponentAtNode(
        container
          ? container.querySelector('#root')
          : document.querySelector('#root')
      );
  }
```

控制台打印如下警告：
> [qiankun] Set window.event while sandbox destroyed or inactive in template! 
![image](https://user-images.githubusercontent.com/22393346/116413463-38549880-a86a-11eb-8b9d-794cd579993e.png)

**Comment by gongshun** [comment]
和 https://github.com/umijs/qiankun/issues/1369 一样的问题？

**Comment by Cyxwmm** [comment]
> 和 #1369 一样的问题？
应该是把
![image](https://user-images.githubusercontent.com/22393346/117235449-4baec780-ae59-11eb-98b1-5c450c35e478.png)
这个能知道是什么原因导致的吗？

**Comment by Cyxwmm** [comment]
是redux导致的吗?

**Comment by Cyxwmm** [comment]
Duplicate of #222

**Comment by michaelwang-ws** [comment]
> Duplicate of #222

It's not the same issue, in this case, no Error has been thrown, just warning
