### ISSUE TITLE
Need help - URL refresh Angular 9 hash mode

### ISSUE THREAD

**Issue by sesanchit** [umijs/qiankun#1434]
Hi Team,

I need help in understanding how to configure the URLs when the container/main app is hosted on the same server as subapps.
I am using Angular 9 in hash mode. Followed this guide - https://qiankun.umijs.org/cookbook#scenario-1-the-main-app-and-micro-apps-are-deployed-to-the-same-server-the-same-ip-and-port 
But, doesn't work. Could you please assist in the documentation of how to proceed with this. After URL refresh, I am directed to the corresponding sub app and doesn't stay on the container / main app.

**Comment by gongshun** [comment]
![image](https://user-images.githubusercontent.com/29347231/116638620-494ff780-a999-11eb-82a6-982b31887530.png)

for example

![image](https://user-images.githubusercontent.com/29347231/116638667-64bb0280-a999-11eb-91a0-ae2b26ccd967.png)

**Comment by sesanchit** [comment]
Hi @gongshun I have followed the similar steps. But, it doesn't work. Do I also need to set the baseHref ?

I have tried these steps.
say example 
container / main app -> https://example.com/app -> app is my container / main app
sub app -> https://example.com/app/mysubapp - > sub app

set the base href conditionally as /app/mysubapp if accessed directly else base-href = app-mysubapp if accessed via Qiankun container app.

registerMicroApps([
  {
    name: 'mysubapp',
    entry: 'https://example.com/app/mysubapp/',
    container: '#container',
    activeRule: '/app-mysubapp',
  }
  ]

But, it doesn't work. Please assist. I will try to create a repo and share the same.

**Comment by sesanchit** [comment]
Able to get this fixed. Thanks. Closing the issue.
