### ISSUE TITLE
使用antd Icon组件导致子应用style标签无限增加

### ISSUE THREAD

**Issue by Cyxwmm** [umijs/qiankun#1437]
## What happens?
使用antd Icon组件导致子应用style标签无限增加

## Mini Showcase Repository(REQUIRED)
[复现版本](https://github.com/Cyxwmm/micro-frontends-test)

## How To Reproduce
1. 点击登录成功，进入qiankun微前端部分
2. 在template1的时候，查看容器内的style标签为正常
3. 切换到template2后，再切换回来，style标签翻倍增长了

## Context

- **qiankun Version**:2.4.1
- **Platform Version**:
- **Browser Version**:

**Comment by Cyxwmm** [comment]
感觉是页面上有多少个Icon组件，就会添加多少个style标签

**Comment by kuitos** [comment]
复现仓库的 submodule 打不开

目测是依赖装的有问题，这个问题 antd 已经修复了 https://github.com/react-component/util/commit/eb6d4df109ff83f4d3cd573133a41946deb59bcc

**Comment by Cyxwmm** [comment]
> > 复现仓库的 submodule 打不开
> > 目测是依赖装的有问题，这个问题 antd 已经修复了 [react-component/util@eb6d4df](https://github.com/react-component/util/commit/eb6d4df109ff83f4d3cd573133a41946deb59bcc)
> 
> 我重新装了依赖，还是不行
> 然后我看了下Antd的版本是 4.15.5 他的依赖库 rc-util 是5.9.4，但是那个修复版本是5.9.6 不知道是不是这个问题导致的

**Comment by Cyxwmm** [comment]
> 复现仓库的 submodule 打不开
> 
> 目测是依赖装的有问题，这个问题 antd 已经修复了 [react-component/util@eb6d4df](https://github.com/react-component/util/commit/eb6d4df109ff83f4d3cd573133a41946deb59bcc)

submodule弄好了 [复现地址](https://github.com/Cyxwmm/micro-frontends-test1)
