### ISSUE TITLE
请教一下微信用用Ts开发 提示未导出生命周期函数，应该怎么写

### ISSUE THREAD

**Issue by lishuaifei3121** [umijs/qiankun#1439]
export  const bootstrap = ():void=>{
  //
  console.log('bootstrap');
}
export const mount = (props:any):void=>{
  renderDom(props.routePrefix);
}
export const unmount = ():void=>{
  //
  console.log('unmount');
}
或者这种
export async function bootstrap() {
  // console.log('bootstrap');
}
export async function mount(props:any) {
  renderDom(props.routePrefix);
}

export async function unmount() {
  console.log('unmount');
  // removeNewChild();
}
两种都不行 有大佬有写过吗

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1216#issuecomment-762579410
