### ISSUE TITLE
多个微应用使用高德地图，地图动态插入script脚本时，导致qiankun 报 wrapper element for XXX with instance xxx_123 is not existed

### ISSUE THREAD

**Issue by matteao03** [umijs/qiankun#1440]
## 背景
- 主应用通过`<script>`引入高德地图
- 多个微应用均使用高德地图功能
- 微应用通过`window` 获取高德地图对象
 
## 现状
在使用高德地图的微应用之间切换时，使用地图的具体页面会报 `“wrapper element for XXX with instance xxx_123 is not existed”`。 

## 复现过程
- 在微应用 `a` 中打开使用高德地图功能的页面，高德地图会动态的插入`script `脚本。 
- 然后切换到微应用 `b`中使用高德地图功能的页面， 会报 `“wrapper element for 微应用a  with instance 微应用a is not existed”` 。

## 排查结果
`/src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts`  62行 ~ 66行
```
  var unpatchDynamicAppendPrototypeFunctions = patchHTMLDynamicAppendPrototypeFunctions(function (element) {
    return elementAttachContainerConfigMap.has(element);
  }, function (element) {
    return elementAttachContainerConfigMap.get(element);
  });
```
在微应用 b 中执行 elementAttachContainerConfigMap.get(element)  ， 在匹配高德地图动态插入的script脚本对象时，匹配到了微应用a 。 而此时微应用a 已经卸载掉了，所以报`“wrapper element for 微应用a with instance 微应用a_123 is not existed”`

## 疑问
- `微应用a `和 `微应用b` 分别动态插入的高德地图的脚本对象，为什么会被qiankun 框架识别为同一个对象？
- 可不可以在`微应用a `卸载时,在`elementAttachContainerConfigMap` 中卸载掉`微应用 a` 相关的动态插入的`style` ，`link`, `script `?

## 环境
- **qiankun Version**: 2.4.0
- **Browser Version**: chrome 
- **框架** ： 主应用和微应用均为：vue 2.6.12
- **高德地图版本**： 1.4.15

**Comment by matteao03** [comment]
### 最小复现仓库
![https://github.com/matteao03/qiankun-share](https://github.com/matteao03/qiankun-share)

### 环境
- 主应用: `localhost:8080`
- app1 : `localhost:8081`
- app2: `localhost:8082`

### 复现步骤
- 在`首页` 点击链接`app1`, 加载 子应用 app1, 然后点击链接`返回首页`， 返回主应用
- 在`首页` 点击链接`app2`, 加载 子应用 app2, 然后点击链接`返回首页`， 返回主应用
- 再次在`首页` 点击链接`app1
- 点击链接`点击进入视频页`，F12 可以看到报错信息

### 排查结果
- 在复现步骤的第三步中，在 proxySandbox.js 中 proxy 的set 和 get 方法各设置一个断点，可以发现，沙箱 由 app1 变为了 app2 。
- 在复现步骤的第四步中， 因为video.js 需要动态插入样式，这时沙箱是app2, 所以报错。同理，高德地图也会动态插入并卸载脚本，同样会报相同的错误： “wrapper element for XXX with instance xxx_123 is not   existed”。

**Comment by gongshun** [comment]
初步排查发现：再次进入子应用 app1 时，里面的 elementUI 使用的沙箱是 app2 的。导致 app1 使用 elementUI 的组件时(组件读取了document)，触发了 setCurrentRunningSandboxProxy。此时设置了错误的 CurrentRunningSandboxProxy

![image](https://user-images.githubusercontent.com/29347231/120093153-eb0a6600-c14a-11eb-8191-3c68f4a1b0ac.png)

然后 video.js 创建 style 标签时，获取到了错误的 CurrentRunningSandboxProxy，导致 proxyAttachContainerConfigMap 数据读取错误。

![image](https://user-images.githubusercontent.com/29347231/120093304-e72b1380-c14b-11eb-87a7-f3c2eeefc925.png)

**快速验证**：注释 app1 中elementUI 的使用，后续就会正常，不会报错了。

![image](https://user-images.githubusercontent.com/29347231/120093317-ff9b2e00-c14b-11eb-8f2a-48e268cfdf5a.png)

临时解决方案：将这个 style 标签过滤掉，就不会报错 

![image](https://user-images.githubusercontent.com/29347231/120093375-6ae50000-c14c-11eb-890d-51686d1c8084.png)

**Comment by matteao03** [comment]
目前我们的项目中使用高德地图都会报同样的错误， 所以临时方案可以解决video.js 的问题，但无法兼顾到高德地图的使用。
#### 两个问题
- 目前我们在项目中是通过 `excludeAssetFilter`  参数避免 `qiankun` 框架劫持高德地图动态插入的 `js`，这种解决方案是否是官方推荐的方案？
-  针对沙箱设置错误的问题，官方是否会在近期有修复的计划安排？

**Comment by kuitos** [comment]
@gongshun 看下为啥沙箱会取错？document 对象被缓存了？

**Comment by gongshun** [comment]
> @gongshun 看下为啥沙箱会取错？document 对象被缓存了？

![image](https://user-images.githubusercontent.com/29347231/120911150-51e1cf00-c6b7-11eb-9719-db489d876eaf.png)

@kuitos app1 再次进入使用的 elementUI 的文件居然是 app2 的，两个子应用是分别安装的 npm 包，所以沙箱就错了。

但是先打开 app2，再进入 app1，使用的文件和沙箱都是正确的。

应该是子应用（app1和app2）复用主应用的 vue.js 依赖导致的，https://github.com/matteao03/qiankun-share/blob/45200e179776df4a47226d18ad6586e9a88f01cc/app1/vue.config.js#L27。如果不复用主应用的 vue.js 依赖，就会正常

**Comment by gongshun** [comment]
问题就在于复用 vue.js 依赖，并且 elementUI 的组件是全局注册的。大致步骤如下：

1. 初次加载 app1，执行所有 js，全局注册 elementUI 组件。
2. 切换到 app2，还会全局注册 elementUI 组件（此时组件的沙箱是app2），这次注册会覆盖上一次 app1 注册的。
3. 然后切换到 app1，这时只会执行 mount 函数了，不会再全局注册 elementUI 组件了，这时候app1使用 elementUI 的组件，沙箱就是 app2。

**Comment by matteao03** [comment]
#### 反馈
我测试了一下主应用和微应用不复用 `vue` 依赖的情况，确实没有上述错误了。
