### ISSUE TITLE
qiankun 2.4.1 version  cannot find where set the window.__POWERED_BY_QIANKUN__

### ISSUE THREAD

**Issue by koalaofpoint** [umijs/qiankun#1441]
hello, I npm qiankun 2.4.1,when I start run the application, visit sub application ，console.log window.__POWERED_BY_QIANKUN__, and window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ both of the result is undified, I visit someone blog's, window.__POWERED_BY_QIANKUN__ set by start() call,and window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ set by lifecycle, but I couldn't find qiankun's start() about window.__POWERED_BY_QIANKUN__ set value, so that the sub app __webpack_public_path__ =undified, so I misunderstanding something, or I try to decline the qiankun's version?

**Comment by jacintoface** [comment]
where do you read the property of window.INJECTED_PUBLIC_PATH_BY_QIANKUN? This property should be obtained in the lifecycle function, because only windows in the lifecycle function point to the Proxy object, or you can take a screenshot of your code
