### ISSUE TITLE
application 'vue-aaa' died in status LOADING_SOURCE_CODE

### ISSUE THREAD

**Issue by zhouguanglong** [umijs/qiankun#1443]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by zhouguanglong** [comment]
主应用切换子应用的时候报错

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1105#issuecomment-750330170
