### ISSUE TITLE
已react17为子应用，Node.js报错

### ISSUE THREAD

**Issue by chenbin1995** [umijs/qiankun#1444]
## What happens?

![image](https://user-images.githubusercontent.com/34931996/117777702-70e37180-b26f-11eb-8513-cedf390681ca.png)
以vue3为主应用，以angular11、vue2、react17为子应用。安照官网的配置，vue2和angular11没问题，react17访问成功一次后，主应用就崩溃。node.js试用10、12、14版本都不行，使用了nvm控制版本。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://gitee.com/ChenBin1995/qiankun-demo.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.4.1
- **Platform Version**: windows10
- **Browser Version**: 谷歌

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1299
