### ISSUE TITLE
vue子应用中组件mounted会加载两次

### ISSUE THREAD

**Issue by MaTonna** [umijs/qiankun#1446]
第一次进入vue子应用，mounted生命周期会执行两次，切换到非微应用，再切换回来，就不会有这个问题。
可能是加载了资源后就马上执行了mounted方法，然后在主应用中激活了activeRule，就会再执行一次mounted，不确定原因。
之前看别的issue是说react-router里的history.listen的回调触发两次，页面也会重复渲染，但是尝试监听了并没有触发两次。
求解！！

**Comment by gongshun** [comment]
官方 demo 能否复现？感觉是你自己写的业务逻辑导致，比如说 v-if，值 true - false- true 变化

**Comment by transtone** [comment]
> 第一次进入vue子应用，mounted生命周期会执行两次，切换到非微应用，再切换回来，就不会有这个问题。
> 可能是加载了资源后就马上执行了mounted方法，然后在主应用中激活了activeRule，就会再执行一次mounted，不确定原因。
> 之前看别的issue是说react-router里的history.listen的回调触发两次，页面也会重复渲染，但是尝试监听了并没有触发两次。
> 求解！！

不仅是两次，是多次。会持续执行。
