### ISSUE TITLE
 Set window.__SENTRY__ while sandbox destroyed or inactive in VOUCHER!

### ISSUE THREAD

**Issue by Homingciu** [umijs/qiankun#1448]
![image](https://user-images.githubusercontent.com/26406656/118264350-26b9f480-b4ea-11eb-8c74-fbf7789355af.png)

"qiankun": "^2.2.2",

我记得以前没这个问题，今天才出现

**Comment by gongshun** [comment]
卸载子应用时，需要清除掉子应用的sentry

**Comment by Homingciu** [comment]
> 卸载子应用时，需要清除掉子应用的sentry

![image](https://user-images.githubusercontent.com/26406656/118425950-debeeb80-b6fc-11eb-8b8e-6753e603ccc2.png)
那这个呢？

**Comment by Homingciu** [comment]
> > 卸载子应用时，需要清除掉子应用的sentry
> 
> ![image](https://user-images.githubusercontent.com/26406656/118425950-debeeb80-b6fc-11eb-8b8e-6753e603ccc2.png)
> 那这个呢？

我看你们不是有修复这个问题吗？

**Comment by Homingciu** [comment]
我看之前的issue说是antd设置的window.event，那是不是一定会有这个报错？

**Comment by gongshun** [comment]
> 我看之前的issue说是antd设置的window.event，那是不是一定会有这个报错？我可以怎么避免

只要没有一直报，这个警告可以忽略吧？

**Comment by Homingciu** [comment]
报错好几百个...虽然不会卡死，但还有有点影响，会影响js执行速度

**Comment by Homingciu** [comment]
@gongshun 
![Uploading image.png…]()

**Comment by gongshun** [comment]
需要一个复现demo

**Comment by seymoe** [comment]
同遇到此问题，Set window.__SENTRY__ while sandbox destroyed or inactive 一直循环导致页面卡死。

子系统里因为sentry在其他团队vue组件中引入，所以没有办法将sentry提到主应用中，并且sentry没有提供uninstall之类的方法，只能刷新页面来卸载，所以暂时的解决办法是：
当从此子系统返回主系统时，不采用vueRouter跳转方式，而是直接 location.href 来进行跳转，触发页面刷新，就没有这个问题了

**Comment by ccysmd** [comment]
set window.event 是antd吗，你解决了没

**Comment by Homingciu** [comment]
> set window.event 是antd吗，你解决了没

1. 是antd
2. 没有解决，只在开发环境报错（从代码也能看出）。
3. 在node_modules里面找到源码，直接注释到报错

**Comment by ChengranYan** [comment]
我也报了，切子应用报了1000多个

**Comment by Jogiter** [comment]
尝试降级到 qiankun@2.0.11 版本后，发现不再打印警告。

**Comment by ybbjegj** [comment]
这个问题有解决办法吗？

**Comment by ybbjegj** [comment]
只能注释掉了吗？

**Comment by Jogiter** [comment]
报错的原因是因为 sentry 默认设置了 `autoSessionTracking: true`，在 sentry 初始化后，会启动定时器定时发送 session 请求。
当切换子应用时，定时器并没有被清除，导致打印大量警告。

**修复办法**：

```ts
Sentry.init({
  // fix Error:  TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
  transport: Sentry.Transports.XHRTransport,
 // remove warning timer
  autoSessionTracking: false,
})
```

**Comment by Kellercai** [comment]
> 

你好，已测试了，此设置并未生效，降级到 qiankun@2.0.11 版本后才能生效

**Comment by ideagay** [comment]
> 
请问怎么清除sentry

**Comment by dingxu369** [comment]
> 同样遇到这个问题，设置窗口。**SENTRY** while sandbox destroyed or inactive 一直循环导向致页面卡死。
> 
> sentry sentry sentry vue组件组件组件，sentry sentry sentry sentry sentry sentry sentry sentry sentry lunstall uninstall unstall之类 方法子系统返回主系统时，不采用vueRouter跳转方式，而且是直接访问location.href 来进行跳转，触发页面刷新，就没有这个问题了

你们是在子系统中单独引入的sentry吗

**Comment by cx91** [comment]
有没有大佬解决了这个问题了呢，我用的umi4没法降qiankun的版本

**Comment by NicolasLaverde** [comment]
Some solution for this? In English Please!

**Comment by beilunyang** [comment]
我也遇到了同样的问题，有人解决了吗
