### ISSUE TITLE
[Bug]子应用挂载到app.vue下的组件的时候，在子应用路由界面刷新，加载不到子应用content

### ISSUE THREAD

**Issue by wusp1994** [umijs/qiankun#145]
## What happens?
之前demo子应用直接挂载到app.vue(顶级)刷新无问题，子应用挂载到自定义的视图组件的时候，在子应用路由界面刷新，加载不到子应用appContent

以admin-wu为主应用，实现在app.vue下的视图组件中以v-html加载子应用。发现render({ appContent, loading }) 函数一共执行了四次，第一次的时候 appContent 为undefined。代码如下
![image](https://user-images.githubusercontent.com/26253981/68650312-a5ce1580-055f-11ea-93d1-8d5e775ef102.png)
造成了，地址为子应用的路径时候，刷新页面子应用appContent 加载不到。

## 最小可复现仓库
https://github.com/wusp1994/qiankunTestByWu.git

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/26253981/68650577-4fada200-0560-11ea-9f86-e8535322a134.png)
以上是从其他页面点过去，可以实现（这里是因为我把主应用的子组件中写了一个 id="app" 的标签）
![image](https://user-images.githubusercontent.com/26253981/68650488-183ef580-0560-11ea-937b-98bd57315c80.png)
以上是在子应用页面刷新加载不到
![image](https://user-images.githubusercontent.com/26253981/68657639-14669f80-056f-11ea-8119-bbf1b3156ecc.png)
应该是子应用创建vue对象的时候，主应用的子组件还没加载到appContent造成的。找不到挂载的id=“app”的dom

## 相关环境信息

- **浏览器版本**：Google Chrome | 76.0.3809.132 (正式版本) （64 位）
- **操作系统**：window10
- **Node 版本**：12.13.0

**Comment by kuitos** [comment]
appContent 可能为空，你的

**Comment by wusp1994** [comment]
![image](https://user-images.githubusercontent.com/26253981/68746346-5fe28180-0633-11ea-8538-3a083fb1f4a0.png)

qiankunTestByWu\admin-wu\src\views\system\testChild\index.vue 的28行，我是可以打印出来的
![image](https://user-images.githubusercontent.com/26253981/68746449-91f3e380-0633-11ea-83f3-9ce1faf1cc00.png)
但是子应用依然会报找不到挂载的dom Cannot find element: #app

**Comment by kuitos** [comment]
因为你自己的路由把子应用的 dom 干掉了https://github.com/wusp1994/qiankunTestByWu/blob/master/admin-wu/src/router/childApps.js#L6

**Comment by wusp1994** [comment]
我不配路由怎么触发app.vue 下的其他视图组件呢

**Comment by wusp1994** [comment]
![image](https://user-images.githubusercontent.com/26253981/68750420-cc14b380-063a-11ea-986d-544a6c5e83f0.png)
是不是 要使用动态路由的功能

**Comment by kuitos** [comment]
1. 出现 undefined 的原因 https://github.com/wusp1994/qiankunTestByWu/blob/master/admin-wu/src/main.js#L88
2. 既然你的子应用的容器是在主应用里动态生成的，你需要确保子应用在 mount 前容器已经 ready

**Comment by RoxanneCIA** [comment]
@kuitos 你好，我这边也有类似的问题，我的主应用的路由是用来挂载子应用时的根节点，但因为路由是懒加载的，然后切换路由子应用就会找不到挂载的DOM节点 Target container is not a DOM element.
