### ISSUE TITLE
关于一个页面加载多个子应用，子应用组件式加载现在支持了么？有对应的文档么?

### ISSUE THREAD

**Issue by loioce** [umijs/qiankun#1451]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
> 一个页面加载多个子应用
办法1：使用 registerMicroApps ，为两个子应用设置相同的 activeRule
办法2：使用两次 loadMicroApp

https://qiankun.umijs.org/zh/cookbook#%E5%90%8C%E6%97%B6%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA%E5%BE%AE%E5%BA%94%E7%94%A8%E6%97%B6

**Comment by loioce** [comment]
感谢回复，我这边还有两个疑问，麻烦解答一下，非常感谢
办法1：使用registerMicroApps,  两个子应用设置相同的activeRule,那么是不是访问子应用的具体页面，还需要两个子应用设置一个跟主应用访问页面相同的页面路由，才能去触发规则，进行加载？
办法2：qiankun加载子应用使用的方式是一个单线程的方式，类似于同步加载，使用两次loadMicroApp，会导致加载很慢么？还有个问题是我看loadMicroApp 仅仅是做到了把子应用挂载进来，那么挂载的同时，我需要直接渲染子应用下方的某个路由，还需要怎么处理呢？

**Comment by loioce** [comment]
@@@@感谢回复，我这边还有两个疑问，麻烦解答一下，非常感谢
办法1：使用registerMicroApps,  两个子应用设置相同的activeRule,那么是不是访问子应用的具体页面，还需要两个子应用设置一个跟主应用访问页面相同的页面路由，才能去触发规则，进行加载？
办法2：qiankun加载子应用使用的方式是一个单线程的方式，类似于同步加载，使用两次loadMicroApp，会导致加载很慢么？还有个问题是我看loadMicroApp 仅仅是做到了把子应用挂载进来，那么挂载的同时，我需要直接渲染子应用下方的某个路由，还需要怎么处理呢？

**Comment by gongshun** [comment]
> 我需要直接渲染子应用下方的某个路由

主应用通知子应用，子应用使用自己的路由实例，跳转到对应的路由页面

**Comment by loioce** [comment]
我的意思可能没表达清楚，比如我现在再主应用A里面，加载有一个子应用 B（路由为/b）, 那我要再/b这个页面里面某个区域显示出c子应用和D子应用的某个页面，loadMicroApp的方式是将子应用加载了，加载的时候默认展示的是C | D子应用的入口，我想在加载的时候，直接展示到c | d 具体某个路由页面，需要怎么处理呢？

**Comment by gongshun** [comment]
> 我的意思可能没表达清楚，比如我现在再主应用A里面，加载有一个子应用 B（路由为/b）, 那我要再/b这个页面里面某个区域显示出c子应用和D子应用的某个页面，loadMicroApp的方式是将子应用加载了，加载的时候默认展示的是C | D子应用的入口，我想在加载的时候，直接展示到c | d 具体某个路由页面，需要怎么处理呢？

https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

**Comment by loioce** [comment]
非常感谢，明白了，还是需要子应用单独处理
