### ISSUE TITLE
微应用使用ag-grid插件，导出功能无法正常使用

### ISSUE THREAD

**Issue by spaceBin** [umijs/qiankun#1454]
## What happens?

ag-grid导出事件报错：Uncaught TypeError: Failed to construct 'MouseEvent': member view is not of type Window.

## Mini Showcase Repository(REQUIRED)

https://github.com/spaceBin/qiankun-template.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

1、克隆项目；
2、运行portal项目：
（1）cd portal
（2）npm install
（3）npm run serve
3、运行app-first项目：
（1）cd app-first
（2）npm install
（3）npm run serve
4、浏览器访问：localhost:7013，访问first应用下的A页面，右键表格导出excel，浏览器控制台报错，导出失败。

**Expected behavior** 1. 2.

期望右键表格导出能正常导出当前表格数据的excel。

## Context

- **qiankun Version**:  2.4.0
- **Platform Version**:
- **Browser Version**:   90.0.4430.212（正式版本） （64 位）

**Comment by gongshun** [comment]
类似问题 https://github.com/umijs/qiankun/issues/570

**Comment by spaceBin** [comment]
好像没看到解决方案




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 微应用使用ag-grid插件，导出功能无法正常使用 (#1454)





 
类似问题 #570

**Comment by gongshun** [comment]
> 好像没看到解决方案

https://github.com/umijs/qiankun/issues/1354#issuecomment-815660117

**Comment by spaceBin** [comment]
收到，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 微应用使用ag-grid插件，导出功能无法正常使用 (#1454)





  
好像没看到解决方案
  
#1354 (comment)

**Comment by tzstone** [comment]
@kuitos 能否在start()的时候配置SnapshotSandbox可选? 而不是默认有window.Proxy就走ProxySandbox, 没有才走SnapshotSandbox. 这样可以暂时规避ag-grid和echarts下载的问题.

**Comment by kuitos** [comment]
> @kuitos 能否在start()的时候配置SnapshotSandbox可选? 而不是默认有window.Proxy就走ProxySandbox, 没有才走SnapshotSandbox. 这样可以暂时规避ag-grid和echarts下载的问题.

sandbox: { loose: true }，副作用就是不能同时加载多个微应用

**Comment by tzstone** [comment]
> > @kuitos 能否在start()的时候配置SnapshotSandbox可选? 而不是默认有window.Proxy就走ProxySandbox, 没有才走SnapshotSandbox. 这样可以暂时规避ag-grid和echarts下载的问题.
> 
> sandbox: { loose: true }，副作用就是不能同时加载多个微应用

好像不是..  { loose: true } 会使用LegacySandbox, LegacySandbox也是基于proxy的, 其实还是会面临和ProxySandbox一样的问题. 我刚试了, 问题还是存在的. 只有SnapshotSandbox还是用的原来的window, 就不会有这种问题.

**Comment by tzstone** [comment]
@kuitos  另外请教个问题, 我用vue2做主应用, angular11做子应用(cli创建的), 都是history模式, 子应用有两个路由a, b. 当子应用嵌在主应用中访问时, 在子应用中使用ag自己的routerlink在a, b之间切换时显示是正常的(说明配置啥的应该没问题), 而在主应用切换路由访问a, b时, 不会触发到a, b对应组件的ngOnInit, 请问知道可能是什么问题吗?

**Comment by kuitos** [comment]
snapshot 是基于 IE 准备的，目前不支持开放。
可能目前你这个场景只能关闭沙箱了？

**Comment by tzstone** [comment]
> snapshot 是基于 IE 准备的，目前不支持开放。
> 可能目前你这个场景只能关闭沙箱了？

恩, 这是最后的方案了.

**Comment by tzstone** [comment]
> @kuitos 另外请教个问题, 我用vue2做主应用, angular11做子应用(cli创建的), 都是history模式, 子应用有两个路由a, b. 当子应用嵌在主应用中访问时, 在子应用中使用ag自己的routerlink在a, b之间切换时显示是正常的(说明配置啥的应该没问题), 而在主应用切换路由访问a, b时, 不会触发到a, b对应组件的ngOnInit, 请问知道可能是什么问题吗?

解决了. 子应用用single-spa helpers(https://single-spa.js.org/docs/ecosystem-angular/#introduction-1)去暴露生命周期, 就可以监听到主应用发起的pushState并触发相应的路由组件重新渲染.
