### ISSUE TITLE
主、子应用都使用dva-cli 建的项目，加载完子应用后，主应用崩溃了！！！

### ISSUE THREAD

**Issue by guyuezhai** [umijs/qiankun#1456]
## What happens?
**使用  [ `dvajs` ](https://dvajs.com/guide/getting-started.html) 创建主应用、子应用**

主、子应用都使用dva-cli 建的项目，加载完子应用后，主应用崩溃了！！！
子应用页面在主应用中显示出来后，主应用挂掉了。

## 报错信息如下
![image](https://user-images.githubusercontent.com/24433701/118792098-e8497e80-b8c9-11eb-9d73-283666d8f734.png)

```js
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 1.
```

## Context

- **qiankun Version**: ^2.4.1
- **Platform Version**: windows 10
- **Browser Version**: 版本 90.0.4430.212（正式版本） （64 位）

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1428 重复，热更新的bug，关闭热更新 or 指定热更新的端口
