### ISSUE TITLE
vue基座和子应用，在主应用中嵌套路由加载子应用后，切换tab加载失败，刷新浏览器，加载正常

### ISSUE THREAD

**Issue by Jiyr0119** [umijs/qiankun#1457]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

基于 #1169 进行测试之后，项目嵌套路由，切换之后浏览器刷新才能加载子应用。

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

https://github.com/Jiyr0119/qiankun-main
https://github.com/Jiyr0119/qiankun-sub

## 复现步骤，错误日志以及相关配置
主应用如下配置
![image](https://user-images.githubusercontent.com/28727613/118910697-846d9700-b957-11eb-8b30-8c354cf7c3a8.png)
![image](https://user-images.githubusercontent.com/28727613/118910724-951e0d00-b957-11eb-900b-5cbb0a9b213b.png)
![image](https://user-images.githubusercontent.com/28727613/118911648-204bd280-b959-11eb-840c-61ff91f659a5.png)
两种配置都有相同的问题，1169里面的也没有这种使用方案，但是我现在需求就是要这样可能每一个item都是一个子应用，但是我还要切换在主应用里面切换子应用的路由。现在就很懵，但是官方demo里又没有问题
![image](https://user-images.githubusercontent.com/28727613/118911966-a0723800-b959-11eb-9539-412cb8226e13.png)
希望大佬解惑，拜托了 甲方指定要微前端，我要负责落地😣

## 相关环境信息

- **qiankun 版本**
-     "qiankun": "^2.4.1",
- **浏览器版本**：
- 版本 90.0.4430.212（正式版本） (x86_64)
- **操作系统**：
- mac

**Comment by Jiyr0119** [comment]
![image](https://user-images.githubusercontent.com/28727613/118914597-1e384280-b95e-11eb-91ae-380dc86ce13f.png)
还有一点为什么这样配置之后浏览器只有iframe 的路径 http://localhost:9529/iframeBox 这个是qiankun做的处理么

**Comment by AyaneruQAQ** [comment]
请问在主应用里切换子应用内的路由解决了吗

**Comment by gongshun** [comment]
![效果图](https://user-images.githubusercontent.com/29347231/120131355-db4a5a80-c1fa-11eb-8abc-6dc84a09b3ae.gif)

https://github.com/gongshun/qiankun-vue-element-admin

**Comment by Jiyr0119** [comment]
> ![效果图](https://user-images.githubusercontent.com/29347231/120131355-db4a5a80-c1fa-11eb-8abc-6dc84a09b3ae.gif)
> 
> https://github.com/gongshun/qiankun-vue-element-admin

感谢。但是我的需求是example那样展开之后来回切换出现的bug

**Comment by gongshun** [comment]
> 感谢。但是我的需求是example那样展开之后来回切换出现的bug

example 也就是加一个嵌套的菜单而已，没有任何问题

![1](https://user-images.githubusercontent.com/29347231/120448646-5871fd00-c3be-11eb-9517-60315eb51b40.gif)

**Comment by Jiyr0119** [comment]
> > 感谢。但是我的需求是example那样展开之后来回切换出现的bug
> 
> example 也就是加一个嵌套的菜单而已，没有任何问题
> 
> ![1](https://user-images.githubusercontent.com/29347231/120448646-5871fd00-c3be-11eb-9517-60315eb51b40.gif)

可以提交到那个仓库嘛 我当时各种试就是没解决 都换成loadMicroApp了

**Comment by Jiyr0119** [comment]
> 请问在主应用里切换子应用内的路由解决了吗

来关注大佬的回答～

**Comment by Jiyr0119** [comment]
> > 可以提交到那个仓库嘛 我当时各种试就是没解决 都换成loadMicroApp了
> 
> 代码更新了

感谢解惑，我知道怎么做了。 不管是这样写 还是用loadMicroApp 都可以满足，但是我还是卡在这 为什么这种路由形式不可以https://github.com/Jiyr0119/qiankun-vue-element-admin

**Comment by gongshun** [comment]
> 感谢解惑，我知道怎么做了。 不管是这样写 还是用loadMicroApp 都可以满足，但是我还是卡在这 为什么这种路由形式不可以https://github.com/Jiyr0119/qiankun-vue-element-admin

不需要把子应用的路由拿到主应用去注册一遍（子应用也注册了一遍路由，会冲突的），不要为了生成菜单而注册路由，菜单数据可以另外写

**Comment by Jiyr0119** [comment]
> > 感谢解惑，我知道怎么做了。 不管是这样写 还是用loadMicroApp 都可以满足，但是我还是卡在这 为什么这种路由形式不可以https://github.com/Jiyr0119/qiankun-vue-element-admin
> 
> 不需要把子应用的路由拿到主应用去注册一遍（子应用也注册了一遍路由，会冲突的），不要为了生成菜单而注册路由，菜单数据可以另外写

感谢 感谢 恍然大悟～

**Comment by maYunLaoXi** [comment]
我也有同样的问题，主应用并没有注册路由。场景也是会有个别子应用其实是同一个vue项目的不同路由在主应用菜单点击加载。来回切换就加载不出来（也没有报错），而我的场景会比题主更加复杂一些，有不同版本的vue子项目和纯html
