### ISSUE TITLE
子应用存在异步下载的js

### ISSUE THREAD

**Issue by whitekyo** [umijs/qiankun#1464]
我调试了一下，发现qiankun默认会将一个子应用绑定一个异步js，并且做js的沙箱处理（这里不包括写在页面上的script标签）。

现在我的子应中存在大量异步，异步的js由于没有包裹沙箱，导致异步的js 拿不到绑定js里面的内容。

现在我的解决方案有两个：
1.在主应用中进行注入
2.将子应用的j所有s打包成一个js

方案1：老实说是无奈的做法，方案2改造成本有点大。所以想问下qiankun本身对这种场景是否有标准解决方案

**Comment by kuitos** [comment]
> 发现qiankun默认会将一个子应用绑定一个异步js，并且做js的沙箱处理

结论不成立，每个异步的都会处理

**Comment by whitekyo** [comment]
> > 发现qiankun默认会将一个子应用绑定一个异步js，并且做js的沙箱处理
> 
> 结论不成立，每个异步的都会处理

我看了下源码，确实都被qiankun拦截了，但是没有注入qiankun定义沙箱
`if (!isHijackingTag(element.tagName) || !isInvokedByMicroApp(element)) {
      return rawDOMAppendOrInsertBefore.call(this, element, refChild);
    }`
!isInvokedByMicroApp(element)只要是异步js，这里都是true

在createElement方法里
`if (Document.prototype.createElement === rawDocumentCreateElement) {
    Document.prototype.createElement = function createElement(tagName, options) {
      var element = rawDocumentCreateElement.call(this, tagName, options);

      if (isHijackingTag(tagName)) {
        var currentRunningSandboxProxy = getCurrentRunningSandboxProxy();

        if (currentRunningSandboxProxy) {
          var proxyContainerConfig = proxyAttachContainerConfigMap.get(currentRunningSandboxProxy);

          if (proxyContainerConfig) {
            elementAttachContainerConfigMap.set(element, proxyContainerConfig);
          }
        }
      }

      return element;
    };
  }`
这里的getCurrentRunningSandboxProxy()永远拿到的都是undefined。导致上面判断都是空。

我的问题是，我子应用异步加载的js，如果才能被qiankun加上js沙盒呢？

**Comment by kuitos** [comment]
提供可复现仓库，不然谁都不知道什么原因😑

**Comment by whitekyo** [comment]
> 提供可复现仓库，不然谁都不知道什么原因😑

好的，我做个demo晚些时候提供，另外我问下，你们有qiankun对接seajs项目的例子吗？可以发我一下研究研究

**Comment by 28610966** [comment]
同问题, 子应用里的异步js 在被加载时变成主应用的域名了, 导致拿不到内容, 为什么会有这么明显的问题呢?

**Comment by gongshun** [comment]
> 同问题, 子应用里的异步js 在被加载时变成主应用的域名了, 导致拿不到内容, 为什么会有这么明显的问题呢?

因为你加载时使用的是相对路径啊

**Comment by guopz** [comment]
相对路径是指？

**Comment by guopz** [comment]
@gongshun 相对路径是指？

**Comment by gongshun** [comment]
> @gongshun 相对路径是指？

子应用中的标签是 `<script src="./a.js"></script>` 或者  `<script src="/a.js"></script>`

**Comment by whitekyo** [comment]
问题解决，我把原来的打包方式修改了，统一打成一个js，避开异步加载js的场景就没有问题了

**Comment by ashuihui** [comment]
同样的问题
