### ISSUE TITLE
线上环境报错：You need to export lifecycle functions in xxx entry

### ISSUE THREAD

**Issue by ringgoyao** [umijs/qiankun#1476]
## What happens?

Uncaught Error: application 'museum' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in museum entry

## Mini Showcase Repository(REQUIRED)
线上地址
http://116.62.212.251:8071/
描述：本地开发环境是没有问题的，所以能基本排除了一些常见的共性bug，比如webpack名称之类的，生产环境是采用的docker部署，不知是否相关，简单的逻辑是：登录之后获取到用户的权限加载相关的子应用，测试了prefetch的几个参数都是一样的问题，不知道从何下手了
    
    
## How To Reproduce
账户:test   密码123456

登录后，点击 左侧菜单 “征集信息”，此时控制台报错
             再切换点击“入藏信息”，则能正常加载

## Context

- **qiankun Version**: 2.4.0
- **Platform Version**:
- **Browser Version**:

**Comment by canyuegongzi** [comment]
![image](https://user-images.githubusercontent.com/32031360/119933549-e44aea00-bfb6-11eb-9697-3ccccd2c8685.png)
资源跨域吧这是

http://116.62.212.251:8072/（子应用）   和主应用（http://116.62.212.251:8071）的端口不一样会跨域问题，可以在子应用的nginx配个请求头部就可以解决

**Comment by canyuegongzi** [comment]
> @canyuegongzi
> 你好，我8072有配置Access-Control-Allow-Origin * ；否则控制台会报Access to fetch at 'http://116.62.212.251:8072/' from origin 'http://116.62.212.251:8071' has been blocked by CORS policy: No 'Access-Control-Allow-Origin，问题应该判断不是因为跨域吧？不然为什么切换菜单能加载成功呢？

刚看了下线上的案例，已经正常了，之前是什么原因导致的？

**Comment by ringgoyao** [comment]
@canyuegongzi  
第一次点击菜单的时候，还是会出现这个问题，我感觉是相关的文件还未下载吧？第二次切换菜单就不报错了。我先弄一个最小的demo去线上排查排查

**Comment by ringgoyao** [comment]
@kuitos   @canyuegongzi
你好，我把主应用代码和子应用代码放到这个地址了，[test](https://github.com/ringgoyao/qiankun)
代码是基于Vue的，基本逻辑是登录后，在主应用的某个路由页面加载子应用，本地开发没有问题，部署到本地nginx时，能复现我提的bug，即:第一次点击子应用的路由时无法加载，切换后一切正常,控制台报You need to export lifecycle functions in xxx entry
我把我的nginx也贴了一下，自己排查好多天了，如果有空还请帮忙看下。

**Comment by gongshun** [comment]
> @kuitos @canyuegongzi
> 你好，我把主应用代码和子应用代码放到这个地址了，[test](https://github.com/ringgoyao/qiankun)
> 代码是基于Vue的，基本逻辑是登录后，在主应用的某个路由页面加载子应用，本地开发没有问题，部署到本地nginx时，能复现我提的bug，即:第一次点击子应用的路由时无法加载，切换后一切正常,控制台报You need to export lifecycle functions in xxx entry
> 我把我的nginx也贴了一下，自己排查好多天了，如果有空还请帮忙看下。

看文档就能解决 https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

![image](https://user-images.githubusercontent.com/29347231/120131909-f073b900-c1fb-11eb-94a6-2b738542cece.png)

https://github.com/ringgoyao/qiankun/blob/f450715c8d150c50910421c27b3c3f4aebf66ebf/mirco-app-sub-dropbox/vue.config.js#L142

如果还不行，那就

![image](https://user-images.githubusercontent.com/29347231/120131950-071a1000-c1fc-11eb-8a5d-03e53c46cf0e.png)

https://github.com/ringgoyao/qiankun/blob/f450715c8d150c50910421c27b3c3f4aebf66ebf/mirco-app-sub-dropbox/vue.config.js#L139

**Comment by ringgoyao** [comment]
@gongshun  经测试：移除webpack中output.globalObject='this',  之前有看到文档中这句话，也测试过，估计因为各种组合原因没有生效，导致完美避开正确解决方案。万分感谢

**Comment by ZhangGaozhen** [comment]
我也遇到这个问题，第一个应用可以正常挂载，第二个应用不行

**Comment by yihuan** [comment]
我遇到的情况是在 env.production 配置的子应用的URL值少一个引号。类似这种：`VUE_APP_SUB_XXX = 'https://xxx.com/`，完美的避开了官网上的各种可能。

**Comment by gongshun** [comment]
> 我遇到的情况是在 env.production 配置的子应用的URL值少一个引号。类似这种：`VUE_APP_SUB_XXX = 'https://xxx.com/`，完美的避开了官网上的各种可能。

你这种情况，刚好对应场景6

![image](https://user-images.githubusercontent.com/29347231/141400853-c82dd7ab-ff7c-4449-a370-bf9cea1a28cc.png)
