### ISSUE TITLE
umi qiankun 子应用2.6.11

### ISSUE THREAD

**Issue by Mluocheng** [umijs/qiankun#1478]
umi qiankun 主应用， 嵌入vue2.6.11 子应用报错。
![image](https://user-images.githubusercontent.com/31057183/120137702-76493180-c207-11eb-80dc-383a61fac831.png)

- **qiankun Version*2.11*:

**Comment by gongshun** [comment]
报这个错误就是因为请求了 js，返回了 html，那么为什么会这样呢，大概率是你的 js 路径不正确，文件404，history 路由会将 404 返回 index.html。懒加载的js路径不正确，你没有动态修改 publicPath 。https://qiankun.umijs.org/zh/guide/tutorial#vue-%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by Mluocheng** [comment]
@gongshun 照着文档给了配置。还是不行。
![image](https://user-images.githubusercontent.com/31057183/120198373-96eba880-c254-11eb-8220-3f1eb402583b.png)
只有注册路由这部分是不太一样， 以及我想是不是因为有路由守卫影响。 
![image](https://user-images.githubusercontent.com/31057183/120198505-bedb0c00-c254-11eb-8d95-7f69c869f2ef.png)


我重新起了一个项目，把现有项目页面挪过去能够渲染出来。

**Comment by gongshun** [comment]
> @gongshun 照着文档给了配置。还是不行。
> ![image](https://user-images.githubusercontent.com/31057183/120198373-96eba880-c254-11eb-8220-3f1eb402583b.png)
> 只有注册路由这部分是不太一样， 以及我想是不是因为有路由守卫影响。
> ![image](https://user-images.githubusercontent.com/31057183/120198505-bedb0c00-c254-11eb-8d95-7f69c869f2ef.png)
> 
> 我重新起了一个项目，把现有项目页面挪过去能够渲染出来。

publi-path.js 这个文件需要在入口文件的最顶部引入，你是不是引入位置不正确？

**Comment by Mluocheng** [comment]
@gongshun  是没错的
![image](https://user-images.githubusercontent.com/31057183/120255957-afdd7380-c2bf-11eb-92b7-d8a4b4ef9b03.png)

**Comment by gongshun** [comment]
针对你的这个报错，我只能说，要么就是代理有问题（请求 js 返回了 html），要么是 `publi-path.js 这个文件没有在入口文件的最顶部引入`，如果都不是，需要你提供复现 demo
