### ISSUE TITLE
vue 子应用间跳转

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1479]
子应用之间跳转，通过props参数传了主应用到Route实例，在子应用使用，如下：
![image](https://user-images.githubusercontent.com/24559368/120279080-9bfa3780-c2e8-11eb-843b-8d6b2dfc6e07.png)

报错
![image](https://user-images.githubusercontent.com/24559368/120278989-8258f000-c2e8-11eb-88c1-f55b04f01612.png)

**Comment by gongshun** [comment]
你子应用的 `unmount` 函数写的有问题

**Comment by JuSanZhi** [comment]
> 你子应用的 `unmount` 函数写的有问题

![image](https://user-images.githubusercontent.com/24559368/120284538-eda5c080-c2ee-11eb-9f23-7bd8e5a14283.png)

**Comment by gongshun** [comment]
> > 你子应用的 `unmount` 函数写的有问题
> 
> ![image](https://user-images.githubusercontent.com/24559368/120284538-eda5c080-c2ee-11eb-9f23-7bd8e5a14283.png)

你再去看看 demo 和教程咋写吧，第一次离开子应用，销毁了 vue 实例，再次进入子应用，没有创建 vue 实例，这时候销毁自然会报错。
