### ISSUE TITLE
bug:🐛I added two vuecli projects, one of which won't load

### ISSUE THREAD

**Issue by xkloveme** [umijs/qiankun#148]
## What happens?
![image](https://user-images.githubusercontent.com/29595042/68745935-82c06600-0632-11ea-8d2d-e41bf663f10b.png)
I added two vuecli projects, one of which won't load and run  window.history.pushState({}, title, href); 
 There seems to be something wrong
[https://github.com/xkloveme/microfrontends](https://github.com/xkloveme/microfrontends)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**:
- **Browser Version**:
- **Node Version**:

**Comment by kuitos** [comment]
pls provide the reproduce step

**Comment by kuitos** [comment]
参考最新 demo
