### ISSUE TITLE
[QUESTION]子应用间共享同一个组件，怎么实现样式隔离

### ISSUE THREAD

**Issue by zjhnlsj** [umijs/qiankun#1485]
## What happens?
两个vue2.0的子应用，存在共享同一个组件时，怎么做到样式隔离的？
这个组件只会加载一次，样式appendChild到第一个子应用，切换到第二个子应用的时候，公共组件的样式不再加载了。

**Comment by gongshun** [comment]
你别卸载第一个子应用就行了，所以你应该用手动加载第一个子应用，自己控制加载卸载

**Comment by yjw2420521** [comment]
我也遇到这个问题, 主应用提供共享组件，切换第一个子应用共享组件样式加载，第二个子应用相同组件的样式就不加载了
