### ISSUE TITLE
主应用跟子应用都是vue， 子应用间dialog 这些组件怎么隔离

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1488]
现在遇到一个问题，a 子应用使用的vue-photo-preview 插件，dialog 的东西都会放在 body。然后在加载b子应用的时候，这个插件还会存在，所以每次从a 子应用调整b子应用的时候，都会加载一下这个组件。请问应该如何更好的阻断

**Comment by gongshun** [comment]
后续会支持的 https://github.com/umijs/qiankun/issues/1207
