### ISSUE TITLE
[Question] the logic about sandbox & execScripts is broken?

### ISSUE THREAD

**Issue by lsdsjy** [umijs/qiankun#1491]
https://github.com/umijs/qiankun/blob/master/src/loader.ts#L333 uses `!useLooseSandbox` as `strictGlobal` to call `execScripts`, but if `sandbox` is `false`, `strictGlobal` becomes `true`(because `useLooseSandbox` is false), which I think is wrong.

**Comment by kuitos** [comment]
Seems it not right, feel free to make a fixing pr~

**Comment by lsdsjy** [comment]
@kuitos https://github.com/umijs/qiankun/pull/1492
