### ISSUE TITLE
[Feature Request] qiankun能否支持套中套

### ISSUE THREAD

**Issue by Jason-YCX** [umijs/qiankun#1494]
## Background

之前用qiankun完成一个主应用A和子应用B的结合，现在要将这个主应用A再作为子应用嵌套进另一个系统C，但实现下来发现，原来的主应用A的页面倒是能加载出来，原来的子应用B就不能加载

## Proposal

这种情况是因为qiankun现在不支持，还是有什么需要配置的

**Comment by gongshun** [comment]
duplicated with https://github.com/umijs/qiankun/issues/960
