### ISSUE TITLE
主微应用都是vue。  部分手机无法子应用

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1496]
![image](https://user-images.githubusercontent.com/24559368/121142652-cdd24780-c86e-11eb-9d97-1797049e7803.png)
![image](https://user-images.githubusercontent.com/24559368/121142686-d88cdc80-c86e-11eb-9783-0c87b974691e.png)
求助！！！！

**Comment by JuSanZhi** [comment]
场景：企业微信的小程序webview，这个webview的链接就是一个qiankun 项目。在微信内是正常，企业微信直接打开也正常。但是企业微信的小程序内就报这样的错误

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1509 重复
