### ISSUE TITLE
如何在quasar框架中使用qiankun

### ISSUE THREAD

**Issue by KinoshitaHanson** [umijs/qiankun#1499]
quasar框架隐藏了入口文件main.js，没有办法自己实例化vue，导致无法实现qiankun的子应用，不知道有没有已知的解决方案

附上quasar相关文档：http://www.quasarchs.com/quasar-cli/boot-files/#%E9%80%82%E5%BD%93%E4%BD%BF%E7%94%A8%E5%90%AF%E5%8A%A8%E6%96%87%E4%BB%B6%E7%9A%84%E7%A4%BA%E4%BE%8B

**Comment by gongshun** [comment]
搞两个入口文件？qiankun 模式下自己实例化，普通模式则按照它这个来

**Comment by KinoshitaHanson** [comment]
> 搞两个入口文件？qiankun 模式下自己实例化，普通模式则按照它这个来

没办法自己实例化， 目前我采取的方法是没有使用官方提供的cli，改为使用vue-cli加quasar插件的形式

**Comment by gongshun** [comment]
可以使用手动加载，切换应用时不卸载，只做样式上的隐藏，这样再次加载就没问题了
