### ISSUE TITLE
关于公共包提取有什么好的方式吗？

### ISSUE THREAD

**Issue by Cyrilszq** [umijs/qiankun#15]
公共包提取有什么好的方案建议，使得各个子应用的依赖都是同一版本

**Comment by kuitos** [comment]
最简单的就是子应用 external 公共依赖，主应用统一加载。
后面 qiankun 或者 umi-plugin-qiankun 会提供相应的公共依赖提取的方案支持

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#how-to-extract-the-common-library

**Comment by longmajuxie** [comment]
> see https://github.com/umijs/qiankun/wiki/FAQ#how-to-extract-the-common-library

> 好像没有权限查看wiki。[](url)

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E6%8F%90%E5%8F%96%E5%87%BA%E5%85%AC%E5%85%B1%E7%9A%84%E4%BE%9D%E8%B5%96%E5%BA%93%EF%BC%9F

**Comment by longmajuxie** [comment]
> https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E6%8F%90%E5%8F%96%E5%87%BA%E5%85%AC%E5%85%B1%E7%9A%84%E4%BE%9D%E8%B5%96%E5%BA%93%EF%BC%9F

目前在做项目的拆分，其中涉及到公共组件的剥离，然后公共组件会牵扯到一些依赖共用，如何更好的对拆分项目的管理。
