### ISSUE TITLE
子应用 vue +cube-ui 。组件icon 样式全部丢失

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1503]
![image](https://user-images.githubusercontent.com/24559368/121465232-00ec1680-c9e8-11eb-86c9-8fcc34bc6594.png)

**Comment by gongshun** [comment]
如果是生产环境，参考 https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

如果是开发环境，你是否开启了样式严格隔离？

![Uploading image.png…]()
