### ISSUE TITLE
子应用切换导致路由错误

### ISSUE THREAD

**Issue by cxn2019** [umijs/qiankun#1507]
主应用与子应用路由都是history模式，都是vue框架，
存在子应用1，appname为app1
子应用2，appname为app2

点击加载子应用1，路由为http://127.0.0.1:8080/app1/***,  切换点击加载子应用2，路由为http://127.0.0.1:8080/app2/***，但是有时会出现点击加载子应用2时，路由会变成http://127.0.0.1:8080/app1/app2/***,导致加载失败，会把上次应用的前缀拼接上

子应用都是动态添加，所以会动态调用注册应用的api

**Comment by gongshun** [comment]
你用什么跳转的路由？主应用的路由实例？

**Comment by cxn2019** [comment]
子应用跳转加载使用的是window.history.push({}, null, '******'),切换到主应用路由就是this.$router.push('******'),使用主应用实例跳转

**Comment by cxn2019** [comment]
上面更正下，window.history.pushState({}, null, '****'),即使更换调用主路由实例this.$router.push也是会出现同样问题，

**Comment by cxn2019** [comment]
老师你好，复现demo已上传https://github.com/cxn2019/Project.git，启动主子应用后，先切换子应用，刷新下，在切换回主应用路由，在回到刚才的子应用，即可复现，辛苦老师了

**Comment by cxn2019** [comment]
老师你好，有进展吗

**Comment by gongshun** [comment]
子应用的路由实例每次都需要销毁重建https://github.com/cxn2019/Project/blob/197320b6304e210b44c0c0870275d0daadb75371/sub-app/src/main.js#L22。

参考 https://github.com/umijs/qiankun/blob/972872f5fe62ca87b6911fbe8c62b389ac65f9c5/examples/vue/src/main.js#L19

**Comment by cxn2019** [comment]
好的，辛苦老师了

**Comment by YFAnt** [comment]
@gongshun  您好， 我现在在 vue 主应用 + umi2子应用也出现了这个问题， 如何在 umi2 销毁初始化路由呢，万分感谢🙏

**Comment by gongshun** [comment]
> @gongshun 您好， 我现在在 vue 主应用 + umi2子应用也出现了这个问题， 如何在 umi2 销毁初始化路由呢，万分感谢🙏

没有代码猜不出来问题，能否提供一个复现demo

**Comment by YFAnt** [comment]
@gongshun  我接入了一个开源的 代码有点多  [here](https://github.com/YFAnt/test) 多切换几次就会出现 ，劳烦您帮忙看下

**Comment by gongshun** [comment]
> @gongshun 我接入了一个开源的 代码有点多 [here](https://github.com/YFAnt/test) 多切换几次就会出现 ，劳烦您帮忙看下

子应用的配置里面加一个`shouldNotModifyDefaultBase: true` 看下

https://github.com/YFAnt/test/blob/3d3824c04a938188cd149042b983663b4bf5d115/jetlinks-ui-antd-1.3.0/config/config.ts#L17

**Comment by YFAnt** [comment]
@gongshun  您好，我发现当切换不成功的时候，例如 由 /a 切换为/b的时候， umi-history 里面的 createBrowserHistory.js 里面的 push 方法执行了一次，这个 里面有个参数 path，我打印了一下 还是之前的/a， 我怀疑他先切换了/b 然后又执行了/a 然后就出现了/a/b的情况

**Comment by YFAnt** [comment]
@gongshun  你好，因为我 umi没咋用过， 我在这个地方加了一个补丁，增加了一个 判断 
<img width="812" alt="image" src="https://github.com/umijs/qiankun/assets/46584057/87405435-80ae-4832-b4f5-6b703d75ecc4">
虽然没解决这个地方为啥会被调用， 但是这样能解决我上面的问题
