### ISSUE TITLE
[Bug]npm-run-all: command not found

### ISSUE THREAD

**Issue by fanguangjian** [umijs/qiankun#1508]
## What happens?
![image](https://user-images.githubusercontent.com/26645436/121644277-2b1c0200-cad6-11eb-9dff-26fd6fc54bb7.png)

yarn examples:install  后报错: /bin/sh: npm-run-all: command not found

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：Chrome
- **操作系统**： Mac

**Comment by gongshun** [comment]
你没发现你安装依赖meichen没成功，有报错吗

![image](https://user-images.githubusercontent.com/29347231/121980329-5183bb00-cdbe-11eb-82f5-95e08818fc25.png)
