### ISSUE TITLE
子应用内某个区域手动加载另外一个子应用嵌入进来

### ISSUE THREAD

**Issue by cxn2019** [umijs/qiankun#1511]
当子应用A已经注册加载到主应用中，点击子应用A内某个页面手动加载子应用B，使用api 是 loadMicroApp手动加载另外一个字应用B，未在主应用注册，结果是子应用B有加载上挂载在子应用A的页面里，但是子应用B的内容未被渲染出来

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1404 重复
