### ISSUE TITLE
父项目与子项目，只用一套部署，会报错404

### ISSUE THREAD

**Issue by mikechen7** [umijs/qiankun#1512]
父项目与子项目，只用一套部署，文件会报错404，但是父项目中可以正常访问，是不是不能够直接通过在子项目中man.js判断，分别走不同的处理方式来处理，既要在父项目中正常使用，又要在子项目中正常使用，请问一下，楼主有什么方案可以处理这种场景吗

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2

**Comment by mikechen7** [comment]
是路由问题，要调整路由，改成hash方式就好了
