### ISSUE TITLE
子应用内的插件及子应用无法使用window

### ISSUE THREAD

**Issue by cxn2019** [umijs/qiankun#1514]
子应用内使用了某个插件，插件内有使用window对象，但是子应用获取的window不对，请教下如何处理，主应用吧把window对象传递给子应用了，但是子应用内安装的插件还没没法使用，这种方式不太好处理

**Comment by gongshun** [comment]
沙箱可以关闭，大部分情况沙箱不会影响 window 对象的使用

**Comment by cxn2019** [comment]
老师你好，把沙箱关闭了会影响到其他子应用的样式，目前涉及子应用比较多，还有其他方式处理吗

**Comment by gongshun** [comment]
> 老师你好，把沙箱关闭了会影响到其他子应用的样式，目前涉及子应用比较多，还有其他方式处理吗

子应用怎么用不了window，举两个例子看看？

**Comment by cxn2019** [comment]
老师你好，例如子应用A里面使用npm install jsplumb安装插件，插件里某段代码使用了window,从node_modules安装插件包复制一个方法代码如下，
“TouchEvent”: function(evt) {
    var touchList = _touchAndList(window, _el, ***********)
}

上面代码里的window就不是原windwo,显示的是被劫持过后的proxy

如果是子应用内某个方法使用，可以从主应用传递，但这个是安装的插件里面使用的，不知道怎么处理

**Comment by gongshun** [comment]
把这个 js 改成动态插入 script 标签的形式加载，然后用 excludeAssetFilter 可以逃出沙箱
