### ISSUE TITLE
router 实例对象在其他js文件如何使用;

### ISSUE THREAD

**Issue by Ghjsw** [umijs/qiankun#1521]
![image](https://user-images.githubusercontent.com/20982392/122718428-8486ec80-d29f-11eb-9a06-73ac4c153395.png)

如图,  在文件最后export default router;

x.js文件内    import router from '../main';

结果 router  为null;

这种情况改如何导出呢?   请大佬们解惑

**Comment by gongshun** [comment]
无法异步 export，你可以将其他需要使用 router 的地方，导出一个函数，在实例化 Router 之后调用，将 router 传给它
