### ISSUE TITLE
在特定情况activeRule钩子中返false，但是还是会执行微应用对应页面js代码

### ISSUE THREAD

**Issue by yangheng15** [umijs/qiankun#1523]
## What happens?

在特定情况activeRule钩子中返false，但是还是会执行微应用对应页面js代码
具体是因为我理解可以在activeRule钩子中动态返回true或者false 来控制是否激活当前的微应用，所以在这里引入了权限控制，通过在钩子中判断是否有权限来返回对应的值，已达到目的。但是发现返回false 时，微应用对应页面的js还是会执行。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: ^2.4.2
- **Platform Version**:
- **Browser Version**:

**Comment by yangheng15** [comment]
想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。

**Comment by gongshun** [comment]
> @gongshun 大佬想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。

理论上可以，但是这个函数不支持异步。没有权限应该不给注册子应用，这样才比较合理

**Comment by yangheng15** [comment]
> > @gongshun 大佬想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。
> 
> 理论上可以，但是这个函数不支持异步。没有权限应该不给注册子应用，这样才比较合理

不支持异步这个可以解决， 您刚刚提到的不注册子应用，我有些疑问，activeRule是激活应用而不是注册应用对吧？
场景：
进入一个子应用路由例如：/app/demoPage  （当前这个路由有权限）所以是可以注册成功的，第一次进入的时候会注册微应用，但是当我通过这个页面中的button按钮跳转到这个页面的子页面时例如：/app/demoPage/childPage 时这个页面我理解是不会再注册微应用了因为之前父页面已经注册过了，但是会走activeRule钩子，所以我在这里做了权限校验，进行拦截，返回了false，但是现在遇到了问题是这个页面中的js执行了。这点让我一直没有想明白是怎么回事。我理解如果不激活当前的路由的微应用应该不会执行这个页面的js代码吧？

**Comment by yangheng15** [comment]
> > @gongshun 大佬想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。
> 
> 理论上可以，但是这个函数不支持异步。没有权限应该不给注册子应用，这样才比较合理

前提是这个跳转按钮是微应用中的，如果是主应用的跳转则不会出现这个问题

**Comment by gongshun** [comment]
> > > @gongshun 大佬想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。
> > 
> > 
> > 理论上可以，但是这个函数不支持异步。没有权限应该不给注册子应用，这样才比较合理
> 
> 前提是这个跳转按钮是微应用中的，如果是主应用的跳转则不会出现这个问题

跳转按钮是微应用的，微应用已经加载了？

**Comment by yangheng15** [comment]
> > > > @gongshun 大佬想问一下，可以在activeRule钩子中做权限的拦截吗？ 如果没有权限则不激活当前路由的微应用。
> > > 
> > > 
> > > 理论上可以，但是这个函数不支持异步。没有权限应该不给注册子应用，这样才比较合理
> > 
> > 
> > 前提是这个跳转按钮是微应用中的，如果是主应用的跳转则不会出现这个问题
> 
> 跳转按钮是微应用的，微应用已经加载了？

/app/demoPage 这个页面是有权限的所以第一次进入这个路由时加载了app这个微应用，但是当通过这个页面中的button 跳转到/app/demoPage/childPage 这个页面（也就是app 这个微应用的子页面）时使用activeRule判断权限返回了false 表示没有权限，不激活这个路由的微应用，发现这个页面的js会执行（这个页面是vue写的，created钩子中调用了接口，发现接口被调用了，所以这个页面执行了）

**Comment by gongshun** [comment]
activeRule只能判断子应用是否会激活，并不会阻止路由跳转，你的子应用已经激活了，你再跳转路由，子应用这时候肯定会响应路由的

**Comment by yangheng15** [comment]
> activeRule只能判断子应用是否会激活，并不会阻止路由跳转，你的子应用已经激活了，你再跳转路由，子应用这时候肯定会响应路由的

那我应该在没有权限时，卸载掉当前子应用吗？因为如果没有权限主应用会渲染其他页面，所以会将主应用的div节点#container 干掉，所以如果不activeRule 拦截 qiankun会报错（因为找不到这个dom节点了）

**Comment by gongshun** [comment]
> 那我应该在没有权限时，卸载掉当前子应用吗？因为如果没有权限主应用会渲染其他页面，所以会将主应用的div节点#container 干掉，所以如果不activeRule 拦截 qiankun会报错（因为找不到这个dom节点了）

暂时不支持子应用的卸载，建议在注册之前判断权限，过滤掉无权限的子应用，或者你用 loadMicroApp 来控制

**Comment by yangheng15** [comment]
> > 那我应该在没有权限时，卸载掉当前子应用吗？因为如果没有权限主应用会渲染其他页面，所以会将主应用的div节点#container 干掉，所以如果不activeRule 拦截 qiankun会报错（因为找不到这个dom节点了）
> 
> 暂时不支持子应用的卸载，建议在注册之前判断权限，过滤掉无权限的子应用，或者你用 loadMicroApp 来控制

可是如果过滤的话，一个子应用的页面会有很多，可能是某一个页面没有权限，我不能把这个子应用都过滤掉吧

**Comment by yangheng15** [comment]
> > > 那我应该在没有权限时，卸载掉当前子应用吗？因为如果没有权限主应用会渲染其他页面，所以会将主应用的div节点#container 干掉，所以如果不activeRule 拦截 qiankun会报错（因为找不到这个dom节点了）
> > 
> > 
> > 暂时不支持子应用的卸载，建议在注册之前判断权限，过滤掉无权限的子应用，或者你用 loadMicroApp 来控制
> 
> 可是如果过滤的话，一个子应用的页面会有很多，可能是某一个页面没有权限，我不能把这个子应用都过滤掉吧

大佬 您的意思是 activeRule这个钩子并不能阻止已经激活过的微应用跳转当前微应用没有权限路由，即使跳转时activeRule返回了false 页面也响应的，我这么理解可以嘛

**Comment by gongshun** [comment]
> 可是如果过滤的话，一个子应用的页面会有很多，可能是某一个页面没有权限，我不能把这个子应用都过滤掉吧

你应该用路由钩子来判断权限啊，activeRule只会激活/卸载子应用，但是无法阻止路由跳转。你用activeRule来做， 路由先跳转，子应用响应了路由，同时activeRule判断为false，被卸载。卸载不会发生在子应用响应路由之前

**Comment by yangheng15** [comment]
> > 可是如果过滤的话，一个子应用的页面会有很多，可能是某一个页面没有权限，我不能把这个子应用都过滤掉吧
> 
> 你应该用路由钩子来判断权限啊，activeRule只会激活/卸载子应用，但是无法阻止路由跳转。你用activeRule来做， 路由先跳转，子应用响应了路由，同时activeRule判断为false，被卸载。卸载不会发生在子应用响应路由之前

大佬 我试了一下，在主应用的路由钩子中判断路由是否有权限，如果没有权限则跳转404页面，发现子应用中button触发的跳转后子应用对应的跳转页面的js还是执行了，我觉的可能是主应用的路由拦截是在子应用跳转之后发生的，那时候子应用的js已经执行了
