### ISSUE TITLE
微前端部署子应用与主应用共用一个端口

### ISSUE THREAD

**Issue by wongyd** [umijs/qiankun#1525]
## What happens?
按照乾坤官网当前的配置,每个应用需要开启一个端口并且对外开放,由于公司限制，子应用和主应用只能用一个端口或者子应用的端口不能对外开放,应该如何部署。

## Mini Showcase Repository(REQUIRED)
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.4.0
- **Platform Version**:
- **Browser Version**:谷歌91.0.4472.101

**Comment by pigfly1** [comment]
你可以参考一下这两种方式:https://qiankun.umijs.org/zh/cookbook#%E5%9C%BA%E6%99%AF-1%EF%BC%9A%E4%B8%BB%E5%BA%94%E7%94%A8%E5%92%8C%E5%BE%AE%E5%BA%94%E7%94%A8%E9%83%A8%E7%BD%B2%E5%88%B0%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88%E5%90%8C%E4%B8%80%E4%B8%AA-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3%EF%BC%89
