### ISSUE TITLE
[Bug]子应用节点挂载在body上的卸载之后子应用节点并未卸载

### ISSUE THREAD

**Issue by itnannan** [umijs/qiankun#1527]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

子应用挂载在body上的节点，在子应用卸载时并未卸载。主应用首页加载子应用时，子应用节点挂载在body上，主应用跳转登录页，应卸载出登录页以外的节点。但是子应用挂载的节点依然保存了下来，导致页面错乱。需刷新页面，或者手动卸载这些节点。
例如summernote
![image](https://user-images.githubusercontent.com/15651294/122876859-91bbde00-d368-11eb-8228-96697093b3f0.png)
正常加载子应用时的节点。
![image](https://user-images.githubusercontent.com/15651294/122876935-a6987180-d368-11eb-91c5-835e1f60459c.png)
返回登录页时的节点。并未处理

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1207 重复
