### ISSUE TITLE
IE publicPath问题

### ISSUE THREAD

**Issue by Zhongxinke** [umijs/qiankun#153]
## What happens?

子应用在 bootstrap 生命周期动态注入 webpack_public_path
![image](https://user-images.githubusercontent.com/33825894/69031080-38fdc400-0a14-11ea-8f06-d243b5ef07f8.png)
打印assetPublicPath，
Chrome下，assetPublicPath='http://localhost:8100/'
IE下， assetPublicPath=‘/’
## Context

- **qiankun Version**: 1.3.5

**Comment by kuitos** [comment]
目前想在 ie 下运行只能关闭沙箱，但是关闭沙箱 assetPublicPath 也用不了吧
