### ISSUE TITLE
[Feature Request] Maybe the div of templateWrapper need can be styled for flex layout

### ISSUE THREAD

**Issue by careyke** [umijs/qiankun#1531]
## Background

When your mian-app and micro-app use flex layout, but the div of templateWrapper can not set. It seem not friendly, micro-app need additional processing styles.

## Proposal

I think you can provide parameters for developers to set the style of templateWrapper.
like this:
```
// current
export function getDefaultTplWrapper(id: string, name: string) {
  return (tpl: string) => `<div id="${getWrapperId(id)}" data-name="${name}">${tpl}</div>`;
}

// modified
export function getDefaultTplWrapper(id: string, name: string, className?:string) {
  return (tpl: string) => `<div id="${getWrapperId(id)}" data-name="${name}" class="${className}">${tpl}</div>`;
}
```

## Additional context

![wrapper](https://user-images.githubusercontent.com/31249072/123056212-40c7ea80-d439-11eb-8c47-2709bd85b1ff.png)

**Comment by gongshun** [comment]
duplicated with https://github.com/umijs/qiankun/issues/333
