### ISSUE TITLE
[Feature Request] antd pro 不使用 umi-qiankun 接入方式

### ISSUE THREAD

**Issue by Jiyr0119** [umijs/qiankun#1536]
## Background
在做一款脚手架工具，在创建项目时 可以选择 主项目模版时 vue element 微应用模版时 antd pro可以供使用者选择多种组合方式，现在vue版本的微前端模式开发完成。但是 antd pro 需要 umi-qiankun的模式，就满足不了我 在 vue 模版为主项目时 antd pro为微应用接入的需求。
![image](https://user-images.githubusercontent.com/28727613/123378403-48b19700-d5bf-11eb-93ac-b282c06ca430.png)

## Proposal

想知道在umi 中 使用常规react微应用的配置模式  ：
https://qiankun.umijs.org/zh/guide/tutorial#react-%E5%BE%AE%E5%BA%94%E7%94%A8

## Additional context

主要就是这种配置 在微应用是antd pro时 不知道在哪里改 😂

![image](https://user-images.githubusercontent.com/28727613/123378858-dd1bf980-d5bf-11eb-995e-76b67e4d0b66.png)

![image](https://user-images.githubusercontent.com/28727613/123378838-d68d8200-d5bf-11eb-9369-816d3fd05ad7.png)

**Comment by gongshun** [comment]
> 就满足不了我 在 vue 模版为主项目时 antd pro为微应用接入的需求。

umi-qiankun 的子应用可以被普通 qiankun 主应用接入

![image](https://user-images.githubusercontent.com/29347231/123397658-3c383900-d5d5-11eb-9332-68eb307adf36.png)

**Comment by Jiyr0119** [comment]
> > 就满足不了我 在 vue 模版为主项目时 antd pro为微应用接入的需求。
> 
> umi-qiankun 的子应用可以被普通 qiankun 主应用接入
> 
> ![image](https://user-images.githubusercontent.com/29347231/123397658-3c383900-d5d5-11eb-9332-68eb307adf36.png)

这个项目是开源的嘛 可以发一下嘛

**Comment by gongshun** [comment]
> 这个项目是开源的嘛 可以发一下嘛

项目用的是 umi-qiankun的官方demo，主项目随便弄的 https://github.com/umijs/umi-plugin-qiankun/tree/master/examples

**Comment by Jiyr0119** [comment]
> > 这个项目是开源的嘛 可以发一下嘛
> 
> 子项目用的是 umi-qiankun 的官方 demo，主项目随便弄的 https://github.com/umijs/umi-plugin-qiankun/tree/master/examples

好滴 好滴 谢谢了

**Comment by JoMartinezZhu** [comment]
umi-qiankun 必须要求子应用是 umi 应用嘛？

**Comment by gongshun** [comment]
> umi-qiankun 必须要求子应用是 umi 应用嘛？

子应用可以是非 umi 应用
