### ISSUE TITLE
[Bug]使用内联 script 脚本，无法解析脚本内容

### ISSUE THREAD

**Issue by jamesjianpeng** [umijs/qiankun#1540]
## 使用内联 script 脚本， 无法解析脚本内容，报错信息如下

![企业微信截图_16248725046815](https://user-images.githubusercontent.com/22436891/123613929-70f6fb00-d836-11eb-8df2-d785bdaedc30.png)

- **qiankun 版本**: 2.1.1
- **浏览器版本**： 91.0.4472.124
- **操作系统**：window 10

**Comment by gongshun** [comment]
这只是提示你这块代码执行报错，具体的错误在下一行
