### ISSUE TITLE
子应用vue项目中使用requirejs报错？

### ISSUE THREAD

**Issue by ibeeger** [umijs/qiankun#1542]
vue技术栈子应用，里面有一部分代码是需要requirejs，异步加载的js模块； 

## How To Reproduce

子应用 script 方式 加载requirejs, requirejs有新增部分
```
this.requireJS = require;
this.requirejs = requirejs;
this.define = define; //感觉像define 导致的；
```

```javascript
require.js:168 Uncaught Error: Mismatched anonymous define() module: function() {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// install a JSONP callback for chunk loading
/******/ 	function webpackJsonpCallback(data) {
/******/ 		var chunkIds = data[0];
/******/ 		var moreModules = data[1];
/******/ 		var executeModules = data[2];
/******/
/******/ 		// add "moreModules" to the modules object,
/******/ 		// then flag all "chunkIds" as loaded and fire callback
/******/ 		var moduleId, chunkId, i = 0, resolves = [];

```
## 最小复现代码
* https://github.com/ibeeger/qiankun-issues-exp.git
 
## 版本环境信息

- **qiankun Version**: 2.3.3
- **Platform Version**: mac os 11.2.2
- **Browser Version**: chrome 90

**Comment by woleicom** [comment]
> vue技术栈子应用，里面有一部分代码是需要requirejs，异步加载的js模块；
> 
> ## How To Reproduce
> 子应用 script 方式 加载requirejs, requirejs有新增部分
> 
> ```
> this.requireJS = require;
> this.requirejs = requirejs;
> this.define = define; //感觉像define 导致的；
> ```
> 
> ```js
> require.js:168 Uncaught Error: Mismatched anonymous define() module: function() {
> return /******/ (function(modules) { // webpackBootstrap
> /******/ 	// install a JSONP callback for chunk loading
> /******/ 	function webpackJsonpCallback(data) {
> /******/ 		var chunkIds = data[0];
> /******/ 		var moreModules = data[1];
> /******/ 		var executeModules = data[2];
> /******/
> /******/ 		// add "moreModules" to the modules object,
> /******/ 		// then flag all "chunkIds" as loaded and fire callback
> /******/ 		var moduleId, chunkId, i = 0, resolves = [];
> ```
> 
> ## 最小复现代码
> * https://github.com/ibeeger/qiankun-issues-exp.git
> 
> ## 版本环境信息
> * **qiankun Version**: 2.3.3
> * **Platform Version**: mac os 11.2.2
> * **Browser Version**: chrome 90

好像是模块定义的不对吧，仓库不允许提交，贴图了
![image](https://user-images.githubusercontent.com/9603048/128106521-409a3123-9dae-4cf5-ad29-cedf14bf6d88.png)
![image](https://user-images.githubusercontent.com/9603048/128106547-682117c6-d5e3-4887-bc6f-942b12388490.png)
![image](https://user-images.githubusercontent.com/9603048/128106559-d72348c8-0a2e-4662-a0e4-4a5349558ace.png)
![image](https://user-images.githubusercontent.com/9603048/128106575-f622f1d3-7869-4b7f-8c04-717f8385a43d.png)
