### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by xiaodoubaoldl** [umijs/qiankun#1545]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

![image](https://user-images.githubusercontent.com/25196057/124061334-45a42400-da61-11eb-867d-c903b3a562aa.png)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun：2.4.2**
- **浏览器版本：ie11**：
- **操作系统：win10**：

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%BB%99-ie-%E6%89%93%E8%A1%A5%E4%B8%81%EF%BC%9F

**Comment by xiaodoubaoldl** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%BB%99-ie-%E6%89%93%E8%A1%A5%E4%B8%81%EF%BC%9F

![image](https://user-images.githubusercontent.com/25196057/124066525-62455980-da6b-11eb-9cd1-b70340c055fc.png)
![image](https://user-images.githubusercontent.com/25196057/124066553-75582980-da6b-11eb-97f5-6e9930774016.png)
还是没有解决第二个是主应用

**Comment by gongshun** [comment]
给主应用加就可以了，需要加在主应用的入口文件**最上面**  参考 https://github.com/gongshun/qiankun-vue-demo 

![image](https://user-images.githubusercontent.com/29347231/124072737-c1a76780-da73-11eb-94c7-92e206e6f1e9.png)
