### ISSUE TITLE
项目启动后主应用如何获取子应用的js文件

### ISSUE THREAD

**Issue by lilin0802** [umijs/qiankun#1550]
## Background

每个子应用都有权限配置的js文件，
怎么在主应用中获取到所有配置文件，并渲染出来

**Comment by webxmsj** [comment]
如果权限配置是挂载在window下的， 或许可以通过afterMount(app, global){ /* global 应该可以获取到*/ }

**Comment by gongshun** [comment]
自定义 fetch 就可以拿到了，https://qiankun.umijs.org/zh/api#startopts

![image](https://user-images.githubusercontent.com/29347231/124408368-b193ce80-dd78-11eb-9dfd-3230566a65c5.png)

**Comment by lilin0802** [comment]
> 如果权限配置是挂载在window下的， 或许可以通过afterMount(app, global){ /* global 应该可以获取到*/ }

项目启动，各个子应用都还没有挂载在主应用上，是去取不到的吧

**Comment by lilin0802** [comment]
> 自定义 fetch 就可以拿到了，https://qiankun.umijs.org/zh/api#startopts
> 
> ![image](https://user-images.githubusercontent.com/29347231/124408368-b193ce80-dd78-11eb-9dfd-3230566a65c5.png)

大佬，能具体说说嘛，最好给个例子，我不是太清楚

**Comment by lx11573** [comment]
> > 自定义 fetch 就可以拿到了，https://qiankun.umijs.org/zh/api#startopts
> > ![image](https://user-images.githubusercontent.com/29347231/124408368-b193ce80-dd78-11eb-9dfd-3230566a65c5.png)
> 
> 大佬，能具体说说嘛，最好给个例子，我不是太清楚

可以看看官方的示例
https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95

**Comment by lilin0802** [comment]
> > > 自定义 fetch 就可以拿到了，https://qiankun.umijs.org/zh/api#startopts
> > > ![image](https://user-images.githubusercontent.com/29347231/124408368-b193ce80-dd78-11eb-9dfd-3230566a65c5.png)
> > 
> > 
> > 大佬，能具体说说嘛，最好给个例子，我不是太清楚
> 
> 可以看看官方的示例
> https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95

这种好像也是点击子应用挂载之后才会调用，而且调用的js文件怎么在子应用配置呢

**Comment by gongshun** [comment]
> 这种好像也是点击子应用挂载之后才会调用，而且调用的js文件怎么在子应用配置呢

预请求就会请求啊，再说了，你都没有加载子应用，需要知道它的权限信息干嘛?这种数据就应该在子应用加载时传给父应用

**Comment by lilin0802** [comment]
> > 这种好像也是点击子应用挂载之后才会调用，而且调用的js文件怎么在子应用配置呢
> 
> 预请求就会请求啊，再说了，你都没有加载子应用，需要知道它的权限信息干嘛?这种数据就应该在子应用加载时传给父应用

非常感谢您的回答！
是这样的，我现在的权限是在子应用中，但是我想在主应用的页面统一配置，这个该怎么搞

**Comment by lilin0802** [comment]
预加载的js文件怎么在子应用配置，目前预加载只有这两个
![image](https://user-images.githubusercontent.com/76139871/124435887-06027280-dda8-11eb-957d-3f96a2889d87.png)

**Comment by gongshun** [comment]
> 预加载的js文件怎么在子应用配置，目前预加载只有这两个
> ![image](https://user-images.githubusercontent.com/76139871/124435887-06027280-dda8-11eb-957d-3f96a2889d87.png)

子应用的 index.html 中引入的 script 都会被预请求，懒加载的 js 不会

**Comment by lilin0802** [comment]
目前解决了这个需求：
1、将子应用的js文件放在public目录下，
2、在主应用里用fetch请求获取
例如：fetch('http://localhost:9001/xxx.js')

**Comment by lx11573** [comment]
> 目前解决了这个需求：
> 1、将子应用的js文件放在public目录下，
> 2、在主应用里用fetch请求获取
> 例如：fetch('http://localhost:9001/xxx.js')

使用通信将所需要的权限传入会不会更好

**Comment by lilin0802** [comment]
> > 目前解决了这个需求：
> > 1、将子应用的js文件放在public目录下，
> > 2、在主应用里用fetch请求获取
> > 例如：fetch('http://localhost:9001/xxx.js')
> 
> 使用通信将所需要的权限传入会不会更好

通信的话需要先把所有子应用都挂载到主应用才能通信吧，这样就不太适合我这个这个项目的需求。

**Comment by lilin0802** [comment]
> > 目前解决了这个需求：
> > 1、将子应用的js文件放在public目录下，
> > 2、在主应用里用fetch请求获取
> > 例如：fetch('http://localhost:9001/xxx.js')
> 
> 使用通信将所需要的权限传入会不会更好

通信的话需要先把所有子应用都挂载到主应用才能通信吧，这样就不太适合我这个这个项目的需求。
