### ISSUE TITLE
electron 中无法匹配子系统页面

### ISSUE THREAD

**Issue by StitchC** [umijs/qiankun#1554]
## What happens?

我在electron 中读取一个部署在 cos 上面的页面，然后在页面中进行路径跳转，但是发现无法触发子应用的加载

路径如下：https://test-cdn.vipthink.cn/app/pc/student/web/2.15.0/index.html#/subject/math

主应用配置如下：

```
registerMicroApps([
 {
    name: 'math',
    entry: '//test-cdn.vipthink.cn/app/pc/student/web/2.15.0/math/',
    container: '#micro-app-container',
    activeRule: '#/subject/math',
    props: {
      baseUrl: '/subject/math',
      route(name, options) {
        changeRoute(name, options)
      }
    }
  },
])
```

## Mini Showcase Repository(REQUIRED)

> null

## How To Reproduce

**Steps to reproduce the behavior:** null

**Expected behavior** 主应用能够正常加载子应用

## Context

- **qiankun Version**: 2.4.2
- **Platform Version**: 
- **Browser Version**: electron 4.2.12 Chrome 68

**Comment by jinbiaode** [comment]
遇到了 有解决办法吗？
