### ISSUE TITLE
Uncaught (in promise) Error: [qiankun] You need to export lifecycle functions in ‘vu3’ entry

### ISSUE THREAD

**Issue by EvanYY** [umijs/qiankun#1557]
## What happens?
问题出现为Monaco 浏览器编辑器插件 ，因为体量过大，就以CDN方式在 public/index.html 引入，再生成全局变量后，其loader.js 会将对象 挂载在window上；
再使用qiankun手动加载微应用后，抛出标题错误。
如果将script 引入的(monaco)loader.js 注释后则会正常加载子应用，打开则不能正常使用子应用

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
https://github.com/EvanYY/qiankun-bugs-main.git
https://github.com/EvanYY/qiankun-bugs-vue3-child.git

## How To Reproduce
![image](https://user-images.githubusercontent.com/29744562/124605111-2a407b00-de9e-11eb-90c3-85fecd97e5df.png)
![image](https://user-images.githubusercontent.com/29744562/124605284-552acf00-de9e-11eb-92e0-41d4297dc733.png)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:  2.4.3
- **Platform Version**: macos  11.4
- **Browser Version**: chrome 版本 91.0.4472.114（正式版本） (x86_64)

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1216 类似。

报错原因：

monaco-editor/min/vs/loader.js 这个 js 里面定义了 define

![image](https://user-images.githubusercontent.com/29347231/125039615-45430300-e0c9-11eb-8e52-ea222f5bdd61.png)

导致子项目的 app.js 执行时，走了错误的判断

![image](https://user-images.githubusercontent.com/29347231/125040177-ea5ddb80-e0c9-11eb-9f1f-da29f0d55bea.png)

验证办法：在主项目的控制台执行如下代码

![image](https://user-images.githubusercontent.com/29347231/125040273-06fa1380-e0ca-11eb-934e-30273dd13a2e.png)

解决办法1：https://github.com/umijs/qiankun/issues/1216#issue-787622598

![image](https://user-images.githubusercontent.com/29347231/125040395-2d1fb380-e0ca-11eb-9cdf-8104dfdc2af7.png)

解决办法2：https://github.com/umijs/qiankun/issues/1216#issuecomment-762579410
