### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by youngList** [umijs/qiankun#1562]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

Application XX died in status LOADING_SOURCE_CODE: Unexpected identifier
浏览器版本一定要chrome 49
关于这个问题的解决方法，全部按照这边的处理的https://qiankun.umijs.org/zh/faq
## 最小可复现仓库
你们自己代码直接在chrome 49打开应该就会出现
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
2.4.1
- **浏览器版本**：
- chrome 49
- **操作系统**：
window

**Comment by gongshun** [comment]
chrome30 都能跑起来 https://github.com/umijs/qiankun/issues/1544

**Comment by youngList** [comment]
谢谢了，明天我在看下发自我的华为手机-------- 原始邮件 --------发件人： gongshun ***@***.***>日期： 2021年7月7日周三 晚上8:35收件人： umijs/qiankun ***@***.***>抄送： youngJson ***@***.***>, Author ***@***.***>主    题： Re: [umijs/qiankun] [Bug]请遵循下文模板提交问题，否则您的问题会被关闭 (#1562)

chrome30 都能跑起来 #1544
