### ISSUE TITLE
qiankun 挂载的子应用如何获取 window？

### ISSUE THREAD

**Issue by lx11573** [umijs/qiankun#1564]
目前有个项目的源码中使用了 
```js
window.addEventListener('message', event => {
 if (event.source === window) ...
})
```
 因为 `qiankun` 挂载的子应用 `window` 返回的都是 `proxy`, 那么子应用中如何能取到 `window`？ 像上面的代码如何才能通过？

**Comment by qiang47199** [comment]
> 当前项目的源码中使用了
> 
> ```js
> 窗口。addEventListener ( 'message' ,  event  =>  { 
>  if  ( event . source  ===  window ) ...
>  } )
> ```
> 
> 因为`qiankun`载载的子应用`window`返回的都挂到那`proxy`子应用中`window`怎么能取？ 像上面的代码怎么不通过？

哈喽，你这个问题是如何解决的。

**Comment by UmbraCi** [comment]
> 目前有个项目的源码中使用了
> 
> ```js
> window.addEventListener('message', event => {
>  if (event.source === window) ...
> })
> ```
> 
> 因为 `qiankun` 挂载的子应用 `window` 返回的都是 `proxy`, 那么子应用中如何能取到 `window`？ 像上面的代码如何才能通过？

你好，请问这个问题怎么解决的，same issue
