### ISSUE TITLE
[Bug]主应用中切换不同子应用时会出现子应用页面一直维持第一次进入时的页面

### ISSUE THREAD

**Issue by kingliuwan** [umijs/qiankun#1567]
## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by San-Shui** [comment]
这个问题目前我也出现了，但是简单的示例复现不了
