### ISSUE TITLE
乾坤在子应用重新更新后，是否能提供刷新机制

### ISSUE THREAD

**Issue by frank994** [umijs/qiankun#1568]
## 乾坤在子应用重新更新后，是否能提供刷新机制
当用户打开一个乾坤应用，在子应用A的A1-old页面停留，这时子应用A进行新的部署，更新了代码。
A1页面更新为A1-new，但用户访问的还是A1-old页面，不管用户如何在应用间切换也好，除非刷新浏览器重新走主应用加载流程。

## Additional context

无

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/830 重复
