### ISSUE TITLE
[Bug]父子应用样式串扰的问题

### ISSUE THREAD

**Issue by bujidao** [umijs/qiankun#1569]
## What happens?

当子应用使用了相对于文档窗口的布局样式的时候，比如`position: fixed`，沙盒约束不了子应用的样式，子应用的样式会全屏乱飘。

## Mini Showcase Repository(REQUIRED)

https://github.com/fengxianqi/qiankun-example

## How To Reproduce

克隆项目, `main`为主应用，`sub_react`、`sub_ vue`为子应用，随便修改其中一个子应用，并修改样式为
```
position: fixed;
top: 0;
```
即可出现子应用浮在父应用上层的现象

## Context

- **qiankun Version**:
- ^2.0.22
- **Platform Version**:
- node v14.15.3
- **Browser Version**:
-  Chromium 91.0.864.64

**Comment by gongshun** [comment]
这种样式污染无解的，父子应用属于同一个document
