### ISSUE TITLE
主应用因为路径问题访问不了微应用

### ISSUE THREAD

**Issue by jojo-1995** [umijs/qiankun#1571]
## What happens?

主应用
访问地址路径： http://localhost:8080/app_h5/
配置：
       registerMicroApps([
  {
    name: 'vueApp',
    entry: '//localhost:8086/exp/',
    container: '#vueContainer',
    activeRule: '/life/vue',
    props: {a:router}
  },
]);

微应用路径：http://localhost:8086/exp/，

问题： 当主应用的访问地址是 http://localhost:8080/app_h5/  去访问微应用http://localhost:8086/exp/,访问不了，没有任何报错
             当主应用的访问地址是 http://localhost:8080    去访问微应用http://localhost:8086/exp/, 完全可以

疑问：主应用必须是根目录吗，主应用和微应用不能同时处于二级目录吗，感谢！

## 相关环境信息

- **qiankun 版本** 2.4.3
- **浏览器版本**： 谷歌最新
- **操作系统**： windows10
- **vue**: 2.6.11

**Comment by gongshun** [comment]
主应用在非根目录，activeRule应该带上主应用的目录，`activeRule: '/app_h5/life/vue'`

**Comment by jojo-1995** [comment]
> 主应用在非根目录，activeRule应该带上主应用的目录，`activeRule: '/app_h5/life/vue'`

谢谢，是我粗心了

**Comment by lele4818** [comment]
> 主应用在非根目录，activeRule应该带上主应用的目录，`activeRule: '/app_h5/life/vue'`

请问这里是否子应用的路由base也需要带上主应用的目录，像这样{ mode: 'history', base: /app_h5/life, }，我自己测试的确子应用的路由base需要带上才行，但是有一个问题除了写死，在不知道主应用的路径的情况下，子应用怎么获取主应用的base（process.env.BASE_URL）路径呢，尝试在子应用bootstrap或者mount钩子中获取，但是此时router已经初始化完毕，无法再去更新base的值了

**Comment by lele4818** [comment]
> > 主应用在非根目录，activeRule应该带上主应用的目录，`activeRule: '/app_h5/life/vue'`
> 
> 谢谢，是我粗心了

请问这里是否子应用的路由base也需要带上主应用的目录，像这样{ mode: 'history', base: /app_h5/life, }，我自己测试的确子应用的路由base需要带上才行，但是有一个问题除了写死，在不知道主应用的路径的情况下，子应用怎么获取主应用的base（process.env.BASE_URL）路径呢，尝试在子应用bootstrap或者mount钩子中获取，但是此时router已经初始化完毕，无法再去更新base的值了
