### ISSUE TITLE
angular7做为主应用启动qiankun报错 ERROR in node_modules/qiankun/es/apis.d.ts(1,13): error TS1005: '=' expected.

### ISSUE THREAD

**Issue by hesuocai** [umijs/qiankun#1573]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by Mickxuanyuan** [comment]
@hesuocai 请问你找到方案了吗？我这边也是这个错。
