### ISSUE TITLE
子应用中先是在window上挂载了xx属性，子应用的iframe中使用了window.parent.xx 为undefined 请问这个是什么问题

### ISSUE THREAD

**Issue by yangheng15** [umijs/qiankun#1575]
子应用中先是在window上挂载了xx属性，子应用的iframe中使用了window.parent.xx 为undefined 请问这个沙箱带来的问题吗？

**Comment by yangheng15** [comment]
@kuitos 大佬 可以帮忙看下这个是什么问题吗？

**Comment by caiguocong** [comment]
我也遇到这个问题，window在子应用被挟持了，求解 @gongshun

**Comment by yangheng15** [comment]
升级前版本：^2.0.15，升级后qiankun版本：^2.4.2 ，升级后才出现的这个问题！

**Comment by caiguocong** [comment]
我试了2.0.15也是不行，我的子应用在mainjs需要给window添加一些方法，window也是被挟持了使用不了

**Comment by caiguocong** [comment]
弱弱的问下，请问 sandbox 在哪里配置

**Comment by yangheng15** [comment]
> 弱弱的问下，请问 sandbox 在哪里配置

start中

**Comment by gongshun** [comment]
的确是 proxy 沙箱导致的。子应用使用的 window 是一个被代理的空对象，所以你添加的属性在沙箱上，并没有在真实的 window 上。而你的 iframe 拿到的是真正的 window，这上面并没有你添加的属性。

2.0.15使用的是旧版沙箱，2.1版本更新，使用的是新版沙箱。

你可以试试 `start({ sandbox : { loose: true } })`，@yangheng15

**Comment by yangheng15** [comment]
> 的确是 proxy 沙箱导致的。子应用使用的 window 是一个被代理的空对象，所以你添加的属性在沙箱上，并没有在真实的 window 上。而你的 iframe 拿到的是真正的 window，这上面并没有你添加的属性。
> 
> 2.0.15使用的是旧版沙箱，2.1版本更新，使用的是新版沙箱。
> 
> 你可以试试 `start({ sandbox : { loose: true } })`，@yangheng15

配置loose后可以拿到子应用上面的属性了，想了解下loose这个配置具体是做了什么，会不会对其他的沙箱样式隔离会有什么影响？

**Comment by gongshun** [comment]
loose 的作用

https://github.com/umijs/qiankun/blob/33c64c88c904315f332cb696e69087519c2d37fe/src/loader.ts#L306

https://github.com/umijs/qiankun/blob/33c64c88c904315f332cb696e69087519c2d37fe/src/sandbox/index.ts#L40

对应两种不同的沙箱：

https://github.com/umijs/qiankun/blob/33c64c88c904315f332cb696e69087519c2d37fe/src/sandbox/proxySandbox.ts#L128

https://github.com/umijs/qiankun/blob/33c64c88c904315f332cb696e69087519c2d37fe/src/sandbox/legacy/sandbox.ts#L27

关键的差别，旧沙箱，属性会写回 window 上

https://github.com/umijs/qiankun/blob/33c64c88c904315f332cb696e69087519c2d37fe/src/sandbox/legacy/sandbox.ts#L93
