### ISSUE TITLE
angular7子应用  启动报错  ERROR in src/app/app-routing.module.ts(10,58): error TS2339: Property '__POWERED_BY_QIANKUN__' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by hesuocai** [umijs/qiankun#1577]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
ts 语法报错，看官网的示例

![image](https://user-images.githubusercontent.com/29347231/125601220-4160bf44-3bc5-4975-b14e-b1deee37ef12.png)
