### ISSUE TITLE
[Bug]对于动态样式隔离，为什么要内联css呢？

### ISSUE THREAD

**Issue by focusLee** [umijs/qiankun#1579]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/670
