### ISSUE TITLE
为什么运行base的时候，子项目一定要是正在运行

### ISSUE THREAD

**Issue by ruomanwei** [umijs/qiankun#158]
![image](https://user-images.githubusercontent.com/19573394/69322506-efb1ac80-0c7f-11ea-884d-25bb2154473a.png)
这个entry有点不太理解，为什么是这样的。

**Comment by kuitos** [comment]
可以把 qiankun 当成 iframe 去理解

**Comment by ruomanwei** [comment]
局限性很大

**Comment by ruomanwei** [comment]
那我为什么不直接用iframe呢

**Comment by kuitos** [comment]
qiankun 不是 iframe，但是保留了 iframe 的优点(隔离性、使用简单)，同时解决了 iframe 的一些问题(UI限制、性能等)

**Comment by whyer11** [comment]
> 那我为什么不直接用iframe呢

这个同觉得有问题。。要求子项目提供web服务，不是很合理

**Comment by kuitos** [comment]
> > 那我为什么不直接用iframe呢
> 
> 这个同觉得有问题。。要求子项目提供web服务，不是很合理

![image](https://user-images.githubusercontent.com/5206843/69398034-6f448780-0d23-11ea-99d5-c048b29ad7df.png)
