### ISSUE TITLE
[Feature Request] 使用loadMicroApp同域问题咨询

### ISSUE THREAD

**Issue by Jiyr0119** [umijs/qiankun#1582]
## Background

 #400 
基于 400 的问题， 发现使用loadMicroApp没有activeRule用来完成里面提到的解决方式
```
registerMicroApps([
  {
    name: 'app-vue-hash', 
    entry: '/child/vue-hash/', // http://localhost:8080/child/vue-hash/
    container: '#appContainer', 
    activeRule: '/app-vue-hash', 
  },
  { 
    name: 'app-vue-history',
    entry: '/child/vue-history/', // http://localhost:8080/child/vue-history/
    container: '#appContainer', 
    activeRule: '/app-vue-history',
  },
],
```
而且loadMicroApp entry 就是直接以浏览器的路径去触发到子应用的。而且尝试修改不生效
```
  this.microApp = loadMicroApp({
      name: 'app1',
      entry: '//localhost:1234/detail',  // 如果这里浏览器的路径是index的时候并不会到detail的页面
      container: this.containerRef.current,
      props: { brand: 'qiankun' },
    });

```

之前的项目是管理平台每个菜单点进去都是一个iframe，所以才使用loadMicroApp现在线上和开发都处理完了。卡在这个刷新进入到子应用的页面这里，求大佬帮忙

## Proposal

https://github.com/Jiyr0119/qiankun-main
https://github.com/Jiyr0119/qiankun-sub
因为是内网环境没法直接上代码，就是以上的dome和内网完全一样的 然后子应用publicpath 也配置了对应目录

**Comment by gongshun** [comment]
1. 在哪个路由下调用 loadMicroApp ，那么你的 “activeRule” 就是这个路由，比如说你在“/child”页面手动加载子应用，那么你的子应用的路由 base 就是“/child”，然后你的 entry 不和 “/child” 相同就可以了。
2. entry 只是为了拿 index.html，指定路由毫无意义。如果想跳到到路由页面，可以在点击“ 子应用的xx页面 ”菜单时，直接 push 到对应路由，例如“/child/detail"。
3. 在某个路由页面加载子应用，看[官网说明](https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8)

**Comment by Jiyr0119** [comment]
> 3\. 官网说明

意思loadMicroApp 其实还是要结合着 registerMicroApps来用么？您第一点说的entry 是指 load 还是 register的路径呀，我现在是只用了loadMicroApp就满足了我的需求了，除了有刷新的这个bug。。。 我一开始的方向就错了么

**Comment by gongshun** [comment]
不需要呀，即使你用 loadMicroApp 

![image](https://user-images.githubusercontent.com/29347231/126419550-ffb57217-f03f-4914-b750-5369992679d5.png)

这一步是必须的。

loadMicroApp 使用的 entry 值和子应用设置的路由 base 不能重复（在qiankun环境的路由base)

**Comment by Jiyr0119** [comment]
> 不需要呀，即使你用 loadMicroApp
> 
> ![image](https://user-images.githubusercontent.com/29347231/126419550-ffb57217-f03f-4914-b750-5369992679d5.png)
> 
> 这一步是必须的。
> 
> loadMicroApp 使用的 entry 值和子应用设置的路由 base 不能重复（在qiankun环境的路由base)

![image](https://user-images.githubusercontent.com/28727613/126438733-aa207624-d55c-4016-b3c2-e9deac4f2398.png)
说出来可能不信 把这里这个注释了 就刷新也没问题了 哈哈哈 其他的都没变 感谢大佬解惑。 等我抽个时间整理一篇博客有关load这种的实践 也出一份力

**Comment by mackxu** [comment]
上面的截图会导致基座和子应用入口html耦合。activeRule 的逻辑自己实现，监听path，加载不同的子应用。同样要求，path和子应用的entry取值不要一样
