### ISSUE TITLE
[Bug]子应用index.html模版和静态资源部署在不同的地方, 路由懒加载的js文件base路径错误, 变成了模版那个路径,尽管publicPath配置成了绝对路径也没用

### ISSUE THREAD

**Issue by WormGirl** [umijs/qiankun#1584]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8

![image](https://user-images.githubusercontent.com/29347231/126418776-3e3888bb-036a-41ec-8bba-923113eaf444.png)

**Comment by WormGirl** [comment]
> https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8
> 
> ![image](https://user-images.githubusercontent.com/29347231/126418776-3e3888bb-036a-41ec-8bba-923113eaf444.png)
谢谢🐶

**Comment by WormGirl** [comment]
谢谢🐶
