### ISSUE TITLE
浏览器安装去广告插件，例如Poper Blocker，vue-router报错

### ISSUE THREAD

**Issue by yusongH** [umijs/qiankun#1587]
# 问题描述
浏览器安装去广告插件，例如Poper Blocker，会出现ChunkLoadError: Loading chunk failed报错

# demo地址
[https://github.com/yusongH/qiankun-loadingchunk](https://github.com/yusongH/qiankun-loadingchunk)

# 重新步骤
1.运行项目，查看项目正常运行
2.chrome浏览器安装Poper Blocker插件，刷新项目出现报错

# 相关版本
#### Browser Version: chrome

**Comment by gongshun** [comment]
确定是浏览器的广告屏蔽插件拦截的？隐身模式下是否正常？我装了 Adblock Plus ，没有被拦截。真的是广告屏蔽插件拦截的，也只能提示用户关闭插件 or 加入白名单，否者无解

**Comment by yusongH** [comment]
> 确定是浏览器的广告屏蔽插件拦截的？隐身模式下是否正常？我装了Adblock Plus，没有被拦截。真的是广告屏蔽用户插件拦截的，也只能加入名单，否者无解

无痕模式下不会有问题，但是无痕模式下好像是没有开启去广告的插件，你那边可以试一下装Poper Blocker，做提示的话，是怎么可以判断到用户安装了这类插件呢？

**Comment by gongshun** [comment]
如何判断用户装了广告拦截插件，你可以百度搜一下

**Comment by yusongH** [comment]
> 确定是浏览器的广告屏蔽插件拦截的？隐身模式下是否正常？我装了 Adblock Plus ，没有被拦截。真的是广告屏蔽插件拦截的，也只能提示用户关闭插件 or 加入白名单，否者无解

还有这样的情况是：
1、把路由的懒加载改成同步加载，就不会报这个错
2、把沙箱的选项sandbox改为false，也不会报这个错

**Comment by Cyrilszq** [comment]
我这边也遇到了同样的问题，排查了下原因，发现是插件内部会定义 document.createElement = function(){}; 但 qiankun 对于 createElement 的劫持是使用的 Document.prototype.createElement = function createElement(){}

这样就会导致 webpack 在利用 jsonp 加载异步脚本的时候，var script = document.createElement('script'); 并不会走 qiankun 劫持后的方法，后续也不会把这个脚本标记为「由子应用触发」(isInvokedByMicroApp)，在执行 document.head.appendChild(script) 后，动态加载进来的脚步也不会在沙箱中执行，webpackJsonpCallback 由于在当前 window 上找不到相应的模块变量，不会执行

**Comment by yusongH** [comment]
> 我这边也遇到了同样的问题，排查了下原因，发现是插件内部会定义 document.createElement = function(){}; 但 qiankun 对于 createElement 的劫持是使用的 Document.prototype.createElement = function createElement(){}
> 
> 这样就会导致 webpack 在利用 jsonp 加载异步脚本的时候，var script = document.createElement('script'); 并不会走 qiankun 劫持后的方法，后续也不会把这个脚本标记为「由子应用触发」(isInvokedByMicroApp)，在执行 document.head.appendChild(script) 后，动态加载进来的脚步也不会在沙箱中执行，webpackJsonpCallback 由于在当前 window 上找不到相应的模块变量，不会执行
> 
> 我这边尝试增加以下代码可以临时解决问题：
> 
> ```js
> beforeMount: [
>       () => {
>         window.document.createElement = Document.prototype.createElement;
>       }
>     ],
> ```
> 
> 但浏览器插件的自由性和侵入性都可以很大，是否需要应用本身去修复也需要考量

这个方案效果怎么样

**Comment by yusongH** [comment]
> # 问题描述
> 浏览器安装去广告插件，例如Poper Blocker，会出现ChunkLoadError: Loading chunk failed报错
> 
> # demo地址
> [https://github.com/yusongH/qiankun-loadingchunk](url)
> 
> # 重新步骤
> 1.运行项目，查看项目正常运行
> 2.chrome浏览器安装Poper Blocker插件，刷新项目出现报错
> 
> # 相关版本
> #### qiankun Version: v2.3.6
> #### Platform Version: vue: v2.6.11 , vue-router: v3.2.0
> #### Browser Version: chrome



> 我这边也遇到了同样的问题，排查了下原因，发现是插件内部会定义 document.createElement = function(){}; 但 qiankun 对于 createElement 的劫持是使用的 Document.prototype.createElement = function createElement(){}
> 
> 这样就会导致 webpack 在利用 jsonp 加载异步脚本的时候，var script = document.createElement('script'); 并不会走 qiankun 劫持后的方法，后续也不会把这个脚本标记为「由子应用触发」(isInvokedByMicroApp)，在执行 document.head.appendChild(script) 后，动态加载进来的脚步也不会在沙箱中执行，webpackJsonpCallback 由于在当前 window 上找不到相应的模块变量，不会执行
> 
> 我这边尝试增加以下代码可以临时解决问题：
> 
> ```js
> beforeMount: [
>       () => {
>         window.document.createElement = Document.prototype.createElement;
>       }
>     ],
> ```
> 
> 但浏览器插件的自由性和侵入性都可以很大，是否需要应用本身去修复也需要考量

是在哪个位置加呢？这个方案你们那边验证的有没有其他问题？

**Comment by yusongH** [comment]
> 我这边也遇到了同样的问题，排查了下原因，发现是插件内部会定义 document.createElement = function(){}; 但 qiankun 对于 createElement 的劫持是使用的 Document.prototype.createElement = function createElement(){}
> 
> 这样就会导致 webpack 在利用 jsonp 加载异步脚本的时候，var script = document.createElement('script'); 并不会走 qiankun 劫持后的方法，后续也不会把这个脚本标记为「由子应用触发」(isInvokedByMicroApp)，在执行 document.head.appendChild(script) 后，动态加载进来的脚步也不会在沙箱中执行，webpackJsonpCallback 由于在当前 window 上找不到相应的模块变量，不会执行
> 
> 我这边尝试增加以下代码可以临时解决问题：
> 
> ```js
> beforeMount: [
>       () => {
>         window.document.createElement = Document.prototype.createElement;
>       }
>     ],
> ```
> 
> 但浏览器插件的自由性和侵入性都可以很大，是否需要应用本身去修复也需要考量

该方法无法保证百分百成功，猜测应该要看插件的执行时机

**Comment by fluoos** [comment]
window.document.createElement = Document.prototype.createElement;
尝试了无效，用户量大了会经常遇到这种问题，各种插件影响，Poper Blocker尤为严重。

**Comment by yusongH** [comment]
> window.document.createElement = Document.prototype.createElement; 试用了，用户量大了会经常遇到这种问题，各种插件影响，Poper Blocker 相对严重。

那您那边是用什么方案解决这个问题的？

**Comment by fluoos** [comment]
> > window.document.createElement = Document.prototype.createElement; 试用了，用户量大了会经常遇到这种问题，各种插件影响，Poper Blocker 相对严重。
> 
> 那您那边是用什么方案解决这个问题的？

没有解决，等用户反馈回来，再看看是不是插件影响，如果是，叫用户关闭插件使用。挺无奈的

**Comment by blackstoneblackstone** [comment]
插件能干的事情太多了，很容易导致网站挂掉，官方应该不会修这种问题吧。
