### ISSUE TITLE
Uncaught Error: Iframe has not been created yet

### ISSUE THREAD

**Issue by Bonnie8ni** [umijs/qiankun#1588]
我嘗試在專案內監聽判斷當 LocalStorage 改變時，重新 Reload Page
並在離開頁面的時候刪除這個監聽

![iShot2021-07-21 09 49 12](https://user-images.githubusercontent.com/15052151/126418322-4e2b9887-bff8-4a13-88d7-6b3041628960.jpg)

但我發現只要加上 removeEventListener 後，只要按下儲存
專案重新 hot-reload 後，就會出現這個 Error

![iShot2021-07-21 09 49 00](https://user-images.githubusercontent.com/15052151/126418074-75e8551b-153d-4377-8490-9f1d6bc0c727.jpg)

我也試著在這裡爬文有發現這篇
https://github.com/umijs/qiankun/issues/299
確認自己的 prefix 應該沒有重複

![iShot2021-07-21 09 49 43](https://user-images.githubusercontent.com/15052151/126418437-695e3f0f-0903-4265-bc7d-c921bfea9cb6.jpg)

不曉得要怎麼解決這個問題，煩請協助

**Comment by gongshun** [comment]
render 是1.x 版本的写法，你用的 qiankun 是什么版本？

**Comment by Bonnie8ni** [comment]
> render 是1.x 版本的写法，你用的 qiankun 是什么版本？

版本：v2.0.24

**Comment by gongshun** [comment]
2.x 版本还是使用 2.x 的写法吧，https://qiankun.umijs.org/zh/cookbook#%E4%BB%8E-1x-%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E5%88%B0-2x-%E7%89%88%E6%9C%AC

**Comment by Bonnie8ni** [comment]
> 2.x 版本还是使用 2.x 的写法吧，https://qiankun.umijs.org/zh/cookbook#%E4%BB%8E-1x-%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E5%88%B0-2x-%E7%89%88%E6%9C%AC

我把 render 改成 container 還是一樣會出現這個問題

**Comment by Bonnie8ni** [comment]
@gongshun
超級離奇，我剛更新完 qiankun 到 v2.4.4（v2.0.24）、react-script 更新到 v4.0.3（原使用v3.4.3）
然後我將 registerMicroApps 內各個 Object 下的 render 更改為 container，且沒有刪除外面的 run render
就沒有再噴出上面那個錯誤了，而且專案正常執行！

`
import React from 'react';
import { ConfigProvider } from 'antd';
import ReactDOM from 'react-dom';
import {
    registerMicroApps, setDefaultMountApp,
    runAfterFirstMounted, start, initGlobalState
} from 'qiankun';
import { Provider } from 'react-redux';
import InitialLocale from 'utils/initialLocale';
import { ConnectedRouter } from 'connected-react-router';
import configureStore, { history } from 'redux/configureStore';
import rootSaga from 'redux/sagas';
import App from 'containers/App/App';
import './index.scss';
import './index.less';
import * as serviceWorker from './serviceWorker';

const packageName = process.env.REACT_APP_PROJECT_NAME;
const initialProject = window.__env.REACT_APP_INITIAL_PROJECT;
const store = configureStore();
store.runSaga(rootSaga);

function render({ appContent, loading }) {
    const container = document.getElementById(packageName);

    ReactDOM.render(
        <Provider store={store}>
            <InitialLocale>
                <ConnectedRouter history={history}>
                    <ConfigProvider prefixCls={packageName}>
                        <App loading={loading} content={appContent} />
                    </ConfigProvider>
                </ConnectedRouter>
            </InitialLocale>
        </Provider>, container);
}

render({ loading: true });

function genActiveRule(routerPrefix) {
    return location => location.pathname.startsWith(routerPrefix);
}

registerMicroApps([
    {
        name: 'jade-portal-order',
        entry: `${window.__env.REACT_APP_SERVICE_ORDER}`,
        container: '#sub-app',
        activeRule: genActiveRule('/portal/order'),
    }, {
        name: 'jade-portal-meter',
        entry: `${window.__env.REACT_APP_SERVICE_METER}`,
        container: '#sub-app',
        activeRule: genActiveRule('/portal/meter'),
    }, {
        name: 'jade-module-blockchain',
        entry: `${window.__env.REACT_APP_SERVICE_BLOCKCHAIN}`,
        container: '#sub-app',
        activeRule: genActiveRule('/portal/blockchain'),
    }, {
        name: 'jade-portal-account',
        entry: `${window.__env.REACT_APP_SERVICE_ACCOUNT}`,
        container: '#sub-app',
        activeRule: genActiveRule('/portal/account'),
    }, {
        name: 'jade-module-fico',
        entry: `${window.__env.REACT_APP_SERVICE_FICO}`,
        container: '#sub-app',
        activeRule: genActiveRule('/portal/fico'),
    }
]);

const actions = initGlobalState({ locale: '' });
actions.offGlobalStateChange();

start();

// 默認子應用
setDefaultMountApp(initialProject);

// 第一個子應用加載完畢回調
runAfterFirstMounted(() => {});

serviceWorker.unregister();
`

**Comment by lou0820** [comment]
我是这样解决的
![image](https://user-images.githubusercontent.com/34848980/130410858-e8c1efdb-3691-4bd1-983d-6d66689644c2.png)

**Comment by Bonnie8ni** [comment]
> 我是这样解决的
> ![image](https://user-images.githubusercontent.com/34848980/130410858-e8c1efdb-3691-4bd1-983d-6d66689644c2.png)

我覺得時不時好像還是會跑出來

**Comment by Bonnie8ni** [comment]
> > 我是这样解决的
> > ![image](https://user-images.githubusercontent.com/34848980/130410858-e8c1efdb-3691-4bd1-983d-6d66689644c2.png)
> 
> 我覺得時不時好像還是會跑出來

對，還是會跑出來 Q_Q
