### ISSUE TITLE
sandbox loose模式下进行开发，样式加载混乱

### ISSUE THREAD

**Issue by Esain** [umijs/qiankun#1594]
## What happens?
沙箱环境下dom加载性能非常差选择在loose模式下运行。结果主应用的部分样式，会加载到子应用的容器中,导致切换应用时被清除掉。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 通过qiankun.start({ sandbox: { loose: true }})启动项目。
2. 开发环境运行后，在不同的子应用之间切换。

**Expected behavior** 
切换应用后，界面展示正常

## Context

- **qiankun Version**:  2.4.1
- **Platform Version**:  angular: 10.2.3、 single-spa: 5.5.5、single-spa-angular: 4.9.2
- **Browser Version**: chrome  92.0.4515.107

**Comment by gongshun** [comment]
这是个老问题 https://github.com/umijs/qiankun/issues/578

**Comment by Esain** [comment]
> 这是个老问题 #578

切换应用的导航栏由基座提供的，所以子应用和基座在一个页面中渲染。问题的原理是清楚了，解决方案不能借鉴，没找到如何判断懒加载的样式来自基座的方法。

**Comment by Esain** [comment]
loose模式下还会一个问题。子应用来回切换，子应用的样式会越来越多。debug时发现恢复子应用时执行rebuild()，恢复之前卸载的样式后，组件的脚本文件还会再执行appendChild(styleEl))。导致记录样式的数组dynamicStyleSheetElements一直增长

**Comment by gongshun** [comment]
loose 并不推荐使用，的确存在很多已知的问题，后续可能会去掉，文档中也没有透出

**Comment by Esain** [comment]
> loose模式下还会一个问题。子应用来回切换，子应用的样式会越来越多。debug时发现恢复子应用时执行rebuild()，恢复之前卸载的样式后，组件的脚本文件还会再执行appendChild(styleEl))。导致记录样式的数组dynamicStyleSheetElements一直增长

缓存样式一直增长的问题，在沙箱模式下也是存在的。因为懒加载模块中的组件，每次子应用remount后都会追加样式文件(已被缓存或新组件都有)，子应用的style标签越来越多
