### ISSUE TITLE
moment.tz can not add new property to proxy.moment 

### ISSUE THREAD

**Issue by hanzhangyu** [umijs/qiankun#1595]
## What happens?

moment.tz can not add new property to proxy.moment 

## Mini Showcase Repository(REQUIRED)

```text
diff --git a/examples/react16/src/App.js b/examples/react16/src/App.js
index 55a00d4..c273b2a 100644
--- a/examples/react16/src/App.js
+++ b/examples/react16/src/App.js
@@ -41,3 +41,13 @@ export default function App() {
     </div>
   );
 }
+
+const script = document.createElement('script');
+script.onload = () => {
+  console.assert(typeof window.moment === 'function', 'moment is loaded');
+  console.assert(window.moment !== window.moment, 'moment is not equal');
+  console.assert(window.moment.tz === undefined, 'rewrite moment property failed');
+}
+script.src = 'https://g.alicdn.com/??/code/lib/moment.js/2.24.0/moment.min.js,/code/lib/moment-timezone/0.5.28/moment-timezone-with-data.min.js';
+script.crossOrigin = 'anonymous';
+document.body.appendChild(script);
```

## How To Reproduce

**Steps to reproduce the behavior:**

1. follow qiankun quick start https://github.com/umijs/qiankun/blob/069fe04e42/README.md#-getting-started
2. add this git diff
3. switch to React16
4. assert is all passed

https://github.com/umijs/qiankun/blob/069fe04e42/src/sandbox/common.ts#L17-L47
according to this getTargetValue function, There is no way to get the same normal function twice

https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L601-L604
rewirte moment property

**Expected behavior**
Provide some solution to get the same value, such as:
```js
import { registerGlobalPlainObjectKey } from 'qiankun';
registerGlobalPlainObjectKey(['moment'])
```
and return on https://github.com/umijs/qiankun/blob/069fe04e42/src/sandbox/proxySandbox.ts#L231-L241

## Context

- **qiankun Version**: 2.4.4
- **Platform Version**: macos 10.15.3
- **Browser Version**: Chrome Version 92.0.4515.107

**Comment by XingMXTeam** [comment]
就版本的qiankun能保证proxy.moment总是返回同一个对象
![image](https://user-images.githubusercontent.com/21259628/127279206-dc4218a1-68b5-48f5-b558-36f46c1ef909.png)

最新版本
![image](https://user-images.githubusercontent.com/21259628/127279445-754c684d-5d22-4626-9d45-08eaf61ba495.png)
