### ISSUE TITLE
子应用使用 window.onhashchange 事件无效

### ISSUE THREAD

**Issue by qiang47199** [umijs/qiankun#1602]
## 问题
我在子应用使用 window.onhashchange 事件无效，最终发现我在子应用打印 window 对象是一个proxy代理的。
如何可以在子应用下使用正常的window对象？拜托帮忙回复下🙏。

![image](https://user-images.githubusercontent.com/42257790/127087043-34794eb2-02e5-44c6-be75-03f08bc54420.png)

## 最小可复现仓库
无

## 相关环境信息
qiankun：v2.4.0
浏览器：Chrome v91+
操作系统：Mac v10.15.3

**Comment by qiang47199** [comment]
这个问题可以使用 addEventListener 去解决，但是如果就是想用 window.onxx 事件有办法解决？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/193#issuecomment-575967642 因为 onhashchange 没有写回到 window，所以无效。

类似问题 https://github.com/umijs/qiankun/issues/1575

**Comment by qiang47199** [comment]
@gongshun 3Q
