### ISSUE TITLE
主应用是hash模式，微应用是history模式，路由怎么配

### ISSUE THREAD

**Issue by jojo-1995** [umijs/qiankun#1603]
## What happens?

主应用是hash模式，微应用是history模式，路由配置错误,activeRule

## 最小可复现仓库

/* qiankun */
import { registerMicroApps, start } from 'qiankun';
const getActiveRule = (hash) => (location) => location.hash.startsWith(hash);
registerMicroApps([
  {
    name: 'vueApp',
    entry: process.env.NODE_ENV == 'development'? '//localhost:8086/exp/' : `https://m-${process.env.BUILD_ENV.toLowerCase()}.ecosaas.com/exp/`,
    container: '#vueContainer',
    activeRule: '/life/vue',
    // activeRule: getActiveRule('#/life/vue'),
    props: {a:router}
  }

## 相关环境信息

- **qiankun 版本**：2.4.3
- **浏览器版本**：谷歌最新
_**ui框架：vant

**Comment by gongshun** [comment]
https://juejin.cn/post/6856569463950639117#heading-23

**Comment by jojo-1995** [comment]
> https://juejin.cn/post/6856569463950639117#heading-23
谢谢

**Comment by xiehuicc** [comment]
请问解决了吗？我也遇到了类似的问题，主应用是hash模式，微应用是history路由模式，进入微应用时，静态资源都成功加载到了，但是微应用显示空白，感觉是微应用内的路由没有匹配上，不知道怎么解决。
