### ISSUE TITLE
有一个问题，针对qiankun的样式是推荐隔离还是共享（团队约束全局样式的写法）

### ISSUE THREAD

**Issue by jojo-1995** [umijs/qiankun#1604]
## What happens?

start({sandbox: {experimentalStyleIsolation: true}}) 模式1
start({sandbox: {strictStyleIsolation:true}});  // 模式2
start({sandbox: {strictStyleIsolation:false}});  // 模式3

## 相关环境信息

- **qiankun 版本**：2.4.3
- **浏览器版本**：谷歌最新

**Comment by jojo-1995** [comment]
> Hello @jojo-1995. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @jojo-1995, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

你好 我描述的很明确
遇到的问题就是 在start({sandbox: {experimentalStyleIsolation: true}}) 模式下，vant的这个日历组件没有挂在body下，否则样式会失效，然后出现了主应用遮挡了子应用弹窗的情况，请问怎么解决

**Comment by gongshun** [comment]
推荐隔离，隔离的问题少，共享的问题多
