### ISSUE TITLE
主应用为vue2  子应用为umi3，主应用控制子应用路由切换 页面不渲染

### ISSUE THREAD

**Issue by fzz14hao** [umijs/qiankun#1608]
问题：主应用为vue2  子应用为umi3，主应用控制子应用路由切换 页面不渲染

问题描述：
主应用有一个通用的菜单，点击菜单切换到子应用的不同页面；
子应用使用vue2 路由为hash，主应用能正常控制子应用的页面切换。
子应用使用umi3 路由为hash，主应用控制只要页面路由 页面不会渲染，子应用单独打开页面能正常切换

请问主应用使用什么方法可以控制子应用的路由达到页面的切换效果呢？

## 相关环境信息
主应用
"qiankun": "^2.0.22",
  "vue": "^2.6.11",
子应用
 "umi": "^3.5.0",

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1536
