### ISSUE TITLE
启用乾坤后页面展示有问题,在访问子页面是上方有loading,下滑页面才是真实页面,效果如图

### ISSUE THREAD

**Issue by XinYueXiao** [umijs/qiankun#1609]
![image](https://user-images.githubusercontent.com/31272499/127290906-c52d3234-066e-4b2f-bfe0-5a1534ed6367.png)

完整的代码在
https://github.com/blueju/umi-qiankun/tree/umi-micro-fe-platform

**Comment by XinYueXiao** [comment]
![image](https://user-images.githubusercontent.com/31272499/127291087-098384c4-6cf7-43fe-8369-90450f470bf6.png)
https://user-images.githubusercontent.com/31272499/127291087-098384c4-6cf7-43fe-8369-90450f470bf6.png

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1217#issuecomment-766663132
