### ISSUE TITLE
你好，请问假如用于承载子应用的的容器中，container不是某个id，而希望是router-view的右边展示部分如何写呢

### ISSUE THREAD

**Issue by Yelixing** [umijs/qiankun#1614]
真诚请教，你好，请问加入用于承载子应用的的容器中，container不是某个id，而希望是router-view的右边展示部分如何写呢

**Comment by gongshun** [comment]
https://github.com/gongshun/qiankun-vue-element-admin

**Comment by xuebigshuai** [comment]
hash模式下怎么实现

**Comment by xuebigshuai** [comment]
我在hash模式下可以将子应用加载到框架内，但子应用的路由跳转会出现问题
