### ISSUE TITLE
按照作者的例子，启动qiankun，vue3的项目报错了Failed to fetch in zone.js

### ISSUE THREAD

**Issue by xuelei4122** [umijs/qiankun#1615]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
Failed to fetch 就是 vue3 子应用没运行起来，是不是有报错？

**Comment by xuelei4122** [comment]
对不起啊。可能是运行先后的问题。我重启下服务可以了。十分感谢

**Comment by xuelei4122** [comment]
对不起啊。可能是运行先后的问题。我重启下服务可以了。十分感谢
