### ISSUE TITLE
微应用是vue-cli2搭建的，main.js导入了qiankun的生命周期，webpack已经配置umd格式，主应用报错找不到qiankuan导出的方法

### ISSUE THREAD

**Issue by jojo-1995** [umijs/qiankun#1616]
## What happens?
微应用是vue-cli2搭建的，main.js导入了qiankun的生命周期，主应用报错找不到qiankuan导出的方法
![微信图片_20210729191423](https://user-images.githubusercontent.com/24888623/127482701-cca191a1-8004-41c5-b2c4-a7debeee812c.png)
![微信图片_20210729191427](https://user-images.githubusercontent.com/24888623/127482712-7427a8b2-7f0b-4278-92cc-9dc07fd672aa.png)
![微信图片_20210729191430](https://user-images.githubusercontent.com/24888623/127482777-82a72e83-3f26-4ecc-9f12-c9f9519d9a2e.png)

## 相关环境信息

- **qiankun 版本**：2.4.3
- **浏览器版本**：谷歌最新

**Comment by gongshun** [comment]
https://www.cnblogs.com/fengsaoke/p/14628997.html

**Comment by jojo-1995** [comment]
> https://www.cnblogs.com/fengsaoke/p/14628997.html

配置后 发到线上报错了

![q](https://user-images.githubusercontent.com/24888623/127611492-26cd6b72-5f99-4daf-b063-2aa7e838a022.png)
![w](https://user-images.githubusercontent.com/24888623/127611498-a6eec559-6afb-4013-9eca-4eafeda39e6d.png)
