### ISSUE TITLE
[Bug]版本问题

### ISSUE THREAD

**Issue by liyugang** [umijs/qiankun#1617]
## What happens?

使用的qiankun版本2.4.5，网站打开f12，切换路由时，加载资源会pending很久，网页加载非常慢。
关闭f12恢复正常。
qiankun切到上一版本也恢复正常。

## 相关环境信息

- **qiankun 版本** 2.4.5
- **浏览器版本**：windows10
- **操作系统**：chrome 91.0.4472.124

**Comment by gongshun** [comment]
请求 pending 不是你的网络问题吗？

**Comment by liyugang** [comment]
不是哦，浏览器关掉f12马上就好了，或者qiankun切换回上一版本也没问题了
而且只出现在chrome里，火狐、safari都不会出现这个问题

**Comment by gongshun** [comment]
你用chrome的隐身模式看看

**Comment by liyugang** [comment]
chrome的隐身模式和正常模式表现一样

**Comment by 86driver** [comment]
俺也一样， 怎么说吧， 我今天晚上还要下班吗

**Comment by 86driver** [comment]
占个楼，  @liyugang     看改动看不懂- -    有解决了麻烦@我一下

**Comment by liyugang** [comment]
@86driver 改回之前版本就好了，暂时锁定到之前版本了，没有用2.4.5最新版本
