### ISSUE TITLE
antd pro 5主应用引用antd pro5子应用，页面一直loading

### ISSUE THREAD

**Issue by kevinpursuing** [umijs/qiankun#1618]
## What happens?

antd pro 5主应用引用antd pro5子应用，页面一直loading

## How To Reproduce

1. 初始化APP1(antd pro 5),在config.ts中配置 ,内容如下
 qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'test', // 唯一 id
          entry: 'http://localhost:8001', // html entry
        },
      ],
      sandbox: { strictStyleIsolation: true, experimentalStyleIsolation: true },
    },
  },
2.调整APP1路由
{
    name: 'test',
    icon: 'table',
    path: '/test',
    microApp: 'test',
  },
3. 初始化SUB_APP1在config.ts中配置 ,内容如下
qiankun: {
    slave: {},
}
4. 在主应用渲染子应用，出现loading
![image](https://user-images.githubusercontent.com/20419163/127609564-77192283-0b78-4734-9cc1-7651933a0e3a.png)

- **qiankun Version**:
 主应用："@umijs/plugin-qiankun": "^2.27.0",
 子应用："@umijs/plugin-qiankun": "^2.27.0",
- **Platform Version**:
 主应用： "name": "ant-design-pro", "version": "5.0.0",
 子应用： "name": "ant-design-pro", "version": "5.0.0",
- **Browser Version**:
  MAC chrome 版本 91.0.4472.164（正式版本） (x86_64)

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1609 重复
