### ISSUE TITLE
died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in vue app entry

### ISSUE THREAD

**Issue by CHU295** [umijs/qiankun#162]
当我自己新建了一个vue项目来引用example里面的子项目的时候，遇到了这个报错。
Uncaught vue app: Application 'vue app' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in vue app entry
看项目报错说子项目缺少生命周期，但子项目来自example，在example main里面运行正常。
使用到我自己新建的项目即报错。

`import fetch from 'isomorphic-fetch';
import Vue from 'vue'
import { registerMicroApps, start, runAfterFirstMounted, setDefaultMountApp } from 'qiankun';
import Framework from './App';

let app = null;

function render({ appContent, loading }) {
  // const container = document.getElementById('container');
  // ReactDOM.render(<Framework loading={loading} content={appContent} />, container);

  if (!app) {
    app = new Vue({
      el: '#app',
      data() {
        return {
          content: appContent,
          loading,
        };
      },
      render(h) {
        return h(Framework, {
          props: {
            content: this.content,
            loading: this.loading,
          },
        });
      },
    });
  } else {
    app.content = appContent;
    app.loading = loading;
  }
}

function genActiveRule(routerPrefix) {
  return location => location.pathname.startsWith(routerPrefix);
}
const request = url =>
  fetch(url, {
    referrerPolicy: 'origin-when-cross-origin',
    // mode: "no-cors",
  });

registerMicroApps(
  [
    {
      name: 'vue app', // app name registered
      entry: '//localhost:7101',
      render,
      activeRule: genActiveRule('/vue'),
    },
  ],
  {
    beforeLoad: [
      app => {
        window.console.log('before load', app);
      },
    ],
    beforeMount: [
      app => {
        window.console.log('before mount', app);
      },
    ],
    afterUnmount: [
      app => {
        window.console.log('after unload', app);
      },
    ],
  },
  {
    fetch: request,
  });
setDefaultMountApp('/vue');
runAfterFirstMounted(() => window.console.info('first app mounted'));

start({ prefetch: true, fetch: request });`

- **Platform**: Windows 1909 64位
- **Browser Version**:Chrome 78.0.3904.108
- **Node Version**:v12.13.1

**Comment by kuitos** [comment]
参考最新 demo
