### ISSUE TITLE
使用默认的examples打包部署

### ISSUE THREAD

**Issue by misskter** [umijs/qiankun#1621]
## Background

我在使用examples里面的项目编译部署的时候，执行npm run build 命令后，在dist目录中没有index.html文件。如果我正常运行的话是可以运行的。

## Proposal

我的建议是既然官网给出了一个演示的demo环境，所以尽量不要有副作用，不管是运行还是编译部署都可以得到正确的结果，即使说我拿你这个项目直接开搞也可以。这样在某种意义上降低开发人员的成本。

**Comment by kuitos** [comment]
examples 里哪一个 build 后没有 index.html？麻烦问题描述清楚

**Comment by misskter** [comment]
就是qiankun这个项目没有打出来一个Index.html 其他的项目均可以。

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/128127307-5062ff14-4ee7-401d-ba90-38c9e217125f.png)
随便找了一个
