### ISSUE TITLE
2.4.5执行examples:install 报错

### ISSUE THREAD

**Issue by margintopt** [umijs/qiankun#1622]
## What happens?
![image](https://user-images.githubusercontent.com/30163907/127734850-feb8c0d6-15ba-4136-97d0-8b5661d8d1d3.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 
1. npm i
2. npm run examples:install

## Context

- **qiankun Version**: 2.4.5
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
用 yarn ，别用npm
![image](https://user-images.githubusercontent.com/29347231/127760624-c25df81e-ef65-4715-841f-746d6bdeffa5.png)

**Comment by madaoLi666** [comment]
used yarn, met same problem
can not find index.d.ts in node_module/history
history's version is 4.10.1
can do examples:install when I commented  gulp-release error throw out
