### ISSUE TITLE
[help] 非vue-cli搭建的vue微应用应当如何改造？

### ISSUE THREAD

**Issue by in-vane** [umijs/qiankun#1623]
## What happens? 

微应用是非vue-cli创建的vue项目，使用webpack4。在根据qiankun文档改造后，报错 You need to export lifecycle functions in [micro-app-name] entry.
在issue里找到了类似的情况：https://github.com/umijs/qiankun/issues/115
翻阅文档，尝试了文档里提到的各种处理方式，都未能奏效。

所以想问一下vue的微应用一定要vue-cli搭建吗？如果不是的话vue微应用应该如何改造？

**Comment by gongshun** [comment]
vue-cli 只是 webpack 的二次封装，本质还是 webpack 构建的

**Comment by in-vane** [comment]
> vue-cli 只是 webpack 的二次封装，本质还是 webpack 构建的

好，我再试试嗷

**Comment by gongshun** [comment]
是否已解决，如果还不能解决，提供复现仓库，然后 reopen
