### ISSUE TITLE
can't find __POWERED_BY_QIANKUN__

### ISSUE THREAD

**Issue by hoho2017** [umijs/qiankun#1634]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:    "qiankun": "^2.4.6",
- **Platform Version**:    项目是umi项目
- **Browser Version**:     谷歌浏览器

**Comment by hoho2017** [comment]
registerMicroApps([
      {
        name: 'reactApp',
        entry: '....',
        container: '#micro',
        activeRule: '/app-react',
      },
    ]);
    // 启动 qiankun
    console.log(window.__POWERED_BY_QIANKUN__);//打印为undefined???
//如上代码，主应用里面打印__POWERED_BY_QIANKUN__是undefined，百思不得其解，就几行代码我也不知道哪错了，求救

**Comment by hoho2017** [comment]
somebody help me please!（救救孩子吧）

**Comment by hoho2017** [comment]
给点思路也行

**Comment by Cygra** [comment]
@hoho2017 `window.__POWERED_BY_QIANKUN__` 的 `window` 是**子应**用的 `window`，主应用和子应用之间、子应用和子应用之间的 `window` 是相互隔离的。所以主应用里面打印 `__POWERED_BY_QIANKUN__` 当然是 `undefined` 啦。

`__POWERED_BY_QIANKUN__` 的作用是让**子应用**能识别出当前是独立运行还是运行在微应用环境中。

可以看一下 https://github.com/umijs/qiankun/blob/master/src/addons/engineFlag.ts

**Comment by hoho2017** [comment]
> @hoho2017 `window.__POWERED_BY_QIANKUN__` 的 `window` 是**子应**用的 `window`，主应用和子应用之间、子应用和子应用之间的 `window` 是相互隔离的。所以主应用里面打印 `__POWERED_BY_QIANKUN__` 当然是 `undefined` 啦。
> 
> `__POWERED_BY_QIANKUN__` 的作用是让**子应用**能识别出当前是独立运行还是运行在微应用环境中。
> 
> 可以看一下 https://github.com/umijs/qiankun/blob/master/src/addons/engineFlag.ts

好像是我子应用写的有问题。。。我再看看
