### ISSUE TITLE
提取公共依赖后,子应用单独运行没问题，在qiankun中出现错误

### ISSUE THREAD

**Issue by sewth** [umijs/qiankun#1637]
![image](https://user-images.githubusercontent.com/21299462/128479613-f6563e0f-c272-4f0c-b858-8465d4f13255.png)
使用cdn引入一些公共模块，链接放在index.html中，在本地调试没问题，打包后子应用单独使用也没问题，不过在qiankun中加载后出现一些错误。
![image](https://user-images.githubusercontent.com/21299462/128479980-cc744975-fdc9-42a4-b7f2-dbb6c6bd2c61.png)
debugger后发现proxy没有正确生成。
![image](https://user-images.githubusercontent.com/21299462/128480184-ff921caa-00ad-476a-9a5f-4051d5ff460f.png)
![image](https://user-images.githubusercontent.com/21299462/128480241-7d5e9839-0ab6-4ea4-a78d-9ef49cb93dd4.png)

**Comment by sewth** [comment]
查到了 主应用也必须将vue同样设置成cdn方式

**Comment by gongshun** [comment]
> 查到了 主应用也必须将vue同样设置成cdn方式

主应用不配置 external 也是可以的，你可以提供个 demo 看一下
