### ISSUE TITLE
[Bug] 微应用第一次退出后第二次无法进入

### ISSUE THREAD

**Issue by SOVLOOKUP** [umijs/qiankun#1638]
# 微应用第一次退出后第二次无法进入

## What happens?

微应用第一次退出后第二次无法进入

## 最小可复现仓库

https://github.com/graph-analysis/LingThink/tree/2c0dbbda3470770695c89efab8a12a6917317d02

## 复现步骤，错误日志以及相关配置

1. `yarn dev` 启动项目进入主页

2. 点击跳转到微应用
![image](https://user-images.githubusercontent.com/53158137/128531430-b640efe8-6d0c-4f76-aa79-8b075ef035ae.png)

3. 点击浏览器返回按钮回到主页，这时候会有 warning
![image](https://user-images.githubusercontent.com/53158137/128531568-7323adb3-2739-4e71-8d70-fa1e4f931f7b.png)

4. 再次点击跳转到微应用，这时不能正常进入了
![image](https://user-images.githubusercontent.com/53158137/128531663-1f5d7d2b-9882-415f-992d-74aaade62ee7.png)

5. 如果这时点击浏览器刷新按钮则能正常加载微应用

## 相关环境信息

- **qiankun 版本** 2.4.6
- **浏览器版本**：版本 92.0.4515.107（正式版本）Arch Linux （64 位）
- **操作系统**：Manjaro

**Comment by gongshun** [comment]
点击浏览器返回，相当于离开当前页面，离开当前页面需要卸载子应用，否则就会出现你这个问题。

https://github.com/umijs/qiankun/pull/1625/files 这个PR导致的
