### ISSUE TITLE
vue的动态获取路由的子项目，第二次进入子应用页面不渲染

### ISSUE THREAD

**Issue by 414022688** [umijs/qiankun#1645]
子应用路由全部是动态获取添加的  在router.beforeEach里面通过异步获取 然后通过router.addRoutes()  	next({ ...to, replace: true }) 动态添加路由，第一次进入子应用跳转都正常，  从子应用跳转回主应用 再重新从主应用点击导航新进入子应用的之前添加的动态路由，页面就不渲染了 ，url会变 但就是不渲染，一直在最后打开的一个路由

**Comment by Huanghao-xm** [comment]
子路由问题

**Comment by xiachenghu** [comment]
楼主，请问问题解决了吗？  我也遇见相同的问题，子应用跳回主应用，再跳转到子应用，子应用展示的页面始终是最后一次打开的应用页面。

**Comment by liuye1296** [comment]
我之前也遇到过  已解决，当时没记录怎么解决  大概记得是   vue3 卸载的时候 手动关闭 history  ， mount 的时候 vue Router  需要重新加载，

**Comment by xiachenghu** [comment]
@liuye1296  感谢大神提供的方法，问题已经解决。  子应用卸载时router置空，重新挂载时router再重新加载。

**Comment by 905868332** [comment]
> 我之前也遇到过 已解决，当时没记录怎么解决 大概记得是 vue3 卸载的时候 手动关闭 history ， mount 的时候 vue Router 需要重新加载，

我重新加载了，但是还是不行
