### ISSUE TITLE
同一个页面手动加载多个微应用报错

### ISSUE THREAD

**Issue by jianwenjuan** [umijs/qiankun#1654]
基座使用的react框架，采用函数组件编写，一个页面加载多个微应用，如果间隔较长时间分别加载微应用是没有问题，但同时加载时就会报错

不同时间加载出来的子应用：
![image](https://user-images.githubusercontent.com/22387830/129536626-22a0655c-d836-429a-9f8c-2d4a9ed33ce9.png)

如果切换界面后，再回到这个页面，同时加子应用就会报错：
![Screenshot 2021-08-16 164208](https://user-images.githubusercontent.com/22387830/129536218-4ad02960-5d33-4998-9aa0-5c6373a865ae.png)

![image](https://user-images.githubusercontent.com/22387830/129536768-ec6f5cb2-9b80-4c58-b8fa-a84ff1148e0b.png)

加载子应用的代码如下：
![image](https://user-images.githubusercontent.com/22387830/129536854-c26bfea0-9070-4a7d-8cc3-0d5e47c2be1d.png)

请问是否有使用错误呢？

- **qiankun Version**: 2.4.6
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
> 如果切换界面后，再回到这个页面，同时加子应用就会报错

切换页面，应该要卸载已加载的子应用

**Comment by haitaodesign** [comment]
复现demo: bf755ed8bc81cb2157fb9a96a5fb25fa8641fd48

![image](https://user-images.githubusercontent.com/14287992/130071597-b7a346a8-717a-401f-8da3-f5515f573163.png)

**Comment by haitaodesign** [comment]
临时处理方案：
1. 升级版本到 2.4.5，2.4.6之后会出现问题
2. 修改微组件手动加载逻辑，组件生命周期内销毁微组件实例

**Comment by jianwenjuan** [comment]
> > 如果切换界面后，再回到这个页面，同时加子应用就会报错
> 
> 切换页面，应该要卸载已加载的子应用 #1638 应该是同一个问题

离开页面时卸载了子应用，就没有这个报错了

**Comment by jianwenjuan** [comment]
离开页面时卸载了子应用，就没有这个报错了

**Comment by freshhu** [comment]
@jianwenjuan 请教一下一个页面加载多个微应用这个demo怎么实现的，能不能发一下您的github这个项目链接，万分感谢。
