### ISSUE TITLE
[help]关于主应用和子应用部署在不同服务器上，子应用请求对应后端服务的问题

### ISSUE THREAD

**Issue by lele4818** [umijs/qiankun#1656]
主应用和子应用部署在不同服务器上，通过官方的文档，前端文件资源可以请求到
![image](https://user-images.githubusercontent.com/41048724/129663051-742300bc-51fa-4632-82b1-943b6ce7f7a3.png)

子应用的后端服务，通常在每个子应用部署的服务器上有对应的nginx配置，代理其后端服务，但是主应用加载了子应用后 ，子应用访问不到其对应后端服务（主应用的服务器上没有子应用的nginx后端服务的代理配置，也不知道子应用的配置文件），这种情况下，子应用如何请求其后端服务呢？还是说主应用的nginx配置文件中必须包含子应用的后端服务代理配置呢？

**Comment by gongshun** [comment]
子应用的请求需要使用完整 url，不能使用相对路径。如果非要用相对路径，需要由主应用配置代理
