### ISSUE TITLE
angular为基座 umi为子项目如何接入

### ISSUE THREAD

**Issue by margintopt** [umijs/qiankun#1657]
## 背景

https://github.com/umijs/umi-plugin-qiankun/tree/master/examples 这里的都是主子都为umi项目且使用的都是@umijs/plugin-qiankun的插件

有没有在主项目中使用原生qiankun的方式，使用这种方式的话umi的子项目要如何配置呢

**Comment by gongshun** [comment]
类似问题 https://github.com/umijs/qiankun/issues/1536 。

demo里面的子应用 https://github.com/umijs/umi-plugin-qiankun/tree/master/examples/app1，可以直接被原生qiankun 主应用接入
