### ISSUE TITLE
开启沙箱模式后，子应用使用element-ui的日历组件点击会闪动消失

### ISSUE THREAD

**Issue by lovedaan** [umijs/qiankun#1659]
## 开启沙箱模式后，子应用使用element-ui的日历组件点击会闪动消失，不能正常显示
子应用就是正常引用element-ui，独立运行的时候是没问题的，但是聚合到主应用，主应用开启沙箱模式，点击子应用的日历组件会闪动，先是显示日历面板然后就很快消失

## 相关环境信息

- **qiankun 版本**： 2.4.4
- **element-ui版本**：2.15.3
- **浏览器版本**：谷歌浏览器
- **操作系统**：win10

**Comment by gongshun** [comment]
已知的问题，https://github.com/umijs/qiankun/issues/1316

**Comment by lovedaan** [comment]
文本框获得焦点，date-picker面板会闪动然后马上消失，不知道什么原因，审查元素看date-picker元素被添加到父应用的body同层，但是即使我代理document.body的appendChild方法到子应用的容器内，还是有这个闪动问题
