### ISSUE TITLE
子应用获取到props里面的值不是最新的

### ISSUE THREAD

**Issue by AllenForward** [umijs/qiankun#1660]
## What happens?

![image](https://user-images.githubusercontent.com/20220665/129832177-b583c064-fc02-4db7-84a7-566c7e06bb44.png)

我在主应用通过接口获取到微应用列表后调用registerMicroApps方法注册微应用

const microApps = apps.map((item) => ({
            name: item.appId,
            entry: item.url,
            container: item.container,
            activeRule: item.activeRule,
            props: {
              token,
              userInfo
            }
          })) 

 registerMicroApps(microApps);

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

首次进入子应用获取到的token没问题,此时退出登录主应用重新注册微应用,再次进入子应用获取到的token还是首次注册微应用传入的token值,不是最新的.

**Expected behavior** 1. 2.
每次重新注册子应用后再进入子应用获取到的props是最新的.

## Context

- **qiankun Version**: 2.4.7
- **Platform Version**: Mac
- **Browser Version**: Chrome 92

**Comment by gongshun** [comment]
目前不支持重新注册，会跳过已注册的子应用（按照name判断），主应用把 token 直接挂在 window 上，子应用就能直接读取到。如果要用props传递，需要用 initGlobalState。
