### ISSUE TITLE
按照文档编辑qiankun配置，遭遇生命钩子丢失，样式丢失问题

### ISSUE THREAD

**Issue by codePorter92** [umijs/qiankun#1661]
您好，工作中发现使用乾坤的一些难处理的问题，恳请大佬们帮个忙
1。新增功能和编辑功能，loadMicroApp引入同一个子应用在不同的页面中，当点击编辑弹出子应用，卸载之后，点击新增功能弹起子应用，子应用显示生命周期的钩子不存在的报错，
2.   loadMicroApp加载中， 同一个功能多次展示子应用，子应用一开始存在样式，之后子应用的样式丢失，
3.   loadMicroApp 清理缓存的时候，unmount卸载之后，再次点击，缓存仍然存在

主应用地址  https://gitee.com/tompan92/angular-micro-main.git  （src\app\widget\schema-micro新增功能   src\app\widget\schema-micro-edit编辑功能 ）
子应用地址  https://gitee.com/tompan92/react-micro.git （index.ts中存在qiankun配置）

qiankun   版本：2.4.3
Chrome   版本:   92.0.4515.131
操作系统  window10

**Comment by gongshun** [comment]
demo 无法运行，需要提供一个简洁的 demo

**Comment by CodeSteppe** [comment]
@codePorter92 你好，我也遇到了同样的问题，请问后来有解决嘛？
