### ISSUE TITLE
[Bug] 基座 调用window.location.reload(); 新窗口的子应用不刷新

### ISSUE THREAD

**Issue by xuergo** [umijs/qiankun#1663]
我不知道这是不是一个问题 当我在主应用调用 window.location.reload();  位于新窗口的子应用无法刷新页面 是我使用错误吗？

**Comment by gongshun** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Location/reload

window.location.reload() 刷新的是当前窗口，新窗口的内容咋会被刷新
