### ISSUE TITLE
如果主应用是不支持 import 模块导入的旧应用，是不是就不能使用「乾坤」

### ISSUE THREAD

**Issue by wungjyan** [umijs/qiankun#1665]
没找到相关资料，是在主应用上非 import 的方式来引用 `qiankun` 的。

希望官方可以解惑下，如果我的主应用不支持 import 的方式，可以使用乾坤吗？

谢谢！

**Comment by HongjiangHuang** [comment]
qiankun支持打包umd. 所以是支持的.

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1147
