### ISSUE TITLE
clone代码之后，执行yarn install正常，再执行yarn examples:install报错

### ISSUE THREAD

**Issue by 156586197** [umijs/qiankun#1673]
Build umd
×  error     Error: D:/source_code/qiankun/src/prefetch.ts(24,5): semantic error TS2717: Subsequent property declarations must have the same type.  Property 'requestIdleCallback' must be of type '(callback: IdleRequestCallback, options?: IdleRequestOptions | undefined) => number', but here has type '(callback: (deadline: RequestIdleCallbackDeadline) => void, opts?: RequestIdleCallbackOptions | undefined) => any'.

以上是报错信息。试过换npm命令，也是报相同的错。

**Comment by WestarkMFF** [comment]
同样问题

**Comment by 156586197** [comment]
报了一个新的错Error: Cannot find module '@babel/runtime/package.json' ;我的babel-runtime是7.10.5版本
