### ISSUE TITLE
父子应用都是hash模式，父应用是vue，菜单两个选项指向了同一个子应用（react）的路由，切换这两个菜单选项，路由会变化，但子应用界面不会刷新。子应用内部切换路由都是可以变化

### ISSUE THREAD

**Issue by chenqiangsuixin** [umijs/qiankun#1680]
![image](https://user-images.githubusercontent.com/13976968/131320782-a09fd29a-841f-4662-be2a-00b1887800fa.png)
这是vue主应用，这两个菜单都指向了同一个react的子应用，切换的时候，子应用不会界面变化
![image](https://user-images.githubusercontent.com/13976968/131320879-da539087-6d60-4958-878e-b398289d3692.png)
在线等，急

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1199

**Comment by ding991** [comment]
@chenqiangsuixin 请问下你是按照#1199的issue解决的吗？
