### ISSUE TITLE
[Bug]使用Angular8作为主应用，类型定义不兼容报错

### ISSUE THREAD

**Issue by hmilin** [umijs/qiankun#1688]
# 使用Angular8作为主应用，类型定义不兼容报错

## What happens?

在Angular8项目中引入qinakun，并注册子应用，报错信息如下：

ERROR in node_modules/qiankun/es/apis.d.ts(1,13): error TS1005: '=' expected.

Angular8使用的是typescript3.5.x，import type 需3.8以上版本才支持。

## 最小可复现仓库

https://codesandbox.io/s/cool-driscoll-k3dcb

## 复现步骤，错误日志以及相关配置

执行yarn start

ERROR in node_modules/qiankun/es/apis.d.ts(1,13): error TS1005: '=' expected.
node_modules/qiankun/es/apis.d.ts(1,33): error TS1005: ';' expected.
node_modules/qiankun/es/apis.d.ts(2,13): error TS1005: '=' expected.
node_modules/qiankun/es/apis.d.ts(2,105): error TS1005: ';' expected.
node_modules/qiankun/es/globalState.d.ts(5,13): error TS1005: '=' expected.
node_modules/qiankun/es/globalState.d.ts(5,43): error TS1005: ';' expected.
node_modules/qiankun/es/interfaces.d.ts(5,13): error TS1005: '=' expected.
node_modules/qiankun/es/interfaces.d.ts(5,38): error TS1005: ';' expected.
node_modules/qiankun/es/interfaces.d.ts(6,13): error TS1005: '=' expected.
node_modules/qiankun/es/interfaces.d.ts(6,67): error TS1005: ';' expected.
node_modules/qiankun/es/prefetch.d.ts(5,13): error TS1005: '=' expected.
node_modules/qiankun/es/prefetch.d.ts(5,38): error TS1005: ';' expected.
node_modules/qiankun/es/prefetch.d.ts(6,13): error TS1005: '=' expected.
node_modules/qiankun/es/prefetch.d.ts(6,52): error TS1005: ';' expected.

## 相关环境信息

- **qiankun 版本** ^2.4.10
- **浏览器版本**：
- **操作系统**：

**Comment by seujzhang** [comment]
怎么解决？

**Comment by zxllzw** [comment]
同样遇到了这个问题

**Comment by NK-DMZ** [comment]
这个怎么解决？
