### ISSUE TITLE
[Bug]子应用的html模板中的js代码中调用document.currentScript.dataset会报错

### ISSUE THREAD

**Issue by littledian** [umijs/qiankun#1689]
## What happens?

子应用的html模板中的js代码中调用document.currentScript.dataset会报错；

## 最小可复现仓库
https://github.com/littledian/qiankun-demo

## 复现步骤，错误日志以及相关配置
在根目录下启动主应用，进入子应用目录下启动子应用；查看主应用控制台就能看到报错；

## 相关环境信息

- **qiankun 版本**：任意版本即可
- **浏览器版本**：不限
- **操作系统**：不限

**Comment by littledian** [comment]
qiankun针对动态插入的js节点，会通过defineProperty设置document.currentScript，但是对于html模板中解析的模板没有设置这个值；
qiankun通过eval的方式来运行js节点的代码，导致document.currentScript的值一直是null，和浏览器运行js的行为不一致；

解决思路：在解析js的基础上保留当前js标签的内容，创建临时的js节点赋值document.currentScript能够解决这个问题；

**Comment by xxih** [comment]
我也遇到了这样的问题，我们的应用有应用 A 用 ModuleFederation 方式加载，应用 B 使用 qiankun 加载

应用 B 中因为有动态插入的 js 节点，通过 defineProperty 设置了 document.currentScript

应用 A 的资源加载依赖于 document.currentScript，先加载应用 B 就会导致应用 A 的加载错误
