### ISSUE TITLE
example 页面加载时控制台报错

### ISSUE THREAD

**Issue by CHU295** [umijs/qiankun#169]
拉取最新代码后报错
VM18914:155036 WebSocket connection to 'ws://localhost:7099/sockjs-node/698/gxczzlrn/websocket' failed: Error during WebSocket handshake: Unexpected response code: 200

VM18914:154938 POST http://localhost:7099/sockjs-node/698/czcmewt2/xhr_streaming?t=1574654053469 404 (Not Found)

EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

功能正常，在页面加载刷新时出现。
另外react16项目配置有问题，自定义配置中devServer open已经设置为false，但是在项目启动的时候会自动打开改服务网页

**Comment by kuitos** [comment]
需要 create-react-app 支持 https://github.com/facebook/create-react-app/pull/7750

**Comment by ChenYCL** [comment]
17react版本目前仍然有这个报错
![image](https://user-images.githubusercontent.com/25706676/113697110-5ca6d480-9705-11eb-8d89-e26052cda446.png)

**Comment by wangchun0020** [comment]
> 17react版本目前仍然有这个报错
> ![image](https://user-images.githubusercontent.com/25706676/113697110-5ca6d480-9705-11eb-8d89-e26052cda446.png)

有解决方案了吗

**Comment by ccysmd** [comment]
change scripts  ["start": "react-app-rewired start"] to ["start": "cross-env WDS_SOCKET_PORT=3000 react-app-rewired start"]
