### ISSUE TITLE
[enhancement] 乾坤处理子应用js、css能不能改成并行，而不是串行处理？

### ISSUE THREAD

**Issue by EraChen233** [umijs/qiankun#1694]
## What happens?

如下图，发现子应用的css和js不是同时发送请求的。
查了乾坤代码，发现是因为要拿到css文件后，`ScopedCSS`对样式增加前缀`div[data-qiankun="xxx"]`，处理完css才会处理js，发送请求拿js文件，然后`getExecutableScript`对js进行处理。

![image](https://user-images.githubusercontent.com/5961185/131983050-b97acd21-9a65-4f88-b5f8-13cd7c8737fc.png)

## EXPECTED

希望是并行处理的，减少耗时。微前端方案首屏打开时间太长了。

**Comment by chris-envas** [comment]
...这算哪门子优化呢?两个包子揉在一起吃和一个吃完接着吃下一个,难道进嘴消化不是等量的吗.又不是多台服务器...

**Comment by kuitos** [comment]
3.0 已支持
