### ISSUE TITLE
动态插入的<style>标签会被qiankun拦截？

### ISSUE THREAD

**Issue by margintopt** [umijs/qiankun#1699]
## What happens?
主应用angular11 子应用umi
开启严格模式ShadowDOM（使用experimentalStyleIsolation 也会出现）
1. 我发现先加载子应用后，再切换回angular，angular每个页面凡是涉及到styleUrls的动态插入的样式都不会在head中生成style标签，
2. 项目中的layout分别为主应用的header组件 和 加载子应用的body容器，我在header中有一个弹出框，弹出框上用到了`cdk-virtual-scroll`，其中的`.cdk-virtual-scroll-spacer`是动态插入的<style>标签中的一个样式，但这个style标签竟然神奇的插在了ShadowDOM（即子应用节点）中，从而导致我主应用的弹出框的样式缺失

但是上述情况都是子应用启用了umi-plugin才出现的，之前用的正常qiankun官网的react子应用模式，并未出现这个问题

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
![image](https://user-images.githubusercontent.com/29347231/132477602-ee4a809d-2dfe-4ee8-a080-bd4891fa1e20.png)

用这个可以逃出沙箱

**Comment by margintopt** [comment]
> ![image](https://user-images.githubusercontent.com/29347231/132477602-ee4a809d-2dfe-4ee8-a080-bd4891fa1e20.png)
> 
> 用这个可以逃出沙箱

可是我主应用ng中那么多页面 也不算静态资源 我怎么去配置这个asseturl呢

**Comment by margintopt** [comment]
我知道了 是因为我qiankun子应用没有卸载完毕 就切换了路由导致了被劫持
可是我原生react子应用配置是没有劫持的
是因为umi默认开启了劫持吗  这个东西可以关掉吗

**Comment by csu-feizao** [comment]
> ![image](https://user-images.githubusercontent.com/29347231/132477602-ee4a809d-2dfe-4ee8-a080-bd4891fa1e20.png)
> 
> 用这个可以逃出沙箱

css文件能够使用此方法解决，但是无法解决动态添加 style 标签，同此 issue https://github.com/umijs/qiankun/issues/2316
