### ISSUE TITLE
html-entry 中 inline script 在导入后被屏蔽了么？

### ISSUE THREAD

**Issue by eelogic** [umijs/qiankun#170]
Hi, 请问下我在尝试子项目用 qiankun html-entry 方式注册的时候，html 里有一些写到 window 对象的赋值语句，类似：
<script>
   var foo = { ... }
</script>
这段代码在导入之后是屏蔽掉，不会执行么？如果是的话，这类的语句用什么方式来转换比较好？这些代码是模板文件里根据 server 端获取内容生成的。

谢谢！

**Comment by kuitos** [comment]
不会，你可以用 examples 里 react15 的例子测试下

**Comment by EdenXY** [comment]
Hi，这个问题解决了吗？我也碰到了一样的问题
