### ISSUE TITLE
微前端模块复用，比如，我页面上，通过乾坤，加载了一个模块。模块需要在页面不同的地方多次渲染，只是数据不一样。这个乾坤能复用么

### ISSUE THREAD

**Issue by Topthinking** [umijs/qiankun#1702]
## What happens?

微前端模块，在一个页面上复用

举个例子：我在页面上，通过乾坤，加载了一个公共模块。该模块需要在当前页面，不同的地方多次渲染，只是传入的数据不一样。这个乾坤能做到么，或者说怎么做

## 相关环境信息

- **qiankun 版本**：2.4.10
- **浏览器版本**：chrome 90
- **操作系统**：mac

**Comment by gongshun** [comment]
https://juejin.cn/post/6856569463950639117#heading-25

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/134833880-df0915c5-484e-41fc-9ad0-bcf0efe42430.png)
当然可以啊
