### ISSUE TITLE
父运用下的子运用如何设置height:100%

### ISSUE THREAD

**Issue by lecd** [umijs/qiankun#1703]
测试代码截图如下：
![image](https://user-images.githubusercontent.com/17017158/132671413-67263ac8-247a-4ce9-9ed6-9ddeb9212dbb.png)

## 相关环境信息

- **qiankun 版本：2.4.10
- **浏览器版本：Microsoft Edge：版本 93.0.961.38 (官方内部版本) (64 位)
- **操作系统**：Windows 11 企业版 Insider Preview

**Comment by menghany** [comment]
[https://github.com/umijs/qiankun/issues/584](url)

div[id^='__qiankun_microapp_wrapper_'] {
  height: 100%;
}

**Comment by lecd** [comment]
> Duplicate of #584
> 
> [https://github.com/umijs/qiankun/issues/584](url)
> 
> `div[id^='__qiankun_microapp_wrapper_'] { height: 100%; }`

这个id是可以解决，它的上一个div，怎么解决呢？
![1631368589(1)](https://user-images.githubusercontent.com/17017158/132950336-2dd3648e-4a4c-4a27-ac0d-182e606f2a21.jpg)

**Comment by menghany** [comment]
> > Duplicate of #584
> > [https://github.com/umijs/qiankun/issues/584](url)
> > `div[id^='__qiankun_microapp_wrapper_'] { height: 100%; }`
> 
> 这个id是可以解决，它的上一个div，怎么解决呢？
> ![1631368589(1)](https://user-images.githubusercontent.com/17017158/132950336-2dd3648e-4a4c-4a27-ac0d-182e606f2a21.jpg)
我刚刚看了一下我这边的项目, 你画红线的这一行,我这边不存在,你检查看看是不是代码插入的dom有问题

**Comment by menghany** [comment]
> > Duplicate of #584
> > [https://github.com/umijs/qiankun/issues/584](url)
> > `div[id^='__qiankun_microapp_wrapper_'] { height: 100%; }`
> 
> 这个id是可以解决，它的上一个div，怎么解决呢？
> ![1631368589(1)](https://user-images.githubusercontent.com/17017158/132950336-2dd3648e-4a4c-4a27-ac0d-182e606f2a21.jpg)

我刚刚看了一下我这边的项目, 你画红线的这一行,我这边不存在,你检查看看是不是代码插入的dom有问题

**Comment by lecd** [comment]
> > > Duplicate of #584
> > > [https://github.com/umijs/qiankun/issues/584](url)
> > > `div[id^='__qiankun_microapp_wrapper_'] { height: 100%; }`
> > 
> > 
> > 这个id是可以解决，它的上一个div，怎么解决呢？
> > ![1631368589(1)](https://user-images.githubusercontent.com/17017158/132950336-2dd3648e-4a4c-4a27-ac0d-182e606f2a21.jpg)
> 
> 我刚刚看了一下我这边的项目, 你画红线的这一行,我这边不存在,你检查看看是不是代码插入的dom有问题

 我查看dom，并没发现问题
我使用的版本信息： 
 "@umijs/plugin-qiankun": "^2.31.1",
 "umi": "^3.5.0",
  "qiankun": "^2.4.10",
  "react": "^17.0.0",

**Comment by lecd** [comment]
> > > Duplicate of #584
> > > [https://github.com/umijs/qiankun/issues/584](url)
> > > `div[id^='__qiankun_microapp_wrapper_'] { height: 100%; }`
> > 
> > 
> > 这个id是可以解决，它的上一个div，怎么解决呢？
> > ![1631368589(1)](https://user-images.githubusercontent.com/17017158/132950336-2dd3648e-4a4c-4a27-ac0d-182e606f2a21.jpg)
> 
> 我刚刚看了一下我这边的项目, 你画红线的这一行,我这边不存在,你检查看看是不是代码插入的dom有问题

我查看dom，并没发现问题，qiankun 路由模式 自己插入进去这个div 的
我使用的版本信息：
"@umijs/plugin-qiankun": "^2.31.1",
"umi": "^3.5.0",
"qiankun": "^2.4.10",
"react": "^17.0.0",

**Comment by gongshun** [comment]
`main>div` 父子选择器可以选择

**Comment by lecd** [comment]
> `main>div` 父子选择器可以选择

谢谢 @gongshun
