### ISSUE TITLE
子应用静态资源路径错误

### ISSUE THREAD

**Issue by yhui02** [umijs/qiankun#1705]
## What happens?

主、子应用都是基于UMI，其中一个子应用的`umi.*.js, umi.*.css`加载时，会正常带上`publicPath`值，但数字开头的js文件（eg：`397.746d490b.async.js`）加载时，就不带`publicPath`了，导致无法加载。子应用的`publicPath`、`base`都已设置。尝试了无数种方法，也不行啊。

## Context

- **qiankun Version**: "@umijs/plugin-qiankun": "^2.30.0"
- **Platform Version**: Mac OS 11.5.2
- **Browser Version**:  Microsoft Edge 版本 92.0.902.84（Chromium）

**Comment by gongshun** [comment]
https://d.umijs.org/zh-CN/config#runtimepublicpath

**Comment by yhui02** [comment]
> https://d.umijs.org/zh-CN/config#runtimepublicpath

感谢！但这个试过了，不行，html里确实有`__webpack_public_path__ `这段，但就是不行，config所有相关参数都试过，也没解决，也换过qiankun旧一点的版本，都不行。目前用`dynamicImport: false`再将少量的文件直接移到根目录临时解决。

**Comment by gt-hans** [comment]
I've got the same issue, publicPath & runtimePublicPath doesn't work.

**Comment by NgeKaworu** [comment]
同样问题

**Comment by xh12** [comment]
我干了一个临时的解决方案，目前先跑着。期待有更好的方案，runtimepublicpath这个设置为true了，但是好像并没有啥用。 为在入口 /src/app.tsx 文件里面 开头设置了 __webpack_public_path__  为我的自己项目的 publicPath

**Comment by gongshun** [comment]
runtimepublicpath 这个设置为 true ，路径还是错的话，可能是因为 entry 写错了：https://github.com/umijs/qiankun/issues/915#issuecomment-688808361
