### ISSUE TITLE
手动在浏览器中输入子应用的url，显示页面未找到

### ISSUE THREAD

**Issue by feishikx** [umijs/qiankun#1708]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 
乾坤最新版本：
主应用和子应用正常启动后，基于 setDefaultMountApp('/v2');  url自动转向 /v2/login 页面，但是当在浏览器地址栏（保持当前URL）按enter后显示空白页页面提示：Cannot GET /v2/login （发出了 http://dev.***.net:7099/v2/login 请求，域名和端口都是主应用的）。手动切换到其他子应用的路由也同样（network中像主应用请求了对应的页面）

**Expected behavior** 1. 2.
正常跳转到对应的页面

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
> 在浏览器地址栏（保持当前URL）按enter后显示空白页页面

history 路由的应用，部署需要配置重定向，所有路径都返回 index.html
