### ISSUE TITLE
微前端应用可以只申请一个前端域名或者端口吗

### ISSUE THREAD

**Issue by snow-factory** [umijs/qiankun#1712]
就是我们团队使用乾坤的过程中，发现多个微前端应用会导致我们申请多个公网域名或者多个公网端口，但我们产品是要输出给客户的，客户不理解为啥会这样，觉得一个web应用就应该一个入口，部署到一个pod中。

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%9C%BA%E6%99%AF-1%E4%B8%BB%E5%BA%94%E7%94%A8%E5%92%8C%E5%BE%AE%E5%BA%94%E7%94%A8%E9%83%A8%E7%BD%B2%E5%88%B0%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8C%E4%B8%80%E4%B8%AA-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3
