### ISSUE TITLE
路由参数变更导致子应用页面重新加载，从而导致页面有闪屏现象

### ISSUE THREAD

**Issue by MrZhaoCn** [umijs/qiankun#1719]
问题：
一个基座+一个子应用，子应用某个页面的一个按钮操作会在url后面追加一些参数，当url变更后，页面又重新加载了，导致闪屏现象，独立运行子应用则不会出现这个问题。

比如一个路由：http://172.19.204.104:8081/#/clearSettle/settleManage/payablePage/index?filterData=%7B%7D  对应一个子应用的一个页面，当我点击这个页面上的一个按钮把路由变更为：http://172.19.204.104:8081/#/clearSettle/settleManage/payablePage/index?filterData=%7B%22managerCode%22%3A%22indirect_purchase%22%7D，这时候页面重新加载了，导致闪屏，但实际上点击操作只是在url后面追加了一些参数，页面仍然是同一个。

- **qiankun Version**: 2.4.10
- **Platform Version**: Vue 2.5.17, Vue router 3.0.1
- **Browser Version**: mac chrome  93.0.4577.82

**Comment by rfw** [comment]
@sanqi-med  解决了吗？怎么解决的？
