### ISSUE TITLE
主应用通过Link进行页面跳转，传递了query参数，在新页面的location中拿不到query信息

### ISSUE THREAD

**Issue by jenny520** [umijs/qiankun#1720]
![image](https://user-images.githubusercontent.com/16450022/133422030-e1afc504-d9d2-41bc-b250-83e024f5969f.png)

然后在详情页面，获取，打印this.props.location的值为
 {
    pathname: 'xxx',
    key: "h1tz4h333",
   pathname: "xxxx"
   search: ""
   state: undefined
}，缺少了query参数，导致在详情页拿不到数据

**Comment by Yan1** [comment]
> ![image](https://user-images.githubusercontent.com/16450022/133422030-e1afc504-d9d2-41bc-b250-83e024f5969f.png)
> 
> 然后在详情页面，获取，打印this.props.location的值为 { pathname: 'xxx', key: "h1tz4h333", pathname: "xxxx" search: "" state: undefined }，缺少了query参数，导致在详情页拿不到数据

请问解决了么
