### ISSUE TITLE
使用手动加载微应用返回出来的实例并没有update这个方法，但是文档里写的有

### ISSUE THREAD

**Issue by jianwenjuan** [umijs/qiankun#1732]
使用手动加载微应用，返回出来的实例没有update方法 
![image](https://user-images.githubusercontent.com/22387830/133743079-b5f26e80-c66e-4cfb-bfc8-fc093640f92f.png)

这是文档里写的
![image](https://user-images.githubusercontent.com/22387830/133743398-0cf3b22f-eefc-41e9-9be4-4f01cf80d3e5.png)

使用的qiankun版本是2.4.6

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/guide/getting-started#1-%E5%AF%BC%E5%87%BA%E7%9B%B8%E5%BA%94%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90

![image](https://user-images.githubusercontent.com/29347231/133748692-7e18fa6e-7915-44d5-b9f7-b6de400a19fe.png)

**Comment by ybbjegj** [comment]
导出了update, 也没有
