### ISSUE TITLE
官方文档

### ISSUE THREAD

**Issue by magicstf** [umijs/qiankun#1735]
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB
官方文档中这个问题中，下面tips说在qiankun最新版本中，qiankun在迭代，这个最新版本到底是哪个版本？是不是可以更精确一点？比如 1.x.x版本以后的版本？这个最新版本完全摸不着头脑。

**Comment by gongshun** [comment]
2.2版本就支持了
