### ISSUE TITLE
【建议】是否可以添加antd pro的demo

### ISSUE THREAD

**Issue by hqqxxf** [umijs/qiankun#174]
现在只有react antd的demo，没有antd pro的。
主要是不知道应该把bootstrap,mount钩子放到哪里，找不到入口文件

**Comment by kuitos** [comment]
antd pro 基于 umi 的，直接用对应的 umi plugin 就可以了 https://github.com/umijs/umi-plugin-qiankun

**Comment by hqqxxf** [comment]
但是我是想把antd pro项目和vue element项目放一起

**Comment by hqqxxf** [comment]
@kuitos 基于 umi-plugin-qiankun不支持vue项目，所以只能选择qiankun

**Comment by kuitos** [comment]
所以你的问题到底是 antd pro 怎么跑起来还是 vue 项目怎么跑起来。。

**Comment by hqqxxf** [comment]
https://github.com/hqqxxf/qiankundemo/tree/master/examples
这个例子里既有vue又有react，但就是antd pro不知道怎么跑

**Comment by kuitos** [comment]
antd-pro 项目作为子应用单独配 plugin 就可以了 https://github.com/umijs/umi-plugin-qiankun#%E5%AD%90%E5%BA%94%E7%94%A8

**Comment by wsdqr001** [comment]
> antd-pro 项目作为子应用单独配 plugin 就可以了 https://github.com/umijs/umi-plugin-qiankun#%E5%AD%90%E5%BA%94%E7%94%A8
用antd pro，子页面一直是loading状态，无法展示
