### ISSUE TITLE
老项目是php模版渲染的，服务是用docker 起的，以php项目为父应用，请问怎么配置。。求大佬帮助～

### ISSUE THREAD

**Issue by yujingxuan** [umijs/qiankun#1747]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by yujingxuan** [comment]
qiankun： v2.5
浏览器chrome
操作系统：MAC OS

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1147#issuecomment-754698527
