### ISSUE TITLE
vue子应用，用push方法跳转页面，然后再点主页面跳转会报错。

### ISSUE THREAD

**Issue by leiyangs** [umijs/qiankun#1750]
## What happens?
qiankun目前没有适配的一个问题，之前忘记提issue，今天来提一下。
vue子应用，用push方法跳转页面，然后再点主页面跳转会报错。改为replace不会报错，但浏览器后退按钮，没有记录
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
demo地址： https://github.com/leiyangs/qiankun-demo

## How To Reproduce

**Steps to reproduce the behavior:
1、点击vue子应用路由
2、点击主应用路由
3、报错
![lALPD2sQwXpADKFHzQO-_958_71](https://user-images.githubusercontent.com/16798581/134856885-801f106b-202e-4500-a198-d444b21d7d04.png)

**Expected behavior** 
正常跳转路由

## Context

- **qiankun Version**: 2.4.8
- **Platform Version**: Windows 10
- **Browser Version**:chrome 94.0.4606.61（正式版本

**Comment by kuitos** [comment]
vue3 的 router 跟 vue2 的 router 不兼容

**Comment by leiyangs** [comment]
> vue3 的 router 跟 vue2 的 router 不兼容

暂时有办法解决吗

**Comment by humorHan** [comment]
应该是router的问题？但是router issue没找到，请问楼主解决了吗？求教~

**Comment by HULIANGA** [comment]
可以试下在子应用里不配置router base，把base当做一级嵌套路由或者直接加载路由path前面

**Comment by leiyangs** [comment]
之前龚老师说，是因为还没有适配，改为replace不会报错可以暂时解决，但浏览器后退按钮，没有记录。因为没有深入研究，只到这里了！

**Comment by leiyangs** [comment]
@humorHan 看一下上面龚老师发的

**Comment by HULIANGA** [comment]
@leiyangs 我在你那个仓库创建了个pull request你可以看下，你这个问题产生的原因是router3和router4的state格式不一样，需要在router3版本的那一端加个afterEach自己修改下state内容。
还有另外一种场景的问题也分享下：主、子应用都是router4，进入子应用页面，再进入主应用页面，点击浏览器上的返回，会到404。这个情况是因为router4的push方法会先执行一个replaceState把当前路由地址添加进去，再执行pushState，因为同一个path在主应用和子应用去掉base之后路径是不一样的。解决办法是：子应用里不配置router base，把base当做一级嵌套路由或者直接加载路由path前面

**Comment by leiyangs** [comment]
@HULIANGA 太棒了，等我有空去看下，非常感谢

**Comment by humorHan** [comment]
> @humorHan 看一下上面龚老师发的

我们目前也是按照replaceState临时解决的，
ps：若若的问一句，龚老师是哪位？

**Comment by gongshun** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/1361

**Comment by aehyok** [comment]
> 主应用切换子应用的路由 子应用响应很慢才会切换

@gjfei  大佬 有解决吗

**Comment by gjfei** [comment]
> 

我也在找这个的解决办法

**Comment by daiwanxing** [comment]
> @leiyangs 我在你那个仓库创建了个pull request你可以看下，你这个问题产生的原因是router3和router4的state格式不一样，需要在router3版本的那一端加个afterEach自己修改下state内容。 还有另外一种场景的问题也分享下：主、子应用都是router4，进入子应用页面，再进入主应用页面，点击浏览器上的返回，会到404。这个情况是因为router4的push方法会先执行一个replaceState把当前路由地址添加进去，再执行pushState，因为同一个path在主应用和子应用去掉base之后路径是不一样的。解决办法是：子应用里不配置router base，把base当做一级嵌套路由或者直接加载路由path前面

谢谢，您的建议解决了我的痛点

目前我司的项目每个子应用的路由 base 都是以 `/mfe-xxx` 前缀做区分，而基座的 base 是 `/`，子应用内部用 `router.push` 跳转应用内页面，然后通过浏览器返回的时候由于 `router.push` 不会带上子应用的 `base`，所以浏览器的地址栏就是一个不带前缀的路由，然后在基座的 router 就会找不到这个路由，进而跳转到 404 了。

按你的建议，现在子应用去掉 base 后， 子应用的路由表的每个路由带上 `/mfe-xxx` 前缀，返回正常。
