### ISSUE TITLE
配置微应用的打包工具要求主子应用的name必须一致是为什么？尝试了名称不一致也可以正常运行

### ISSUE THREAD

**Issue by xiyuanyuan** [umijs/qiankun#1753]
### Discussed in https://github.com/umijs/qiankun/discussions/1752

<div type='discussions-op-text'>

<sup>Originally posted by **xiyuanyuan** September 28, 2021</sup>
各位大牛，想咨询下如下配置要求packageName在主应用中需要作为配置name。想了解下这么做的原因？
尝试了在一个主应用一个子应用的场景下，我胡乱写name也是没问题的。子应用可以被正常渲染和使用。
```js
const packageName = require('./package.json').name;

module.exports = {
  output: {
    library: `${packageName}-[name]`,
    libraryTarget: 'umd',
    jsonpFunction: `webpackJsonp_${packageName}`,
  },
};
```</div>

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/770 重复
