### ISSUE TITLE
react子应用使用useUrlState改变url的时候组件渲染两次

### ISSUE THREAD

**Issue by weeqe** [umijs/qiankun#1754]
点击一次add后 console.log打印了两次
子应用部分代码
```
const Test = () => {
  const [state, setState] = useUrlState({ count: '1' });
  console.log(1222)
  return (
      <>
        <button
            style={{ marginRight: 8 }}
            type="button"
            onClick={() => setState({ count: Number(state.count || 0) + 1 })}
        >
          add
        </button>
        <button type="button" onClick={() => setState({ count: undefined })}>
          clear
        </button>
        <div>state: {state?.count}</div>
      </>
  );
}
```
![image](https://user-images.githubusercontent.com/28505184/135078897-9f97afed-f755-430e-b7ee-6c0830901000.png)
仓库地址：https://github.com/weeqe/qiank

**Comment by gongshun** [comment]
同一个问题？ https://github.com/umijs/qiankun/issues/1423

**Comment by weeqe** [comment]
> 点击一次add后 console.log打印了两次 子应用部分代码
> 
> ```
> const Test = () => {
>   const [state, setState] = useUrlState({ count: '1' });
>   console.log(1222)
>   return (
>       <>
>         <button
>             style={{ marginRight: 8 }}
>             type="button"
>             onClick={() => setState({ count: Number(state.count || 0) + 1 })}
>         >
>           add
>         </button>
>         <button type="button" onClick={() => setState({ count: undefined })}>
>           clear
>         </button>
>         <div>state: {state?.count}</div>
>       </>
>   );
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/28505184/135078897-9f97afed-f755-430e-b7ee-6c0830901000.png) 仓库地址：https://github.com/weeqe/qiank
