### ISSUE TITLE
主应用hash路由跳转问题

### ISSUE THREAD

**Issue by coderhsx** [umijs/qiankun#1759]
主应用vue2+  hash路由   基于路由页面添加的微应用
微应用 react 16.8  hash路由
主应用挂载微应用后，在主应用点击跳转链接（该链接能匹配到微应用的某个路由），地址栏链接已改变，但微应用未监听到路由变化，导致页面没有正常切换

在微应用内部做路由跳转时，页面能正常跳转

 感觉就像是vue拦截了 hashchange 导致 react没有监听到变化而没有切换
 请问有大佬知道是怎么回事吗？ 希望能给萌新一些解决办法。

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1199#issuecomment-818740774

**Comment by jackieli123723** [comment]
同问

**Comment by coderhsx** [comment]
主应用使用  location.hash = path 进行hash替换，微应用能够监听到hash变化，从而正常跳转
