### ISSUE TITLE
[Bug] 文档地址都404了呀

### ISSUE THREAD

**Issue by ViavaCos** [umijs/qiankun#1776]
## What happens?
link not valid as below:
https://github.com/umijs/qiankun/blob/e90ca04d1309fb6d4b44449dd7fe8541fe840fe1/docs/faq/README.zh.md

such as:
https://github.com/umijs/qiankun/blob/e90ca04d1309fb6d4b44449dd7fe8541fe840fe1/zh/guide/getting-started#1-%E5%AF%BC%E5%87%BA%E7%9B%B8%E5%BA%94%E7%9A%84%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E9%92%A9%E5%AD%90

**Comment by gongshun** [comment]
文档有在线地址：https://qiankun.umijs.org/zh/faq，这里面的链接是相对路径，通过在线地址才能正确访问
