### ISSUE TITLE
主应用react，子应用angular7，zone一直在监听操作并进入死循环，导致页面很卡顿

### ISSUE THREAD

**Issue by daisymark** [umijs/qiankun#1782]
![Uploading image.png…]()

**Comment by thbor** [comment]
after i set sandbox as false,it does not print setTimout,and it works.

**Comment by thbor** [comment]
but i don't know why,if someone can answer me?

**Comment by thbor** [comment]
maybe you can try to set loose as true of sandbox,after qiankun2.2,singular has been changed to loose,it is useful for me
