### ISSUE TITLE
[Bug] React 17.x 无法安装

### ISSUE THREAD

**Issue by hihuangwei** [umijs/qiankun#1786]
npm 版本 8.1.0
node 版本 16.13.0

````
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: console@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16" from @umijs/plugin-qiankun@2.35.0
npm ERR! node_modules/@umijs/plugin-qiankun
npm ERR!   dev @umijs/plugin-qiankun@"^2.35.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

````

## 相关环境信息

- **qiankun 版本**:2.35.0
- **浏览器版本**：
- **操作系统**：

**Comment by smilebuz** [comment]
遇到了相同的问题，这里有解决吗

**Comment by liwei511** [comment]
直到1.39.2还不支持react17
`
{
  "name": "@umijs/plugin-qiankun",
  "version": "2.39.2",
  "description": "umi plugin for qiankun",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "scripts": {
    "start": "npm-run-all --parallel start:*",
    "start:master": "cd examples/master && umi dev",
    "start:app1": "cd examples/app1 && umi dev",
    "start:app2": "cd examples/app2 && umi dev",
    "start:app3": "cd examples/app3 && umi dev",
    "start:app4": "cd examples/app4 && umi dev"
  },
  "files": [
    "lib",
    "src"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/umijs/plugins"
  },
  "keywords": [
    "umi"
  ],
  "authors": [
    {
      "name": "chencheng",
      "email": "sorrycc@gmail.com"
    }
  ],
  "license": "MIT",
  "bugs": "http://github.com/umijs/plugins/issues",
  "homepage": "https://github.com/umijs/plugins/tree/master/packages/plugin-qiankun#readme",
  "peerDependencies": {
    "react": "16",
    "react-dom": "16",
    "umi": "^3.2.21",
    "webpack": "^4.41.0"
  },
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@babel/runtime": "^7.4.5",
    "address": "^1.1.2",
    "http-proxy-middleware": "^2.0.3",
    "lodash": "^4.17.15",
    "path-to-regexp": "^1.7.0",
    "qiankun": "^2.2.1"
  },
  "devDependencies": {
    "mockjs": "^1.0.1-beta3",
    "npm-run-all": "^4.1.5",
    "umi-request": "^1.1.0"
  }
}
`

**Comment by lihqi** [comment]
同样的问题，有解决方式么

**Comment by BBKmaisi** [comment]
什么时候可以解决修复啊
