### ISSUE TITLE
[Bug]window.setImmediate不生效

### ISSUE THREAD

**Issue by Evashasha** [umijs/qiankun#1787]
## window.setTimeout/window.setImmediate不生效

在使用braf-editor时，点击上传图片时，源代码里面是会执行
```jsx
window.setImmediate(() => {
      this.rootElement.classList.add('active');
 });
```
但是在主应用里面这个方法的执行是无效的，不会执行传给window.setImmediate的函数

示例地址：
https://github.com/Evashasha/qiankun-example

示例代码路径`./react16/src/pages/About.js`：
```jsx
window.setImmediate(()=>{
    console.log(1111)
  });
  window.setTimeout(()=>{
    console.log(1111, '22222')
  });
```

**Comment by gongshun** [comment]
子应用的 `window` 是一个沙箱，这上面的确没有 `setImmediate` 函数，但是当你执行这个函数时，会先从沙箱上查找，沙箱上找不到就会去主应用的 `window` 上找（真实的 `window` ），此时肯定是能找到这个函数的。源码：https://github.com/umijs/qiankun/blob/3a0a1d1d1ca886d255a2c8ec108ec8511050c0b5/src/sandbox/proxySandbox.ts#L281

你可以打印一下这个函数及函数的返回值，肯定是都有值，至于它的回调函数为啥没执行？可能是浏览器一直在执行其他的语句导致的

![image](https://user-images.githubusercontent.com/29347231/139567597-6b2d1631-277b-435f-b215-eb4d84879c48.png)

文档：https://developer.mozilla.org/zh-CN/docs/Web/API/Window/setImmediate

另外，我在主子应用都是 vue 的项目中，回调函数里面是可以打印出来的。

**Comment by Evashasha** [comment]
> 子应用的 `window` 是一个沙箱，这上面的确没有 `setImmediate` 函数，但是当你执行这个函数时，会先从沙箱上查找，沙箱上找不到就会去主应用的 `window` 上找（真实的 `window` ），此时肯定是能找到这个函数的。源码：
> 
> https://github.com/umijs/qiankun/blob/3a0a1d1d1ca886d255a2c8ec108ec8511050c0b5/src/sandbox/proxySandbox.ts#L281
> 
> 你可以在子应用打印一下 `window.setImmediate` 这个函数及函数的返回值，肯定是都有值，至于它的回调函数为啥没执行？可能是浏览器一直在执行其他的语句导致的
> 
> ![image](https://user-images.githubusercontent.com/29347231/139567597-6b2d1631-277b-435f-b215-eb4d84879c48.png)
> 
> 文档：https://developer.mozilla.org/zh-CN/docs/Web/API/Window/setImmediate
> 
> 另外，我在主子应用都是 vue 的项目中，回调函数里面是可以打印出来的。



> 子应用的 `window` 是一个沙箱，这上面的确没有 `setImmediate` 函数，但是当你执行这个函数时，会先从沙箱上查找，沙箱上找不到就会去主应用的 `window` 上找（真实的 `window` ），此时肯定是能找到这个函数的。源码：
> 
> https://github.com/umijs/qiankun/blob/3a0a1d1d1ca886d255a2c8ec108ec8511050c0b5/src/sandbox/proxySandbox.ts#L281
> 
> 你可以在子应用打印一下 `window.setImmediate` 这个函数及函数的返回值，肯定是都有值，至于它的回调函数为啥没执行？可能是浏览器一直在执行其他的语句导致的
> 
> ![image](https://user-images.githubusercontent.com/29347231/139567597-6b2d1631-277b-435f-b215-eb4d84879c48.png)
> 
> 文档：https://developer.mozilla.org/zh-CN/docs/Web/API/Window/setImmediate
> 
> 另外，我在主子应用都是 vue 的项目中，回调函数里面是可以打印出来的。


我主应用里面木有找到，window下面没有这个方法
<img width="750" alt="截屏2021-10-3116 26 33" src="https://user-images.githubusercontent.com/20812374/139574497-765555e3-4777-449b-9531-d0e6bbd2df32.png">
<img width="449" alt="截屏2021-10-3116 26 24" src="https://user-images.githubusercontent.com/20812374/139574500-cad0d357-b3cd-4f21-9cf7-de2eda2b0c1a.png">

**Comment by gongshun** [comment]
> 我主应用里面木有找到，window下面没有这个方法

![image](https://user-images.githubusercontent.com/29347231/139575213-f379ddd4-792f-46eb-a07c-46f52206f1af.png)

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/setImmediate#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

![image](https://user-images.githubusercontent.com/29347231/139575160-0a0d8958-bc8c-43d5-9025-162d46e85f2f.png)
