### ISSUE TITLE
vue3项目，webpackage启用externals，loadMicroApp加载子应用时主应用内容被子应用替换

### ISSUE THREAD

**Issue by WeiJianZhou** [umijs/qiankun#1790]
## What happens?

1. 创建2个空白的vue3应用，命名为mainApp和microApp
2. 新建vue.config.js
```javascript
/** mainApp vue.config.js */
module.exports = {
  configureWebpack: {
    externals: {
      vue: 'Vue'
    }
  }
}

/** microApp vue.config.js */
const port = 7777
const name = 'micro'

module.exports = {
  configureWebpack: {
    externals: {
      vue: 'Vue'
    },
    devServer: {
      port,
      // 跨域
      headers: {
        'Access-Control-Allow-Origin': '*',
      }
    },
    output: {
      // 把子应用打包成 umd 库格式(必须)
      library: `${name}-[name]`,
      libraryTarget: 'umd',
      jsonpFunction: `webpackJsonp_${name}`,
    }
  }
}
```
3. 修改public/index.html
4. 
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1791 重复
