### ISSUE TITLE
creat-react-app  子应用，静态资源存cdn。子应用加载报错

### ISSUE THREAD

**Issue by JuSanZhi** [umijs/qiankun#1792]
![image](https://user-images.githubusercontent.com/24559368/139778985-7fb01e45-2ee3-49e8-9cac-c0aa424fdb21.png)
![image](https://user-images.githubusercontent.com/24559368/139779219-b54891fc-e1bd-4617-9801-33f4c2ae1ffc.png)

静态资源没有存放cdn 之前，是正常的，但是搭配了oss 之后，就报了这个错

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8

![image](https://user-images.githubusercontent.com/29347231/139781235-0cd454ba-3381-4979-9a7e-a7431ee9ed27.png)

**Comment by JuSanZhi** [comment]
> https://qiankun.umijs.org/zh/guide/tutorial#%E5%BE%AE%E5%BA%94%E7%94%A8
> 
> ![image](https://user-images.githubusercontent.com/29347231/139781235-0cd454ba-3381-4979-9a7e-a7431ee9ed27.png)

好的，试了下了正常了。每次都不记得注释那个 pubilc-path.js 的文件

**Comment by gongshun** [comment]
可以判断下环境

```js
if (window.__POWERED_BY_QIANKUN__ && process.env.NODE_ENV === 'development') {
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
```
