### ISSUE TITLE
qiankun怎么和vue的keep-alive结合使用

### ISSUE THREAD

**Issue by winneyLin** [umijs/qiankun#1793]
## Background

主应用通过通过tagView切换不同子应用，需要页面缓存的功能，这里结合vue的keep-alive，但是报错了，只能在同一个字应用内用keep-alive，有什么好的建议吗
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/361 重复
