### ISSUE TITLE
子应用为webpack5的react项目，主应用为react项目，生命周期已抛出，在主应用中点击子应用，可以找到运行到public-path.js文件，但是运行不到抛出的生命周期中，项目也没有使用treesharking，求教怎么回事

### ISSUE THREAD

**Issue by lizhen12345** [umijs/qiankun#1797]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by lizhen12345** [comment]
![image](https://user-images.githubusercontent.com/43994612/140276679-de5ccee7-83ac-4477-98ed-5f711f5794bc.png)

**Comment by lizhen12345** [comment]
![image](https://user-images.githubusercontent.com/43994612/140277124-dbe88a6f-7016-4d17-b7ae-d62f26a1fb02.png)

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by lizhen12345** [comment]
> https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
老哥，这里面的方式都试了，感觉不是这里面的问题，。
