### ISSUE TITLE
接口报404

### ISSUE THREAD

**Issue by lovesL** [umijs/qiankun#1798]
## Background
![image](https://user-images.githubusercontent.com/27960630/140281720-3cb57043-b3bc-4ba5-bbf6-87b4d1695cdd.png)
8000端口是我主应用端口  子应用端口是8002 当前接口是子应用的但是我不明白为什么主应用去调这个接口了 

"@umijs/plugin-qiankun": "^2.35.1",

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/694 重复
