### ISSUE TITLE
dva框架集成qiankun

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/qiankun#18]
你好，请问dva框架改如何写挂载函数？dva框架的入口文件index.js是这种形式的：
const app = dva();
app.router(require('./router').default);
app.start('#root');

**Comment by kuitos** [comment]
一样的，但是可能多一个卸载 dva model 的步骤，比如这样：
```js
let app;
export const mount = async () => {
  app = dva();
  app.router(require('./router').default);
  app.start('#root');
}

export const unmount = async () => {
  ReactDOM.unmountComponentAtNode('#root');
  app._models.forEach(model => {
    app.unmodel(model.namespace);
  });
}
```

**Comment by gaorubin1990** [comment]
> 一样的，但是可能多一个卸载 dva model 的步骤，比如这样：
> 
> ```js
> let app;
> export const mount = async () => {
>   app = dva();
>   app.router(require('./router').default);
>   app.start('#root');
> }
> 
> export const unmount = async () => {
>   ReactDOM.unmountComponentAtNode('#root');
>   app._models.forEach(model => {
>     app.unmodel(model.namespace);
>   });
> }
> ```

你好，谢谢回复，这样试过，但是报错
![image](https://user-images.githubusercontent.com/49272745/61032187-82e5f600-a3f3-11e9-819d-a03cb46aeaaa.png)
另外看到qiankun需要在webpack配置相关参数，我是用dva-cli生成的工程，roadhog需要如何配置呢？

**Comment by gaorubin1990** [comment]
> > 一样的，但是可能多一个卸载 dva model 的步骤，比如这样：
> > ```js
> > let app;
> > export const mount = async () => {
> >   app = dva();
> >   app.router(require('./router').default);
> >   app.start('#root');
> > }
> > 
> > export const unmount = async () => {
> >   ReactDOM.unmountComponentAtNode('#root');
> >   app._models.forEach(model => {
> >     app.unmodel(model.namespace);
> >   });
> > }
> > ```
> 
> 你好，谢谢回复，这样试过，但是报错
> ![image](https://user-images.githubusercontent.com/49272745/61032187-82e5f600-a3f3-11e9-819d-a03cb46aeaaa.png)
> 另外看到qiankun需要在webpack配置相关参数，我是用dva-cli生成的工程，roadhog需要如何配置呢？

报错信息：dva app:Application 'dva app' died in status LOADING_SOURCE_CODE:You need to export the functional lifecycles in dva app entry

**Comment by kuitos** [comment]
webpack 需要先按照文档中的方式配置好 https://github.com/umijs/qiankun#webpack
roadhog 底层也是用的 webpack https://github.com/sorrycc/roadhog#configuration

**Comment by gaorubin1990** [comment]
> webpack 需要先按照文档中的方式配置好 https://github.com/umijs/qiankun#webpack
> roadhog 底层也是用的 webpack https://github.com/sorrycc/roadhog#configuration

你好，但是roadhog并没有output参数，会报错

**Comment by kuitos** [comment]
https://github.com/sorrycc/roadhog/issues/36

**Comment by kindlymental** [comment]
想问一下,最后是如何解决的

**Comment by huangyl15** [comment]
请问这个问题最终是如何处理的？

**Comment by kurongdashi** [comment]
> 你好，请问dva框架改如何写挂载函数？dva框架的入口文件index.js是这种形式的：
> const app = dva();
> app.router(require('./router').default);
> app.start('#root');

请问，这个问题最终怎么解决的，现在我们这边项目也是用的dva，遇到了同意的问题

**Comment by zoii** [comment]
> 
在根目录下新建 webpack.config.js

const { name } = require('./package');

module.exports = function (config, test) {
  config.output = {
    ...config.output,
    library: `${name}`,
    libraryTarget: 'umd',
    jsonpFunction: `webpackJsonp_${name}`,
  };

  return config;
  
};
