### ISSUE TITLE
子应用antd pro样式丢失

### ISSUE THREAD

**Issue by godismygirl** [umijs/qiankun#180]
## What happens?

主应用和子应用都是umi antd pro， 用qiankun插件搭建微前端，子应用加载完成后发现antd pro的样式丢失。控制台报多个style component实例冲突

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
复现仓库地址
https://github.com/godismygirl/qiankunIssue.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

**Comment by godismygirl** [comment]
自己没整对

**Comment by wsdqr001** [comment]
> 自己没整对

请问如果主应用和子应用都用了styled-components是怎么解决的？
