### ISSUE TITLE
DEMO里的vue2案例是错的，没人发觉吗，跑不起来的！

### ISSUE THREAD

**Issue by 406087475** [umijs/qiankun#1800]
这个只要拉项目下来运行下就知道了，居然没人报这个问题。

![image](https://user-images.githubusercontent.com/9188028/140295007-0eb17a20-5a46-4316-9c23-ac07082c44da.png)

要改成这样才能跑，想确认下，乾坤项目首页的动图里，vue2是怎么样跑起来的？

**Comment by 406087475** [comment]
改成这样，打包出来的是跑不起来的，好神奇

**Comment by gongshun** [comment]
可以正常运行的 

https://github.com/umijs/qiankun/blob/9a4cc256850346a3903233802b747be5b61efb09/examples/vue/src/main.js#L20

**Comment by 406087475** [comment]
vue-router的问题，我看了下vue-router3.5.3 (for vue2)、vue-router4.x(for vue3)的源码。
发觉在hash模式下，vue-router3.5.3没有拿base对location path做处理。
vue-router4.x是有做替换的，所以没问题。

**Comment by 406087475** [comment]
> 可以正常运行的，都录屏了
> 
> https://github.com/umijs/qiankun/blob/master/examples/example.gif

你这个录屏意义不大啊，本地运行和构建运行，我都试过了，确实是有问题啊。

**Comment by gongshun** [comment]
> 你这个录屏意义不大啊，本地运行和构建运行，我都试过了，确实是有问题啊。

啥问题啊？怎么就跑不起来？能录屏看看吗

**Comment by 406087475** [comment]
> > 你这个录屏意义不大啊，本地运行和构建运行，我都试过了，确实是有问题啊。
> 
> 啥问题啊？怎么就跑不起来？能录屏看看吗

你看下，新拉的项目
https://www.loom.com/share/8ec41abc466244d39b1dbb3a4b4e94e0

**Comment by gongshun** [comment]
> 
> 你看下，新拉的项目 https://www.loom.com/share/8ec41abc466244d39b1dbb3a4b4e94e0

不知道你改了啥，官方demo，我重新下载安装依赖，正常运行

**Comment by 406087475** [comment]
> 不知道你改了啥，官方demo，我重新下载安装依赖，正常运行

我知道为啥你能跑起来了，vue2项目里的 mode: 'history' 是这个，我改成了 hash。
就会出现我说的问题了

**Comment by gongshun** [comment]
> > 不知道你改了啥，官方demo，我重新下载安装依赖，正常运行
> 
> 我知道为啥你能跑起来了，vue2项目里的 mode: 'history' 是这个，我改成了 hash。 就会出现我说的问题了

改成 hash 依然正常运行，你还改了 activeRule ？demo 没问题的

https://qiankun.umijs.org/zh/cookbook#activerule-%E4%BD%BF%E7%94%A8-locationhash-%E5%8C%BA%E5%88%86%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by 406087475** [comment]
![image](https://user-images.githubusercontent.com/9188028/140469544-7094d5ff-b72d-4933-90b8-ecc3371af11c.png)

这里也写了

**Comment by gongshun** [comment]
> 这里也写了

它的前提是用 location.hash 值来设置 activeRule，否则是不需要这样写的

1.  如果什么也不改，demo 是可以正常运行的
2. 如果你还有问题，你把你改的 demo 发出来

**Comment by 406087475** [comment]
我用 location.hash 值来设置 activeRule，还是必须设置多一级空白路由的。
我是觉得这样不好，这样导致项目单独运行的时候，也会多一层路由。
不过可以自己区分环境做下过滤了。
