### ISSUE TITLE
路由不变的情况下，通过选择不同的角色，重新加载微应用（微应用是固定的）会导致报错

### ISSUE THREAD

**Issue by moolisi** [umijs/qiankun#1803]
## 遇到的问题

1. 主框架通过切换不同的角色后，需要重新的渲染微应用（微应用是固定的，只是通过切换了不同的角色事件后，去重新渲染微应用，微应用内部是通过角色来获取对应数据的）
2. 每次切换角色后，通过loadMicroApp方法去重新加载微应用
3. 这种情况下控制台有报错
4. 报错是否是因为重新渲染微应用前，是否需要卸载之前已经渲染的微应用？
5. 如何通过事件手动的卸载微应用？

[https://ecstest.ledc.changyan.cn/w/error-img.png](url)
报错提供的链接：https://single-spa.js.org/error/?code=31&arg=mount&arg=parcel&arg=ma7932baabacf043c7b829bd86ef075eb4_1636103976243_858&arg=3000

## 相关环境信息
chrome  版本 95.0.4638.69（正式版本） （64 位）

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1654#issuecomment-905284106
