### ISSUE TITLE
更改主应用代码 ，保存，报错 Cannot read properties of undefined (reading 'iframeReady')，子应用不显示

### ISSUE THREAD

**Issue by p919533** [umijs/qiankun#1804]
![image](https://user-images.githubusercontent.com/26241954/141233874-fefbe894-57f8-4d6a-8fb0-71814de0065e.png)

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import {
    registerMicroApps,
    start,
    addGlobalUncaughtErrorHandler
} from 'qiankun';
import reportWebVitals from './reportWebVitals';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';
import { renderRoutes } from 'react-router-config';
import Routes from 'routes';
import 'antd/dist/antd.variable.min.css';
import './index.css';

// console.log('a=========', a)

ConfigProvider.config({
    theme: {
        primaryColor: '#0b80fd'
    }
});

ReactDOM.render(
    <React.StrictMode>
        <ConfigProvider locale={zhCN} prefixCls="ant-main">
            <Router>{renderRoutes(Routes)}</Router>
        </ConfigProvider>
    </React.StrictMode>,
    document.getElementById('root')
);

// 注册微应用;
registerMicroApps(
    [
        {
            // 子应用的容器
            name: 'document', // app name registered
            // 子应用的入口js
            entry: '//localhost:4001',
            // 主应用显示子应用的容器
            container: '#sub-child',
            // 路由激活状态
            activeRule: '/index1'
        },
        {
            // 子应用的容器
            name: 'document2', 
            // 子应用的入口js
            entry: '//localhost:4004',
            // 主应用显示子应用的容器
            container: '#sub-child',
            // 路由激活状态
            activeRule: '/index2'
        }

        
    ],
    {
        beforeLoad: (app) => {
            return Promise.resolve();
        },
        afterMount: (app) => {
            return Promise.resolve();
        }
    }
);

addGlobalUncaughtErrorHandler((event) => {
    console.error(event, 'event2');
    const { message: msg }:any = event;
    if (msg && msg.includes('died in status LOADING_SOURCE_CODE')) {
        console.error('微应用加载失败，请检查应用是否可运行');
    }
});

start();

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

**Comment by gongshun** [comment]
热更新bug https://github.com/umijs/qiankun/issues/1428

**Comment by p919533** [comment]
> 热更新bug #1428
![image](https://user-images.githubusercontent.com/26241954/141730690-58b00707-cd79-4805-8988-122d56008399.png)
修改了热更新端口 没有用

**Comment by yueyp** [comment]
> Hello @p919533. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @p919533, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

The main application warehouse address is visible to  https://github.com/yueyp/react-main
The child application warehouse address is visible to  https://github.com/yueyp/react-child

**Comment by mebtte** [comment]
Same issue.

**Comment by p919533** [comment]
> Same issue.
有解决办法吗

**Comment by p919533** [comment]
> Hello @p919533. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @p919533, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

The main application warehouse address is visible to https://github.com/yueyp/react-main
The child application warehouse address is visible to https://github.com/yueyp/react-child

**Comment by cat-walk** [comment]
遇到了同样的问题，热更新时偶现这个bug，希望尽快有解决方案，不然每次出问题了都需要刷新页面。

**Comment by lyfcp** [comment]
同样遇到这个问题，希望尽快出解决方案

**Comment by jk4235** [comment]
我是能拿到iframeReady这个方法,但是这个方法里面调用的变量状态不对,导致react-error-overlay弹出的iframe没有消失,挡住了整个页面

debug看下来应该是修改主应用热更新的时候,子应用也trigger了热更新,但是一些闭包变量读取出来不对(因为只修改了主应用,子应用是不应该出发更新的,一些flag变量没有变更)

我想了一个比较hack的方法

在子应用里写一个umi插件

```js
// plugins/dev-scripts.js 如果你项目用ts,这里也要写成js文件

export default (api) => {
  api.describe({
    key: "modifyDevScripts",
    config: {
      schema(joi) {
        return joi.object();
      },
    },
    enableBy: api.env === "development",
  });

  api.register({
    key: "addDevScripts",
    fn: () => {
      return `
      Object.defineProperty(window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__, 'iframeReady', {
        value: () => {
          document.body.removeChild(document.querySelector('iframe[style*="z-index: 2147483647;"]'));
        },
        configurable: false,
        writable: false,
        enumerable: true
      })`;
    },
  });
};

```

之后在.umirc.ts里
```typescript
export default defineConfig({
  ... otherConfig,
  fastRefresh: false, // 关闭这个
  plugins: [
    ...otherPlugins,
    path.resolve(__dirname, './plugins/dev-scripts.js') // 引入插件
  ]
})
```

之后重启应用即可,这样也不影响主应用和子应用的热更新

总之整体思路就是自己重写iframeReady这个方法

**Comment by maotong06** [comment]
同样的问题

**Comment by dtntakk** [comment]
我这边产生的原因是主应用和子应用都有react-error-overlay，react-error-overlay会往window写入__REACT_ERROR_OVERLAY_GLOBAL_HOOK__属性，然而开启sandbox后，子应用卸载后sandbox会将子应用写入window的属性删除[https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts#L192](https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts#L192)，导致__REACT_ERROR_OVERLAY_GLOBAL_HOOK__属性被删除。
我这边暂时的解决方法是缓存主应用的__REACT_ERROR_OVERLAY_GLOBAL_HOOK__，监听路由变化，子应用卸载后再手动写回去
`window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__MASTER__ = { iframeReady: window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__.iframeReady };
    window.addEventListener('popstate', () => {
      setTimeout(() => {
        if (!location.pathname.includes('slave') && !window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__) {
          window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__ = window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__MASTER__;
        }
      }, 100);
    })`
希望官方能有更合理的解决方法吧

**Comment by Lemonreds** [comment]
Same issue.

**Comment by wangzishun** [comment]
same issue.
我的解决方案是在最顶层的主应用添加了一个全局变量. 
```js
window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__ = {}
```

[react-error-overlay use window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__](https://github.com/facebook/create-react-app/blob/66bf7dfc43350249e2f09d138a20840dae8a0a4a/packages/react-error-overlay/src/index.js#L181)

**Comment by bingjieL** [comment]
mark

**Comment by daiwenyu** [comment]
mark
