### ISSUE TITLE
webpack5还需要配置chunkLoadingGlobal这个吗

### ISSUE THREAD

**Issue by ChengranYan** [umijs/qiankun#1806]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
需要的。`webpack4`  升级 `webpack5`，`jsonpFunction` 换成了 `chunkLoadingGlobal`

**Comment by UmbraCi** [comment]
> 需要的。`webpack4` 升级 `webpack5`，`jsonpFunction` 换成了 `chunkLoadingGlobal`

为什么文档没有更新呢？
我看这个merge请求被close掉了，是不是忙忘了https://github.com/umijs/qiankun/pull/2240
