### ISSUE TITLE
多个子应用使用高德时， 切换子应用导致高德地图加载的始终是第一个子应用的信息而产生报错

### ISSUE THREAD

**Issue by oathll** [umijs/qiankun#1807]
**背景**
主应用react   子应用 react  
主应用通过@uiw/react-amap 引入高德地图
多个微应用引入各自@uiw/react-amap 使用高德地图功能

**现状**
子应用A使用完高德地图功能后，切换到子应用B使用时，使用地图的具体页面会报 “wrapper element for XXX with instance xxx_432424 is not existed”。

另外如果在子应用重新刷新一次也可以解决，看了下刷新后会触发
[@umijs/plugin-qiankun] MicroApp XXXX is updating with props:  xxxx
那么现在有什么办法能在切换的时候触发这个方法么？

看过https://github.com/umijs/qiankun/issues/1440 提到的问题，基本一样的，不过他是vue的
现在这一块已经有解决方案了么？还是说还是得去修改源码？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1826#issuecomment-974580355
