### ISSUE TITLE
【问题】如果传入自定义fetch时，需不需要兼容fetch的第一个参数是不同类型的情况

### ISSUE THREAD

**Issue by ChengranYan** [umijs/qiankun#1808]
【问题】如果传入自定义fetch时，需不需要兼容fetch的第一个参数是不同类型的情况

https://developer.mozilla.org/en-US/docs/Web/API/fetch
resource
This defines the resource that you wish to fetch. This can either be:
A string or any other object with a stringifier — including a URL object — that provides the URL of the resource you want to fetch.
A Request object.

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95
