### ISSUE TITLE
使用 vue-cli 创建的主应用 主应用自己的路由如何跳转呢

### ISSUE THREAD

**Issue by CookyG** [umijs/qiankun#181]
## What happens?
使用 vue-cli 创建了一个主应用，跳转子应用的路由没问题 跳转主应用的路由 无法进入
参考了examples 目录里面参考了主应用的配置
setDefaultMountApp也注释没有默认跳转
是需要更改代码？还是说qiankun暂不支持呢？

## 相关配置

![image](https://user-images.githubusercontent.com/20312873/70291009-d169b600-1814-11ea-899d-0962f1021325.png)
## 相关环境信息

- **浏览器版本**：chrome 最新版
- **操作系统**：win10最新系统
- **Node 版本**：12.13.1

**Comment by kuitos** [comment]
提供一下可复现的仓库

**Comment by 15982153332** [comment]
主应用引入vue-router，再加上router-view就可以了

**Comment by bacy** [comment]
> 主应用引入vue-router，再加上router-view就可以了

如果子页面和主页面有相同的路由/about，跳转主页面的about，会把子页面的about也带出来，你那边会出现吗？

**Comment by 15982153332** [comment]
没遇到，我没有相同的路由，这个应该可以规避




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈波"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 下午3:39
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun] 使用 vue-cli 创建的主应用 主应用自己的路由如何跳转呢 (#181)



 
主应用引入vue-router，再加上router-view就可以了
  
如果子页面和主页面有相同的路由/about，跳转主页面的about，会把子页面的about也带出来，你那边会出现吗？
