### ISSUE TITLE
[Bug]微应用文件跟新后，访问的还是旧版文件

### ISSUE THREAD

**Issue by Tyrone-web** [umijs/qiankun#1816]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?
![image](https://user-images.githubusercontent.com/53857417/142113973-d6fda712-561c-4d6e-89d5-b094845fe63d.png)
在子应用中使用了这个方案后单独访问子应用是ok的，但是通过基座访问该子应用仍然存在缓存问题

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
1、在子应用中配置Cache-Control no-cache
2、构建好后访问通过基座（主程序）访问步骤1中的子应用（任然存在缓存，和预期结果不符）
3、直接访问步骤1配置的子应用（不存在缓存和预期结果相符）

## 相关环境信息

- **qiankun 版本** 2.3.4
- **浏览器版本**：67
- **操作系统**：windows64

**Comment by gongshun** [comment]
主应用刷新一下，应该就正常了，如果是访问中子应用更新，就还是会读取缓存的内容

**Comment by jiangjunfeng98** [comment]
缓存问题，可以看下官网的常见问题 [微应用文件更新之后，访问的还是旧版文件](https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%96%87%E4%BB%B6%E6%9B%B4%E6%96%B0%E4%B9%8B%E5%90%8E%E8%AE%BF%E9%97%AE%E7%9A%84%E8%BF%98%E6%98%AF%E6%97%A7%E7%89%88%E6%96%87%E4%BB%B6)

**Comment by Tyrone-web** [comment]
https://github.com/umijs/qiankun/issues/1816#issuecomment-981104805 就是参照官网给的示例改的呀
https://github.com/umijs/qiankun/issues/1816#issuecomment-971218409 主应用刷新是指清除缓存刷新嘛？清除缓存刷新是可以的，但是普通刷新不可以

**Comment by syhsghr1993** [comment]
分场景

**Comment by syhsghr1993** [comment]
按官方的配置的话也之解决了一个场景。如果子应用发布后，操作者任然停留在页面，此时因为不是初次加载子应用，导致子应用的index.html不会重新下载所以还是加载的缓存。如果子应用发布后，操作者新打开页面或者之前没有进入到子应用的页面，那会下载子应用最新的的index.html，此时所有加载的都是最新的了。

**Comment by gongshun** [comment]
> 按官方的配置的话也之解决了一个场景。如果子应用发布后，操作者任然停留在页面，此时因为不是初次加载子应用，导致子应用的index.html不会重新下载所以还是加载的缓存。如果子应用发布后，操作者新打开页面或者之前没有进入到子应用的页面，那会下载子应用最新的的index.html，此时所有加载的都是最新的了。

正在访问的用户继续浏览旧版本，新打开的用户使用新版本，这应该没啥问题

**Comment by syhsghr1993** [comment]
> > 按官方的配置的话也之解决了一个场景。如果子应用发布后，操作者任然停留在页面，此时因为不是初次加载子应用，导致子应用的index.html不会重新下载所以还是加载的缓存。如果子应用发布后，操作者新打开页面或者之前没有进入到子应用的页面，那会下载子应用最新的的index.html，此时所有加载的都是最新的了。
> 
> 正在访问的用户继续浏览旧版本，新打开的用户使用新版本，这应该没啥问题

是的一般问题不大。只不过有时候有缓存时以旧的接口入参访问后端新发布的接口可能会报错，体验不是特别好

**Comment by jiakaiqiang** [comment]
有什么好的解决方案吗  子应用发布后  用户无感刷新   拿到最新的发布版本

**Comment by Tyrone-web** [comment]
> 

在基座加载子应用的接口后做一个随机数，每次请求都不缓存

**Comment by joinzhu** [comment]
官方的方法不一定所有情况都适用，而且小公司的新手前端很多还不懂nginx，也没有正儿八经的运维同学，下面是我的解决办法
修改主应用的main.js的start方法
`
start({
  prefetch: ['A','B'], // 预加载 name为 A和B的子应用
  async fetch(url) { // 自定义fetch方法，加上一个no-cache
    return window.fetch(url, {
      cache: 'no-cache'
    })
  }
})
`

**Comment by kimi009** [comment]
同样的问题，子应用修改后部署了，但是刷新没有更新上去

**Comment by HyaCiovo** [comment]
遇到了相同的问题，也在nginx上配置了no-cache。子应用重新部署后，通过父应用基座访问依旧是老版子应用代码，刷新也没有用，只有禁用缓存后刷新才可以获取到最新的代码

**Comment by HyaCiovo** [comment]
请问有大佬有好的解决方案吗？是umi+qiankun的项目，小白找不到自定义fetch请求的入口🫠
