### ISSUE TITLE
[Bug] 两个子应用域名一样能否支持

### ISSUE THREAD

**Issue by alvin0216** [umijs/qiankun#1818]
## What happens?

如题：比如这边通过 nginx 配置部署，访问的域名是一样的。

```js
https://www.a.com/aaa // 应用1
https://www.a.com/bbb // 应用2
```

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%9C%BA%E6%99%AF-1%E4%B8%BB%E5%BA%94%E7%94%A8%E5%92%8C%E5%BE%AE%E5%BA%94%E7%94%A8%E9%83%A8%E7%BD%B2%E5%88%B0%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8C%E4%B8%80%E4%B8%AA-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3
