### ISSUE TITLE
[Feature Request] compatible with IE

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#182]
## Background

ref https://github.com/umijs/qiankun/issues/27
主要是沙箱基于 proxy，无法兼容 IE
目前诉求比较少，需求比较多的话会排上日程

当前也可以通过关闭沙箱的方式来兼容 IE https://qiankun.umijs.org/zh/faq/#qiankun-%E8%83%BD%E5%85%BC%E5%AE%B9-ie-%E5%90%97%EF%BC%9F

## Proposal
兼容版沙箱采用 window diff 方案，且支持自动降级

## Additional context

有 IE 兼容性需求的可以在下面 +1

**Comment by janryWang** [comment]
+1

**Comment by fenngding** [comment]
+2

**Comment by Koomita** [comment]
+3

**Comment by viviprprpr** [comment]
+4

**Comment by freewalker8** [comment]
+5

**Comment by phobal** [comment]
+6

**Comment by xiexingen** [comment]
+10086

**Comment by xiexingen** [comment]
+1

**Comment by wufeng87** [comment]
+9

**Comment by xiexingen** [comment]
IE的找个还打算兼容吗？刚好公司前端这块打算重构

**Comment by zuoerkou** [comment]
+1 +1 +1

**Comment by JimmyHook** [comment]
+1

**Comment by wufeng87** [comment]
偏个楼，@xiexingen @zuoerkou 你们ie11下，iframe的add和remove，会出现内存泄漏吗？

**Comment by tangjinzhou** [comment]
+1

**Comment by pang-y** [comment]
+1

**Comment by freewalker8** [comment]
兼容IE有计划了么，本来打算用qiankun来搭建项目，突然发现不支持IE

**Comment by kuitos** [comment]
> 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie

**Comment by xiexingen** [comment]
> > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie

你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数

**Comment by kuitos** [comment]
> > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> 
> 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数

这个跟 qiankun 没关系 https://umijs.org/config/#targets

**Comment by xiexingen** [comment]
> > > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> > 
> > 
> > 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数
> 
> 这个跟 qiankun 没关系 https://umijs.org/config/#targets

我这边设置了targets的，可能别的问题引起的吧

**Comment by xiexingen** [comment]
> > > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> > 
> > 
> > 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数
> 
> 这个跟 qiankun 没关系 https://umijs.org/config/#targets

我这边设置了targets的，可能别的问题引起的吧

**Comment by gongdf** [comment]
+1

**Comment by eelogic** [comment]
+1

**Comment by pang-y** [comment]
+1

**Comment by Ji-Yuhang** [comment]
> > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> 
> 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数

我也遇到了这个问题，
node_modules/@umijs/plugin-qiankun/lib/common.js 存在 let const 箭头函数等 es6 语法
```
const noop = () => {}; // @formatter:on
```

**Comment by Lensgcx** [comment]
+++111111111

**Comment by yuyic** [comment]
> > > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> > 
> > 
> > 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数
> 
> 我也遇到了这个问题，
> node_modules/@umijs/plugin-qiankun/lib/common.js 存在 let const 箭头函数等 es6 语法
> 
> ```
> const noop = () => {}; // @formatter:on
> ```

和你一样的问题

**Comment by viviprprpr** [comment]
> > > > > 当前也可以通过关闭沙箱的方式来兼容 IE https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie
> > > 
> > > 
> > > 你试过这样可以吗，我试了没用 我这边报错是umi.js文件里面使用了箭头函数
> > 
> > 
> > 我也遇到了这个问题，
> > node_modules/@umijs/plugin-qiankun/lib/common.js 存在 let const 箭头函数等 es6 语法
> > ```
> > const noop = () => {}; // @formatter:on
> > ```
> 
> 和你一样的问题

```js
extraBabelIncludes: [path.join(__dirname, './node_modules/@umijs'), path.join(__dirname, './node_modules/qiankun')]
```

我现在是通过重新编译这两个包解决的，方法有点蠢

**Comment by jallens** [comment]
+1

**Comment by liucien** [comment]
+1

**Comment by ShuiYueJingHuaXiao** [comment]
+1

**Comment by weiyuq** [comment]
+1

**Comment by gaorubin1990** [comment]
+1

**Comment by HeGanjie** [comment]
+1

**Comment by gongxihai22** [comment]
+1

**Comment by qtttttttttting** [comment]
+1

**Comment by fanghe1979** [comment]
+1

**Comment by anteguitado** [comment]
+1

**Comment by branchesgit** [comment]
+1

**Comment by xileliu** [comment]
希望支持ie

**Comment by hal9000plant** [comment]
+1

**Comment by wufeng87** [comment]
@kuitos ie11有计划了吗？或者能分享些解决思路吗？我们暂时还是需要支持ie11的。

**Comment by kuitos** [comment]
> @kuitos ie11有计划了吗？或者能分享些解决思路吗？我们暂时还是需要支持ie11的。谢谢

issue 描述里有思路跟临时解决方案

**Comment by huwsun** [comment]
+1

**Comment by fengruiabc** [comment]
+10086

**Comment by shichuanpo** [comment]
+1

**Comment by wangqh** [comment]
+1

**Comment by Pengjee** [comment]
+1

**Comment by anncwb** [comment]
+1

**Comment by anncwb** [comment]
+1

**Comment by simondiep** [comment]
+1

**Comment by weishili** [comment]
+1

**Comment by blitheinsz** [comment]
请问，qiankun什么时候支持IE浏览器，支持IE9, IE10和IE11吗？ 我们很多项目目前是兼容到IE9的

**Comment by dwtrace** [comment]
+1

**Comment by wusp1994** [comment]
+1

**Comment by Yowi** [comment]
+1

**Comment by netbeen** [comment]
还有部分IE的客户，很是顾虑，如果支持IE就可以完美使用qiankun了

**Comment by anncwb** [comment]
+1

**Comment by zmzimpl** [comment]
+1

**Comment by f-origin** [comment]
+1,   强烈希望支持ie，本来准备上qiankun 这个见过的最完美的微前端方案， 被IE 卡了

**Comment by pengchengCN** [comment]
+1

**Comment by conioX** [comment]
+1, any news?

**Comment by fireairforce** [comment]
可怕～

**Comment by a1029563229** [comment]
+1

**Comment by pangjian** [comment]
+1

**Comment by gysheng** [comment]
+1

**Comment by Lining1108** [comment]
+1

**Comment by hkdg** [comment]
+1

**Comment by Bonnie8ni** [comment]
+1

**Comment by CR903** [comment]
+1

**Comment by WtecHtec** [comment]
+NNNNNNNNNN

**Comment by Richar-Dada** [comment]
+1

**Comment by conioX** [comment]
need documentation for this

**Comment by dedoyle** [comment]
+1

**Comment by ooooevan** [comment]
+1

**Comment by xuduogui** [comment]
+1

**Comment by xuduogui** [comment]
https://github.com/umijs/qiankun/pull/296
看到了这个，现在是支持了主应用为vue的ie兼容么？

**Comment by Deturium** [comment]
> #296
> 看到了这个，现在是支持了主应用为vue的ie兼容么？

IE11 的兼容随 2.0 发布；跟技术栈是不是 vue 无关

**Comment by waltbest2** [comment]
+1，为了angular项目。2.0 什么时候发布？

**Comment by kuitos** [comment]
released https://zhuanlan.zhihu.com/p/131022025

**Comment by wangming-wm** [comment]
+1

**Comment by fengyun2** [comment]
+100，什么时候计划支持呢？

**Comment by cshsh** [comment]
+1
