### ISSUE TITLE
[Bug]主应用的路由中用registerMicroApps，加载子应用，无法渲染子应用其他路由的组件，点击路由跳转也无效

### ISSUE THREAD

**Issue by z-lionel** [umijs/qiankun#1821]
主应用和子应用都是vue，都是用的history模式，现在是在主应用能渲染到子应用的app.vue界面的内容，
但是子应用下面的<router-view />下面的内容渲染不了，<router-link to="/demo" >demo</router-link>
点击跳转也没有效果。

主应用配置：
```
registerMicroApps([
  {
    name: 'vueapp',
    entry:'http://localhost:8080',
    container: '#container',
    activeRule: '/vue',
  },
],{
  beforeLoad: app => {
    console.log('before load app.name====>>>>>', app.name)
    return Promise.resolve()
  },
  beforeMount: [
    app => {
      console.log('[LifeCycle] before mount %c%s', 'color: green;', app.name)
      return Promise.resolve()
    }
  ]
});
```
子路由配置
`const routes = [
  { path: '/', redirect: '/demo' },
  { path: '/home', name: 'home', component: () => import('./view/Home.vue') },
  { path: '/demo', name: 'demo',  component: () => import('./view/Demo.vue')}
]`

版本号
```
"qiankun": "^2.5.1",
 "vue": "^3.2.22",
 "vue-router": "^4.0.12"
```

**Comment by z-lionel** [comment]
有个问题是不是vue3.x 和 vue-router 4.x现在还没适配？
我下载这个项目，用里面的主应用加载我的子应用的时候就报错，
他里面自带的vue2.x 和 router 3.x就没问题
https://github.com/gongshun/qiankun-vue-demo/tree/feature/routing-page

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1750#issuecomment-929929034

**Comment by 1048034876** [comment]
我的代码，主子应用都是history模式，本地运行在不同的端口没什么问题，但是按照官方提供的部署方案，配置到同一个服务器下，就会出现你上面说的加载子应用只能展示App.vue的内容，子应用里面<router-view/>的内容不会展示。控制台打印已经进入了子应用的aftermount，并且无任何报错
