### ISSUE TITLE
qiankun2.0+vue基座+react微应用报错

### ISSUE THREAD

**Issue by lyfcp** [umijs/qiankun#1822]
## What happens?

vue主应用打开react子应用报错，提示WebSocket connection to 'ws://localhost:8080/sockjs-node' failed，然后vue-cli自动停止了，试了下vue主应用+vue子应用没有问题，不知道是不是react的问题

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.0
- **Platform Version**:vue-cli 4.5
- **Browser Version**:

**Comment by gongshun** [comment]
react 的热更新bug https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643

**Comment by lyfcp** [comment]
> react 的热更新bug [#1428 (comment)](https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643)

可以了，感谢感谢
