### ISSUE TITLE
[Bug]主应用的路由中用registerMicroApps，加载子应用，无法渲染子应用其他路由的组件，点击路由跳转也无效

### ISSUE THREAD

**Issue by z-lionel** [umijs/qiankun#1823]
主应用和子应用都是vue，都是用的history模式，现在是在主应用能渲染到子应用的app.vue界面的内容，
但是子应用下面的<router-view />下面的内容渲染不了，<router-link to="/demo" >demo</router-link>
点击跳转也没有效果。
主应用报错，点击router-link也报错这个错
`vue-router.esm-bundler.js?6c02:3295 ChunkLoadError: Loading chunk 0 failed`

主应用配置：
```
registerMicroApps([
  {
    name: 'vueapp',
    entry:'http://localhost:8080',
    container: '#container',
    activeRule: '/vue',
  },
],{
  beforeLoad: app => {
    console.log('before load app.name====>>>>>', app.name)
    return Promise.resolve()
  },
  beforeMount: [
    app => {
      console.log('[LifeCycle] before mount %c%s', 'color: green;', app.name)
      return Promise.resolve()
    }
  ]
});
```
子路由配置
`const routes = [
  { path: '/', redirect: '/demo' },
  { path: '/home', name: 'home', component: () => import('./view/Home.vue') },
  { path: '/demo', name: 'demo',  component: () => import('./view/Demo.vue')}
]`

版本号
```
"qiankun": "^2.5.1",
 "vue": "^3.2.22",
 "vue-router": "^4.0.12"
```

**Comment by gongshun** [comment]
重复提交 https://github.com/umijs/qiankun/issues/1821
