### ISSUE TITLE
 died in status LOADING_SOURCE_CODE: 'set' on proxy: trap returned falsish for property '__SVG_SPRITE__'

### ISSUE THREAD

**Issue by 15982153332** [umijs/qiankun#183]
## What happens?
Uncaught TypeError: Application 'forwarder' died in status LOADING_SOURCE_CODE: 'set' on proxy: trap returned falsish for property '__SVG_SPRITE__'

子应用返回主应用是报错，刷新页面正常，再次进入子应用返回主应用还是报同样的错误

![图片](https://user-images.githubusercontent.com/16485092/70302924-3c2ce880-1839-11ea-9609-c71c3eaf6d4c.png)

**Comment by 15982153332** [comment]
打包部署后的线上环境

**Comment by kuitos** [comment]
请提供可重现的仓库

**Comment by 15982153332** [comment]
线上网址：http://47.105.53.77/workbench/index，打开比较慢，因为带宽只有1M；
第一步：进入首页过后点击顶部的工作台，工作台页面的都是子应用，目前只启用的只有第一排的三个，分别是货代宝，易接单，客服中心
第二步：点击其中一个任一子应用

第三步：产生报错信息，子应用打不开，但是刷新一下就可以打开了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kuitos"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 晚上6:15
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun]  died in status LOADING_SOURCE_CODE: 'set' on proxy: trap returned falsish for property '__SVG_SPRITE__' (#183)




请提供可重现的仓库

**Comment by 15982153332** [comment]
线下任何问题，只是发布过后会产生这种问题，所以不知道怎么处理，已经纠结三天了，希望能指点一下走出困惑，所有的都是按照qiankun一步步来实现的！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kuitos"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 晚上6:15
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun]  died in status LOADING_SOURCE_CODE: 'set' on proxy: trap returned falsish for property '__SVG_SPRITE__' (#183)




请提供可重现的仓库

**Comment by 15982153332** [comment]
请问一下，子应用和子应用之间可以互相跳转吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kuitos"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 晚上6:15
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"丶道不出的未来"<190649821@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun]  died in status LOADING_SOURCE_CODE: 'set' on proxy: trap returned falsish for property '__SVG_SPRITE__' (#183)




请提供可重现的仓库

**Comment by kuitos** [comment]
@15982153332 没看懂，什么场景跟诉求？

**Comment by 15982153332** [comment]
怎么手动卸载子应用呢

**Comment by 15982153332** [comment]
默认打开第一个子应用A，A里面点击链接跳转其它子应用报错，这个方案可行吗，线上一直报错

**Comment by kuitos** [comment]
子应用之间跳转通过超链接即可。
无法通过你的链接复现你说的问题，能提供一个可复现的仓库么，不然没法排查

**Comment by 15982153332** [comment]
找到原因了，是因为线上的端口被占用导致，换了一个端口就正常了
