### ISSUE TITLE
【问题】子应用遮罩层挂载到了body,遮罩层能遮住了全部，如果挂载到子应用，那公共的地方（主应用）又遮罩不住

### ISSUE THREAD

**Issue by zhuanghongbin** [umijs/qiankun#1831]
子应用使用elemenui框架那种dialog或者抽屉组件，遮罩层挂载到了父应用的body，子应用的实际内容被遮罩层遮住，这种要怎么处理，如果只挂载的子组件本身，那父应用，一些公共的地方又没遮住，请问有没有方案思路，谢谢

**Comment by duoWB** [comment]
element-ui dialog，drawer 组件可以设置 `modal-append-to-body` 为false

**Comment by Hew007** [comment]
> element-ui dialog，drawer 组件可以设置 `modal-append-to-body` 为false

不挂载到body 就会被子应用容器遮住，不能全屏遮罩
