### ISSUE TITLE
使用loadmicroApps做缓存方案，切换到下一个子应用的时候，前一个子应用的路由还会被监听出发，如何解除这种监听，同时还能做到子应用的keep-alive

### ISSUE THREAD

**Issue by sa0012** [umijs/qiankun#1837]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
路由钩子解除不了，只能在内部判断，如果跳转的路由与当前子应用无关，直接放行即可
