### ISSUE TITLE
刷新React微应用后主应用终端报错

### ISSUE THREAD

**Issue by Wind-man-JH** [umijs/qiankun#1838]
环境：Vue(基座)， React(微应用)
必显路径：启动基座和微应用后，路由切换到微应用，在微应用页刷新，基座的终端就会报错，接口如图：
![image](https://user-images.githubusercontent.com/56903684/143052445-5c8c352c-513b-44fd-9d3e-c270c9aaf37b.png)

，终端如图：
![image](https://user-images.githubusercontent.com/56903684/143051961-38ce97da-e89f-4119-b94b-ccad3f6dd830.png)

ps: 如果微应用是Vue就不会存在这个现象

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1822 重复
