### ISSUE TITLE
[Bug]关于shadowDOM样式隔离产生的问题

### ISSUE THREAD

**Issue by ViavaCos** [umijs/qiankun#1839]
这个问题已经被多次提及，目前是否有解决方案？

https://github.com/umijs/qiankun/issues/1316
https://github.com/umijs/qiankun/issues/1395

问题描述:

当子应用中调用的 组件/插件 会被添加到与视图容器同级(挂载至document.body)的问题。
当使用qiankun时，由于样式隔离，该 组件/插件 的样式会被隔离在子应用(#shadow-root)内，而DOM则挂载至document.body
由于这种组件都存在着全局遮罩层，因此以上issue中提及的将组件挂载至子应用的挂载容器上是无法解决问题的。

如图：
![图片](https://user-images.githubusercontent.com/46273525/143195635-7e16c98c-7c08-4656-9bde-0022f38b9d69.png)

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/1061#issuecomment-826119150

**Comment by ViavaCos** [comment]
> [#1061 (comment)](https://github.com/umijs/qiankun/pull/1061#issuecomment-826119150)

Okay..

**Comment by AzronChan** [comment]
@ViavaCos 请问大佬最后怎么解决的？

**Comment by ViavaCos** [comment]
> @ViavaCos 请问大佬最后怎么解决的？

最终采用的方案是，取消样式隔离，维护好命名空间。

**Comment by razr001** [comment]
我自己做了个方案，基本于ShadowDOM的，根据vue-style-loader源码修改的
https://github.com/drinkjs/shadow-style-loader
