### ISSUE TITLE
vue-cli3.0设置了样式隔离之后主应用访问子应用报错

### ISSUE THREAD

**Issue by zhangxuanlin** [umijs/qiankun#184]
vue-cli3.0
开发环境：css设置了隔离之后，主应用无法访问子应用，设为false就可以
// vue.config.js
css: {
    extract: true
}
![image](https://user-images.githubusercontent.com/17699676/70302975-62528880-1839-11ea-9c8b-b8bbe64e27e7.png)
求解！

**Comment by kuitos** [comment]
css.extract 跟样式隔离没有关系。跑了下 example 里的 vue 项目并没有出现你说的问题。
issue 先关了如果还有问题可随时 reopen 并请提供可复现的仓库。
