### ISSUE TITLE
主应用（vue3）的子路由内接入子应用（vue2），子应用内部跳转携带query参数，报错匹配不到路径

### ISSUE THREAD

**Issue by zhangmin0925** [umijs/qiankun#1851]
## What happens?

如题，子应用内跳转时携带了query参数，跳转无反应（子应用页面无资源匹配）
<img width="720" alt="image" src="https://user-images.githubusercontent.com/33387312/144347887-175d7bc6-b611-454f-897f-f4b62ca97c7d.png">

复现仓库：https://github.com/zhangmin0925/qiankun-vue3-test

复现路径：
1. 分别运行主应用、子应用
2. 访问主应用页面，点击“主应用的子路由”
3. 点击“去About”则页面无响应，报错匹配不到路径：
    [Vue Router warn]: No match found for location with path "/web-index#/about?a=1&b=8"
4. 如果上一步是点击“不带query参数去About”那就没问题

**Comment by aylaSong** [comment]
你好，请问这个问题解决了么？我也遇到了同样的问题。。

**Comment by jiangjunfeng98** [comment]
可以看下这个issue。https://github.com/umijs/qiankun/issues/1361

**Comment by gongshun** [comment]
vue-rouer4 改了路由匹配规则，匹配更加严格了。

你的路由注册的是 `path: '/web-index',` ，与当前的路由不匹配，所以不显示内容，至于那个警告，也是因为路由没匹配

只需要把 `path: '/web-index',` 改为 `path: '/web-index:pathMatch(.*)'` 。 https://github.com/zhangmin0925/qiankun-vue3-test/blob/4b3e3c2197565b9778f37807d177d47b48f092f5/base/src/router/index.js#L12

![123](https://user-images.githubusercontent.com/29347231/144695539-d4abc62b-0159-486d-af11-3562a7594772.gif)

**Comment by zhangmin0925** [comment]
> vue-rouer4 改了路由匹配规则，匹配更加严格了。
> 
> 你的路由注册的是 `path: '/web-index',` ，与当前的路由不匹配，所以不显示内容，至于那个警告，也是因为路由没匹配
> 
> 只需要把 `path: '/web-index',` 改为 `path: '/web-index:pathMatch(.*)'` 。 https://github.com/zhangmin0925/qiankun-vue3-test/blob/4b3e3c2197565b9778f37807d177d47b48f092f5/base/src/router/index.js#L12
> 
> ![123](https://user-images.githubusercontent.com/29347231/144695539-d4abc62b-0159-486d-af11-3562a7594772.gif)

感谢，把 path: '/web-index', 改为 path: '/web-index:pathMatch(.*)' ，可以了！

**Comment by zhangmin0925** [comment]
> 你好，请问这个问题解决了么？我也遇到了同样的问题。。

已解决，在主应用注册子路由的时候，把 path: '/web-index', 改为 path: '/web-index:pathMatch(.*)'好了
