### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by 3223554** [umijs/qiankun#1857]
antd pro v2 接入乾坤时，已在config中注册插件    
['@umijs/plugin-qiankun', { slave: {} }]
编译时出现
Error: Error: Plugin /Users/zhaochongjing/work/websaas/AppWeb/MyAppWeb/shopAdmin/node_modules/@umijs/plugin-qiankun/lib/index.js execute failed
Cannot find module '@@/history'

请问如何解决，官方可以提供一个antd pro v2 的demo吗？
如不配置该插件，在antd pro v2 中，如何暴露钩子函数？

- **qiankun 版本     "@umijs/plugin-qiankun": "^2.35.2",

**Comment by WoodenMan001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
