### ISSUE TITLE
Application died in status LOADING_SOURCE_CODE

### ISSUE THREAD

**Issue by Pasoul** [umijs/qiankun#186]
## What happens?

1. 构建基于qiankun的vue项目，项目分root、app1、app2三个目录
2. 按照qiankun的要求对子项目进行改造
3. 启动项目，默认进入app1，此时的url为`http://localhost:8080/app1#`，点击路由切换到app2，报错：
![image](https://user-images.githubusercontent.com/22902187/70419206-f4f46100-1a9f-11ea-9de9-41464bb01167.png)
但是在浏览器手动改变url为`http://localhost:8080/app2#`并刷新，可以正常切换到app2

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

demo：https://github.com/Pasoul/qiankun-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

1. 分别启动root、app1、app2项目
2. 在浏览器打开`http://localhost:8080`默认进入子项目app1
3. 点击切换到app2报错
![image](https://user-images.githubusercontent.com/22902187/70419632-c62aba80-1aa0-11ea-80c5-1fd17391d391.png)

**Expected behavior** 1. 2.

正常切换到app2

## Context

- **Platform**: mac
- **Browser Version**: 最新chrome
- **Node Version**: 8.10.0

**Comment by kuitos** [comment]
app1 跟 app2 的 library 名重名了导致的 https://github.com/Pasoul/qiankun-demo/blob/master/app1/build/webpack.base.conf.js#L24，建议按照文档中的方案配置 webpack https://github.com/umijs/qiankun#webpack ，同时确保不同应用之间 package name 不重复
