### ISSUE TITLE
当两个子应用快速切换的时候，总会出现[qiankun] Wrapper element for  XXX is not existed! , 弱网环境更加明显

### ISSUE THREAD

**Issue by lixiaozhangme** [umijs/qiankun#1864]
![image](https://user-images.githubusercontent.com/19645470/145377593-391728d2-e54d-4b4c-a9e5-015fb3a8850e.png)
是否应该建立loadApp自动中止操作， 在路由匹配变化的时候，或者在importEntry成功的时候查看路由是否和进入loadapp的时候一致；loadApp是一个异步且严格要求异步结束后的环境的过程， 异步结束后是否应该校验前后触发环境的差异，或者环境改变中止loadApp的流程呢

**Comment by gongshun** [comment]
你是最新版吗，快速切换导致 `Wrapper element` 报错不是已经修复了吗，https://github.com/umijs/qiankun/issues/1089

**Comment by yaoyuanrong** [comment]
您这个问题解决了吗？

**Comment by yaoyuanrong** [comment]
> ![image](https://user-images.githubusercontent.com/19645470/145377593-391728d2-e54d-4b4c-a9e5-015fb3a8850e.png) 是否应该建立loadApp自动中止操作， 在路由匹配变化的时候，或者在importEntry成功的时候查看路由是否和进入loadapp的时候一致；loadApp是一个异步且严格要求异步结束后的环境的过程， 异步结束后是否应该校验前后触发环境的差异，或者环境改变中止loadApp的流程呢

这个问题解决了吗？

**Comment by PossibleMaybe** [comment]
遇到同样问题，不知道如何解决

**Comment by PossibleMaybe** [comment]
我的问题已经解决了，原因是我使用了antd的Modal.confirm，我在onOk的时候没有使用modal.destroy()，直接进行了子应用路由的跳转。解决方式是在跳转之前，先对modal进行销毁操作，路由跳转最好使用setTimeout(fn)包一下。

**Comment by YCenhao** [comment]
遇到相同问题
