### ISSUE TITLE
子项目样式覆盖问题

### ISSUE THREAD

**Issue by phobal** [umijs/qiankun#187]
## What happens?

子项目使用了 ant-design-pro, 里面对某些 antd 组件进行了样式修改，子项目单独运行是没有问题的，但一旦集成到主项目中样式就会丢失，比如我的 demo 是这样的：

1. 子项目单独运行的时候是这样的

![image](https://user-images.githubusercontent.com/9244211/70601034-2d28aa80-1c2c-11ea-8d81-50f1bbc16f98.png)

2. 从主项目中进入的时候样式被覆盖了

![image](https://user-images.githubusercontent.com/9244211/70601093-4a5d7900-1c2c-11ea-8288-2ccc6f6fd2ee.png)

大概排查了一下原因，发现是 qiankun 会将子项目的 `umi.css` 的样式由子系统的 `<link>` 方式

![image](https://user-images.githubusercontent.com/9244211/70601453-028b2180-1c2d-11ea-9f36-8b683b36625f.png)

改为 `<style>` 的方式

![image](https://user-images.githubusercontent.com/9244211/70601521-29e1ee80-1c2d-11ea-8dfd-038558856415.png)

改成 <style> 方式后，会将样式放在子系统的 `mountElementId` 后，这样就导致它的加载优先级变得最高，如果在业务组件中有对 `umi.css` 中的样式进行修改的都将失效！

所以这里就有个疑问：
**为啥需要将部分样式由`<link>` 的方式改为 `<style>` 的方式呢?**

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/phobal/antd-pro-microfe/tree/style-order-issue

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**: mac
- **Browser Version**: chrome Version 78.0.3904.108 (Official Build) (64-bit)
- **Node Version**: v10.16.0

**Comment by kuitos** [comment]
子应用动态插入的样式优先级变低导致的，可以先考虑动态插入的样式加入一些specifier提高优先级

**Comment by phobal** [comment]
@kuitos 子应用 entry 中的 css 文件能不能像其他子应用非 entry 那样动态插入到主应用的<head> 中呢？这样就能避免样式优先级变化了。加入 specifier 来提高优先级是可以，但是大多数时候各个业务部门都在各自的子应用中开发，只有在系统集成的时候才会接入到主应用中来， 一两处还好，但是一旦多了就会变得很麻烦。

举一个业务中经常涉及到的示例吧

在使用第三方组件库的时候难免会做一些特殊样式修改，比如我上面举得 demo 那样，对 <Icon> 组件自定义样式

``` js
// a.jsx
<Icon className={styles.upgradeIcon} type="arrow-up" />
```
``` less
// a.less
.upgradeIcon {
    color: #f5222d;
}
```

**Comment by shengbeiniao** [comment]
大概率是因为主子应用都引用的antd导致的，下面讲下解决这个问题的基本思路，利用webpack可以打包cjs、esm，并可以external root的特性，采用如下解决方案


1. 在主应用新建external.js，包含如下代码，并在global.js首行中引用
```
import * as g_lodash from 'lodash'
import * as g_react from 'react'
import * as g_react_dom from 'react-dom'
import * as g_moment from 'moment'
import * as g_antd from 'antd'
import * as g_dataset from '@antv/data-set'
import * as g_bizcharts from 'bizcharts'
import * as g_redux from 'redux'
import * as g_redux_saga from 'redux-saga'
import * as g_react_redux from 'react-redux'
import * as g_immer from 'immer'
import * as g_dva from 'dva'
import * as g_dva_loading from 'dva-loading'
import * as g_dva_immer from 'dva-immer'
import * as g_react_router_dom from 'react-router-dom'
import * as g_url from 'url'
import * as g_uuid from 'uuid'
import * as g_umi from 'umi'
import * as g_corejs from 'core-js'
import * as g_value_equal from 'value-equal'
import * as g_whatwg_fetch from 'whatwg-fetch'
import * as g_runtime from 'regenerator-runtime/runtime'
import * as g_utils from '@zstack-cmp/utils'
import * as g_components from '@zstack-cmp/components'

window.g_lodash = g_lodash
window.g_react = g_react
window.g_react_dom = g_react_dom
window.g_moment = g_moment.default
window.g_antd = g_antd
window.g_dataset = g_dataset
window.g_bizcharts = g_bizcharts
window.g_redux = g_redux
window.g_redux_saga = g_redux_saga
window.g_react_redux = g_react_redux
window.g_immer = g_immer
window.g_dva = g_dva
window.g_dva_loading = g_dva_loading.default
window.g_dva_immer = g_dva_immer
window.g_react_router_dom = g_react_router_dom
window.g_url = g_url
window.g_uuid = g_uuid
window.g_umi = g_umi
window.g_corejs = g_corejs
window.g_value_equal = g_value_equal
window.g_whatwg_fetch = g_whatwg_fetch
window.g_runtime = g_runtime
window.g_utils = g_utils
window.g_components = g_components

```

2. 配置所有子应用.umirc的external，建议写一个工具类
 config.externals = {
      'lodash': 'g_lodash',
      'react': 'g_react',
      'react-dom': 'g_react_dom',
      'moment': 'g_moment',
      'antd': 'g_antd',
      '@antv/data-set': 'g_dataset',
      'bizcharts': 'g_bizcharts',
      'redux': 'g_redux',
      'redux-saga': 'g_redux_saga',
      'react-redux': 'g_react_redux',
      'immer': 'g_immer',
      'dva': 'g_dva',
      'dva-loading': 'g_dva_loading',
      'dva-immer': 'g_dva_immer',
      'react-router-dom': 'g_react_router_dom',
      'url': 'g_url',
      'uuid': 'g_uuid',
      'umi': 'g_umi',
      'core-js': 'g_corejs',
      'value-equal': 'g_value_equal',
      'whatwg-fetch': 'g_whatwg_fetch',
      'regenerator-runtime/runtime': 'g_runtime'
    }

3. 设置所有应用umi-plugin-react，antd=false，dynamic=false
> qiankun使用import-html-entry插件，如果dynamic为true，会导致umi生成一个vendors.chunk.css，被qiankun异步加载，在dom生成后，才会加载css，导致子应用之间切换出现卡屏现象

4. 在主应用的global.less中引入antd样式
@import '../node_modules/antd/dist/antd.less';
> 注意node_modules的路径，引入必须为less，这样才能使用umi的theme定制antd主题

这个external怎么生成的？
哈~
访问http://localhost:8000/umi.js.map，格式化后你可以看到所有umi的依赖，8000端口注意换成子应用的端口

**Comment by phobal** [comment]
@shengbeiniao 可不可以帮我把这个 demo https://github.com/phobal/antd-pro-microfe/tree/style-order-issue 按照你的那样配置一下呢？

我尝试了一下还是没有生效呢
