### ISSUE TITLE
> > > 同求，目前我的vue公共组件会报

### ISSUE THREAD

**Issue by jendy2012** [umijs/qiankun#1870]
> > > 同求，目前我的vue公共组件会报
> > > $attrs is readonly.
> > > $listeners is readonly.
> > > 这个错误，导致监听路由会失效
> > 
> > 
> > 我这边也出现了这个问题，请问解决了没？
> 
> +1 请问解决了吗
> +1 影响很大

_Originally posted by @bruce-le in https://github.com/umijs/qiankun/issues/1421#issuecomment-905394904_

**Comment by gongshun** [comment]
好像是因为安装的 `vue` 和 `vue-template-compiler` 的版本不一致？更新一下这两个依赖包

**Comment by jendy2012** [comment]
> 好像是因为安装的 `vue` 和 `vue-template-compiler` 的版本不一致？更新一下这两个依赖包

我现在这两个版本都是一样的。还是报错。

**Comment by hrcyx** [comment]
可以检查一下是否主应用和子应用重复注册了公共组件。

**Comment by Aolef** [comment]
同样情况，请问有解决方案吗

**Comment by zhangyingdong1995** [comment]
同样情况，请问有解决方案吗
