### ISSUE TITLE
手动加载子应用之后，切换到angular子应用卡死

### ISSUE THREAD

**Issue by ygh1** [umijs/qiankun#1872]
## 手动加载子应用之后，切换到angular子应用卡死
仓库地址
[github.com/ygh1/qiankun-example](https://github.com/ygh1/qiankun-example)

- **qiankun Version 2.6.3**:
- **node Version v16.13.1**:
- **Browser Version 最新google版本**:

**Comment by gongshun** [comment]
主应用把 `import 'zone.js';` 放在页面最上面就好了

https://github.com/ygh1/qiankun-example/blob/53749fe124251c5fbdf657e56deaca1e4cb0d5e6/main/src/main.js#L8

**Comment by ygh1** [comment]
已解决

> 主应用把 `import 'zone.js';` 放在页面最上面就好了
> 
> https://github.com/ygh1/qiankun-example/blob/53749fe124251c5fbdf657e56deaca1e4cb0d5e6/main/src/main.js#L8

谢谢，确实这样就解决了
