### ISSUE TITLE
[Bug]react子应用路由使用异步组件时，加载的组件chunk拆分js的publcPath不对，导致报错Unexpected token '<'

### ISSUE THREAD

**Issue by JanasLuo** [umijs/qiankun#1873]
## What happens?

问题如标题
子应用为cra创建的react项目，使用react-app-rewired修改相关webpack配置。项目路由不使用异步组件进行代码拆分时可以正常加载显示，使用react自带的lazy或者react-loadable进行异步加载路由页面进行代码拆分时，请求的chunk代码的js路径publcPath不对（变成基座的publcPath了），导致报错。按照官方文档public-path.js有添加和使用

## 最小可复现仓库
https://github.com/JanasLuo/admin-system/tree/qiankun-test

## 复现步骤，错误日志以及相关配置
复现步骤：
1、运行上面仓库的qiankun-test分支子应用
`yarn
  yarn start
`
根据实际子应用端口配置基座应用的entry地址。
2、主基座应用：
`
  registerMicroApps([
    {
      name: 'react app', // app name registered
      entry: '//localhost:3000',
      container: '#testMicroApp',
      activeRule: '/testMicroApp',
    },
  ])
`
基座是随便什么项目，子应用默认是3000端口，入口文件加载正确，路由组件的chunk代码加载路径不对：
![image](https://user-images.githubusercontent.com/25318710/146174594-f708d3fb-790e-4cac-a814-87f7b398a42e.png)
![image](https://user-images.githubusercontent.com/25318710/146174994-68eb0352-49ac-42a6-83a2-25870922ee78.png)

## 相关环境信息

- **qiankun** :版本2.6.3
- **浏览器版本** :chrome  96.0.4664.55
- **操作系统**：mac Catalina 10.15.7
- **webpack版本**： 4.44.2

**Comment by gongshun** [comment]
复现demo链接404

**Comment by wellhappy** [comment]
遇到了相同问题

**Comment by JanasLuo** [comment]
> 

基座应用用你自己随便什么项目，子应用yarn start以后根据 具体端口配置entry的端口。

**Comment by JanasLuo** [comment]
> 

基座应用用你自己随便什么项目，子应用yarn start以后根据 具体端口配置entry的端口。没有启其他服务应该是//localhost:3000

**Comment by JanasLuo** [comment]
> 复现demo链接404

基座应用用你自己随便什么项目，子应用yarn start以后根据 具体端口配置entry的端口。没有启其他服务应该是//localhost:3000

**Comment by JanasLuo** [comment]
> 复现demo链接404

不好意思 仓库权限问题 已开启public

**Comment by gongshun** [comment]
https://github.com/JanasLuo/admin-system/blob/37ab6ff594bfed7ecbe5cd8570666bb24a4f874c/src/public-path.js#L12

要按照文档写啊，eslint 报警告，给个注释就行了

![image](https://user-images.githubusercontent.com/29347231/146475488-d32f8da2-b7f1-4433-92bb-fd0ac04c4401.png)

**Comment by qq756585379** [comment]
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  // @ts-ignore
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
这个是加过的
