### ISSUE TITLE
子应用路由快速切换主应用路由，子工程的dom节点还在

### ISSUE THREAD

**Issue by wangyingjie123** [umijs/qiankun#1877]
## What happens?

浏览器直接输入子工程路由比如 www.baidu.com/children子工程还没完全加载完的时候点击切换到了主工程路由 www.baidu.com/parent 这时候子工程加载的dom节点还在，没有删除掉

## Context

- **qiankun Version**: 2.5.0
- **Platform Version**:  
- **Browser Version**: chrome 96

**Comment by wangyingjie123** [comment]
> 

内网链接，不支持发出来，可以加我QQ2969057196 方便讨论

**Comment by gongshun** [comment]
> 内网链接，不支持发出来，可以加我QQ2969057196 方便讨论

改一改官方demo，能否复现？

**Comment by wangyingjie123** [comment]
> > 内网链接，不支持发出来，可以加我QQ2969057196 方便讨论
> 
> 改一改官方demo，能否复现？

![image](https://user-images.githubusercontent.com/22096113/146932013-d3c96b97-ab7c-4ef8-b018-0acfc1d81151.png)

![image](https://user-images.githubusercontent.com/22096113/146932061-5ede5d78-7531-4454-8dc0-90242cf24e71.png)
然后就变成这样了，子工程html模版里的dom还在

**Comment by gongshun** [comment]
> 然后就变成这样了，子工程html模版里的dom还在

是手动加载的？https://github.com/umijs/qiankun/issues/1774

**Comment by wangyingjie123** [comment]
> > 然后就变成这样了，子工程html模版里的dom还在
> 
> 是手动加载的？#1774

是的，子工程dom还在，不是手动加载，是路由分发

**Comment by wangyingjie123** [comment]
> > 然后就变成这样了，子工程html模版里的dom还在
> 
> 是手动加载的？#1774

发现问题原因了：（禁用缓存的情况下）快速切换路由的时候子工程js未加载，没办法执行unmount生命周期，所以删除container节点，子工程的样式也无法卸载，可能会有样式污染。解决办法：fetch请求未完成或者evel未执行就切换路由的情况下删除子工程dom节点
