### ISSUE TITLE
重复使用loadMicroApp加载微应用失败

### ISSUE THREAD

**Issue by LvCoding112** [umijs/qiankun#1881]
## What happens?

  使用loadMicroApp的方式手动加载微应用，切换页面（路由），再返回微应用所在的页面，页面空白加载失败

## Mini Showcase Repository(REQUIRED)

 暂无

## How To Reproduce
1. 页面首次加载，切换到微应用所在的页面，页面加载成功
2. 切换到其他页面，然后返回微应用所在的页面，页面空白加载失败

## Context

- **qiankun Version**: 2.6.3
- **Platform Version**: macOs **10.15.7**
- **Browser Version**: Google Chrome  版本 96.0.4664.110（正式版本） (x86_64)

**Comment by gongshun** [comment]
有无报错？是否同一个问题 https://github.com/umijs/qiankun/issues/1734#issuecomment-947466824

**Comment by LvCoding112** [comment]
> 有无报错？是否同一个问题 [#1734 (comment)](https://github.com/umijs/qiankun/issues/1734#issuecomment-947466824)
感谢帮助，问题已解决，是同一个bug

**Comment by Lyan0505** [comment]
@gongshun  请问下怎么解决的
