### ISSUE TITLE
VUE3 主应用跳转到VUE2子应用，再从子应用跳转到主应用，跳转不过去问题

### ISSUE THREAD

**Issue by aylaSong** [umijs/qiankun#1882]
主应用VUE3+TS   
        路由模式history     "vue-router": "^4.0.0-0",

子应用VUE2
       路由模式 hash        "vue-router": "3.0.6",

子应用 VUE3+TS
        路由模式 hash      "vue-router": "^4.0.0-0",

主应用跳转到VUE2的子应用，再从VUE2的子应用跳转到主应用或是VUE3的子应用，路由报错。跳转不过去。路由是underfined.
![截屏2021-12-20 下午6 39 52](https://user-images.githubusercontent.com/95476345/146754427-0924a19f-aefe-4371-9c27-383066a20797.png)

VUE2 子应用的路由 
http://localhost:9090/vue#/alarm/alarms   不能和主应用和其他子应用之间相互跳转

VUE3 子应用的路由  
 http://localhost:9090/mafia#/report    主子应用之间可以相互跳转

两个子应用配置是一样的。
目测区别是VUE2的路由有多级，VUE3子应用路由只有一级，不知道是不是这个问题。求救大佬们指点一下。（不是这个问题，试了下，只有一层路由跳转也不行，一摸一样的报错）
![截屏2021-12-20 下午6 48 09](https://user-images.githubusercontent.com/95476345/146755481-a1bfb412-f2db-4a01-bcf1-8b83f183e01d.png)

**Comment by haixiangyan** [comment]
![image](https://user-images.githubusercontent.com/17061654/146767865-90512cbc-611b-48cd-adb5-cba2f059e016.png)

这里的 `undefined` 是不是有点关系？还有就是感觉少了一个 `/`？

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1361#issuecomment-904628940 重复

**Comment by aylaSong** [comment]
谢谢各位大佬，已解决。

**Comment by Lucky-HJ** [comment]
> 谢谢各位大佬，已解决。

请问怎么解决的 ，我现在也涉及到子应用跳主应用失败的问题

**Comment by hlwen** [comment]
> commented

这个配置记得加上
if (window.__POWERED_BY_QIANKUN__) { // 动态添加publicPath
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
