### ISSUE TITLE
loadMicroApp 加载失败后，再一次执行，并不会重新发起http请求，而是直接报错

### ISSUE THREAD

**Issue by falseLuffy** [umijs/qiankun#1885]
## What happens?

loadMicroApp 加载失败后，再一次执行，并不会重新发起http请求，而是直接报错

## Mini Showcase Repository(REQUIRED)
暂无

## How To Reproduce

将微应用服务停止 ，使用loadMicroApp 加载微应用，可以得到失败，然后将微应用重启，再次使用loadMicroApp 加载，此时不会发起新的请求，而是报错

## Context

- **qiankun Version**: 2.6.3
- **Platform Version**:window10
- **Browser Version**:Google Chrome 版本 96.0.4664.110（正式版本） (x86_64)

**Comment by ViavaCos** [comment]
所以，报错是什么，不能再次加载还是加载不到资源？感觉提供个报错信息可能更有利于解决问题。

**Comment by falseLuffy** [comment]
> 所以，报错是什么，不能再次加载还是加载不到资源？感觉提供个报错信息可能更有利于解决问题。

不能再次发起请求。

**Comment by XSnowHoly** [comment]
我也碰到这个问题，qiankun 官方是否可以考虑优化一下手动加载失败后的重试机制？

**Comment by dangc9** [comment]
你可以配置一个动态entry地址，比如：entry:  `http://localhost:8080/?timestamp=${new Date().getTime()}`

**Comment by falseLuffy** [comment]
> 

这样每次执行loadMicroApp都会重新请求资源，效率将会大大降低

**Comment by falseLuffy** [comment]
> 你可以配置一个动态entry地址，比如 entry: `http://localhost:8080/?timestamp=${new Date().getTime()}`


这样每次执行loadMicroApp都会重新请求资源，效率将会大大降低
