### ISSUE TITLE
怎样阻止微应用被切换时，微应用状态被缓存?

### ISSUE THREAD

**Issue by plrthink** [umijs/qiankun#1888]
## What happens?

怎样阻止微应用被切换时，微应用状态被缓存？

## 相关环境信息

- **qiankun 版本**
2.5.1
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
什么状态被缓存？数据还是 js 内容？

**Comment by plrthink** [comment]
不好意思，是我们自己代码导致的
