### ISSUE TITLE
循环嵌套的问题

### ISSUE THREAD

**Issue by jcsofts** [umijs/qiankun#1889]
主应用："umi": "^3.5.20",   "@umijs/plugin-qiankun": "^2.35.4",
子应用："vue": "2.6.12",
孙应用：主应用本身又是孙应用

目的是：
1. 主应用在/chat时调用子应用，
2. 子应用要复用主应用里的一个组件(组件用的dva做state )，因此，主应用又是孙应用

主应用qiankun配置
`qiankun: {
    master: {
      apps: [
        {
          name: "chatcloud",
          entry: "http://localhost:8800/app-chat/app/index.html",
          props: {
            enableUrl: `${PATH_INTEGRATION.integration.create}?type_provider_type_id=`,
          },
          //credentials: true,
        },
      ],
    },
    slave: {
      enable: true,
      shouldNotModifyDefaultBase: true,
      //shouldNotModifyRuntimePublicPath: true,
      shouldNotAddLibraryChunkName: true,
    },
  },`

子应用 用的qiankun loadMicroApp
` mounted(){
    loadMicroApp({
      name: 'crm-client',
      entry: '//localhost:8000/admin/dashboard/welcome/',
      container: '#crmContactDetail',
    });
  }`

问题：
在主应用里加载vue 子应用后，子应用加载孙应用的组件时一直出现
Uncaught (in promise) Error: [qiankun]: You need to export lifecycle functions in crm-client entry
![image](https://user-images.githubusercontent.com/33087222/147301862-bdadff47-4bca-4895-a435-a38a5c0d60bb.png)

支持这种使用方式吗？或者哪里配置有问题

**Comment by gongshun** [comment]
子应用复用主应用的组件，不需要在子应用手动加载主应用，主应用提供这个组件子应用直接使用即可。

- 如果是技术栈相同

    主项目入口文件：
    ```
    import HelloWorld from '@/components/HelloWorld.vue'
    window.commonComponent = { HelloWorld };
    ```
    子项目直接使用：
    ```
    components: { 
      HelloWorld: window.__POWERED_BY_QIANKUN__ ? window.commonComponent.HelloWorld :
         import('@/components/HelloWorld.vue'))
    }
    ```

- 如果技术栈不同

    主项目入口文件：
    ```
    window.createHelloWorld = container => {
      return new Vue({
        store,
        i18n,
        render: h => h(HelloWorld),
      }).$mount(container);
    }
    ```
    子项目直接使用：
    ```
    window.createHelloWorld('#appVueHash')
    ```

其实循环嵌套也不是不可以，只是很容易出问题。你这个报错就按照官网的常见问题来检查，应该能解决

**Comment by jcsofts** [comment]
>
