### ISSUE TITLE
开启strictStyleIsolation模式，子应用使用vant 样式不生效

### ISSUE THREAD

**Issue by leohai** [umijs/qiankun#1891]
## What happens?

当在shadowDom 里使用:root选择器声明css变量无法穿透出去
期望： 有什么方法能够达到声明有效呢，比如如何将vant源码中的选择器`:root`修改为选择器`:host`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
![image](https://user-images.githubusercontent.com/34530234/147340746-05c7bd79-2714-473b-9eac-a49209a4dd9b.png)
写了个简单模拟vant 的例子 如下
``` js
<body>
        <div id="root"></div>
</body>
<script type="text/javascript">
  let shadow = root.attachShadow({mode: 'open'})
  var para = document.createElement('p')
  var style = document.createElement('style')
  style.textContent = `
    :root{
        --vant-p-color: blue
    }
    .p-color {
      color: var(--vant-p-color);
    }
  `
  para.innerHTML = '这是一个p标签'
  para.classList.add('p-color')
  shadow.append(style)
  shadow.append(para)
</script>
```

## How To Reproduce
如图所示

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/pull/1061#issuecomment-826119150
