### ISSUE TITLE
子应用路由使用React.lazy()加载，会报错

### ISSUE THREAD

**Issue by qq756585379** [umijs/qiankun#1898]
## What happens?
const Home = React.lazy(() => import("../pages/Home"))，这样写会报错
import Home from "@/pages/Home"; 这样写不会报错

```
// import Home from "@/pages/Home";
const Home = React.lazy(() => import("../pages/Home"))

export function createRoutes() {
  const routes: RouteConfig[] = [
    {
      path: `/home`,
      component: (props: any) => (
        <React.Suspense fallback={<div/>}>
          <Home {...props} />
        </React.Suspense>
      ),
    }
  ]
  return routes
}
```

**Comment by gongshun** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/1873#issuecomment-996363126

**Comment by qq756585379** [comment]
if (window.POWERED_BY_QIANKUN) {
// eslint-disable-next-line no-undef
// @ts-ignore
webpack_public_path = window.INJECTED_PUBLIC_PATH_BY_QIANKUN;
}
这个是加过的
@gongshun

**Comment by qq756585379** [comment]
示例代码地址：https://gitee.com/756585379/qiankun，启动qiankun-main和app-front，页面点击nav0，里面有home和about两个按钮

**Comment by gongshun** [comment]
![image](https://user-images.githubusercontent.com/29347231/147637273-9335a148-a6a2-45b1-9e66-41c4d1874423.png)

这个文件你没有引入

**Comment by qq756585379** [comment]
😄，好吧，细节没注意到
