### ISSUE TITLE
微应用 vue 2.x 组件内css没有加载进来

### ISSUE THREAD

**Issue by zicheng-jscoder** [umijs/qiankun#1904]
主应用vue 2.x + elementUI+less,微应用vue 2.x + elementUI+scss，主应用正常、微应用路由界面渲染正常css预处理加载了，组件内css没加载出来

**Comment by zicheng-jscoder** [comment]
打包过后通过node部署

**Comment by wangi4myself** [comment]
查看资源请求路径是否正确
