### ISSUE TITLE
主应用报错，无法加载子应用的js文件

### ISSUE THREAD

**Issue by Blubiubiu** [umijs/qiankun#1905]
## What happens?

注册子应用后 主应用报错 [import-html-entry]: error occurs while executing entry script

single-spa.min.js:2 Uncaught TypeError: application 'vue-app111' died in status LOADING_SOURCE_CODE: Cannot assign to read only property 'dot' of object '#<Object>'

## Context

<img width="748" alt="企业微信截图_703d94a0-c78b-40e3-904b-a7855d809eff" src="https://user-images.githubusercontent.com/16317188/148005427-f8878814-8c9d-46d2-a88a-aeea8d2b444c.png">

<img width="628" alt="企业微信截图_262d1bba-b2c3-4140-876c-0a63473d0699" src="https://user-images.githubusercontent.com/16317188/148005612-53a5f62e-8d14-42c2-9a8e-0f3189c50202.png">

- **qiankun Version**:  2.6.3
- **Platform Version**: mac os 11.6.3
- **Browser Version**: chrome 96

**Comment by Blubiubiu** [comment]
我使用demo或者重新创建项目是ok的，现在问题是我将逻辑引入到公司项目中就会出现问题，可是项目过大，我也无法定位和排查到底问题出在哪里

<img width="827" alt="企业微信截图_a22d1837-0542-4801-ae57-ce5aec97075a" src="https://user-images.githubusercontent.com/16317188/148030265-9b520e48-2659-4d43-b1fe-41687eaf14d9.png">

目前定位是遍历到ENTITIES中的dot时就会出现报错导致子应用加载不成功

**Comment by Blubiubiu** [comment]
定位到问题了，无法兼容dot-js，是否有办法可以解决？
https://github.com/Blubiubiu/qiankun-demo/tree/main

**Comment by Blubiubiu** [comment]
不只是dot-js，好像很多js库都没有兼容，我在原项目中删除dot的引用还会有其他js导致同样错误报出

**Comment by gongshun** [comment]
不需要 `qiankun`，下面两行代码就能复现你的报错了
```js
import dot from 'dot-js';
window.dot = dot;
```
dot-js 自己限制了：

![image](https://user-images.githubusercontent.com/29347231/148042346-5967190a-c8c0-4dc8-a265-92ff78ab9cca.png)

`window.dot1 = dot;` 换个变量名，就会正常

**Comment by Blubiubiu** [comment]
可我在项目中去除dot-js引用后还是会有还是会有同样的报错，是否有方法能排查出其他的呢？

**Comment by Blubiubiu** [comment]
谢谢，变量名的更换需要放在哪里呢？我尝试在app.vue和main.js中添加都不起作用

**Comment by gongshun** [comment]
> https://user-images.githubusercontent.com/16317188/148005427-f8878814-8c9d-46d2-a88a-aeea8d2b444c.png

这个报错，如果有 sourceMap，点进去能看到报错位置

**Comment by Blubiubiu** [comment]
报错位置在node_modules包中，我这边在想办法解决吧，谢谢解答
