### ISSUE TITLE
主运用路径太重复能不能解决下吗

### ISSUE THREAD

**Issue by ithings-yill** [umijs/qiankun#1907]
子应用路由配置
![image](https://user-images.githubusercontent.com/43743313/148047112-8bb0e97d-6015-4fdf-bb33-57fe43d931a0.png)
主应用路由配置
![image](https://user-images.githubusercontent.com/43743313/148047294-6091f845-b8e6-4f7f-b568-951e8ab2ec18.png)
主应用的菜单路径
![image](https://user-images.githubusercontent.com/43743313/148047554-432ce95a-774c-4dff-a144-2af046e7e0d5.png)
最终浏览器显示
![image](https://user-images.githubusercontent.com/43743313/148047690-debd6fcb-3b7f-4ead-a1a6-1df86ccb4ad6.png)
这个路径太重复了：
![image](https://user-images.githubusercontent.com/43743313/148048322-7d4490e9-6e06-45b6-8eed-92afa060e828.png)
我希望：
主应用菜单配置：只要子应用的路由，一一对应就好了

**Comment by gongshun** [comment]
你注册子应用的路由不正确，应该使用路由 base，而不是子级加 path

**Comment by ithings-yill** [comment]
> 你注册子应用的路由不正确，应该使用路由 base，而不是子级加 path

开发不需要加base,我有判断（ base: process.env.NODE_ENV === 'production' ? '/main' : '/'）

我的问题在于，比如：
    子应用路由配置（/realState/dynamicMonitor）
    主应用路由配置（/realState） 
    主应用菜单配置（/realState/dynamicMonitor） 而不是（/realState/realState/dynamicMonitor）
最后浏览器地址：http://127.0.0.1:8001/realState/dynamicMonitor 
而不是现在的：http://127.0.0.1:8001/realState/realState/dynamicMonitor
我不知道表单清楚了没。

**Comment by gongshun** [comment]
主应用配置了 `/realState` ，子应用的路由就不需要 `/realState/dynamicMonitor`，直接 `/dynamicMonitor` 不就可以了

https://github.com/gongshun/qiankun-ant-design-pro-demo
