### ISSUE TITLE
子项目发布到测试环境Icon 图标不显示

### ISSUE THREAD

**Issue by aylaSong** [umijs/qiankun#1909]
乾坤最新版本 2.6.3
基座 VUE3.x.  elementPlus
子项目1: VUE2.X element 2.15.6

本地测试没问题，发布到测试环境，子项目用element icon图标不显示

![截屏2022-01-05 下午5 02 01](https://user-images.githubusercontent.com/95476345/148190143-55e196b6-ea07-44de-b6a0-2af0b456fc27.png)
正常情况下应该会有个大包后的CSS文件
![截屏2022-01-05 下午5 03 51](https://user-images.githubusercontent.com/95476345/148190484-47d64a39-f570-4fb7-871e-0431a07f8c52.png)
但是测试环境这个打包后的CSS文件获取不到
请教大佬给些思路

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

**Comment by aylaSong** [comment]
你发的链接我之前就看过了，不能解决我的问题，图片是没问题的，是用element 样式库自带的icon图标不显示

**Comment by aylaSong** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404
你发的链接我之前就看过了，不能解决我的问题，图片是没问题的，是用element 样式库自带的icon图标不显示

**Comment by gongshun** [comment]
是否开启了样式严格隔离？ https://github.com/umijs/qiankun/issues/736

**Comment by aylaSong** [comment]
> 是否开启了样式严格隔离？ #736

没有开启严格模式
![截屏2022-01-05 下午6 21 33](https://user-images.githubusercontent.com/95476345/148201595-4c7916f9-8670-45d2-be99-a45025e5d3b7.png)

**Comment by aylaSong** [comment]
> 你的 elementPlus 是用的 CDN 的文件，没有经过 webpack 打包？
> 
> elementUI 的字体图标打包后不生效很早就知道了，[https://github.com/umijs/qiankun/issues/217，](https://github.com/umijs/qiankun/issues/217%EF%BC%8C)
> 
> 因为 qiankun 把外链 css 改成了内联 css ，导致里面的相对路径的 css 路径错了，解决办法就是写死路径或者打包成 base64

好的，问题已经解决了，谢谢大佬。

**Comment by wlLeblanc** [comment]
怎么解决的？大佬
