### ISSUE TITLE
[ASK] UmiJS Qiankun Plugin

### ISSUE THREAD

**Issue by conioX** [umijs/qiankun#1914]
Hi, sorry create this thread here, 

I try qiankun with umijs plugin, but i want use credential "include" so i can send cookie to user

```
import { start } from 'qiankun';

start({
  fetch(url, ...args) {
    // Enable cors mode for the specified microapp
    if (url === 'http://app.alipay.com/entry.html') {
      return window.fetch(url, {
        ...args,
        mode: 'cors',
        credentials: 'include',
      });
    }

    return window.fetch(url, ...args);
  },
});
```

there is a method or config to send cookie with umijs plugin?

**Comment by gongshun** [comment]
https://umijs.org/plugins/plugin-qiankun#app

![image](https://user-images.githubusercontent.com/29347231/148711841-eb54156b-c0b2-42b0-8c31-256079398bf5.png)

**Comment by conioX** [comment]
thank you @gongshun :)
