### ISSUE TITLE
微应用 entry 时 cookie 未携带的问题，在项目路由跳转时，cookie还是无法携带

### ISSUE THREAD

**Issue by ryanmans** [umijs/qiankun#1919]
根据官网的配置，在手动注册微应用时，加上了fetch的自定义， 子应用在加载时，入口文件能够正常携带上主应用配置的cookie。但是在子应用内部，路由跳转时，请求资源，这个时候，cookie 无法携带

fetch的配置方式，直接复制官网案例的。         
return window.fetch(url, {
                    ...args,
                    mode: 'cors',
                    credentials: 'include'
                  })

**Comment by wohaiwo** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
踩了下坑 这里有个http 请求头的限制
得让后端在 nginx request header 添加一个 Access-Control-Allow-Credentials: true
