### ISSUE TITLE
微应用打包之后 md 檔無法正常展示

### ISSUE THREAD

**Issue by Bonnie8ni** [umijs/qiankun#1925]
## What happens?

微应用有使用 react-markdown 將 .md 檔案展現在網頁上，以作為網站 changelog 頁面

單開子應用時，可以正常顯示 md 檔內容，如下圖

![iShot2022-01-12 14 52 40](https://user-images.githubusercontent.com/15052151/149078417-39e47530-e8ea-47f9-9058-615e10c58b16.jpg)

但當主應用包覆子應用一起開起來時，會顯示 html，如下圖

![iShot2022-01-12 14 48 15](https://user-images.githubusercontent.com/15052151/149077967-3c6a9473-12e9-45c5-8010-1d1ac5faef37.jpg)

## Mini Showcase Repository(REQUIRED)

不知如何使用範例

## How To Reproduce

看 F12 感覺主應用開啟後會把子應用這段全部變成文字，想請問要怎麼避免這個問題

## Context

- **qiankun Version**: 2.5.0
- **react-markdown**: 7.1.2
- **Browser Version**: chrome 96.0.4664.110

**Comment by gongshun** [comment]
这是因为资源的路径错了吧，404返回了index.html的内容

**Comment by Bonnie8ni** [comment]
解決了
後來把檔案放在 public 下，位置直接指絕對路徑
已不會發生錯誤，謝謝 @gongshun
