### ISSUE TITLE
配合umi，异步加载入口，会导致第二次加载无法渲染子页面？

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [umijs/qiankun#1927]
umi主应用嵌套umi子应用，再次加载会导致无法渲染

由于需要异步加载入口，umi主入口被我改造成这样，刷新浏览器可以正常显示，但是切换路由回来就不能渲染了

![image](https://user-images.githubusercontent.com/32830366/149257287-26df54bb-62e4-44ae-b190-3cdaca482f82.png)

**Comment by WuBin88996** [comment]
请问此问题是否已解决
