### ISSUE TITLE
[Feature Request] 支持一个运行时同时有多个微应用在跑吗？

### ISSUE THREAD

**Issue by wued2017** [umijs/qiankun#193]
请问现在支持一个页面内，同时运行A、B、C、D几个微应用吗？

**Comment by mayako21126** [comment]
https://github.com/umijs/qiankun#-roadmap

**Comment by wued2017** [comment]
请问后面会支持吗？
关注过14届D2会议上有知分享说，会实现【多实例，⼀个运⾏时同时有多个 App Actived】

**Comment by kuitos** [comment]
2.0 支持，1月前后发布

**Comment by tianlizhao** [comment]
文章看完了, 写的很不错, 特别是 HTML Entry, 我一直在思考, 怎么做到子应该可以独立运行, 又可以被嵌入, 给了新的启发.
有两个地方不太明白,
1. 文章提出了在集成时, 可以选择两种
  a. 单实例, 一个运行时, 只有一个 App 启动
  b. 多实例, 一个运行时, 可以有多个 App 启动

  下面说到资源加载问题, "如果子应用中既有react15又有react16 .... 在运行时分析当前的子应用，最后可以决定真实运行时真正的消费到哪一个基础框架的版本..."
  如果是多实例, 这部分应该怎么解决呢? 

2. "蚂蚁提出了JS Sandbox机制，其中bootstrap、mount及unmount生命周期是子应用需要暴露出来的，因为子应用的整个生命周期都是被主应用所管理的，所以可以在主应用中给子应用插入各种拦截的机制..."

这部分是怎么做的?
如果有两个子应用同时存在, 又添加了两个全局变量 a, 应该怎么处理?
这种拦截机制应该怎么设计呢?

谢谢

**Comment by kuitos** [comment]
抱歉回复的有点晚..

问题 1 跟问题 2 背后的解决方案应该是同一个。
多实例场景同时又有多个不同 react 版本加载，这个问题是依赖新的沙箱机制的，具体思路就是所有子应用的全局变量变更都是在闭包中产生的，不会真正回写到 window 上，这样就能避免多实例之间的污染了，可以参考之前这里的讨论 https://github.com/umijs/qiankun/pull/130#issuecomment-549847590

**Comment by wued2017** [comment]
> 2.0 支持，1月前后发布
请问近期有发布2.0的计划吗

**Comment by kuitos** [comment]
3月底之前会发布 2.0
