### ISSUE TITLE
多微应用加载时页面及路由错乱甚至不显示内容

### ISSUE THREAD

**Issue by yangdan8** [umijs/qiankun#1930]
可重现仓库代码链接
https://github.com/yangdan8/qiankun-vite-demo.git

执行方式
```bash
pnpm examples:install
pnpm examples:start-multiple
```

重现步骤
点击页面中的About和Home进行切换

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%90%8C%E6%97%B6%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA%E5%BE%AE%E5%BA%94%E7%94%A8%E6%97%B6
