### ISSUE TITLE
[Bug]多子应用路由切换，实际跳转的路由地址与预期不符

### ISSUE THREAD

**Issue by zmzimpl** [umijs/qiankun#1938]
## What happens?
现有：
应用A - 路由1
应用A - 路由2

应用2 - 路由1
应用2 - 路由2

初始化时进入 应用A - 路由1
切换路由至 应用B - 路由1
切换路由至 应用A - 路由2，此时显示的界面的 应用A - 路由1 的界面，地址栏是 应用A - 路由2 的地址

基座没用使用路由，两个子应用都是 history

- **qiankun 版本**： "^2.6.3"
- **浏览器版本**：最新Chrome
- **操作系统**：Window10

**Comment by eachLee** [comment]
子应用里缓存的<router-view>加key区分了吗？

**Comment by zmzimpl** [comment]
> 子应用里缓存的加key区分了吗？

请问是在哪里的缓存加Key？

**Comment by eachLee** [comment]
> 
子应用里的router-view上
![image](https://user-images.githubusercontent.com/22219313/149726762-9eb1fbc5-b97d-4c25-ad0a-f834e06f8177.png)

**Comment by Manybin** [comment]
楼主怎么解决的呢，我也遇到这个问题了，添加key不管用

**Comment by ZzTaidhm** [comment]
请问是如何解决的呢？我也遇到同样问题  @gongshun

**Comment by eachLee** [comment]
vue-router版本的问题 升级到3.3.4之后就没有这个问题了

**Comment by ZzTaidhm** [comment]
> 

你好，我的应用1是react，应用2是vue，目前是react会出现此情况

**Comment by ZzTaidhm** [comment]
> vue-router版本的问题 升级到3.3.4之后就没有这个问题了

你好，我是应用A是react，应用B是Vue，刚升级了应用B的路由到3.3.4，依然失败。
跳转用的window.history.pushState(null, '', url)方式
现有：
应用A（react） - 路由1
应用A - 路由2

应用B（vue） - 路由1
应用B - 路由2

初始化时进入 应用A - 路由1
切换路由至 应用B - 路由1
切换路由至 应用A - 路由2，此时显示的界面的 应用A - 路由1 的界面，地址栏是 应用A - 路由2 的地址

基座没用使用路由，两个子应用都是 history

qiankun 版本： "^2.4.4"
浏览器版本：最新Chrome

**Comment by ZzTaidhm** [comment]
> > vue-router版本的问题 升级到3.3.4之后就没有这个问题了
> 
> 你好，我是应用A是react，应用B是Vue，刚升级了应用B的路由到3.3.4，依然失败。 跳转用的window.history.pushState(null, '', url)方式 现有： 应用A（react） - 路由1 应用A - 路由2
> 
> 应用B（vue） - 路由1 应用B - 路由2
> 
> 初始化时进入 应用A - 路由1 切换路由至 应用B - 路由1 切换路由至 应用A - 路由2，此时显示的界面的 应用A - 路由1 的界面，地址栏是 应用A - 路由2 的地址
> 
> 基座没用使用路由，两个子应用都是 history
> 
> qiankun 版本： "^2.4.4" 浏览器版本：最新Chrome
qiankun版本升级到2.6.3，还是不行😭

**Comment by gongshun** [comment]
> 基座没用使用路由，两个子应用都是 history

demo 发出来看看啊

**Comment by ZzTaidhm** [comment]
这个问题解决了，是因为我react子应用路由写的有问题，多谢大佬们围观且指点
