### ISSUE TITLE
[Bug]  umi2版本qainkun , 子应用开启gzip 后 报错，

### ISSUE THREAD

**Issue by bobsivian** [umijs/qiankun#1943]
## What happens?

父应用 ： umi2+@umijs/plugin-qiankun 1.7.1
子应用：antd pro 5 + @umijs/plugin-qiankun   2.35.4
当子应用在nginx 端 开启gzip 压缩 ，在父应用中访问时， 报错
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

------子应用关闭gzip 压缩访问正常--------------------
父应用 ： umi2+@umijs/plugin-qiankun 1.7.1
子应用：antd pro 5 + @umijs/plugin-qiankun   2.35.4   （不在nginx 端开启gzip ）
页面正常；
------------------父子应用都是 umi3 也正常----------------------------
如果父应用 子应用 都是antd pro 5 + @umijs/plugin-qiankun   2.35.4； 
即使子应用 开启 gzip 压缩 页面依然正常
----------------------------------------------------------------------------
由于老项目是umi2 编写，实在无法升级为umi3 , 希望能够帮忙处理下；

## 相关环境信息

- **qiankun 版本** @umijs/plugin-qiankun 1.7.1
- **浏览器版本**：chrome 最新版本
- **操作系统**：windows

**Comment by gongshun** [comment]
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

这是警告，一般警告不会导致页面显示异常

**Comment by bobsivian** [comment]
> > Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
> 
> 这是警告，一般警告不会导致页面显示异常

今天重新试了下已经正常加载了，昨天可能有缓存因素在、而且需要在修改为gzip 后， 父应用需要从新编译
