### ISSUE TITLE
qiankun 微应用使用 echarts 地图钻取时有明显卡顿现象

### ISSUE THREAD

**Issue by yl196356303** [umijs/qiankun#1944]
## 现状?

1.微应用独立运行时echarts地图钻取流畅
2.微应用嵌入qiankun，地图钻取时，有明显的卡顿
3.关闭 sandbox 就不会出现 2 描述的现象

## 最小可复现仓库

https://github.com/yl196356303/qinkun-echarts-demo

## 复现步骤，错误日志以及相关配置

1.qiankun加载子应用 http://localhost:8080/micro-app/
2.钻取地图出现明显卡顿
3.http://localhost:7071/ 独立运行微应用钻取地图很流畅
4.关闭 sandbox 就不会出现

## 相关环境信息

- **qiankun 版本**:  2.5.1
- **浏览器版本**：chrome  97.0.4692.71
- **操作系统**：windows 10
-**node版本**：v14.15.0

**Comment by renwofei423** [comment]
可以试试v2.0.26版本

**Comment by yangjie-web** [comment]
解决了吗  我也遇到了相同的问题

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
