### ISSUE TITLE
子应用CDN引用vue-echarts时，无法解析资源

### ISSUE THREAD

**Issue by ydobi** [umijs/qiankun#1946]
子应用采用CDN方式引入vue-echarts时，报错
<img width="1035" alt="WX20220121-101900@2x" src="https://user-images.githubusercontent.com/22515445/150454033-0442964f-9767-4d3b-b5fc-3e0b84364497.png">
排查原因是qiankun改变了脚本window指向，导致无法获取VueDemi属性
<img width="1017" alt="WX20220121-101832@2x" src="https://user-images.githubusercontent.com/22515445/150454014-5ccd3883-e759-4230-ac95-b8dd10865c2b.png">

**Comment by 992forever** [comment]
> 子应用采用CDN方式引入vue-echarts时，报错 <img alt="WX20220121-101900@2x" width="1035" src="https://user-images.githubusercontent.com/22515445/150454033-0442964f-9767-4d3b-b5fc-3e0b84364497.png"> 排查原因是qiankun改变了脚本window指向，导致无法获取VueDemi属性 <img alt="WX20220121-101832@2x" width="1017" src="https://user-images.githubusercontent.com/22515445/150454014-5ccd3883-e759-4230-ac95-b8dd10865c2b.png">

你好，我也遇到同样的问题，使用import ECharts from 'vue-echarts'引用时部署后就报错，请问你最后解决了吗？
