### ISSUE TITLE
qiankun与vue-router一起使用会造成路由守卫重复执行

### ISSUE THREAD

**Issue by yunlongduan** [umijs/qiankun#1948]
1.环境：vue3.2.16+vue-router4.0.12+qiankun2.6.3+vite2.6.4
2.复现代码：
`<router-view v-slot="{ Component }">
          <keep-alive :include="cacheList" :max="20">
               <component :is="Component" />
          </keep-alive>
  </router-view>
  <div id="container"></div>`
如上：<div id="container"></div>用于存放微应用的的盒子，搭配路由一起使用时会造成路由onBeforeRouteUpdate生命周期函数重复执行2次。

**Comment by gjfei** [comment]
同样遇到了

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1865 重复

**Comment by gjfei** [comment]
> 

又解决方案嘛？

**Comment by gongshun** [comment]
> 又解决方案嘛？

好像有一个临时方案？https://github.com/umijs/qiankun/issues/1750#issuecomment-973842262

**Comment by yunlongduan** [comment]
> 

暂时没找到

**Comment by Nikkolast88** [comment]
好像会先跳/micro/sub，然后在跳到/micro-sub/

**Comment by songdengwei** [comment]
我也遇到同样的问题，导致二级页面出不来，默认的首页可以出来

**Comment by nieyunfeng** [comment]
大佬是怎么解决的呀
