### ISSUE TITLE
异步chunk的window如何隔离？

### ISSUE THREAD

**Issue by zjlhope** [umijs/qiankun#1952]
qiankun目前的实现能隔离子应用入口chunk的window，但是子应用的异步chunk怎么隔离呢？
子应用被webpack打出的异步chunk，是在子应用运行过程中通过script异步加载下来浏览器自动执行的，这时候你没办法通过fetch手动加载他们，然后eval执行他们（此时通过提供sanbox给window)，进而没法对这些异步chunk的window进行隔离，请大神赐教~

**Comment by gongshun** [comment]
异步的 js ,如果是插入到 body 或者 head，也会被劫持的 https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend/common.ts
