### ISSUE TITLE
[Bug] 关于子应用 js chunk 按需加载，出现 Loading chunk 。。。failed

### ISSUE THREAD

**Issue by idujiawei** [umijs/qiankun#1953]
# 子应用 js 做了按需引入，会出现 Loading chunk 。。。failed

## What happens?
关于子应用 js chunk 按需加载，出现 Loading chunk 。。。failed

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置

子应用 js 是按需加载的，在主应用切换到子应用中，首次没有问题，子应用的静态资源文件，以及按需加载的 js 文件都会走 fetch 请求过来。

在该页面刷新，会出现 ` Loading chunk 。。。failed`，按需加载的js文件加载失败的错误，并且在 network 中可以看到这个 js 
 加载方式是 sctipt，不是走的乾坤的fetch，而是 app.js 的按需加载。

在这个页面强刷，不会出现上面的问题。

这个问题只有在完成部署的环境下出现，在开发环境下没有复现。
开发环境引用线上子应用地址，也不会复现。
只有线上主应用请求线上子应用才会复现

想请教一下，

1. 为什么强刷乾坤会拦截到按需加载的 js？而刷新拦截不到？
2. 为什么开发环境没有问题，而线上环境会出现这个问题

前端服务
我们的前端项目部署是nginx直接指向 index.html文件

## 相关环境信息

- **qiankun 版本**：2.6.3
- **浏览器版本**：chrome 最新
- **操作系统**：window10

**Comment by Bing0915** [comment]
同样觉得子应用 cdn 的vendors按需加载的时候 path 指定不是很明确  没有遵从资源指定的 http:// 路径 而是以当前 path 去查找资源😶‍🌫️😶‍🌫️😶‍🌫️

**Comment by StevenLikeWatermelon** [comment]
> 同样觉得子应用 cdn 的vendors按需加载的时候 path 指定不是很明确 没有遵从资源指定的 http:// 路径 而是以当前 path 去查找资源😶‍🌫️😶‍🌫️😶‍🌫️

这个问题 请问你解决了吗

**Comment by jiujiubanban** [comment]
> > 同样觉得子应用 cdn 的vendors按需加载的时候 path 指定不是很明确 没有遵从资源指定的 http:// 路径 而是以当前 path 去查找资源😶‍🌫️😶‍🌫️😶‍🌫️
> 
> 这个问题 请问你解决了吗

暂时通过主应用start()方法 正则匹配了异步资源 更改了加载路径

**Comment by dongongfeiyu** [comment]
同样的问题，麻烦问下解决了吗？

**Comment by ShiChenCong** [comment]
> 同样的问题，麻烦问下解决了吗？

我这边是通过动态配置`__webpack_public_path__ = process.env.PUBLIC_PATH` 解决了

**Comment by bowencool** [comment]
一样。
而且我自己复现不了，线上日志里经常有这些。

**Comment by StevenLikeWatermelon** [comment]
> > 同样的问题，麻烦问下解决了吗？
> 
> 我这边是通过动态配置`__webpack_public_path__ = process.env.PUBLIC_PATH` 解决了

__webpack_public_path__ = process.env.PUBLIC_PATH

这个写法和直接在vue.config.js里面写死publicPath有区别吗

**Comment by ShiChenCong** [comment]
> > > 同样的问题，麻烦问下解决了吗？
> > 
> > 
> > 我这边是通过动态配置`__webpack_public_path__ = process.env.PUBLIC_PATH` 解决了
> 
> **webpack_public_path** = process.env.PUBLIC_PATH
> 
> 这个写法和直接在vue.config.js里面写死publicPath有区别吗

我这边的场景是，publich path配置错误，导致load failed，后来定位到，是发布到线上的应用用的其他地址，需要动态设置

**Comment by chenchenwuai** [comment]
我遇到了同样的问题，找了两天问题，最后解决方法是： registerMicroApps里面子应用的entry最后的字符一定要加 “/”
<img width="881" alt="image" src="https://user-images.githubusercontent.com/32892396/170407800-b6856602-e647-47fb-99e3-9c63e6ff6210.png">
