### ISSUE TITLE
子应用如何跳转到主应用中的登录页面

### ISSUE THREAD

**Issue by Lucky-HJ** [umijs/qiankun#1955]
## Background

当子应用本地token 失效时 ，需要跳到主应用的登陆页面 重新登陆获取token

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BD%AC

**Comment by Lucky-HJ** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BD%AC

主应用和微应用都是 hash 模式，主应用根据 hash 来判断微应用，则不用考虑这个问题。这是官网给的，没有解释子应用跳主应用的方案。
我先需要从子应用跳转到主应用，我试了path 但是子应用中也有自己的登陆，这就很尴尬了？？？？？

**Comment by gongshun** [comment]
> 主应用和微应用都是 hash 模式，主应用根据 hash 来判断微应用，则不用考虑这个问题。这是官网给的，没有解释子应用跳主应用的方案。

子应用跳主应用一样的啊，也可以用主应用的路由实例或者 history 对象

**Comment by Lucky-HJ** [comment]
> 子应用跳主应用一样的啊，也可以用主应用的路由实例或者 history 对象

这里有个疑问啊，我如何在子应用代码中，获取主应用的路由实例？？？

**Comment by gongshun** [comment]
> 

![image](https://user-images.githubusercontent.com/29347231/153115377-d7ac0cde-0020-4e52-b0aa-bd3a354f1d8c.png)

主应用把路由实例挂在window上，子应用也能获取到，props 传给子应用也行

**Comment by Lucky-HJ** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/29347231/153115377-d7ac0cde-0020-4e52-b0aa-bd3a354f1d8c.png)
> 
> 主应用把路由实例挂在window上，子应用也能获取到，props 传给子应用也行

mainRouter.push({ path: '/login' }) 试过了，每次跳转都会跳到主项目的首页，搞得我很崩溃啊，求指教
