### ISSUE TITLE
在沙箱中使用defineProperty重新定义window上的属性时影响主应用中window的属性

### ISSUE THREAD

**Issue by peanutli** [umijs/qiankun#1958]
子应用中：
```js
Object.defineProperty(window, 'stop', {
  enumerable: false,
  writable: false,
  value: 1
})
```
主应用中：
`console.log(window.stop)`

现象：输出 1
期望：输出 stop 函数

**Comment by gongshun** [comment]
设计如此，https://github.com/umijs/qiankun/blob/8916dd2c2b3178b6d2927e6d214f6e276d544873/src/sandbox/proxySandbox.ts#L343
