### ISSUE TITLE
运用请教

### ISSUE THREAD

**Issue by LivySara** [umijs/qiankun#1959]
出现错误：
![image](https://user-images.githubusercontent.com/39461618/153378043-7ce6fc67-b244-466f-9feb-01fad51cb510.png)

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-while-xxx-mounting

**Comment by lyhzwf** [comment]
> 出现错误： ![image](https://user-images.githubusercontent.com/39461618/153378043-7ce6fc67-b244-466f-9feb-01fad51cb510.png)

除了官网上说的可能的错误，检查下你的主应用和子应用有没有使用document.write，如果有，删掉再试试

**Comment by Xiphap-China** [comment]
已经收到你的邮件，我会尽快给你回复～
