### ISSUE TITLE
qiankun安装报错

### ISSUE THREAD

**Issue by xiaoqufengdi** [umijs/qiankun#1965]
## qiankun 代码仓master分支
安装报错
 Cannot find module 'E:\temp\qiankun-master\node_modules\coa\compile.js'

需要在package.json里面指定命令行解析器的版本
  "resolutions": {
    "coa": "2.0.2"
  },

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/1969#issuecomment-1059910501 重复
