### ISSUE TITLE
[Feature Request] localStorage和sessionStorage的一些问题

### ISSUE THREAD

**Issue by gtdalp** [umijs/qiankun#197]
主系统A内嵌B和C子系统，当主系统A和子系统C用的是同一套框架，也就是localStorage和sessionStorage设置的key是一样的，当个我打开C子系统的时候，会把当主系统A已经设置的localStorage和sessionStorage覆盖掉，请问怎么解决？

**Comment by wusp1994** [comment]
localStorage 和sessionStorage是存在浏览器里面，是**_浏览器全局_**的当然会覆盖啊。

**Comment by kuitos** [comment]
同一套框架设置的值也会是一样的吧。

如果不一样，可以自己基于生命周期钩子做下手动的处理，比如子应用 unmount 时把 localStorage 改成之前主应用的值 https://github.com/umijs/qiankun/#registermicroapps

**Comment by gtdalp** [comment]
key是一样，每个子系统设置的值不一样，为了版本管理方便，所有的子系统跟主系统用的都是统一的一套框架，现在我的场景已经有10个子系统在接入到主系统，子系统还在不断增加，并且属于其他未知团队开发，不可能记录每个子系统的值吧。

**Comment by kuitos** [comment]
建议 key 之间用 namespace 区分，这样也比较合理。

实在不行在生命周期里做记录以及回滚的事情，写几行通用的代码就可以搞定，参考上面的回复。

**Comment by hzfvictory** [comment]
> 建议 key 之间用 namespace 区分，这样也比较合理。
> 
> 实在不行在生命周期里做记录以及回滚的事情，写几行通用的代码就可以搞定，参考上面的回复。

这样的话  如果一个页面同时展示多个子应用  还是有冲突的风险
