### ISSUE TITLE
主应用点击浏览器回退按钮回退到子应用，缺少子应用router-base

### ISSUE THREAD

**Issue by feelgooda** [umijs/qiankun#1971]
## 相关环境信息
- 主应用 vue3+vue-router4 + vite；
- 子应用 vue3 + vue-router4 + webpack;  子应用router-base: /app/go
- 路由模式history（使用hash没毛病，但是他们要求用history）；

## 复现步骤
- 1.打开主应用
- 2.点击跳转子应用
`
当前路径：http://localhost:3101/app/go/goWeb/productConfig/entry
控制台打印：window.history.state —— 
 {"back":null,"current":"/home/auth","forward":null,"replaced":true,"position":24,"scroll":null}
`
- 3.点击按钮返回主应用首页
`
当前路径：http://localhost:3101/home/auth
控制台打印：window.history.state —— {"back":"/home/auth","current":"/goWeb/productConfig/entry","forward":null,"replaced":true,"position":25,"scroll":null}
{"back":"/goWeb/productConfig/entry","current":"/home/auth","forward":null,"replaced":false,"position":26,"scroll":null}
`
- 4.点击浏览器回退
`
当前路径：http://localhost:3101/goWeb/productConfig/entry
控制台打印window.history.state
{"back":"/home/auth","current":"/goWeb/productConfig/entry","forward":"/home/auth","replaced":true,"position":25,"scroll":{"left":0,"top":0}}
`

- 5.浏览器返回的地址不对，缺少子应用的router-base: /app/go （ps:在子引用中点击浏览器前进，后退没问题，只出现在主应用回退为子应用，且路由模式为history）

**Comment by gongshun** [comment]
同一个问题，https://github.com/umijs/qiankun/issues/1865

**Comment by mzcc666GtHb** [comment]
遇到同样的问题了，请问怎么解决啊
