### ISSUE TITLE
[Feature Request] 子项目组件复用, 可否引用基座那一层的node_modules组件

### ISSUE THREAD

**Issue by a15218378694** [umijs/qiankun#1979]
## Background

现在很多子项目, 都用了类似的组件, 都是复制过去的, 导致有很多的重复代码

## Proposal

不知道该怎么处理代码冗余的问题

## Additional context

发npm包 ? 各个子项目引入, 还是直接引入基座那一层的包

**Comment by gongshun** [comment]
重复提交 https://github.com/umijs/qiankun/issues/1290
