### ISSUE TITLE
主应用和子应用都用angular12+ zorro, 在某些下拉框多的模态框打开后，页面非常的卡顿

### ISSUE THREAD

**Issue by haoyuerji** [umijs/qiankun#1980]
复现条件：
主应用和子应用都用angular12+ zorro, 
在某些下拉框多的模态框打开后，
页面非常的卡顿

第一：卡顿的问题是否可以解决？
第二：有一个不完美的解决方案：关闭sandbox后性能问题解决，但是关闭sandbox后导航无法跳转，浏览器前进后退也失效？

**Comment by renwofei423** [comment]
试试qiankun 2.0.26版本。

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
