### ISSUE TITLE
子应用之间切换报没导出生命周期函数

### ISSUE THREAD

**Issue by freewalker8** [umijs/qiankun#199]
## What happens?
vue技术栈，在portal注册了两个子应用，关闭了js sandbox，在切换子应用的时候被切入的子应用报没倒出生命周期函数，实际已倒出，刷新页面能正常加载出子应用，但路由跳转就报没导出生命周期函数的错误。
index.js:184 Uncaught mfe-admin: Application 'mfe-admin' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in mfe-admin entry
    at http://localhost:8000/vendors~app.js:5591:25
    at step (http://localhost:8000/vendors~app.js:18247:23)
    at Object.next (http://localhost:8000/vendors~app.js:18228:53)
    at fulfilled (http://localhost:8000/vendors~app.js:18218:58)
## Mini Showcase Repository(REQUIRED)

https://github.com/freewalker8/mfe-demo-qiankun/tree/develop-ie

## How To Reproduce

拉取代码，安装依赖包，运行npm run serve 启动portal，在子应用根目录运行npm run serve_mfe启动子应用，访问portal页http://localhost:8000/，打开控制台，在portal点击导航栏的日志管理即可复现错误

**Expected behavior** 
能导航到子应用，无报错
## Context

- **Platform**:
- **Browser Version**: Chrome 版本 79.0.3945.79（正式版本） （64 位）
- **Node Version**: v10.17.0

**Comment by kuitos** [comment]
webpack 配置按照这个来 https://github.com/umijs/qiankun/#webpack

```js
output: {
    library: `${packageName}-[name]`,
    libraryTarget: 'umd',
    jsonpFunction: `webpackJsonp_${packageName}`,
  },
```

对应你的代码[这里](https://github.com/freewalker8/mfe-demo-qiankun/blob/develop-ie/mfe-log/vue.config.js#L41)的配置需要改成 `${packageName}-[name]`
