### ISSUE TITLE
网络或其他原因导致子应用加载失败，无法手动重新加载

### ISSUE THREAD

**Issue by xioozq** [umijs/qiankun#1990]
## What happens?
使用loadMicroApp加载子应用，无法手动重新加载
------------------------------------------------------------------
Failed to load the subapplication using loadMicroApp and cannot be manually reloaded

## 复现步骤，错误日志以及相关配置
1. 关闭网络
2. 调用loadMicroApp加载子应用
3 加载失败后，没有可供重试的API
4. 此时卸载掉旧的实例再重新调用loadMicroApp， 并不会真的发出请求，而是把刚才加载的错误重新抛出了
------------------------------------------------------------------
1. Shut down the network
2. Call loadMicroApp to load subapplications
3 No API is available for retry after the loading fails
4. Uninstalling the old instance and calling loadMicroApp again does not actually issue the request. Instead, it rethrows the error that was just loaded

## 相关环境信息

- **qiankun 版本** 2.6.3
- **浏览器版本**： 98.0.4758.109
- **操作系统**：mac 12.1

**Comment by w578202450** [comment]
我也遇到了这个问题，大佬们能不能给个方案

**Comment by xioozq** [comment]
> 

修改源码， 跳过缓存

**Comment by xioozq** [comment]
> 我也遇到了这个问题，大佬们能不能给个方案

修改源码， 跳过缓存  @w578202450

**Comment by yinran100** [comment]
> > 我也遇到了这个问题，大佬们能不能给个方案
> 
> 修改源码， 跳过缓存 @w578202450

哪段源码

**Comment by xioozq** [comment]
> > > 我也遇到了这个问题，大佬们能不能给个方案
> > 
> > 
> > 修改源码， 跳过缓存 @w578202450
> 
> 哪段源码

src/api.ts > memorizedLoadingFn
