### ISSUE TITLE
使用axios自定义fetch ，response.text()  报错

### ISSUE THREAD

**Issue by FANZHETWO** [umijs/qiankun#1991]
##  我使用axios.get 方法自定义fetch，出现TypeError: response.text is not a function 的错误，见下图
![image](https://user-images.githubusercontent.com/22415838/156684220-a252a104-2ec0-44d4-807b-7f87860aa957.png)

##  重现代码如下
![image](https://user-images.githubusercontent.com/22415838/156684313-b6e3d880-6e8b-4d3f-b580-1a9a16cdc097.png)

##  报错代码定位，readResAsString  方法下的文本返回需要兼容下
![image](https://user-images.githubusercontent.com/22415838/156684434-d6365d4b-e956-4177-8225-4f959a4f2ed2.png)

## 相关环境信息

- **qiankun 版本**2.6.3
- **浏览器版本**： chrome 98.0.4758.102
- **操作系统**：

**Comment by gongshun** [comment]
自定义 fetch，你需要兼容 fetch 的使用，axios 和 fetch 是不一样的，如果你要用 axios 来自定义 fetch，你需要在返回的值中加入text 方法，例如：

```js
async fetch(url) {
    return instance.get(url).then(res => ({
      async text(){  return res }
    }));
 },
```

**Comment by FANZHETWO** [comment]
> 自定义 fetch，你需要兼容 fetch 的使用，axios 和 fetch 是不一样的，如果你要用 axios 来自定义 fetch，你需要在返回的值中加入text 方法，例如：
> 
> ```js
> async fetch(url) {
>     return instance.get(url).then(res => ({
>       async text(){  return res }
>     }));
>  },
> ```

大佬厉害
