### ISSUE TITLE
主应用加载子应用的部分静态资源异常时,希望兼容下异常资源而不是整个子应用都加载不出来

### ISSUE THREAD

**Issue by xiao-qi-l** [umijs/qiankun#1992]
### 问题
主应用加载子应用的部分静态资源异常时，会导致整个子应用都加载不出来(白屏)。
### 建议
建议主应用加载子应用资源时若出现异常，则针对这个文件进行异常处理，而不是整个子应用都加载不出来。

## 复现步骤，错误日志以及相关配置

具体场景是我们的一个子应用的静态资源被用户本地设置的dns劫持了。
举例：
使用任意一个本地电脑访问不了的资源都可以稳定复现；如：维基百科(https://zh.wikipedia.org/zh-hans/Wikipedia:%E9%A6%96%E9%A1%B5)
操作步骤：
在子应用的html中添加上如下代码：
<script type="text/javascript" src="https://zh.wikipedia.org/zh-hans/Wikipedia:%E9%A6%96%E9%A1%B5"></script>

## 相关环境信息

- **qiankun 版本**：2.5.1
- **浏览器版本**： 98.0.4758.109(chrome)
- **操作系统**：mac

**Comment by xioozq** [comment]
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E7%94%B1%E4%BA%8E%E8%BF%90%E8%90%A5%E5%95%86%E5%8A%A8%E6%80%81%E6%8F%92%E5%85%A5%E7%9A%84%E8%84%9A%E6%9C%AC%E5%8A%A0%E8%BD%BD%E5%BC%82%E5%B8%B8%E5%AF%BC%E8%87%B4%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by xiao-qi-l** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E7%94%B1%E4%BA%8E%E8%BF%90%E8%90%A5%E5%95%86%E5%8A%A8%E6%80%81%E6%8F%92%E5%85%A5%E7%9A%84%E8%84%9A%E6%9C%AC%E5%8A%A0%E8%BD%BD%E5%BC%82%E5%B8%B8%E5%AF%BC%E8%87%B4%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98

好的，谢谢🙏
