### ISSUE TITLE
从主应用里面，点击菜单切换子应用，第一次没问题，但是要是当前菜单在子应用，如果这个时候切换其他子应用会出现页面404

### ISSUE THREAD

**Issue by 1996zjun** [umijs/qiankun#1997]
描述：
点击菜单 进入 子应用A，然后点击菜单 进入子应用B， 这个时候按道理会根据路由去匹配进入子应用B，但是效果还是进入的子应用A，然后就出现了 页面404
按照官网例子，在子应用的unmount中已经卸载了内容。还是出现问题
![image](https://user-images.githubusercontent.com/23065551/158159096-751efe14-4e42-4ad0-9b21-6844e952b9c0.png)

**Comment by 1996zjun** [comment]
找到问题了。
![image](https://user-images.githubusercontent.com/23065551/158541085-84d0dd42-3c04-478e-85c6-a636af4d74a7.png)
去掉这一行就可以，但是还是有点不明白为啥会从子应用里面去匹配当前跳转的路由呢。 而不是应该先用主应用去匹配路由直接跳转

**Comment by liuye1296** [comment]
这是  qiankun  依赖  single-spa 这个库的问题

**Comment by 1996zjun** [comment]
现在出现了另外一个问题，跳转进入子应用的详情页面时候 （这个详情页面是子应用的静态路由） 出现404了，
