### ISSUE TITLE
基于vue框架hash模式，uniapp子应用页面不展示

### ISSUE THREAD

**Issue by joyji** [umijs/qiankun#1998]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

使用registerMicroApps加载子应用，主子应用都是hash模式，主应用为vue框架，子应用为在主应用的某个路由页面下加载，即在Layout组件下展示。子应用基于uniapp框架，在点击主应用菜单时，子应用不能显示
![Uploading 1647325873914.jpg…]()
![Uploading 1647325898380.jpg…]()

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- 最新
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#activerule-%E4%BD%BF%E7%94%A8-locationhash-%E5%8C%BA%E5%88%86%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by joyji** [comment]
> 

https://github.com/joyji/qiankun_demo.git 
master分支， 是在qiankun-vue-element-admin 中新增了基于uniapp的demo, 但是路由不到相关页面

**Comment by joyji** [comment]
> > 
> 
> https://github.com/joyji/qiankun_demo.git master分支， 是在qiankun-vue-element-admin 中新增了基于uniapp的demo, 但是路由不到相关页面

1. 造成uniapp看不到的原因找到了 ： 主应用的index.html中的id="app"; main.js挂载的el:"#app";App.vue中的id="app"，可能与uniapp中的id冲突了，我把主应用的app替换成appMain就可以访问了；
2. ！！！新的问题： 在主应用菜单栏中新建两个子应用相关菜单，/pages/index/index 和 /pages/editor/index 在切换的时候会造成主应用的页面刷新，这又是啥坑？🆘
