### ISSUE TITLE
Loading page Fixed at the top of screens

### ISSUE THREAD

**Issue by AnasAlamin** [umijs/qiankun#2003]
i'm using Qiankun with Antd, and i can access the micro app but there's loading page visible at the top of the screen and i couldn't seem to know how to remove it.
<img width="627" alt="Screen Shot 2022-03-18 at 17 02 53" src="https://user-images.githubusercontent.com/30214883/159017677-7d43bb93-a210-4580-96d0-556eade1a9e7.png">

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1217#issuecomment-766663132
