### ISSUE TITLE
[Bug] 弱网环境下子应用没有加载出来

### ISSUE THREAD

**Issue by wuhaohao1234** [umijs/qiankun#2006]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/35450336/159229783-47acd2ea-2830-44c7-a5ec-04ec64552c40.png">
qiankun框架是否可以对外暴露一个api,一个超时时间

**Comment by gongshun** [comment]
弱网只会影响文件请求，服务器设置超时时间就行了，然后用自定义 fetch 就可以捕获这个错误

**Comment by wuhaohao1234** [comment]
搞错了，其实是子应用挂载的dom没有销毁导致的问题
