### ISSUE TITLE
主工程，子工程都使用 umi 创建， 通过主工程加载子工程页面后，页面上的下载文件链接无法下载文件。 

### ISSUE THREAD

**Issue by defolly** [umijs/qiankun#2012]
通过主工程可以正常打开加载展示子工程的页面， js， css 文件 都没问题，但子工程 有一些 excel 模板文件需要下载，下载不成功。

![image](https://user-images.githubusercontent.com/10161473/160067660-391ca465-719a-4e6e-bb04-b6861330d8e0.png)

子工程的路径为 uc-permission-web, 通过 配置微应用 permission-web 加载子工程

通过 /permission-web/excel/xxx.xlsx 无法下载excel文件 

直接访问子工程路径   /uc-permission-web/excel/xxx.xlsx 是能下载的。

也就是 子工程 内部有下载链接，需要下载本工程内部的文件，点链接无法下载，我觉得应该是 fetch 的问题，但不知道怎样解决。

大家有遇到这个总问题吗？

**Comment by defolly** [comment]
主工程（基座工程） https://github.com/defolly/test-portal-web.git
子工程 （其中一个业务工程） https://github.com/defolly/test-uc-web.git

在实际项目中，主工程和子工程都是使用 history路由模式,  因部署静态在github上，调整子工程的路由为 hash

问题描述：子工程中有excel需要下载，通过主工程加载子工程的页面，无法下载文件

操作步骤：

1. 通过主工程入口： https://defolly.github.io/test-portal-web/
![image](https://user-images.githubusercontent.com/10161473/160351124-5739856b-d6f4-4f20-aee8-e95e167063d7.png)

2. 访问子工程的页面可以正常显示
3. 点导入按钮，弹出框，再点下载模板，无法下载文件
![image](https://user-images.githubusercontent.com/10161473/160351723-cd4b344e-e34a-49ee-a318-14abd0f549ee.png)

4.直接通过子工程入口： https://defolly.github.io/test-uc-web/#/user
  进行下载，是能正常下载的。
![image](https://user-images.githubusercontent.com/10161473/160353147-0751d5a6-fa16-43b3-86d6-d46e58b2c43f.png)

**Comment by jk4235** [comment]
```ts
const excelUrl = `${window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__}excel/xxx.xlsx`
```

**Comment by defolly** [comment]
> ```ts
> __INJECTED_PUBLIC_PATH_BY_QIANKUN__
> ```

谢谢，问题解决！
之前让开发人员直接写死项目号也能解决，但那种方式如果更改了nginx配置要改代码，没那么灵活

**Comment by zoushenglin** [comment]
有没有前辈遇到这样一种情况，子项目单独访问的时候，下载文件正常，通过主工程加载子工程页面后，载文件链接无法下载文件的情况，文件路径是网络路径
![image](https://user-images.githubusercontent.com/18183002/199382911-2b305e0b-6290-43a1-81b5-a57f2c2733a6.png)

**Comment by zoushenglin** [comment]
主项目和子项目都是vue3
