### ISSUE TITLE
Why antdesign component Cascader cannot use in sub-systems

### ISSUE THREAD

**Issue by taoqianbao** [umijs/qiankun#2018]
Why antdesign component Cascader not cannot use in sub-systems?

![image](https://user-images.githubusercontent.com/2980733/160550653-23202a8c-2b4b-45e7-8e48-b584a7195977.png)

but it can use without qiankun framework 

`<FormItem
              label="管理机构"
              name="orgIdGroup"
              {...formItemLayout}
              extra={`${enableEdit ? '请到组织机构树中修改' : ''}`}
              rules={[
                {
                  required: !enableEdit,
                  message: '请选择管理机构',
                },
              ]}
            >
              <Cascader
                disabled={enableEdit}
                loadData={this.onloadData}
                fieldNames={{ label: 'name', value: 'id', children: 'children' }}
                options={structureTreeOptions || []}
                changeOnSelect
                placeholder={`${enableEdit ? initOrgIdGroup.join('/') : '请选择管理机构'}`}
              />
            </FormItem>`

**Comment by szy1000** [comment]
我这边解决了！我的主框架用的vue 加入了ant-design-vue框架。 把主框架里面的ant-design-vue删除了 就好了。
