### ISSUE TITLE
js模块文件由js生成时，路径不对

### ISSUE THREAD

**Issue by Yukyi** [umijs/qiankun#202]
## What happens?

如果js文件路径不在html中，是由app.js生成的，比如当前端口7099，子应用是80，那app.js是80，但是js生成的文件是相对路径是7099端口的地址 http://localhost:7099/main.e31bb0bc.js 这个怎么解决
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**:
- **Browser Version**:
- **Node Version**:

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#why-dynamic-imported-assets-missing

**Comment by Yukyi** [comment]
vuecli中设置__webpack_public_path__无效 因为cli中会给webpack.config设置默认的publicPath:'',这个怎么解决 只能在子应用里把publicPath写死吗
