### ISSUE TITLE
当使用qiankun npm module时，react16项目热更新之后无法工作。examples cannot work when react16 hot reload actived, which use qiankun from npm module

### ISSUE THREAD

**Issue by xiaoyaozi1010** [umijs/qiankun#203]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**:
- **Browser Version**:
- **Node Version**:

**Comment by kuitos** [comment]
请不要重复开 issue
