### ISSUE TITLE
vue子应用中router实例初始化位置

### ISSUE THREAD

**Issue by xi5he5ha5a** [umijs/qiankun#2030]
![image](https://user-images.githubusercontent.com/38763105/162218836-74dfd0e2-6849-4c91-bac9-39c9625d91a5.png)

如图示例，在render中初始化router实例，那么当我要在store中使用router实例时，该怎么做呢qaq？
若是在main.js中导出router实例，由于运行顺序，store中也无法访问router实例。
router实例的使用就变得不是那么方便了。。还是说还得回到原本的实例化router方式

**Comment by gongshun** [comment]
把 store 中访问 router 的函数改写一下，导出一个函数，然后再实例化路由之后调用这个函数，函数参数是路由实例
