### ISSUE TITLE
[Bug] 子应用中 Promise 发生异常，不会触发 unhandledrejection 事件，导致无法全局捕获这类异常信息

### ISSUE THREAD

**Issue by weieyuan** [umijs/qiankun#2031]
## What happens?
在子应用中，全局监听 unhandledrejection 的事件并不会被触发，导致没法统一对这类异常进行处理。

例如在子应用中代码如下，unhandledrejection 事件不会被触发：
window.addEventListener('unhandledrejection', (event) => {
  console.log(event);
});

new Promise(() => {
  throw new Error('1233');
});

## 最小可复现仓库
任意子应用中都可以复现该问题

**Comment by gongshun** [comment]
测试了下，是正常触发的：

![image](https://user-images.githubusercontent.com/29347231/165665405-5c95ca63-db60-4ecc-b2c5-2377185454a4.png)

在子应用的 index.html 文件中插入如下代码：

![image](https://user-images.githubusercontent.com/29347231/165665460-74594660-26d7-4ee8-8635-a51e452e749b.png)
