### ISSUE TITLE
qiankun下大3D文件渲染很慢

### ISSUE THREAD

**Issue by heningyuan6256** [umijs/qiankun#2035]
## What happens?

我将一个3D文件的查看界面 https://github.com/kovacsv/Online3DViewer 变成了qiankun的 子项目，他是一个html项目，用nginx跑起来后，发现qiankun下大3D文件的渲染速度比单独启动慢一分钟

## Mini Showcase Repository(REQUIRED)

https://github.com/kovacsv/Online3DViewer

## How To Reproduce

https://github.com/kovacsv/Online3DViewer         子应用

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kshiw** [comment]
如果是loadMicroApp 试试 sandbox: false  速度有明显提升

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。

**Comment by Jadeee** [comment]
> released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。

加上页面就会报错
![image](https://user-images.githubusercontent.com/24861431/197318263-63884493-6187-4a2b-9b48-53a7e50a01c5.png)
