### ISSUE TITLE
在nextjs+react中使用qiankun当作主应用时报错 ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ClimbingLamb** [umijs/qiankun#2037]
#### 当我寻找解决办法时找到以下下解决办法

使用React Hook ==> 
```
useEffect( () => {
    registerMicroApps([]);
    start();
  },[])
```
但仍然不起作用

## Mini Showcase Repository(REQUIRED)

> [mini GitHub repository 最小复现库](https://github.com/ClimbingLamb/nextjs_qiankun.git).

## How To Reproduce

**Steps to reproduce the behavior:** 
1.npm install
2.[ 访问启动的应用](http://localhost:3000)

**Expected behavior** 
```
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:///Users/wenshi/Desktop/nextjs_qiankun/node_modules/import-html-entry/lib/utils.js (119:27)
Module._compile
node:internal/modules/cjs/loader (1101:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
Module.load
node:internal/modules/cjs/loader (981:32)
Function.Module._load
node:internal/modules/cjs/loader (822:12)
Module.require
node:internal/modules/cjs/loader (1005:19)
require
node:internal/modules/cjs/helpers (102:18)
Object.<anonymous>
file:///Users/wenshi/Desktop/nextjs_qiankun/node_modules/import-html-entry/lib/process-tpl.js (13:14)
Module._compile
node:internal/modules/cjs/loader (1101:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
```

## Context

- **qiankun Version**:
2.7.0
- **Platform Version**:
v16.13.1
- **Browser Version**:
100.0.4896.75（正式版本） (arm64)
- **operating system**:
macOS

**Comment by aurora-lch** [comment]
页面首次加载报错，路由跳转是没问题的。我用micro app也遇到过类似的问题，我用的nextjs14+ app router，官网有一段解释是
To optimize the initial page load, Next.js will use React's APIs to render a static HTML preview on the server for both Client and Server Components. This means, when the user first visits your application, they will see the content of the page immediately, without having to wait for the client to download, parse, and execute the Client Component JavaScript bundle.

应该是import qiankun 的时候客户端代码在服务端执行了
