### ISSUE TITLE
[Bug]https 缓存资源跨域问题

### ISSUE THREAD

**Issue by nightmaring** [umijs/qiankun#2041]
## What happens?
子应用访问第三方资源时候，服务器已经给添加了跨域头，此时可以正常访问，一段时间后，再次打开，资源读取的是缓存文件，会出现跨域头丢失的情况，造成子应用资源跨域显示空白。
![image](https://user-images.githubusercontent.com/18131312/163094948-b3599dcb-7833-444c-87d7-f91f01211145.png)
正常的时候。
![image](https://user-images.githubusercontent.com/18131312/163095183-03a2c099-6aa3-4e52-b2b1-d8d4a651b266.png)
错误的时候。

## 最小可复现仓库
子应用https，过一、两天就会出现。

## 相关环境信息

- **qiankun 版本**：v2.5.0
- **浏览器版本**：Google Chrome 100.0.4896.75
- **操作系统**：widnow10

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%96%87%E4%BB%B6%E6%9B%B4%E6%96%B0%E4%B9%8B%E5%90%8E%E8%AE%BF%E9%97%AE%E7%9A%84%E8%BF%98%E6%98%AF%E6%97%A7%E7%89%88%E6%96%87%E4%BB%B6

**Comment by nightmaring** [comment]
> [https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%96%87%E4%BB%B6%E6%9B%B4 %E6%96%B0%E4%B9%8B%E5%90%8E%E8%AE%BF%E9%97%AE%E7%9A%84%E8%BF%98%E6%98%AF%E6 %97%A7%E7%89%88%E6%96%87%E4%BB%B6](https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%96%87%E4%BB%B6%E6%9B%B4%E6%96%B0%E4%B9%8B%E5%90%8E%E8%AE%BF%E9%97%AE%E7%9A%84%E8%BF%98%E6%98%AF%E6%97%A7%E7%89%88%E6%96%87%E4%BB%B6)

资源文件没有更新也可以用这个吗

**Comment by gongshun** [comment]
> 资源文件没有更新也可以用这个吗

文件缓存相关的都是这个

**Comment by gongshun** [comment]
> 这样的话是不是一些需要缓存的资源文件也是每次都是最新的

百度一下：协商缓存和强缓存

**Comment by nightmaring** [comment]
> 

我尝试给html加了，但是css资源还是走缓存，我是不是应该给css加？

**Comment by nightmaring** [comment]
> > 这样的话是不是一些需要缓存的资源文件也是每次都是最新的
> 
> 百度一下：协商缓存和强缓存

我尝试给html加了，但是css资源还是走缓存，我是不是应该给css加？

**Comment by nightmaring** [comment]
已解决。
详情参考：[CORS规则](https://help.aliyun.com/document_detail/31870.html)
