### ISSUE TITLE
umi   dynamicImport  *.async.js 请求地址不正确

### ISSUE THREAD

**Issue by QDyanbing** [umijs/qiankun#2045]
主项目子项目都是umi。
部署方式采用 nginx,把html文件放到了服务器；js，css资源放到了oss上；

主项目加载子项目umi.xxxx.js资源时可以正常加载（从子项目oss地址加载）；
加载子项目的 *.async.js 这样的资源时加载地址指向了子项目部署地址 /*.async.js;不能正确的从oss上加载；
子项目已经配置了publicPath

**Comment by gongshun** [comment]
https://d.umijs.org/zh-CN/config#runtimepublicpath 设置为false

**Comment by QDyanbing** [comment]
感谢回答

**Comment by QDyanbing** [comment]
在子项目app.ts里加入window.resourceBaseUrl  这种是可以解决的，但是想问下具体的原因；看代码里这个src被改成了我 子项目部署的地址，并不会从oss去请求；
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/66234749/163307525-685fb4ed-8cc3-401a-95ea-9ae5067da87b.png"> 是qiankun主项目请求子项目资源时候改写了地址吗

**Comment by gongshun** [comment]
plugin-qiankun 默认开启了runtimePublicPath： https://github.com/umijs/umi-plugin-qiankun/blob/7c6e4cd96233b321e8dfd87f05a98f2adbd06a66/src/slave/index.ts#L35

然后注入了 window.publicPath： https://github.com/umijs/umi-plugin-qiankun/blob/7c6e4cd96233b321e8dfd87f05a98f2adbd06a66/src/slave/index.ts#L58

你们的HTML和js/css分开部署，正确应该是写死打包时的 publicPath，然后关闭 runtimePublicPath，就不会有问题.

如果你们用了 runtimePublicPath，那就需要配置 window.resourceBaseUrl ,这样就能拦截 qiankun 设置的 window.publicPath

**Comment by QDyanbing** [comment]
确实如此，我尝试去掉了resourceBaseUrl runtimePublicPath false是ok的；umi文档runtimePublicPath默认是false，一直以为是false；

**Comment by coderew** [comment]
@umijs/max使用的是4.0.0-rc.22,将runtimePublicPath:false,打包后的htm文件内容还有window.publicPath = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN呢？
