### ISSUE TITLE
react 17 为基站，打开angular13版本的微应用报错 In this configuration Angular requires Zone.js

### ISSUE THREAD

**Issue by baokeyu123** [umijs/qiankun#2048]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?
    main.ts:15 Error: In this configuration Angular requires Zone.js
    at new NgZone (core.mjs:25264:19)
    at getNgZone (core.mjs:26120:77)
    at PlatformRef.bootstrapModuleFactory (core.mjs:25996:24)
    at eval (core.mjs:26055:41)

需要在react主应用public中加入 zone.js脚本才能解决
![image](https://user-images.githubusercontent.com/37439789/163508313-367a5a33-a7d1-4ab8-a78c-eb3288b0d609.png)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.7
- **浏览器版本**：最新
- **操作系统**：Windows

**Comment by gongshun** [comment]
文档已说明 https://qiankun.umijs.org/zh/guide/tutorial#angular-%E5%BE%AE%E5%BA%94%E7%94%A8

![image](https://user-images.githubusercontent.com/29347231/164213448-7ce59410-613a-4f04-b948-4ec1b69abe6b.png)

**Comment by baokeyu123** [comment]
@gongshun 不可以，必须要在主应用里面加 zone.js包。才能运行起来。
