### ISSUE TITLE
angular老应用html entry方式接入，二次渲染报错

### ISSUE THREAD

**Issue by fengruiabc** [umijs/qiankun#205]
## What happens?

angular老应用html entry方式接入，二次渲染报错

## 最小可复现仓库

复现步骤已另外方式提交--钉钉

## 复现步骤，错误日志以及相关配置

1: 初始化渲染成功
2: 后续切回angular报错
![image](https://user-images.githubusercontent.com/20036035/71470421-0b701b80-2807-11ea-954b-fab2c86967a8.png)

## 相关环境信息
chrome

**Comment by kuitos** [comment]
$templateCahe 导致的

**Comment by LKCheng** [comment]
楼主的angular1.x 怎么接入的. 我这边接入后 子应用angular1.x（一直loading）没有报错
