### ISSUE TITLE
进入子应用再回到主应用切换动态路由时TypeError: Cannot read properties of undefined (reading 'appWrapperGetter')

### ISSUE THREAD

**Issue by babyzhu** [umijs/qiankun#2051]
主应用通过按钮点击手动加载子应用
html：
![image](https://user-images.githubusercontent.com/11517997/163957861-f1df3e93-0af4-4171-b3b7-1184508db6a3.png)

js：
showVue.value = true;
 loadMicroApp(child.doc.loadapp);
 start(); // 启动qiankun

子应用返回主应用切换动态路由，一直报TypeError: Cannot read properties of undefined (reading 'appWrapperGetter')
如何才能消除这个警告呢
还设有一个问题是主应用是quasar。
registerMicroApps这个会失效吗?

**Comment by gongshun** [comment]
同一个问题？ https://github.com/umijs/qiankun/issues/1238

**Comment by babyzhu** [comment]
解决了，离开子应用后，加了一个手动卸载

**Comment by youssef-mahdi** [comment]
Please can you describe how to do the manual uninstall ?

**Comment by httol** [comment]
> 解决了，离开子应用后，加了一个手动卸载

跟没说一样。

**Comment by lijun-wu** [comment]
> 

怎么解决得啊
