### ISSUE TITLE
[Feature Request] 微应用路由跳转

### ISSUE THREAD

**Issue by Zuojiangtao** [umijs/qiankun#2052]

**Comment by gongshun** [comment]
子应用的路由使用的是 abstract 模式吗？

**Comment by Zuojiangtao** [comment]
> 

子应用和主应用都是用了history模式

**Comment by gongshun** [comment]
> 子应用和主应用都是用了history模式

主应用跳子应用直接跳转就行啊，为啥需要子应用的路由实例

**Comment by Zuojiangtao** [comment]
> > 子应用和主应用都是用了history模式
> 
> 主应用跳子应用直接跳转就行啊，为啥需要子应用的路由实例

之前子应用跳父应用失败，我以为得按照网上的方法，把父应用路由实例传给子应用才行，现在我把子应用重定向注释掉就好了。

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BD%AC

**Comment by Zuojiangtao** [comment]
我没用官网的这2种方法，直接注释掉子应用的重定向就好了。

**Comment by YYL1999** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BD%AC

history.pushState() 不好使啊

**Comment by BTBMan** [comment]
设置了路由的base好像会问题啊 😢

**Comment by BTBMan** [comment]
history.pushState()的时候 第一个参数不要是false相关的值

**Comment by JefferyLiang520** [comment]
> 



> history.pushState()的时候 第一个参数不要是false相关的值就没问题了

我是vue子应用跳转react子应用，直接使用pushState(null, '', url)的形式 路由会先跳转到react子应用 然后又快速的跳转到vue子应用中来 并且将刚才的url直接拼到了vue子应用的路径后，按照你的说法改了就可行了，这是啥原因呢

**Comment by BTBMan** [comment]
vue-router里有个和这个相关的判断 但我是vue子应用之间跳转会出问题 跳转其他的技术框架相关的子应用好像没问题
