### ISSUE TITLE
主应用在懒加载其自身某个页面资源时，错误使用了微应用沙箱环境去fetch主应用资源

### ISSUE THREAD

**Issue by vchenpeng** [umijs/qiankun#2056]
## What happens?

使用qiankun注册微应用，在start函数上使用自定义fetch函数处理。后续再加载主应用下的资源时，注册子应用时的fetch函数被调用了。

## 最小可复现仓库

[https://github.com/vchenpeng/qiankun-demo](https://github.com/vchenpeng/qiankun-demo)

## 复现步骤，错误日志以及相关配置

先访问主应用内页面A，然后跳转至微应用中任意一个页面，再然后使用history.pushState跳转至主应用内页面B（此页面按需加载），即可复现。

重要：**如果在微应用路径下直接刷新，然后再跳转会主应用页面B（此页面按需加载），此时按需加载的主应用资源不会调注册时自定义的fetch，此时正常。**

附:
1. 为了方便识别加载的哪个fetch，我在加载子应用资源时的fetch函数中，在其header中增加了一个qiankun: 2.7.0
2. 主应用微应用均使用vue2.0
3. 最小可复现仓库根目录有录屏

## 相关环境信息

- **qiankun 版本**：2.7.0
- **浏览器版本**：100.0.4896.75（正式版本） (x86_64)
- **操作系统**：mac 10.15.6

**Comment by vchenpeng** [comment]
后续进展

**推断**：vue-router先触发加载异步资源，此时乾坤内部存在调用没有释放，导致这种情况。
**解决**：如果在主应用，其路由定义的beforeEach或beforeEnter中设置setTimeout(next, 0)，则问题不存在。
```
{
      path: "/sub/(.*)*",
      name: "sub",
      component: () => import(/* webpackChunkName: "sub" */ "@/sub.vue"),
      beforeEnter: (to, from, next) => {
          setTimeout(next, 0);
      }
}
```

**疑问**：
1. 这种处理未解决本issues标题的初心，主应用资源根本上就不应该触发微应用资源的fetch；
2. **issues中提到的这种场景暂无法解释**：如果在微应用路径下直接刷新，然后再跳转会主应用页面B（此页面按需加载），此时按需加载的主应用资源不会调注册时自定义的fetch，此时正常。

**Comment by chiaweilee** [comment]
https://github.com/umijs/qiankun/issues/2058 遇到同样的问题
主应用开启懒加载，从微应用返回主应用时，部分路由白屏。

直接访问主应用路由时，加载的内容是：

```
window.webpackJsonp ....
```

从微应用返回加载主应用路由时则是：

```
window.__TEMP_EVAL_FUNC__ = function(){;(function(window, self, globalThis){with(window){ window.webpackJsonp .... }
```

尝试修改了qiankun源码，避免使用 with(window){}，问题临时解决。

// import-html-entry
function getExecutableScript(scriptSrc, scriptText, proxy, strictGlobal) {
    const sourceUrl = isInlineCode(scriptSrc) ? '' : `//# sourceURL=${scriptSrc}\n`;
 
    // 通过这种方式获取全局 window，因为 script 也是在全局作用域下运行的，所以我们通过 window.proxy 绑定时也必须确保绑定到全局 window 上
    // 否则在嵌套场景下， window.proxy 设置的是内层应用的 window，而代码其实是在全局作用域运行的，会导致闭包里的 window.proxy 取的是最外层的微应用的 proxy
    const globalWindow = (0, eval)('window');
    globalWindow.proxy = proxy;
    // TODO 通过 strictGlobal 方式切换 with 闭包，待 with 方式坑趟平后再合并 
    // return strictGlobal
    return false  👈  改了这里，避免使用 with(window) {}
        ? `;(function(window, self, globalThis){with(window){;${scriptText}\n${sourceUrl}}}).bind(window.proxy)(window.proxy, window.proxy, window.proxy);`
        : `;(function(window, self, globalThis){;${scriptText}\n${sourceUrl}}).bind(window.proxy)(window.proxy, window.proxy, window.proxy);`;
}

**Comment by chiaweilee** [comment]
根据作者的最小可复现仓库：

![image](https://user-images.githubusercontent.com/29817353/165216334-34aef82f-6cab-4cf8-9fea-9304267febdc.png)

**Comment by vchenpeng** [comment]
```js
// qiankun内部patchDocumentCreateElement函数

Document.prototype.createElement = function createElement (tagName, options) {
  var element = rawDocumentCreateElement.call(this, tagName, options);

  if (isHijackingTag(tagName)) {
    // 这里_ref得到微应用沙盒还未释放
    var _ref = getCurrentRunningApp() || {},
      currentRunningSandboxProxy = _ref.window;

    if (currentRunningSandboxProxy) {
      var proxyContainerConfig = proxyAttachContainerConfigMap.get(currentRunningSandboxProxy);
      if (proxyContainerConfig) {
        // 👇 重点看这里：当微应用跳主应用页面，此时加载的element为script
        // 此时getCurrentRunningApp()得到的还是微应用，进而错误的使用沙盒环境加载资源
        elementAttachContainerConfigMap.set(element, proxyContainerConfig);
      }
    }
  }

  return element;
}; 
```

推断：qiankun中的render沙箱重写了document.createElement后，欠缺处理子应用切换回主应用环境场景的环境问题
补充：当然也可以start时设`sandbox: false`，但这种也并不是一个很好的解决方式

**Comment by vchenpeng** [comment]
解决方案：

在主应用入口优先加载`qiankun`，避免第三方路由管理器在`qiankun`加载前注册`popstate`、`hashchange `。[已提交pr faq]

**Comment by Leecason** [comment]
> sandbox

@vchenpeng 我从 React 子应用切到 React 主应用里也遇到这个问题了，请问一下在主应用里可以如何修复这个问题呢

**Comment by vchenpeng** [comment]
> @vchenpeng 我从 React 子应用切到 React 主应用里也遇到这个问题了，请问一下在主应用里可以如何修复这个问题呢

在主应用入口js内最顶部import { } from 'qiankun';

**Comment by gaofei019** [comment]
还是直接用qiankun配置主应用，尽量不要用umijs/qiankun插件了，坑太多

**Comment by Soo-For** [comment]
> > @vchenpeng 我从 React 子应用切到 React 主应用里也遇到这个问题了，请问一下在主应用里可以如何修复这个问题呢
> 
> 在主应用入口js内最顶部import { } from 'qiankun';

主应用为服务端渲染的项目，直接import { } from 'qiankun' 会报错（关于window）。
