### ISSUE TITLE
主应用控制下，在同一子应用下跳转，第一次会失败？

### ISSUE THREAD

**Issue by qq253498229** [umijs/qiankun#2057]
## What happens?

我的菜单在主应用里，现在在主应用里操作路由的跳转。
在第一次跳转到某一个子应用是正常的，但是接下来如果想跳转到同一子应用的其它懒加载模块就会失效，需要来回切换几次路由才会正常，并且之后该子应用下所有路由就都正常了。如果切换子应用再切换回来，又会失效，还是要重新切换几次。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/qq253498229/bug-repo-qiankun1

这个git仓库中fontend/app0-main是主应用，app1-shop是测试用的子应用，同时启动这两个即可重现。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.7.0
- **Platform Version**: angular 13.2.0
- **Browser Version**: MacOS 版本 100.0.4896.127（正式版本） (x86_64)

**Comment by qq253498229** [comment]
Uploading 屏幕录制2022-04-25 下午3.58.00.mov…

**Comment by qq253498229** [comment]
https://user-images.githubusercontent.com/31200516/165045964-43e37c46-d30b-4501-838a-eea60b0ab090.mov

**Comment by qq253498229** [comment]
貌似是我框架搭的有问题呢，我又重新搭了一遍就好了。。。我再对比一下哈

**Comment by youxinxie** [comment]
你好，我也遇到了这个问题，想请教一下，这个问题是如何解决的？拜谢

**Comment by qq253498229** [comment]
> 你好，我也遇到了这个问题，想请教一下，这个问题是如何解决的？拜谢

说实话我也不知道咋解决的哈哈哈，反正就是全删了从头重新搭，多弄几遍就好了。。。。

**Comment by youxinxie** [comment]
大佬，谢谢你的答复，我再尝试一下。
大佬，你们的angular项目用qiankun重构流程走通了吗？是否已经重构完成？我现在有点纠结了，感觉问题有点多，有点没有勇气尝试下去。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 主应用控制下，在同一子应用下跳转，第一次会失败？ (Issue #2057)





  
你好，我也遇到了这个问题，想请教一下，这个问题是如何解决的？拜谢
  
说实话我也不知道咋解决的哈哈哈，反正就是全删了从头重新搭，多弄几遍就好了。。。。

**Comment by qq253498229** [comment]
> 

走通了，https://github.com/qq253498229/qiankun-ng13-docker，这个是demo

**Comment by youxinxie** [comment]
感谢大佬，我来学习一下。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月26日(星期天) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 主应用控制下，在同一子应用下跳转，第一次会失败？ (Issue #2057)





   
走通了，https://github.com/qq253498229/qiankun-ng13-docker，这个是demo

**Comment by youxinxie** [comment]
大佬，非常感谢。按照你提供的demo，我这边也走通了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月26日(星期天) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 主应用控制下，在同一子应用下跳转，第一次会失败？ (Issue #2057)





   
走通了，https://github.com/qq253498229/qiankun-ng13-docker，这个是demo

**Comment by youxinxie** [comment]
大佬，可不可以加个微信或者qq，有问题想请教你一下。现在遇到一个问题是：开发环境正常，打包部署后会出现以下问题：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月26日(星期天) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 主应用控制下，在同一子应用下跳转，第一次会失败？ (Issue #2057)





   
走通了，https://github.com/qq253498229/qiankun-ng13-docker，这个是demo

**Comment by qq253498229** [comment]
> 大佬，可不可以加个微信或者qq，有问题想请教你一下。现在遇到一个问题是：开发环境正常，打包部署后会出现以下问题：
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "umijs/qiankun" ***@***.***&gt;; 发送时间:&nbsp;2023年2月26日(星期天) 下午2:51 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [umijs/qiankun] 主应用控制下，在同一子应用下跳转，第一次会失败？ (Issue #2057) 走通了，[https://github.com/qq253498229/qiankun-ng13-docker，这个是demo](https://github.com/qq253498229/qiankun-ng13-docker%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%98%AFdemo) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

qq253498229

**Comment by afc3liuyuan** [comment]
遇到了同样的问题，查不出来，已经奔溃了

**Comment by qq253498229** [comment]
> 遇到了同样的问题，查不出来，已经奔溃了

我在前几天升级angular得时候又遇见这个问题了，是webpack的问题，改用 `@angular-builders/custom-webpack`之后就好了，参考一下这个类的78行

https://github.com/qq253498229/qiankun-ng13-docker/blob/fc802368b0f06881245ddafd23438491818701f0/frontend/app1-shop/angular.json#L78
