### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by mango-lzp** [umijs/qiankun#206]
## What happens?
主应用为react应用，子应用为umi应用，在umi应用上   src/app.jsx  向外export 生命周期方法，umi应用直接挂掉。不知为何，望耐心指教。

## 最小可复现仓库
https://github.com/mango-lzp/qiankun-issue

## 复现步骤，错误日志以及相关配置
进入sub，yarn start。 如果app.jsx向外暴露方法，则启动的页面报错。
如需特殊配置，望告知。
## 相关环境信息

- **浏览器版本**：chorm 版本 79.0.3945.88
- **操作系统**：windows 10
- **Node 版本**：12.14.0

**Comment by kuitos** [comment]
umi 应用使用插件 https://github.com/umijs/umi-plugin-qiankun
