### ISSUE TITLE
应用部署后访问子应用 刷新后主应用文件引用变为子应用目录地址 导致页面报错

### ISSUE THREAD

**Issue by masansi** [umijs/qiankun#2061]
## What happens?
angular 基座 
子应用一个jq 三个angular
应用部署后访问子应用 刷新后主应用文件引用变为子应用目录 导致页面报错
这个问题在jq微应用里面是不会出现

## Mini Showcase Repository(REQUIRED)

无

## Context

https://user-images.githubusercontent.com/58510160/165472084-ee3e14a1-2200-4f8e-9272-0417ea220b38.mp4

- **qiankun Version**: 2.7.0
- **Platform Version**: angular 13.3.0

**Comment by masansi** [comment]
刷新前
![image](https://user-images.githubusercontent.com/58510160/165472473-87a60f9a-8975-4bbd-8707-88394aa4be1b.png)
进入子应用刷新后
![image](https://user-images.githubusercontent.com/58510160/165472723-f90ff943-6a50-4cbb-bf7f-3d3353302a81.png)

**Comment by gongshun** [comment]
主应用打包时需要将这些路径设置为相对路径，以 / 开头，相对于当前网站的根目录

**Comment by masansi** [comment]
> 主应用打包时需要将这些路径设置为相对路径，以 / 开头，相对于当前网站的根目录。例如，
> 
> ```
> <script type="text/javascript" src="/main.js"></script>
> ```
我修改了一下nginx配置 如果加载到404资源就重定向到根 ， 但是我觉得这个办法很蠢
