### ISSUE TITLE
主应用的两个菜单分别对应同一个子应用的两个路径，第一个子应用页面显示正常，第二个就无法显示，也没有报错

### ISSUE THREAD

**Issue by Lym-m** [umijs/qiankun#2062]
## What happens?

主子应用都是用的vue3+hash模式
我怀疑是我的路由配置有问题，但是两个子路由，无论先打开哪一个，另一个就无法显示。
主应用路由：
![image](https://user-images.githubusercontent.com/28731690/165660441-5e4cc788-3240-4403-9b06-a4e7c81db633.png)

子应用路由：
![image](https://user-images.githubusercontent.com/28731690/165660504-0e94174c-8d09-4df5-a6d5-855754f1f763.png)

页面情况：
![image](https://user-images.githubusercontent.com/28731690/165660793-09e1e7cf-4f2a-4ef0-9f65-9993a02839db.png)

![image](https://user-images.githubusercontent.com/28731690/165660825-5be7349e-9702-433d-87da-c3ab602a8426.png)

控制台里也没有报错信息，组件里打印的信息也成功打印了
![image](https://user-images.githubusercontent.com/28731690/165660916-aede9c22-2d3e-4d2d-ba70-fe8006df6fbc.png)

- **qiankun Version**: 2.3.2
- **Platform Version**: window10
- **Browser Version**: chrome

**Comment by gongshun** [comment]
可以参考下别人的demo：https://github.com/umijs/qiankun/issues/1777
