### ISSUE TITLE
部署后子应用空白

### ISSUE THREAD

**Issue by xxftop1** [umijs/qiankun#2063]
**报错信息： application 'sub-user' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in sub-user entry                       sub-user是子应用名称**

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
