### ISSUE TITLE
Uncaught SyntaxError: application 'vue app' died in status LOADING_SOURCE_CODE: Unexpected token '<'

### ISSUE THREAD

**Issue by linh0801** [umijs/qiankun#2066]
## What happens?
主应用点击激活子应用的链接时， 报错： app-errors.js?17fe:11 Uncaught SyntaxError: application 'vue app' died in status LOADING_SOURCE_CODE: Unexpected token '<'。
[已经按照官方处理类似问题的方法](https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry)，可结果，我遇到的问题依然还存在。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
[主应用 ](https://github.com/linh0801/qiankundemo)   [子应用](https://github.com/linh0801/qiankunsub)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.7.0
- **Platform Version**:主子应用都是借助vue cli 5.04 创建的
- **Browser Version**:

**Comment by gongshun** [comment]
https://github.com/linh0801/qiankundemo/blob/0bbb8ffb5a0fcbe01ed7ee33e199c712a2119ca4/src/main.js#L17 

这个写法是错误的，应该是 `entry: '//localhost:8888'`

**Comment by revfanc** [comment]
> 

有效
