### ISSUE TITLE
umi dva子应用卸载，控制台报错 Unexpected keys "@@dva", "global", "login", "settings" found in preloadedState argument passed to createStore 

### ISSUE THREAD

**Issue by Wster11** [umijs/qiankun#2068]
umi qiankun 子应用卸载dva数据 控制台报错

      app = getDvaApp()
     
      app._models.forEach((model) => {
        console.log(model, 'model')
        app.unmodel(model.namespace)
      }) 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/20762404/166876765-976e2c58-41e3-4cff-a23b-8ef2ea2e0585.png">

"@umijs/plugin-qiankun": "^2.35.2",
"umi": "^3.2.0",
"dva": "^2.4.0",

**Comment by 1474282816** [comment]
@Wster11 你好，最终找到原因或者解决办法了吗？我现在也遇到这个问题了，请问是怎么解决的

**Comment by Wster11** [comment]
> @Wster11 你好，最终找到原因或者解决办法了吗？我现在也遇到这个问题了，请问是怎么解决的

dev时的错误，打包到线上就没有了，没有处理
