### ISSUE TITLE
qiankun可以同一个页面加载多个不同路由的子应用吗？

### ISSUE THREAD

**Issue by mayefeng** [umijs/qiankun#2069]
qiankun可以同一个页面加载多个不同路由的子应用吗？
比如主应用路由是/home，它由两个子应用模块组成，一个子应用路由是/task/list另外一个子应用路由是/bi/release/id

**Comment by gongshun** [comment]
demo：https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

**Comment by mayefeng** [comment]
> demo：https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

我的意思是主应用同一个页面里包含两个子应用，主应用路由是/home，比如头部是A子应用路由是/task/list，底部是B子应用/bi/release/id

而demo是同一个页面切换两个子应用
