### ISSUE TITLE
主应用和子应用都使用browser，构建时却需要将子应用配置写成hash才行

### ISSUE THREAD

**Issue by viviprprpr** [umijs/qiankun#207]
主应用和子应用都使用browser，本地运行时没有问题，但是线上构建后子应用必须写成hash才能使用，主应用和子应用都使用hash时，子应用必须写成browser，请问这是什么问题

主应用配置：
![image](https://user-images.githubusercontent.com/40267580/71556410-52624900-2a73-11ea-9ba7-d9bb576567f1.png)

**Comment by kuitos** [comment]
请按照 issue 模板提问题
