### ISSUE TITLE
react  umi-qiankun 子应用页面关闭后之后再次打开 子应用的脚本不执行

### ISSUE THREAD

**Issue by WuBin88996** [umijs/qiankun#2070]
第一打开子应用页面没有问题  执行bootstrap> mount.... 页面关闭后执行unmount之后 再次打开子应用页面 该应用的脚本不执行

主应用 app.ts/qiankun
![image](https://user-images.githubusercontent.com/32702573/166894369-03075547-dc79-4aae-ad68-269fd9d950a8.png)

主应用 app.ts/patchRoutes
![image](https://user-images.githubusercontent.com/32702573/166894828-b51ba485-5860-4549-a4b3-a552d93d845b.png)

microAppPage
![image](https://user-images.githubusercontent.com/32702573/166894667-5064568d-89a2-4b77-92ea-3c62497a1172.png)

**Comment by gongshun** [comment]
再次加载只会执行 mount 函数，设计如此
