### ISSUE TITLE
主应用同一个页面里包含两个子应用，主应用路由是/home，比如头部是A子应用路由是/task/list，底部是B子应用/bi/release/id，可以实现吗？

### ISSUE THREAD

**Issue by mayefeng** [umijs/qiankun#2074]
> demo：https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

我的意思是主应用同一个页面里包含两个子应用，主应用路由是/home，比如头部是A子应用路由是/task/list，底部是B子应用/bi/release/id

而demo是同一个页面在两个子应用之间切换

_Originally posted by @mayefeng in https://github.com/umijs/qiankun/issues/2069#issuecomment-1118422410_

**Comment by gongshun** [comment]
你把布局换一下不就是了吗

![image](https://user-images.githubusercontent.com/29347231/167106489-6d48f74a-c81c-4ba2-aac1-b0df04b4cbad.png)

**Comment by mayefeng** [comment]
> demo 跑起来，如下图，你把布局换一下不就是了吗，同时展示2个子应用的不同页面，上下结构
> 
> ![image](https://user-images.githubusercontent.com/29347231/167106489-6d48f74a-c81c-4ba2-aac1-b0df04b4cbad.png)

谢谢，我切错分支了
