### ISSUE TITLE
重新mount微应用时由于缓存导致mountPromise状态有误

### ISSUE THREAD

**Issue by eightHundreds** [umijs/qiankun#2076]
https://github.com/umijs/qiankun/blob/7d1206e821717807183f9fcecd1fa3cb5cd20382/src/apis.ts#L134-L151

第149行。

场景: 
将一个微应用unmount后又重新mount，调用方依赖了loadMicroApp返回的mountPromise

由于这里的缓存，第二次mount时返回的mountPromise其实是第一次mount的mountPromise，这样调用方的.then回调会直接执行（实际上第二次mount正在运行中）

**Comment by gaofei019** [comment]
这个怎么解决

**Comment by kuitos** [comment]
这个跟缓不缓存没关系，你拿了前一次 loadMicroApp 的返回，这个肯定是有问题的。
正确的做法：
```js
const microApp1 = loadMicroApp(xxx);
microApp1.unmount();

// remount
const microApp2 = loadMicroApp(xxx);
microApp2.unmount();
```
