### ISSUE TITLE
实际项目中容器切换路由,销毁时报错Cannot access rules  

### ISSUE THREAD

**Issue by Yukyi** [umijs/qiankun#208]
## What happens?

demo没问题，但是用在实际项目中，路由切换中会在卸载当前子应用样式时出现问题：报错

Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
![微信截图_20191230175226](https://user-images.githubusercontent.com/40049627/71576951-42a73b00-2b2d-11ea-98c4-c6b985018f06.png)

报错后切换路由，html也不会被卸载了

未切换前的head:
![image](https://user-images.githubusercontent.com/40049627/71579156-4be8d580-2b36-11ea-86fd-e004ae62e055.png)
切换之后的head:
![image](https://user-images.githubusercontent.com/40049627/71579177-6327c300-2b36-11ea-850a-d3e2e0f96210.png)

貌似就卸载到了link之前的style

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Platform**:
- **Browser Version**:
- **Node Version**:

**Comment by kuitos** [comment]
qiankun版本升级到最新

**Comment by tdida** [comment]
@kuitos qiankun 更新到 1.3.10-1 还是报同样的错

**Comment by kuitos** [comment]
@tdida 提供一下可复现的仓库

**Comment by tdida** [comment]
@kuitos 对比了报错的代码，还是qiankun老版本的代码，应该本地依赖有问题

**Comment by tdida** [comment]
@kuitos 明明按照了 1.3.10-1 版本，执行代码还是1.3.9 的代码
