### ISSUE TITLE
导航栏写在基座，子应用内多个页面，页面切换出现问题

### ISSUE THREAD

**Issue by Liptid** [umijs/qiankun#2080]
## 问题描述

导航栏写在基座，子应用内多个页面，页面切换出现问题。路由点一次添加一次。

## 基座配置
![image](https://user-images.githubusercontent.com/24221312/167867527-7bd24b8e-84aa-40a8-a43b-06d9231356e6.png)
![image](https://user-images.githubusercontent.com/24221312/167867570-21e485b3-4bc3-4c47-9162-dd842909cc7a.png)
导航栏：
![image](https://user-images.githubusercontent.com/24221312/167867664-43f7ce7e-7209-4034-9659-213b3891f6a3.png)
## 子应用配置
![image](https://user-images.githubusercontent.com/24221312/167868679-87a806b2-2dcb-4e32-a9f2-ec1eba7cb21f.png)
![image](https://user-images.githubusercontent.com/24221312/167971420-0d8919cd-839e-491e-8614-0e4fba232e9b.png)
![image](https://user-images.githubusercontent.com/24221312/167971430-ec6580ed-cbec-4546-b96c-46ce7d3b39b4.png)

## 问题图片
来回切换异常。地址栏路由正常，刷新后可以正常加载页面，但是导航栏点击切换页面无效。line-product和app-home分别为两个页面的容器，被重复添加，重复添加，重复添加
![image](https://user-images.githubusercontent.com/24221312/167868187-d4e85829-7add-45a6-9863-98a2e5dd9223.png)

**Comment by 905868332** [comment]
怎样解决的啊

**Comment by maYunLaoXi** [comment]
解决了吗?
