### ISSUE TITLE
[Bug]Failed to run script `examples:install`

### ISSUE THREAD

**Issue by mulongjiangliu** [umijs/qiankun#2082]
## What happens?

Follow steps in `Examples` section README.md.
It throws bunch of errors while run `yarn  examples:install`.

![image](https://user-images.githubusercontent.com/16498016/168018774-ccab68a5-ba8f-4e68-b1a8-efe8a5f18cf3.png)

![image](https://user-images.githubusercontent.com/16498016/168018810-03df68d0-0d32-4c08-91dd-da12181b0be1.png)

## 最小可复现仓库

https://stackblitz.com/github/umijs/qiankun/tree/v2.7.0

## 复现步骤，错误日志以及相关配置
Follow steps in `Examples` section README.md.

## 相关环境信息

- **qiankun 版本** 2.7.0

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1969#issuecomment-1104842516
