### ISSUE TITLE
我们的项目使用了多实例的 qiankun，当打开两个来自同一个微应用 x 的页面 A 和 B 时，关闭页面 A，再打开微应用内的页面 A，被打开的页面并不能成功加载，展示空白

### ISSUE THREAD

**Issue by lfhwnqe** [umijs/qiankun#2084]
## What happens?

我们的项目使用了多实例的 qiankun，当打开两个来自同一个微应用 x 的页面 A 和 B 时，关闭页面 A，再打开微应用内的页面 A，被打开的页面并不能成功加载，展示空白
## 最小可复现仓库
https://github.com/umijs/qiankun/commit/bf755ed8bc81cb2157fb9a96a5fb25fa8641fd48

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/28968665/168509399-a8751089-eca5-47ce-9d85-546607a75cef.png)

## 相关环境信息

- **qiankun 版本**: 2.6.3/2.7.0 
- **浏览器版本**：chrome 101.0.4951.64（正式版本） (x86_64)
- **操作系统**：MACOS

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1734#issuecomment-947466824

**Comment by jiangdexiao** [comment]
> #1734 (comment)

2.4.4版本没有问题，2.4.4之后版本引入的新问题，到最新版本2.7.4版本现在都还存在这个问题

**Comment by mdchun** [comment]
> [#1734 (comment)](https://github.com/umijs/qiankun/issues/1734#issuecomment-947466824)
@gongshun 
子应用就算是卸载了也还是不行，只有锁定2.4.5的版本没有问题，之后的版本都有问题
