### ISSUE TITLE
[问题] 基座通过loadMicroApp加载子应用之后会报一个错

### ISSUE THREAD

**Issue by iDestin** [umijs/qiankun#2088]
## What happens?

基座通过loadMicroApp加载子应用之后会报一个错，基座和子应用都是react17搭建的。看报错应该是chunk里面的内容有问题，有大佬遇到过

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/36811055/168571315-5b292df8-604b-4cb0-b1e4-452844ad781c.png">

<img width="973" alt="image" src="https://user-images.githubusercontent.com/36811055/168571681-1173d483-cee8-452f-b5b7-ad70e8e49f8a.png">

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.5.0
- **浏览器版本**：chorme 100
- **操作系统**：macos 12

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1062#issuecomment-724410170

**Comment by iDestin** [comment]
> [#1062 (comment)](https://github.com/umijs/qiankun/issues/1062#issuecomment-724410170)

感谢大佬，问题得到了解决👍🏻
