### ISSUE TITLE
代码部署后，子应用只有第一次可以访问，再访问时报错

### ISSUE THREAD

**Issue by viviprprpr** [umijs/qiankun#209]
## What happens?

代码部署后，子应用只有第一次可以访问，再访问时报错，报错信息如下

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/40267580/71582589-dab11e80-2b45-11ea-9b1a-f23ef68c9a24.png)

## 相关环境信息

- **浏览器版本**：
- **操作系统**：
- **Node 版本**：

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by kuitos** [comment]
关了，如果有可复现的仓库请随时reopen
