### ISSUE TITLE
mac Safari下报错 [import-html-entry]: error occurs while executing entry script http://cutler-dev.eimos.com/js/app.2826c421.js

### ISSUE THREAD

**Issue by mayefeng** [umijs/qiankun#2090]
mac Safari下报错 [import-html-entry]: error occurs while executing entry script http://cutler-dev.eimos.com/js/app.2826c421.js

chrome没有问题

![lALPJxRxRnS6nWLNAwbNCbI_2482_774 png_720x720q90g](https://user-images.githubusercontent.com/25976176/168581947-8adc88dd-4c6d-4d7a-aa22-e829b8e2f8f7.jpg)

**Comment by pefecter** [comment]
我也遇见了  不过我是chrome也有问题  有咩有解决
