### ISSUE TITLE
Set window.event while sandbox destroyed or inactive in umiDemo-[name]! 

### ISSUE THREAD

**Issue by tiger-24** [umijs/qiankun#2092]
主应用vue+qiankun
操作如下：
1、首次进入umi子应用，正常
![image](https://user-images.githubusercontent.com/50128214/168985717-81577e8b-1ab9-4356-9e86-f4f01c7bc447.png)
2、离开umi子应用，报警告。
![image](https://user-images.githubusercontent.com/50128214/168986123-e33f6575-585f-4696-80a0-6bb5c9c12343.png)
3、再次进入umi子应用， 报错
![image](https://user-images.githubusercontent.com/50128214/168986482-cef1351b-ceb2-4b8d-b71e-c1825f1b9d7a.png)
4、在修改umi子应用中的dom， 报错
![image](https://user-images.githubusercontent.com/50128214/168986823-38f619b9-2879-4d1a-be5d-90a34888a7d6.png)
 急急急 ！！！ 求大佬指点

- **qiankun Version**: 2.7.0
- **@umijs/plugin-qiankun Version**:2.37.2

**Comment by ganluren007** [comment]
@tiger-24  你好，我在使用过程也遇到和你一样的问题，麻烦问下你这个问题有解决了吗？有的话是如何解决的
