### ISSUE TITLE
子应用public下静态资源问题

### ISSUE THREAD

**Issue by jiaicon** [umijs/qiankun#2096]
子应用使用ant design pro搭建，放在public下的静态资源，在主应用中打开时，还是从根路径获取，导致获取不到。
![image](https://user-images.githubusercontent.com/34124517/169436355-e3f4cb31-f4e4-4336-b0fb-39d6aedea013.png)
我试着配置了publicPath跟runtimePublicPath，结果也不行，也尝试了public-path.js的方案，也没生效。
希望可以自动加上子域名或其他方法可以加载到。
具体的情况可以看这里：https://segmentfault.com/q/1010000041046676
子应用还需要配置什么吗？

**Comment by gongshun** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/654

public下的资源不会经过 webpack 打包，不会注入 publicPath，所以无解，要么放到src目录，要么上传到服务器，用绝对路径引入
