### ISSUE TITLE
项目在本地跑的时候没有问题，部署到nginx 之后，刷新出现No input file specified.

### ISSUE THREAD

**Issue by daihaoxin** [umijs/qiankun#21]
如题，目前的情况好像是不能刷新，刷新后就找不到引导文件了，在webpack跑dev-server的时候是正常的，有没有同学遇到过类似的问题

**Comment by kuitos** [comment]
提供一下可复现的 repo？

**Comment by kuitos** [comment]
closed via deactivated, if your problem not solved, feel free to reopen

**Comment by wusp1994** [comment]
能提供下，你是怎么部署的吗？为社区做下贡献

**Comment by wusp1994** [comment]
不用了，谢谢。可以部署成功运行

**Comment by JqiangLiu** [comment]
> 不用了，谢谢。可以部署成功运行

老哥,能给个部署demo么.发到我邮箱也行,794753235@qq.com
