### ISSUE TITLE
[Feature Request] antd pro 作为基座应用

### ISSUE THREAD

**Issue by duwei54** [umijs/qiankun#210]
我看了文档和api,没有弄懂怎么把一个andpro项目作为父应用.
我想父应用可以:
1.统一登录
2.统一左侧菜单管理
3.统一header和footer.
子应用也是umi+antd的应用:
1.只负责中间内容区显示.
2.暴露出多个路由

**Comment by Hades-li** [comment]
我就把原本是基于vue-admin-element框架的项目，利用qiankun，改造成了你说的这种微前端，踩了无数的坑。
大坑会集中在路由，子项目的缓存，tag标签的处理上。
总结，这种中后台管理项目，个人认为没必要上微前端。上的原因是为了自身企业项目管理上变得方(geng)便(jia)而(dan)已(teng)。领导说要拆分项目。结果办法就只有两个，要么iframe，要么微前端。我拒绝了iframe。

**Comment by duwei54** [comment]
@Hades-li 厉害了,我都不知道如何下手.看到飞冰团队的这个[ice-lab方案](https://github.com/ice-lab/icestark) 感觉成熟点呢.

**Comment by Hades-li** [comment]
[ice-lab方案](https://github.com/ice-lab/icestark)之前也看了，可惜，差了一点，他们的方案中没有提供tag标签这个组件。就是有了这个tag组件，整个项目就蛋疼了非常多，并且没有成熟方案可以利用。因为，有了这个tag标签，子项目和外框项目之间就需要增加数据，事件交互，比如，tag的增加，关闭，名称变更，刷新页面，缓存子项目的状态（子项目不能被销毁）等等。前提，这还是建立在父框架和子项目用的都是同一个技术栈。如果是vue,react等单页应用技术栈混用。那么坑的数量还将增加。

**Comment by kuitos** [comment]
tag标签是啥

**Comment by duwei54** [comment]
@kuitos 我猜应该是之前中后台比较常见的Tab页设计吧

**Comment by Hades-li** [comment]
> @kuitos 我猜应该是之前中后台比较常见的Tab页设计吧

是的。

**Comment by Estelle00** [comment]
@Hades-li 我也使用的vue-admin-element这个项目改造的 卡在了 主应用样式影响子应用的问题和公用包提取公用问题

**Comment by kevinPFish** [comment]
@duwei54 老哥已经实现了吗？

**Comment by duwei54** [comment]
@duwei54 放弃了!主要是没时间精力来搞.我是搞后端的 😂

**Comment by dbkillerf6** [comment]
> [ice-lab方案](https://github.com/ice-lab/icestark)之前也看了，可惜，差了一点，他们的方案中没有提供tag标签这个组件。就是有了这个tag组件，整个项目就蛋疼了非常多，并且没有成熟方案可以利用。因为，有了这个tag标签，子项目和外框项目之间就需要增加数据，事件交互，比如，tag的增加，关闭，名称变更，刷新页面，缓存子项目的状态（子项目不能被销毁）等等。前提，这还是建立在父框架和子项目用的都是同一个技术栈。如果是vue,react等单页应用技术栈混用。那么坑的数量还将增加。

我理解这种问题，基于 custom event 实现一个 event bus 就可以了吧

**Comment by kuitos** [comment]
closed via inactive

**Comment by GreatAuk** [comment]
> 基于vue-admin-element框架的项目，利用qiankun，改造成了你说的这种微前端，

`vue-element-admin` 上有遇到这个问题吗
![image](https://user-images.githubusercontent.com/20253809/82422834-8affcf00-9ab5-11ea-9785-2e77f0a8e095.png)
