### ISSUE TITLE
vue主应用挂载vue子应用，刷新不显示，每隔一分钟再刷新才正常显示

### ISSUE THREAD

**Issue by Chonglin-X** [umijs/qiankun#2102]
**环境：**
1、主应用和子应用都是vue3
2、主应用是若依脚手架的vue3
**问题：**
创建两个vue-cli，配置一个主一个子，可正常显示，把主切换成若依的vue，刷新不显示，每隔一分钟再刷新才正常显示
**报错：**
Error: application 'vue-test-1' died in status LOADING_SOURCE_CODE: [qiankun]: Target container with #vue3 not existed while vue-test-1 loading!

**Comment by Chonglin-X** [comment]
操作步骤按照官网，未做改动

**Comment by Chonglin-X** [comment]
> https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-while-xxx-loading

看到这个了，请问大佬，调整 start 函数调用时机是怎么调呢，不管start方法在什么地方，结果都不变

**Comment by gongshun** [comment]
那就说明你的容器放在了路由页面，得参考这个

https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8

PS: Vue3的路由写法变了，文档实例是Vue2的

**Comment by Chonglin-X** [comment]
> > > https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-while-xxx-loading
> > 
> > 
> > 看到这个了，请问大佬，调整 start 函数调用时机是怎么调呢，不管start方法在什么地方，结果都不变
> 
> 那就说明你的容器放在了路由页面，得参考这个
> 
> https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E5%9C%A8%E4%B8%BB%E5%BA%94%E7%94%A8%E7%9A%84%E6%9F%90%E4%B8%AA%E8%B7%AF%E7%94%B1%E9%A1%B5%E9%9D%A2%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8
> 
> PS: Vue3的路由写法变了，文档实例是Vue2的

谢谢大佬讲解，我试一下
