### ISSUE TITLE
[Bug] yarn examples:install 失败

### ISSUE THREAD

**Issue by snaketzy** [umijs/qiankun#2126]
## What happens?

![image](https://user-images.githubusercontent.com/8423335/171124096-98eed92d-d7b5-46a4-bf82-5a0a04af7af1.png)

## 最小可复现仓库
本repo， master分支

## 复现步骤，错误日志以及相关配置
yarn install
yarn examples:install

angular9

## 相关环境信息
yarn@1.22.19
node@14.18.2
uplink@https://registry.npmmirror.com/,https://mirrors.cloud.tencent.com/npm/

**Comment by gongshun** [comment]
报错已经很明显了，网络问题，连接失败
