### ISSUE TITLE
子应用出错信息优化

### ISSUE THREAD

**Issue by huyansheng3** [umijs/qiankun#213]
## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

目前子应用如果出错，调用的eval(window.proxy)，这样错误信息全到eval这里了。有时候很不好查出问题所在

**Comment by kuitos** [comment]
可以展开错误堆栈跟到子应用报错的行，开发环境也可以通过给子应用打 sourcemap 解决，参考 https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L74

**Comment by yuyic** [comment]
@kuitos 必须要展开才可以看到报错行吗？但这样就无法将报错行上传到类似sentry这样的日志管理工具上

**Comment by yuyic** [comment]
@kuitos 另外，子应用包裹了错误边界后就无法再通过展开堆栈找到错误行了
