### ISSUE TITLE
import-html-entry]: error occurs while executing entry script

### ISSUE THREAD

**Issue by wgod9527** [umijs/qiankun#2139]
import-html-entry]: error occurs while executing entry script

**Comment by wgod9527** [comment]
资源可以打开，却一直报这个错

**Comment by gongshun** [comment]
所有的这种报错第一句都是 [import-html-entry]: error occurs while executing entry script ，这仅仅是提示报错位置，第二句才是真正的错误。

**Comment by wgod9527** [comment]
> 所有的这种报错第一句都是 [import-html-entry]: error occurs while executing entry script ，这仅仅是提示报错位置，第二句才是真正的错误。

"Uncaught ReferenceError: application 'vue-micro-app' died in status LOADING_SOURCE_CODE: antd_4c6f69efc7a77ce47996 is not defined"

**Comment by duxin14436106** [comment]
single-spa minified message #31: See https://single-spa.js.org/error/?code=31&arg=bootstrap&arg=application&arg=crm&arg=4000
准备从qiankun主系统 跳转到子系统 但是一直报错这个
