### ISSUE TITLE
当子应用项目没有模块系统时，如何暴露那3个函数

### ISSUE THREAD

**Issue by crixusshen** [umijs/qiankun#214]

**Comment by crixusshen** [comment]
自己解决了，由于我们这个古老项目是最原始的JSP实现方式，根本就没有什么模块系统，也没有用之类的CMD,AMD模式。基本就是JQUERY+JSP那种实现方式。查看了下源代码，可以通过定义一个window对象下的应用名称对象，如window['your application name'] = {}，然后将这3个需要暴露的函数赋值给它，至于这么做有没有副作用还不知道，源代码下对于这块的处理应该是给UMD模式用的。

**Comment by mowatermelon** [comment]
> 自己解决了，由于我们这个古老项目是最原始的JSP实现方式，根本就没有什么模块系统，也没有用之类的CMD,AMD模式。基本就是JQUERY+JSP那种实现方式。查看了下源代码，可以通过定义一个window对象下的应用名称对象，如window['your application name'] = {}，然后将这3个需要暴露的函数赋值给它，至于这么做有没有副作用还不知道，源代码下对于这块的处理应该是给UMD模式用的。

你好，我想请问一下，你这个挂载window下的三个方法，是写的空方法体，内部需要写什么实现吗？我这边挂载到window下，提示说cannot  observe of null
