### ISSUE TITLE
最新版本2.7.2的升级导致切换子应用加载的当前css文件丢失

### ISSUE THREAD

**Issue by boyrest** [umijs/qiankun#2141]
## What happens?
qiankun 2.7.2 切换子应用加载的当前页面引入的css文件丢失

## How To Reproduce
加载子应用A和B，操作顺序 1.打开子应用A第一个页面 2.打开子应用B第一个页面 3.重新打开子应用A第一个页面

- **qiankun Version**: 2.7.2
- **umi**: 3.5.26
- **@umijs/plugin-qiankun**: 2.22.1

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/11408703/172742829-571ff290-ca06-4543-94ad-aa231ce6a8f1.png">

**Comment by boyrest** [comment]
切回版本2.7.1问题解决

**Comment by zzjin23** [comment]
+1

**Comment by zgf123** [comment]
这个能否在2.7.3 版本修复呢

**Comment by lucaslz2020** [comment]
我也是~

**Comment by lhmiao** [comment]
使用 emotion 时同遇到这个问题，回退至 v2.7.1 版本解决
