### ISSUE TITLE
主应用动态添加的style被算到了子应用中，子应用被unmount后，style也没有了。

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#2145]
## What happens?
主应用动态添加的style被算到了子应用中，子应用被unmount后，style也没有了。
sandbox: true,  启用沙箱或useLooseSandbox为true都不行。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.7.1
- **Platform Version**: windows，angular
- **Browser Version**: chrome

**Comment by gongshun** [comment]
应该是同一个问题 https://github.com/umijs/qiankun/issues/2141

**Comment by gongshun** [comment]
看了 2.7.3 版本是否修复了

**Comment by waltbest2** [comment]
> 看了 2.7.3 版本是否修复了

看了一下提交的代码，只是在remove时做了改动，这个应该是修改之前的bug
但是我说的问题是本身机制问题。添加时就不应该往子应用的div里加，要加到主dom中。
![image](https://user-images.githubusercontent.com/63687537/174203139-4b31c767-0eec-47e0-9114-b3d249d56619.png)

我升级测试，问题还是存在。

**Comment by gongshun** [comment]
很早之前是有这个bug，https://github.com/umijs/qiankun/issues/578 已经修复了（useLooseSandbox为true就会有这个问题）

**Comment by waltbest2** [comment]
> 很早之前是有这个bug，#578 已经修复了（useLooseSandbox为true就会有这个问题）

即使sandbox: true也不行。
重现很简单，你就打开一个子应用。
直接在浏览器控制台上 执行
const s = document.createElement('style');
s.innerText = 'span { background: red;}';
document.head.appendChild(s);
这个是模拟主应用添加style，当切到另一个子应用时，这个样式就没了。

**Comment by Tinet-zhangmd** [comment]
> 很早之前是有这个bug，#578 已经修复了（useLooseSandbox为true就会有这个问题）

现在还是有这个问题，我采用了 #578的![image](https://user-images.githubusercontent.com/49385806/174218141-f73f0921-9966-43a0-b8b3-f865cf535ac2.png)这个方案，样式没有问题，但子应用的路由懒加载模块就会出现chunk load error错误，导致js加载失败

**Comment by waltbest2** [comment]
> > 很早之前是有这个bug，#578 已经修复了（useLooseSandbox为true就会有这个问题）
> 
> 现在还是有这个问题，我采用了 #578的![image](https://user-images.githubusercontent.com/49385806/174218141-f73f0921-9966-43a0-b8b3-f865cf535ac2.png)这个方案，样式没有问题，但子应用的路由懒加载模块就会出现chunk load error错误，导致js加载失败

我这个场景是第一次就打开子应用的页面，如果主工程中有异步加载style的场景就不行。如果主工程是angular，就会这样
angular都是动态添加style内联样式。

**Comment by gdnwr** [comment]
确实是有这个问题，我是主项目、子项目都是VUE2; 
现在只能先设置vue.config.js中的css.extract=false，将CSS文件动态注入到 JavaScript 中的 inline 代码，等待qiankun后续修复。

**Comment by zhuyankun** [comment]
什么时候修复？？

**Comment by 1021437281** [comment]
> > > 很早就修复之前有这个bug，#578已经有了（useLooseSandbox为真有这个问题）
> > 
> > 
> > 现在还是有这个，我采用了#578的![图片](https://user-images.githubusercontent.com/49385806/174218141-f73f0921-9966-43a0-b8b3-f865cf535ac2.png)这个，没有问题的样式问题，但是应用的路由延迟加载模块出现错误，导致js加载失败
> 
> 我这个场景是第一次就打开子应用的页面，如果主工程里面添加了异步加载样式的场景就不行 。

**Comment by zmf0705** [comment]
我也遇到了这样的问题，请问这个问题解决了吗？ @waltbest2
