### ISSUE TITLE
qiankun 多个应用，只启动一个 会报这个错 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by baikai55** [umijs/qiankun#2149]
import { registerMicroApps, start } from "qiankun";
registerMicroApps([
  {
    name: "index", // 应用的名字
    entry: "//localhost:8080", // 默认会加载这个html 解析里面的js 动态的执行 （子应用必须支持跨域）fetch
    container: "#container", // 容器id
    activeRule: "/app/index", // 根据路由 激活的路径
  },
  {
    name: "app",
    entry: "//localhost:8081",
    container: "#container",
    activeRule: "/app/app",
  },
]);
start();

**我查官方文档，发现是往`start()`里边传值**

[官方文档的设置](https://qiankun.umijs.org/zh/api#prefetchappsapps-importentryopts)
请复制这个快速搜索 => start(opts?)

**我尝试过 `start({ opts: { prefetch: false } });`、`start({ prefetch: false });`、`start(false);`** **都不行**

**请问各位大佬这个该怎么传参数**

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1085#issuecomment-731995703

`start({ prefetch: false });`

**Comment by baikai55** [comment]
> [第1085章（评论）](https://github.com/umijs/qiankun/issues/1085#issuecomment-731995703)
> 
> `start({ prefetch: false });`

好的，谢谢大佬。
经过操作
当基座为：`http://localhost:8082/` 
微应用1为：`http://localhost:8080/`
微应用2为：`http://localhost:8081/`
基座：`main.js => start({ prefetch: false });`
停止 微应用1 服务 之后依然会报错：
 `GET http://localhost:8080/ net::ERR_CONNECTION_REFUSED` 和 `Uncaught (in promise) TypeError: Failed to fetch`

重启基座服务后=>：
当基座为：`http://localhost:8080/` 
微应用1 服务停止，
微应用2为：`http://localhost:8081/`
这样不会报错。
