### ISSUE TITLE
重复进入子应用时，子应用获取到的路由错误（已更新复现仓库）

### ISSUE THREAD

**Issue by viviprprpr** [umijs/qiankun#215]
重复进入子应用时，子应用获取到的路由错误

## 最小可复现仓库

https://github.com/viviprprpr/personal-test-umi-plugin-qiankun.git
万分感谢🙏

## 复现步骤，错误日志以及相关配置

点击进入子应用，浏览器点击返回，循环三次必定报警告，然后再点击进入子应用，浏览器路由变了，但是子应用获取到的还是上一个。

![image](https://user-images.githubusercontent.com/40267580/71667626-df254380-2da0-11ea-8062-9060d801dfbc.png)

## 相关环境信息

- **qiankun 版本**
1.3.4
- **浏览器版本**：
chrome 79.0.3945.88
- **操作系统**：
mac

**Comment by kuitos** [comment]
没有可复现仓库无法排查出是什么问题，有效信息太少了

**Comment by viviprprpr** [comment]
> 没有可复现仓库无法排查出是什么问题，有效信息太少了

您好，复现仓库已经提供，麻烦了

**Comment by viviprprpr** [comment]
@kuitos 这个问题有办法解决么🙏

**Comment by jallens** [comment]
该问题有解决了吗 @viviprprpr
