### ISSUE TITLE
主应用的某个路由页面下加载微应用，路由跳转切换到主应用别的路由页再切回来后子应用容器下的dom被清空

### ISSUE THREAD

**Issue by fszqj** [umijs/qiankun#2153]
## What happens?

- 主应用跟子应用都是根据vue2.0搭建，都是hash模式

子应用挂载的#mircro-app-wrapper容器是在主应用的A路由页下面，在A路由页下loadMicroApp子应用挂载完成后，跳转到主应用B路由页之后再切回A页，之前A路由页下的子应用挂载容器#mircro-app-wrapper下的dom节点被清空了，这个问题该怎么处理？期望切换回A页面时可以重新显示子应用的内容。

## 复现步骤，错误日志以及相关配置

主应用存在两个layout，一个显示子应用的adminLayout，一个是主应用的其他layout，adminLayout有侧边栏及主要内容区域，主要内容区域用于显示子应用内容。主应用根据侧边栏菜单绑定的url导航到子应用的路由页，并通过loadMicroApp加载不同的子应用

切换前：
![image](https://user-images.githubusercontent.com/45392202/174570389-7f99815f-13bf-45d5-9bc7-5480304cdc94.png)
切换到/home再切换回来后：
![image](https://user-images.githubusercontent.com/45392202/174573342-3da761fe-548e-4892-a04a-51e8ac4863b2.png)

主应用的其他路由：
```
{
    path: '/',
    component: portalLayout,
    redirect: '/home',
    children: [
      {
        name: 'Home',
        path: 'home',
        component: () => import('@/views/portal/home/index')
      },
      {
        name: 'Products',
        path: 'products',
        component: () => import('@/views/portal/home/Products')
      }
    ],
    hidden: true
  }
```
主应用下加载微应用的路由：
```
// sub app route
  {
    path: `/scfp-admin/*`,
    component: adminLayout,
    hidden: true
  }
```
主应用下加载微应用的路由的adminLayout：
```
<template>
  <section class="app-main">
    <transition name="fade-transform" mode="out-in">
      <keep-alive v-if="showComponent" v-show="$route.name" :include="cachedViews">
        <!-- 主应用渲染区，用于挂载主应用路由触发的组件 -->
        <router-view :key="key" :altered="altered" class="router-view" />
      </keep-alive>
    </transition>
    <!-- 子应用渲染区，用于挂载子应用节点，每个子应用分别使用独立的容器，自己控制子应用的显隐 -->
    <div
      v-for="item of sub_apps"
      v-show="$route.path.startsWith(item.activeRule)"
      :id="item.name"
      :key="item.name"
    ></div>
  </section>
</template>
```

## 相关环境信息

- **qiankun 版本**
- 2.6.3
- **浏览器版本**：
- Chrome 102.0.5005.115
- **操作系统**：
- win10

**Comment by gongshun** [comment]
参考demo ： https://github.com/gongshun/qiankun-vue-demo/tree/feature/keep-alive

**Comment by Huichifangqiu** [comment]
麻烦问下是怎么解决的？

**Comment by BranceLee** [comment]
我解决这个问题，通过 renderWithQiankun 里的mount 声明周期包含所有入口 js/ts 的初始化操作，因为每次main app 切换到 sub-app 的时候都会通过mount 来重新挂着 sub-app， 所以需要完全include 需要执行的入口js.
