### ISSUE TITLE
关于var变量的问题

### ISSUE THREAD

**Issue by crixusshen** [umijs/qiankun#216]
## 原始项目中var变量在迁移中遇到的问题

项目中有2个js脚本，第一个脚本存放了一些变量（使用var定义），第二个脚本会引用第一个脚本中的这些var变量，在默认浏览器环境下第一个脚本的变量会自动被升位为全局变量。

```javascript
// first.js:
var foo = "hello";
var bar = "world";

// second.js(在first.js后引用):
function test() {
   console.log(foo + " " + bar);   // hello world
}
```

上面的代码在没有使用qiankun前在浏览器环境下是正常的，因为foo和bar会被自动的变为全局，但是使用了qiankun改造后，发现这些变量并不会被塞入window下，查看了源代码沙盘脚本中通过proxy代理了一个临时的window.proxy变量；而在import-html-entry插件中在eval代码时传入的变量是这个window.proxy，也就是说必须对之前first.js中的变量声明为window.foo和window.bar才可以成功触发proxy从而进行沙盘变量的赋值。请问有没有什么方式可以不用去修改原始代码，因为我们这个项目已经十几年了，实现上使用的是最传统的JSP+JQUERY，连模块系统之类的都没有使用，N年前的前端现状却是都是这样来实现的，求助！！！

**Comment by kuitos** [comment]
搞个脚本把引用的 js concat 成一个应该就可以了

**Comment by kuitos** [comment]
框架层面这个无法处理了

**Comment by gaorubin1990** [comment]
请问jsp这种前后端不分离的项目也能集成到qiankun里吗？

**Comment by kuitos** [comment]
> 请问jsp这种前后端不分离的项目也能集成到qiankun里吗？

HTML Entry 只需要一个页面地址，跟你怎么部署的无关

**Comment by gaorubin1990** [comment]
但是子应用中不是要求打包为umd模式并且要暴漏生命周期函数吗，不分离的项目无法满足啊

**Comment by kuitos** [comment]
打包方式跟部署方式是两回事

**Comment by 4x4l** [comment]
> 搞个脚本把引用的 js concat 成一个应该就可以了

如果是以下的情况，即使concat也没有用...
```js
// first.js:
var foo = "hello";
var bar = "world";

// second.js(在first.js后引用):
function test() {
   console.log(window.foo + " " + window.bar);   // hello world
}
```

**Comment by wxwzl** [comment]
> 搞个脚本把引用的 js concat 成一个应

> 搞个脚本把引用的 js concat 成一个应该就可以了

想得太简单了吧，我看你们的子应用挂载思路是要在入口文件里就拿到整个页面的dom结构，然后渲染到某个dom节点下，而jsp页面是是同时具有静态dom节点又有js动态生成的节点，那些静态节点要整个html页面在浏览器里执行完才知道

**Comment by wxwzl** [comment]
加载jsp页面，我觉得需要一个隐藏的iframe,去加载jsp页面，同时将css的link节点和javascript节点加载到主应用的页面，但这里边存在一堆的css样式污染和js命名空间污染

**Comment by myNameCao** [comment]
子应用 中  如果引入一些外部的文件，这个外部文件写发  就有全局变量 无法访问的问题 ，不知道怎么解决

**Comment by XingXiaoWu** [comment]
同出现这类问题。。我还不是var变量，我这是老项目的common.js里面一堆function，html引入对应的js运行的时候直接提示找不到。。。

**Comment by xtthaop** [comment]
今天也遇到这种情况了，直接进去改源码了

**Comment by JasonGaoG** [comment]
同问，有什么方案么
