### ISSUE TITLE
主应用第一次打开子应用可以渲染，点击其他路由，再打开子应用，页面空白整体空白

### ISSUE THREAD

**Issue by mrcluo** [umijs/qiankun#2161]
## What happens?

主应用：qiankun + vue2        主应用 #app,存放子应用容器#subapp
子应用：qiankun + react       子应用 #root

问题描述：
1 页面第一次加载后，打开子应用渲染没问题
2 点击vue项目的其他路由导航后，再点击子应用页面就空白了

业务场景：
路由导航中，react子应用走history.pushState无刷新加载子应用，主应用自己的路由走vue自己router-link

[
![image](https://user-images.githubusercontent.com/40492120/175891439-d6662499-41de-4637-8826-32be0b7102e0.png)
](url)
如下图，其实子应用是加载成功，dom也能看到，就是页面空白
[
![image](https://user-images.githubusercontent.com/40492120/175893344-42af5e98-9649-4bb9-b9a6-4fcb6ab995ff.png)
](url)

## 尝试
自己尝试了pushState和replaceState，没达到想要的效果
history.pushState的目的是为了无刷新，修改历史栈，匹配子应用，本地写demo两个子应用之间只用history.pushState不会出现问题，但是和vue-router一起用就不行了
history.pushState(null, url, url)

这个也不行
// await this.$router.push(url)
// history.replaceState({ ...history.state, ...{key: 213} }, '')

这个可以，但是页面会整体刷新一下
// window.location.href = url

## 期待的效果
打开react子应用渲染成功，点击主应用的其他路由渲染成功，再点击react子应用的路由渲染成功

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：谷歌浏览器版本 102.0.5005.115（正式版本）
- **操作系统**：windows 10

 希望官方大佬看到回复下，感谢

**Comment by mrcluo** [comment]
> 子应用路由模式是 hash ？[#1199 (comment)](https://github.com/umijs/qiankun/issues/1199#issuecomment-818740774)

都是history的模式

**Comment by mrcluo** [comment]
已经解决了，辛苦各位。
问题：
由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到
解决方案：
主应用加载子应用的方式从 全局注册 改为 局部注册

**Comment by liswn** [comment]
> 



> 已经解决了，辛苦各位。 问题： 由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到 解决方案： 主应用加载子应用的方式从 全局注册 改为 局部注册

大佬，我也遇到和你一样的问题，请问一下“局部注册是什么意思呢”

**Comment by lucky-zouzou** [comment]
> 已经解决了，辛苦各位。 问题： 由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到 解决方案： 主应用加载子应用的方式从 全局注册 改为 局部注册

请问是怎么解决的呢？遇到了类似的问题，是刷新后就变成空白了

**Comment by LeslieCheung-FCC** [comment]
> 已经解决了，辛苦各位。 问题： 由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到 解决方案： 主应用加载子应用的方式从 全局注册 改为 局部注册

这个怎么改？

**Comment by 2733711860** [comment]
> 已经解决了，辛苦各位。 问题： 由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到 解决方案： 主应用加载子应用的方式从 全局注册 改为 局部注册

大佬，能具体说说吗

**Comment by weizhuanhua** [comment]
> > 已经解决了，辛苦各位。 问题： 由于子应用的url为动态地址，和主应用中配置的activeRule匹配不到 解决方案： 主应用加载子应用的方式从 全局注册 改为 局部注册
> 
> 大佬，能具体说说吗

子应用动态路由的话 主应用的全局注册registerMicroApps 改成 局部loadMicroApp 注意局部注册的时机 反正都是坑
