### ISSUE TITLE
这个警告怎样消除 [qiankun] lifecycle not found from sts-system entry exports, fallback to get from window['sts-system']

### ISSUE THREAD

**Issue by SanMako** [umijs/qiankun#2162]
我在正确接入qiankun之后，子应用已经可以加载了，但是控制台有一条警告日志：
[qiankun] lifecycle not found from sts-system entry exports, fallback to get from window['sts-system']
如下图所示：
![image](https://user-images.githubusercontent.com/76836628/175980328-bd33e0a7-97d0-47c3-8f86-deb7dd683d39.png)
请问这个日志可以消除吗？

- **qiankun 版本**：^2.7.3
- vue版本：^3.2.36
- **浏览器版本**：chrome 102.0.5005.115
- **操作系统**： windows10

**Comment by gongshun** [comment]
> library 设置为 ${name} 就可以了

https://github.com/umijs/qiankun/issues/770
