### ISSUE TITLE
[Feature Request] fetch请求的js脚本不会被浏览器缓存，导致页面加载变慢

### ISSUE THREAD

**Issue by Miller-Wang** [umijs/qiankun#2163]
## 子应用接入微前端
原来子应用加载js，会使用浏览器缓存，接入乾坤后，每次都要fetch js脚本，无法使用浏览器缓存，导致页面加载变慢

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/906 重复

**Comment by aique127** [comment]
> 与 #906 重复

楼主解决没。和#906的问题相反啊并没有重复，这我发现子应用js文件就算设置了强缓存，也不会生效，每次刷新还是会重新请求。
