### ISSUE TITLE
发布到线上环境后，主子应用报跨域问题了，请问怎么解决

### ISSUE THREAD

**Issue by mrcluo** [umijs/qiankun#2165]
## What happens?

发布到线上后，主应用打开，报子应用跨域问题
主应用域名 https://predataenginecdp.71360.com/
子应用域名  https://predataenginecdpbi.71360.com/

本地可以的，因为本地的devServer配置了 'Access-Control-Allow-Origin': '*'

[
![image](https://user-images.githubusercontent.com/40492120/176369984-099cb507-3d61-40e8-9f92-f872f56c4ee1.png)
](url)

## 复现步骤，错误日志以及相关配置

主应用打开，报跨域问题，见上图
请问在哪里进行配置呢，如何配置呢 我问后端，他也不是很清楚qiankun的东西

## 相关环境信息

- **qiankun 版本**：2.7.0
- **浏览器版本**：谷歌浏览器版本 102.0.5005.115（正式版本）
- **操作系统**：windows 10

**Comment by mrcluo** [comment]
解决了
解决方案：
location / {
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
      add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
    }

**Comment by IceRain-mvc** [comment]
上面的代理是在主应用还是子应用中解决的
