### ISSUE TITLE
[Feature Request] 能否提供彻底卸载loadMicroApp加载的子应用，下次进入能重新走首次流程

### ISSUE THREAD

**Issue by czwaiwai** [umijs/qiankun#2166]
## Background

生产可能已经发布了新的子应用，但是用户由于已加载过子应用，导致无法获取到更新后的子应用
且子应用在部分js应网络问题加载失败后，无法通过再次加载子应用来提供访问重试的方案
## Proposal

建议提供彻底卸载方法来移除已加载过的子应用，能让子应用像首次加载子应用一样的流程

**Comment by kuaifengle** [comment]
每个加载完毕的微应用 都有生命周期函数可以执行

![image](https://user-images.githubusercontent.com/24524172/177303161-5a53ddd8-0928-4770-a0dc-b3cc1e1f3712.png)

销毁的函数:  unmount()

```
// 加载微应用
 let microApp = loadMicroApp({})

// 销毁微应用
microApp.unmount()

```

**Comment by XSnowHoly** [comment]
> 每个加载完毕的微应用 都有生命周期函数可以执行
> 
> ![image](https://user-images.githubusercontent.com/24524172/177303161-5a53ddd8-0928-4770-a0dc-b3cc1e1f3712.png)
> 
> 销毁的函数: unmount()
> 
> ```
> // 加载微应用
>  let microApp = loadMicroApp({})
> 
> // 销毁微应用
> microApp.unmount()
> ```

如果因为网络问题没有加载成功微应用如何重试？

**Comment by kuaifengle** [comment]
可以先查询微应用是否加载成功 再确定是否需要卸载
```      
     if (microApp.getStatus() == 'MOUNTED') {
                   microApp.unmount()
             }
```
