### ISSUE TITLE
子应用的事件监听失效。

### ISSUE THREAD

**Issue by baikai55** [umijs/qiankun#2168]
做的后台管理项目，搜索框、表格居多。因为每个页面搜索框占用的高度不同。做了页面高度监听。
取到整个页面的高度 减去 搜索框 占用的 高度 动态 赋值 表格高度。
项目单独运行的时候，事件监听是没问题的。表现的与我的预期相符。

当我启动主应用 。通过主应用访问子应用时，这个页面监听效果就失效了。只有刷新页面才会触发。

请问一下如何才能在主应用中继续触发我的监听事件
![子监听](https://user-images.githubusercontent.com/102270733/176398312-22a0fd0b-28a2-465c-8915-5b1a02c3b698.png)

这个似乎是我写的监听事件

**Comment by baikai55** [comment]
"qiankun": "^2.7.2",
start({ prefetch: false });

**Comment by gongshun** [comment]
需要用 addEventListener 添加事件监听，不可以使用 window.onXX 添加，子应用的 window 是沙箱，不是真实的 window

**Comment by YuArtian** [comment]
为啥刷新页面又触发了。。。

**Comment by baikai55** [comment]
> 为啥刷新页面又触发了。。。

是我没说清楚，因为在mouted中调用了这个函数。所以刷新时会调用

**Comment by UmbraCi** [comment]
> 需要用 addEventListener 添加事件监听，不可以使用 window.onXX 添加，子应用的 window 是沙箱，不是真实的 window

在子应用中window.addEventListener监听message事件，这个监听事件似乎挂载到的是主基座的全局，但是在chrome dev的dom的EventListener面板又找不到，如何让子应用监听自己的messe事件呢
