### ISSUE TITLE
datart作为子应用，发布到线上时，woff2等字体图标不展示，路径错误

### ISSUE THREAD

**Issue by mrcluo** [umijs/qiankun#2169]
**技术栈**
主应用： qiankun + vue
子应用:   qiankun + datart

**场景：**
本地打开子应用datart，图标可以正常显示
发布到线上环境，图标空白，如下图
[
![image](https://user-images.githubusercontent.com/40492120/176446001-5afee83a-e3c5-41f3-916f-141ffee5a5d2.png)
](url)

**问题定位：**
控制台报错提示
Failed to decode downloaded font: https://predataenginecdp.71360.com/static/media/iconfont.86f52cba.woff2

发布到线上后，发现woff2等字体图标路径是 **主应用域名** ，非datart子应用的域名，猜测是图标空白的原因，见上图

**尝试解决：**
网上搜索，解决方案：把图标的路径转为base64的，绕过路径的问题
在craco.config.js里配置如下，但是打包(npm run build:test)后dist目录无文件变化，猜测下面的写法有问题，请问下面的配置要如何写呢

[
![image](https://user-images.githubusercontent.com/40492120/176448599-5d6d5e7c-f396-441d-8665-60cc48bf182a.png)
](url)
下面代码拥挤在一起了。。见上图
`module.exports = {
  module: {
    rules: [
      {
        test: /\.(png|jpe?g|gif|webp|woff2?|eot|ttf|otf)$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 99999999,
            },
          },
        ],
      },
    ],
  }
}`

**Comment by YuArtian** [comment]
loader 不是有 publicPath 配置嘛

**Comment by mrcluo** [comment]
> loader 不是有 publicPath 配置嘛
你好啊，你说的是file-loader吗，试了，build后，dist目录还是无文件变化
[
![image](https://user-images.githubusercontent.com/40492120/176568476-af158424-a8cc-425e-a033-05d8e08dddc1.png)
](url)

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

**Comment by mrcluo** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

我就是按照这个配置的 (笑哭)

**Comment by mrcluo** [comment]
已解决，是craco封装webpack的原因，配置loader写法不一样了

**Comment by meriter** [comment]
> 已解决，是craco封装webpack的原因，配置loader写法不一样了

能贴下配置吗，感谢。
