### ISSUE TITLE
vue项目里使用element-ui相对的字体未能成功加载

### ISSUE THREAD

**Issue by PolanZ** [umijs/qiankun#217]
## What happens?

vue示例里，使用了element-ui引入到了相对路径的字体，加载不到，也定义了publicPath
所以是不是针对这种引入相对路径资源进行处理呢，这样的问题该如何解决呢
```js
Failed to decode downloaded font: http://localhost:7099/static/fonts/element-icons.535877f5.woff
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:7099/static/fonts/element-icons.732389de.ttf
OTS parsing error: invalid version tag
```
加载到了入口项目的路径下了，那么这样css里相对引入的资源该如何解决呢

## 相关环境信息

- **qiankun 版本** 1.3.10
- **浏览器版本**：google chrome 79
- **操作系统**：win64

**Comment by Jim-jw** [comment]
把你的publicPath怎么配的发出来看一下

**Comment by PolanZ** [comment]
@Jim-jw 就是自带的vue示例啊，没改过其他就是，在home.vue里面使用icon时测试到问题
```html
<i class="el-icon-edit"></i>
```

vue/src/public-path.js

```js
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
```

**Comment by zhangsalle** [comment]
+1

**Comment by zhangsalle** [comment]
element字体是通过css文件的@font-face引入的

**Comment by F-loat** [comment]
暂时可以在 vue.config.js 里直接配置好 publicPath

**Comment by novaor** [comment]
这个问题现在是怎么解决的

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/issues/218#issuecomment-573518895

**Comment by kuitos** [comment]
demo 里的 live public path 没生效导致的

**Comment by littleluckly** [comment]
> demo 里的 live public path 没生效导致的

开发环境配置后没问题了，但是用nginx部署后publicPath不生效，依然不能加载字体文件，

**Comment by chenillwang** [comment]
我们内部项目，本地开发没有问题，请求的资源路径都是相对的。发布到对应的线上环境就出了问题，静态资源是发布到另一个域名上托管的，通过  __webpack_public_path__ 
 = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__; 注入的环境会导致子项目的js/css报错，请求的资源是子应用的入口+js/css文件，但是我们的入口在域名的基础上多了一些路径，所以把这个取消了。之后又发现element-ui打包出来的font文件无法访问，访问的路径是主入口项目的domain + fonts/字体文件。求助~

**Comment by lucasleelz** [comment]
怎么关闭了~ 我也遇见这个问题了啊~

**Comment by F-loat** [comment]
live public path 需要在 import 其他资源前配置，可以直接把 public.js 作为构建的第一个入口文件，这样基本就没问题了

**Comment by lucasleelz** [comment]
@F-loat  我漏掉了一步， 没有在`main.js`中引入`public-path.js`.

**Comment by lianruhe** [comment]
@Deturium  确实有该问题。

开发模式可以加载到字体文件，webpack 有对应的文件映射；但是打包之后字体文件是作为资源文件加载，使用的是相对路径，根据主应用的 domain 是找不到对应的文件的。

可以试一下 url-loader 配一个public-path

**Comment by lucasleelz** [comment]
部署之后确实有问题~

**Comment by 15982153332** [comment]
加上这个，亲测可用
config.module
      .rule("fonts")
      .test(/\.(ttf|otf|eot|woff|woff2)$/)
      .use("url-loader")
      .loader("url-loader")
      .tap(options => {
        options = {
          // limit: 10000,
          name: '/static/fonts/[name].[ext]',
        }
        return options
      })
      .end()

**Comment by zhe-he** [comment]
vue-cli + element-ui 字体渲染乱码。可以用此解决：
```
chainWebpack: config => {
    let fontRule = config.module.rule('fonts');
        fontRule.uses.clear();
        fontRule.use('file-loader').loader('file-loader').options({
            name: 'static/fonts/[name].[hash:8].[ext]'
        });
}
```

**Comment by jzz4012650** [comment]
> 加上这个，亲测可用
> config.module
> .rule("fonts")
> .test(/.(ttf|otf|eot|woff|woff2)$/)
> .use("url-loader")
> .loader("url-loader")
> .tap(options => {
> options = {
> // limit: 10000,
> name: '/static/fonts/[name].[ext]',
> }
> return options
> })
> .end()

针对 VUE CLI，也可使用 publicPath：
```js
config.module
  .rule('fonts')
    .use('url-loader')
    .loader(require.resolve('url-loader'))
    .tap(options => _.merge(options, {
      fallback: {
        options: {
          publicPath: '/static/' 
        }
      }
    }));
```

**Comment by zx8887** [comment]
> > 加上这个，亲测可用
> > config.module
> > .rule("fonts")
> > .test(/.(ttf|otf|eot|woff|woff2)$/)
> > .use("url-loader")
> > .loader("url-loader")
> > .tap(options => {
> > options = {
> > // limit: 10000,
> > name: '/static/fonts/[name].[ext]',
> > }
> > return options
> > })
> > .end()
> 
> 针对 Vue-CLI，也可使用`file-loader`的`publicPath`：
> 
> ```js
> config.module
>   .rule('fonts')
>     .use('url-loader')
>     .tap(options => _.merge(options, {
>       fallback: {
>         options: { // file-loader 的 options 
>           publicPath: '/static/' 
>         }
>       }
>     }));
> ```
> 
> 除了字体，其他**静态资源**应该也有类似问题，可类似解决。

找了半天。终于找到解决办法。。
这样设置后，调试界面看css里面的url是转化成了base64，十分感谢

**Comment by qiushuaichang** [comment]
> 加上这个，亲测可用
> config.module
> .rule("fonts")
> .test(/.(ttf|otf|eot|woff|woff2)$/)
> .use("url-loader")
> .loader("url-loader")
> .tap(options => {
> options = {
> // limit: 10000,
> name: '/static/fonts/[name].[ext]',
> }
> return options
> })
> .end()

是在哪个文件中设置的

**Comment by qiushuaichang** [comment]
> > > 加上这个，亲测可用
> > > config.module
> > > .rule("fonts")
> > > .test(/.(ttf|otf|eot|woff|woff2)$/)
> > > .use("url-loader")
> > > .loader("url-loader")
> > > .tap(options => {
> > > options = {
> > > // limit: 10000,
> > > name: '/static/fonts/[name].[ext]',
> > > }
> > > return options
> > > })
> > > .end()
> > 
> > 
> > 针对 Vue-CLI，也可使用`file-loader`的`publicPath`：
> > ```js
> > config.module
> >   .rule('fonts')
> >     .use('url-loader')
> >     .tap(options => _.merge(options, {
> >       fallback: {
> >         options: { // file-loader 的 options 
> >           publicPath: '/static/' 
> >         }
> >       }
> >     }));
> > ```
> > 
> > 
> > 除了字体，其他**静态资源**应该也有类似问题，可类似解决。
> 
> 找了半天。终于找到解决办法。。
> 这样设置后，调试界面看css里面的url是转化成了base64，十分感谢

我的也是自动转成base64了，但是这个劲爆或者问题，你是怎么解决的？

**Comment by myNameCao** [comment]
> live public path 需要在 import 其他资源前配置，可以直接把 public.js 作为构建的第一个入口文件，这样基本就没问题

> 怎么关闭了~ 我也遇见这个问题了啊~
 ```js
import './public-path   放在 最前面一般就 没有问题了
```

**Comment by cjlhll** [comment]
> > live public path 需要在 import 其他资源前配置，可以直接把 public.js 作为构建的第一个入口文件，这样基本就没问题
> 
> > 怎么关闭了~ 我也遇见这个问题了啊~
> 
> ```js
> import './public-path   放在 最前面一般就 没有问题了
> ```

牛逼，我还各种找配置，结果挪上去就好了。

**Comment by PolanZ** [comment]
您的邮件我已收到，会尽快回复。亲

**Comment by lianruhe** [comment]
已经收到您的来信，我会尽快查看。

**Comment by rcnicky** [comment]
> > live public path 需要在 import 其他资源前配置，可以直接把 public.js 作为构建的第一个入口文件，这样基本就没问题
> 
> > 怎么关闭了~ 我也遇见这个问题了啊~
> 
> ```js
> import './public-path   放在 最前面一般就 没有问题了
> ```

微前端已经搞过好些次了，今天又搞个新环境，确实没注意这块，又找了半小时原因

**Comment by lianruhe** [comment]
已经收到您的来信，我会尽快查看。
