### ISSUE TITLE
当子应用中有引用带空格的资源文件时，会导致子应用加载失败

### ISSUE THREAD

**Issue by zwlijun** [umijs/qiankun#2171]
当页面中有引用带空格的资源文件时，会导致子应用加载失败（微应用在收集资源文件时对含有空格的资源处理存在问题，会将空格及后面的内容丢弃掉）
【资源引用】
![image](https://user-images.githubusercontent.com/1833161/176819044-1bb6b799-0d79-4c0c-af9b-812ffb52084c.png)
![image](https://user-images.githubusercontent.com/1833161/176819233-070428e2-be17-45d2-a9e4-ceda4ae46125.png)

实际在主应用加载时，资源路径被截断了，导致资源加载失败。如下图：
![image](https://user-images.githubusercontent.com/1833161/176818658-f703b4fa-7b10-4e8f-ae69-162d63fbaf4c.png)

**Comment by kuitos** [comment]
3.0 已修复
