### ISSUE TITLE
子应用状态下，monaco-editor编辑器代码提示展示为空

### ISSUE THREAD

**Issue by mrcluo** [umijs/qiankun#2173]
**技术栈**
主应用： qiankun + vue
子应用:   qiankun + datart

**场景：**
本地打开项目 或者 datart独立打开 展示都是正常的
发布到线上环境，sql的下拉框展示空白，但是是可以点击的。功能正常，只是ui不展示。如下图

[
![image](https://user-images.githubusercontent.com/40492120/177079916-7ac7800e-0a52-4e52-82af-e3702515e7c2.png)
](url)

**尝试解决：**
控制台没有报错提示

**感谢大佬，期望翻牌**

**Comment by gongshun** [comment]
样式污染了吧，文字颜色被别的地方覆盖了

**Comment by mrcluo** [comment]
> 样式污染了吧，文字颜色被别的地方覆盖了

感谢你的回复，的确是样式污染了
