### ISSUE TITLE
2.4.5版本以后的一个修改导致了如果默认打开的URL是子应用，切换路由回主应用时CSS会不加载

### ISSUE THREAD

**Issue by chen735623058** [umijs/qiankun#2176]
发生版本 2.4.5-2.7.3都有这个问题
通过调试发现是因为 proxySandbox这个文件中的下图方法

![image](https://user-images.githubusercontent.com/6779783/177674293-9f0a3fcb-2b59-4602-bf96-6bae4a6a9368.png)

放到这个if判断中就可以解决，希望后续版本能解决

**Comment by chen735623058** [comment]
![image](https://user-images.githubusercontent.com/6779783/177674461-a918b2d4-18bf-4ea0-9fa9-e942f289a5eb.png)
就是因为这次代码更新引起的

**Comment by githubCK** [comment]
这个问题感觉挺严重啊，官方什么时候给解决一下，更新个版本！

**Comment by chen735623058** [comment]
你好，我写了例子工程，可以复现这个问题，并且我也找到了出现这个问题的原因，是在切换回路由的时候同时调用了主工程菜单导致，能给我一下你的邮件或者联系方式吗？我发例子工程给你，因为工程涉及到一些内部项目结构，不太想把这个程序放到git上，

**Comment by chen735623058** [comment]
@kuitos

**Comment by kuitos** [comment]
> 你好，我写了例子工程，可以复现这个问题，并且我也找到了出现这个问题的原因，是在切换回路由的时候同时调用了主工程菜单导致，能给我一下你的邮件或者联系方式吗？我发例子工程给你，因为工程涉及到一些内部项目结构，不太想把这个程序放到git上，

抽一个最小复现放出来，或者直接在example上改

**Comment by mewangbin** [comment]
我也发现这个问题了，场景：
1.主应用main-app 是一个多标签页的项目，通过loadMicroApp 手动加载 子应用sub-app
2.子应用sub-app 挂载在主应用main-app 的 /dashboard/sub-app/下。
3.访问步骤：
   a)打开：http://localhost:xxx/main-app/dashboard/sub-app/sub-route1,将在main-app下新增一个标签页 用来显示 子应用的sub-route1 
   b)如果通过路由切换到主应用对应的组件，可以通过
    setCurrentRunningApp(null);
    或
    const rawAppendChild = HTMLHeadElement.prototype.appendChild;
    const rawAddEventListener = window.addEventListener;
    HTMLHeadElement.prototype.appendChild = rawAppendChild;
    window.addEventListener = rawAddEventListener;
    这种方式 在 路由守卫那里做处理，能保证切换到主路由的组件样式正常
    c) 但是，如果不是路由切换的，只是主应用的动态组件（diag?? drawer?? ），style动态插入到header这种，会发现加载不了。

**Comment by chen735623058** [comment]
我发现这个问题的根本原因就是因为在代码里面通过get的代理监听了所有的对象变化然后处理样式是否是当前已加载的样式，再处理是否要加载新样式，这里有一个问题如果在切换路由的同时去改变页面的布局这种情况会有很多的Object属性发生变化，导致这个切换样式的判断事件无法在一帧之内完成，就会导致样式没有加载样式，特别是样式是挂在母工程上的，因为母工程的路由本来就不用需要去下载子工程的代码可以直接跳转页面。所以有两个方法可以解决 
1. 就是我上面说的改qiankun的源码 
2. 是在路由值守里面增加一个延时
```
router.beforeEach(async (to, from, next) => {
    if (hasToken) {
        // 这里获取一下当前的用户权限，主要是防止每次访问页面都要重新注册路由
        const hasRoles = store.getters.roles && store.getters.roles.length > 0;
        if (hasRoles) {
            // ！！！！！！ 发现就是在切换路由的时候因为业务需求需要根据路由的标记切换左侧的目录 就会引起这个问题
            store.dispatch('Permission/changemenurouters', _menutype);
            加上一个setTimeout 也可以解决，但是根源还是在框架里面的那一行代码
            setTimeout(()=> {
                next();
            },500)
        }
});
```

**Comment by Raven2049** [comment]
同有此问题，官方什么时候修复一下

**Comment by zhaojiankun6** [comment]
@chen735623058 你现在是暂时修改的源码解决吗？

**Comment by chen735623058** [comment]
@ zhaojiakun6  不是的 我这边是在切换路由的时候加了一个延时解决的。
`router.beforeEach(async (to, from, next) => {
    if (hasToken) {
        // 这里获取一下当前的用户权限，主要是防止每次访问页面都要重新注册路由
        const hasRoles = store.getters.roles && store.getters.roles.length > 0;
        if (hasRoles) {
            // ！！！！！！ 发现就是在切换路由的时候因为业务需求需要根据路由的标记切换左侧的目录 就会引起这个问题
            store.dispatch('Permission/changemenurouters', _menutype);
            加上一个setTimeout 也可以解决，但是根源还是在框架里面的那一行代码
            setTimeout(()=> {
                next();
            },500)
        }
});`

**Comment by chengxuan12** [comment]
> ![image](https://user-images.githubusercontent.com/6779783/177674461-a918b2d4-18bf-4ea0-9fa9-e942f289a5eb.png) 就是因为这次代码更新引起的

代码位置调整，看上去为了解决 #1486 #1266

**Comment by chengxuan12** [comment]
> ![image](https://user-images.githubusercontent.com/6779783/177674461-a918b2d4-18bf-4ea0-9fa9-e942f289a5eb.png) 就是因为这次代码更新引起的

代码位置调整，看上去为了解决 https://github.com/umijs/qiankun/pull/1486 https://github.com/umijs/qiankun/issues/1266

**Comment by chengxuan12** [comment]
> ![image](https://user-images.githubusercontent.com/6779783/177674461-a918b2d4-18bf-4ea0-9fa9-e942f289a5eb.png) 就是因为这次代码更新引起的

这块代码的更新，看上去是为了解决 #1266 的问题。

我用的是2.8.0版本。 this.registerRunningApp(name, proxy) 等价于
 setCurrentRunningSandboxProxy(proxy);
 nextTick(() => setCurrentRunningSandboxProxy(null));

我也出现了这个问题。因为发现触发的是get里的 'Symbol(Symbol.unscopables)'。
所以尝试放在 ` if (p === Symbol.unscopables) return unscopables;  ` 的后面。

<img width="972" alt="image" src="https://user-images.githubusercontent.com/12962551/215315133-5415ef55-ca64-4b0d-bd57-f896d72f4ea9.png">
