### ISSUE TITLE
[Feature Request] 子应用服务挂掉后，主应用报you need to export lifecycle functions in xx entry 的问题

### ISSUE THREAD

**Issue by wongfugui** [umijs/qiankun#2179]
在主应用注册了子应用相关信息，但是子应用服务挂掉后，导致请求不到对应的文件，主应用就会报you need to export lifecycle functions in xx entry，导致页面直接白屏。这种情况是否有办法能不报错显示404页面？或者能在哪捕获到报错，至少让页面不是全部白屏？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1127
