### ISSUE TITLE
[Bug]publicPath动态从父容器获取与写死publicPath表现不一致

### ISSUE THREAD

**Issue by Yukyi** [umijs/qiankun#218]
## What happens?
当设置动态的publicPath时，src文件外的文件，比如public里的一些json文件或者图片的地址就匹配不上publicPath。这样就必须把所有静态资源都放进src文件中了
在vue.config.js写死这个publicPath就没有这个问题

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
qiankun 注入的 runtimePublicPath 是你配置的 htmlentry 的地址的域名，检查下你配的 entry

**Comment by Yukyi** [comment]
htmlentry 的地址的域名没问题，其他的静态资源路径都是对的，只有动态配置时，src外的静态资源文件runtimePublicPath不一样

**Comment by kuitos** [comment]
来个可复现的仓库？

**Comment by F-loat** [comment]
* `public` 中的文件一般通过绝对路径进行引用，然后自行处理基础 URL [public 文件夹](https://cli.vuejs.org/zh/guide/html-and-static-assets.html#public-%E6%96%87%E4%BB%B6%E5%A4%B9)

* `vue-cli` 目前对 `__webpack_public_path__` 的支持应该是有问题的，建议还是直接写死 `publicPath` https://github.com/vuejs/vue-cli/issues/5002

* 在 vue 项目中使用 qiankun 框架可以用我封装的插件，对开发模式下的 `publicPath` 进行了自动处理 [vue-cli-plugin-qiankun](https://github.com/F-loat/vue-cli-plugin-qiankun/blob/master/index.js#L2-L22)
