### ISSUE TITLE
iphone13无法运行qiankun

### ISSUE THREAD

**Issue by zhaowend** [umijs/qiankun#2182]
## What happens?
qiankun 在xcode13上的模拟器以及真机调试都可以正常运行，但是当发布到正式版本的时候，从应用商店下载之后无法使用，发布值之后并不能查看错误类型，xcode上面调试没有任何报错

- **qiankun Version**: 2.7.3
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
大概率是因为 activeRule 不匹配，子应用没加载，部署的问题

**Comment by zbigdong** [comment]
我这边使用的是 capacitor打包ios 我发现打包发布之后物理地址（window.document.location.href）会从（http:localhost）变成 capacitor:/localhost#（模拟器是http:localhost/#），我使用的是history模式。activeRule是/main/micro_web（和子应用路径保持一致）在网页上能够正常使用，模拟器路径要加#/main/micro_web才能使用。我这边的疑问是打包之后的地址http://localhost/#是否对activeRule有影响？非常感谢

**Comment by zbigdong** [comment]
> 大概率是因为 activeRule 不匹配，子应用没加载，部署的问题,

这是我在ios设备中看到的href路径，无法匹配到子路由中/main/micro_web/yilukaiguan这个页面，子应用有加载进来
capacitor://localhost#/main/
micro_web/yilukaiguan?
id=62271760-bfce-11ec-
abf0-43720419f97f&name=1
703%E7%81%AF&buildingld
=fb4f4cc0-
bee1-11ec-85c1-43720419f9

**Comment by zhaowend** [comment]
忘记关闭了，确实是因为真机上面有个hash标识#导致无法匹配activeRule导致的，感谢
