### ISSUE TITLE
子应用切换时视觉问题

### ISSUE THREAD

**Issue by denglingbo** [umijs/qiankun#219]
## What happens?
切换菜单时，主子应用来回切换的时候，子应用出现闪烁，怀疑是样式为加载完毕

## 最小可复现仓库
官方demo 就有该问题

## 复现步骤，错误日志以及相关配置
1. html entry 的模式下
2. 快速来回切换菜单

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by zhangsalle** [comment]
这个问题，感觉是不是无解，appendChild link就会触发css请求，请求过程中先加载js和html，然后才请求回来link。link onload事件在304的情况下又无法触发

**Comment by kuitos** [comment]
> 这个问题，感觉是不是无解，appendChild link就会触发css请求，请求过程中先加载js和html，然后才请求回来link。link onload事件在304的情况下又无法触发

应该是有解的，在尝试一些新的思路插入动态样式。

304 应该也会触发 onload 的。

**Comment by zhangsalle** [comment]
> > 这个问题，感觉是不是无解，appendChild link就会触发css请求，请求过程中先加载js和html，然后才请求回来link。link onload事件在304的情况下又无法触发
> 
> 应该是有解的，在尝试一些新的思路插入动态样式。
> 
> 304 应该也会触发 onload 的。

我试了304不能触发onload，这样css和js的加载顺序就不可控。
后面如果有解决，麻烦同步下，谢谢🙏

**Comment by laixstx** [comment]
目前正被这个问题折磨，有什么解决方案吗？

**Comment by sleepq123** [comment]
Custom Elements are great for integrating components inside the browser. But when building a site that is accessible on the web, chances are that initial load performance matters and users will see a white screen until all js frameworks are downloaded and executed. Additionally, it’s good to think about what happens to the site if the JavaScript fails or is blocked. Jeremy Keith explains the importance in his ebook/podcast Resilient Web Design. Therefore the ability to render the core content on the server is key. Sadly the web component spec does not talk about server rendering at all. No JavaScript, no Custom Elements :(
自定义元素非常适合在浏览器内部集成组件。但是，当构建一个可在Web上访问的站点时，初始负载性能很重要，并且用户将看到白屏，直到下载并执行所有js框架。另外，最好考虑一下如果JavaScript失败或被阻止，网站会发生什么情况。杰里米·基思（Jeremy Keith）在他的电子书/播客“弹性Web设计”中解释了重要性。因此，在服务器上呈现核心内容的能力至关重要。可悲的是，Web组件规范根本没有讨论服务器渲染。没有JavaScript，没有自定义元素:(

**Comment by winjeysong** [comment]
感觉这个问题挺影响体验的，期待解决方案

**Comment by 957739315** [comment]
被同样的问题困扰，希望能尽快修复，或者提供相应的解决方案。

**Comment by maquannene** [comment]
这个问题现在有解了吗？
目前只能把子应用的打包模式搞成 不切片，一旦有动态加载，就会出问题。
例如使用 umi 的 dynamicImport 配置，就会出现切换子应用，重新加载子应用时会加载一下  css chunk，但此时 js 已经加载好了，此时样式错乱。开启浏览器 slow 3g 的时候，现象很明显。

**Comment by yaoleia** [comment]
是不是还没有方案，难受。。

**Comment by maquannene** [comment]
有这个问题的话，暂时使用  styleLoader 来解决吧。
不要单独打出来 css chunk，直接把 css 插到 dom 中。

**Comment by qinyouzhi** [comment]
> 有这个问题的话，暂时使用 styleLoader 来解决吧。 不要单独打出来 css chunk，直接把 css 插到 dom 中。

能发一下配置代码吗

**Comment by dadazhouRenee** [comment]
> 有这个问题的话，暂时使用 styleLoader 来解决吧。 不要单独打出来 css chunk，直接把 css 插到 dom 中。
我这边也有 样式没加载出来之前 先计算了元素的高度 就会有问题
@maquannene  请问是这样配置的吗 可能一些第三方插件的样式 会覆盖项目样式呢 
```
styleLoader: {
  injectType: 'singletonStyleTag'
}
```

**Comment by maquannene** [comment]
> > 有这个问题的话，暂时使用 styleLoader 来解决吧。 不要单独打出来 css chunk，直接把 css 插到 dom 中。
> > 我这边也有 样式没加载出来之前 先计算了元素的高度 就会有问题
> > @maquannene  请问是这样配置的吗 可能一些第三方插件的样式 会覆盖项目样式呢
> 
> ```
> styleLoader: {
>   injectType: 'singletonStyleTag'
> }
> ```
styleLoader: {} 就可以，如果希望样式全都集中在一个 <style /> 中，就用 singletonStyleTag；

不过这样还是存在一些弊端，目前经过我们项目的大规模实践，一旦 css 量非常大时，styleLoader 的解析 + 插入 <style /> 就会非常慢。

**Comment by dadazhouRenee** [comment]
插入很慢的话 是对打包时长有影响么 还是什么别的方面啊 @maquannene

**Comment by maquannene** [comment]
> 插入很慢的话 是对打包时长有影响么 还是什么别的方面啊 @maquannene

打包影响不关键，打包时长只会影响开发者；

插入是切换应用执行时的处理，影响就是切换应用速度变慢、变卡、或者一小段白屏 loading，对用户体验不好；

**Comment by Ivy1994** [comment]
请问这个问题现在解决了么？

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by cqh52306** [comment]
mark，同样被困扰，特别是多个子应用来回切换的时候特别明显

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by bingjieL** [comment]
mark

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by Liyu123123** [comment]
有新解决办法了吗

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by dashaowang** [comment]
有大佬解决了吗

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by qinyouzhi** [comment]
SC_DISABLE_SPEEDY=true




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/qiankun] 子应用切换时视觉问题 (#219)





 
有大佬解决了吗

**Comment by dashaowang** [comment]
> SC_DISABLE_SPEEDY=true
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月6日(星期二) 下午4:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [umijs/qiankun] 子应用切换时视觉问题 (#219) 有大佬解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬  我目前没有用到css in js也可以用这个环境变量吗?是加在主系统还是子系统呢？

**Comment by qinyouzhi** [comment]
没用css in js我就不清楚了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/qiankun] 子应用切换时视觉问题 (#219)





  
SC_DISABLE_SPEEDY=true
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月6日(星期二) 下午4:25 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [umijs/qiankun] 子应用切换时视觉问题 (#219) 有大佬解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
大佬  我目前没有用到css in js也可以用这个环境变量吗?是加在主系统还是子系统呢？

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by ivesein** [comment]
有大佬有解决办法吗

**Comment by mo-ocean** [comment]
css:{
extract: false
}
把css 打包到 js 文件里面，不要单独加载

**Comment by mo-ocean** [comment]
css:{
extract: false
}
把css 打包到 js 文件里面，不要单独加载

**Comment by batmanSix** [comment]
> css:{ extract: false } 把css 打包到 js 文件里面，不要单独加载

亲测能解决么？

**Comment by mo-ocean** [comment]
> > css:{ extract: false } 把css 打包到 js 文件里面，不要单独加载
> 
> 亲测能解决么？

我负责的项目就是这样做的，另外快速切换的时候 给菜单加一个防抖，300ms 够了

**Comment by batmanSix** [comment]
> > > css:{ extract: false } 把css 打包到 js 文件里面，不要单独加载
> > 
> > 
> > 亲测能解决么？
> 
> 我负责的项目就是这样做的，另外快速切换的时候 给菜单加一个防抖，300ms 够了

但是这样有个问题你webpack 或者vite 打包的css 跟js 不分离会导致js产物过大加载慢

**Comment by mo-ocean** [comment]
> 

目前的网络速度，加载很快的，这个不是问题，可以接受的程度，亲测设置慢速3G的情况，加载会比较慢

**Comment by yousmellnice** [comment]
我也遇到了这个问题，切换子应用的时候，样式文件的加载比较慢，但是有那么一瞬间闪烁，大家有解决思路吗？

**Comment by vaezc** [comment]
2023年了 还没有解决办法么

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by 2000dzh** [comment]
这个问题有解决方案吗，我最近也遇到了😭

**Comment by 957739315** [comment]
您好，你所发的邮件我已收到。需要回复的，请等待回复,我会尽快处理祝您平安幸福！

**Comment by kuitos** [comment]
> 这个问题有解决方案吗，我最近也遇到了😭

3.0会解决

**Comment by QiangTian1993** [comment]
mark

**Comment by Yibs2016** [comment]
mark

**Comment by ganggangtian** [comment]
> > 这个问题有解决方案吗，我最近也遇到了😭
> 
> 3.0会解决

3.0计划什么时候发布？或有没有单独方案先解决闪烁问题？

**Comment by ganggangtian** [comment]
> > 这个问题有解决方案吗，我最近也遇到了😭
> 
> 3.0会解决

3.0计划什么时候发布？或有没有单独方案先解决闪烁问题？ @kuitos

**Comment by CeceWall** [comment]
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Time ***@***.***>
发送时间: Thursday, April 20, 2023 4:14:58 PM
收件人: umijs/qiankun ***@***.***>
抄送: WeiJian ***@***.***>; Manual ***@***.***>
主题: Re: [umijs/qiankun] 子应用切换时视觉问题 (#219)


mark

―

**Comment by vaclock** [comment]
> 有这个问题的话，暂时使用 styleLoader 来解决吧。 不要单独打出来 css chunk，直接把 css 插到 dom 中。

可以直接给css文件强制缓存，这样再次切换回来浏览器就不会加载css文件，就不会有这个闪烁问题了
