### ISSUE TITLE
请问子应用使用monaco-editoer的时候，会出现无法加载workers的问题。子应用单独使用的时候不会出现问题

### ISSUE THREAD

**Issue by jiaruifeng1** [umijs/qiankun#2190]
![image](https://user-images.githubusercontent.com/46318244/179223848-6b2ecacc-83bf-4ebd-9005-9795952eacb3.png)

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1586#issuecomment-883825586
