### ISSUE TITLE
乾坤捕获不到分项目vue语法错误，控制到没有报错信息

### ISSUE THREAD

**Issue by yaoyuanrong** [umijs/qiankun#2191]
**背景：**
      线上环境，server传给我的一个列表数据缺少了某个关键字段，导致前端报错（本地开发能看到报错信息）列表渲染直接失败，整个页面假死。但是线上环境打开控制台看不到报错信息，前端很难去追查问题，无法快速定位问题
![image](https://user-images.githubusercontent.com/46862208/179348753-22e38716-3274-4b67-877c-acb86eaddbb0.png)

**思路：**
     能不能把分项目的报错信息透传到主项目上呢？
**版本：**
   qiankun: [2.0.16]
   chrome：103.0.5060.114（正式版本）
希望技术大大们有个反馈信息，谢谢各位

**Comment by gongshun** [comment]
大概率是因为你用了try catch 把报错拦截了

**Comment by yaoyuanrong** [comment]
> 
应该不是，我最后用Vue.config.errorHandler坚挺vue报错，然后 window.console.error  把错误信息在全局环境中打印出来才好使的

**Comment by Caveolaes** [comment]
> > 
> 
> 应该不是，我最后用Vue.config.errorHandler坚挺vue报错，然后 window.console.error 把错误信息在全局环境中打印出来才好使的

找到解决之法了么

**Comment by yaoyuanrong** [comment]
> 
在子项目的main.js加入
Vue.config.errorHandler = function (err, vm, info) {
  window.console.error('VueError', err, vm, info);
};

**Comment by HHH1994** [comment]
会不会和qiankun无关，我试了一下，vue-cli4+ , vue2.6+的版本进行打包，在没有加入Vue.config.errorHandler 的情况下，打包后的产物中发生ReferenceError被catch掉了，感觉和vue中的glob
![11111](https://user-images.githubusercontent.com/24916262/187615785-abafbefe-d9bf-4ae9-92af-33dc9e7ece76.png)
alHandleError，logError有关，我还没有完全定位出来

**Comment by yaoyuanrong** [comment]
> 会不会和qiankun无关，我试了一下，vue-cli4+ , vue2.6+的版本进行打包，在没有加入Vue.config.errorHandler 的情况下，打包后的产物中发生ReferenceError被catch掉了，感觉和vue中的glob ![11111](https://user-images.githubusercontent.com/24916262/187615785-abafbefe-d9bf-4ae9-92af-33dc9e7ece76.png) alHandleError，logError有关，我还没有完全定位出来

看上去把生产环境的报错直接try catch掉了，我后续在看看
