### ISSUE TITLE
父子应用为同域，通过文件夹区分地址，在通过父应用访问子应用时路由路径上会多出子文件夹名字

### ISSUE THREAD

**Issue by huhaoGitHub** [umijs/qiankun#2195]
基于qiankun和nuxtjs的微前端项目
主应用：http://zc.xx.ink/assets/
子应用：http://zc.xx.ink/base/

部署后主应用访问子应用xxx/xxx路径时，路径应为：http://zc.xx.ink/assets/base/xxx/xxx，但是会有二次跳转导致路由地址变成http://zc.xx.ink/base/assets/base/xxx/xxx。

相关版本：
nuxtjs 2.15.8
qiankun 2.7.3

**Comment by gongshun** [comment]
大概率是路由 base 设置问题
