### ISSUE TITLE
关于 jsSandBox的bug

### ISSUE THREAD

**Issue by DWDtest1** [umijs/qiankun#22]
即使配置jsSandbox： false， 也没有用， 因为getSandBox的逻辑是在registerMicroApps, 此时jsSandBox 为true; 所以此配置无效；

关于路由的问题最近在采坑， 我们的项目同时使用了hashHistory和browserHistory， 在切换的时候发现与react-router-dom 有冲突， 无法正确识别， 找了下RR的[issue](https://github.com/ReactTraining/react-router/issues/6304) 操作window.history好像不推荐；

我是直接在主应用调single-spa的singleSPANavigate的方法，不知道qiankun在内部推广的时候有没有好的建议啊

**Comment by kuitos** [comment]
> 即使配置jsSandbox： false， 也没有用， 因为getSandBox的逻辑是在registerMicroApps, 此时jsSandBox 为true; 所以此配置无效；

哪里看到的代码？贴一下

**Comment by DWDtest1** [comment]
registerMicroApps(
  [
    { name: 'react app', entry: '//localhost:7100', render, activeRule: genActiveRule('/react') },
    { name: 'vue app', entry: { scripts: [ '//localhost:7100/main.js' ] }, render, activeRule: genActiveRule('/vue') },
  ],
  {
    beforeLoad: [async app => {
      console.log('before load', app);
    }],
    beforeMount: [async app => {
      console.log('before mount', app);
    }],
    afterMount: [async app => {
      console.log('before mount', app);
    }],
    afterUnmount: [async app => {
      console.log('after unload', app);
    }],
  },
);

start({ prefetch: true, jsSandbox: false });   <  ---  这个false是没有用的， 因为sandbox 在register的时候就生成了

**Comment by kuitos** [comment]
https://github.com/umijs/qiankun/blob/master/src/index.ts#L53

可以自己 debug 看看执行流程

**Comment by DWDtest1** [comment]
let useJsSandbox = true;
export function start(opts: StartOpts = {}) {
  if (jsSandbox) {
    useJsSandbox = jsSandbox;
  }

这个 if 是多余的啊

**Comment by kuitos** [comment]
fixed, thx!

**Comment by kuitos** [comment]
其他问题可以提到这里 https://github.com/umijs/qiankun/issues/23  这个 issue 先关了
