### ISSUE TITLE
重复进入子应用时，子应用获取到的路由错误

### ISSUE THREAD

**Issue by viviprprpr** [umijs/qiankun#220]
## What happens?

重复进入子应用时，子应用获取到的路由错误

## 最小可复现仓库

https://github.com/viviprprpr/personal-test-umi-plugin-qiankun.git
万分感谢🙏

## 复现步骤，错误日志以及相关配置

点击进入子应用，浏览器点击返回，连续操作三次必定报警告，然后再点击进入子应用，浏览器路由变了，但是子应用获取到的还是上一个。

## 相关环境信息

- **qiankun 版本**
1.3.4
- **浏览器版本**：
chrome 79.0.3945.88
- **操作系统**：
mac

**Comment by Deturium** [comment]
你的问题描述不是很清楚，下次请给一下错误日志和示意
我试了一下，在主子应用间反复横跳的话有几率触发这个：
```
index.js:1 Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/knowledgespace".
```
随后再尝试跳往子应用的话会出现 404 的错误页

你说的是这个问题吗？


#### 解决方法

在 `src/app.js` 的主应用设置中，开启 `jsSandBox: true`

这样子应用的错误就不会影响主应用了


#### 问题原因

umi 的 history 路由是依赖于 `history` 库的 `createBrowserHistory` 的，创建 history 实例的时候有传入一个 `basename`，而在子应用中，你的 basename 是 `/knowledgespace`，因此当你尝试从子应用中后退的时（前往 `/`）会触发错误

你可以通过 `window.routerBase` 和 `window.g_history` 来查看 umi 的 history 实例的情况来验证这一点

**Comment by viviprprpr** [comment]
@Deturium 您好，确实是这个问题。

但是因为我需要兼容ie11，根据文档说明需要`jsSandBox: false`，所以有没有其他办法能够解决。

而且经过测试，当`jsSandBox: true`时，确实不会404了，但是有时候需要点两次浏览器返回才能正常返回

**Comment by Deturium** [comment]
不用 jsSandbox 的话，就得手动避免全局变量的冲突了，你这里就是要处理好 history

一个可行的思路是，手动使用 `history/createBrowserHistory` 来创建 history 对象，让各个子应用都使用同一个 history 来做路由，由此保证他们的路由都能正常工作

比如这样：https://alili.tech/archive/5ff0b366/#%E5%8F%AA%E6%9C%89%E4%B8%80%E4%B8%AAhistory

比较麻烦，得做不少定制化工作

**Comment by viviprprpr** [comment]
那这个后续会有优化或者jsSandbox兼容IE的计划么

现在可以暂时主应用使用browser，子应用使用hash，但是感觉不太好

**Comment by Deturium** [comment]
有计划，见 #182

**Comment by viviprprpr** [comment]
好的，非常感谢🙏

**Comment by laixstx** [comment]
> 你的问题描述不是很清楚，下次请给一下错误日志和示意
> 我试了一下，在主子应用间反复横跳的话有几率触发这个：
> 
> ```
> index.js:1 Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/knowledgespace".
> ```
> 
> 随后再尝试跳往子应用的话会出现 404 的错误页
> 
> 你说的是这个问题吗？
> 
> #### 解决方法
> 在 `src/app.js` 的主应用设置中，开启 `jsSandBox: true`
> 
> 这样子应用的错误就不会影响主应用了
> 
> #### 问题原因
> umi 的 history 路由是依赖于 `history` 库的 `createBrowserHistory` 的，创建 history 实例的时候有传入一个 `basename`，而在子应用中，你的 basename 是 `/knowledgespace`，因此当你尝试从子应用中后退的时（前往 `/`）会触发错误
> 
> 你可以通过 `window.routerBase` 和 `window.g_history` 来查看 umi 的 history 实例的情况来验证这一点

设置了 jsSandBox: true，但是从子应用切换到主应用，并在之后每次切换应用路由时，都会有类似报错：
```
Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/app1".
```
![image](https://user-images.githubusercontent.com/10735940/75839120-f74a2b00-5e02-11ea-90d1-942d9831c1ce.png)


重现仓库（umi-plugin-qiankun 的自带 examples 就有这个问题）：https://github.com/umijs/umi-plugin-qiankun

**Comment by topwood** [comment]
same +1
