### ISSUE TITLE
application 'sub-react' died in status LOADING_SOURCE_CODE: Unexpected token '<' 

### ISSUE THREAD

**Issue by wang-binbin** [umijs/qiankun#2200]
## What happens?
用react 做子应用 本地测试没问题，打包后nginx中出现这个报错

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by coderja** [comment]
遇到了同样的问题 请问你后来是怎么解决的呢

**Comment by zy0228** [comment]
同样的问题
