### ISSUE TITLE
[Bug] 主应用切换同一个子应用不同路由，导致子应用重复卸载与挂载

### ISSUE THREAD

**Issue by buxuku** [umijs/qiankun#2204]
## What happens?

通过主应用的菜单来切换子应用不同的路由，当两个菜单是同属于一个子应用时，依然会导致子应用先被卸载再重新挂载

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置

主应用采用的是antd pro + plugin-qiankun, 子应用为webpack配置的react应用

假如主应用配置如下菜单，

```javascript
[{
    path: '/app1/home',
    name: '子应用1首页',
    microApp: 'app1',
},
{
    path: '/app1/list',
    name: '子应用1列表页',
    microApp: 'app1',
},]

```
在主应用中，当菜单由`子应用1首页`切换至`子应用1列表页`时，会先触发子应用`app1`的`unmount`生命周期，卸载掉子应用，再重新挂载子应用，触发`mount`生命周期。
<img width="303" alt="image" src="https://user-images.githubusercontent.com/7866330/180983876-34c2a5d6-2cad-49cd-ad18-4bf1c6969928.png">

但如果配置成嵌套的形式，就是正常的，不会导致子应用的卸载。比如下面的配置：

```javascript
[{
    path: '/app1/',
    name: '子应用1菜单',
    microApp: 'app1',
    routes: [
       {
            path: 'home',
            name: '子应用1首页',
       },
       {
            path: 'list',
            name: '子应用1列表页',
       },
    ]
}]
```

而在实际的业务需求中，子应用的路由可能分布在主应用的多处菜单当中，不一定完全嵌套到一个菜单下面。

## 相关环境信息

- **qiankun 版本** `"@umijs/plugin-qiankun": "^2.39.2",`
- **浏览器版本**： chrome 103.0.5060.134
- **操作系统**： mac os

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1105#issuecomment-827294328
