### ISSUE TITLE
[Feature Request] vue2 实现微前端抽屉化（组件化）

### ISSUE THREAD

**Issue by heyden-suimu** [umijs/qiankun#2208]
## Background

技术栈  
 "vue": "^2.6.12",
 "vue-router": "^3.0.1"
有把子应用嵌套到Drawer抽屉里面，看了相关资料，貌似只能用umi或者Fes.js，但因为老代码不好升级vue3
![image](https://user-images.githubusercontent.com/21190653/181409914-0e0b5071-7c3d-47de-b06e-c726e9ede615.png)

## Proposal

实现低版本的vue框架的微前端组件化

## Additional context

大佬们有碰到这种场景，或者有解决思路吗？

**Comment by gongshun** [comment]
子应用会被加载到容器中啊，而容器放在哪里，还不是取决于你自己

**Comment by heyden-suimu** [comment]
> 子应用会被加载到容器中啊，而容器放在哪里，还不是取决于你自己

可能是我表达的不太清楚，我这边的场景是有B，C或者多个子应用会调用A子应用的抽屉（详情页），所以有多实例的情况，然后看了相关资料，好想解决多实例子应用的路由冲突问题，好想vue2.6的版本貌似解决不了，，，

**Comment by gongshun** [comment]
> 多实例子应用的路由冲突问题

直接用 vue-router 的 abstract 模式就行了

至于你说的在一个子应用调用另一个子应用的组件/页面，参考：https://juejin.cn/post/6856569463950639117#heading-25
