### ISSUE TITLE
子项目用vite-plugin-theme插件，主项目引入报错[import-html-entry]: error occurs while executing normal script，子项目单独启动是没问题的

### ISSUE THREAD

**Issue by gaofeng222** [umijs/qiankun#2210]
我们有两个项目，都是用的jeecg的vue3.0+vite2搭建的，子项目用到了vite-plugin-theme插件，单独启动是没问题的，但是主应用接入后就报错了，导致整个页面样式错位了！
经排查，问题应该就出现在这里，但是不知道怎么解决，是qiankun的问题，还是vite插件的问题
![image](https://user-images.githubusercontent.com/18065659/181435449-b1824501-32f4-4f6b-92af-776076a70c9e.png)

![image](https://user-images.githubusercontent.com/18065659/181434919-3c24b017-2739-4b34-ab4c-468d213870e8.png)

## 相关环境信息
- **qiankun 版本**
- "qiankun": "^2.5.1",
- "vite": "^2.6.10",
-  插件"vite-plugin-theme": "^0.8.1",
- **浏览器版本**：
-  chrome
- **操作系统**：
- window10

**Comment by 992forever** [comment]
@gaofeng222 你好请问你解决了吗？我也遇到了相似的问题

**Comment by gaofeng222** [comment]
> 没有呢，在等官方的解决方案，vite-plugin-theme插件也有人提这个issue，但是官方没人回应

**Comment by gaofeng222** [comment]
> @gaofeng222 你好请问你解决了吗？我也遇到了相似的问题
还没有解决，我这是开发的时候就有问题，也有人在vite-plugin-theme那边提到，但是还没人回复解决方法
https://github.com/vbenjs/vite-plugin-theme/issues/13

**Comment by zqy233** [comment]
qiankun支持vite了？

**Comment by lucky-zouzou** [comment]
请问作者解决了吗？我的项目没有装vite-plugin-theme，线上环境也出现一样的报错，找不到原因 T T

**Comment by zhaohuanyuu** [comment]
有解决的同学吗

**Comment by JohnsonCoding** [comment]
有解决的朋友吗？急急急

**Comment by JohnsonCoding** [comment]
@gaofeng222 你好，请问最后怎么解决的，谢谢了

**Comment by dxh110** [comment]
这个问题到24年了，现在解决了吗 @gaofeng222
