### ISSUE TITLE
AntD confirm 等全局挂载且有监听的组件切换子应用时，会报错并系统崩溃。

### ISSUE THREAD

**Issue by dbkillerf6** [umijs/qiankun#222]
## What happens?
开着 sandbox，然后在一个子应用里用 antd 的 confirm 的 onOk 跳另一个子应用就会报错，原因应该是 unmount 的时候，挂载在 window 上的监听没有清除。

<img width="1357" alt="4DC6B242-D7F2-486B-89E6-2A281186807F" src="https://user-images.githubusercontent.com/59460901/71983962-e649c700-3262-11ea-81bb-d948804c0770.png">

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/dbkillerf6/qiankun

### Step 1:
<img width="1673" alt="DE002A86-8E9A-4736-8BFC-D7298573DD2E" src="https://user-images.githubusercontent.com/59460901/71984304-8bfd3600-3263-11ea-9299-2138eea28748.png">

### Step 2:
<img width="1679" alt="C4A9277E-02DF-4560-8A1C-8735C030A9EB" src="https://user-images.githubusercontent.com/59460901/71984367-acc58b80-3263-11ea-9558-13d4d8c11d90.png">

## Context

- **qiankun Version**: 1.3.11
- **Browser Version**: chrome 79.0.3945.88
- **OS Version**：Mac 10.14

**Comment by Deturium** [comment]
~~咦，这个问题照理说要出错早应该暴露了呀。。~~

#### 问题原因

这个报错是由于 qiankun 做 js 沙箱的时候使用了 Proxy，而 MDN 上说
```
The set method should return a boolean value. Return true to indicate that assignment succeeded. If the set method returns false, and the assignment happened in strict-mode code, a TypeError will be thrown.
```

确实如你推测，在沙箱卸载了之后，依旧有人往 fakeWindow 上 set 属性，这个时候我们返回了 false 导致抛出了异常，由此引发了后面的卡死


通过打些 log，可以发现你的栗子里，是由于 React 尝试改 window.event 导致的，这个跟 React 的事件代理机制的实现有关，相关 React 代码在这里 [invokeGuardedCallback](https://github.com/facebook/react/blob/c11015ff4f610ac2924d1fc6d569a17657a404fd/packages/shared/invokeGuardedCallbackImpl.js#L182)

而去看 antd 的 confirm 的源码的话会发现 onclick 之后实际上 antd 还干了些别的操作（比如 setState 之类的），导致了有新的 React 事件触发

这样的话其实复现 demo 的核心部分可以变成这样

```js
function goto(title, href) {
  window.history.pushState({}, title, href);
  setTimeout(() => {
    windos.event = 'set value after jsSandbox unmount';
  }, 50)
}
```

本质上就是由于沙箱卸载之后，还在往旧沙箱对象新增/修改属性导致的


#### 解决方法

可以考虑让 Proxy 永远返回 true，这里 throw Error 似乎没有价值
@kuitos

**Comment by ganluren007** [comment]
该问题还是会出现
