### ISSUE TITLE
无法监听到 子应用加载失败的事件

### ISSUE THREAD

**Issue by Huhui-coder** [umijs/qiankun#2224]
当子应用发生如下错误时：
<img width="963" alt="wecom-temp-c6767c4bc23f77dd1f6b9b40a583a42f" src="https://user-images.githubusercontent.com/37322200/182362518-14003ae5-8573-46cf-80f2-a8d2195b918c.png">
在主应用中，无法使用 window.addEventListener("unhandledrejection", (e) => {}) 监听到。

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api#addglobaluncaughterrorhandlerhandler
