### ISSUE TITLE
如何实现同一个页面手动加载多个微应用

### ISSUE THREAD

**Issue by freshhu** [umijs/qiankun#2225]
## Background

想实现一个页面可以由多个微应用拼凑而成的页面，该如何配置和实现？

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by gongshun** [comment]
官方demo里面就有一个例子 https://github.com/umijs/qiankun/blob/master/examples/main/multiple.js

**Comment by freshhu** [comment]
@gongshun 谢谢  我看看

**Comment by freshhu** [comment]
> 官方demo里面就有一个例子 https://github.com/umijs/qiankun/blob/master/examples/main/multiple.js

谢谢 我下载运行一下看看

**Comment by freshhu** [comment]
> 官方demo里面就有一个例子 https://github.com/umijs/qiankun/blob/master/examples/main/multiple.js

![image](https://user-images.githubusercontent.com/32830559/182594313-b9d55ef0-3952-4a6c-bb1f-5ec021bce129.png)
看着不像，这个还是只能展示一个微应用。我想要一个首页能够同时展示2个以上的微应用，就是这个页面是由微应用1、微应用2、微应用3 多个微应用组成，并一次性加载出来。

**Comment by jk4235** [comment]
```ts
import { loadMicroApp } from "qiankun";
const app = loadMicroApp(
    {
      name: appName,
      entry: resourceEntry,
      container: appContainer,
      props: appProps,
    },
    { singular: true, sandbox: { experimentalStyleIsolation: true } }
);
```
直接在你希望加载的地方手动调用这个方法就好了,当然你也要手动管理下unmount之类的,根据你的业务需要

**Comment by freshhu** [comment]
@gongshun @jk4235 主要想实现如下图的效果：（比如都是vue项目，那么怎么配置路由呢？）

![129536626-22a0655c-d836-429a-9f8c-2d4a9ed33ce9](https://user-images.githubusercontent.com/32830559/182997021-8acca0d3-ec18-4cdb-90d6-43cd7d9374a5.png)

**Comment by gongshun** [comment]
> @gongshun @jk4235 主要想实现如下图的效果，同时在一个页面上展示：（比如都是vue项目，那么怎么配置路由呢？）
> 

https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

**Comment by freshhu** [comment]
> https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

谢谢大佬！

**Comment by yinran100** [comment]
> > @gongshun @jk4235 主要想实现如下图的效果，同时在一个页面上展示：（比如都是vue项目，那么怎么配置路由呢？）
> 
> https://github.com/gongshun/qiankun-vue-demo/tree/feature/abstract-route

如果是多个同名应用呢，能实现吗
