### ISSUE TITLE
[Feature Request] 主应用history，子应用hash路由。支持 /app/#/about 形式

### ISSUE THREAD

**Issue by thinkingc** [umijs/qiankun#2228]
## Background
![image](https://user-images.githubusercontent.com/23413521/183036322-ceb386dd-2ab2-479d-87fd-2bf2dbc01d29.png)
主应用使用history，子应用使用hash，主子都是react应用，但react-router不支持 /app/#/about 这种路由，子应用路由改变时页面不变。

## Proposal
期望支持 /app/#/about 这种路由

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1199#issuecomment-818740774
