### ISSUE TITLE
[Bug]子应用使用this.$router.push跳转当前地址报错

### ISSUE THREAD

**Issue by hql7** [umijs/qiankun#223]
## What happens?

子应用是vue项目，使用this.$router.push跳转当前地址报错，跳转到另一个地址没问题。保存信息：“NavigationDuplicated”，并且报错后f5刷新整个程序错误，错误信息：“Uncaught SyntaxError: Unexpected token '<'”。从地址栏进入跟路由才恢复

## 最小可复现仓库

可复现仓库：https://github.com/hql7/wl-qiankun

## 复现步骤，错误日志以及相关配置

1. 主应用导航至子应用路由A
2. 在子应用内使用this.$router.push导航A
即报错

## 相关环境信息

- **qiankun 版本** 1.3.11
- **浏览器版本**：谷歌
- **操作系统**：win10

**Comment by Deturium** [comment]
这两个都不是 qiankun 的问题

#### NavigationDuplicated 

这个是 vue-router 的报错，你应该是 push 相同路由了


#### Uncaught SyntaxError

至于 `Uncaught SyntaxError: Unexpected token '<'`，这是 `vue-cli-service` 的问题

默认情况下，它打包出来的 js 资源地址是相对路径，比如 `<script type="text/javascript" src="js/app.js"></script>`

当你在子应用路径下的时候（比如 `http://localhost:7770/basic/about`） ，上面的 js 资源就指向了 `/basic/js/app.js`，这你 F5 当然出错

**Comment by kuitos** [comment]
第二个问题配置 publicPath 就可以了

**Comment by F-loat** [comment]
* 第一个问题可能也是没有配置 vue-router 的 `base` 属性

> 配置后子项目内部跳转使用 `$router.push`，不同子项目间跳转需要使用 `history.pushState`

``` js
const router = new VueRouter({
  mode: 'history',
  base: window.__POWERED_BY_QIANKUN__ ? '/projectName' : '/',
  routes
})
```

* 配置 publicPath

``` js
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__
}
```

**Comment by hql7** [comment]
@kuitos @F-loat @Deturium 在我仓库里，既按照demo配置了publicPath，也配置了vue-router 的 base 属性。
![image](https://user-images.githubusercontent.com/23188802/72228893-8bf39200-35e5-11ea-820a-ecd698df12e0.png)
![image](https://user-images.githubusercontent.com/23188802/72228920-bfceb780-35e5-11ea-93fb-d34306b6c36d.png)

正常push相同路由应该没问题吧

**Comment by F-loat** [comment]
@hql7 查了一下，是 vue-router 本身的问题 https://github.com/vuejs/vue-router/issues/2872#issuecomment-519073998 ，只有使用 router-link 才不会抛出错误

**Comment by hql7** [comment]
@F-loat 路由问题看来只能这样啦。
f5刷新整个程序错误，错误信息：“Uncaught SyntaxError: Unexpected token '<'”这个，即便我配置publicPath也会存在，看来需要再排查了

**Comment by hql7** [comment]
第二个错误为在主项目vue.config.js里设置 publicPath: './',引起

**Comment by frei-x** [comment]
把 publicPath: './' 改相对路径改为  publicPath: '/' 根路径 . 或者只能用hash路由了
