### ISSUE TITLE
子应用动态路由切换不触发重新加载

### ISSUE THREAD

**Issue by zhaoxu666** [umijs/qiankun#2231]
我的项目中，页签缓存子应用路由采用的方式：https://github.com/gongshun/qiankun-vue-demo/tree/feature/keep-alive
现在在子应用中，动态路由不同页签间切换，页面不会重新加载

**Comment by zhaoxu666** [comment]
https://github.com/zhaoxu666/qiankun-vue-demo 这是我的git仓库地址。在app-vue-history子应用下，需要用到vue router中的动态路由，但是两个动态路由间切换，页面不会发生任何变化。期待您的回复

**Comment by gongshun** [comment]
https://github.com/zhaoxu666/qiankun-vue-demo/blob/c99ddb0957e3a5ee2bf8e0765962a8807052e5bd/app-vue-history/src/views/Detail.vue#L17

页面被keep-alive，再次加载不会触发 created 生命周期钩子啊，只会触发 activated 和 deactivated 

https://v2.cn.vuejs.org/v2/api/#keep-alive

**Comment by LeslieCheung-FCC** [comment]
我现在也有同样问题，第一次从主应用切换到子应用正常，从子路由切换到主应用也正常加载，此时再切换到子路由不能重新加载，不论怎么切换子应用路由页面一直停留在上一次离开的子应用页面

**Comment by rookie-zhou** [comment]
我也遇到 相同的问题 必须重新加载dom才能正常，但是这样导致页面整体刷新

**Comment by masteralva** [comment]
有解决方案吗。或者 是什么问题导致的。 我也遇到了

**Comment by 905868332** [comment]
> 我现在也有同样问题，第一次从主应用切换到子应用正常，从子路由切换到主应用也正常加载，此时再切换到子路由不能重新加载，不论怎么切换子应用路由页面一直停留在上一次离开的子应用页面

我也遇到了，咋整啊
