### ISSUE TITLE
[Feature Request] 进入已经加载过的子应用，只会重新请求css吗？

### ISSUE THREAD

**Issue by wongfugui** [umijs/qiankun#2235]
## Background

第一次进入子应用，查看控制台，发现请求了js文件和css文件，离开子应用再次进入，发现只请求了css文件，是对js做了保存吗？目前在第二次进入子应用时，会先显示一个没有任何样式的页面，然后才渲染出对应的样式，是因为js已经存在了，所以渲染出了界面，但是css文件并未加载，直到css文件请求到后才渲染出样式？这种现象如何避免？

**Comment by ivesein** [comment]
哥们 这个问题咋解决的
