### ISSUE TITLE
[Bug]render({ appContent, loading })函数优化

### ISSUE THREAD

**Issue by hql7** [umijs/qiankun#224]
## What happens?

render({ appContent, loading }) 函数要求用户调用 render()时传入一个对象，即便是 render({})，否则将报错。所以至少将示例中render({ appContent, loading }) -> render({ appContent, loading } = {})

## 最小可复现仓库

qiankun仓库

## 复现步骤，错误日志以及相关配置

不想使用loading或其他配置，直接 render()

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
appContent 也不要？

**Comment by hql7** [comment]
@kuitos https://github.com/umijs/qiankun/blob/master/examples/main/index.js  demo中会先调用一下render({ loading: true }); 如果将loading配置去掉直接调用render()，则会报错

**Comment by kuitos** [comment]
没明白什么场景？为什么会直接调用 render ？

**Comment by F-loat** [comment]
* Vue 项目的话可以参考下我的这种写法 [App.vue](https://github.com/F-loat/vue-cli-plugin-qiankun/blob/master/generator/template/master/src/App.vue)

* React 项目的话首次 render 和之后每次的逻辑都是一致的，感觉没有必要做区分，首次可以直接 

``` js
render({ appContent: null })
```

**Comment by kuitos** [comment]
还是没看懂。。 你说的是 qiankun 的要求配置的 render 函数可以什么都不传还是说 demo 里的写法可以优化？

**Comment by kuitos** [comment]
> @kuitos https://github.com/umijs/qiankun/blob/master/examples/main/index.js demo中会先调用一下render({ loading: true }); 如果将loading配置去掉直接调用render()，则会报错

demo 里的实现只是个示例，报错是因为实现问题，跟 qiankun 本身没关系吧。。我改下 demo 好了

**Comment by hql7** [comment]
@kuitos @F-loat 是的，只是实现问题。我意思是如果render()这种情况会报错，何不做下小小的处理

**Comment by kuitos** [comment]
@hql7 loading 参数可以是 optional，但是 appContent 应该是 required 的，render 参数为空对于 qiankun 而言是没意义的，或者说是不合法的，不应该兼容

**Comment by kuitos** [comment]
况且报错是因为 demo 里的实现报的错，qiankun 本身没给你抛任何异常啊..
