### ISSUE TITLE
子应用html引入第三方依赖时出现replaced by import-html-entry，集成到主应用中时失效

### ISSUE THREAD

**Issue by MainPri** [umijs/qiankun#2244]
## What happens?
子应用的index.html中引入第三方js依赖的时候会失效，观察dom时发现添加“replaced by import-html-entry”

## How To Reproduce
子应用页面中添加livePlayer，Mqtt通信等依赖包，子应用单独运行没有问题，当与主应用集成时，会提示如下错误
![image](https://user-images.githubusercontent.com/25527317/185521091-76f511f1-1fbf-443f-a522-728379334eaa.png)
子页面应用的依赖
![image](https://user-images.githubusercontent.com/25527317/185521129-e8207779-6876-471b-9433-164694c2d41b.png)

## Context
qiankun ^2.7.4
vue  ^2.6.12

**Comment by jieyuming** [comment]
我也遇到该问题，你们最后有解决吗
