### ISSUE TITLE
[Bug]qiankun子项目引入webpack5属性ModuleFederationPlugin 报错找不到子项目生命周期函数

### ISSUE THREAD

**Issue by w123angmeng** [umijs/qiankun#2256]
## 问题描述

qiankun子项目引入webpack5 ModuleFederationPlugin 报错找不到子项目生命周期函数
qiankun2.x 到底支不支持ModuleFederationPlugin？希望给个定论，好几个issue相关的，大家都踩坑，望答复

## 最小可复现仓库

https://github.com/w123angmeng/demo

## 复现步骤，错误日志以及相关配置

复现步骤：
1. cd main && cnpmi && npm run serve        // qiankun基座 http://localhost:3000/
    cd common && cnpmi && npm run serve // 公共组件库 http://localhost:3003/
    cd app1 && cnpmi && npm run serve       // qiankun子组件 http://localhost:3001/
    cd app2 && cnpmi && npm run serve       // qiankun子组件 http://localhost:3002/
2. 打开http://localhost:3000 点击页面tab app1，页面报错“找不到子应用生命周期函数”

报错信息如下：
`Uncaught Error: application 'app1' died in status LOADING_SOURCE_CODE: [qiankun]: You need to export lifecycle functions in app1 entry
    at getLifecyclesFromExports (loader.js:220:9)
    at _callee17$ (loader.js:325:37)
    at tryCatch (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at fulfilled (tslib.es6.js:71:58)`

尝试排错：
打断点查看getLifecyclesFromExports判断是否导出生命周期函数在 子应用导出生命周期函数之前执行了，很不解！！！
子应用入口文件写法：
const { bootstrap, mount, unmount } = await import('./bootstrap')
export { bootstrap, mount, unmount }

## 相关环境信息

- **qiankun 版本**：qiankun@2.7.4
- **浏览器版本**：104.0.5112.102（正式版本） （64 位）
- **操作系统**：Windows 10 专业版

**Comment by fantasticsoul** [comment]
推荐 hel-micro https://github.com/tnfe/hel
hel-micro, 模块联邦 sdk 化，免构建、热更新、工具链无关的微模块方案
相关文章介绍：[hel-micro 模块联邦新革命](https://juejin.cn/post/7138792768234586148)

**Comment by Una2** [comment]
+1

**Comment by Una2** [comment]
大佬现在有解决方案吗？

**Comment by chenshuaifeng110** [comment]
就是给出的答案千奇百怪，连一个能用的都没有。webpack5现在都在用，连基本的需求都搞不定，请大家回答的时候贴上依赖版本，要不然又在自说自话

**Comment by weihuago4** [comment]
子应用使用联邦模块的话，打包的入口文件bootstrap内容应该是
`import("index")`
因为没有向外暴露qiankun的声明钩子函数，所以会报错
可以在index文件中暴露生命周期函数，然后在bootstrap文件向外暴露生命周期函数
`
const p = import("index")

export const bootstrap = () => p.then(m => m.boostrap());
export const mount = () => p.then(m => m.mount());
export const unmount = () => p.then(m => m.unmount());
`

**Comment by weihuago4** [comment]
子应用使用联邦模块的话，打包的入口文件bootstrap内容应该是
import("index")
因为没有向外暴露qiankun的声明钩子函数，所以会报错
可以在index文件中暴露生命周期函数，然后在bootstrap文件向外暴露生命周期函数
`const p = import("index")

export const bootstrap = () => p.then(m => m.boostrap());
export const mount = () => p.then(m => m.mount());
export const unmount = () => p.then(m => m.unmount());`

**Comment by weihuago4** [comment]
子应用使用联邦模块的话，打包的入口文件bootstrap内容应该是
`import("index")`
因为没有向外暴露qiankun的声明钩子函数，所以会报错
可以在index文件中暴露生命周期函数，然后在bootstrap文件向外暴露生命周期函数
```
const p = import("index")
export const bootstrap = () => p.then(m => m.boostrap());
export const mount = () => p.then(m => m.mount());
export const unmount = () => p.then(m => m.unmount());
```

**Comment by warplan** [comment]
遇到相同的问题，有大佬能提供解决方案吗

**Comment by HULIANGA** [comment]
> 遇到相同的问题，有人解决了吗

我是这样搞的，跟你楼上的方法差不多
``` js
// 联合模块如果需要配置shared，需要用一个异步import引入main，然后把这个文件作为入口
// import('./main')相当于import('./main').then(() => {})
// 由于qiankun子应用要导出生命周期钩子，所以需要用await的方式
// 要使用await需要配置webpack：
// experiments: {
//   topLevelAwait: true
// },
const { bootstrap, mount, unmount, update } = await import('./main')
export { bootstrap, mount, unmount, update }
```

**Comment by gezhicui** [comment]
> > 遇到相同的问题，有人解决了吗
> 
> 我是这样搞的，跟你楼上的方法差不多
> 
> ```js
> // 联合模块如果需要配置shared，需要用一个异步import引入main，然后把这个文件作为入口
> // import('./main')相当于import('./main').then(() => {})
> // 由于qiankun子应用要导出生命周期钩子，所以需要用await的方式
> // 要使用await需要配置webpack：
> // experiments: {
> //   topLevelAwait: true
> // },
> const { bootstrap, mount, unmount, update } = await import('./main')
> export { bootstrap, mount, unmount, update }
> ```

这样还是不行

**Comment by kuitos** [comment]
https://github.com/umijs/qiankun/issues/2256#issuecomment-1382643752 这个是正解

**Comment by kuitos** [comment]
> [#2256 (comment)](https://github.com/umijs/qiankun/issues/2256#issuecomment-1382643752) 这个是正解

@gongshun 感觉可以加到 FAQ 里

**Comment by Ahuzsp** [comment]
![sort](https://github.com/user-attachments/assets/8d9b3e2e-f6bb-4a4b-8a63-646d3769868c)
我这样尝试了可以，手动控制一下app和remoteApp的加载顺序
