### ISSUE TITLE
[Feature Request] say something

### ISSUE THREAD

**Issue by yizuierguo** [umijs/qiankun#2259]
我们现在在qiankun中使用了globalState，会警告：“globalState.js:18 [qiankun] globalState tools will be removed in 3.0, pls don't use it!” 请问globalState会废弃吗？
另外在3.0中要如何使用类似全局变量功能，还有3.0的大概发布时间是什么时候？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/discussions/1378
