### ISSUE TITLE
[Bug]子应用无法获取window，导致百度地图无法使用

### ISSUE THREAD

**Issue by IronRookie** [umijs/qiankun#2262]
![image](https://user-images.githubusercontent.com/32155725/188069473-e00f8334-160e-4e57-a4ca-cd7f0d0980e9.png)
如图所示，将百度地图传入props以后，可以在子应用通过
![image](https://user-images.githubusercontent.com/32155725/188069561-efee8414-a344-4ee3-a631-066c3a686b89.png)
此方法创建地图，但是百度地图原本会在window中注入其他变量，比如
![image](https://user-images.githubusercontent.com/32155725/188069681-dc79dd06-d36e-4662-8376-8d4d3a366061.png)
但是不清楚是否是因为这个原因，导致地图会报错，影响一部分功能使用，这个时候该如何解决呢

**Comment by IronRookie** [comment]
![image](https://user-images.githubusercontent.com/32155725/188074552-875d72e5-fd53-4526-bd9b-1bf059079b82.png)
接入以后会报错，并且地图加载不出来

**Comment by gongshun** [comment]
主应用加载了百度地图，子应用直接使用就行了，没必要通过 props 传下来

**Comment by dleged** [comment]
可以把百度地图的动态加载的请求资源 excludeAssetFilter 过滤掉

**Comment by GOGOGOSIR** [comment]
> 主应用加载了百度地图，子应用直接使用就行了，没必要通过 props 传下来

可以正常加载，但是qiankun会抛出一个这样的警告
