### ISSUE TITLE
qiankun@2.7.5 与 typescript冲突

### ISSUE THREAD

**Issue by punyfish** [umijs/qiankun#2265]
## What happens?
项目无法启动：
![image](https://user-images.githubusercontent.com/38232683/188557514-7ae55841-6e12-4aaf-a463-c24430def41e.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

1.使用angular-cli 创建 一个angular-14工程
2.npm install qiankun
3. src/main.ts中 照着官网加入乾坤相关代码。
4.npm start 报错

## Context

- **qiankun Version**: 2.7.5
- **Platform Version**:  windows node16
- **Browser Version**:

**Comment by kuitos** [comment]
ts 版本升到最新
