### ISSUE TITLE
react子应用路由使用异步组件时，加载的组件chunk拆分js的publcPath不对, 导致访问404

### ISSUE THREAD

**Issue by Anthony-Zeng** [umijs/qiankun#2268]
## What happens?

webpack 设置了 publicPath: https://xxxx:9091/tenant_6898417330674466816/
子应用打包后，在本地使用serve 是访问正常的

**只有访问使用React.lazy引入的组件的时候是不正确**

子应用也设置了
> if (window.__POWERED_BY_QIANKUN__) {
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}

本地访问部署的请求地址
![image](https://user-images.githubusercontent.com/88867412/189028448-60bb5e1a-817d-4023-85d1-852f69e72c54.png)

生产环境访问的请求地址
![image](https://user-images.githubusercontent.com/88867412/189028796-083d85c4-494d-42b4-9958-0ed756472bd3.png)

**生产环境是手动加载的子应用**

## Mini Showcase Repository(REQUIRED)

暂时没有

## Context

- **qiankun Version**: 2.4.3
- **Platform Version**: react 16.8.6
- **Browser Version**:

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/915
