### ISSUE TITLE
我现在也有同样问题，第一次从主应用切换到子应用正常，从子路由切换到主应用也正常加载，此时再切换到子路由不能重新加载，不论怎么切换子应用路由页面一直停留在上一次离开的子应用页面

### ISSUE THREAD

**Issue by rookie-zhou** [umijs/qiankun#2269]
我现在也有同样问题，第一次从主应用切换到子应用正常，从子路由切换到主应用也正常加载，此时再切换到子路由不能重新加载，不论怎么切换子应用路由页面一直停留在上一次离开的子应用页面

_Originally posted by @LeslieCheung-FCC in https://github.com/umijs/qiankun/issues/2231#issuecomment-1241430189_

**Comment by rookie-zhou** [comment]
主应用菜单配置了子应用路由，在主应用菜单点击子应用对应的路由例如app1/about 能成功加载，此时点击主应用app1/user 浏览器地址栏发生变化，但是页面未切换到子应用对应的页面
在 link上配置 reloadDocument 可以勉强解决 但是 页面刷新会导致白屏 体验不好

**Comment by rfw** [comment]
@rookie-zhou  解决了吗？怎么解决的？

**Comment by superermiao** [comment]
这个可能是子应用加载路由时拿不到上次的路由，出现失败，我这边是有报错的，主要是pushState报错。我的解决方案是：
<img width="753" alt="image" src="https://user-images.githubusercontent.com/24588825/199436295-a715097c-0d40-4b8d-9f32-e2e9727241ad.png">

**Comment by 905868332** [comment]
我也遇到了，主应用子应用都是vue2，这该怎么解决啊
