### ISSUE TITLE
[Bug]更新npm依赖包后，不适配IE浏览器，报 对象不支持“contains”属性或方法

### ISSUE THREAD

**Issue by jsjgsr** [umijs/qiankun#2274]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

在2022.9月前，项目可在ie环境中心运行
公司内部npm包依赖环境更新后，项目重新下载包进行编译，项目在ie环境中加载部分组件报错。
ie报错信息如下。
![image](https://user-images.githubusercontent.com/14258302/190837444-0eaaa8c2-b587-4403-a51b-cad529b6703e.png)
![image](https://user-images.githubusercontent.com/14258302/190837457-f65ca3f6-d9ef-4ee4-a076-a2bac936735b.png)

业务代码没有进行过修改。相同代码8月构建的时候可以运行，现在构建无法运行
- **qiankun 版本**
- "qiankun": "2.4.10",
- "@umijs/plugin-qiankun": "2.30.1",
- **浏览器版本**：
- ie11
- **操作系统**：
win

**Comment by gongshun** [comment]
这貌似不是 qiankun 的代码？ie的问题很早就兼容了 https://github.com/umijs/qiankun/pull/1016
