### ISSUE TITLE
可否支持重命名 __INJECTED_PUBLIC_PATH_BY_QIANKUN__ ?

### ISSUE THREAD

**Issue by Valar103769** [umijs/qiankun#2277]
## What happens?
因为 umi3 的`runtimepublicpath` [配置项]( https://v3.umijs.org/zh-CN/config#runtimepublicpath)需要的名字是 `window.resourceBaseUrl || window.publicPath` 而不是  `__INJECTED_PUBLIC_PATH_BY_QIANKUN__`
🙏

**Comment by Valar103769** [comment]
> https://github.com/umijs/umi-plugin-qiankun/blob/7c6e4cd96233b321e8dfd87f05a98f2adbd06a66/src/slave/index.ts#L55

真的吗? 我开启了没生效啊, 而且我看文档, 这个选项默认是关闭的啊

**Comment by Valar103769** [comment]
> 

@gongshun

**Comment by Valar103769** [comment]
> > https://github.com/umijs/umi-plugin-qiankun/blob/7c6e4cd96233b321e8dfd87f05a98f2adbd06a66/src/slave/index.ts#L55
> 
> 真的吗? 我开启了没生效啊, 而且我看文档, 这个选项默认是关闭的啊

不知道这个配置是什么鬼, 感觉问题不少 , 配置以后 ,报跨域的错, 但是我在控制台fetch试了,没有跨域啊



<img width="1843" alt="image" src="https://user-images.githubusercontent.com/36926073/190979555-8d5b2eeb-e677-4112-acf0-946366d43331.png">

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/36926073/190979431-539d024d-3033-441f-8ac5-11e842d73371.png">

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/2045#issuecomment-1098677300

**Comment by Valar103769** [comment]
> [#2045 (comment)](https://github.com/umijs/qiankun/issues/2045#issuecomment-1098677300)

那个人是关闭了该选项, 
我是主动开启, 或者借助pluhin-qiankun默认开启, 总之都是开启了. 我再描述下问题, 子应用使用umi3创建的,主应用使用vite+ qiankun,非umi

子应用配置如下 :
```js
// config/config.ts
export default defineConfig({
  base:'/',
 qiankun: {
    slave: {},
  },
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
  },
})

```

主应用
```js
// main.ts
import { start,registerMicroApps } from 'qiankun';

registerMicroApps([
    {
      name: 'react app', // app name registered
      entry: '//localhost:8000',
      container: '#yourContainer',
      activeRule: '/bi-v3',
    },
   
  ]);
  
  start();

app.mount('#app');
```

进入`http://127.0.0.1:5173/bi-v3` 时,  子应用有个登录时权限判断,跳转登录页
```js
      if (!isLogin) {
        history.push({
          pathname: loginPath,
          query: {
            ...location.query,
            ...(redirect && { redirect }),
          },
        })
      }
```
此时url为 `http://127.0.0.1:5173/user/login`  页面卡死
我尝试配置
子应用的 ` base:'/bi-v3'` 解决了这个问题, 所以并不像[文档说的, 注册插件](https://v3.umijs.org/zh-CN/plugins/plugin-qiankun#%E5%AD%90%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE)就行

```js
 export default {
  qiankun: {
    slave: {},
  },
}; 
```
所以
**问题1: 需要怎么配置base? 我没找到相关文档** 

之后会请求一个 `http://localhost:5173/devScripts.js` 文件, 这个地址端口错误了, 应该是子应用的8000端口, 这个端口是由window.__webpack_public_path__ 提供的吧? 
但是我在子应用打印 __webpack_public_path__ ,其值一直是 `http://localhost:8000/`,

**2. 端口问题是__webpack_public_path__ 来修改吗?** 
**3. 如何更正这个端口问题?**

@gongshun

**Comment by Valar103769** [comment]
@gongshun 你手里有antd pro 搭建的项目吧? 现在官网的脚手架坏了, 我给不了demo

**Comment by gongshun** [comment]
> @gongshun 你手里有antd pro 搭建的项目吧? 现在官网的脚手架坏了, 我给不了demo

以前试过，
主应用 Vue + 子应用: umi3，正常运行 https://github.com/umijs/qiankun/issues/2277#issuecomment-1251774633

**Comment by Valar103769** [comment]
> 

给个demo

**Comment by gongshun** [comment]
> 
> 给个demo

https://github.com/umijs/qiankun/issues/1536
