### ISSUE TITLE
代码仓库跑不起来

### ISSUE THREAD

**Issue by DanileQin** [umijs/qiankun#2279]
按照官网步骤：
yarn install - 选择1.12.0
yarn example:install - 在build的时候就报错了。
![image](https://user-images.githubusercontent.com/34501848/191411836-f917a3cd-9e24-41af-9225-8529dee225eb.png)

看了代码内部ts的报错内容是：
![image](https://user-images.githubusercontent.com/34501848/191412108-23d5b700-8ade-443b-bc46-e5ac196353b5.png)

**Comment by kuitos** [comment]
本地依赖版本没装对
