### ISSUE TITLE
【求教】多个子应用激活时路由竞争问题

### ISSUE THREAD

**Issue by ynchuan** [umijs/qiankun#2280]
业务中存在多个子应用同时激活时，基于路由驱动的子应用路由改造成本较高，所以想咨询下是否有可能在子应用上下文中重写histroy&location及popState等路由相关的方法，实现不可视路由的可能性。或者当前是否有更好的解决方案。

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%90%8C%E6%97%B6%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA%E5%BE%AE%E5%BA%94%E7%94%A8%E6%97%B6

**Comment by Rahim-Chan** [comment]
可以拦截路由响应

**Comment by MAXLZ1** [comment]
多个子应用同时激活时，`vue`采用`abstract`路由，`react`采用`memory`路由。

[https://maxlz1.github.io/micro-app-demos/qiankun-demo/vue3-main/dist/#/coexist-micro-app](https://maxlz1.github.io/micro-app-demos/qiankun-demo/vue3-main/dist/#/coexist-micro-app)

**Comment by wudith** [comment]
> 多个子应用同时激活时，`vue`采用`abstract`路由，`react`采用`memory`路由。
> 
> https://maxlz1.github.io/micro-app-demos/qiankun-demo/vue3-main/dist/#/coexist-micro-app

angular请问有没啥好的方案
