### ISSUE TITLE
主应用和子应用同时使用高德地图或者两个子应用都用到地图切换两个地图页面时会卡死

### ISSUE THREAD

**Issue by webwuyou** [umijs/qiankun#2286]
## What happens?

项目中主应用和一个子应用都用到了高德地图，都是使用cdn的形式在index.html引入地图的cdn链接，（所有应用都是vue项目），开始用的都是高德1.4.6的版本地图没有问题，但是因为1X的地图使用了document.write，会偶现子应用节点找不到的问题，所以升级地图到2.0。升级后在两个地图页面来回切换的时候会卡死。

后来测试，创建了三个空项目，接入qiankun，其中两个子应用接入高德地图也会出现卡死的情况（cdn形式，loader的形式都有问题）

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
git地址
https://github.com/webwuyou/qiankun-demo.git

## How To Reproduce

1、在进入main(主应用)，和vue1，vue2（两个子应用），分别执行npm install安装依赖，
2、分别执行npm run serve启动项目
3、在主应用的about页面和vue2子应用入口都使用了高德地图
4、在vue2的app.vue中有一行注释，改成this.map=new AMap.Map('vue2-map');，然后在主应用的about页面和app-vue2
这两个链接之间来回点击就会卡死
## Context

"qiankun": "^2.8.1",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0"

chrome：版本 98.0.4758.102

**Comment by hardestHu** [comment]
问题解决了吗？如何解决的

**Comment by huangche007** [comment]
请问解决了吗？ @webwuyou
