### ISSUE TITLE
react子应用路由使用懒加载无法加载相关资源

### ISSUE THREAD

**Issue by meoki-wong** [umijs/qiankun#2289]
qinakun主应用react   子应用react
子应用react-router6  动态路由  设置了懒加载后  切换到懒加载路由报错  
报错信息
![image](https://user-images.githubusercontent.com/66433819/194227852-995ffa63-d6ca-46a5-bcd7-d02707e7a781.png)
## 相关环境信息

- **qiankun 版本2.8.1**
- **浏览器版本chrome105**：
- **操作系统macos10.15.6**：

**Comment by meoki-wong** [comment]
当前是修改public-path的__webpack_public_path__路径解决  拼接上缺失的文件路径

**Comment by JavonHuang** [comment]
遇到同样问题，
主应用IP
 http://localhost:3001/static/js/src_page_home_Home_tsx.chunk.js net::ERR_ABORTED 404 (Not Found)
实际
子应用IP
 http://localhost:3000/static/js/src_page_home_Home_tsx.chunk.js net::ERR_ABORTED 404 (Not Found)

请问你是怎么配置的的public-path

**Comment by looktheworld** [comment]
> 

``` 
if (window.__POWERED_BY_QIANKUN__) {
    __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ + '相对路径';
}
````

**Comment by wxwzl** [comment]
> 

这个是啥原理，感觉没有用啊，webpack项目打包出来的js资源里根本就没有引用__webpack_public_path__的地方

**Comment by wxwzl** [comment]
> > 
> 
> ```
> if (window.__POWERED_BY_QIANKUN__) {
>     __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ + '相对路径';
> }
> ```

这个是啥原理，感觉没有用啊，webpack项目打包出来的js资源里根本就没有引用__webpack_public_path__的地方
