### ISSUE TITLE
[Styles Isolation] 不同的子应用运行的 UI 框架大版本不同，如何兼容样式？

### ISSUE THREAD

**Issue by dbkillerf6** [umijs/qiankun#229]
### 说明
最近 AntD 4 的 rc.1 版本已经出了，面向未来的话，我们一定会遇到不同的子应用运行的 UI 框架大版本不同的情况，如：
- A 运行了 AntD 3
- B 运行了 AntD 4

甚至在一些要求框架不相关的场景下，C 还有可能跑着 AntD Vue，这就可能会导致 css 样式不兼容。刚刚还看到 2.0 会支持官方支持同一页面运行不同实例，那这个问题就显得更重要了。

### 现有瓶颈
就目前了解到的方案来说
- qiankun 的样式隔离是通过注册和卸载样式表实现的，在这个过程中 UI 框架可能会修改全局样式，无论是单实例还是多实例，都会存在主应用和子应用 UI 框架样式冲突的情况；
- 由于组件有可能挂载在 body 上（如：message、Modal、Drawer 等），如果我直接用 shadow dom 的话，样式是可以隔离，但也会导致上述组件样式加载出错；
- 如果我们让子应用不引用 UI 框架样式，通过主应用下发，同一大版本还好，不同大版本就太坑了。

### 未来
所以想请教一下，qiankun 2.0 对于样式隔离的设计是怎样的？不同的子应用运行的 UI 框架大版本不同，如何兼容样式？

**Comment by kuitos** [comment]
当前 demo 就有 antd2 和 antd3 的例子，目前主子应用隔离需要手动处理，参考 https://github.com/umijs/qiankun/wiki/FAQ#how-to-guarantee-the-main-app-stylesheet-isolated-with-sub-apps，单实例场景基本够用了。

2.0 的方案针对多实例场景大抵是支持子应用选择开启 shadowdom 做彻底隔离，Modal 等问题可以通过配置 antd 的全局 getPopupContainer 配置来解决。

**Comment by wufeng87** [comment]
在load了antd2的react子应用后，我这也重现了样式冲突。antd2、antd3的样式都在。
![image](https://user-images.githubusercontent.com/1686808/74514389-668cd780-4f47-11ea-953b-9ca75ddac57d.png)
