### ISSUE TITLE
[Bug]手动加载方式 子应用 history 路由 dom 渲染不出来

### ISSUE THREAD

**Issue by ErKeLost** [umijs/qiankun#2292]
## What happens?

手动加载方式 子应用 history 路由 dom 渲染不出来

## 最小可复现仓库
使用官方 demo 测试 ， 主子应用都是 vue

https://github.com/ErKeLost/test-qiankun

启动项目
![image](https://user-images.githubusercontent.com/66500121/194540734-35b18d48-ccec-4ea6-8ea3-f4352d79ae24.png)

点击 history loadMicro 手动加载

![image](https://user-images.githubusercontent.com/66500121/194540931-df8a2ed6-3973-4bc9-9c57-7a24d5050194.png)

![image](https://user-images.githubusercontent.com/66500121/194540998-a37446fe-2e76-491f-a195-ef7e56540a67.png)

`router-view` 渲染不出来, 把路由改为 `hash` 模式可以正常运行

这是hash模式下 手动加载
![image](https://user-images.githubusercontent.com/66500121/194541655-470ccc2e-6ebf-4b13-8554-a3e332eec653.png)

**Comment by gongshun** [comment]
即使你使用手动加载，history 路由子应用的路由 base 还是需要配置的（和注册方式加载子应用一样）

**Comment by ErKeLost** [comment]
> 即使你使用手动加载，history 路由子应用的路由 base 还是需要配置的（和注册方式加载子应用一样）

好的 感谢
