### ISSUE TITLE
vue子应用使用路由懒加载，报Cannot read properties of null (reading 'onerror')

### ISSUE THREAD

**Issue by liswn** [umijs/qiankun#2293]

**Comment by 961998264** [comment]
![image](https://user-images.githubusercontent.com/38360133/229444570-7845989e-fb36-42d2-926f-57423c1857a2.png)

**Comment by 961998264** [comment]
![image](https://user-images.githubusercontent.com/38360133/229452783-70094d77-8e8b-4cce-a0d1-97736f6d58e9.png)
报错是因为在子应用加入federation的情况下。主应用加载子应用的一些依赖的时候，404了。
