### ISSUE TITLE
yarn examples:start-multiple启动项目，在页面点击 mount 按钮报错

### ISSUE THREAD

**Issue by Mr-jiao** [umijs/qiankun#2298]
## What happens?

yarn examples:start-multiple启动项目，在页面点击 mount 按钮报错

## Mini Showcase Repository(REQUIRED)

示例代码仓库

## How To Reproduce
step1:
yarn examples:start-multiple
step2:
点击 mount 按钮

**
![image](https://user-images.githubusercontent.com/44920775/195319052-ecf56e20-a781-40cd-9b9e-7f209b207939.png)
**

## Context

- **qiankun Version**: 2.8.1
- **Platform Version**:
- **Browser Version**: chrome 105.0.5195.125

**Comment by gongshun** [comment]
与 https://github.com/umijs/qiankun/issues/2300 相同，已发布2.8.3
