### ISSUE TITLE
【请教】打一个子应用包，注册多个子应用，IE上无法正常打开第二个子应用

### ISSUE THREAD

**Issue by huangyipingChina** [umijs/qiankun#2299]
应用场景如下：
       生产环境通过配置生成一个特色应用的配置，然后通过qiankun注册这个新增的子应用，每次新增的子应用的entry都使用已经打好的一个固定的子应用前端包的路径。于是导致一个问题：qiankun上注册的各个子应用的name都是不同的，而我打的子应用包只有一个，所以打包output里的library是固定的，没办法做到library和注册子应用的name一 一对应上。所以IE浏览器始终只能打开第一个子应用，打开第二个子应用的时候就找不到生命周期函数。并且在子应用中有自己的复杂的业务逻辑，无法仅仅通过将子应用组件共享出来就实现所有的功能。针对这种场景有什么好的建议吗

**Comment by gongshun** [comment]
子应用只加载一次，导出一个函数，大概如下：

```js
const createHelloWorld = container => {
  const router = new Router();
  const store = new Vuex.Store();
  return new Vue({
    el: container,
    store,
    router,
    render: h => h(App)
  });
}
```

主应用拿到，直接调用这个函数： createHelloWorld("#container")，就可以渲染第二次，两个应用之间如果想要路由互不干扰，可以用 abstract 模式。销毁第二个应用需要手动卸载

**Comment by huangyipingChina** [comment]
主应用进入子应用是通过路由控制的，加载第一个子应用的时候，子应用能够抛出你说的这个方法，但加载第二个子应用的时候，我怎么知道去调用这个函数去触发子应用的加载呢；
能讲的更详细一点么？大佬

**Comment by gongshun** [comment]
> 主应用进入子应用是通过路由控制的，加载第一个子应用的时候，子应用能够抛出你说的这个方法，但加载第二个子应用的时候，我怎么知道去调用这个函数去触发子应用的加载呢； 能讲的更详细一点么？大佬

子应用激活的时机不是已知的吗？activeRule 匹配路由，主应用可以自己判断 activeRule
