### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#23]
使用上的一些问题在统一提到这里

**Comment by DWDtest1** [comment]
关于路由的问题最近在采坑， 我们的项目同时使用了hashHistory和browserHistory， 在切换的时候发现与react-router-dom 有冲突， 无法正确识别， 找了下RR的[issue](https://github.com/ReactTraining/react-router/issues/6304) 操作window.history好像不推荐；

我是直接在主应用调single-spa的singleSPANavigate的方法，不知道qiankun在内部推广的时候有没有好的建议啊

**Comment by gaorubin1990** [comment]
本地运行是没问题的，但是把子应用从qiankun框架分离出来，主应用和子应用单独部署后，报错跨域问题。
![image](https://user-images.githubusercontent.com/49272745/61701296-802ebd80-ad70-11e9-9a56-c2280db66e3a.png)
Access to fetch at 'http://micro-sub-web.devapp.com/' from origin 'http://micro-web.devapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
而我在子应用中已经导出为umd模块了。
"start": "parcel serve ./src/index.html --global dvaapp --port 7103",
"build": "parcel build ./src/index.html --global dvaapp --public-url ./",
请问这个跨域是什么原因？如何解决呢？

**Comment by kuitos** [comment]
> 本地运行是没问题的，但是把子应用从qiankun框架分离出来，主应用和子应用单独部署后，报错跨域问题。
> ![image](https://user-images.githubusercontent.com/49272745/61701296-802ebd80-ad70-11e9-9a56-c2280db66e3a.png)
> Access to fetch at 'http://micro-sub-web.devapp.com/' from origin 'http://micro-web.devapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 而我在子应用中已经导出为umd模块了。
> "start": "parcel serve ./src/index.html --global dvaapp --port 7103",
> "build": "parcel build ./src/index.html --global dvaapp --public-url ./",
> 请问这个跨域是什么原因？如何解决呢？

原因是你主应用在 http://micro-web.devapp.com 域名下，子应用在 http://micro-sub-web.devapp.com/ 域名下，主应用加载子应用过程中会去取相应的静态资源，自然就跨域了。解决需要给服务器做下配置，google 一下 https://www.google.com/search?q=cors+nginx&oq=cors+nginx&aqs=chrome..69i57j0l5.5930j0j4&sourceid=chrome&ie=UTF-8

**Comment by gaorubin1990** [comment]
请问每次release版本的更新内容可以说明一下吗

**Comment by kuitos** [comment]
> 请问每次release版本的更新内容可以说明一下吗

好的，后面会加 release log

**Comment by gaorubin1990** [comment]
目前使用parcel开发及正式环境都可以，但是webpack按照文档进行配置（umd）总是报错，建议版主能否将example中其中一个示例修改为webpack打包指导下。

**Comment by kuitos** [comment]
具体什么问题?

**Comment by gaorubin1990** [comment]
> 具体什么问题?

我把主应用修改为webpack打包方式，报这个错误，但是又搜索不到这个插件。
![image](https://user-images.githubusercontent.com/49272745/63160548-9f0f2f80-c050-11e9-93a5-629ef6ac4893.png)

**Comment by gaorubin1990** [comment]
版主你好，该问题与qiankun关联性不大，请问使用parcel打包如何实现proxy代理？

**Comment by houyaowei** [comment]
> > 具体什么问题?
> 
> 我把主应用修改为webpack打包方式，报这个错误，但是又搜索不到这个插件。
> ![image](https://user-images.githubusercontent.com/49272745/63160548-9f0f2f80-c050-11e9-93a5-629ef6ac4893.png)
你看下node_module下qiankun的包装好了么

**Comment by Lizhooh** [comment]
假设有用到 react-router，vue-router ...

希望给一个 examples，涉及单页面路由的示例。

**Comment by guojingwen** [comment]
子应用路由跳转问题，只能到子应用跟路由‘/’  无法跳转的子应用具体路由
基座example 我是用的是vue,  vue子应用我做了路由，

**Comment by guojingwen** [comment]
解决了 原来子应用路由定义 path 也要 ‘/’ 开头

**Comment by hetianxiang** [comment]
能提供一个配置vuecli3已有项目 子项目中用了vuerouter 和 vuex ？更改子项目的方式吗，但是按照项目只改了webpack 的配置貌似也不生效 能提供一个demo 吗？谢谢

**Comment by Auroraan** [comment]
在做迁移遗留系统的项目，想问问，主程序和子程序怎么实现通信呢？是必须要使用umi-plugin-qiankun吗？

**Comment by HadeAs** [comment]
> > 本地运行是没问题的，但是把子应用从qiankun框架分离出来，主应用和子应用单独部署后，报错跨域问题。
> > ![image](https://user-images.githubusercontent.com/49272745/61701296-802ebd80-ad70-11e9-9a56-c2280db66e3a.png)
> > Access to fetch at 'http://micro-sub-web.devapp.com/' from origin 'http://micro-web.devapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> > 而我在子应用中已经导出为umd模块了。
> > "start": "parcel serve ./src/index.html --global dvaapp --port 7103",
> > "build": "parcel build ./src/index.html --global dvaapp --public-url ./",
> > 请问这个跨域是什么原因？如何解决呢？
> 
> 原因是你主应用在 http://micro-web.devapp.com 域名下，子应用在 http://micro-sub-web.devapp.com/ 域名下，主应用加载子应用过程中会去取相应的静态资源，自然就跨域了。解决需要给服务器做下配置，google 一下 https://www.google.com/search?q=cors+nginx&oq=cors+nginx&aqs=chrome..69i57j0l5.5930j0j4&sourceid=chrome&ie=UTF-8

但是官网的示例里面，主应用和子应用都是不同的端口号启动的，为什么不存在跨域问题呢？

**Comment by bingo618** [comment]
### 整合Angular子项目使用singleSpaAngular导出生命周期问题。
![TIM截图20190918094758](https://user-images.githubusercontent.com/20422686/65097958-74224d80-d9f9-11e9-94e5-c566bc5d88ae.png)
#### 子项目仓库：
[https://github.com/bingo618/micro-angular](url)
#### 主项目仓库：
[https://github.com/bingo618/micro-base](url)
#### 线上地址：
[http://bin.ananlab.com/](url)

**Comment by HadeAs** [comment]
浏览器兼容性如何？我试了下IE11浏览器打开报错。 @kuitos

**Comment by kuitos** [comment]
> 浏览器兼容性如何？我试了下IE11浏览器打开报错。 @kuitos

see https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie

**Comment by HadeAs** [comment]
> > > 本地运行是没问题的，但是把子应用从qiankun框架分离出来，主应用和子应用单独部署后，报错跨域问题。
> > > ![image](https://user-images.githubusercontent.com/49272745/61701296-802ebd80-ad70-11e9-9a56-c2280db66e3a.png)
> > > Access to fetch at 'http://micro-sub-web.devapp.com/' from origin 'http://micro-web.devapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> > > 而我在子应用中已经导出为umd模块了。
> > > "start": "parcel serve ./src/index.html --global dvaapp --port 7103",
> > > "build": "parcel build ./src/index.html --global dvaapp --public-url ./",
> > > 请问这个跨域是什么原因？如何解决呢？
> > 
> > 
> > 原因是你主应用在 http://micro-web.devapp.com 域名下，子应用在 http://micro-sub-web.devapp.com/ 域名下，主应用加载子应用过程中会去取相应的静态资源，自然就跨域了。解决需要给服务器做下配置，google 一下 https://www.google.com/search?q=cors+nginx&oq=cors+nginx&aqs=chrome..69i57j0l5.5930j0j4&sourceid=chrome&ie=UTF-8
> 
> 但是官网的示例里面，主应用和子应用都是不同的端口号启动的，为什么不存在跨域问题呢？

@kuitos 麻烦看一下这个呢

**Comment by Hades-li** [comment]
### 对于vue-router路由守卫不能销毁的困惑
对于vue的实列可以调用destory函数来销毁。但vue-router并没有提供销毁功能。如果A子项目配置了beforeEach的全局守卫函数，当从A项目切换到B项目时，A项目的路由守卫回调函数依然会被执行，导致全局受到影响。
最好的办法是能在A子项目unmount的时候移除路由监听，但完全没办法去除。
有什么好办法来解决此问题。

**Comment by kuitos** [comment]
> ### 对于vue-router路由守卫不能销毁的困惑
> 对于vue的实列可以调用destory函数来销毁。但vue-router并没有提供销毁功能。如果A子项目配置了beforeEach的全局守卫函数，当从A项目切换到B项目时，A项目的路由守卫回调函数依然会被执行，导致全局受到影响。
> 最好的办法是能在A子项目unmount的时候移除路由监听，但完全没办法去除。
> 有什么好办法来解决此问题。

beforeEach 方法会返回一个 unRegister，unmount 的时候再调一下就好了。see https://github.com/vuejs/vue-router/blob/dev/src/index.js#L134

**Comment by kuitos** [comment]
@HadeAs 因为 parcel 默认开了跨域啊..

**Comment by HadeAs** [comment]
多个子系统同时处于active状态，且子系统之间存在同名className，那么就会发生样式冲突。这种情况下只有加个前缀确保样式名的唯一性 @kuitos

**Comment by HadeAs** [comment]
目前项目准备用qiankun，但是需要支持IE10+，请问何时可以提供，或者麻烦提供一个临时的解决方案可以支持IE10+  @kuitos

**Comment by Hades-li** [comment]
> > ### 对于vue-router路由守卫不能销毁的困惑
> > 对于vue的实列可以调用destory函数来销毁。但vue-router并没有提供销毁功能。如果A子项目配置了beforeEach的全局守卫函数，当从A项目切换到B项目时，A项目的路由守卫回调函数依然会被执行，导致全局受到影响。
> > 最好的办法是能在A子项目unmount的时候移除路由监听，但完全没办法去除。
> > 有什么好办法来解决此问题。
> 
> beforeEach 方法会返回一个 unRegister，unmount 的时候再调一下就好了。see https://github.com/vuejs/vue-router/blob/dev/src/index.js#L134

感谢，vue-router文档中貌似一个字都没提这个功能函数。

**Comment by rqc-git** [comment]
qiankun 基于 single-spa  做了哪些改进?您能大概说下吗？

**Comment by littleDaniel** [comment]
同求兼容ie的解决方案

**Comment by rqc-git** [comment]
qiankun 基于 single-spa  做了哪些改进？@kuitos

**Comment by kuitos** [comment]
> qiankun 基于 single-spa 做了哪些改进？@kuitos

https://github.com/umijs/qiankun/#sparkles-features

**Comment by Hades-li** [comment]
qiankun支持hash模式路径吗？目前的子项目全都采用hash模式而且不能改成history模式

**Comment by kuitos** [comment]
@Hades-li 支持

**Comment by fenngding** [comment]
有ie的场景需求,能否给一个解决的思路或方案,如果能直接兼容更好! 要不高版本的ie都无法支持,感觉会受浏览用户的抵触吧

**Comment by CodeLittlePrince** [comment]
怎么让开发更顺畅？
---
从demo使用方式来看，子应用通过实现生命周期中的moun来挂载渲染dom。所以本地开发子应用不得不先启整个主应用，然后才能开发。不然就是手动在子应用的入口文件先执行挂载dom相关代码，然后上线的时候再删除。
那就好奇这个框架作者自己再蚂蚁用的时候是怎么个开发方式呢？

**Comment by kuitos** [comment]
@CodeLittlePrince https://github.com/umijs/qiankun/wiki/FAQ#how-to-make-sub-app-to-run-independently

**Comment by kuitos** [comment]
> 有ie的场景需求,能否给一个解决的思路或方案,如果能直接兼容更好! 要不高版本的ie都无法支持,感觉会受浏览用户的抵触吧

短期内不考虑 IE，vue3、mobx5 都不兼容 IE，以后不兼容 IE 的 library 只会越来越多..

**Comment by CodeLittlePrince** [comment]
使用问题
---
乾坤从demo来看很棒，但是我用我一直用的脚手架初始的项目来结合乾坤，但是弄了好久还是整不通，一直报：
```shell
index.esm.js:638 Uncaught game: Application 'game' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in game entry
```
![image](https://user-images.githubusercontent.com/17001245/66558068-853c2580-eb85-11e9-8196-63d54bea33a2.png)
实在是搞不定了，拜托楼主帮我看看是咋解决T  T。
项目地址：https://github.com/CodeLittlePrince/qiankun-test

**Comment by Hades-li** [comment]
主框架和子应用间如何通信？
比如我想在主框架中获取子应用的根实例，但主框架中的afterMount等回调函数中的参数，返回的和我注册时props参数是一样的，并且并不能在子应用中将子应用的某个实列对象付值给props的参数中的属性。
请教有什么办法实现父子应用间的数据互通？

**Comment by kuitos** [comment]
props 里可以写回调函数，跟你写 react 怎么父子通信是一样的原理 @Hades-li

**Comment by alanchanzm** [comment]
# Vue异步加载子项目路由失败

编译命令
```
parcel index.html --global xyz --port 1236
```

router
```
import Vue from 'vue';
import Router from 'vue-router';
import PageOne from './views/PageOne.vue';

Vue.use(Router);

const routes = [
  {
    path: '/',
    name: 'one',
    component: PageOne
  },
  {
    path: '/two',
    name: 'two',
    component: () => import('./views/PageTwo.vue')
  }
];

export default new Router({
  mode: 'history',
  base: '/child',
  routes
});
```

报错信息
```
Failed to resolve async component default: Error: Cannot find module 'src/views/PageTwo.vue'
```

**Comment by kuitos** [comment]
报 bug 新开 issue 吧，这里主要收集一些 question，常见问题已收集到 https://github.com/umijs/qiankun/wiki/FAQ

**Comment by ZhaoZhenFengDE** [comment]
![image](https://user-images.githubusercontent.com/21331414/67202612-a4676c80-f43b-11e9-8a94-a407fc7223a0.png)
你好，我在拉下代码本地测试的时候，新建了一个react21的应用，然后使用webpack打包，
    libraryTarget 设置了 umd ，但是出现了跨域错误。请问怎么解决呢？

**Comment by kuitos** [comment]
> 目前项目准备用qiankun，但是需要支持IE10+，请问何时可以提供，或者麻烦提供一个临时的解决方案可以支持IE10+ @kuitos

一定要支持 ie 先关闭 jsSandbox 吧

**Comment by soulwu** [comment]
使用qiankun后，如果子应用里有代码执行错误，怎么才能看到原始的错误位置？目前都会被统一定位到qiankun框架依赖的import-html-entry中的eval方法里，基本是无法调试的状态

**Comment by kuitos** [comment]
> 使用qiankun后，如果子应用里有代码执行错误，怎么才能看到原始的错误位置？目前都会被统一定位到qiankun框架依赖的import-html-entry中的eval方法里，基本是无法调试的状态

开发阶段配下 source-map，参考 https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L55

**Comment by soulwu** [comment]
> > 使用qiankun后，如果子应用里有代码执行错误，怎么才能看到原始的错误位置？目前都会被统一定位到qiankun框架依赖的import-html-entry中的eval方法里，基本是无法调试的状态
> 
> 开发阶段配下 source-map，参考 https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L55

由于我这边不是使用的umi，我根据这个例子在我的webpack配置中加入了对应的SourceMapDevToolPlugin配置，但是我测试下来还是看不到实际的执行堆栈。有没有纯粹的webpack配置样例？

**Comment by soulwu** [comment]
> > 使用qiankun后，如果子应用里有代码执行错误，怎么才能看到原始的错误位置？目前都会被统一定位到qiankun框架依赖的import-html-entry中的eval方法里，基本是无法调试的状态
> 
> 开发阶段配下 source-map，参考 https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L55

而且import-html-entry加载js的方式也不是使用script标签，而是通过fetch获取的，在Source面板中也是无法看到对应的资源，这种情况下还能使用sourcemap吗？

**Comment by kuitos** [comment]
> 而且import-html-entry加载js的方式也不是使用script标签，而是通过fetch获取的，在Source面板中也是无法看到对应的资源，这种情况下还能使用sourcemap吗？

能用，webpack 配置跟[这个](https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L55)是一样的
