### ISSUE TITLE
子应用开启 dll不支持 ？

### ISSUE THREAD

**Issue by huyansheng3** [umijs/qiankun#230]
## What happens?

子应用开启dll, dll中 `var umi = {} `是在window.proxy上生效，执行到入口js时，提示 umi undefined.

另外如果有子应用的js报错，错误信息都只会在 execScript的入口这里，看不到更加具体的报错信息，开发体验不够完善。 目前社区的system-js不太清楚能不能解决这个问题。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
提供可复现 repo.
umi 应用直接用插件开发阶段可以跳转 sourcemap

**Comment by wufeng87** [comment]
@huyansheng3 你好，这个问题解决了吗？我也遇到了类似的问题。

**Comment by conanmy** [comment]
@huyansheng3 @wufeng87 我也遇到了，还没有查出来具体原因，你们解决了吗？

**Comment by conanmy** [comment]
webpack dll 文件输出为 var xxx = {} 时会出现这个问题，看了下 qiankun 的代码，是因为脚本在执行的时候会被包裹 (function(window, self){;${scriptText}\n${sourceUrl}}).bind(window.proxy)(window.proxy, window.proxy)，因而这种变量无法被挂载到 window 上。

在 dll 构建的 output 上声明 libraryTarget: 'window' 会让输出变为 window["vendor"] = {}，这样就解决了。

**Comment by humorHan** [comment]
> webpack dll 文件输出为 var xxx = {} 时会出现这个问题，看了下 qiankun 的代码，是因为脚本在执行的时候会被包裹 (function(window, self){;${scriptText}\n${sourceUrl}}).bind(window.proxy)(window.proxy, window.proxy)，因而这种变量无法被挂载到 window 上。
> 
> 在 dll 构建的 output 上声明 libraryTarget: 'window' 会让输出变为 window["vendor"] = {}，这样就解决了。

添加libraryTarget: 'window' ，这个window指的是proxy后的window吗？如果不是的话多个子应用相同声明的dll就会重复了

**Comment by conanmy** [comment]
> > webpack dll 文件输出为 var xxx = {} 时会出现这个问题，看了下 qiankun 的代码，是因为脚本在执行的时候会被包裹 (function(window, self){;${scriptText}\n${sourceUrl}}).bind(window.proxy)(window.proxy, window.proxy)，因而这种变量无法被挂载到 window 上。
> > 在 dll 构建的 output 上声明 libraryTarget: 'window' 会让输出变为 window["vendor"] = {}，这样就解决了。
> 
> 添加libraryTarget: 'window' ，这个window指的是proxy后的window吗？如果不是的话多个子应用相同声明的dll就会重复了

libraryTarget: 'window' 是 webpack 的一个配置属性值，可以看下 webpack 文档
