### ISSUE TITLE
最新2.8.2版本对部分框架打包的子应用兼容有问题

### ISSUE THREAD

**Issue by JackDing1208** [umijs/qiankun#2300]
## What happens?

安装最新版本后以往可以正常加载的子应用报错
将qiankun版本写死成2.7.4后恢复正常
子应用打包脚手架为create-react-app

## Context

![image](https://user-images.githubusercontent.com/48002519/195503270-33b6f86a-135f-4510-aa24-ddf578fdbb3c.png)

**Comment by tranthotuong** [comment]
me too. I have the same an issue
![image](https://user-images.githubusercontent.com/50495846/195505170-148db397-b211-4ee2-9d8e-28fc767e9a9e.png)

**Comment by zeusyaoyao** [comment]
+1, 升级到2.8.2，create-react-app 构建的子应用直接死循环了

**Comment by kuitos** [comment]
released v2.8.3
