### ISSUE TITLE
微应用保活unmount时机控制

### ISSUE THREAD

**Issue by wash1983** [umijs/qiankun#2304]
## Background

乾坤主应用实现tab页切换多个子应用的功能。 切换时会调用unmount 销毁子应用，造成状态无法保存。看了很多解决方案，基本时失loadmicroapp 自己控制时机。

## Proposal

registerMicroApps 能否暴露一个接口，由应用去控制是否需要销毁子应用。不销毁时，缓存一下微应用。

## Additional context

 感谢贡献如此美妙的框架。

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/361

**Comment by RainManGO** [comment]
我也是多页签，再次打开的时候，没有自动加载应用是为什么呢？我和url 绑定一起了

**Comment by r70kg** [comment]
乾坤现在支持应用保活了吗

**Comment by JunmingZ** [comment]
还没有

**Comment by JunmingZ** [comment]
> 乾坤现在支持应用保活了吗

还没有
