### ISSUE TITLE
版本2.8.3，报错

### ISSUE THREAD

**Issue by mdchun** [umijs/qiankun#2308]
## What happens?
使用qiankun@2.8.3版本时，有如下报错:  
[import-html-entry]: error occurs while executing entry script

SharedArrayBuffer is not defined
![image](https://user-images.githubusercontent.com/7719710/196315567-2b2329b4-6c6c-4136-a863-f1b646020478.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.8.3
- **Platform Version**:
- **Browser Version**:  Chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Comment by gongshun** [comment]
v2.8.4 发布了，这个问题应该修复了 https://github.com/umijs/qiankun/pull/2320
