### ISSUE TITLE
[Feature Request] 支持single-spa提供的override功能

### ISSUE THREAD

**Issue by wufeng87** [umijs/qiankun#231]
## Background

override功能可以在线上应用动态注入（override）子应用，能较方便的和主应用联合调试。
相关链接：
https://www.youtube.com/watch?v=vjjcuIxqIzY&list=PLLUD8RtHvsAOhtHnyGx57EYXoaNsxGrTU&index=4
https://www.npmjs.com/package/import-map-overrides

## Proposal
能支持类似的override功能。

**Comment by howel52** [comment]
这个确实可以有

不过怎么做 override 得想下（比如 production /  test  https 环境下 override 到 localhost 后触发安全机制的问题），最后做成什么样的可能也得想一下；

@kuitos 怎么看

**Comment by kuitos** [comment]
线上应用可以注入似乎听起来就像是安全隐患😂
技术上确实可以考虑这个特性，但是工程上需要考虑的问题会比较多，比如这个特性只能在 dev 阶段开启，prod 阶段自动关闭，以及你说的 https 等安全机制的问题。

如果只是为了方便与主应用联调，或许有更简单可靠的机制可以使用（umi-plugin-qiankun 后续会支持）。

**Comment by dbkillerf6** [comment]
这个问题我们也遇到过，只不过 production 下，我们需要 RegistrableApp[] 是动态的，所以自己统一提供了 basement 服务，在主应用 init 的时候动态加载 RegistrableApp[] 再对子应用注册，与子应用注册相关的配置都在后台修改（提供 devEntry 字段）：
- 主应用本地开发时，会默认生成一个子应用配置的 json，更改这个 json 就可以进行本地调试；
- 主应用在测试环境，服务读取 devEntry，提供注入后的子应用配置
- 主应用在生产环境，服务不会读取 devEntry

我觉得这个问题，不一定要实现在内核里，可以基于 qiankun 在上层应用中实现。

**Comment by howel52** [comment]
从结果上看的话，借助工具也是可以实现这一目的的，比如 charles forward

**Comment by dbkillerf6** [comment]
用类似这样的工具，本地劫持入口文件也不是不行：http://wproxy.org/whistle/install.html

**Comment by howel52** [comment]
> 这个问题我们也遇到过，只不过 production 下，我们需要 RegistrableApp[] 是动态的，所以自己统一提供了 basement 服务，在主应用 init 的时候动态加载 RegistrableApp[] 再对子应用注册，与子应用注册相关的配置都在后台修改（提供 devEntry 字段）：
> 
> * 主应用本地开发时，会默认生成一个子应用配置的 json，更改这个 json 就可以进行本地调试；
> * 主应用在测试环境，服务读取 devEntry，提供注入后的子应用配置
> * 主应用在生产环境，服务不会读取 devEntry
> 
> 我觉得这个问题，不一定要实现在内核里，可以基于 qiankun 在上层应用中实现。

2333 和我们目前的方式一模一样

**Comment by dbkillerf6** [comment]
> > 这个问题我们也遇到过，只不过 production 下，我们需要 RegistrableApp[] 是动态的，所以自己统一提供了 basement 服务，在主应用 init 的时候动态加载 RegistrableApp[] 再对子应用注册，与子应用注册相关的配置都在后台修改（提供 devEntry 字段）：
> > 
> > * 主应用本地开发时，会默认生成一个子应用配置的 json，更改这个 json 就可以进行本地调试；
> > * 主应用在测试环境，服务读取 devEntry，提供注入后的子应用配置
> > * 主应用在生产环境，服务不会读取 devEntry
> > 
> > 我觉得这个问题，不一定要实现在内核里，可以基于 qiankun 在上层应用中实现。
> 
> 2333 和我们目前的方式一模一样

RegistrableApp 动态加载应该都需要做，毕竟做集成的话，每次来个新的子应用都要上线主应用，那会被老板砍死的（逃

**Comment by kuitos** [comment]
xswitch 你值得拥有，线上调试不二利器 https://github.com/yize/xswitch

**Comment by ousiri** [comment]
基于import-map-overrides写了个类似的工具  [qiankun-overrides](https://www.npmjs.com/package/qiankun-overrides/v/1.0.1)，不过要手动加一下代码，因为qiankun的加载逻辑和single-spa不一样
