### ISSUE TITLE
子应用字体文件在生产环境下无法正常加载

### ISSUE THREAD

**Issue by Lzp0225** [umijs/qiankun#2311]
## What happens?
代码中按照官方提示添加了public-path.js且放在入口文件顶部，随后按照网上给出的解决方案去单独处理font文件，这时本地和生产都不正常加载font文件了
main.js以及vue.config.js配置
![image](https://user-images.githubusercontent.com/37355986/196651054-3c4d326e-37a9-4d8a-a3bb-3263b4fb25b0.png)
![image](https://user-images.githubusercontent.com/37355986/196651267-9f77b2b6-d1af-4858-8d62-a5bc02ab0a3b.png)
![image](https://user-images.githubusercontent.com/37355986/196650255-a337ecd0-6f75-476f-b4b2-8bd909510eb5.png)
我的资源文件输出路径为默认的dist/fonts/...

本地环境：
![image](https://user-images.githubusercontent.com/37355986/196651734-9b9fc4dd-9421-42bf-a05a-57637e79caee.png)

线上环境:
![image](https://user-images.githubusercontent.com/37355986/196652664-66b664d7-5ac8-4985-bed7-cd0a8d492677.png)

- **qiankun Version**:2.7.5
- **Platform Version**:chorme
- **Browser Version**:105.0

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

**Comment by Lzp0225** [comment]
> https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E6%89%93%E5%8C%85%E4%B9%8B%E5%90%8E-css-%E4%B8%AD%E7%9A%84%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E5%92%8C%E5%9B%BE%E7%89%87%E5%8A%A0%E8%BD%BD-404

用的就是官方给的示例，丝毫无作用，现在采用cdn去解决了
