### ISSUE TITLE
2.8.3版本 只要加上speedy:true  start({ sandbox:{ speedy:true} }); 页面就会报错

### ISSUE THREAD

**Issue by zh1011** [umijs/qiankun#2313]
![image](https://user-images.githubusercontent.com/41102878/196876337-9e9c53ec-d425-4495-968e-e4330913c0d3.png)

SharedArrayBuffer is not defined

我在本地环境加上 
'Cross-Origin-Embedder-Policy': 'require-corp',
 'Cross-Origin-Opener-Policy': 'same-origin'

同样报错

**Comment by Jadeee** [comment]
请问解决了吗，我也遇到相同的情况

**Comment by zh1011** [comment]
> 请问解决了吗，我也遇到相同的情况
没有  我后来放弃了 没有使用

**Comment by gongshun** [comment]
v2.8.4 发布了，这个问题应该修复了 https://github.com/umijs/qiankun/pull/2320
