### ISSUE TITLE
[Bug]同一路由挂载angular8和react16子项目失败

### ISSUE THREAD

**Issue by zhusijia** [umijs/qiankun#232]
## What happens?

同一路由挂载angular8和react16子项目失败

## 最小可复现仓库

https://github.com/zhusijia/qiankun-demo

## 复现步骤，错误日志以及相关配置

```
cd sub-app-angular && yarn && yarn start
cd sub-app-rect && yarn && yarn start
cd main-project && yarn && yarn start
```

angular可以挂载，react项目报错，VM18492:35401 Mounting application 'sub-app-react' did not resolve or reject for 3000 milliseconds“

## 相关环境信息

- Platform: mac
- Browser Version: chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by Deturium** [comment]
取消同时只能挂在一个 app 的限制，将 `main-project/index.js` 改为

```js
start({ 
  prefetch: true,
  singular: false,
});
```

`singular` 默认是 `true`
