### ISSUE TITLE
子应用之间的 window.addEventListener会互相影响。

### ISSUE THREAD

**Issue by StephewZ** [umijs/qiankun#2323]
子应用A注册点击事件  window.addEventListener('click', e => { console.log(e) })

子应用B点击会触发子应用A的事件监听，设计如此吗？

**Comment by gongshun** [comment]
设计如此

**Comment by UmbraCi** [comment]
> 设计如此

原本子应用就是一个iframe，通信代码都是监听message事件，现在子应用的window.addEventListener直接挂到主应用去了，何解呢，不太想动原本子应用的业务代码
