### ISSUE TITLE
如果直接使用umi 加plugin会render两次

### ISSUE THREAD

**Issue by huyansheng3** [umijs/qiankun#233]
## What happens?

![image](https://user-images.githubusercontent.com/11534583/72603197-871b3f00-3953-11ea-823b-e743bc121032.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
第二个render只是取到引用存起来以供下次 remount 调用，第一次不会被执行。

先关了，如果还有问题请reopen并提供可复现的仓库
