### ISSUE TITLE
history.block 子项目跳转问题

### ISSUE THREAD

**Issue by xiaofeng-bm** [umijs/qiankun#2330]
各位大佬，请教一个问题
1、主项目和子项目都是用umi那一套搭建的。
2、子项目A使用了history.block做离开弹框，在A项目内路由跳转都ok，但是A项目跳另一个B项目，会先跳到B项目，然后history.block生效，又跳回了A项目，或者有时候两个路由会疯狂切换。

**Comment by seujzhang** [comment]
> 两个路由会疯狂切换

两个路由会疯狂切换解决了么？我也遇到了。。。

**Comment by xiaofeng-bm** [comment]
> > 两条路由疯狂切换
> 
> 两条路由疯狂切换解决了怎么办？我也遇到了。。。



> > 两个路由会疯狂切换
> 
> 两个路由会疯狂切换解决了么？我也遇到了。。。

对对对，你找到解决办法了吗

**Comment by tpc-ht** [comment]
请问，最后解决了吗。我也遇到了

**Comment by xiaofeng-bm** [comment]
> 请问，最后解决了吗。我也遇到了

没有，你要是找到方法了，请告诉我一下
