### ISSUE TITLE
为什么子应用加载成功之后script的标签都被注释了？

### ISSUE THREAD

**Issue by pangwenbo** [umijs/qiankun#2333]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/67305584/202338279-716fa402-c600-44ec-be6f-5c22a692ca35.png">

**Comment by gongshun** [comment]
qiankun 是先用 fetch 请求到 js 的内容，然后使用 eval 来执行一下（为了实现沙箱），这样就没必要再插入 script 了
