### ISSUE TITLE
子应用中怎么动态插入带有javascript脚本的script标签？非插入js远程文件

### ISSUE THREAD

**Issue by EdenXY** [umijs/qiankun#2336]
- **qiankun 版本**
- 2.7.0
- **浏览器版本**：
- chrome

目前实行代码如下，发现无法成功插入

```javascript
let bodyEle = document.getElementsByTagName('body')[0]
let oldScriptEle = document.getElementById('custom-script')
!!oldScriptEle && bodyEle.removeChild(oldScriptEle) // 先清除后插入！！

let newScriptEle = document.createElement('script')
newScriptEle.id = ''custom-script''
newScriptEle.type = 'text/javascript'
newScriptEle.innerHTML = 'function helloWorld(){ alert("Hello world!"); }'
bodyEle.appendChild(newScriptEle)
```

**Comment by EdenXY** [comment]
> 动态插入 mobx 的 umd 的 script，执行完成后打印出的 window 上多了对

可能我表达得不够清晰，我要插入的是JavaScript脚本代码，而非通过url异步加载远程文件

**Comment by vincenteof** [comment]
> > 动态插入 mobx 的 umd 的 script，执行完成后打印出的 window 上多了对
> 
> 可能我表达得不够清晰，我要插入的是JavaScript脚本代码，而非通过url异步加载远程文件

子应用通过 appendChild 插入的 script 都会执行的，只是不会出现在 header 里而已

**Comment by EdenXY** [comment]
> 

你说的是对了，子应用确实是可以直接插入 script 脚本，是另一个插件和 qiankun 结合时候的时候出了问题。

**Comment by sy296565890** [comment]
> > 动态插入 mobx 的 umd 的 script，执行完成后打印出的 window 上多了对
> 
> 可能我表达得不够清晰，我要插入的是JavaScript脚本代码，而非通过url异步加载远程文件

大佬，请问动态插入JavaScript脚本代码，而非通过url异步加载远程文件 解决了吗
