### ISSUE TITLE
生产环境ChunkLoadError

### ISSUE THREAD

**Issue by aaronzag** [umijs/qiankun#2338]
主子系统vue2，路由都是history，子系统组件通过懒加载方式，开发环境没有任何问题。
发布线上后，从主系统登录成功，加载子系统，首页未使用懒加载，正常显示，切换路由，报错loading chunk xxxx failed。然后退出登录，不刷新登录页面，重新登录，路由切换正常。刷新登录页面，重新登录，依然报错。打开控制台，发现把组件的chunk的js插入到主系统的head中了，不知道是什么原因导致的？
<img width="408" alt="image" src="https://user-images.githubusercontent.com/37403479/202914038-b9eb1327-1a7f-42c6-8cfc-9e19cf2f2d8f.png">

**Comment by gongshun** [comment]
是 https://github.com/umijs/qiankun/issues/2340 同一个问题？

**Comment by BadMooncc** [comment]
我这边使用hash模式 本地子应用切换时(页面首次加载) 也报这个错误，再点一次菜单进入该路由就行了 真奇怪
