### ISSUE TITLE
在safari浏览器中,子应用使用iframe嵌套微信公众号正常，子应用嵌入主应用后微信公众号报错

### ISSUE THREAD

**Issue by ZPower-Zhang** [umijs/qiankun#2339]
## What happens?
最近在做微信公众号授权的功能，在safari浏览器中子应用通过iframe嵌套授权页面，无论是在本地还是线上单独运行的时候都能正常使用，但是当子应用嵌入主应用，会出现授权问题
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/17979348/203035899-f0071bab-49dc-48d1-a37d-092d97613116.png">

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
"qiankun": "^2.3.1",
"vue": "2.6.10",
safari. 15.6.1 (17613.3.9.1.16)

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
因为子应用嵌入主应用后，他和主应用属于同一个window，子应用所在的域是主应用的

**Comment by ZPower-Zhang** [comment]
> 因为子应用嵌入主应用后，他和主应用属于同一个window，子应用所在的域是主应用的

这个应该是不同浏览器下处理方式不同导致的，在chrome上是正常的😂
