### ISSUE TITLE
一个页面同时放了子应用和主应用的功能,主应用的样式文件被子应用加载了。

### ISSUE THREAD

**Issue by lansefengxinzi** [umijs/qiankun#2349]
## What happens?

一个页面同时放了子应用和主应用的功能，这时子应用处于激活态，document.head.appendChild被劫持。此时去点击主应用的按钮加载主应用的懒加载组件，样式会被插入到子应用中

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/lansefengxinzi/qiankun-test

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 主应用懒加载的样式应该插入到主应用中

## Context

- **qiankun Version**: 2.8.4
- **Platform Version**: react 16.8.3
- **Browser Version**:

**Comment by lansefengxinzi** [comment]
> Hello @lansefengxinzi. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @lansefengxinzi, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
稍等

https://github.com/lansefengxinzi/qiankun-test

**Comment by lansefengxinzi** [comment]
<img width="1089" alt="企业微信截图_6ba2cca8-eceb-409e-94cf-174726db4a4d" src="https://user-images.githubusercontent.com/12048313/204428768-abb0fcdd-1892-449d-ba3d-7d44c79ea2df.png">

<style class="monaco-colors"></style>， 这个样式文件是主应用中，  组件<Editor/> monaco-editor 的样式，被子应用拦截，加载到qiankun 下面。导致样式不对。

**Comment by lansefengxinzi** [comment]
代码：

>`import React, { useRef, useEffect, useState } from 'react'; // lazy,
import { Divider, Button } from 'antd';
import { loadMicroApp } from 'qiankun';
import Editor from './pages/Editor';

import 'antd/dist/antd.min.css';
import './App.css';

export default function App() {
  const appInstanceRef = useRef(null);
  const [show, setShow] = useState(false);

  useEffect(() => {
    appInstanceRef.current = loadMicroApp(
      { name: 'vue', entry: '//localhost:7101', container: '#vue' },
      { sandbox: { experimentalStyleIsolation: true } },
    );
  }, []);

  return (
    <div className="app-main">
      <Button
        onClick={() => {
          setShow(!show);
        }}
      >
        加载组件
      </Button>
      <Divider />
      {show && <Editor />}
      <div id="vue"></div>
    </div>
  );
}
`

**Comment by Tiarnach** [comment]
@lansefengxinzi

**Comment by wangzongming** [comment]
提前加载一个 `monaco-editor` 组件，并隐藏它完美解决。
应该和这个问题相关：https://github.com/microsoft/monaco-editor/issues/3776

**Comment by kuitos** [comment]
最新版本默认开启了 speedy，应该没有这个问题了
