### ISSUE TITLE
想问一下singular: false的作用是什么？实现tab切换过程中遇到的问题

### ISSUE THREAD

**Issue by lvan-zhang** [umijs/qiankun#2351]
想要实现的是有一个类似浏览器标签的tab切换功能，目前这个tab切换是写在主应用的，父子应用技术栈都是vue，使用的keep-alive来缓存状态，qiankun使用的registerMicroApps+start加载子应用，现在遇到的问题是：

主应用和子应用如果点击的是自己的路由是可以保存状态的，但是一旦从主应用切到子应用，或者从子应用1切到子应用2，都是不会保存状态的，因为qiankun会丢失掉应用，重新进行加载，这是我不期望的，但是我有看到start中有一个参数是singular: false，好像是可以同时渲染，但是我加上也没有用。

所以我想问这个singular: false具体应用场景是什么样的？以及我现在遇到的tab切换问题有什么思路可以解决？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/361

**Comment by lvan-zhang** [comment]
> 
ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后
还是想问一下第一个问题singular: false的作用以及使用场景？

**Comment by gongshun** [comment]
> ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后 还是想问一下第一个问题singular: false的作用以及使用场景？

https://github.com/umijs/qiankun/issues/1310

**Comment by lvan-zhang** [comment]
> 

感谢！！

**Comment by wawaPoplar** [comment]
> > 
> 
> ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后 还是想问一下第一个问题singular: false的作用以及使用场景？

hello 我遇到了跟你一样的场景，现在是手动加载子应用，但是出现了 切换二级页面 页面白屏的问题，你有遇到类似的问题吗？

**Comment by lvan-zhang** [comment]
> > > 
> > 
> > 
> > ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后 还是想问一下第一个问题singular: false的作用以及使用场景？
> 
> hello 我遇到了跟你一样的场景，现在是手动加载子应用，但是出现了 切换二级页面 页面白屏的问题，你有遇到类似的问题吗？

你可以再说具体一点，切换二级页面我不理解什么意思？不过我遇到过类似，因为手动加载子应用的时候，另一个应用不会卸载，如果你有多个项目中都是绑定在id=app的节点上，可能会冲突，这个问题我也解决了，我最近会写一篇博客出来详细介绍我做的过程，到时候回复你

**Comment by wawaPoplar** [comment]
> app

我是 子应用挂载在主应用的一个组件里，每次路由切换的时候手动loadMicroApp，组件销毁的时候 unmount 子应用；但是这样就做不到缓存，但是不 unmount 的话就会白屏

**Comment by wawaPoplar** [comment]
> > > > 
> > > 
> > > 
> > > ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后 还是想问一下第一个问题singular: false的作用以及使用场景？
> > 
> > 
> > hello 我遇到了跟你一样的场景，现在是手动加载子应用，但是出现了 切换二级页面 页面白屏的问题，你有遇到类似的问题吗？
> 
> 你可以再说具体一点，切换二级页面我不理解什么意思？不过我遇到过类似，因为手动加载子应用的时候，另一个应用不会卸载，如果你有多个项目中都是绑定在id=app的节点上，可能会冲突，这个问题我也解决了，我最近会写一篇博客出来详细介绍我做的过程，到时候回复你

我是 子应用挂载在主应用的一个组件里，每次路由切换的时候手动loadMicroApp，组件销毁的时候 unmount 子应用；但是这样就做不到缓存，但是不 unmount 的话就会白屏

**Comment by lvan-zhang** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ok，了解了，看了下就是用qiankun手动加载子应用的方式就不会有重新加载的问题了。然后 还是想问一下第一个问题singular: false的作用以及使用场景？
> > > 
> > > 
> > > hello 我遇到了跟你一样的场景，现在是手动加载子应用，但是出现了 切换二级页面 页面白屏的问题，你有遇到类似的问题吗？
> > 
> > 
> > 你可以再说具体一点，切换二级页面我不理解什么意思？不过我遇到过类似，因为手动加载子应用的时候，另一个应用不会卸载，如果你有多个项目中都是绑定在id=app的节点上，可能会冲突，这个问题我也解决了，我最近会写一篇博客出来详细介绍我做的过程，到时候回复你
> 
> 我是 子应用挂载在主应用的一个组件里，每次路由切换的时候手动loadMicroApp，组件销毁的时候 unmount 子应用；但是这样就做不到缓存，但是不 unmount 的话就会白屏

虽然没遇到过，但是解决的思路还是找到白屏的原因，你的子应用最终还是挂载在一个dom（类似div id="app"）上的，去看白屏的时候这个dom里面是不是为空或者是被隐藏掉了之类的原因

**Comment by tong822218** [comment]
> 屏

你好请问解决了吗我也遇到这个问题了
