### ISSUE TITLE
[Bug]应用中打开modal再关闭，插入的overflow-y: hidden不会消失

### ISSUE THREAD

**Issue by zhujun24** [umijs/qiankun#2360]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

应用中打开 antd modal 再关闭，插入的overflow-y: hidden不会消失，关键字是 rc-util-locker，导致页面无法上下滚动

<img width="824" alt="Screen Shot 2022-12-21 at 16 44 56" src="https://user-images.githubusercontent.com/7301773/208860146-e97530a0-3d22-42ab-ba0a-8b36bf3c4277.png">

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.8.4
- **浏览器版本**：Chrome 108.0.5359.124 (Official Build) (x86_64)
- **操作系统**：MacOS 12.6.2

**Comment by a992681784** [comment]
遇到同样的问题了，请问下你那边解决了吗？

**Comment by zhujun24** [comment]
> 遇到同样的问题了，请问下你那边解决了吗？

关闭 sandbox 临时解决

**Comment by a992681784** [comment]
> > 遇到同样的问题了，请问下你那边解决了吗？
> 
> 关闭 sandbox 临时解决

谢谢 我去试下

**Comment by mmmmmmmgo** [comment]
https://github.com/ant-design/ant-design/issues/38845

**Comment by janninaweigal** [comment]
除了关闭sandbox，还有其他解决方案不
