### ISSUE TITLE
子应用动态插入的script脚本，无法保证脚步执行顺序

### ISSUE THREAD

**Issue by lucy091** [umijs/qiankun#2362]
## What happens?

export function load(url: string) {
  const node: any = document.createElement('script');

  node.src = url;
  node.async = false;

  document.head.appendChild(node);

}

如通过以上load方法 插入a, b,c 三个脚本，无法保证 a执行完了再执行b, 然后再执行c,
实际是谁先下载完谁先执行

## Context

- **qiankun Version**: 2.8.4
- **Platform Version**: umi 3
- **Browser Version**:

**Comment by lucy091** [comment]
取消沙箱模式，可以保证执行顺序

**Comment by lucy091** [comment]
https://github.com/kuitos/import-html-entry/pull/96
@kuitos  
@gongshun

**Comment by mdchun** [comment]
请问有其他解决方案么？

**Comment by kuitos** [comment]
3.0 支持了
