### ISSUE TITLE
子应用vue.config.js中的publicPath能动态设置吗？

### ISSUE THREAD

**Issue by infinityXN** [umijs/qiankun#2369]

**Comment by gongshun** [comment]
https://webpack.docschina.org/guides/public-path/#on-the-fly

![image](https://github.com/umijs/qiankun/assets/29347231/56008c33-1987-4e5a-8183-0a0329539381)

https://qiankun.umijs.org/zh/guide/tutorial#vue-%E5%BE%AE%E5%BA%94%E7%94%A8

![image](https://github.com/umijs/qiankun/assets/29347231/aff8d5f5-7fa2-43a3-9561-c96f220a302f)
