### ISSUE TITLE
IE 11 问题，官方建议的polyfill 都加了，控制台还是报 Unhandled promise rejection Error: 找不到成员。

### ISSUE THREAD

**Issue by litandota** [umijs/qiankun#2370]
![image](https://user-images.githubusercontent.com/10540308/211706347-fe94df1b-952a-4672-91b6-1b2bd704cc12.png)

报错信息截图如上；
qiankun版本 2.4.2

**Comment by litandota** [comment]
@gongshun  求大佬帮助

**Comment by litandota** [comment]
是否是因为IE 不支持proxy导致的？  我尝试引入了 import 'es6-proxy-polyfill'  还是报错

**Comment by litandota** [comment]
![image](https://user-images.githubusercontent.com/10540308/211963594-45c43026-76ce-43a8-b458-5216c1d0290a.png)
貌似不是proxy不支持导致的，错误的抛出是在qiankun源码中，位置如上图

**Comment by gongshun** [comment]
官方 demo 能在 IE10 上运行 https://github.com/umijs/qiankun/issues/1402

**Comment by litandota** [comment]
> 官方 demo 能在 IE10 上运行 #1402

能从报错上看出大概可能是哪里影响的么？  我这边主应用的配置和官方demo完全一致了

**Comment by aique127** [comment]
> > 官方 demo 能在 IE10 上运行 #1402
> 
> 能从报错上看出大概可能是哪里影响的么？ 我这边主应用的配置和官方demo完全一致了


请问解决了吗，我设置样式隔离experimentalStyleIsolation: true 且子应用entry为服务器域名地址的时候也报同样的错误，但是当entry为本地localhost的时候没问题。
