### ISSUE TITLE
[Bug]主/子应用开发环境下同时设置为https，在Edge浏览器访问子应用无法加载

### ISSUE THREAD

**Issue by Angelnashuai** [umijs/qiankun#2371]
## What happens?

主应用和子应用都是vue-cli4 快速搭建的项目，vue3.0 + ts版本

主应用和子应用同时在vue.config.js中配置https: true，在非chromium内核版本Edge浏览器访问子应用页面白屏，提示无法fetch，考虑是不是浏览器不支持fetch，于是加入了官网中的配置，运行后提示调用的对象无误，依然无法加载子应用。

但是如果将主/子应用同时设置为http协议后反而能正常显示，不需要在主应用的main.ts文件添加补丁配置，那么之前断定是不不支持fetch的结论不成立。不知道是不是因为https安全策略限制导致fetch方法表现异常？

## 最小可复现仓库
https://github.com/Angelnashuai/test

## 复现步骤，错误日志以及相关配置

1、主子应用设置vue.config.js文件
```
{
   devServer: {
      https: true,
      disableHostCheck: true,
      ...
   }
}
```

运行结果：
主应用正常运行，点击子应用时加载失败，报错提示无法fetch

2、主应用设置polyfill

`main.ts` 文件
```
import 'whatwg-fetch';
import 'custom-event-polyfill';
import 'core-js/stable/promise';
import 'core-js/stable/symbol';
import 'core-js/stable/string/starts-with';
import 'core-js/web/url';
```

`babel.config.js` 文件
```
{
  presets: [
    "@vue/cli-plugin-babel/preset",
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3
      }
    ]
  ],
}
```

运行结果：
主应用正常运行，点击子应用加载失败，报错提示调用的对象无效

3、addGlobalUncaughtErrorHandler 错误日志
```
{
  bubbles: false,
  cancelable: false,
  cancelBubble: false,
  colno: 7,
  currentTarget: Window,
  defaultPrevented: fasle,
  error: {
    appOrparcelName: "one",
    description: "调用的对象无效",
    message: "application 'one' died in status LOADING_SOURCE_CODE: 调用的对象无效"
    number: -2174181133
    stack: "
       TypeError: application 'one' died in status LOADING_SOURCE_CODE: 调用的对象无效
       at stop (eval code: 251:40)
       at _callee17$ (eval code: 659:13)
       at tryCatch (eval code: 64:9)
       at Anonymous function (eval code: 899)
       at asyncGeneratorStep  function (eval code: 899)
       ...
       ...
    "
  }
  ...
}
```

## 相关环境信息
- **qiankun 版本**  2.8.4
- **浏览器版本**：Microsoft Edge 44.18362.387.0       Microsoft EdgeHTML 18.18363
- **操作系统**：Window 10

**Comment by gongshun** [comment]
浏览器安全策略限制，http 和 https 不能混用，主应用也改成 https 就行了

**Comment by Angelnashuai** [comment]
> 

主子应用都是https

**Comment by Angelnashuai** [comment]
> 浏览器安全策略限制，http 和 https 不能混用，主应用也改成 https 就行了

主子应用都是设置的https

**Comment by Angelnashuai** [comment]
@gongshun @kuitos 不好意思之前表述不够准确，已将文中的表述进行了完善。
实际的情况是主应用，子应用的协议类型设置的是一样的，并没有混用。
当主/子应用同时设置为https的时候在edge不能正常访问子应用，但是都设置成http时就能正常显示。设置为https时出现的问题及解决方式在文中已经描述，不知道是不是因为https安全策略限制导致fetch方法表现异常。
更新版本至2.9.2后问题依然存在。

**Comment by hellowuxin** [comment]
> @gongshun @kuitos 不好意思之前表述不够准确，已将文中的表述进行了完善。 实际的情况是主应用，子应用的协议类型设置的是一样的，并没有混用。 当主/子应用同时设置为https的时候在edge不能正常访问子应用，但是都设置成http时就能正常显示。设置为https时出现的问题及解决方式在文中已经描述，不知道是不是因为https安全策略限制导致fetch方法表现异常。 更新版本至2.9.2后问题依然存在。
> 
> 因为项目需要必须使用https协议，但是定位不到具体原因，麻烦大佬们看下是什么原因。

我将 entry 的值添加 / 结尾就成功了

**Comment by Angelnashuai** [comment]
> > @gongshun @kuitos 不好意思之前表述不够准确，已将文中的表述进行了完善。 实际的情况是主应用，子应用的协议类型设置的是一样的，并没有混用。 当主/子应用同时设置为https的时候在edge不能正常访问子应用，但是都设置成http时就能正常显示。设置为https时出现的问题及解决方式在文中已经描述，不知道是不是因为https安全策略限制导致fetch方法表现异常。 更新版本至2.9.2后问题依然存在。
> > 因为项目需要必须使用https协议，但是定位不到具体原因，麻烦大佬们看下是什么原因。
> 
> 我将 entry 的值添加 / 结尾就成功了

请问使用的edge浏览器是非chrome内核的吗？浏览器版本：Microsoft Edge 44.18362.387.0 Microsoft EdgeHTML 18.18363 依然不生效
