### ISSUE TITLE
子应用使用antd upload报错Illegal invocation，主应用不会

### ISSUE THREAD

**Issue by zhupp034** [umijs/qiankun#2375]
## What happens?
子应用使用antd-upload，选择文件的时候点击取消，再次点击上传，直接报错Illegal invocation
![image](https://user-images.githubusercontent.com/33925263/212246856-7c6e6a62-2a81-40f8-9b6c-a1969302851c.png)

## Mini Showcase Repository(REQUIRED)
复现仓库：
https://github.com/zhupp034/bugPreview/tree/main/example/umi-qiankun

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.点击文件上传
http://localhost:8888/slave/home 路由下，点击文件上传
2.点击取消上传
![image](https://user-images.githubusercontent.com/33925263/212247241-ae906122-74c7-4e64-b36b-356ef2a7d09e.png)
3. 再次点击文件上传
4. 控制台报错
![image](https://user-images.githubusercontent.com/33925263/212246856-7c6e6a62-2a81-40f8-9b6c-a1969302851c.png)

**Expected behavior** 1. 2.
期待正常上传

## Context

- **Umi Version**:4.0.44
- **Node Version**:16.19.0
- **Platform**:win11

**Comment by xiaxinn** [comment]
我们遇到了同样的问题

**Comment by zackBRAVE** [comment]
同样遇到这个问题，请问有人解决了吗
