### ISSUE TITLE
qiankun does not work with AdGuard

### ISSUE THREAD

**Issue by registerMt** [umijs/qiankun#2378]
## What happens?

当AdGuard开启的时候，子应用[project-key]在cdn，qiankun无法加载子应用 
报错信息：
`
application 'project-key' died in status LOADING_SOURCE_CODE: //local.adguard.org?ts=1673424687935&amp;type=content-script&amp;dmn=g.alicdn.com&amp;pth=%2Fweb%2Fproject-key%2F1.0.25%2Fbuild%2Findex.html&amp;app=msedge.exe&amp;css=3&amp;js=1&amp;rel=0&amp;rji=0&amp;sbe=1 load failed with status 400
`

## Mini Showcase Repository(REQUIRED)
普通的qiankun应用，AdGuard关闭的情况下正常访问。

## 复现方式：
1. 安装AdGuard**软件**（不是浏览器插件）
2. 浏览器安装AdGuard浏览器助手插件
3. 子应用cnd链接如果是https，需要开启过滤 https

AdGuard 设置生效示例：
![新建项目](https://user-images.githubusercontent.com/123796160/215264971-7ecac307-6f17-4a5d-967f-788c3232bf50.jpg)

## 猜测原因:
AdGuard 的劫持请求存在`&amp;` 在html里访问自动转换 `&amp;`为 & 加载成功， 但是在import-html-entry 中fetch则不会自动转换
`<!--  script //local.adguard.org?ts=1673837448404&amp;type=content-script&amp;dmn=... replaced by import-html-entry -->`

## 单点解决方案
参考官方文档，把adguard请求过滤：
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E7%94%B1%E4%BA%8E%E8%BF%90%E8%90%A5%E5%95%86%E5%8A%A8%E6%80%81%E6%8F%92%E5%85%A5%E7%9A%84%E8%84%9A%E6%9C%AC%E5%8A%A0%E8%BD%BD%E5%BC%82%E5%B8%B8%E5%AF%BC%E8%87%B4%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98

    options: {
      prefetch: true,
      sandbox: true,
      async fetch(url, ...args): Promise<any> {
        // 子应用中如果被adgurad劫持
        if (typeof url === 'string' && url.indexOf('adguard') > -1) {
          return {
            async text() {
              return '';
            },
          };
        }
        return window.fetch(url, ...args);
      },
    }

## 问题
AdGuard用户比较多，目前每天有1-2个用户会出现这个问题，无法访问。或者还有其他的情况导致url存在 `&amp;`

是否可以在 import-html-entry fetch子应用的时候就可以转换一下url？

**Comment by gongshun** [comment]
### 问题分析

的确是这个原因，不过`&amp;` 转义为`&`是浏览器解析 html 时自动做的，url 的几个解码函数并不能实现（unescape、decodeURI、decodeURIComponent）

常见的几个转义符号[如下](https://developer.mozilla.org/zh-CN/docs/Glossary/Entity)，[完整的符号转换](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references)就比较多了

![image](https://user-images.githubusercontent.com/29347231/219935332-5f1979d0-fcc0-4234-8bfc-6f8fadef1571.png)

### 解决方案

修改 import-html-entry，在 js/css 文件的请求之前，对 url 进行一下解码，具体做法有以下两个：

1. 直接用字符串替换

先定义好替换规则，然后直接字符串替换，缺点是无法枚举所有的字符

```js
url = url.replace('&amp;','&')
```

2. 借助 DOM 解析

![image](https://user-images.githubusercontent.com/29347231/219936026-1ac89a08-d4a2-4606-9adf-6a7ecba3f971.png)

如果是这样做的话，可以直接解析子应用的整个 html ，然后直接获取里面的 script、link 和 style 等标签，也不用正则匹配了，不过改动较大

### 临时解决方案

使用自定义的 getTemplate  ，手动转换 html 中的转义字符串

```
start({
  getTemplate(tpl) {
    return tpl.replace('&amp;','&')
  },
});
```

**Comment by kuitos** [comment]
第二个方案不用全部改吧？匹配出 srcript url 之后，在 push 到数组之前，用 DOMParser 处理一下是不是就行

**Comment by gongshun** [comment]
> 第二个方案不用全部改吧？匹配出 srcript url 之后，在 push 到数组之前，用 DOMParser 处理一下是不是就行

可以的，只修改这部分代码就行
