### ISSUE TITLE
Angular作为基座，Angular子应用包含子路由时，点击子应用子路由，主应用跟子应用一直触发脏检查

### ISSUE THREAD

**Issue by whg4** [umijs/qiankun#2384]
## What happens?

Angular作为基座，Angular子应用包含子路由时，来回切换子应用子路由，主应用跟子应用一直触发脏检查，导致cpu占用率过高，页面卡顿

## Mini Showcase Repository(REQUIRED)

> https://github.com/whg4/angular-qiankun-demo

## How To Reproduce

**Steps to reproduce the behavior:** 
![image](https://user-images.githubusercontent.com/37855991/216042974-2444a69f-bf9c-4012-a064-f59ad47cd4b5.png)

- yarn start:main启动基座
- yarn start:app1启动子应用
- 浏览器访问http://localhost:4200
- 点击Subapp1路由，然后点击Subapp1 subroute路由，主应用和子应用一直触发脏检查
![image](https://user-images.githubusercontent.com/37855991/216043404-fa7f8e14-a756-480f-89ba-5036712d6a19.png)

**Expected behavior**
切换到子应用子路由时不触发脏检查死循环

## Context

- **qiankun Version**: 2.8.4
- **Platform Version**: windows 10
- **Browser Version**: Google Chrome 109.0.5414.120（正式版本） （64 位）

**Comment by wys0529** [comment]
你可以尝试下子应用使用生产模式启动，start()配置一下 sandbox:{ speedy:true }能解决性能问题，但是对开发模式不友好，还有可能会引起路由跳转（我们当前项目angular 主子应用均为hash模式），具体原因未知

**Comment by whg4** [comment]
> 你可以尝试下子应用使用生产模式启动，start()配置一下 sandbox:{ speedy:true }能解决性能问题，但是对开发模式不友好，还有可能会引起路由跳转（我们当前项目angular 主子应用均为hash模式），具体原因未知 #2197

除了开发环境，生成环境Angular也是一直触发脏检查，后面排查https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts#L389
```typescript
private registerRunningApp(name: string, proxy: Window) {
    if (this.sandboxRunning) {
      const currentRunningApp = getCurrentRunningApp();
      if (!currentRunningApp || currentRunningApp.name !== name) {
        setCurrentRunningApp({ name, window: proxy });
      }
      // FIXME if you have any other good ideas
      // remove the mark in next tick, thus we can identify whether it in micro app or not
      // this approach is just a workaround, it could not cover all complex cases, such as the micro app runs in the same task context with master in some case
      nextTask(clearCurrentRunningApp);
    }
  }
```

这里Angular获取全局变量的时候，会频繁调用nextTask（setTimeout）。我推测Zone.js捕获到这些任务，在任务清空时，会通知Angular进行脏检查。然后Angular进行脏检查的时候，又获取全局变量，形成一个死循环了

**Comment by wys0529** [comment]
对的 脏检查会一直触发，我的方法也是治标不治本，期待官方能给出什么好的解决方案，也可以把沙盒关了看一下

**Comment by whg4** [comment]
> 对的 脏检查会一直触发，我的方法也是治标不治本，期待官方能给出什么好的解决方案，也可以把沙盒关了看一下

目前是fork了qiankun的包，把nextTask中被zone.js封装后setTimeout换成原生的setTimeout，
```typescript
const nextTick: (cb: () => void) => void =
  typeof window.Zone === 'function' ? (window as any).__zone_symbol__setTimeout : (cb) => Promise.resolve().then(cb);
```
这样运行nextTask就不会被zone一直劫持了

@gongshun @kuitos 官方有解决方案吗

**Comment by kuitos** [comment]
example 上能稳定复现吗？能复现的话可以直接提pr修复
