### ISSUE TITLE
speedy模式生命周期方法获取失败

### ISSUE THREAD

**Issue by Aeero** [umijs/qiankun#2385]
## What happens?

生命周期方法获取失败，子应用无法加载

## Mini Showcase Repository(REQUIRED)

https://github.com/Aeero/qiankun-issue/tree/bug/window

## How To Reproduce

1.  yarn examples:install
2. yarn examples:start
3. 打开链接：http://localhost:7099/issue
4. 
![image](https://user-images.githubusercontent.com/13835083/216331037-979c2968-977e-49cf-a176-7740be120098.png)
5. qiankun回退到2.8.1版本，链接正常访问

## Context

这一步获取window：undefined（而2.8.1版本获取的window为proxy）
![image](https://user-images.githubusercontent.com/13835083/216331546-a15ba9c2-6257-4aff-a1af-c6236c876a4b.png)

我的webpack配置
![image](https://user-images.githubusercontent.com/13835083/216331942-c6b74b84-1e70-4a1f-a791-2078ea763611.png)

期望不是通过修改webpack解决，因为我这边的场景子应用有十多个，不太可能每个项目都去修改webpack配置的

- **qiankun Version**: >1.8.4
- **Platform Version**: macos
- **Browser Version**: chrome latest

**Comment by kuitos** [comment]
你那里没报错？
![image](https://user-images.githubusercontent.com/5206843/217844185-cbac3e80-187f-41ba-b6c3-bd921608163a.png)
回退到 2.8.1 一样报这个错

**Comment by kuitos** [comment]
你那里没报错？
![image](https://user-images.githubusercontent.com/5206843/217844185-cbac3e80-187f-41ba-b6c3-bd921608163a.png)
回退到 2.8.1 一样报这个错
