### ISSUE TITLE
fetch请求如何配置Nginx缓存

### ISSUE THREAD

**Issue by Cyxwmm** [umijs/qiankun#2396]
## 背景

![image](https://user-images.githubusercontent.com/22393346/218648696-45aabce5-14ab-4b77-a914-239b1160f843.png)

Etag是Nginx默认生成的，通过单独fetch请求获取静态资源，不会走缓存。请问 Nginx需要如何配置，才能让其走缓存

**Comment by gongshun** [comment]
检查下是否禁用了缓存

![image](https://user-images.githubusercontent.com/29347231/218689867-b769345c-d31a-4e15-8015-f677c9b4b099.png)

**Comment by Cyxwmm** [comment]
> 检查下是否禁用了缓存
> 
> ![image](https://user-images.githubusercontent.com/29347231/218689867-b769345c-d31a-4e15-8015-f677c9b4b099.png)

并没有禁用缓存 不知道为啥通过fetch就是缓存不了。正常访问子应用是可以命中缓存的....
![image](https://user-images.githubusercontent.com/22393346/219521690-407936e9-2728-4291-837f-6417f9f47b74.png)

**Comment by Cyxwmm** [comment]
nginx的配置如下      
location / {
	try_files $uri $uri/ /index.html;
	add_header Cache-Control no-cache;
	add_header Access-Control-Allow-Origin *;
	add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS';
	add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
	if ( $request_method = 'OPTIONS' ) {
		return 204;
	}
      }

**Comment by gongshun** [comment]
那应该是浏览器安全策略限制了，可以了解下：Chrome 86 启用缓存分区（ Cache partitioning）

**Comment by Cyxwmm** [comment]
> 那应该是浏览器安全策略限制了，可以了解下：Chrome 86 启用缓存分区（ Cache partitioning）

那岂不是没法通过缓存来优化静态资源的加载？

**Comment by joebnb** [comment]
same issue on my scenario,any update?

**Comment by kuitos** [comment]
响应头里 cache-control 都 no-cache 了咋缓存..

**Comment by gongshun** [comment]
> 响应头里 cache-control 都 no-cache 了咋缓存..

no-cache 并不是不缓存哦，no-cache 是每次都必须携带 etag 发请求去检查，如果 tag 一致，会返回 304，而不是文件

![image](https://github.com/umijs/qiankun/assets/29347231/ac404f06-50cb-4b15-a73d-3c7fd742315e)

他这里还是返回200，但是 etag 是一致的，可能是服务器哪里配错了，按理说服务器应该返回304的

**Comment by kuitos** [comment]
这个 js 已经带 hash 了，可以直接做成强缓存了，304 也没必要了

**Comment by gongshun** [comment]
> 这个 js 已经带 hash 了，可以直接做成强缓存了，304 也没必要了

是这样没错，但是他这个没命中304，应该也是有问题的

**Comment by 18518300669** [comment]
看origin你这个是跨域了，跨域的fetch请求即使304，在浏览器也是200，你可以看Time和Size大小应该是已经命中了。看服务端日志或者本地抓包一下，应该已经返回的304.
