### ISSUE TITLE
[Bug] v2.9.2 在低版本浏览器，会产生异常 globalThis is not defined

### ISSUE THREAD

**Issue by viko16** [umijs/qiankun#2398]
## What happens?

- 在 v2.9.2 ，使用 `loadMicroApp` 加载子应用，在低版本浏览器 (Chrome < 70)，会产生异常 `globalThis is not defined`，导致子应用加载失败
- 如果锁定到 v2.9.1，一切都正常了

| 在 Chrome 110 | 在 Chrome 69 |
| ------------- | ------------ |
|      <img width="1026" alt="image" src="https://user-images.githubusercontent.com/5064777/218795025-694e386d-cee2-4fae-81b4-0844e0eb976a.png">         |      <img width="1024" alt="image" src="https://user-images.githubusercontent.com/5064777/218794849-2cef220c-a262-492f-a333-238576ef1ed3.png">        |

## 最小可复现仓库

https://github.com/viko16/qiankun-global-this

## 复现步骤，错误日志以及相关配置

1. npm install
2. npm run dev
3. 访问 http://localhost:8000/

## 相关环境信息

- **qiankun 版本** 2.9.2
- **浏览器版本**：Chrome/69.0.3497.0
- **操作系统**：Mac OS X 10_16_0

**Comment by kuitos** [comment]
released https://github.com/kuitos/import-html-entry/releases/tag/v1.14.2
