### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/qiankun#24]
本地运行是没问题的，但是把子应用从qiankun框架分离出来，主应用和子应用单独部署后，报错跨域问题。

Access to fetch at 'http://micro-sub-web.devapp.com/' from origin 'http://micro-web.devapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

而我在子应用中已经导出为umd模块了。
"start": "parcel serve ./src/index.html --global dvaapp --port 7103",
"build": "parcel build ./src/index.html --global dvaapp --public-url ./",
请问这个跨域是什么原因？如何解决呢？

**Comment by kuitos** [comment]
跨域问题你需要自己配置服务器解决了，qiankun 没办法帮你处理

**Comment by lemonwong** [comment]
解决了吗  我也有这个问题  Nginx已经配置了跨域 还是不行

**Comment by William-Cai** [comment]
> 解决了吗 我也有这个问题 Nginx已经配置了跨域 还是不行

我是偶尔会出现改问题

**Comment by ufodba** [comment]
我之前是没有这个问题，突然就出现了，没有改任何东西。只是更新了浏览器版本。请问有人解决了吗？
