### ISSUE TITLE
[Bug]qiankun 2.10.0 版本，微应用嵌入后报错

### ISSUE THREAD

**Issue by Cool-Star** [umijs/qiankun#2406]
## What happens?

版本升级到2.10.0以后，嵌入微应用会报错
[Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'](https://stackoverflow.com/questions/61966422/failed-to-execute-observe-on-mutationobserver-parameter-1-is-not-of-type-n)

原因是微应用通过MutationObserver监测window.document， 此时的document在微前端模式下被代理了不再是一个node节点。

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
released v2.10.1
