### ISSUE TITLE
[Bug]2.10.1版本 子应用是elementui时el-select控件弹出位置错误即使设置了 el-select 属性 popper-append-to-body=false 还是不能解决 2.9.3版本没有该问题

### ISSUE THREAD

**Issue by wushujia789** [umijs/qiankun#2408]
2.10.1版本   
子应用是elementui时el-select控件弹出位置错误即使设置了
el-select  属性  popper-append-to-body=false  还是不能解决
2.9.3版本没有该问题

**Comment by liuruibin** [comment]
我也遇到同样的问题，现在是"qiankun": ">2.10.1 || 2.9.3",希望下个版本可以解决

**Comment by gongshun** [comment]
复现demo：https://github.com/gongshun/qiankun-vue-demo/tree/report-bug

复现步骤：
1. 根目录安装依赖：`npm i`
2. 给主子应用安装依赖：`npm run install-all`
3. 启动主子应用：`npm run start-all`
4. 浏览器访问：http://localhost:8080/app-vue-history/

![image](https://user-images.githubusercontent.com/29347231/221526936-44d07d7b-df18-4fa7-a9ca-02b648e54fc2.png)

**Comment by zeyongTsai** [comment]
element-ui popper.js 内部有对 window.document 和 元素的 parentNode 进行对比的逻辑，在2.10.x  qiankun 实现了 document 的 proxy，导致这个判断失败，进而不能正确计算出元素的位置。

**Comment by zrui1121** [comment]
2.10.6版本，同样的问题还是存在，问题描述：
1、在el-drawer里面的el-select的下拉框，会在el-select触发focus事件时候，下拉框出现在屏幕左上角
2、el-drawer挂载在body上
3、只在el-drawer里面的el-select触发focus事件会复现，其他情况正常
