### ISSUE TITLE
yarn examples:install出现错误

### ISSUE THREAD

**Issue by 1320611670** [umijs/qiankun#2410]
通过yarn examples:install安装出现报错
![bug](https://user-images.githubusercontent.com/77874445/221132469-38c21652-cff5-4a9c-a0f0-abc4988e52ba.png)
我安装了好几次yarn问题始终没有解决，我别的项目安装依赖都没出错了，初步判断应该不是我的环境问题，是你们的配置出现冲突了吧，麻烦你们看看感谢，我的yarn版本是1.22.19

**Comment by BadMooncc** [comment]
你这肯定不是人家的问题啊

**Comment by 1320611670** [comment]
> 
主要没有解决方案，我试过好几次依赖版本卸载安装

**Comment by LuoRiWuSheng** [comment]
```c#
yarn 版本  yarn version v1.22.18
node 版本 v14.19.3
```

我的机子是可以运行的 

操作步骤：

```
yarn run examples:install
yarn run examples:start
```

![image](https://github.com/umijs/qiankun/assets/23192097/2129e9c3-f082-44d7-b95c-a2bd5ef73a9b)

**Comment by LuoRiWuSheng** [comment]
> > 
> 
> 主要没有解决方案，我试过好几次依赖版本卸载安装

看下我上面的截图

**Comment by webxmsj** [comment]
直接关了吧 和人家有啥关系

**Comment by vortesnail** [comment]
必须使用 yarn，1.22.x 版本有用

**Comment by BigFrontEnd-China** [comment]
yarn run examples:install  执行完成先  再执行 yarn run examples:start
