### ISSUE TITLE
qiankun  版本 2.10.2 在safari 13.1.3 上 加载不到子应用

### ISSUE THREAD

**Issue by rjz0528** [umijs/qiankun#2420]
qiankun 最新 版本 2.10.2 safari 13.1.3 (13) 这个大版本， 中和部分 14 版本会报错 t.name.indexOf("bound ") && !t.hasOwnProperty("prototype");

**Comment by kuitos** [comment]
麻烦补充一下更详细的报错信息

**Comment by lihao336991** [comment]
我也遇到了这个问题，完整报错信息是 TypeError: application 'creator-creator' died in status LOADING_SOURCE_CODE: undefined is not an object (evaluating 'e.name.indexOf')
错误堆栈是：
qiankun@2.10.11/node_modules/qiankun/es/utils.js at indexOf(108:25)
qiankun@2.10.11/node_modules/qiankun/es/sandbox/patchers/dynamicAppend/forStrictSandbox.js at value(95:53)
node_modules/import-html-entry/esm/utils.js at window(158:17)

**Comment by rjz0528** [comment]
> 我也遇到了这个问题，完整报错信息是 TypeError: application 'creator-creator' dead in status LOADING_SOURCE_CODE: undefined is not an object (evaluating 'e.name.indexOf') 错误堆栈是： qiankun@2.10.11/node_modules/qiankun/es/utils.js at indexOf(108:25) qiankun@2.10.11/node_modules/qiank un/es/sandbox/patchers/dynamicAppend/forStrictSandbox.js 位于值（95:53）node_modules/import-html-entry/esm/utils.js 位于窗口（ 158 : 17 ）

这个 升级版本， 或者，直接定级在 14一下的版本

**Comment by lihao336991** [comment]
> 

升级safari版本？还是升级框架版本？用户的浏览器版本是不可控的

**Comment by rjz0528** [comment]
> > 
> 
> 升级safari版本？还是升级框架版本？用户的浏览器版本是不可控的

你直接 用 qiankun 最新版本吧。 或者使用  "2.9.3", 但是这样存在 弊端。

**Comment by lihao336991** [comment]
> 



> > > 
> > 
> > 
> > 升级safari版本？还是升级框架版本？用户的浏览器版本是不可控的
> 
> 你直接 用 qiankun 最新版本吧。 或者使用 "2.9.3", 但是这样存在 弊端。

现在就是qiankun最新版本2.10.11。会有什么弊端呢？

**Comment by laohubzy** [comment]
> > > 
> > 
> > 
> > 升级safari版本？还是升级框架版本？用户的浏览器版本是不可控的
> 
> 你直接 用 qiankun 最新版本吧。 或者使用 "2.9.3", 但是这样存在 弊端。

升级到2.10.11 好像还是没有解决问题。

**Comment by laohubzy** [comment]
> 麻烦补充一下更详细的报错信息

在Safari 13.0.2版本中，对于document.all 返回的typeof 与项目中期望的不一致。
var callable = naughtySafari ? typeof fn === 'function' && typeof fn !== 'undefined' : typeof fn === 'function'  会返回true, 但是在isBoundedFunction方法中无法取到 document.all.name，从而导致直接报错。建议直接修改 isBoundedFunction中 fn.name.indexOf('bound ')的兼容性

**Comment by rjz0528** [comment]
> > > > 
> > > 
> > > 
> > > 升级safari版本？还是升级框架版本？用户的浏览器版本是不可控的
> > 
> > 
> > 你直接 用 qiankun 最新版本吧。 或者使用 "2.9.3", 但是这样存在 弊端。
> 
> 升级到2.10.11 好像还是没有解决问题。

那就降级吧。 先降到 2.9.3。 我目前使用这个版本 没有问题。  之后在升上去

**Comment by kuitos** [comment]
safari 13.1.3 下的问题已经已经修复了 https://github.com/umijs/qiankun/pull/2465

> 在Safari 13.0.2版本中，对于document.all 返回的typeof 与项目中期望的不一致。
var callable = naughtySafari ? typeof fn === 'function' && typeof fn !== 'undefined' : typeof fn === 'function' 会返回true

我在 safari 13.1.3 下测试了，这段逻辑应该没问题会返回 false，能给一个 Safari 13.0.2 下 `typeof document.all === 'function' && typeof document.all === 'undefined'` 和 `typeof document.all === 'function' && typeof document.all !== 'undefined'` 的执行截图吗？ @laohubzy

**Comment by cd6428** [comment]
@laohubzy @lihao336991 您好，我们在钉钉内置的qiankun应用中也出现了此问题，也是iPhone会出现此问题，qiankun版本是2.10.8，请问我们应该如何解决该问题呢
