### ISSUE TITLE
angular+ng-zorro+qiankun加载子应用ng-zorro报错

### ISSUE THREAD

**Issue by lichao1233** [umijs/qiankun#2429]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

加载子应用ng-zorro报错
## 最小可复现仓库
子应用 angular + single-spa-angular15 + ng-zorro 主应用 angular15 + qiankun + ng-zorro 
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/127492157/224285922-37e1a118-9e4b-48f6-88aa-e63403e3f000.png)

## 相关环境信息

- **qiankun 版本**2.10.2
- **浏览器版本**： 111.0.5563.64
- **操作系统**：windows11

**Comment by lanmingle** [comment]
对于 angular 12+ 我试用了 qiankun / wujie / micro-app 等都觉得不怎么样，各种各样的问题，我建议使用模块联邦，目前这个还是运行得很不错。
https://github.com/angular-architects/module-federation-plugin

**Comment by miaomiao9527** [comment]
> 

@lichao1233 请问最后解决了吗？我也遇到同样的问题了。
