### ISSUE TITLE
基座vue3 + vue-router4, 子应用 vue2 + vue-router3,子应用无法动态加载路由，并且beforEach只触发一次

### ISSUE THREAD

**Issue by GOGOGOSIR** [umijs/qiankun#2430]
## What happens?

基座vue3 + vue-router4, 子应用 vue2 + vue-router3。会出现以下两个问题：

1. 跳转子应用时，如果是懒加载的路由，该资源会被主应用加载，则会导致路由报错

2. 首次跳转子应用可以触发子应用的beforeEach，但是切换至其他应用的地址后，再切回来，则无法触发子应用的beforeEach

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/GOGOGOSIR/qiankun-issue

## How To Reproduce

复现 **跳转子应用时，如果是懒加载的路由，该资源会被主应用加载，则会导致路由报错:**  问题步骤如下：

![Kapture 2023-03-12 at 14 51 30](https://user-images.githubusercontent.com/26272801/224529206-8e16f80f-d3d6-4fc8-a507-1e78b0cf70b5.gif)

如图所示，在访问 js/src_views_about_vue.js 资源时是用的主应用的 9000 端口，而不是子应用的 9004 端口

**Expected behavior** 

访问子应用的页面对应的路由资源，应该是子应用去加载对应的资源

复现 **首次跳转子应用可以触发子应用的beforeEach，但是切换至其他应用的地址后，再切回来，则无法触发子应用的beforeEach:**  问题步骤如下：

![Kapture 2023-03-12 at 14 57 55](https://user-images.githubusercontent.com/26272801/224529455-870f3c2b-6cce-4784-9ff4-9bccc1e7eba6.gif)

如图所示，再次切换回子应用qiankun-micro-vue2的 guide 页面时，不触发子应用 router 的 beforeEach 钩子’

**Expected behavior** 

每次访问子应用的页面能触发router的路由守卫

## Context

- **qiankun Version**: 2.9.2
- **主应用的vue版本**: 3.2.41
- **主应用的vue-router版本**: 4.1.5
- **子应用的vue版本**: 2.6.14
- **子应用的vue-router版本**: 3.2.0
- **Platform Version**: macOS
- **Browser Version**: chrome

**Comment by GOGOGOSIR** [comment]
对于 跳转子应用时，如果是懒加载的路由，该资源会被主应用加载，则会导致路由报错 该问题目前已修复：
<img width="592" alt="image" src="https://user-images.githubusercontent.com/26272801/226081001-88667b54-1fbe-4e4a-b470-803cd9c98d15.png">

**Comment by GOGOGOSIR** [comment]
但是对于问题2. 首次跳转子应用可以触发子应用的beforeEach，但是切换至其他应用的地址后，再切回来，则无法触发子应用的beforeEach。这个问题到目前依然未解决

**Comment by long36708** [comment]
首次跳转子应用可以触发子应用的beforeEach，但是切换至其他应用的地址后，再切回来，则无法触发子应用的beforeEach .请问这个问题解决了吗
