### ISSUE TITLE
[Bug]子应用都路由按需加载下，访问A子应用后，B子应用调用A子应用的样式丢失

### ISSUE THREAD

**Issue by mayefeng** [umijs/qiankun#2444]
## What happens?

1、主应用下有A、B两个子应用，同时B子应用下也会调用A子应用，A、B应用都做了路由按需加载
2、先访问A， 后访问B，B中调用A应用的样式丢失
3、先访问B，后访问A，A的样式丢失

## 最小可复现仓库
非常抱歉，由于公司安全保密机制，代码暂不可外传

## 相关环境信息

- **qiankun 版本**：2.10.3 2.7.3 2.6.3 都有
- **浏览器版本**：Chrome: 111.0.5563.64
- **操作系统**：MacOs Windows都有

**Comment by kuitos** [comment]
先保证 qiankun 版本都是最新
