### ISSUE TITLE
ProxySandbox 在主子应用存在同名属性时 bound 逻辑存在问题

### ISSUE THREAD

**Issue by beliefgp** [umijs/qiankun#2456]
## What happens?

在子应用存在诸如此类场景时：`var Vs = Object.prototype.hasOwnProperty; Vs({a:1}, 'a')` 返回结果与实际不符。

## 最小可复现仓库
主应用代码：

```
var Vs = () => { };
```

子应用代码：
```
var Vs = Object.prototype.hasOwnProperty;
Jr = (C,B)=>{
  for (var r in B || (B = {}))
      Vs.call(B, r) && zs(C, r, B[r]);
  return C
}
```
因为主应用正好有压缩的重名属性，导致 `has` 判断存在，进入了 FakeWindow 的 `get` 逻辑。
实际上在 `var Vs = Object.prototype.hasOwnProperty;` 赋值时逻辑都是正常的。
但是在读取时，实际命中逻辑 [get 代码](https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts#L284):

```
const actualTarget = propertiesWithGetter.has(p) ? globalContext : p in target ? target : globalContext;
const value = actualTarget[p]; // 这里其实都还是正常的，p = Vs ， value = hasOwnProperty

// 因为这里只是校验了 p = Vs 变量的 Descriptor，未命中这里返回 false
if (isPropertyFrozen(actualTarget, p)) {
  return value;
}

const boundTarget = useNativeWindowForBindingsProps.get(p) ? nativeGlobal : globalContext;
// 最终走到了这里，value=hasOwnProperty 被 bind 给了 globalContext，造成后续判断异常
return getTargetValue(boundTarget, value);
```

## 相关环境信息

- **qiankun 版本**：2.10.5
- **浏览器版本**：Chrome
- **操作系统**：Mac

**Comment by kuitos** [comment]
你的应用是 esbuild 构建的吗

**Comment by beliefgp** [comment]
@kuitos 压缩是，就是 umi 那套，这个问题主要原因和什么构建的没核心关系吧，就是凑巧了，主子应用压缩后，存在同名变量，
正好同名的变量值是 Object.prototype.hasOwnProperty 这种 api，然后经过 bound 后，值就不对了

**Comment by kuitos** [comment]
https://umijs.org/docs/api/config#esbuildminifyiife 这个配置打开。
压缩后不应该存在泄露到全局的变量，这本身就是有问题的。

**Comment by beliefgp** [comment]
THX

**Comment by yvesyao** [comment]
debug 了一整天。要是 umi 可以针对接入 qiankun 的应用进行强提示就好了……
