### ISSUE TITLE
[Feature Request] 子应用加载时如何加入动态效果？

### ISSUE THREAD

**Issue by ilovemath** [umijs/qiankun#246]
vue开发主程序时，希望通过transition为子应用切换加入动态效果，如下所示：
`  <transition name="fade" mode="out-in">
      <div class="appContainer" v-html="content">content</div>
</transition>
`

**Comment by kuitos** [comment]
这个跟 qiankun 没关系吧，主应用怎么渲染是你自己实现的

**Comment by ilovemath** [comment]
主应用再切换子应用的时候使用transition没有效果，切换很生硬
