### ISSUE TITLE
qiankun微应用在79版或63版chrome浏览器中无法加载微应用，微应用报错

### ISSUE THREAD

**Issue by 1003363041** [umijs/qiankun#2462]
## What happens?

微应用在低版本浏览器中无法加载，报错信息为：
application “xxxx” died in status LOADING_SOURCE_CODE: Illegal invocation
at Proxy.eval (document-create-element.js?5450.4)
at Object ../node_modules/core-js/internals/document-create-element.js

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.10.2
- **Platform Version**:mac
- **Browser Version**:chrome63

**Comment by kuitos** [comment]
chrome 79 里跑了下 example 没复现，能提供下最小可复现吗

**Comment by YuanWenLai** [comment]
Chrome/62.0.3202.73 Safari/537.36也能复现这个问题，我看主应用是有加babel-polyfill。

场景：
需要将现有开发的管理平台，内嵌到一个安卓7.1.1的机器里

报错：app-errors.js?b147:11 Uncaught TypeError: application 'login' died in status LOADING_SOURCE_CODE: Illegal invocation

本地调试查看：
![Uploading image.png…]()
