### ISSUE TITLE
element-ui 与element-plus 样式都是el-开头的，样式污染

### ISSUE THREAD

**Issue by LdPz-ROOM** [umijs/qiankun#2463]
基座应用采用vue2、element-ui
子应用采用vue3、element-plus
因为element-ui和element-plus前缀相同、命名规则相同，但内部html结构发生变化，从而导致子应用element-plus的样式会被污染

**Comment by gongshun** [comment]
https://element-plus.org/zh-CN/guide/namespace.html#%E8%AE%BE%E7%BD%AE-elconfigprovider
element-plus 可以 自定义命名空间
