### ISSUE TITLE
EventSource's response不符合预期

### ISSUE THREAD

**Issue by fguizc** [umijs/qiankun#247]
## What happens?

[子应用](https://github.com/fguizc/qiankun-slave-repo)和[父应用](https://github.com/fguizc/qiankun-master-repo)已经做了代码隔离，分属于两个项目。

子应用在开发环境下配置 `webpack-hot-middleware`，且为`browserHistory`模式，在本地（默认配置 //localhost:8080/）打开子应用无问题

```js
// build/dev-server.js
var webpackHotMiddleware = hotMiddleware(compiler, {
      log: false,
      heartbeat: 2000,
      path: '/__hmr'
    })
```

在父应用中注册后访问子应用，于本地打开`http://localhost:7099/forchange`后控制台报错：
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`，查看控制台看到请求`http://localhost:7099/__hmr`，返回的是父应用的html文本，导致无法正常渲染子应用

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/fguizc/qiankun-master-repo
https://github.com/fguizc/qiankun-slave-repo

## How To Reproduce

**Steps to reproduce the behavior:**

1. 子应用中执行 `yarn dev` 和 `yarn mock` 两个命令
2. 父应用执行 `yarn start`
3. 打开控制台 `http://localhost:7099`，等待自动跳转到默认子应用，此时控制台出现正文描述错误

**Expected behavior** 
正常渲染React子应用

## Context

- **qiankun Version**:
- **Platform Version**: mac
- **Browser Version**: chrome80

**Comment by kuitos** [comment]
`path: '/__hmr'` 这里配置路径补全，带上端口号

**Comment by fguizc** [comment]
@kuitos 

不好意思，再请教一下。按照上面的配置，更改了
```js
// build/webpack.dev.conf.js
'entry: {
    app: ['webpack-hot-middleware/client?path=__hmr&dynamicPublicPath=true', './src/main/index.tsx']
  },
```
达到补齐配置的目的后，仍然无法正常渲染React子应用，表现为只加载了应用的`app.xxx.js`但对应路由的chunk并未加载
