### ISSUE TITLE
speedy导致的问题

### ISSUE THREAD

**Issue by galenjiang** [umijs/qiankun#2474]
## What happens?

遍历元素的时候为了不拿document这个元素, 判断了 someElement.parentNode  !== document
但是等号左边是原生的document, 等号右边是proxy后的，导致了判断失败

## 复现步骤，错误日志以及相关配置

assert.notEqual( someElement.parentNode, document)

很多lib可能都会用这个来判断。建议默认改成false

**Comment by kuitos** [comment]
这个应该已经修复了 https://github.com/umijs/qiankun/pull/2415 检查下版本是不是最新
