### ISSUE TITLE
vue+element UI子应用下拉框挂载问题

### ISSUE THREAD

**Issue by anyi1998** [umijs/qiankun#2476]
## What happens?

主应用为umi+antd, 子应用1为umi+antd， 子应用2为vue+element UI。

1、当sandbox为true的时候，vue+elememt UI子应用el-select, el-popover 弹出层显示在页面最左上角；

2、当sandbox为false时，umi+antd子应用出现mount后立即unmount的现象；

3、sandbox设置strictStyleIsolation或者experimentalStyleIsolation为true的时候，umi+antd子应用样式存在丢失的问题。

请问可能是什么问题，应该怎么做？

## Context

- **qiankun Version**: 主应用及子应用1、2都是用的 @umijs/plugin-qiankun: 2.37.1

**Comment by gongshun** [comment]
- 问题1应该和 https://github.com/umijs/qiankun/issues/2474 https://github.com/umijs/qiankun/issues/2408 同一个问题，已经修复
- 问题2和问题3没有复现代码，不知问题

antd 的样式污染可以不用 qiankun 的 css 沙箱，antd 支持修改class前缀，样式隔离效果好性能高 https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB

**Comment by anyi1998** [comment]
用的包已经更新到最新的@umijs/plugin-qiankun 2.43.3，问题还是存在

> * 问题1应该和 [speedy导致的问题 #2474](https://github.com/umijs/qiankun/issues/2474) [[Bug]2.10.1版本 子应用是elementui时el-select控件弹出位置错误即使设置了 el-select 属性 popper-append-to-body=false 还是不能解决 2.9.3版本没有该问题 #2408](https://github.com/umijs/qiankun/issues/2408) 同一个问题，已经修复
> * 问题2和问题3没有复现代码，不知问题
> 
> antd 的样式污染可以不用 qiankun 的 css 沙箱，antd 支持修改class前缀，样式隔离效果好性能高 https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB
