### ISSUE TITLE
加载子应用，但子应用的包不存在，会一直重复刷新加载。

### ISSUE THREAD

**Issue by haiyang01** [umijs/qiankun#2478]
问题：加载子应用，但是 子应用的包不存在，会一直重复刷新加载。

- **qiankun 版本**：2.10.6
- **浏览器版本**：Chrome 版本 112.0.5615.138（正式版本） （64 位）
- **操作系统**：windows

**Comment by BeMxself** [comment]
我也遇到这个问题了，有解决方案吗？

**Comment by linhf123** [comment]
或许是 wepback 热更新的 wss 地址对不上，可以调整下 SOCKET_SERVER 配置试试，可以用 beforeunload 阻止浏览器重新加载排查下
`
window.addEventListener('beforeunload', (event) => {
  // Cancel the event as stated by the standard.
  event.preventDefault();
  // Chrome requires returnValue to be set.
  event.returnValue = 'Are you sure you want to leave this page?';
});
`
看看有没有类似的报错
![image](https://github.com/user-attachments/assets/9300476f-1a3d-476c-9108-4896a4e093f3)

参考：https://blog.csdn.net/violetjack0808/article/details/86577776

**Comment by G1King** [comment]
> 或许是 wepback 热更新的 wss 地址对不上，可以调整下 SOCKET_SERVER 配置试试，可以用 beforeunload 阻止浏览器重新加载排查下 `window.addEventListener('beforeunload', (event) => { // Cancel the event as stated by the standard. event.preventDefault(); // Chrome requires returnValue to be set. event.returnValue = 'Are you sure you want to leave this page?'; });` 看看有没有类似的报错 ![image](https://private-user-images.githubusercontent.com/32009993/352490139-9300476f-1a3d-476c-9108-4896a4e093f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDE0NzAsIm5iZiI6MTcyNTQ0MTE3MCwicGF0aCI6Ii8zMjAwOTk5My8zNTI0OTAxMzktOTMwMDQ3NmYtMWEzZC00NzZjLTkxMDgtNDg5NmE0ZTA5M2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YzJmNzc5MDU3YTMwOTBlNDNiZGQ3ZGNiZDg3M2Y4OGI5ODc5YTU5MGViMWIyZGY1ZWU3MzQ1MWNmYjA3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ge4W_c6rXzEwiC6uOZFrIxMYXzAQYAdAgGqmVqmU2o4)
> 
> 参考：https://blog.csdn.net/violetjack0808/article/details/86577776

牛逼 感谢解决了问题啊 一直没找到问题在哪
