### ISSUE TITLE
import-html-entry 将外部CSS链接转换为嵌入式样式, 导致appContent巨大

### ISSUE THREAD

**Issue by wukong1995** [umijs/qiankun#248]
## What happens?
`import-html-entry` 将外部CSS链接转换为嵌入式样式, 导致appContent巨大，目前接入原有项目时，props.content的大小是402kb

在`import-html-entry`代码中写到：convert external css link to inline style for performance optimization。但是字符串的长度有402kb，是否会对qiankun性能有影响？

## 最小可复现仓库
https://github.com/laiyefe/micro-tts/tree/dev_wpp_qiankun，

## 复现步骤，错误日志以及相关配置
1. 使用了demo中的react FrameFrameWork，在此组件中将props.content 打印出来

## 相关环境信息

- **qiankun 版本**: `^1.3.14`
- **浏览器版本**：chrome 79.0.3945.130（正式版本） （64 位）
- **操作系统**： macos

**Comment by kuitos** [comment]
我们实践中有超过 1m 的 css 会被转为内联样式，目前还没有发现明显的性能问题
