### ISSUE TITLE
[求助]window.onresize在子应用不执行

### ISSUE THREAD

**Issue by web-zwb** [umijs/qiankun#2488]
## What happens?

qiankun版本： 2.7.0
浏览器版本：chrome 111.0.5563.147
操作系统：win10

问题：主应用为vue项目，子应用也是vue项目，在子应用页面的mounted内执行window.onresize不执行
## 最小可复现仓库

window.onresize = () => {
      console.log('监听屏幕尺寸')
  }

**Comment by onburn** [comment]
@web-zwb 一样的问题，子应用单独访问可以触发resize监听，通过qiankun加载进来不可以，请问你解决了吗？

**Comment by onburn** [comment]
看官方描述意思是，子应用是代理基座应用的window，不知道是不是这个原因导致的子应用无法触发resize；临时更为了ResizeObserver监听dom处理
