### ISSUE TITLE
部署后子应用的 sourceMap 的 filePath 问题

### ISSUE THREAD

**Issue by yzw7489757** [umijs/qiankun#249]
## What happens?
部署后子应用的 sourceMap 的 filePath 问题

## 最小可复现仓库

[magic-front](https://github.com/yzw7489757/Magic-front)

## 复现步骤，错误日志以及相关配置

main.xxx.cn 主应用容器
apps.xxx.cn 子应用1  =====>  main.xxx.cn/apps 
performance.xxx.cn 子应用2 =====>  main.xxx.cn/performance 

子应用1 actived 时，由于 sourceMap 基于当前路径产生了错误的url，fail parse。 
e.g. ：
current: http://main.localhost.cn/apps/views/home
fetch:  http://main.localhost.cn/apps/views/app.7b9aa6e8.js.map ❌
fetch:  http://apps.localhost.cn/static/js/app.7b9aa6e8.js.map ✅
虽然能关掉但是解决不了问题[手动滑稽]。请问这块你们是怎么处理的。

![alt](https://staticfile-1254003462.cos.ap-chengdu.myqcloud.com/WechatIMG3.jpeg)

线上复现地址 [https://magic.yuanziwen.cn](https://magic.yuanziwen.cn)
## 相关环境信息

- **qiankun 版本** : 1.3.14
- **浏览器版本**：Chrome 版本 80.0.3987.87（正式版本 64 位）"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
- **操作系统**：MacOS 10.14.6 (18G103)

**Comment by kuitos** [comment]
参考 umi plugin 的处理 https://github.com/umijs/umi-plugin-qiankun/blob/master/src/slave/index.ts#L80
