### ISSUE TITLE
angular子应用的图片资源在基座中404，配置publicpath无效

### ISSUE THREAD

**Issue by yiqisweet** [umijs/qiankun#2490]
angular 基座配合 angular子应用 都是angular@11.x
子应用的图片在基座中404，配置publicpath无效，也导入了    __webpack_public_path__ 

下的demo也有这个问题，请问如何解决
（其他框架子应用的资源配置后即可正常，唯独angular失效）

**Comment by wnyjk** [comment]
1 设置base
 const { container } = props 
 container.querySelector('base')?.setAttribute('href', window .__INJECTED_PUBLIC_PATH_BY_QIANKUN__);
只加载一个子应用可以，加载多个子应用的时候，base只能有一个生效。


2 将相对路径拼接为绝对路径 （可以改为公共方法，或者指令统一更改）
for example:  img1 = `${(window as any).__INJECTED_PUBLIC_PATH_BY_QIANKUN__}assets/img/task-title.svg`;

**Comment by wnyjk** [comment]
如果你是monorepo项目，也可以考虑将静态资源放在主应用下。

还有一种就是转为base64.但是不太好

**Comment by suruicq** [comment]
我遇到了相同的问题，请问你最后是怎么解决的呀？
