### ISSUE TITLE
ant-design-pro 使用 qiankun，开发环境能正常使用，build 后 主应用 加载 子应用会报 initFocus is not a function 错误

### ISSUE THREAD

**Issue by yanthink** [umijs/qiankun#2493]
## What happens?

![image](https://github.com/umijs/qiankun/assets/9098321/b3d6dcfd-729e-4d6f-aa74-9b85223a1e04)

主应用和子应用都使用 ant-design-pro 6.0.0 开发， dev 环境能正常使用，build 后 主应用 加载 子应用会报 initFocus is not a function 错误

主应用配置

`config/config.ts`

```js
qiankun: {
   master: {},
},
```

`src/app.tsx`

```js
export const qiankun = {
  apps: [
    {
      name: 'app1',
      entry: '//localhost:8888',
    },
  ],
  routes: [
    {
      path: '/app1/*',
      name: 'app1',
      microApp: 'app1',
      microAppProps: {
        autoCaptureError: true,
      },
    },
  ],
};
```

子应用配置

`config/config.ts`

```js
qiankun: {
    slave: {
      shouldNotModifyDefaultBase: true,
    },
 },
```

`src/app.tsx`

```js
export const qiankun = {
  bootstrap() {
    console.log('react app bootstraped');
  },
  mount(props) {
    console.log(props);
  },
  unmount(props) {
    console.log(props);
  },
  update(props) {
    console.log(props);
  },
};
```

## Context

- **qiankun Version**:2.10.6
- **Platform Version**: MacOS 13.0 (22A380)
- **Browser Version**: Chrome 113.0.5672.92

**Comment by yanthink** [comment]
umi 配置加上 [esbuildMinifyIIFE: true](https://umijs.org/docs/api/config#esbuildminifyiife) 就好了，建议官方在 umijs 微前端文档FAQ里加上，不然对新手太不友好了。

**Comment by xu-wenhao** [comment]
@

> umi 配置加上 [esbuildMinifyIIFE: true](https://umijs.org/docs/api/config#esbuildminifyiife) 就好了，建议官方在 umijs 微前端文档FAQ里加上，不然对新手太不友好了。

我被这个问题折磨两天了，qiankun文档翻了个遍，怎么搞都是这个问题，终于看到你的这个方法解决了，感谢！
官方确实应该把这个加到FAQ里面，使用umi全家桶并开启微前端肯定会遇到这个问题的！

**Comment by gongshun** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/2456
