### ISSUE TITLE
关于子应用挂载问题

### ISSUE THREAD

**Issue by wbbw007** [umijs/qiankun#25]
目前使用qiankun时，通过路由从一个子应用跳转到另一个子应用时，是否可以两个子应用同时处于挂载状态，而其中一个不会被unmount掉

**Comment by kuitos** [comment]
激活规则是根据你配置的 activeRule 来的，如果要两个同时 mount 规则配成一样的就行了。
但是如果两个应用都是含路由的话这么做肯定会报错的，因为浏览器 url 只有一个，一个应用识别了另一个通常就 404 了

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#could-i-active-two-sub-apps-at-the-same-time
