### ISSUE TITLE
[Bug]接入子项目报错：LOADING_SOURCE_CODE: jQuery is not defined

### ISSUE THREAD

**Issue by 429365799** [umijs/qiankun#250]
## What happens?

引入子项目报错：
![image](https://user-images.githubusercontent.com/7577355/74523257-bbd0e500-4f57-11ea-836f-c2ace7c63795.png)

## 最小可复现仓库

由于是公司内网的项目，抱歉无法提供项目

## 复现步骤，错误日志以及相关配置
用的是qiankun的example基础之上修改的：
main.js：
![image](https://user-images.githubusercontent.com/7577355/74523503-21bd6c80-4f58-11ea-86a7-2a6b1882f723.png)

子项目中的webpack配置：
![image](https://user-images.githubusercontent.com/7577355/74523585-4b769380-4f58-11ea-8f7e-5ee9c0d0d21c.png)

子项目入口文件bootstrap.js：
![image](https://user-images.githubusercontent.com/7577355/74523724-a14b3b80-4f58-11ea-802c-8f0102c9cd69.png)

子项目单独访问时的资源加载：
![image](https://user-images.githubusercontent.com/7577355/74523974-246c9180-4f59-11ea-839d-f78a355089da.png)

子项目在qiankun中的资源加载：
![image](https://user-images.githubusercontent.com/7577355/74524789-ac9f6680-4f5a-11ea-9efc-b902f5c35abb.png)

报错信息：
![image](https://user-images.githubusercontent.com/7577355/74524144-685f9680-4f59-11ea-942b-73d7023a7f6f.png)

附带相关nginx配置：
![image](https://user-images.githubusercontent.com/7577355/74524312-c1c7c580-4f59-11ea-94fa-dc03fca5bb9d.png)

以及nginx的html目录结构：
![image](https://user-images.githubusercontent.com/7577355/74524391-e7ed6580-4f59-11ea-9c10-298a367fd15a.png)

子项目单独访问是没问题的，但是一加载到qiankun中就上述错误，怀疑是不是执行vendor.js之后环境没初始化好？还是jquery之类的库没有成功暴露到window上？是js沙箱相关的问题吗。

有个信息就是qiankun用1.3.8的时候可以加载项目，但是项目切换就出现各种干扰问题，于是想着升级qiankun版本，就出现上述问题

## 相关环境信息

- **qiankun 版本**：1.3.14
- **浏览器版本**：版本 66.0.3359.139（正式版本） （64 位）
- **操作系统**：win7

**Comment by Deturium** [comment]
信息太少了，尤其是跟出错的 `jQuery` 相关的部分根本没有

请提供下最小复现 demo，不然无法排查

**Comment by kuitos** [comment]
closed via inactive
