### ISSUE TITLE
Antd5 run in the qiankun with shadow dom, css not appear?

### ISSUE THREAD

**Issue by AsuraLuo** [umijs/qiankun#2500]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by AsuraLuo** [comment]
```javascript
 await start({
    singular: true,
    sandbox: {
      strictStyleIsolation: true,
      experimentalStyleIsolation: true
    }
  })
```

**Comment by kuitos** [comment]
duplicated with https://github.com/ant-design/ant-design/issues/42358

**Comment by AsuraLuo** [comment]
@kuitos strictStyleIsolation 不建议使用了，新版本准备废弃了
是在乾坤3.0版本里面吗。目前2.新版本有什么办法能解决这个问题吗
