### ISSUE TITLE
项目nginx部署后，子应用刷新没有qiankun生命周期

### ISSUE THREAD

**Issue by menghuanyipin** [umijs/qiankun#2506]
## What happens?
基座应用：
    "qiankun": "^2.7.4",
    "vue": "^3.2.45",
    "vue-router": "^4.1.6"
    "vite": "^4.0.0",
     // ./micros/app.js
    
      const apps = [
        {
          name: 'street-patrol',
          entry: process.env.NODE_ENV === 'production' ? '/street-patrol/' : '//localhost:5000',
          container: '#app',
          activeRule: '/street-patrol'
        },
        {
          name: 'horizon-front',
          entry: process.env.NODE_ENV === 'production' ? '/horizon-front/' : '//localhost:4000',
          container: '#app',
          activeRule: '/horizon-front'
        }
      ];
      export default apps;

子应用：
    "vite-plugin-qiankun": "^1.0.15",
    "vue": "^3.3.2",
    "vue-router": "^4.2.0"
    "vite": "^4.3.5",
    // main.ts
    import {
        renderWithQiankun,
        qiankunWindow,
        type QiankunProps,
    } from "vite-plugin-qiankun/dist/helper";
    
    const render = (props: QiankunProps = {})=>{
    
        const { container,onGlobalStateChange } = props;
        const el: string | Element = container?.querySelector("#street-patrol") || "#street-patrol";
        const app = createApp(App)
        
        const router = createRouter({
            history: createWebHistory("/street-patrol/"),//createWebHistory(import.meta.env.BASE_URL),
            routes
        })
    
        app.use(createPinia())
        app.use(router)
        app.mount(el)
    
    
        if(onGlobalStateChange){
            props.onGlobalStateChange((state:any) => {
              console.log('通信状态发生改变：', state);
              let {DoGis,token,userInfo} = state;
              app.config.globalProperties.$DoGis = DoGis;
              app.config.globalProperties.$token = token;
              app.config.globalProperties.$userInfo = userInfo;
            }, true);
        }
    }
    
    const initQianKun = () => {
        renderWithQiankun({
          bootstrap() {
            console.log("微应用:bootstrap");
          },
          mount(props) {
            // 获取主应用传入数据
            console.log("微应用:mount", props);
            render(props);
          }, 
          unmount(props) {
            console.log("微应用:unmount", props);
            
            setTimeout(() => {
              location.reload();
            }, 0);
          },
          update(props) {
            console.log("微应用:update", props);
          },
        });
    };
    
    qiankunWindow.__POWERED_BY_QIANKUN__ ? initQianKun() : render();

    // vite.config.ts
    export default defineConfig({
      base: "/street-patrol/",
      plugins: [
        vue(),
        qiankun("street-patrol", {
          useDevMode: true,
        }),
      ],
      server: {
        headers: {
          "Access-Control-Allow-Origin": "*",
        },
        origin: 'http://localhost:5000',
        port: 5000,
        hmr: {
          overlay: false
        },
        host: '0.0.0.0'
      },
      resolve: {
        alias: {
          '@': fileURLToPath(new URL('./src', import.meta.url))
        }
      }
    })

nginx 配置：

#基座配置
 location / {
            root   /usr/share/nginx/html/xa-pcg-base;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }
#子应用配置（该应用没有问题）
    location /horizon-front {
        root   /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control no-cache;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }
#子应用配置（该应用刷新有问题）
    location /street-patrol {
        root  /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ /street-patrol/index.html;
        add_header Cache-Control no-cache;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }

问题描述：
开发环境下没有问题，部署nginx服务器后，基座点击按钮跳转子应用没有问题（子应用的qiankun生命周期都会执行），但是子应用不能刷新，刷新后基座似乎没有执行，子应用检测qiankunWindow.__POWERED_BY_QIANKUN__ 为 undefined ；qiankun生命周期无法执行；导致浏览器回退无法回到基座应用上。

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/cookbook#%E5%9C%BA%E6%99%AF-1%E4%B8%BB%E5%BA%94%E7%94%A8%E5%92%8C%E5%BE%AE%E5%BA%94%E7%94%A8%E9%83%A8%E7%BD%B2%E5%88%B0%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%90%8C%E4%B8%80%E4%B8%AA-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3

![image](https://github.com/umijs/qiankun/assets/29347231/7a831604-55b8-44df-8ea7-5ebed095ccea)

![image](https://github.com/umijs/qiankun/assets/29347231/c95d8319-8941-4110-889d-c79b0f2bbc90)

**Comment by Caesar-APAX** [comment]
@menghuanyipin 
你都不看文档的嘛，ngnix部署

**Comment by menghuanyipin** [comment]
感谢各位大佬~
