### ISSUE TITLE
不同子项目要求不同版本的node版本怎么办

### ISSUE THREAD

**Issue by UmbraCi** [umijs/qiankun#2509]
应用中把微前端项目做成monorepo，实际安装依赖的时候，一些老旧项目因为node-sass版本兼容问题，不得不得使用NODE V14的版本，有些新的子项目又是用umijs最新版构建的又需要nodeV16版本，这种情况怎么办，node-sass升级就要升级loader，又会牵涉到webpack的大版本更新，breakchange非常多，实在不想动原有的业务代码。

**Comment by aladdin-add** [comment]
这个和qiankun没关系。:)

**Comment by UmbraCi** [comment]
> 这个和qiankun没关系。:)

已经用pnpm V7+node14解决这个问题

**Comment by Hachiko2018** [comment]
> > 这个和qiankun没关系。:)
> 
> 已经用pnpm V7+node14解决这个问题

老哥能具体说一下吗？
