### ISSUE TITLE
子应用中往父容器 `head` 节点动态 `appendChild` 新节点时，新节点挂载在子应用 

### ISSUE THREAD

**Issue by xinyu-shopastro** [umijs/qiankun#2511]
## What happens?
子应用中往父容器 `head` 节点动态 `appendChild` 新节点时，新节点实际挂载在子应用里面

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
```
  const head = document.querySelector('head');
  const linkTag = document.createElement('link');
  linkTag.setAttribute('rel', 'shortcut icon');
  linkTag.setAttribute('type', 'image/svg');
  linkTag.setAttribute('id', 'new-favicon');
  linkTag.setAttribute('href', iconUrl);
  head.appendChild(linkTag);
```

**Expected behavior** 1. 2. 子应用中往父容器 `head` 节点 `appendChild` 新节点时，新节点应该添加到父级 `head` 中

## Context

- **qiankun Version**: 2.10.8
- **Platform Version**:
- **Browser Version**:

求告知这种需求应该怎么实现

**Comment by xinyu-shopastro** [comment]
#2502

**Comment by kuitos** [comment]
子应用要操作主应用的 dom 就属于沙箱逃逸了，这个不符合预期。
如果一定要这么做只能把沙箱关了。
