### ISSUE TITLE
[Bug]2.10.8版本 子应用是elementui时el-select在el-drawer中触发focus事件时候下拉框弹出位置错误

### ISSUE THREAD

**Issue by zrui1121** [umijs/qiankun#2512]
## What happens?
1、在el-drawer里面的el-select的下拉框，会在el-select触发focus事件时候，下拉框出现在屏幕左上角
2、el-drawer挂载在body上
3、只在el-drawer里面的el-select触发focus事件会复现，其他情况正常

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:
1、打开el-drawer，el-select组件包含在内，绑定focus事件
2、触发focus事件，下拉框出现在屏幕左上角

**Expected behavior
1、下拉框出现位置正确

## Context

- **qiankun Version: 2.10.8
- **Platform Version: vue2+elementUI
- **Browser Version: V113 Chrome

**Comment by gongshun** [comment]
试了下，没有复现，测试demo ：https://github.com/gongshun/qiankun_bug_report/tree/issue-2512

![image](https://github.com/umijs/qiankun/assets/29347231/a90af4ab-5348-4990-b40a-c29c726b6148)
