### ISSUE TITLE
qiankun子应用样式丢失

### ISSUE THREAD

**Issue by PingZaiDotTse** [umijs/qiankun#2514]
## What happens?
umi+qiankun项目在原本的linux服务器上可以正常运行(外网环境)，但当把父应用和子应用同样的方式部署在堡垒机的windows server 2012上后(无法访问外网)，却出现了当父应用访问子应用时，子应用的antd组件样式全部丢失，自己写的css正常。
antd组件在umi config里配置了如下：
```js
antd: {
    configProvider: {
      prefixCls: 'bms-ant',   
      primaryColor: '#3377FF'
      // getPopupContainer:(triggerNode:HTMLElement)=>triggerNode
    }
  },
  qiankun: {
    slave: {},
  },
  mfsu: {},
  lessLoader: {
    modifyVars: { '@ant-prefix': 'bms-ant' }
  }, //对应修改生成的 antd 样式类名
```
## 最小可复现仓库
最小复现仓库由于是在堡垒机中，无法提供额外的访问demo
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
控制台并没有报错信息

## 相关环境信息

- **qiankun 版本**: 抱歉，用的是umi插件，不知道如何看版本
- **Antd版本**: ^5.0.7
-  **umi版本**:"@umijs/max": "^4.0.51 
- **node版本**: v19.2.0
- **浏览器版本**：chrome
- **操作系统**：windows server 2012

**Comment by kuitos** [comment]
andt5 有兼容性要求 see https://ant-design.antgroup.com/docs/react/compatible-style-cn
