### ISSUE TITLE
第二次进入子应用样式异常，less文件丢失，这个是什么原因呢

### ISSUE THREAD

**Issue by JQKxxx** [umijs/qiankun#2523]
![image](https://github.com/umijs/qiankun/assets/54975209/d5e01fd1-da79-4ab0-bcfc-3746842ae153)
![image](https://github.com/umijs/qiankun/assets/54975209/76d417e7-a5a0-4772-ac67-c409e58ae4c3)

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by buslightyear** [comment]
样式文件丢失的问题，你解决了吗。我第一次就丢失
