### ISSUE TITLE
离开子应用报 application 'xxx' died in status UNMOUNTING: router is not defined

### ISSUE THREAD

**Issue by huangguangpo** [umijs/qiankun#2524]
主应用及子应用都是vue2版本，子应用里有自己的路由规则，所以主应用在 配路径是 有加 /xxx/*
当进入子应用后，离开时返回主应用或切换其他子应用是，会报 application 'xxx' died in status UNMOUNTING: router is not defined

在子应用的mainjs内 有暴露卸载方法

export async function unmount() {
  console.log('router---', router)
  instance.$destroy()
  instance.$el.innerHTML = ''
  router = null
  instance = null
}

**Comment by zpersion** [comment]
解决了吗？ 你是怎么解的
