### ISSUE TITLE
【bug】ie11环境下开启experimentalStyleIsolation隔离时出现bug。

### ISSUE THREAD

**Issue by aique127** [umijs/qiankun#2527]
复现步骤
1、ie11环境下开启experimentalStyleIsolation: true。
2、子应用中有css使用了动画且样式为-webkit-transform。
3、这时候浏览器报错：找不到成员，导致渲染子应用失败。
4、我已经使用官方示例复现https://github.com/aique127/qiankun-example

![experimentalStyleIsolation](https://github.com/umijs/qiankun/assets/43040641/edbba4b7-9a12-4b0a-aa4d-c2562c2c94cb)
![webkit](https://github.com/umijs/qiankun/assets/43040641/a2591fc6-e687-443d-b477-1f4bd83a10d5)

![ie11-error](https://github.com/umijs/qiankun/assets/43040641/931d71ce-a3d2-4ef8-b135-9efe94ec5b6d)

**Comment by aique127** [comment]
请问我还需要做哪些操作，大佬们能不能回应一下呢。 @gongshun @kuitos  。
只要使用了elementui这个问题必现。

**Comment by aique127** [comment]
原因我已经找到了，ie11环境下，当css样式中使用了@Keyframe且带有-webkit-私有前缀时，cssRules获取不到cssText导致报错: 找不到成员。

**Comment by wangdaodao** [comment]
目前使用`postcss-remove-prefixes`尝试解决，可以参考
postcss.config.js中配置
```js
const unprefix = require('postcss-remove-prefixes');
module.exports = {
    plugins: [unprefix]
};
```

**Comment by aique127** [comment]
> 



> 目前使用`postcss-remove-prefixes`尝试解决，可以参考 postcss.config.js中配置
> 
> ```js
> const unprefix = require('postcss-remove-prefixes');
> module.exports = {
>     plugins: [unprefix]
> };
> ```

多谢。但是把所有前缀了都去掉了，css还能兼容其它浏览器吗？

**Comment by wangdaodao** [comment]
> 

目前来看，我这里把饿了么组件和项目的都去掉了前缀，并没有发现什么兼容性问题，后期等官方合并了代码，应该就能从根本上解决这个问题了。
