### ISSUE TITLE
老项目如何引入qiankun？求思路

### ISSUE THREAD

**Issue by ShenJieXin** [umijs/qiankun#2528]
## 相关环境信息

- **最新qiankun 版本**
- **浏览器版本**：Chrome最新
- **操作系统**：windows11
- **node版本**：v12.5.0

**Comment by liimin** [comment]
写个组件,里面套个iframe可还行?

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1147#issuecomment-754698527

**Comment by yooki99** [comment]
每个jq页面当作子应用注册
