### ISSUE TITLE
[Bug]子应用是angular项目，配置了__webpack_public_path__，但是加载的静态资源图片404.

### ISSUE THREAD

**Issue by wnyjk** [umijs/qiankun#2529]
子应用是angular项目，配置了__webpack_public_path__，但是加载的静态资源图片404.

图片使用的相对路径
 < img class="img"  src="./assets/img/checked.png" alt="">

但是  获取资源的路径是从主应用去获取  http://localhost:5173/assets/img/checked.png
主应用：  http://localhost:5173/
子应用： http://localhost:7000/

## 相关环境信息

- **qiankun 版本**： ^2.10.8
-  **angular 版本**： ^15.0.0
- **浏览器版本**： google 113.0.5672.94
- **操作系统**： win10

**Comment by kuitos** [comment]
这段代码得过一遍编译，才会自动把 publicPath 补上
