### ISSUE TITLE
[Bug] @umijs/plugin-qiankun 接入子项目资源加载错误

### ISSUE THREAD

**Issue by Draco-china** [umijs/qiankun#253]
## What happens?
![image](https://user-images.githubusercontent.com/22271474/74727460-277ac100-527c-11ea-9f60-c8a440421c62.png)

## 最小可复现仓库
抱歉，由于是公司内网的项目，无法提供项目

## 复现步骤，错误日志以及相关配置
- 开发环境下正常， 错误在于生产环境
- 子应用单独运行正常
- 从父应用中运行时资源路径错误

子项目页面资源与umi资源加载正常

![image](https://user-images.githubusercontent.com/22271474/74727817-aec83480-527c-11ea-8cc9-b67fc5e70e15.png)
![image](https://user-images.githubusercontent.com/22271474/74727877-c69fb880-527c-11ea-8b6a-b0ca193f642d.png)

父应用中运行子应用时的资源请求地址错误
![image](https://user-images.githubusercontent.com/22271474/74727957-ee8f1c00-527c-11ea-94e9-c117b75d4005.png)

子应用单独运行时
![image](https://user-images.githubusercontent.com/22271474/74728369-94db2180-527d-11ea-9a34-bf8ba4549d35.png)

- 子应用配置
![image](https://user-images.githubusercontent.com/22271474/74728074-1da58d80-527d-11ea-969e-469472683974.png)
- 父应用配置
![image](https://user-images.githubusercontent.com/22271474/74728649-234fa300-527e-11ea-94c0-ec93ea985b5b.png)
![image](https://user-images.githubusercontent.com/22271474/74728164-3d3cb600-527d-11ea-8faa-7293a6f3d45f.png)

## 其它信息说明
 @umijs/plugin-qiankun 版本 1.3.4 时运行正常
此后的 1.3.5～1.4.0 都存在上述问题

根据 https://github.com/umijs/qiankun/wiki/FAQ#why-dynamic-imported-assets-missing 已配置publicPath

**Comment by kuitos** [comment]
子应用配置个 `runtimePublicPath: false` 看看

**Comment by Draco-china** [comment]
> 子应用配置个`runtimePublicPath: false`看看

配置后已经恢复正常，谢谢，

对比打包前后的index.html, 
移除了
<script>
window.publicPath = <%= YOUR PUBLIC_PATH %>
</script>
那我可以理解为 运行时 window.publicPath 将 <%= YOUR PUBLIC_PATH %> 转化成了 `/` 请求，所以导致资源请求错误吗？
