### ISSUE TITLE
子应用里动态创建a标签下载文件, download属性失效

### ISSUE THREAD

**Issue by guyi233** [umijs/qiankun#2530]
- **qiankun 版本**: 2.7.0
- **浏览器版本**：114.0.5735.110（正式版本） （64 位）
- **操作系统**：windows10

![image](https://github.com/umijs/qiankun/assets/114651290/888b8259-c651-424b-ad98-d51524e15166)
后端返回的blob, 前端动态创建a标签实现下载
发现a标签的download属性失效(单独运行子应用是可以的), 导致下载的文件名称不对

**Comment by kuitos** [comment]
验证了一下，最新版无法复现
