### ISSUE TITLE
【BUG】IE11中，报SCRIPT16389

### ISSUE THREAD

**Issue by JiKhun** [umijs/qiankun#2534]
在IE11中，报错如下：
![FC8512DC-B250-47dd-AC1C-DF81C545B2FB](https://github.com/umijs/qiankun/assets/35250555/70130d46-ab9d-4c97-8581-6ae59c471e57)
![31BCE6CB-E9F3-4364-AFAE-95662DFB2A8F](https://github.com/umijs/qiankun/assets/35250555/364caad7-ed81-4e3e-8528-283ee607fb84)

qiankun Version: 2.10.5
Platform Version: win10
Browser Version: ie11

**Comment by gongshun** [comment]
![image](https://github.com/umijs/qiankun/assets/29347231/47f71e16-b8ec-4028-892b-636724eaf61b)

https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%BB%99-ie-%E6%89%93%E8%A1%A5%E4%B8%81
