### ISSUE TITLE
vue hash路由模式下 匹配问题

### ISSUE THREAD

**Issue by xiaohuooo** [umijs/qiankun#2540]
vue hash路由模式下 匹配不到多个路径比如说 activeRule：#/a/b/c ,而history就可以

## 相关环境信息

- **qiankun 版本** 2.9.1
- **浏览器版本**：edge 114.0.1823.58 (正式版本) (64 位)
- **操作系统**：win11

**Comment by gongshun** [comment]
看文档，需要把activeRule写成函数， https://qiankun.umijs.org/zh/cookbook#activerule-%E4%BD%BF%E7%94%A8-locationhash-%E5%8C%BA%E5%88%86%E5%BE%AE%E5%BA%94%E7%94%A8
