### ISSUE TITLE
[Bug]子应用的className成功渲染到dom上，但是样式文件未成功加载

### ISSUE THREAD

**Issue by buslightyear** [umijs/qiankun#2541]
## What happens?

子应用的自定义样式丢失了，样式文件未成功加载。
应用已经单独部署在服务器上，如果单独直接访问该微应用的页面，formStyle样式是正常的。通过访问主应用所加载的该微应用的页面才会出现自定义样式formStyle丢失的问题

## 最小可复现仓库
无

## 复现步骤，错误日志以及相关配置

// index.jsx

> 
> import style from './assets/css/index.less';
> 
> 《div className={style.formStyle}>示例</div >

// /assets/css/index.less

> 
> .formStyle{
>     position: absolute;
>     right: 8px;
>     top: 5px;
> }

![image](https://github.com/umijs/qiankun/assets/39004975/7bf571d1-482f-422f-857c-59ec2f063fcf)

## 相关环境信息

- **qiankun 版本** ：^2.10.8
- **浏览器版本**：114.0.5735.134（正式版本） （64 位）
- **操作系统**：window11

**Comment by wybks2** [comment]
> Since the issue was labeled with `Need Reproduction`, but no response in 30 days. This issue will be close. If you have any questions, you can comment and reply. 由于该 issue 被标记为需要可复现步骤，却 30 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

我也出现了这个问题，是css样式文件没加载。同一个页面，部分css文件有时候会丢失。刷新页面，会正常

**Comment by amy0133** [comment]
我这边也突然出现了这个问题，这个有什么解决办法吗？

![Image](https://github.com/user-attachments/assets/388defe9-18de-4f1b-b28e-5cd53ab3053d)

![Image](https://github.com/user-attachments/assets/a200a9ce-aa41-4eeb-b525-cd4197d4d020)
