### ISSUE TITLE
子应用MouseEvent.buttons 在特定条件下值会出现问题

### ISSUE THREAD

**Issue by fanggz2017** [umijs/qiankun#2546]
背景：父子应用都是使用react，子应用引用了@antv/g6这个库
          
## What happens?
1.  当我使用G6这个库，并对canvas进行拖拽的时候，发现一旦页面上触发了其他鼠标事件，g6的canvas拖拽事件就会失效；
2.  当不使用qiankun的时候，并不会出现这个问题；
3. 排查到G6的代码库有有这样一段代码
![image](https://github.com/umijs/qiankun/assets/30068618/b84e6216-66c4-4dbc-8819-4ec19488fb69)
4. 在qiankun下，当子应用触发其他鼠标事件的时候，再触发拖拽事件window.event.buttons的值始终为0， 在不使用qiankun时，这个值会置为1。
5. 在qiankun下，如果先触发拖拽，再触发其他事件，就不会导致window.event.buttons的出问题。

## 最小可复现仓库
   - 
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
1.  准备两个最简单的react父子应用库；
2.  
![image](https://github.com/umijs/qiankun/assets/30068618/5e8d45fa-ba71-442d-b94a-f4ef98d4efec)

## 相关环境信息

- **qiankun 版本**
- 2.10.10
- **浏览器版本**：
- 114.0.5735.198
- **操作系统**：
- MacOS

我现在只知道G6拖拽的时候会对window.event.buttons做判断，没明白为什么在qiankun下window.event.buttons的值会出现差异

**Comment by kuitos** [comment]
如果只在本地出现，那应该跟 https://github.com/umijs/qiankun/issues/2375 是同类问题

**Comment by fanggz2017** [comment]
确实是的，haha，打包到线上就正常了。
