### ISSUE TITLE
问题 Wrapper element for XXX is not existed! 必现, sandbox.loose 设为 true 的办法并不完美，请问有无完美的办法？

### ISSUE THREAD

**Issue by FedLife** [umijs/qiankun#2547]
问题 **Wrapper element for XXX is not existed!** 必现。issues有人问过，但没找到完美解决办法。简要说明如下：
1. 我有两个微应用 A 和 B，都是基于webpack构建的；
2. 由于历史问题，**微应用A较重**，index.html约有81kb；
3. 通过 registerMicroApps 注册到了qiankun，并启动，核心代码如下：
```
registerMicroApps(
    apps.map(app => ({
      ...app,
      entry: urlFix(app.entry),
      container: "#__subapp-viewport__",
      loader,
      props: options.transferedProps
    })),
    {
      beforeLoad: options.beforeLoad || [
        app => {
          console.log(app.name)
        },
      ],
      beforeMount: options.beforeMount || [
        app => {
          console.log(app.name)
        },
      ]
    },
  );
start({
  // sandbox: {
  //   loose: true,
  // },
 });
```
4. 进入微应用A时，不等页面渲染完，点击微应用B的入口，就报错了，在控制台可以观察到：
        - 应用生命周期函数 `beforeMount` 和 `beforeLoad`打印的应用不一致（beforeLoad打印的是B，beforeMount打印的是A）；
        - `Wrapper element for XXX is not existed!`的报错信息；
  

5. sandbox.loose 设为 true 不完美的地方在于：虽没有报错，但渲染的应用是之前没出来的A，不是切换后的B

期望：**在较重的微应用A没有出来时切到微应用B后，能够正常渲染微应用B。**

- **qiankun Version**:  2.10.10
- **Platform Version**:  macOS14.0 Beta
- **Browser Version**:  chrome 114.0.5735.198

**Comment by FedLife** [comment]
重现问题的仓库 (`qiankun examples`)的修改：https://github.com/FedLife/qiankun-examples/tree/main
![Jul-11-2023 16-45-33](https://github.com/umijs/qiankun/assets/25764065/c7c68740-4943-43b3-b644-2f7bdc37e510)

**Comment by FedLife** [comment]
> Hello @FedLife. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @FedLife, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

重现问题的仓库（`qiankun examples`的修改）：https://github.com/FedLife/qiankun-examples/tree/main
![Jul-11-2023 16-45-33](https://github.com/umijs/qiankun/assets/25764065/c7c68740-4943-43b3-b644-2f7bdc37e510)

**Comment by kuitos** [comment]
singular 配置为 true https://qiankun.umijs.org/zh/api#startopts

**Comment by FedLife** [comment]
1.  文档的介绍里，singular 默认就是 true
2. 我还是在重现的demo里显式地加上了这个配置，问题和之前一样
![image](https://github.com/umijs/qiankun/assets/25764065/6c4f558a-437f-4838-a805-cab278aa4916)

**Comment by kuitos** [comment]
看日志打印顺序都是对的，那就是应用本身的问题，比如 unmount 后代码还在跑

**Comment by kuitos** [comment]
![image](https://github.com/umijs/qiankun/assets/5206843/77e06d04-9491-498a-855f-b55514508a38)

**Comment by FedLife** [comment]
日志开始是对的 后面貌似窜了
![image](https://github.com/umijs/qiankun/assets/25764065/83c7dcf5-f1f4-4536-9ef2-aa682c07b28e)

**Comment by kuitos** [comment]
URL又跳到了heavyA啊，react16就自动卸载了

**Comment by FedLife** [comment]
url变化：初始为 `react16` ->  点击 `heavyA` -> 点击 `react16`

应该是要中止 `heavyA` 渲染 `react16`，结果却自动跳到了 `heavyA`

**Comment by kuitos** [comment]
对，问题就是为什么自动跳到了 heavyA。目测是 heavyA 的路由在前一次 unmount 时没有被卸载

**Comment by xilongwang1** [comment]
@FedLife 解决了吗? 我也遇到了, 一个月了还没解决

**Comment by FedLife** [comment]
> @FedLife 解决了吗? 我也遇到了, 一个月了还没解决

没有，只是简单处理了下，在报错的时候让页面重载一次，保证有东西出来

**Comment by JunmingZ** [comment]
我直接用loadMicroApp取代registerMicroApps，直接手动控制卸载注册，暂时脱离了这个Wrapper element for XXX is not existed! 的问题， 等qiankun3.0吧。

**Comment by kojuit** [comment]
我们的问题是一样的，我这边start()执行的时候把 prefetch设置成 false能解决这个问题

**Comment by jiaoxuyang1013** [comment]
真的好坑，自动注册就报错了， 改成手动控制就没问题

**Comment by mutour123** [comment]
真的好坑，这个问题我也遇到了，解决不了。手动控制都没有用

**Comment by jasonHzq** [comment]
> 真的好坑，自动注册就报错了， 改成手动控制就没问题

黑盒加魔法太多了。。

**Comment by ChengCuotuo** [comment]
如果是 react18，unmountComponentAtNode 已经被标记为 Deprecated，取消挂载会报这个错误，改成 unmount 
https://react.dev/reference/react-dom/client/createRoot#root-unmount
可以解决这个问题
