### ISSUE TITLE
[Feature Request] 子应用沙箱setter和getter的场景需求

### ISSUE THREAD

**Issue by TheYuuu** [umijs/qiankun#2550]
## Background

在希望子应用可以通过微前端加载子应用的场景中
子应用是一个spa，内部有/a/xx 路由
子孙应用也是一个spa，内部有/b/xx路由
那么，子应用加载完子孙应用后，子孙应用会根据当前站点 /a/xx 的url去内部匹配路由/b/xx，子孙应用就404了

## Proposal

<img width="669" alt="image" src="https://github.com/umijs/qiankun/assets/31104528/1987a49a-f3b2-4350-bd61-9ab7a35f9cb8">

目前尝试过在基座层面代理location对象，在沙箱getter返回处理好的location对象，给子孙应用提供正确的路由信息，其实wujie也是这么做的，那么在qiankun2或者qiankun3中，会有类似microAppSandboxSetter和microAppSandboxGetter的的参数吗

## 额外

同时，目前qiankun中，performance.now返回永远是第一次进入系统的相对时间，那么在切换子应用时，刚加载的子应用内部通过performance.now获取相对时间戳，在一些场景是希望是相对于开始加载子应用的那个时间点，目前如果有如上的设计也可以比较好的解决问题

**Comment by kuitos** [comment]
有更合理的方案 https://qiankun.umijs.org/zh/cookbook#%E5%90%8C%E6%97%B6%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA%E5%BE%AE%E5%BA%94%E7%94%A8%E6%97%B6

**Comment by TheYuuu** [comment]
> 有更合理的方案 https://qiankun.umijs.org/zh/cookbook#%E5%90%8C%E6%97%B6%E5%AD%98%E5%9C%A8%E5%A4%9A%E4%B8%AA%E5%BE%AE%E5%BA%94%E7%94%A8%E6%97%B6

感觉场景不太像呢
目前是注册了两个子应用{ name: 'appA', url: '/app/a', entry: 'a.html'}, { name: 'appB', url: '/app/b', entry: 'b.html'}
两个应用都需要在站点下能够直接访问 host/app/a/a1 和 host/app/b/b1
现在appA内部通过微前端加载appB的entry，这个时候appB是正确挂载的，但是浏览器地址是 /app/a/a1，appB内部的路由系统仍然还是404了

**Comment by kuitos** [comment]
官网锚点好像有点问题。
我判断下来就是同一个场景 ![image](https://github.com/umijs/qiankun/assets/5206843/6806bcf0-47d6-49c9-a480-293e96c0348e)

**Comment by TheYuuu** [comment]
> 

感谢，试了下确实是可以支持，但是我这边微前端子应用vue和react有几百个仓库，还有3个ng1，改造成本太难接受了，目前也只能通过代理location实现
