### ISSUE TITLE
vue项目复制子应用地址到其他浏览器，进不去子应用？

### ISSUE THREAD

**Issue by wlLeblanc** [umijs/qiankun#2551]
vue项目复制子应用地址到其他浏览器，进不去子应用？发现没有创建vue实例，但这又不是独立运行，这个改怎么处理，各位大佬帮帮忙！谢谢！

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/blob/master/examples/vue/src/main.js#L32
