### ISSUE TITLE
[Bug]子应用修改代码可以热更新，但是主应用没有同步更新

### ISSUE THREAD

**Issue by liangchaofei** [umijs/qiankun#2553]
## What happens?

子应用修改代码可以热更新，但是主应用没有同步更新

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
1.主应用绑定子应用
2.在子应用中修改代码，页面数据同步更新
3.但是主应用页面没有同步更新，需要手动刷新页面才能更新
4.期望主应用也可以同步更新，不需要手动刷新页面

## 复现地址
https://github.com/liangchaofei/micro

## 相关环境信息

- **qiankun 版本**：最新版本
- **浏览器版本**：chrome
- **操作系统**：mac

**Comment by Skylerliutian** [comment]
same
