### ISSUE TITLE
项目使用qiankun后监听路由变化会触发两次

### ISSUE THREAD

**Issue by xmm228** [umijs/qiankun#2555]
## What happens?

项目使用qiankun 框架后，使用公司内部的埋点sdk会触发两次浏览上报，一次refer 和当前地址都是正确，第二次 refer和当前地址一样，原因是sdk监测到两次路由变化，非qiankun的项目都是正常，目前确认是qiankun导致了两次路由变化，请问这个如何修改解决，感谢

**Comment by 2356625718** [comment]
我也遇到了这个问题，第一次进入一切正常，当第二次进入子应用时，子应用的useEffect会执行两次，分别在mount生命周期之前和之后

**Comment by kuitos** [comment]
single-spa 的行为 https://single-spa.js.org/docs/api/#popstateevent
可以通过文档上的方式过滤 single-spa 抛出的事件
