### ISSUE TITLE
子A应用加载了之后，跳到另一个子应用B，在返回到子应用A，弱网的情况下cdn的css再次加载，页面重绘的视觉很明显

### ISSUE THREAD

**Issue by Zwahxf** [umijs/qiankun#2577]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
3.0 已修复
