### ISSUE TITLE
[Bug] 乾坤导致 jszip 的 setImmediate 方法不执行

### ISSUE THREAD

**Issue by zhengxs2018** [umijs/qiankun#2589]
## What happens?

我们使用 docx-preview 模块预览 word 文档，但其内部使用了 jszip。在微应用模式下，无法预览，也不会报错，原因是 setImmediate 没有被执行。

![image](https://github.com/umijs/qiankun/assets/7506913/a7fe69f4-b1e3-4174-8859-df281ffae8a7)

## Mini Showcase Repository(REQUIRED)

[示例代码](https://github.com/zhengxs2018/qiankun-doc-jszip)

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 启动基座和微应用
2. 单独启动，可以正常显示 word 文档
3. 从基座加载，文档无法显示
5. 经过调试，在 jszip 模块中，setImmediate 方法未执行

临时解决方案

1. 通过 setTimeout 模拟 setImmediate 来解决
2. 使用完成的 url。

<img width="458" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/e85d259c-f96e-4ddc-9858-ffbb80df5dbb">

**Expected behavior** 

setImmediate 能被正常执行

## Context

- **qiankun Version**: qiankun@^2.10.12
- **Platform Version**: 
- **Browser Version**: Chrome 115.0.5790.170

**Comment by zhengxs2018** [comment]
经过重新定位，基本可以确定不是 qiankun 的问题。

@vue-office/docx 内部打包了 jszip，并且可能是 babel 的插件导致 buffer 模块被打包进来

![image](https://github.com/umijs/qiankun/assets/7506913/71c4f5ba-ca87-4a89-b5d4-0fd5b004b140)

![image](https://github.com/umijs/qiankun/assets/7506913/824f2e66-8cbd-4db9-b464-bf2d171d4c44)

导致 jszip 中的 `isNode : typeof Buffer !== "undefined"` 判断为 true

这时传递相对路径，再因为 isNode 为 true，走 jszip 处理，所以走的是 node 端处理。

<img width="225" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/149cbafb-5685-4ae4-8601-8eda8e7bb115">

<img width="515" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/0e8dc914-9639-4a4c-87d2-d18330be1a1b">

如果使用完整的 url，再兼容下 setImmediate ，就没问题，因为不走 jszip 了。

<img width="361" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/106c2559-ae3c-4c2b-a8b2-443a35f8ddc2">

![image](https://github.com/umijs/qiankun/assets/7506913/d1c6c8d8-3b6c-42db-89c4-17f2022d5e2f)

**Comment by ygcedu** [comment]
我也遇到同样的问题，但是受到这篇文章的启发：[https://gcdn.grapecity.com.cn/showtopic-151446-1-1.html](https://gcdn.grapecity.com.cn/showtopic-151446-1-1.html)，最终通过禁用qiankun的沙箱模式（start({ sandbox: false })）成功预览docx文件了
