### ISSUE TITLE
提供entry配置为scripts/styles/html的例子

### ISSUE THREAD

**Issue by topwood** [umijs/qiankun#26]
目前例子中的三个都是直接使用了entry: ""的形式加载子应用。我大致扫了眼代码里面是有对entry: {scripts : [], styles: []}解析并加载的，但是自己试了下遇到一些问题。最好能官方提供一下例子，谢谢。

**Comment by kuitos** [comment]
你的配置提供一下

**Comment by kinsliy** [comment]
@kuitos 我想一个路由配置几个子应用，按照目前entry的方式直接输入localhost地址，是有点问题的，麻烦给一个demo？
{ name: 'react app', entry: { scripts: [ '//localhost:7100','//localhost:7102' ] }, 
    render, activeRule: genActiveRule('/demo') },
