### ISSUE TITLE
[Feature Request] log more info while lifecycles not found

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#2604]
## Background

Need more info for debug

## Proposal

Like which lifecycle missed and which variable is searching

**Comment by wanghangit** [comment]
有些疑问想提前达成共识，好方便进入开发
**lifecycle相关**
1. 我记得single-spa针对每一个生命周期都是有类型校验的，这样只需要保证qiankun内部的正确性。我理解除了mount和unmount是必须的，只有这两个是需要校验的
**其他log**
1. 我看源码很多都是有默认实现的，一个是review看目前项目中哪些方法没有默认实现可能会导致执行错误
2. 加载子应用，依赖运行时生成的代码在执行时可能导致的问题
**通用问题**
1. 打印log用什么方式，需要提供统一的log方法来处理吗
2. 只有在development环境需要吗，还是根据不同的场景来处理

**Comment by kuitos** [comment]
log 现在有一个简单的统一封装

**Comment by wanghangit** [comment]
> 比如失败时，需要输出一下当前找到了哪个变量，这样就能知道是变量本身导出有问题还是找错了变量

这里我有些没明白，在找变量的时候都是通过属性（固定或动态的key）访问的，如果没找到就是导出本身有问题。
- 还是说其实想要的是一段帮助信息都提供给用户，让用户自己去判断比如：searching key is xxx but found undefined
- 可能更详细的把在哪个方法中调用的也打印出来，并给出修复建议

是我理解这样吗？

**Comment by kuitos** [comment]
当前找的是哪个变量，然后这个变量上缺乏哪个导出，这些信息

**Comment by wanghangit** [comment]
> 当前找的是哪个变量，然后这个变量上缺乏哪个导出，这些信息

好的，那和我理解的差不多，就是输出格式上看看是否有更好的建议
