### ISSUE TITLE
[Bug]vue子应用，报错Iframe has not been created yet. 

### ISSUE THREAD

**Issue by liudiming** [umijs/qiankun#2609]
## What happens?

主应用是umijs创建的项目，子应用是vue2，本项目有两个字应用，另外一个子应用也是vue2，两个子应用配置是一样的，但是有一个就启动不了，会报错Iframe has not been created yet.
![image](https://github.com/umijs/qiankun/assets/67784740/db8ee8e1-5fb4-4509-bc58-6f3f90c5b508)

![image](https://github.com/umijs/qiankun/assets/67784740/378454cb-139b-41a5-923c-bf98e96d0237)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
这是主应用app.ts
![image](https://github.com/umijs/qiankun/assets/67784740/890d25e8-5243-405b-a2cc-0f43f6344fa9)
这是主应用的路由
![image](https://github.com/umijs/qiankun/assets/67784740/33b14ef7-6148-460c-b5b8-7cf61be18eb3)

这是子应用
![image](https://github.com/umijs/qiankun/assets/67784740/8949bc72-b432-4120-8f8a-dab3f5e70363)
这是子应用路由
![image](https://github.com/umijs/qiankun/assets/67784740/ff5566c2-b3d8-4c1d-bb0e-49feb687dfe1)

## 相关环境信息

- **qiankun 版本**
- 主应用： 2.43.3
- 子应用： 2.43.3
- **浏览器版本**： chrome
- **操作系统**：windows

**Comment by gongshun** [comment]
代码问题有2点：

1. 不要把子应用的路由拿到主应用去注册一遍
2.  `__webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;` 这个代码需要单独一个文件

造成这个报错的应该是问题1，参考issue： https://github.com/umijs/qiankun/issues/1588 https://github.com/umijs/qiankun/issues/299
