### ISSUE TITLE
[Feature Request]当获取子项目entry出错时，增加重试次数

### ISSUE THREAD

**Issue by wukong1995** [umijs/qiankun#261]
## Background

获得子项目的entry时，得到404或者500的页面，除非主动刷新页面，那么在主项目存活期间，子项目一直是404或500

## Proposal

在获得entry file的时候，假如出错的情况，增加重试机制。

**Comment by xiezhongfu** [comment]
**这个还挺有意思的**
我在 jupyterlab 的前端代码里看到有类似的机制，参考的是 aws 的实现。针对微前端的话应该需要考虑这几个问题，欢迎拍砖，欢迎补充。
- 重试的机制需要把应用是否处于激活结合起来
- 还需要处理应用间切换的时候重试机制的拉起和暂停或销毁，以及切换的过程中怎么取消/中断一些网络请求

**Comment by kuitos** [comment]
registerMicroApps api 的第三个参数，可以传入一个自定义的 fetch 来实现这个能力。

不过也可以考虑 qiankun 直接支持。

**Comment by xlldll** [comment]
easily show this error:
error occurs while executing the entry //xx.com/js/xx.js
