### ISSUE TITLE
Ant Design Pro 子应用无法正确跳转

### ISSUE THREAD

**Issue by oulp** [umijs/qiankun#262]
### 🐛 bug 描述

主应用是用Ant Design Pro搭建，使用插件umi-plugin-qiankun。
根据 https://github.com/umijs/umi-plugin-qiankun 配置主应用，运行正常无错误，但子应用无法跳转
 

### 💻 复现代码

测试代码： https://github.com/oulp/antd-qiankun

```
config.ts

[
    '@umijs/plugin-qiankun',
    {
      master: {
        apps: [
          {
            name: '设备',
            entry: 'http://localhost:8001/device',
            base: '/device',
            mountElementId: 'root-subapp-container',
          },
        ],
        defer: true,
        jsSandbox: true,
        prefetch: true,
      },
    },
  ]
```
### © 版本信息

- Ant Design Pro 版本: [ 4.0.0]
- umi 版本
- 浏览器环境 [chrome]
- 开发环境 [mac OS]

**Comment by kuitos** [comment]
提供完整的可复现仓库，只有一个配置无法定位问题

**Comment by oulp** [comment]
> 提供完整的可复现仓库，只有一个配置无法定位问题

谢谢，代码 https://github.com/oulp/antd-qiankun

**Comment by oulp** [comment]
@kuitos 谢谢，代码 https://github.com/oulp/antd-qiankun

**Comment by Deturium** [comment]
> @kuitos 谢谢，代码 https://github.com/oulp/antd-qiankun

你的子应用在哪里？

**Comment by oulp** [comment]
> > @kuitos 谢谢，代码 https://github.com/oulp/antd-qiankun
> 
> 你的子应用在哪里？

**Comment by oulp** [comment]
> > @kuitos 谢谢，代码 https://github.com/oulp/antd-qiankun
> 
> 你的子应用在哪里？

子应用不是随便做个就行，现在的问题是点击菜单正常会有个子应用请求，现在是请求没发起

**Comment by kuitos** [comment]
给可复现的仓库，不然无法定位问题

**Comment by oulp** [comment]
> 给可复现的仓库，不然无法定位问题

谢谢，子应用：https://github.com/oulp/antd-qiankun-slave.git

**Comment by Deturium** [comment]
你在[这里]( https://github.com/oulp/antd-qiankun/blob/master/config/config.ts#L66) 开启了 `defer`配置
当该配置开启的时候，需要使用 `import { qiankunStart } from 'umi'` api 通知 qiankun 启动

具体的看 [文档](https://github.com/umijs/umi-plugin-qiankun#masteroptions)

**Comment by oulp** [comment]
> 你在[这里](https://github.com/oulp/antd-qiankun/blob/master/config/config.ts#L66) 开启了 `defer`配置
> 当该配置开启的时候，需要使用 `import { qiankunStart } from 'umi'` api 通知 qiankun 启动
> 
> 具体的看 [文档](https://github.com/umijs/umi-plugin-qiankun#masteroptions)

正常加载了，但页面上半部分显示404，然后子应用的内容在页面下面正常显示。
也增加了subAppContainer页面，代码已提交，请帮查看下，谢谢！

**Comment by oulp** [comment]
> 你在[这里](https://github.com/oulp/antd-qiankun/blob/master/config/config.ts#L66) 开启了 `defer`配置
> 当该配置开启的时候，需要使用 `import { qiankunStart } from 'umi'` api 通知 qiankun 启动
> 
> 具体的看 [文档](https://github.com/umijs/umi-plugin-qiankun#masteroptions)

正常加载了。 
点击子应用时，页面上面显示umi development 404 page，下面显示正常的子应用内容。根据文档在主应用也增加了subAppContainer页面。
代码已提交，请帮查看下，谢谢！

**Comment by oulp** [comment]
已解决，谢谢！
