### ISSUE TITLE
SnapshotSandbox在active期间delete属性问题

### ISSUE THREAD

**Issue by cdLVV** [umijs/qiankun#2629]
https://github.com/umijs/qiankun/blob/afb92ed64d10c0e5d5734c98a4b89f343078da32/src/sandbox/snapshotSandbox.ts#L58C25-L58C25

```
inactive() {
    this.modifyPropsMap = {};

    iter(window, (prop) => {
      if (window[prop] !== this.windowSnapshot[prop]) {
        // 记录变更，恢复环境
        this.modifyPropsMap[prop] = window[prop];
        window[prop] = this.windowSnapshot[prop];
      }
    });

    if (process.env.NODE_ENV === 'development') {
      console.info(`[qiankun:sandbox] ${this.name} origin window restore...`, Object.keys(this.modifyPropsMap));
    }

    this.sandboxRunning = false;
  }
```
如果在active期间delete了window上的某个属性，由于inactive时，是遍历的window，是遍历不到被删除的属性的，所以也不会记录到变更的对象上，也不会还原快照上原属性。

这里是否有问题。还是说故意设计的

**Comment by wanghangit** [comment]
这个问题提了一个pr来修 https://github.com/umijs/qiankun/pull/2869
### legacyProxySanbox的问题
发现legacyProxySanbox有另外一个delete引起的问题，原因如下：
Proxy没有定义deleteProperty方法，删除会默认删除fakeWindow上的值，导致子应用中的delete功能失效，由于不被推荐是否还需要兼容

**Comment by kuitos** [comment]
legacyProxySanbox 不用兼容了
