### ISSUE TITLE
[Bug]chrome 老版本无法加载子应用

### ISSUE THREAD

**Issue by fringesoft** [umijs/qiankun#263]
## What happens?

基于VUE开发的子应用，在最新的Chrome版本上运行正常，目前发现Chrome 49.0.2623.112上加载子应用失败，控制台报错信息如下：
`You need to export the functional lifecycles in app1 entry`

以下为子应用导出的生命周期钩子函数
```
export async function bootstrap(props) {
  console.log("bootstrap", props);
}

export async function mount({ data = {} } = {}) {
  router = new VueRouter({
    base: window.__POWERED_BY_QIANKUN__ ? "/app1/" : "/",
    mode: "hash",
    routes
  });
  instance = new Vue({
    router,
    store,
    render: h => h(App, { props: data })
  }).$mount("#app");
}
export async function unmount() {
  console.log("挂载后");
  instance.$destroy();
  instance = null;
  router = null;
}
```

## 最小可复现仓库

内部项目暂无法提供

## 复现步骤，错误日志以及相关配置

主应用跳转子应用时

## 相关环境信息

- **qiankun 版本** 1.3.14
- **浏览器版本**：Chrome 49.0.2623.112
- **操作系统**：windows7

**Comment by fringesoft** [comment]
import-html-entry中的utils.js中采用for/in遍历查找子模块入口对象的处理，可能因为不同游览器对for/in遍历返回顺序不一致造成子应用加载失败。

**Comment by kuitos** [comment]
解决方案
https://qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by tdida** [comment]
@kuitos 
使用 @umijs/plugin-qiankun
在 Chrome 49 环境下
同样报错 You need to export the functional lifecycles in callout entry
