### ISSUE TITLE
[Bug]子应用的样式加载异常

### ISSUE THREAD

**Issue by leechar-lcn** [umijs/qiankun#264]
qiankun版本：1.3.14
谷歌浏览器：80.0.3987.100（正式版本） （64 位）
操作系统：win10 专业版

问题描述：子应用在使用 mini-css-extract-plugin 抽离样式的时候，qiankun 把样式当成 fetch 请求处理，而不是 stylesheet 请求。导致样式没有插入到页面中去。目前我用 style-loader 把样式都抽离到了 html 里解决了问题，但是这样的话，样式就不能异步加载了。

**Comment by kuitos** [comment]
这个应该不会， @Deturium  看下？

**Comment by Deturium** [comment]
我尝试了 mini-css-extract-plugin，并没有出现你描述的情况

可以给一下复现例子吗？

**Comment by kuitos** [comment]
closed via inactive

**Comment by oufeng** [comment]
用最新版还是遇到了这个问题，怎么就关闭了？
