### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by xiaoYangHAHAHA** [umijs/qiankun#2645]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?
  

  react子应用，index 异步导入   发生```You need to export lifecycle functions in xxx entry```
  确定的是我的配置应该是没问题的，当我手动修改 ```entry``` 为 ``` bootstrp ```后，此刻是正常的
## 最小可复现仓库
https://github.com/xiaoYangHAHAHA/qiankun-example/tree/master/sub-react/src
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
将index.js 重命名为 bootstrap.js，同时创建index.js
```
// index.ts 
import('./bootstrat')
```

## 相关环境信息

- **qiankun 版本*2.10.13 *
- **浏览器版本*116.0.5845.110 *：
- **操作系统*macOS 13.4.1 *：

**Comment by kuitos** [comment]
你可能需要学习一下 esm 模块的原理，这里 index.ts 只有一个 import 的话，对于 index.ts 本身而言，是没有任何导出的。

如果 bootstrap 里有 lifecycles 的话，这样改一下应该就行：
```js
export * from './bootstrap'
```

**Comment by xiaoYangHAHAHA** [comment]
抱歉，可能是我没有描述清楚错误发生的真正原因
我是按图在进行操作  关键代码如下 

但当我将boorstrap.tsx 重命名为 index.ts，将入口文件替换后结果就一切正常了


<img width="974" alt="image" src="https://github.com/umijs/qiankun/assets/61615010/978cdb48-6bf6-4b10-b1eb-597ecf4e82a9">

```js.
  // bootstrap.tsx
import './public-path'
import React from 'react'
import ReactDom from 'react-dom/client'
import App from './App'
import { Provider } from 'react-redux'
import { store } from './store'

function render() {
  const root = ReactDom.createRoot(
    document.getElementById('root') as HTMLElement
  )
  root.render(
    <Provider store={store}>
      <App />
    </Provider>
  )
}

if (!(window as any).__POWERED_BY_QIANKUN__) {
  render()
}

export async function bootstrap() {
  console.log('react app bootstraped')
}

export async function mount(props: any) {
  console.log('props:::：', props)
  render()
}

export async function unmount() {
  const root = ReactDom.createRoot(
    document.getElementById('root') as HTMLElement
  )
  root.unmount()
  // ReactDOM.unmountComponentAtNode(document.getElementById('root'))
}

export async function update(props: any) {
  console.log('update props', props)
}
```
```js 
  // index.ts
    import('./bootstrap)
```

**Comment by xiaoYangHAHAHA** [comment]
很抱歉，是我的描述不够清晰
是使用了``` webpack5 ``` MF  , 改造后的 index.ts 如下，但还是会发生 ```You need to export lifecycle functions in xx entry```

```
版本信息
    "webpack": "^5.88.2",
    "qiankun": "^2.10.13",
```

```   
//. index.ts

const { bootstrap, mount, unmount, update } = await import('./bootstrap')

export { bootstrap, mount, unmount, update }
```

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/issues/2256#issuecomment-1700295457

**Comment by xiaoYangHAHAHA** [comment]
非常感谢您的回复
