### ISSUE TITLE
子应用如何获取自己的window对象

### ISSUE THREAD

**Issue by qmlqmlqml** [umijs/qiankun#2658]
我的子应用有引用第三方的很多个js文件，这个文件里面写了很多挂在在window的方法，单独启用没有问题，但是放进微应用后，我的window对象获取不到这些变量和方法，导致相关功能无法使用。但是我又不可能吧所有的js文件都在主应用里面引入，那样子应用单独运行时还要引入一遍，请问有没有什么好的解决办法

**Comment by shanchuan1** [comment]
@kuitos 大佬,这个问题求解答
