### ISSUE TITLE
[Bug]文档拼写错误

### ISSUE THREAD

**Issue by wangronglei** [umijs/qiankun#2659]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

https://qiankun.umijs.org/zh/faq

最近更新的文档拼写错误

如图：

<img width="1382" alt="image" src="https://github.com/umijs/qiankun/assets/13018762/da4baaed-8ffe-4a72-b7b2-f3d5d388f486">

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by aladdin-add** [comment]
fixed by https://github.com/umijs/qiankun/pull/2662.
