### ISSUE TITLE
single-spa minified message #31

### ISSUE THREAD

**Issue by dorseysen** [umijs/qiankun#2660]
## What happens?

We Use the plug-in vite-plugin-qiankun to manually register the Qiankun route. The code is as follows:

【plugins】：vite-plugin-qiankun
```js
const appInstance = createApp({xxx})
renderWithQiankun({
  mount(props){
    render(props)
  },
  bootstrap(){},
  unmount(props){
    appInstance?.unmount()
  },
  update(){}
})
```

An error is reported when the route is switched to another service.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.7.4
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/2469#issuecomment-1518961397

**Comment by shuwenjunn** [comment]
try to unmount the sub app before leave the sub app worked to me.
