### ISSUE TITLE
子应用单独跑时可以热更新，在主应用中跑失效

### ISSUE THREAD

**Issue by cs-storm** [umijs/qiankun#2667]
已经有参考过此 issue ： https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643。
该 issue 中的解决方法对我来说不适用。
主应用：vue 2.6.10
子应用：react 17.0.2

子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求
子应用跑于父应用时：ws成功建立，端口正确，代码变更时无额外请求

**Comment by mjnd1** [comment]
> 已经有参考过此 issue ： [https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643。](https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643%E3%80%82) 该 issue 中的解决方法对我来说不适用。 主应用：vue 2.6.10 子应用：react 17.0.2
> 
> 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时无额外请求

看看子应用和父应用的端口号是否配置了

我的问题是：

主应用：react 18.2.0
子应用：react 18.2.0

子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求
子应用跑于父应用时：ws成功建立，端口正确，代码变更时有额外请求

然后调试了一下，发现是子应用没有触发 react-dom 的更新操作，导致子应用的热更新失败。

**Comment by cs-storm** [comment]
> > 已经有参考过此 issue ： [https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643。](https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643%E3%80%82) 该 issue 中的解决方法对我来说不适用。 主应用：vue 2.6.10 子应用：react 17.0.2
> > 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时无额外请求
> 
> 看看子应用和父应用的端口号是否配置了
> 
> 我的问题是：
> 
> 主应用：react 18.2.0 子应用：react 18.2.0
> 
> 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时有额外请求
> 
> 然后调试了一下，发现是子应用没有触发 react-dom 的更新操作，导致子应用的热更新失败。



> > 已经有参考过此 issue ： [https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643。](https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643%E3%80%82) 该 issue 中的解决方法对我来说不适用。 主应用：vue 2.6.10 子应用：react 17.0.2
> > 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时无额外请求
> 
> 看看子应用和父应用的端口号是否配置了
> 
> 我的问题是：
> 
> 主应用：react 18.2.0 子应用：react 18.2.0
> 
> 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时有额外请求
> 
> 然后调试了一下，发现是子应用没有触发 react-dom 的更新操作，导致子应用的热更新失败。

我们的问题一样，react-dom 没有触发更新操作，端口号是否配置是指？你通过配置端口号解决问题了吗？

**Comment by mjnd1** [comment]
> > > 已经有参考过此 issue ： [https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643。](https://github.com/umijs/qiankun/issues/1428#issuecomment-862891643%E3%80%82) 该 issue 中的解决方法对我来说不适用。 主应用：vue 2.6.10 子应用：react 17.0.2
> > > 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时无额外请求
> > 
> > 
> > 看看子应用和父应用的端口号是否配置了
> > 我的问题是：
> > 主应用：react 18.2.0 子应用：react 18.2.0
> > 子应用单独跑时： ws 成功建立，代码变更时有 hot-update.js 请求 子应用跑于父应用时：ws成功建立，端口正确，代码变更时有额外请求
> > 然后调试了一下，发现是子应用没有触发 react-dom 的更新操作，导致子应用的热更新失败。
> 
> 我们的问题一样，react-dom 没有触发更新操作，端口号是否配置是指？你通过配置端口号解决问题了吗？

子应用有端口号的，比如我的子应用，端口号是 30002，而主应用是 30000，我在子应用的 .env 文件中配置了 WDS_SOCKET_PORT = 30002，这样子应用代码变更时有 hot-update.js 请求，但是子应用的热更新还是失败的。

具体的原因可能需要看一下 react-dom 的具体实现了。

**Comment by cs-storm** [comment]
在配置端口后出现了 hot-update.json ，但确实还没有子应用的热更新

**Comment by mjnd1** [comment]
> 在配置端口后出现了 hot-update.json ，但确实还没有子应用的热更新

不同情况具体的原因，只知道 react-dom 的 scheduleRefresh （热更新）函数没有执行。导致子应用没有热更新成功。

**Comment by york-chen** [comment]
@mjnd1  你好，请问找到为什么react-dom为啥没有执行了吗，我也是一路打断点，跟踪到qiankun源码，发现热更新文件生成的函数执行了，但是这个函数里面的函数组件没有更新，没有头绪了

**Comment by mjnd1** [comment]
> @mjnd1 你好，请问找到为什么react-dom为啥没有执行了吗，我也是一路打断点，跟踪到qiankun源码，发现热更新文件生成的函数执行了，但是这个函数里面的函数组件没有更新，没有头绪了

暂时不清楚原因，你仔细找找看，为什么函数组件更新。

**Comment by york-chen** [comment]
@mjnd1 我今天早上跟踪了一下webpack热更新的时候会执行入口文件
但是当执行到
if (!window.__POWERED_BY_QIANKUN__) {
    mountApp({});
  }
let appinstance:Root
function mountApp(props:any){
    const { container } = props;
    appinstance = createRoot(container ? container.querySelector('#app'):document.querySelector('#app')!)
    appinstance.render(<RouteConfig />)
}

由于是主系统访问的，这个mountApp函数不会被调用，但是如果是单独访问就会执行，然后走reactDom的逻辑，感觉qiankun是不是应该再搞一个生命周期函数，这样就可以调用渲染逻辑了

**Comment by york-chen** [comment]
/* global __react_refresh_library__ */

const safeThis = require('core-js-pure/features/global-this');
const RefreshRuntime = require('react-refresh/runtime');
console.log('我是子应用的 reactRefreshEntry')
if (process.env.NODE_ENV !== 'production') {
  if (typeof safeThis !== 'undefined') {
    //这个地方将__reactRefreshInjected改为__reactRefreshInjected_sub，即可注册react-refresh的热更新逻辑
    --var $RefreshInjected$ = '__reactRefreshInjected';
    ++var $RefreshInjected$ = '__reactRefreshInjected_sub';
    // Namespace the injected flag (if necessary) for monorepo compatibility
    if (typeof __react_refresh_library__ !== 'undefined' && __react_refresh_library__) {
      $RefreshInjected$ += '_' + __react_refresh_library__;
    }
    console.log(safeThis[$RefreshInjected$])
    console.log(window[$RefreshInjected$])
    // Only inject the runtime if it hasn't been injected
    if (!safeThis[$RefreshInjected$]) {
      // Inject refresh runtime into global scope
      console.log('我是子应用的 reactRefreshEntry')
      RefreshRuntime.injectIntoGlobalHook(safeThis);

      // Mark the runtime as injected to prevent double-injection
      safeThis[$RefreshInjected$] = true;
    }
  }
}

调整 @umijs/react-refresh-webpack-plugin/client/ReactRefreshEntry.js文件，即可开启子系统的热更新
原因是主系统注册react-refresh相关逻辑的时候设置了safeThis[$RefreshInjected$] = true;等到子系统去访问的时候，沙盒机制逻辑让他读取到了真正的window上的这个属性，导致没有注册上
至于怎么调整合适，看自己了

**Comment by 1111mp** [comment]
> /* global **react_refresh_library** */
> 
> const safeThis = require('core-js-pure/features/global-this'); const RefreshRuntime = require('react-refresh/runtime'); console.log('我是子应用的 reactRefreshEntry') if (process.env.NODE_ENV !== 'production') { if (typeof safeThis !== 'undefined') { //这个地方将__reactRefreshInjected改为__reactRefreshInjected_sub，即可注册react-refresh的热更新逻辑 --var RefreshInjected = '__reactRefreshInjected'; ++var RefreshInjected = '__reactRefreshInjected_sub'; // Namespace the injected flag (if necessary) for monorepo compatibility if (typeof **react_refresh_library** !== 'undefined' && **react_refresh_library**) { RefreshInjected += '_' + **react_refresh_library**; } console.log(safeThis[$RefreshInjected$]) console.log(window[$RefreshInjected$]) // Only inject the runtime if it hasn't been injected if (!safeThis[$RefreshInjected$]) { // Inject refresh runtime into global scope console.log('我是子应用的 reactRefreshEntry') RefreshRuntime.injectIntoGlobalHook(safeThis);
> 
> ```
>   // Mark the runtime as injected to prevent double-injection
>   safeThis[$RefreshInjected$] = true;
> }
> ```
> 
> } }
> 
> 调整 @umijs/react-refresh-webpack-plugin/client/ReactRefreshEntry.js文件，即可开启子系统的热更新 原因是主系统注册react-refresh相关逻辑的时候设置了safeThis[$RefreshInjected$] = true;等到子系统去访问的时候，沙盒机制逻辑让他读取到了真正的window上的这个属性，导致没有注册上 至于怎么调整合适，看自己了

根据这里的内容，我目前是这么解决的：
每个应用的webpack配置中通过webpack.DefinePlugin定义全局变量
```ts
// your project name
import { name } from '../package.json';

new webpack.DefinePlugin({
	'process.env.APP_NAME': JSON.stringify(name),
}),
```
然后更改 `node_modules\@pmmmwh\react-refresh-webpack-plugin\client\ReactRefreshEntry.js`内容如下：
```js
/* global __react_refresh_library__ */

const safeThis = require('core-js-pure/features/global-this');
const RefreshRuntime = require('react-refresh/runtime');

if (process.env.NODE_ENV !== 'production') {
  if (typeof safeThis !== 'undefined') {
    // 这里拼上 process.env.APP_NAME 来做隔离 确保每个子应用都会注册上热更
    var $RefreshInjected$ = '__reactRefreshInjected_' + process.env.APP_NAME + "_";
    // Namespace the injected flag (if necessary) for monorepo compatibility
    if (typeof __react_refresh_library__ !== 'undefined' && __react_refresh_library__) {
      $RefreshInjected$ += '_' + __react_refresh_library__;
    }
		
    // Only inject the runtime if it hasn't been injected
    if (!safeThis[$RefreshInjected$]) {
      // Inject refresh runtime into global scope
      RefreshRuntime.injectIntoGlobalHook(safeThis);

      // Mark the runtime as injected to prevent double-injection
      safeThis[$RefreshInjected$] = true;
    }
  }
}
```
然后子应用热更新就会生效了
