### ISSUE TITLE
[Task] 配套的 UI Library（React 版本）

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#2677]
提供 `MicroApp` 组件，方便用户更快速使用，如 umi plugin 提供的模式：

```js
import { MicroApp } from 'umi';

export default function Page() {
  return <MicroApp name="app1" />;
}
```

1. React 版本直接复用 umi plugin 的实现即可 https://github.com/umijs/umi/blob/master/packages/plugins/libs/qiankun/master/MicroApp.tsx
2. Vue 版本需要新写一个，这两个部分逻辑应该可以抽出来复用
3. 其他技术栈先不考虑

**Comment by kuitos** [comment]
@gaopeng0108 这个我改成 React 版本实现了，Vue 版本的我单独建一个

**Comment by gaopeng0108** [comment]
> @gaopeng0108 这个我改成 React 版本实现了，Vue 版本的我单独建一个

好的，我先理解一下这个任务。我看 qiankun 有搞成 monorepo 的计划，是希望 MicroApp 的使用不和 umi 绑定，单独放在 qiankun 仓库里给用户使用吗？

**Comment by kuitos** [comment]
是的。你切到 next 分支
