### ISSUE TITLE
[Task] 配套的 UI Library（Vue 版本）

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#2689]
ref #2677

应该可以有一部分逻辑是共用的？

**Comment by LadyChatterleyLover** [comment]
这个是单独提供一个组件还是单独新建一个工程来写呢？

**Comment by kuitos** [comment]
是个单独的包 https://github.com/umijs/qiankun/tree/next/packages/ui-bindings/vue

**Comment by linghaoSu** [comment]
hi,  @kuitos 希望能够认领这个任务

**Comment by kuitos** [comment]
欢迎，https://github.com/umijs/qiankun/discussions/2688 这里报个名并看下参与要求 @linghaoSu

**Comment by qiYuei** [comment]
@linghaoSu 加下微信 qiYuein  拉你进群
