### ISSUE TITLE
inline script should not add sourceURL

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#2694]
![image](https://github.com/umijs/qiankun/assets/5206843/7ed3b1ac-fe8a-4434-80fc-cffc972159f7)

**Comment by wanghangit** [comment]
这里我有一个疑问，sourceMap应该加载的是map.js文件，而这里的实现逻辑拼接的是src或者baseURL，好像不能起到调试的作用。
这里的本意是想在with语句执行报错可以映射到加载的原文件中吗，如果是这样的话baseUrl换成entry是不是更合理些，而不是删掉

**Comment by kuitos** [comment]
sourceURL 是为了报错时 Chrome source 能跳到正确的外链 js，不是用来做 sourcemap 的，内联的 script 则没有这个问题

**Comment by wanghangit** [comment]
> sourceURL 是为了报错时 Chrome source 能跳到正确的外链 js，不是用来做 sourcemap 的，内联的 script 则没有这个问题

这里有一个疑问，如果entry中的外链执行报错需要跳转到外链js，那子应用的内联js报错是不是也应该跳转到子应用的htmlEntry文件。
还有我看目前下测试用例比较少，我是在这个pr中增加上下游的测试用例，还是只测我这一个方法就好了
