### ISSUE TITLE
ie 兼容性问题

### ISSUE THREAD

**Issue by ChasLui** [umijs/qiankun#27]
我跑examples 在 ie 11 浏览器无法正常访问, 并且我看到代码中有用到 proxy, 请问对于 ie 是否有兼容计划

**Comment by kuitos** [comment]
暂无计划，pr is welcome

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/wiki/FAQ#does-qiankun-compatible-with-ie

**Comment by letmeknowhow** [comment]
仍然无计划？
