### ISSUE TITLE
@qiankunjs/shared 和 @qiankunjs/sandbox 相互依赖

### ISSUE THREAD

**Issue by bravepg** [umijs/qiankun#2701]
## 问题描述
@qiankunjs/shared 和 @qiankunjs/sandbox 之间有个相互依赖，导致子包拓扑关系没有正确识别，所以在 build 的时候没有办法按照依赖顺序正确构建

## 代码

![image](https://github.com/umijs/qiankun/assets/22069371/2c6d91b6-cd2f-477d-b76e-7d6292c7b627)

**Comment by kuitos** [comment]
resolved
