### ISSUE TITLE
[Feature Request] 主应用可否自定义全局前缀？

### ISSUE THREAD

**Issue by Billyas** [umijs/qiankun#2708]
## Background

需求场景，需要将主应用部署在 example.com/mainproject  路径下。

## Proposal

我使用Vue的config  `publicPath：  /mainproject/` 进行尝试时，发现无法正常加载微应用。

## Additional context

1. 请问`qiankun` 框架是否支持这种全局前缀的配置？
2. 如果不支持，请告知原因谢谢。

**Comment by hellolukeding** [comment]
如果是webpack的话，webpack proxy里面配置一下
```javascript
        pathRewrite: {
          '^subapp': ''
        }
```

**Comment by gongshun** [comment]
主应用在非根目录是可以的，需要修改 activeRule，在前面加上主应用的访问前缀，例如：`/app1` => `/mainproject/app1`，同时，如果子应用是history路由，需要修改路由 base
