### ISSUE TITLE
https://qiankun.umijs.org/ 官网无法访问

### ISSUE THREAD

**Issue by sdtazhanghe** [umijs/qiankun#2713]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

https://qiankun.umijs.org/ 官网无法访问

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

https://qiankun.umijs.org/ 官网无法访问

## 复现步骤，错误日志以及相关配置

输入网址并访问

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by aladdin-add** [comment]
![image](https://github.com/umijs/qiankun/assets/13050025/976ad054-3103-4cc3-a860-3edd4e60a2da)


看着是正常的啊。可以打开/关闭网络代理再试试，如果还出现的话，请提供报错的具体内容。

**Comment by kuitos** [comment]
现在应该好了，Vercel 的服务器国内访问有点不稳定
