### ISSUE TITLE
[Feature Request] 关闭js沙箱依然是可以支持css隔离等hijack的？

### ISSUE THREAD

**Issue by wufeng87** [umijs/qiankun#273]
## Background
目前的做法是，关闭沙箱后，所有hijack都没法使用了，包括css隔离、副作用处理。

## Proposal
我的想法是，在关闭沙箱时，只是不支持js隔离，依然是可以支持hijack。
部分修改的代码截图如下：
![image](https://user-images.githubusercontent.com/1686808/75738743-01562600-5d3e-11ea-92ea-e172ff9323b0.png)
![image](https://user-images.githubusercontent.com/1686808/75738790-1af76d80-5d3e-11ea-82e2-358b9287756a.png)

不知道这样改动会有其他问题吗？谢谢。

**Comment by kuitos** [comment]
沙箱的设计目的就是隔离副作用，关闭沙箱还能让一些隔离机制生效，这个设计语义上有点前后矛盾。

**Comment by wufeng87** [comment]
ok, 谢谢。目前我是想在ie11上运行，所以自己这么改动并测试下。
