### ISSUE TITLE
重新挂载子应用报错 「SKIP_BECAUSE_BROKEN」

### ISSUE THREAD

**Issue by lfzs** [umijs/qiankun#2735]
## What happens?
1、基座激活 micro-a 应用
2、卸载 micro-a， 激活 micro-b 应用
3、卸载 micro-b，再次激活 micro-a 应用（报错）
![image](https://github.com/umijs/qiankun/assets/20108480/af66c991-c8d3-4b81-a8d4-c534d5d1a79a)
```
loadApp.ts:107 Uncaught TypeError: application 'micro-a' died in status SKIP_BECAUSE_BROKEN: Cannot read properties of null (reading 'firstChild')
```

## Mini Showcase Repository(REQUIRED)

可复现仓库：https://github.com/lfzs/qiankun-rc-vite/tree/main

## How To Reproduce

查看 README.md 步骤

## Context

- **qiankun Version**: 3.0.0-rc.5
- **Platform Version**:  Mac 
- **Browser Version**: Chrome 版本 118.0.5993.70（正式版本） (x86_64)

**Comment by lfzs** [comment]
@bravepg 您好，请问什么时候能修复呢？

**Comment by bravepg** [comment]
![image](https://github.com/umijs/qiankun/assets/22069371/ce5aae84-3836-4ec5-8c98-6f70cb59758c)

qiankun 2.0 把节点挂载到了用户指定的节点下，然后做了 gc 和 dom 的重建工作
![image](https://github.com/umijs/qiankun/assets/22069371/a6982bb4-bac7-4a8c-be5d-58e05fdd02d1)

============
![image](https://github.com/umijs/qiankun/assets/22069371/502ffd02-75ad-4705-b4a4-f45e2d592dea)
qiankun 3.0 直接复用了 dom 节点，然后做了 gc。
![image](https://github.com/umijs/qiankun/assets/22069371/9e74f3cb-e73f-4121-b09d-2e4e130d4aaa)


有两种改法：
1. 跟 2.0 保持一致，将 qiankun 挂载到用户指定的节点，增加 gc 和 dom 重建代码
2. 保持现有模式，直接移除 gc 代码即可。

个人觉得第一种更合理，你觉得呢 @kuitos

**Comment by kuitos** [comment]
3.0 也是做了重建了
![image](https://github.com/umijs/qiankun/assets/5206843/2ebeefb4-f77e-42fb-806a-8d4cbdc475ef)

看来是这段代码有点 bug

**Comment by bravepg** [comment]
3.0.0-rc.9，已经解决
