### ISSUE TITLE
[Bug]升级 1.4.0 版本报错

### ISSUE THREAD

**Issue by xiaoiver** [umijs/qiankun#274]
## What happens?

升级到 1.4.0 后出现如下报错，1.3.x 版本是 OK 的：
```
[qiankun]: odc-sql-console wrapper with id __qiankun_subapp_wrapper_for_odc_sql_console__ not ready!
```

猜测可能和 https://github.com/umijs/qiankun/pull/257 有关？
不太确定是否是我之前的用法（主应用配置）不正确导致。

## 最小可复现仓库

主应用为阿里云 XConsole 项目。
子应用为 Umi/Bigfish 项目，使用了 `umi-qiankun-slave` 插件。

## 复现步骤，错误日志以及相关配置

主应用配置如下：
```javascript
entry: {
  styles: [
    'xxx.css',
  ],
  scripts: [
    'xxx.js',
  ],
  html: `<html>
    <head>
      <link rel="stylesheet" href="xxx.css">
    </head>
    <body>
      <div id="root-slave"></div>
      <script src="xxx.js"></script>
    </body>
  </html>`
},
```

## 相关环境信息

- **qiankun 版本** 1.4.0
- **浏览器版本**：Chrome
- **操作系统**：Mac

**Comment by kuitos** [comment]
released v1.4.1
