### ISSUE TITLE
主应用中跳转路由（都是子应用的activeRule的路径），子应用总是先卸载再加载

### ISSUE THREAD

**Issue by 776725893** [umijs/qiankun#2748]
# 提问之前强烈建立您能先阅读一下[《如何正确的提出一个 Issue》](https://github.com/umijs/qiankun/issues/1115)

## What happens?

父应用在加载子应用后，在父应用的tabs栏跳转，子应用总是先卸载又安装。
子应用为vue-cli配置的vue3框架
比如子应用的activeRule为/sub-cost
父亲应用从/sub-cost/1 去往 /sub-cost/2
微应用还是会卸载。目前排查到的原因是去往/sub-cost/2的时候
activeRule的pathname为1导致返回的false，组件卸载
![image](https://github.com/umijs/qiankun/assets/95426999/09aa20e3-220d-4900-8c47-2ed1d2b09a75)
![1697973236962](https://github.com/umijs/qiankun/assets/95426999/8ace5d88-04d8-4cce-85e7-5dfc2566875e)

## 最小可复现仓库  
github地址：
https://github.com/776725893/qiankun-err-demo

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**2.10.11
- **浏览器版本**：谷歌浏览器118.0.5993.89
- **操作系统**：win10/win11

**Comment by 776725893** [comment]
子应用使用官方vue3的demo也会有这个问题，但是子应用是vue2的目前不会出现该问题

**Comment by 776725893** [comment]
@bravepg  大佬能帮忙看看嘛

**Comment by bravepg** [comment]
> @bravepg 大佬能帮忙看看嘛

ok 我看看

**Comment by kuitos** [comment]
这个好像是 vue3 的 bug？ @gongshun

**Comment by bravepg** [comment]
![image](https://github.com/umijs/qiankun/assets/22069371/1a1f0a41-3429-4856-81bb-90ed60c77df9)

看起来是主应用和子应用的路由实例冲突了，如果我直接 pushState 的话是 ok 且也会执行两次


![image](https://github.com/umijs/qiankun/assets/22069371/caf7bcc4-9b98-4de4-bd9d-5ec52ac86064)

**Comment by 776725893** [comment]
https://github.com/umijs/qiankun/issues/1865
是vue-router4的问题。根据这个回答在beforeEach里面的配置暂时解决了。
![image](https://github.com/umijs/qiankun/assets/95426999/54fdd018-e8eb-4542-aea8-1f53d3c2eaef)

**Comment by sir-ran** [comment]
> #1865 是vue-router4的问题。根据这个回答在beforeEach里面的配置暂时解决了。 ![image](https://user-images.githubusercontent.com/95426999/277528629-54fdd018-e8eb-4542-aea8-1f53d3c2eaef.png)

怎么解决的啊，感觉就是vue-router4的原因。

**Comment by 776725893** [comment]
> > #1865 是vue-router4的问题。根据这个回答在beforeEach里面的配置暂时解决了。 ![image](https://user-images.githubusercontent.com/95426999/277528629-54fdd018-e8eb-4542-aea8-1f53d3c2eaef.png)
> 
> 怎么解决的啊，感觉就是vue-router4的原因。

我是根据这个回答在beforeEach中配置解决的
https://github.com/umijs/qiankun/issues/1865#issuecomment-1702231908

**Comment by 776725893** [comment]
使用上述解决方案后出现，浏览器返回时，url拼接的参数丢失。对别人的代码做出改正后正常。
`
let current: any = window.location.pathname.split("/");
        if (current[1] === current[2]) {
          current = current.slice(2);
          current = current.join("/");
          current = current.startsWith("/") ? current : "/" + current;
          current += window.location.search + window.location.hash;
          history.replaceState(
            {
              back: from.fullPath,
              current:
                window.location.pathname +
                window.location.search +
                window.location.hash,
            },
            String(to.name),
            current
          );
        } else {
          history.replaceState(
            {
              back: from.fullPath,
              current:
                window.location.pathname +
                window.location.search +
                window.location.hash,
            },
            String(to.name),
            ""
          );
        }
`

**Comment by qq1332783374** [comment]
我这边 vue3应用 在销毁的时候执行 router.options.history.destory 方法 可以完美解决跨应用跳转问题
![企业微信截图_17018524103208](https://github.com/umijs/qiankun/assets/35019188/4b867cd6-7336-4a90-b756-f5406ff906ec)

**Comment by 776725893** [comment]
> 我这边 vue3应用 在销毁的时候执行 router.options.history.destory 方法 可以完美解决跨应用跳转问题 ![企业微信截图_17018524103208](https://private-user-images.githubusercontent.com/35019188/288347733-4b867cd6-7336-4a90-b756-f5406ff906ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTUzMzMsIm5iZiI6MTcwMTg1NTAzMywicGF0aCI6Ii8zNTAxOTE4OC8yODgzNDc3MzMtNGI4NjdjZDYtNzMzNi00YTkwLWI3NTYtZjU0MDZmZjkwNmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjhlZjVjMWM4MzVlY2YxOWUzZmU1Y2JjZGZjN2I1MTZlMDZhMDVmNTBjZWZlMjVhYjBiOTBjMjhiZWRkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dR4SaZrx0I6KmZX9kLY_WapiMO52Xw9y2Y919-899Y)

感觉不太对呢，demo是同一应用切换一直会卸载=>加载。按理来说切换是不会执行卸载操作的，所以你这段代码是不会执行的

**Comment by LeonGong** [comment]
终极解决办法：（父级子级都是history）：
//历史记录完善 父级应用路由守卫添加
    history.replaceState({ back: from.path }, to.name as string, '')
    if (!window.history.state.current) window.history.state.current = to.fullPath
    if (!window.history.state.back) window.history.state.back = from.fullPath

**Comment by hotWater-me** [comment]
昆明开幕
，，，，，
