### ISSUE TITLE
[Feature Request] 想请问下RoadMap何时发布？

### ISSUE THREAD

**Issue by zp2359** [umijs/qiankun#276]
Parcel apps integration (multiple sub apps displayed at the same time, but only one uses router at most)
 Communication development kits between master and sub apps
 Nested Microfrontends

想请问下，这三个特性，什么时候能发布呢？业务急需。 前几天2.0发布了，但是很快就回滚了。

**Comment by kuitos** [comment]
3 月底会发布，可以 watch repo 关注 release 信息
