### ISSUE TITLE
[Feature Request] waf 会自动注入一个js，但是乾坤加载的时候报错

### ISSUE THREAD

**Issue by OldKing-lion** [umijs/qiankun#2769]
## Background

目前项目使用的是angular&vue&qiankun,最近线上测试的时候发现页面上打印了一个错误，导致页面无法正确加载ctrl+f5后正常。在我调试代码的时候发现，是_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=7&cb=414815996这个东西引起的。请问有办法解决吗，我们是云服务，也没办法不使用这个。

## Proposal

希望处理一下代码，在JZ这个方法里判断一下，如果不是字符串，应该e.src.startsWith
![image](https://github.com/umijs/qiankun/assets/13028615/cc2a71ee-e23f-4c9b-9bce-36722c45b02f)

**Comment by OldKing-lion** [comment]
当我服务器开启waf的时候，会自动生成一个注入的脚本，类似/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=7&cb=414815996，这个时候qiankun js加载的时候会报个错误，e.startsWith is not a function 好像是和上面那个脚本有关系，ctr+f5后正常，请问怎么解决这个问题

**Comment by OldKing-lion** [comment]
> Hello @OldKing-lion. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox](https://codesandbox.io/) or clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples) to your GitHub repository.
> 
> 你好 @OldKing-lion, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox](https://codesandbox.io/) 或直接 clone [qiankun examples](https://github.com/umijs/qiankun/tree/master/examples)，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

提供不了。因为只有开启了waf的服务器才会有这个问题。开发环境和不开启WAF的环境是没有这个问题的。不过你可以看下我最开始发的那张图，那是我断点定位到的代码。

**Comment by kuitos** [comment]
只有一个截图没办法判断是什么原因导致的，可以本地起个 node 模拟一下 waf 的行为

**Comment by OldKing-lion** [comment]
> 只有一个截图没办法判断是什么原因导致的，可以本地起个 node 模拟一下 waf 的行为

![image](https://github.com/umijs/qiankun/assets/13028615/0809808b-0201-4328-ad51-027af0f6f1bc)
我发现我这个js是标记了async的，为什么没有被正确处理？
![image](https://github.com/umijs/qiankun/assets/13028615/516a7570-dd6e-4be4-ad1c-09f1c5b15ca9)
我使用的版本：
![image](https://github.com/umijs/qiankun/assets/13028615/161429c5-fd12-4d96-9750-3b0f77ae2744)

**Comment by OldKing-lion** [comment]
@kuitos  帮忙看下

**Comment by kuitos** [comment]
确保都装的最新版本，只有截图没有复现的话只能靠猜了😑

**Comment by OldKing-lion** [comment]
> 确保都装的最新版本，只有截图没有复现的话只能靠猜了😑

最新版也不行。在加载子应用的时候就报错. excludeAssetFilter都没执行. 看了import-html-entry的代码，也确实有判断async标记的脚本。我现在在想怎么不让waf插入的脚本应该qiankun的加载

**Comment by kuitos** [comment]
qiankun 跟 import-html-entry 实际安装的什么版本，发出来看看

**Comment by OldKing-lion** [comment]
知道为什么了，问题在import-html-entry这个包里。
首先是_getExternalScripts方法：这个方法的return里，判断scripts里的元素是不是string,是string，返回string，不是string,组装对象返回，代码如下：
// for prefetch
function _getExternalScripts(scripts) {
  var fetch = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : defaultFetch;
  var fetchScript = function fetchScript(scriptUrl, opts) {
    return scriptCache[scriptUrl] || (scriptCache[scriptUrl] = fetch(scriptUrl, opts).then(function (response) {
      // usually browser treats 4xx and 5xx response of script loading as an error and will fire a script error event
      // https://stackoverflow.com/questions/5625420/what-http-headers-responses-trigger-the-onerror-handler-on-a-script-tag/5625603
      if (response.status >= 400) {
        throw new Error("".concat(scriptUrl, " load failed with status ").concat(response.status));
      }
      return response.text();
    }));
  };
  return Promise.all(scripts.map(function (script) {
    if (typeof script === 'string') {
      if (isInlineCode(script)) {
        // if it is inline script
        return (0, _utils.getInlineCode)(script);
      } else {
        // external script
        return fetchScript(script);
      }
    } else {
      // use idle time to load async script
      var src = script.src,
        async = script.async,
        crossOrigin = script.crossOrigin;
      var fetchOpts = crossOrigin ? {
        credentials: 'include'
      } : {};
      if (async) {
        return {
          src: src,
          async: true,
          content: new Promise(function (resolve, reject) {
            return (0, _utils.requestIdleCallback)(function () {
              return fetchScript(src, fetchOpts).then(resolve, reject);
            });
          })
        };
      }
      return fetchScript(src, fetchOpts);
    }
  }));
}
然后在调用的时候，用到getExecutableScript方法，该方法里有个判断是不是内联脚本的isInlineCode方法：如下图，如果_getExternalScripts返回的内容是对象，isInlineCode方法的参数也是对象，那code.startsWith肯定会报错，因为startsWith是string对象的方法。

![image](https://github.com/umijs/qiankun/assets/13028615/97b71a93-0eb1-4b3c-bd1c-b6311e427999)
![image](https://github.com/umijs/qiankun/assets/13028615/ec4e8fc9-482a-4326-afcc-4858c10c26f6)

大佬@kuitos 您看下我分析的是否有问题，如果没有问题，您能否打个patch？

**Comment by OldKing-lion** [comment]
我是没有复现，因为我比较菜，你们的examples我没跑起来，我也不会用nodejs模仿waf的行为。但是我经过调试和翻阅import-html-entry的包，发现了这个问题。你们可以验证一下。这个解决了，也是对框架的一个完善。
![image](https://github.com/umijs/qiankun/assets/13028615/aef06221-74f0-467b-b5f7-c5b22c382752)

**Comment by OldKing-lion** [comment]
> qiankun 跟 import-html-entry 实际安装的什么版本，发出来看看

现在qiankun是v2.10.14
 import-html-entry是v1.15.1

**Comment by bravepg** [comment]
> _getExternalScripts

这里应该不是根因，这个只是 async 标识，后面对 async 标识会有不同的处理
![image](https://github.com/umijs/qiankun/assets/22069371/092be692-d4ac-457c-acf3-84408f5272a0)

**Comment by OldKing-lion** [comment]
> > _getExternalScripts
> 
> 这里应该不是根因，这个只是 async 标识，后面对 async 标识会有不同的处理 ![image](https://user-images.githubusercontent.com/22069371/279307871-092be692-d4ac-457c-acf3-84408f5272a0.png)

我调试了线上的代码，抛出异常的地方就是isInlineCode方法

**Comment by bravepg** [comment]
或者你可以把调用栈给截图放出来...

**Comment by OldKing-lion** [comment]
调试代码执行顺序：
![image](https://github.com/umijs/qiankun/assets/13028615/c177a125-7336-47bd-a3e3-be40418dc4aa)
![image](https://github.com/umijs/qiankun/assets/13028615/4c8f6863-9e4e-48ed-a7ae-0b9f38bc9c00)
![image](https://github.com/umijs/qiankun/assets/13028615/54cc713e-405d-4ca4-9ec5-241b0598176f)
![image](https://github.com/umijs/qiankun/assets/13028615/df60dee7-4dc8-4ebf-99ba-29c8c19473b9)

**Comment by OldKing-lion** [comment]
> > > _getExternalScripts
> > 
> > 
> > 这里应该不是根因，这个只是 async 标识，后面对 async 标识会有不同的处理 ![image](https://user-images.githubusercontent.com/22069371/279307871-092be692-d4ac-457c-acf3-84408f5272a0.png)
> 
> 你这段代码我有看到，但是没看到有执行，好像是在一个schedule的方法里调用

**Comment by bravepg** [comment]
![image](https://github.com/umijs/qiankun/assets/22069371/b9f8390e-2ea1-4cd8-b7bc-61ca31e06419)
你这个都是作用域变量，不是调用栈。截这个
![image](https://github.com/umijs/qiankun/assets/22069371/734a961f-2878-4000-9d9c-ddcfa4401829)

**Comment by OldKing-lion** [comment]
![image](https://github.com/umijs/qiankun/assets/13028615/a8b606b7-054a-4fa6-a8dd-57f5223e2dd5)
![image](https://github.com/umijs/qiankun/assets/13028615/2d0f50a9-6527-4944-b7b8-7cc24553883e)
![image](https://github.com/umijs/qiankun/assets/13028615/ad96c32e-3f2e-4a1b-8ea5-79875d74368a)
![image](https://github.com/umijs/qiankun/assets/13028615/f7be1269-edbb-464b-b3c9-8fe2a715457e)
我其实前面特意截的变量，堆栈信息不太清楚吧

**Comment by OldKing-lion** [comment]
![image](https://github.com/umijs/qiankun/assets/13028615/0ff5cba1-acd0-4a3b-9f8a-64a50777b8d4)

**Comment by bravepg** [comment]
你能看下你的 entry 是个啥么？
![image](https://github.com/umijs/qiankun/assets/22069371/efa4f8e5-5e29-47a5-8ff9-32f392afaf4e)

**Comment by OldKing-lion** [comment]
> 你能看下你的 entry 是个啥么？ ![image](https://user-images.githubusercontent.com/22069371/279338867-efa4f8e5-5e29-47a5-8ff9-32f392afaf4e.png)

https://domain/subdomain/index.html

**Comment by OldKing-lion** [comment]
> 你能看下你的 entry 是个啥么？ ![image](https://user-images.githubusercontent.com/22069371/279338867-efa4f8e5-5e29-47a5-8ff9-32f392afaf4e.png)
我代码里的entry是 https://domain/subdomain/index.html
断点调试，这里我晚点看下

**Comment by OldKing-lion** [comment]
因为waf生成的这个东西不是一直都有，如果我浏览器ctrl+f5就没了，也就不会报错了。所以现在我看不到错误了，晚点我要更新一下，更新后第一次加载，就会有这个错误

**Comment by OldKing-lion** [comment]
最终去掉了注入，解决

**Comment by ken1987** [comment]
我也遇到这个问题，是因为 vue-cli 配置了 crossorigin: 'use-credentials'，去掉就正常了

**Comment by cwj540858520** [comment]
这问题还是没解决啊。。。想复现的话在子项目的index.html手动加一个async的script标签就会出现这个错误。

**Comment by FreeIess** [comment]
问题依然存在，复现场景是子应用index.html的最后一个script标签为外链标签，且带有async或crossorigin标识，此时在解析时会将该资源标记为entry，带有async/crossorigin标识的script标签会被处理为一个对象而不是src字符串，因此执行startsWith方法时报错，导致页面无法访问

<img width="872" height="391" alt="Image" src="https://github.com/user-attachments/assets/fa2770e8-8208-44b2-8fdb-ae8f1fbf2031" />

<img width="929" height="508" alt="Image" src="https://github.com/user-attachments/assets/ef4da956-15dc-458a-a095-b9378787bce8" />

<img width="946" height="359" alt="Image" src="https://github.com/user-attachments/assets/ea979898-d685-4a44-8b2f-cc8270cd2e49" />

<img width="926" height="182" alt="Image" src="https://github.com/user-attachments/assets/892f0aa0-a2d8-470b-b231-df0fe1b5d891" />

**Comment by FreeIess** [comment]
@OldKing-lion  请reopen此问题😂😂😂
