### ISSUE TITLE
[Bug]demo中导航来回切换几次后，添加到dom的css隔离失效了

### ISSUE THREAD

**Issue by seanuu** [umijs/qiankun#279]
## What happens?
v1.4.2 中附带的demo中导航来回切换几次后，添加到dom的css隔离失效了，所有子应用js加载的样式都插入到了主应用的head中

## 复现步骤，错误日志以及相关配置
![pic](https://user-images.githubusercontent.com/25326568/75782408-da2d4200-5d99-11ea-8e9a-85f9a939f5fe.png)

**Comment by peterzhai** [comment]
您好,我现在使用的是qiankun2.2.1,子应用的样式还是添加到子应用下，子应用一旦删除，再添加时，样式就不会再新增了，请问如何解决？
