### ISSUE TITLE
[Bug] webpack-plugin 单测 ci 上无法运行

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#2795]
ref https://github.com/umijs/qiankun/pull/2794#discussion_r1384679545

复现步骤：
1. 这里 script 改为 test https://github.com/umijs/qiankun/blob/next/packages/webpack-plugin/package.json#L11
2. 项目根目录执行 npm test

会发现卡在了 webpack build 环节

**Comment by kuitos** [comment]
@nayonglin cc

**Comment by nayonglin** [comment]
> @nayonglin cc

#2800
