### ISSUE TITLE
如何使用nextjs当做子应用接入乾坤？

### ISSUE THREAD

**Issue by zoudingyi** [umijs/qiankun#2820]
## What happens?

目前我使用vue3构建了qiankun主应用，目前想接入一个nextjs项目当做子应用，但是不知道在哪里配置生命周期，nextjs使用的最新14版本，并且使用App Router。

## 相关环境信息

- **qiankun 版本**：2.10.13
- **浏览器版本**：Chrome 119.0.6045.124
- **操作系统**：Windows

**Comment by zhangwuyang-github** [comment]
same question

**Comment by sqlnice** [comment]
据我了解的信息，目前微前端框架没有支持 Next.js App Router 模式的
