### ISSUE TITLE
app1: Application 'app1' died in status LOADING_SOURCE_CODE

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#283]
## What happens?
主应用配置
![image](https://user-images.githubusercontent.com/13429648/75802547-d7414a00-5db7-11ea-82ff-0def7a7b7b60.png)
layout:
![image](https://user-images.githubusercontent.com/13429648/75802870-68182580-5db8-11ea-8b22-d680e9c2f2af.png)

子应用基于umijs生基础测试项目
截图165行这里去render dom节点root-sub在我的项的layout里，刷新浏览器报找不到这个dom元素
报错截图：
![image](https://user-images.githubusercontent.com/13429648/75802931-8b42d500-5db8-11ea-8588-1e45cfc30a07.png)

registerMicroApps注册app，activeRule匹配会执行render,layout还没执行registerMicroApps render 已在执行了
还是我这样去配置本身存在问题？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
容器节点是你自己提供的，你需要确保 render 方法被调用的时候节点是已经 ready 的。
可以通过在 beforeLoad、beforeMount 这些钩子里添加一些钩子来确保顺序，或者等节点 ready 了再启动 qiankun。
