### ISSUE TITLE
左侧菜单来回切换主应用和子应用，子应用卸载完成以后不加载主应用了

### ISSUE THREAD

**Issue by caojide** [umijs/qiankun#2830]
![6a1502e815b5f232683763cbcf1a712](https://github.com/umijs/qiankun/assets/25580735/e02a3032-6bef-4d2a-8c61-4383cb0be13d)

**Comment by caojide** [comment]
附上左侧菜单的跳转方法

**Comment by daigang1228** [comment]
遇到同样问题，求解决方法
