### ISSUE TITLE
[Bug]examples中的angular9子项目不能单独运行

### ISSUE THREAD

**Issue by kaichen87** [umijs/qiankun#284]
examples中的angular9子项目不能单独运行

extra-webpack.config.js中使用
const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options);
时会出现该问题

**Comment by Deturium** [comment]
应该是跟  `zone.js` 的 external 配置有关

**Comment by kuitos** [comment]
单独运行时不配置 external 即可

**Comment by kaichen87** [comment]
const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options);
这段配置的作用是什么

**Comment by Deturium** [comment]
> const singleSpaWebpackConfig = singleSpaAngularWebpack(angularWebpackConfig, options);
> 这段配置的作用是什么

其实这个去掉项目也是能跑的，这个配置是 `single-spa-angular` 导出的一些 webpack 配置，详情可以看这里：
https://github.com/single-spa/single-spa-angular/blob/master/src/webpack/index.ts
