### ISSUE TITLE
子应用动态添加的样式在第三次进入的时候会丢失

### ISSUE THREAD

**Issue by iwyvi** [umijs/qiankun#285]
## What happens?

子应用动态添加的样式在第三次进入的时候会丢失。
挂载子应用时正常，第一次切出去再切回来正常，再重复这个操作时就会丢失子应用样式

目测是 https://github.com/umijs/qiankun/pull/282 这次提交带来的 bug

https://github.com/umijs/qiankun/blob/ef812d993c883d75edbfa015419c72b545bbc42f/src/hijackers/dynamicHeadAppend.ts#L175

这里使用了 `rawAppendChild` ，导致在新一轮 sandbox 的 mount 执行sideEffectsRebuildersAtMounting rebuild 时添加的 style 没有进入上面 hijack 的 appendChild 里，因此新的一轮里 `dynamicStyleSheetElements` 为空，此后重新进入子应用后就不再重新添加样式了。

## 复现方式

当前项目内给 `vue` 示例的 `About.vue` 页面中加一句样式，重复切换子应用即可复现

## Context

- **qiankun Version**: 1.4.3
- **Platform Version**: MacOS 10.15.3
- **Browser Version**: Microsoft Edge 82.0.443.0

**Comment by tdida** [comment]
@kuitos 

看了1.4.3 包的代码，还未修复这个问题
- qiankun Version: 1.4.3

![image](https://user-images.githubusercontent.com/18672870/76051051-8773a600-5fa4-11ea-8795-ce72a3337080.png)

**Comment by kuitos** [comment]
released v1.4.4

**Comment by xiaoLus** [comment]
@kuitos 
2.0版 还是出现这个问题（v2.0.25 ）

**Comment by xuehaoyu** [comment]
最新版本还是有这个问题 react
