### ISSUE TITLE
[Bug]资源加载出错然后换一个entry, 但是name不变的话, 不会再次请求新资源

### ISSUE THREAD

**Issue by zWingz** [umijs/qiankun#2854]
## What happens?

我们希望通过`loadMicroApp`加载资源A时, 假如资源加载失败, 比如: cdn问题或者cos问题, 会回退到另一个备份地址,然后重新加载插件. 阅读源码发现在通过`loadMicroApp`加载时, 会把`name`+`containerXPath`作为key缓存下来.  https://github.com/umijs/qiankun/blob/master/src/apis.ts#L148. 所以如果我只改`entry`, 是不会重新加载, 还必须把`name`也改了才行.

所以这里是不是要做下`catch`处理? 如果异常了,则把缓存也销毁了
或者直接用`name` +`entry` 作为缓存的`key`

## 复现步骤，错误日志以及相关配置

- 加载一个404的资源, 失败后
- 修改entry重新加载

## 相关环境信息

- **qiankun 版本** 2.10.16
- **浏览器版本**：
- **操作系统**：

**Comment by Arima-s** [comment]
我还遇到个问题，如果子应用某个路由对应页面报错了， 切换到 当前子应用的其他路由， 子应用的页面也不会渲染....

**Comment by hello-astar** [comment]
@kuitos 求修复v2版本
