### ISSUE TITLE
[RFC] 关于沙箱隔离的一点想法

### ISSUE THREAD

**Issue by seanuu** [umijs/qiankun#286]
## 思路

> 把子应用的代码在对应创建的 iframe 中执行，不需要特殊处理的上下文方法或属性代理到顶层上下文处理，需要特殊处理上下文方法改在 iframe 中修改后再代理出去，这样隔离处理会不会好一些

**Comment by kuitos** [comment]
不错的想法，但是这个方案问题还是很多的。
主要是子应用的 js 里不单只有逻辑计算，还有各种副作用，比如 js 里需要对 url 做一个变更（跳转），js 里做一个弹框等等。本质上这个方案跟直接用 iframe 做嵌入是没有区别的，那 iframe 的问题你就需要再去解决了。

**Comment by seanuu** [comment]
let iframe = document.createElement('iframe');
iframe.style.display = 'none';
document.body.appendChild(iframe);

let iframeWin = iframe.contentWindow;
iframeWin.name = 'iframeWin';
window.name = 'window';

let iframeProxy =  new Proxy(iframeWin, {
    get: function (target, propKey, receiver) {
        return Reflect.get(window, propKey, receiver);
    }
    // ...
});

// 子应用创建 挂载
let appModule = function app() {
    console.log(location);
    console.log(name);

    let div = document.createElement('div');
    div.innerText = 'test';
    document.body.appendChild(div);

    name = 'appModule';
    console.log(window.name);

    setTimeout(() => {
        document.body.removeChild(div);
    }, 1000)
};
let code = `(${appModule.toString()})()`;

iframeProxy.eval(code);

**Comment by seanuu** [comment]
检测了一下，这样操作的话在 iframe 环境运行代码，全局属性方法会从主应用window中找，设置iframe的全局属性，不会污染到主应用，设置后的全局属性在 iframe 环境也还能找到

**Comment by seanuu** [comment]
好像还有很多问题，无视这个想法吧

**Comment by kuitos** [comment]
欢迎各种方案或想法上的交流😀

**Comment by coveychen95** [comment]
hey bro. 你的想法实现了！参见腾讯[wujie](https://wujie-micro.github.io/doc/guide/#%E6%97%A0%E7%95%8C%E6%96%B9%E6%A1%88)前端方案

**Comment by gyk-123** [comment]
solute ！

**Comment by aique127** [comment]
腾讯应该给你一份offer

**Comment by supuwoerc** [comment]
solute ！

**Comment by Lu-xiao-hang** [comment]
good nice
