### ISSUE TITLE
子应用正常加载，页面上也显示了，但是控制台有一个报错

### ISSUE THREAD

**Issue by viviprprpr** [umijs/qiankun#288]
## What happens?

umi-plugin-qiankun，子应用正常加载，页面上也显示了，entry也有值，但是控制台有一个报错

![image](https://user-images.githubusercontent.com/40267580/75982852-6e2a1580-5f22-11ea-9086-9127d92fd956.png)

## Context

- **@umijs/plugin-qiankun Version**:  ^1.5.0
- **Browser Version**:  Google Chrome 80.0.3987.122

**Comment by kuitos** [comment]
提供一个可复现的仓库

**Comment by kuitos** [comment]
closed via inactive
