### ISSUE TITLE
为什么qiankun@2.3.6版本处理文件ArrayBuffer耗时是2.10.16版本的4倍？

### ISSUE THREAD

**Issue by Pasoul** [umijs/qiankun#2884]
## What happens?
我有一个主应用root和子应用app1，在app1子应用的App.vue里有一段代码，逻辑是将fileRender读取到的文件ArrayBuffer转换成二进制字符串，问题在于qiankun@2.3.6版本，一个27MB的视频文件转换耗时大概在16秒（正常耗时的四倍），在qiankun@2.10.16版本转换耗时是4秒（这个时间是正常的）。在2.3.6版本基础上，独立访问app1微应用，转换耗时也是4秒（这个时间也是正常的）。
```
function convertUint8ArrayToBinaryString(u8Array) {
  let i
  const len = u8Array.length
  let bStr = ''
  for (i = 0; i < len; i++) {
    bStr += String.fromCharCode(u8Array[i])
  }

  return bStr
}

const fileReader = new FileReader()
fileReader.readAsArrayBuffer(files[0])
const _startTime = Date.now()
fileReader.onload = () => {
  console.log('开始转换');
  const fileReaderResult = fileReader.result
  // 核心逻辑是这里，问题也出在这里，在2.3.6版本转换耗时很长
  const bytes = new window.Uint8Array(fileReaderResult)
  convertUint8ArrayToBinaryString(bytes)
  console.log('转换结果耗时', Date.now() - _startTime)
}
```

## Mini Showcase Repository(REQUIRED)

https://github.com/Pasoul/qiankun-demo

## How To Reproduce

**Steps to reproduce the behavior:**
1. 打开仓库地址，分别启动主应用root和子应用app1
2. app1 页面上添加文件，文件是仓库里的一个视频
![image](https://github.com/umijs/qiankun/assets/22902187/6487695e-2911-45c3-950b-40bb3c1a4a25)
3.查看控制台打印的耗时，此时应该是16秒左右
![image](https://github.com/umijs/qiankun/assets/22902187/ef6a9b53-f2ce-44ce-bbca-24cb21670a2b)
4.独立访问微应用app1，添加文件，查看控制台打印的耗时，此时应该是4秒左右
![image](https://github.com/umijs/qiankun/assets/22902187/9d6ec830-4318-4e26-a408-99d1f8c1f401)
5.root应用安装qiankun@2.10.16版本，然后再重复上述流程，发现不管是独立运行子应用还是在主应用环境下，耗时都是4秒

**Expected behavior** 
1. 想知道为什么2.3.6版本会存在耗时长的问题，为什么2.10.16版本解决了这个问题？

## Context

- **qiankun Version**: 2.3.6
- **Platform Version**: MacOS 12.2.1
- **Browser Version**: Chrome 版本 117.0.5938.132

**Comment by Pasoul** [comment]
经过反复对比确认，2.9.0以下qiankun版本均有此问题，2.9.0版本 此问题不存在

**Comment by Pasoul** [comment]
问题解决了，在子应用访问全局变量String时，在全局缓存一个String变量
```
const { String } = window
function convertUint8ArrayToBinaryString(u8Array) {
  let i
  const len = u8Array.length
  let bStr = ''
  for (i = 0; i < len; i++) {
    bStr += String.fromCharCode(u8Array[i])
  }

  return bStr
}
```

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/pull/2271
