### ISSUE TITLE
主应用切换菜单路由第二次加载时子应用scirpt标签内代码不执行

### ISSUE THREAD

**Issue by zjy850984598** [umijs/qiankun#2887]
## What happens?

子应用为原生java-web项目，第一次启动页面加载正常，主应用切换菜单路由第二次加载时子应用scirpt标签内代码不执行

## 项目配置
主项目
<img width="633" alt="image" src="https://github.com/umijs/qiankun/assets/45356080/1b7086fc-dc6c-43d1-acfa-a0b36961ca39">

子应用
<img width="561" alt="image" src="https://github.com/umijs/qiankun/assets/45356080/70074dcb-a979-49ab-90d3-a92a2f2a7305">
<img width="955" alt="image" src="https://github.com/umijs/qiankun/assets/45356080/7322be0e-31c5-479a-acc7-a99fe2a261ed">

## 复现操作
<img width="383" alt="image" src="https://github.com/umijs/qiankun/assets/45356080/0ad4a661-9e7d-4ece-a128-b860aca9ad19">
点击菜单切换

## 相关环境信息

"qiankun": "^2.10.16",
<img width="731" alt="image" src="https://github.com/umijs/qiankun/assets/45356080/dc8dcbb3-49d9-4aee-b243-2d05b970c16b">

**Comment by gongshun** [comment]
再次加载时，只会执行 mount 生命周期函数

**Comment by zjy850984598** [comment]
> 再次加载时，只会执行 mount 生命周期函数

好的 感谢。 已找到解决方法。

**Comment by zjy850984598** [comment]
> > 再次加载时，只会执行 mount 生命周期函数
> 
> 好的 感谢。 已找到解决方法。

@gongshun 抱歉，打扰了。 方法还是不行。 怎么能让子应用每次都重新加载load呢。 子应用是老项目jsp，现在的话第一次加载没问题。第二次脚本和css就不执行了。使用loadMicroApp也不行。使用 #830 提供的方法也不行

**Comment by gongshun** [comment]
> @gongshun 抱歉，打扰了。 方法还是不行。 怎么能让子应用每次都重新加载load呢。 子应用是老项目jsp，现在的话第一次加载没问题。第二次脚本和css就不执行了。使用loadMicroApp也不行。使用 #830 提供的方法也不行

使用手动加载控制，然后每次加载时给子应用换个 name 应该就可以了

**Comment by Yearning-Free-Life** [comment]
你好，你的jsp项目是怎么集成进去的呢
