### ISSUE TITLE
[Bug] 代码安全扫描不通过；

### ISSUE THREAD

**Issue by liumemgmei** [umijs/qiankun#2897]
# 当服务器配置 Content-Security-Policy "default-src 'self'"时候， 页面加载不出来，加了'unsafe-eval'， 安全扫描就不通过；

如果能解决这个问题， 我们愿意有偿。感谢您的查阅！

**Comment by bravepg** [comment]
https://github.com/umijs/qiankun/issues/1302

**Comment by bravepg** [comment]
在 qiankun3.0 中可以解决这个问题，你可以用个 rc 版本试下？https://github.com/umijs/qiankun/tree/v3.0.0-rc.3

预计不久会推出正式版
