### ISSUE TITLE
想咨询下3.0中图中这两个部分在哪里能看到，是否有示例

### ISSUE THREAD

**Issue by xiao-qi-l** [umijs/qiankun#2898]
![image](https://github.com/umijs/qiankun/assets/81614723/8e212826-50be-4e01-870f-3140f4d77e3d)
1.沙箱支持配置访问的全局变量代理有使用示例吗？
2.沙箱实现不再依赖 eval，在哪里的源码能够体现出来(想学习看看)，我看import-import-html-entry中还是使用eval执行子应用代码的？

**Comment by bravepg** [comment]
切换到 next 分支可以查看，https://github.com/umijs/qiankun/tree/next

**Comment by Rockergmail** [comment]
@xiao-qi-l 我也在next分支看不到没用eval。但是release说的是沙箱的实现，我也对比了2.x的3种sandbox本身也没有直接用eval，只是在execScripts时有用到eval。
