### ISSUE TITLE
react version conflicts. Can qiankun improve its version dependence on react

### ISSUE THREAD

**Issue by xiaofeihui** [umijs/qiankun#2906]
npm install start =======================================================================
 npm ERR! code ERESOLVE
 npm ERR! ERESOLVE could not resolve
 npm ERR! 
 npm ERR! While resolving: @umijs/plugin-qiankun@2.41.0
 npm ERR! Found: react@17.0.2
 npm ERR! node_modules/react
 npm ERR!   react@"^17.0.0" from the root project
 npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @ahooksjs/use-request@2.8.15
 npm ERR!   node_modules/@ahooksjs/use-request
 npm ERR!     @ahooksjs/use-request@"^2.0.0" from @umijs/plugin-request@2.6.0
 npm ERR!     node_modules/@umijs/plugin-request
 npm ERR!       @umijs/plugin-request@"2.6.0" from @umijs/preset-react@1.8.12
 npm ERR!       node_modules/@umijs/preset-react
 npm ERR!         dev @umijs/preset-react@"1.8.12" from the root project
 npm ERR!   93 more (@ant-design/icons, @ant-design/pro-descriptions, ...)
 npm ERR! 
 npm ERR! Could not resolve dependency:
 npm ERR! peer react@"16" from @umijs/plugin-qiankun@2.41.0
 npm ERR! node_modules/@umijs/plugin-qiankun
 npm ERR!   dev @umijs/plugin-qiankun@"^2.41.0" from the root project
 npm ERR! 
 npm ERR! Conflicting peer dependency: react@16.14.0
 npm ERR! node_modules/react
 npm ERR!   peer react@"16" from @umijs/plugin-qiankun@2.41.0
 npm ERR!   node_modules/@umijs/plugin-qiankun
 npm ERR!     dev @umijs/plugin-qiankun@"^2.41.0" from the root project
 npm ERR! 
 npm ERR! Fix the upstream dependency conflict, or retry
 npm ERR! this command with --force or --legacy-peer-deps
 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
 npm ERR! 
 npm ERR! 
 npm ERR! For a full report see:
 npm ERR! /van_cache/npm/_logs/2024-02-18T09_52_34_158Z-eresolve-report.txt
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /van_cache/npm/_logs/2024-02-18T09_52_34_158Z-debug-0.log

**Comment by kuitos** [comment]
@umijs/plugin-qiankun 更新到最新版本
