### ISSUE TITLE
antd 主子应用样式覆盖问题

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#295]
## What happens?
![image](https://user-images.githubusercontent.com/13429648/76165979-2d3a3700-6196-11ea-938b-ba73fbf229ab.png)
按照文档我配置了本地项目预期是修改项目antd 样式添加前缀

根据文档修改如下：
![image](https://user-images.githubusercontent.com/13429648/76166020-522eaa00-6196-11ea-8058-acb7283de484.png)

预览css 文件是成功修改成了ant11,设计用到的组件如button classNme 还是ant 所以导致没有了样式？
1.常见问题说的增加样式全局配置，是修改ant-prefix这个变量吧
2.我还需要修改什么配置吗？找了一圈没找到相关的文档说明？求帮助

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
https://ant.design/components/config-provider/#API

**Comment by xileliu** [comment]
非常感谢，还是文档上的疏忽

**Comment by zjscy666** [comment]
ant-prefix这个是ant design的前缀？
