### ISSUE TITLE
本地调试子应用没有热更新

### ISSUE THREAD

**Issue by 21duxue** [umijs/qiankun#2965]
子应用和主应用都是用的react，构建工具是webpack5.0

脚手架内部用的热更新插件是

 "webpack-dev-middleware": "5.2.2",
 "webpack-hot-middleware": "2.25.1",

子应用更新后，单独打开是可以更新的，但是在主应用的loadMicroApp下，不触发热更新。
也没有在主应用窗口下发现加载hot-update.json,以及hot-update.js

有没有对于webpack-hot-middleware做适配呀，或者需要怎么处理一下？？？

## 相关环境信息

- **qiankun 版本**：2.7.2
- **浏览器版本**：谷歌
- **操作系统**：MAC

**Comment by chen-jieyi** [comment]
提主有解决这个问题吗？
