### ISSUE TITLE
qiankun在子应用页面刷新后在切换子应用的其他页面报错Uncaught Error: [qiankun]: Wrapper element for xxx is not existed!

### ISSUE THREAD

**Issue by HLDipsy** [umijs/qiankun#2976]
背景：
     主应用引入了一个子应用的三个页面，在主应用页面，无论刷新还是怎么样进入都是正常的，子应用页面也是正常访问的

问题：
      在子应用的页面刷新后，在切换子应用其他的页面会就会报错 Uncaught Error: [qiankun]: Wrapper element for xxx is not existed!
还会把生命周期中的数据 里的name也就是子应用的name 修改为 原name+_1

**Comment by Reeyc** [comment]
解决了吗

**Comment by wh1teYu** [comment]
解决了吗 请问 @HLDipsy
