### ISSUE TITLE
error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".

### ISSUE THREAD

**Issue by ZiSeFeng** [umijs/qiankun#298]
Arguments: 
  /usr/local/bin/node /usr/local/lib/node_modules/yarn/bin/yarn.js run start:vue

PATH: 
  /var/folders/7s/bp7g9rf17_7829rmwkrwmgjr0000gn/T/yarn--1583720352714-0.3726914850885128:/Users/maqin/test/react/qiankun/node_modules/.bin:/Users/maqin/.config/yarn/link/node_modules/.bin:/usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools

Yarn version: 
  1.22.0

Node version: 
  12.16.1

Platform: 
  darwin x64

Trace: 
  Error: EISDIR: illegal operation on a directory, read

npm manifest: 
  {
    "name": "qiankun",
    "version": "1.4.5",
    "description": "An completed implementation of Micro Frontends",
    "keywords": [
      "micro frontend",
      "microfrontend",
      "micro frontends",
      "micro-frontend",
      "micro-frontends",
      "microservice"
    ],
    "main": "./lib/index.js",
    "module": "./es/index.js",
    "types": "./es/index.d.ts",
    "sideEffects": false,
    "scripts": {
      "examples:install": "npm-run-all --serial build install:*",
      "examples:start": "npm-run-all --parallel start:*",
      "install:main": "cd examples/main && yarn",
      "start:main": "cd examples/main && yarn start",
      "install:react16": "cd examples/react16 && yarn",
      "start:react16": "cd examples/react16 && yarn start",
      "install:react15": "cd examples/react15 && yarn",
      "start:react15": "cd examples/react15 && yarn start",
      "install:vue": "cd examples/vue && yarn",
      "start:vue": "cd examples/vue && yarn start",
      "install:angular9": "cd examples/angular9 && yarn",
      "start:angular9": "cd examples/angular9 && yarn serve:qiankun",
      "build": "father-build",
      "release": "np --no-cleanup --yolo --no-publish",
      "prepublishOnly": "yarn lint && yarn build",
      "lint": "yarn lint:js && yarn lint:prettier",
      "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
      "lint:fix": "yarn lint:js -- --fix",
      "lint:prettier": "check-prettier lint",
      "prettier": "prettier -c --write **/*",
      "docs:dev": "vuepress dev docs",
      "docs:build": "vuepress build docs",
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "repository": {
      "type": "git",
      "url": "git+https://github.com/kuitos/qiankun.git"
    },
    "files": [
      "dist",
      "es",
      "lib"
    ],
    "author": "Kuitos",
    "license": "MIT",
    "bugs": {
      "url": "https://github.com/kuitos/qiankun/issues"
    },
    "homepage": "https://github.com/kuitos/qiankun#readme",
    "dependencies": {
      "@babel/runtime": "^7.5.5",
      "import-html-entry": "^1.4.1",
      "lodash": "^4.17.11",
      "single-spa": "^4.4.3",
      "tslib": "^1.10.0"
    },
    "devDependencies": {
      "@types/lodash": "^4.14.129",
      "@types/vfile-message": "1.x",
      "@umijs/fabric": "^1.1.10",
      "@vuepress/plugin-google-analytics": "^1.2.0",
      "@vuepress/plugin-pwa": "^1.2.0",
      "babel-plugin-import": "^1.12.1",
      "check-prettier": "^1.0.3",
      "concurrently": "^4.1.2",
      "father-build": "^1.7.0",
      "husky": "^2.3.0",
      "lint-staged": "^9.4.2",
      "np": "^5.0.3",
      "npm-run-all": "^4.1.5",
      "prettier": "^1.18.2",
      "rimraf": "^3.0.0",
      "typescript": "^3.4.5",
      "vuepress": "^1.2.0"
    },
    "husky": {
      "hooks": {
        "pre-commit": "lint-staged"
      }
    },
    "lint-staged": {
      "**/*.{js,ts,json,css,md}": [
        "yarn prettier",
        "git add"
      ],
      "**/*.{js,ts}": [
        "yarn lint:fix",
        "git add"
      ]
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

**Comment by ZiSeFeng** [comment]
`yarn examples:start` 命令行输入后，报error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".
如果是进入每个子项目的时候，就是打开

**Comment by kuitos** [comment]
请按照 issue 模板提交问题
