### ISSUE TITLE
Uncaught Error: Iframe has not been created yet

### ISSUE THREAD

**Issue by yejunhong** [umijs/qiankun#299]
创建了test，test1 两个路由，切换test1在切换test，test内容获取不到内容，
还产生了
1、Uncaught Error: Iframe has not been created yet
2、WebSocket connection to 'ws://127.0.0.1:7099/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200
仓库：https://github.com/yejunhong/qiankun

**Comment by Deturium** [comment]
你路由选取的不好，test 是 test1 的 prefix

当你的路由从 test1 切换到 test 的时候，两个子应用是同时激活的，冲突了

**Comment by kuitos** [comment]
https://github.com/yejunhong/qiankun/blob/master/micro/index.js#L6 导致两个应用都返回了 true

**Comment by yejunhong** [comment]
@Deturium 原来是路由和name冲突，已解决，多谢

**Comment by yejunhong** [comment]
> 你路由选取的不好，test 是 test1 的 prefix
> 
> 当你的路由从 test1 切换到 test 的时候，两个子应用是同时激活的，冲突了

原来是路由和name冲突，已解决，多谢

**Comment by yejunhong** [comment]
> https://github.com/yejunhong/qiankun/blob/master/micro/index.js#L6 导致两个应用的 activeRule 都返回了 true，从而导致两个应用被同时激活

多谢，指出问题
