### ISSUE TITLE
是否考虑独立组件支持

### ISSUE THREAD

**Issue by ShaofeiZi** [umijs/qiankun#3]
我需要通过 URL 加载远程的项目，但是应用已经成型所以路由功能对我来说是多余且有害的。
或者我某个页面中需要加载多个远程项目。这个时候路由功能也较为难受。
我相信这不只是我一个人会遇到的问题。
如果可以支持将远程项目包装为组件。灵活性会增加很多。

**Comment by kuitos** [comment]
一个页面加载几个模块，是由调用者决定的
