### ISSUE TITLE
webui-inpatient-bedcard wrapper with id __qiankun_subapp_wrapper_for_webui_inpatient_bedcard__ not ready!

### ISSUE THREAD

**Issue by frontHu** [umijs/qiankun#301]
## What happens?
- 主应用配置
![image](https://user-images.githubusercontent.com/19454392/76271822-a7f97400-62b4-11ea-8e30-4aec64cfd5bc.png)

- 子应用配置
![image](https://user-images.githubusercontent.com/19454392/76271870-c9f2f680-62b4-11ea-9cf7-da949bf47825.png)

- 主应用运行后报如下错误
![image](https://user-images.githubusercontent.com/19454392/76271908-e000b700-62b4-11ea-8c44-db840c6b28df.png)

## Context

- **qiankun Version**: 1.3.10
- **Platform Version**: window10 
- **Browser Version**: Chrome

**Comment by stevenspiel** [comment]
How did you fix this? I'm getting the same error.

**Comment by cshsh** [comment]
是怎么解决的，我也遇到这个问题

**Comment by mowatermelon** [comment]
How did you fix this? I'm getting the same error.

**Comment by BearD01001** [comment]
请问有解决吗，我也遇到了同样的问题，打断点发现那个 DOM 节点在子应用刚开始载入的时候是有渲染出来的，但是完全载入后整个节点就完全消失了

**Comment by liuxiuqian** [comment]
> 请问有解决吗，我也遇到了同样的问题，打断点发现那个 DOM 节点在子应用刚开始载入的时候是有渲染出来的，但是完全载入后整个节点就完全消失了

请问你的解决了吗
