### ISSUE TITLE
子应用的子路由强制刷新，然后就404了

### ISSUE THREAD

**Issue by tolerious** [umijs/qiankun#302]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

子应用的子路由强制刷新，然后就404了，这个问题有办法处理么？ 
## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by mayako21126** [comment]
应该是history模式的原因，谷歌下history 404，用代理服务器做下处理就行

**Comment by kuitos** [comment]
参考 https://router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90
