### ISSUE TITLE
umijs/max + antd的父级项目和两个子项目，父项目中切换子项目时提示：Router basename="/oms"> is not able to match the URL "/pms/" because it does not start with the basename, so the <Router> won't render anything.

### ISSUE THREAD

**Issue by iswinter1993** [umijs/qiankun#3028]
## What happens?
umijs/max + antd的父级项目和两个子项目，父项目中切换子项目时提示：Router basename="/oms"> is not able to match the URL "/pms/" because it does not start with the basename, so the <Router> won't render anything. 子项目卸载后，想要切换的另一个子项目挂载后不显示了。
![微信图片_20241203171900](https://github.com/user-attachments/assets/bcefc819-e7d1-4e60-b687-dc7485122ab4)

umijs/max项目的配置
![微信截图_20241203172125](https://github.com/user-attachments/assets/a4d66492-c88a-4877-80f2-a5a53701073a)
![微信截图_20241203172243](https://github.com/user-attachments/assets/093080dc-ce3a-4144-bc4b-fea2499544b6)
![微信截图_20241203172344](https://github.com/user-attachments/assets/40719531-f7cf-44d1-a609-8a937d423162)

父级"@umijs/max": "4.0.75",
子级"@umijs/max": "4.0.76",

**Comment by jk4235** [comment]
父级路由关于子应用配置应该可以去掉，master里配置后会自动加载进去的
