### ISSUE TITLE
[Feature Request] 预加载子应用的时机

### ISSUE THREAD

**Issue by wufeng87** [umijs/qiankun#304]
## Background
目前的预加载时机是第一个子应用mount后，触发其他子应用的预加载

## Proposal
是否可以支持主应用加载后，即开始子应用的预加载?

目前看来，只加载主应用，没加载子应用时，不会触发预加载
qiankun version 1.3.14"

**Comment by kuitos** [comment]
`prefetch: 'all'`
see https://qiankun.umijs.org/zh/api/#start-opts
