### ISSUE TITLE
[Feature Request] 有个手动unmount的需求

### ISSUE THREAD

**Issue by wufeng87** [umijs/qiankun#305]
## Background
我有一个子应用是主应用的二级路由才触发的：
路由1： /main-a/   对应主应用的a模块
路由2： /main-a/child-a    对应主应用的a模块，以及子应用a
路由3:   /main-b/  主应用b模块
当我由路由2切换到路由3时，因为路由切换，子应用的dom在调用unmount之前就被移除了，然后会出现下面这个错。我想，这个场景我需要在componentWillUnmount时 手动unmount子应用a。
```
Uncaught fssc: Application 'fssc' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.
```
## Proposal
查看了single-spa的api，好像没暴露unmount接口。有什么好建议吗？谢谢。

**Comment by kuitos** [comment]
你需要确保子应用挂载的节点是稳定的。比如提供一个不会被移除的 div

**Comment by bacy** [comment]
window[appName].unmount()
