### ISSUE TITLE
[Bug]子应用加载第三方脚本

### ISSUE THREAD

**Issue by fringesoft** [umijs/qiankun#306]
## What happens?

子应用中无法正常加载第三方提供的脚本，无论是直接在index.html中直接用script加载还是在js代码中动态生成，均报跨域问题，无法加载

## 最小可复现仓库

内部项目，暂无法提供

## 复现步骤，错误日志以及相关配置

见问题描述

## 相关环境信息

- **qiankun 版本** 1.4.0
- **浏览器版本**：Chrome
- **操作系统**：window 10

**Comment by kuitos** [comment]
开启跨域，或者把脚本拉到本地。
see https://qiankun.umijs.org/zh/faq/#%E5%AD%90%E5%BA%94%E7%94%A8%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E4%B8%80%E5%AE%9A%E8%A6%81%E6%94%AF%E6%8C%81%E8%B7%A8%E5%9F%9F%E5%90%97%EF%BC%9F

**Comment by fringesoft** [comment]
关于这个问题个人觉得没法要求第三方开启跨域，同时第三方的脚本中也会有动态创建script标签的可能。在1.4.5版本上尝试了一下，在进入需要第三方脚本的界面时将document.head.appendChild先保存然后替换会原生版本，并在离开该界面时还原回qiankun的版本，勉强能实现。
这里想咨询一下是否可以在hijackers可以增加过滤选项，对默写域名下的脚本不进行hijack处理

**Comment by xiaoiver** [comment]
> 关于这个问题个人觉得没法要求第三方开启跨域，同时第三方的脚本中也会有动态创建script标签的可能。在1.4.5版本上尝试了一下，在进入需要第三方脚本的界面时将document.head.appendChild先保存然后替换会原生版本，并在离开该界面时还原回qiankun的版本，勉强能实现。
> 这里想咨询一下是否可以在hijackers可以增加过滤选项，对默写域名下的脚本不进行hijack处理

我也遇到了同样的问题，阿里云 XConsole 控制台会添加其他 JS 脚本，调用被 qiankun 劫持的 `appendChild` 就报错了。

**Comment by ilbefun** [comment]
有解决办法吗？
