### ISSUE TITLE
父子应用如何进行通信和数据共享。

### ISSUE THREAD

**Issue by zfha** [umijs/qiankun#307]
## Background

举个栗子: main框架会负责整个用户信息，用户权限的获取和限制。而这部分数据其实是所有子应用共享的，是否有办法让子应用直接获取父框架的共享数据。

**Comment by youyuyi** [comment]
sessionStorage

**Comment by hql7** [comment]
qiankun支持主应用传递信息给所有子应用，这里有一个文章https://juejin.im/post/5e1824296fb9a02fde20fec9



在 2020-03-13 11:24:18，"fanfan" <notifications@github.com> 写道：

Background

举个栗子: main框架会负责整个用户信息，用户权限的获取和限制。而这部分数据其实是所有子应用共享的，是否有办法让子应用直接获取父框架的共享数据。

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/76722942-9adef800-6780-11ea-8a49-c4cad593f815.png)

see 
https://qiankun.umijs.org/zh/api/#registermicroapps-apps-lifecycles-opts

**Comment by Bonnie8ni** [comment]
如上所說主應用是利用 registerMicroApps 的 props 傳遞數據給子應用
請問當父應用傳遞的值（來自localstorage）有更新時要怎麼重新傳給子應用？
