### ISSUE TITLE
[Feature Request] examples中主应用main并不是一个具体的技术栈，如果我用react作为主应用技术栈，如何通过路由的方式挂载应用，而非事先写死结构在主应用中

### ISSUE THREAD

**Issue by zhangyanling77** [umijs/qiankun#308]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by zhangyanling77** [comment]
现在的exapmles看起来是mian里面html结构是事先写好的。跳转路由的方式是原生script来触发。我想要主应用就是react，并且路由触发应用加载通过react-router得方式。可以提供个示例吗

**Comment by zhangyanling77** [comment]
比如外框架作为主应用，那么路由控制是在主应用，一开始可以并不加载任何子应用，而是展示自己的资源。当通过路由触发来调起子应用，类似传统的iframe方式，有法做吗

**Comment by hql7** [comment]
@zhangyanling77 https://github.com/hql7/wl-micro-frontends 这有个以vue为主应用的，不知是否如我理解你的需求

**Comment by issochen** [comment]
@zhangyanling77 这个 https://github.com/issochen/qiankun-vue-demo  呢

**Comment by kuitos** [comment]
参考 umi plugin 的 example https://github.com/umijs/umi-plugin-qiankun/tree/master/examples

**Comment by mowatermelon** [comment]
> 比如外框架作为主应用，那么路由控制是在主应用，一开始可以并不加载任何子应用，而是展示自己的资源。当通过路由触发来调起子应用，类似传统的iframe方式，有法做吗

可以默认只做主应用的加载，默认进来可以用主服务的login和Daborad ，然后如果有具体 router-view 涉及到子服务的页面，这边乾坤会自动的找子服务的资源进行返回，加载。

比如，子服务这边注册的路由是 `/aaa`,相关的路由隐射，则这边主服务监听到`/aaa/*`都会自动映射子服务下。
