### ISSUE TITLE
v-html和importEntry不会导致js被下载两次吗

### ISSUE THREAD

**Issue by bacy** [umijs/qiankun#309]
### 一个小疑问，v-html和importEntry不会导致js被下载两次吗？

![image](https://user-images.githubusercontent.com/5163569/76621182-c20fac80-6569-11ea-8296-cd0c6d43d885.png)
## 相关环境信息

- **qiankun 版本**
1.4.5
- **浏览器版本**：
chrome
- **操作系统**：
mac

**Comment by fringesoft** [comment]
我也碰到同样的问题，vue中用v-html指令渲染的时候js文件会被下载两次，当js文件较大时有些游览器还会加载包content-length不一致的错误，我目前的解决方法是在赋值给v-html前移除所有用link标签加载的js脚本：
  ```
  //避免重复加载资源
    var fixedAppContent = "";
    if (appContent) {
      fixedAppContent = appContent;
      var linkTags = appContent.match(/<link((?!<).)*>/g);
      for (let i = 0; i < linkTags.length; i++) {
        fixedAppContent = fixedAppContent.replace(
          linkTags[i],
          linkTags[i].replace("<", "<!--").replace(">", "-->")
        );
      }
    }
```

**Comment by bacy** [comment]
> 我也碰到同样的问题，vue中用v-html指令渲染的时候js文件会被下载两次，当js文件较大时有些游览器还会加载包content-length不一致的错误，我目前的解决方法是在赋值给v-html前移除所有用link标签加载的js脚本：
> 
> ```
> //避免重复加载资源
>   var fixedAppContent = "";
>   if (appContent) {
>     fixedAppContent = appContent;
>     var linkTags = appContent.match(/<link((?!<).)*>/g);
>     for (let i = 0; i < linkTags.length; i++) {
>       fixedAppContent = fixedAppContent.replace(
>         linkTags[i],
>         linkTags[i].replace("<", "")
>       );
>     }
>   }
> ```

这是个不错的办法，不过你这样写，会把css给移除了
![image](https://user-images.githubusercontent.com/5163569/76675425-5a527380-65f4-11ea-8c7d-9b2a56fe3bb3.png)
除了判断link的话，还得把style过滤掉

**Comment by kuitos** [comment]
npm update 更新到最新的依赖即可
