### ISSUE TITLE
[Bug]内网深信服网管给子项目注入了cookie/flash.js，导致子系统加载失败

### ISSUE THREAD

**Issue by wubinsheng2017** [umijs/qiankun#310]
## What happens?
公司内网配置了深信服的网管系统。
在这环境下访问我们页面时，出现了以下问题：
qiankuan加载子系统时，会有较大概率出现混入了一个 cookie/flash.js的文件，然后出现加载错误。
插入的链接：http://1.1.1.3:89/cookie/flash.js
qiankun去fetch该链接时，出现了跨域错误，加载失败，结果就导致整个子系统加载中断了。

## 最小可复现仓库

因为与项目代码无关，且依赖环境，所以没法提供复现仓库和步骤

## 相关环境信息

- **qiankun 版本**：1.3.11
- **浏览器版本**：chrome 80
- **操作系统**：windows 10

**Comment by fringesoft** [comment]
你可以看看 issue：
Duplicate of #306
咱们碰到的应该是同一个问题：子应用加载后如果jsandbox开启的话（start方法中设置为true），所有srcipt标签包括通过appendChild动态添加的script都会被乾坤拦截并改用fetch和eval进行加载和执行，如果加载的是第三方并且第三方的服务器没有开启跨域的话就会出现这个问题，感觉很大概率上无法加载很多第三方。我目前加载百度地图的时候用了点野路子，原理是在乾坤替换掉原生的appendChild方法前先保存原生的appendChild方法，后续需要加载第三方时替换回来，并在离开页面时在替换回乾坤的代理方法，具体如下：（vue+百度地图+乾坤1.4.5）


 ```
initBaiduMap() {
      var self = this;
      //这里在界面上增加一个div标签用于插入script标签，因为其他标签已经都被qiankun代理了
     // 这样做将影响减少到最小
      var el = document.getElementById("ext");
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.language = "javascript";
      script.src =
        "http://api.map.baidu.com/getscript?v=3.0&ak=bUkCG41b2cr6XTqqkeSQpMrr";
      script.onload = function() {
        if (window.BMap) {
          self.map = new window.BMap.Map("mapContainer");
          var point = new window.BMap.Point(self.longitude, self.latitude);
          self.map.centerAndZoom(point, 15);
          self.marker = new window.BMap.Marker(point);
          self.map.addOverlay(self.marker);
        }
      };
      //保留并替换head标签的appendChild，因为第三方里还有可能会往这里append
      this.qiankunHeadAppendChild = document.head.appendChild;
      document.head.appendChild = this.$portal.rawHeadAppendChild;
      //替换待插入目标的appendChild方法
      el.appendChild = document.appendChild;

      el.appendChild(script);
```
上述方法调用百度地图成功，不过不要忘了页面销毁的前将appendChild替换回来

**Comment by wubinsheng2017** [comment]
> 你可以看看 issue：
> Duplicate of #306
> 咱们碰到的应该是同一个问题：子应用加载后如果jsandbox开启的话（start方法中设置为true），所有srcipt标签包括通过appendChild动态添加的script都会被乾坤拦截并改用fetch和eval进行加载和执行，如果加载的是第三方并且第三方的服务器没有开启跨域的话就会出现这个问题，感觉很大概率上无法加载很多第三方。我目前加载百度地图的时候用了点野路子，原理是在乾坤替换掉原生的appendChild方法前先保存原生的appendChild方法，后续需要加载第三方时替换回来，并在离开页面时在替换回乾坤的代理方法，具体如下：（vue+百度地图+乾坤1.4.5）
> 
> ```
> initBaiduMap() {
>      var self = this;
>      //这里在界面上增加一个div标签用于插入script标签，因为其他标签已经都被qiankun代理了
>     // 这样做将影响减少到最小
>      var el = document.getElementById("ext");
>      var script = document.createElement("script");
>      script.type = "text/javascript";
>      script.language = "javascript";
>      script.src =
>        "http://api.map.baidu.com/getscript?v=3.0&ak=bUkCG41b2cr6XTqqkeSQpMrr";
>      script.onload = function() {
>        if (window.BMap) {
>          self.map = new window.BMap.Map("mapContainer");
>          var point = new window.BMap.Point(self.longitude, self.latitude);
>          self.map.centerAndZoom(point, 15);
>          self.marker = new window.BMap.Marker(point);
>          self.map.addOverlay(self.marker);
>        }
>      };
>      //保留并替换head标签的appendChild，因为第三方里还有可能会往这里append
>      this.qiankunHeadAppendChild = document.head.appendChild;
>      document.head.appendChild = this.$portal.rawHeadAppendChild;
>      //替换待插入目标的appendChild方法
>      el.appendChild = document.appendChild;
> 
>      el.appendChild(script);
> ```
> 
> 上述方法调用百度地图成功，不过不要忘了页面销毁的前将appendChild替换回来

对于你的需求，这样是能行的，因为你是白名单模式。
但是我这是被劫持的场景，没有白名单的概念，如果哪天名字不再是flash.js，我的代码又要改。
我的建议是，在加载资源的策略了，qiankun能不能和浏览器一致，不要因为某一个资源出错，而终止整个加载的过程

**Comment by smk0621** [comment]
也有同样的问题。例如被深信服劫持导致加载深信服的资源，其实是和子应用无关的，不影响子应用的加载的。但是目前来说一个资源无法加载就终止整个加载过程就就直接导致白屏。我们也不能要求第三方必须加上跨域。这个就很尴尬了。

**Comment by shengbeiniao** [comment]
同样的问题，卡巴斯基注入js，子应用被block，mark

**Comment by dishenghk** [comment]
可以传入fetch方法,自行处理一下特殊跨域问题

**Comment by xiezhongfu** [comment]
是不是可以用 iframe 包成跟 import-html-entry 适配的 api 格式搞下。用 iframe 自定义成 “fetch”

**Comment by wufeng87** [comment]
试试改下乾坤代码，start时传入一个参数：js隔离白名单。就这个js还是走script标签加载。

**Comment by kuitos** [comment]
解决步骤：
1. npm update 确保相关依赖升级到最新
2. 参考文档 https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E7%94%B1%E4%BA%8E%E8%BF%90%E8%90%A5%E5%95%86%E5%8A%A8%E6%80%81%E6%8F%92%E5%85%A5%E7%9A%84%E8%84%9A%E6%9C%AC%E5%8A%A0%E8%BD%BD%E5%BC%82%E5%B8%B8%E5%AF%BC%E8%87%B4%E5%AD%90%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by JamesWen1993** [comment]
@wubinsheng2017 请问下具体是怎么操作的？可以发个邮箱给我看下吗？谢谢dalao。。wenzy@ruhrtec.cn

**Comment by wubinsheng2017** [comment]
> @wubinsheng2017 请问下具体是怎么操作的？可以发个邮箱给我看下吗？谢谢dalao。。[wenzy@ruhrtec.cn](mailto:wenzy@ruhrtec.cn)
const hosts = [ '127.0.0.1', ... ]
const customImportConfig = {
  fetch (url, ...args) {
    if (hosts.every(h => url.indexOf(h) === -1)) {
      return Promise.resolve({
        text () { return '' }
      })
    }

    return window.fetch(url, { ...args, referrerPolicy: 'origin-when-cross-origin' })
  }
}

start({ prefetch: true, fetch: customImportConfig.fetch })

**Comment by JamesWen1993** [comment]
@fringesoft dalao这个this.$portal.rawHeadAppendChild哪里来的？

**Comment by sushuier** [comment]
解决方案，亲测有效：
![image](https://github.com/umijs/qiankun/assets/22663393/a34b4d6e-ff73-4000-b9b1-325514812642)
在 registerMicroApps 方法中传入的 entry 字段后添加 index.text（只需这一个操作即可，其他什么都不用动），即可绕开内网环境监测fetch请求html页面动态注入cookie；

**Comment by chengkai2022** [comment]
有一个比较好的方法，禁止给html注入域外文件。
例如在nginx.conf中增加
`location ~* /.html$ {
            add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
            add_header Content-Security-Policy "default-src 'self'; script-src 'self';";
        }`

**Comment by GED-wei** [comment]
直接把问题抛给网络部的小伙伴，一个识别终端类型的旧功能，关掉就好了。
