### ISSUE TITLE
子应用的异步请求会转发到主应用上

### ISSUE THREAD

**Issue by wulucxy** [umijs/qiankun#315]
## What happens?

假设现在有主、子应用，端口号分别为 6001，7001。主、子应用都是通过 `koa2` 来做服务端。

其中子应用有一个异步请求：

```
axios.get('/app/getList')
```
正常来说，这个请求会转发到 `localhost:7001/app/getList`，但是自引用通过 htmlEntry 引入以后，真正调用的地址变成了`localhost:6001/app/getList`，与预期不符

也就是说，我们想要的只是前端的聚合，后端的接口仍然保持不变，目前的做法是把这两个全部集合在主应用上了，违背了微服务的初衷。

@kuitos

**Comment by Deturium** [comment]
这个就是正常行为

你可以把子应用的请求路径改为绝对路径，或者在主应用做劫持转发

**Comment by wulucxy** [comment]
@Deturium 

1. 子应用的请求路径包括开发、测试、预发和生产，并且是根据外部配置传递，无法写死。
2. 主应用劫持转发，相当于每次请求都要走两遍。。。。

请问下，难道蚂蚁内部也是采用这种做法么？

**Comment by kuitos** [comment]
> 子应用的请求路径包括开发、测试、预发和生产，并且是根据外部配置传递，无法写死。
配置通过接口等方式下发，不是写死到代码里

> 应用劫持转发，相当于每次请求都要走两遍。。。。
主应用劫持 ajax 直接转换成跨域调用，或者通过主应用代理，不会走两遍

**Comment by kuitos** [comment]
蚂蚁内部是两种方式结合起来用的，服务端代理 + 前端劫持请求转换成跨域

**Comment by wulucxy** [comment]
@kuitos  谢谢，请问下前端拦截这块是通过什么实现的，我看qiankun 里面没有提供劫持 ajax 的实现？

**Comment by wulucxy** [comment]
@Deturium @kuitos 感谢提供思路，已实现该方案

**Comment by drafish** [comment]
> 蚂蚁内部是两种方式结合起来用的，服务端代理 + 前端劫持请求转换成跨域

如果是前端劫持请求转换成跨域的话，是不是要把子应用的host写进代码里，感觉这样的话不是很优雅呀

**Comment by Xiao-HuangShu** [comment]
> @Deturium @kuitos 感谢提供思路，已实现该方案
最近我也遇到这个问题，请问作者大大是怎么实现的

**Comment by Liquid-Zhangliquan** [comment]
> > @Deturium @kuitos 感谢提供思路，已实现该方案
> > 最近我也遇到了这个问题，我子应用的请求转发到了主应用，导致我子应用无法接受到接口返回的数据，请问作者大大是怎么实现的，谢谢

我也想问这个问题，我单独子应用可以请求数据，整合进去，就请求不到子应用的数据了

**Comment by xzh1656694723** [comment]
没有详细的操作步骤吗？表示看不懂呀~
