### ISSUE TITLE
为什么不建议提取子应用的公共依赖？

### ISSUE THREAD

**Issue by wangmeijian** [umijs/qiankun#317]
## Background

在[文档](https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E6%8F%90%E5%8F%96%E5%87%BA%E5%85%AC%E5%85%B1%E7%9A%84%E4%BE%9D%E8%B5%96%E5%BA%93%EF%BC%9F)中看到说不建议提取子应用的公共依赖，为什么？有什么副作用吗？

**Comment by kuitos** [comment]
共用依赖也是一种耦合，后面子应用想升级基础库了，必须等主应用升级才行、

**Comment by wangmeijian** [comment]
了解
