### ISSUE TITLE
[Bug]使用build后的主应用无法隔离css样式

### ISSUE THREAD

**Issue by CeceWall** [umijs/qiankun#318]
## What happens?

build后的主应用加载时无法隔离css样式
使用的webpack或parcel打包均能复现(demo中使用parcel)

## 最小可复现仓库

> prod-style-bug分支

https://github.com/CeceWall/qiankun-css-order-bug/tree/prod-style-bug

#### 安装

`yarn install-all`

#### 运行

`yarn start-all`

#### 复现方法

1. 编译完毕后，打开[主应用dev](http://127.0.0.1:5678)和[主应用prod](http://127.0.0.1:5679)

2. dev模式中子应用的样式未加载到主应用的head中，prod模式中head被污染

## 相关环境信息

- **qiankun 版本**: 1.4.5
- **浏览器版本**：Google Chrome | 80.0.3987.132 (正式版本) （64 位）
- **操作系统**：Windows10 1903

**Comment by Deturium** [comment]
1. qiankun 暂时不处理主子应用之间的样式隔离问题

2. qiankun 现在已经不会把子应用的样式表插入主应用 head，而是插在子应用所在的 DOM 结构中

**Comment by Deturium** [comment]
prod 环境 head 被污染这个问题，应该是 style-loader 导致的 
```
    css: {
        extract: false,
    },
```
style-loader 在引用 bootstrap 阶段做的事情在生产环境没被劫持

@kuitos  生产环境是不是也应该劫持一下？
[hijackers#L18](https://github.com/umijs/qiankun/blob/master/src/hijackers/index.ts#L18)

**Comment by kuitos** [comment]
@CeceWall 生产环境不开启 extract 的原因是？

**Comment by CeceWall** [comment]
#303 因为外部样式没法保证加载顺序。想在解决前暂时关闭extract解决

**Comment by CeceWall** [comment]
> @CeceWall 生产环境不开启 extract 的原因是？

#303 因为外部样式没法保证加载顺序。想在解决前暂时关闭extract解决
