### ISSUE TITLE
是否乾坤只适用于主流开发库（react/vue/angular）？

### ISSUE THREAD

**Issue by crixusshen** [umijs/qiankun#32]
我们企业内部目前都是使用自研的框架（完全自研，也没有基于主流库做二次改造），我想使用它并不是来解决不同组使用不同的技术栈来共建的问题，而是我想使用它来解决业务逻辑层公用的问题，例如目前我们的app和微信内大量功能都是使用自研框架来实现，目前需要做网站端，为了公用核心逻辑层，是否乾坤可以使用在自研的框架中？

**Comment by kuitos** [comment]
不限制应用的技术栈，子应用只需要按照这个步骤就能接入 https://github.com/umijs/qiankun#sub-app

**Comment by crixusshen** [comment]
@kuitos 好的，十分感谢你的回答
