### ISSUE TITLE
dva 项目，model是动态挂载的，二次加载model未挂载，先渲染导致报错

### ISSUE THREAD

**Issue by middle2021** [umijs/qiankun#320]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by middle2021** [comment]
> 提供可复现仓库

https://i.loli.net/2020/03/18/voGAO27WqHcRyTE.png

**Comment by jiangxiaoyu66** [comment]
@alipay404  遇到了同样的问题，请问是怎么解决的呢

**Comment by alipay404** [comment]
> 
```
`const dynamicWrapper = dynamic({ app, ...dynamics, resolve: () => dynamicResolve({ app, ...dynamics }) })`
```
