### ISSUE TITLE
[Bug][@umijs/plugin-qiankun] 低版本浏览器兼容问题

### ISSUE THREAD

**Issue by tdida** [umijs/qiankun#322]
在最新的Chrome版本上运行正常，目前发现Chrome 49加载子应用失败，控制台报错信息如下：
You need to export the functional lifecycles in callout entry

umi 配置了 chainWebpack
``
const packageName = require('../package.json').name;

chainWebpack: config => {
    config.output
      .library(packageName)
      .libraryTarget('umd')
      .jsonpFunction(`webpackJsonp_${packageName}`);
  },
``
## 相关环境信息

- **qiankun 版本**  @umijs/plugin-qiankun 1.5.1
- **浏览器版本**：chrome 49
- **操作系统**：window 10

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by tdida** [comment]
配置了

`
chainWebpack: config => {
config.output
.library(packageName)
.libraryTarget('umd')
.jsonpFunction(webpackJsonp_${packageName});
}
`

**Comment by kuitos** [comment]
1. 使用 plugin 不需要单独配置，跟着 plugin 的文档来
2. 按链接文档里的步骤确认解决
3. 文档的方式都尝试了不能解决的话，提供可复现的仓库

**Comment by tdida** [comment]
@kuitos 
修改 @umijs/plugin-qiankun 源码这里，重新打包，解决了这个问题
![image](https://user-images.githubusercontent.com/18672870/76918969-7b6fd880-6902-11ea-908e-f625ef090e2d.png)

**Comment by node-rookie** [comment]
@kuitos chrome58版本也有同样的问题，能请问下乾坤浏览器支持的版本吗

**Comment by node-rookie** [comment]
@tdida 能问问怎么解决的吗？
