### ISSUE TITLE
[Bug] start函数中的fetch属性只在prefetch中有效

### ISSUE THREAD

**Issue by CeceWall** [umijs/qiankun#325]
## What happens?
在使用@umijs/plugin-qiankun插件时，发现无法替换fetch函数

原因如下：

- qiankun中start传入的fetch函数不生效
- @umijs/plugin-qiankun 无法传递registerMicroApps的全部参数

## 最小可复现仓库

官方example稍作修改即可复现

## 复现步骤，错误日志以及相关配置

1. 随意替换官方示例中主应用的start函数的fetch参数，如图
![image](https://user-images.githubusercontent.com/26295849/76942973-8f82fc80-6939-11ea-98e3-b6993ed8bf59.png)
2. 代码中和实际观察，fetch函数均未生效。prefetch依赖requestIdleCallback，未触发
3. 修改registerMicroApps函数中的fetch参数，这次生效了
![image](https://user-images.githubusercontent.com/26295849/76943155-db35a600-6939-11ea-89d5-571d7230e9b3.png)
4. @umijs/plugin-qiankun中，[代码显示](https://github.com/umijs/plugins/blob/master/packages/plugin-qiankun/src/master/runtimePlugin.ts#L116)没有传递registerMicroApps第三个参数

## 相关环境信息

- **umi 版本**：3
- **qiankun 版本**：1.4.5
- **浏览器版本**：Google Chrome | 80.0.3987.132 (正式版本)
- **操作系统**：Windows10 1903

**Comment by kuitos** [comment]
自定义的 fetch 在调用 registerMicroApps 时也需要传
![image](https://user-images.githubusercontent.com/5206843/76975900-28cc0600-696e-11ea-81cc-7c499b2271fc.png)

https://qiankun.umijs.org/zh/api/#registermicroapps-apps-lifecycles-opts

这个设置 fetch 的 api 不太合理，2.0 会改掉

**Comment by CeceWall** [comment]
@umijs/plugin-qiankun 无法传递把fetch传递给registerMicroApps吧

**Comment by kuitos** [comment]
需要升级下 @umijs/plugin-qiankun
