### ISSUE TITLE
子项目在使用相对路径svg资源的时候，无法显示对应的svg图标

### ISSUE THREAD

**Issue by kkk25641463** [umijs/qiankun#327]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
请使用 issue 模板提交问题，谢谢
