### ISSUE TITLE
umi-plugub-qiankun的umi微前端，如何打包生产环境，没有找到相关文档，能告知一下吗

### ISSUE THREAD

**Issue by rodchen-king** [umijs/qiankun#328]
## Background

umi-plugub-qiankun的umi微前端，如何打包生产环境，没有找到相关文档，能告知一下吗

**Comment by kuitos** [comment]
正常 umi 项目怎么打包微前端场景就怎么打包，没有差异

**Comment by rodchen-king** [comment]
> 正常 umi 项目怎么打包微前端场景就怎么打包，没有差异

我现在遇到情况是，主程序上跳转子应用的时候，没有去获取子应用的资源，dev环境时可以的，就是打完包之后不行。

**Comment by kuitos** [comment]
提供可复现的仓库
