### ISSUE TITLE
关于请求资源（如果资源是servlet的服务端渲染页面），服务端拿不到cookie的问题

### ISSUE THREAD

**Issue by crixusshen** [umijs/qiankun#329]
qiankun拉取css js servlet这些资源时，服务端拿不到cookie，请问这是因为自带的fetch的credentials默认并没有设置为include导致的吗？

**Comment by kuitos** [comment]
registerMicroApps 跟 start 里可以配置自定义 fetch
https://qiankun.umijs.org/zh/api/#registermicroapps-apps-lifecycles-opts
https://qiankun.umijs.org/zh/api/#start-opts
![image](https://user-images.githubusercontent.com/5206843/77062145-494f9b00-6a16-11ea-9df4-a539215d87d7.png)
