### ISSUE TITLE
子项目css使用相对路径的svg图片当背景, 父项目无法请求到资源

### ISSUE THREAD

**Issue by tianctrl** [umijs/qiankun#330]
## What happens?
同一个项目里, 不同组件使用的svg背景, 有的偶尔可以在父项目中获取到.
css的写法为 : background-image: url(../assets/images/map-icon-cljl-h.svg)
同样的写法, 不清楚为什么有的可以显示有的不可以显示.

## Mini Showcase Repository(REQUIRED)

没有什么特殊写法, 只是css的background-image.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 1.4.3
- **Platform Version**: react 16.12
- **Browser Version**: chrom 80 (最新)

**Comment by kuitos** [comment]
配置 webpack publicPath 及相关的 loader，确保 svg 的地址为带域名的全路径，参考 https://qiankun.umijs.org/zh/faq/#b-%E4%BD%BF%E7%94%A8-webpack-%E9%9D%99%E6%80%81-publicpath-%E9%85%8D%E7%BD%AE
