### ISSUE TITLE
[Feature Request] 请问有基于angularjs的例子吗

### ISSUE THREAD

**Issue by zengyunchun** [umijs/qiankun#331]
请问有基于angularjs的例子吗

**Comment by Deturium** [comment]
你的意思是 `angularjs` 作为子应用接入的例子吗，还没有
你可以参考其他技术栈的例子，结合 https://single-spa.js.org/docs/ecosystem-angularjs/ 自己实现

欢迎 PR

**Comment by kuitos** [comment]
closed via inactive

**Comment by chengxuanxie** [comment]
> 你的意思是 `angularjs` 作为子应用接入的例子吗，还没有
> 你可以参考其他技术栈的例子，结合 https://single-spa.js.org/docs/ecosystem-angularjs/ 自己实现
> 
> 欢迎 PR


之前也遇到了这个问题，在issue里面翻了很久，最后自己摸索出来了，思路就是从这个issue来的。遇到同样问题的朋友可以参考一下我的例子:
https://github.com/chengxuanxie/qiankun-angular-angularjs/blob/master/README.md
