### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by 523451928** [umijs/qiankun#332]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

浏览器刷新偶现报错
![image](https://user-images.githubusercontent.com/24381309/77227069-6623d400-6bb8-11ea-91ad-d35886bfdd91.png)
single-spa.min.js?25a2:1 Uncaught vue customerPlatformIndex: Application 'vue customerPlatformIndex' died in status LOADING_SOURCE_CODE: [qiankun]: vue customerPlatformIndex wrapper with id __qiankun_subapp_wrapper_for_vue_customer_platform_index__ not ready!
请教一下怎么解决

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by Deturium** [comment]
请按模板提 issue 并给出复现仓库
