### ISSUE TITLE
[Feature Request] Wrapper element style

### ISSUE THREAD

**Issue by davidebianchi** [umijs/qiankun#333]
## Background

I'm trying to integrate this library in an existing microfrontend application with a specific way to handle overflow usign overflow hidden and auto.
The wrapper div added by this lib broke the percentage height of the supapp components.

I try to replace the template, but it is only possible to add a sub template.

## Proposal

To solve this issue, the container div could be replace with an inline element, like a span (or could be an option to switch around div and span element)

**Comment by kuitos** [comment]
You could set a custom `getTemplate` function to replace the div string with span, see https://qiankun.umijs.org/api/#registermicroapps-apps-lifecycles-opts
![image](https://user-images.githubusercontent.com/5206843/77275675-de42e480-6cf3-11ea-9723-5b5770cd8305.png)

**Comment by davidebianchi** [comment]
Hi @kuitos, thanks for the reply! Yes I tried to add a getTemplate function, but the template does not replace the existent wrapper. Instead it is a children of the default wrapper. It could be possible to changee the getTeemplate to replace the existing default?

**Comment by kuitos** [comment]
Yes it is by design~

With your scenario you may could use a descendant selector to make the div inline with css, such as: 
```html
<style>
  #your-container > div { style: inline; }
</style>

<div id="your-container">
  <div id="qiankun_wrapper">...</div>
</div>
```

**Comment by davidebianchi** [comment]
Yes, but the problem custom template results over the `qiankun_wrapper ` using the `getTemplatet` function:

```js
<div id="qiankun_wrapper">
  <div id="your-container">...</div>
</div>
```

Is this a bug? If it is, I can open a PR to fix this unexpected behaviour.

**Comment by kuitos** [comment]
Not a bug, it was by design😄

The layer of `qiankun_wrapper` must be kept in the html to ensure that we could find the sub app by a regular id, that is why you could not overwrite it with a custom `getTemplate` function

**Comment by davidebianchi** [comment]
Ok, perfect! But could the template wrap the `qiankun_wrapper `? As you showed [here](https://github.com/umijs/qiankun/issues/333#issuecomment-602540870)?

At the moment this is not the case, the `qiankun_wrapper` is a children of the custom template. And by css we can not referencing to a parent element (without use css [has selector](https://caniuse.com/#feat=css-has), but it is not supported by any browser)


Make this could be as simple as [here](https://github.com/umijs/qiankun/blob/master/src/register.ts#L93) use `flowRight` instead of `flow`, or switch the order of the called function:

```js
getTemplate: flow(getDefaultTplWrapper(appName), getTemplate),
```

**Comment by kuitos** [comment]
We could not change the order or use `flowRight ` instead, which could not avoid changing the html structure by a custom `getTemplate` function.

With your scenario you could use a css selector from the parent of `qiankun_wrapper`, as the render was all defined by yourself, such as the example:
```jsx
function render({appContent}) {
  return ReactDOM.render(
    <div id="render-container" dangerouslySetInnerHTML={{ __html: appContent }} />,
    container,
  )
}
```

Now you could define the style of `qiankun_wrapper `
```css
#render-container > div {
  display: inline;
}
```

**Comment by davidebianchi** [comment]
Ah ok, so I should not use the template but use the wrapper component! I've lost this piece of code 😄 

Thank you!
