### ISSUE TITLE
[Feature Request] 非webpack打包的项目如何接入qiankun

### ISSUE THREAD

**Issue by kevinPFish** [umijs/qiankun#338]
阅读过文档，子应用都是通过webpack暴露生命周期钩子和函数；请问非webpack打包，传统的后端模板渲染的MPA项目如何接入呢？

**Comment by zengyunchun** [comment]
我也想知道有没有像single-spa一样可以有es5的版本或者在全局上有个对象可以注册

**Comment by caogenyin** [comment]
主应用是非webpack打包的传统项目如何接入？

**Comment by mowatermelon** [comment]
> 步骤一

这边可以通过` entry`进行标记引入的js文件资源，然后在对应的`appEntry.js`，写对应实现。

```html
<script src="/appEntry.js" entry></script>
```

> 步骤二

在`appEntry.js`中写一个闭包，手动挂载对应的` application`对象，到`window`对象下。

```javascript
(()=>{
   window['your application name'] = {};
})()

```

> 步骤三

给对应的` application`对象，实现bootstrap/mount/unmount这三个函数。

```javascript
(()=>{
   const bootstrap = ()=>{};
   const mount = ()=>{};
   const unmount = ()=>{};
   window['your application name'] = {
     bootstrap,mount,unmount
  };
})();
```

**Comment by kevinPFish** [comment]
@mowatermelon 谢谢提供的思路，我尝试一下

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%AD%90%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F
