### ISSUE TITLE
项目内部路由跳转按需加载的文件无法传递cookie

### ISSUE THREAD

**Issue by PhoenixAve** [umijs/qiankun#341]
## 问题描述
注册项目时自定义了fetch方法，设置credentials为'include'，但是项目内部路由跳转页面后获取按需加载的文件时没有携带cookie
## 相关环境信息
qiankun 版本 1.4.5

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by PhoenixAve** [comment]
## 仓库地址：
https://github.com/PhoenixAve/qiankun-cookie
## 修改内容(/main/index.js)
主要就是在注册项目时传递了fetch，其他的跟仓库/example下代码一样
// 设置cookie
```javascript
document.cookie = 'name=jack;password=123'
registerMicroApps([...], {}, {
  fetch: (url) => {
      return fetch(url, {
        credentials: 'include',
        mode: 'cors'
      })
   }
})
```

**Comment by PhoenixAve** [comment]
好了

**Comment by PhoenixAve** [comment]
在"dynamicHeadAppend.ts"文件的97行中找到"execScripts"函数的调用，此时传递了三个参数，并没有传递自定义的fetch函数，所以在"execScripts"函数内部会采用"defaultFetch"，最终没有传递cookie到服务器，并且获取js文件时，content-type的值不正确，截图如下：

![image](https://user-images.githubusercontent.com/14257149/77664417-352d1000-6fb9-11ea-9a82-7764497d640b.png)

[qiankun/src/hijackers/dynamicHeadAppend.ts文件第97行](https://github.com/umijs/qiankun/blob/master/src/hijackers/dynamicHeadAppend.ts#L97)代码如下
```javascript
...
execScripts(null, [src], proxy).then(
...
)
```

[import-html-entry/src/index.js中第98行`execScripts`的定义部分](https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L98)如下
```javascript
export function execScripts(entry, scripts, proxy = window, opts = {}) {
    const { fetch = defaultFetch } = opts;
    ...
}
```
