### ISSUE TITLE
[Bug] 404页面如何判断 

### ISSUE THREAD

**Issue by dream2023** [umijs/qiankun#343]
## What happens?

当未匹配任何子应用的时候，现在是没有办法进行判断，然后跳转到404页面

## 复现步骤，错误日志以及相关配置

随便起一个微服务 , 然后url输入  `/xxxxxxxxx`

## 尝试过的方案

1、因为未匹配最终结果是 appContent === '' 和 loading === false ，所以想依据以上进行判断，结果不理想，因为正常组件渲染过程中也会出现上述两个值

2、使用一个activeRule始终为 true的子应用，一个404页面就做为1个子应用，感觉不太合适

3、监听 location 变化，另外去检测 `genActiveRule` 的返回值，感觉不是很优雅

有没有什么钩子函数能进行处理或者判断？？

**Comment by kuitos** [comment]
参考 https://github.com/umijs/qiankun/blob/master/src/prefetch.ts#L101
