### ISSUE TITLE
主项目切换登录页和主页面时使用v-if和v-show对应的问题

### ISSUE THREAD

**Issue by gudepeng** [umijs/qiankun#345]
## What happens?
主子项目都使用vue，主项目使用在自己的路由和子项目切换的时候会出现问题。
在主工程的app。vue中
<router-view v-if="!isshow" />
    <div v-else>
      <div id="router-view" v-html="content"></div>
    </div>
如果roter-view和咱们的v-html使用v-if做切换，在切换的时候如果子项目没有注销完。也就是主项目的afterunmout没执行。就会报错，没有ready。导致主项目路由失效。
如果使用v-if的话。会导致路由后的页面样式丢失。

## Context

- **qiankun Version**:1.4.3

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by gudepeng** [comment]
已解决了。是因为主项目的路由里使用了异步加载路由。改成同步就好了
