### ISSUE TITLE
父应用无法判断是否应该进入 404 page

### ISSUE THREAD

**Issue by cjfff** [umijs/qiankun#346]
## What happens?

需求是，父应用能监听每次路由跳转，并判断是否有匹配到某个路由（子应用），如果没有，则跳转 404 page。

现在只发现了一个相关的 issue 提及监听路由变化，但是并不能达到需求。

附上具体 [issue](https://github.com/umijs/qiankun/blob/master/src/prefetch.ts#L101)

如有相关的钩子，希望可以在文档中或者此处留下帮助解决方案 🙏

**Comment by kuitos** [comment]
把子应用的 base 路由录入主应用，然后主应用路由体系里自己搞个 404 路由就可以了吧

**Comment by cjfff** [comment]
@kuitos  这里解决了一个没有匹配到任何子应用的情况，但是如果 `active` 函数生效了，但是子应用的路由其实也没有匹配到，这时候就是子应用的路由体系 404 了，这时候应该怎么解决呢？

我这边的思考是，在子应用也定义一个 * 路由去兜底，然后引导到父应用的 404 page，但是这样随着应用的变多会变得耦合严重（方案修改的时候会很痛苦）

特来问问大佬有没有好的想法 ~

**Comment by kuitos** [comment]
子应用路由交给子应用自己管控
see https://github.com/umijs/qiankun/issues/339#issuecomment-604375888

**Comment by cjfff** [comment]
> 子应用路由交给子应用自己管控
> see [#339 (comment)](https://github.com/umijs/qiankun/issues/339#issuecomment-604375888)

好的，谢谢指点!
