### ISSUE TITLE
app1 wrapper with id __qiankun_subapp_wrapper_for_app_1__ not ready!

### ISSUE THREAD

**Issue by zhangfu-git** [umijs/qiankun#362]
在子应用router.replace到主应用的登录页面， 登录成功再进入到这个子应用提示:app1 wrapper with id __qiankun_subapp_wrapper_for_app_1__ not ready!

- **qiankun Version**: "^1.4.5"

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by kuitos** [comment]
closed via inactive

**Comment by liuxiuqian** [comment]
你好，这个问题解决了吗

**Comment by zhangfu-git** [comment]
@liuxiuqian 检测一下应用的name，package.json
