### ISSUE TITLE
主应用和子应用之间怎么解决跨域问题？

### ISSUE THREAD

**Issue by wisdomG** [umijs/qiankun#364]
已经成功运行了repo中的examples。
但如果我把其中一个子应用的entry改到`//location:3000`（这个端口上跑的也是一个前端服务），浏览器就会提示跨域问题，在qiankun框架下，怎么解决这个跨域问题？

虽说是配置nginx可以解决跨域问题。但我们开发环境通常不会去配nginx，有没有其他办法解决该问题？

**Comment by kuitos** [comment]
see https://github.com/umijs/qiankun/blob/master/examples/react15/webpack.config.js#L13

**Comment by maYunLaoXi** [comment]
> see https://github.com/umijs/qiankun/blob/master/examples/react15/webpack.config.js#L13

些方法无法解决页面加载后微应用里的路由点击
