### ISSUE TITLE
[Feature Request] 动态参数传递

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/qiankun#368]
## Background

qiankun能够支持动态参数传递吗？子应用接受主应用的props只在子应用mount时接收。主应用传递一个动态变量，主应用修改了变量，子应用能接收到修改吗？例如主应用切换了国际化。

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by terevor** [comment]
这种需求应该靠global event来解决吧

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/39
