### ISSUE TITLE
如何解决外部资源引用问题？

### ISSUE THREAD

**Issue by tcper** [umijs/qiankun#369]
尝试跑了一下example，在7100端口的sub-app如果引用自己的logo.svg没有问题
当它被3000端口的main加载后，原来正常引用的logo.svg会直接从3000端口路径引用，形成404

qiankun方案未来会如何解决？一切都从main网关转接静态资源？

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%AD%90%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F

**Comment by wjingxian2008** [comment]
> see https://qiankun.umijs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%AD%90%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F

老哥，这个链接里的publicpath 也解决不了angular 中img标签引入图的问题额
