### ISSUE TITLE
[求助]加载vue项目时，提示“You need to export the functional lifecycles in vue app entry”

### ISSUE THREAD

**Issue by houyaowei** [umijs/qiankun#37]
vue项目index.js写法如下：

![Jietu20190819-140601](https://user-images.githubusercontent.com/3080429/63242629-95710c00-c28a-11e9-890f-6d36afc095f1.jpg)

我是参考example中的实现。
 
错误提示如下：
![Jietu20190819-141129](https://user-images.githubusercontent.com/3080429/63242840-48da0080-c28b-11e9-816a-cbbafc499957.jpg)

这样的错误是在哪块呢？
谢谢

**Comment by houyaowei** [comment]
[补充] 有时候React项目提示如下：

![Jietu20190819-142109](https://user-images.githubusercontent.com/3080429/63243302-af135300-c28c-11e9-920e-abb2d661c407.jpg)

**Comment by kuitos** [comment]
给个可以复现的 repo？

**Comment by houyaowei** [comment]
我把demo打了个包。

https://pan.baidu.com/s/1OQNsUX_y2eI1MOxkb2fYng

**Comment by kuitos** [comment]
能 github 上建个仓库吗..

**Comment by houyaowei** [comment]
https://github.com/houyaowei/micro-frontend

**Comment by houyaowei** [comment]
> 能 github 上建个仓库吗..
帮忙看下，是不是我的webpack配置有问题
谢谢

**Comment by houyaowei** [comment]
请问在切换项目时怎么会切换两次呢？parcel版本切换时这里不再执行
![Jietu20190820-181253](https://user-images.githubusercontent.com/3080429/63338915-57e9ad00-c376-11e9-9066-8bddf7b0709a.jpg)

**Comment by kuitos** [comment]
给出重现步骤

**Comment by houyaowei** [comment]
> 给出重现步骤

就是点击项目进行切换

**Comment by kuitos** [comment]
跑不起来，缺配置
![image](https://user-images.githubusercontent.com/5206843/63852755-9c56f780-c9cb-11e9-8f3e-84b887b3536a.png)

@houyaowei

**Comment by kuitos** [comment]
close as inactive, feel free to reopen if you need.

**Comment by hqqxxf** [comment]
请问你解决了吗？我也遇到了@houyaowei
