### ISSUE TITLE
[RFC] mount 时 render 默认增加 app 参数

### ISSUE THREAD

**Issue by fantasyroot** [umijs/qiankun#370]
## 背景

> 无法获取当前 mount 的 app 的注册信息。我需要知道当前 app 信息，并在框架展示当前 app 的名称、图标等信息。

## 思路

[https://github.com/umijs/qiankun/blob/master/src/register.ts#L164](https://github.com/umijs/qiankun/blob/master/src/register.ts#L164)

` async () => render({ appContent, loading: false }),`

建议 render 的时候，把 app 也传进去：
` async () => render({ app, appContent, loading: false }),`

这样我框架层可以获取这个 props.app，做对应应用的原信息展示。

## 跟进

- [ ] render 默认多传入一个 app 参数

**Comment by kuitos** [comment]
直接在生命周期钩子里也可以获取这个信息。
![image](https://user-images.githubusercontent.com/5206843/78449403-ec5a1300-76ac-11ea-9276-5c4b693b69d3.png)

render 在 2.0 版本会被移除（当然也兼容 1.0 的用法）
