### ISSUE TITLE
[Bug]子应用之间切换报错

### ISSUE THREAD

**Issue by wisdomQiuqiu** [umijs/qiankun#373]
## What happens?
项目启动之后，各个子项目使用pushState之间的切换时，报错
从main子项目切换进入supply-chain-manage子项目，子项目之间公用了index.html
默认第一次进入的是main项目，也可以设置默认为supply-chain-manage子项目，都是可以运行，但切换就不可以
项目都是vue项目
`
[LifeCycle] after unmount main

initApp.js:34 [LifeCycle] before load supply-chain-manage

log.js:24 [HMR] Waiting for update signal from WDS...

index.js:135 error occurs while executing the entry http://localhost:6262/index.c51e1b0ad25021856fbc.js
//此js本地单独打开是可以获取到的

window.history.pushState @ single-spa.min.js:32
Project.push @ project.vue?./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--14-0!./node_modules/_babel-loader@8.1.0@babel-loader/lib!./node_modules/_ts-loader@6.2.2@ts-loader??ref--14-2!./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.9.1@vue-loader/lib??vue-loader-options:35
click @ project.vue?./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"5e450ba2-vue-loader-template"}!./node_modules/_vue-loader@15.9.1@vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/_cache-loader@4.1.0@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.9.1@vue-loader/lib??vue-loader-options:18
invokeWithErrorHandling @ vue.esm.js:1862
invoker @ vue.esm.js:2187
original._wrapper @ vue.esm.js:7555
initApp.js:37 [LifeCycle] before mount main
initApp.js:51 ErrorEvent {isTrusted: true, message: "Uncaught supply-chain-manage: Application 'supply-…NG_SOURCE_CODE: Cannot redefine property: $router", filename: "webpack:///./node_modules/single-spa/lib/esm/single-spa.min.js?", lineno: 32, colno: 4077, …}
single-spa.min.js:32 Uncaught supply-chain-manage: Application 'supply-chain-manage' died in status LOADING_SOURCE_CODE: Cannot redefine property: $router
    at Function.defineProperty (<anonymous>)
    at Function.install (webpack://supply-chain-manage-%5Bname%5D/./node_modules/_vue-router@3.1.6@vue-router/dist/vue-router.esm.js?:1248:10)
    at Function.e.use (https://unpkg.com/vue@2.6.11/dist/vue.min.js:6:37095)
    at eval (webpack://supply-chain-manage-%5Bname%5D/./node_modules/_vue-router@3.1.6@vue-router/dist/vue-router.esm.js?:2906:14)
    at Module../node_modules/_vue-router@3.1.6@vue-router/dist/vue-router.esm.js (eval at exec (webpack:///./node_modules/import-html-entry/esm/index.js?), <anonymous>:9273:1)
    at __webpack_require__ (eval at exec (webpack:///./node_modules/import-html-entry/esm/index.js?), <anonymous>:736:30)
    at fn (eval at exec (webpack:///./node_modules/import-html-entry/esm/index.js?), <anonymous>:111:20)
    at eval (webpack://supply-chain-manage-%5Bname%5D/./src/project-supply-chain-manage/router/index.ts?:10:41)
    at Object../src/project-supply-chain-manage/router/index.ts (eval at exec (webpack:///./node_modules/import-html-entry/esm/index.js?), <anonymous>:10074:1)
    at __webpack_require__ (eval at exec (webpack:///./node_modules/import-html-entry/esm/index.js?), <anonymous>:736:30)
`

## 相关环境信息
window环境
"axios": "^0.19.2",
    "compression-webpack-plugin": "^3.1.0",
    "core-js": "^3.6.4",
    "element-ui": "^2.13.0",
    "qiankun": "^1.4.5",
    "sass": "^1.26.3",
    "tiny-cookie": "^2.3.2",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "vue": "^2.6.11"

**Comment by kuitos** [comment]
提供可复现的仓库

**Comment by wisdomQiuqiu** [comment]
子项目和基层项目都是vue组合，切换就会报错
https://github.com/wisdomQiuqiu/demo

**Comment by wisdomQiuqiu** [comment]
我注意到你们的demo都是不一样的技术，很少这种所有的都一样的吧？？主要是我的项目有几个是主题一样，都是从老的vue项目迁移过来。还有一个问题就是热加载好像没有用了，需要手动刷新，有没有解决方法呢？？

**Comment by kuitos** [comment]
@eynol 看下？

**Comment by eynol** [comment]
项目有这些问题
1.设置的entry的url，有些时候访问不到html内容，需要url加上index.html
2.route设置里 有个*匹配，去掉这个，看一下规则换种写法
3.ts错误检查插件偶尔生效偶尔不生效的样子？

问题的范围是在点击导航跳到新url后，vue-router的有个ensureURL函数又给改回main/home了，导致又重新挂载了main。

**Comment by wisdomQiuqiu** [comment]
通常是因为在项目中安装了vue-router的依赖并且用Vue.use()使用了vue-router，还在index.html页面引入了vue-router.js文件。就会报这个错误。我的子项目里面的router都有一个Vue.use(VueRouter)，是否是js的问题，导致重复定义？？

**Comment by wisdomQiuqiu** [comment]
基层的那个项目，我是没有设置router的，是否是子项目的js没有做到完全的隔离？？？

**Comment by wisdomQiuqiu** [comment]
将子项目的Vue.use()与new Vue({
    store,
    // router,
    render: (h: any) => h(App)
  }).$mount('#supply-chain-manage')注释就可以了，但是没有路由也不合理呀？？？？

**Comment by daomul** [comment]
> 将子项目的Vue.use()与new Vue({
> store,
> // router,
> render: (h: any) => h(App)
> }).$mount('#supply-chain-manage')注释就可以了，但是没有路由也不合理呀？？？？

我也有一样的问题，不过是第一次打开就报错，试了下确实是注释就好。。。额

**Comment by daomul** [comment]
我是基座的项目和子项目都使用了vue-router，遇到一样的问题

**Comment by eynol** [comment]
> 基层的那个项目，我是没有设置router的，是否是子项目的js没有做到完全的隔离？？？

第一步 ，你删掉 ` *匹配`,
第二步 改一下webpack打包的sourcemap，使用的eval去跑的代码，有些串连了。我试一下改sourcemap

@kuitos 这里用不用也注入eval到sandbox里？

**Comment by wisdomQiuqiu** [comment]
能不能具体一下sourcemap修改？？

**Comment by eynol** [comment]
sourcemap的修改内容为
```
    config.output.devtoolNamespace =  【你的应用名称】,
    config.devtool = false;
  
    config.plugins.push(
      new webpack.SourceMapDevToolPlugin(
        {
          //@ts-ignore maybe deprecated
          namespace: 【你的应用名称】,
          append: `\n//# sourceMappingURL=协议://域名:${端口t}/[url]`, 👮‍♀️ 👮‍♀️这里publicPath
          filename: '[file].map',
        },
      )
    )
   config.output.[ 🚓🚓这里改下面三个
        library: `${packageName}`,
        libraryTarget: 'umd',
        jsonpFunction: `webpackJsonp_${packageName}`
],
```

改了sourcemap以后，你的父应用使用了CDN上的代码，在window上挂载了Vue，这个扩散给子应用了，所以报错

Uncaught TypeError: Cannot redefine property: $router
。

FIX ： 父应用把这些external的代码注释掉，用webpack打包，或者在代码加载后 父应用改一个名字



VueRouter 里这么写的
```javascript
if (inBrowser && window.Vue) {
  window.Vue.use(VueRouter);
}
```

**Comment by kuitos** [comment]
> @kuitos 这里用不用也注入eval到sandbox里？

这个是啥问题？

**Comment by eynol** [comment]
对了 父应用改为webpack后，initApp里要引入Vue。

issue我就关了，不是qiankun的bug，是VueRouter那三行代码的原因，还有你路由匹配的规则导致页面出不去。
