### ISSUE TITLE
[Bug]主服务跳转子应用(传统项目)指定地址失败。

### ISSUE THREAD

**Issue by mowatermelon** [umijs/qiankun#379]
## What happens?

子应用为传统应用，这边需要主项目中地址直接访问子项目中的指定html页面

## 最小可复现仓库

https://github.com/mowatermelon/test-qiankun-pureHtml

## 复现步骤，错误日志以及相关配置

- `yarn`,安装项目依赖
- `yarn dev:i`,安装父子项目依赖
- `yarn dev:s`,启动服务
- 点击`Purehtml about`，发现跳转页面错误

## 相关环境信息

- **qiankun 版本**: 1.4.5
- **浏览器版本**：Google Chrome 版本 80.0.3987.162
- **操作系统**：win 10 专业版

## 现有效果

这边指定的是`purehtml/about.html`，但是实际渲染的页面还是`purehtml/index.html`。

> main/index.html

```html
        <li onclick="push('/vue/About')">Vue</li>
        <li onclick="push('/purehtml/about.html')">Purehtml about</li>
```

> purehtml/index.html

```html
  <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
    Purehtml Example
  </div>
```

> purehtml/about.html

```html
  <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
    Purehtml Example about
  </div>
```
![image](https://user-images.githubusercontent.com/18508817/78104403-bf460000-7421-11ea-9c39-e4ebdc27382e.png)

点击路由`purehtml/about.html`，实际页面显示的是`Purehtml Example`，即实际渲染的页面还是`purehtml/index.html`的内容。

## 希望效果

点击路由`purehtml/about.html`，实际页面显示的是`Purehtml Example about`，即实际渲染的页面还是`purehtml/about.html`的内容。

![image](https://user-images.githubusercontent.com/18508817/78104611-0df39a00-7422-11ea-8dae-c8f067481198.png)

**Comment by eynol** [comment]
qiankun不是nginx ，注册的子应用是 purehtml/index.html里的内容，会执行里面的代码，这里的代码没有监听location变动，所以 purehtml/index.html的代码不会对路由变化有反应。

改变为purehtml/about.html, 会先过qiankun的规则，startWith（‘purehtml’）,然后还是挂载你注册的。

想要跳转到about.html页面，要么自己改一下激活规则，注册两个应用，单独匹配，
或者自己在index.html里用其他的方式自己去加载页面，pjax什么的

**Comment by mowatermelon** [comment]
> qiankun不是nginx ，注册的子应用是 purehtml/index.html里的内容，会执行里面的代码，这里的代码没有监听location变动，所以 purehtml/index.html的代码不会对路由变化有反应。
> 
> 改变为purehtml/about.html, 会先过qiankun的规则，startWith（‘purehtml’）,然后还是挂载你注册的。
> 
> 想要跳转到about.html页面，要么自己改一下激活规则，注册两个应用，单独匹配，
> 或者自己在index.html里用其他的方式自己去加载页面，pjax什么的

感谢回答，一朵小花.jpg

> 初步理解

这边意思是，我在`main/index.js`这样注册的子服务，不能通配`purehtml`子项目下的所有子页面吗？只是注册了`purehtml/index.html`页面？

```javascript
function genActiveRule(routerPrefix) {
  return location => location.pathname.startsWith(routerPrefix);
}

registerMicroApps(
  [
    {
      name: 'purehtml',
      entry: '//localhost:7105',
      render,
      activeRule: genActiveRule('/purehtml'),
    },
])
```

> 解法理解

如果是想要访问`purehtml/about.html`页面，应该修改`startsWith`判断，改成全等判断？这边可以通过一个服务端口注册两个子应用吗？

```javascript
function genActiveRuleEx(routerPrefix) {
  return location => location.pathname === routerPrefix;
}

registerMicroApps(
  [
    {
      name: 'purehtml',
      entry: '//localhost:7105',
      render,
      activeRule: genActiveRule('/purehtml'),
    },
    {
      name: 'purehtml-about',
      entry: '//localhost:7105',
      render,
      activeRule: genActiveRuleEx('/purehtml/about.html'),
    },
])
```

**Comment by mowatermelon** [comment]
> 疑问点

乾坤这边不是支持子应用为传统应用吗？难道如果子项目为传统应用，要给每一个子项目的页面注册一个服务？

**Comment by mowatermelon** [comment]
## 修改代码如下

> main/index.js

```javascript

function genActiveRuleEx(routerPrefix) {
  return location => location.pathname === routerPrefix;
}

registerMicroApps(
  [
    {
      name: 'purehtml-about',
      entry: '//localhost:7105',
      render,
      activeRule: genActiveRuleEx('/purehtml/about.html'),
    },
])

```

> purehtml/entry-a.js

```javascript

(global => {
  global.__POWERED_BY_QIANKUN__ || (__webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__);
  debugger;
  global['purehtml-about'] = {
    bootstrap: () => {
      console.log('purehtml-about bootstrap');
      return Promise.resolve();
    },
    mount: () => {
      console.log('purehtml-about mount');
      return Promise.resolve();
    },
    unmount: () => {
      console.log('purehtml-about unmount');
      return Promise.resolve();
    },
  };
})(window);

```


> purehtml/about.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Purehtml Example</title>
</head>
<body>
  <div style="display: flex; justify-content: center; align-items: center; height: 200px;">
    Purehtml Example about
  </div>
</body>
<script src="//localhost:7105/entry-a.js" entry></script>
</html>
```

##  报错

报错`Uncaught purehtml-about: Application 'purehtml-about' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in purehtml-about entry`

我发现我这边只注册了'purehtml-about'，但是这边点击`purehtml/about.html`路由进行跳转的时候，还是跳转的是`purehtml/index.html`

![image](https://user-images.githubusercontent.com/18508817/78113242-06d48800-7432-11ea-9c50-cdc27e1c144c.png)


## 期望 

能准确跳转到指定页面`purehtml/about.html`

**Comment by eynol** [comment]
> 乾坤这边不是支持子应用为传统应用吗？难道如果子项目为传统应用，要给每一个子项目的页面注册一个服务？

传统应用是指非React 非Vue 这样的打包好的📦bundle应用，有很多需要手动👋修改的地方。

1.子应用挂载生命周期挂载到window[你注册的应用名称] = {生命周期}
2.父应用注册时设置name为 你注册的应用名称

```
 {
      name: 'purehtml-about',
      entry: '//localhost:7105/purehtml/about.html', // 这里要具体到传统页面
      render,
      activeRule: genActiveRuleEx('/purehtml/about.html'),
    },
{
      name: 'purehtml-a',
      entry: '//localhost:7105/purehtml/index.html',
      render,
      activeRule: genActiveRuleEx('/purehtml/index.html'),
    },
```

**Comment by mowatermelon** [comment]
> > 乾坤这边不是支持子应用为传统应用吗？难道如果子项目为传统应用，要给每一个子项目的页面注册一个服务？
> 
> 传统应用是指非React 非Vue 这样的打包好的📦bundle应用，有很多需要手动👋修改的地方。
> 
> 1.子应用挂载生命周期挂载到window[你注册的应用名称] = {生命周期}
> 2.父应用注册时设置name为 你注册的应用名称
> 
> ```
>  {
>       name: 'purehtml-about',
>       entry: '//localhost:7105/purehtml/about.html', // 这里要具体到传统页面
>       render,
>       activeRule: genActiveRuleEx('/purehtml/about.html'),
>     },
> {
>       name: 'purehtml-a',
>       entry: '//localhost:7105/purehtml/index.html',
>       render,
>       activeRule: genActiveRuleEx('/purehtml/index.html'),
>     },
> ```

`/purehtml/index.html`和`purehtml/index.html`都可以正常挂载和卸载了。

疯狂撒花.gif

可以啦，可以啦，万分感谢~~~~~

![image](https://user-images.githubusercontent.com/18508817/78119886-b06c4700-743b-11ea-9765-cdd249adcb6a.png)
