### ISSUE TITLE
异步路由加载到head

### ISSUE THREAD

**Issue by chenfengjw163** [umijs/qiankun#38]
当子应用的路由为异步加载，或者子应用中有异步组件时，异步加载的js或者css加载到了head部分，当子应用卸载时是没法卸载head部分的内容的，qiankun有什么解决方案吗

**Comment by kuitos** [comment]
提供一个最小可复现的 repo？

**Comment by chenfengjw163** [comment]
repo: https://github.com/chenfengjw163/qk-demo
main文件夹为portal项目，react16为子应用，分别安装依赖后，执行yarn start or npm run start
复现步骤：
1. main、react16文件夹分别安装依赖
2.根目录执行yarn start或者npm run start
3.打开http://localhost:7099，点击页面中的page2超链接
4.查看元素，head中存在localhost:7100/Page2.chunk.js和Page2.chunk.css

造成原因：
webpack支持code split，异步加载的文件会在head中新增一个link或者script标签。当子应用卸载后head中的标签并不会被移除，js文件倒还好，css文件会造成全局污染

**Comment by kuitos** [comment]
收到，近期会支持。如果有 block 到你的开发，可以临时先把 code split 关掉，我们这边发版本后再开启

**Comment by chenfengjw163** [comment]
是否可以提供下解决思路，在qiankun还没发布前，我们可以先自己适配下

**Comment by kuitos** [comment]
如果 css 地址固定的话，可以在 unmout 阶段手动移除相关的 css 节点

**Comment by chenfengjw163** [comment]
之前考虑过一个方案，在加载子应用之前遍历head的节点，卸载子应用时，移除掉除了这些子节点以外的节点

**Comment by chenfengjw163** [comment]
#51 支持子应用code split

**Comment by peterzhai** [comment]
现在我需要将样式加载到body->header,现在的新版本全加到子应用了。而我的项目是按路由加载 同一个项目的子应用。结果删除一个子应用，一开始加载的样式没了，影响到了剩下的子应用
