### ISSUE TITLE
[Bug]子项目为requirejs项目，跳转报错require is not defined

### ISSUE THREAD

**Issue by mowatermelon** [umijs/qiankun#380]
## What happens?

子项目为requirejs项目，跳转报错require is not defined

## 最小可复现仓库

https://github.com/mowatermelon/test-qiankun-pureHtml/tree/requirejs

## 复现步骤，错误日志以及相关配置

- `yarn`,安装项目依赖
- `yarn dev:i`,安装父子项目依赖
- `yarn dev:s`,启动服务
- 点击`r-purehtml`，发现跳转报错误

## 相关环境信息

- **qiankun 版本**: 1.4.5
- **浏览器版本**：Google Chrome 版本 80.0.3987.162
- **操作系统**：win 10 专业版

## 现有效果

> main/index.html

```html
        <li onclick="push('/vue/About')">Vue</li>
        <li onclick="push('/r-purehtml')">Purehtml-r</li> 
        <li onclick="push('/r-purehtml/about.html')">Purehtml-r about</li> 
```

> r-purehtml/index.html

```html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="Cache-Control" content="no-transform" />
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="format-detection" content="telephone=no" />
  <title>测试requirejs子服务</title>
</head>

<body>
 <h1>requirejs  hello!</h1>
  
<script src="./plugins/requirejs/require.min.2.3.5.js" type="text/javascript"></script>
<script src="./config/require.config.js"></script>
<script src="./index.js"></script>

<script src="//localhost:7106/entry.js" entry></script>
</body>

</html>
```

> 错误信息

主要是为`Uncaught r-purehtml: Application 'r-purehtml' died in status LOADING_SOURCE_CODE: require is not defined`。

```html
error occurs while executing http://localhost:7106/config/require.config.js
exec @ index.js:141
schedule @ index.js:165
schedule @ index.js:170
(anonymous) @ index.js:176
(anonymous) @ index.js:175
Promise.then (async)
_execScripts @ index.js:110
execScripts @ index.js:224
(anonymous) @ register.js:163
step @ tslib.es6.js:100
(anonymous) @ tslib.es6.js:81
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
(anonymous) @ register.js:85
(anonymous) @ load.js:20
Promise.then (async)
(anonymous) @ load.js:19
Promise.then (async)
at @ load.js:10
(anonymous) @ reroute.js:78
(anonymous) @ reroute.js:77
Promise.then (async)
qt @ reroute.js:57
pt @ navigation-events.js:65
window.history.pushState @ navigation-events.js:102
push @ vue:29
onclick @ vue:19
app-errors.js:9 Uncaught r-purehtml: Application 'r-purehtml' died in status LOADING_SOURCE_CODE: require is not defined
    at Proxy.eval (eval at exec (http://localhost:7099/main.e31bb0bc.js:4354:13), <anonymous>:39:4)
    at eval (eval at exec (http://localhost:7099/main.e31bb0bc.js:4354:13), <anonymous>:41:22)
    at eval (<anonymous>)
    at exec (http://localhost:7099/main.e31bb0bc.js:4354:13)
    at schedule (http://localhost:7099/main.e31bb0bc.js:4380:9)
    at schedule (http://localhost:7099/main.e31bb0bc.js:4385:11)
    at http://localhost:7099/main.e31bb0bc.js:4391:14
    at new Promise (<anonymous>)
    at http://localhost:7099/main.e31bb0bc.js:4390:12
```

![image](https://user-images.githubusercontent.com/18508817/78105832-a12dcf00-7424-11ea-8e90-5bda733ec8af.png)

## 希望效果

点击路由`/r-purehtml`，正常加载。

**Comment by Deturium** [comment]
qiankun 执行脚本时候用了 eval
`;(function(window){;   var require;   }).bind(window)(window);` 

而 requirejs 内部依赖了 `var require;` 这样的 var 声明会把 require 变量挂载在 window 上这个行为

**Comment by Deturium** [comment]
简单的解法的话
把 requirejs 的 script 放在主应用加载即可

**Comment by mowatermelon** [comment]
> 简单的解法的话
> 把 requirejs 的 script 放在主应用加载即可


感谢解答，有些疑问点:

- 子项目这边很多页面都是有各自的通过requirejs引入的资源项，全部需要提取到主应用吗？
- 主应用这边是配置requirejs的加载吗？那requirejs这边的require.config.js也是要放到主项目？
- 如果把requirejs这边资源加载放到主应用，这边就不会和乾坤这边加载冲突了？

**Comment by Deturium** [comment]
其实就是类似 webpack 配置 external，把 requirejs 外置出去一样；把 requirejs 放主应用去加载，子应用都能共用到 require

main app
`<srcipt src="./require.min.js"></script>`

sub app
`<srcipt src="./require.config.js"></script>`

----------

或者在 requirejs 最后加一行  `window.require = require`

**Comment by Deturium** [comment]
@kuitos  有没有其他办法处理这个事情？

**Comment by kuitos** [comment]
内部自己再加一行，`window.require = require` 就可以了吧

**Comment by mowatermelon** [comment]
> window.require = require

好的 我试一下 感谢解答

**Comment by mowatermelon** [comment]
> 我在 require.min.js中添加了一行 `window.require = require`，这边require相关功能基础能用。

![image](https://user-images.githubusercontent.com/18508817/78115393-58324680-7435-11ea-98c1-c0c63cb9258a.png)

> 但是正常情况下，这边页面都是会通过require做相关资源加载。

这边虽然成功在全局输出了require对象，但是这边资源引用能力都失败了，通过路径这边访问文件时正常访问的，但是这边都报错了。

![image](https://user-images.githubusercontent.com/18508817/78118604-d09b0680-7439-11ea-9a55-5a7b9e6f314f.png)

**Comment by eynol** [comment]
```
require(['domReady!','css!@styles/index'], 👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
function () {
  console.log(11111);
  alert('345')
})


 { 
paths: {
            // 定义路径别名（统一以@开头标识表明为相对路径）👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️

            '@styles': 'http://localhost:7106/styles', 👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
            '@plugins': 'http://localhost:7106/plugins',👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
            // Require插件
            'domReady': 'http://localhost:7106/plugins/requirejs/require.domReady'
        },
        // 配置加载css解析器
        map: {
            '*': {
                'css': 'http://localhost:7106/plugins/requirejs/require.css.min.js'
            }
        },
        deps: ['css!@styles/index'],👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
        waitSeconds: 30
}


```

``` diff 
// requirejs.css.min.js
--- define()
+++ window.define()
```

```diff
// require.min.2.3.5.js
}((this), "undefined" == typeof setTimeout ? void 0 : setTimeout);
+++ this.requirejs = requirejs;
+++ this.require = require;
+++  this.define = define
```

**Comment by mowatermelon** [comment]
> ```
> require(['domReady!','css!@styles/index'], 👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
> function () {
>   console.log(11111);
>   alert('345')
> })
> 
> 
>  { 
> paths: {
>             // 定义路径别名（统一以@开头标识表明为相对路径）👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
> 
>             '@styles': 'http://localhost:7106/styles', 👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
>             '@plugins': 'http://localhost:7106/plugins',👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
>             // Require插件
>             'domReady': 'http://localhost:7106/plugins/requirejs/require.domReady'
>         },
>         // 配置加载css解析器
>         map: {
>             '*': {
>                 'css': 'http://localhost:7106/plugins/requirejs/require.css.min.js'
>             }
>         },
>         deps: ['css!@styles/index'],👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️👮‍♀️
>         waitSeconds: 30
> }
> ```
> 
> ```diff
> // requirejs.css.min.js
> --- define()
> +++ window.define()
> ```
> 
> ```diff
> // require.min.2.3.5.js
> }((this), "undefined" == typeof setTimeout ? void 0 : setTimeout);
> +++ this.requirejs = requirejs;
> +++ this.require = require;
> +++  this.define = define
> ```


成功啦，成功啦，这边修改了`requirejs.css.min.js`和`require.min.2.3.5.js`，这边`lodash`也成功输出了，样式效果也成功了，感谢耐心解答~~~~

疯狂撒花.jpg

![image](https://user-images.githubusercontent.com/18508817/78122914-faefc280-743f-11ea-8a83-1ddf28792c69.png)

**Comment by hql7** [comment]
mark

**Comment by sky124380729** [comment]
mark mark
