### ISSUE TITLE
qiankun主应用支持react-router路由和子应用路由混合使用吗？

### ISSUE THREAD

**Issue by rootsli** [umijs/qiankun#382]
如题

**Comment by RichieChoo** [comment]
官方实例跑着都报错，真是服了，阿里上百个应用都用这东西？？

**Comment by eynol** [comment]
> 官方实例跑着都报错，真是服了，阿里上百个应用都用这东西？？

跑官方demo建议切换到1.x分支，master上是2.0开发过程中，可以看项目的project了解进度。

路由的混合使用是可以实现的，要改的地方有点多，思路是：构造一个history对象，然后分别给父应用和子应用的RouteContent.Provider，建议去看React Router和history源码，在这里注入[code](https://github.com/ReactTraining/react-router/blob/926d7a4a0709d9028a2297f6dae7403761189a5f/packages/react-router/modules/Router.js#L58)。

Project中目前没有这方面的打算，微应用建议不要耦合，url只是一个状态而已。

**Comment by WuQiuYang** [comment]
> > 官方实例跑着都报错，真是服了，阿里上百个应用都用这东西？？
> 
> 跑官方demo建议切换到1.x分支，master上是2.0开发过程中，可以看项目的project了解进度。
> 
> ~路由的混合使用是可以实现的，要改的地方有点多，思路是：构造一个history对象，然后分别给父应用和子应用的RouteContent.Provider，建议去看React Router和history源码，在这里注入[code](https://github.com/ReactTraining/react-router/blob/926d7a4a0709d9028a2297f6dae7403761189a5f/packages/react-router/modules/Router.js#L58)。~
> 
> qiankun父应用和子应用在同一个url的状态之下，那个url他们是共享的，所以可以父应用是BrowserRouter，子应用是HashRouter，也可以两个都是相同的BrowserRouter。
> 
> Project中目前没有这方面的打算，微应用建议不要耦合，url只是一个状态而已。

@eynol 反之不行是吧？ 就是 父应用是HashRouter，子应用想使用BrowserRouter

**Comment by eynol** [comment]
> > > 官方实例跑着都报错，真是服了，阿里上百个应用都用这东西？？
> > 
> > 
> > 跑官方demo建议切换到1.x分支，master上是2.0开发过程中，可以看项目的project了解进度。
> > ~路由的混合使用是可以实现的，要改的地方有点多，思路是：构造一个history对象，然后分别给父应用和子应用的RouteContent.Provider，建议去看React Router和history源码，在这里注入[code](https://github.com/ReactTraining/react-router/blob/926d7a4a0709d9028a2297f6dae7403761189a5f/packages/react-router/modules/Router.js#L58)。~
> > qiankun父应用和子应用在同一个url的状态之下，那个url他们是共享的，所以可以父应用是BrowserRouter，子应用是HashRouter，也可以两个都是相同的BrowserRouter。
> > Project中目前没有这方面的打算，微应用建议不要耦合，url只是一个状态而已。
> 
> [@eynol](https://github.com/eynol) 反之不行是吧？ 就是 父应用是HashRouter，子应用想使用BrowserRouter

是可行的，但不推荐，原因是URL维护成本会升高：
1. 如果父应用 BrowserRouter, 子应用HashRouter时，子应用路由变更只改hash就可以了。
2. 反过来，如果父应用 HashRouter, 子应用 BrowserRouter 时，子应用切换，需要特殊处理URL中路径，还要保留的hash部分

为了实现 父应用 HashRouter, 子应用 BrowserRouter，为了在子应用路由切换时，保持 hash 不变，需要特殊处理 子应用使用的 History 上下文，每一步子应用的路由变更都不能让hash丢失。
