### ISSUE TITLE
如何实现常见的中后台应用标签页浏览

### ISSUE THREAD

**Issue by werts** [umijs/qiankun#384]
乾坤是个不错的产品，目前正在考虑接入。但有个问题，在中后台应用中常见的标签页浏览怎么实现呢？？
比如angular里可以使用routereusestratege，vue里可以使用keep-alive，老式的应用可以使用iframe。
如果微前端使用相同技术栈，如angular，是否有可能？

**Comment by werts** [comment]
@mowatermelon 能否进一步？多谢

**Comment by jockey100332** [comment]
> qiankun这边和UI层没有紧密关联，不会局限main的使用技术栈
但是setDefaultMountApp()会影响路由跳转，如果我在父项目中也有路由的话，那么在 入口文件中 start 就会之间跳到default 的路由中，而在路由组件里面的话子项目的根结点还没有挂载到dom中，就会查询不到

**Comment by kuitos** [comment]
duplicated with #361
