### ISSUE TITLE
[Bug]子项目为requirejs项目，跳转之后加载资源内部的方法显示未定义

### ISSUE THREAD

**Issue by mowatermelon** [umijs/qiankun#389]
## What happens?

子项目为requirejs项目，跳转之后加载资源内部的方法显示未定义

## 最小可复现仓库

https://github.com/mowatermelon/test-qiankun-pureHtml/tree/requirejs

## 复现步骤，错误日志以及相关配置

- `yarn`,安装项目依赖
- `yarn dev:i`,安装父子项目依赖
- `yarn dev:s`,启动服务
- 点击`r-purehtml`，跳转完毕，调用内部资源文件方法，提示未定义

## 相关环境信息

- **qiankun 版本**: 1.4.5
- **浏览器版本**：Google Chrome 版本 80.0.3987.162
- **操作系统**：win 10 专业版

## 现有效果

> main/index.html

```html
        <li onclick="push('/vue/About')">Vue</li>
        <li onclick="push('/r-purehtml')">Purehtml-r</li> 
```

> r-purehtml/util/common.js

```javascript
function getBaseReqUrl(){
  return 'xxxxxxx';
}
```

> r-purehtml/util/regularHelper.js

```javascript
/**
 * 返回正则测试结果的方法
 * @param {RegExp} reg  用来检测变量的正则，必选
 * @param {Any} variable  需要检测的变量值，必选
 */
function testReg(reg, variable) {
  let res = false;
  if (reg instanceof Array) {
      res = RegExp(reg[0]).test(reg[1]);
  } else {
      res = reg.test(variable);
  }
  return res;
}
/**
 * 判断变量长度是否小于某个长度的方法
 * @param {Any} variable  需要检测的变量值，必选
 * @param {Number} num  用来检测变量的长度值，必选
 */
function testLowLength(variable, num) {
  if (typeof num !== 'number' || num < 0) {
      num = 0;
  }
  return variable.length < num;
}
```

> r-purehtml/config/require.config.js

```javascript
            'common': defaultPath + '/util/common',
            'regularHelper': defaultPath + '/util/regularHelper',
```

> r-purehtml/index.js

```javascript
'use strict';

require(['lodash','common','regularHelper'],
function (_, common, regularHelper) {
  require(['domReady!', 'css!./styles/index'], function () {
    const { warn: log } = console;

    log(_);
    log(11111);
    log('getBaseReqUrl', getBaseReqUrl);
    log('guidGenerator', guidGenerator);

    log('testReg', testReg);
    log('testLowLength', testLowLength);
  })
});
```

> 错误信息

主要是为`Uncaught r-purehtml: Application 'r-purehtml' died in status LOADING_SOURCE_CODE: getBaseReqUrl is not defined`。

```bash
VM371:10 Uncaught ReferenceError: getBaseReqUrl is not defined
    at eval (eval at exec (index.js:139), <anonymous>:10:26)
    at Object.execCb (eval at exec (index.js:139), <anonymous>:6:12861)
    at b.check (eval at exec (index.js:139), <anonymous>:6:6615)
    at b.eval (eval at exec (index.js:139), <anonymous>:6:9036)
    at eval (eval at exec (index.js:139), <anonymous>:6:814)
    at eval (eval at exec (index.js:139), <anonymous>:6:9497)
    at each (eval at exec (index.js:139), <anonymous>:6:289)
    at b.emit (eval at exec (index.js:139), <anonymous>:6:9465)
    at b.check (eval at exec (index.js:139), <anonymous>:6:7174)
    at b.enable (eval at exec (index.js:139), <anonymous>:6:9363)
```

![image](https://user-images.githubusercontent.com/18508817/78226556-757f1780-74fe-11ea-8e32-1167b0577387.png)

## 希望效果

点击路由`/r-purehtml`，正常加载内部资源方法。

**Comment by eynol** [comment]
```javascript
// util.js
window.define(function(require, exports, module) {
 
       function search(){
            console.log('查js👖用法')
       }
        exports.howToUse = search
}

// index.js
require(['util'],function(util){
      util.howToUse()
})
```

**Comment by eynol** [comment]
之所以之前能够调用的原因是，在common里定义的方法挂载到全局了，所以你的子应用能够从全局访问（requirejs的会拿到js文本 然后用script标签去执行代码，所以之前的代码都在全局作用域里执行的，require一下就可以到处用了）。

qiankun这边会对子应用的js脚本拿到文本内容后用eval的方式运行，运行在一个函数的作用域里，并注入一个fakeWindow对象，那些var变量就不会挂载到window上了，这就是为啥之前要主动加两行window.require= require。

每个子应用都会有自己的fakeWindow。

fakewindow上找不到会到真的window上去找，所以父页面的window相当于是共享的。

**Comment by mowatermelon** [comment]
> 之所以之前能够调用的原因是，在common里定义的方法挂载到全局了，所以你的子应用能够从全局访问（requirejs的会拿到js文本 然后用script标签去执行代码，所以之前的代码都在全局作用域里执行的，require一下就可以到处用了）。
> 
> qiankun这边会对子应用的js脚本拿到文本内容后用eval的方式运行，运行在一个函数的作用域里，并注入一个fakeWindow对象，那些var变量就不会挂载到window上了，这就是为啥之前要主动加两行window.require= require。
> 
> 每个子应用都会有自己的fakeWindow。
> 
> fakewindow上找不到会到真的window上去找，所以父页面的window相当于是共享的。

我之前有想到 改造现有的代码 通过模块输出 方法，主要是 改造量有点大，就想先问问官方建议，感谢耐心解答。
