### ISSUE TITLE
子项目之间如何通信

### ISSUE THREAD

**Issue by Hufe921** [umijs/qiankun#39]
子项目如何通信（背景：项目仅有一个页面，页面中的各个子组件需要单独部署，独立仓库，甚至使用不同的框架），请问用现在的qiankun框架能否满足需求，之前看过single-spa（没有找到比较合适的子项目通信方案），现在的qiankun是如何做子项目之间通信的呢？感谢

![image](https://user-images.githubusercontent.com/27001251/63331069-7dbb8580-c367-11e9-8ac1-9167a98cac9a.png)

**Comment by shengbeiniao** [comment]
子项目之间通信，models的共享，貌似比较麻烦，因为切换路由应用会被卸载，我的解决方案是把涉及通信的部分由后端来处理，子应用可以把Service层暴露出去

**Comment by houyaowei** [comment]
可以用redux

**Comment by kuitos** [comment]
不要用 redux 这种耦合技术栈的方案，这样微前端的能力就直接被破坏了。应用之间通信方案可以看这篇文章的 communication 章节 https://micro-frontends.org/

**Comment by kuitos** [comment]
后续 qiankun 会提供相应的封装

**Comment by bulaye** [comment]
我的解决方案是，做一个前端eventbus，挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。

**Comment by howel52** [comment]
> 我的解决方案是，做一个前端eventbus，可以通过dll编译的方式将eventbus挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。

版本一致是走 cdn 么？不走 cdn 的话 eventbus 一升级，所有 slave 都得升级，系统一多难免会有纰漏。

我们这边的思路是封装了一个单例的 qiankun-bridge，实例挂在 window 上，提供 handler 单向通信 与 events 发布订阅。

**Comment by bulaye** [comment]
> > 我的解决方案是，做一个前端eventbus，可以通过dll编译的方式将eventbus挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。
> 
> 版本一致是走 cdn 么？不走 cdn 的话 eventbus 一升级，所有 slave 都得升级，系统一多难免会有纰漏。
> 
> 我们这边的思路是封装了一个单例的 bridge，实例挂在 window 上，提供 handler（单向通信） 与 events （发布订阅）。

我这边生产上还是会使用master window下挂载的eventbus进行master-slave间通信；只是在开发阶段，不会去起master的壳，那slave中也需要一个eventbus

封装一个单例bridge，也避免不了这个bridge升级影响slave和master吧，或许我还理解不够深

ps：我从https://zhuanlan.zhihu.com/p/80776391 这个链接了解到这个项目，关于样式隔离那，如果考虑一个页面上同时显示多个slave，那这种样式隔离就没效果了吧；

目前在搞js沙箱，在学习你们的项目，希望能够多多交流，感谢大佬的回复

**Comment by howel52** [comment]
> master

单例能够保证的是调试的时候会比较好还原，各个 Salve 及 Master 能够确保调用到的实例方法一定是某个确切版本的。   非单例可能造成 Salve A 调的 v1.0.1 Slave B 调的 v1.0.2。   至于说 bridge 升级影响的问题，理论上只要保持 master 依赖的 bridge 是最新版，根据加载 qiankun 的 slave 加载顺序可以得出，master 上 new bridge 会被最新执行，那么各 salve 调用到的 bridge 一定是同一个可用版本；

如果是破坏性特别大的 breaking change，比如某个核心实例方法去除了，那需要 slave 业务代码也做升级。

**Comment by howel52** [comment]
> 我的解决方案是，做一个前端eventbus，可以通过dll编译的方式将eventbus挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。

有个比较明显的坑是：Master 想 emit 一个事件给 Slave， 但 Slave 是异步的，在没有 mount 前收不到 master emit 的事件，这就得在 sdk 或者你说的 eventbus 里维护一个事件锁与事件队列，等 slave mount 后再将队列里的事件按序补推；

**Comment by bulaye** [comment]
> > 我的解决方案是，做一个前端eventbus，可以通过dll编译的方式将eventbus挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。
> 
> 有个比较明显的坑是：Master 想 emit 一个事件给 Slave， 但 Slave 是异步的，在没有 mount 前收不到 master emit 的事件，这就得在 sdk 或者你说的 eventbus 里维护一个事件锁与事件队列，等 slave mount 后再将队列里的事件按序补推；

确实有这个坑，目前的做法是一分为二，认为如果又在slave在mount前，master想传递数据给slave的情况，那么把数据作为slave初始化参数处理，mount后的数据交互再走事件。。。

想问你们这边的bridge怎么解决这种情况的，只有handler（单向通信） 与 events （发布订阅），没有事件补发能解决问题吗

**Comment by howel52** [comment]
> > > 我的解决方案是，做一个前端eventbus，可以通过dll编译的方式将eventbus挂载到window下，master和slave在开发阶段保证eventbus版本一致，在运行时就不会出错，不知道这样会不会有坑。。。
> > 
> > 
> > 有个比较明显的坑是：Master 想 emit 一个事件给 Slave， 但 Slave 是异步的，在没有 mount 前收不到 master emit 的事件，这就得在 sdk 或者你说的 eventbus 里维护一个事件锁与事件队列，等 slave mount 后再将队列里的事件按序补推；
> 
> 确实有这个坑，目前的做法是一分为二，认为如果又在slave在mount前，master想传递数据给slave的情况，那么把数据作为slave初始化参数处理，mount后的数据交互再走事件。。。
> 
> 想问你们这边的bridge怎么解决这种情况的，只有handler（单向通信） 与 events （发布订阅），没有事件补发能解决问题吗

对与这种场景，我认为 master 与 salve 最好不要耦合的太紧密，因为对 master 或 slave 自身而言，应该只需要关注 发布/订阅 背后的业务逻辑

举例：在 Slave A 中点击 Master 上的一个 Button 从而跳转到 Salve B，就这种场景而言实际上可以包含不只一个「事件」：
1. onClick button 后唤醒 Salve B balabla
2. Salve B 被 button 唤醒后 emit 一个事件告诉 Master balabala
3. 等等等等

那么这些事件之间除了数据/参数 以外，事件的先后顺序也必须保持一致。对于业务代码而言，不应该关注这些细节，这些细节就可以在 bridge 处抹平，假装是个 slave 的 mount 是个同步的，同时假装 emit 的事件不会丢（不丢数据，也不丢顺序）

参照：https://github.com/howel52/qiankun-bridge/blob/378a3d1456b8f1fc8ddaa30fcc827c7c2600efdf/src/QiankunBridge.ts#L95

**Comment by howel52** [comment]
不急的话可以等一波 qiankun 官方的通信机制 @bulaye

**Comment by bulaye** [comment]
> 不急的话可以等一波 qiankun 官方的通信机制 @bulaye

好的，感谢

**Comment by wusp1994** [comment]
弱弱的问一句，子应用和主应用 现在能通信了？

**Comment by hql7** [comment]
2.0大概什么时间发布，目前项目正在方案考察阶段，马上就要立项了

**Comment by mayako21126** [comment]
简单列一下我自己整理实践的各种通信方式，抛砖引玉吧
Custom Event，DOM Event，Web Worker，这三类都是用浏览器的本身api，耦合小。url通信走的是路由那套，还有就是走发布订阅那套。
我这边的解决方式是写了一个[bridge](https://github.com/mayako21126/wex)，挂载在window上，拿登录来说，Slave根据环境判断是独立运行还是走元框架(master)，走master就调用master的登录组件来登录(我们是用svelte写的共同组件)，通过bridge获取到登录信息作为输入源。反之则调用Slave的登录组件获取登录信息作为输入源。对于登录方法而言，无非是传参不同罢了，其它表现是一致的。真要是马上立项的可以自己先选用上述几种方式临时过渡
![image](https://user-images.githubusercontent.com/15900776/71958498-694f2b00-322b-11ea-81d5-086d693afa20.png)

**Comment by jruif** [comment]
自己简单处理的话，使用`发布订阅`可能比较合适，或者还有基于本地存储系统的、还可以基于custom event的，现在浏览器支持也比较好了
![image](https://user-images.githubusercontent.com/4211238/72682211-a78afb00-3b05-11ea-986c-0e60762dacb1.png)

具体怎么用看各自需求来处理

**Comment by FireLiujie** [comment]
是否能够使用localStorage进行通信呢？

**Comment by zhiguangphoenix** [comment]
> 是否能够使用localStorage进行通信呢？

可以是可以，但是感觉跟其他的方法区别不太大😅

**Comment by kuitos** [comment]
@dbkillerf6 来看看

**Comment by dbkillerf6** [comment]
> @dbkillerf6 来看看

可以 check 一下这样是否 OK：https://github.com/umijs/qiankun/pull/412

**Comment by pgp-account** [comment]
请问是怎么实现多个子应用同时展示在一个页面的呢

**Comment by github1025** [comment]
> 请问是怎么实现多个子应用同时展示在一个页面的呢

// singular:false 同时激活2个应用
start({singular: false})
