### ISSUE TITLE
ts文件 useRootExports 找不到该模块

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#390]
## What happens?
1.提示找不到模块，项目ts版本的，现在直接修改该文件为js是不报错的
![image](https://user-images.githubusercontent.com/13429648/78234124-4c17b900-7509-11ea-816b-24b1b079e569.png)
2. 发现rootExports文件不能为.ts

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by xileliu** [comment]
![image](https://user-images.githubusercontent.com/13429648/78234297-8f722780-7509-11ea-811c-39ceda164cda.png)
gu官网的也一样

**Comment by kuitos** [comment]
提供基本的版本信息

**Comment by xileliu** [comment]
> 提供基本的版本信息

"@umijs/plugin-qiankun": "^1.5.4",
"umi": "^2.9.0",
"umi-plugin-react": "^1.8.0",
"umi-types": "^0.3.0"

**Comment by kuitos** [comment]
page/.umi 目录删了然后重试下

**Comment by xileliu** [comment]
> page/.umi 目录删了然后重试下

删掉也不行
1.如果文件修改成rootExports.js
![image](https://user-images.githubusercontent.com/13429648/78314403-71014000-758c-11ea-9307-34fc29053dad.png)

2.如果文件修改成rootExports.ts
![image](https://user-images.githubusercontent.com/13429648/78314466-9ee68480-758c-11ea-9203-465dba59b59b.png)

**Comment by xileliu** [comment]
@kuitos

**Comment by kuitos** [comment]
released v1.5.5
