### ISSUE TITLE
[Feature Request] 子项目能当做主项目再注册子项目吗

### ISSUE THREAD

**Issue by crazyair** [umijs/qiankun#394]
## Background

子项目能当做主项目再注册子项目吗？用 @umijs/plugin-qiankun 的仓库，新建个 app4，让它当做 app2 的子项目，最后测试报错。
![image](https://user-images.githubusercontent.com/7971419/78345814-c0695f80-75d0-11ea-8c26-3196de4660b5.png)
是不是一个 qiankun 只能有一个 master ？

## Proposal

-

## Additional context

-

**Comment by crazyair** [comment]
父、子项目导出的都是 `qiankun `。

**Comment by kuitos** [comment]
报错信息提示的很明显了

**Comment by crazyair** [comment]
> 报错信息提示的很明显了

要不要支持，跟 react-router 一样，无限极嵌套，children 下渲染子组件，qiankun 用 rouer 匹配跟 react-router 有异曲同工之妙。

**Comment by crazyair** [comment]
> 报错信息提示的很明显了

报错信息不重要，也不是这个原因报的错，主要是，有没有考虑子项目也可以当做主项目再注册子项目。

**Comment by kuitos** [comment]
可以通过主应用把 registerMicroApps 方法传给子应用，子应用再调这个方法注册新的子应用。

> 要不要支持，跟 react-router 一样，无限极嵌套，children 下渲染子组件，qiankun 用 rouer 匹配跟 react-router 有异曲同工之妙。

路由嵌套也是所有的路由共用一个 react-router，而不是一个路由使用一个 react-router 实例。

**Comment by crazyair** [comment]
现在子项目 app.ts 导出 qiankun 好像跟主项目导出名称相同。
透传给子应用，确实是用一个 react-router 实例，可以这样做。
其实还有个问题，子项目 base 为 a 那他在当 另外一个子项目的子项目，这个 base 不能改，有问题啊？

**Comment by kuitos** [comment]
最新版本 umi plugin 已经支持
