### ISSUE TITLE
子项目热加载问题

### ISSUE THREAD

**Issue by wisdomQiuqiu** [umijs/qiankun#395]
当子项目进行开发的时候，需要主动的浏览器刷新，重新载入项目。是否可以配置增加热加载？

**Comment by kuitos** [comment]
子应用可以独立开发，不用非得在主应用中看效果 see https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E7%8B%AC%E7%AB%8B%E8%BF%90%E8%A1%8C%E5%AD%90%E5%BA%94%E7%94%A8%EF%BC%9F

**Comment by Bonnie8ni** [comment]
請問如果不一定要在主應用看效果
那資料流在父子之間要如何傳遞

**Comment by bacy** [comment]
> 請問如果不一定要在主應用看效果
> 那資料流在父子之間要如何傳遞

一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面

**Comment by Bonnie8ni** [comment]
> > 請問如果不一定要在主應用看效果
> > 那資料流在父子之間要如何傳遞
> 
> 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面

我還是不太明白 ....
若不啟動主應用，那共享的數據storage或者cookie如何寫入

例如說我的父應用上有個切換多國語系的功能
我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
父應用如果切換多國語系就從新導入一次子應用嗎?

**Comment by bacy** [comment]
> > > 請問如果不一定要在主應用看效果
> > > 那資料流在父子之間要如何傳遞
> > 
> > 
> > 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面
> 
> 我還是不太明白 ....
> 若不啟動主應用，那共享的數據storage或者cookie如何寫入
> 
> 例如說我的父應用上有個切換多國語系的功能
> 我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
> 父應用如果切換多國語系就重新導入一次子應用嗎?

你说的这种属于父子间通信，目前还不在这个框架处理范围，后续也许乾坤会自带解决方案。目前只能靠你自己解决，比如你主项目写storage，可以在子项目监听storage改变的event啊。你甚至可以在注册的时候，把主项目的实例传到子项目（registerXX的最后一个参数），这样数据共享就更方便了

**Comment by Bonnie8ni** [comment]
> > > > 請問如果不一定要在主應用看效果
> > > > 那資料流在父子之間要如何傳遞
> > > 
> > > 
> > > 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面
> > 
> > 
> > 我還是不太明白 ....
> > 若不啟動主應用，那共享的數據storage或者cookie如何寫入
> > 例如說我的父應用上有個切換多國語系的功能
> > 我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
> > 父應用如果切換多國語系就重新導入一次子應用嗎?
> 
> 你说的这种属于父子间通信，目前还不在这个框架处理范围，后续也许乾坤会自带解决方案。目前只能靠你自己解决，比如你主项目写storage，可以在子项目监听storage改变的event啊。你甚至可以在注册的时候，把主项目的实例传到子项目（registerXX的最后一个参数），这样数据共享就更方便了

你說的兩個方式我有試過

1. 主項目寫入 storage，子項目在 componentDidMount 監聽 storage
問題點：子項目只有在第一次時可以得到 storage，當主項目set storage後，子項目並沒有更新，沒有生命週期可以判斷  storage 改變，無法在不刷新頁面的情況下重新得到 storage。

2. 主項目傳遞到子項目
問題點：測試過後，主項目也是只有第一次將 storage 傳進子項目，當主項目更改後 storage，主項目的生命週期並沒有把 storage 重新帶給子項目。
　
因為我的主項目與子項目是在同一頁，不知道還有什麼方式可以做得到，我目前想的到的是如果切換語言就重新載入一次子項目，但我不知道這樣做法是否正確？還是有其他方式 ...
　
謝謝你的回答，我很感動

**Comment by bacy** [comment]
> > > > > 請問如果不一定要在主應用看效果
> > > > > 那資料流在父子之間要如何傳遞
> > > > 
> > > > 
> > > > 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面
> > > 
> > > 
> > > 我還是不太明白 ....
> > > 若不啟動主應用，那共享的數據storage或者cookie如何寫入
> > > 例如說我的父應用上有個切換多國語系的功能
> > > 我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
> > > 父應用如果切換多國語系就重新導入一次子應用嗎?
> > 
> > 
> > 你说的这种属于父子间通信，目前还不在这个框架处理范围，后续也许乾坤会自带解决方案。目前只能靠你自己解决，比如你主项目写storage，可以在子项目监听storage改变的event啊。你甚至可以在注册的时候，把主项目的实例传到子项目（registerXX的最后一个参数），这样数据共享就更方便了
> 
> 你說的兩個方式我有試過
> 
> 1. 主項目寫入 storage，子項目在 componentDidMount 監聽 storage
>    問題點：子項目只有在第一次時可以得到 storage，當主項目set storage後，子項目並沒有更新，沒有生命週期可以判斷  storage 改變，無法在不刷新頁面的情況下重新得到 storage。
> 2. 主項目傳遞到子項目
>    問題點：測試過後，主項目也是只有第一次將 storage 傳進子項目，當主項目更改後 storage，主項目的生命週期並沒有把 storage 重新帶給子項目。
>    　
>    因為我的主項目與子項目是在同一頁，不知道還有什麼方式可以做得到，我目前想的到的是如果切換語言就重新載入一次子項目，但我不知道這樣做法是否正確？還是有其他方式 ...
>    　
>    謝謝你的回答，我很感動

放假还这么拼。。。
`if (window.addEventListener) {
    window.addEventListener("storage", handleStorage, false);
} else {
    window.attachEvent("onstorage", handleStorage);
}`
监听是用window的eventlistener，不是react或者vue的响应式。主子应用没有跨域的话，应该是能监听到的。

**Comment by Bonnie8ni** [comment]
> > > > > > 請問如果不一定要在主應用看效果
> > > > > > 那資料流在父子之間要如何傳遞
> > > > > 
> > > > > 
> > > > > 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面
> > > > 
> > > > 
> > > > 我還是不太明白 ....
> > > > 若不啟動主應用，那共享的數據storage或者cookie如何寫入
> > > > 例如說我的父應用上有個切換多國語系的功能
> > > > 我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
> > > > 父應用如果切換多國語系就重新導入一次子應用嗎?
> > > 
> > > 
> > > 你说的这种属于父子间通信，目前还不在这个框架处理范围，后续也许乾坤会自带解决方案。目前只能靠你自己解决，比如你主项目写storage，可以在子项目监听storage改变的event啊。你甚至可以在注册的时候，把主项目的实例传到子项目（registerXX的最后一个参数），这样数据共享就更方便了
> > 
> > 
> > 你說的兩個方式我有試過
> > 
> > 1. 主項目寫入 storage，子項目在 componentDidMount 監聽 storage
> >    問題點：子項目只有在第一次時可以得到 storage，當主項目set storage後，子項目並沒有更新，沒有生命週期可以判斷  storage 改變，無法在不刷新頁面的情況下重新得到 storage。
> > 2. 主項目傳遞到子項目
> >    問題點：測試過後，主項目也是只有第一次將 storage 傳進子項目，當主項目更改後 storage，主項目的生命週期並沒有把 storage 重新帶給子項目。
> >    　
> >    因為我的主項目與子項目是在同一頁，不知道還有什麼方式可以做得到，我目前想的到的是如果切換語言就重新載入一次子項目，但我不知道這樣做法是否正確？還是有其他方式 ...
> >    　
> >    謝謝你的回答，我很感動
> 
> 放假还这么拼。。。
> `if (window.addEventListener) { window.addEventListener("storage", handleStorage, false); } else { window.attachEvent("onstorage", handleStorage); }`
> 监听是用window的eventlistener，不是react或者vue的响应式。主子应用没有跨域的话，应该是能监听到的。

對，我是用這種方式監聽，但是監聽不到更新 Q_Q
他應該要塞在子應用的哪裏，因為塞在生命週期裡，無法觸發生命週期
（我是用 react 寫）

**Comment by wisdomQiuqiu** [comment]
我想到的只能手动写一个固定的数据在子项目里面，但是如果这个项目是需要登录的，token没办法作假。还是需要自己手动的设置吧。还是比较麻烦的

**Comment by mayako21126** [comment]
> > > > > > > 請問如果不一定要在主應用看效果
> > > > > > > 那資料流在父子之間要如何傳遞
> > > > > > 
> > > > > > 
> > > > > > 一般情况，子项目应该是相对独立的。共享的数据也应该在storage或者cookie里面
> > > > > 
> > > > > 
> > > > > 我還是不太明白 ....
> > > > > 若不啟動主應用，那共享的數據storage或者cookie如何寫入
> > > > > 例如說我的父應用上有個切換多國語系的功能
> > > > > 我要如何讓子應用知道父應用已將多國語系切換(寫在storage或cookie)
> > > > > 父應用如果切換多國語系就重新導入一次子應用嗎?
> > > > 
> > > > 
> > > > 你说的这种属于父子间通信，目前还不在这个框架处理范围，后续也许乾坤会自带解决方案。目前只能靠你自己解决，比如你主项目写storage，可以在子项目监听storage改变的event啊。你甚至可以在注册的时候，把主项目的实例传到子项目（registerXX的最后一个参数），这样数据共享就更方便了
> > > 
> > > 
> > > 你說的兩個方式我有試過
> > > 
> > > 1. 主項目寫入 storage，子項目在 componentDidMount 監聽 storage
> > >    問題點：子項目只有在第一次時可以得到 storage，當主項目set storage後，子項目並沒有更新，沒有生命週期可以判斷  storage 改變，無法在不刷新頁面的情況下重新得到 storage。
> > > 2. 主項目傳遞到子項目
> > >    問題點：測試過後，主項目也是只有第一次將 storage 傳進子項目，當主項目更改後 storage，主項目的生命週期並沒有把 storage 重新帶給子項目。
> > >    　
> > >    因為我的主項目與子項目是在同一頁，不知道還有什麼方式可以做得到，我目前想的到的是如果切換語言就重新載入一次子項目，但我不知道這樣做法是否正確？還是有其他方式 ...
> > >    　
> > >    謝謝你的回答，我很感動
> > 
> > 
> > 放假还这么拼。。。
> > `if (window.addEventListener) { window.addEventListener("storage", handleStorage, false); } else { window.attachEvent("onstorage", handleStorage); }`
> > 监听是用window的eventlistener，不是react或者vue的响应式。主子应用没有跨域的话，应该是能监听到的。
> 
> 對，我是用這種方式監聽，但是監聽不到更新 Q_Q
> 他應該要塞在子應用的哪裏，因為塞在生命週期裡，無法觸發生命週期
> （我是用 react 寫）

[子项目之间如何通信](https://github.com/umijs/qiankun/issues/39) 联动这个，你的问题在于如何进行应用间通信，拿你的语言切换举例。在官方未发布2.0之前我们可以通过任意一个简易小巧的发布订阅库来做临时处理，我们这是拿了一个之前处理小程序状态处理来写的[wex](https://github.com/mayako21126/wex)的进行处理，先在父应用上构建一个store
![image](https://user-images.githubusercontent.com/15900776/78743590-a2657b80-7991-11ea-81f5-d73e875c0d46.png)
然后编写对应的Mutation
![image](https://user-images.githubusercontent.com/15900776/78743613-b4471e80-7991-11ea-8012-d45da05a72b3.png)
在父应用语言变化时
![image](https://user-images.githubusercontent.com/15900776/78743681-e48ebd00-7991-11ea-8321-e4f613a2c54e.png)
子应用前提是自身功能完整可独立运行。在其语言组件里加入
![image](https://user-images.githubusercontent.com/15900776/78743769-27509500-7992-11ea-9213-e3b818f15e63.png)
让其能响应父应用的数据发布，并调用子应用自身语言库的语言切换事件即可

**Comment by Lining1108** [comment]
可以看看[wl-micro-frontends](https://github.com/hql7/wl-micro-frontends)，这里作者 @hql7 使用了rxjs实现主、子应用之间动态通信，实时监听

**Comment by Bonnie8ni** [comment]
> mayako21126
我一直不成功，可能是因為我的資料流是寫 redux-saga?
謝謝你提供方式，我去試試 ><

> Lining1108 
這個教學好完整，我試試看在 react 要怎麼實現
謝謝 lining :)

**Comment by zxh1307** [comment]
点赞

**Comment by kuitos** [comment]
duplicated with #340

**Comment by stoneChen** [comment]
关键还是识别entry js的问题，热当子应用的任意运行时文件变更后，子应用html后边会插入类似xxx.hot-update.js这样的script。此时主应用再去加载这个子应用会把xxx.hot-update.js识别为入口js，导致生命周期方法找不到。

qiankun提供了entry标记来识别主入口，可以使用这个插件https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates
webpack配置关键点：
```js
//...
plugins: [
      // Generates an `index.html` file with the <script> injected.
      new HtmlWebpackPlugin(
        // 省略...
      ),
      new ScriptExtHtmlWebpackPlugin({
        custom: {
          test: /bundle\.js$/, // 这个正则根据你的输出js名而定
          attribute: 'entry'
        }
      }),
]
```
重启子应用，然后子应用就可以开启热加载开发，并在主应用下预览了。
![image](https://user-images.githubusercontent.com/4470552/86529279-13a9c180-bee2-11ea-8c2d-5105d391bf19.png)

**Comment by humorHan** [comment]
> 关键还是识别entry js的问题，热当子应用的任意运行时文件变更后，子应用html后边会插入类似xxx.hot-update.js这样的script。此时主应用再去加载这个子应用会把xxx.hot-update.js识别为入口js，导致生命周期方法找不到。
> 
> qiankun提供了entry标记来识别主入口，可以使用这个插件https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates
> webpack配置关键点：
> 
> ```js
> //...
> plugins: [
>       // Generates an `index.html` file with the <script> injected.
>       new HtmlWebpackPlugin(
>         // 省略...
>       ),
>       new ScriptExtHtmlWebpackPlugin({
>         custom: {
>           test: /bundle\.js$/, // 这个正则根据你的输出js名而定
>           attribute: 'entry'
>         }
>       }),
> ]
> ```
> 
> 重启子应用，然后子应用就可以开启热加载开发，并在主应用下预览了。
> ![image](https://user-images.githubusercontent.com/4470552/86529279-13a9c180-bee2-11ea-8c2d-5105d391bf19.png)

不是很明白。我的情况是这样的，不想启动主应用，所以主应用是域名地址，某个query参数下会加载本地localhost的子应用，这样的情况应该如何支持子应用修改的热更新？

**Comment by humorHan** [comment]
> 子应用可以独立开发，不用非得在主应用中看效果 see https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E7%8B%AC%E7%AB%8B%E8%BF%90%E8%A1%8C%E5%AD%90%E5%BA%94%E7%94%A8%EF%BC%9F

这样用不了主子应用的通信了吧，如果主应用获取鉴权等信息，子应用咋获取

**Comment by zhujun24** [comment]
@kuitos "子应用可以独立开发，不用非得在主应用中看效果"，如果不太方便独立开发子应用，需要在主应用中看效果，有整合webpack-hot-middleware类似的热更新方案吗？
