### ISSUE TITLE
localStorage 或 cookie 在父應用與子應用之間如何通訊

### ISSUE THREAD

**Issue by Bonnie8ni** [umijs/qiankun#397]
專案是使用 create-react-app 建立
我的父應用與子應用在同一個頁面
我有一個 i18n 的功能寫在父應用，他會把 key 值寫入 localstorage
但在切換此功能時，要如何將新的 key 值提供給子應用？

我有試過使用 registerMicroApps props 傳入
但切換語言時，不會再次傳入

**Comment by kuitos** [comment]
主应用的上下文跟子应用是共享的，子应用直接取 localStorage 就可以了

**Comment by Bonnie8ni** [comment]
可是父應用更新localStorage的時候
子應用不會重新更新
（父應用跟子應用在同一個頁面）

**Comment by Bonnie8ni** [comment]
> 主应用的上下文跟子应用是共享的，子应用直接取 localStorage 就可以了

可是父應用更新localStorage的時候
子應用不會重新更新
（父應用跟子應用在同一個頁面）

**Comment by Bonnie8ni** [comment]
![image](https://user-images.githubusercontent.com/15052151/78420322-94a5b280-7680-11ea-9331-698124f141e7.png)

像這樣藍色區域是主應用，上面有切換語系的功能
紅色區域是子應用
我要如何在主應用切換語系時
觸發子應用也更新呢？
