### ISSUE TITLE
支持异步启动~

### ISSUE THREAD

**Issue by lucasleelz** [umijs/qiankun#399]
#225  What happens?

有一些场景子应用的需要挂载的 mountElementId 节点是有主应用异步生成的，如果在节点生成之前子应用就已经启动的话，会造成 Target dom is not container 异常

这个功能是否应该放在`qiankun`中，而不是放在`umi-plugin-qiankun`?
项目仅仅是想使用`qiankun`而不是一整套`umijs`
## 相关环境信息

- **qiankun 版本** 1.4.5
- **浏览器版本**：版本 79.0.3945.117（正式版本） （64 位）
- **操作系统**：MacOS 10.15.4

**Comment by kuitos** [comment]
umi-plugin-qiankun 也是基于 qiankun 的。

在合适的时机调用 [start](https://qiankun.umijs.org/zh/api/#start-opts) 方法就可以了。

**Comment by lucasleelz** [comment]
好
