### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by houyhea** [umijs/qiankun#4]
不错的项目！提一些小疑问：
1. 支持angularjs 1.x的接入吗？
1. 采用proxey做沙箱，是不是不考虑稍微低版本的不支持proxey语法的浏览器？
1. 已经在阿里内部生产环境使用了吗？

**Comment by kuitos** [comment]
1. 支持
2. 是的，暂不支持，如果需求大后续会考虑
3. 是先在内部上线了一些产品实践过才开源的😀

**Comment by chenkan** [comment]
补充一下：
3. 已经在阿里内部生产环境使用了吗？
（已经规模化生产环境使用）
