### ISSUE TITLE
[Feature Request] 区分 console 的宿主

### ISSUE THREAD

**Issue by howel52** [umijs/qiankun#40]
## Background
目前 Master 与 Slave 的 runtime log 都混在控制台里, 没有做区分, 无法直观的感受到某个 log 记录是哪个应用打的

## Proposal
Proxy Console, 在 master runtime 里使用 console.log('foo'), 实际打印为 'Master: foo', 在 Salve runtime 下使用 console.log('bar')，实际打印为 '[SlaveName]: bar'

不过，该如何区分这个 Proxy 呢？  两者都是从同一  window 里拿的 Console，包括像 Sentry 类的工具也会复写 console.error，不知有没有好的解决方案。

**Comment by kuitos** [comment]
有一个疑问，log 应该只应该开发阶段才有吧，线上应用不应该还有很多 log 吧

**Comment by howel52** [comment]
> 有一个疑问，log 应该只应该开发阶段才有吧，线上应用不应该还有很多 log 吧

是的

**Comment by kuitos** [comment]
开发体验的提升可以作为下一阶段的重点目标来做

**Comment by howel52** [comment]
简单写了一下，还是遇到了一楼的说的那个问题；  对 jsSandbox 中的 console 做了一层 Proxy,  子应用之间可以区分出来，但是此时 Master 上的 log 也会走这个 proxy；

如图所示：
![proxy-console.gif](https://i.loli.net/2019/08/27/CTLa3iNdrOJbclh.gif)

代码可见:
https://github.com/howel52/qiankun/commit/e0b429f71f7cbde7cb008fa24d84c43a5033f1f4

**Comment by bulaye** [comment]
开发的时候是不是不应该感觉到这个app是slave，runtime时才决定某一个app是slave

**Comment by howel52** [comment]
> 开发的时候是不是不应该感觉到这个app是slave，runtime时才决定某一个app是slave

这个看怎么理解这个开发了

对于某个业务 slave 的 feature 开发而言，它在开发过程中可能确实不需要关注 master，甚至不需要启 master 的壳。

但 feature 开发完后，应该还是会在本地起一个 master 看下是否符合预期（因为只有在 local master 里，表现才与 test、production 一模一样）

我们这边目前本地开发都会套在 master 里，master 上的一些 service component 本身自带 test log，这样会导致 log 很多，无法专注于某个 slave 的 log.
