### ISSUE TITLE
子应用路由跳转报错

### ISSUE THREAD

**Issue by jiang-24-gdufs** [umijs/qiankun#401]
## What happens?

node_modules/_history4.10.1@history/esm/history.js 中#517行, 子项目的路由跳转时window.location 有时候会被赋值为 href 字符串, 执行 ```var href = window.location.href;```返回undefind导致后续基于 href 字符串的操作统统报错

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
这个不是 qiankun 的问题。

有需要帮助可以随时 reopen 并提供可复现仓库。
