### ISSUE TITLE
2.0大概什么时间段发布？

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#403]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
4.13 发布

**Comment by Clive-Wang** [comment]
发布了吗？npm怎么升级啊？还是V1.4.5版本
