### ISSUE TITLE
子应用与子应用组件共享复用

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#404]
## What happens?

子应用的带有业务属性的组件能在其他子应用中共享吗？qiankun 2.0 会支持这样的功能吗？
案例：
app1 => 子应用中 <demo config={a:1}> 组件需要共享复用，在app2 子应用中类似import demo from '...'; 方式调用在app2子应用中传送数据config展示渲染？
基于这种场景qiankun 2.0 能够支持吗？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by terevor** [comment]
这个更像webpack5的ModuleFederation适用的场景

**Comment by eynol** [comment]
可以做到啊，首先把你需要共享的代码，抽取出独立的仓库，打包成library，然后在父应用中加载，这样代码就能从window[你的lirbary名称]获取到了，子应用也可以获取到。

如果你说的是Module Federation这样的方式共享，直接在源码层面，那需要qiankun写插件什么的了。

**Comment by eynol** [comment]
https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E6%8F%90%E5%8F%96%E5%87%BA%E5%85%AC%E5%85%B1%E7%9A%84%E4%BE%9D%E8%B5%96%E5%BA%93%EF%BC%9F

**Comment by mayako21126** [comment]
依靠框架解决这个问题最终又将提高父子应用耦合，个人认为子应用是要满足[SCS](http://scs-architecture.org/)这一特性的，你提出的这个问题应该要从工程体系层面上解决。
根据你的描述你其实需要的是一个业务组件中台，从这个角度来想的你可以参考下OpenComponents，npm私包甚至更极端点的你也可以考虑用svelte之类的去写全通用组件。通过建设中台去完成你的业务组件复用。微前端从现在看它必然是一个系统而不是单单一个框架

**Comment by xileliu** [comment]
> 可以做到啊，首先把你需要共享的代码，抽取出独立的仓库，打包成library，然后在父应用中加载，这样代码就能从window[你的lirbary名称]获取到了，子应用也可以获取到。
> 
> 如果你说的是Module Federation这样的方式共享，直接在源码层面，那需要qiankun写插件什么的了。

业务组件可能富有很多业务逻辑在里面，你说的大概就是单独包npm的方式，这样开发调试是个问题

**Comment by howel52** [comment]
这种父子之间的强耦合感觉不是很合适

**Comment by xileliu** [comment]
> 适

如果按照每个业务组件单独在项目里build libary 文件方式，系统目前是umijs 创建似乎不支持多entry 的方式来做这个事情，如果单独把业务组件抽离一个npm包的方式其实维护成本太高，还有别的好的解决方案吗?

**Comment by monxiaolee** [comment]
全局组件

**Comment by 1degrees** [comment]
这个方法太麻烦了， 很恶心啊， 如果一个不是应用很频繁的组件，还特意抽出来，真的太搞事了，
感觉还不如直接用A应用路由挂载一个组件， 在其他应用中直接挂载A应用，并锁定到指定路由就可以应用组件了

**Comment by 1degrees** [comment]
> 可以做到啊，首先把你需要共享的代码，抽取出独立的仓库，打包成library，然后在父应用中加载，这样代码就能从window[你的lirbary名称]获取到了，子应用也可以获取到。
> 
> 如果你说的是Module Federation这样的方式共享，直接在源码层面，那需要qiankun写插件什么的了。

这个方法太麻烦了， 很恶心啊， 如果一个不是应用很频繁的组件，还特意抽出来，真的太搞事了，
感觉还不如直接用A应用路由挂载一个组件， 在其他应用中直接挂载A应用，并锁定到指定路由就可以应用组件了

**Comment by yuzhanglong** [comment]
最近有做过研究，利用 webpack module federation 即可，https://github.com/yuzhanglong/mf-lite

**Comment by yousmellnice** [comment]
> > 可以做到啊，首先把你需要共享的代码，抽取出独立的仓库，打包成library，然后在父应用中加载，这样代码就能从window[你的lirbary名称]获取到了，子应用也可以获取到。
> > 如果你说的是Module Federation这样的方式共享，直接在源码层面，那需要qiankun写插件什么的了。
> 
> 业务组件可能富有很多业务逻辑在里面，你说的大概就是单独包npm的方式，这样开发调试是个问题

除了当跨仓库的时候，可以通过qiankun实现复用吗？目前的是通过npm包引入，但是每次组件迭代升级，项目那边就要更新版本、打包部署不够丝滑
