### ISSUE TITLE
Qiankun & Single-SPA : Unable to navigate to App01 from App02

### ISSUE THREAD

**Issue by shouviksmazumdar** [umijs/qiankun#405]
I am new to Qiankun & Single-SPA Micro Frontend Meta Framework. I have a simple use case. My React app & Angular app need to co-exist.All is working fine but I have can't seem to navigate from App02 to App1

Use case: When I click on a hyperlink in App02 , the call should go to the main router (single-spa) and it should navigate to App01

For some odd reason , all navigation is being caught by the current SPA router.

**Comment by eynol** [comment]
1.  `window.addEventListener` is hijacked by SPA.
1. SPA code load first, the original event is captured by SPA

Maybe your `activeRule` or `App1` route configuration is not correct?

Please provide a mini repo to reproduce the  behavior.

**Comment by kuitos** [comment]
closed via inactive
