### ISSUE TITLE
[Bug]多个页面，多个布局，在qiankun中如何使用或者是配置

### ISSUE THREAD

**Issue by xusong0621** [umijs/qiankun#410]
# 多个页面，多个布局，在qiankun中如何使用或者是配置

## What happens?

qiankun 在使用的时候，如果主应用有登录界面，再跳转到默认例子的主页面，这个需要怎么样的配制。还有就是官方的钉钉群那张图片看不清楚，也加不了群，有没有更详细的使用文档

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by BruceCham** [comment]
文档和示例没有同步，启动失败，细节问题有点多了

**Comment by kuitos** [comment]
跳转直接通过 url 就可以了

**Comment by kuitos** [comment]
@BruceCham 启动失败是什么问题

**Comment by BruceCham** [comment]
@kuitos 
切换到 v1.4.3基本上就正常了，v1.4.4和v1.4.5里面的示例和文档相差太大，文档相对也比较简易，项目很多细节会报错，修不过来的节奏

**Comment by kuitos** [comment]
1.x 文档看这里 https://v1.qiankun.umijs.org/zh/

过程中碰到的问题，欢迎提 pr 到 faq 分享经验，一起完善下官方文档，也可以帮助后面的开发者更快的解决问题🤝

**Comment by xusong0621** [comment]
> 跳转直接通过 url 就可以
钉钉的群号，官方文档那张图片钉钉识别不出来，我要如何加钉钉的qiankun群
