### ISSUE TITLE
以script标签引入的js会报错

### ISSUE THREAD

**Issue by jiang-24-gdufs** [umijs/qiankun#417]
## What happens?
<script src="./lib/js/jquery.min.js"></script>
<script src="./lib/js/bootstrap.min.js"></script>
bootstrap内部判断全局变量jQuery是否存在, 因为执行jquery.js时window指向了window.proxy, jQuery无法挂载到全局变量中导致bootstrap.js提前结束执行

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by jiang-24-gdufs** [comment]
> 提供可复现仓库

https://github.com/jiang-24-gdufs/qiankun_issue--417
### qiankun demo 访问purehtml可以看到控制台报错
### jQuery被proxy代理, 原来bootstrap访问jQuery依赖的方式会报错

**Comment by howel52** [comment]
我看下

**Comment by howel52** [comment]
```diff
<script src="//localhost:7104/jquery.min.js"></script>
+ <script>
+  jQuery = window.$
+ </script>
<script src="//localhost:7104/bootstrap.min.js"></script>
<script src="//localhost:7104/entry.js" entry></script>
```
