### ISSUE TITLE
我是用angluar8 接入乾坤，发现在配置子路由之后，生产环境刷新会报错

### ISSUE THREAD

**Issue by hwx373629** [umijs/qiankun#418]
**nginx配置**
![nginx配置](https://user-images.githubusercontent.com/31237524/78967787-e7c2ae00-7b35-11ea-8738-8fe3dc1d4f32.png)
**生产文件路径**
![生产文件](https://user-images.githubusercontent.com/31237524/78967860-04f77c80-7b36-11ea-958f-1adec06d7d65.png)
![生产文件2](https://user-images.githubusercontent.com/31237524/78967865-06c14000-7b36-11ea-9739-fc44117b2bd6.png)

注册的子应用
![image](https://user-images.githubusercontent.com/31237524/78973823-42aed200-7b43-11ea-82e3-bdb9071fd96a.png)

**app1的路由配置**
![路由配置](https://user-images.githubusercontent.com/31237524/78967823-f3ae7000-7b35-11ea-9327-e787aeee214a.png)
**正常的跳转都ok**
![正常跳转](https://user-images.githubusercontent.com/31237524/78967877-0e80e480-7b36-11ea-9daa-9d330e4c41af.png)
**但是跳转到app1/test 之后刷新报错**
![F5刷新报错](https://user-images.githubusercontent.com/31237524/78967921-25bfd200-7b36-11ea-8fad-40848d6b3e9c.png)

浏览器版本：版本 80.0.3987.149（正式版本） （64 位）
操作系统：window10
服务器系统：centos7

**Comment by kaichen87** [comment]
extra-webpack.config.js配置修改如下
const webpackMerge = require('webpack-merge');

module.exports = (config, options) => {
  const singleSpaConfig = {
    output: {
      library: 'mdd-front-oss',
      libraryTarget: 'umd',
    },
    externals: {
      'zone.js': 'Zone',
    },
  };
  const mergedConfig = webpackMerge.smart(config, singleSpaConfig);
  return mergedConfig;
};

**Comment by hwx373629** [comment]
配置之后，直接无法跳转
APP1 还是之前的配置 一级路由可以，APP2按照您的配置 直接报错了
![image](https://user-images.githubusercontent.com/31237524/79084248-4326b300-7d65-11ea-81e4-d3850d897d47.png)

**Comment by waltbest2** [comment]
我在build angular工程时，报错，请问怎么解决的
polyfills-es5.js: Invalid left-hand side in assignment expression (9:2)

   7 |          exports["polyfills-es5.js"] = factory(polyfills-es5.js);
   8 |  else
>  9 |          polyfills-es5.js = factory(polyfills-es5.js);
     |          ^
  10 | })(window, function() {
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/         // The module cache

**Comment by hwx373629** [comment]
> 我在build angular工程时，报错，请问怎么解决的
> polyfills-es5.js: Invalid left-hand side in assignment expression (9:2)
> 
> 7 | exports["polyfills-es5.js"] = factory(polyfills-es5.js);
> 8 | else
> 
> > 9 |          polyfills-es5.js = factory(polyfills-es5.js);
> > |          ^
> > 10 | })(window, function() {
> > 11 | return /******/ (function(modules) { // webpackBootstrap
> > 12 | /******/         // The module cache
![image](https://user-images.githubusercontent.com/31237524/79293020-2923d680-7f05-11ea-8929-8d4523261bc0.png)
这l两个文件要修改 
你看看demo里面 angluar9里面的这个两个文件的配置

**Comment by hwx373629** [comment]
> 我在build angular工程时，报错，请问怎么解决的
> polyfills-es5.js: Invalid left-hand side in assignment expression (9:2)
> 
> 7 | exports["polyfills-es5.js"] = factory(polyfills-es5.js);
> 8 | else
> 
> > 9 |          polyfills-es5.js = factory(polyfills-es5.js);
> > |          ^
> > 10 | })(window, function() {
> > 11 | return /******/ (function(modules) { // webpackBootstrap
> > 12 | /******/         // The module cache

我在你issue下面回复了
