### ISSUE TITLE
启动qiankun项目报错

### ISSUE THREAD

**Issue by yangangzhang** [umijs/qiankun#42]
将qiankun项目clone下来之后，安装依赖，npm start 报错
![image](https://user-images.githubusercontent.com/20433039/63757569-e321f000-c8ec-11e9-8f5e-9987050580bd.png)

**Comment by kuitos** [comment]
```shell
npm i
npm run install:examples
npm start
```
https://github.com/umijs/qiankun#-examples

**Comment by yangangzhang** [comment]
您好，感谢回答，就是按照这个执行的，只不过用的cnpm
![image](https://user-images.githubusercontent.com/20433039/63758045-c20dcf00-c8ed-11e9-8591-61217be00442.png)

**Comment by yangangzhang** [comment]
这个地方报的错
![image](https://user-images.githubusercontent.com/20433039/63758214-07320100-c8ee-11e9-8b6f-b70987ea4ffd.png)
没有搞明白

**Comment by kuitos** [comment]
看启动日志有没有报错

**Comment by yangangzhang** [comment]
没有报错
![image](https://user-images.githubusercontent.com/20433039/63759547-46f9e800-c8f0-11e9-809d-efaede64f2a5.png)

**Comment by kuitos** [comment]
浏览器报错信息是 localhost:7100 这个地址拿不到资源

**Comment by yangangzhang** [comment]
7100这个服务需要启动吗？需要启动是在哪启动？
看的错误的原因是react这个地方报错

**Comment by kuitos** [comment]
react 那个只是 warning
windows 不支持并行跑命令行吗。。
试下把这个几个命令分开跑吧 https://github.com/umijs/qiankun/blob/6d5f616ba92dc6a4bd3772c3089c05c5cbf6355f/package.json#L12-L15

**Comment by yangangzhang** [comment]
感谢，分开执行跑起来了，就是那个warning还存在，另外map文件不存在，给了提示
![image](https://user-images.githubusercontent.com/20433039/63818088-d98e9b80-c971-11e9-9cc5-8bb58ab74a67.png)

**Comment by kuitos** [comment]
拉下最新的代码

**Comment by yangangzhang** [comment]
拉取了新的代码，warning不存在了，现在就是存在一个提示
![image](https://user-images.githubusercontent.com/20433039/63824199-e8347d00-c988-11e9-9783-be623beaa784.png)

**Comment by kuitos** [comment]
这个问题另外开个 issue 吧，这个 issue 先关了
