### ISSUE TITLE
[Bug] body污染，子应用中toast动态插入div 到 body, 在toast未关闭时切换子应用，动态插入的div未被清理

### ISSUE THREAD

**Issue by gaoletian** [umijs/qiankun#421]
#421 What happens?

[Bug] body污染，子应用中toast动态插入div 到 body, 在toast未关闭时切换子应用，动态插入的div未被清理

**React子应用 toast**

![image](https://user-images.githubusercontent.com/25849581/78987555-ed81b900-7b60-11ea-8092-4382d482440d.png)

**切换Vue子应用**

![image](https://user-images.githubusercontent.com/25849581/78987652-320d5480-7b61-11ea-97f9-6e21a48dc6c8.png)

![image](https://user-images.githubusercontent.com/25849581/78987722-608b2f80-7b61-11ea-8e80-3f7b1a1143e2.png)

## 相关环境信息

- **qiankun 版本** v2.0.1
- **浏览器版本**：chrome
- **操作系统**： mac osx

**Comment by kuitos** [comment]
dom 插入这类副作用需要应用自己清理

**Comment by gaoletian** [comment]
got it close

**Comment by kuitos** [comment]
antd 组件可以在子应用 unmount 里统一调一下 Toast.hide()

**Comment by esymeptoo** [comment]
> antd 组件可以在子应用 unmount 里统一调一下 Toast.hide()

如果ui库没有提供这类清除方法应该怎么做呢 目前方案是在子应用劫持document.body.appendChild将动态插入的节点保存在一个数组内部 子应用unmount阶段遍历移除 node.parentNode.removeNode(node)
但是子应用获取到的document.body.appendChild已经是被qiankun劫持过的 如果主应用也有appendChild的副作用也会随着子应用的移除被移除掉 所以能否提供一个全局变量window.isSalve表明目前是子应用环境

**Comment by mengsixing** [comment]
子项目内部是否可以通过 MutationObserver 去监控 Dom 的变化，在子项目卸载时进行恢复呢？
