### ISSUE TITLE
我现在有个需求，通过tab标签页，来回切换子应用，怎么保持状态呢

### ISSUE THREAD

**Issue by Clive-Wang** [umijs/qiankun#428]
我现在有个需求，通过tab标签页，来回切换子应用，怎么保持状态呢

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/361

**Comment by atliwen** [comment]
可以参考我的实现 ，  https://www.cnblogs.com/atliwen/p/14281041.html    我也是结合他人的 添加自己想法。 大概思路。

**Comment by JackieZhang-Coding** [comment]
> 可以参考我的实现 ， https://www.cnblogs.com/atliwen/p/14281041.html 我也是结合他人的 添加自己想法。 大概思路。

请问你这个有代码吗？

**Comment by Clive-Wang** [comment]
非常感谢您的回复，可以提供个源码看看吗？非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 上午10:09
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"リーダー "<1334766964@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun] 我现在有个需求，通过tab标签页，来回切换子应用，怎么保持状态呢 (#428)





 
可以参考我的实现 ，  https://www.cnblogs.com/atliwen/p/14281041.html    我也是结合他人的 添加自己想法。 大概思路。

**Comment by kuaifengle** [comment]
参考演示地址: https://github.com/kuaifengle/qiankun-vue3-tabsPage
