### ISSUE TITLE
[Bug]entry中配置styles载入subapp为何不对样式处理，例如插入style到容器中

### ISSUE THREAD

**Issue by Easy-Martin** [umijs/qiankun#429]
- **qiankun 版本** 1.4.5
- **浏览器版本**：chrome80
- **操作系统**：windows
![image](https://user-images.githubusercontent.com/12482868/79194245-cf68d100-7e5e-11ea-8626-b2872072378a.png)
目前在render方法中处理插入一个style
![image](https://user-images.githubusercontent.com/12482868/79194477-31293b00-7e5f-11ea-8dc6-4e36b109bfab.png)

**Comment by kuitos** [comment]
config entry 现在并不完全支持，推荐使用 html entry 方式
