### ISSUE TITLE
[Feature Request] 限制子应用单独启动

### ISSUE THREAD

**Issue by awefeng** [umijs/qiankun#434]
## Background

在项目中，我只想用户能从主应用中进入子应用；限制用户直接能从子应用进入。

## Proposal

主子应用中通过约定一个配置项，当子应用检测到不是来自主应用的加载。则不能进入，显示一个拦截界面

## Additional context

待补充

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#%E5%A6%82%E4%BD%95%E7%8B%AC%E7%AB%8B%E8%BF%90%E8%A1%8C%E5%AD%90%E5%BA%94%E7%94%A8%EF%BC%9F
