### ISSUE TITLE
The activeWhen argument must be a function

### ISSUE THREAD

**Issue by Clive-Wang** [umijs/qiankun#440]
报错：The activeWhen argument must be a function，
激活规则这样配置 activeRule: '/app1' ，就报上面的错误。是因为我本地的qiankun版本不对吗？那要怎么进行升级啊

**Comment by kuitos** [comment]
使用 qiankun v2.0

**Comment by Clive-Wang** [comment]
> 使用 qiankun v2.0

我现在用的V1.4.5，怎么升级啊，使用npm更新的还是V1.4.5
