### ISSUE TITLE
子应用之间怎么跳转

### ISSUE THREAD

**Issue by wangyapeng** [umijs/qiankun#445]
现在再做微前端整合
子应用之间的跳转和子应用跳转主应用

**Comment by kuitos** [comment]
```html
<a href="/appA">跳转到 A</a>
<a href="/appB">跳转到 B</a>
```

**Comment by wangyapeng** [comment]
what is this?

**Comment by wangyapeng** [comment]
这样解决问题？

**Comment by gaoletian** [comment]
history.pushState

**Comment by drafish** [comment]
> ```
> <a href="/appA">跳转到 A</a>
> <a href="/appB">跳转到 B</a>
> ```

这样会导致整个页面重新加载一遍，感觉不太好呀，还是history.pushState比较好，但还是不够优雅，最好是可以在Link中设置base路径，像这样子，不过貌似umi/link不支持传base参数
```
<Link to='/appA' base='/'>跳转到应用A</Link>
<Link to='/appB' base='/'>跳转到应用B</Link>
<Link to='/' base='/'>跳转到主应用</Link>
```

**Comment by JiangJingxuan** [comment]
> > ```
> > <a href="/appA">跳转到 A</a>
> > <a href="/appB">跳转到 B</a>
> > ```
> 
> 这样会导致整个页面重新加载一遍，感觉不太好呀，还是history.pushState比较好，但还是不够优雅，最好是可以在Link中设置base路径，像这样子，不过貌似umi/link不支持传base参数
> 
> ```
> <Link to='/appA' base='/'>跳转到应用A</Link>
> <Link to='/appB' base='/'>跳转到应用B</Link>
> <Link to='/' base='/'>跳转到主应用</Link>
> ```

我也遇到过类似的问题,我的主应用路由带有base,所以跳转子应用的时候路由地址不正确,最后实在没别的办法了,就把history改了一下
![image](https://user-images.githubusercontent.com/25758620/84243920-815a0c00-ab35-11ea-8bcb-74d230df01b3.png)
不知道会不会给你提供些思路

**Comment by lyxverycool** [comment]
我用pushState 这种路由跳转页面会加载不出来，能加载到#app这一层，但里面内容没了。。感觉毕竟是前端路由，不能映射到子项目的路由。a标签是可以的

**Comment by czero1995** [comment]
a标签跳转会使整个页面重新刷新，原来的状态都会丢失掉。
用router的history跳转会带上子应用的base，导致路由跳转404。
调主应用的路由，主应用再去匹配分发到子应用路由
跳转的时候先判断是否在qiankun环境下，如果是qiankun环境下，调用h5自带的history.pushState()跳转
如果是子应用独立开发部署，就使用路由跳转。
import { history as umiHistory } from 'umi';

export const qiankunJump = (url:string, name="页面名称",params=null) => {
    window.__POWERED_BY_QIANKUN__  ?  history.pushState(params, name, url) : umiHistory.push(url);
 }

qiankunJump('/routePath')
