### ISSUE TITLE
2.0.0 插入的子项目展示空白，js未被插入

### ISSUE THREAD

**Issue by tantuer** [umijs/qiankun#447]
## What happens?

使用2.0版本起服务，当正常匹配到子项目路径的时候，子项目的dom被插入到指定的#id container下，但是js并没有被插入，导致该container下空白。

![image](https://user-images.githubusercontent.com/8870158/79437749-33c59500-8005-11ea-9485-2581d3a58829.png)

## Context

- **qiankun Version**: 2.0.0
- **Platform Version**:mac
- **Browser Version**:chrome

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by tantuer** [comment]
通过参考你们提供的demo,目前已解决，是我配置有问题，thanks

**Comment by zhaoxm2016** [comment]
@tantuer 你好请问你是如何解决的啊，我部署的Nginx上之后一直也报错，开发环境下没问题
