### ISSUE TITLE
生产环境，有什么部署的最佳实践吗，也没相关文档

### ISSUE THREAD

**Issue by JinJieTan** [umijs/qiankun#450]
这个问题很重要啊，重要资料缺失了

**Comment by JinJieTan** [comment]
这个问题非常致命，还有小伙伴在使用nginx去配合做部署，这些导致前端没有闭环，希望可以解决！！谢谢

**Comment by hwx373629** [comment]
同求

**Comment by leogcry22** [comment]
同

**Comment by haoliangwu** [comment]
@JinJieTan 
我当前部署是用 docker + nginx，本质上还是 nginx。我感觉这个部署的最佳实践是很难有个统一标准判定的，因为如果是从一开始就做微前端架构的项目还好，但大多数情况都需要考虑旧项目的兼容问题。

另一方面是因为各个公司各个团队部署流程和工具体系千差万别，其实也很难找到一套真正意义上的”最佳实践“并形成文档。我觉得这个只能是通过看一些从迁移到部署的分享帖来取经了。

**Comment by hql7** [comment]
https://juejin.cn/post/6921649095610204173 简陋的docker部署
