### ISSUE TITLE
可以在基座的通过api动态添加props传递给子组件

### ISSUE THREAD

**Issue by jockey100332** [umijs/qiankun#453]
## Background
我需要一部分异步数据通过props传递给子项目，但是请求的异步数据没办法保存进dva 中，因为app.js 没有办法获取到dva 的实例，在子项目中也没有办法存储父项目传递的数据

我希望可以将传子的数据单独独立处理，在app 中可以做相关读写，也可以在页面级进行动态修改

我目前采用的是localstorage 的方式，但是我感觉不是很优雅，

**Comment by dbkillerf6** [comment]
文档：https://qiankun.umijs.org/zh/api/#initgloabalstate-state

1. 在【主应用】初始化一份数据；
2. 【子应用】使用 onGlobalStateChange 将全局数据保存到【子应用】里
3. 修改全局数据用 setState，只修改【子应用】数据那就直接变更 2 存下来的数据
