### ISSUE TITLE
TypeError: parcel 'react15_0' died in status NOT_MOUNTED: Cannot read property 'appWrapperGetter' of undefined

### ISSUE THREAD

**Issue by xileliu** [umijs/qiankun#454]
## What happens?
官方demo
1.单独启动
![image](https://user-images.githubusercontent.com/13429648/79541033-b446cd00-80bb-11ea-8926-a21362f1178a.png)
2.在启动react 15 demo
![image](https://user-images.githubusercontent.com/13429648/79541085-c9bbf700-80bb-11ea-98d9-2f495ec42c67.png)
会报错
![image](https://user-images.githubusercontent.com/13429648/79541135-dfc9b780-80bb-11ea-8a55-0c620ef8d05e.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
无法复现。

更新下你本地的代码到最新并重新 `yarn build`

**Comment by xileliu** [comment]
> 无法复现。
> 
> 更新下你本地的代码到最新并重新 `yarn build`

![image](https://user-images.githubusercontent.com/13429648/79550593-2377ed80-80cb-11ea-8a81-4fad0d19acce.png)

文档这个配置的话，另外加载的子应用必须暴露每个周期函数吗？
第一看这个文档感觉就是可以直接用截图demo,默认就会把子应用资源加载过来插入到指定container 节点，实际测试好像必须在子应用写
![image](https://user-images.githubusercontent.com/13429648/79550856-7ea9e000-80cb-11ea-87b4-814fce243b29.png)

**Comment by xileliu** [comment]
@kuitos

**Comment by kuitos** [comment]
微应用的定义是一致的，不管用什么方式加载，都需要满足这些条件 https://qiankun.umijs.org/zh/guide/getting-started.html#%E5%BE%AE%E5%BA%94%E7%94%A8

**Comment by xileliu** [comment]
> 微应用的定义是一致的，不管用什么方式加载，都需要满足这些条件 https://qiankun.umijs.org/zh/guide/getting-started.html#%E5%BE%AE%E5%BA%94%E7%94%A8
谢谢回复解答

**Comment by xileliu** [comment]
> 微应用的定义是一致的，不管用什么方式加载，都需要满足这些条件 https://qiankun.umijs.org/zh/guide/getting-started.html#%E5%BE%AE%E5%BA%94%E7%94%A8

umi-plugin-qiankun 什么时候更新

**Comment by xileliu** [comment]
@kuitos
