### ISSUE TITLE
关于打包的疑问

### ISSUE THREAD

**Issue by hzyhbk** [umijs/qiankun#455]
## What happens?
我基于 umi-plugin-qiankun 的 examples 在本地跑，没问题；现在想把子应用打包下，然后再在父应用里去加载，结果子应用的资源就一直报404

## 最小可复现仓库
https://github.com/umijs/umi-plugin-qiankun

## 复现步骤，错误日志以及相关配置
1. clone 以上仓库， 安装依赖，
2. 进到exapmles目录
3. 打包app1，然后cd dist，通过 `http-server -p 8001 --cors` 启动本地服务
4. cd master 然后 npm start 启动 master 访问 /app1
5. 控制台报错资源 404

![image](https://user-images.githubusercontent.com/42671099/79544651-ee1ad200-80c1-11ea-948d-47d4eb47d9e4.png)

我个人感觉应该去加载 localhost:8001/app1/xx.js ，不知道为何少了 **app1** 这个前缀

## 相关环境信息

- **qiankun 版本**: 1.4.5
- **浏览器版本**：chrome:  81.0.4044.113（正式版本） （64 位）
- **操作系统**：macos: 10.14.6 (18G95)

**Comment by kuitos** [comment]
entry 配置成 `localhost:8001/app1/index.html`
