### ISSUE TITLE
用vuecli3部署线上环境出现问题

### ISSUE THREAD

**Issue by JamesWen1993** [umijs/qiankun#456]
## What happens?

通过nginx配置后输入主应用url是好的，但是刷新后子应用找不到，而且直接进子应用路由也是这样的问题。我看了下window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__为null。
本地环境是好的。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/JamesWen1993/mirco

## How To Reproduce

![QQ20200417-164848-HD](https://user-images.githubusercontent.com/14937294/79551791-bb2a0b80-80cc-11ea-933d-8a6ebef82170.gif)

nginx配置:
![image](https://user-images.githubusercontent.com/14937294/79551554-64bccd00-80cc-11ea-91e6-5bbc979169d8.png)

## Context

- **qiankun Version**:^2.0.0-3
- **Platform Version**: mac
- **Browser Version**:chrome 80.0.3987.163（正式版本） （64 位）

**Comment by kuitos** [comment]
`/disaster` 路径的访问被你代理到子应用了
![image](https://user-images.githubusercontent.com/5206843/79563113-bc643400-80de-11ea-95ca-438d2c96686a.png)

**Comment by JamesWen1993** [comment]
@kuitos 图片挂了。。能发个到我的邮箱吗。。感谢JamesWen1993@163.com
