### ISSUE TITLE
基座是angularjs 1.7.x，load angular9 的app，IE 11 下 unmount时会把基座环境搞挂

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#457]
## What happens?
基座是angularjs 1.7.x是可以的，我这里可以，但是在IE 11下，如果load一个angular 9的app，unmount时，会把基座的angularjs环境搞挂掉，一堆报错

ERROR Error: Uncaught (in promise): TypeError: 对象不支持此操作
TypeError: 对象不支持此操作

TypeError: 缺少对象

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by waltbest2** [comment]
内部代码仓库，不好提供。
快照沙箱是直接操作window下面的变量，这块有没有可能误杀。

**Comment by kuitos** [comment]
最小可复现版本，可以基于 example 改或者别的方式。
没有复现仓库不知道你上下文都做了哪些事情，无法帮你排查问题。

**Comment by zengyunchun** [comment]
> 内部代码仓库，不好提供。
> 快照沙箱是直接操作window下面的变量，这块有没有可能误杀。
我们也有angularjs版本，能否加我qq交流下595724205

**Comment by zengyunchun** [comment]
> 内部代码仓库，不好提供。
> 快照沙箱是直接操作window下面的变量，这块有没有可能误杀。

@waltbest2 我们也有angularjs版本，能否加我qq交流下595724205

**Comment by kuitos** [comment]
如果有可复现仓库可以随时 reopen

**Comment by waltbest2** [comment]
初步怀疑，snapshotSandbox.ts里面inactive会恢复之前的window的所有变量，会把新设置在window下面的覆盖掉。

所以请帮忙分析inactive是在什么时机触发的。

**Comment by whitekyo** [comment]
咨询下angular1.x。你们是如何实现unmount的
