### ISSUE TITLE
[Bug]项目名称的英文解释不准确

### ISSUE THREAD

**Issue by shuod** [umijs/qiankun#458]
## What happens?

项目名称的英文解释不准确。
1）
乾指的是天，不是天堂heaven，这个有特定的宗教内涵；坤翻译成earth的话，容易误解为土，或者地球，都是不准确的。

建议把乾翻成sky，坤翻成land。这两个翻译和乾卦，坤卦里赋予乾和坤的各种属性都兼容；

2）
不管是中国还是外国，乾坤和宇宙都是不同的。中国文化里，“上下四方曰宇，古往今来曰宙”。乾坤很明显缺了时间部分；而在现代宇宙学里，宇宙同样指无限空间和无限时间。

所以，严格讲，乾坤指的仅仅是地球的空间部分。简单的说，就解释成是space就可以了。其实，现代space science即空间科学，多指近地空间研究，所以和乾坤有重合的地方。

**Comment by Deturium** [comment]
1. 乾和坤的翻译

你想翻译为 sky 和 land 老实讲没什么错；但是就目前外网上出现的翻译来说，乾 翻译为 heaven 比 sky 多，坤 几乎不会翻译为 land，基本都是 earth

比如 https://www.iching-online.com/iching-trigrams.htm
又或者 wiki 上的翻译 https://en.wikipedia.org/wiki/Bagua

我觉得还是尊重现存翻译吧


2. qiankun 和宇宙

这里你说的没错，乾坤不等于宇宙，甚至光说等于宇 也不太好
毕竟天和地是乾坤的自然象征，硬说是代表空间也不怎么好
