### ISSUE TITLE
子应用挂载的顺序依赖

### ISSUE THREAD

**Issue by feihua666** [umijs/qiankun#46]
## Background

主项目A：一个项目是主入口项目，负责加载其它子项目
子项目B：主要用来负责各个子项目的导航，现在用作后台管理菜单框架页面，中间区域用来挂载其它子项目
子项目C、D...等：依赖项目B的优先挂载，因为这些项目要等待B项目渲染完成后，需要挂载到B项目提供的dom元素上

## Proposal

在注册子应用的时候，额外添加一个配置项如：mountOrder: number,用来描述和控制子项目挂载的顺序，或者是其它配置项如：mountDependency: appName,挂载依赖的项目等

## Additional context

暂时没有想到

**Comment by kuitos** [comment]
c、d挂载到B上，那对于主应用而言 A、B才是子应用啊，C、D是B的子应用

**Comment by feihua666** [comment]
> 
> 
> c、d挂载到B上，那对于主应用而言 A、B才是子应用啊，C、D是B的子应用

你说有很对，关系是这 个关系，你的意思是每个主应用只负责挂载自己的子应该是吗？

**Comment by kuitos** [comment]
> > c、d挂载到B上，那对于主应用而言 A、B才是子应用啊，C、D是B的子应用
> 
> 你说有很对，关系是这 个关系，你的意思是每个主应用只负责挂载自己的子应该是吗？

是的

**Comment by feihua666** [comment]
> 
> 
> > > c、d挂载到B上，那对于主应用而言 A、B才是子应用啊，C、D是B的子应用
> > 
> > 
> > 你说有很对，关系是这 个关系，你的意思是每个主应用只负责挂载自己的子应该是吗？
> 
> 是的

thanks
