### ISSUE TITLE
注册微应用报错  application 'vue-app1' died in status LOADING_SOURCE_CODE: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by zxh1307** [umijs/qiankun#460]
注册微应用报错  application 'vue-app1' died in status LOADING_SOURCE_CODE: Cannot read property 'then' of undefined

**Comment by kuitos** [comment]
请遵循模板提交问题，否则您的问题会被关闭

**Comment by zhangfu-git** [comment]
@zxh1307 请问解决了吗？
