### ISSUE TITLE
[qiankun] You need to export lifecycle functions in doc entry

### ISSUE THREAD

**Issue by JinJieTan** [umijs/qiankun#462]
一个项目很奇怪，总是会报这个错，我去源码里调试发现
   

// fallback to global variable who named with ${appName} while module exports not found
    const globalVariableExports = (global as any)[appName];
    console.log(globalVariableExports,'globalVariableExports',global,appName)

下面的appName是 globalVariableExports是undefined

**Comment by JinJieTan** [comment]
这是一个废弃的项目，但是不知道为什么就是会出问题

webpack配置：
```
  output: {
        filename: `js/${name}-[name].js`,
        library: `${name}-[name]`,
        libraryTarget: 'umd',
        jsonpFunction: `webpackJsonp_${name}`,
    },
```

入口index.tsx文件

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './app';
import './assets/less/index.less';
import 'antd/dist/antd.less';

// ReactDOM.render(<App />, document.querySelector('#root'));
function render(props: any) {
    const { container } = props;
    console.log(props,'props')
    ReactDOM.render(<App />, container ? container.querySelector('#root') : document.querySelector('#root'));
}

function storeTest(props: any) {
    props.onGlobalStateChange(
        (value: any, prev: any) => console.log(`[onGlobalStateChange - ${props.name}]:`, value, prev),
        true
    );
    props.setGlobalState({
        ignore: props.name,
        user: {
            name: props.name,
        },
    });
}


//@ts-ignore
if (!window.__POWERED_BY_QIANKUN__) {
    render({});
}

export async function bootstrap() {
    console.log('[react16] react app bootstraped');
}
//@ts-ignore
export async function mount(props) {
    console.log('[react16] props from main framework', props);
    storeTest(props);
    render(props);
}

export async function unmount() {
    //@ts-ignore
    ReactDOM.unmountComponentAtNode(document.getElementById('root'));
}


```

**Comment by S-ionantha** [comment]
老哥，你这怎么怎么解决的

> 这是一个废弃的项目，但是不知道为什么就是会出问题
> 
> webpack配置：
> 
> ```
>   output: {
>         filename: `js/${name}-[name].js`,
>         library: `${name}-[name]`,
>         libraryTarget: 'umd',
>         jsonpFunction: `webpackJsonp_${name}`,
>     },
> ```
> 
> 入口index.tsx文件
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import App from './app';
> import './assets/less/index.less';
> import 'antd/dist/antd.less';
> 
> // ReactDOM.render(<App />, document.querySelector('#root'));
> function render(props: any) {
>     const { container } = props;
>     console.log(props,'props')
>     ReactDOM.render(<App />, container ? container.querySelector('#root') : document.querySelector('#root'));
> }
> 
> function storeTest(props: any) {
>     props.onGlobalStateChange(
>         (value: any, prev: any) => console.log(`[onGlobalStateChange - ${props.name}]:`, value, prev),
>         true
>     );
>     props.setGlobalState({
>         ignore: props.name,
>         user: {
>             name: props.name,
>         },
>     });
> }
> 
> 
> //@ts-ignore
> if (!window.__POWERED_BY_QIANKUN__) {
>     render({});
> }
> 
> export async function bootstrap() {
>     console.log('[react16] react app bootstraped');
> }
> //@ts-ignore
> export async function mount(props) {
>     console.log('[react16] props from main framework', props);
>     storeTest(props);
>     render(props);
> }
> 
> export async function unmount() {
>     //@ts-ignore
>     ReactDOM.unmountComponentAtNode(document.getElementById('root'));
> }
> ```

老哥你这问题是怎么解决的？

**Comment by featureMonday** [comment]
我也遇到这个问题啦，请问是什么问题嘛？

**Comment by shuyanzi** [comment]
+1

**Comment by ldgoooo** [comment]
只剩一个entry的就可以了，应该是要保证每个entry都要加lifecycle functions 
entry: {
    index: './src/index.js',
    // framework: ['react','react-dom'],
  },

**Comment by JinJieTan** [comment]
真正的问题所在，qiankun的文档，没有提到这点.

webpack的entry 必须设置为main 才能有效加载子应用。反正我没有再用了

**Comment by howel52** [comment]
> 真正的问题所在，qiankun的文档，没有提到这点.

FAQ 第一条就是 🤪 ：https://qiankun.umijs.org/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by JinJieTan** [comment]
> > 真正的问题所在，qiankun的文档，没有提到这点.
> 
> [FAQ 第一条](https://qiankun.umijs.org/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry) 就是 🤪

本来不想回复，文档必定看过，我在一些交流群解决了好些因为这个main导致的问题,你自己去看看那个文档写清楚了webpack的 entry是要为main吗？

**Comment by kuitos** [comment]
不需要 entry 是 main，[FAQ](https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry) 文档里提到了最后的终极方案
![image](https://user-images.githubusercontent.com/5206843/85948292-b0b8a780-b982-11ea-8e6f-a84c08caa2c3.png)

**Comment by humorHan** [comment]
还是没解决，请问大佬解决了吗？

**Comment by zuibunan** [comment]
> > > 真正的问题所在，qiankun的文档，没有提到这点.
> > 
> > 
> > [FAQ 第一条](https://qiankun.umijs.org/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry) 就是 🤪
> 
> 本来不想回复，文档必定看过，我在一些交流群解决了好些因为这个main导致的问题,你自己去看看那个文档写清楚了webpack的 entry是要为main吗？

太坑了，我搞了一上午搞不好，最后换成main.js出来了...

**Comment by Haixiang6123** [comment]
> 不需要 entry 是 main，[FAQ](https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry) 文档里提到了最后的终极方案
> ![image](https://user-images.githubusercontent.com/5206843/85948292-b0b8a780-b982-11ea-8e6f-a84c08caa2c3.png)

666，太吊了！
