### ISSUE TITLE
加载cesium报错

### ISSUE THREAD

**Issue by JamesWen1993** [umijs/qiankun#463]
## What happens?

子应用加载cesiumJs（一款三维地图底层框架）报资源找不到

## Mini Showcase Repository(REQUIRED)

https://github.com/JamesWen1993/mirco
进入disaster页面点击about
## How To Reproduce

cesium的引用在子应用的index.html里
![image](https://user-images.githubusercontent.com/14937294/79634180-820c9c80-819b-11ea-8315-8cde07f01d74.png)

cesium需要寻找对应的script
![image](https://user-images.githubusercontent.com/14937294/79634126-322dd580-819b-11ea-9ba5-c032858a0a1d.png)

找的源码函数是下方
function getBaseUrlFromCesiumScript() {
    var scripts = document.getElementsByTagName('script');
    for ( var i = 0, len = scripts.length; i < len; ++i) {
        var src = scripts[i].getAttribute('src');
        var result = cesiumScriptRegex.exec(src);
        if (result !== null) {
            return result[1];
        }
    }
    return undefined;
}

然后返回后找不到地址我打印了scripts发现没有子应用引入的script，都是主应用的script
 let scripts = document.getElementsByTagName('script');

找不到路径所以报下面的错误
![image](https://user-images.githubusercontent.com/14937294/79634144-45d93c00-819b-11ea-9644-123bcaa5858c.png)

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
getBaseUrlFromCesiumScript 需要重写，子应用加载的 script 标签不会插入到 dom

**Comment by JamesWen1993** [comment]
@kuitos 那个方法是cesium封装好的源码。那我该去怎么加载这种外部js？

**Comment by kuitos** [comment]
外部 js 正常加载就行了。
这个报错是因为 getBaseUrlFromCesiumScript 用了一些非常规手段拼装 url。
解决方案：
1. 修改 getBaseUrlFromCesiumScript 实现取到正确的路径
2. cesiumJs 移到主应用加载

**Comment by JamesWen1993** [comment]
@kuitos 主要是cesium这个文件太大了，只有子应用在用，放主应用会占空间
还有外部js我加载百度地图报了跨域，不知道改如何处理（估计他们不支持吧）
![image](https://user-images.githubusercontent.com/14937294/79636380-d0c13300-81a9-11ea-8bf4-45ea9ae02eeb.png)

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#%E5%BE%AE%E5%BA%94%E7%94%A8%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E4%B8%80%E5%AE%9A%E8%A6%81%E6%94%AF%E6%8C%81%E8%B7%A8%E5%9F%9F%E5%90%97%EF%BC%9F

**Comment by JamesWen1993** [comment]
不行吖，你们这方法是用来过滤的。过滤掉后就不加载这js了。。主要百度啊，高德这些引用下不下来诶。。他们也是本地注入的形式注入js的

**Comment by kuitos** [comment]
你看错了吧

**Comment by crazyDopamine** [comment]
沙盒劫持了HTMLHeadElement.prototype.appendChild方法，而百度地图等是通过在head下添加子元素去请求的，所以请求会通过import-html-entry的execScripts。源码中加配置方法，可以实现。

interfaces.ts:
type QiankunSpecialOpts = {
  isRawHeadAppendChild?: (newChild: any) => boolean;
  prefetch?: PrefetchStrategy;
  sandbox?:
    | boolean
    | {
        strictStyleIsolation?: boolean;
        patchers?: Patcher[];
      };
  /*
    with singular mode, any app will wait to load until other apps are unmouting
    it is useful for the scenario that only one sub app shown at one time
  */
  singular?: boolean | ((app: LoadableApp<any>) => Promise<boolean>);
};
dynamicHeadAppend.ts中patch方法
HTMLHeadElement.prototype.appendChild = function appendChild<T extends Node>(this: HTMLHeadElement, newChild: T) {
    const isRawHeadAppendChild = frameworkConfiguration.isRawHeadAppendChild
      ? frameworkConfiguration.isRawHeadAppendChild(newChild)
      : false;
    if (isRawHeadAppendChild) {
      return rawHeadAppendChild.call(this, newChild) as T;
    }
...

然后启动时：
start({
  isRawHeadAppendChild(newChild) {
    if (newChild && newChild.src && newChild.src.indexOf("baidu.com")) {
      return true
    }
    return false
  }
})

**Comment by qtpalmtop** [comment]
设置CESIUM_BASE_URL路径试试，我加载cesium是成功的
const isProd = false;

(global => {
  global['h5-map-app'] = {
    bootstrap: () => {
      global.CESIUM_BASE_URL = isProd ? 'http://182.48.115.108:8887/h5-map-app/public/cesium/Cesium/' : 'http://localhost:8088/public/cesium/Cesium/';
      console.log('h5-map-app bootstrap');
      return Promise.resolve();
    },
    // ...
}
