### ISSUE TITLE
angular子项目报错

### ISSUE THREAD

**Issue by caojianbiao** [umijs/qiankun#466]
No NgModule metadata found for 'AppModule'.
pull项目以后升级至最新angular版本，关闭ivy后出现
其余配置项都与example相同

- **qiankun Version :2.0.2
- **Platform Version:MacOS 10.15
- **Browser Version: chrome 80

**Comment by caojianbiao** [comment]
No NgModule metadata found for 'AppModule'.
pull项目以后升级至最新angular版本，关闭ivy后出现

**Comment by hwx373629** [comment]
examples 里面的angular9 -》tsconfig.json   配置 "target": "es2015", build打包会报错
![image](https://user-images.githubusercontent.com/31237524/79928963-f040b000-8476-11ea-817e-1c605083f416.png)
 配置 "target": "es5",  build打包正常 但是部署生产无法使用
![image](https://user-images.githubusercontent.com/31237524/79928900-d0a98780-8476-11ea-94b9-16f701a52bd0.png)

现在不知道是因为这个配置的原因导致生产无法使用，还是什么原因 求生产部署文档
