### ISSUE TITLE
如何在子项目访问完整window对象

### ISSUE THREAD

**Issue by dengBox** [umijs/qiankun#467]
有看到qiankun对window做了代理，但是子项目里面有些三方库依赖完整的window对象，会访问其中一些属性，这样会导致三方库报错了，除了修改这些库之外，还有别的方式处理吗

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by dengBox** [comment]
很简单

**Comment by dengBox** [comment]
抱歉，问题描述的有点问题，代码仓库暂时不能提供，复现的场景是: subProject开启jsSandbox。使用了tinymce。改库在初始化时候 内部报错了，经排查是因为代理window的问题，关闭jsSandbox即正常。
1. ```"qiankun": "^1.4.5"```  
2. ```"@tinymce/tinymce-vue": "^3.2.0"```

**Comment by grtan** [comment]
我也遇到子应用使用tinymce时，初始化报错的问题了

**Comment by dengBox** [comment]
> 我也遇到子应用使用tinymce时，初始化报错的问题了

我之前改过tinymce源码，后来放弃了，关闭了`jsSandbox`，就可以正常访问了

**Comment by wubobuaa** [comment]
除了关闭sandbox，还有什么好的解决方案吗

**Comment by dengBox** [comment]
@kuitos  大佬有什么好的建议吗

**Comment by kuitos** [comment]
具体报什么错？

**Comment by wubobuaa** [comment]
tinymce源码里很多地方用到了window对象，导致报错
![QQ截图20200820174817](https://user-images.githubusercontent.com/2927031/90755209-7d085700-e30d-11ea-8ca9-b63eff3c008f.jpg)

**Comment by kuitos** [comment]
具体报什么错...

**Comment by cloydlau** [comment]
错是在tinymce里面报的：```Error in mounted hook: "TypeError: Cannot read property 'scroll' of undefined"```
子系统独立启动没问题

**Comment by shichuanpo** [comment]
> 具体报什么错...

应该是qiankun用了严格模式，tinymce又是bind(this)去绑定的事件，导致this指向为空

**Comment by Rabbitzzc** [comment]
想知道手动挂载子应用，如何对 window 对象中某些字段在子应用中进行隔离，比如主应用 `window.Vue`，不想在子应用中也能访问到该属性

**Comment by CrazyLiar** [comment]
请问... 这个问题解决了吗，同遇到

**Comment by bossikill** [comment]
同样碰到了
start({
  sandbox: { strictStyleIsolation: false }
})

就好了..但是样式就难受了

**Comment by shichuanpo** [comment]
您好！邮件已收到！

**Comment by shichuanpo** [comment]
您好！邮件已收到！

**Comment by jiale01** [comment]
你好我也有这个问题，请问解决了吗

**Comment by dengBox** [comment]
> 你好我也有这个问题，请问解决了吗

需要关闭沙箱的严格模式，或者升级qiankun到最新版本。

**Comment by lvchengli** [comment]
试一下 new globalThis.Function("return this")()

**Comment by shichuanpo** [comment]
您好！邮件已收到！
