### ISSUE TITLE
[Feature Request] 在vue中如何keep-alive子站点界面

### ISSUE THREAD

**Issue by theshying** [umijs/qiankun#469]
后台系统是多tab的风格，每个tab都加载子站点的界面，那么在切换各个tab的时候如何才能能保界面数据保存住呢? 类似于vue中的keep-alive效果？ 有什么好的解决方案吗？

目前想要到的就是把render后的appContent html缓存在内存中，但是各个tab对应的js沙箱好像路由变了就会unmount了， 无法实现上述需求，框架层面有提供这方面的支持吗？

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/361
