### ISSUE TITLE
Master 和 Slave 同时引入相同子应用，样式挂载有可能出错

### ISSUE THREAD

**Issue by dbkillerf6** [umijs/qiankun#472]
## What happens?

Master 和 Slave（同一时间共存的引用），同时使用 loadMicroApp 引入相同的子应用（暂命名：Widget），会在两个同名 dom 上挂载样式表：

<img width="520" alt="3145E336-9C30-450B-9F3E-E9C5702ABB80" src="https://user-images.githubusercontent.com/59460901/79757154-4239e680-834e-11ea-8854-7596f98887fd.png">

由于 Slave 的 dom 层级比 Master 深，如果 SlaveWidget 的样式表在 MasterWidget 之后挂载，就会挂载到 MasterWidget 上：

<img width="737" alt="D2C4A5B6-9650-42E1-8BBA-14F01C087481" src="https://user-images.githubusercontent.com/59460901/79757586-dd32c080-834e-11ea-8e4b-a5679f0f4e5d.png">

## 解法
- 让 Master 引入并把 loadMicroApp 传递给 Slave，保证使用的都是同一个方法，但用起来不灵活
- 把 appInstanceCounts 挂到全局，不是很优雅
- appInstanceId 后缀使用时间戳保证唯一性，推荐

**Comment by kuitos** [comment]
> 让 Master 引入并把 loadMicroApp 传递给 Slave，保证使用的都是同一个方法

原来是设想用这个方式做微应用嵌套的，通过 props 将 loadMicroApp 传给子应用，主要原因是 single-spa 官方的 parcel 嵌套就是通过 props 做的，qiankun 也使用这个方式可以直接复用 single-spa 的一些能力，比如微应用卸载后，微应用嵌套的微应用也会自动卸载。

**Comment by howel52** [comment]
> 这个方式的问题是会导致组件级别的微应用无法脱离宿主独立运行了，确实不够解耦。

组件级别的微应用应该不用考虑是否需要脱离宿主独立运行吧，时间戳的解法我觉得比较完美了。
