### ISSUE TITLE
[Bug]使用qiankun时如果子项目是react项目本地开发联调时总是报错

### ISSUE THREAD

**Issue by Pingan2018** [umijs/qiankun#475]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
loader.js:262 Uncaught Error: application 'react' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in react entry

app是使用乾坤的父项目，react16是react脚手架生成的子项目，vue2是vue脚手架生成的vue子项目，子项目和父项目都启动后更改react子项目中的内容会报以上错误
## 最小可复现仓库
https://git.lug.ustc.edu.cn/hongshudashu/qiankun-test.git

## 复现步骤，错误日志以及相关配置
1、先启动react项目，在启动vue项目，最后启动app父项目，然后改变把vue项目中home路由名称改为home1，本地保存，vue项目中状态试试改变为home1，app项目中vue子项目的路由名称也实时改变为home1，然后改变react项目中的home路由名称为home1，本地保存，react子项目中状态实时改变，但是app父项目中react子项目无变化，刷新app项目，浏览器就会报以上错误
2、还有一个问题就是soucemap文件总是加载失败
loader.js:262 Uncaught Error: application 'react' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in react entry

## 相关环境信息

- **qiankun 版本**："^1.3.14"
- **浏览器版本**：Chrome 80.0.3987.163
- **操作系统**：window 10    64位

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/340
