### ISSUE TITLE
手动加载微应用时直接跳转到了结束应用中

### ISSUE THREAD

**Issue by 554027743** [umijs/qiankun#476]
> 子系统进入成功
prefetch.js?6036:72 [qiankun] prefetch starting after  mounted... (3) [{…}, {…}, {…}]
vue.runtime.esm.js?2b0e:8429 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
main.js?56d7:20 离开子系统了
sandbox.js?a973:130 [qiankun:sandbox] app4 modified global properties restore... (6) ["__INJECTED_PUBLIC_PATH_BY_QIANKUN__", "webpackHotUpdatedajiayiyang4", "dajiayiyang4", "webpackJsonp_antd-demo", "__VUE_HOT_MAP__", "__INJECTED_PUBLIC_PATH_BY_QIANKUN__"]
loader.js?6f14:19 Uncaught (in promise) Error: parcel 'app4_0' died in status UNMOUNTING: [qiankun] target container with #app4 not existed while rendering!
    at assertElementExist (loader.js?6f14:19)
    at render (loader.js?6f14:119)
    at eval (loader.js?6f14:401)
    at step (tslib.es6.js?9ab4:100)
    at Object.eval [as next] (tslib.es6.js?9ab4:81)
    at eval (tslib.es6.js?9ab4:74)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:70)
    at unmount (loader.js?6f14:399)
    at eval (single-spa.min.js?25a2:2)
### 子系统配置
- configureWebpack: {
-         output: {
-             library: `${packageName}`,
-             libraryTarget: 'umd',
-             jsonpFunction: `webpackJsonp_${packageName}`,
-         }
-     },

### 子系统函数

`//主系统加载前的回掉
export async function bootstrap(props) {
  console.log('开始进入了子系统')
}

export async function mount(props) {
  console.log('这是从主系统传来的参数='+props)
  console.log('子系统进入成功')
}

export async function unmount(props) {
  console.log('离开子系统了')
  
}

export async function update(props) {
  console.log('调用了手动加载子系统的方法，参数是=', props);
}`

**Comment by 554027743** [comment]
当我把子应用和主应用的  output.library 设为一样时就正常了。
这是什么问题啊？

**Comment by kuitos** [comment]
注意看报错信息
> Uncaught (in promise) Error: parcel 'app4_0' died in status UNMOUNTING: [qiankun] target container with #app4 not existed while rendering!

**Comment by 554027743** [comment]
我挂载的 dom叫 app4 但是不知道为什么会出现一个 app4_0的子系统报错

**Comment by 554027743** [comment]
> 注意看报错信息
> 
> > Uncaught (in promise) Error: parcel 'app4_0' died in status UNMOUNTING: [qiankun] target container with #app4 not existed while rendering!

我的子系统叫 app4 不知道为什么会生成 app_4加载失败的报错
