### ISSUE TITLE
手动加载微应用，返回的微应用实例上没有 update 方法

### ISSUE THREAD

**Issue by pineapplejs** [umijs/qiankun#477]
## What happens?

使用手动加载微应用方式，返回的微应用实例上没有 update 方法

![3](https://user-images.githubusercontent.com/20431351/79833377-d7d08700-83dd-11ea-90f3-dee2132bcb8e.png)

![1](https://user-images.githubusercontent.com/20431351/79832865-e7030500-83dc-11ea-8c34-d1e723e0e5ec.png)

文档中的使用

![2](https://user-images.githubusercontent.com/20431351/79832900-f3875d80-83dc-11ea-925a-af8f16ee65f1.png)

## Context

- **qiankun Version**: 2.0.2
- **Platform Version**: MacOS 10.15.5
- **Browser Version**: Chrome 84.0.4120.0

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/79856479-fdba5380-83fe-11ea-857c-4ba1311f292c.png)

**Comment by pineapplejs** [comment]
@kuitos 微应用里已经导出 update 钩子了，但是主应用里手动加载微应用返回的实例上没有 update 方法，调用会报错。

**Comment by kuitos** [comment]
released v2.0.4

**Comment by Topthinking** [comment]
> released v2.0.4

2.4.10 也有这个问题

**Comment by Topthinking** [comment]
@keyding 你解决了么，我怎么安装2.0.4版本，这个问题还在啊

**Comment by Topthinking** [comment]
![image](https://user-images.githubusercontent.com/13382821/133064987-c57e7922-8841-4fe6-bfbf-8c4228038bca.png)

```
// 打印原型a，看到update。但是直接调用就是undefined
console.log(2222,a,'update>>>:',a.update);
```

**Comment by Topthinking** [comment]
@sorrycc

**Comment by yzwxk** [comment]
> ![image](https://user-images.githubusercontent.com/13382821/133064987-c57e7922-8841-4fe6-bfbf-8c4228038bca.png)
> 
> ```
> // 打印原型a，看到update。但是直接调用就是undefined
> console.log(2222,a,'update>>>:',a.update);
> ```

能看到，调用是undefined，很有可能是update和load间隔太近。毕竟load是个promise。可以试试
`
if (this.microApp) {
  this.microApp.mountPromise.then(() => {
   this.microApp.update()
    })
  }
  `
