### ISSUE TITLE
手动加载子应用时，挂载节点会被替换成 id="app"

### ISSUE THREAD

**Issue by 554027743** [umijs/qiankun#478]
**我有几个动态挂载点** 

- `<div :id="item.name"></div>`

**手动加载子应用**

- `microApp = loadMicroApp(`
        `{`
          `name: cObj.name, //应用的名称`
          `entry: cObj.entry, //子系统路径`
          `container: cObj.container //子系统对应的`
        `},`
       ` {`
          `singular: true, //启动多系统状态`
          `sandbox:{ strictStyleIsolation: true }`
        `}`
     ` );`

**子应用被加载后  【例如我的id=app4的话 加载完成后就变成 id=app】**
**加载多个后id都为id="app"**

**然后会报错**

- `parcel 'app4_0' died in status SKIP_BECAUSE_BROKEN: [qiankun] target container with #app4 not existed while rendering!`

大神帮忙看下怎么解决

**Comment by 554027743** [comment]
我跟踪了代码，好像是在进入子系统的 bootstrap 后就把我挂载点删除掉了？为什么啊？

**Comment by kuitos** [comment]
目测是你子应用把节点给覆盖了。
如果不是提供可复现仓库

**Comment by lianghx-319** [comment]
如果主应用也是 Vue 和 React 的话。渲染流程是这样的
1. 主应用 render，挂载在一个 id 上
2. qiankun 启动
3. fetch 子应用
4. 子应用也是 Vue 和 React 之类，也会找一个 id 挂载
5. 如果主应用和子应用挂载的 id 刚好一样就会把主应用的全部 dom 覆盖掉了

**Comment by dbkillerf6** [comment]
我们也遇到过同样的问题，目前解法是把样式和 dom 挂到两个 div 上：

主应用：
```ts
import React, { useRef, useEffect } from 'react';
import { loadMicroApp } from 'qiankun';
import { IReactWidgetLoaderProps } from '../interface';

const ReactWidget: React.FC<IReactWidgetLoaderProps> = props => {
  const containerId = `widget-${props.name}-${+new Date()}`;
  const widgetRef = useRef<Record<string, any>>({});

  const { name, entry, config } = props;

  useEffect(() => {
    const ref = loadMicroApp({
      name,
      entry,
      container: `#${containerId}-style`,
      props: {
        config,
        containerId: `${containerId}-dom`,
      },
    });

    widgetRef.current = ref;

    return () => {
      const { current } = widgetRef;
      current.mountPromise.then(() => current.unmount());
    };
  }, []);

  return (
    <div id={containerId}>
      <div id={`${containerId}-style`} />
      <div id={`${containerId}-dom`} />
    </div>
  );
};

export default ReactWidget;
```

子应用：
```ts
export async function mount(props: any) {
  ReactDOM.render(
    <Component {...props} />,
    document.getElementById(props.containerId) as HTMLElement
  );
}
```

**Comment by dbkillerf6** [comment]
> 目测是你子应用把节点给覆盖了。

目前用 `loadMicroApp` 的时候，会在`container` 上生成 `${container}_${count}` 的 dom 来挂载样式，但是微应用也会在 mount 的时候挂载。

也就是说，如果微应用挂载的节点也是 `container` 的话，样式和微应用的挂载就会有冲突。

**Comment by kuitos** [comment]
```jsx
<div id={containerId}>
    <div id={`${containerId}-style`} />
    <div id={`${containerId}-dom`} />
</div>
```

这个不是合理的做法，微应用渲染的 dom 容器应该是自己在自己的 html 里声明，不应该由主应用来提前构建好。比如微应用的 html 自己声明一个 `<div id={`${containerId}-dom`} />` 容器。

**Comment by dbkillerf6** [comment]
> 这个不是合理的做法，微应用渲染的 dom 容器应该是自己在自己的 html 里声明，不应该由主应用来提前构建好。比如微应用的 html 自己声明一个 `<div id={${containerId}-dom} />` 容器。


这个很赞同，已变更：
```html
<div id={containerId} />
```
```ts
export async function mount(props: any) {
  ReactDOM.render(
    <HeaderComponent {...props} />,
    document.querySelector(`#${props.containerId} #root`) as HTMLElement
  );
}
```

**Comment by kuitos** [comment]
如果有可复现仓库可以随时 reopen
