### ISSUE TITLE
[Bug]当子系统中的html里有script时，会被import-html-entry替换

### ISSUE THREAD

**Issue by cloudZQY** [umijs/qiankun#479]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
子系统的html中有inline scripts时，被import-html-entry替换

## 复现步骤，错误日志以及相关配置
官方example加script标签就可复现，inline scripts会被转换成\

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
by design

**Comment by yangdan8** [comment]
这个还没有处理吗?使用shadow dom方式是不行的

**Comment by myNameCao** [comment]
想知道 这个问题 最后 怎么 解决了？

**Comment by Rabbitzzc** [comment]
qiankun 是通过 import-html-entry 获取的子应用 js，然后解析出子应用 js 的 text。然后 qiankun 创造自己的上下文执行子应用的 js，因此页面上存在这个标识。。。

**Comment by oufeng** [comment]
同问解决方案
