### ISSUE TITLE
shadow-dom开启后，element-ui的弹窗 不能正常使用

### ISSUE THREAD

**Issue by daichunlin1995** [umijs/qiankun#481]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

主应用开启了shadow-dom加载子应用之后 ，子应用中使用了element-ui的弹窗类或选择类组件，出现报错

## 错误展示

![image](https://user-images.githubusercontent.com/55657083/79840982-4ebf4d00-83e9-11ea-8514-977da9d2c3f2.png)

## 相关环境信息

- **qiankun 版本**：2.0.2
- **浏览器版本**：chrome
- **操作系统**：win10

**Comment by simoncx** [comment]
同求隔离开启后此类错误该如何解决？

**Comment by Deturium** [comment]
这种也需要组件库配合，我看你也在那边开了 issue

https://github.com/ElemeFE/element/issues/19226

**Comment by kuitos** [comment]
组件库需要解决在shadow dom 下渲染的问题

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/api/#%E6%89%8B%E5%8A%A8%E5%8A%A0%E8%BD%BD%E5%BE%AE%E5%BA%94%E7%94%A8
![image](https://user-images.githubusercontent.com/5206843/80508632-e05f2980-89aa-11ea-9e6d-5002c9e18d70.png)

**Comment by winterZhao** [comment]
sandbox: false  把沙箱关掉临时解决一下

**Comment by brandonxiang** [comment]
用antd也有同样的问题，感觉sandbox的门槛好高
