### ISSUE TITLE
子项目中的 js 文件有用到 loadscript 加载其他脚本，在微服务下，没有执行对应的回调函数

### ISSUE THREAD

**Issue by BruceCham** [umijs/qiankun#484]
## What happens?
微服务下的子项目中的 js 文件有用到 loadscript 加载阿里云的滑动验证脚本：http://g.alicdn.com/sd/nvc/1.1.154/nvch5.js
loadscript('nvch5.js', function(){})
微服务加载 nvch5.js 后，没有执行对应的回调函数

## 最小可复现仓库
```
可访问的环境地址：
http://m.xueersibook.com/cicp/store/user/login
```

## 复现步骤，错误日志以及相关配置
操作步骤
```
操作步骤：
1、输入手机号
2、点击发送验证码
预期：
3、出现滑块验证
结果
3、由于滑块服务的脚本加载后没有执行对应的回调函数，滑动验证功能没有出现 
```

js 文件地址http://g.alicdn.com/sd/nvc/1.1.154/nvch5.js  
loadscript 加载的 js 文件 //g.alicdn.com/sd/nch5/index.js?_t=440981  
截图显示

<img alt="代码断点截图" title="代码断点截图" src="https://xesbook-static-test.oss-cn-beijing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202020-04-21%2021.28.01.png" />

## 相关环境信息

- **qiankun 版本** 2.0.2
- **浏览器版本**：chrome 80.0.3987.163
- **操作系统**：Mac 10.13.6

**Comment by kuitos** [comment]
提供可复现仓库
