### ISSUE TITLE
import-html-entry的getGlobalProp实现不合理

### ISSUE THREAD

**Issue by canlatte** [umijs/qiankun#485]
看代码noteGlobalProps和getGlobalProp方法是配对使用的
先用noteGlobalProps记录全局变量，找出第一第二最后一个属性
执行entry代码后再用getGlobalProp方法看第一第二最后一个属性是否变化，变化的话就是导出的生命周期方法

这个实现依赖对象属性的遍历顺序，js标准中对对象属性遍历顺序是没有规定的，各个浏览器实现不一样，chrome的不同版本也不一样，有一些版本是按首字母顺序遍历的，像搜狗这些浏览器则是会在全局变量里加上很多浏览器的变量，导致最后一个属性可能是浏览器的属性，结果是找不到生命周期方法

建议把属性名和子应用名做强约定，导出生命周期方法属性名必须和应用名相同，这样直接用应用名找全局变量，避免这种情况

**Comment by kuitos** [comment]
1. 对象属性的遍历顺序自 es6 之后实际是有 ecmascript 规范的，即不论是使用 for each 还是 Object.keys 都是有顺序规定的，具体可查 https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys
2. 对于一些低版本或者没有按规范实现的浏览器，qiankun 也做了 fallback https://github.com/umijs/qiankun/blob/b02c71b496253b44a3b614bfd87358a1c18446b1/src/loader.ts#L146
