### ISSUE TITLE
加载一个子应用后，如何手动指定子应用跳转的路由地址呢？

### ISSUE THREAD

**Issue by theshying** [umijs/qiankun#486]
目前自动加载一个子应用之后，子应用会根据url去匹配对应的路由，

但使用手动加载子应用的时候，如何指定url让子应用去匹配？

**Comment by kuitos** [comment]
没理解“指定url让子应用去匹配”是啥意思？

url 就在浏览器地址栏，子应用 mount 之后自己就能获取到，你没办法指定吧。
如果你指希望跟自动加载的机制一样，那就在相应的路由下手动加载子应用就好了。

除非你说的是 memory router？https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/MemoryRouter.md

**Comment by theshying** [comment]
需求和#487类似，就是在主站点的一个界面中需要加载多个子站点的界面来组合生成，看文档的描述，这种需求目前为止应该是实现不了的吗？

**Comment by xjchenhao** [comment]
> 需求和[#487](https://github.com/umijs/qiankun/issues/487)类似，就是在主站点的一个界面中需要加载多个子站点的界面来组合生成，这种需求目前为止应该是实现不了的吗？
> 
> 看文档的描述，手动加载子应用以后会自动根据浏览器url地址去匹配（而没办法手动指定url），那针对上述情况，同一个界面中永远只会有一个子应用的界面能正常显示。

这个需求+1
