### ISSUE TITLE
多个子应用加载到同一页面，某个子应用路由跳转时其他子应用如何保持页面不变？

### ISSUE THREAD

**Issue by simoncx** [umijs/qiankun#487]
请教一下，加载了多个子应用到同一个界面，那么当某个子应用跳转路由的时候，如何让其他的应用保持不变? 而不是显示空白？

![image](https://user-images.githubusercontent.com/6457365/79953625-c0ad9a00-84ae-11ea-8710-9a3535d2929b.png)

我看到文档里面有说：
![image](https://user-images.githubusercontent.com/6457365/79959955-5f3df900-84b7-11ea-841c-eedc178897c1.png)

是不是指在同一个页面不能同时存在有多个需要做路由跳转的子应用？现在2.0版本也是如此？

- **qiankun 版本**：2.0
- **浏览器版本**：Chrome
- **操作系统**： win 10

**Comment by kuitos** [comment]
正如文档里所说，浏览器的 url 只有一个。
比如别人喊张三的时候，除非两个人都叫张三，不然肯定只有一个人会答应。

这个跟 qiankun 什么版本无关，qiankun 不会控制你的路由。

**Comment by simoncx** [comment]
> 正如文档里所说，浏览器的 url 只有一个。
> 比如别人喊张三的时候，除非两个人都叫张三，不然肯定只有一个人会答应。
> 
> 这个跟 qiankun 什么版本无关，qiankun 不会控制你的路由。

能请教一下，如果想要实现这种效果，有没有什么比较好的思路呢？

**Comment by theshying** [comment]
找到解决的办法了吗

**Comment by theshying** [comment]
> > 正如文档里所说，浏览器的 url 只有一个。
> > 比如别人喊张三的时候，除非两个人都叫张三，不然肯定只有一个人会答应。
> > 这个跟 qiankun 什么版本无关，qiankun 不会控制你的路由。
> 
> 非常感谢您的答复，能请教一下，如果想要实现这种效果，有没有什么比较好的思路呢？目前想要实现的效果就是当某个模块点击切换路由的时候，只是那个模块会变化，其他模板不会有任何变化，还是停留在之前的路由界面。
> 
> 我在想如果通过基座应用去接管子应用的路由，能不能行得通。

找到解决的办法了吗? 我也遇到了同样的问题

**Comment by Cyberpunkerplus** [comment]
> > 正如文档里所说，浏览器的 url 只有一个。
> > 比如别人喊张三的时候，除非两个人都叫张三，不然肯定只有一个人会答应。
> > 这个跟 qiankun 什么版本无关，qiankun 不会控制你的路由。
> 
> 非常感谢您的答复，能请教一下，如果想要实现这种效果，有没有什么比较好的思路呢？目前想要实现的效果就是当某个模块点击切换路由的时候，只是那个模块会变化，其他模板不会有任何变化，还是停留在之前的路由界面。
> 
> 我在想如果通过基座应用去接管子应用的路由，能不能行得通。
可以实现的，创建出一个同域iframe，管理你的子应用location,我这边已经试验成功

**Comment by xjchenhao** [comment]
> > > 正如文档里所说，浏览器的 url 只有一个。
> > > 比如别人喊张三的时候，除非两个人都叫张三，不然肯定只有一个人会答应。
> > > 这个跟 qiankun 什么版本无关，qiankun 不会控制你的路由。
> > 
> > 
> > 非常感谢您的答复，能请教一下，如果想要实现这种效果，有没有什么比较好的思路呢？目前想要实现的效果就是当某个模块点击切换路由的时候，只是那个模块会变化，其他模板不会有任何变化，还是停留在之前的路由界面。
> > 我在想如果通过基座应用去接管子应用的路由，能不能行得通。
> 
> 可以实现的，创建出一个同域iframe，管理你的子应用location,我这边已经试验成功

通过iframe加载了子应用以后，回到真正在主应用渲染的子应用不会出现渲染不出来“白屏”的情况吗？

**Comment by loioce** [comment]
一个页面的某个区域加载多个子应用，只能用iframe加载么？能不能再子应用里面手动加载呢？但是怎么跳转到子应用具体的页面我没有什么思路
