### ISSUE TITLE
document 沙盒环境

### ISSUE THREAD

**Issue by kwoktung** [umijs/qiankun#493]
## What happens?
在沙盒环境样式隔离的环境下。子应用document. getElementById 等API因为应用在shadowDOM里面。所以没有办法获取正确数据。建议对document.getElementById等 做打补丁处理（先在shadowDOM查询然后在去document上查询），才能达到子应用完全技术隔离。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/umijs/qiankun/blob/v2.0.0/examples/main/index.js#L96

官方仓库里面的example。将start的sandbox的参数改为{ strictStyleIsolation：true }

这样子子应用在 shadowDOM中，子应用中的例如 React 在 unmount的时候

需要从 props.container 获取 unmount 的节点

`  ReactDOM.unmountComponentAtNode(
    container ? container.querySelector('#react15Root') : document.getElementById('react15Root'),
  );`

但是一些 外部库可不知道啊，很容易写出`document.getElementById('react15Root')`报错。没有所谓的 JS 隔离的效果啊啊啊，建议是不是可以打补丁啊啊啊。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.0.0
- **Platform Version**: osx 10.14.11
- **Browser Version**: chrome

**Comment by tantuer** [comment]
我也有差不多的问题，子应用如果想用window对象，貌似获取不到？

**Comment by kwoktung** [comment]
> 我也有差不多的问题，子应用如果想用window对象，貌似获取不到？

window 对象有在沙盒里面。但是 document没有

window 沙盒见 https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L47

**Comment by tantuer** [comment]
> > 我也有差不多的问题，子应用如果想用window对象，貌似获取不到？
> 
> window 对象有在沙盒里面。但是 document没有
> 
> window 沙盒见 https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L47

在子应用如何调用window啊?

**Comment by QxQstar** [comment]
> > > 我也有差不多的问题，子应用如果想用window对象，貌似获取不到？
> > 
> > 
> > window 对象有在沙盒里面。但是 document没有
> > window 沙盒见 https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L47
> 
> 在子应用如何调用window啊?

可以使用 top 变量

**Comment by kuitos** [comment]
不应该做 document 的隔离，问题很多，而且 qiankun 相比 iframe 有一个重要的优势就是 dom 结构是共享的，从而可以避免很多 UI 交互上的问题。

ShadowDOM 导致的内部应用无法直接使用 document.querySelector 查询节点的问题不应该是 qiankun 来解决，应该是微应用自身或者组件库需要提供适配 ShadowDOM 环境的配置，因为即便没有 qiankun，你自己使用 ShadowDOM，这些问题还是存在的。

**Comment by poorli** [comment]
> 不应该做 document 的隔离，问题很多，而且 qiankun 相比 iframe 有一个重要的优势就是 dom 结构是共享的，从而可以避免很多 UI 交互上的问题。
> 
> ShadowDOM 导致的内部应用无法直接使用 document.querySelector 查询节点的问题不应该是 qiankun 来解决，应该是微应用自身或者组件库需要提供适配 ShadowDOM 环境的配置，因为即便没有 qiankun，你自己使用 ShadowDOM，这些问题还是存在的。

前辈，请问您那边有好的实践吗？我们是接入老的项目，有不少地方有使用 document.querySelector

**Comment by kwoktung** [comment]
> > 不应该做 document 的隔离，问题很多，而且 qiankun 相比 iframe 有一个重要的优势就是 dom 结构是共享的，从而可以避免很多 UI 交互上的问题。
> > ShadowDOM 导致的内部应用无法直接使用 document.querySelector 查询节点的问题不应该是 qiankun 来解决，应该是微应用自身或者组件库需要提供适配 ShadowDOM 环境的配置，因为即便没有 qiankun，你自己使用 ShadowDOM，这些问题还是存在的。
> 
> 前辈，请问您那边有好的实践吗？我们是接入老的项目，有不少地方有使用 document.querySelector

我们可不可以Sub App 在生命周期里面mount的阶段document.querySelector 覆盖。然后在unmount的阶段在还原？？

**Comment by zjy7** [comment]
> > > 不应该做 document 的隔离，问题很多，而且 qiankun 相比 iframe 有一个重要的优势就是 dom 结构是共享的，从而可以避免很多 UI 交互上的问题。
> > > ShadowDOM 导致的内部应用无法直接使用 document.querySelector 查询节点的问题不应该是 qiankun 来解决，应该是微应用自身或者组件库需要提供适配 ShadowDOM 环境的配置，因为即便没有 qiankun，你自己使用 ShadowDOM，这些问题还是存在的。
> > 
> > 
> > 前辈，请问您那边有好的实践吗？我们是接入老的项目，有不少地方有使用 document.querySelector
> 
> 我们可不可以Sub App 在生命周期里面mount的阶段document.querySelector 覆盖。然后在unmount的阶段在还原？？

可以吗

**Comment by wangfpp** [comment]
如何使用window和document啊
