### ISSUE TITLE
请问支持es5的用法吗，支持导出umd模式吗？

### ISSUE THREAD

**Issue by taoyan-t** [umijs/qiankun#496]
请问支持es5的用法吗，支持导出umd模式吗？

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq/#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F

**Comment by taoyan-t** [comment]
> https://qiankun.umijs.org/zh/faq/#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F
你好，是主应用是es5的模式下，你说的是子应用

**Comment by xiaoxiaofan123** [comment]
请问找到方法了吗
