### ISSUE TITLE
紧急！乾坤2.0.2版本，引用的single-spa不支持ie11，出现了箭头函数

### ISSUE THREAD

**Issue by JinJieTan** [umijs/qiankun#499]
紧急！乾坤2.0.2版本，引用的single-spa不支持ie11，出现了箭头函数不支持的语法

![image](https://user-images.githubusercontent.com/47209029/80057320-d7a8c680-8558-11ea-9c94-dd32b0e372af.png)

**Comment by kuitos** [comment]
代码是你自己打包编译的，请自行处理，如果不知道怎么处理请移步 babel 文档或 google https://babeljs.io/docs/en/babel-preset-env

请注意 issue 区不是 stackoverflow
