### ISSUE TITLE
支持spa+ssr的模式

### ISSUE THREAD

**Issue by GitHubForQiuKai** [umijs/qiankun#5]
能支持支持spa+ssr的模式吗，是否有栗子

**Comment by kuitos** [comment]
qiankun 只是能让你更方便的用微前端的 library，能不能支持 ssr 得看上层怎么用的

**Comment by kuitos** [comment]
closed via deactivated, if your problem not solved, feel free to reopen

**Comment by guojingwen** [comment]
> qiankun 只是能让你更方便的用微前端的 library，能不能支持 ssr 得看上层怎么用的

以 vue ssr 为主应用   使用webpack构建   开发是  样式会丢失

**Comment by poryzhao** [comment]
项目使用nextjs做的ssr，这种情况还可以使用qiankun来将其改造成子应用吗？

尝试在registerMicroApps中注册了它，但是父应用会导致浏览器卡死，没有报错信息。
