### ISSUE TITLE
nuxt为主应用时，我写在了plugin中，container需要怎么配置呢？

### ISSUE THREAD

**Issue by Wendy123123** [umijs/qiankun#500]
nuxt为主应用时，我写在了plugin中，container需要怎么配置呢？

`import {registerMicroApps, start} from 'qiankun'

registerMicroApps([
  {
    name:  'seamodel-webapp', // app name registered
    entry:  '//localhost:7100',
    container:  '#yourContainer',  // 头脑断裂???
    activeRule:  '/seamodel',
  },
]);

start();`

**Comment by kuitos** [comment]
这个你需要自己想办法了，比如提供一个固定或一定规则的 container id
