### ISSUE TITLE
在子应用中使用百度地图跨域的问题

### ISSUE THREAD

**Issue by feihua666** [umijs/qiankun#501]
子应用中使用了百度地图，在使用百度地图根据地理位置获取坐标时会加载额外的js，会有触发方式fetch和script的区别，导致跨域问题
1.未使用qiankun情况下：
  正常
2.qiankun版本1.4.6情况下：
  开启沙箱：fetch触发方式，导致跨域问题
  关闭沙箱：script触发方式，正常
3.qiankun版本2.0.4情况下：
  无论开启还是关闭沙箱：fetch触发方式，导致跨域问题

是qiankun代理了js的请求？

firefox 75.0(64位)

**Comment by howel52** [comment]
see: https://qiankun.umijs.org/faq/#must-a-sub-app-asset-support-cors

**Comment by feihua666** [comment]
> 
> 
> see: https://qiankun.umijs.org/faq/#must-a-sub-app-asset-support-cors

感谢回复，我看了这个问题的解决方式。
但我觉得这种方式是适合一次性引用第三方脚本，比如jQquery,jQquery是一个整体脚本不会再动态加载其它脚本。
但百度地图的入口脚本只提供了基础功能，如果使用其它功能时百度地图自己会加载额外的脚本，而这些额外的脚本不可能一次全部引入。
是不是只能将请求百度的域名替换成自己的域名，然后再用nginx去代理？

**Comment by Xujun007** [comment]
方便告知下你这个问题最终的解决方案吗？
我在乾坤的官网上看了提供的解决方式，不太适合地图这个场景。
