### ISSUE TITLE
主应用切换路由时，子应用找不到container设置的容器

### ISSUE THREAD

**Issue by daichunlin1995** [umijs/qiankun#505]
## What happens?

主应用中将container：#id 容器设置在了一个组件里面，切换路由，就会报错；测试了下，发现组件卸载发生在子应用卸载之前，请问这个该怎么解决

## 最小可复现仓库
![image](https://user-images.githubusercontent.com/55657083/80179250-b4eae080-8632-11ea-954d-93155634d59a.png)

## 相关环境信息

- **qiankun 版本**2.0
- **浏览器版本**：chrome
- **操作系统**：win10

**Comment by taoyan-t** [comment]
我用qiankun 2.0.4版本也有这个错，两个子路由切换就报这个错

**Comment by daichunlin1995** [comment]
> 我用qiankun 2.0.4版本也有这个错，两个子路由切换就报这个错

是的 我使用render 的形式也不行，就是一定要存在这个container

**Comment by kuitos** [comment]
升级到 v2.0.5
