### ISSUE TITLE
[Feature Request] Support of `type=module` and `nomodule` attribute in `import-html-entry`

### ISSUE THREAD

**Issue by iplus26** [umijs/qiankun#507]
## Background

Angular Cli inserts `<script type=module src="polyfill.es2015.js">` and `<script nomodule src="polyfill.es5.js">` into `index.html`, for differential loading. 

`import-html-entry` doesn't recognize the attributes, and load two javascript file both.

## Proposal

`import-html-entry` should recognize `type=module` and `nomodule` attributes, and import only one of two.

If no one is working on this, I would like to create a PR for `import-html-entry` package.

## Additional context

* [Angular Differential Loading](https://angular.io/guide/deployment#differential-loading)
* [MDN: `nomodule` attribute of script tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-nomodule)

**Comment by kuitos** [comment]
pr is welcome
