### ISSUE TITLE
手动加载微应用的时候报错

### ISSUE THREAD

**Issue by Clive-Wang** [umijs/qiankun#508]
#422  What happens?
我这里在主应用里面，调用loadApp方法去加载微应用，挂载到<div id="app-view-box"></div>
export function loadApp(){
	const microApp = loadMicroApp({
		name: 'app1',
		entry: 'http://localhost:8091',
		container: '#app-view-box'
	}, {singular:true});
}
在子应用main.js函数中：
import Vue from "vue";
import VueRouter from "vue-router";
import App from "./App.vue";
import routes from "./router";
import "./public-path";

Vue.config.productionTip = false;

let router = null;
let instance = null;

function render() {
  router = new VueRouter({
    base: window.__POWERED_BY_QIANKUN__ ? "/app1" : "/",
    mode: "hash",
    routes
  });

  instance = new Vue({
    router,
    render: h => h(App)
  }).$mount("#app");
}

if (!window.__POWERED_BY_QIANKUN__) {
  render();
}

export async function bootstrap() {
  console.log("vue app bootstraped");
}

export async function mount(props) {
  console.log("props from main app", props);
  render();
}

// 增加 update 钩子以便主应用手动更新微应用
export function update(props) {
  console.log("props from main app， update", props);
  render();
}

export async function unmount() {
  instance.$destroy();
  instance = null;
  router = null;
}

## 复现步骤，错误日志以及相关配置

现在报错，如下：
error occurs while executing the entry http://localhost:8091/static/js/app.js
Uncaught (in promise) TypeError: Cannot redefine property: $router
    at Function.defineProperty (<anonymous>)
    at Function.install (VM110645 vue-router.esm.js:1248)
    at Function.Vue.use (vue.min.js:4584)
    at eval (VM110645 vue-router.esm.js:2916)
有没有大神遇见过这样的问题，求助！

## 相关环境信息
- **qiankun 版本** ： 2.0.3
- **浏览器版本**：Google Chrome 64.0.3282.140
- **操作系统**：win7

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#vue-router-%E6%8A%A5%E9%94%99-uncaught-typeerror-cannot-redefine-property-router

**Comment by Clive-Wang** [comment]
> see https://qiankun.umijs.org/zh/faq/#vue-router-%E6%8A%A5%E9%94%99-uncaught-typeerror-cannot-redefine-property-router

加载子应用的时候，报错：Uncaught (in promise) ReferenceError: __webpack_require__ is not defined，是什么原因导致的

**Comment by ygwoo** [comment]
如果全局环境必须需要存在Vue且不可改名字，可以通过配置子应用webpack，编译打包时替换掉’window.Vue.use(VueRouter);‘即可。
`
  config.module
      .rule('string-replace')
      .test(/vue-router\.(common|esm)\.js$/) // 替换vue-router文件的实际路径匹配
      .use('string-replace-loader')
      .loader('string-replace-loader')
      .options({
        search: 'window\\.Vue\\.use\\(VueRouter\\)\\s*;?',
        replace: '// 自动注册个屁(╯>д<)╯⁽˙³˙⁾',
        flags: 'g',
      })
      .end();
`
