### ISSUE TITLE
[Feature Request] loadMicroApp 能不能返回解析好的字符串缓存起来,更加灵活

### ISSUE THREAD

**Issue by crper** [umijs/qiankun#510]
现在声明式的,可以拿到appContent,
那loadMicroApp可否提供一些能力,
比如我拿到整个加载后的实例,方便自己在某些区域,直接插入dom结构.
达到更灵活的切换子应用的效果!

**Comment by kuitos** [comment]
1. render 2.0 已经不推荐了，如果你开始用了 2.0 的话应该会看到开发阶段的警告
2. 如果是 1.x 版本，render 回调提供的 appContent 怎么处理怎么渲染完全由用户自己决定，比如你完全可以自己通过 appContent 构建出 dom，拿到这个 dom 后想干嘛都行

**Comment by crper** [comment]
@kuitos  我在试水的demo是2.x, 我现在有这么一个场景,需要实现,一直没摸索出来.

- 就是在弹窗中灵活的加载某个子应用,可以随着弹窗生成和销毁.
- 另外一个就是多子应用同时渲染的问题(开了singular就各种报错)


![图片](https://user-images.githubusercontent.com/8272877/80278520-acc19c80-8729-11ea-877d-c73f6c008d34.gif)
