### ISSUE TITLE
[Bug]手动加载一个微应用（多实例模式下）异常

### ISSUE THREAD

**Issue by theshying** [umijs/qiankun#514]
## What happens?
当使用多实例模式手动加载一个微应用的时候出现很奇怪的异常报错，单实例模式下没有此问题
![image](https://user-images.githubusercontent.com/18634059/80295343-a290b400-87a4-11ea-956f-2c9183f2a681.png)

## 相关环境信息

- **qiankun 版本**： 2.0.5
- **浏览器版本**：chrome 81.0.4044.92
- **操作系统**：window7

**Comment by Clive-Wang** [comment]
我也是这个情况，不知道咋解决

**Comment by theshying** [comment]
已经发现问题了， 好像用webpack devserver起的站点作为子站点就存在这样的问题，因为热更新的原因， 打包完成后部署的子站点就不存在这样的问题

**Comment by Clive-Wang** [comment]
> 已经发现问题了， 好像用webpack devserver起的站点作为子站点就存在这样的问题，因为热更新的原因， 打包完成后部署的子站点就不存在这样的问题

那你打包后的静态资源跨域问题是怎么解决的

**Comment by theshying** [comment]
> > 已经发现问题了， 好像用webpack devserver起的站点作为子站点就存在这样的问题，因为热更新的原因， 打包完成后部署的子站点就不存在这样的问题
> 
> 那你打包后的静态资源跨域问题是怎么解决的

看你的部署方式呀，我用http-server这个包起的静态资源服务器，可以加参数--cors支持跨域，生产上让后端添加支持跨域的头
