### ISSUE TITLE
vue子项目部署到生产环境后，项目中抛出的异常信息定位困难

### ISSUE THREAD

**Issue by jiong0208** [umijs/qiankun#515]
## What happens?
子项目中抛出的错误信息不好定位，错误信息对应的文件全部import-html-entry库中的eval方法了

![1](https://user-images.githubusercontent.com/21174896/80297272-38800b00-87b4-11ea-92d0-f6b2a499855f.png)
![2](https://user-images.githubusercontent.com/21174896/80297283-47ff5400-87b4-11ea-8f49-5fab1e396ea9.png)
如图所示

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

相关环境信息
qiankun 版本 ： 2.0.5
浏览器版本：Google Chrome 64.0.3282.140
操作系统：win10

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/433
