### ISSUE TITLE
clearInterval 是否可以做的更加灵活

### ISSUE THREAD

**Issue by howel52** [umijs/qiankun#52]
## What happens?

我们在 Master 中有一个强依赖 interval 的业务组件，用于发送心跳；当子应用切换时， interval 会被默认清理掉。 
https://github.com/umijs/qiankun/blob/24f8858ae845211bf34fac7525d333df87a82807/src/hijackers/timer.ts#L30-L41

## 最小可复现仓库
https://github.com/howel52/qiankun/tree/bug/interval

![interval-demo.gif](https://i.loli.net/2019/08/31/PGQ4gF3Y5bRKtxl.gif)

## 复现步骤，错误日志以及相关配置
点击 demo 中的 start interval，随后切换应用，interval 会被 clear

## 相关环境信息

- **Node 版本**：v10
- **操作系统**：macOS

**Comment by howel52** [comment]
我觉得可以将「在沙箱切换期间自动清理 interval」这个东西做成可配置的；

因为 interval 这个事情从业务代码开发的角度上应该是「有始必有终」的，就好比我们写一个 react 组件，在 didMount 里新增的事件，业务应该自己在 unmount 里 remove掉，没有 remove 掉的副作用应该是业务代码自身有问题；

可以理解乾坤在沙箱层面帮助开发者自动 clear interval 这一行为，但这个「是否自动清除定时器」应该可以做成可配置化的。

或者说针对 Master 需要一个定时器的业务场景，有其他可以绕开的方案么

**Comment by kuitos** [comment]
子应用的副作用(timer)之类我觉得是应该要强制清除的，应用都卸载了还有任务在跑我觉得不科学😂

我理解你这个问题其实是因为沙箱无法正确的区分副作用来自 master 还是 slave，导致误伤了 master 的 interval 导致的，相关 issue  https://github.com/umijs/qiankun/pull/51 https://github.com/umijs/qiankun/issues/40

这几个问题周末我找个方式一并解决，思路应该是一样的

**Comment by howel52** [comment]
嗯，不过需要明确一下以下两种场景的副作用归属：

- Master 上有个 「事件监听」，事件背后的副作用由 Master 来处理；   这个时候 Slave emit 了这个事件，对于 Master 而言，Master 的副作用开始生效；那么子应用的切换会导致这个在 Master 的副作用失效么？（因为从逻辑上看，这是由 Salve 的 emit 动作触发了 Master 的副作用）

- Master 有个 function 自上而下传递给 Salves，且这个 function 背后有针对 Master 的副作用，Salves 在某个时机主动调用了这个 function； 那么子应用的切换会导致 Master 的副作用消失么？

这俩个副作用虽然由 Slave 触发，但真正的副作用是由 master 'runtime' 来负责的，那么这个时候实际上这俩副作用不应该被清理掉； 

所以我觉得这俩场景的副作用归属于 Master

**Comment by kuitos** [comment]
有道理~

我觉得现阶段需要秉持的原则是谁污染谁治理，没人治理的 qiankun 帮忙治理，但只限于 slave 在自己的 runtime 里触发的副作用。

你说的这两个场景，我理解都是 slave 调用 master 的接口，而 master 的接口实现里触发了副作用，我认为这种场景副作用清理与否需由 master 来决定，因为消费接口的人是不需要(也不应该)关心调用是否会导致副作用的。既然副作用还是 master 自己触发的，理应由他自己清理。但我们可能要提供一种机制，能让 master 清除的知道谁消费了他的 api，又该在什么时候销毁相应的副作用。

qiankun 应该自动帮助 slave 清理由 slave 主动触发的副作用，如果后面有更精细化的场景控制，可以用类似插件的机制开放一些切面，让用户能方便的往 hijacker 中织入代码，从而知道当前触发了什么副作用(比如做了 onresize)，以便自己决定要不要在 unmount 时销毁对应的 listener。

**Comment by howel52** [comment]
赞同

**Comment by shengbeiniao** [comment]
遇到同样的问题，采用redux-persist库，setInterval异步持久化

[redux-persist perlink](https://github.com/rt2zz/redux-persist/blob/d7efde9115a0bd2d6a0309ac6fb1c018bf06dc30/src/createPersistoid.js#L60)

注释后work
![image](https://user-images.githubusercontent.com/3301995/71459902-8b38be80-27e4-11ea-8064-e1d001930082.png)

**Comment by shengbeiniao** [comment]
在不破坏qiankun代码的基础上，用webpack alias解决

umi配置
```
  config.alias = {
      './hijackers': path.resolve(workspaceFolder, 'src/vendor/hijackers.js')
    }
```
hijackers.js
```
import _noop from 'lodash/noop'
import hijackDynamicHeadAppend from 'qiankun/es/hijackers/dynamicHeadAppend'
import hijackHistoryListener from 'qiankun/es/hijackers/historyListener'
import hijackPublicPath from 'qiankun/es/hijackers/publicPath'
import hijackWindowListener from 'qiankun/es/hijackers/windowListener'

// 禁用hijackTimer
export function hijackAtMounting(appName, proxy) {
  return [
    hijackWindowListener(),
    hijackHistoryListener(),
    hijackDynamicHeadAppend(appName, proxy)
  ]
}
export function hijackAtBootstrapping(appName, publicPath, proxy) {
  return [
    process.env.NODE_ENV === 'development'
      ? hijackDynamicHeadAppend(appName, proxy)
      : function() {
          return function() {
            return _noop
          }
        },
    hijackPublicPath(publicPath)
  ]
}
```

**Comment by dbkillerf6** [comment]
> 子应用的副作用(timer)之类我觉得是应该要强制清除的，应用都卸载了还有任务在跑我觉得不科学😂
> 
> 我理解你这个问题其实是因为沙箱无法正确的区分副作用来自 master 还是 slave，导致误伤了 master 的 interval 导致的，相关 issue #51 #40
> 
> 这几个问题周末我找个方式一并解决，思路应该是一样的

其实有时候由于业务需要，有一些来自 slave 的副作用是需要执行在 slave 切走之后的：

比如业务组件中的 message 设定了 3 秒自动消失，如果 qiankun 自动帮使用者清副作用，会导致提示框无法消失。

可能提供一个 switch 会好一些，让用户自行选择。我们最近也是因为这个原因，暂时关闭了 jsSandbox。

**Comment by howel52** [comment]
> 可能提供一个 switch 会好一些，让用户自行选择。我们最近也是因为这个原因，暂时关闭了 jsSandbox。

关闭 jsSandbox 代价有点高啊，我们这边走的是 esm +  webpack alias，把 hijacker 的 timer 部分 replace 掉了

**Comment by dbkillerf6** [comment]
> 关闭 jsSandbox 代价有点高啊，我们这边走的是 esm + webpack alias，把 hijacker 的 timer 部分 replace 掉了

少侠好武功，我们也安排上了，还挺好使

**Comment by kuitos** [comment]
至今还在 alias 属实惭愧啊😂
有一些新的想法，我们应该可以直接在 proxy 里做一些标记，以区分主应用跟子应用的监听。message 的问题确实更麻烦点，或许需要一个配置来让用户可以设置最大延迟清理时间，默认可以是 5s ？

**Comment by youyuyi** [comment]
之前用Jquery，layui框架做的单页面项目如何集成到乾坤框架啊？
比如一个简单的**单页面index.html，<h1>标签hello world</h1>**
虽然可以集成进去，但提示： Application 'home' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in home entry。
loading状态也不能消失。

这个单页应用的中要如何改造呢？

**Comment by xiezhongfu** [comment]
> 之前用Jquery，layui框架做的单页面项目如何集成到乾坤框架啊？
> 比如一个简单的**单页面index.html，<h1>标签hello world</h1>**
> 虽然可以集成进去，但提示： Application 'home' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in home entry。
> loading状态也不能消失。
> 
> 这个单页应用的中要如何改造呢？

这应该是 single-spa 框架在执行 load 的时候函数报错了。你这个应用生命周期函数没写好吧

**Comment by youyuyi** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>非Vue、React或NG工程化框架开发的项目</title>
	<style type="text/css">
		.info{text-align: center; padding: 50px 10px; color: #666; }
	</style>
	<script>
	if (window.__POWERED_BY_QIANKUN__) {
	    __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
	}
	let instance = null;
	export async function bootstrap ({ fns = [] } = {}) {
	    Array.isArray(fns) && fns.map(i => {
	        Vue.prototype[i.name] = i;
	    });
	}

	export async function mount ({ data = {} } = {}) {
	    instance = document;
	    /*instance = new Vue({
	        router,
	        // store,
	        render: h => h(App, { props: data })
	    }).$mount("#app");*/
	}

	export async function unmount () {
	    instance.$destroy();
	    instance = null;
	}
	window.__POWERED_BY_QIANKUN__ || mount();
	</script>
</head>
<body>
<div class="info">
	<h1>本页面如何集成如何集成进qiankun框架中</h1>
	<p>该系统页面用Jquery或Layui等框架来做的！</p>
	<p>另外，如果是原来用JQ，bootstrap，layui等开发的多页面后台系统如何集成进去？</p>
	<p>本页面集成进去，可以显示，但loading不消失，报错： Application 'home' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in home entry。</p>
</div>
</body>
</html>

**Comment by youyuyi** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>非Vue、React或NG工程化框架开发的项目</title>
	<style type="text/css">
		.info{text-align: center; padding: 50px 10px; color: #666; }
	</style>
	<script>
	if (window.__POWERED_BY_QIANKUN__) {
	    __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
	}
	let instance = null;
	export async function bootstrap ({ fns = [] } = {}) {
	    Array.isArray(fns) && fns.map(i => {
	        Vue.prototype[i.name] = i;
	    });
	}

	export async function mount ({ data = {} } = {}) {
	    instance = document;
	    /*instance = new Vue({
	        router,
	        // store,
	        render: h => h(App, { props: data })
	    }).$mount("#app");*/
	}

	export async function unmount () {
	    instance.$destroy();
	    instance = null;
	}
	window.__POWERED_BY_QIANKUN__ || mount();
	</script>
</head>
<body>
<div class="info">
	<h1>本页面如何集成如何集成进qiankun框架中</h1>
	<p>该系统页面用Jquery或Layui等框架来做的！</p>
	<p>另外，如果是原来用JQ，bootstrap，layui等开发的多页面后台系统如何集成进去？</p>
	<p>本页面集成进去，可以显示，但loading不消失，报错： Application 'home' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in home entry。</p>
</div>
</body>
</html>`

**Comment by xu8511831** [comment]
ie11下主动`clearInterval`之后，浏览器会报错`调用的对象无效`，可以改成如下：
```js
return function free() {
    intervals.forEach(function (id) {
      try{
        return global.clearInterval(id);
      }catch(err){}
    });
    global.setInterval = rawWindowInterval;
    global.clearInterval = rawWindowClearInterval;
    return _noop;
  };
```
