### ISSUE TITLE
Unhandled Rejection (Error): parcel 'child1_0' died in status NOT_MOUNTED: [qiankun] Target container with #subapp not existed while child1 mounting!

### ISSUE THREAD

**Issue by naivefun** [umijs/qiankun#522]
## What happens?
![image](https://user-images.githubusercontent.com/10683378/80311285-6182b900-8811-11ea-8d5c-92271f394ea3.png)

![image](https://user-images.githubusercontent.com/10683378/80311291-69daf400-8811-11ea-9a47-dde966c4ae37.png)

as the pics show, I cannot make it work.

- **qiankun Version**: 2.0.5
- **Platform Version**: Mac
- **Browser Version**: Chrome

**Comment by kuitos** [comment]
The error message had shown the reason.

You could check the dom in browser why #subapp not existed and who removed it.
