### ISSUE TITLE
multi react sub apps' unmountComponentAtNode throws error

### ISSUE THREAD

**Issue by naivefun** [umijs/qiankun#523]
## What happens?
![image](https://user-images.githubusercontent.com/10683378/80312197-701f9f00-8816-11ea-9274-118b077a6a36.png)

if multi subapps are react-based, the unmount/mount callback conflicts with each other, see the screenshot for details.

```js
export async function unmount() {
  ReactDOM.unmountComponentAtNode(document.getElementById("root") as any);
}
```

**Comment by kuitos** [comment]
check out the example https://github.com/umijs/qiankun/blob/5be1295e0754b311aa6bcd7ee5f71da28efaff6a/examples/react15/index.js#L32
