### ISSUE TITLE
微应用路由用的hash模式，entry地址为指定路由地址打不开？

### ISSUE THREAD

**Issue by Clive-Wang** [umijs/qiankun#525]
## What happens?

我的微应用路由用的是hash模式，手动加载微应用的时候，entry地址为 http://localhost:72/#about/，发现页面没有加载完全。

## Mini Showcase Repository(REQUIRED)

const microApp = loadMicroApp({
          name: 'app1',
          entry: 'http://localhost:72/#about/',
          container: '#app-view-box'
}, {singular:true});

![image](https://user-images.githubusercontent.com/22654766/80326528-a8050180-886b-11ea-9296-1d709fe449f9.png)
![image](https://user-images.githubusercontent.com/22654766/80326533-ad624c00-886b-11ea-91db-d71fff1cebe9.png)

确定不是div的问题导致没有显示完全，而是页面没有加载

## Context

- **qiankun Version**: 2.0.3
- **Platform Version**: win7
- **Browser Version**: Google Chrome 64.0.3282.140

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by zhangfu-git** [comment]
@Clive-Wang entry应该http://localhost:72/#/about/

**Comment by 2669115099** [comment]
> @Clive-Wang entry应该http://localhost:72/#/about/

我的entry地址是这样写的，但是还是不显示路由页面，值显示了app.vue的内容

**Comment by lizeyuan** [comment]
> > @Clive-Wang entry应该http://localhost:72/#/about/
> 
> 我的entry地址是这样写的，但是还是不显示路由页面，只显示了app.vue的内容
解决了么
