### ISSUE TITLE
VUE项目按照官网方式配置子应用但不生效

### ISSUE THREAD

**Issue by abcdlei5219593** [umijs/qiankun#527]
## VUE项目按照官网方式配置子应用但不生效

主应用的注册代码
`let app = null;
function render({ appContent, loading } = {}) {
	if (!app) {
		app = new Vue({
			el: '#container',
			router,
			store,
			data() {
				return {
					content: appContent,
					loading
				};
			},
			render(h) {
				return h(App, {
					props: {
						content: this.content,
						loading: this.loading
					}
				});
			}
		});
	} else {
		app.content = appContent;
		app.loading = loading;
	}
};

registerMicroApps([
	{
		name: 'forum',
		entry: 'https://ims-dev.xinchao.com/forum/pc/index.html', //'localhost:8081',
		render,
		activeRule: '/forum/pc',
	},
]);

start();`

在页面点击URL:https://ims-dev.xinchao.com/forum/pc/index.html 的a标签，浏览器被全局刷新了跳转到新地址，感觉框架并没有拦截到url的变化
- **qiankun Version**:2.02
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
a 标签是你自己的行为，跟 qiankun 没有关系。
qiankun 只会匹配 activeRule 里配置的规则。

**Comment by abcdlei5219593** [comment]
> a 标签是你自己的行为，跟 qiankun 没有关系。
> qiankun 只会匹配 activeRule 里配置的规则。

1、qiankun里 跳子系统不通过A标签怎么跳转？子应用和主应用URL都不同的。
2、我这项目里面A标签地址的PATH部分，在activeRule里写了的啊，不应该被匹配拦截么

**Comment by kuitos** [comment]
1. history.pushState
2. hash anchor

**Comment by abcdlei5219593** [comment]
> 1. history.pushState
> 2. hash anchor
谢谢，我试试看。  这么重要的点为什么不写在文档里呢？
