### ISSUE TITLE
子应用使用 antd icons 会抛异常

### ISSUE THREAD

**Issue by naivefun** [umijs/qiankun#528]
## What happens?
![image](https://user-images.githubusercontent.com/10683378/80342541-eebc2100-8896-11ea-890c-42aca679b5f8.png)
if the child app contains any antd icon component, the error is as above.

## Demo Repo
https://github.com/naivefun/qiankun-demo

```js
import { FastBackwardOutlined } from "@ant-design/icons";
<FastBackwardOutlined />
```
This actually affects any component that uses antd icons: sidebar, select .... this makes antd unusable as a child app?

如果子应用包含 @ant-design/icons 则会报以上的错误。另外 antd 中多个组件依赖 icon，例如 Select 的向下箭头，同样也会报一样的错误。

Demo 中可以看到。

**Comment by abcdlei5219593** [comment]
can u use chinese? cant understand

**Comment by kuitos** [comment]
Pls follow the issue template to report issue and provide the required information, or your issue will be closed.

**Comment by naivefun** [comment]
Update: `sandbox: false` 就没有这个问题。

**Comment by naivefun** [comment]
Update: 发现另外一个问题，在同样的 demo 中，`import './logo.svg;` 导入的 img url 会视图从主应用中加载 `/static/media/logo.xxxx.svg`，但实际上 logo 在子应用域名下。这个在文档中没有提及如何设置？

**Comment by naivefun** [comment]
@kuitos @abcdlei5219593  更新了 demo repo，能看看吗？多谢。

**Comment by kuitos** [comment]
使用你的 demo 无法重现报错

![image](https://user-images.githubusercontent.com/5206843/80508446-a55cf600-89aa-11ea-970e-52281d261a87.png)

**Comment by naivefun** [comment]
@kuitos  抱歉，不小心把 `sandbox: false` push 上去了，我重新改掉了，你 pull 一下试试看？
