### ISSUE TITLE
加载子应用时，加载CSS的chunkHash名字不存在。

### ISSUE THREAD

**Issue by abcdlei5219593** [umijs/qiankun#529]
在加载子应用时，通过NETWORL，发现qiankun在加载子应用 的CSS 'https://ims-dev.xinchao.com/forum/pc/static/css/chunk-3ece8ee4.ad8d7a43.css'
但服务器打包出的文件并没有这个CSS文件。
还有子项目页面发送的请求也一直卡着没有返回结果。

没过几秒浏览器会抛出一条警告：14single-spa.min.js:2 Throttling navigation to prevent the browser from hanging. See https://crbug.com/882238. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection

**Comment by kuitos** [comment]
请遵循模板提交问题，否则您的问题会被关闭

**Comment by Koomita** [comment]
pushState的url参数带了中文也会抛出这个错误

> Throttling navigation to prevent the browser from hanging. See https://crbug.com/882238. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection
