### ISSUE TITLE
主应用render如何控制，切换微应用时再刷新浏览器，主应用的render会丢失，请教如何处理

### ISSUE THREAD

**Issue by zhaoxm2016** [umijs/qiankun#530]
主应用主要是负责菜单生产，有render
ReactDOM.render(
    <LocaleProvider locale={zhCN}>
        <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
                <Routes />
            </PersistGate>
        </Provider>
    </LocaleProvider>,
    document.getElementById('root')
);

注册微应用：
registerMicroApps([
    {
        name: 'cdm', // app name registered
        entry: '//127.0.0.1:8080/cdm/',
        container: '#yourContainer',
        activeRule: '/cdm'
    },
    {
        name: 'vue app',
        entry: { scripts: ['//localhost:7100/main.js'] },
        container: '#yourContainer',
        activeRule: '/yourActiveRule2',
    },
],{
    beforeMount: [
        app => console.log('before mount', app.name),
    ],
});

/*
setDefaultMountApp('/uoa');
*/

start();

runAfterFirstMounted(() => {
    console.log('[MainApp] first app mounted');
});

**Comment by kuitos** [comment]
请遵循模板提交问题，否则您的问题会被关闭
