### ISSUE TITLE
严格模式，react会出现事件以及导航失效的问题

### ISSUE THREAD

**Issue by simoncx** [umijs/qiankun#531]
## Background
手动加载多个子应用到同一个页面，采用严格样式隔离，会导致一下框架如Vue，React，在做dialog或者向body中创建div的操作时样式失效、事件失效。

## Proposal
是否有模拟样式隔离的方案，否则接入微应用后采用严格样式隔离，会出现一些奇怪的问题，比如内部的js操作document等等。

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/80482625-1be7fc80-8987-11ea-9c32-90f523f13749.png)

see https://qiankun.umijs.org/zh/api/#loadmicroapp-app-configuration

微应用适配 shadow dom 的问题需要自己处理
