### ISSUE TITLE
再次返回子应用总是回到离开之前的子应用的路由，但我想跳转到这个子应用的其他路由

### ISSUE THREAD

**Issue by zhangfu-git** [umijs/qiankun#532]
## What happens?
子应用B下有两个路由/list和/create, /默认重定到/list, 先访问了子应用B的/create后，通过主应用路由跳转到子应用A， 然后在子应用A拿到参数后跳转到子应用B的/list，但被重定向到/create

看起来被KeepAliveRoute， 但子应用没有设置这个值，如果进行子应用和子应用的跳转？

## Mini Showcase Repository(REQUIRED)
子应用路由方式: hash

## Context

- **qiankun Version**:  "^1.4.5"
- **Platform Version**: mac
- **Browser Version**: chrome

**Comment by kuitos** [comment]
子应用 B 的 history 卸载的时候没有清理吧。

提供可复现仓库，不然无法帮助到你。

**Comment by zhangfu-git** [comment]
这个是手动协作还是自动协作的？

**Comment by zhangfu-git** [comment]
https://github.com/zhangfu-git/qiankun_demo
这个是复现的demo

**Comment by CareyToboo** [comment]
@zhangfu-git 这个问题有解决吗？目前也是，子应用间路由切换时，只能跳转到 上个应用之前停留的页面，不能正常进入设定的页面。

**Comment by lu2294** [comment]
> @zhangfu-git 这个问题有解决吗？目前也是，子应用间路由切换时，只能跳转到 上个应用之前停留的页面，不能正常进入设定的页面。

老哥，这个问题解决了么？

**Comment by BryanYbj** [comment]
@zhangfu-git 老哥这个问题咋解决的

**Comment by zhangfu-git** [comment]
@San-Shui 2年前遇到这个问题，时间有点久了忘记具体怎么解决的，好像是升级了qiankun的版本解决的，试试    "qiankun": "^2.0.15"，你试试
