### ISSUE TITLE
子应用单独运行图片可以正常显示，在主应用里无法正常显示

### ISSUE THREAD

**Issue by zhaoxm2016** [umijs/qiankun#535]
非base64处理的图片，直接打包在项目里

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F

**Comment by zhaoxm2016** [comment]
@kuitos 
http://127.0.0.1:8080/lib/flexible.js  这个是子应用的js，都可以正常加载，webpack配置了跨域
子应用里的图片是在代码里import使用的
但是子应用在主应用里运行的话，它是去主应用下找这个图片了、
http://127.0.0.1:8989/static/media/nodata.a0370800.png
8989端口是主应用，8080端口是子应用，这个图片是子应用的图片

**Comment by zhaoxm2016** [comment]
@kuitos 
![32782A79-ADE2-4485-BB0A-6848391F9941](https://user-images.githubusercontent.com/51771541/80559442-171b5b00-8a10-11ea-9c47-c7616e56105e.png)

同样的在一个子项目里，同一个组件，两张图片，在组件内import 引入，一个可以正常显示，一个不可以正常显示，不能正常显示都是在主应用下找图片了

**Comment by kuitos** [comment]
1. 能正常显示的是因为图片被 base64 了，没有了 uri 寻址过程，可以看这里了解详细原理 https://webpack.js.org/loaders/file-loader/
2. 看这里 https://qiankun.umijs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F
3. 配置了 publicPath 没用我猜是因为你是直接通过 img 标签引入的，如 `<img src="/abc.png">`，因为这部分没有被 webpack 处理所以 publicPath 没有生效，这个需要你自己处理。

如果还有问题可以 reopen issue 并提供可复现仓库。

**Comment by zhaoxm2016** [comment]
@kuitos 确实是你说的第三种情况，这个处理有什么方案建议吗？感谢

**Comment by zhaoxm2016** [comment]
全部转换成base64都没问题

**Comment by zhaoxm2016** [comment]
![50A834DE-AF0B-4A90-A015-2B6001F40927](https://user-images.githubusercontent.com/51771541/80566353-5d2ee980-8a25-11ea-849b-d24e51de32ed.png)
![41113162-FCED-4E70-B15C-821698AEE22D](https://user-images.githubusercontent.com/51771541/80566372-6d46c900-8a25-11ea-8e60-a0bb170ffe89.png)
这是loader的处理
@kuitos

**Comment by zhaoxm2016** [comment]
webpack应该处理过了，但是官网提供的方案好像不起作用
@kuitos

**Comment by zhaoxm2016** [comment]
解决了

**Comment by OPfewnojnolfew** [comment]
@zhaoxm2016 麻烦问下，这个问题最后是怎么解决的？

**Comment by chshsh** [comment]
@zhaoxm2016 请问解决方法

**Comment by wjingxian2008** [comment]
> 1. 能正常显示的是因为图片被 base64 了，没有了 uri 寻址过程，可以看这里了解详细原理 https://webpack.js.org/loaders/file-loader/
> 2. 看这里 https://qiankun.umijs.org/zh/faq/#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F
> 3. 配置了 publicPath 没用我猜是因为你是直接通过 img 标签引入的，如 `<img src="/abc.png">`，因为这部分没有被 webpack 处理所以 publicPath 没有生效，这个需要你自己处理。
> 
> 如果还有问题可以 reopen issue 并提供可复现仓库。

额，需要自己处理。。。 @kuitos

**Comment by BryanYbj** [comment]
@zhaoxm2016 请问解决方法
