### ISSUE TITLE
建议是否可以直接新增获取全局state的API

### ISSUE THREAD

**Issue by zhaoxm2016** [umijs/qiankun#539]
个人理解onGlobalStateChange这个方法是在全局state变化的时候可以控制组件或者子应用重新渲染，如果提供一个全局获取的方法，这样可以省去一些注入过程？

或者作者未提供这个API的考虑在什么地方？

**Comment by zhaoxm2016** [comment]
如果在主应用初始化一个全局state,子应用只需要获取值，并在组件中使用的话，感觉操作不是很方便

**Comment by kuitos** [comment]
> 如果在主应用初始化一个全局state,子应用只需要获取值，并在组件中使用的话，感觉操作不是很方便

这种场景就直接传自己的数据就好了，用不到 onGlobalStateChange 这些 api。

onGlobalStateChange 是针对有响应式诉求的场景的。

**Comment by zhaoxm2016** [comment]
@kuitos 
嗯理解，微应用拆分过程中确实不应该存在过多的数据依赖，但是在实际线上情况往往会出现在子应用切换的时候需要兼容一些数据处理（复杂对象），可以借用乾坤的通讯机制做一个中转，这样大家在实操过程中可能会更加方便

**Comment by zhaoxm2016** [comment]
如果想看全局state的话，除了在监听里面能看到，还能通过别的途径查看吗
@kuitos

**Comment by kuitos** [comment]
没有~
