### ISSUE TITLE
子应用图片显示问题

### ISSUE THREAD

**Issue by zhaoxm2016** [umijs/qiankun#540]
子应用在主应用里部分图片可以展示，部分图片展示不出来

qiankun:2.0.8

**Comment by zhaoxm2016** [comment]
https://github.com/umijs/qiankun/issues/535

**Comment by zhaoxm2016** [comment]
@kuitos

**Comment by kuitos** [comment]
不要重复开 issue，有问题可以 reopen 之前的 issue
