### ISSUE TITLE
import-html-entry升级至1.7.10 后eval inlineScript会出错

### ISSUE THREAD

**Issue by justJokee** [umijs/qiankun#541]
## What happens?

子应用的html中写几段inlineScript，不压缩被eval执行后，关于sourceURL的注释出错，相关详情已在import-html-entry仓库中提交pr

## Mini Showcase Repository(REQUIRED)

无

## How To Reproduce

于子应用的html中写任何未经压缩的多行inlineScript

## Context

- **qiankun Version 2.0.9**:
- **Platform Version win10**:
- **Browser Version all**:

**Comment by kuitos** [comment]
resolved by https://github.com/kuitos/import-html-entry/commit/ca70017e603b63615ddfd6cc009c7a6d6c712543
