### ISSUE TITLE
[Feature Request] 默认启动希望可以拓展下配置方式,变得灵活一些

### ISSUE THREAD

**Issue by crper** [umijs/qiankun#542]
### 当前设置默认的启动子应用用的是`setDefaultMountApp`这个函数

那可以在保留这个的基础上,在注册的时候,以参数的形式来开启,
若是有多个设置了,默认则取最后一个,写法如下

```javascript
  route:[
  	{
      name: "app-modules-list",
      entry: "//localhost:2222",
      container: "#mounted-content__content",
      activeRule: "/app-modules-list",
      default:true , // 入口 appEntry,unset use '',boolean on off
    },
  ], // registerMicroApps

```

`setDefaultMountApp`其实还能再做的更弹性一点,设置子应用的`name`也支持!
我看当前只支持子应用的链接,这里面做多一层判断就能实现了.

当前欠缺的这些需求,我是准备自己封装,qiankun可以考虑是否直接支持方便用这个框架的人使用

**Comment by kuitos** [comment]
app 上再加个 default 的方式感觉不太好，现在配置已经很多了，再加配置会有多的成本出来（比如还要考虑多个 app 都设置了 default：true）

设置 name 也支持这个可以考虑，但是有一个问题，比如 name 为 a 的应用 activeRule 配置是 `/user/:id` 这种，那么 setDefaultMountApp('a') 应该跳转到哪里？

感觉 `setDefaultMountApp` 应该 rename 成 `setDefaultMountLink` 会更合适🤔

**Comment by crper** [comment]
@kuitos `setDefaultMountApp`这样设计可行否?

- 直接链接: `setDefaultMountLink`,
- 直接名字: `setDefaultMountAppName`
- 综合型:

```typescript
setDefaultMountApp:{name?:string;url?:string;}
```

上面两种就是派生方法,继承`setDefaultMountApp`导出具体部分实现..

**Comment by kuitos** [comment]
> 比如 name 为 a 的应用 activeRule 配置是 /user/:id 这种，那么 setDefaultMountApp('a') 应该跳转到哪里？

这个问题怎么解决？

**Comment by crper** [comment]
我没看错的话,qiankun现在还不支持动态路由声明吧..

我觉得第一版的话,可以就是强制要求,
若是是以`name`作为跳转,`activeRule`必须是可以访问的绝对路径.

若是要支持动态路由,在`url`变化的时候,
那至少得自己实现一个`url`适配器解析成目前的`activeRule`的效果,

这是我的一点看法,可行性还得摸索

**Comment by kuitos** [comment]
> 我没看错的话,qiankun现在还不支持动态路由声明吧..

支持的 https://qiankun.umijs.org/zh/api/#registermicroapps-apps-lifecycles

**Comment by crper** [comment]
我说的`name`跳转...你可以觉得是一个别名的作用..

就是当前配置的基础信息都是需要都具备的..

跳转`name`-> 匹配对应传入信息的{name,`activeRule},只是`match`的作用..

并不影响当前的`activeRule`的逻辑..

为什么有这个需求,因为有时候名字更具有语义化,代码可读性会好些.

**Comment by kuitos** [comment]
啥意思没看懂。
`setDefaultMountApp` 里既传 `name` 又传 `url`？

**Comment by crper** [comment]
和上面强调的别名的作用一个道理的...

就是传`name`就拿`name`去匹配对应的项
若是传`url`就是当前的`activeRule`中的链接概念,
若是两个都传,就是完全匹配,不仅校验名字且校验链接.
若是匹配不到,就相当于执行了`setDefaultMountApp('')`
