### ISSUE TITLE
测试 material ui 加载不符合沙箱隔离的预期...

### ISSUE THREAD

**Issue by X-neuron** [umijs/qiankun#543]
## What happens?

   测试material ui 出错，复杂的场景。
<img src="https://i.loli.net/2020/04/29/vuXlOAqxM5kTsZ3.gif" >

## How To Reproduce

https://github.com/X-neuron/material-test
git clone 
npm run build
部署个测试下即可

**Comment by X-neuron** [comment]
webpack里output 配完publicPath 也不行...

**Comment by Buggersldx** [comment]
= = 我也出现了和你类似的问题，先跑子程序，然后再跑主程序的功能，主程序的样式没有加载，导致页面变形

**Comment by X-neuron** [comment]
> = = 我也出现了和你类似的问题，先跑子程序，然后再跑主程序的功能，主程序的样式没有加载，导致页面变形

可能样式隔离不彻底~~还有些配置他们没考虑到~

**Comment by mengyouhan** [comment]
> 先跑子程序，然后再跑主程序的功能，主程序的样式没有加载，导致页面变形
对我也是这样，strictStyleIsolation设置为true也会这样

**Comment by yunliang-ding** [comment]
样式隔离确实有点问题，而且子应用之间的iconfont图标也冲突了。
