### ISSUE TITLE
[RFC] 使用手动加载的方式，切换react子应用时，样式丢失

### ISSUE THREAD

**Issue by taoyan-t** [umijs/qiankun#546]
## What happens?

使用手动加载的方式，子应用为纯页面，React，Vue时，只有切换React项目时样式会丢失

## Mini Showcase Repository(REQUIRED)

> 可复现仓库地址：https://github.com/taoyan-t/Test.git

## How To Reproduce

**切换react项目时样式丢失

**样式正常显示

**Comment by kuitos** [comment]
CRA 应用需要声明下这个配置 https://github.com/umijs/qiankun/blob/cb65f91bd94f4ead10c0a50ae466738d4d041cb3/examples/react16/.rescriptsrc.js#L8
