### ISSUE TITLE
[Bug]IE 11下，如果按路由切换子app时，新路由下设置在window的变量可能都失效。

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#547]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
在IE 11下，切换子app，如果新的app里面初始化异步设置了一些变量在window下面，页面打开时可能取不到。

## 相关环境信息

- **qiankun 版本**
2.0.5
- **浏览器版本**：
IE 11
- **操作系统**：
Windows 10

初步怀疑，snapshotSandbox.ts里面inactive会恢复之前的window的所有变量，会把新设置在window下面的覆盖掉。

所以请帮忙分析inactive是在什么时机触发的。

**Comment by waltbest2** [comment]
iter(window, prop => {
      if (window[prop] !== this.windowSnapshot[prop]) {
        // 记录变更，恢复环境
        this.modifyPropsMap[prop] = window[prop];
        window[prop] = this.windowSnapshot[prop];
      }
    });


你这里是不是应该遍历windowSnapshot，而不是直接遍历window？

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by waltbest2** [comment]
项目背景是这样的，我们当前全部是由angularjs实现的，想逐步切angular9，所以大部分的 页面和路由还是angularjs和ui-router。
当从angular的app切回到angularjs的老路由的时候，老路由里面的逻辑是可能会向window下面写一些变量，但是在写入后，又执行了inactive，这时候快照proxy认为这些window下变量是app的，所以被抹掉了。

现在如果老路由不执行，没办法执行unmount。所以尝试在unmount后，通知angularjs处理，这个不太可行。

现在我是在想，有没有办法通过window全局变量拿到被抹掉的那些window下面的值？我在afterunmount的时候重新再写入一下。
有没有办法拿到 this.modifyPropsMap[prop]

**Comment by lance-li** [comment]
请问你的项目在IE11 下 是否显示子应用 页面？
我的主应用main.js如下：
`
/*import 'core-js/stable/promise';
import 'core-js/stable/symbol';
import 'core-js/stable/string/starts-with';
import 'core-js/web/url';*/

import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import { Message } from "element-ui";
import {
  registerMicroApps,
  setDefaultMountApp,
  runAfterFirstMounted,
  start,
  addGlobalUncaughtErrorHandler,
  // initGlobalState, // 官方应用间通信
} from "qiankun";
import apiDataFilter from "./utils/apiDataFilter";
import mfeList from './mfe'
import {fetch as fetchPolyfill} from 'whatwg-fetch'
Vue.config.productionTip = false


let app = null;

/*渲染方式*/
function render({ appContent, loading } = {}) {
  if (!app) {
    app = new Vue({
      el: "#container",
      router,
      store,
      data() {
        return {
          content: appContent,
          loading
        };
      },
      render(h) {
        return h(App, {
          props: {
            content: this.content,
            loading: this.loading
          }
        });
      }
    });
  } else {
    app.content = appContent;
    app.loading = loading;
  }
}

render({loading: true });

function genActiveRule(routerPrefix) {
  return location => location.pathname.startsWith(routerPrefix);
}

/*注册子模块*/
function registerMicro(list) {
  let msg = {

  }
  if (list.length === 0) {
    Message({
      type: 'error',
      message: "没有可以注册的子应用数据"
    })
    return;
  }
  // 处理子应用注册数据
  let apps = [];
  let defaultApp = null;
  list.forEach(item => {
    apps.push({
      name: item.moduleName,
      entry: item.entry,
      //render,
     container:'#subAppLayout',
      activeRule: genActiveRule(item.routerBase),
      props: { ...msg, ROUTES: item.children, routerBase: item.routerBase }
    })
    if (item.defaultRegister) defaultApp = item.routerBase;
  });
  // 注册子应用
  registerMicroApps(apps, {
    beforeLoad: [
      app => {
        console.log("before load", app);
      }
    ],
    beforeMount: [
      app => {
        console.log("before mount", app);
      }
    ],
    afterUnmount: [
      app => {
        console.log("after unload", app);
      }
    ]
  });

  if (!defaultApp) defaultApp = list[0].routerBase;

  setDefaultMountApp(defaultApp);

  runAfterFirstMounted((app) => {
    console.log(app,'runAfterFirstMounted')
  });

  start({ prefetch: true ,sandbox:{strictStyleIsolation: true},fetch(url,...args){
       return fetchPolyfill(url,...args)
    }});

  addGlobalUncaughtErrorHandler(event => console.log('--------',event));
}

const isProd = process.env.NODE_ENV === 'production';

let list = mfeList;
if (isProd){
  apiDataFilter.request({}).then((res)=>{
    let result = res.data;
    registerMicro(result)
  })
}else {
  try {
    console.log('registerMicro')
    registerMicro(list)
  }catch (e) {
    console.log('e---------',e)
  }
}

/*new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')*/
`

子应用main.js如下：
`import Vue from 'vue'
import VueRouter from 'vue-router'
import App from './App.vue'
import routes from './router'
import store from './store'
import "./public-path";

Vue.config.productionTip = false
console.log('--------------------------------------')

let router = null;
let instance = null;
const isMFE = process.env.NODE_ENV === 'mfe';
const __qiankun__ = window.__POWERED_BY_QIANKUN__;


export async function bootstrap({components, utils, emitFnc, pager, actions }) {

  // 注册主应用下发的组件
/*  Vue.use(components);
  // 把工具函数挂载在vue $mainUtils对象
  Vue.prototype.$mainUtils = utils;
  // 把mainEmit函数一一挂载
  Object.keys(emitFnc).forEach(i => {
    Vue.prototype[i] = emitFnc[i]
  });
  // 在子应用注册呼机
  pager.subscribe(v => {
    console.log(`监听到子应用${v.from}发来消息：`, v)
    // store.dispatch('app/setToken', v.token)
  })
  Vue.prototype.$pager = pager;
  // 在子应用注册官方通信
  /!* actions.onGlobalStateChange((state, prev) => console.log(`子应用subapp-ui监听到来自${state.from}发来消息：`, state, prev)); *!/
  Vue.prototype.$actions = actions;*/
}

export async function mount({ data = {}, ROUTES, routerBase, state,container } = {}) {
  router = new VueRouter({
    base: __qiankun__ ? routerBase : "/",
    mode: "history",
    routes: isMFE && __qiankun__ ? routes : routes
  });
  instance = new Vue({
    router,
    store,
    render: h => h(App, {
      props: {...data, ...state }
    })
  }).$mount(container ? container.querySelector('#app') : '#app');
}

export async function unmount() {
  instance.$destroy();
  instance = null;
  router = null;
}

// 单独开发环境
__qiankun__ || mount();
`
主应用 config如下：
`/* eslint-disable no-shadow */
const path = require('path');
const fs = require('fs');
const HtmlWebpackTagsPlugin = require('html-webpack-tags-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;


function resolve(dir) {
  return path.join(__dirname, dir);
}

/**
 * 获取代理库地址
 * @param {String} dir 目录地址
 */
function getPortalLibs(dir = './public/libs') {
  const cssFiles = [];
  const jsFiles = [];
  const jsReg = /\.js$/;
  const cssReg = /\.css$/;
  const basePath = '/libs/';

  try {
    const files = fs.readdirSync(dir); 
    const vueLibs = [];
    const thdLibs = [];

    files.map((file) => {
      if (jsReg.test(file)) {
        jsFiles.push(basePath + file);
      } else if (cssReg.test(file)) {
        cssFiles.push(basePath + file);
      }
      return file;
    });

    // 分离出vue核心库和第三方库
    jsFiles.map((lib) => {
      if (lib.startsWith(`${basePath}vue`)) {
        // vue核心最先加载
        if (lib.split('@')[0] === `${basePath}vue`) {
          vueLibs.unshift(lib);
        } else {
          vueLibs.push(lib);
        }
      } else {
        thdLibs.push(lib);
      }
      return true;
    });

    console.log(vueLibs.join(','))

    return {
      cssFiles,
      jsFiles: [...vueLibs, ...thdLibs] // 优先加载vue核心库
    }
  } catch (error) {
    throw new Error(error);
  }
}

const libs = getPortalLibs();

const scriptPreloadAttr = {
  rel: 'preload',
  as: 'script'
}
const scriptAttr = {
  type: 'text/javascript'
}

const links = [
  '/libs/font-awesome-4.7.0/css/font-awesome.min.css',
  ...libs.cssFiles,
  ...(libs.jsFiles.map(path => ({
    path,
    publicPath: false,
    attributes: scriptPreloadAttr
  })))
];

const scripts = [
  ...(libs.jsFiles.map(path => ({
    path,
    publicPath: false,
    append: false, // 添加到已有脚本前面————代理库需要先加载
    attributes: scriptAttr
  })))
];

const port = 8081;

module.exports = {
  lintOnSave: false,
  devServer: {
    host:'0.0.0.0',
    hot: false,
    port,
    disableHostCheck: true,
    overlay: {
      warnings: false,
      errors: true,
    },
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    proxy: {
      '/backend': {
        target: 'http://10.128.0.180:8002/backend', // 你接口的域名  //测试环境：47.99.190.39:8002 //开发环境：121.196.221.253:8002//vpc测试环境: 120.24.230.253//120.76.143.89深圳的测试环境
        changeOrigin: true,
        ws: true
      }
    }
  },
  configureWebpack:{
     entry:["babel-polyfill","whatwg-fetch","./src/main.js"],
  }
}
`
子应用config如下：
`const path = require('path');
const { name } = require('./package');

function resolve(dir) {
  return path.join(__dirname, dir);
}

const port = 8091; // dev port
module.exports = {
  /**
   * You will need to set publicPath if you plan to deploy your site under a sub path,
   * for example GitHub Pages. If you plan to deploy your site to https://foo.github.io/bar/,
   * then publicPath should be set to "/bar/".
   * In most cases please use '/' !!!
   * Detail: https://cli.vuejs.org/config/#publicpath
   */
  //publicPath: dev ? `//localhost:${port}` : '/',
  lintOnSave: false,
  outputDir: 'dist',
  assetsDir: 'static',
  filenameHashing: true,
  // tweak internal webpack configuration.
  // see https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md
  devServer: {
    hot: true,
    disableHostCheck: true,
    port,
    overlay: {
      warnings: false,
      errors: true,
    },
    headers: {
      'Access-Control-Allow-Origin': '*',
    }
  },
  // 自定义webpack配置
  configureWebpack: {
   // entry:["whatwg-fetch","./src/main.js"],
    resolve: {
      alias: {
        '@': resolve('src'),
      },
    },
    output: {
      // 把子应用打包成 umd 库格式
      library: `${name}-[name]`,
      libraryTarget:'umd',
      jsonpFunction: `webpackJsonp_${name}`,
    },
  },
};
`

**Comment by WLyKan** [comment]
> 项目背景是这样的，我们当前全部是由angularjs实现的，想逐步切angular9，所以大部分的 页面和路由还是angularjs和ui-router。
> 当从angular的app切回到angularjs的老路由的时候，老路由里面的逻辑是可能会向window下面写一些变量，但是在写入后，又执行了inactive，这时候快照proxy认为这些window下变量是app的，所以被抹掉了。
> 
> 现在如果老路由不执行，没办法执行unmount。所以尝试在unmount后，通知angularjs处理，这个不太可行。
> 
> 现在我是在想，有没有办法通过window全局变量拿到被抹掉的那些window下面的值？我在afterunmount的时候重新再写入一下。
> 有没有办法拿到 this.modifyPropsMap[prop]

为什么不考虑迁移angularjs 到 angular呢，我看官方文档有共存的支持，是不是有什么坑呀？
