### ISSUE TITLE
[Feature Request] html-entry 解析是否可以提供一些扩展的能力

### ISSUE THREAD

**Issue by kjl-tech-blog** [umijs/qiankun#548]
## Background

一些情况下，我们需要针对解析出来的 scripts 等做一些黑名单过滤逻辑，或者是自定义 entry 文件的解析。目前采取的方式是 fork 了一份 import-html-entry 然后在 webpack 中设置 alias 实现的。希望有更合理的方式来实现 html 解析能力的扩展。

**Comment by kuitos** [comment]
start 配置里有一个 getTemplate 配置，可以自定义模板处理函数
https://qiankun.umijs.org/zh/api/#start-opts

![image](https://user-images.githubusercontent.com/5206843/80782742-f7b83580-8ba9-11ea-98fe-932e2a5003ab.png)

https://qiankun.umijs.org/zh/faq/#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-gettemplate-%E6%96%B9%E6%B3%95

**Comment by kjl-tech-blog** [comment]
好的。
