### ISSUE TITLE
获取子应用报错：application 'vueapp' died in status LOADING_SOURCE_CODE: Cannot read property 'then' of undefined     at importHTML (index.js?50b2:198)

### ISSUE THREAD

**Issue by hello-lun** [umijs/qiankun#549]
### 获取子应用报以下错误：
![image](https://user-images.githubusercontent.com/34638158/80821702-d425d700-8c0b-11ea-94a5-8f775958d712.png)
 这是什么回事呢

**Comment by nabaonan** [comment]
我今天爆了类似的错误，经过我排查是entry没有设置，你也可以看看是不是entry没有设置呢

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by zhangfu-git** [comment]
@hello-lun  升级到2.0 遇到相同的问题，请问解决了吗？

**Comment by zhangfu-git** [comment]
@hello-lun 我合这边使用start添加了fetch配置，但没有return fetch 导致
