### ISSUE TITLE
Unexpected keys "@@dva"

### ISSUE THREAD

**Issue by eevin** [umijs/qiankun#550]
主子应用都使用umi 3 框架
子应用切换回主应用异常信息：
devScripts.js:5035 Unexpected keys "@@dva", "global" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "login", "activities", "project", "businessRelease", "hello", "sysMenu", "sysRole", "sysStatic", "sysUrl", "sysUser", "loading". Unexpected keys will be ignored. 
    in Context.Provider

qiankun插件："@umijs/plugin-qiankun": "^2.1.1",

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by Shijiuwei** [comment]
@eevin 我也遇到这样的问题，请问你是这么解决这个问题的

**Comment by 942368681** [comment]
@eevin 同样问题  解决了吗？

**Comment by gogoinga** [comment]
有解决了吗？同问

**Comment by buquan** [comment]
+1
