### ISSUE TITLE
[Bug]带有react portal的组件 挂载时出错

### ISSUE THREAD

**Issue by caianfa** [umijs/qiankun#554]
## What happens?
带有react portal的组件 会render的时候会报出如下错误:
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

例如 Modal DatePicker Notification等组件

antd版本： 4.2.0
qiankun   2.0.11
## 最小可复现仓库
当前仓库

## 复现步骤，错误日志以及相关配置
当前仓库下的example下 react16目录 将antd版本改为最新版本

## 相关环境信息

- **qiankun 版本**  2.0.11
- **浏览器版本**：
- **操作系统**：

**Comment by weekitmo** [comment]
遇到一样的问题，我的情况是子项目在html上引入自己用webpack打包的库，会报这个错
