### ISSUE TITLE
开发环境运行正常，部署至nginx上出错

### ISSUE THREAD

**Issue by zhaoxm2016** [umijs/qiankun#555]
<img width="723" alt="1" src="https://user-images.githubusercontent.com/51771541/81176781-3ac63e80-8fd8-11ea-999e-60965ddf7336.png">

大家帮忙分析下问题可能出错在哪呢

**Comment by zhaoxm2016** [comment]
![DINGTALK_IM_2597912298](https://user-images.githubusercontent.com/51771541/81246795-122b5c80-904b-11ea-939c-986984dafe42.JPG)

**Comment by zhaoxm2016** [comment]
按照这个做了检查，1、2、3都没有问题。
第4项，标签是用HtmlwebpackPlugin插件动态插入的。
@kuitos

**Comment by zhaoxm2016** [comment]
![7E1434EC-02CC-440C-A66A-3EE70592CCB4](https://user-images.githubusercontent.com/51771541/81247491-b6fa6980-904c-11ea-968f-d4b7eb10af55.png)

**Comment by zhaoxm2016** [comment]
![3C32D72C-94FD-4B6C-A5B7-552FBF3506D4](https://user-images.githubusercontent.com/51771541/81249242-c976a200-9050-11ea-8fd9-12502b87fb3b.png)
应该是在import-html-entry过程中出错了吧？

**Comment by zhaoxm2016** [comment]
@kuitos 官方大大是否帮忙分析下原因，指点一下

**Comment by zhaoxm2016** [comment]
![C01EFABE-8C1C-483A-823B-FE6D27010234](https://user-images.githubusercontent.com/51771541/81260743-313ae600-906d-11ea-9b89-4efd4e343af1.png)
这是打开sourceMap之后的报错

**Comment by zhaoxm2016** [comment]
@kuitos 可以指点一下吗

**Comment by kuitos** [comment]
子应用加载过程中自己报错了，错误栈指向的 baseIsAruguments 方法，自己 debug 看下
