### ISSUE TITLE
父应用怎么合理处理子应用的接口代理

### ISSUE THREAD

**Issue by jiang263** [umijs/qiankun#557]
比如子应用的有个接口代理如下:
  proxy: {
     ‘/apis’: {
        target: `http://127.0.0.1:3333`,
        changeOrigin: true,
        pathRewrite: {
         '^/apis': ''
        }
      }
父应用怎么处理子应用的代理呢？，再代理一遍？

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/315#issuecomment-625680040
