### ISSUE TITLE
预加载为什么不利用浏览器自身缓存，直接请求一次不使用，而是这样styleCache = {}缓存，不会导致内存被不断占用嘛

### ISSUE THREAD

**Issue by yozojo** [umijs/qiankun#562]
预加载为什么不走利用浏览器自身的缓存功能，直接请求一次不使用，而是这样styleCache = {}缓存，不会导致内存被不断占用嘛，而且浏览器自身的缓存能力应该会被自己声明的临时变量性能更好吧，也不会跟js线程抢资源

**Comment by kuitos** [comment]
1. 静态资源开启 http 强缓存并不是每个应用都能做到的
2. chrome 对 js 引擎的内存限制在 512mb 以上，基本不用担心静态资源缓存占用的问题，如果出现了加个 lrucache 就行了
3. io 不会跟 js 线程抢资源
