### ISSUE TITLE
IE11 对象不支持此操作

### ISSUE THREAD

**Issue by lance-li** [umijs/qiankun#565]
## What happens?

![image](https://user-images.githubusercontent.com/21050392/81658838-b8bc9680-946b-11ea-98e9-dca80c6c3dee.png)

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by lance-li** [comment]
仓库地址如下：
https://github.com/lance-li/single-test.git

**Comment by lance-li** [comment]
![4291589380876_ pic](https://user-images.githubusercontent.com/21050392/81826976-e63c3980-956a-11ea-91b9-8c31773d9d5b.jpg)

**Comment by gongshun** [comment]
我在IE11上也报错了，并且我已经为`qiankun`和`single-spa`配置了`babel`转码:

![image](https://user-images.githubusercontent.com/29347231/82303431-82dc5c80-99ed-11ea-9671-b8b878ed0a2c.png)

报错如下：

![image](https://user-images.githubusercontent.com/29347231/82303371-735d1380-99ed-11ea-9239-a614226a4be6.png)

代码仓库：https://github.com/gongshun/qiankun-vue-demo

**Comment by kuitos** [comment]
@Deturium 看下

**Comment by mollion** [comment]
//vue.config.js 配置 @gongshun
transpileDependencies: [
    'import-html-entry'
  ]

**Comment by gongshun** [comment]
@mollion 我试了下，还是不行，仍然是报错。
transpileDependencies: ['single-spa','qiankun','import-html-entry']

**Comment by lance-li** [comment]
@kuitos  这个问题 @Deturium 一直没时间看吗？

**Comment by ycr6708536** [comment]
ie 11 的 MouseEvent 是 object，需要引入polyfill
https://developer.mozilla.org/zh-CN/docs/Web/API/MouseEvent/MouseEvent

**Comment by lance-li** [comment]
@ycr6708536 并没有解决问题啊 ！

**Comment by gongshun** [comment]
@lance-li 引入他说的 `polyfill`，项目就可以跑起来了，只不过加载子项目还是有报错，这是`single-spa`的兼容性问题，而不是`qiankun`

**Comment by cshsh** [comment]
SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。

![image](https://user-images.githubusercontent.com/12389638/85085850-a58bac00-b20b-11ea-96c0-f3c33552d824.png)

**Comment by rogerIF** [comment]
@cshsh 这个是ajax错误，只会在部分IE版本出现，处理方法可以参考<https://www.jianshu.com/p/10f20e7005fd>

**Comment by justJokee** [comment]
我也遇到了这个问题，请问有人知道怎么解么

**Comment by benbenkoulan** [comment]
@lance-li 
SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。
请问这个问题有解决吗
