### ISSUE TITLE
vue store 传递

### ISSUE THREAD

**Issue by gudepeng** [umijs/qiankun#566]
今天突发奇想了个传递方式。
我主项目和子项目都是vue
我在主项目中编写store。然后在主项目new vue的时候传递进去，然后也把store传递到子项目中。在子项目new vue的时候把store传递进去。子项目内直接操作store修改，主项目获取到的store的值一样，但是子项目页面不会变化，需要自己写$forceUpdate()。主项目的store修改，子项目其实也是能取到的，但是页面不会刷新，一样要自己写$forceUpdate()

**Comment by zhxx** [comment]
朋友，你这样父子项目耦合度太高了，不建议这样做。

**Comment by howel52** [comment]
see: https://qiankun.umijs.org/api/#initgloabalstate-state

**Comment by gongshun** [comment]
我实现了你这个需求：https://github.com/gongshun/qiankun-vue-demo

**Comment by gudepeng** [comment]
> 朋友，你这样父子项目耦合度太高了，不建议这样做。

嗯，这个懂。也是突发奇想。以为现在在实际开发中碰到一个问题，就比如说store。每个子项目都有共同的stroe。但是现在共同的store我需要告诉每个子项目团队去修改。感觉很费劲，所以在想可不可以通过主项目传递过去，这样，有什么变动的时候只需要主项目去改下就可以了。

**Comment by gudepeng** [comment]
> see: https://qiankun.umijs.org/api/#initgloabalstate-state

感觉回答，但是你这不是我发问的内容。我目前线上的项目就是在初始化子项目的时候把store.getter传递过去，然后主项目需要变动子项目数据的时候调用initgloabalstate

**Comment by gudepeng** [comment]
> 我实现了你这个需求：https://github.com/gongshun/qiankun-vue-demo

感谢回答。但是我看了下你的代码不是我说的这种情况，你这还是主项目和子项目单独引用store

**Comment by dbkillerf6** [comment]
我觉得主应用下发的能力还是最好框架无关，针对这个需求，感觉可以：

1、 主应用利用 module cache 创建 state 并暴露 `get`、`dispatch`、`subscribe` 和 `unsubscribe`：
```ts
const state: Record<string, any> = {};

const deps: Record<string, Record<string, any>> = {};

const counter: Record<string, number> = {};

export function get(key: string) {
  return state[key];
}

export function dispatch(key: string, value: any) {
  state[key] = value;
  const targetDeps = deps[key] || {};
  Object.keys(targetDeps).forEach(key => {
    targetDeps[key](value);
  });
}

export function subscribe(key: string, callback: (valve: any) => void): string {
  const count = counter[key] || 0;
  const targetDeps = deps[key] || {};
  const secret = `${key}-${count + 1}`;

  counter[key] = count + 1;
  targetDeps[secret] = callback;
  deps[key] = targetDeps;

  return secret;
}

export function unsubscribe(key: string, secret: string) {
  const targetDeps = deps[key] || {};

  if (secret in targetDeps) {
    delete targetDeps[secret];
  }

  deps[key] = targetDeps;
}
```

2、主应用初始化的时候绑定一个 getter 到 window 上：
```ts
import { get, dispatch, subscribe, unsubscribe } from './store';

Object.defineProperty(window, '$store', {
  get: function() {
    return { get, dispatch, subscribe, unsubscribe };
  }
});
```

3、各个应用通信时使用 `$store` 的方法即可，如果你想要响应式的体验，可以在各个应用初始化的时候做点手脚，比如 vue 可以用 mixin，react 可以封装 hooks：
```ts
export function useGlobalState(key: string, defaultValue?: any) {
  const defaultState = $store.get(key) || defaultValue;
  const [globalState, setGlobalState] = useState(defaultState);

  function handleGlobalState(value: any) {
     $store.dispatch(key, value);
  }

  useEffect(() => {
    if (defaultState) {
      handleGlobalState(defaultState);
    }

    const secret =  $store.subscribe(key, setGlobalState);
    return () => {
       $store.unsubscribe(key, secret);
    };
  }, []);

  return [globalState, handleGlobalState];
}
```

把技术相关性从主应用转移到微应用，技术栈就能解耦开了，直接用 vuex 太重了。

**Comment by gucovip** [comment]
这个问题，我在实际使用中也有过这样的想法。但是后来发现，由父项目提供对应公告数据的接口，有利于解耦。父子应用的数据应该严格的隔离防止污染，不然可能出现无法估量的麻烦。 @gudepeng
