### ISSUE TITLE
【咨询】qiankuan在load子应用时，会检查dom是否存在，请问这个检查有没有hook点

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#569]
![image](https://user-images.githubusercontent.com/63687537/81783898-a2c3da00-952e-11ea-84f1-497c057b6717.png)

我尝试在beforeload的hook中，发现这个dom检查在beforeload前做

**Comment by kuitos** [comment]
这不是在 before load 之后么

**Comment by waltbest2** [comment]
![image](https://user-images.githubusercontent.com/63687537/81785215-9b053500-9530-11ea-953a-029f015a6b01.png)


beforeload 还没有执行完

**Comment by waltbest2** [comment]
![image](https://user-images.githubusercontent.com/63687537/81785296-b83a0380-9530-11ea-90c9-5d5aec3254dc.png)

**Comment by kuitos** [comment]
提供可复现仓库
