### ISSUE TITLE
vue-cli3子项目接入

### ISSUE THREAD

**Issue by yangangzhang** [umijs/qiankun#57]
## 跨域问题

主项目用的是parcel，接入的子项目是vue-cli3搭建的小项目，已经配置了output，报错，问题如下图所示
![image](https://user-images.githubusercontent.com/20433039/64110388-963e8d80-cdb4-11e9-869b-abb0e1fa60f4.png)

**Comment by kuitos** [comment]
localhost:7106 是哪里的资源？

**Comment by yangangzhang** [comment]
这是是vue-cli脚手架接入的子项目，设置的端口号7106

**Comment by yangangzhang** [comment]
> localhost:7106 是哪里的资源？

这是是vue-cli脚手架接入的子项目，设置的端口号7106

**Comment by kuitos** [comment]
提供可复现的 repo

**Comment by hetianxiang** [comment]
可以配置你跨域项目的webpack-dev-server 设置为允许跨域

**Comment by yangangzhang** [comment]
> 可以配置你跨域项目的webpack-dev-server 设置为允许跨域

是的，这样可以，或者在主文件中配置可以了，谢谢

**Comment by Hades-li** [comment]
> 可以配置你跨域项目的webpack-dev-server 设置为允许跨域

麻烦告知，webpack-dev-server如何自身设置允许跨域

**Comment by JqiangLiu** [comment]
@wwlh200 这个在vue2.0(旧项目)里要怎么配,试过在config/index里面添加,还是报跨域的错误

**Comment by F-loat** [comment]
vue 项目可以使用 [vue-cli-plugin-qiankun](https://github.com/F-loat/vue-cli-plugin-qiankun) 这个插件快速接入 qiankun 框架
