### ISSUE TITLE
[Bug] 多次使用 loadMicroApp 挂载同名微应用，会出现 element 和样式挂载错误

### ISSUE THREAD

**Issue by dbkillerf6** [umijs/qiankun#574]
## What happens?

多次使用 loadMicroApp 挂载同名微应用，会出现样式挂载错误和 [qiankun] Wrapper element for card-list with instance card-list_1589423446854 is not existed!

## Mini Showcase Repository(REQUIRED)

https://github.com/dbkillerf6/qiankun-error-demo

## Context

- **qiankun Version**: 2.0.11

**Comment by dbkillerf6** [comment]
感觉是两个问题：
#### 1. 样式挂载
可能需要改 `src/sandbox/patchers/dynamicHeadAppend`

#### 2. [qiankun] Wrapper element for card-list with instance card-list_1589423446854 is not existed!
本地在 node_modules 里面 debug 了一下，修改 `src/loader.ts` 可解：
```javascript
// line 83
const element = elementGetter();  ->  const element = elementGetter; 

// line 230
() => element  ->  element
```

**Comment by kuitos** [comment]
原因是子应用配置了这个导致的 https://github.com/dbkillerf6/qiankun-error-demo/blob/09f88806eda5681d34cc1605cd715f37ef2e4f0b/micro/card-list/config/webpack.config.js#L140

webpack 默认的 globalObject 值是 'window'，通常不配就行，如果改成了 'this' 会导致沙箱泄露，从而导致不同实例共用了同一个 chunk 运行时，而前一个运行时因为卸载后 element 被置为 null，下一个实例因为还是在同一运行时里会直接使用前一个闭包中的 element，从而造成了报错

**Comment by wssgchungang** [comment]
> 原因是子应用配置了这个导致的 https://github.com/dbkillerf6/qiankun-error-demo/blob/09f88806eda5681d34cc1605cd715f37ef2e4f0b/micro/card-list/config/webpack.config.js#L140
> 
> webpack 默认的 globalObject 值是 'window'，通常不配就行，如果改成了 'this' 会导致沙箱泄露，从而导致不同实例共用了同一个 chunk 运行时，而前一个运行时因为卸载后 element 被置为 null，下一个实例因为还是在同一运行时里会直接使用前一个闭包中的 element，从而造成了报错

我子应用用的是umi ，webpack的配置也没改，不同路由下加载同名微应用，切换的时候也是空页面
