### ISSUE TITLE
[Bug]当我只有一个子项目时，prefetch不生效

### ISSUE THREAD

**Issue by gongshun** [umijs/qiankun#575]
## What happens?

我的主项目本身就有很多路由和页面，现在使用`qiankun2.0`集成一个子项目，子项目的`prefetch`时机是`window.addEventListener('single-spa:first-mount'）`，我只有一个子项目，不会有
`single-spa:first-mount`事件，所以子项目的`prefetch`不生效。

## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置

无

## 相关环境信息

- **qiankun 版本**：2.0
- **浏览器版本**：chrome
- **操作系统**：win10

**Comment by kuitos** [comment]
`prefetch: 'all'`，看下文档

![image](https://user-images.githubusercontent.com/5206843/81899877-5f30a500-95ee-11ea-8acd-d43e387f9290.png)
