### ISSUE TITLE
entry是否可以设置相对路径

### ISSUE THREAD

**Issue by benrennanshen** [umijs/qiankun#577]
场景是这样的：ip和端口，客户只给了一个，但是要访问不同子项目，entry相对路径应该怎么配置，例如：app1:entry://192.168.1.191:8087/budget,app2:entry://192.168.1.191:8087/diagnostic 这样访问会报错VM35 chunk-vendors.16b7d406.js:44 Uncaught Error: application 'sub-app-diagnostic' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in sub-app-diagnostic entry，如果类似于这样配置就可以正常访问//192.168.1.191:8088/budget

![1589443067137_4718EAD5-ADAA-4352-A426-DE8E447EE081](https://user-images.githubusercontent.com/29425816/81910470-96a74d80-95fe-11ea-8be0-55af6e96a6f6.png)
我圈的相对路径不可以访问，只要不同的端口就可以正常访问了，列如：最下边的可以正常访问

**Comment by gongshun** [comment]
是你没有在入口文件导出需要的生命周期吧

**Comment by benrennanshen** [comment]
报这个错误是没有导出生成周期，但是我只是把端口跟主应用不一样就可以正常访问，肯定是因为某些愿意触发了这个问题

**Comment by dbkillerf6** [comment]
你端口跟主应用一样不就去请求主应用了？那肯定没有声明周期啊

**Comment by benrennanshen** [comment]
谢谢，我把端口改成跟另外一个可以成功访问的子应用的端口一致，仅仅是在nginx做了相对路径的映射，但是fetch数据失败了
![image](https://user-images.githubusercontent.com/29425816/81919615-a62c9380-960a-11ea-8794-746627467488.png)

**Comment by benrennanshen** [comment]
一个端口使用相对路径完全可以，原来是我nginx不熟悉，已上线成功

**Comment by shinji3887** [comment]
> 一个端口使用相对路径完全可以，原来是我nginx不熟悉，已上线成功

你好，我现在也需要使用相对路径，请问你是怎么配置entry的？

**Comment by yangdan8** [comment]
> 一个端口使用相对路径完全可以，原来是我nginx不熟悉，已上线成功

可以分享一下配置吗?

**Comment by hql7** [comment]
https://juejin.cn/post/6844904143413313549#heading-22 快速调整为双端口方案
