### ISSUE TITLE
从子项目页面跳转到主项目自身的页面时，主项目页面的css未加载

### ISSUE THREAD

**Issue by gongshun** [umijs/qiankun#578]
## What happens?

从子项目页面跳转到主项目自身的页面时，主项目页面的css未加载

## Mini Showcase Repository(REQUIRED)

https://github.com/gongshun/qiankun-vue-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

如图所示，当页面处于子项目`app-vue-hash`时，点击导航`about`，跳转到主项目的路由页面，主项目的这个页面`css`未加载，刷新页面才会加载

![bug gif](https://user-images.githubusercontent.com/29347231/81916158-0a008d80-9606-11ea-8b3f-43b38203ba70.gif)

**Expected behavior** 1. 2.

从子项目路由跳转到主项目自己的路由页面时，主项目页面的`css`能正确加载

## Context

- **qiankun Version**:  2.0
- **Platform Version**: win10
- **Browser Version**: Chrome 81

**Comment by daichunlin1995** [comment]
https://github.com/umijs/qiankun/issues/517

**Comment by gongshun** [comment]
产生这个问题的原因是：在子项目跳转到父项目时，子项目的卸载需要一点点的时间，在这段时间内，父项目加载了，插入了css，但是被子项目的css沙箱记录了，然后被移除了。父项目的事件监听也是一样的，所以需要在子项目卸载完成之后再跳转。
临时解决办法：先复制一下`HTMLHeadElement.prototype.appendChild`和`window.addEventListener`，路由钩子函数`beforeEach`中判断一下，如果当前路由是子项目，并且去的路由是父项目的，则还原这两个对象.
```js
const childRoute = ['/app-vue-hash','/app-vue-history'];
const isChildRoute = path => childRoute.some(item => path.startsWith(item))
const rawAppendChild = HTMLHeadElement.prototype.appendChild;
const rawAddEventListener = window.addEventListener;
router.beforeEach((to, from, next) => {
  // 从子项目跳转到主项目
  if(isChildRoute(from.path) && !isChildRoute(to.path)){
    HTMLHeadElement.prototype.appendChild = rawAppendChild;
    window.addEventListener = rawAddEventListener;
  }
  next();
});
```

`demo`也已经更新

**Comment by IndexXuan** [comment]
+1 官方大大准备怎么解决 ？

**Comment by Plortinus** [comment]
这个问题用 defer 属性能解决吗？

**Comment by gongshun** [comment]
> 这个问题用 defer 属性能解决吗？


@Plortinus 不可以。
`qiankun`是根据路由`path`参数来加载子项目的，解决这个问题，有两个办法：
1. 子项目的`HTMLHeadElement.prototype.appendChild`事件里面，先判断当前path是不是子项目，如果不是，就不记录新增的`link/style`标签
2. 子项目一旦触发卸载，立马冻结记录`link/style`标签的数组。
@kuitos 大佬觉得可行不

**Comment by kuitos** [comment]
`singular: false` 应该就可以解决了

**Comment by gongshun** [comment]
> `singular: false` 应该就可以解决了，不过这算是一个临时方案

我试了下，不能解决这个问题，只能用上面的 `hack` 方法

**Comment by kuitos** [comment]
看了下，是因为走到了兼容 1.x 的逻辑里了

近期打算发布 2.1 把兼容逻辑去掉，去掉后应该就不会有这个问题了

**Comment by shuyanzi** [comment]
> ```js
> const rawAppendChild = HTMLHeadElement.prototype.appendChild;
> const rawAddEventListener = window.addEventListener;
> router.beforeEach((to, from, next) => {
>   // 从子项目跳转到主项目
>   if(isChildRoute(from.path) && !isChildRoute(to.path)){
>     HTMLHeadElement.prototype.appendChild = rawAppendChild;
>     window.addEventListener = rawAddEventListener;
>   }
>   next();
> });
> ```
首次加载还是走qiankun代理的appendChild方法，子应用的资源还是加载到了子应用容器里。
（patchAtBootstrapping, patchAtMounting方法共加载两次，会给HTMLHeadElement.prototype.appendChild赋值两次）

故想到从源头拦截appendChild，使qiankun的重写方法不生效

经尝试，这样是可以的：

const originAppendChild = HTMLHeadElement.prototype.appendChild
Object.defineProperty(HTMLHeadElement.prototype, 'appendChild', {
  set() {}, // 使后来的重写操作失效
  get() {
    return (newChild: any) => {
      return originAppendChild.call(this, newChild)
    }
  },
})

**Comment by GreatAuk** [comment]
v2.0.14 依然存在这个问题

**Comment by IndexXuan** [comment]
> 看了下，是因为走到了兼容 1.x 的逻辑里了
> 
> 近期打算发布 2.1 把兼容逻辑去掉，去掉后应该就不会有这个问题了

大佬，好久了，啥时候 2.1 版本啊 ...

**Comment by cjfff** [comment]
哈哈，不是没加载，是加载到了 `qiankun` 区域下的 `head` 中...  希望官方快点修复 ~

**Comment by qiuzhenlin1990** [comment]
老问题了，啥时候能修复？

**Comment by 535601882** [comment]
请问现在主项目的CSS加载到子项目下面，官方有解决方案吗？

**Comment by tianyige21** [comment]
> > `singular: false` 应该就可以解决了，不过这算是一个临时方案
> 
> 我试了下，不能解决这个问题，只能用上面的 `hack` 方法
是不是叫hook呀

**Comment by zwlijun** [comment]
这个问题还是存在，有解决了朋友吗？
qiankun版本: 2.5.1
-------------
应用场景：
主应用使用的是异步路由加载；在子应用页面刷新后，切回主应用页面，样式丢失。

**Comment by AprilLemon** [comment]
> ## 这个问题还是存在，有解决了朋友吗？
> qiankun版本: 2.5.1
> 应用场景： 主应用使用的是异步路由加载；在子应用页面刷新后，切回主应用页面，样式丢失。

#1730 主项目page不多，直接引入，不要懒加载

**Comment by addamx** [comment]
今天也碰到这个问题，在strictSandbox的模式下(2.7.0)，在跳转到主项目页面之前，把执行setCurrentRunningApp(null)，这样就确保不会影响到主项目的css加载。

```ts
import { setCurrentRunningApp } from 'qiankun/es/sandbox/common';

router.beforeEach((routeTo, routeFrom, next) => {
  setCurrentRunningApp(null);
  ....
}
```

**Comment by hopekayo** [comment]
> 今天也碰到这个问题，在strictSandbox的模式下(2.7.0)，在跳转到主项目页面之前，把执行setCurrentRunningApp(null)，这样就确保不会影响到主项目的css加载。
> 
> ```ts
> import { setCurrentRunningApp } from 'qiankun/es/sandbox/common';
> 
> router.beforeEach((routeTo, routeFrom, next) => {
>   setCurrentRunningApp(null);
>   ....
> }
> ```

试了这个方案可以，在调转到主应用前，执行一下setCurrentRunningApp(null);

**Comment by sanfran1068** [comment]
angular改怎么解决？

**Comment by sanfran1068** [comment]
那angular项目该怎么处理？

**Comment by zmf0705** [comment]
请问这个问题有解决嘛，angular主项目和vue子项目碰到了这个问题。

**Comment by HappyYang233** [comment]
> 产生这个问题的原因是：在子项目跳转到父项目时，子项目的卸载需要一点点的时间，在这段时间内，父项目加载了，插入了css，但是被子项目的css沙箱记录了，然后被移除了。父项目的事件监听也是一样的，所以需要在子项目卸载完成之后再跳转。 临时解决办法：先复制一下`HTMLHeadElement.prototype.appendChild`和`window.addEventListener`，路由钩子函数`beforeEach`中判断一下，如果当前路由是子项目，并且去的路由是父项目的，则还原这两个对象.
> 
> ```js
> const childRoute = ['/app-vue-hash','/app-vue-history'];
> const isChildRoute = path => childRoute.some(item => path.startsWith(item))
> const rawAppendChild = HTMLHeadElement.prototype.appendChild;
> const rawAddEventListener = window.addEventListener;
> router.beforeEach((to, from, next) => {
>   // 从子项目跳转到主项目
>   if(isChildRoute(from.path) && !isChildRoute(to.path)){
>     HTMLHeadElement.prototype.appendChild = rawAppendChild;
>     window.addEventListener = rawAddEventListener;
>   }
>   next();
> });
> ```
> 
 HTMLHeadElement.prototype.appendChild = rawAppendChild;
在router.beforeEach中修改HTMLHeadElement.prototype.appendChild 在下面的场景会有问题：
可按照以下步骤复现：
1、从主应用进入子应用
2、通过**浏览器返回按钮**返回主应用
3、再次进入子应用
这个时候请求子应用的静态资源的方式会变为script并将静态资源插入到主应用的head标签下，控制台会产生load chunk x failed的错误。

**Comment by zmf0705** [comment]
谢谢您的来稿，正在处理。。。
