### ISSUE TITLE
在构建后的文件中报错

### ISSUE THREAD

**Issue by Jude-summery** [umijs/qiankun#579]
## What happens?
在本地调试时一切正常，但是在打包上线之后，出现了如下的报错,
![TIM图片20200514194246](https://user-images.githubusercontent.com/24602891/81930405-1cd18d00-961b-11ea-998b-2cf3557912f0.png)
![TIM图片20200514194158](https://user-images.githubusercontent.com/24602891/81930327-075c6300-961b-11ea-8f18-673ee2486905.png)
- **qiankun Version**: 2.0.11

**Comment by kuitos** [comment]
提供可复现仓库后可自行 reopen
