### ISSUE TITLE
[求助] 组件集成有没有好的建议？

### ISSUE THREAD

**Issue by M-ike** [umijs/qiankun#58]
开发中有一些场景，需要用到组件集成，请问有没有什么好的建议？

页面结构简化一下是这样的：
<div>
    <tab>app1 page</tab>
    <tab>app2 page</tab>
</div>
或者 在同一个页面的不同区域要展示来自两个应用的内容

**Comment by howel52** [comment]
如果是单纯的组件级别的场景，可以参考服务化组件的思想

app 级别的话可以看下 roadmap, https://github.com/umijs/qiankun/blob/master/README.md#-roadmap   WIP

**Comment by Dolov** [comment]
> 

服务化组件 这个有什么好的实践么
