### ISSUE TITLE
使用sandbox，vue + Element引发的问题

### ISSUE THREAD

**Issue by Kcium** [umijs/qiankun#580]
## What happens?

问题一：

![image](https://user-images.githubusercontent.com/20454249/82008293-d6257680-969e-11ea-8885-10299a32d379.png)
![image](https://user-images.githubusercontent.com/20454249/82008613-c35f7180-969f-11ea-9131-3eb383f3bc9f.png)

Error in callback for watcher "showPopper": "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

开启沙盒模式后，获取元素style信息会报错，

完整代码如下
```
import {
  registerMicroApps,
  runAfterFirstMounted,
  setDefaultMountApp,
  start,
  initGlobalState,
  loadMicroApp
} from 'qiankun';
// for angular subapp
// import 'zone.js';
import './index.less';
import render from './render/ReactRender';

const loader = (loading: any) => render({ loading });

registerMicroApps(
  [
    {
      name: 'vue',
      entry: '//localhost:7101/',
      container: '#subapp-viewport',
      loader,
      activeRule: '/vue'
    }
  ],
  {
    beforeLoad: [
      (app) => {
        console.log('[LifeCycle] before load %c%s', 'color: green;', app.name);
        return Promise.resolve(app.name);
      }
    ],
    beforeMount: [
      (app) => {
        console.log('[LifeCycle] before mount %c%s', 'color: blue;', app.name);
        return Promise.resolve(app.name);
      }
    ],
    afterMount: [
      (app) => {
        console.log('[LifeCycle] after mount %c%s', 'color: green;', app.name);
        return Promise.resolve(app.name);
      }
    ],
    afterUnmount: [
      (app) => {
        console.log('[LifeCycle] after unmount %c%s', 'color: red;', app.name);
        return Promise.resolve(app.name);
      }
    ]
  }
);

const { onGlobalStateChange, setGlobalState } = initGlobalState({
  csInfo: {}
});

onGlobalStateChange((value, prev) => console.log('[onGlobalStateChange - master]:', value, prev));

setDefaultMountApp('/vue');

start({
  sandbox: {
    // strictStyleIsolation: true,
  }
});
// start();


// 装载navbar
loadMicroApp({
  name: 'navbar',
  entry: '//localhost:7001/angel-navbar/',
  container: '#mainapp-header'
}, {
  sandbox: {
    strictStyleIsolation: false
  },
},);

runAfterFirstMounted(() => {
  console.log('[MainApp] first app mounted');
});
```

如果把 `start()` 改成 `start({ singular: false }); `也会报同样的错误

问题二： 
这里还有另外一个问题，如果我不使用沙盒模式，就会出现 '/vue' 路由无法加载，会一直显示 mount 超时，给子应用单独设置超时时间也不行
![image](https://user-images.githubusercontent.com/20454249/82008794-37017e80-96a0-11ea-8286-cbab24ec1cc9.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.0.11
- **Platform Version**: mac
- **Browser Version**: chrome 81.0.4044.138 (Official Build) (64-bit)

**Comment by kuitos** [comment]
提供可复现仓库

**Comment by KAionro** [comment]
> 提供可复现仓库

因为是我本地项目，没有使用github，暂时没法提供，但是试了几个demo，只要是使用了 vue + Element 提供的 popover 相关的组件都会出现类似问题

**Comment by KAionro** [comment]
> 提供可复现仓库

官方提供的 example 里的vue 项目，随便在 Home.vue 里添加一个相关popover的组件就会报错的

```
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png"/>
    <HelloWorld msg="Vue.js Demo"/>

    <el-button @click="dialogVisible = true" type="text">Open Dialog</el-button>

    <el-dropdown>
      <span class="el-dropdown-link">
        下拉菜单<i class="el-icon-arrow-down el-icon--right"></i>
      </span>
      <el-dropdown-menu slot="dropdown">
        <el-dropdown-item>黄金糕</el-dropdown-item>
        <el-dropdown-item>狮子头</el-dropdown-item>
        <el-dropdown-item>螺蛳粉</el-dropdown-item>
        <el-dropdown-item disabled>双皮奶</el-dropdown-item>
        <el-dropdown-item divided>蚵仔煎</el-dropdown-item>
      </el-dropdown-menu>
    </el-dropdown>

    <el-dialog
      :before-close="handleClose"
      :visible.sync="dialogVisible"
      title="Dialog"
      width="30%">
      <span>dialog message</span>
      <span class="dialog-footer" slot="footer">
        <el-button @click="dialogVisible = false">cancel</el-button>
        <el-button @click="dialogVisible = false" type="primary">ok</el-button>
      </span>
    </el-dialog>
  </div>

</template>
```

**Comment by KAionro** [comment]
` start({ singular: false }) ` 使用该模式启动的情况下会出现类似问题
求教。

**Comment by liuzhen88** [comment]
> `start({ singular: false })` 使用该模式启动的情况下会出现类似问题
> 求教。

我也遇到同样的问题，您解决了吗？

**Comment by Kcium** [comment]
> > `start({ singular: false })` 使用该模式启动的情况下会出现类似问题
> > 求教。
> 
> 我也遇到同样的问题，您解决了吗？

Element-ui 在使用getComputedStyle这个方法的时候，其实需要判断一下
可以在mount钩子函数里添加如下代码
```
// @ts-ignore
  window.getComputedStyle = (element, property) => {
    if (!element || element.nodeType === 9) return {};
    return getStyle(element, property);
  };
```

**Comment by vius** [comment]
> > > `start({ singular: false })` 使用该模式启动的情况下会出现类似问题
> > > 求教。
> > 
> > 
> > 我也遇到同样的问题，您解决了吗？
> 
> Element-ui 在使用getComputedStyle这个方法的时候，其实需要判断一下
> 可以在mount钩子函数里添加如下代码
> 
> ```
> // @ts-ignore
>   window.getComputedStyle = (element, property) => {
>     if (!element || element.nodeType === 9) return {};
>     return getStyle(element, property);
>   };
> ```

getStyle function在哪里定义呢？

**Comment by XianlongLi** [comment]
你好，请问一下这个问题是怎么解决的，能提供一下完整的代码吗

**Comment by Kcium** [comment]
> 你好，请问一下这个问题是怎么解决的，能提供一下完整的代码吗

重写该方法的实现
`
window.getComputedStyle = (element, property) => {
    if (!element || element.nodeType === 9) return {};
    return getStyle(element, property);
  };
`

**Comment by xyz12345678** [comment]
getStyle 这个方法是什么？  会报undefined

**Comment by xyz12345678** [comment]
> > 你好，请问一下这个问题是怎么解决的，能提供一下完整的代码吗
> 
> 重写该方法的实现
> `window.getComputedStyle = (element, property) => { if (!element || element.nodeType === 9) return {}; return getStyle(element, property); };`

getStyle 这个方法是什么？ 会报undefined

**Comment by lovedaan** [comment]
"element-ui": "^2.15.3","qiankun": "^2.4.4",我也遇到这个问题，开启了沙箱之后，找到window.getComputedStyle (element, property)  element节点找到的是沙箱dom，所以报错了。
在子应用的mainjs里面加上 
var rawGetComputedStyle = window.getComputedStyle;
window.getComputedStyle = function (el, pseudoElt) {
  if (el === document) return { overflow: "auto" };
  if (el instanceof HTMLElement) {
    return rawGetComputedStyle(el, pseudoElt);
  } else {
    return {}
  }
};
// 解决定位问题
Object.defineProperty(document, "scrollLeft", {
  get() {
    return document.documentElement.scrollLeft;
  },
});
Object.defineProperty(document, "scrollTop", {
  get() {
    return document.documentElement.scrollTop;
  },
});

**Comment by Kcium** [comment]
> > > 你好，请问一下这个问题是怎么解决的，能提供一下完整的代码吗
> > 
> > 
> > 重写该方法的实现
> > `window.getComputedStyle = (element, property) => { if (!element || element.nodeType === 9) return {}; return getStyle(element, property); };`
> 
> getStyle 这个方法是什么？ 会报undefined


贴一段完整的代码吧

```

export async function mount(props: any) {
  const getStyle = window.getComputedStyle;
  // @ts-ignore
  window.getComputedStyle = (element, property) => {
    if (!element || element.nodeType === 9) return {};
    return getStyle(element, property);
  };

  render(props);
  registerStore(props);
}

```
