### ISSUE TITLE
[Bug]浏览器按钮返回主应用，主应用页面并没有渲染出来

### ISSUE THREAD

**Issue by hqy1204** [umijs/qiankun#582]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
浏览器按钮子应用返回主应用，主应用页面并没有渲染出来

## 复现步骤，错误日志以及相关配置
1、点击子应用路由进入子应用；
2、点击浏览器返回按钮
3、主应用页面空白

## 相关环境信息

- **qiankun 版本：2.0.11**
- **浏览器版本：Chrome/81.0.4044.138**：
- **操作系统：win7**：

**Comment by kuitos** [comment]
提供可复现仓库后再 reopen
