### ISSUE TITLE
无法修改__qiankun_microapp_wrapper_容器样式

### ISSUE THREAD

**Issue by KAionro** [umijs/qiankun#584]
## What happens?

当使用 singular = false 的时候
`start({ singular: false });`

子应用的容器会默认添加id __qiankun_microapp_wrapper_xxxx

我在子应用less文件添加如下图所有
![image](https://user-images.githubusercontent.com/20454249/82184142-b3eb5d00-9919-11ea-80ba-8824d4490c57.png)

但是，该dom上并没有该样式属性
![image](https://user-images.githubusercontent.com/20454249/82184199-ce253b00-9919-11ea-9f82-338a30fd31c6.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.0.11
- **Platform Version**:max os
- **Browser Version**:Google Chrome | 81.0.4044.138 (Official Build) (64-bit)

**Comment by kuitos** [comment]
> [attr|=value]
表示带有以 attr 命名的属性的元素，属性值为“value”或是以“value-”为前缀（"-"为连字符，Unicode 编码为 U+002D）开头。典型的应用场景是用来匹配语言简写代码（如 zh-CN，zh-TW 可以用 zh 作为 value）。

see https://developer.mozilla.org/zh-CN/docs/Web/CSS/Attribute_selectors

**Comment by KAionro** [comment]
div[id^='__qiankun_microapp_wrapper_'] {
  height: 100%;
}

这样用解决了

**Comment by 18595439829** [comment]
设置子应用容器子元素的全局样式:
#subapp-viewport {
  width: 100vw;
  height: 100vh;

  &>div {
    width: inherit;
    height: inherit;
  }
}
