### ISSUE TITLE
[Bug]主应用进入子应用，点击浏览器返回按钮返回主应用，主应用空白

### ISSUE THREAD

**Issue by hqy1204** [umijs/qiankun#585]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
主应用进入子应用，点击浏览器返回按钮返回主应用，主应用空白

## 最小可复现仓库
https://github.com/hqy1204/qiankunTest.git

## 复现步骤，错误日志以及相关配置
1、点击vue链接进入子应用
2、点击浏览器返回按钮返回主应用

##预期效果
主应用有渲染效果
## 相关环境信息

- **qiankun 版本：2.0.11**
- **浏览器版本:Chrome/81.0.4044.138**：
- **操作系统:win7**：

**Comment by songning0605** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by hqy1204** [comment]
@songning0605 我的主要问题是我把子应用挂载到父应用上的#app上了。若挂载父应用上导致子应用还没销毁实例；父应用的路由已经挂载了，我猜是这个原因导致没有渲染的吧。所以得在新建一个容器挂载子应用

**Comment by songning0605** [comment]
> @songning0605 我的主要问题是我把子应用挂载到父应用上的#app上了。若挂载父应用上导致子应用还没销毁实例；父应用的路由已经挂载了，我猜是这个原因导致没有渲染的吧。所以得在新建一个容器挂载子应用
是的，我也是在外边包了一层容器，用路由的方式访问空页面，这样目标节点就一直存在了
```
{
      path: '/',
      component: '@/layouts/AppContainer',
      routes: [
        { path: '/', redirect: 'index' },
        { path: 'index', exact: true, component: '@/pages/home/Home' },
        { path: 'optimization', exact: true, component: '@/layouts/BlankLayout' },
        { path: 'oms', exact: true, component: '@/layouts/BlankLayout' },
      ],
    },
```

**Comment by songning0605** [comment]
@hqy1204  是的，我也是在外边包了一层容器，提前渲染，这样目标节点就一直存在了
```
{
      path: '/',
      component: '@/layouts/AppContainer',
      routes: [
        { path: '/', redirect: 'index' },
        { path: 'index', exact: true, component: '@/pages/home/Home' },
        { path: 'optimization', exact: true, component: '@/layouts/BlankLayout' },
        { path: 'oms', exact: true, component: '@/layouts/BlankLayout' },
      ],
    },
```

**Comment by cqupt-yifanwu** [comment]
same question

**Comment by cqupt-yifanwu** [comment]
两位解决了么

**Comment by hqy1204** [comment]
@cqupt-yifanwu 检查子应用挂载的dom节点是否为父应用的#app。若是的话，会出现该上述情况，解决方案需要创建新容器挂载子应用

**Comment by cqupt-yifanwu** [comment]
> @cqupt-yifanwu 检查子应用挂载的dom节点是否为父应用的#app。若是的话，会出现该上述情况，解决方案需要创建新容器挂载子应用

可是如果新建节点挂载子应用，当路由匹配到子应用时主应用还在页面上，我目前需求想要子应用完全代替主应用

**Comment by hqy1204** [comment]
不可能完全代替吧，因为需要父应用基座注册子应用；如果只是页面上的代替。可以通过路由跳转实现

**Comment by hqy1204** [comment]
@cqupt-yifanwu 不可能完全代替吧，因为需要父应用基座注册子应用；如果只是页面上的代替。可以通过路由跳转实现

**Comment by cqupt-yifanwu** [comment]
@hqy1204 我没有表达清楚，是这样，我想把主应用做成一个首页，里面有很多子应用入口，点击跳转到子应用，当我返回回来主应用首页就显示不出来了，其实就是上面你们说的 子应用挂载到了 父应用的#app，这种情况我应该怎么操作？

**Comment by hqy1204** [comment]
@cqupt-yifanwu 目前解决方案是创建新容器挂载子应用。`#frame`是负责挂载子应用的容器；`#nav`是负责路由跳转。ps:  /vue是子应用路由,挂载在`#frame`上
```
  <div id="app">
    <div id="nav">
      <router-link to="/home">Home</router-link>|
      <router-link to="/about">About</router-link>|
      <router-link to="/vue">vue</router-link>
    </div>
    <router-view />
    <div id="frame"></div>
  </div>
```

**Comment by cqupt-yifanwu** [comment]
@hqy1204 那么假如不是每个页面都需要nav 跳回来其实就不行了

**Comment by hqy1204** [comment]
@cqupt-yifanwu https://github.com/hqy1204/qiankunTest.git 的dev分支上的应该有你的解决方案。该仓库我屏蔽了nav导航栏可以通过url输入路由/vue就可以进入子应用

**Comment by cqupt-yifanwu** [comment]
> @cqupt-yifanwu https://github.com/hqy1204/qiankunTest.git 的dev分支上的应该有你的解决方案。该仓库我屏蔽了nav导航栏可以通过url输入路由/vue就可以进入子应用

这样首页不是没有内容了么，我打算把首页做成子应用了..

**Comment by hqy1204** [comment]
@cqupt-yifanwu 路由设置redirect..
```
{
        path: '/',
        redirect: '/vue',
 },
```
