### ISSUE TITLE
[问题]已vue作为主应用，手动强行卸载子应用后，懒加载js报错，并且不可恢复。

### ISSUE THREAD

**Issue by Hades-li** [umijs/qiankun#586]
## 问题
基于qiankun做了一个vue的插件，使用qiankun采用手动方式载入子应用。在子应用加载的过程当中，强行切换路由，其实也就是强行unmouted当前的子应用。结果就造成子应用vue-router在懒加载页面js时报错（因为vue实例被强行destory了，报错也属正常）。关键是，这样的报错，在重新load这个子应用时，依然会再次报错，无法恢复。如图：
![qiankun](https://user-images.githubusercontent.com/12124478/82296242-7e12ab00-99e3-11ea-9908-0dff0b8db0ea.gif)

vue的实例在unmouted时会被destory。在再次load时会重新实例化。理论不应该会再次报错。
不能确定，是由于vue-router本身的机制造成，还是qiankun缓存了某些东西导致。求指点。

## 相关环境信息

- **qiankun 版本**：2.0.2
- **浏览器版本**：chorme 81
- **操作系统**：win10

## 可复现版本库
[https://github.com/Hades-li/qiankun-vue](https://github.com/Hades-li/qiankun-vue)

**Comment by kuitos** [comment]
@gongshun 看下这个问题还有吗

**Comment by gongshun** [comment]
看了下他这个demo，子项目间频繁切换不会报错了。

子项目快速切主项目页面，`vue-router` 会报错（文件路径是正确的），但是不影响使用和再次加载。

![image](https://user-images.githubusercontent.com/29347231/95882325-2454b800-0dac-11eb-8626-4e09492c9f75.png)

![image](https://user-images.githubusercontent.com/29347231/95882496-58c87400-0dac-11eb-8a2d-07352436a468.png)

应该是 js 沙箱对  `history` 对象的劫持影响了 `vue-router` ，关闭沙箱就不会报错。猜测和https://github.com/umijs/qiankun/issues/578 是一个问题
