### ISSUE TITLE
[Bug] vue 项目中，在页面 checkbox 比较多的情况下，切换 checkbox 状态导致卡顿

### ISSUE THREAD

**Issue by everyun** [umijs/qiankun#588]
## What happens?

在 vue 项目中，当页面 checkbox 比较多的情况下，改变 checkbox 状态会导致页面卡顿，element 和 iview 的 checkbox 都可以复现

## 最小可复现仓库

https://github.com/everyun/qiankun-vue-demo

### 运行
master 为基座，module 为微应用  
分别 npm install && npm run serve 之后  
主项目访问地址 http://localhost:10010/simple/  
微应用直接地址为 http://localhost:10011/simple/  

### 复现
页面中放了 200 个 checkbox，当切换 checkbox 状态时，可以感觉到明显的卡顿  
直接访问微应用做同样的操作，没有卡顿的现象

**Comment by mollion** [comment]
使用iview的table时，缩放浏览器窗口时，也会感觉到卡顿

**Comment by kuitos** [comment]
released v2.0.12-2，做了一定程度的优化，相较之前有大概 45% 的性能提升，可以试下

**Comment by kuitos** [comment]
closed via inactive

**Comment by xiaoLus** [comment]
@kuitos ant-design-vue@2.0.0 table组件和select组件也是同样情况，子应用单独访问，非常流畅，接入qiankun主应用后非常卡

**Comment by kuitos** [comment]
@xiaoLus 提供一个可复现仓库，我们看看

**Comment by xiaoLus** [comment]
issue: #1110 

[复现仓库](https://github.com/xiaoLus/qiankun-vue3-antd2)

**Comment by lihuangshuaige** [comment]
2.6版本还是很卡啊

**Comment by Tinet-zhangmd** [comment]
> 2.6版本还是很卡啊
请问您这边怎么处理的？

**Comment by kuitos** [comment]
released v2.8.0，通过 `{ sandbox: { speedy: true } }` 配置开启。
