### ISSUE TITLE
【bug】特殊的 script 标签不应该被执行

### ISSUE THREAD

**Issue by gongshun** [umijs/qiankun#596]
## What happens?

子项目中使用了`system.js`，`system.js`的配置文件是一个`script`标签，内容是一个`json`：
```js
<script type="systemjs-importmap">
      {
        "imports": {
          "navbar": "http://localhost:8080/app.js",
          "app1": "http://localhost:8082/app.js",
          "app2": "http://localhost/app.js",
          "single-spa": "https://cdnjs.cloudflare.com/ajax/libs/single-spa/4.3.7/system/single-spa.min.js",
          "vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js",
          "vue-router": "https://cdn.jsdelivr.net/npm/vue-router@3.0.7/dist/vue-router.min.js"
        }
      }
    </script>
```

或者是外链`json`：
```js
<script type="systemjs-importmap" src="/config/importmap.json"></script>
```

当这个子系统被`qiankun`加载时，这个特殊的`script`标签，里面的内容被当成`js`去执行了，然后就报错了：

![image](https://user-images.githubusercontent.com/29347231/82629113-57da4e80-9c21-11ea-8bcc-c03e13f0a330.png)

![image](https://user-images.githubusercontent.com/29347231/82629129-645ea700-9c21-11ea-9f83-3eede1cc7b3f.png)

![image](https://user-images.githubusercontent.com/29347231/82629162-75a7b380-9c21-11ea-9a2b-036d955d2e6c.png)

## Mini Showcase Repository(REQUIRED)

无

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

这种特殊的`script`标签不应该被当成`js`执行，或者说获取到的`script`标签内容，应该判断下类型，是js才应该被执行

## Context

- **qiankun Version**: 2.0.11
- **Platform Version**: win10
- **Browser Version**: chrome

**Comment by daihaoxin** [comment]
@kuitos  这个是 import-html-entry  库里面的问题吧？

**Comment by daihaoxin** [comment]
> @kuitos 这个是 import-html-entry 库里面的问题吧？

> @kuitos 这个是 import-html-entry 库里面的问题吧？

按照现在 import-html-entry  中对 script 标签的处理方式是获取内容，然后用注释替换原有的 script 标签。



如下这种格式的 json 引入，因为无法使用，按照现有的方式处理，应该没有问题。

```html
<script>
    {
    	"name": "xxx",
    	"age": 18
    }
</script>
<!-- 或者 -->
<script src="http://xxx.com/filename.json"></script>
```

只要对导出的 `systemjs` 地图的方式处理下即可，`<script type="systemjs-importmap">`。



一点想法，大佬看看思路对不对
