### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by zeihang** [umijs/qiankun#6]
我仿照着react16写了一个项目，但是一直给我报这个错误，为啥呢
`Uncaught myReact app: Application 'myReact app' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in myReact app entry`

**Comment by zeihang** [comment]
是这么导出的吗
`export async function bootstrap() {
    console.log('react app bootstraped');
}

export async function mount(props) {
    console.log('props from main framework', props);
    ReactDOM.render(<App />, document.getElementById('reactRoot'));
}

export async function unmount() {
    ReactDOM.unmountComponentAtNode(document.getElementById('reactRoot'));
}`

**Comment by jiachaosun** [comment]
@zeihang 
你解决了吗？我也遇到这个问题了，既有项目加进去就打不开。

**Comment by kuitos** [comment]
@jiachaosun see https://github.com/umijs/qiankun/issues/8
