### ISSUE TITLE
[反馈]使用qiankun时，vue-devtools无法调试子项目

### ISSUE THREAD

**Issue by zczhangchao51** [umijs/qiankun#601]
这个问题可能不是qiankun的问题

## What happens?

![image](https://user-images.githubusercontent.com/14327786/82686185-031dee80-9c88-11ea-82a9-8d5135f02cee.png)

![image](https://user-images.githubusercontent.com/14327786/82686051-c651f780-9c87-11ea-87ac-c3dc2f80e114.png)

## 最小可复现仓库

官方示例即可复现，只要父子都是vue项目则无法调试子项目

**Comment by kuitos** [comment]
see https://github.com/vuejs/vue-devtools/issues/64#issuecomment-238025184

**Comment by zczhangchao51** [comment]
> see [vuejs/vue-devtools#64 (comment)](https://github.com/vuejs/vue-devtools/issues/64#issuecomment-238025184)

十分感谢回复，不过例子里的解决办法仅适用两个根实例的场景，多数的情况下父应用会含有多级组件嵌套，所以这里列出我的两个解决方式：

1、 通过测试vue-devtool会顺着组件树来显示，所以一种解决办法是把子应用挂载到父应用的挂载点的后面（不推荐）

`
// main root
var vm = new Vue({ 
  el: '#root', 
  render(h){
     return <app>
         <header></header>
         <content></content>  // 挂载点在这里面
     </app>
  }  
}); 
// sub root
var sub = new Vue({ el: '#footer' });

// 以下代码都要注意在开发环境开启即可
content.$children = [sub]
`

2、另外vue-devtool也会监测页面上组件的新增删除等，并识别这些元素的__vue__属性，所以第二种方式，把子应用的挂载到一个空div上丢到页面中

`
// main root
var vm = new Vue({ 
  el: '#root', 
  render(h){
     return <app>
         <header></header>
         <content></content> // 挂载点在这里面
     </app>
  }  
}); 
// sub root
var sub = new Vue({ el: '#footer' });

// 以下代码都要注意在开发环境开启即可
subDiv = document.createElement('div')
subDiv.__vue__ = sub
 document.body.appendChild(subtDiv)
`

**Comment by GreatAuk** [comment]
@zczhangchao51 `document.body.appendChild(subtDiv)` 里的 `subDiv` 打错了

**Comment by LeungCNGD** [comment]
@zczhangchao51 

subDiv = document.createElement('div')
subDiv.__vue__ = sub
document.body.appendChild(subDiv)

按照你的方法设置了，好像没起作用，具体要怎么写？

**Comment by LeungCNGD** [comment]
@zczhangchao51 

subDiv = document.createElement('div')
subDiv.__vue__ = sub
document.body.appendChild(subDiv)

按你的方法设置了，但是没起作用，具体要怎么写？

**Comment by nickolboy** [comment]
> @zczhangchao51
> 
> ```
> subDiv = document.createElement('div')
> subDiv.__vue__ = sub
> document.body.appendChild(subDiv)
> ```
> 
> 按你的方法设置了，但是没起作用，具体要怎么写？

同没成功，[vuejs/vue-devtools#64 (comment)](https://github.com/vuejs/vue-devtools/issues/64#issuecomment-238025184)这个也没成功

**Comment by fyzwjd** [comment]
@zczhangchao51 按这个办法成功了，但是页面刷新或者重新加载后，就又不起作用了，除非另开页签打开，不知道其他人有遇到这个情况不

**Comment by GitHdu** [comment]
> @zczhangchao51 按这个办法成功了，但是页面刷新或者重新加载后，就又不起作用了，除非另开页签打开，不知道其他人有遇到这个情况不

同遇到这种情况，请问解决了吗

**Comment by xdwxls** [comment]
请问这个问题解决了吗？

**Comment by topul** [comment]
基座是vue3，子应用是vue2，怎么处理？

**Comment by gjfei** [comment]
> 请问这个问题解决了吗？

这个在我的项目里面也没用

**Comment by zuibunan** [comment]
> 

not work for me

**Comment by zuibunan** [comment]
@topul not work for me

**Comment by gjfei** [comment]
升级到最新版的vue devtools 就可以了
