### ISSUE TITLE
[Feature Request] import-html-entry插件中能否使用new Function取代eval

### ISSUE THREAD

**Issue by gongshun** [umijs/qiankun#602]
## Background

MDN上提到：

1. eval() 是一个危险的函数

2. eval() 通常比其他替代方法更慢

原文地址： https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval

## Proposal

使用`new Function`取代`eval`，安全性上没有提升，但是性能有提升。

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function

两者可以实现完全一样的效果，不同的点在于`new Function`声明的是全局函数。

但是我看`import-html-entry`中`eval`使用的是引用地址，声明的也是全局函数，因此，我觉得可以用`new Function`取代`eval`。

![image](https://user-images.githubusercontent.com/29347231/82781798-59a84a00-9e8d-11ea-9d9d-39a7f5a07e3b.png)

![image](https://user-images.githubusercontent.com/29347231/82781817-6167ee80-9e8d-11ea-95eb-015a346847cb.png)

![image](https://user-images.githubusercontent.com/29347231/82781846-76448200-9e8d-11ea-8cb1-1d3ed4042114.png)

**Comment by dreamllq** [comment]
同时这块我发现，在IE11中运行到这块时会提示语法错误

**Comment by danealiu** [comment]
> 同时这块我发现，在IE11中运行到这块时会提示语法错误

同在IE11中运行到这块时会提示语法错误，这个怎么解决呢，现在导致IE11打不开子应用

**Comment by zry754331875** [comment]
@gongshun 为啥关闭，我也遇到了这个问题，在eval执行代码块的时候时间过长

**Comment by gongshun** [comment]
> @gongshun 为啥关闭，我也遇到了这个问题，在eval执行代码块的时候时间过长

两者还是有一些差异的，无法直接替换

**Comment by zry754331875** [comment]
> > @gongshun 为啥关闭，我也遇到了这个问题，在eval执行代码块的时候时间过长
> 
> 两者还是有一些差异的，无法直接替换

我替换后发现性能上没什么区别哈。。。。。

**Comment by fantasyroot** [comment]
> > @gongshun 为啥关闭，我也遇到了这个问题，在eval执行代码块的时候时间过长
> 
> 两者还是有一些差异的，无法直接替换

具体是什么差异导致无法替换？同在考虑这个事情
