### ISSUE TITLE
子应用如何改变主应用的state中的数据

### ISSUE THREAD

**Issue by Alfred-Skyblue** [umijs/qiankun#604]
求解，好像只介绍了主应用给子应用传值，没有子应用给主应用传值的方法啊

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/api#initglobalstatestate

![image](https://user-images.githubusercontent.com/5206843/82794492-25d91e80-9ea5-11ea-8db9-45f00d353db4.png)
