### ISSUE TITLE
子应用的CDN文件引用相对资源，主应用加载cdn的引用资源时路径引用错误

### ISSUE THREAD

**Issue by keunone** [umijs/qiankun#605]
## 子应用
![1](https://user-images.githubusercontent.com/17746982/82798792-9daa4780-9eab-11ea-84bd-2da4ce457153.png)
cdn资源内容：  
![3](https://user-images.githubusercontent.com/17746982/82798832-ae5abd80-9eab-11ea-9e03-c09d6576a31e.png)

## 主应用
![2](https://user-images.githubusercontent.com/17746982/82798919-ccc0b900-9eab-11ea-9134-6a3354f72424.png)

**Comment by zhouJiecode** [comment]
？
为什么close？

**Comment by 252860883** [comment]
这个问题有解吗？
