### ISSUE TITLE
子应用路由前缀相同时，路由切换错误

### ISSUE THREAD

**Issue by HermitSun** [umijs/qiankun#607]
## What happens?

两个子应用路由前缀相同时，路由切换时会出现错误，并且控制台报错：`Uncaught TypeError: application 'vuer' died in status LOADING_SOURCE_CODE: application 'vuer' died in status`
如，我这里有两个Vue的子应用，分别映射到/vue和/vue2，初始的默认路由是/vue，然后在父应用的导航栏点击Vue2进行路由切换时，会错误切换到/vue/2，而不是预期中的/vue2。
但是只要子应用的路由前缀不同，就不会出现这个问题，比如一个/vue，一个/react。

## Mini Showcase Repository

https://github.com/HermitSun/qiankun-router-jump-error

## How To Reproduce

**Steps to reproduce the behavior:**
1. npm install
2. 启动子应用和父应用
3. 访问localhost:1234
4. 点击导航栏的“Vue2”

**Expected behavior**
能够切换到另一个名为Vue2的子应用

## Context

- **qiankun Version**: 2.0.11
- **Platform Version**: Windows 10 1903（内部版本号 18362.145），框架版本Vue 2.6.11
- **Browser Version**: Chrome 81.0.4044.138 x64

**Comment by zhe-he** [comment]
+1
/monitor
monitorAd
monitor_ad
monnitor-ad

后面的路由都会有问题

**Comment by kuitos** [comment]
`activeRule` 可以自己写 function 做精确匹配

**Comment by HermitSun** [comment]
> `activeRule` 可以自己写 function 做精确匹配

懂了，原来文档里说的前缀匹配也包括这个情况啊，我以为所谓的前缀匹配指的是`/vue/*`。
需要在文档里补充一下吗？

**Comment by kuitos** [comment]
这个问题其实是 single-spa 的问题，谁有兴趣去 single-spa 提个 pr 支持一下?

**Comment by HermitSun** [comment]
> 这个问题其实是 single-spa 的问题，谁有兴趣去 single-spa 提个 pr 支持一下?

心有余而力不足啊（笑）
给dalao点赞👍

**Comment by kuitos** [comment]
single-spa v5.2.2 released

**Comment by throneoftheGame** [comment]
> `activeRule` 可以自己写 function 做精确匹配

能写一个function的例子吗？在做项目重构 旧项目路径为 /marking  / marking/list/detail
