### ISSUE TITLE
[推荐] 集成angular进入example

### ISSUE THREAD

**Issue by ZuccRoger** [umijs/qiankun#61]
## Background

  在微前端实践资料并没有那么丰富的前提下，qiankun帮助了我很多，目前市面上主流有3大框架，react 、 vue 和 angular ，我认为如果在example里面集成angular会帮助很大，而且内容会丰富，会更加能够帮助刚刚进入前端领域的新人，如何在实践过程中，更好的掌握这个新的技术

## Additional context
  Thank you very much ! It could be better that enrich the content of procedure of usage!

**Comment by chary2060** [comment]
所以，应该怎么加呢？

**Comment by kuitos** [comment]
子应用配置可以直接使用 single-spa 的方案 https://single-spa.js.org/docs/ecosystem.html
angular 的在这里 https://single-spa.js.org/docs/ecosystem-angular.html

**Comment by kuitos** [comment]
ref https://github.com/umijs/qiankun/issues/236

**Comment by kaichen87** [comment]
Angular8 的DEMO
https://github.com/kaichen87/micro-frontends-qiankun

**Comment by Deturium** [comment]
examples 中已添加 angular9 的例子
