### ISSUE TITLE
[Feature Request] 有没有人有SSM框架（Spring+SpringMVC+MyBatis+JSP）的这种非前后端分离的项目作为子应用接入qiankun的例子么

### ISSUE THREAD

**Issue by koupeng** [umijs/qiankun#610]
## Background

[Feature Request] 有没有人有SSM框架（Spring+SpringMVC+MyBatis+JSP）的这种非前后端分离的项目作为子应用接入qiankun的例子么

**Comment by shengliangli** [comment]
提一个思路：在 index.jsp 中引用 index.js ，index.js 可以用 react 等前端框架生成，或者参照 例子中的 纯 html 例子。

除了主要的 index.jsp的输出外，ssm 框架的其他输出页面转换为输出 json 数据。

其实，引入了spa 之后，和原有的 ssm 框架的功能有冲突和替代，一个市页面渲染，一个是服务器端渲染，思路都不一样，只能互相妥协，重新划分各自的边界，缩减后端的势力范围，补上前端的内容。

**Comment by koupeng** [comment]
这里也有个一个 #214  ，这个思路还是不太明白。能不能说的详细点。
（1）ssm 框架的其他输出页面转换为输出 json 数据。    这是什么意思
（2）怎么划分边界，不管我怎么弄在SSM框架里都是后台渲染吧。

**Comment by shengliangli** [comment]
划分边界是说ssm框架该干什么，前端该干什么，需要重新分工
ssm的其他输出页面转换的意思是说 ssm 框架的输出转换为单页应用，页面渲染由前端架构实现，ssm 框架只提供json 数据查询接口

**Comment by rogerIF** [comment]
在浏览器和后端中间件（如：`tomcat`）之间用node加一个换器，作为服务端渲染的后端。把每个的`jsp`当成一个个单独的路由，使用`vue`的服务端渲染（`SSR`），每次访问，都经过：
```
 浏览器 --> index.html --> node --> tomcat -->node -->浏览器
```
这样做：
1. 对`qiankun`来说，只处理纯前端页面（html,js,css,image,font）;
2. 对`tomcat`来说，依旧可以独立访问，基本不需要大改；
主要的工作量，就是用`node`做个转换器，`SSR`的方案现在很成熟，可以找到现成的库，权限控制可能要多花费一些时间

**Comment by dbkillerf6** [comment]
既然是服务端渲染JSP，直接MPA不香么？

**Comment by koupeng** [comment]
谢谢各位的回答，基本已经放弃了。

**Comment by Create-jyd** [comment]
放弃+1
