### ISSUE TITLE
qiankun启动后，子应用使用location.reload()刷新页面，发生无限循环跳转

### ISSUE THREAD

**Issue by hql7** [umijs/qiankun#611]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

qiankun启动后，子应用使用location.reload()刷新页面，在重新加载的子应用页面发生无限循环跳转

## 最小可复现仓库

https://github.com/wl-ui/wl-mfe

由于仓库里已经用某些神奇的办法暂时修复，重现请将‘master\src\core\app-register.js’ 中的  setDefaultMountApp(defaultApp + '/'); 后面的  +‘/’  去掉

## 复现步骤，错误日志以及相关配置

1. qiankun启动后加载登陆子应用，子应用进行登陆逻辑后使用location.reload()刷新页面
2. 刷新后会重新注册子应用并setDefaultMountApp()加载新的子应用。
3. 此时不晓得是qiankun和vue router发生了什么冲突，页面开始在新加载的子应用页面无限刷新。

所有子应用均为vue， 产生无限刷新的子应用为 vue3.0beta

目前解决办法：setDefaultMountApp(defaultApp + '/'); 默认加载子应用时在路由前缀后加‘/’

## 相关环境信息

- **qiankun 版本** 2.0.8
- **浏览器版本**：谷歌
- **操作系统**：win

**Comment by gongshun** [comment]
这是你子应用操作导致的无限循环，与 qiankun 无关，主应用加载 -> 注册子应用 -> 子应用加载 -> 子应用刷新页面 -> 主应用重新加载

**Comment by hql7** [comment]
到最后一步后，为何应用页面开始无线刷新呢

发自我的iPhone

**Comment by gongshun** [comment]
因为回到了第一步呀

**Comment by hql7** [comment]
@gongshun 没有循环哦，location.reload()只执行了一次。第一次启动主应用，加载a子应用，a应用location.reload()刷新。此时根据条件主应用启动注册的是 b,c,d应用，页面效果是在b应用一直刷新。可见变化是地址栏一直在 http://localhost:6750/b -> http://localhost:6750/b/ ->http://localhost:6750/b  应用b是vue3.0beta的版本，vue2.x版本无此异常

**Comment by drawwind** [comment]
另外一种引起无限循环的是，用vue webpack主应用挂载umi的时候，也会发生，好像hmr有冲突，把umi的hmr关掉，就不会了

**Comment by terevor** [comment]
我这边有类似的问题，vue应用。

表现是：route.query中有任意属性值为undefined或者number，会自动触发一次popstate，然后删除undefined的属性，number的转成string

比如：router.push({ query: { page: 1 } })，路由会自动变一次，route.query.page的值会由数字1变成字符串'1'

诡异的是，我劫持了router原型的push和replace方法，发现根本就没有执行过，而应用独立运行不会出现此现象，只有接入qiankun才会出现

**Comment by Cyberpunkerplus** [comment]
location对象是否没有隔离开，造成直接刷新主应用

**Comment by Mr-jiangzhiguo** [comment]
遇到同样的问题

**Comment by Mr-jiangzhiguo** [comment]
![image](https://user-images.githubusercontent.com/22312092/88550325-081a6800-d054-11ea-9d86-80cfd6df54c2.png)

我感觉是 主工程和子工程用的是同一个变量 `g_initWebpackHotDevClient` 导致的，循环热更新，

临时解决的办法是，把子工程的这个 `window.location.reload();` 注释掉
