### ISSUE TITLE
[BUG]: Angular9 application not working in the provided examples

### ISSUE THREAD

**Issue by cohancarpentier** [umijs/qiankun#618]
Here is the fix I found (for now):

- Bump `single-spa-angular` to `^4.1.0`
- Change the import in `main.qiankun.ts` to 
`import { singleSpaAngular, getSingleSpaExtraProviders } from 'single-spa-angular';`

and add:
`platformBrowserDynamic(getSingleSpaExtraProviders()).bootstrapModule(AppModule);`

If you'd like, I can submit a PR. Thanks for the work on Qiankun!

**Comment by kuitos** [comment]
A pr for fixing would be very appreciate😃

**Comment by cohancarpentier** [comment]
> A pr for fixing would be very appreciate😃

Well, the problem is that on unmount, I get this error:
`TypeError: can't access property "cssRules", container is null`

Coming from JSS:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/44584733/83289555-3a722b00-a1b3-11ea-89f8-506299571cda.png">

Does that ring a bell?

**Comment by Rofound** [comment]
运行后报错，angular 无法显示页面
![image](https://user-images.githubusercontent.com/26542093/86335152-b400ab80-bc80-11ea-9c28-415632742377.png)
