### ISSUE TITLE
[Bug]子应用为老项目，相对路径的图片加载问题

### ISSUE THREAD

**Issue by luffyli** [umijs/qiankun#619]
## What happens?

qiankun子应用是jquery老项目，图片地址是相对路径，加载时图片地址的域名和端口却变成了主应用的地址了。目前只能通过类似nginx转发的方式处理。

## 最小可复现仓库

qiankun仓库中的examples/purehtml目录

## 复现步骤，错误日志以及相关配置

在qiankun仓库中的examples/purehtml目录中的index.html中新增一个img标签，src地址使用相对路径图片地址，打开该子项目后可复现

## 相关环境信息

- **qiankun 版本**：2.0.11
- **浏览器版本**：83.0.4103.61
- **操作系统**：windows 10 1909

**Comment by gongshun** [comment]
@kuitos 这个问题能否通过`qiankun`注入`base`标签解决，虽然注入`base`标签是一件危险的事情。你可以把子项目部署到主项目同一个服务器，或者文件共享，Nginx转发

**Comment by gaoletian** [comment]
如果是非动态插入的，可以在start选项里自定义getTemplte里，替换相对路经为绝对路径，动态插入的可以包装一下插入元素函数，

**Comment by zhgw01** [comment]
自己写demo的时候也碰到这个类似的问题，子项目中img为```<img alt="Vue logo" src="/img/logo.82b9c7a5.png">```, 路径`/img/logo.82b9c7a5.png`会被解析到主项目的baseurl， 导致图片寻找失败

**Comment by keunone** [comment]
@luffyli 请问可以提供下解决思路吗？

**Comment by koupeng** [comment]
我的vue-cli子应用也是这个问题，本地测试没问题，npm run build之后解析的url一直是主应用的。我也设置了以下代码到顶层。

/* eslint-disable eol-last,semi,camelcase */
if (window.__POWERED_BY_QIANKUN__) {
    console.log('XXXx')
    // eslint-disable-next-line
    __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__
    console.log('__webpack_public_path__', window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__)
}

**Comment by kuitos** [comment]
解决方案：
1. 图片传 cdn，代码中直接应用 cdn 地址
2. html/css 走 webpack 编译，原理参考 https://github.com/umijs/qiankun/issues/654#issuecomment-643042892

**Comment by zdc1111** [comment]
@kuitos  第二点 中 使用webpack打包 旧项目  html中引入的css 中使用background: url('./src/images/qrcode.png')   webpack 是找不到html引入css依赖的   publicpath 设置就无效了   有啥其它好方案吗

**Comment by Leon-z** [comment]
> @kuitos 第二点 中 使用webpack打包 旧项目 html中引入的css 中使用background: url('./src/images/qrcode.png') webpack 是找不到html引入css依赖的 publicpath 设置就无效了 有啥其它好方案吗

你试试编译的时候把runtimePublicPath 设置为`false`.应该可以解决问题
