### ISSUE TITLE
浏览器兼容性问题

### ISSUE THREAD

**Issue by mengxingshike2012** [umijs/qiankun#62]
1. html-import-entry 去加载资源的时候， 搜狗浏览器 无法解析到生命周期函数， 谷歌正常
>>>  断点看了下，execScript 返回的结果是空对象， webpack已经配置umd，

2. html-import-entry  fetch issue  [cookie](https://github.com/github/fetch#sending-cookies)

**Comment by kuitos** [comment]
请遵循模板提交问题，否则您的问题会被关闭

**Comment by mengxingshike2012** [comment]
第一个问题，原因是html-import-entry这个库里面的utils里面copy了一段systemjs来判断entry模块的代码， 使用了firstGlobalProp，secondGlobalProp, 以及lastProp 来判断
·```
export function getGlobalProp() {
	let cnt = 0;
	let lastProp;
	let hasIframe = false;
	for (let p in global) {
		if (!global.hasOwnProperty(p))
			continue;

		// 遍历 iframe，检查 window 上的属性值是否是 iframe，是则跳过后面的 first 和 second 判断
		for (let i = 0; i < window.frames.length; i++) {
			const frame = window.frames[i];
			if (frame === global[p]) {
				hasIframe = true;
				break;
			}
		}
		if (!hasIframe && (cnt === 0 && p !== firstGlobalProp || cnt === 1 && p !== secondGlobalProp))
			return p;
		cnt++;
		lastProp = p;
	}
	if (lastProp !== lastGlobalProp)
		return lastProp;
}



经测试搜狗浏览器此段代码无法正常工作， 不符合期望， 故使用搜狗浏览器加载子应用报错：缺少提供声明周期方法；
