### ISSUE TITLE
qiankun2.0 当某个子项目加载失败时，切换到一个会重定向的子应用，加载状态异常

### ISSUE THREAD

**Issue by zczhangchao51** [umijs/qiankun#620]
## What happens?

使用qiankun2.0的loader来获取加载状态

`const loader = loading => render({ loading });`

如果上一个子应用加载失败，切换到一个会重定向的子应用，loading的状态会不正常

![image](https://user-images.githubusercontent.com/14327786/83329290-33364480-a2bb-11ea-8131-8ad71e704ce3.png)

## Mini Showcase Repository(REQUIRED)

稍微改动官方例子可复现

1. 在vue子应用的src/main.js中加入重定向代码

![image](https://user-images.githubusercontent.com/14327786/83329379-b3f54080-a2bb-11ea-9aea-305c482b886f.png)

`
  router.beforeEach((to, from, next) => {
    if (!to.query.test && !from.query.test) {
      to.query.test = '123';
      return next(to);
    }
    next();
  });
`
2. 只让主应用和vue子应用加载正常

3. 从加载失败的子应用切换到vue子项目即可复现

## 原因

single-spa内部有个加载应用失败重试的机制，当从一个失败的应用切换到正常的应用还会再尝试加载这个失败的应用，但是这时候正常的应用没有卸载，导致失败的子应用一直处于loading: true的状态

## Context

- **qiankun Version**: 2.0.11
- **Platform Version**: mac
- **Browser Version**: chrome

**Comment by kuitos** [comment]
single-spa 的 bug，已修复 https://github.com/single-spa/single-spa/pull/638
