### ISSUE TITLE
vue-cli下 使用electron封装软件，调试情况下qiankun正常加载页面，打包后无法访问，没有报错信息

### ISSUE THREAD

**Issue by 554027743** [umijs/qiankun#623]
vue-cli下 使用electron封装软件，调试情况下qiankun正常加载页面，打包后无法访问，没有报错信息

**Comment by kuitos** [comment]
请使用模板提交问题，否则您的问题将会被关闭

**Comment by Jane-blog** [comment]
请问你解决这个问题了吗？我也遇到了，无从下手呀

**Comment by jinbiaode** [comment]
今天遇到了  到现在没查到问题！！！！！  怎么解决的？
