### ISSUE TITLE
[Bug] 脚手架没有生产构建案例 

### ISSUE THREAD

**Issue by guojingwen** [umijs/qiankun#63]
## What happens?
 开发环境正常，生产环境下运行加载子项目报错
报错信息
![image](https://user-images.githubusercontent.com/12098305/64516228-b0cab680-d320-11e9-83a3-0b8742351e9d.png)

基座（main）我改成了vue 加了router, 只有一个子应用，也是vue  也有路由
开发模式可以正常运行，使用parcel build index.html命令打包main   和vue 
然后写了一个server.js 启动项目  
server.js 内容如下

`
const koa = require('koa')
const fs = require('fs')
const path = require('path')
const toStatic = require('koa-static')
const staticVueFiles = toStatic(path.resolve(__dirname, './../../../Documents/study/qiankun/examples/vue/dist'), {gzip: true})
const staticExampleFiles = toStatic(path.resolve(__dirname, './../../../Documents/study/qiankun/examples/main/dist'), {gzip: true})

const app = new koa()
app.use(async function (ctx, next) {
  if (ctx.req.method !== 'GET') {
    ctx.body = 'pleace check request method and request url'
    return next()
  }
  const pathname = ctx.req.url
  if (/^\/vue/.test(pathname) && path.extname(pathname)) {
    ctx.req.url = ctx.req.url.replace(/\/vue/, '')
    return await staticVueFiles.apply(this, [ctx, next])
  }
  
  if (/\.(css|js|html)/.test(pathname)) {
    return await staticExampleFiles.apply(this, [ctx, next])
  }
  let text = await new Promise((resolve, reject) => {
    fs.readFile(path.resolve(__dirname, './../../../Documents/study/qiankun/examples/main/dist/index.html'), 'utf-8', function (error, data) {
      if (error) return reject(error)
      resolve(data)
    })
  })
  ctx.body = text
  next()
})

app.listen(7000, () => {
  console.log('微服务项目 服务启动端口: 7000')
})
`

## 相关环境信息

- **Node 版本**：v12.1.0
- **操作系统**：macOS Hign Sierra 10.13.6 (17G7024)

**Comment by harrydengchao** [comment]
老兄，你解决了吗？   我是基座跳转子应用的时候，页面加载不出来，但是也不报错。

**Comment by kuitos** [comment]
提供一下可复现的仓库

**Comment by sakitam-fdd** [comment]
@guojingwen 猜测应该是 build时没有添加 global 参数，
`cross-env NODE_ENV=production parcel build index.html --global reactapp --public-url ./`，
完整实例参考一下这个[https://github.com/sakitam-gis/map-popup-useage](https://github.com/sakitam-gis/map-popup-useage)

**Comment by wusp1994** [comment]
https://github.com/wusp1994/qiankunTestByWu.git 我已构建出，vue-cli 3 为主应用和子应用构建工具的项目，且运行成功：包括主应用路由跳转控制子应用，子应用内路由跳转。

**Comment by kuitos** [comment]
参考最新 demo

**Comment by HuangZhaoPing** [comment]
mark
