### ISSUE TITLE
企业微信PC端打开网页，去加载子应用的时候报错

### ISSUE THREAD

**Issue by fyxwanan** [umijs/qiankun#631]
## What happens?

企业微信PC端打开网页，去加载子应用的时候报错
正常高版本的谷歌火狐IE等常见浏览器都没有什么问题，初步怀疑是PC企业微信内置浏览器内核太低了，有没有小伙伴遇到过，能否给个建议。

![image](https://user-images.githubusercontent.com/33709049/83592177-58150b00-a58c-11ea-9fd1-bf6092f71230.png)

**Comment by fyxwanan** [comment]
umi.js:1 Uncaught knowledgespace: Application 'knowledgespace' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in knowledgespace entry

**Comment by fyxwanan** [comment]
umi.js:1 Uncaught knowledgespace: Application 'knowledgespace' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in knowledgespace entry
图片挂了，报错就是这个，其他浏览器正常访问- -

**Comment by dbkillerf6** [comment]
https://qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

> 如果在上述步骤完成后仍有问题，通常说明是浏览器兼容性问题导致的。可以尝试 将有问题的微应用的 webpack output.library 配置成跟主应用中注册的 name 字段一致

**Comment by gaoletian** [comment]
我的企业微信项目已上线，没有有碰到你的情况，你你用用的乾坤版本是？

**Comment by fyxwanan** [comment]
> 我的企业微信项目已上线，没有有碰到你的情况，你你用用的乾坤版本是？

![image](https://user-images.githubusercontent.com/33709049/83648409-98a27200-a5e8-11ea-9169-90d23430b499.png)
`"[@umijs/plugin-qiankun](https://npmjs.com/package/@umijs/plugin-qiankun)": "^2.0.5",`
`"[umi](https://npmjs.com/package/umi)": "^3.0.5"`
应该都是最新版，就很奇怪，就连ie都能正常加载，PC微信内置浏览器就不行

**Comment by gaoletian** [comment]
我没有使用umi，引用用的乾坤版本是2.0.1，最新版本在单例模式下有bug

**Comment by kuitos** [comment]
解决方案参考 https://qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

**Comment by danluckjoet** [comment]
请问这个问题，最后解决了吗？

**Comment by danluckjoet** [comment]
我也遇到这个问题了，请问最后解决了吗？
