### ISSUE TITLE
子应用刷新404是什么情况 大佬们

### ISSUE THREAD

**Issue by zengzozo** [umijs/qiankun#632]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by hql7** [comment]
贴图，是不是用了运行时接口代理

发自我的iPhone

**Comment by millzhang** [comment]
我也遇到这种情况，我的部署目录是
- portal 基座
- app 子应用
位于同级目录下。

**Comment by lawmancs** [comment]
我也出现过404，是因为地址被其他代理匹配上了
~~~ json
devServer: {
  proxy: {
   "/app": {
      ....
    }
  }
}
~~~

这时假如我的子应用的路由地址配置成 `app-web/xxx` 时就会匹配上了代理地址，导致404，

只要把`/app`改为`/app/`就可以正常刷新了

可以参考一下，看是这问题导致的么？

**Comment by millzhang** [comment]
> 我也出现过404，是因为地址被其他代理匹配上了
> 
> ```json
> devServer: {
>   proxy: {
>    "/app": {
>       ....
>     }
>   }
> }
> ```
> 
> 这时假如我的子应用的路由地址配置成 `app-web/xxx` 时就会匹配上了代理地址，导致404，
> 
> 只要把`/app`改为`/app/`就可以正常刷新了
> 
> 可以参考一下，看是这问题导致的么？

我这边出现问题是生产环境呢 应该不是此类原因 谢谢哈

**Comment by MaxBaiWhite** [comment]
父应用的publicPath写完整的地址试试

**Comment by gemmer01** [comment]
是因为你的router的 baseUrl的问题，最新的demo我在你问我的问题上做了回复
另外说下最好history模式！

**Comment by gemmer01** [comment]
> 我也遇到这种情况，我的部署目录是
> 
> * portal 基座
> * app-front 子应用的目录名
> 
> 位于同级目录下/data/frontend/micro-front-demo。
> 
> 1. 且父子应用位于相同的域名下；
> 2. 路由采用的是hash模式
>    Nginx的配置是
> 
> ```
> server {
>    listen 81;
>   server_name localhost;
>   root /data/frontend/micro-front-demo;
>   index index.html;
>   xxxxx(其他的是一些代理)
> }
> ```
> 
> 子应用的routeBase是`/app`,
> 主应用的访问是 `http://ip:81/portal` , 成功访问到子应用`http://ip:91/app/index`
> 但是在子应用中刷新页面，404了，因为nginx中没有代理app到app-front,但如果添加该代理，会直接进入子应用，整个基座布局就不存在了，求大佬指教下！！

是因为你的router的 baseUrl的问题，最新的demo我在你问我的问题上做了回复
另外说下最好history模式！

**Comment by winterZhao** [comment]
我碰到的是开发过程中，history模式下，子应用刷新会404，然后在vue.config.js里的devServer增加了
```
historyApiFallback:{
    index:'/index.html'
  },
```

**Comment by kuitos** [comment]
see https://router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90
