### ISSUE TITLE
[Feature Request] location对象是否没有隔离

### ISSUE THREAD

**Issue by Cyberpunkerplus** [umijs/qiankun#633]
location对象是否没有隔离，造成多个子应用并行的时候抢占浏览器的location资源，能否将其隔离？

**Comment by kuitos** [comment]
不会隔离，隔离 location 就跟 iframe 没什么区别了，参考 https://qiankun.umijs.org/zh/guide#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%98%AF-iframe

**Comment by Cyberpunkerplus** [comment]
> 不会隔离，隔离 location 就跟 iframe 没什么区别了，参考 https://qiankun.umijs.org/zh/guide#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%98%AF-iframe
 对location对象隔离，又避免iframe体验问题，岂不美哉，sandbox隔离的更彻底。
