### ISSUE TITLE
子服务使用element-ui:  Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by liuzhen88** [umijs/qiankun#634]
## What happens?

主项目加载vue子项目，子项目使用element-ui。
其中子项目单独使用el-select没有问题，
但是在主项目中加载vue子项目，再使用el-select就会报错。

## Mini Showcase Repository(REQUIRED)

https://github.com/liuzhen88/qiankun-bug-report.git

## How To Reproduce

**1. git clone https://github.com/liuzhen88/qiankun-bug-report.git

**2. yarn install && npm run dev 。 启动主服务。

**3. cd vue && yarn install && npm run dev。启动vue子服务。

**4. 打开浏览器，http://localhost:9000访问主服务。 http://localhost:9001访问子服务。

**5. 主服务中，鼠标移动到select框上，点击报错。而子服务上正常。

## Context

- **qiankun Version**: 2.0.11
- **Platform Version**: mac os
- **Browser Version**: chrome

其他版本，可以在package.json中查看

**Comment by Liaoct** [comment]
我测试了下 在v2.0.13下没有这个问题 但是在开启{ strictStyleIsolation: true }时，有这个问题

**Comment by zerolidao** [comment]
start({singular: false})也会有这种情况

**Comment by mango-csl** [comment]
这个问题，主要是由于2.0.0_3 中新加的代码，劫持了document引起的
commit #427 
[代码位置](https://github.com/umijs/qiankun/blob/7d046d1b5f2c0e74e1c2fd8255f70cc434e1583a/src/sandbox/patchers/dynamicHeadAppend.ts#L163)

element 中的 popper.js，受影响取不到预期的 parent ，从而 getStyleComputedProperty 方法出错

```
    /**
     * Returns the scrolling parent of the given element
     * @function
     * @ignore
     * @argument {Element} element
     * @returns {Element} offset parent
     */
    function getScrollParent(element) {
        var parent = element.parentNode;

        if (!parent) {
            return element;
        }

        if (parent === root.document) {
            // Firefox puts the scrollTOp value on `documentElement` instead of `body`, we then check which of them is
            // greater than 0 and return the proper element
            if (root.document.body.scrollTop || root.document.body.scrollLeft) {
                return root.document.body;
            } else {
                return root.document.documentElement;
            }
        }

        // Firefox want us to check `-x` and `-y` variations as well
        if (
            ['scroll', 'auto'].indexOf(getStyleComputedProperty(parent, 'overflow')) !== -1 ||
            ['scroll', 'auto'].indexOf(getStyleComputedProperty(parent, 'overflow-x')) !== -1 ||
            ['scroll', 'auto'].indexOf(getStyleComputedProperty(parent, 'overflow-y')) !== -1
        ) {
            // If the detected scrollParent is body, we perform an additional check on its parentNode
            // in this way we'll get body if the browser is Chrome-ish, or documentElement otherwise
            // fixes issue #65
            return parent;
        }
        return getScrollParent(element.parentNode);
    }
```
可以修改子应用 proxy 中的 getComputedStyle 解决
```
  let proxy = createSandbox(name).proxy;
  proxy.getComputedStyle = function () {
    try {
      return window.getComputedStyle(...arguments);
    } catch (e){
      return {}
    }
  };
```

**Comment by Liaoct** [comment]
> // Element-ui 在使用getComputedStyle这个方法的时候，其实需要判断一下
> 可以在mount钩子函数里添加如下代码
> // @ts-ignore
>   window.getComputedStyle = (element, property) => {
>     if (!element || element.nodeType === 9) return {};
>     return getStyle(element, property);
>   };

getStyle在哪里定义的呢？

**Comment by lianer** [comment]
可以把以下代码插入到容器中，暂时来解决这个问题，但从长远来看，还是得想办法解决`递归 parentNode 会访问到沙箱外原始 document 对象的问题`

```js
var rawGetComputedStyle = window.getComputedStyle;
window.getComputedStyle = function (el) {
  if (el === document) return {'overflow': 'auto'};
  return rawGetComputedStyle(el, null);
}
Object.defineProperty(document, 'scrollLeft', {
  get () {
    return document.documentElement.scrollLeft;
  }
});
Object.defineProperty(document, 'scrollTop', {
  get () {
    return document.documentElement.scrollTop;
  }
});
```

**Comment by lmjben** [comment]
> 可以把以下代码插入到容器中，暂时来解决这个问题，但从长远来看，还是得想办法解决`递归 parentNode 会访问到沙箱外原始 document 对象的问题`
> 
> ```js
> // 解决报错问题
> var rawGetComputedStyle = window.getComputedStyle;
> window.getComputedStyle = function (el, pseudoElt) {
>   if (el === document) return {'overflow': 'auto'};
>   return rawGetComputedStyle(el, pseudoElt);
> }
> 
> // 解决定位问题
> // 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
> Object.defineProperty(document, 'scrollLeft', {
>   get () {
>     return document.documentElement.scrollLeft;
>   }
> });
> Object.defineProperty(document, 'scrollTop', {
>   get () {
>     return document.documentElement.scrollTop;
>   }
> });
> ```

这段代码加在哪个地方呢？

**Comment by lianer** [comment]
> > 可以把以下代码插入到容器中，暂时来解决这个问题，但从长远来看，还是得想办法解决`递归 parentNode 会访问到沙箱外原始 document 对象的问题`
> > ```js
> > // 解决报错问题
> > var rawGetComputedStyle = window.getComputedStyle;
> > window.getComputedStyle = function (el, pseudoElt) {
> >   if (el === document) return {'overflow': 'auto'};
> >   return rawGetComputedStyle(el, pseudoElt);
> > }
> > 
> > // 解决定位问题
> > // 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
> > Object.defineProperty(document, 'scrollLeft', {
> >   get () {
> >     return document.documentElement.scrollLeft;
> >   }
> > });
> > Object.defineProperty(document, 'scrollTop', {
> >   get () {
> >     return document.documentElement.scrollTop;
> >   }
> > });
> > ```
> 
> 这段代码加在哪个地方呢？

加在全局，使所有微应用都可以应用到

**Comment by lmjben** [comment]
上述的方案都试过，并没有生效，还有什么好的方案吗？

**Comment by yzend** [comment]
> 上述的方案都试过，并没有生效，还有什么好的方案吗？

```js
// 解决报错问题
var rawGetComputedStyle = window.getComputedStyle;
window.getComputedStyle = function (el, pseudoElt) {
  // 将判断条件更改下试试 返回的可能是DocumentFragment
  if (el.nodeType === 11) return {'overflow': 'auto'};
  return rawGetComputedStyle(el, pseudoElt);
}

// 解决定位问题
// 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
Object.defineProperty(document, 'scrollLeft', {
  get () {
    return document.documentElement.scrollLeft;
  }
});
Object.defineProperty(document, 'scrollTop', {
  get () {
    return document.documentElement.scrollTop;
  }
});
```

**Comment by lianer** [comment]
> > 上述的方案都试过，并没有生效，还有什么好的方案吗？
> 
> ```js
> // 解决报错问题
> var rawGetComputedStyle = window.getComputedStyle;
> window.getComputedStyle = function (el, pseudoElt) {
>   // 将判断条件更改下试试 返回的可能是DocumentFragment
>   if (el.nodeType === 11) return {'overflow': 'auto'};
>   return rawGetComputedStyle(el, pseudoElt);
> }
> 
> // 解决定位问题
> // 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
> Object.defineProperty(document, 'scrollLeft', {
>   get () {
>     return document.documentElement.scrollLeft;
>   }
> });
> Object.defineProperty(document, 'scrollTop', {
>   get () {
>     return document.documentElement.scrollTop;
>   }
> });
> ```

作者修复了，修改了 document 代理的实现方式，更新一下乾坤

**Comment by neu-yuyang** [comment]
> > > 上述的方案都试过，并没有生效，还有什么好的方案吗？
> > 
> > 
> > ```js
> > // 解决报错问题
> > var rawGetComputedStyle = window.getComputedStyle;
> > window.getComputedStyle = function (el, pseudoElt) {
> >   // 将判断条件更改下试试 返回的可能是DocumentFragment
> >   if (el.nodeType === 11) return {'overflow': 'auto'};
> >   return rawGetComputedStyle(el, pseudoElt);
> > }
> > 
> > // 解决定位问题
> > // 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
> > Object.defineProperty(document, 'scrollLeft', {
> >   get () {
> >     return document.documentElement.scrollLeft;
> >   }
> > });
> > Object.defineProperty(document, 'scrollTop', {
> >   get () {
> >     return document.documentElement.scrollTop;
> >   }
> > });
> > ```
> 
> 作者修复了，修改了 document 代理的实现方式，更新一下乾坤

更新了2.2.2  还是有这个问题呢

**Comment by K-walker** [comment]
哈哈，我更新到 2.3.3 还是存在这个问题，各位肿么破 😭

**Comment by xinlai3698** [comment]
哈哈，我更新到 2.3.6 还是存在这个问题，各位肿么破 😭

**Comment by Aaronlamz** [comment]
哈哈，我更新到 2.4.0 还是存在这个问题，各位肿么破 😭

**Comment by 123jiacheng123** [comment]
哈哈，我更新到 2.4.2 还是存在这个问题，各位肿么破 😭

**Comment by tengerfly** [comment]
建议重写的getComputedStyle方法写在基座里边，我原来重写的方式是写在子应用里边的，刚开始是好的，子应用更新之后，线上还是报错，本地是可以的。后来将重写的方法写在了基座里边，解决问题了。个人猜测原因：qiankun重新代理了子应用的window，getComputedStyle是window的方法，直接去修改window而不是去修改代理后的window

**Comment by lovedaan** [comment]
elementUI的select组件是可以了，没报错了，但是date-picker日期组件有新的问题，文本框获得焦点，date-picker面板会闪动然后马上消失，不知道什么原因，审查元素看date-picker元素被添加到父应用的body同层，但是即使我代理document.body的appendChild方法到子应用的容器内，还是有这个闪动问题

**Comment by lovedaan** [comment]
解决 getComputedStyle 报错，上面哥们的方法，我加多个判断就可以了
 // 解决报错问题
  let rawGetComputedStyle = window.getComputedStyle;
  window.getComputedStyle = function (el, pseudoElt) {
    if (el === document) return { overflow: "auto" };
    if (el instanceof HTMLElement) {
      return rawGetComputedStyle(el, pseudoElt);
    } else {
      return {}
    }
  };

**Comment by zhangyuhan2016** [comment]
针对 el-popover 还存在新的问题， element-ui popover 事件监听无法判断 shadow dom，会导致 open => close，无法正常展示。

提供一个简陋的解决方案：

```
<el-popover
  v-model="popShow"
  trigger="click"
>
  <p>Show on click</p>        
  <div slot="reference" >
    <button @click.stop="popShow = true">测试</button>
  </div>
</el-popover>
```

**Comment by fendo8888** [comment]
> 解决 getComputedStyle 报错，上面哥们的方法，我加多个判断就可以了 // 解决报错问题 let rawGetComputedStyle = window.getComputedStyle; window.getComputedStyle = function (el, pseudoElt) { if (el === document) return { overflow: "auto" }; if (el instanceof HTMLElement) { return rawGetComputedStyle(el, pseudoElt); } else { return {} } };

这个可用

**Comment by zhanyoulin456** [comment]
上面的解决方法试了个遍，没一个可行 vue2.6.14 element-ui 2.15.13

**Comment by anyi1998** [comment]
解决问题了，总结一下上面大佬的发言
// 解决报错问题
let rawGetComputedStyle = window.getComputedStyle;
window.getComputedStyle = function (el, pseudoElt) {
 if (el === document) return { overflow: "auto" };
 if (el instanceof HTMLElement) {
    return rawGetComputedStyle(el, pseudoElt);
 } else {
     return {}
  }
};
// 解决定位问题
// 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
Object.defineProperty(document, 'scrollLeft', {
  get () {
    return document.documentElement.scrollLeft;
  }
});
Object.defineProperty(document, 'scrollTop', {
  get () {
    return document.documentElement.scrollTop;
  }
});
一起放在父应用的入口就行，比如main.js or app.js

**Comment by jetaimeyu** [comment]
> elementUI的select组件是可以了，没报错了，但是date-picker日期组件有新的问题，文本框获得焦点，date-picker面板会闪动然后马上消失，不知道什么原因，审查元素看date-picker元素被添加到父应用的body同层，但是即使我代理document.body的appendChild方法到子应用的容器内，还是有这个闪动问题
这个问题有人知道怎么解决吗

**Comment by a13133808351** [comment]
> 子应用使用elementUI的报错，亲测以下代码有效：
> 
> ```
> function fixGetComputedStyle() {
>     // 解决getComputedStyle报错问题
>     const getStyle = window.getComputedStyle;
>     window.getComputedStyle = (element, property) => {
>         if (!element || element.nodeType === 9) return {};
>         return getStyle(element, property);
>     };
> }
> function fixPopperPosition() {
>     // 解决popper.js定位问题
>     Object.defineProperty(document, 'scrollLeft', {
>         get() {
>             return document.documentElement.scrollLeft;
>         },
>     });
>     Object.defineProperty(document, 'scrollTop', {
>         get() {
>             return document.documentElement.scrollTop;
>         },
>     });
> }
> ```
> 
> 然后在子应用需要暴露的mount函数里调用：
> 
> ```
> export async function mount(props) {
>   fixGetComputedStyle();
>   fixPopperPosition();
>   render(props);
>   registerStore(props);
> }
> ```

我是特意来赞爆你的！！！！！！感谢bro

**Comment by a13133808351** [comment]
谢谢！这个问题已解决 好像是主应用和子应用的micro-app的安装的依赖版本不同，所以报错
（如记错请见谅）



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: saltand ***@***.***&gt;
发送时间: 2024年3月13日 10:32
收件人: umijs/qiankun ***@***.***&gt;
抄送: a13133808351 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [umijs/qiankun] 子服务使用element-ui:  Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. (#634)





 
我的情况是，基座应用分发了一个弹窗组件到子应用，弹窗里套了另一个弹窗和 el-select。
 这种情况下需要把上面的 fixGetComputedStyle fixPopperPosition 写在基座的 main.js 中。

**Comment by ltf-space** [comment]
> 子应用使用elementUI的报错，亲测以下代码有效：
> 
> ```
> function fixGetComputedStyle() {
>     // 解决getComputedStyle报错问题
>     const getStyle = window.getComputedStyle;
>     window.getComputedStyle = (element, property) => {
>         if (!element || element.nodeType === 9) return {};
>         return getStyle(element, property);
>     };
> }
> function fixPopperPosition() {
>     // 解决popper.js定位问题
>     Object.defineProperty(document, 'scrollLeft', {
>         get() {
>             return document.documentElement.scrollLeft;
>         },
>     });
>     Object.defineProperty(document, 'scrollTop', {
>         get() {
>             return document.documentElement.scrollTop;
>         },
>     });
> }
> ```
> 
> 然后在子应用需要暴露的mount函数里调用：
> 
> ```
> export async function mount(props) {
>   fixGetComputedStyle();
>   fixPopperPosition();
>   render(props);
>   registerStore(props);
> }
> ```

我这样写 级联选择器可用，日期组件还是闪一下 消失 子应用elemetui2.15.13

**Comment by a13133808351** [comment]
谢谢您回复


后面发现是父子容器的qiankun版本不一致
调整成一样的版本号 就好了🥲


------------------ 原始邮件 ------------------
发件人: ltf ***@***.***&gt;
发送时间: 2024年11月27日 10:03
收件人: umijs/qiankun ***@***.***&gt;
抄送: a13133808351 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [umijs/qiankun] 子服务使用element-ui:  Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. (#634)
