### ISSUE TITLE
大佬们，请教一下子应用中使用axios异步请求数据会报Maximum call stack size exceeded

### ISSUE THREAD

**Issue by congceng999** [umijs/qiankun#635]
主应用加载子应用时界面能正常显示(主子应用都是vue),就是异步请求会报Maximum call stack size exceeded,但是子应用单独运行是没问题，请问这是什么原因导致的呢？

子应用webpack配置
`const packageName = require('../package.json').name`
`output: {`
    `  path: config.build.assetsRoot,`
   `   filename: '[name].js',`
    `  library: `${packageName}`,`
    `  libraryTarget: 'umd',`
    `  jsonpFunction: `webpackJsonp_${packageName}`,`
    `  publicPath:`
      `  process.env.NODE_ENV === 'production'`
        `  ? config.build.assetsPublicPath`
        `  : config.dev.assetsPublicPath`
  `  },`
## 相关环境信息

- **qiankun 版本**：v2.0.11
- **浏览器版本**：chrome 83.0.4103.61
- **操作系统**：macOs 10.14.6

**Comment by kuitos** [comment]
closed via inactive

**Comment by UsagiLan** [comment]
请问这个问题现在有解决办法了吗？我也遇到了同样的问题

**Comment by 1422322974** [comment]
如果是用的vite 建议使用[vite-plugin-legacy-qiankun](https://github.com/lishaobos/vite-plugin-legacy-qiankun) 这个插件试试。
