### ISSUE TITLE
styled-components子应用rebuild时样式混乱

### ISSUE THREAD

**Issue by chenqiangmingyu** [umijs/qiankun#637]
## What happens?

子应用采用styled-components样式控制时，切出切回，子应用rebuild，样式异常

## How To Reproduce

1. 正常启动主应用，启动styled-components controlled 子应用
2. 切离子应用，再重新切回子应用
3. 样式混乱

期望正常样式

## Context

- **qiankun: 2.0.12**:
- **styled-components: 4.4.1**:
- **Chrome:  83.0.4103.61**:

**Comment by chenqiangmingyu** [comment]
styled-components#GroupedTag.js插入cssRule是正序插入
`let ruleIndex = this.indexOfGroup(group + 1);
    for (let i = 0, l = rules.length; i < l; i++) {
      if (this.tag.insertRule(ruleIndex, rules[i])) {
        this.groupSizes[group]++;
        ruleIndex++;
      }
    }`

qiankun是逆序插入
`
for (var i = 0; i < cssRules.length; i++) {
       var cssRule = cssRules[i];
       stylesheetElement.sheet.insertRule(cssRule.cssText);
}
`
样式先后顺序异常导致rule继承混乱，stylesheetElement.sheet.insertRule(cssRule.cssText, i); 确保rule 按原顺序重建

**Comment by howel52** [comment]
提供下最小可复现仓库 reopen

**Comment by easyzeng** [comment]
想问问这个issue有没有进展，我们的项目也碰到了这个问题，不是很稳定，要重复几次切换子应用才可以复现

**Comment by fxh615** [comment]
纠结了，qiankun  和  styled-components  不能一起用呀

**Comment by fxh615** [comment]
@chenqiangmingyu 问题解决了么

**Comment by CareyToboo** [comment]
我这边也有相同问题，只要切换子应用 styled component 样式就丢失了。

**Comment by easyzeng** [comment]
我最近仔细看了一下这个额问题，@chenqiangmingyu 发现的问题是正确的，在我们内部的app里面，第一次加载css正确，第二次加载styled-component生成的script就被reveser过来了，第三次加载，因为是reverse的reverse, 所以又正常了。

目前没有发现特别好的解决办法。

**Comment by CareyToboo** [comment]
我这边具体情况是， createGlobaleStyle`` 样式，页面刷新后初次加载是正常的，切换后丢失了，不知道具体原因。目前决方案是，关闭 sandbox 参数。不隔离子应用样式，貌似可以暂时缓解这个问题，不然直接没法用。

解决办法后边再找找看，也要需要初始化一个最基本的 repo，浮现这个问题。

**Comment by easyzeng** [comment]
## How to Reproduce

Clone repository https://github.com/easyzeng/qiankun/commit/d9b741671e5823604f2866f501e18cc7f09807ae

```
$ yarn install
$ yarn examples:install
$ yarn examples:start
```

To reproduce the issue
1. Start with React 16 App (Should see three red buttons)
2. Navigate to any other micro-frontend app
3. Mount React16 App again (Button turns into yellow)

**Comment by ruoruoji** [comment]
发现开发环境是正常的，线上环境会出现这种情况。
线上
![image](https://user-images.githubusercontent.com/30526662/108958405-e5196a80-76ad-11eb-9354-3c3d45787e1e.png)
开发
![image](https://user-images.githubusercontent.com/30526662/108958437-f5c9e080-76ad-11eb-9780-78e5cbece244.png)

**Comment by NexxLuo** [comment]
我的情况是开发环境错误，线上环境正常。用的umi-plugin-qiankun。`sandbox:false`

**Comment by liuwei1025** [comment]
> 发现开发环境是正常的，线上环境会出现这种情况。 线上 ![image](https://user-images.githubusercontent.com/30526662/108958536-15610900-76ae-11eb-8846-67cb4ae3a280.png) 开发 ![image](https://user-images.githubusercontent.com/30526662/108958437-f5c9e080-76ad-11eb-9780-78e5cbece244.png)

可以参照这个问题解决 target属性指向父容器就可以了

**Comment by dleged** [comment]
> 想问问这个issue有没有进展，我们的项目也碰到了这个问题，不是很稳定，要重复几次切换子应用才可以复现
style
[<StyleSheetManager disableCSSOMInjection={true}> //你的应用代码 ...... <StyleSheetManager/>](https://github.com/umijs/qiankun/issues/1426#issuecomment-989593513) 这样可以解
