### ISSUE TITLE
[Bug]registerMicroApps和loadMicroApp是否可以共存

### ISSUE THREAD

**Issue by guoqn** [umijs/qiankun#638]
## What happens?
* registerMicroApps 和 loadMicroApp 共存的情况下，就会报错，请问这两种方式是否可以共存？

## 最小可复现仓库
就使用仓库的demo

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/10399955/83739866-b8897280-a688-11ea-80bb-2527638a4558.png)

![image](https://user-images.githubusercontent.com/10399955/83740277-33528d80-a689-11ea-87f9-37c19c392839.png)

## 相关环境信息

- **qiankun 版本**
最新版
- **浏览器版本**：
chrome
- **操作系统**：
macOS

**Comment by dbkillerf6** [comment]
不要抢占 container 就行
