### ISSUE TITLE
[Bug]vue-cli3生产部署时发现的问题,并附带临时解决方法

### ISSUE THREAD

**Issue by fenngding** [umijs/qiankun#64]
## What happens?

对于vue的微服务部署,vue-cli3在打包构建时会默认去除index.html内所有属性的引号(直接npm run serve无此问题),
而qianqun引用的import-html-entry库的scripts和css的提取规则均是以引号作为正则的一部分来提取的.直接导致无法获取到scripts和css.然后整个微服务的切入看起来会卡在 before load执行之后(实际是因为没有脚本可以执行)

## 最小可复现仓库

这个不需要仓库了,随便打包一下就能得到.

临时的解决办法:
chainWebpack: config => {
    config.plugin("html").tap(args => {
      args[0].minify = false;
      return args;
    });
}

这个问题一度让我怀疑人生,只能一层层的debugqer,最终才发现问题所在.
为了让有更多的人顺利的使用qianqun这套不错的微服务解决方法,
建议还是qiankun对import-html-entry的匹配规则做一个兼容.或者给用户们提供各个技术栈对应的部署配置.

**Comment by guojingwen** [comment]
@fenngding 老哥请你吃个饭，也解决了我的问题

**Comment by yangangzhang** [comment]
> ## What happens?
> 对于vue的微服务部署,vue-cli3在打包构建时会默认去除index.html内所有属性的引号(直接npm run serve无此问题),
> 而qianqun引用的import-html-entry库的scripts和css的提取规则均是以引号作为正则的一部分来提取的.直接导致无法获取到scripts和css.然后整个微服务的切入看起来会卡在 before load执行之后(实际是因为没有脚本可以执行)
> 
> ## 最小可复现仓库
> 这个不需要仓库了,随便打包一下就能得到.
> 
> 临时的解决办法:
> chainWebpack: config => {
> config.plugin("html").tap(args => {
> args[0].minify = false;
> return args;
> });
> }
> 
> 这个问题一度让我怀疑人生,只能一层层的debugqer,最终才发现问题所在.
> 为了让有更多的人顺利的使用qianqun这套不错的微服务解决方法,
> 建议还是qiankun对import-html-entry的匹配规则做一个兼容.或者给用户们提供各个技术栈对应的部署配置.

主项目和子项目都是vue-cli3，那么都需要加这个配置吗？

**Comment by yangangzhang** [comment]
> @fenngding 老哥请你吃个饭，也解决了我的问题

您好，您的部署成功了吗？主项目和子项目都是vue-cli3?

**Comment by fenngding** [comment]
只有子服务需要这个设置,这个设置的目的是避免主服务在使用import-html-entry无法正确的获取到scripts和css

**Comment by fenngding** [comment]
> > @fenngding 老哥请你吃个饭，也解决了我的问题
> 
> 您好，您的部署成功了吗？主项目和子项目都是vue-cli3?

只有子服务需要这个设置,这个设置的目的是避免主服务在使用import-html-entry无法正确的获取到scripts和css

**Comment by yangangzhang** [comment]
> > > @fenngding 老哥请你吃个饭，也解决了我的问题
> > 
> > 
> > 您好，您的部署成功了吗？主项目和子项目都是vue-cli3?
> 
> 只有子服务需要这个设置,这个设置的目的是避免主服务在使用import-html-entry无法正确的获取到scripts和css

明白了，谢了大哥

**Comment by guojingwen** [comment]
> > @fenngding 老哥请你吃个饭，也解决了我的问题
> 
> 您好，您的部署成功了吗？主项目和子项目都是vue-cli3?

demo  通了还在研究

**Comment by Auroraan** [comment]
> > > @fenngding 老哥请你吃个饭，也解决了我的问题
> > 
> > 
> > 您好，您的部署成功了吗？主项目和子项目都是vue-cli3?
> 
> demo 通了还在研究

可以分享一下 demo 的git地址吗？

**Comment by djkloop** [comment]
> > > @fenngding 老哥请你吃个饭，也解决了我的问题
> > 
> > 
> > 您好，您的部署成功了吗？主项目和子项目都是vue-cli3?
> 
> demo 通了还在研究

老哥你的那个其他子项目和example里面的vue写的是一样的吗？  我这个地方一直报你那个错
Application 'vue app main' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in vue app

**Comment by wusp1994** [comment]
通过看你们的提问和回答，跑通了我的微前端解决方案qiankun测试用例，主应用及子应用均为vue-cli 3 构建 https://github.com/wusp1994/qiankunTestByWu.git

**Comment by kuitos** [comment]
@wusp1994  直接提个 pr 到 example？

**Comment by wusp1994** [comment]
@kuitos 有什么要求吗？主应用和子应用都要改

**Comment by kuitos** [comment]
@wusp1994 pr 先提上来一起看下:laughing:

**Comment by GabrielchenCN** [comment]
我现在有个类似的问题啊，是由这个引起的吗 #873
