### ISSUE TITLE
insertBefore未重写异常

### ISSUE THREAD

**Issue by Joshwoooooooooooooooooooooooooooooooong** [umijs/qiankun#642]
## What happens?

现有A、B、C三个应用，这三个应用共同引用了同一套UI组件（样式都是通过insertBefore插入的），当我在A、B两个应用来回切换时，因为卸载沙盒会触发副作用重建，所以patchCount会变为负数。这时候我的切换到C，因为patchCount不为0的原因，所以他不会重写insertBefore方法，导致我的样式插入到了appName为A或B应用的节点中，导致`loader.js:35 Uncaught (in promise) Error: [qiankun] Wrapper element for appNameB with instance appNameB_1591472711221 is not existed!`

## 最小可复现仓库

描述已经很清晰了，原因也找到了

## 复现步骤，错误日志以及相关配置

```js
loader.js:35 Uncaught (in promise) Error: [qiankun] Wrapper element for appNameB with instance appNameB_1591472711221 is not existed!
    at assertElementExist (loader.js:35)
    at eval (loader.js:108)
    at HTMLHeadElement.insertBefore (dynamicHeadAppend.js:227)
    at insertStyleElement (VM231290 addStyles.js:177)
    at createStyleElement (VM231290 addStyles.js:219)
    at addStyle (VM231290 addStyles.js:296)
    at addStylesToDom (VM231290 addStyles.js:139)
    at module.exports (VM231290 addStyles.js:90)
    at eval (VM231492 _transform_condition.js:16)
```

## 相关环境信息

- **qiankun 版本**： v2.0.12
- **浏览器版本**： 83.0.4103.97（正式版本） （64 位）
- **操作系统**：windows 10

**Comment by kuitos** [comment]
没看明白卸载沙箱为啥会触发副作用重建，以及 patchCount 为啥会变成负数

提供一个可复现仓库吧

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
> 没看明白卸载沙箱为啥会触发副作用重建，以及 patchCount 为啥会变成负数
> 
> 提供一个可复现仓库吧

我没法打印patchCount出来，你在dynamicHeadAppend.ts:358行插入`console.log(patchCount)`，然后在AB应用间来回切换两次，就能重现patchCount为负数的场景了

**Comment by Joshwoooooooooooooooooooooooooooooooong** [comment]
> 没看明白卸载沙箱为啥会触发副作用重建，以及 patchCount 为啥会变成负数
> 
> 提供一个可复现仓库吧

卸载沙箱触发副作用重建这块，是我看错了，是触发free

**Comment by shopnb1** [comment]
我想知道，你如何解决这个问题的？我现在也有你这样的问题
