### ISSUE TITLE
提问：关于资源预加载问题 

### ISSUE THREAD

**Issue by netherashura** [umijs/qiankun#644]
请问，qiankun指南-介绍-特性 里面提到了资源预加载，请问是否提供了手动预加载的方法，
例如加载主项目 的时候 ，加载子项目A和子项目B，

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/84020324-3a450d00-a9b5-11ea-811c-f900d1b8fa36.png)
https://qiankun.umijs.org/zh/api#startopts
