### ISSUE TITLE
qiankun对于后端请求跨域传递cookie是如何处理的？

### ISSUE THREAD

**Issue by shinji3887** [umijs/qiankun#646]
传统做法是加一层nginx反向代理，所有的后端请求都先经过nginx再到后端服务
乾坤里面应该如何去做？还是要加反向代理吗

**Comment by kuitos** [comment]
复写 fetch，开启 `credentials: 'include'`
![image](https://user-images.githubusercontent.com/5206843/84222598-90779480-ab0a-11ea-90ef-1c8db7750897.png)
https://qiankun.umijs.org/zh/api#startopts
