### ISSUE TITLE
[Bug]挂载节点放在router-view以及路由下，就会抛出找不到挂载点，有没有间接实现方式

### ISSUE THREAD

**Issue by xianzhiyun** [umijs/qiankun#647]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
vue项目
如果挂载节点放在router-view以及路由下，就会抛出找不到挂载点；
但是我想保持和子应用路由一直成绩关系，有没有好建议

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
`router-view` 并不是一个真实的节点，首先你得匹配到这个路由，才会加载这个路由的内容。如果你非要这样做，建议你在这个路由页面的 `mounted` 周期注册 `qiankun` 的子项目并启动。

**Comment by dbkillerf6** [comment]
在路由页 mounted 里用 loadMicroApp

**Comment by kuitos** [comment]
异步导致的吧，微应用启动时路由的页面还没有被装载

上面的回复给了答案，在路由页 mounted 周期调用 loadMicroApp 加载应用即可

如果不能解决你的问题，请提供可复现仓库并 reopen issue
