### ISSUE TITLE
请问，使用 cdn 的形式引入 运行时 会有什么局限性吗

### ISSUE THREAD

**Issue by GreatAuk** [umijs/qiankun#649]
主应用和子应用都是基于 vue 的，所以主应用和子应用的 vue、vue-router 、vuex、element-ui 这些公共依赖都是使用 cdn 的形式引入,再配置 `externals`，这样能够通过浏览器缓存来优化。
```
// 主应用
<script src="url/libs/vue/2.6.11/vue.js"></script>
```
```
// 子应用
<script src="url/libs/vue/2.6.11/vue.js"></script>
```

**Comment by kuitos** [comment]
没有限制

建议你直接跑个项目试一下

**Comment by yujun96** [comment]
> 没有限制
> 
> 建议你直接跑个项目试一下


当子应用的cdn中有相对地址。祝主应用加载的时候会出现404

**Comment by wangcheng007** [comment]
> > 没有限制
> > 建议你直接跑个项目试一下
> 
> 当子应用的cdn中有相对地址。祝主应用加载的时候会出现404

2022.08.02 still
