### ISSUE TITLE
路由同时激活多应用，有应用died

### ISSUE THREAD

**Issue by wang-qiqi** [umijs/qiankun#65]
## 代码 可修改example>main>index.js

> 
`function genActiveRule(routerPrefix) {
  if (typeof routerPrefix === "string") {
    return location => location.pathname.startsWith(routerPrefix);
  }

  return location => routerPrefix.includes(location.pathname);
}

render({ loading: true });

registerMicroApps(
  [
    {
      name: "react app",
      entry: "//localhost:7100",
      render,
      activeRule: genActiveRule("/react")
    },

    {
      name: "react15 app",
      entry: "//localhost:7102",
      render,
      activeRule: genActiveRule(["/react15", "/react"])
    },
    {
      name: "vue app",
      entry: "//localhost:7101",
      render,
      activeRule: genActiveRule("/vue")
    }
  ],
  {
    beforeLoad: [
      app => {
        console.log("before load", app);
      }
    ],
    beforeMount: [
      app => {
        console.log("before mount", app);
      }
    ],
    afterUnmount: [
      app => {
        console.log("after unload", app);
      }
    ]
  }
);`

## 如何重现
**Steps to reproduce the behavior:**
1.可修改example>main>index.js
2.按readme运行即可；

**Expected behavior**
`1.会有如下报错`
`app-errors.js:9 Uncaught react app: Application 'react app' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.`
2.
`app-errors.js:9 Uncaught react app: Application 'react app' died in status SKIP_BECAUSE_BROKEN: Target container is not a DOM element.`
## Context

- **Node Version**:v8.16.0
- **Platform**:mac os

**Comment by wang-qiqi** [comment]
`/**
 * @author Kuitos
 * @since 2019-05-16
 */

import React from "react";
import ReactDOM from "react-dom";
import { runDefaultMountEffects } from "../../esm/effects";
import { registerMicroApps, start } from "../../esm/index";
import Framework from "./Framework";

function render({ appContent, loading }) {
  const container = document.getElementById("container");
  ReactDOM.render(
    <Framework loading={loading} content={appContent} />,
    container
  );
}

function genActiveRule(routerPrefix) {
  if (typeof routerPrefix === "string") {
    return location => location.pathname.startsWith(routerPrefix);
  }

  return location => routerPrefix.includes(location.pathname);
}

render({ loading: true });

registerMicroApps(
  [
    {
      name: "react app",
      entry: "//localhost:7100",
      render,
      activeRule: genActiveRule("/react")
    },

    {
      name: "react15 app",
      entry: "//localhost:7102",
      render,
      activeRule: genActiveRule(["/react15", "/react"])
    },
    {
      name: "vue app",
      entry: "//localhost:7101",
      render,
      activeRule: genActiveRule("/vue")
    }
  ],
  {
    beforeLoad: [
      app => {
        console.log("before load", app);
      }
    ],
    beforeMount: [
      app => {
        console.log("before mount", app);
      }
    ],
    afterUnmount: [
      app => {
        console.log("after unload", app);
      }
    ]
  }
);

runDefaultMountEffects("/react");

start();
`模板代码不全，可参考以下部分

**Comment by kuitos** [comment]
你这个方式会导致多个应用尝试挂载到同一个dom节点上，自然就报错了

**Comment by kuitos** [comment]
改下render方法，把不同的应用挂载到不同的节点就没问题了

**Comment by wang-qiqi** [comment]
解决了，非常感谢！
