### ISSUE TITLE
是否可以通过子应用的路由获取到子应用的页面对象

### ISSUE THREAD

**Issue by JiangJingxuan** [umijs/qiankun#650]
## What happens?
有这样一个场景
宿主应用 master  里面有一个页面/master/list
子应用   App1  里面有一个页面/app1/detail

master的list页面上的新增按钮,点击后会打开一个Modal框(页面路由不会发生变化),我想在这个Modal框里加载App1的detail页面,请问基于qiankun可以实现这个操作吗?

## 相关环境信息
项目是基于umi3搭建的用的qiankun插件

**Comment by gongshun** [comment]
给你提供一个思路，在注册子项目时，通过  `props`  将父项目的实例化`Vuex` 传过去，然后子项目的`mounted`生命周期将你的 `detail ` 组件传给 `Vuex` ，这样父项目就可以拿到这个组件了

**Comment by dbkillerf6** [comment]
```
export async funtion mount(props) {
  if (props.renderType === 'modal_detail') {
    // 需要渲染 detail
    ReactDom.render(<Detail>, props.container.querySelector('#root'))
  } else {
    // 现在的渲染逻辑
  }
}
```

**Comment by JiangJingxuan** [comment]
> ```ts
> export async funtion mount(props) {
>   if (props.renderType === 'modal_detail') {
>     // 需要渲染 detail
>     ReactDom.render(<Detail />, props.container.querySelector('#root'))
>   } else {
>     // 现在的渲染逻辑
>   }
> }
> ```
> 
> 主应用的 Modal 用 loadMicroApp 加载就行，传 props 的时候把 renderType 带上

哦哦   我尝试下
