### ISSUE TITLE
vuecli4生成的主应用和微应用,主应用加载微应用时报错

### ISSUE THREAD

**Issue by maihuochai** [umijs/qiankun#651]
## 描述

vuecli4生成的[主应用](https://github.com/maihuochai/root-qiankun.git)和[微应用](https://github.com/maihuochai/goods-qiankun.git),主应用加载微应用时报错如下：
`application 'goods-qiankun' died in status LOADING_SOURCE_CODE: [qiankun] Wrapper element for goods-qiankun with instance goods-qiankun_1591856402475 is not existed!`
![image](https://user-images.githubusercontent.com/28753640/84362911-8afc7600-ac00-11ea-903b-7835f66b622a.png)

## 最小可复现仓库
root（[https://github.com/maihuochai/root-qiankun.git](https://github.com/maihuochai/root-qiankun.git)）
goods([https://github.com/maihuochai/goods-qiankun.git](https://github.com/maihuochai/goods-qiankun.git))

## 复现步骤，错误日志以及相关配置
1.下载项目（root、goods）
2.运行root
3.运行goods

## 相关环境信息

- **qiankun 版本**^2.0.13
- **浏览器版本**：谷歌浏览器开发者版85.0.4164.4
- **操作系统**：windows10

**Comment by dbkillerf6** [comment]
https://qiankun.umijs.org/zh/api/#%E5%9F%BA%E4%BA%8E%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE

**Comment by maihuochai** [comment]
感谢大佬，是我太菜了，没看文档

**Comment by shuyanzi** [comment]
> 感谢大佬，是我太菜了，没看文档

是什么问题呢？

**Comment by maihuochai** [comment]
> > 感谢大佬，是我太菜了，没看文档
> 
> 是什么问题呢？

是看别人的教程中版本和当前版本不一致
教程中是main这么写的：
`import Vue from 'vue'
import App from './App.vue'
import router from './router'
import { registerMicroApps, start } from 'qiankun';
Vue.config.productionTip = false
let app = null;
function render({ appContent, loading }) {
  if (!app) {
    app = new Vue({
      el: '#container',
      router,
      data() {
        return {
          content: appContent,
          loading,
        };
      },
      render(h){
        return h(App, {
          props: {
            content: this.content,
            loading: this.loading,
          },
        })
      } 
    });
  } else {
    app.content = appContent;
    app.loading = loading;
  }
}
function initApp() {
  render({ appContent: '', loading: false });
}
initApp();
function genActiveRule(routerPrefix) {
  return location => location.pathname.startsWith(routerPrefix);
}
registerMicroApps([
  { 
    name: 'app-vue-hash',
    entry: 'http://localhost:80', 
    render, 
    activeRule: genActiveRule('/app-vue-hash')
  },
  { 
    name: 'app-vue-history', 
    entry: 'http://localhost:1314',
    render, 
    activeRule: genActiveRule('/app-vue-history') 
  },
]);
start();
`
而官方文档中推荐这么写：
`import { registerMicroApps } from 'qiankun';

registerMicroApps(
  [
    {
      name: 'app1',
      entry: '//localhost:8080',
      container: '#container',
      activeRule: '/react',
      props: {
        name: 'kuitos',
      }
    }
  ],
  {
    beforeLoad: app => console.log('before load', app.name),
    beforeMount: [
      app => console.log('before mount', app.name),
    ],
  },
);
`

别人教程中指定render函数，而官方文档推荐指定容器选择器，按照官方推荐的写就不会报这个错
