### ISSUE TITLE
qiankun中父应用中加载子应用的问题

### ISSUE THREAD

**Issue by shinji3887** [umijs/qiankun#655]
[使用iview-admin作为后台管理端（基于vue）](https://github.com/iview/iview-admin)
<img width="1028" alt="截屏2020-06-1123 45 24" src="https://user-images.githubusercontent.com/38430452/84407717-c8cbbf80-ac3d-11ea-9767-3383f23d35ed.png">
基本布局如上，想实现点击左面菜单，右面区域加载子应用的效果
在主页面main.vue 的配置如下：
定义显示子应用的容器appContainer：
<img width="800" alt="截屏2020-06-1123 48 45" src="https://user-images.githubusercontent.com/38430452/84408049-3e379000-ac3e-11ea-9c1a-bab97e205b05.png">
数据配置：
<img width="804" alt="截屏2020-06-1123 49 06" src="https://user-images.githubusercontent.com/38430452/84408064-4394da80-ac3e-11ea-94a3-c80e05d626eb.png">
定义qiankun启动函数：
<img width="768" alt="截屏2020-06-1123 49 19" src="https://user-images.githubusercontent.com/38430452/84408079-47c0f800-ac3e-11ea-9bef-d68ed04b7498.png">
配置完以后点击菜单，可以路由，但是是页面整体跳转到了子应用的vue页面，而不是在主应用的框架内，报错如下：
<img width="1279" alt="截屏2020-06-1123 51 48" src="https://user-images.githubusercontent.com/38430452/84408316-9078b100-ac3e-11ea-9dfa-525ae7953bde.png">
从报错信息看，似乎是因为整体跳转到了子应用页面，找不到appContainer容器报的错，那么问题是为什么会整体跳转，而不在主应用的框架内跳转？

**Comment by gongshun** [comment]
子应用的根id不要叫`#app`，子应用的`index.html`中`<div id="app"></div>`改一下，还有入口文件`main.js`：
```
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
```

**Comment by shinji3887** [comment]
> 子应用的根id不要叫`#app`，子应用的`index.html`中`<div id="app"></div>`改一下，还有入口文件`main.js`：
> 
> ```
> new Vue({
>   router,
>   store,
>   render: h => h(App)
> }).$mount("#app");
> ```

改了根id以后可以了，非常感谢！
