### ISSUE TITLE
antPro为子应用， 打包为静态网页，引用时异步加载的js引用地址不对

### ISSUE THREAD

**Issue by ailonghun** [umijs/qiankun#659]
![image](https://user-images.githubusercontent.com/45844357/84481929-6fa96d80-acc9-11ea-89c5-7daf463820ef.png)

**Comment by ailonghun** [comment]
只要没有在入口  index.html文件中引用，引用地址就不对

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404%EF%BC%9F
