### ISSUE TITLE
quankun 子应用（vue build之后），运行不了，报错无法识别生命周期钩子[qiankun] You need to export lifecycle functions

### ISSUE THREAD

**Issue by xugongyang** [umijs/qiankun#662]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by eynol** [comment]
我记得官方文档里 和别人的issue里已经有解答了。善用搜索。 umd模块 entry名称属性 导出生命周期

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
