### ISSUE TITLE
请问 eggjs 下的视图能作为 quankun 的子应用来用吗

### ISSUE THREAD

**Issue by xugongyang** [umijs/qiankun#663]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
对于 qiankun 而言，entry 只要是可访问的能返回 html 内容的 url 就行。
just try it
