### ISSUE TITLE
主应用加载微应用时，微应用的资源请求域名变成主应用域名

### ISSUE THREAD

**Issue by hujiangyun** [umijs/qiankun#664]
## What happens?

![3841592047316_ pic](https://user-images.githubusercontent.com/28855505/84567501-ac4d9580-adab-11ea-9d9a-d62eaac30e77.jpg)
![251592046699_ pic](https://user-images.githubusercontent.com/28855505/84567506-b8395780-adab-11ea-8c31-a8f2d5eedd56.jpg)
![231592046667_ pic](https://user-images.githubusercontent.com/28855505/84567522-ca1afa80-adab-11ea-932e-f435e366519b.jpg)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: 2.0.13
- **Platform Version**: vue 2.6 vue-cli3.0
- **Browser Version**: chrome 83.0.4103.97

**Comment by hujiangyun** [comment]
第一张图片是微应用的登录页面

**Comment by hujiangyun** [comment]
第一张图是微应用的地址，第二张图是进入微应用之后请求图片资源，第三张是微应用请求后端，希望大佬能帮忙解决一下，谢谢。

**Comment by poorli** [comment]
> 第一张图是微应用的地址，第二张图是进入微应用之后请求图片资源，第三张是微应用请求后端，希望大佬能帮忙解决一下，谢谢。

(参考官网 FQA：为什么微应用加载的资源会 404？)[https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404]

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404
