### ISSUE TITLE
CDN资源应如何处理？

### ISSUE THREAD

**Issue by ringgoyao** [umijs/qiankun#666]
情景：子应用下加载了阿里的iconfont 资源
在App.vue
@import 'https://at.alicdn.com/t/font_1727417_s81gcan0qvs.css';

主应用查看时，可以看到资源已加载成功，但是没有显示出来icon

![image](https://user-images.githubusercontent.com/5906943/84636564-484fdc00-af27-11ea-86f5-e4537f909dec.png)

通过查询资料，得知可以加iconfont相关文件放到本地处理，如果希望通过用cdn的方式加载有没有办法解决?

**Comment by kuitos** [comment]
请提供可复现仓库，否则您的 issue 将被关闭

**Comment by ringgoyao** [comment]
sandbox: { strictStyleIsolation: false }  跟此配置有关系

**Comment by 535601882** [comment]
我也遇到了子应用使用<link href="//at.alicdn.com/t/font_****.css"/>加载阿里的iconfont 图标不被显示的问题。请问有解决方案吗？
