### ISSUE TITLE
使用loadMicroApp手动加载应用后怎么保持多个子应用同时激活

### ISSUE THREAD

**Issue by weisiqian** [umijs/qiankun#669]
## Background

公司业务场景需要支持在同一页面同时保持多个子应用激活，搭建框架时我通过loadMicroApp加载所有的子应用，没有使用registerMicroApps注册，也没有使用start启动应用，当我设置activeRule为相同的路由时发现同一时间只有一个子应用是被激活的。所以我想问下使用loadMicroApp手动加载应用后怎么同时保持多个子应用激活。

## Proposal

使用loadMicroApp手动加载应用，保持多个子应用同时激活

## Additional context

无

**Comment by kuitos** [comment]
loadMicroApp 是手动加载应用的方式，mount unmout 都是由你程序自主控制的，同一时间需要 mount 几个应用也可以自己控制

**Comment by bylb1988** [comment]
> loadMicroApp 是手动加载应用的方式，mount unmout 都是由你程序自主控制的，同一时间需要 mount 几个应用也可以自己控制

但是如果路由切换了 手动挂载的dom还在 但页面元素就没有了，这个应该怎么解决？

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/361
