### ISSUE TITLE
按需异步加载的文件出错

### ISSUE THREAD

**Issue by ChengKIKI** [umijs/qiankun#673]
## What happens?

从主应用打开时子应用的文件按需加载，出错。子应用单独打开可以正常运行。

报错信息：Loading chunk 3 failed.  at HTMLScriptElement.onScriptComplete

![image](https://github.com/ChengKIKI/mic/blob/master/error.png)
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

[地址](https://github.com/ChengKIKI/mic)

## How To Reproduce

cd mic

yarn install

yarn mic:install

yarn mic:start

http://localhost:7099

## Context

- **qiankun ^2.0.2**:
- **chrome  v83.0.4103.97**:

**Comment by kuitos** [comment]
1. qiankun 升级到最新版本
2. 因为你的 angularjs 子应用配置的路径规则是 `/angularjsois`，但是子应用进入后立即跳转到一个其他的路径下，导致子应用被卸载，进而导致异步加载的 js 报错
https://github.com/ChengKIKI/mic/blob/master/angularjsois/src/app/router/router.config.js#L179

可以将子应用的路由设置  base 为 `/angularjsois`，确保子应用 url 的变更都在同一个 base 下
