### ISSUE TITLE
咨询下使用qiankun如何在一个的页面的某一块嵌入子应用？

### ISSUE THREAD

**Issue by YFFisker** [umijs/qiankun#677]
## Background
基座工程使用VUE，想在一个dashboard页面中的某一块嵌入一张子应用界面，这个如何配置呢？使用loadMicroApp手动加载的方式？如果可以的话麻烦提供下简单的示例代码，谢谢。

**Comment by kuitos** [comment]
示例代码文档里提供了 https://qiankun.umijs.org/zh/api#loadmicroappapp-configuration

或者看 example https://github.com/umijs/qiankun/blob/master/examples/main/multiple.js
