### ISSUE TITLE
examples 下angular9的demo报错

### ISSUE THREAD

**Issue by codingzhou** [umijs/qiankun#678]
最新master分支下的代码, 按照文档执行
yarn install
yarn examples:install
yarn examples:start
打开localhost:7099, 点击angular路由, 报错, 如截图
![image](https://user-images.githubusercontent.com/14120629/85015351-67a26f80-b19a-11ea-9a1e-2346a7d9ce99.png)

**Comment by hellojayjay** [comment]
我还有另外一个报错
![TIM截图20200701141308](https://user-images.githubusercontent.com/42774792/86209410-24d29580-bba5-11ea-85e2-f29eb86e8543.png)

**Comment by sxhieen** [comment]
可以参考这个
