### ISSUE TITLE
IE11浏览器运行报错  [import-html-entry] Here is no "fetch" on the window env, you need to polyfill it

### ISSUE THREAD

**Issue by cshsh** [umijs/qiankun#679]
## What happens?
vue.config.js配置了  transpileDependencies: ['single-spa', 'qiankun', 'import-html-entry']，且main.js文件里面引入了babel-polyfill。项目运行起来报错

![image](https://user-images.githubusercontent.com/12389638/85034914-2c616a00-b1b5-11ea-8b1e-7a48aae14925.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by cshsh** [comment]
已解决

**Comment by wocwin** [comment]
大佬，解决方法？

**Comment by lucio-jiang** [comment]
楼上怎么解决的 能说一下吗

**Comment by lucio-jiang** [comment]
> 已解决

同问，楼上能说一下解决方案吗

**Comment by cshsh** [comment]
@lucio-jiang  vue.config.js 配置   transpileDependencies: [ 'import-html-entry']
main.js引入   import 'fetch-polyfill'

**Comment by anLl** [comment]
> 已解决

又出现了另一个问题
![image](https://user-images.githubusercontent.com/11817793/86111401-470ed980-baf9-11ea-82c3-c277b6556814.png)

![image](https://user-images.githubusercontent.com/11817793/86111321-32cadc80-baf9-11ea-8e46-a27d8f594a6c.png)

**Comment by liuxiuqian** [comment]
@anLl 这个问题解决了吗

**Comment by liuxiuqian** [comment]
umi.js 配置的 react 项目 IE11浏览器运行报错 [import-html-entry] Here is no "fetch" on the window env, you need to polyfill it 如何解决

**Comment by anLl** [comment]
> @anLl 这个问题解决了吗

没有啊，脑壳疼

**Comment by Torn1996** [comment]
有解决方案吗？

**Comment by Torn1996** [comment]
已解决。
由于IE浏览器中没有fetch，解决方案如下：
main.js中引入import 'fetch-polyfill'，同时要保证fetch-polyfill的加载顺序先于import-html-entry
