### ISSUE TITLE
父子应用卸载的顺序问题

### ISSUE THREAD

**Issue by kinsliy** [umijs/qiankun#68]
## 相关环境信息

- **Node 版本**：10
- **操作系统**：mac

**Comment by kuitos** [comment]
可以在B应用 unmount 时手动卸载C应用

**Comment by kinsliy** [comment]
@kuitos 如果B应用下很多子应用，当B应用卸载的时候，不确定具体是哪个子应用挂载？那我要在B应用unmount的时候把所有的子应用卸载吗？还是可以得到当前哪个子应用挂载？

**Comment by kinsliy** [comment]
@kuitos 子应用的ReactDom是子应用的react，所以没办法在父应用这里的reactdom去卸载，会有这个问题
![image](https://user-images.githubusercontent.com/11538819/65032285-6a570680-d975-11e9-9952-c79f8363b26e.png)

**Comment by kinsliy** [comment]
![image](https://user-images.githubusercontent.com/11538819/65032306-75119b80-d975-11e9-846e-f5c257eadc2e.png)

**Comment by kinsliy** [comment]
@kuitos 尝试用spa的api，unloadApplication，不知道这里是不是可以用 ？

**Comment by kuitos** [comment]
多个子应用嵌套会尝试在 2.x 版本解决
