### ISSUE TITLE
[Feature Request] 主应用提供策略控制子应用资源的加载

### ISSUE THREAD

**Issue by shizhipeng** [umijs/qiankun#680]
## Background

按照webpack externals的方案，在主应用访问子应用时，需要告知子应用不再请求指定的公共依赖

## Proposal

提供一种过滤方案，可以不去处理（fetch&eval）指定的公共script

## Additional context
-

**Comment by kuitos** [comment]
external 不是子应用做的么，子应用只要不在 html 里引用 external 的库，统一由主应用引用就可以了吧

**Comment by shizhipeng** [comment]
> external 不是子应用做的么，子应用只要不在 html 里引用 external 的库，统一由主应用引用就可以了吧

但是子应用也要独立访问，所以子应用是需要在html里引入external 的库，然后主应用访问时，则不需要让fetch和eval子应用的这份js了

**Comment by kuitos** [comment]
子应用的 external 库 上加一个 ignore 属性就行了，如：
```html
<link ignore rel="stylesheet" href="//cnd.com/antd.css">
<script ignore src="//cnd.com/antd.js"></script>
```

**Comment by shizhipeng** [comment]
噢 看了下 原来已经有了 👍
