### ISSUE TITLE
同域问题交流

### ISSUE THREAD

**Issue by gemmer01** [umijs/qiankun#681]
**最近好多朋友在https://github.com/umijs/qiankun/issues/400 向我咨询同域问题
新开一帖大家交流分享，管理员可尝试不关闭此贴大家共同交流

https://github.com/gemmer01/Micro-front-end/这是我的github工程，里面有配置
此项目同域跨域都存在大家可以下载尝试下，具体的配置.conf里面都有
主应用是7000，child3也是7000
![image](https://user-images.githubusercontent.com/10986766/85103092-9a9b4080-b238-11ea-8b65-fbf4edeb448b.png)
7000端口是同域跨域共存的，跨域不说了同域的配置如下：
   location /vue3 {  
	    try_files $uri $uri/  /vue3/index.html; 	
	    index  index.html index.htm;
    }
![test](https://user-images.githubusercontent.com/10986766/85103162-bdc5f000-b238-11ea-96ea-704dc9b9c077.gif)

同域child3报错不用看我没有配置远程mock，ui已经出来了就说明成功了
另外配的时候一定要注意publicPath 和 router basepath
前端小学生不断成长进步中，如果有哪做的不好希望大佬指正，共同交流进步 谢谢**

**Comment by sxhieen** [comment]
谢谢！Angular亲测有效，路由有无带hash都可以
