### ISSUE TITLE
不使用npm包管理的前端服务如何作为主应用接入qiankun

### ISSUE THREAD

**Issue by winterZhao** [umijs/qiankun#684]
请问一下，我们的主应用是一个java多页面后端渲染服务，用的是ftl模板引擎，ftl里直接以cdn形式引入的vue1开发的。没有使用node_modules，想请问一下这种形式的主应用如何作为主应用接入qiankun。

**Comment by gongshun** [comment]
你就参考 `jQuery` 项目如何接入就行了

**Comment by howel52** [comment]
从描述看，可以先判断下你们目前的开发模式接入 SPA 微前端方案的必要性。
