### ISSUE TITLE
主应用导致浏览器假死，只能通过浏览器的任务管理器强杀

### ISSUE THREAD

**Issue by koupeng** [umijs/qiankun#685]
## What happens?

主应用导致浏览器假死，只能通过浏览器的任务管理器强杀

## How To Reproduce
（1）我的主应用是基于Ant Design Pro4的项目工程
（2）子应用也是AntD pro4
（3）主应用跳转的子应用是通过Link跳转到新的标签的形式进入子应用
（4）在主应用跳转子应用后，子应用如果没有完全加载完成，就把标签关闭，主应用死掉，出现白屏，无法关闭标签，可以通过谷歌的任务管理器强制关闭。

## Context

- **qiankun Version**:     "@umijs/plugin-qiankun": "^2.2.0-0",
- **Platform Version**:
- **Browser Version**:  谷歌版本 74.0.3729.131（正式版本） （32 位）

**Comment by kuitos** [comment]
closed via inactive
