### ISSUE TITLE
遗留系统迁移

### ISSUE THREAD

**Issue by Auroraan** [umijs/qiankun#69]
在遗留系统中暴露了钩子，但是出现了跨域的问题，请问怎么解决呢，还需要怎么设置吗？

Access to fetch at 'http://127.0.0.1:4000/' from origin 'http://localhost:7099' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by kinsliy** [comment]
@Auroraan 自己项目添加可以通过跨域的配置，这不属于qiankun的问题

**Comment by Auroraan** [comment]
嗯嗯，自己添加的项目，除了暴露钩子外，还需要配置什么吗？有没有除了qiankun里面examples之外的demo

**Comment by Auroraan** [comment]
> @Auroraan 一个是export 生命周期的钩子，还有就是如果是webpack就看下文档那里的output配置下应该就可以了

https://github.com/umijs/qiankun/issues/69#issuecomment-530715762

**Comment by Auroraan** [comment]
我想问问，遗留系统迁移的项目，主应用程序和子应用程序通信，需要怎么实现？是需要使用@umijs/plugin-qiankun才可以解决吗？

**Comment by Auroraan** [comment]
> @Auroraan 一个是export 生命周期的钩子，还有就是如果是webpack就看下文档那里的output配置下应该就可以了

我想问问，遗留系统迁移的项目，主应用程序和子应用程序通信，需要怎么实现？是需要使用@umijs/plugin-qiankun才可以解决吗？
