### ISSUE TITLE
子应用偶尔会获取不到container, 子应用渲染不出来

### ISSUE THREAD

**Issue by v5sollee** [umijs/qiankun#690]
## What happens?
刷新页面的时候控制台报错, 子应用卡在loading页面加载不出来,调试发现没有获取到container DOM,这种情况偶尔出现, 在弱网情况下出现的概率较高, 是我的配置有什么问题吗?
![错误信息](https://m1-cdn.imeijian.cn/8e78ab83d154b3dedcb3d3c19d526720.jpeg?x-oss-process=style/1000wh_j2x)

```javascript
single-spa.min.js?25a2:2 Uncaught Error: application 'trading' died in status LOADING_SOURCE_CODE: [qiankun] Target container with #subapp-viewport not existed while trading loading!
    at assertElementExist (loader.js?6f14:20)
    at render (loader.js?6f14:148)
    at _callee16$ (loader.js?6f14:240)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at fulfilled (tslib.es6.js?9ab4:71)
```
### 项目配置
```javascript
function render({ appContent, loading }) {
  const container = document.getElementById('app');
  ReactDOM.render(
    <Provider store={store}>
      <Router history={history}>
        <Switch>
          <Route path="/login" component={Login} />
          <div id="subapp-viewport" />
        </Switch>
      </Router>
    </Provider>,
    container
  );
}
```

```javascript
const microApps = [
  {
    name: 'app1',
    port: 9106,
    props: {}
  },
  {
    name: 'app2',
    port: 9105,
    props: {}
  },
  {
    name: 'trading',
    port: 9104,
    props: {}
  },
];
```

```javascript
/**
 * Step1 初始化应用（可选）
 */
render({ loading: true });
const loader = loading => render({ loading });

/**
 * Step2 注册子应用
 */
registerMicroApps(
  microApps.map(v => ({
    name: v.name,
    activeRule: `/${v.name}`,
    loader,
    container: '#subapp-viewport',
    entry: 'localhost:3000'
    props: {}
  })),
  {
    beforeLoad: [ ],
    beforeMount: [ ],
    afterUnmount: [ ]
  },

);
```

## Context

- **qiankun Version**: "^2.0.11",
- **Platform Version**: Mac OS 10.15.4
- **Browser Version**:  Chrome 83.0.4103.106

**Comment by Genluo** [comment]
应该是写法问题导致的报错，可以首先渲染外层框架，然后在注册子应用

**Comment by Genluo** [comment]
感觉用法有点问题，要么去掉registerMicroApps中的loader，要么去掉container、loader配置项，使用render配置，类似如下配置方式：
```typescript
    const result: RegistrableApp[] = config.map(currentPageConfig => ({
        name: currentPageConfig.name,
        entry: currentPageConfig.entry,
        activeRule: genActiveRule(currentPageConfig.path),
        render: ({ appContent, loading }): void => renderMicroApp({ appContent, loading })
    }));
```

**Comment by v5sollee** [comment]
> 感觉合适的问题，或者去掉注册MicroApps中的加载器，或者去掉容器，加载器配置项，使用渲染配置，类似如下配置方式：
> 
> ```ts
>     const  结果：RegistrableApp [ ]  =  config 。映射（currentPageConfig  =>  （{ 
>         名称：currentPageConfig 。名称，
>         条目：currentPageConfig 。条目，
>         activeRule：genActiveRule （currentPageConfig 。路径），
>         使：（{ appContent ，装载} ）：空隙  => renderMicroApp （{ appContent ，装载} ）
>     } ））;
> ```
> 
> loader配置项的作用只是为了告诉主应用程序加载状态发生变化，而渲染器和容器配置项决定子应用程序的渲染，并且渲染器的配置项优先

**Comment by v5sollee** [comment]
> 感觉用法有点问题，要么去掉registerMicroApps中的loader，要么去掉container、loader配置项，使用render配置，类似如下配置方式：
> 
> ```ts
>     const result: RegistrableApp[] = config.map(currentPageConfig => ({
>         name: currentPageConfig.name,
>         entry: currentPageConfig.entry,
>         activeRule: genActiveRule(currentPageConfig.path),
>         render: ({ appContent, loading }): void => renderMicroApp({ appContent, loading })
>     }));
> ```
> 
> loader配置项的作用只是为了告诉主应用loading 状态发生变化，而render和container配置项决定子应用的渲染，并且render的配置项优先

试了下不行,我是按照官方Demo那种写法来的😓
```javascript
// 目前只能定位到报错的时候,在loader文件的getRender里面找不到容器DOM
loader.js

var containerElement = typeof container === 'string' ? document.querySelector(container) : container;
// 获取containerElement 为 null时,报错
```

大部分情况下都是能正常获取到的, 个别情况会报错,将Chrome Network 设置成 Slow 3G之后就很容易复现了

**Comment by kuitos** [comment]
报错是因为微应用渲染时，`<div id="subapp-viewport" />` 这个容器还没有渲染到 dom 树里，原因是 ReactDOM.render 本身就是异步的，只是弱网场景放大了这个异步时序问题。

解决方案可以利用 ReactDOM.render 的第三个参数来确保 render 完成后再调用 registerMicroApps，或者直接换成 loadMicroApp api 手动控制微应用的加载。

> 而render和container配置项决定子应用的渲染，并且render的配置项优先

render 配置已经不推荐用了，如果你在本地开发环境应该能看到控制台的 warning

**Comment by wowtrxqn** [comment]
这个问题如何解决最好？

**Comment by liujianchao1995** [comment]
我在nuxt里使用时，也遇到了这个问题。请问该如何解决？

**Comment by hello-astar** [comment]
解决了吗
