### ISSUE TITLE
子应用接口调用报404是怎么回事

### ISSUE THREAD

**Issue by lilinfan** [umijs/qiankun#694]
子应用接口调用报404是怎么回事

**Comment by gongshun** [comment]
接口的路径写绝对路径，如果是 `axios`，可以设置 `axios.defaults.baseURL`

**Comment by lilinfan** [comment]
> 接口的路径写绝对路径，如果是 `axios`，可以设置 `axios.defaults.baseURL`

这样子就涉及到跨域的问题了，能用vue-cli的dev-serve解决这问题吗？

**Comment by gongshun** [comment]
> 这样子就涉及到跨域的问题了，能用 `vue-cli` 的 `dev-serve` 解决这问题吗？

本地开发可以用 `dev-serve` ，部署了不行

**Comment by lilinfan** [comment]
本地开发单独项目可以访问，放一起就不行，dev-serve这个已经设置了
devServer:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;port:&nbsp;7105,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;headers:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'Access-Control-Allow-Origin':&nbsp;'*',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;proxy:&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"/core-api":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target:&nbsp;url
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"/upload":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target:url
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"/export":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target:&nbsp;url
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;open:true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;historyApiFallback:true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;disableHostCheck:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compress:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;},






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gongshun"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午4:37
收件人: "umijs/qiankun"<qiankun@noreply.github.com&gt;; 
抄送: "Vampire ℡"<1226405800@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/qiankun] 子应用接口调用报404是怎么回事 (#694)





  
这样子就涉及到跨域的问题了，能用 vue-cli 的 dev-serve 解决这问题吗？
  
本地开发可以用 dev-serve ，部署了不行

**Comment by lilinfan** [comment]
> > 这样子就涉及到跨域的问题了，能用 `vue-cli` 的 `dev-serve` 解决这问题吗？
> 
> 本地开发可以用 `dev-serve` ，部署了不行

本地开发单独的项目可以访问，放一起就不行，dev-serve已经设置了
`devServer: {
		port: 7105,
		headers: {
			'Access-Control-Allow-Origin': '*',
		  },
		proxy: {
			
			"/core-api": {
				target: url
			},
			"/upload": {
				target:url
			},
			"/export": {
				target: url
			},
		},
		open:true,
		historyApiFallback:true,
		disableHostCheck: true,
    	compress: true,
		
	},`

**Comment by gongshun** [comment]
相对路径的问题，还是需要设置 `baseURL` ，设置之后会请求到你的本地开发的代理服务。

**Comment by lilinfan** [comment]
> 相对路径的问题，还是需要设置 `baseURL` ，设置之后会请求到你的本地开发的代理服务。

大佬，请问一下我试着访问图片的路径访问失败了，加了baseURL又变成了跨域，该怎么解决

**Comment by gongshun** [comment]
跨域不难解决吧，加响应头 `'Access-Control-Allow-Origin': '*'`  就行

**Comment by howel52** [comment]
请求时产生的跨域问题是浏览器侧的机制，可以部署在同域，或是支持跨域响应

[FAQ](https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E4%B8%80%E5%AE%9A%E8%A6%81%E6%94%AF%E6%8C%81%E8%B7%A8%E5%9F%9F%E5%90%97%EF%BC%9F)

**Comment by xiaohuaxiangwoyiyang** [comment]
> 子应用接口调用报404是怎么回事

解决了吗

**Comment by BrucePhoebus** [comment]
> > 子应用接口调用报404是怎么回事
> 
> 解决了吗

有一个比较lo的做法
```JS
let proxy = null

if (process.env.NODE_ENV === 'development') {
  const child1Proxy = require('../child1/proxy')
  proxy = {
    ...child1Proxy
  }
}
```
主应用在开发环境下导入子应用的proxy

**Comment by BrucePhoebus** [comment]
对于这个问题，开发环境跨域好像不是很好解决，正常来说主应用不应该混入子应用的东西，而简单代理无法实现，多技术栈的项目不可能简单放在同域之下运行，开发状态使用nginx代理或啥不知道怎么玩，还是简单的将所有子应用的proxy都在开发环境状态下拷贝到主应用，这样算是勉强可用

**Comment by zhaoqi-nb** [comment]
大佬们，这个有最新的解决办法嘛

**Comment by Sheepeer** [comment]
子应用api从相对地址改为绝对地址可以解决这个问题
![image](https://user-images.githubusercontent.com/78125933/223065743-b2176477-0ad2-491e-a9c3-34f971d641c3.png)

**Comment by hanalice** [comment]
绝对路径可以解决问题，对于使用swagger 生成的service, 可以在app.module.ts 里面注入rootUrl 值。
![image](https://github.com/umijs/qiankun/assets/18046501/249f09b0-5926-436e-8686-e296b77ee1e2)

**Comment by hanalice** [comment]
> 对于这个问题，开发环境跨域好像不是很好解决，正常来说主应用不应该混入子应用的东西，而简单代理无法实现，多技术栈的项目不可能简单放在同域之下运行，开发状态使用nginx代理或啥不知道怎么玩，还是简单的将所有子应用的proxy都在开发环境状态下拷贝到主应用，这样算是勉强可用

webpack dev server 的话不是自动开启跨域的吗？

![image](https://github.com/umijs/qiankun/assets/18046501/3475afa8-9c94-4e01-87f8-cb725b2be055)

**Comment by wenqstart** [comment]
> > > 子应用接口调用报404是怎么回事
> > 
> > 
> > 解决了吗
> 
> 有一个比较lo的做法
> 
> ```js
> let proxy = null
> 
> if (process.env.NODE_ENV === 'development') {
>   const child1Proxy = require('../child1/proxy')
>   proxy = {
>     ...child1Proxy
>   }
> }
> ```
> 
> 主应用在开发环境下导入子应用的proxy

我在主应用设置了和子应用一样的proxy配置，还是404，主应用用的umi4，子应用是vite vue3
