### ISSUE TITLE
将ant pro v4.0加入examples里面作为子应用启动正常、浏览器访问报错：Disconnected from the devServer, trying to reconnect...，但是将ant pro v2.0加入examples里面启动、访问都正常

### ISSUE THREAD

**Issue by zengfanshunq** [umijs/qiankun#695]
将ant pro v4.0加入examples里面作为子应用，启动、浏览器访问报错：Disconnected from the devServer, trying to reconnect...，但是将ant pro v2.0加入examples里面启动、访问都正常

**Comment by howel52** [comment]
Need Reproduction提供下最小可复现仓库 reopen

**Comment by cschensai** [comment]
你好请问解决了吗
