### ISSUE TITLE
在qinkun 项目里使用 import-html-entry 失效

### ISSUE THREAD

**Issue by zq78049721** [umijs/qiankun#696]
import Vue from 'vue'
import VueRouter from 'vue-router'
// import Home from '../views/Home.vue'
import importHTML from 'import-html-entry';

function getComponent() {
  return importHTML('http://192.168.8.37:8081/index.html')
    .then(res => {
      console.info(res);
      return res.execScripts().then((exports)=>{
        console.info(exports)
        return exports;
      })
    });
}

// import About from '../views/About.vue'

Vue.use(VueRouter)
const routes = [
  {
    path: '*',
    name: 'Home',
    component: getComponent
  }
]

const router = new VueRouter({
  routes,
  mode: 'history'
})

export default router

------------------------------------------------------
exports 里面永远拿到不到东西

**Comment by kuitos** [comment]
html 里的 entry js 需要 umd 包

这个问题跟 qiankun 没关系，关了~

**Comment by zq78049721** [comment]
import-html-entry 那个类库里面好像不能建立issue 所以我在这里提问的，个人猜测好像是跟沙盒有关系，因为我尝试请求了  import-html-entry 里面的示例页面 
https://raw.githubusercontent.com/kuitos/import-html-entry/master/example/template.html
同样的代码用普通的vue页面运行完全没有问题，
但是如果使用了qiankun的项目就得不到任何得exports ,是否能帮忙看一下原因？

**Comment by kuitos** [comment]
提供一个可复现仓库
