### ISSUE TITLE
请问我其中一个子程序是Nuxt开发的ssr应用，现在想接入主程序，出现渲染问题

### ISSUE THREAD

**Issue by userpan** [umijs/qiankun#697]
![image](https://user-images.githubusercontent.com/13382299/86078725-4d815f00-bac1-11ea-9fb7-930a5445effd.png)

![image](https://user-images.githubusercontent.com/13382299/86078645-2cb90980-bac1-11ea-9fc7-805089393e51.png)

在加载子程序时候出现一闪而过，然后就开始报错
求大神搭救，谢谢

**Comment by howel52** [comment]
提供可复现仓库 reopen

**Comment by dujuncheng** [comment]
> 

你好，请问这个问题后面有办法解决了吗~
