### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by screetBloom** [umijs/qiankun#698]
Hi there，some confusion：
- 如何理解「独立开发、独立部署」这句话，独立是相对什么来说
- 如何理解《[可能是你见过最完善的微前端解决方案](https://zhuanlan.zhihu.com/p/78362028)》中提到的 「MPA 方案的优点在于 部署简单、各应用之间硬隔离，天生具备技术栈无关、独立开发、独立部署的特性」。通过webpack配置，在不拆分项目的情况下一个git repo也是可以做MPA的，为什么这里说MPA天生具备技术栈无关、独立开发独立部署呢？在不拆分项目的情况下似乎做不到这一点

阅读《qiankun-指南-介绍》时的一些疑惑，如果能解答一下这两点问题会十分感谢
@kuitos

**Comment by kuitos** [comment]
1. 相对于集成开发，集成部署的方案
2. 通常工程上 MPA 就是用独立仓库的方式来维护的，一个 git 仓库也能做但会比较麻烦，容易潜意识把项目往耦合的形态上牵引

**Comment by screetBloom** [comment]
首先十分感谢你的回复


> 1. 相对于集成开发，集成部署的方案
> 2. 通常工程上 MPA 就是用独立仓库的方式来维护的，一个 git 仓库也能做但会比较麻烦，容易潜意识把项目往耦合的形态上牵引

第【2】点理解下来，就是说微前端在工程结构上是不推荐集中式的项目管理，更加推荐分散、相互独立的形式是吗？

**Comment by kuitos** [comment]
> 第【2】点理解下来，就是说微前端在工程结构上是不推荐集中式的项目管理，更加推荐分散、相互独立的形式是吗？

是的

**Comment by screetBloom** [comment]
好的，十分感谢你的回复

再请教最后一个疑惑：
在拆分git repo的情况下，拆分之后公共模块、公共能力通过NPM包引用存在比较明显的管理成本
请问对**公共能力复用有什么比较好的实践方案推荐吗？**

**Comment by kuitos** [comment]
1. 项目之间复用性越强越说明拆分粒度不合理，可能是拆分过细，通常粒度合适的场景，耦合跟依赖复用的诉求不会那么强
2. 可以考虑 Webpack Module Federation

**Comment by screetBloom** [comment]
十分感谢你的耐心回复👍
