### ISSUE TITLE
关于样式隔离

### ISSUE THREAD

**Issue by mengxingshike2012** [umijs/qiankun#7]
我们的场景是： 一个老项目还是antd1.x的， 而且是一些非常基础的功能， 暂时没有精力升级，
而新项目使用了antd3,  现在发现两者的样式会存在一些冲突， 感觉Example还是简单了些， 想问下在内部使用过程中，还有没有一些坑(经验)分享?

**Comment by kuitos** [comment]
qiankun 可以确保子应用之间样式隔离，主应用跟子应用之间的样式冲突需要手动解决，以 antd 为例，主应用可以通过设置 prefixCls 的方式避免冲突

**Comment by mengxingshike2012** [comment]
试了下不行， 因为是开发环境， 没有抽离css, 加载了之后追加到了head里面， 子应用切换还是有影响的；改prefix这个已经改了， 主要是ant本身的一些不兼容改动有影响

**Comment by kuitos** [comment]
开发环境也 extract 一下

**Comment by mengxingshike2012** [comment]
现在有一个问题， 发现在应用切换的时候， 已经是apploading false的状态了， 有肉眼明显可以感知到卡顿， 已经prefetch了， 所以是慢在了js parse and compile 吗， 首次子应用切换的体验有点不太好

**Comment by kuitos** [comment]
loading false 时子应用 js 已经执行完毕了，可以看下是不是子应用有自己的异步渲染逻辑，或者子应用自己的 render 本身就很耗时

**Comment by mengxingshike2012** [comment]
首次和二次有什么区别/缓存吗， 切换后再切回来就很快？

**Comment by kuitos** [comment]
对于 qiankun 来说子应用 mount 阶段没有区别，第一次只是多了个 load 跟 bootstrap，但是这两个完成之前都是 loading true。检查一下是不是你有什么缓存的全局 store 之类的东西？

**Comment by mengxingshike2012** [comment]
说错了， 确实是 js fetch了， 但是第一次render, 此时apploading = true 特别的慢

**Comment by kuitos** [comment]
第一次进入会有 js 执行的耗时，这个时候慢的话说明子应用本身初始化就慢~

**Comment by kuitos** [comment]
可以看下你子应用的包的大小

**Comment by guojingwen** [comment]
基于 react 基座，多个react 子应用的 微服务系统，子应用之间样式确实是隔离的，

而基于vue基座， 多个vue子应用的 微服务系统，子应用之前的样式不是隔离的，原因子应用的是插入 html>head元素里面，而不是html>body>container元素里面

**Comment by guojingwen** [comment]
貌似需要写一个webpack插件处理下

**Comment by kuitos** [comment]
@guojingwen 原因是这个 #38，近期会官方修复这个问题

**Comment by guojingwen** [comment]
期待哦 @kuitos

**Comment by yangangzhang** [comment]
> @guojingwen 原因是这个 #38，近期会官方修复这个问题

修复了吗？测试了一下是没有

**Comment by keunone** [comment]
@mengxingshike2012 请问你antd版本样式隔离的问题怎么解决的？

**Comment by mengxingshike2012** [comment]
@keunone  不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀

**Comment by keunone** [comment]
不好意思，没有描述清楚，我是主应用antd（4.0）的样式影响了子应用（3.0）的样式，可以借鉴下你们webpack的loader怎么处理的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mengxingshike2012"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午4:56
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"Keun"<746542397@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun] 关于样式隔离 (#7)





 
@keunone  不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀

**Comment by funmore** [comment]
> @keunone 不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
> 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
> 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀

我的情况是2） 主子应用冲突  ，我想请教下 如果前缀antd-替换成了自己的前缀， 那么在引用组件的时候是不是也要写个loader，把这些在组件中class name 替换了？

**Comment by zhangkuiworld** [comment]
> @keunone 不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
> 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
> 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀

“把前缀antd-替换成了自己的前缀”这个怎么实现？方便透露下嘛

**Comment by keunone** [comment]
> > @keunone 不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
> > 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
> > 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀
> 
> “把前缀antd-替换成了自己的前缀”这个怎么实现？方便透露下嘛

 PostCSS 加前缀插件，打包后自动添加前缀

**Comment by keunone** [comment]
> > @keunone 不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
> > 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
> > 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀
> 
> “把前缀antd-替换成了自己的前缀”这个怎么实现？方便透露下嘛

@zhangkuiworld 
PostCSS 加前缀插件，打包后自动添加前缀

**Comment by xiaoqiangz** [comment]
> 现在有一个问题， 发现在应用切换的时候， 已经是apploading false的状态了， 有肉眼明显可以感知到卡顿， 已经prefetch了， 所以是慢在了js parse and compile 吗， 首次子应用切换的体验有点不太好

你好，想咨询下这个卡顿是如何解决的？

**Comment by humorHan** [comment]
> > > @keunone 不太清除你现在遇到的问题是子应用之间样式冲突还是主子应用之前样式冲突；
> > > 1）如果是子应用之间，那么使用抽离出单独css文件的方式(htmlentry)，这样乾坤本身会隔离各个子应用的样式
> > > 2）如果是主子应用冲突，我们是直接写了一个webpack的loader，把前缀antd-替换成了自己的前缀
> > 
> > 
> > “把前缀antd-替换成了自己的前缀”这个怎么实现？方便透露下嘛
> 
> @zhangkuiworld
> PostCSS 加前缀插件，打包后自动添加前缀

请问哪个插件呢，找到一个postcss-modules的不生效

**Comment by humorHan** [comment]
> qiankun 可以确保子应用之间样式隔离，主应用跟子应用之间的样式冲突需要手动解决，以 antd 为例，主应用可以通过设置 prefixCls 的方式避免冲突
> see https://ant.design/docs/react/customize-theme

@kuitos  
 主应用elementplus  子应用element，因为UI库有dom和css改动导致主子应用互相冲突，这个有什么方案嘛

**Comment by dongongfeiyu** [comment]
@humorHan 您好，请问最终是怎么解决的？目前也遇到了这个问题

**Comment by hellodigua** [comment]
同样遇到了楼上关注elementUI跨版本的问题，期待有大佬提供解决方案

**Comment by lasiaz** [comment]
同样遇到了elementUI 不同版本的隔离问题，期待解决方案

**Comment by humorHan** [comment]
> 同样遇到了楼上关于elementUI跨版本的问题，期待有大佬提供解决方案

postcss-plugin-namespace
remind：需要排除添加在body上的样式
