### ISSUE TITLE
IE11无法启动,[import-html-entry] Here is no "fetch" on the window env, you need to polyfill it

### ISSUE THREAD

**Issue by anLl** [umijs/qiankun#701]
## What happens?

IE11无法启动,[import-html-entry] Here is no "fetch" on the window env, you need to polyfill it
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
### 2：使用ie11打开
![image](https://user-images.githubusercontent.com/11817793/86199675-4fb0ef80-bb8d-11ea-94bf-c6b3131977f2.png)
### 4：没有报fetch错误，出现了新的错误
![image](https://user-images.githubusercontent.com/11817793/86200618-c3ec9280-bb8f-11ea-927e-5300b2f4b468.png)
### 5：点入报错js
![image](https://user-images.githubusercontent.com/11817793/86200643-db2b8000-bb8f-11ea-8d7d-c6463f54a4f1.png)

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:2.0.15
- **Platform Version**:vue
- **Browser Version**:ie11

**Comment by kuitos** [comment]
@howel52 看下是不是同一个问题 https://github.com/umijs/qiankun/issues/565#issuecomment-641672927

**Comment by anLl** [comment]
> @howel52 看下是不是同一个问题 [#565 (comment)](https://github.com/umijs/qiankun/issues/565#issuecomment-641672927)

不是一个问题，能帮忙解决一下么

[qiankun-ie](https://github.com/anLl/qiankun-ie)

**Comment by howel52** [comment]
我找台 windows 看看

**Comment by anLl** [comment]
> 我找台 windows 看看
哥，能加个微信嘛，或者钉钉么，我在钉钉1群，火烧眉毛了，客户突然要ie11，都蒙了

**Comment by howel52** [comment]
此楼大概是有两个问题：
1. IE 需要 fetch polyfill
2. 在 patcher 里验证了下，`super` 写法构建后的产物在  `@babel/runtime/helpers/esm/setPrototypeOf` 里跑不起来了

第一个不是问题

第二个目前看只有 IE 会有关于 setPrototypeOf 的问题，UIEvent 的 patcher 是为了解决 ProxySandbox 的问题，IE 里其实不会有 Proxy，这么看的话是不是部分 patcher 是不用打在 IE 上的 @kuitos 

（不过这个 super 写法构建完后在 IE 上跑不起来是有点奇怪）

**Comment by kuitos** [comment]
> UIEvent 的 patcher 是为了解决 ProxySandbox 的问题，IE 里其实不会有 Proxy，这么看的话是不是部分 patcher 是不用打在 IE 上的 @kuitos

+1，调整一下整理出一个只为 Proxy 沙箱服务的 patcher 集？

**Comment by anLl** [comment]
> > UIEvent 的 patcher 是为了解决 ProxySandbox 的问题，IE 里其实不会有 Proxy，这么看的话是不是部分 patcher 是不用打在 IE 上的 @kuitos
> 
> +1，调整一下整理出一个只为 Proxy 沙箱服务的 patcher 集？

我这边如何修改呢，丢丢着急

**Comment by shinji3887** [comment]
顶，同样的问题，测试机器为win10+ie11
qiankun版本为2.0.15

**Comment by howel52** [comment]
> 我这边如何修改呢

不等发包的话可以 alias 掉 patcher UIEvent 的 es 代码，参考这个 https://github.com/umijs/qiankun/issues/52#issuecomment-569386202

**Comment by anLl** [comment]
> > 我这边如何修改呢
> 
> 不等发包的话可以 alias 掉 patcher UIEvent 的 es 代码，参考这个 [#52 (comment)](https://github.com/umijs/qiankun/issues/52#issuecomment-569386202)


> > 我这边如何修改呢
> 
> 不等发包的话可以 alias 掉 patcher UIEvent 的 es 代码，参考这个 [#52 (comment)](https://github.com/umijs/qiankun/issues/52#issuecomment-569386202)

不要意思啊，我再问问什么时候发新版本喃

**Comment by howel52** [comment]
@anLl  [v2.0.16](https://github.com/umijs/qiankun/releases/tag/v2.0.16)

**Comment by anLl** [comment]
> @anLl [v2.0.16](https://github.com/umijs/qiankun/releases/tag/v2.0.16)

万分感谢，万分感谢~

**Comment by liuxiuqian** [comment]
> > @anLl [v2.0.16](https://github.com/umijs/qiankun/releases/tag/v2.0.16)
> 
> 万分感谢，万分感谢~
问题解决了吗 我引入最新的 v2.0.16 还是会存在问题

**Comment by shinji3887** [comment]
ie支持fetch，应该用fetch-polyfill还是whatwg-fetch呢？
看了下fetch-polyfill最后一次更新是5年前了，whatwg-fetch更新比较频繁
官方文档上面似乎写的也是whatwg-fetch
