### ISSUE TITLE
demo中Angular9的serve:qiankun为什么需要--disable-host-check和--live-reload false

### ISSUE THREAD

**Issue by sxhieen** [umijs/qiankun#703]
如果不加会有什么影响吗

**Comment by Deturium** [comment]
`--disable-host-check` 是 [webpack 的配置项](https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck)
如果你给子应用绑定了一个本地 host，那开发的时候可能会遇到 `Invalid Host header` 这样的错误；这时需要关闭 host 检查

`--live-reload` 是关闭热重载，HRM 同理
因为我们开发的时候往往同时启动主应用和子应用，主应用侧加载的子应用的热重载功能时常会出错；你可以关了，不一定报错
