### ISSUE TITLE
注册微应用的时候entry参数是否可以使用相对路径？

### ISSUE THREAD

**Issue by shinji3887** [umijs/qiankun#704]
例子里面似乎使用的都是绝对路径，是否可以使用主应用的相对路径作为entry参数？（比如主应用的nginx做个反代）
试了将entry的地址设置为和主应用一样的ip和端口，会进入无限循环跳转模式

**Comment by shinji3887** [comment]
试了将entry的地址设置为和主应用一样的ip和端口，会进入无限刷屏模式

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/577#issuecomment-652846777

**Comment by hql7** [comment]
https://juejin.cn/post/6844904143413313549#heading-22 快速调整为双端口方案

**Comment by fyzwjd** [comment]
@hql7  请教下，这种双端口方案，打包的publicPath是固定的，如何区分集成测试环境和正式发布环境呢，用打包脚本来区分吗，显得不一致
