### ISSUE TITLE
主项目是用的single-spa能挂载qiankun的子项目吗？

### ISSUE THREAD

**Issue by ljxtest** [umijs/qiankun#705]
一个项目是基于ant pro开发的用qiankun做了微服务
需要和另外一个用single-spa的项目做集成
请问有解决方案吗？

**Comment by kuitos** [comment]
可以

**Comment by ljxtest** [comment]
大神请问有相关文档可以参考一下吗？single-spa中entry直接请求子应用尝试了一下不行，  pro中也没有入口文件可以供single-spa封装。。
