### ISSUE TITLE
内存泄漏问题 [ proxyGetterMap ]

### ISSUE THREAD

**Issue by lkiarest** [umijs/qiankun#706]
## What happens?

我是在 vue 项目里使用 loadMicroApp 动态加载子应用的。
每次执行 mount 之后，调用链是 :
patchAtMounting -> patchDynamicAppend -> setProxyPropertyGetter , 这个函数中会把 proxy 放到 map 中：
```
proxyGetterMap.set(proxy, { ...prevGetters, [property]: getter });
```
之后子应用 unmount 的时候并没有释放这个 map 中的对象，下一个应用 mount 又会继续往里面加。
因为 proxy 里包含了 window 对象，所以这个泄漏的影响还是比较大的。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
这个可以解决一下

有兴趣也可以直接提 pr
