### ISSUE TITLE
纯静态html应用作为一个微前端的一个子应用,相对链接无法正常跳转

### ISSUE THREAD

**Issue by PmcFizz** [umijs/qiankun#707]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

使用官方提供的demo, 在purehtml根目录下创建一个home.html 并引入entry.js
在purehtml的index.html里 加上  <a href="./home.html">home.html</a>
点击a链接 无法正常跳转到home.html

在微前端框架里无法正常访问到home.html  请问目前解决办法吗? 
"qiankun": "^2.0.15",
chrome浏览器
windows操作系统

**Comment by kuitos** [comment]
提供最小可复现仓库后可自行 reopen

**Comment by PmcFizz** [comment]
已添加的 最小可复现仓库  https://github.com/PmcFizz/qiankun-demo 
希望能够再百忙之中看一下 非常感谢

**Comment by kuitos** [comment]
a 路径给的是相对地址，集成后就是相对于主域的，自然就跳转不到正确的路径。需要将超链改成带子域域名的绝对路径

**Comment by PmcFizz** [comment]
写个公共方法，判断是否在微服务中，统一进行链接跳转前的拦截，url处理。
