### ISSUE TITLE
[Bug？]window.history.pushState 路径url如果是xxx2这种形式，路径就会变成xxx/2

### ISSUE THREAD

**Issue by Hades-li** [umijs/qiankun#71]
## What happens?
我自行封装了一个vue的main项目，用的就是example中的Framwok.vue组件。
其中window.history.pushState调用时，为什么如果路径是xxx2这种英文加数字的形式，路径就会变成xxx/2。
但我在子项目里同样也这样调用，确能正常切换url路径。
## 相关环境信息

- **Node 版本**：10.15.3
- **操作系统**：win10

**Comment by kuitos** [comment]
麻烦提供一下可复现仓库

**Comment by Hades-li** [comment]
> 麻烦提供一下可复现仓库

可复现仓库已提供，问题描述也重新梳理了。
