### ISSUE TITLE
dva 配置 路由项 当路由后面多个/  刷新不出来

### ISSUE THREAD

**Issue by zjscy666** [umijs/qiankun#711]
## What happens?
在dva的index.js文件，配置相关微前端服务，结果路由/vue是好的，/vue/不行了,/vue/about刷新的时候也不回显，报错Uncaught SyntaxError: Unexpected token '<'，重定向出错，如何处理
registerMicroApps([
{
            name: 'vue',
            entry: '//localhost:7101',
            container: '#subapp-viewport',
            // render,
            activeRule: ['/vue']
        }
])

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

"dva": "^2.4.1",
    "history": "^5.0.0",
    "qiankun": "^2.0.15",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"

**Comment by kuitos** [comment]
提供最小可复现仓库后可自行 reopen

**Comment by zjscy666** [comment]
这个是dva createBrowserHistory路由的问题 暂时解决了 太难了

**Comment by yitjhy** [comment]
能说下怎么将dva改造成qiankun主应用的么，急，谢谢了🙏

**Comment by Jeannette0217** [comment]
请问一个是怎么解决的。
