### ISSUE TITLE
微应用如何去调用主应用的方法？

### ISSUE THREAD

**Issue by shinji3887** [umijs/qiankun#713]
文档里好像没有提及，在微应用里面可以调用主应用的组件（例如vue组件）或者js方法吗？

**Comment by rogerIF** [comment]
不能直接调吧，你可以把主应用供子应用使用的方法放在props里传给子应用，[props - object - 可选，主应用需要传递给微应用的数据](https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles)

**Comment by howel52** [comment]
状态可以通过 [globalState](https://qiankun.umijs.org/zh/api#initglobalstatestatehttps://qiankun.umijs.org/zh/api#initglobalstatestate)

要实现自己的 pub/sub 可以走 [CustomEvent](https://developer.mozilla.org/zh-CN/docs/Web/API/CustomEvent)

**Comment by gongshun** [comment]
注册子应用时通过 `props` 把主应用的方法传过去，然后子应用挂载到全局
