### ISSUE TITLE
[Bug]子应用的link css 文件里的图片地址是相对的 旧应用如何解决拿不到资源的问题

### ISSUE THREAD

**Issue by ZzzMackie** [umijs/qiankun#717]
## 最小可复现仓库

qiankun仓库中的的例子/ purehtml目录

## 复现步骤，错误日志以及相关配置

在qiankun仓库中的例子/ purehtml目录中的index.html中添加一个link标签引入css，src地址使用相对路径图片地址，打开该子项目后可复现

## 相关环境信息

qiankun版本：2.0.11
浏览器版本：83.0.4103.61
操作系统：windows 10 1909

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/619
