### ISSUE TITLE
[Bug]公共依赖提取的时候，qiankun，代理window访问并没有先访问微应用的window，再访问主应用的window。

### ISSUE THREAD

**Issue by shannonliang** [umijs/qiankun#718]
问题：
公共依赖提取的时候，qiankun，代理window访问并没有先访问微应用的window，再访问主应用的window。

场景：
a) 在主应用配置webpack的externals 

   externals: {
        'vue': 'Vue',
        'element-ui': 'element-ui',
        'vue-router': 'VueRouter'
      }
b) 主应用html页面引入公共依赖

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <script src="https://unpkg.com/element-ui/lib/index.js"></script>

c) 在微应用中不做任何依赖剔除。

然后会Vue Router 报错 Uncaught TypeError: Cannot redefine property: $router

所以显然沙箱的window代理策略是有问题，没有先访问微应用中Vue对象。官网说明和解决方案如下截图：

![image](https://user-images.githubusercontent.com/13606897/86442819-ed98eb80-bd40-11ea-82cb-aa0d2c52f60d.png)

d) 按照官网的解决方法二，修改主应用的vue变量为vue2后，微应用如果还要提取公共依赖vue，就会找不到vue对象了。
如果微应用不做依赖剔除，也不是我想要的结果，我本来是要做提取公共依赖的。

求解，如果有更详细的落地的提取依赖方案，希望帮忙贴个地址。

**Comment by kuitos** [comment]
@eynol 看下

**Comment by gongshun** [comment]
子项目要想复用公共依赖，配置 `webpack` 的 `externals` 是必须的，而配置了这个之后，子项目独立运行时，这些依赖的来源有且仅有 `index.html` 中的外链 `script` 标签。

有两种情况：

-  子项目之间的依赖“复用”

这个很好办，你只需要保证依赖的 `url` 一致即可。比如说子项目A使用了 `vue`，子项目B也使用了同版本的 `vue`，如果两个项目使用了同一份 `CND` 文件，加载时会先从缓存读取:

```js
const fetchScript = scriptUrl => scriptCache[scriptUrl] ||
	(scriptCache[scriptUrl] = fetch(scriptUrl).then(response => response.text()));
```

- 子项目复用主项目的依赖

只需要给子项目 `index.html` 中公共依赖的 `script` 和 `link` 标签加上 `ignore` 属性（这是自定义的属性，非标准属性）。

有了这个属性，`qiankun` 便不会再去加载这个 `js/css`，而子项目独立运行，这些 `js/css` 仍能被加载，如此，便实现了“子项目复用主项目的依赖”。

```html
<link ignore rel="stylesheet" href="//cnd.com/antd.css">
<script ignore src="//cnd.com/antd.js"></script>
```

需要注意的是，主项目中的公共依赖需要暴露出来（挂载到 `window` 上），且需要和子项目版本保持一致。即主项目也配置 `externals` 。这里如果有兼容性问题，可以考虑通过 `props` 把依赖传给子项目。

**Comment by eynol** [comment]
在没有external Vue的时候，window.Vue 这个变量并不存在，因为被webpack等打包器给闭包引入了一个变量Vue。你在使用Router的时候是`Vue.use(VueRouter)` 去注册的。
这个时候，父应用和子应用的Vue版本和router都是互相隔离的，因为闭包。

做的改动是场景a) 和场景b), 这个时候
![.......... :(e=e||self).Vue=t().......](https://user-images.githubusercontent.com/12581247/87849876-aacd3b00-c91e-11ea-9538-5380fff4c867.png)
主应用会在window.Vue上挂载Vue，见上图。

这个改变会导致 
1. 主应用的Webpack会从`window[libraryname]` 去读取配置的`externals`, 主应用是可以执行的。
2. vue-router 在加载的时候 去读取了window.Vue 然后把自己给卖出去了 `if (inBrowser && window.Vue){Vue.use(VueRouter)}`。

子应用就算什么也不改变，它 VueRouter 的这行画蛇添足的副作用的代码也依然在的，就会去读取window.Vue，哎哟，拿到了主应用的Vue，（你想问，为啥不是子应用的Vue呢？你想想看，子应用用的webpack，Vue是个变量，不在window.Vue上，所以提的这个issue标题不对，你对webpack不怎么熟）。 

这个时候 子应用的VueRouter 也把自己卖了，但是window.Vue说，我已经买过VueRouter了，不能再买你了。 这个就是出现问题的原因。



那怎么解呢？ 

1. 配置externals ,但是不叫Vue 改成

```
externals: {
'vue': 'Vue2',// 这个的意思是告诉webpack 去把winodw.Vue2当做‘vue’ 这个模块
'element-ui': 'element-ui2',
'vue-router': 'VueRouter2'
}
```

2. 在主应用刚加载完CDN上的Vue后，立即执行小的函数去把window上的名称改掉。
```
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
<link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
<script src="https://unpkg.com/element-ui/lib/index.js"></script>
<script >
  window.Vue2 = winow.Vue;
  window.Vue2 = undefined;

window['element-ui2'] = window[ 'element-ui2'];
// 自己去掉原来的名称
// .... 等等的其他的CDN依赖
</script>

```

**Comment by shannonliang** [comment]
@eynol @gongshun 感谢回答，我明白了这个问题原因了。
1、主应用externals配置Vue后，对象是绑定在window上，这个没问题。
2、子应用没有做任何配置，但还会执行子应用Router中的```if (inBrowser && window.Vue) {
  window.Vue.use(VueRouter)
}``` 这行代码，执行的window.Vue是存在的，只不过不是子项目的，是主项目的，就产生了副作用redefine的问题。所以让我误以为是window的代理出现问题了。

再次感谢2位大佬的细心解答。

**Comment by humorHan** [comment]
有些麻烦，直接主应用props透传Vue等三方依赖实例不好么？

**Comment by hehaibo123** [comment]
#

> 麻烦，直接主应用道具透传Vue等三方依赖实例不好么？

请问您是怎么处理的

**Comment by zhijunw** [comment]
> @eynol @gongshun 感谢回答，我明白了这个问题原因了。 1、主应用externals配置Vue后，对象是绑定在window上，这个没问题。 2、子应用没有做任何配置，但还会执行子应用Router中的`if (inBrowser && window.Vue) { window.Vue.use(VueRouter) }` 这行代码，执行的window.Vue是存在的，只不过不是子项目的，是主项目的，就产生了副作用redefine的问题。所以让我误以为是window的代理出现问题了。
> 
> 再次感谢2位大佬的细心解答。

请问父应用 externals 配置 Vue  子应用externals 也配置 Vue, 这种情况只需要在子应用 Index.html 引用的链接加上 ignore 就可以了吧

> 在没有external Vue的时候，window.Vue 这个变量并不存在，因为被webpack等打包器给闭包引入了一个变量Vue。你在使用Router的时候是`Vue.use(VueRouter)` 去注册的。 这个时候，父应用和子应用的Vue版本和router都是互相隔离的，因为闭包。
> 
> 做的改动是场景a) 和场景b), 这个时候 ![.......... :(e=e||self).Vue=t().......](https://user-images.githubusercontent.com/12581247/87849876-aacd3b00-c91e-11ea-9538-5380fff4c867.png) 主应用会在window.Vue上挂载Vue，见上图。
> 
> 这个改变会导致
> 
> 1. 主应用的Webpack会从`window[libraryname]` 去读取配置的`externals`, 主应用是可以执行的。
> 2. vue-router 在加载的时候 去读取了window.Vue 然后把自己给卖出去了 `if (inBrowser && window.Vue){Vue.use(VueRouter)}`。
> 
> 子应用就算什么也不改变，它 VueRouter 的这行画蛇添足的副作用的代码也依然在的，就会去读取window.Vue，哎哟，拿到了主应用的Vue，（你想问，为啥不是子应用的Vue呢？你想想看，子应用用的webpack，Vue是个变量，不在window.Vue上，所以提的这个issue标题不对，你对webpack不怎么熟）。
> 
> 这个时候 子应用的VueRouter 也把自己卖了，但是window.Vue说，我已经买过VueRouter了，不能再买你了。 这个就是出现问题的原因。
> 
> 那怎么解呢？
> 
> 1. 配置externals ,但是不叫Vue 改成
> 
> ```
> externals: {
> 'vue': 'Vue2',// 这个的意思是告诉webpack 去把winodw.Vue2当做‘vue’ 这个模块
> 'element-ui': 'element-ui2',
> 'vue-router': 'VueRouter2'
> }
> ```
> 
> 2. 在主应用刚加载完CDN上的Vue后，立即执行小的函数去把window上的名称改掉。
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
> <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
> <script src="https://unpkg.com/element-ui/lib/index.js"></script>
> <script >
>   window.Vue2 = winow.Vue;
>   window.Vue2 = undefined;
> 
> window['element-ui2'] = window[ 'element-ui2'];
> // 自己去掉原来的名称
> // .... 等等的其他的CDN依赖
> </script>
> ```

请问父应用 externals 配置 Vue  子应用externals 也配置 Vue, 这种情况只需要在子应用 Index.html 引用的链接加上 ignore 就可以了吧
