### ISSUE TITLE
无法获取 document 造成的组件问题

### ISSUE THREAD

**Issue by lkiarest** [umijs/qiankun#719]
## What happens?

由于 window 中获取到的 document 对象不是真正的 document 对象，在业务逻辑中使用到此对象比较的地方都会挂掉。
目前是在 vue 组件库 element-ui 中遇到的，在 popper.js 文件中有一段经典的父节点递归查找操作：

```
function getScrollParent(element) {
        var parent = element.parentNode;

        if (!parent) {
            return element;
        }

        // 这个地方判断会挂掉，导致循环继续执行出现异常 ！！！！
        if (parent === root.document) {
            // Firefox puts the scrollTOp value on `documentElement` instead of `body`, we then check which of them is
            // greater than 0 and return the proper element
            if (root.document.body.scrollTop || root.document.body.scrollLeft) {
                return root.document.body;
            } else {
                return root.document.documentElement;
            }
        }
     // ...............
}
```

parent === root.document 这个地方判断始终是 false，导致拿到的对象错误，后续所有的操作都会挂掉。

**Comment by lianer** [comment]
可以把以下代码插入到容器中，暂时来解决这个问题，但从长远来看，还是得想办法解决`递归 parentNode 会访问到沙箱外原始 document 对象的问题`

```js
// 解决报错问题
var rawGetComputedStyle = window.getComputedStyle;
window.getComputedStyle = function (el) {
  if (el === document) return {'overflow': 'auto'};
  return rawGetComputedStyle(el, null);
}

// 解决定位问题
// 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
Object.defineProperty(document, 'scrollLeft', {
  get () {
    return document.documentElement.scrollLeft;
  }
});
Object.defineProperty(document, 'scrollTop', {
  get () {
    return document.documentElement.scrollTop;
  }
});
```

**Comment by renjimin** [comment]
同关注qiankun的最新解决方案

**Comment by zhaozhong** [comment]
> 可以把以下代码插入到容器中，暂时来解决这个问题，但从长远来看，还是得想办法解决`递归 parentNode 会访问到沙箱外原始 document 对象的问题`
> 
> ```js
> // 解决报错问题
> var rawGetComputedStyle = window.getComputedStyle;
> window.getComputedStyle = function (el, pseudoElt) {
>   if (el === document) return {'overflow': 'auto'};
>   return rawGetComputedStyle(el, pseudoElt);
> }
> 
> // 解决定位问题
> // 既然 popper.js 拿了 document 作为 offsetParent 对象，那将错就错，把 document 对象模拟成 document.documentElement 对象，使它可以正常运作
> Object.defineProperty(document, 'scrollLeft', {
>   get () {
>     return document.documentElement.scrollLeft;
>   }
> });
> Object.defineProperty(document, 'scrollTop', {
>   get () {
>     return document.documentElement.scrollTop;
>   }
> });
> ```

亲测有效，感谢！
