### ISSUE TITLE
不同路径使用同一个应用会失败，且第一个使用的成功，后续的失败

### ISSUE THREAD

**Issue by kinsliy** [umijs/qiankun#72]
不同路径使用同一个应用会失败，且第一个使用的成功，后续的失败

![image](https://user-images.githubusercontent.com/11538819/64774726-5717f580-d587-11e9-98b7-7458543cdd2d.png)

## 复现步骤，错误日志以及相关配置

使用上图配置即可

## 相关环境信息

- **Node 版本**：10
- **操作系统**：mac

**Comment by kinsliy** [comment]
@kuitos 这个就像组件复用一样，我可能在A页面用这个应用，C页面也可能需要这个应用，还是说这样的思想是错误的？ 应用不需要复用？

**Comment by kuitos** [comment]
这种场景不应该是A、C两个页面作为两个子应用吗？共同依赖的这个可以只是一个普通组件

**Comment by kinsliy** [comment]
@kuitos 可能我的思想就是这个应用可以复用到组件级别，最开始想的就是一个组件，props传入应用的地址，这个可以当作应用用了

**Comment by Auroraan** [comment]
我只是 添加了一个子应用程序

**Comment by Auroraan** [comment]
我只是添加了一个子应用程序（遗留系统的迁移），出现和你相似的这个错误，想问问你是怎么解决的呢
![image](https://user-images.githubusercontent.com/42374922/64938386-4bcb0f80-d890-11e9-9d6b-355613d213a2.png)

**Comment by kuitos** [comment]
@kinsliy 没有复现你这个报错，提供一个可复现的仓库？

**Comment by kuitos** [comment]
closed via inactive
