### ISSUE TITLE
再提IE兼容-目前的最新版本2.0.16在IE11下报错 error:【对象不支持此操作】

### ISSUE THREAD

**Issue by justJokee** [umijs/qiankun#724]
## What happens?

IE11下在加载子应用时报错 error:【对象不支持此操作】

## 最小可复现仓库

官方仓库中的例子即可复现（主工程/examples/main 子工程为/examples/vue）

## 相关环境信息

- **qiankun 版本**：2.0.16
- **浏览器版本**：IE11
- **操作系统**：windows10

**Comment by justJokee** [comment]
由 [issues#565](https://github.com/umijs/qiankun/issues/565) 认为是single-spa导致此bug的相关回答来看，我在本地建了两个工程进行试验，一个用qiankun加载，一个用single-spa加载，结果single-spa在IE11正常运行，切换到qiankun加载，就报了‘对象不支持此操作’，然后一路debug，基本锁定到 apis.ts中registerMicroApps函数中的 registerApplication 出了问题，再往下就不清楚了，仅提供给各位做一个参考 @kuitos @howel52 @Deturium

**Comment by gudepeng** [comment]
同样碰到。在ie11下兼容问题，最开始报的fetch不支持，然后安装了fetch-polyfill后，在main.js中引入import 'fetcg-polyfill'并在vue.config.js中添加transpileDependencies:['import-html-entry']后，fetch不报错了，但是single-spa.main.js报 Object doesn't support this action

**Comment by gudepeng** [comment]
@howel52 求助

**Comment by gudepeng** [comment]
刚升级了下子项目的qiankun。升级到了最新版本2.0.16。虽然还是报 Object doesn't support this action但是显示的是app-errors.js(11,1)报错

**Comment by lawmancs** [comment]
![image](https://user-images.githubusercontent.com/10524392/86694354-19b4b500-c03e-11ea-995a-7146c1f3c3c7.png)

我也走到这一步，走不下去了，IE确实比较烦，，又绕不开

**Comment by finnlee87** [comment]
同样问题

**Comment by finnlee87** [comment]
The same.
![image](https://user-images.githubusercontent.com/8564495/86696590-29cd9400-c040-11ea-8266-8a3c7b884859.png)

**Comment by gudepeng** [comment]
请问有人解决了吗？项目要上线，比较着急。不想整个都推翻。

**Comment by gongshun** [comment]
直观上是 `single-spa.min.js` 报错，由于代码是是压缩后的代码，不太好排查。

![image](https://user-images.githubusercontent.com/29347231/87400122-fca65600-c5ea-11ea-883b-29f8f8d028df.png)

找到 `node_modules\single-spa\package.json`，找到 `"module": "lib/esm/single-spa.min.js"` 这一行，改成 `"module": "lib/esm/single-spa.dev.js"`，然后重启项目。

发现 `single-spa` 报错原因是 `APP` 加载失败，代码如下：

```js
function handleAppError(err, app, newStatus) {
  var transformedErr = transformErr(err, app, newStatus);
  if (errorHandlers.length) {
    errorHandlers.forEach(function (handler) {
      return handler(transformedErr);
    });
  } else {
    setTimeout(function () {
      throw transformedErr; // 这一行抛出的错误，也就是控制台显示的
    });
  }
}
```

打印了一下APP加载出错的错误，如下：

![image](https://user-images.githubusercontent.com/29347231/87398709-e3040f00-c5e8-11ea-851d-71fbfae0d5c7.png)

这个意思是 `eval` 中的代码报错了吗，可是子项目独立运行时IE11可以打开

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%BB%99-ie-%E6%89%93%E8%A1%A5%E4%B8%81%EF%BC%9F

**Comment by gudepeng** [comment]
@gongshun 请问解决了吗？我这依然不好用。也安装了@babel/preset-env配置了"useBuiltIns": "entry"

**Comment by gudepeng** [comment]
@kuitos  能给个官方集成好用的demo吗？

**Comment by gongshun** [comment]
@gudepeng 解决了，入口文件新增这几个就可以了：
```js
import 'whatwg-fetch';
import 'core-js/stable/promise';
import 'core-js/stable/symbol';
import 'core-js/stable/string/starts-with';
import 'core-js/web/url';
```
https://github.com/gongshun/qiankun-vue-demo

**Comment by guokewei** [comment]
gongshun  IE9,10 兼容吗
