### ISSUE TITLE
应用如何部署在二级目录

### ISSUE THREAD

**Issue by freedom2012** [umijs/qiankun#727]
由于公司只能对外提供80端口，所以只能通过nginx的80端口地址匹配进行转发，转发到qiankun主应用（2750端口）没问题，但是主应用加载子应用（2753端口）的时候，即使entry加上二级目录，qiankun好像把二级目录截取掉了，例如：entry: "http://localhost/app"，请求子应用的时候变成”http://localhost"。请问大神如何处理？

**Comment by kuitos** [comment]
http://localhost/app -> http://localhost/app/

前者相对路径的 context 是 http://localhost，后者是 http://localhost/app

**Comment by gongshun** [comment]
@kuitos 这个问题好像是个 `bug`，当你访问 `http://localhost/app` 时，实际请求文件是 `http://localhost/app/index.html`，这时相对路径是 `http://localhost/app` 没错的，而你的代码里面，默认他带了 `index.html` ，去掉了 `path` 的最后一个值，这里是不是应该先判断一下，最后一个 `path` 是路径还是文件，如果是文件，则去掉 `path` 的最后一位。或者说，文档的入口文件写法示例应该注明一下，如果是二级目录需要强制带上 `index.html`。

源码：https://github.com/kuitos/import-html-entry/blob/f72824ac3e09e6ecfd25120cadf0dfadd78adaae/src/utils.js#L90

**Comment by kuitos** [comment]
并不是这样的。
你可以试下通过 `http://localhost/app` 和 `http://localhost/app/` 两个路径 serve 一个 html，然后在 html 里引入一个相对路径的资源，看看浏览器解析出来的地址是什么样的

**Comment by gongshun** [comment]
> 并不是这样的。
> 你可以试下通过 `http://localhost/app` 和 `http://localhost/app/` 两个路径 serve 一个 html，然后在 html 里引入一个相对路径的资源，看看浏览器解析出来的地址是什么样的

的确是这样。

![image](https://user-images.githubusercontent.com/29347231/86704842-dc552500-c047-11ea-8488-36c35830ad44.png)


![image](https://user-images.githubusercontent.com/29347231/86704763-ca738200-c047-11ea-9e28-3fa2f2c93124.png)

**Comment by hql7** [comment]
https://juejin.cn/post/6844904143413313549#heading-22 快速调整为双端口方案
