### ISSUE TITLE
[Feature Request] 加载子应用禁用缓存

### ISSUE THREAD

**Issue by Kermit-Xuan** [umijs/qiankun#730]
## Background

目前加载每个子应用的时候，是用的 fetch 加载 entry，这样有个问题就是后期子应用更新后，fetch 请求到的还是缓存(上次的内容)，当然也可以通过关闭浏览器缓存的方法去解决这个，但是系统不止是开发人员使用，还有运营人员，所以这个成本有点高。

## Proposal

可以在每次加载子应用的 entry 时加上随机参数去禁用缓存，这样即使子应用未更新，浏览器请求其资源文件时会使用缓存，如果子应用更新，会自动请求新的资源文件地址。

**Comment by kuitos** [comment]
1. 缓存问题通常是你的工程部署策略不对，fetch entry 时加时间戳只是头痛医头脚痛医脚的解法，并不能真正解决问题，比如你的工程里用 img 标签引用了一张图片，一样会出问题
2. 如果一定要 fetch 时候加时间戳，可以使用自定义 fetch，参考 https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95

**Comment by Kermit-Xuan** [comment]
比如部署策略哪里有问题？目前部署使用的是SPA History模式

**Comment by kuitos** [comment]
常见的工程问题
1. 静态服务器针对 entry html 的缓存过期策略设置不合理或者未生效
2. 应用内静态资源 （js/css/image）未使用 hash 模式

**Comment by Kermit-Xuan** [comment]
目前情况是这样的，entry 的 html 是没有设置缓存的，缓存是浏览器的 disk 缓存

**Comment by Kermit-Xuan** [comment]
导致子应用更新后，还是从 disk 里面读取。

**Comment by kuitos** [comment]
缓存过期策略没生效

**Comment by gongshun** [comment]
`index.html` 配置一个响应头 `Cache-Control no-cache;`

**Comment by fengxueding3** [comment]
我也遇到这样的问题，子应用每次发版，都出现缓存问题，必须手动清除缓存。如果在entry增加no-cache，应该是可以解决，但是都不能利用缓存带来的优化效果了。
我目前也是没有设缓存策略，是要服务器增加缓存策略，Etag ?
@Kermit-Xuan 你后面是怎么解决的？

**Comment by Kermit-Xuan** [comment]
就是在服务端给 entry 加 `no-cache`，这样只是每次请求入口的 `index.html` 不缓存，资源还是有缓存的。

**Comment by jessjava** [comment]
> 就是在服务端给 entry 加 `no-cache`，这样只是每次请求入口的 `index.html` 不缓存，资源还是有缓存的。

重新部署的话index.html引入的资源哈希就会改变了，应该没问题。

**Comment by uWydnA** [comment]
> 我也遇到这样的问题，子应用每次发版，都出现缓存问题，必须手动清除缓存。如果在entry增加no-cache，应该是可以解决，但是都不能利用缓存带来的优化效果了。
> 我目前也是没有设缓存策略，是要服务器增加缓存策略，Etag ?
> @Kermit-Xuan 你后面是怎么解决的？

有一个东西叫协商缓存.... cache-control + etag + last-modified

**Comment by 1992106** [comment]
> Cache-Control no-cache;

怎么加？是通过nginx吗？方便发一下配置吗？

**Comment by uWydnA** [comment]
> > Cache-Control no-cache;
> 
> 怎么加？是通过nginx吗？方便发一下配置吗？

在nginx的server里加
```nginx 
expires off;
add_header Cache-Control "no-cache";
```

**Comment by qiufeng2016** [comment]
相同的问题，目前微服务路由采用的是hash方案，服务加载完成后html被缓存，无法通过浏览器缓存策略更新至html，导致资源重新部署后js加载异常，有没有可以解决的方案？

**Comment by Wulakaka** [comment]
> 1. 缓存问题通常是你的工程部署策略不对，fetch entry 时加时间戳只是头痛医头脚痛医脚的解法，并不能真正解决问题，比如你的工程里用 img 标签引用了一张图片，一样会出问题
> 2. 如果一定要 fetch 时候加时间戳，可以使用自定义 fetch，参考 https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95

自定义 fetch 并不能解决问题，第二次加载不会再次 fetch

**Comment by flyzhouke** [comment]
主要解决加载的html页面不被缓存 

<img width="636" height="189" alt="Image" src="https://github.com/user-attachments/assets/3bf783a0-5c7a-4e37-b0dd-24c25a8e0af3" />
