### ISSUE TITLE
[Bug]各个子应用绑定的Vue原型方法会互相干扰

### ISSUE THREAD

**Issue by masongzhi** [umijs/qiankun#732]
# 各个子应用绑定的Vue原型方法会互相干扰

## What happens?

Vue在主应用使用cdn加载，子应用使用externals，不用子应用绑定在Vue原型上的方法会被覆盖，没有做到Vue的沙箱隔离

## 相关环境信息

- **qiankun 版本**: 2.0.15
- **浏览器版本**：chrome 64
- **操作系统**：macOs

**Comment by yu530feng** [comment]
我的理解是子应用使用externals后，子应用下window.Vue是不存在的，因此set（Vue.prototype.$aaa=aaa）时, 是设置到主应用下的window.Vue上的. 因此切换子应用后，会重复上述过程。所以并不存在沙箱隔离。沙箱隔离仅针对子应用下全局变量。

**Comment by lkiarest** [comment]
> 我的理解是子应用使用externals后，子应用下window.Vue是不存在的，因此set（Vue.prototype.$aaa=aaa）时, 是设置到主应用下的window.Vue上的. 因此切换子应用后，会重复上述过程。所以并不存在沙箱隔离。沙箱隔离仅针对子应用下全局变量。

按当前的设计，你这种情况需要自行处理隔离，比如在子应用 mount 的时候重新挂载 $aaa。
但是如果遇到同时运行多个子应用的情况就不好办了。

**Comment by bowencool** [comment]
> > 我的理解是子应用使用externals后，子应用下window.Vue是不存在的，因此set（Vue.prototype.$aaa=aaa）时, 是设置到主应用下的window.Vue上的. 因此切换子应用后，会重复上述过程。所以并不存在沙箱隔离。沙箱隔离仅针对子应用下全局变量。
> 
> 按当前的设计，你这种情况需要自行处理隔离，比如在子应用 mount 的时候重新挂载 $aaa。
> 但是如果遇到同时运行多个子应用的情况就不好办了。

很多插件都会这样：
``` js
if (inBrowser && window.Vue) {
  window.Vue.use(VueRouter)
}
```
