### ISSUE TITLE
[Bug]umi生成的子项目，dev-server的sockethost走了主项目的port导致热更新失效

### ISSUE THREAD

**Issue by bluescurry** [umijs/qiankun#733]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

主项目是使用vue-cli3创建的，子项目是使用umi创建的。子项目的port是8066，主项目的是port是8080。在主项目中，子项目devServer的Socket请求走了主项目的port，导致socket404了，请问这个问题怎么解决呢？

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
实现不太好复现...

## 相关环境信息

- **qiankun 版本**: 2.0.15
- **浏览器版本**：Chrome 83.0.4103.116
- **操作系统**：mac

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/umi/issues/4441
