### ISSUE TITLE
demo中的Angular子应用如何拿到主应用通信的GlobalState

### ISSUE THREAD

**Issue by sxhieen** [umijs/qiankun#735]
其他两个框架demo有示例

**Comment by sxhieen** [comment]
尝试了一下，在single-spa.d.ts的export type AppProps里再加上onGlobalStateChange，setGlobalState和offGlobalStateChange，好像可以

**Comment by kuitos** [comment]
singleSpaPropsSubject 里有
https://github.com/umijs/qiankun/blob/master/examples/angular9/src/single-spa/single-spa-props.ts#L4
