### ISSUE TITLE
iconfont在子应用中无法出现

### ISSUE THREAD

**Issue by cpa0701** [umijs/qiankun#736]
## What happens?
iconfont在子应用中无法正常加载

## Mini Showcase Repository(REQUIRED)

在父应用和子应用中都引入了iconfont.js，只有父应用的icon生效了，子应用无法加载

## How To Reproduce

![image](https://user-images.githubusercontent.com/24648209/86749133-957b2580-c06f-11ea-9f18-6f5eefcee130.png)

![image](https://user-images.githubusercontent.com/24648209/86748633-34535200-c06f-11ea-8172-c1a89bf5cf74.png)

![image](https://user-images.githubusercontent.com/24648209/86748755-4b923f80-c06f-11ea-85cd-cd519798acce.png)

## Context

- **qiankun Version**:2.0.16

**Comment by cpa0701** [comment]
解决了，要关闭沙盒模式。。。。。。。

**Comment by jxs7754** [comment]
@cpa0701 如果需要开启css沙盒模式，有解决办法吗？

**Comment by cpa0701** [comment]
> @cpa0701 如果需要开启css沙盒模式，有解决办法吗？

不知道，问问大神吧

**Comment by PHenryy** [comment]
same problem

**Comment by kukudehu829** [comment]
使用url-loader转一下就可以了，是因为主应用中在打包后不可以使用相对地址造成的
