### ISSUE TITLE
路由劫持，当触发过一次微前端加载后，如果失败，点击其他路由还是会去尝试重新加载这个失败的微前端

### ISSUE THREAD

**Issue by zjscy666** [umijs/qiankun#739]
## What happens?

路由劫持，当触发过一次微前端加载后，如果失败，点击其他路由还是会去尝试重新加载这个失败的微前端，但是如果用location.href直接刷新，那就没问题了！但是微前端这个应该尽量少加载，刷新是不得已的最后手段！如何才能在为前端加载失败后，点击其他路由，微前端不会重复报**应用died

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
检查自己的activeRule配置，是否多个路由触发了同一个失败的微应用。
如果不是这个问题，请提供可复现仓库并reopen这个issue

**Comment by han-neil** [comment]
我也遇到了同样的问题，怎么解决的，老铁

**Comment by zjscy666** [comment]
let arr = [
      {
        name: 'vue',
        entry: '//localhost:7101',
        container: '#subapp-viewport',
        // render,
        activeRule: ['/subapp/vue']
      },
      {
        name: 'react15',
        entry: '//localhost:7100',
        container: '#subapp-viewport',
        activeRule: '/subapp/react15',
      }tigongge
    ];
最近2周多一直在处理可视化的问题，刚刚看issue，我的activeRule是这样的，这个配置按照文档的规则是可行的，除非微前端只按照/subapp匹配，大佬，看下我这配置的activeRule有没有问题，如果没有问题，我提供个可复现的demo把
![image](https://user-images.githubusercontent.com/22449281/88786508-310e3a80-d1c5-11ea-8458-868ec3700f10.png)
