### ISSUE TITLE
设置了public-path, 静态资源依旧404

### ISSUE THREAD

**Issue by codingzhou** [umijs/qiankun#740]
主工程： vue cli搭建
子工程：
1. vue 搭建的micro project 设置public path 资源请求不报404
2. angular 搭建的micro project设置public path无效, 资源请求报错404
![image](https://user-images.githubusercontent.com/14120629/87016863-d5721200-c201-11ea-98ad-2529b6ce396a.png)
![image](https://user-images.githubusercontent.com/14120629/87016872-da36c600-c201-11ea-8bd3-1b1c9be6e488.png)
![image](https://user-images.githubusercontent.com/14120629/87016918-e7ec4b80-c201-11ea-9b6f-3aeccb840b66.png)
复现代码：
https://github.com/codingzhou/micro-template-for-qiankun/blob/master/micro-app-angular/src/public-path.js
https://github.com/codingzhou/micro-template-for-qiankun/blob/master/micro-app-vue/src/public-path.js

**Comment by kuitos** [comment]
地址是你自己代码里拼的 https://github.com/codingzhou/micro-template-for-qiankun/blob/89ac75c952592f846112bb8e0dc119a135116261/micro-app-angular/src/app/app.component.ts#L10

**Comment by wjingxian2008** [comment]
> 地址是你自己代码里拼的 https://github.com/codingzhou/micro-template-for-qiankun/blob/89ac75c952592f846112bb8e0dc119a135116261/micro-app-angular/src/app/app.component.ts#L10

不能自己拼接吗？要怎么处理这里，img标签也不能用src=‘’ 类似这样吗？如果是，要怎么处理呢？

**Comment by wjingxian2008** [comment]
> 主工程： vue cli搭建
> 子工程：
> 
> 1. vue 搭建的micro project 设置public path 资源请求不报404
> 2. angular 搭建的micro project设置public path无效, 资源请求报错404
>    ![image](https://user-images.githubusercontent.com/14120629/87016863-d5721200-c201-11ea-98ad-2529b6ce396a.png)
>    ![image](https://user-images.githubusercontent.com/14120629/87016872-da36c600-c201-11ea-8bd3-1b1c9be6e488.png)
>    ![image](https://user-images.githubusercontent.com/14120629/87016918-e7ec4b80-c201-11ea-9b6f-3aeccb840b66.png)
>    复现代码：
>    https://github.com/codingzhou/micro-template-for-qiankun/blob/master/micro-app-angular/src/public-path.js
>    https://github.com/codingzhou/micro-template-for-qiankun/blob/master/micro-app-vue/src/public-path.js

你的问题解决了吗，我也遇到了，不知如何处理
