### ISSUE TITLE
[Bug]angular7微应用加载失败，不能识别生命周期函数

### ISSUE THREAD

**Issue by wudith** [umijs/qiankun#741]
按single-spa官网封装的基于angular7的子应用，使用single-spa-angular:build启动，已导出三个必要的生命周期函数和webpack配置。
在qiankun主应用加载失败，识别不到生命周期函数：[qiankun] You need to export lifecycle functions in my-app entry。但是在single-spa官方示例下是可以成功识别并加载：https://github.com/joeldenning/coexisting-angular-microfrontends

## 复现步骤，错误日志以及相关配置

1、使用Angular schematics新建一个angular7的子应用：参考https://zh-hans.single-spa.js.org/docs/ecosystem-angular#angular-cli
（需要手动将single-spa-angular版本降至3.6.0，并增加APP_BASE_HREF路由配置）

 2、修改qiankun官网示例的main的multiple.js文件配置为angular7子应用的地址：
const app1 = loadMicroApp(
  { name: 'my-app', entry: '//localhost:4200', container: '#react15' },
  {
    sandbox: {
      // strictStyleIsolation: true,
    },
  },
);

3、启动npm run start:multiple

## 相关环境信息

- **qiankun 版本**：2.0.15
- **single-spa-angular 版本**：3.6.0
- **浏览器版本**：Google Chrome 83.0.4103.116
- **操作系统**：win8 64位

**Comment by kuitos** [comment]
see https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

如果不能解决，请提供可复现仓库并 reopen issue

**Comment by wudith** [comment]
> see https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
> 
> 如果不能解决，请提供可复现仓库并 reopen issue


复现仓库地址
https://github.com/wudith/qiankun4angular7

请问如何reopen issue？
