### ISSUE TITLE
loadMicroApp 再跳转页面后卡死

### ISSUE THREAD

**Issue by ldgoooo** [umijs/qiankun#744]
Throttling history state changes to prevent the browser from hanging.
/Users/xxx/works/projects/nong/lyl-electron/node_modules/single-spa/lib/umd/single-spa.min.js:2 Throttling history state changes to prevent the browser from hanging.
(anonymous) @ /Users/xxx/works/projects/nong/lyl-electron/node_modules/single-spa/lib/umd/single-spa.min.js:2
pushState @ /Users/xxx/works/projects/nong/lyl-electron/node_modules/vue-router/dist/vue-router.common.js:1697
replaceState @ /Users/xxx/works/projects/nong/lyl-electron/node_modules/vue-router/dist/vue-router.common.js:1708

**Comment by ldgoooo** [comment]
handleSendSms(){
  		
  		if(this.phone.length!=11){
  			this.$Message.error('请输入正确的手机号')
  			return
  		}
      this.microApp = loadMicroApp(
        { name: 'spin-validate', entry: '//localhost:3012', container: this.$refs.spin,singular:true, props: { phone: this.phone,uid:"lyl",data:"" } },  
      );

 beforeDestroy(){
    this.microApp.unmount();
  }

 this.$router.push({path: '/'}) //路由跳转后卡死

**Comment by ldgoooo** [comment]
![image](https://user-images.githubusercontent.com/2022063/87116778-48829380-c2a9-11ea-8fd6-6d4aedcb6545.png)

**Comment by kuitos** [comment]
按照模板提交 issue
提供可复现仓库后可自行 reopen
