### ISSUE TITLE
proxy.test.prototype is undefined

### ISSUE THREAD

**Issue by chairui2001** [umijs/qiankun#748]
## What happens?

The third-party js library is used in the sub application, the errors like “Cannot set property 'classname' of undefined” appear, because there are some codes like "window.xxx.prototype.classname = 'yyy'" in it. 
It's ok when then sub app run as a stand alone application，but not in qiankun framework.

## Mini Showcase Repository(REQUIRED)

INPUT:      `window.test=function(a,b,c){this.a=a,this.b=b,this.c=c}`
RESULT:    ƒ (a,b,c){this.a=a,this.b=b,this.c=c}

INPUT:      `window.test.prototype`
RESULT:    {constructor: ƒ}

INPUT:      `proxy.test=function(a,b,c){this.a=a,this.b=b,this.c=c}`
RESULT:    ƒ (a,b,c){this.a=a,this.b=b,this.c=c}

INPUT:      `proxy.test.prototype`
RESULT:    undefined

## How To Reproduce

Mark sure the system is showing any sub app now. 
Then the "proxy" is available.
Press F12 to open the dev tool, then input below in console pannel：

```
window.test=function(a,b,c){this.a=a,this.b=b,this.c=c}
window.test.prototype
proxy.test=function(a,b,c){this.a=a,this.b=b,this.c=c}
proxy.test.prototype
```

## Context

- **qiankun Version**: 2.0.16
- **Platform Version**: WIN 10
- **Browser Version**: Chrome 80.0.3987.132

**Comment by node-rookie** [comment]
遇到了同样的问题

**Comment by node-rookie** [comment]
@kuitos 有没有什么解决方案呢  一些三方依赖库用不了

**Comment by node-rookie** [comment]
@chairui2001 did you solve this problem？

**Comment by whereiscode** [comment]
@node-rookie 我也是这个问题

**Comment by whereiscode** [comment]
这个问题我快调试哭了 4天了

**Comment by whereiscode** [comment]
我目前解决了 通过把window传给子应用
