### ISSUE TITLE
如何将子应用的路由信息传给父应用？比如meta

### ISSUE THREAD

**Issue by cpa0701** [umijs/qiankun#749]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

如应用无法获取子应用路由中的meta信息
子应用
![image](https://user-images.githubusercontent.com/24648209/87217910-eeed9800-c380-11ea-8446-41b831c69bae.png)
父应用
![image](https://user-images.githubusercontent.com/24648209/87217929-0af13980-c381-11ea-895f-1516246f0ec3.png)

- **qiankun 版本**2.0.16
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api/#initglobalstate-state
可以通过 `initGlobalState` 传递数据给父项目

**Comment by cpa0701** [comment]
> https://qiankun.umijs.org/zh/api/#initglobalstate-state
> 可以通过 `initGlobalState` 传递数据给父项目

**Comment by cpa0701** [comment]
> https://qiankun.umijs.org/zh/api/#initglobalstate-state
> 可以通过 `initGlobalState` 传递数据给父项目

说起initGlobalState ，我发现setGlobalState会先去执行以下当前应用对应的actions，
比如actions.setGlobalState(‘user/login’)，它会同时触发当前应用中的user/login这个actions，而不是只执行我监听的事件，很不方便;所以我改用@ice/stark-data了，不知道你有没有遇到过类似经历

**Comment by gongshun** [comment]
> 说起initGlobalState ，我发现setGlobalState会先去执行以下当前应用对应的actions，
> 比如actions.setGlobalState(‘user/login’)，它会同时触发当前应用中的user/login这个actions，而不是只执行我监听的事件，很不方便;所以我改用@ice/stark-data了，不知道你有没有遇到过类似经历

它就是这样设计的 :joy:，如果都是vue项目，可以考虑将父项目的 `store` 传过去，还能双向绑定

**Comment by cpa0701** [comment]
> > 说起initGlobalState ，我发现setGlobalState会先去执行以下当前应用对应的actions，
> > 比如actions.setGlobalState(‘user/login’)，它会同时触发当前应用中的user/login这个actions，而不是只执行我监听的事件，很不方便;所以我改用@ice/stark-data了，不知道你有没有遇到过类似经历
> 
> 它就是这样设计的 😂，如果都是vue项目，可以考虑将父项目的 `store` 传过去，还能双向绑定

好吧。。。

**Comment by kuitos** [comment]
> 比如actions.setGlobalState(‘user/login’)，它会同时触发当前应用中的user/login这个actions，而不是只执行我监听的事件，很不方便

这是个啥？能给个具体的例子？
