### ISSUE TITLE
single-spa.min.js:258 Uncaught sub-a: Application 'sub-a' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by wsq1992** [umijs/qiankun#75]
我使用create-react-app生成的三个项目，一个主应用，两个子应用a和b。我在a切换到b的时候出现出现这个错误 ： single-spa.min.js:258 Uncaught sub-a: Application 'sub-a' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element. 我对比你给的例子之后，发现a切换到b的时候是先执行的render方法，之后在执行的a应用提供的卸载方法。以至于a在执行卸载方法的时候找不到a应用的根节点。你给的例子是先执行的卸载，然后在执行render的？？？
node v9.11.2
npm 5.6.0
webpack 4.39.1

**Comment by kuitos** [comment]
请遵循 issue 模板提交问题，否则您的问题会被关闭
