### ISSUE TITLE
[Bug]]angular6-7版本微应用加载失败

### ISSUE THREAD

**Issue by wudith** [umijs/qiankun#753]
按single-spa官网封装的基于angular7的子应用，使用single-spa-angular:build启动，已导出三个必要的生命周期函数和webpack配置。
在qiankun主应用加载失败，识别不到生命周期函数：[qiankun] You need to export lifecycle functions in my-app entry。但是在single-spa官方示例下是可以成功识别并加载：https://github.com/joeldenning/coexisting-angular-microfrontends

已按此FAQ排查未能解决： https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry

## 复现步骤，错误日志以及相关配置

1、使用Angular schematics新建一个angular7的子应用：参考https://zh-hans.single-spa.js.org/docs/ecosystem-angular#angular-cli
（需要手动将single-spa-angular版本降至3.6.0，并增加APP_BASE_HREF路由配置）

 2、修改qiankun官网示例的main的multiple.js文件配置为angular7子应用的地址：
const app1 = loadMicroApp(
  { name: 'my-app', entry: '//localhost:4208', container: '#react15' },
  {
    sandbox: {
      // strictStyleIsolation: true,
    },
  },
);

3、启动npm run start:multiple

## 相关环境信息

- **qiankun 版本**：2.0.15
- **single-spa-angular 版本**：3.6.0
- **浏览器版本**：Google Chrome 83.0.4103.116
- **操作系统**：win8 64位

## 复现仓库地址

https://github.com/wudith/qiankun4angular7

**Comment by wudith** [comment]
仓储增加使用@angular-builders/custom-webpack:browser作为builder的angular7子应用工程示例，参考qiankun官方github的angular9的配置，依然出现加载失败

**Comment by xiaopengzhu** [comment]
是KPI项目吧？感觉就几个静态页面的项目能用，加上登录,  权限，动态加载等特性就各种报错，完全不像介绍文档中说的那么简单。

**Comment by tidemaker** [comment]
解决了吗？为什么就关闭了？

**Comment by wudith** [comment]
没解决，项目决定升级版本，不用再解决了，谢谢



---原始邮件---
发件人: "vincent"<notifications@github.com&gt;
发送时间: 2020年9月14日(周一) 下午5:51
收件人: "umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"wudith"<176163187@qq.com&gt;;
主题: Re: [umijs/qiankun] [Bug]]angular7微应用加载失败 (#753)




 
解决了吗？为什么就关闭了？
