### ISSUE TITLE
[Feature Request]qiankun新版本，能否支持url中如果前缀是主应用的，有懒加载文件，不要挂到子应用里。

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#754]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

2.0.16后，根据url判断是否属于子应用，由子应用接管所有的文件懒加载，但是如果打开这个url时，url的前半部分是属于主应用的，也有懒加载，如何能够让这部分的静态文件懒加载到主应用里

**Comment by kuitos** [comment]
没看明白，这个跟 2.0.16 无关吧，之前的版本符合预期？

给个具体的示例或者仓库吧

**Comment by waltbest2** [comment]
我配置了singular。

2.0.11是可以，比如/a/b。是子应用，但是/a是左侧菜单，这个左侧菜单是主应用的，/b对应的是右边部分
所以直接访问/a/b时，qiankun判断是子应用，但是加载左侧菜单需要懒加载一些js

2.0.11时候，appendChild是被主应用接管，即使主应用懒加载一些js也不会有问题。但是2.0.16开始，/a依赖的js也被认为是/b依赖的。

**Comment by kuitos** [comment]
同一个问题 https://github.com/umijs/qiankun/issues/578
这个先关了
