### ISSUE TITLE
子应用mount 内容空白

### ISSUE THREAD

**Issue by C-somnus** [umijs/qiankun#757]
问题：
子应用mount 内容空白

![Snipaste_2020-07-14_17-41-11](https://user-images.githubusercontent.com/17853356/87410980-9aa11d00-c5f9-11ea-84a2-1d2375c35614.png)
![Snipaste_2020-07-14_17-41-30](https://user-images.githubusercontent.com/17853356/87410986-9e34a400-c5f9-11ea-8454-ecc9b3083f28.png)

**Comment by kuitos** [comment]
使用模板提交 issue
