### ISSUE TITLE
关于qiankun的nginx部署问题

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/qiankun#766]
想请教一下大家都是如何部署qiankun的父子项目的。
我目前的想法是父项目配一个路由地址，如 a.test.com
子项目配一个，如 b.test.com
然后修改父项目的entry: '//localhost:7001',为b.test.com
但是这样的话不是还需要维护一份dev的qiankun配置和生产的qiankun配置吗。
或者是否有其他更简单的方式

另外是否有qiankun的交流群，官网的交流群人数已经满了

**Comment by howel52** [comment]
duplicate: https://github.com/umijs/plugins/issues/282#issuecomment-658693040

**Comment by Luxiaoshi** [comment]
@howel52 大佬，qiankun交流群有吗，钉钉的那个1群满了

**Comment by howel52** [comment]
官网有：https://qiankun.umijs.org/#community

![image](https://user-images.githubusercontent.com/9854818/87536453-baa11100-c6cb-11ea-9deb-097e535845ed.png)

**Comment by ldhfx** [comment]
> 官网有：https://qiankun.umijs.org/#community
> 
> ![image](https://user-images.githubusercontent.com/9854818/87536453-baa11100-c6cb-11ea-9deb-097e535845ed.png)



> 官网有：https://qiankun.umijs.org/#community
> 
> ![image](https://user-images.githubusercontent.com/9854818/87536453-baa11100-c6cb-11ea-9deb-097e535845ed.png)

谢谢

**Comment by guodongzzzZ** [comment]
@howel52  大佬，新的交流群又满了，还有新的群吗
