### ISSUE TITLE
[提问]关于demo 中子项目 webpack 配置的 library 项的疑问

### ISSUE THREAD

**Issue by gongshun** [umijs/qiankun#770]
https://github.com/umijs/qiankun/blob/536e78c95e81919f330909e6950a5f390bc20090/examples/vue/vue.config.js#L2
https://github.com/umijs/qiankun/blob/536e78c95e81919f330909e6950a5f390bc20090/examples/vue/vue.config.js#L45

`library` 这个值，打包后对应这个，没错吧：

![image](https://user-images.githubusercontent.com/29347231/87623231-86733200-c757-11ea-9ebf-4acbfe324ad5.png)

然后 `qiankun` 取子项目暴露的生命周期也是根据 `appName` 来的。

我有两点疑问：
1. 按理说 `library` 设置为 `${name}` 就可以了，为什么要加后面的`-[name]`，我看 `demo` 的提交历史，一开始写的就是 `${name}` 
2.  加了 `-[name]` ，和 `appName` 就对不上了，为什么 `qiankun` 还能取到生命周期，`demo` 可以正常运行。

我在尝试 `qiankun` 项目嵌套 `qiankun` 项目时发现这个问题，打开“孙子”项目，报错生命周期找不到，然后将 `webpack` 配置的 `library` 项值去掉 `-[name]`，就可以正常加载

**Comment by stoneChen** [comment]
qiankun是通过查找【在当前子应用挂载周期内，最后一个挂在到window上的全局变量】来找到子应用入口的。
不过这个『最后一个』的判断姿势我认为值得商榷，我这边遇到了问题。

**Comment by gongshun** [comment]
> qiankun是通过查找【在当前子应用挂载周期内，最后一个挂在到window上的全局变量】来找到子应用入口的。
> 不过这个『最后一个』的判断姿势我认为值得商榷，我这边遇到了问题。see #777

明白了，即使 `library` 和 `appName` 没对上，也能跑起来，是因为 `qiankun` 优先取【最后一个挂在到 `window` 上的全局变量】，按 `appName` 取是降级方案。

但是 `demo` 中 `library` 和 `appName` 没对上，降级方案也是行不通的

**Comment by gongshun** [comment]
@kuitos  ` library: ${name}-[name], ` 这个配置是有其他的目的，还是说这是个 `bug`

**Comment by stoneChen** [comment]
只要在所有子应用里不重复就行，这么配置的前提是默认所有子应用的package.json中name是不相同的。
如果你能保证library值不重复，子应用里写死也是可以的。

**Comment by kuitos** [comment]
多 entry 或者多 chunk 的场景，只配置 `library: `${name}`` 几个 chunk 的 umd 导出就重名了

**Comment by gongshun** [comment]
> 多 entry 或者多 chunk 的场景，只配置 `library: name` 几个 chunk 的 umd 导出就重名了

的确是这样，但是![image](https://user-images.githubusercontent.com/29347231/88158005-10cb0280-cc3e-11ea-8587-7601b8e7dffc.png)这么配置，你的降级方案也行不通吧
