### ISSUE TITLE
如果sandbox设置为{ strictStyleIsolation: true }，子应用的@font-face设置的字体不会加载

### ISSUE THREAD

**Issue by node-rookie** [umijs/qiankun#771]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

如果sandbox设置为{ strictStyleIsolation: true }，子应用的@font-face设置的字体不会加载
## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本** 2.0.16
- **浏览器版本**：chrome 85.0.4161.3
- **操作系统**：macos

**Comment by teenth** [comment]
大佬解决了吗

**Comment by 1206497655** [comment]
同问，大佬解决了吗

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/92551978-146c2480-f292-11ea-8288-3a94525b31de.png)

https://www.google.com.hk/search?q=shadow+dom+font+face&oq=shadow+dom+font+face

https://stackoverflow.com/questions/54546007/why-doesnt-font-awesome-work-in-my-shadow-dom
