### ISSUE TITLE
可以升级下@babel/runtime版本吗 现有版本会报错

### ISSUE THREAD

**Issue by RedingSir** [umijs/qiankun#776]
当前依赖 "@babel/runtime": "^7.5.5" 会导致 'TypeError: (0 , _typeof3.default) is not a function' 的编译错误 查看babel/runtime 已有issue 并在此issue中修复 https://github.com/babel/babel/pull/11049 

## What happens?

当前依赖 "@babel/runtime": "^7.5.5" 会导致 'TypeError: (0 , _typeof3.default) is not a function' 的编译错误

## 最小可复现仓库

https://github.com/babel/babel/issues/11036

## 相关环境信息

- **qiankun 版本**
所有版本
- **浏览器版本**：
all
- **操作系统**：
macos

**Comment by kuitos** [comment]
没锁版本，自己 npm update 一下
