### ISSUE TITLE
[Bug][带复现repo]查找子应用入口的"最后一个挂载到window下变量"的问题

### ISSUE THREAD

**Issue by stoneChen** [umijs/qiankun#777]
## What happens?

当子应用内存在`window.xxx = yyy` 这样的代码时，主应用查找不到子应用的生命周期函数。

## 最小可复现仓库

https://github.com/stoneChen/qiankun-test/tree/issue_last-window-variable

## 复现步骤，错误日志以及相关配置

1. clone复现仓库
2. cd到micro-app, npm i && npm start.
3. cd到master-app, npm i && npm start.

主应用报错：
![image](https://user-images.githubusercontent.com/4470552/87846676-36859e00-c904-11ea-9f88-1455e131681e.png)

子应用内仅有一句`window.console = window.console || (() => {});` 即可复现此问题。
调试信息：
![image](https://user-images.githubusercontent.com/4470552/87846647-f32b2f80-c903-11ea-9f30-17b18c03c10a.png)

通过设置主应用内load子应用name为`micro-app-main`可让qiankun找到子应用，但这是兜底逻辑，qiankun仍然会打印警告(还存在少量性能损耗)。

依赖`for in`语法来查找最后一个挂载的window属性，我认为是不靠谱的，而且不同浏览器的遍历顺序可能是有差别的。
我通过简单的修改乾坤代码：在proxy的set方法内记录最后一个被设置的window属性名，然后在取值时使用这个属性名，基本验证是可行的(见下图)，请作者考虑一下是否合理。
![image](https://user-images.githubusercontent.com/4470552/87847463-29b87880-c90b-11ea-826a-88e2254a07d3.png)

![image](https://user-images.githubusercontent.com/4470552/87847440-eeb64500-c90a-11ea-877a-b8b5cc4f7971.png)

## 相关环境信息

- **qiankun 版本**: 2.0.16
- **浏览器版本**：83.0.4103.116
- **操作系统**：mac os 10.15.5

**Comment by kuitos** [comment]
> 子应用内仅有一句window.console = window.console || (() => {});

umd 包里不存在这种情况

> 依赖for in语法来查找最后一个挂载的window属性，我认为是不靠谱的，而且不同浏览器的遍历顺序可能是有差别的。

see https://github.com/umijs/qiankun/issues/485#issuecomment-617677419

**Comment by stoneChen** [comment]
> > 子应用内仅有一句window.console = window.console || (() => {});
> 
> umd 包里不存在这种情况
@kuitos 
这个没理解。我的意思是，子应用内源码存在`window.console = window.console || (() => {});`即可复现此问题，导致按照qiankun默认的查找逻辑会出问题。

另外，即使将来所有浏览器遍历属性顺序是一致的，但按照现有逻辑，仍然在查找效率上存在疑问(循环+排除iframe)。
在fakeWindow的set方法内记录最后一次添加的属性(对应umd包的最后一句`root['xxx'] = factory()`)，这个策略(不需要循环+排除iframe)不知道作者是否考虑过，是否存在其他问题？

**Comment by kuitos** [comment]
基于 proxy 的方式是可行的，但是 ie 场景下就不能兼容了

**Comment by kuitos** [comment]
查找效率/性能 这些问题，如果没有特定的上下文或者 profile，很多时候都会是伪命题，不同的 边界/浏览器环境 可能都会得出不一样的结果。

**Comment by stoneChen** [comment]
@kuitos 是否考虑把兜底取子应用entry方案移动到遍历方案之前？这个成本比较低，性能损耗较小，也不必打印警告。
![image](https://user-images.githubusercontent.com/4470552/88133849-a7cf9480-cc15-11ea-9462-9aaff0139e44.png)

**Comment by kuitos** [comment]
前置就成默认行为，就不是兜底方案了

**Comment by kuitos** [comment]
> 当子应用内存在window.xxx = yyy 这样的代码时，主应用查找不到子应用的生命周期函数。

这个问题需要被修复

**Comment by maxmeng93** [comment]
这个bug大概什么时候可以修复，我升级qiankun后也遇到这种问题了，在主应用里无法获取到子应用，以前在主应用通过 `window['appName-app']` 是可以的。
