### ISSUE TITLE
vue cli 2.0 webpack如何配置umd打包

### ISSUE THREAD

**Issue by fewiki** [umijs/qiankun#778]
我在build/ webpack.dev.conf.js 增加了umd打包的配置，没有生效

```
output: {
      library: `${name}-[name]`,
      libraryTarget: 'umd',// 把子应用打包成 umd 库格式
      jsonpFunction: `webpackJsonp_${name}`,
    },
````

**Comment by kuitos** [comment]
https://www.google.com/search?sxsrf=ALeKk02PB7pHaZ9Tk3Uv3HviRoAwZhpttg%3A1595219569550&ei=cR4VX9WSIdXr-QaOjqfoBg&q=vue+cli+2.0+webpack+output&oq=vue+cli+2.0+webpack+output&gs_lcp=CgZwc3ktYWIQAzIECCMQJzoHCCMQsAIQJ1C1DVi1DWD_EGgAcAB4AIABzAKIAacEkgEFMi0xLjGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiVj6D-_9rqAhXVdd4KHQ7HCW0Q4dUDCAw&uact=5
