### ISSUE TITLE
Wrapper element for home with instance home_1595212251307 is not existed!

### ISSUE THREAD

**Issue by ExcaliburZhou** [umijs/qiankun#779]
## What happens?
1，主应用切换子应用的链接时，报错
Error: [qiankun] Wrapper element for home with instance home_1595213348018 is not existed!

**Comment by xuyingqi** [comment]
请问这个问题解决了吗？我遇到相同的报错...

**Comment by maquannene** [comment]
同样遇到报错。屏蔽了一堆代码，将 代码最简化，发现又不报错了。是不是跟 dom 的复杂程度有关？

**Comment by qibiaoWang** [comment]
关注，希望回复原因和解决方案

**Comment by hellojayjay** [comment]
改了下loader.js，把 syncAppWrapperElement2Sandbox 实现改成这样好像可以解决这个问题，但是不知道做法正不正确
![image](https://user-images.githubusercontent.com/42774792/120290981-6c056100-c2f5-11eb-8434-414f4a3fa857.png)

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/1105#issuecomment-750330170

**Comment by huangyuefeng666** [comment]
怎么解决这个问题
