### ISSUE TITLE
Uncaught react app: Application 'react app' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by leon0707** [umijs/qiankun#78]
## What happens?
I tried the examples. An exception threw.

```shell
Uncaught react app: Application 'react app' died in status UNMOUNTING: unmountComponentAtNode(...): Target container is not a DOM element.
    at eval (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:30509:32)
    at Object.unmountComponentAtNode (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:30512:11)
    at Array.unmount (eval at exec (http://localhost:7099/main.e31bb0bc.js:31987:11), <anonymous>:171157:21)
    at i (http://localhost:7099/main.e31bb0bc.js:32599:21)
    at http://localhost:7099/main.e31bb0bc.js:32601:38
```

## Mini Showcase Repository(REQUIRED)

No showcase

## How To Reproduce
**Steps to reproduce the behavior:**
1. `npm run install:examples`
2. `npm start`
3. click react16 + antd3, then click react15 + antd2 immediately

**Expected behavior**
1. content should change

## Context
The bug can be reproduced when I click the `li` fast.

- **Node Version**:
12.4.0
- **Platform**:
MacOS

**Comment by HadeAs** [comment]
我也遇到相同的问题

**Comment by yangangzhang** [comment]
window对于package.json中的&&链式命令支持度不好，把npm run install:examples在package.json中的命令分开执行

**Comment by HadeAs** [comment]
> window对于package.json中的&&链式命令支持度不好，把npm run install:examples在package.json中的命令分开执行

我是Mac的 也有这样的问题

**Comment by yangangzhang** [comment]
> > window对于package.json中的&&链式命令支持度不好，把npm run install:examples在package.json中的命令分开执行
> 
> 我是Mac的 也有这样的问题

我的是windows，这样解决了，mac的话，你也这样试试

**Comment by HadeAs** [comment]
还是一样的问题，我调试了一下，发现在执行子应用unmount函数中的卸载组件方法时，要卸载组件所在的dom元素已经不存在了，生成的是新的要加载组件的dom元素。估计是这个原因导致的报错吧 @kuitos

**Comment by kuitos** [comment]
fixed
重新跑下 npm run build 即可

**Comment by wumiangithub** [comment]
怎么解决的，我也遇到同样问题
