### ISSUE TITLE
strictStyleIsolation 开启后 点击事件失效

### ISSUE THREAD

**Issue by SimonsXue** [umijs/qiankun#780]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/88007576-df204180-cb40-11ea-9c5b-6afce2f8a4cd.png)

https://qiankun.umijs.org/zh/api#loadmicroappapp-configuration
