### ISSUE TITLE
[Bug]Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by gq1045010037** [umijs/qiankun#782]
关于qiankun父子通讯时使用useModel获取props时，@@qiankunStateFromMaster'无效的挂接。

在使用plugin-qiankun时，父子应用通讯中使用useModel('@@qiankunStateFromMaster')获取主应用的传的props时，报Invalid hook call. Hooks can only be called inside of the body of a function component。

父应用使用 路由绑定式 消费微应用，导出useQiankunStateForSlave函数，子应用中用useModel获取透传的props时无法得到值。并且报Invalid hook call. Hooks can only be called inside of the body of a function component的错。

主应用和子应用都是ant design pro V5版本。umi的版本是3.2.10 ，  react@16.12.0 ，react-dom@16.12.0

## 相关环境信息

- **qiankun 版本**
@umijs/plugin-qiankun：2.5.1
qiankun：2.0.16
- **浏览器版本**：
Google Chrome 83.0.4103.116（正式版本）
- **操作系统**：
MAC

**Comment by kuitos** [comment]
useModel 基于 hooks，hooks 只能在 function component 中使用
https://zh-hans.reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by gq1045010037** [comment]
好的，谢谢。

**Comment by wellenzhong** [comment]
所以要拿父应用传过来的props并全局保存起来, 应该在哪里拿呢?
