### ISSUE TITLE
生产环境主项目和子项目之间的跨域问题如何解决呢？

### ISSUE THREAD

**Issue by liuly-6** [umijs/qiankun#783]
qiankun 本身没有对跨域这方面的处理吗？

**Comment by S-ionantha** [comment]
同问

**Comment by Liaozzzzzz** [comment]
配置nginx

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E4%B8%80%E5%AE%9A%E8%A6%81%E6%94%AF%E6%8C%81%E8%B7%A8%E5%9F%9F%E5%90%97%EF%BC%9F
