### ISSUE TITLE
Invalid key bootstrap from plugin

### ISSUE THREAD

**Issue by jimStyle88** [umijs/qiankun#784]
What happens?
     主应用 : 
    qiankun(v1.4.6) 、umi (v2.12.5)
  子应用：
   umi (2.13.0）
  以上情况接入qiankun 时，子应用已在app.js文件 执行 export  bootstrap 、mount 、unmount 三个生命周期的情况下报错  
  AssertionError: Invalid key bootstrap from plugin
   主应用的elements 里可以找到子应用的节点
  ![image](https://user-images.githubusercontent.com/20588608/88144818-1881ab80-cc2c-11ea-9d45-b371d405a77e.png）
![image](https://user-images.githubusercontent.com/20588608/88145922-c3469980-cc2d-11ea-9b78-6abf9eac21da.png)

Mini Showcase Repository(REQUIRED)

 无

 How To Reproduce
 

 Context

- **qiankun Version**:1.4.6
- **Platform Version**:win 10 
- **Browser Version**: Chrome 83.0.4103.116（正式版本） （64 位）

**Comment by kuitos** [comment]
umi2 应用使用插件接入 https://github.com/umijs/umi-plugin-qiankun

**Comment by jimStyle88** [comment]
> umi2 应用使用插件接入 https://github.com/umijs/umi-plugin-qiankun
我这边的场景是：主应用已经通过qiankun （1.4.6） ,接入了一个非 umi  的项目在线上运行，现在需要再接入一个基于umi (2.13.0）开发的项目，我尝试过给 子应用 使用插件的方式，得出 结果：
主应用报错：
error occurs while executing the entry http://localhost:5003  
Uncaught fmc: Application 'fmc' died in status LOADING_SOURCE_CODE: Unexpected token '<'
子应用白屏：
![image](https://user-images.githubusercontent.com/20588608/88163840-d5343680-cc45-11ea-8863-60193dcb5473.png)
疑问点：
1、在不修改主应用方式的情况下，应该如何接入 基于umi (2.13.0）开发的子应用
2、如果修改主应用使用插件的方式，因为考虑到之后的子应用有可能 有多种形态，比如 框架、多页、服务端渲染等场景。

麻烦大佬指导指导，感谢您的回复！

**Comment by kuitos** [comment]
仅 umi 子应用用插件也是可以的，不要求主应用也必须用插件

**Comment by jimStyle88** [comment]
> 仅 umi 子应用用插件也是可以的，不要求主应用也必须用插件

大佬帮忙看看我上面提到的问题，主应用用qiankun  ,子应用用插件的， 报的错误应该怎么定位处理？看样子应该是子应用暴露的生命周期有关（我是按照文档来的）
