### ISSUE TITLE
当一个子应用因为某些原因加载失败之后，后续不管跳转任何地址，都会去试图请求这个子应用

### ISSUE THREAD

**Issue by han-neil** [umijs/qiankun#787]
## What happens?

当一个子应用因为某些原因加载失败之后，后续不管跳转任何地址，都会去试图请求这个子应用，导致会一直走异常监听方法报错，如果能通过参数控制要不要后续一直去请求或者提供一个加载失败的回调就好了

## 最小可复现仓库

https://github.com/han-neil/qiankun-bug.git

## 复现步骤，错误日志以及相关配置

1、运行main和sub1工程，不要运行sub2工程
2、进入主页后点击sub2，然后打开控制台，不管点击sub1还是home，都会报错，因为都会去加载sub2

## 相关环境信息

- **qiankun 版本** 2.0.16
- **浏览器版本**：chorme: 84.0.4147.89（正式版本）
- **操作系统**：win10

**Comment by han-neil** [comment]
没有关，都这么久了

**Comment by cshsh** [comment]
@han-neil 解决了？

**Comment by qiuzhenlin1990** [comment]
确实，我也遇到过。某个子应用资源请求失败会影响整个系统所有子应用的路由切换(除非刷新页面)。一个子应用资源加载失败，如果尝试加载另外一个子应用，还是会请求上一个失败的资源。希望官方能够尽快修复这个问题

**Comment by qiuzhenlin1990** [comment]
> 没有人管，都这么久了

问题解决了么？

**Comment by han-neil** [comment]
> > 没有人管，都这么久了
> 
> 问题解决了么？

还没有

**Comment by Jaasdsa** [comment]
我也发现了

**Comment by xiezhongfu** [comment]
https://github.com/umijs/qiankun/issues/844#issuecomment-686231963
