### ISSUE TITLE
关于ie11的polyfill问题

### ISSUE THREAD

**Issue by shinji3887** [umijs/qiankun#788]
按照官方文档的说明，将
```
import 'whatwg-fetch';
```
放在main.js中不起作用,报错
```
[import-html-entry] Here is no "fetch" on the window env, you need to polyfill it
```
需要直接放到`import-html-entry`这个module中，fetch ployfill才会生效
这样就要修改npm依赖包了，有其他方式完成这个polyfill么？

**Comment by gongshun** [comment]
放到 `main.js` 的最开头就行了

**Comment by kuitos** [comment]
看 whatwg-fetch 文档，里面有 webpack 场景怎么用 https://github.com/github/fetch#importing
