### ISSUE TITLE
entry 使用scripts、styles配置 ，__INJECTED_PUBLIC_PATH_BY_QIANKUN__和主应用域名一致，导致请求和资源无法正确加载

### ISSUE THREAD

**Issue by vius** [umijs/qiankun#791]
希望提供一种自定义方式 可以自己定义当前的__INJECTED_PUBLIC_PATH_BY_QIANKUN__
![image](https://user-images.githubusercontent.com/12264907/88270802-c9f60f00-cd08-11ea-9748-09a16d2b13ff.png)
这是import-html-entry中代码逻辑

**Comment by HermitSun** [comment]
+1，有时候想部署在非根路径下面，这样不太方便

**Comment by vius** [comment]
> +1，有时候想部署在非根路径下面，这样不太方便

不仅仅是路径问题 还有域名不同的问题 这样直接采用了主应用的 会有问题的

**Comment by kuitos** [comment]
getPublicPath 可以自己复写 
![image](https://user-images.githubusercontent.com/5206843/88287465-e738d680-cd24-11ea-808b-c40c5463a1f7.png)

https://qiankun.umijs.org/zh/api#startopts

**Comment by vius** [comment]
> getPublicPath 可以自己复写
> ![image](https://user-images.githubusercontent.com/5206843/88287465-e738d680-cd24-11ea-808b-c40c5463a1f7.png)
> 
> https://qiankun.umijs.org/zh/api#startopts

这个api是可以复写  但是入参只是 ‘/’ 没有其他参数（比如当前子应用config）传入 感觉不是很方便  期望注册子应用支持自定义
