### ISSUE TITLE
[提问]前后端的应用没有进行分离，子应用挂载存在跨域情况是不是无法解决

### ISSUE THREAD

**Issue by mhfe123** [umijs/qiankun#792]
我的主应用跟子应用是独立的系统，子应用的前后端没有分离，访问的子应用端口是后端暴露的端口，后端服务又不能设置随便人都可以跨域访问，这样我主应用挂载子应用时就会存在跨域的情况，是不是无法解决这样的情况呀
![image](https://user-images.githubusercontent.com/33445131/88280714-e26e2580-cd18-11ea-916a-ef3dd3d7603d.png)

**Comment by kuitos** [comment]
> 不能设置随便人都可以跨域访问

这是个伪命题，跨域也是可以做 host 跟身份鉴权的
