### ISSUE TITLE
开发调试阶段的稳定性.

### ISSUE THREAD

**Issue by JH46666** [umijs/qiankun#794]
## What happens?

当我进行 dev 调试阶段,很容易出现这个错误,不得不重新启动子项目.
loader.js:187 Uncaught Error: application 'ReactMicroApp' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in ReactMicroApp entry
    at getLifecyclesFromExports (loader.js:187)
    at _callee16$ (loader.js:279)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at fulfilled (tslib.es6.js:71)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
在子应用 app.js 里面做了修改:
// 此时我们还没有微应用，所以 apps 为空
  // 导入主应用工具类库
  import { conSjh } from '../utils/index';

  const msg = {
    utils: conSjh // 从主应用读出的工具类库
  };

const apps = [{
  name: 'ReactMicroApp',
  entry: '//localhost:10100',
  container: '#frame',
  activeRule: '#/react',
  props: msg // 将定义好的数据传递给子应用
}];

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:  "^2.0.16",
- **Platform Version**: mac
- **Browser Version**:  mac chrome版本 83.0.4103.116

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/340
