### ISSUE TITLE
父子应用通讯可以通过onGlobalStateChange，子应用获取到数据后，无法直接操作子应用model

### ISSUE THREAD

**Issue by jimStyle88** [umijs/qiankun#797]
What happens?
主应该通过 props / setGlobalState  的方式 传递参数给子应用，无法直接使用dispatch 或者其他操作更新 子应用的model   希望可以实现在子应用 mount 的时候，对子应用model   进行更新

目前临时解决方案：通过本地缓存，在umi  项目  的 basicLayout.js  再写入到model 中。

相关环境信息
- **qiankun 版本**： 2.0.16
- **浏览器版本**：83.0.4103.116（正式版本） （64 位）
- **操作系统**：window

**Comment by esymeptoo** [comment]
```
onGlobalStateChange(val => { store.commit() }, true)
```

**Comment by kuitos** [comment]
closed via inactive
