### ISSUE TITLE
[Bug]主系统与子系统之间数据传递有问题

### ISSUE THREAD

**Issue by HadeAs** [umijs/qiankun#80]
## What happens?

主系统注册子应用时，传入props参数。子应用加载时，打印props里的值，发现没有传入的参数

## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置
1. 注册子应用
![20190917191035](https://user-images.githubusercontent.com/12652964/65036805-db4eec00-d97e-11e9-8c3f-6839eaa45a6a.jpg)

2. 启动项目，打开控制台，查看信息
![20190917190708](https://user-images.githubusercontent.com/12652964/65036858-00dbf580-d97f-11e9-80bc-1fba7def0371.jpg)

## 相关环境信息

- **Node 版本**：v10.15.3
- **操作系统**：Mac

**Comment by kuitos** [comment]
因为 name 重名被内部的 props 覆盖了 ... 换成别的 key 就可以了

**Comment by HadeAs** [comment]
> 因为 name 重名被内部的 props 覆盖了 ... 换成别的 key 就可以了

多谢
