### ISSUE TITLE
子应用之间的样式是不会互相影响，但是父子应用的会影响的，有个场景，父用了ant design， 子也用了ant design，父子的ant design等不同的版本样式会冲突

### ISSUE THREAD

**Issue by zjscy666** [umijs/qiankun#807]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)
子应用之间的样式是不会互相影响，但是父子应用的会影响的，有个场景，父用了ant design， 子也用了ant design，父子的ant design等不同的版本样式会冲突，比较就算用了module，也是注册在global，解决方案就是父子ant design版本保持一致，但是这样有点局限性，有啥办法可以解决父子应用样式互相影响的问题

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by howel52** [comment]
https://qiankun.umijs.org/faq#how-to-guarantee-the-main-app-stylesheet-isolated-with-sub-apps

**Comment by zjscy666** [comment]
上面只有修改样式，没有说如何加前缀的，伤心
