### ISSUE TITLE
子应用css url()中的图片用相对路径加载失败

### ISSUE THREAD

**Issue by drafish** [umijs/qiankun#808]
## What happens?

最近项目里用上了qiankun，子应用单独加载url()中的图片加载正常，但是当子应用在主应用中加载的时候url()中的图片加载不出来。

主应用：
```
{
   "qiankun": "^2.0.12",
}

{
    name: 'app1',
    entry: '//localhost:8080/sub/app1/',
    container: '#root-subapp-container',
    activeRule: '/app1',
}
```

子应用：
```
{
    "umi": "^3.1.1",
    "@umijs/plugin-qiankun": "^2.5.1",
}

{
    base: '/app1',
    publicPath: '/sub/app1/',
}

{
    background: url('~@/assets/bg.png');
}
```

url()中的图片相对路径是相对css文件所在路径，css文件是`http://localhost:8080/sub/app1/umi.css`，url()中的图片就是`http://localhost:8080/sub/app1/static/bg.png`。

当子应用单独加载的时候图片加载正常，但是在主应用中加载的时候图片加载路径就变成这样了`http://localhost:8080/app1/static/bg.png`。

我自己排查了下，问题是出在`import-html-entry`库。这个库会请求子应用的css文件，并将请求到的文件内容用嵌到子应用的<style>标签中。这就导致了子应用的外联样式变成了内联样式，url()中的相对路径从原来的相对css文件地址变成了相对html文档地址了。

因为`import-html-entry`库没法提issue，所以我提到这里了，希望能够修复下这个问题。

**Comment by drafish** [comment]
其实umi我觉得也有点问题，因为我已经在子应用里配置了publicPath了，但是打包出来的css文件中，url()里面还是相对路径，没有将publicPath加进去。

我已经在umi那边提了[issue](https://github.com/umijs/umi/issues/5030)和[PR](https://github.com/umijs/umi/pull/5031)，但是被@sorrycc拒绝了，他说这应该是微前端框架需要解决的问题。所以在这里提下这个issue，希望能修复下

**Comment by gongshun** [comment]
打包插件的锅，没有注入pubicPath . https://github.com/umijs/qiankun/issues/670

**Comment by kuitos** [comment]
chainWebpack 改下相关插件的 publicPath 配置

**Comment by Jaasdsa** [comment]
我的子应用的没有webpack 这样打包工具，所以publicPath 无法在编译时解决，但是__INJECTED_PUBLIC_PATH_BY_QIANKUN__这个变量，请问怎么劫持css文件里的url()方法

**Comment by Jaasdsa** [comment]
![image](https://user-images.githubusercontent.com/29112372/91980694-3f1e2080-ed5a-11ea-8d75-b390ed5734c1.png)

**Comment by gongshun** [comment]
> 我的子应用的没有webpack 这样打包工具，所以publicPath 无法在编译时解决，但是__INJECTED_PUBLIC_PATH_BY_QIANKUN__这个变量，请问怎么劫持css文件里的url()方法

你可以修改源码，正则匹配 `css` 的内容，注入 `__INJECTED_PUBLIC_PATH_BY_QIANKUN__`。

源码位置：https://github.com/kuitos/import-html-entry/blob/433d77ed4719100fab2c4b31d414ae36ee38e1a6/src/index.js#L63
