### ISSUE TITLE
vue主框架，不同路由模式导致子应用加载报错的问题

### ISSUE THREAD

**Issue by Xiao-HuangShu** [umijs/qiankun#809]
## What happens?
    vue主应用路由如下：

![image](https://user-images.githubusercontent.com/27752523/88993977-eeaa4200-d319-11ea-9599-3390f9bf87e2.png)
  
 子应用挂载点是主应用下的Home页

  路由模式为hash子应用正常加载

  history模式是报如下错误

![TIM截图20200731103114](https://user-images.githubusercontent.com/27752523/88993645-18af3480-d319-11ea-8a48-4747b2a7ac37.png)

## 配置如下
 1、主应用及qiankun
   
![image](https://user-images.githubusercontent.com/27752523/88993783-7479bd80-d319-11ea-8fe6-74d0e357a136.png)

![image](https://user-images.githubusercontent.com/27752523/88993802-7f345280-d319-11ea-9efc-93d91d85fcb1.png)
![image](https://user-images.githubusercontent.com/27752523/88993815-865b6080-d319-11ea-9d27-da91c505b742.png)
2、子应用配置
  
![image](https://user-images.githubusercontent.com/27752523/88993839-983d0380-d319-11ea-9890-c9f747b28ada.png)

   
## 相关环境信息
- **qiankun 版本2.0.16
- **浏览器版本Chrome 83.0.4103.116：
- **操作系统win10：

**Comment by gongshun** [comment]
在 `home`  页的 `mounted` 周期注册并 `start` 子项目

**Comment by Xiao-HuangShu** [comment]
挂载点放在根下就没有问题了，具体原因我猜想大概是因为路由引起的，qinkun跳转的子应用路由不存在主应用注册的路由中，导致页面跳转的时候动态路由匹配不到，从而导致挂载子应用的节点home页不渲染，dom树不存在，挂载点就不存在

![image](https://user-images.githubusercontent.com/27752523/89625687-dd89a400-d8ca-11ea-9e7c-a3b5d504342c.png)
