### ISSUE TITLE
迁移项目出现问题，也获取不到子应用程序的content

### ISSUE THREAD

**Issue by rqc-git** [umijs/qiankun#81]
## What happens?
主应用程序 自己基于qiankun起的项目；
子应用程序选取 examples/react,examples/vue（因为已经暴露钩子），没有做任何改动。
但是加载子应用程序的时候报错：如下：
![image](https://user-images.githubusercontent.com/25263162/65060917-5b8b4680-d9ab-11e9-816b-c8f397a58b59.png)
子应用程序内容content并没有变化

## Mini Showcase Repository(REQUIRED)
无

## How To Reproduce

启动自己的项目，链接到子应用程序

## Context

- **Node Version**:
v11.9.0
mac

**Comment by rqc-git** [comment]
![image](https://user-images.githubusercontent.com/25263162/65061149-e8360480-d9ab-11e9-9819-55c48b05d386.png)
在主程序中已经可以拿到钩子，但是为什么还是提示 钩子 不是函数的错误？

**Comment by kuitos** [comment]
更新到 1.1.9 试试

**Comment by rqc-git** [comment]
升级后会出现这个问题，我已经按官方例子暴露出了钩子函数
![image](https://user-images.githubusercontent.com/25263162/65120275-f291e600-da1f-11e9-90ce-07b0dec5fc85.png)

**Comment by kuitos** [comment]
删 node_modules 重装一下所有的依赖，然后再看下你的报错

**Comment by yandwuhan** [comment]
![image](https://user-images.githubusercontent.com/22886969/65200843-ff174c80-daba-11e9-8013-355f44bc763a.png)
![image](https://user-images.githubusercontent.com/22886969/65200866-148c7680-dabb-11e9-89ad-7789e8a8c789.png)
1.1.9仍然报错没有抛出钩子函数
还有麻烦问一下，你们的沙箱是怎么代理到子页面的呢。我主要是想用你们这个沙箱的功能，单独拿出来测试了，对于全局变量和事件的监听都很好。但是不知道怎么把子页面的window替换为jsSandbox

**Comment by kuitos** [comment]
> ![image](https://user-images.githubusercontent.com/22886969/65200843-ff174c80-daba-11e9-8013-355f44bc763a.png)
> ![image](https://user-images.githubusercontent.com/22886969/65200866-148c7680-dabb-11e9-89ad-7789e8a8c789.png)
> 1.1.9仍然报错没有抛出钩子函数
> 还有麻烦问一下，你们的沙箱是怎么代理到子页面的呢。我主要是想用你们这个沙箱的功能，单独拿出来测试了，对于全局变量和事件的监听都很好。但是不知道怎么把子页面的window替换为jsSandbox

代码在这里。

@rqc-git @yandwuhan 报 issue 请提供可复现的仓库，不然没法定位问题，这个 issue 我先关了
