### ISSUE TITLE
React 子应用中的图片相对路径加载失败

### ISSUE THREAD

**Issue by npm-ued** [umijs/qiankun#810]
## What happens?
通过create react app创建的子应用中如果有图片（非base64）都会加载失败，
目前exaple中react16添加图片也能复现

- **qiankun Version**: 最新版版master
- **Platform Version**: mac os Catalina 10.15.4
- **Browser Version**: chrome 84.0.4147.105

**Comment by npm-ued** [comment]
对比Vue直接访问为相对路径，嵌入到qiankun中为绝对路径，没有问题

**Comment by Bonnie8ni** [comment]
我也有這個問題 +1

**Comment by xupea** [comment]
> production-ready 
> 已在蚂蚁内外经受过足够大量的线上系统的考验及打磨，健壮性值得信赖

就这？

**Comment by npm-ued** [comment]
#826 不是qiankun框架的问题，React 应用在配置runtime 基础路径，需要在入口处

**Comment by npm-ued** [comment]
> > production-ready
> > 已在蚂蚁内外经受过足够大量的线上系统的考验及打磨，健壮性值得信赖
> 
> 就这？

demo的问题，这个问题不是框架的
