### ISSUE TITLE
父应用在 vue-router 包裹的页面下手动加载子应用，子应用内的 router 跳转失效

### ISSUE THREAD

**Issue by Hansuku** [umijs/qiankun#811]
## What happens?

父应用是 vue，有自己的 router，在`/micro-app`路由的这个页面中手动加载了子应用
子应用有两个页面，分别是 `/micro-app/` 和 `/micro-app/about` 从前面的路由跳转到后面的路由失败
看了下应该是这个跳转被父应用的 router 捕捉到了，但是父应用下并没有注册`/micro-app/about`这个路由，才导致没有页面可以相应。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/Hansuku/vue-subapp-qiankun

## How To Reproduce

下载项目，分别给 vue 和 sub-app 里安装好依赖，启动服务，然后在`vue/src/components/HelloWorld.vue`文件里修改子应用运行的端口，在浏览器里查看项目，点击 about 就可以

## Context

- **qiankun Version**:2.0.16
- **Platform Version**:MacOS Catalina 10.15.6/nodejs v12.18.2/npm 6.14.6
- **Browser Version**:Chrome 84.0.522.49 (官方内部版本) (64 位)

**Comment by Swings12138** [comment]
楼主解决了嘛  我也是同样的问题

**Comment by Hansuku** [comment]
@Swings12138 解决了 其实是自己蠢了。子应用的/micro-app/about这个路由 同样需要被父应用注册 父应用把这个路由同样指向微应用基座就好了。

**Comment by ldhfx** [comment]
> @Swings12138 解决了 其实是自己蠢了。子应用的/micro-app/about这个路由 同样需要被父应用注册 父应用把这个路由同样指向微应用基座就好了。

也就是说在主应用中要注册所有的子应用的路由吗   感觉这个方式怪怪的    有其他方式吗

**Comment by Sapphire2k** [comment]
同样遇到这个问题，但是不可能全都配置到主应用里吧

**Comment by youthug** [comment]
mark，请问楼主解决了吗
