### ISSUE TITLE
子应用之间的样式是不会互相影响，但是父子应用的会影响的，有个场景，父用了ant design， 子也用了ant design，父子的ant design等不同的版本样式会冲突，比较就算用了module，也是注册在global，解决方案就是父子ant design版本保持一致，但是这样有点局限性，有啥办法可以解决父子应用样式互相影响的问题

### ISSUE THREAD

**Issue by zjscy666** [umijs/qiankun#813]
子应用之间的样式是不会互相影响，但是父子应用的会影响的，有个场景，父用了ant design， 子也用了ant design，父子的ant design等不同的版本样式会冲突，比较就算用了module，也是注册在global，解决方案就是父子ant design版本保持一致，但是这样有点局限性，有啥办法可以解决父子应用样式互相影响的问题

虽然也要回到，但是只给了这个链接，https://qiankun.umijs.org，
上面的回答https://ant.design/docs/react/customize-theme
只有修改样式，比如颜色，并没有增加ant--design主应用前缀，也没有说明，如何增加主应用前缀

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by rockyxia** [comment]
开启沙箱...
完全隔离开

**Comment by zjscy666** [comment]
沙箱对react不友好，因为react事件监听再document，所以需要额外做处理，我已经解决了，作者大大可以关闭下我的issue了，累死我了，修改了主应用前缀，只是ant design文档换肤主题那块 隐藏的很深 还好有几个朋友讨论 但是说句实话 换了前缀后 因为ant design的样式严谨性 需要修改的细节也有一点

**Comment by KellenHe** [comment]
@zjscy666 你好，能讲下你的方案吗？
我修改了antd前缀之后会有下面的问题：
修改antd的前缀，只是修改了css的前缀，但是最终生成的组件还是使用了ant的前缀。会导致组件样式失效。
比如修改@ant-prefix = myant之后。组件还是叫ant-xxx。只是css变为myant-xxx了，这样组件会没有样式。

**Comment by oaspireo** [comment]
> @zjscy666 你好，能讲下你的方案吗？
> 我修改了antd前缀之后会有下面的问题：
> 修改antd的前缀，只是修改了css的前缀，但是最终生成的组件还是使用了ant的前缀。会导致组件样式失效。
> 比如修改@ant-prefix = myant之后。组件还是叫ant-xxx。只是css变为myant-xxx了，这样组件会没有样式。

需要配合ConfigProvider改变组件js绑定的class前缀

**Comment by zhaochengxiang** [comment]
通过给主应用ant增加前缀 是能解决样式冲突 
但目前又出现其他问题 通过less的modidyVars动态修改一些常量 比如primary-color 组件样式不会变
有人能解决这个问题吗?

**Comment by Dashuai-Black** [comment]
> @zjscy666 你好，能讲下你的方案吗？ 我修改了antd前缀之后会有下面的问题： 修改antd的前缀，只是修改了css的前缀，但是最终生成的组件还是使用了ant的前缀。会导致组件样式失效。 比如修改@ant-prefix = myant之后。组件还是叫ant-xxx。只是css变为myant-xxx了，这样组件会没有样式。

这个问题有解决方案了么
