### ISSUE TITLE
sandbox 开启 strictStyleIsolation 没有内容

### ISSUE THREAD

**Issue by teenth** [umijs/qiankun#815]
没开启的时候

```js
    start({
      // sandbox: { strictStyleIsolation: true }
    })
```
![image](https://user-images.githubusercontent.com/16316491/89156743-c3d02000-d59d-11ea-862f-110870ea13b0.png)
开启后
```js
    start({
       sandbox: { strictStyleIsolation: true }
    })
```
![image](https://user-images.githubusercontent.com/16316491/89156860-0a257f00-d59e-11ea-8f9c-272541145aaa.png)
![image](https://user-images.githubusercontent.com/16316491/89156942-32ad7900-d59e-11ea-8c3a-0b45542ca27b.png)
![image](https://user-images.githubusercontent.com/16316491/89157070-743e2400-d59e-11ea-94f5-4871c1fa075c.png)

请问下是什么原因

**Comment by teenth** [comment]
已解决：
```js
// 子应用
function render (props = {}) {
  const { container } = props;
  instance =  new Vue({
    render: h => h(App),
  }).$mount(container ? container.querySelector('#micro-app') : '#micro-app')
}
export async function mount(props) {
  render(props)
}

// 父应用
    registerMicroApps([
      {
        name: 'micro-app',
        entry: '//localhost:10301/',
        container: '#test',
        activeRule: '#/micro',
        props: {
          container: document
        }
      }
    ])
```

**Comment by kuitos** [comment]
container 会自动传过去，不用手动设置成 document，demo 里有 https://github.com/umijs/qiankun/blob/master/examples/vue/src/main.js#L29
