### ISSUE TITLE
legacy sandbox 存在漏洞

### ISSUE THREAD

**Issue by tangshengzhi** [umijs/qiankun#819]
legacy sandbox  如果在子应用运行期间，父应用修改了window下的变量会导致addedPropsMapInSandbox和modifiedPropsOriginalValueMapInSandbox无法记录到，从而出现意料之外的情况。

抱歉，因为公司网络环境不太好，暂时无法提供可复现仓库。

qiankun版本:2.0.16
chrome版本:84
操作系统:windows

似乎可行的解决思路：sandbox  inactive的时候将currentUpdatedPropsValueMap和window进行对比，得出直接跳过proxy直接更新的属性。将modifiedPropsOriginalValueMapInSandbox 和 currentUpdatedPropsValueMap 更新为 此时window上的真实值。

**Comment by kuitos** [comment]
给个 example repo 吧，能访问 github 就说明网络 ok 的

或者有解决方案了直接提个 pr 更好😃

**Comment by tangshengzhi** [comment]
认真思考了下，window下的值的变化似乎无法完全捕获到。   即使解决也只能解决部分场景下的legacy sanbox的漏洞。
只能自己项目中避免   父子应用间去同时修改共用同一变量的方式去共享数据等。直接用官方的GlobalState即可
