### ISSUE TITLE
主应用怎么通知子应用的接口重新请求。

### ISSUE THREAD

**Issue by ztfstar** [umijs/qiankun#820]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

我想在主应用某个状态改变的时候通知子应用重新请求某个接口怎么实现呢？现在在子应用里用的是onGlobalStateChange可以监听到状态变化。

## 相关环境信息

- **qiankun 版本** ：2.0.16
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
```
export function mount(props) {
  window.props = props
}
```
然后在某个需要发请求的页面
```js
window.props.onGlobalStateChange((state, prev) => {
    // state: 变更后的状态; prev 变更前的状态
    console.log(state, prev);
 });
```
