### ISSUE TITLE
[Feature Request] 可以添加一个dva的例子么

### ISSUE THREAD

**Issue by neu-liruijia** [umijs/qiankun#822]
## Background

添加dva子项目的时候，会有一些报错，想了解下dva作为子项目是怎么接入的

**Comment by yinqiong919** [comment]
你添加dva子项目的时候报什么错？生命周期导出错误还是啥？

**Comment by Neu-Li** [comment]
> 你添加dva子项目的时候报什么错？生命周期导出错误还是啥？

ncaught TypeError: application '项目名称' died in status LOADING_SOURCE_CODE: Failed to fetch

**Comment by yinqiong919** [comment]
请问下你的生命周期函数导出是怎么配置的，我在index.js中导出生命周期函数就直接报错

**Comment by wanghongjiajijingjing** [comment]
这个问题我也遇到了，请问为啥关闭了呢？
