### ISSUE TITLE
已开发得Vue，如何在子路由中使用qiankun，引入别的Vue项目

### ISSUE THREAD

**Issue by Swings12138** [umijs/qiankun#824]
这是测试案例
这是主应用得main.js

function genActiveRule (routerPrefix) {
  // eslint-disable-next-line no-debugger
  debugger
  return location => location.hash.startsWith(routerPrefix)
}
registerMicroApps([
  {
    name: 'test',
    entry: { scripts: ['//localhost:7101'] },
    container: '#test',
    activeRule: genActiveRule('#/test')
  }
])

start()
new Vue({
  render: h => h(App),
  store,
  router
}).$mount('#app')

子应用就是 源码 example里面的 vue项目，我单独启动后

在主应用的路由test文件中 
<template>
  <div id="test">
  </div>
</template>

请求路由却报错，找不到节点
Uncaught Error: application 'test' died in status LOADING_SOURCE_CODE: [qiankun] Target container with #test not existed while test loading!

**Comment by Oscar-ren** [comment]
主应用要把 registerMicroApps 传给子应用，不过我的虽然不报错了，子应用内的子应用还是不渲染

**Comment by gongshun** [comment]
方法1：在子路由页面的 `mounted` 周期 `registerMicroApps` 并 `start` 就可以了
方法2： 在APP.vue写好这个容器，用 `v-show` 隐藏起来，当切到这个路由时，再显示

**Comment by Swings12138** [comment]
> 主应用要把 registerMicroApps 传给子应用，不过我的虽然不报错了，子应用内的子应用还是不渲染

  我现在是在我的主应用的路由中用loadMicroApp，加载子页面，但是现在问题是，子页面的也有路由切换，点击路由切换无法响应

**Comment by Swings12138** [comment]
> 方法1：在子路由页面的 `mounted` 周期 `registerMicroApps` 并 `start` 就可以了
> 方法2： 在APP.vue写好这个容器，用 `v-show` 隐藏起来，当切到这个路由时，再显示



> 主应用要把 registerMicroApps 传给子应用，不过我的虽然不报错了，子应用内的子应用还是不渲染

  我现在是在我的主应用的路由中用loadMicroApp，加载子页面，但是现在问题是，子页面的也有路由切换，点击路由切换无法响应

**Comment by litianyangz** [comment]
@Swings12138 问题解决了吗，我也遇到了这种问题

**Comment by lulongwen** [comment]
new Vue({
  router,
  render: h => h(App),
  mounted () {
    // 注册应用
    registerMicroApps(APP_CONFIG)
    // 启动应用, all主应用start后,即开始预加载所有微应用静态资源
    start({
      prefetch: false, // 'all' 取消预加载，不点击路由，不加载
    })
  }
}).$mount('#rootApp')

**Comment by lulongwen** [comment]
把 registerMicroApps 放在mounted里面执行

**Comment by maolaila** [comment]
> 把 registerMicroApps 放在mounted里面执行

不行的，还是[qiankun]: Target container with #vue not existed after vueApp mounted!

**Comment by gongshun** [comment]
> 不行的，还是[qiankun]: Target container with #vue not existed after vueApp mounted!

https://qiankun.umijs.org/zh/faq#application-died-in-status-not_mounted-target-container-with-container-not-existed-after-xxx-mounted

**Comment by z-lionel** [comment]
> > 方法1：在子路由页面的 `mounted` 周期 `registerMicroApps` 并 `start` 就可以了
> > 方法2： 在APP.vue写好这个容器，用 `v-show` 隐藏起来，当切到这个路由时，再显示
> 
> > 主应用要把 registerMicroApps 传给子应用，不过我的虽然不报错了，子应用内的子应用还是不渲染
> 
> 我现在是在我的主应用的路由中用loadMicroApp，加载子页面，但是现在问题是，子页面的也有路由切换，点击路由切换无法响应

请问最后怎么解决了，我现在也遇到这样的问题

**Comment by gongshun** [comment]
> 怎么解决了，我现在也遇到这样的问题

https://github.com/gongshun/qiankun-vue-demo/tree/feature/routing-page

**Comment by lyhzwf** [comment]
> 

试了还是不行，，有人解决了的吗

**Comment by duanweidi** [comment]
我也遇到了问题，各位大佬谁解决了，指导一下噻

**Comment by lulongwen** [comment]
这是来自卢珑文的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
