### ISSUE TITLE
qiankun子项目在ios移动端加载缓慢

### ISSUE THREAD

**Issue by fyxwanan** [umijs/qiankun#825]
qiankun子项目在ios移动端加载缓慢

**Comment by Gairo2021** [comment]
why close?

**Comment by fyxwanan** [comment]
> why close?

启用预加载之后访问还是挺快的

**Comment by Gairo2021** [comment]
但是 判断是移动端的情况下 ，我看到预加载那个方法 直接被return了，你是怎么让他继续预加载的？

**Comment by Gairo2021** [comment]
> > why close?
> 
> 启用预加载之后访问还是挺快的

但是 判断是移动端的情况下 ，我看到预加载那个方法 直接被return了，你是怎么让他继续预加载的？

**Comment by fyxwanan** [comment]
> > > why close?
> > 
> > 
> > 启用预加载之后访问还是挺快的
> 
> 但是 判断是移动端的情况下 ，我看到预加载那个方法 直接被return了，你是怎么让他继续预加载的？

找到原因之后就简单做了。直接修改框架中写的逻辑。
方法一：修改node_modules里的文件：
可以参考博客： https://blog.csdn.net/vM199zkg3Y7150u5/article/details/107703740

**Comment by Gairo2021** [comment]
> > > > why close?
> > > 
> > > 
> > > 启用预加载之后访问还是挺快的
> > 
> > 
> > 但是 判断是移动端的情况下 ，我看到预加载那个方法 直接被return了，你是怎么让他继续预加载的？
> 
> 找到原因之后就简单做了。直接修改框架中写的逻辑。
> 方法一：修改node_modules里的文件：
> 可以参考博客： https://blog.csdn.net/vM199zkg3Y7150u5/article/details/107703740

谢谢，最近也在用qiankun 接移动端项目，加个vx 交流吧，jialu2021
