### ISSUE TITLE
[BUG] umi-qiankun插件开启prefetch：'all'之后， 移动端不会预加载子应用， 但是PC是可以预加载的

### ISSUE THREAD

**Issue by fyxwanan** [umijs/qiankun#827]
"@umijs/plugin-qiankun": "2.2.0",
"umi": "^3.0.5",

// qianku配置
  qiankun: {
    master: {
      jsSandbox: false, // 是否启用 js 沙箱，默认为 false
      prefetch: 'all', // 是否启用 prefetch 特性，默认为 true
      defer: true,
    },
  },

PC移动端都生效了，都有日志：
![image](https://user-images.githubusercontent.com/33709049/89400550-a5f1ef00-d746-11ea-963e-8b916b551f17.png)

PC访问可以预加载子应用
![image](https://user-images.githubusercontent.com/33709049/89400471-865ac680-d746-11ea-983e-18beb2b5eb71.png)

移动mobile模式访问失效
![image](https://user-images.githubusercontent.com/33709049/89400618-b86c2880-d746-11ea-9069-014872d5dbdc.png)

请问这个属性跟终端有关系吗？

**Comment by howel52** [comment]
> 请问这个属性跟终端有关系吗？

是的，移动端关闭了预加载

**Comment by fyxwanan** [comment]
> > 请问这个属性跟终端有关系吗？
> 
> 是的，移动端关闭了预加载

那么请问一下是为何关闭了移动端预加载呢，为用户流量做考虑吗，还是遇到了其他什么问题🤔。  或者官方有给出相应的配置，增加开放移动端子项目预加载吗？ 或者后期会考虑开放吗🤔

**Comment by kuitos** [comment]
移动端你偷偷拉流量被用户发现，会被投诉的😂
