### ISSUE TITLE
[Feature Request] 嵌套的微前端项目，子项目内的子项目不渲染

### ISSUE THREAD

**Issue by Oscar-ren** [umijs/qiankun#828]
## Background

目前有`项目 A`，内部注册了`项目 B`，`项目 B`也使用了 qiankun，内部注册了`项目 C`

如果只是简单的 registerMicroApps `项目B`，浏览器会报错 application '项目C' died in status LOADING_SOURCE_CODE

查看了相关 issue 后将 registerMicroApps 方法传递给 `项目 B`，项目B正常渲染，但是项目C不会渲染，代码类似如下
```javascript
props.registerMicroApps(
            microFrontendConfig.map(item => ({
                name: item.name,
                entry: item.entry ? item.entry : `/app/${item.name}`,
                container: '#subapp-container',
                activeRule: genActiveRule(item.activeRule),
            }))
        );

        start({
            prefetch: true,
            singular: true,
        });
```

考虑是否是因为 start 方法引用不一样导致的，将 start 方法也作为 props 传递给 `项目 B`，`项目 C` 仍然不渲染，浏览器报错
`single-spa minified message #1 singleSpa.start() was not called`

求解这种情况该如何处理，谢谢。

## Proposal

希望是主应用不用关心子应用是否也是 qiankun 架构，注册就可使用

**Comment by Oscar-ren** [comment]
`single-spa minified message #1 singleSpa.start() was not called`
是因为`项目B`内也引用了 qiankun，去掉了不报错了，但是`项目C`仍然不渲染

**Comment by gongshun** [comment]
可以参考下我这个https://juejin.im/post/6856569463950639117#heading-29

**Comment by kuitos** [comment]
用 loadMicroApp 就好了，registerMicroApps 是共用 url 的，所以会出现类似路由冲突的问题

**Comment by Swings12138** [comment]
> 用 loadMicroApp 就好了，registerMicroApps 是共用 url 的，所以会出现类似路由冲突的问题

使用load 子应用的vue项目 如何切换路由呢

**Comment by Oscar-ren** [comment]
> 可以参考下我这个https://juejin.im/post/6856569463950639117#heading-29

不行嘞，你的方案当访问 /app-vue-hash 时，都没有加载 /app-qiankun 主应用，子应用还是不会渲染

**Comment by Swings12138** [comment]
感谢，现在已经可以了，我现在是在主应用下的子路由下添加的registerMicroApps，并且在子应用设置了base，从而实现子路由的跳转。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/qiankun"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午4:01
收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;;
抄送:&nbsp;"Dude"<1219649500@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/qiankun] [Feature Request] 嵌套的微前端项目，子项目内的子项目不渲染 (#828)





  
可以参考下我这个https://juejin.im/post/6856569463950639117#heading-29
  
不行嘞，你的方案当访问 /app-vue-hash 时，都没有加载 /app-qiankun 主应用，子应用还是不会渲染

**Comment by humorHan** [comment]
是嵌套应用嘛，请问子应用再去registerMicroApps 是否生效了

**Comment by Oscar-ren** [comment]
> 是嵌套应用嘛，请问子应用再去registerMicroApps 是否生效了

我的项目没生效，最后采用 loadMicroApp 方式实现的

**Comment by humorHan** [comment]
> 感谢，现在已经可以了，我现在是在主应用下的子路由下添加的registerMicroApps，并且在子应用设置了base，从而实现子路由的跳转。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "umijs/qiankun" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月6日(星期四) 下午4:01 收件人:&nbsp;"umijs/qiankun"<qiankun@noreply.github.com&gt;; 抄送:&nbsp;"Dude"<1219649500@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [umijs/qiankun] [Feature Request] 嵌套的微前端项目，子项目内的子项目不渲染 (#828) 可以参考下我这个https://juejin.im/post/6856569463950639117#heading-29 不行嘞，你的方案当访问 /app-vue-hash 时，都没有加载 /app-qiankun 主应用，子应用还是不会渲染 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

问下，有提供demo吗，不太明白怎么实现 @Swings12138 Swings12138

**Comment by wudith** [comment]
子应用的子应用（简称孙子应用）需要配置baseUrl的前缀同子应用，此地址可以从子应用的prod属性传过来动态设置，然后在子应用registerMicroApps设置孙子应用的路由，这样当从子应用跳转到孙子应用就可以匹配子应用的路由规则实现孙子应用的渲染。
