### ISSUE TITLE
子应用使用VUE时，开启experimentalStyleIsolation后样式问题

### ISSUE THREAD

**Issue by HULIANGA** [umijs/qiankun#829]
## What happens?

子应用使用VUE时，开启experimentalStyleIsolation后，第一次加载子应用A正常，切换到另一个子应用B后再回到A，样式没有添加div[data-qiankun=vue]

## Mini Showcase Repository(REQUIRED)

官方仓库内的example

## How To Reproduce

**启动后访问vue应用，样式如下**
![vue1](https://user-images.githubusercontent.com/4363954/89498285-86af9c00-d7f0-11ea-8455-0dc0ba635731.png)
**切换到react15，再切换到vue，样式如下** 
![vue2](https://user-images.githubusercontent.com/4363954/89498347-a8108800-d7f0-11ea-8e75-6b63afbe99a7.png)
**react没有此问题**

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by HULIANGA** [comment]
补充说明：vue微应用添加了提取css的配置才会出现这个问题
css: {
    extract: true,
  },

**Comment by kuitos** [comment]
文档里有说明
![image](https://user-images.githubusercontent.com/5206843/89604108-262a6880-d89d-11ea-8e5a-808f2d27fe62.png)

**Comment by lijing666** [comment]
> 文档里有说明
> ![image](https://user-images.githubusercontent.com/5206843/89604108-262a6880-d89d-11ea-8e5a-808f2d27fe62.png)

@kuitos 但是实际情况下，基本所有的项目都是以link标签的方式插入样式的呢？style方式写的样式很少的，全部写在style里边会导致请求数据巨大；然后qiankun对于html入口里边link的样式是做了处理的，转成了style方式写入，但是写入的时候出现了bug，比如开启这个experimentalStyleIsolation:true属性之后，第一次加载时style的转换是带了scope前缀的，然后在子应用建切换几次后，style的样式又变成原始link的样式了，这个问题是存在的了；不知道我说的有没有问题，请指教，谢谢

**Comment by lijing666** [comment]
@kuitos 其实这个比较好修复了，刚刚看了源码，只需要把loadApp的逻辑移到createElement中就可以了，你看看有什么问题？同样这里建议可以给出一个自定义处理css的注册回调，这样可以方便处理子应用css中资源包含`url(/images/test.png)`或者`url(../images/test.png)`等一系列无法确定css资源请求上下文的场景，毕竟很多项目都是将资源和html放在一起的

```
function createElement(appContent, strictStyleIsolation,configuration,appName,assetPublicPath) {
  var containerElement = document.createElement('div');
  containerElement.innerHTML = appContent; // appContent always wrapped with a singular div

  var appElement = containerElement.firstChild;

  if (strictStyleIsolation) {
    if (!supportShadowDOM) {
      console.warn('[qiankun]: As current browser not support shadow dom, your strictStyleIsolation configuration will be ignored!');
    } else {
      var innerHTML = appElement.innerHTML;
      appElement.innerHTML = '';
      var shadow;

      if (appElement.attachShadow) {
        shadow = appElement.attachShadow({
          mode: 'open'
        });
      } else {
        // createShadowRoot was proposed in initial spec, which has then been deprecated
        shadow = appElement.createShadowRoot();
      }

      shadow.innerHTML = innerHTML;
    }
  }
  //experimentalStyleIsolation的逻辑从loadApp移到createElement这里就可以了，保证切换子应用的时候也会执行这里的逻辑
  if (appElement && isEnableScopedCSS(configuration)) {
    let styleNodes = appElement.querySelectorAll('style') || [];
    styleNodes.forEach(function (stylesheetElement) {
      css.process(appElement, stylesheetElement, appName);
    });
  }

  return appElement;
}

```

**Comment by kuitos** [comment]
> 开启这个experimentalStyleIsolation:true属性之后，第一次加载时style的转换是带了scope前缀的，然后在子应用建切换几次后，style的样式又变成原始link的样式了，这个问题是存在的了

@lijing666  如果是 bug 的话开个 issue 提供可复现仓库吧

**Comment by lijing666** [comment]
> > 开启这个experimentalStyleIsolation:true属性之后，第一次加载时style的转换是带了scope前缀的，然后在子应用建切换几次后，style的样式又变成原始link的样式了，这个问题是存在的了
> 
> @lijing666 如果是 bug 的话开个 issue 提供可复现仓库吧

@kuitos 好的，我看看怎么重提一个issue，并给出复现仓库
