### ISSUE TITLE
关于vue-router全局守卫无法销毁的困惑

### ISSUE THREAD

**Issue by Hades-li** [umijs/qiankun#83]
对于vue的实列可以调用destory函数来销毁。但vue-router并没有提供销毁功能。如果A子项目配置了beforeEach的全局守卫函数，当从A项目切换到B项目时，A项目的路由守卫回调函数依然会被执行，导致全局受到影响。
最好的办法是能在A子项目unmount的时候移除路由监听，但完全没办法去除。
有什么好办法来解决此问题。

**Comment by IndexXuan** [comment]
+1 how to resolve it ? @Hades-li

**Comment by joinwen** [comment]
mark

**Comment by my9074** [comment]
@Hades-li   有解决方案吗?

**Comment by IndexXuan** [comment]
@my9074 貌似 vue-router 最近的版本解决了，随着 new Vue 的 app 实例被销毁，相应的监听会销毁

**Comment by my9074** [comment]
@IndexXuan 是 vue3 版本的 router 还是 vue2 版本的？

**Comment by klonhj2015** [comment]
升级一下vue-router的版本
https://github.com/vuejs/vue-router/pull/3172
