### ISSUE TITLE
[Feature Request] 移动端H5项目接入qiankun 时发现  prefetch.js 中 prefetch函数 在判断为 isMobile后直接return了

### ISSUE THREAD

**Issue by Gairo2021** [umijs/qiankun#831]
## Background

公司多个移动端项目 想接入qiankun 主要为了多个 主应用项目集成复用 业务子应用模块。为了 能有更好的体验，想给个别子应用在主应用加载完以后预加载，但是在 执行start({prefetch:true})以后，虽然development模式下console 打印提示已预加载完，但实际体验和prefetch:false 是一样的，所以查看源码发现 在prefetch.js文件的   prefetch函数中 50行，在子应用执行预加载过程中判断是 isMobile 预加载函数就直接return了。
```
function prefetch(entry, opts) {
  var _this = this;

  if (isMobile || isSlowNetwork) {
    // Don't prefetch if an mobile device or in a slow network.
    return;
  }
```

## Proposal

是否能提供一个参数，在 start 时传入参数时，跳过这个 如果时手机端就结束预加载的判断。

希望给予解答，感谢。

**Comment by kuitos** [comment]
可以改为只判断是慢速网络

pr is welcome

**Comment by merchantli** [comment]
hello，最近在调研 h5 接入乾坤的可行性。想和你具体聊聊，可以详聊一下吗
