### ISSUE TITLE
内存泄露？

### ISSUE THREAD

**Issue by deeWong** [umijs/qiankun#832]
这是bug吗？随着在同一个标签页刷新，内存占用快照在不断变大。。。。是不是有内存泄露？
![image](https://user-images.githubusercontent.com/30404809/89530072-73b4c000-d820-11ea-8e4a-42e8289808d3.png)
下图看看我的项目未使用qiankun重构前的内存
![image](https://user-images.githubusercontent.com/30404809/89530687-811e7a00-d821-11ea-8a81-7aa5670fdff7.png)

希望作者能优化一波。

**Comment by deeWong** [comment]
找到根源了，是开发者工具的问题。开发者工具，在执行eval()操作，会占用内存。
qiankun因为使用eval执行js文件的代码，所以当项目js文件总量很大（尤其在本地开发js文件未被压缩的时候）。每刷新一次页面，占用内存就增加一次。假如项目js文件总大小50M，那么每刷新一次，开发者工具占用内存增加50M。所以在开发的时候会发现电脑机器越来越慢，因为内存被大量占用。

**Comment by kuitos** [comment]
感谢反馈，开发者工具是chrome自带的那个，还是你装的插件？

**Comment by deeWong** [comment]
> 感谢反馈，开发者工具是chrome自带的那个，还是你装的插件？

不是，就是chrome原来自带的开发者工具。刷新是不会清空该工具所占用的内存，导致刷新次数越多，它占用的内存越大。

**Comment by candy-Tong** [comment]
> 找到根源了，是开发者工具的问题。开发者工具，在执行eval()操作，会占用内存。
> qiankun因为使用eval执行js文件的代码，所以当项目js文件总量很大（尤其在本地开发js文件未被压缩的时候）。每刷新一次页面，占用内存就增加一次。假如项目js文件总大小50M，那么每刷新一次，开发者工具占用内存增加50M。所以在开发的时候会发现电脑机器越来越慢，因为内存被大量占用。

我想问一下，eval导致chrome devtool这个有相关的资料吗？我也遇到了这个问题，想知道相关的资料，以及解决方法

**Comment by lovedaan** [comment]
> > 找到根源了，是开发者工具的问题。开发者工具，在执行eval()操作，会占用内存。
> > qiankun因为使用eval执行js文件的代码，所以当项目js文件总量很大（尤其在本地开发js文件未被压缩的时候）。每刷新一次页面，占用内存就增加一次。假如项目js文件总大小50M，那么每刷新一次，开发者工具占用内存增加50M。所以在开发的时候会发现电脑机器越来越慢，因为内存被大量占用。
> 
> 我想问一下，eval导致chrome devtool这个有相关的资料吗？我也遇到了这个问题，想知道相关的资料，以及解决方法

在另一个issues有小伙伴回复了，在入口文件引用zone.js貌似可以解决，可以试下。#1073

**Comment by humorHan** [comment]
> 
有官方出处吗，求指导~

**Comment by jiangyh1024** [comment]
@deeWong @humorHan 有解决方案吗？ 子应用卸载后 未释放内存

**Comment by liuyib** [comment]
> @deeWong @humorHan 有解决方案吗？ 子应用卸载后 未释放内存

+1
