### ISSUE TITLE
微应用在主应用下，浏览器点击回退按钮，页面不渲染，成白屏

### ISSUE THREAD

**Issue by Swings12138** [umijs/qiankun#835]
q1：微应用 挂在 主应用下的某个路由下
微应用也有路由，现在微应用可以正常跳转，但是点击浏览器的回退按钮，页面就空白了
q2： 主应用和微应用的css 污染怎么解决呢

**Comment by kuitos** [comment]
1. 提供可复现仓库
2. https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB
