### ISSUE TITLE
请问微应用挂载不上是什么原因呢

### ISSUE THREAD

**Issue by yitiaoxianyu0927** [umijs/qiankun#838]
Uncaught Error: application 'vueApp' died in status SKIP_BECAUSE_BROKEN: [qiankun] Target container with #vue not existed after vueApp mounted!

**Comment by dengBox** [comment]
错误信息说的是，没有容器节点，检查一下你的版本，看看对应的文档排查一下

**Comment by dinglittle** [comment]
同款问题, 时好时坏

**Comment by tangs8dj** [comment]
意思是vueApp微应用加载的时候， 没有找到挂载节点#vue

**Comment by yitiaoxianyu0927** [comment]
找到问题了  子应用和父应用渲染的都是#app

**Comment by fengxianqi** [comment]
> 找到问题了 子应用和父应用渲染的都是#app

求分享一下解决思路

**Comment by dengBox** [comment]
> > 找到问题了 子应用和父应用渲染的都是#app
> 
> 求分享一下解决思路

子应用额父应用不要挂载在一个dom上，应该是父子关系

**Comment by fengxianqi** [comment]
> > > 找到问题了 子应用和父应用渲染的都是#app
> > 
> > 
> > 求分享一下解决思路
> 
> 子应用和父应用不要挂载在一个dom上，应该是父子关系

试过这个方案了，无效。


尝试过的无效方案
----

方案一：
父应用的index.html使用`<div id="root-app"></div>`，子应用的index.html使用`<div id="app"></div>`，即上面所说的父子节关系方案，试过了无效。

方案二：
父应用mounted后再调用`registerMicroApps`注册子应用，**也无效**。父应用`main.js`
```
new Vue({
  render: h => h(App),
  mounted: () => {
    console.log('subapp-viewport', document.querySelector('#subapp-viewport'))
    registerMicroApps([ {  name: 'app', ... } ], { });
    start();
  },
}).$mount('#root-app');
```

**Comment by tangs8dj** [comment]
@fengxianqi  fengxianqi需要交流一下吗？

**Comment by fengxianqi** [comment]
> > > > 找到问题了 子应用和父应用渲染的都是#app
> > > 
> > > 
> > > 求分享一下解决思路
> > 
> > 
> > 子应用和父应用不要挂载在一个dom上，应该是父子关系
> 
> 试过这个方案了，无效。
> 
> ## 尝试过的无效方案
> 方案一：
> 父应用的index.html使用`<div id="root-app"></div>`，子应用的index.html使用`<div id="app"></div>`，即上面所说的父子节关系方案，试过了无效。
> 
> 方案二：
> 父应用mounted后再调用`registerMicroApps`注册子应用，**也无效**。父应用`main.js`
> 
> ```
> new Vue({
>   render: h => h(App),
>   mounted: () => {
>     console.log('subapp-viewport', document.querySelector('#subapp-viewport'))
>     registerMicroApps([ {  name: 'app', ... } ], { });
>     start();
>   },
> }).$mount('#root-app');
> ```
> 
> 这句代码`console.log('subapp-viewport', document.querySelector('#subapp-viewport'))`能正常获取到dom，说明此时已经有了dom了，但仍报`Uncaught Error: application 'xxxx' died in status SKIP_BECAUSE_BROKEN: [qiankun] Target container with #subapp-viewport not existed while yunying mounting!`
> 
> ```
> Uncaught Error: application 'xxxx' died in status SKIP_BECAUSE_BROKEN: [qiankun] Target container with #subapp-viewport not existed while yunying mounting!
> ```
> 
> **这个问题是生产环境清空缓存后首次进入页面时才会出现，点击刷新后会正常。开发环境localhost是正常的**

我的问题已经排查解决了。不是qiankun导致的，是因为我这边的子应用`index.html`使用了一个高德地图的js导致的:
```
<script src="https://webapi.amap.com/maps?v=1.4.15&key=&plugin=AMap.Geocoder,AMap.PlaceSearch"></script>
```
该js首次加载时会使用document.write去复写一次整个html，导致html中不存在子应用容器的div，从而导致了这个的问题，移除该js就解决了。

**Comment by yitiaoxianyu0927** [comment]
console.log("render",props);
  const { container } = props;

  instance = new Vue({

    router,
    render: h => h(App)

  }).$mount(container ? container.querySelector('#app') : '#app')  渲染到父应用子区域的#app，我这么解决好用了。

**Comment by kuitos** [comment]
高德地图升级到 2.0 即可 https://lbs.amap.com/api/jsapi-v2/summary
