### ISSUE TITLE
路由劫持，当触发过一次微前端加载后，如果失败，点击其他路由还是会去尝试重新加载这个失败的微前端(已经复现)

### ISSUE THREAD

**Issue by zjscy666** [umijs/qiankun#844]
## What happens?

https://github.com/zjscy666/qiankun-activeRule
步骤： 1.yarn start
2.http://localhost:8000/home输入
3.切换reportapp和vue（点击页面按钮即可），因为微前端加载慢，所以需要多切换几次，多试几次

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by zjscy666** [comment]
作者大大 npm包啥时候更新

**Comment by han-neil** [comment]
我也遇到同样的问题，但好像没人管，后面我只能放弃他们的异常捕获方法了

**Comment by kuitos** [comment]
没有子应用的 repo ？

**Comment by qiuzhenlin1990** [comment]
确实，我也遇到过。某个子应用资源请求失败会影响整个系统所有子应用的路由切换(除非刷新页面)。一个子应用资源加载失败，如果尝试加载另外一个子应用，还是会请求上一个失败的资源

**Comment by qiuzhenlin1990** [comment]
> ## What happens?
> https://github.com/zjscy666/qiankun-activeRule
> 步骤： 1.yarn start
> 2.[http://localhost:8000/home输入](http://localhost:8000/home%E8%BE%93%E5%85%A5)
> 3.切换reportapp和vue（点击页面按钮即可），因为微前端加载慢，所以需要多切换几次，多试几次
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue.
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **qiankun Version**:
> * **Platform Version**:
> * **Browser Version**:

问题解决了么？

**Comment by lucien925** [comment]
同求解决办法~~

**Comment by xiezhongfu** [comment]
这个应该是 single-spa 的特性，[LOAD_ERROR 大于 200ms 会重试](https://github.com/single-spa/single-spa/blob/master/src/applications/apps.js#L43)

**Comment by qiuzhenlin1990** [comment]
> 这个应该是 single-spa 的特性，[LOAD_ERROR 大于 200ms 会重试](https://github.com/single-spa/single-spa/blob/master/src/applications/apps.js#L43)

如何解决这个问题呢？某个子应用加载失败会影响到其他子应用页面的正常渲染

**Comment by Old-poplar** [comment]
这个问题有找到解决方法么？
