### ISSUE TITLE
微应用路由跳转后，点击浏览器后退按钮，页面白屏

### ISSUE THREAD

**Issue by Swings12138** [umijs/qiankun#845]
thanks code;

Q：
father为主应用  child为子应用
点击父应用下的能效管理，可以正常加载子应用，点击子应用的跳转按钮也可以正常跳转，但是跳转后，点击浏览器回退按钮，页面白屏

代码重现
https://github.com/Swings12138/qiankunDemo.git

npm install 
npm run serve

求解决

**Comment by fengxianqi** [comment]
看了一下代码有不对的地方：
1. father的main.js没有引用qiankun
2. child的package.json的name仍是father，应为父应用注册子应用时所使用的name
示例代码先写完整吧

**Comment by Swings12138** [comment]
> 看了一下代码有不对的地方：
> 
> 1. father的main.js没有引用qiankun
> 2. child的package.json的name仍是father，应为父应用注册子应用时所使用的name
>    示例代码先写完整吧

我是在夫应用得mounted里面 引入得乾坤 ，这个package.json 我改了 还是不行

**Comment by cshsh** [comment]
@fengxianqi 为什么package.json的name，要与父应用注册子应用时所用的name一致

**Comment by fengxianqi** [comment]
> @fengxianqi 为什么package.json的name，要与父应用注册子应用时所用的name一致

因为这个项目里面vue.confg.js的output写明了name是依赖于package.json的name，而qiankun规定了output是必须要name能匹配上的。
实际上，只需要保证output的name与父应用注册的子应用name一致即可，不需要与package.json的name有关联。

**Comment by gongshun** [comment]
原因是路由冲突和路由不匹配。刷新和回退是一样的，当你在 `/nxgl/child2` 刷新，也会白屏，原因是主项目没有这个路由，所以不会加载任何页面（白屏）。

如果你想在某个路由页面注册子应用，你必须保证你的布局容器页面会加载。办法有两个：
1. 卸载app.vue（一些菜单导航不想显示使用 v-show/v-if 隐藏）
2. 给这个路由页面的 path 后面加一个 *，只要前缀匹配，都会加载

另外，可以在某个路由页面注册子项目，但是你需要在 mounted 周期注册并启动
