### ISSUE TITLE
qq maps 跨域了有什么办法可以解决

### ISSUE THREAD

**Issue by lilinfan** [umijs/qiankun#849]

**Comment by kuitos** [comment]
参考 https://qiankun.umijs.org/zh/faq#%E5%BE%AE%E5%BA%94%E7%94%A8-jsonp-%E8%B7%A8%E5%9F%9F%E9%94%99%E8%AF%AF%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%EF%BC%9F
