### ISSUE TITLE
子应用加载后又消失了，没有触发过相关生命周期，是怎么回事？

### ISSUE THREAD

**Issue by zeyongTsai** [umijs/qiankun#852]
## What happens?

如题：子应用加载完毕后，断点在子应用（Vue应用）的mounted 事件里面的时候，都能看到应用已经被渲染。但是之后被渲染的东西就不见了，变成了
```html
<!--  script //localhost:8081/bundle.js replaced by import-html-entry -->
```
应用的  beforeDestroy 或者 应用对应的 render component 自己的  beforeDestroy 都没有触发，主应用的路由也没有变化，就是内容不见了。

## Context

- **qiankun Version**:  2.0.20
- **Platform Version**:  win10
- **Browser Version**: Chrome/81.0.4044.138

**Comment by kuitos** [comment]
提供可复现仓库后再 reopen

**Comment by maquannene** [comment]
+1.
主应用使用 qiankun demo；
子应用用的 umi，跟楼主情况一致，会 render 出来，然后再消失，原因就是 
`<!--  script //localhost:8081/bundle.js replaced by import-html-entry -->`

**Comment by savelifeme** [comment]
+1
主应用使用qiankuan umi 插件
子应用是vue2
html直接不加载js 
![image](https://github.com/umijs/qiankun/assets/32872731/e4cd59e6-0915-4887-a8e6-2db77f9e3721)

楼主 解决了吗
