### ISSUE TITLE
手动加载和卸载子应用，加载越来越慢最后页面崩溃

### ISSUE THREAD

**Issue by hulandianqing** [umijs/qiankun#853]
## What happens?

手动控制子应用的加载，每次加载前卸载上一个加载完毕的子应用。大概加载7次以后加载很慢。10次以后页面崩溃
通过浏览器任务管理器发现页面加载时占用cpu很高

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://github.com/hulandianqing/qiankun-test

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.点击测试
![image](https://user-images.githubusercontent.com/5196263/89981779-177df000-dca7-11ea-839c-219a2eb2758e.png)
2.弹框提示加载完成
![image](https://user-images.githubusercontent.com/5196263/89981873-42684400-dca7-11ea-84ce-f7b6d17734be.png)
3.持续点击测试按钮会发现越来越慢
**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
2.0.20
- **Platform Version**:
element ui 2.13.2
- **Browser Version**:
Microsoft Edge 84.0.522.58

**Comment by hulandianqing** [comment]
我把父应用的store设置到子应用的data中。
![image](https://user-images.githubusercontent.com/5196263/89986171-beb25580-dcae-11ea-9a67-3b7052b086df.png)

把这块代码去掉后不会出现了。
是不是这种写法的问题？我应该怎么改？

**Comment by hulandianqing** [comment]
改为使用update更新子应用了

**Comment by luhuaxin** [comment]
老铁，我也遇到这个问题，反复切换子应用，大概7,8次后页面就崩溃了

**Comment by itnannan** [comment]
老铁 怎么手动卸载子应用呀
