### ISSUE TITLE
生命周期一直抛错，按照文档来， 不知道哪里有问题

### ISSUE THREAD

**Issue by weishaodaren** [umijs/qiankun#858]
## What happens?

主应用 umi qiankun 三个子应用 vue react umi（目前都能跑） 现在加入两个 vue子应用 ：
vue 2.5 webpack 4  \ vue cli3 
package.json name 也唯一

![22910384-8E10-4702-9867-D3220A793599](https://user-images.githubusercontent.com/45391716/90002221-f5936600-dcc4-11ea-8f34-15e4dfe35c4c.png)
![54618488-AD05-41c8-8A3E-84F00576305D](https://user-images.githubusercontent.com/45391716/90002223-f75d2980-dcc4-11ea-8110-13fb14598ac6.png)

`import './public-path'
import 'babel-polyfill'
import Vue from 'vue'
import router from './router'
import store from './store'
import 'normalize.css/normalize.css' // A modern alternative to CSS resets
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '@/styles/index.scss' // global css
import App from './App'
import cache from '@/utils/cache'
import '@/permission' // permission control
import '@/styles/animate.css'
import * as filters from './filters' // global filters
import moment from 'moment'
// 自定义全局点击空白处组件
import clickoutside from './directives'
import empty from './directives/empty'
import photo from './directives/photo'
// 表情
import {
  emoji
} from './utils/emoji'

/** 事件传递 */
import VueBus from 'vue-bus'

/** 常用flex组件 */
import {
  Flexbox,
  FlexboxItem
} from '@/components/flexbox'

/** 懒加载图片 */
import VueLazyload from 'vue-lazyload'

Vue.use(ElementUI, {
  size: 'small',
  zIndex: 3000,
}).use(VueBus).use(VueLazyload, {
  preLoad: 1.3,
  error: require('@/assets/img/send_img.png'),
  loading: require('@/assets/img/loading.gif'),
  attempt: 1,
})

cache.loadingCache()

Vue.component('flexbox', Flexbox)
Vue.component('flexbox-item', FlexboxItem)

// 注册全局过滤器
Object.keys(filters).forEach(key => {
  Vue.filter(key, filters[key])
})

// 处理时间的过滤器
Vue.use(require('vue-moment'))
moment.locale('zh_cn')

Vue.directive('clickoutside', clickoutside)
Vue.use(empty)
Vue.use(photo)

Vue.prototype.emoji = emoji

Vue.config.productionTip = false

// let router = null
let instance = null

function render(props = {}) {
  if (props) {
    // 注入 actions 实例
    // actions.setActions(props)
  }
  const {
    container
  } = props

  instance = new Vue({
    router,
    store,
    data: {
      eventHub: new Vue(),
    },
    render: h => h(App),
  }).$mount(container ? container.querySelector('#slave-app-crm') : '#slave-app-crm')
}

if (!window.__POWERED_BY_QIANKUN__) {
  render()
}

function storeTest(props) {
  props.onGlobalStateChange && props.onGlobalStateChange((value, prev) => console.log(`[onGlobalStateChange - ${props.name}]:`, value, prev), true)
  props.setGlobalState &&
    props.setGlobalState({
      ignore: props.name,
      user: {
        name: props.name,
      },
    })
}
export async function bootstrap() {
  console.log('[vue] vue app bootstraped')
}

export async function mount(props) {
  console.log('[vue] props from main framework', props)
  storeTest(props)
  render(props)
}

export async function unmount() {
  instance.$destroy()
  instance.$el.innerHTML = ''
  instance = null
  router.length = 0
  // router = null
}

function emptyAction() {
  console.log('Current action is empty')
}

class Actions {
  // 默认值为空 Action
  actions = {
    onGlobalStateChange: emptyAction,
    setGlobalState: emptyAction,
  }

  /**
   * 设置 actions
   */
  setActions(actions) {
    this.actions = actions
  }

  /**
   * 映射
   */
  onGlobalStateChange(...args) {
    return this.actions.onGlobalStateChange(...args)
  }

  /**
   * 映射
   */
  setGlobalState(...args) {
    return this.actions.setGlobalState(...args)
  }
}
const actions = new Actions()
export default actions
![00F9019F-15AD-433a-B84F-86C0FD149749](https://user-images.githubusercontent.com/45391716/90002420-355a4d80-dcc5-11ea-8645-7f8c159d6f21.png)
`

**Comment by weishaodaren** [comment]
![C70DFF14-CB90-4f29-9D4B-5C787F6D2470](https://user-images.githubusercontent.com/45391716/90003183-4c4d6f80-dcc6-11ea-8892-08f7cc85f861.png)
补一张 抛错信息

**Comment by gaorubin1990** [comment]
请问这个问题如何解决的？我的显现是报了这个问题，但是子应用能正常显示

**Comment by yaya1286249672** [comment]
同问  最后怎么解决的 啊
