### ISSUE TITLE
Loading two microapps with { singular: false } doesn't work

### ISSUE THREAD

**Issue by mwasilewski** [umijs/qiankun#859]
## What happens?

I have one master app and two micro apps that I want to load on same page.

I see only one loaded:

<img width="1063" alt="Screen Shot 2020-08-12 at 14 09 57" src="https://user-images.githubusercontent.com/994439/90013419-85c1b300-dca5-11ea-8b1f-52be66b91862.png">

My template:

```
<div id="container">
    <h2>App 1 container:</h2>
    <div id="app1Container" />
    <h2>App 2 container:</h2>
    <div id="app2Container" />
  </div>
```
apps passed to registerMicroApps:

```
apps: [
   { name: 'app-1', entry: '//localhost:8082', container: '#app1Container', activeRule: () => true },
   { name: 'app-2', entry: '//localhost:8083', container: '#app2Container', activeRule: () => true },
]
```

and starting like this:

```
start({ singular: false })
```

## Mini Showcase Repository:

https://github.com/mwasilewski/qiankun-issue/

here is master vue app with config:

https://github.com/mwasilewski/qiankun-issue/blob/master/master/src/App.vue

## How To Reproduce

just run all 3 apps with `yarn serve` and go to http://localhost:8081/

## Context

- **qiankun Version**: 2.0.20
- **Platform Version**: mac
- **Browser Version**: all

**Comment by kuitos** [comment]
You need to set the vue mount container like this https://github.com/umijs/qiankun/blob/6e29a3cf345d84075402f1903db52fa548b4539b/examples/vue/src/main.js#L29

otherwise they will be replaced by each other as they use the same container id https://github.com/mwasilewski/qiankun-issue/blob/master/app-1/src/main.js#L11

**Comment by gongshun** [comment]
> You need to set the vue mount container like this
> 
> https://github.com/umijs/qiankun/blob/6e29a3cf345d84075402f1903db52fa548b4539b/examples/vue/src/main.js#L29
> 
> otherwise they will be replaced by each other as they use the same container id https://github.com/mwasilewski/qiankun-issue/blob/master/app-1/src/main.js#L11

虽然这样能解决问题，但是不太符合规范吧。

他这个问题是由于 app1 和 app2 都使用了同一个根 id `#app`，导致加载 app2 时，实例化到了第一个应用的根id #app 中。一个HTML中id应该是唯一的，修改子应用根 id 比较合理。

English：

Although this can solve the problem, it does not meet the specifications.

His problem was that app1 and app2 both used the same root id `#app`, which caused it to be instantiated to the root id #app of the first application when app2 was loaded. The id in an HTML should be unique. It is reasonable to modify the root id of the sub-application.

**Comment by kuitos** [comment]
Usually a child application doesn't know whether they are unique or not, as they are not aware of each other, and it shouldn't care imo.

**Comment by gongshun** [comment]
You can set the root id to the name of the sub-project, so that it can be unique

**Comment by kuitos** [comment]
You could never guarantee your project name is unique, while you could not know who will be migrated into the same master app with you.
