### ISSUE TITLE
query changed,but render same as first time

### ISSUE THREAD

**Issue by humingzhi** [umijs/qiankun#86]
## What happens?
query change, but get same render result

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce
**Steps to reproduce the behavior:**
1. navigate to /user/info?id=1
2.navigate to /user/info?id=2

**Expected behavior**
1. show user id=1 info
2. show user id=2 info

## Context

- **Node Version**:
- **Platform**:

is qiankun cache render result using url as key?

**Comment by kuitos** [comment]
Never did that

**Comment by chendanping** [comment]
@humingzhi Has the problem been solved? I got the same problem since add qiankun
