### ISSUE TITLE
子应用A 跳入子应用B 没有问题，但是子应用B往回跳就会报错 ，出现找不到模块的情况（子应用使用的是异步组件，动态注册路由表）

### ISSUE THREAD

**Issue by lance-li** [umijs/qiankun#860]
![image](https://user-images.githubusercontent.com/21050392/90087586-c4ac4300-dd4f-11ea-89cc-5e42717296c1.png)
<img width="694" alt="1597280840221_ADEFADEB-7383-4F02-B738-C89804A1F448" src="https://user-images.githubusercontent.com/21050392/90087653-e4dc0200-dd4f-11ea-8978-2ebbe72f77cf.png">
<img width="883" alt="1597280876924_96812411-F9D4-4068-BC52-02459E3F6AB9" src="https://user-images.githubusercontent.com/21050392/90087659-e73e5c00-dd4f-11ea-9bde-9e6efad1a779.png">

**Comment by cpa0701** [comment]
1.是chunk找不到吗？我也遇到了，解决办法是把所有的依赖包都同意了版本
2.子应用间的跳转我用的都是location.href或a标签的href跳转，同时带上了activeRule路径
能提供下报错信息吗？

**Comment by lance-li** [comment]
已解决，犯了低级错误
