### ISSUE TITLE
[Feature Request] 关于路由复用和qiankun的冲突点

### ISSUE THREAD

**Issue by KellenHe** [umijs/qiankun#862]
## Background

![image](https://user-images.githubusercontent.com/9713892/90202787-47e19d80-de11-11ea-83e1-f0dc35b1ee69.png)

路由复用功能可以在一个界面输入一些数据，跳转到别的界面，再切换回来，输入的数据还存在。
但是qiankun当跳转的别的界面，会卸载。每次进入都会刷新。
请问有没有一种方式可以解决这个问题？

## Proposal

有没有策略可以控制qiankun的unmount。

**Comment by gongshun** [comment]
使用 loadMicroApp 加载子项目就可以了

**Comment by KellenHe** [comment]
@gongshun 谢谢，问题解决了。还想请问下，使用loadMicroApp后是否需要手动卸载？

**Comment by gongshun** [comment]
> @gongshun 谢谢，问题解决了。还想请问下，使用loadMicroApp后是否需要手动卸载？

需要的，loadMicroApp返回一个对象，里面就包含了卸载的方法

**Comment by KellenHe** [comment]
@gongshun 再次感谢
目前还遇到一个样式问题想请教一下，
我的主应用是angular，子应用是react。
主应用angular使用了keep-alive。

在进行页面切换时，发现qiankun劫持了angular组件的样式并加载到了错误的地方。
![image](https://user-images.githubusercontent.com/9713892/90353400-aceafc80-e078-11ea-86f2-faad8d2f2ec1.png)
请问这个有方法解决吗

**Comment by gongshun** [comment]
> 在进行页面切换时，发现qiankun劫持了angular组件的样式并加载到了错误的地方。

这是个老 bug 了，https://github.com/umijs/qiankun/issues/578

**Comment by KellenHe** [comment]
@gongshun 谢谢，问题解决了。

**Comment by KellenHe** [comment]
@gongshun 还想请教一个问题，关于mock数据，子应用单独运行可以正常mock，嵌入到主应用之后发送的并没有被mock，而是直接发送了请求，没有拦截成功。

**Comment by gongshun** [comment]
> @gongshun 还想请教一个问题，关于mock数据，子应用单独运行可以正常mock，嵌入到主应用之后发送的并没有被mock，而是直接发送了请求，没有拦截成功。

子应用独立运行时，mock是node服务器代理拦截实现的，如果你的主子应用都在本地开发环境，理论上这个代理还是生效的

**Comment by KellenHe** [comment]
@gongshun 子应用是代理在8000端口，主应用是4200端口。可能是代理的端口不一样，子应用的devserver在嵌入到主应用后无效了。

**Comment by Tinet-zhangmd** [comment]
您好，我现在主框架跟子框架都是angular，使用loadMicroapp做加载,但出现了路由总是跳转到使用loadMicroapp的页面，您这边存在这种问题吗？
