### ISSUE TITLE
两个做了异步加载的子应用快速切换，会导致window全局变量丢失

### ISSUE THREAD

**Issue by deeWong** [umijs/qiankun#863]
比如说，有两个子应用A、B，入口文件为a.js及b.js。
网页第一次渲染，进入A子应用。
然后点击B子应用（执行的逻辑如下：fetch加载b.js，eval执行b.js），再快速切回A子应用（执行逻辑如下：记录b应用当前的全局变量快照，切换A应用）。
最后，再次点击B子应用（这个时候不会重新加载并执行b.js），可能会页面空白（目前发现有做异步加载的应用会这样）。
有一种情况：
如果b.js还在加载过程中，马上切换A子应用，会导致 `记录b应用的全局快照` 这一操作并不完全准确。因为 `执行b.js` 过程中可能会注入或修改一些全局变量，但没有记录到快照中，导致遗失，从而导致再次点击B子应用会页面空白。

**Comment by deeWong** [comment]
按照目前框架提供的能力，倒是有一种方案可以处理这个问题，就是使用手动加载子应用，自己控制什么时候需要重新加载子应用。

**Comment by Deturium** [comment]
按照目前 qiankun 的沙箱设计，应该并不会因为这样的切换导致混乱
提供一下复现例子

**Comment by deeWong** [comment]
发现最新版本的qiankun还是有问题，demo地址https://github.com/deeWong/qiankun-async-demo。复现步骤看readme

**Comment by deeWong** [comment]
> 发现最新版本的qiankun还是有问题，demo地址[https://github.com/deeWong/qiankun-async-demo。](https://github.com/deeWong/qiankun-async-demo%E3%80%82) 复现步骤看readme

@Deturium

**Comment by whereiscode** [comment]
iframe里我发现是会window定义的方法丢失 这是真的

**Comment by kuitos** [comment]
released v2.1.0
