### ISSUE TITLE
Create React App 作为主应用，Umi作为子应用，创建的应用出现报错

### ISSUE THREAD

**Issue by snowtreetree** [umijs/qiankun#868]
## What happens?

项目执行时出现报错

![image](https://user-images.githubusercontent.com/30932683/90369906-14b43e00-e09f-11ea-8b61-66de8ab38055.png)

```js
Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at JsonpReceiver.F4Ei.JsonpReceiver._cleanup (devScripts.js:2233)
    at JsonpReceiver.F4Ei.JsonpReceiver._abort (devScripts.js:2216)
    at HTMLScriptElement.script.onload (devScripts.js:2271)
    at success (dynamicAppend.js:154)
    at schedule (index.js:208)
    at index.js:216
    at new Promise (<anonymous>)
    at index.js:215
```

![image](https://user-images.githubusercontent.com/30932683/90370481-0e729180-e0a0-11ea-956c-14b138013ffb.png)

```js
index.js:178 Uncaught SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at exec (index.js:178)
    at schedule (index.js:205)
    at index.js:216
    at new Promise (<anonymous>)
    at index.js:215
```

![image](https://user-images.githubusercontent.com/30932683/90370550-26e2ac00-e0a0-11ea-8187-41e7bd2830e8.png)

![image](https://user-images.githubusercontent.com/30932683/90501220-9a5aeb00-e17e-11ea-8eb6-7a0f943ef761.png)

```js
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

**[for-qiankun-example](https://github.com/snowtreetree/for-qiankun-example)**
## How To Reproduce

- **项目使用create-react-app作为主应用，Umi作为子应用。**

- **项目启动，分别进入到`main-app`和`app1`，执行yarn start。**

- **浏览器打开http://localhost:3000/app1**

## Context

- **qiankun Version**: 2.0.21
- **Umi Version**: 3.2.16
- **Platform Version**: 
- **Browser Version**:

**Comment by snowtreetree** [comment]
@kuitos 大佬，是我这边打开方式有问题吗？😂。

**Comment by haoyinag** [comment]
@snowtreetree @sorrycc 遇到同样的问题

**Comment by jerexyz** [comment]
这个其实是因为sub-app 热更新的dev-script 链接不对造成的。
参考https://github.com/umijs/umi/issues/4441

使用[xSwitch](https://chrome.google.com/webstore/detail/xswitch/idkjhjggpffolpidfkikidcokdkdaogg/related)配置如下代理即可解决：
![image](https://user-images.githubusercontent.com/5208531/91017292-a2a0a380-e620-11ea-81f1-27d96c13fb61.png)

**Comment by haoyinag** [comment]
@jerexyz 我配置了 ，但还是报错，应该是我配置不对
我是用`npm-run-all`启动的，
然后主应用是`http://10.100.13.179:3000/`，vue是`http://10.100.13.179:1111`，都正常，
就是umi的`http://10.100.13.179:2222`报错

然后xswitch配置
```js
{
  "proxy": [
    [
      "(.*)/dev-server/(.*)", // https://www.sample.com/path1/path2/index.js
      "http://10.100.13.179:3000/dev-server/$2", // http://127.0.0.1:3000/index.js
    ],
  ],
}
```

**该怎么用这个，还是我那里弄错了，也没有别的服务在跑的**

**Comment by pingbaobao** [comment]
解决了吗，相同问题

**Comment by virtueDe** [comment]
请问问题怎么解决  我的 Version 也是 2.0.21   子应用使用百度地图 就会报 
![image](https://user-images.githubusercontent.com/46802209/92548938-cd2e6580-f28a-11ea-8607-77ecb6f2bcad.png)
这问题

**Comment by poppyLuo** [comment]
> 请问问题怎么解决 我的 Version 也是 2.0.21 子应用使用百


> 请问问题怎么解决 我的 Version 也是 2.0.21 子应用使用百度地图 就会报
> ![image](https://user-images.githubusercontent.com/46802209/92548938-cd2e6580-f28a-11ea-8607-77ecb6f2bcad.png)
> 这问题

遇到相同问题，请问怎么解决的？

**Comment by giscafer** [comment]
类似问题，本地可以，打包部署后访问子应用资源错误

```
 SyntaxError: Unexpected token '<' at eval
```

![image](https://user-images.githubusercontent.com/8676711/106081902-afd43800-6154-11eb-8166-5d5a9de8e60c.png)
![image](https://user-images.githubusercontent.com/8676711/106081934-bebaea80-6154-11eb-8fba-47423a737d7a.png)

**Comment by GOGOGOSIR** [comment]
> > 请问问题怎么解决 我的 Version 也是 2.0.21 子应用使用百
> 
> > 请问问题怎么解决 我的 Version 也是 2.0.21 子应用使用百度地图 就会报
> > ![image](https://user-images.githubusercontent.com/46802209/92548938-cd2e6580-f28a-11ea-8607-77ecb6f2bcad.png)
> > 这问题
> 
> 遇到相同问题，请问怎么解决的？

我也是遇到相同的问题

**Comment by snowtreetree** [comment]
@GOGOGOSIR @giscafer @poppyLuo @virtueDe @pingbaobao 
非常抱歉，我最近也没在关注这块，试了下我之前的项目，替换了子应用的端口号，就没再报对应的错误。
