### ISSUE TITLE
[Bug]子应用手动加载卸载再加载后，部分变量会赋值给已卸载的 proxy window 对象

### ISSUE THREAD

**Issue by Oscar-ren** [umijs/qiankun#869]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

使用 loadMicroApp 加载了一个子应用，点击菜单切换到其他页面，该子应用被 unmount 卸载。

然后点回之前的菜单，重新 loadMicroApp 该子应用，发现页面报错类似如下：

`Set window.regeneratorRuntime while sandbox destroyed or inactive in panyuan!` 

经过排查后发现，是 execScripts 中被 with(window) 包裹的代码加载其他 webpack 模块引起的，这个被引入的模块中 window 对象还是之前被卸载的子应用。

暂时还没定位到为什么会发生这种问题，想问一下是否有思路和解决办法，谢谢。

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置

- 先 loadMircroApp 子应用 a
- 切换路由，a.unmount()
- 再 loadMicroApp 子应用 a

控制台出现报错如下
![image](https://user-images.githubusercontent.com/9464221/90401716-ee0efb00-e0d0-11ea-86c9-3a02c8d09a3d.png)

其中时间戳是我为了区分前后两个子应用打的标记，可以看出报错的子应用标记和当前加载的不一样 

## 相关环境信息

已升级到最新版本 2.0.20

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by Oscar-ren** [comment]
发现是 globalObject 配置的问题，使用的 create-react-app 默认为 this，修改成 window 后问题修复

**Comment by ChrisPei** [comment]
> 发现是 globalObject 配置的问题，使用的 create-react-app 默认为 this，修改成 window 后问题修复

非常有帮助，高质量的issues

**Comment by gaofei019** [comment]
> 发现是 globalObject 配置的问题，使用的 create-react-app 默认为 this，修改成 window 后问题修复

如何配置？
