### ISSUE TITLE
子应用添加了__webpack_public_path__ = 'window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__'配置路径不正确获取不到资源

### ISSUE THREAD

**Issue by miniai** [umijs/qiankun#870]
![4P8Q$HL34JFRWYAZ61GHSD4](https://user-images.githubusercontent.com/8953012/90404252-c0c44c00-e0d4-11ea-8163-15dcb660848d.png)
![NJ9V~19QQ~W W21D)F7HSKW](https://user-images.githubusercontent.com/8953012/90404276-c883f080-e0d4-11ea-964e-60c1eab4832c.png)
地址应该为http://aqzl.com/userCenter/

**Comment by miniai** [comment]
userCenter子应用是配置在二级目录下，单独访问没有问题，主应用加载的时候，加载不到资源，会报跨域问题，实际上子应用nginx配置了可跨域

**Comment by miniai** [comment]
直接写死http://aqzl.com/userCenter/就对了

**Comment by gongshun** [comment]
你的 entry 也写成 `http://aqzl.com/userCenter/`就可以了，最后面有一个 `/`

**Comment by miniai** [comment]
谢谢，我是少了个```/```，我试试，一个斜杠找死我了····
