### ISSUE TITLE
请问 vue父子应用hash路由开发模式能调用 生产模式调用不了 

### ISSUE THREAD

**Issue by yitiaoxianyu0927** [umijs/qiankun#871]
开发模式   localhost:1234 调用 localhost:10100  
生产模式   ip:port/a 调用 ip:port/b

{
    name:"vueApp",
    //entry:"//localhost:10100",   开发模式
    entry:"//&{ip}:&{port}/qiankun-vue",  生产模式
    container: '#micro',
    activeRule: '/#/vue'
 }

**Comment by gongshun** [comment]
`${ip}:${port}/qiankun-vue/` 最后面加一个 / 试试
