### ISSUE TITLE
clearInterval(undefined|null)在chrome上不会报错，在ie和edge上报错：调用的对象无效

### ISSUE THREAD

**Issue by omglhw** [umijs/qiankun#872]
edge浏览器
![image](https://user-images.githubusercontent.com/34580322/90465943-13d4e800-e143-11ea-9130-6fec4c7e114f.png)

chrome浏览器

![image](https://user-images.githubusercontent.com/34580322/90465990-30712000-e143-11ea-857f-54592f9f25c4.png)

**Comment by kuitos** [comment]
edge 什么版本？84 上试了下没复现

**Comment by kuitos** [comment]
测试下来只有低版本的 edge 才有这个问题，猜测是低版本 edge 的 bug，建议升级下浏览器

**Comment by xu8511831** [comment]
ie11上报错`调用对象无效`，子应用进行切换，id对应的句柄应该已经被销毁了
```js
   // interval.js
   intervals.forEach(function (id) {
      return global.clearInterval(id);
    });
```

**Comment by mapeng-gh** [comment]
在edge浏览器这个版本中，子应用调用`clearInterval(intervalId)`报“调用对象无效”异常

![image](https://user-images.githubusercontent.com/11573653/113111009-4d71e380-923a-11eb-9dc8-12431795d1ea.png)

经过测试，将`clearInterval(intervalId)`改成`window.clearInterval(intervalId)`没问题，但不知为何

**Comment by xinhailishi** [comment]
> 调用对象无效

因为，你这样改后，他成了死循环。一直调用window.clearInterval，一直是快照沙箱内部这个clearInterval函数了，就是window.clearInterval。

**Comment by xinhailishi** [comment]
> 在edge浏览器这个版本中，子应用调用`clearInterval(intervalId)`报“调用对象无效”异常
> 
> ![image](https://user-images.githubusercontent.com/11573653/113111348-ad688a00-923a-11eb-9db1-6e264db9fe1f.png)
> 
> 经过尝试，将`rawWindowClearInterval(intervalId)`改成`window.clearInterval(intervalId)`没问题，但不知为何

> 调用对象无效

因为，你这样改后，他成了死循环。一直调用window.clearInterval，一直是快照沙箱内部这个clearInterval函数了，就是window.clearInterval。 @mapeng-gh
