### ISSUE TITLE
[Bug]主应用在部署后无法加载资源，没有触发资源请求，没有报错，本地正常

### ISSUE THREAD

**Issue by GabrielchenCN** [umijs/qiankun#873]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

主应用是vue-cli3搭建，子应用也是vue-cli3搭建，主，子应用同时在本地，可以触发子应用html（资源）的加载，主在本地，子应用在服务器，可以触发子应用的html（资源）加载，主应用部署后，single-spa没有触发任何网络请求，状态一直在NOT_LOADED，NOT_MOUNTED和MOUNTED切换，但是没有成功加载资源，导致single-spa找不到 mount等方法，一直是空的，导致页面什么都没发生，也没有任何报错。。

## 最小可复现仓库

我的仓库本地都是好的，主仓库部署了才有问题。。

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by GabrielchenCN** [comment]
![image](https://user-images.githubusercontent.com/11185797/90467044-c9a13600-e145-11ea-903a-b82411684d40.png)

**Comment by GabrielchenCN** [comment]
这里的状态我看会跳到SKIP_BECAUSE_BROKEN,然后没有报错也没有加载资源

**Comment by gongshun** [comment]
看看子项目打包后的 `index.html` 内容

**Comment by GabrielchenCN** [comment]
远程的子项目通过本地的父项目是可以加载的

远程子项目 index.html，格式化后如下，难道就是没有引号的原因吗？

`
<!DOCTYPE html>
<html lang=en>
    <head>
        <meta charset=utf-8>
        <meta http-equiv=X-UA-Compatible content="IE=edge">
        <meta name=viewport content="width=device-width,initial-scale=1">
        <link rel="shortcut icon">
        <title>xxx管理平台</title>
        <link href=css/chunk-vendors.98a5c11f.css rel=preload as=style>
        <link href=css/index.381c459e.css rel=preload as=style>
        <link href=js/chunk-vendors.86fa3dee.js rel=preload as=script>
        <link href=js/index.6c444825.js rel=preload as=script>
        <link href=css/chunk-vendors.98a5c11f.css rel=stylesheet>
        <link href=css/index.381c459e.css rel=stylesheet>
    </head>
    <body>
        <div id=app></div>
        <script>
        </script>
        <script src=js/chunk-vendors.86fa3dee.js></script>
        <script src=js/index.6c444825.js></script>
    </body>
</html>

`

**Comment by gongshun** [comment]
> 远程子项目 index.html，格式化后如下，难道就是没有引号的原因吗？

引号 `bug` 早就修复了，父项目是如何部署的呢

**Comment by GabrielchenCN** [comment]
> > 远程子项目 index.html，格式化后如下，难道就是没有引号的原因吗？
> 
> 引号 `bug` 早就修复了，父项目是如何部署的呢

和子应用一致，通过vue-cli-service build 后，推送到目标服务器，父应用的其他功能在服务器上正常，只是不能自动加载qiankun的子应用

**Comment by gongshun** [comment]
> 子应用一致，通过vue-cli-service build 后，推送到目标服务器，父应用的其他功能在服务器上正常，只是不能自动加载qiankun的子应

控制台没有报错嘛，publicPath 有修改吧

**Comment by GabrielchenCN** [comment]
> > 子应用一致，通过vue-cli-service build 后，推送到目标服务器，父应用的其他功能在服务器上正常，只是不能自动加载qiankun的子应
> 
> 控制台没有报错嘛，publicPath 有修改吧

没有任何报错，debugger发现single-spa状态到了SKIP_BECAUSE_BROKEN，就直接结束了，因为qiankun引用的single-spa的mini包，没法断到正确的位置。。publicPath有修改，不修改我理解本地的父应用也加载不到远端的子应用吧

**Comment by gongshun** [comment]
> 没有任何报错，debugger发现single-spa状态到了SKIP_BECAUSE_BROKEN，就直接结束了，因为qiankun引用的single-spa的mini包，没法断到正确的位置。。publicPath有修改，不修改我理解本地的父应用也加载不到远端的子应用吧

有可能是路由没匹配上，导致子项目没激活

**Comment by GabrielchenCN** [comment]
> > 没有任何报错，debugger发现single-spa状态到了SKIP_BECAUSE_BROKEN，就直接结束了，因为qiankun引用的single-spa的mini包，没法断到正确的位置。。publicPath有修改，不修改我理解本地的父应用也加载不到远端的子应用吧
> 
> 有可能是路由没匹配上，导致子项目没激活

我能看到请求子应用的index.html方法已经在start()里面调用了，即代码在尝试加载（http://xxx.com/yy/zzz_web/dev_micro_web/）这个地址，但是没有发出network请求。。在network看不到东西，直接结束了也没有报错。。很奇怪，实在不行我只有跑一个本地的qiankun包，然后引用开发环境的single-spa在服务器上debugger一下了，不知道还有没有什么好的方法

**Comment by gongshun** [comment]
> 我能看到请求子应用的index.html方法已经在start()里面调用了，即代码在尝试加载`http://xxx.com/yy/zzz_web/dev_micro_web/`这个地址，但是没有发出network请求。。在network看不到东西，直接结束了也没有报错。。很奇怪，实在不行我只有跑一个本地的qiankun包，然后引用开发环境的single-spa在服务器上debugger一下了，不知道还有没有什么好的方法

\node_modules\import-html-entry\lib 对这里面的文件打个断点看看，这是加载文件的逻辑

**Comment by GabrielchenCN** [comment]
自己本地编译了single-spa的开发包，用qiankun引用发现是因为本地路径是localhost/#/myapp,然后服务器是 xxx.com/xxx/yyy/zzz/#/myapp, 然后路由中心的配置是/#/myapp，路由没有正确匹配引起的。
主应用增加了一个函数，帮助补充window.location.pathname前缀

**Comment by xiao-ma-g** [comment]
请问解决了吗，我也是遇到这个问题 ，vue3的项目 本地没问题 打包部署之后 第一次打开也没问题，第二次打开就没请求资源了  刷新就可以
