### ISSUE TITLE
最低支持IE几？

### ISSUE THREAD

**Issue by microCloudCode** [umijs/qiankun#874]
请问qiankun最低支持到IE几？

**Comment by Deturium** [comment]
官方支持到 IE 11，更低没有测试过

**Comment by xusong0621** [comment]
想问一下，会支持到IE 10吗，如果需要支持IE 10需要做什么样的配制

**Comment by wangkai1995** [comment]
目前线上环境最低 我们适配到了IE10

**Comment by EPDUED** [comment]
我配了@babel/preset-env和whatwg-fetch 还是在ie跑不起来，5555555555

**Comment by EPDUED** [comment]
> 目前线上环境最低,我们适配到了IE10

有具体配置么

**Comment by wangkai1995** [comment]
> > 目前线上环境最低,我们适配到了IE10
> 
> 有具体配置么

这个东西就很复杂了 。polyfill 其中promise影响就很大 corejs的独立polyfill 和babel-runtim的有冲突，而且不止这点。

**Comment by wangkai1995** [comment]
其中webpack的相关配置也进行了很多修改，有些配置和修改是根据项目来的

**Comment by EPDUED** [comment]
> 其中webpack的相关配置也进行了很多修改，有些配置和修改是根据项目来的

我先用个没有业务属性的纯乾坤试试吧

**Comment by Jay-Ivy** [comment]
> 我配了@babel/preset-env和whatwg-fetch 还是在ie跑不起来，5555555555

请问解决了吗,我配置了也一样,触发加载子应用时会提示对象不支持此方法 single-spa.min.js(32,2123)

**Comment by serveboy** [comment]
兼容ie11,ie10亲测不兼容.

**Comment by chenxing1991** [comment]
> 兼容ie11,ie10亲测不兼容.
ie11下报这个错  子应用路由无法加载是什么原因
![image](https://user-images.githubusercontent.com/18613090/108967738-d5ece980-76ba-11eb-9540-737eee6b7d9d.png)

**Comment by loioce** [comment]
> > 兼容ie11,ie10亲测不兼容.
> > ie11下报这个错  子应用路由无法加载是什么原因
> > ![image](https://user-images.githubusercontent.com/18613090/108967738-d5ece980-76ba-11eb-9540-737eee6b7d9d.png)

你好，请问你这个问题解决了么?我也遇到同样的问题了

**Comment by Ch2x** [comment]
> 其中webpack的相关配置也进行了很多修改，有些配置和修改是根据项目来的
兼容IE10需要改动到源码吗

**Comment by Ch2x** [comment]
> 其中webpack的相关配置也进行了很多修改，有些配置和修改是根据项目来的

兼容IE10需要改动到源码吗 @wangkai1995
