### ISSUE TITLE
可以打包的成果物 主应用和子应用 不跨域吗，主应用子应用都在一个域名下

### ISSUE THREAD

**Issue by zdc1111** [umijs/qiankun#876]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by Deturium** [comment]
可以

**Comment by zdc1111** [comment]
@Deturium  可以提供一下方法吗

**Comment by Deturium** [comment]
这个跟 qiankun 怎么用无关
你把两个应用都部署到同一台机器不就可以了

**Comment by zdc1111** [comment]
@Deturium   不是很理解   两个应用部署同一个机器不需要开两个端口号吗  这样不就跨域了

**Comment by zdc1111** [comment]
@Deturium   我还是不大理解    帮忙看一下哈   打包时候 主应用和子应用是变成同一个域名了 不过一刷新 主应用就被刷掉了

![image](https://user-images.githubusercontent.com/39116292/90639976-04988c00-e262-11ea-835d-16cec64b9bf5.png)

**Comment by gongshun** [comment]
> ![image](https://user-images.githubusercontent.com/39116292/90639976-04988c00-e262-11ea-835d-16cec64b9bf5.png)

`activeRule` 不要和子项目的真实路径一样，比如你的子项目真实路径是 `/react` ，你的 `activeRule` 和菜单 可以是 `/child/react`，或者你把所有子项目都部署在一个特殊目录下，这样子项目的真实访问路径就是 `/child/react`，而这时 `activeRule` 可以是 `/react`。

然后你的主子项目都是 `history` 路由，都需要配置 `try_files` 。

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/400

善用 issue 搜索

**Comment by zdc1111** [comment]
@Deturium  我看过那个帖子了  也是和我一样  进入子应用后刷新路由就变成子应用了   不能解决问题啊

**Comment by zdc1111** [comment]
能否官方出个解决文档呢。。。  帮助一下
