### ISSUE TITLE
[Bug]IE10 切换子应用时，报错：无法获取未定义或 null 引用的属性 "__IE_DEVTOOLBAR_CONSOLE_COMMAND_LINE"

### ISSUE THREAD

**Issue by dmccer** [umijs/qiankun#877]
## What happens?
IE10 切换子应用时，报错：无法获取未定义或 null 引用的属性 "__IE_DEVTOOLBAR_CONSOLE_COMMAND_LINE"

## 最小可复现仓库
无

## 复现步骤，错误日志以及相关配置
1. IE10 浏览器
2. 两个子应用，从其中一个切换到另一个
![2020-08-19 17-12-40 的屏幕截图](https://user-images.githubusercontent.com/1461254/90616770-6cd67600-e240-11ea-9b47-5fd32868ed04.png)

![2020-08-19 17-23-32 的屏幕截图](https://user-images.githubusercontent.com/1461254/90617474-4c5aeb80-e241-11ea-9d8b-1873a2a96b6f.png)

报错位置：this.windowSnapshot 为 undefined

## 相关环境信息

- **qiankun 版本**
2.0.21
- **浏览器版本**：
IE10
- **操作系统**：
Windows 7

**Comment by pangjian** [comment]
@dmccer 请问你是如何兼容ie10的, 我安装官方兼容ie的说明都做了,ie11可以,ie10死活不行, 也没有明显的报错.
