### ISSUE TITLE
[Feature Request] umi-plugin-qiankun 不支持 registerMicroApps 的 lifeCycles 参数 

### ISSUE THREAD

**Issue by howel52** [umijs/qiankun#88]
## Background
umi-plugin-qiankun 并没有处理 [qiankun registerMicroApps](https://github.com/umijs/qiankun#registermicroapps) 的第二个可选参数，只处理了 apps entry
https://github.com/umijs/umi-plugin-qiankun/blob/e1371660b59a1ae74efc277af67a6f307813e96e/src/master/runtimePlugin.ts#L39

因此采用 umi-plugin-qiankun 的父应用目前无法在 master 统一配置生命周期；

## Proposal
1. umi-plugin-qiankun/master 支持 lifeCycles 参数（但编译时的 lifecycle 似乎没有什么太大的意义）
2. 像 dva / qiankun runtime entry 那样，在 app.js 中 export lifecycle

**Comment by kuitos** [comment]
config 里可以加个 lifecycles 配置，跟 apps 同级的

pr is welcome😀

**Comment by howel52** [comment]
> config 里可以加个 lifecycles 配置，跟 apps 同级的

这里的 config 指的是静态编译时么

**Comment by dazjean** [comment]
文档得更新上啊
