### ISSUE TITLE
请教大家, 在应用切换时会有白屏, 有没有更优雅的显示方式? 演示地址: https://github.com/Witee/qiankun-test/tree/loading-problem

### ISSUE THREAD

**Issue by Witee** [umijs/qiankun#881]
我想加一个切换动画, 如 loading 之类的, 但不知道该加到什么地方.

注册时有个参数 `lifeCycles`  (registerMicroApps(apps, lifeCycles?)), 加到这里合适吗?

**Comment by gongshun** [comment]
https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles

![image](https://user-images.githubusercontent.com/29347231/90724956-f8f4a600-e2f1-11ea-8d20-939cb7ce4c61.png)

**Comment by Witee** [comment]
> https://qiankun.umijs.org/zh/api#registermicroappsapps-lifecycles
> 
> ![image](https://user-images.githubusercontent.com/29347231/90724956-f8f4a600-e2f1-11ea-8d20-939cb7ce4c61.png)

感谢回复, 我的代码如下:
```
const apps = [
  {
    ...
    loader: (loading) => {
      if (loading) {
        ReactDOM.render(<h1>Loading...</h1>, document.getElementById('subApp'));
      }
    },
  },
];

registerMicroApps(apps);
```
子应用都挂载在 `subApp` 上, 所以在 `loading` 为 `true` 时获取节点并渲染 `<h1>Loading...</h1>` 显示.

这样设置是正确的吗?

**Comment by Witee** [comment]
我这样写会在控制台报个错:

```
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.
```

不知道有没有更好的办法.

**Comment by gongshun** [comment]
> 我这样写会在控制台报个错:
> 
> ```
> Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.
> ```
> 
> 不知道有没有更好的办法.

一般是把 `loading` 赋给一个值，如果用的是 `vue`，可以赋给一个变量 `this.childLoading = loading`，然后使用 `v-loading = childLoading` 就可以了

**Comment by Witee** [comment]
> > 我这样写会在控制台报个错:
> > ```
> > Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.
> > ```
> > 
> > 
> > 不知道有没有更好的办法.
> 
> 一般是把 `loading` 赋给一个值，如果用的是 `vue`，可以赋给一个变量 `this.childLoading = loading`，然后使用 `v-loading = childLoading` 就可以了

我是 `react`, 有好的方式吗?

**Comment by gongshun** [comment]
> 我是 `react`, 有好的方式吗?

渲染 id 不要用子项目的容器 'subApp' ，就可以了

**Comment by Witee** [comment]
> > 我是 `react`, 有好的方式吗?
> 
> 渲染 id 不要用子项目的容器 'subApp' ，就可以了

不是很明白, 我建了一个测试的项目, 帮忙看看

[`https://github.com/Witee/qiankun-test`](https://github.com/Witee/qiankun-test)

演示过程如下:
1.  分别进入 `main` 和 `app1` 目录, 执行 `npm install` 和 `npm start`
2. 访问 `http://localhost:4000/`
3. 点击页面上的 `APP1` 切换路由时会在页面中间显示一个 `Loading...`

这样是通过配置 `loader` 实现的, 在为 `true` 时找到子应用的挂载点 `subApp` 渲染 `Loading...`,
但在控制台会有一个报错:
```
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.`
```

如果在 `lifeCycles` 的 `beforeLoad` 生命周期中做同样的操作也可以实现, 而且没有报错, 但感觉这样操作不是很正规.

帮忙看看应该使用什么样的方式显示 `Loading...` 呢?
