### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by zss1004504439** [umijs/qiankun#884]
## what？
`git clione ` 后 ` yarn examples:start ` 报错
![image](https://user-images.githubusercontent.com/24915880/90840301-37d73a00-e38c-11ea-8208-f550a1cadb07.png)

## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置

`git clione ` 后 ` yarn examples:start ` 报错

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
https://github.com/umijs/qiankun#-getting-started
