### ISSUE TITLE
在子应用的bootstrap阶段发生错误，会无法再加载其他的应用

### ISSUE THREAD

**Issue by zczhangchao51** [umijs/qiankun#886]
## What happens?

在子应用的bootstrap阶段发生错误，再也无法切换其他的子应用

![image](https://user-images.githubusercontent.com/14327786/90872395-26fbe800-e3cf-11ea-9dea-495b1911ee6a.png)

## Mini Showcase Repository(REQUIRED)

稍微改动官方的例子可复现

例如在react15的`index.js`文件里加入一段会导致错误的代码

```diff
import 'antd/dist/antd.min.css';
import './index.css';
+ console.log(a);
```

即可复现

## Context

- **qiankun Version**: 2.0.21
- **Platform Version**: mac 
- **Browser Version**: chrome 84

**Comment by gongshun** [comment]
可以捕获全局错误吧：addGlobalUncaughtErrorHandler
