### ISSUE TITLE
【百度浏览器】不兼容，原因如下，看看能不能优化这个方法？

### ISSUE THREAD

**Issue by deeWong** [umijs/qiankun#887]
先看源码，这里应该是执行entry js，然后查找entry js给window对象新注入的变量。这里我们着重看`getGlobalProp`这个方法最后拿到的值是什么？
![image](https://user-images.githubusercontent.com/30404809/90947322-81e11e00-e467-11ea-82d1-b7149ea90941.png)

chrome浏览器拿到的是正确的，lastProp = 'teacher-teacher'
![image](https://user-images.githubusercontent.com/30404809/90947360-c7055000-e467-11ea-935a-c2286de582b6.png)

这个是百度浏览器调试，内核也是谷歌，但是拿到的lastProp = 'openDatabase'，且lastProp === lastGlobalProp。
原因是百度浏览器window新增的key并不是在for(var key in window)的最后。。。略坑。
![image](https://user-images.githubusercontent.com/30404809/90947295-40e90980-e467-11ea-841f-d92993086417.png)
报错如下：
![image](https://user-images.githubusercontent.com/30404809/90947405-4561f200-e468-11ea-8132-65c6bde1fb19.png)

不知道后面国内使用谷歌内核做浏览器的厂商会不会也有这样的问题。。。。。
大佬们希望可以优化一下这个方法，比如说：
noteGlobalProps拿到所有的key，执行完entry js之后再拿一次所有的key，做一次对比，看多出来的是哪个key？

**Comment by gongshun** [comment]
有降级方案，你把 `webpack` 配置的这一项改一下就可以了： 
```
 library: `${name}-[name]`,
```
改成：
```
 library: `${name}`,
```

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
