### ISSUE TITLE
猎豹浏览器不兼容

### ISSUE THREAD

**Issue by cpa0701** [umijs/qiankun#890]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

猎豹浏览器无法兼容，会出现子应用没有到处lifeCircle的报错
![image](https://user-images.githubusercontent.com/24648209/90993284-d7900480-e5e6-11ea-8b06-60c84f5b5c1a.png)

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 复现步骤，错误日志以及相关配置
运行可供下载的样例，npm run example:star
在猎豹浏览器上运行，报错

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
https://github.com/umijs/qiankun/issues/770

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
