### ISSUE TITLE
Get load chunk error when switching applications, if the JS resources of asynchronous route are still being downloaded

### ISSUE THREAD

**Issue by luruozhou** [umijs/qiankun#892]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

use qiankun examples

## How To Reproduce

**Steps to reproduce the behavior
1. edit App.vue file in Vue example to help reproduce this case.
![image](https://user-images.githubusercontent.com/10755486/91007635-0c17b680-e60f-11ea-8074-cf02c08d70ea.png)

2. start examples & stay in Vue page.
3. click the about link
4. then we'll find 'Loading chunk 0 failed.' in console.
![image](https://user-images.githubusercontent.com/10755486/91008221-754bf980-e610-11ea-9198-0a8994cc290e.png)

5. The reason for this is that, Vue's sandbox is inactive after Vue app is unmounted， the code below do not work well as expected, then webpack will lead to an error.  So we should make sandbox work well even was inactive.
![image](https://user-images.githubusercontent.com/10755486/91008008-f48cfd80-e60f-11ea-9de2-5dab68e386b4.png)

![image](https://user-images.githubusercontent.com/10755486/91008119-3fa71080-e610-11ea-871e-063e7ee37797.png)

**Expected behavior** 1. 2.
there is no error in console.
## Context

- **qiankun Version**:  latest
- **Platform Version**: any
- **Browser Version**: any

**Comment by luruozhou** [comment]
Hope this problem can be resolved as soon, how is it going nnw?

**Comment by luruozhou** [comment]
Maybe return the right value from the getter of sandbox  is a better and easy way to ensure the webpackJsonP perform nomally

**Comment by jjzhangtt** [comment]
同样的问题+1...

**Comment by kuitos** [comment]
released v2.1.0
