### ISSUE TITLE
子应用为纯html   script  标签定义的方法无法调用

### ISSUE THREAD

**Issue by zdc1111** [umijs/qiankun#898]
## What happens?

子应用为纯html   script  标签定义的方法无法调用
a   href="javascript:void(0);" onclick="say()">say</a
<script type="text/javascript">
    function say() {
        alert(1111111);
    }
</script>

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
两个解法：
1. 关闭沙箱
2. 不用使用这种隐性的全局变量声明，统一换成手动 注册/调用 window
