### ISSUE TITLE
能否添加配置项，当路由跳转时才真正获取模块资源

### ISSUE THREAD

**Issue by rade1995** [umijs/qiankun#9]
感谢分享！感觉让微前端更简单的面向我们。
看了例子，注册app时就请求了所有的资源。如果模块注册过多时是否会造成一些资源浪费，我们的第一层路由就分出了很多模块，并且一个使用者可能只会应用到其中30%的模块，能否加个配置项当真正的选择到这个微应用时才开始请求它，消减去一些用户体验(我们是可以接受的，现在用的方式更加的糟糕)。

**Comment by kuitos** [comment]
不需要预加载的话可以通过配置关掉
```js
start({prefetch: false})
```
https://github.com/umijs/qiankun#start

**Comment by rade1995** [comment]
不好意思没有仔细看文档，恶补英语:）
