### ISSUE TITLE
挂载在window上的变量某些情况下切换应用无法隔离

### ISSUE THREAD

**Issue by xluos** [umijs/qiankun#90]
## What happens?
子应用挂载在window上的变量有时切换应用后无法隔离。
起因：我在迁移应用的过程中发现子应用的全局变量在子应用卸载后依然可以访问。于是尝试使用仓库中提供的Demo进行复现，发现只有在进行操作后才有这个情况

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
复现仓库地址：https://github.com/xluos/qk-test-demo

## How To Reproduce
**Steps to reproduce the behavior:**
1.初始状态切换两个应用 window上的变量状态隔离的
2.在react应用下点击弹窗后，再切换window上的变量不在卸载

**Expected behavior**
变量可以正常隔离
![GIF](https://user-images.githubusercontent.com/23625189/65423940-e1404380-de3c-11e9-9b06-52f3675fe316.gif)

**Comment by kuitos** [comment]
版本升到 1.1.12-0 试试

**Comment by xluos** [comment]
> 版本升到 1.1.12-0 试试

@kuitos 
升级版本无效
我看了一下代码应该是这两行的原因，如果一个变量被赋值多次，先删除，再恢复原来值 这样的顺序就会把这个变量再加到window上面去。调换一下顺序就没问题了

https://github.com/umijs/qiankun/blob/cb8d94199a5d63af22c58963fcc6793e8d1075d8/src/sandbox.ts#L171-L175

如果子应用重新渲染，或者再次给这个新增的变量赋值，这时`addedPropsMapInSandbox`里面因为在第一次执行时就已经添加进入了这个变量，就会把这个变量再次放进`modifiedPropsOriginalValueMapInSandbox`中 ，而执行unmount的时候，`modifiedPropsOriginalValueMapInSandbox.forEach((v, p) => setWindowProp(p, v));`这句会把已经删掉的变量加回去。
