### ISSUE TITLE
前后端不分离的项目 jsp或ftl模板那种    可以作为子应用吗 

### ISSUE THREAD

**Issue by zdc1111** [umijs/qiankun#901]
## What happens?
前后端不分离的项目 jsp那种    可以作为子应用吗 

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by Alfred-Skyblue** [comment]
同问

**Comment by zhenizhui** [comment]
我能想到的操作是，对于这种后端直出的页面，使用iframe

但是无可避免会有体验的问题。

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F
