### ISSUE TITLE
子应用在入口js调用Mock.mock(某个接口)，独立运行正常，集成时报错：子应用找不到生命周期方法application 'headbar' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in

### ISSUE THREAD

**Issue by uCloudCastle** [umijs/qiankun#902]
## What happens?

子应用在入口js调用Mock.mock(某个接口)，独立运行正常，集成时报错：子应用找不到生命周期方法application 'headbar' died in status LOADING_SOURCE_CODE: [qiankun] You need to export lifecycle functions in

## Mini Showcase Repository(REQUIRED)

https://codeup.aliyun.com/5f27667edb0493ecef90b643/aviana-front-frame.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

子应用在入口js调用Mock.mock()
主应用加载

**Expected behavior** 1. 2.

能正常加载并且子应用正常mock

## Context

- **qiankun Version**:   2.0.21
- **Platform Version**:   vue 2.6.11
- **Browser Version**:   chrome 84

**Comment by kuitos** [comment]
https://qiankun.umijs.org/zh/faq#application-died-in-status-loading_source_code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
