### ISSUE TITLE
 子应用没有热加载

### ISSUE THREAD

**Issue by humorHan** [umijs/qiankun#903]
预期：
1. 开发子应用不希望启动主应用
2. 菜单权限等是希望只有主应用实现一次，所以还是需要【带壳】开发，利用主子应用通信传递信息。
基于以上预期有个思路:
主应用部署发布环境(http://test.com?PORT=8081),根据query端口会设置子应用entry为localhost:8081达到上述预期效果
存在问题：
子应用无法热加载，给开发带来一定困扰，请问是否有解决方案

备注：强烈希望达到预期行为，可以做很多事情
1. 功能收敛到主应用，不比推进很多子应用做功能升级
2. 主子应用功能隔离更加清晰 不存在交集部分
3. 模块共享需要

qiankun 版本： 2.0.21
浏览器：  chrome 最新版
操作系统： mac

**Comment by humorHan** [comment]
@kuitos  如上

**Comment by humorHan** [comment]
已解决，原因是socket的地址还是url的地址，手动在devserver指定sockHost即可；另外基于安全考虑不允许获取本机资源，也可以在devserver指定allowedHosts

**Comment by reuwi** [comment]
@humorHan 样式也可以热更新？我这边调试了一下，发现源代码的热更新都是有问题的，qiankun会劫持掉css文件的加载，导致mini-css-extract-plugin 工作异常
