### ISSUE TITLE
【样式丢失】 react16 - 使用react-boilerplate脚手架 使用styled-components 

### ISSUE THREAD

**Issue by zlh90510** [umijs/qiankun#905]
如题 切换子应用后  样式出现丢失 styled-compoennts 的样式 标签没有加载

独立运行子应用 样式 加载如下
![image](https://user-images.githubusercontent.com/13471387/91681494-3292a000-eb81-11ea-86ce-557bf3f4c313.png)

通过框架切换 后样式加载如下
![image](https://user-images.githubusercontent.com/13471387/91681570-62da3e80-eb81-11ea-8345-d20038871b05.png)

**Comment by kuitos** [comment]
closed via inactive

**Comment by Rabbitzzc** [comment]
这个场景遇到过一次了，暂时不清楚解决方案，以及原因。都是内部代码没办法提供复现步骤呀

**Comment by LittlehorseXie** [comment]
请问作者后面解决了吗 
我在子应用独立运行且通过ModuleFederationPlugin使用父应用组件时 遇到了
