### ISSUE TITLE
关于qiankun依赖 import-html-entry存在的隐患

### ISSUE THREAD

**Issue by dengBox** [umijs/qiankun#906]
## Background

1.  项目架构如下 common系统作为平台入口项目，内部包含子系统A、B、C
2. 主项目发版后请求的资源由浏览器发起会在请求头包含  
![image](https://user-images.githubusercontent.com/29906246/91821662-43b6dc00-ec69-11ea-8e03-d763977ab0af.png)
3. 每次重新发版时，浏览器会和服务器进行资源校验，以保证不会有缓存失效的问题。
4.  但是子项目是由fetch发起请求，请求头部不会携带`If-None-Match If-Modified-Since`等重要信息字段导致资源失效。  
![image](https://user-images.githubusercontent.com/29906246/91821987-bb850680-ec69-11ea-9070-849ede7a3148.png)

## Proposal
1. 可以将fetch的头部加入header，因为不仅仅是html文件 还有css/js等
2. 可以补充一下说明文档，可能有些人不知道会有这个问题

## Additional context

作者有没有好的方案参考一下

**Comment by kuitos** [comment]
跟 import-html-entry 没关系，是你们的服务端没有设置正确的响应头

duplicated with https://github.com/umijs/qiankun/issues/730

**Comment by dengBox** [comment]
1. 我理解你说的这个方案不缓存html，我想表达的意思是 fetch是否会引起浏览器头部信息`If-None-Match If-Modified-Since`的缺失，导致服务器不能校验此文件的有效性。从而使用了浏览器缓存。
2. 因为我做过测试，不改动代码的前提下，重新发版子项目，独立访问该域名，每次都是可以拿到最新的资源。nginx也是可以看到访问日志，但是如果是手动fetch或者从主项目去加载子系统就不会生效，拿到的是旧的资源

**Comment by gongshun** [comment]
> 1. 我理解你说的这个方案不缓存html，我想表达的意思是 fetch是否会引起浏览器头部信息`If-None-Match If-Modified-Since`的缺失，导致服务器不能校验此文件的有效性。从而使用了浏览器缓存。
> 2. 因为我做过测试，不改动代码的前提下，重新发版子项目，独立访问该域名，每次都是可以拿到最新的资源。nginx也是可以看到访问日志，但是如果是手动fetch或者从主项目去加载子系统就不会生效，拿到的是旧的资源

你没有配置 `Cache-Control no-cache` 导致触发了强缓存，所以请求不会携带 `If-None-Match` 。你配了这个就会携带了

![image](https://user-images.githubusercontent.com/29347231/91942514-a96c9c00-ed2d-11ea-9272-aa1a6884dbf9.png)

**Comment by dengBox** [comment]
好的，谢谢。

**Comment by kuitos** [comment]
独立开 tab、cmd + R、不开 tab 贴地址等不同方式访问，浏览器的行为都是不一样的。
目测是你们的 nginx 的 cache-control maxage 设置的有问题，disable cache 情况下看下响应头。

这个 issue 先关了。

**Comment by Feahter** [comment]
fetch方式请求文件，cache默认default,响应头出现Etag或者Last-Modified会让fetch的缓存策略变成no-store.
![image](https://user-images.githubusercontent.com/13764431/122858252-91ade500-d34c-11eb-82c7-238ec33305d2.png)

**Comment by wudith** [comment]
> fetch方式请求文件，cache默认default,响应头出现Etag或者Last-Modified会让fetch的缓存策略变成no-store. ![image](https://user-images.githubusercontent.com/13764431/122858252-91ade500-d34c-11eb-82c7-238ec33305d2.png)

大佬，我在nginx配置去掉了Etag或者Last-Modified，在chrome还是没有缓存，不知是什么原因

![image](https://user-images.githubusercontent.com/30773885/196601271-f5a3f8b4-4914-4f65-928b-76282f1d69e0.png)
