### ISSUE TITLE
[Feature Request] 主应用和子应用部署在不同的端口，导致dev-server和mock报404

### ISSUE THREAD

**Issue by KellenHe** [umijs/qiankun#907]
## Background

比如主应用部署在4200，子应用部署在8000。这时子应用的dev-server会请求到主应用的4200端口，mock数据也会404。

## Proposal

请问这种有什么办法解决吗

**Comment by ayiaq1** [comment]
set public path

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/315
