### ISSUE TITLE
[Bug]子应用的web worker不能被正确加载和使用

### ISSUE THREAD

**Issue by GabrielchenCN** [umijs/qiankun#908]
## What happens?

子应用中使用web worker, 并使用worker-loader打包报错，单独使用可以。

子应用worker-loader必须设置为 inline ，才能正确加载，否则由于跨域限制，加载不了worker

## 复现步骤，错误日志以及相关配置

子应用单独使用

![image](https://user-images.githubusercontent.com/11185797/92117664-0e0c2180-ee28-11ea-8334-144d9fa98155.png)

放入主应用中
![image](https://user-images.githubusercontent.com/11185797/92118561-38121380-ee29-11ea-8f97-725bc2a1eafc.png)

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
https://github.com/webpack-contrib/worker-loader/issues/154

**Comment by GabrielchenCN** [comment]
不是CORS的问题，web worker是不能跨域加载的，这里要么自己内联worker要么需要实现一个worker加载器，也就是下载worker代码再用blob的方式内联
