### ISSUE TITLE
[RFC] qiankun 提供内置的 context 变量

### ISSUE THREAD

**Issue by kuitos** [umijs/qiankun#91]
## 背景

子应用需要知道当前是否运行在 qiankun 模式当中

## 思路

qiankun 在 start 后往 window 上挂载一个变量，比如 `window.__POWERED_BY_QIANKUN__`

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by howel52** [comment]
https://github.com/umijs/qiankun/blob/7916ded4a49451b16ee8a94d87525e4f3e6e2ef9/src/index.ts#L151  这个 key 最好能有业务自定义的能力，默认可以为 __POWERED_BY_QIANKUN__

**Comment by kuitos** [comment]
操作失误直接 push master 了。。 我搞个 pr 。。

**Comment by kuitos** [comment]
> 这个 key 最好能有业务自定义的能力

什么场景？

**Comment by howel52** [comment]
> 什么场景？

在乾坤没有提供这个 context 能力之前，可以通过在 master 注入一个类似与 example 中的 isMain 来支持 env 的判断， 乾坤提供内置能力后，自定义 key 可以无缝切换。

**Comment by kuitos** [comment]
这个主意是给调用方自己消费的，相对于 qiankun 提供了默认的一个标识吧，之前自己搞了一个就用之前那个好了。

**Comment by howel52** [comment]
> 这个主意是给调用方自己消费的，相对于 qiankun 提供了默认的一个标识吧，之前自己搞了一个就用之前那个好了。

有道理

**Comment by howel52** [comment]
close https://github.com/umijs/qiankun/pull/95
