### ISSUE TITLE
乾坤是否支持微应用里面嵌套微应用

### ISSUE THREAD

**Issue by hzfvictory** [umijs/qiankun#910]
## What happens?

乾坤是否支持微应用里面嵌套微应用

## 相关环境信息

- **qiankun 版本**  2.0.24
- **浏览器版本**：  84.0.4147.135
- **操作系统**： mac

**Comment by kuitos** [comment]
支持

**Comment by hzfvictory** [comment]
> 支持

里面的一些全局变量不会冲突吗
