### ISSUE TITLE
qiankun中import-html-entry对于html页面url的处理

### ISSUE THREAD

**Issue by gds-prue** [umijs/qiankun#915]
## What happens?
function getEntirePath(path, baseURI) {
	return new URL(path, baseURI).toString();
}
getEntirePath(matchedScriptSrc, baseURI);

其中baseURI 可能不只是一个域名，比如为 http://location:5000/good

期望的到 http://location:5000/good/matchedScriptSrc。
实际得到 http://location:5000/matchedScriptSrc。

## 相关环境信息

-  import-html-entry 1.9.1。

**Comment by gongshun** [comment]
`entry` 最后面加一个 `/`，正确是 `http://location:5000/good/` 而不是 `http://location:5000/good`

**Comment by gds-prue** [comment]
@gongshun 可能我没有描述清楚，设置 entry: 'http://location:5000/good/index.html'。 然后在import-html-entry中的assetPublicPath会被设置为 http://location:5000/good/。在html中，如果一个资源路径为相对路径resourcesPath='/static/css.js'，则会调用 getEntirePath(resourcesPath,assetPublicPath)方法重新处理路径。得到的是http://location:5000/static/css.js，而不是我期望的 http://location:5000/good/static/css.js

**Comment by gongshun** [comment]
![image](https://user-images.githubusercontent.com/29347231/92474737-eb568000-f20e-11ea-8ff9-94bd5c93778d.png)

你的子项目单独访问可以吗，部署到二级目录也是要配置 `publicPath` 的：https://cli.vuejs.org/zh/config/#publicpath，如果你配置了，一般来说打包之后，你的js的路径应该是`/good/static/css.js`，而不是`/static/css.js`

**Comment by gds-prue** [comment]
@gongshun 理想状态是B项目（子应用）可以单独访问，然后需要被集成到A项目（主应用）。
此时用的一套build代码,全是相对路径/static/css.js，
B项目单独存在的时候是没有问题的，作为在A中需要额外路由/good/。 然后就找不到文件了。
已经设置了 __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__。
对于css和js。来说是没有问题的。
但是html,中的url路径会有问题

**Comment by gongshun** [comment]
> s和js。来说是没有问题的。
> 但是html,中的url路径会有

你的子应用单独访问地址是 `http://location:5000/` 吗？额外路由和 entry 无关

**Comment by gds-prue** [comment]
@gongshun 
目前B项目域名http://projecta.com(假设) 单独访问没有问题。然后ng,指向具体的资源目录

目前A项目域名http://projectb.com(假设)  entry:'/good/index.html'  然后ng, /good/ 指向具体的资源目录。
       这样对于html中就会访问 http://projectb.com/staic/css.js  而不是我想要的http://projectb.com/good/staic/css.js。 重而找到 
   不到资源。

你说的是想我设置 entry:'http://projecta.com/index.html' 而不是 entry:'/good/index.html' ？

**Comment by gds-prue** [comment]
我的理解qiankun的设计理念是好的，能根据entry做动态。但是html中的url处理还是有点难以理解

**Comment by gongshun** [comment]
这是你的部署问题，https://github.com/umijs/qiankun/issues/400#issuecomment-676947927

**Comment by gds-prue** [comment]
我的相关的使用是react, 使用的webpack和 html-webpack-plugin。 我不想去固定死publicpath。不然二级目录变化得重新编译。
而是想动态注入，qiankun 提供的INJECTED_PUBLIC_PATH_BY_QIANKUN 与 __webpack_public_path__ 配合提供了这样的能力。
但是对与由html-webpack-plugin生成的html,没有声明publicpath，会导致其中的url缺失二级目录

**Comment by gongshun** [comment]
抛开 qiankun 不谈，你动态修改 publicpath ，然后把子项目部署在二级目录，看看能否正确加载。尝试两次，__webpack_public_path__ 分别为 /good/ 和 http://location:5000/good/

**Comment by gds-prue** [comment]
[
![image](https://user-images.githubusercontent.com/35244704/92548797-817bbc00-f28a-11ea-903e-7cf01e62fe2c.png)
](url)
[
![image](https://user-images.githubusercontent.com/35244704/92548881-af610080-f28a-11ea-8c24-89b47fabb75c.png)
](url)
[
![image](https://user-images.githubusercontent.com/35244704/92548979-de777200-f28a-11ea-9794-28ffbfe1bff7.png)
](url)
![image](https://user-images.githubusercontent.com/35244704/92548993-e800da00-f28a-11ea-9f43-99a9b0a5b558.png)

**Comment by gongshun** [comment]
如果你不用 qiankun，仅仅是动态修改 webpack_public_path ，如果为 http://location:5000/good/ ，资源也是不能正确加载的

**Comment by kuitos** [comment]
1. webpack 的 `__webpack_public_path__ ` 配置是用来给动态加载的资源做路径补全的，不适用于那些直接在 html 中静态引入的 js/css/img 等，这些资源要想变更路径前缀需要配置 webpack publicPath，这个可以翻下 webpack 文档或者自己做下测试验证
2. 你的 html 里静态引入的 `/static/css.js` 是绝对路径的资源，这种写法无论是 `http://localhost:5000` 还是 `http://localhost:5000/good/` 上下文中访问，计算出来的地址都会是 `http://localhost:5000/static/css.js`，原因上面 @gongshun 的截图里说明了，你可以自己随便搞个 html 测试一下
3. assetPublicPath 或许应该叫 assetContext 或者 assetRuntimePublicPath，现在这个命名确实容易让人误解其等价于 webpack 的 publicPath 配置

**Comment by gds-prue** [comment]
如果抛开qiankun,和 import-html-entry不说，html,本身是静态的，不会有动态能力，必须借助webpack的publicPath做修改。或者使用ssr等，使html具有动态能力。
但是在使用了qiankun之后，我看了 import-html-entry对html做了一些更好的处理。我觉得是不是可以通过import-html-entry对静态html提供一些额外的能力。比如动态的url。
或者对getTemplate增强，增加一个而外的参数assetPublicPath，交给开发者自己做动态

**Comment by kuitos** [comment]
你无法处理所有的资源依赖的场景，比如 html 里静态引入的 img、css 里引入的图片、字体等，这块应该是由打包工具去做替换更合理，除非你在运行时把所有的静态资源加载都拦截，然后做 url 匹配和替换😂 
qiankun 目前只关注了自己关心的 css/js，因为这部分他是需要手动处理的。完全动态的场景自定义的 getTemplate 也不能完全 cover，比如上面提到的 css 中引入了图片的场景。

最好的做法是所有的静态资源都发 cdn，不要从自己的服务器拿了。。 除了省钱没有什么其他优点🤪

**Comment by gds-prue** [comment]
我觉得只需要处理html本身自带的url就好了，至于其他的，我觉得是打包工具处理的。还有其他场景么，我倒是没有遇到过。🤪
