### ISSUE TITLE
第一个子应用一直处于fetch中，然后点击其他子应用，其他子应用不加载，需等到第一个fetch返回才会加载

### ISSUE THREAD

**Issue by qiangf811** [umijs/qiankun#916]
## What happens?

我采用的是Vue+router来加载子应用，
页面初始化进入第一个路由加载子应用，第一个子应用fetch还没结束前，点击其他路由，其关联的子应用不会加载，也没触发生命钩子。

## Context

- **qiankun Version**: 2.0.21
- **Platform Version**:MacOS
- **Browser Version**: Chrome 87.0.4256.0

**Comment by qiangf811** [comment]
复现的逻辑是，给一个子应用的entry配上无效的或者需要fetch很长的url，就会发生这种情况，比如给的entry是http://123.1.1.1。
具体的demo见https://github.com/qiangf811/simple-micro-apps。
我觉得这是一个问题~

**Comment by kuitos** [comment]
`singular: true` 的模式下会出现这种情况，后一个应用必须等待前一个应用 settled，符合预期
