### ISSUE TITLE
主应用和微应用是由同一个框架编写，无法加载

### ISSUE THREAD

**Issue by wushunqing** [umijs/qiankun#917]
主应用和微应用都是Vue编写，分别是两个不同端口的服务。当主应用使用loadMicroApp 去加载时，报Unexpected token '<'，  感觉是重名的js所致。请问有什么办法解决。
![image](https://user-images.githubusercontent.com/20431475/92579068-4ba4fa80-f2bf-11ea-9b51-7479f8a228be.png)

**Comment by gongshun** [comment]
这种错误是因为请求的是 `js/css` 文件，但是返回了 `html` 文件导致的。同一技术栈没问题的：https://github.com/gongshun/qiankun-vue-demo

**Comment by ikecoolon** [comment]
子应用main.js引入 public-path.js  

//public-path.js
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
}
