### ISSUE TITLE
子项目中业务需要引入第三方js（例如高德地图、阿里云oss）跨域报错

### ISSUE THREAD

**Issue by wangwenjie1314** [umijs/qiankun#92]
子项目中业务需要引入第三方js（例如高德地图、阿里云oss）跨域报错，这种怎么破
![WX20190926-100440](https://user-images.githubusercontent.com/4018406/65652672-1b7c3180-e045-11e9-8764-1e5f5082091e.png)
<img width="732" alt="WX20190926-100451@2x" src="https://user-images.githubusercontent.com/4018406/65652678-220aa900-e045-11e9-9b6d-1d11aec7bb80.png">
<img width="767" alt="WX20190926-100226@2x" src="https://user-images.githubusercontent.com/4018406/65652683-2931b700-e045-11e9-8a50-121a6e0cd271.png">

复现地址url：
http://onetomany.lovexiaoxuan.cn

**Comment by kuitos** [comment]
拖到本地然后直接 import 吧

**Comment by succulen-plants** [comment]
完全不支持跨域吗， 子项目全在不同的服务器

**Comment by kuitos** [comment]
就是需要你的子应用支持跨域访问啊

**Comment by htcqp802** [comment]
我也遇到了同样的问题 怎么解决啊。还是不太懂，同样是跨域的资源，为什么子应用能访问，主应用为什么访问不了呢？为什么主应用无法访问子应用依赖的第三方资源，而可以访问子应用自己的js呢？不同样是跨域吗

**Comment by JqiangLiu** [comment]
老哥解决了么,同样自业务需要引入百度地图

**Comment by kuitos** [comment]
三方 js 如果不能开启其跨域配置的话，把 js 拉到本地跟自己的代码一起部署就行了，或者传到其他支出跨域的 cdn 上
