### ISSUE TITLE
[Feature Request] 既然已经支持父工程静态文件加载隔离处理，能否再增加父工程window下全局变量隔离处理，不要造成误删除。

### ISSUE THREAD

**Issue by waltbest2** [umijs/qiankun#926]
## Background
最新乾坤版本支持配置主工程静态文件url规则，让主工程文件挂到父dom里。
能否再增加window下全局变量的白名单，这样如果切换子应用同时，父工程有有window下全局变量变化，不会导致被误删除。

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by kuitos** [comment]
开了沙箱时，主应用的 window 变更不会受影响。

如果你碰到了不符合预期的行为，开一个 issue 并提供可复现仓库吧

**Comment by waltbest2** [comment]
> 开了沙箱时，主应用的 window 变更不会受影响。
> 
> 如果你碰到了不符合预期的行为，开一个 issue 并提供可复现仓库吧

IE 11下的快照沙箱也是不受影响的吗？

**Comment by kuitos** [comment]
快照沙箱不支持这种级别的隔离

**Comment by kuitos** [comment]
你可以在 beforeUnmount 钩子里记录一下相应的值，然后 afterUnmount 里手动恢复

**Comment by waltbest2** [comment]
> afterUnmount

beforeUnmount 到 afterUnmount  之间如果有增加怎么办？

**Comment by kuitos** [comment]
这中间就只有 unmount 了，unmount 是你自己实现的
