### ISSUE TITLE
主应用是hash,子应用既有history，又有hash,如何切换路由

### ISSUE THREAD

**Issue by hjx5309** [umijs/qiankun#927]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?
主应用是hash,子应用既有history，又有hash,如何切换路由

## 最小可复现仓库

为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

## 相关环境信息

- **qiankun 版本**:
- **浏览器版本**：谷歌
- **操作系统**：

**Comment by gongshun** [comment]
`history.pushState()` 
https://developer.mozilla.org/zh-CN/docs/Web/API/History/pushState
https://github.com/umijs/qiankun/blob/bf6f0df2ddbe6ab3a3b3f38a8214a0af9f56a7f7/examples/main/index.html#L30
