### ISSUE TITLE
公司特殊，子应用不允许跨域的情况下，配置了nginx在主应用下，要怎么处理子应用刷新基座没有的问题？？？

### ISSUE THREAD

**Issue by tianliangOrmoon** [umijs/qiankun#928]
## What happens?
公司项目特殊，子应用不允许跨域。所以只能nginx来反向代理！
父应用：9400
子应用：9250
目前方案是：
9400 nginx服务下 配置对应9250的location 
 /child {.....}
/tochild{....}
父应用的注册该子应用的配置是 
{
 entry:'....:9400'/tochild,
 activepath:'/child'
}
只有这样才可以使子应用刷新时 基座不会没掉！或者404问题！
但是我们可以从9400/tochild访问子应用！感觉不是太好有什么好的方案吗？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:v2.0.24
- **Platform Version**:
- **Browser Version**:

**Comment by gongshun** [comment]
`activeRule` 和 `entry` 的路径不同就不会刷新变成子项目了。不想子项目被独立访问，可以根据请求的来源判断下，子项目是用`fetch` 请求的，可以带参数和 `cookie`

**Comment by tianliangOrmoon** [comment]
主要是这样的代价导致9400/tochild也能访问子应用

**Comment by leason-wan** [comment]
> 主要是这样的代价导致9400/tochild也能访问子应用

@gongshun 说的方案可以解决，加参数或者cookie判断请求是否来自主应用。

**Comment by qiansr** [comment]
> ## What happens?
> 公司项目特殊，子应用不允许跨域。所以只能nginx来反向代理！
> 父应用：9400
> 子应用：9250
> 目前方案是：
> 9400 nginx服务下 配置对应9250的location
> /child {.....}
> /tochild{....}
> 父应用的注册该子应用的配置是
> {
> entry:'....:9400'/tochild,
> activepath:'/child'
> }
> 只有这样才可以使子应用刷新时 基座不会没掉！或者404问题！
> 但是我们可以从9400/tochild访问子应用！感觉不是太好有什么好的方案吗？
> 
> A clear and concise description of what the bug is.
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue.
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **qiankun Version**:v2.0.24
> * **Platform Version**:
> * **Browser Version**:

遇到同样需求，能放一下这里完整的配置吗？
9400 nginx服务下 配置对应9250的location
/child {.....}
/tochild{....}
父应用的注册该子应用的配置是
{
entry:'....:9400'/tochild,
activepath:'/child'
}
