### ISSUE TITLE
Is qiankun also based on SystemJS?

### ISSUE THREAD

**Issue by mkampmey** [umijs/qiankun#929]
Hello!
I saw that qiankun is based on single-spa and so I was wondering if qiankun is also using SystemJS to load different SPAs. The cool thing about single-spa is that you can change the route to your SPA during runtime without deploying anything just by modifying the import map, which is then used by SystemJS. So is qiankun also using SystemJS?

**Comment by gongshun** [comment]
No, qiankun is using [import-html-entry](https://github.com/kuitos/import-html-entry) to load apps
