### ISSUE TITLE
看源码 single-spa中的registerApplication没有实现。  在切换应用的时候调用了pushstate，但是每个app中的unmount是怎么触发执行的

### ISSUE THREAD

**Issue by kaihekaihe** [umijs/qiankun#93]
看源码 single-spa中的registerApplication没有实现。

在切换应用的时候调用了pushstate，但是每个app中的unmount是怎么触发执行的

**Comment by kuitos** [comment]
https://github.com/umijs/qiankun/blob/master/src/index.ts#L84

**Comment by kuitos** [comment]
unmount 的逻辑 https://github.com/CanopyTax/single-spa/blob/master/src/navigation/reroute.js#L61
