### ISSUE TITLE
vue+qiankun做为主应用，主应用配置路由之后，加载的子应用，子应用路由切换页面加载不出来

### ISSUE THREAD

**Issue by litianyangz** [umijs/qiankun#930]
## 背景

> 代码仓库地址 https://github.com/litianyangz/vue-qiankun.git

## 思路
主路由配置如下
### const routes = [
    {
        path: '/',
        name: 'home',
        icon: 'el-icon-s-home',
        redirect: '/home',
        leaf: true,
        component: () => import('@/components/MainMenu.vue'),
        children: [
            {
                path: '/home',
                name: '首页',
                component: () => import('@/views/main/Main.vue'),
                meta: {
                    isQiankun: true
                }
            }
        ]
    },
    {
        path: '/',
        name: 'about',
        icon: 'el-icon-s-data',
        leaf: true,
        component: () => import('@/views/Home.vue'),
        children: [
            {
                path: '/about',
                name: '关于',
                component: () => import('@/views/mine/Mine.vue'),
                meta: {
                    isQiankun: true
                }
            }
        ]
    },
    {
        path: '/',
        name: '微应用',
        icon: 'el-icon-s-data',
        component: () => import('@/views/Home.vue'),
        leaf: true,
        children: [
            {
                path: '/qiankunchild',
                name: '微应用-vue',
                meta: {
                    isQiankun: false
                }
            }
        ]
    },
]
子主路由配置如下
### const routes = [
    {
        path: '/',
        name: 'Home',
        component: Home
    },
    {
       path: '/about',
       name: 'About',
       component: () => import(/* webpackChunkName: "about" */ '../views/About.vue')
    }
]

**Comment by gongshun** [comment]
应该是你的主项目路由冲突了，你可以看看这个demo：https://github.com/gongshun/qiankun-vue-demo

**Comment by litianyangz** [comment]
@gongshun 这个demo我看过了，太过于简单，以至于我没法看出我的问题出在哪里
子应用的路由还会与主应用有冲突吗，我把主应用的路由与子应用路由名字有冲突的修改后也不行，我上传了代码仓库，希望能下载帮忙看下问题，谢谢，这个问题困扰我一周了。

**Comment by gongshun** [comment]
你的路由代码里面，写了三个 `path: '/'` ，每一个都有一个子路由，分别是`/home`，`/about`，`/qiankunchild`。他们本可以写到一起。
目前问题有三个：
1.  不要把路由和菜单混在一起
2. 子项目的 path 不需要注册路由 （`/qiankunchild` 这个不需要）
3. 既然你的 `Home` 组件每个页面都会加载，你为什么不把他写到 `app.vue` 里面？

造成你这个现象的根本原因是第三个，`path: '/'` 只有三个子路由，当你跳转到子项目的 `about` 页面时，路由为 `/qiankunchild/about`，不匹配`path: '/'` 的任一个子路由，所以`path: '/'` 未激活，`MainMenu` 组件未加载。表现只加载了`app.vue`的内容，就是内容为空

**Comment by litianyangz** [comment]
@gongshun 好的 我试着修改下，谢谢了
