### ISSUE TITLE
低版本chrome加载应用报错

### ISSUE THREAD

**Issue by bingo618** [umijs/qiankun#931]
低版本chrome浏览器加载子应用`Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.`，关闭沙箱配置正常，如何解决？

## 相关环境信息

- **qiankun 版本**
    qiankun: "^2.0.16",
- **浏览器版本**：
- **操作系统**：

**Comment by kuitos** [comment]
版本升级到最新

**Comment by zhilianbi520** [comment]
> 低版本chrome浏览器加载子应用`Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.`，关闭沙箱配置正常，如何解决？
> 
> ## 相关环境信息
> * **qiankun 版本**
>   qiankun: "^2.0.16",
> * **浏览器版本**：
> * **操作系统**：
@bingo618 想问，版本是有多低？
