### ISSUE TITLE
[Bug]isConstructable 函数建议去掉toString后的首字母大写匹配

### ISSUE THREAD

**Issue by stoneChen** [umijs/qiankun#932]
## What happens?

![image](https://user-images.githubusercontent.com/4470552/93186459-3d4c5800-f771-11ea-89f4-ce5f65fe0a99.png)

本地开发时(准确讲，是代码未被uglify时)，我们自己写构造函数的确是首字母大写（或者直接用ES6 class），但是当代码被uglify后，这个function名将会被改写，可能是一个小写字母，且由于某种原因前几个条件没有满足，导致『本地开发正常，而打包后在集成环境出错』的问题。

## 最小可复现仓库
成本太高了哇

## 复现步骤，错误日志以及相关配置
无

## 相关环境信息

- **qiankun 版本**: 2.0.24
- **浏览器版本**： 85.0.4183.83（正式版本）
- **操作系统**：Mac OS X 10.15 or windows

**Comment by kuitos** [comment]
给个前几个条件也没匹配到的例子

**Comment by stoneChen** [comment]
> 给个前几个条件也没匹配到的例子

集成某个历史子系统时，该子系统改写了Date类(将Date指向了自定义函数，此操作的合理性暂不讨论)，且此新函数没有设置`fn.prototype.constructor = fn`, 但是函数名确实是大写的，在本地开发环境(代码没有压缩)，这个新函数名仍然是大写的，所以本地没有暴露问题。

集成部署后，代码被压缩，函数名变成小写了，导致集成后报错。

PS: 把`fn.prototype.constructor = fn`这句加上确实OK了。

只是不理解判断首字母大写这个条件的必要性在哪。

**Comment by kuitos** [comment]
> 不太理解判断首字母大写这个条件的必要性在哪

大写判断是 || 不是 &&，所以这并不是一个必要条件

你这个场景主要问题还是在于没有满足 prototype 的判断条件

是否可构造函数目前还没有一个完美的检查手段，如果有更优的解决方案欢迎提 pr 来改善 https://github.com/umijs/qiankun/blob/master/src/sandbox/common.ts#L20

**Comment by 961998264** [comment]
同样碰到这个问题，本地没有问题，线上环境，本来isConstructable是true，结果变成false了。

**Comment by 961998264** [comment]
> > 不太理解判断首字母大写这个条件的必要性在哪
> 
> 大写判断是 || 不是 &&，所以这并不是一个必要条件
> 
> 你这个场景主要问题还是在于没有满足 prototype 的判断条件
> 
> 是否可构造函数目前还没有一个完美的检查手段，如果有更优的解决方案欢迎提 pr 来改善 https://github.com/umijs/qiankun/blob/master/src/sandbox/common.ts#L20

你这话不对吧。class函数在经过babel处理后，变成function,自然无法通过classRegex.test(fnString)的判断，那么又因为被处理成小写开头的名字，也无法通过constructableFunctionRegex.test(fnString)。

**Comment by 961998264** [comment]
![image](https://user-images.githubusercontent.com/38360133/230552535-da655b46-fe0c-4394-b8d8-7ee53e02d68b.png)这个是本地开发环境toString的结果，自然符合大写字母开头;
![image](https://user-images.githubusercontent.com/38360133/230553773-f17519d3-aad6-4297-ac3e-e24a1ca700aa.png)
这个是压缩之后的toString()结果。

**Comment by 961998264** [comment]
解决方案：
![image](https://user-images.githubusercontent.com/38360133/230560194-2dcbf851-25f9-4d00-a7b4-95a40815cc2d.png)
