### ISSUE TITLE
umi-qiankun 微应用调用接口后，切换路由后报错

### ISSUE THREAD

**Issue by coder-liulin** [umijs/qiankun#936]
## What happens?

umi-qiankun 微应用调用接口后，切换路由后告警错误

This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

https://gitee.com/persLiu/micro-qiankun.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:  ^2.11.0
- **Platform Version**: Mac 
- **Browser Version**: Chrome 85.0.4183.102

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/97269104-ee153f00-1867-11eb-8180-ad259928f61b.png)

**Comment by kuitos** [comment]
提供 github 仓库后可自己 reopen
