### ISSUE TITLE
如何将存静态页面改造为可以介入qiankun的页面

### ISSUE THREAD

**Issue by jingsam** [umijs/qiankun#938]
如何将存静态页面快速地改造为qiankun页面，暂时考虑到以下几点：
1、mount中的render函数怎么写？
2、所有引用的资源都要以绝对路径引用，改造工作量挺大，是否可以增加一个rootPath的选项，让相对路径针对于rootPath去解析。
3、跨域不用说了，要全部改造为可跨域，登录所涉及的cookie可能不符合安全规范；
4、如果要传递状态，子引用是否要引入qiankun？

**Comment by gongshun** [comment]
1. 官方有例子: https://github.com/umijs/qiankun/tree/master/examples/purehtml
2.  `window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__` 就是你说的 `rootPath`，参考这个解决路径问题：[jQuery 老项目的资源加载问题](https://juejin.im/post/6844904185910018062#heading-22)
4. 传递状态，子项目不需要引入 `qiankun`，子项目生命周期函数的参数，就能拿到这个值
