### ISSUE TITLE
基于 single-spa 搭的微前端主应用，子应用是 umi 及 umi qiankun 插件，但子应用连接不上

### ISSUE THREAD

**Issue by ruizhengyun** [umijs/qiankun#939]
## What happens?

基于 single-spa 搭的微前端主应用，子应用是 umi 及 umi qiankun 插件，但子应用连接不上

<img width="1161" alt="micro-frontend" src="https://user-images.githubusercontent.com/6204303/90305264-6d46d800-def3-11ea-80b1-aa966d9280d5.png">

<img width="1129" alt="micro-frontend-react" src="https://user-images.githubusercontent.com/6204303/90305275-910a1e00-def3-11ea-8b17-8118b7ce343d.png">

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

- 主应用是基于 single-spa 开发的微前端 8000 端口
- 子应用是 umi 搭建的，也装了 `@umijs/plugin-qiankun`
- 子应用服务启动没问题，主应用出现 `Disconnected from the devServer, trying to reconnect...` 问题

## 相关环境信息

- **Umi 版本**：3.2.14
- **Node 版本**：12.10.0
- **操作系统**：mac

**Comment by gongshun** [comment]
解决办法：子应用搞个环境变量，指定热更新的端口就可以了，参考https://github.com/umijs/umi-plugin-qiankun/blob/master/examples/app3/.env

**Comment by HeeBooo** [comment]
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/23186355/165722189-0656ba30-3c19-46c3-8e7a-9251d650998f.png">
这里base配制和你主应用注册时候的name一致就好了
