### ISSUE TITLE
配置文件中的publicPath在css的url()中不生效

### ISSUE THREAD

**Issue by drafish** [umijs/qiankun#940]
## What happens?
配置文件中加了`publicPath: '/sub/app/'`，但是打包出来的css文件中，url()里面还是相对路径，没有将publicPath加进去

![image](https://user-images.githubusercontent.com/18543527/87371213-745a8d80-c5b7-11ea-8fcc-6e7d3658c18c.png)
## 最小可复现仓库

> https://github.com/drafish/umi-demo

## 相关环境信息

- **Umi 版本**：^3.2.2

**Comment by xiaohuoni** [comment]
转过来，发现已经有一个一样的issues了

**Comment by 1007029335** [comment]
请问解决了吗

**Comment by xiaohuoni** [comment]
https://github.com/umijs/qiankun/issues/808
