### ISSUE TITLE
qiankun如何兼容ssr项目

### ISSUE THREAD

**Issue by ZhengXingchi** [umijs/qiankun#946]
## What happens?
项目中原来一个老项目用的umi+egg进行ssr服务端渲染。现在需要将项目进行整合，但是umi+egg这边不知道如何进行配置

**Comment by ZhengXingchi** [comment]
现在umi的页面与egg是耦合的，请问这种情况qiankun框架能够驾驭吗

**Comment by kuitos** [comment]
qiankun不挑技术栈
