### ISSUE TITLE
注册子应用后 主应用报错 [import-html-entry]: error occurs while executing entry script

### ISSUE THREAD

**Issue by GonyMaster** [umijs/qiankun#947]
## What happens?

注册子应用后 主应用报错 [import-html-entry]: error occurs while executing entry script

子应用的全局变量已经过来了 但是界面没有渲染成功 单独打开子应用是没有问题的

## Context
![image](https://user-images.githubusercontent.com/14261751/93878637-f5977480-fd0c-11ea-8040-3e056474ba66.png)

- **qiankun Version**:2.0.25
- **Platform Version**:win10
- **Browser Version**:chrome

**Comment by kuitos** [comment]
Uncaugh Error: only one instance of babel-polyfill is allowed

https://www.google.com.hk/search?q=only+one+instance+of+babel-polyfill+is+allowed&oq=only+one+instance+of+babel-polyfill+is+allowed

**Comment by gongshun** [comment]
`babel-polyfill` 主应用引入一次就可以了，子应用不需要重复引入

**Comment by mhfe123** [comment]
> `babel-polyfill` 主应用引入一次就可以了，子应用不需要重复引入

但是如果子应用不引入babel-polyfill，子应用怎么去打包呢，本身都是两个不同的项目

**Comment by 535601882** [comment]
> > `babel-polyfill` 主应用引入一次就可以了，子应用不需要重复引入
> 
> 但是如果子应用不引入babel-polyfill，子应用怎么去打包呢，本身都是两个不同的项目

遇到相同的问题。有合适的解决方案吗？？

**Comment by gongshun** [comment]
> 但是如果子应用不引入babel-polyfill，子应用怎么去打包呢，本身都是两个不同的项目

`cdn` 引入，主子项目都引人，但是子应用的` script` 标签加上 `ignore` 属性

**Comment by mhfe123** [comment]
> > 但是如果子应用不引入babel-polyfill，子应用怎么去打包呢，本身都是两个不同的项目
> 
> `cdn` 引入，主子项目都引人，但是子应用的` script` 标签加上 `ignore` 属性

但是有时候项目是离线的，不可能从外网加载资源啊

**Comment by gongshun** [comment]
> 但是有时候项目是离线的，不可能从外网加载资源啊

不能用 cdn 也没关系，把 js 下载到本地，随着项目一起部署，script 标签引入，子应用的 script 标签加上 ignore 属性就行了

**Comment by huangche007** [comment]
@GonyMaster 搞定没？我也是遇到和你一样的问题

**Comment by zsychy** [comment]
@GonyMaster 老哥解决了吗
我也遇到了

**Comment by Raylayll** [comment]
救命，我在子应用中没引入babel-polyfill，在本地主子应用运行正常，子应用部署到测试环境就报了这个错误，怎么回事？？？

**Comment by 1091785626** [comment]
看看这个样子是否能解决问题
entry: {
        app: ['@babel/polyfill', resolve('src/main.js')]
    },

**Comment by JoeHR** [comment]
- qiankun Version:2.3.2
- Platform Version:win10
- Browser Version:chrome

主应用 和 子应用 都是 vue-cli 4.5.0 版本的vue-cli 创建的 vue 项目，没有主动引入 过 babel-polyfill,也会报这个错误 

![image](https://user-images.githubusercontent.com/22998545/100441850-0f28b400-30e2-11eb-88b8-9dcca1bee461.png)

**Comment by wsb260** [comment]
解决办法是啥就关闭了？？？子应用不引用根本就行不通，什么下载js根本不靠谱

**Comment by mhfe123** [comment]
> 解决办法是啥就关闭了？？？子应用不引用根本就行不通，什么下载js根本不靠谱

删掉import，然后再index.html里边通过script标签去引入，然后子应用的script标签上加上ignore属性，如果是qiankun框架引入的话ignore会生效，如果是自己启动，ignore就不会生效

**Comment by lizeyuan** [comment]
> * qiankun Version:2.3.2
> * Platform Version:win10
> * Browser Version:chrome
> 
> 主应用 和 子应用 都是 vue-cli 4.5.0 版本的vue-cli 创建的 vue 项目，没有主动引入 过 babel-polyfill,也会报这个错误
> 
> ![image](https://user-images.githubusercontent.com/22998545/100441850-0f28b400-30e2-11eb-88b8-9dcca1bee461.png)

请问解决了么，没有引入babel-polyfill

**Comment by lizeyuan** [comment]
这个有点不靠谱啊，回答的什么玩意

**Comment by gongshun** [comment]
> 主应用 和 子应用 都是 vue-cli 4.5.0 版本的vue-cli 创建的 vue 项目，没有主动引入 过 babel-polyfill,也会报这个错误
> 
> ![image](https://user-images.githubusercontent.com/22998545/100441850-0f28b400-30e2-11eb-88b8-9dcca1bee461.png)

@joeHR 这个报错和 issue 根本不是同一个问题，所有的这种报错第一句都是  `[import-html-entry]: error occurs while executing entry script` ，这仅仅是提示报错位置，第二句才是真正的错误。

至于你这个报错，参考 https://github.com/umijs/qiankun/issues/1105#issuecomment-750330170

**Comment by xiaoqiangz** [comment]
> > * qiankun Version:2.3.2
> > * Platform Version:win10
> > * Browser Version:chrome
> > 
> > 主应用 和 子应用 都是 vue-cli 4.5.0 版本的vue-cli 创建的 vue 项目，没有主动引入 过 babel-polyfill,也会报这个错误
> > ![image](https://user-images.githubusercontent.com/22998545/100441850-0f28b400-30e2-11eb-88b8-9dcca1bee461.png)
> 
> 请问解决了么，没有引入babel-polyfill

一样的，请问解决了吗？

**Comment by luocong2016** [comment]
## 在微应用 `index.html` 添加
```
<script src="xxx/babel-polyfill.min.js" ignore></script>
```

**Comment by Xpluto1** [comment]
![Uploading image.png…]()

**Comment by Xpluto1** [comment]
我遇到的问题好像不一样

![11](https://user-images.githubusercontent.com/22413530/109919189-41563d00-7cf3-11eb-8328-711228389d63.png)

**Comment by panzhengtao** [comment]
> 
> 
>     * qiankun Version:2.3.2
> 
>     * Platform Version:win10
> 
>     * Browser Version:chrome
> 
> 
> 主应用 和 子应用 都是 vue-cli 4.5.0 版本的vue-cli 创建的 vue 项目，没有主动引入 过 babel-polyfill,也会报这个错误
> 
> ![image](https://user-images.githubusercontent.com/22998545/100441850-0f28b400-30e2-11eb-88b8-9dcca1bee461.png)

我的qiankun 版本是： 2.4.1
遇到这个问题的原因是我在apps里面使用了render属性，应改为最新的container挂载方式。
![图片](https://user-images.githubusercontent.com/20961522/116536879-17e31780-a918-11eb-9b37-139078fd5029.png)

**Comment by Adgeros** [comment]
升级到最新版本就好了

**Comment by Adgeros** [comment]
> 升级到最新版本就好了

或者是路由配置的不对

**Comment by MyIsAChaYeDan** [comment]
这个问题无解了 没有一个人的解决方法是对的

**Comment by LiuwqGit** [comment]
可能是因为没有动态设置 publicPath
#1062

**Comment by xcgs123** [comment]
> > 解决办法是啥就关闭了？？？子应用不引用根本就行不通，什么下载js根本不靠谱
> 
> 删掉import，然后再index.html里边通过script标签去引入，然后子应用的script标签上加上ignore属性，如果是qiankun框架引入的话ignore会生效，如果是自己启动，ignore就不会生效

有代码吗，看下

**Comment by FateZeros** [comment]
这个问题有解决了的吗？

**Comment by billxie1988** [comment]
检查下UserAgent 是否获取正常，我遇到 了这个问题 是一个向下兼容的问题。发现老版本移动端的系统 设置UA的方式不一样，适配后就好了

**Comment by Xpluto1** [comment]
是入口配置的问题，不是qiankun的问题

**Comment by ZxBee** [comment]
你的publicPath 和 router base 信息 是否是对应上的 看下

**Comment by Ho-Jack** [comment]
分析一下我遇见的“Uncaugh Error: only one instance of babel-polyfill is allowed”报错解决方案：
微应用引入第三方插件内引入了 babel-polyfill和主应用的babel-polyfill冲突导致报错，在控制台会打印“Uncaugh Error: only one instance of babel-polyfill is allowed”，并且会显示出错误位置，可以到该报错位置引入的第三方插件是否有引入babel-polyfill，可以在依赖中查找babel-polyfill关键字找到并删除相关引入，看是否有效，来判断哪个第三方插件有问题

**Comment by xuqihua** [comment]
怎么解决的？

**Comment by fantasyroot** [comment]
跟这个问题是一样的 https://github.com/umijs/qiankun/issues/1613

**Comment by fz6m** [comment]
也遇到了这个报错，原因是引入了有 Breaking change 的 `core-js` 3.23.0 版本，换成 >= 3.23.1 就好了。

**Comment by Xpluto1** [comment]
您的邮件已经收到，我会尽快处理！

**Comment by 992forever** [comment]
> 是入口配置的问题，不是qiankun的问题

你好，我出现的问题报错信息跟你的一样，请问你最后是怎么解决的呢？

**Comment by wuzhouchao** [comment]
![ENVG`KABGHMM$O%G29D$6BN](https://user-images.githubusercontent.com/62629899/183327672-df71d169-0660-488c-b5e8-6526b61ce1f4.png)
我这是什么问题啊

**Comment by Xpluto1** [comment]
您的邮件已经收到，我会尽快处理！

**Comment by gitspringcould** [comment]
大佬，问题解决了吗？

**Comment by Xpluto1** [comment]
您的邮件已经收到，我会尽快处理！
