### ISSUE TITLE
接入react的ts子项目会报错

### ISSUE THREAD

**Issue by Jackson-p** [umijs/qiankun#949]
## What happens?

用vue-cli 生成了一个ts+router+vuex+eslint+prettier的基座项目，按照官方文档进行配置后，如果是接qiankun官方example里的react 16 项目没有问题。
![download](https://user-images.githubusercontent.com/20417123/93958396-fd94fa00-fd88-11ea-8a14-ec98c212ec76.png)

但发现如果是接已经有的React ts项目会有报错

chrome端：webpackHotDevClient.js:60 WebSocket connection to 'ws://localhost:9999/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200

vue-cli基座 devServer的终端:

![6e2401cd94612902384c06181a248be2](https://user-images.githubusercontent.com/20417123/93958964-47321480-fd8a-11ea-9ee2-9045375ef0fd.png)

然后vue-cli自动终止

## How To Reproduce

**Steps to reproduce the behavior:** vue-cli 创建如上项目，接ts子项目

**Expected behavior** 1运行正常.

## Context

- **qiankun Version**: 2.0.25
- **Platform Version**: vue-cli 4.5.6
- **Browser Version**:  85.0.4183.102

## 补充

其实也有可能不是ts问题，如果确实不是ts问题，想请教下 一般这样报错是因为什么呢

**Comment by tigermmmmm** [comment]
请问解决了吗 为什么呢

**Comment by Jackson-p** [comment]
> 请问解决了吗 为什么呢

没解决呀orz

**Comment by ccysmd** [comment]
没有解决咋关了呢，我也有这个问题

**Comment by tinet-dongfb** [comment]
暂时的解决办法，有办法希望@下我
const index = config.plugins.findIndex(v => v.definitions);
    const ev = config.plugins[index].definitions['process.env'];

    ev.WDS_SOCKET_HOST = "'localhost'"
    ev.WDS_SOCKET_PORT = "3000"
    ev.WDS_SOCKET_PATH = "'http://localhost:3000'"

**Comment by lyfcp** [comment]
请问这个解决了吗，我也遇到这个问题，搞了半天没搞好

**Comment by lyfcp** [comment]
> 暂时的解决办法，有办法希望@下我
> 
> const index = config.plugins.findIndex(v => v.definitions); const ev = config.plugins[index].definitions['process.env']; ev.WDS_SOCKET_HOST = "'localhost'" ev.WDS_SOCKET_PORT = "3000" ev.WDS_SOCKET_PATH = "'http://localhost:3000'"

这个在哪配置

**Comment by tinet-dongfb** [comment]
> > 暂时的解决办法，有办法希望@下我
> > const index = config.plugins.findIndex(v => v.definitions); const ev = config.plugins[index].definitions['process.env']; ev.WDS_SOCKET_HOST = "'localhost'" ev.WDS_SOCKET_PORT = "3000" ev.WDS_SOCKET_PATH = "'http://localhost:3000'"
> 
> 这个在哪配置

webpack的加plugins的地方；不知道是不是和你遇到的错误一样
