### ISSUE TITLE
[Bug]document.head.removeChild(script)错误-Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by lijing666** [umijs/qiankun#951]
## 重现步骤
启动时开启沙箱和样式隔离
`start({ 
          prefetch: true ,
          sandbox: {strictStyleIsolation: true}
        });`
第一步：子应用内部调用document.head.appendChild(script); 添加一个脚本标签
第二步：子应用内部调用document.head.removeChild(script); 移除这个脚本标签后，报错：
`dynamicAppend.js Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

## 问题分析
qiankun的dynamicAppend沙箱模式，重写了document.head.appendChild和document.head.removeChild方法，并且document.head.appendChild在插入脚本时只是插入了注释到shadowdom的root中，并没有真实的插入script标签，所以document.head.removeChild的时候失败了，这是dynamicAppend.js的代码，isHijackingTag判断了script标签但是最终
`container.contains(child)`为false，最终调用了原始的document.head.removeChild导致错误：

`function getNewRemoveChild(opts) {
  return function removeChild(child) {
    var headOrBodyRemoveChild = opts.headOrBodyRemoveChild;

    try {
      var tagName = child.tagName;

      if (isHijackingTag(tagName)) {
        var appWrapperGetter = opts.appWrapperGetter;
        var storedContainerInfo = child[attachElementContainerSymbol];

        if (storedContainerInfo) {
          // eslint-disable-next-line prefer-destructuring
          appWrapperGetter = storedContainerInfo.appWrapperGetter;
        } // container may had been removed while app unmounting if the removeChild action was async

        var container = appWrapperGetter();

        if (container.contains(child)) {
          return rawRemoveChild.call(container, child);
        }
      }
    } catch (e) {
      console.warn(e);
    }

    return headOrBodyRemoveChild.call(this, child);
  };
}`

## 相关环境信息

- **qiankun最新版本**
- **浏览器chrome85**：
- **操作系统mac**：

**Comment by dragonir** [comment]
遇到相同的问题，子应用为backbone时，打开应用显示
`DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

**Comment by kuitos** [comment]
原因是 script 是被转换成 comment 然后 append 到 container 的，所以 remove 的 container.contains 判断就会失效

什么场景下会需要 remove 一个动态插入的 script ？有真实场景吗？ @lijing666

**Comment by lijing666** [comment]
> 原因是 script 是被转换成 comment 然后 append 到 container 的，所以 remove 的 container.contains 判断就会失效
> 
> 什么场景下会需要 remove 一个动态插入的 script ？有真实场景吗？ @lijing666

@kuitos 真实场景就是我们在子应用中，引入了systemjs动态加载远程脚本，systemjs引入全局脚本就是先插入script标签，然后移除

**Comment by Dz-9527** [comment]
> > 原因是 script 是被转换成 comment 然后 append 到 container 的，所以 remove 的 container.contains 判断就会失效
> > 什么场景下会需要 remove 一个动态插入的 script ？有真实场景吗？ @lijing666
> 
> @kuitos 真实场景就是我们在子应用中，引入了systemjs动态加载远程脚本，systemjs引入全局脚本就是先插入script标签，然后移除

我也遇到了这个问题 解决办法是把 systemjs源码里面有个 document.head.removeChild(script) 注释掉就可以

**Comment by Asher-Tan** [comment]
> > 原因是 script 是被转换成 comment 然后 append 到 container 的，所以 remove 的 container.contains 判断就会失效
> > 什么场景下会需要 remove 一个动态插入的 script ？有真实场景吗？ @lijing666
> 
> @kuitos 真实场景就是我们在子应用中，引入了systemjs动态加载远程脚本，systemjs引入全局脚本就是先插入script标签，然后移除
后来怎么处理的呢？

**Comment by jiangSSS** [comment]
幸运儿签到。
