### ISSUE TITLE
window的箭头事件不生效

### ISSUE THREAD

**Issue by wangfpp** [umijs/qiankun#952]
## What happens?
在普通HTML的子应用中使用window事件无效
```javascript
window.onload = _ => {
    console.log(11); //这里的代码不会执行　 所有的windows事件都不生效
}
```

## Context

- **qiankun Version**:　２．０．２５
- **Platform Version**:Ubuntu 20.04
- **Browser Version**: Chrome 85

**Comment by kuitos** [comment]
子应用加载之前 window 就已经是 loaded 状态了，自然不会再触发 onload 事件

**Comment by wangfpp** [comment]
我在子应用中有定时器　想在子应用销毁的时候清除该如何做呢　
我关闭了js沙箱

**Comment by gongshun** [comment]
> 我在子应用中有定时器　想在子应用销毁的时候清除该如何做呢

unmount 周期销毁就可以了
