### ISSUE TITLE
这个basename警告怎么去掉呢？

### ISSUE THREAD

**Issue by whereiscode** [umijs/qiankun#954]
Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/#/a/website/page/add" to begin with "/app1".

**Comment by gongshun** [comment]
`react-router` 的警告，与 `qiankun` 无关。https://github.com/ReactTraining/react-router/issues/6516

**Comment by whereiscode** [comment]
@gongshun 好的谢谢
