### ISSUE TITLE
qiankun 是否支持前端离线包本地加载

### ISSUE THREAD

**Issue by jaryWu** [umijs/qiankun#955]
## Question

如题，看过官方文档，也搜过各种介绍qiankun的文章，但是没有介绍过原生iOS/Android webview加载离线主应用/子应用包的场景，我们是web混合开发App，有原生iOS/Android 缓存前端离线资源的需求，想问下qiankun目前是否支持这种场景，烦请解答

## 复现步骤，错误日志以及相关配置

<img width="717" alt="image" src="https://user-images.githubusercontent.com/10849011/94219206-dbca7d00-ff18-11ea-8d30-4fdfe33b1588.png">

## 相关环境信息

- **qiankun 版本**：2.0.24
- **操作系统**：MacOS 10.15.6

**Comment by howel52** [comment]
端内 web 应用采用 qiankun 主要是为了解决什么问题？

**Comment by jaryWu** [comment]
> 端内 web 应用采用 qiankun 主要是为了解决什么问题？

**Comment by jaryWu** [comment]
> 端内 web 应用采用 qiankun 主要是为了解决什么问题？

是因为移动端做了一套基于版本比对的缓存机制，web版本更新之后，移动端就会加载远程连接，同时会异步下载web静态资源包，app下次打开，如果已经缓存了静态资源并且版本没有更新，就会加载app本地web资源，此时就会遇到这个问题，这个问题卡了很久，望提供一下解决思路，感谢

**Comment by leason-wan** [comment]
start可以自定义fetch，可以通过这个做

**Comment by gongshun** [comment]
> start可以自定义fetch，可以通过这个做

离线环境，没有服务器，fetch 用不了 :joy:

**Comment by wenwu-bianjie** [comment]
qiankun没有用过，基于pwa技术可以离线加载本地资源，可以使用pwa的npm  workbox 包试下可以不

**Comment by kuitos** [comment]
> start可以自定义fetch，可以通过这个做

正解，复写 fetch 方法然后里面去从本地读就可以了

**Comment by kuitos** [comment]
参考 https://qiankun.umijs.org/zh/faq#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-fetch-%E6%96%B9%E6%B3%95
