### ISSUE TITLE
umi多环境配置时，qiankun属性配置.umirc.test.ts文件无法覆盖.umirc.ts文件的配置？

### ISSUE THREAD

**Issue by bingo618** [umijs/qiankun#957]
## What happens?

umi多环境配置时，qiankun属性配置.umirc.test.ts文件无法覆盖.umirc.ts文件的配置？

## 相关环境信息

- **qiankun 版本**
"@umijs/plugin-qiankun": "^2.4.0",
"qiankun": "^2.0.17-3",
- **浏览器版本**：
chrome
- **操作系统**：
mac os

**Comment by kuitos** [comment]
closed via inactive

**Comment by Rlagnl** [comment]
@kuitos 您好，遇到了相同问题，请问是否有修复或其他解决方案呢？
