### ISSUE TITLE
嵌套子应用预计什么时候支持

### ISSUE THREAD

**Issue by humorHan** [umijs/qiankun#960]
如题，最近项目中(使用qiankun 不使用umijs)需要用到嵌套子应用，想问下
1. 现在是否支持，文档没有看到相关说明
2. 如果支持能否给出demo
3. 如果不支持是否有计划支持，大概时间是？以及对应的环境隔离是基于子应用，还是所有应用的环境隔离(比如子应用和孙子应用是否有隔离性)
@kuitos

**Comment by gongshun** [comment]
支持嵌套的，可以看下这个：https://juejin.im/post/6856569463950639117#heading-29

**Comment by humorHan** [comment]
> 支持嵌套的，可以看下这个：https://juejin.im/post/6856569463950639117#heading-29

en 非常感谢，文章写得很好， 看了下，有个疑问是为什么不在主应用做注册所有应用的事情而是开放给子应用注册孙子应用，这样有如下两个疑问
1. 子应用和孙子应用是否环境隔离
2. 子应用不想关于微前端的事情，只关心正常开发，但是现在貌似也需要关心了
大佬 可以看下我的问题吗

**Comment by gongshun** [comment]
1. 「 主项目将 qiankun 的注册函数传递给子项目 」这个使用场景趋向于：将嵌套的子项目都注册为同级子项目，直接用主项目的容器」
2. 「 子项目自己运行一个 qiankun 实例 」： 子应用就是相当于一个普通的子应用

关于隔离，主应用和子应用以及孙子应用，：
1. css 是不隔离的（当然了，如果使用 `shadow` 是隔离的）
2. js 沙箱，window 上的值是可以单项传递的：主应用 -> 子应用 ->  孙子应用

**Comment by humorHan** [comment]
> 1. 「 主项目将 qiankun 的注册函数传递给子项目 」这个使用场景趋向于：将嵌套的子项目都注册为同级子项目，直接用主项目的容器」
> 2. 「 子项目自己运行一个 qiankun 实例 」： 子应用就是相当于一个普通的子应用
> 
> 关于隔离，主应用和子应用以及孙子应用，：
> 
> 1. css 是不隔离的（当然了，如果使用 `shadow` 是隔离的）
> 2. js 沙箱，window 上的值是可以单项传递的：主应用 -> 子应用 ->  孙子应用

明白，多谢~
不过感觉还是应该在主应用注册好多有应用，子项目只关心正常业务  收敛性好一些  避免所有人都需要了解qiankun的成本问题。

请问下采用子应用中注册子应用的方式，而没有采用主应用注册所有应用的方式  是有什么考虑吗

**Comment by gongshun** [comment]
> 请问下采用子应用中注册子应用的方式，而没有采用主应用注册所有应用的方式 是有什么考虑吗

没有规定必须用哪种方案，看情况选择吧 :joy:

**Comment by humorHan** [comment]
> > 请问下采用子应用中注册子应用的方式，而没有采用主应用注册所有应用的方式 是有什么考虑吗
> 
> 没有规定必须用哪种方案，看情况选择吧 😂

好的，感谢大佬回复~ 暂时没有其他问题了
