### ISSUE TITLE
子应用的是vue框架，富文本用的是tiny，加载不出来了

### ISSUE THREAD

**Issue by hechangquan** [umijs/qiankun#961]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## 最小可复现仓库

子应用富文本tiny报错，显示不出来，本地独立项目一点问题都没有

## 复现步骤，错误日志以及相关配置

子应用富文本tiny报错，显示不出来，本地独立项目一点问题都没有

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by gongshun** [comment]
提供一下最小复现demo

**Comment by han-neil** [comment]
sandbox 设置为false即可

**Comment by huangche007** [comment]
@hechangquan  你好，搞定了吗？我也遇到了这个问题

**Comment by huangche007** [comment]
@han-neil 设置sandbox是可以，但是就做不到资源的隔离了

**Comment by huangche007** [comment]
@han-neil 搞定了，通过`excludeAssetFilter - (assetUrl: string) => boolean - 可选，指定部分特殊的动态加载的微应用资源（css/js) 不被 qiankun 劫持处理。`可以解决

**Comment by hechangquan** [comment]
> @hechangquan 你好，搞定了吗？我也遇到了这个问题



> sandbox 设置为false即可

这个也要设置，但是还是会报错，我改了tiny的源码才可以

**Comment by hechangquan** [comment]
> @han-neil 搞定了，通过`excludeAssetFilter - (assetUrl: string) => boolean - 可选，指定部分特殊的动态加载的微应用资源（css/js) 不被 qiankun 劫持处理。`可以解决

嗯可以试一下

**Comment by SongMengyao** [comment]
> @han-neil 搞定了，通过`excludeAssetFilter - (assetUrl: string) => boolean - 可选，指定部分特殊的动态加载的微应用资源（css/js) 不被 qiankun 劫持处理。`可以解决

加上去貌似没效果，里面打印的log都没出来，，，可以把你们的代码贴一下吗？谢谢

**Comment by CareyToboo** [comment]
> > @han-neil 搞定了，通过`excludeAssetFilter - (assetUrl: string) => boolean - 可选，指定部分特殊的动态加载的微应用资源（css/js) 不被 qiankun 劫持处理。`可以解决
> 
> 加上去貌似没效果，里面打印的log都没出来，，，可以把你们的代码贴一下吗？谢谢

+1, 试了一下也是没有效果，估计是哪里 写的有问题。

**Comment by hechangquan** [comment]
把那个沙箱关了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mengyao Song"<notifications@github.com&gt;; 
发送时间: 2020年10月29日(星期四) 下午5:49
收件人: "umijs/qiankun"<qiankun@noreply.github.com&gt;; 
抄送: "千古绝唱"<279201338@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [umijs/qiankun] 子应用的是vue框架，富文本用的是tiny，加载不出来了 (#961)





  
@han-neil 搞定了，通过excludeAssetFilter - (assetUrl: string) =&gt; boolean - 可选，指定部分特殊的动态加载的微应用资源（css/js) 不被 qiankun 劫持处理。可以解决
  
加上去貌似没效果，里面打印的log都没出来，，，可以把你们的代码贴一下吗？谢谢
