### ISSUE TITLE
项目启动找不到es文件

### ISSUE THREAD

**Issue by 309027590** [umijs/qiankun#962]
##项目启动找不到es文件

ERROR in ./index.js
Module not found: Error: Can't resolve '../../es' in 'D:\technical-doc\qiankun\examples\main'
 @ ./index.js 1:0-111 30:0-17 72:23-38 91:0-18 96:0-5 97:0-20

**Comment by gongshun** [comment]
先打包一下： `npm run build`
启动 `demo`，你可以：先 `npm run examples:install`，再 `npm run examples:start`

**Comment by LeeHao12** [comment]
项目必须使用 yarn 安装依赖，否则会出错

**Comment by jett2020** [comment]
先安装qiankun  执行 yarn add qiankun
然后把 qiankun 替换 ../../es 即可
