### ISSUE TITLE
vue子项目时，router懒加载报错

### ISSUE THREAD

**Issue by 15102642047** [umijs/qiankun#963]
router懒加载引入页面时，如下：
component: resolve => require(['../src/views/About.vue'], resolve)

会报如下的错误：
app.js:988 ChunkLoadError: Loading chunk 0 failed.

疑问：子项目使用懒加载路由时，主项目是否读取不到路由，导致错误？qiankun自包含懒加载吗？

**Comment by gongshun** [comment]
检查下路径是否正确，路径不正确说明是 `publicPath` 的原因。参考这个 demo: https://github.com/gongshun/qiankun-vue-demo
