### ISSUE TITLE
子应用挂载时，如果有动态添加非style、script、link等标签，存在内存泄漏问题

### ISSUE THREAD

**Issue by yizeshun** [umijs/qiankun#964]
## What happens?

子应用挂载时，如果有动态添加非style、script、link等标签，该标签不会被添加到子应用的挂载容器中，故不会随着子应用的卸载而被删除，这样会存在内存泄漏的风险

## Mini Showcase Repository(REQUIRED)
源码中加上 DIV_TAG_NAME 可以解决这个问题
 switch (element.tagName) {
        case LINK_TAG_NAME:
        case STYLE_TAG_NAME: {
          const stylesheetElement: HTMLLinkElement | HTMLStyleElement = newChild as any;
          const { href } = stylesheetElement as HTMLLinkElement;
          if (!invokedByMicroApp || (excludeAssetFilter && href && excludeAssetFilter(href))) {
            return rawDOMAppendOrInsertBefore.call(this, element, refChild) as T;
          }

          const mountDOM = appWrapperGetter();

          if (scopedCSS) {
            css.process(mountDOM, stylesheetElement, appName);
          }

          // eslint-disable-next-line no-shadow
          dynamicStyleSheetElements.push(stylesheetElement);
          const referenceNode = mountDOM.contains(refChild) ? refChild : null;
          return rawDOMAppendOrInsertBefore.call(mountDOM, stylesheetElement, referenceNode);
        }

        **case DIV_TAG_NAME: {
            const divElement: HTMLDivElement = newChild as any;
            if (!invokedByMicroApp) {
                return rawDOMAppendOrInsertBefore.call(this, element, refChild) as T;
              }

              const mountDOM = appWrapperGetter();
              const referenceNode = mountDOM.contains(refChild) ? refChild : null;
              return rawDOMAppendOrInsertBefore.call(mountDOM, divElement, referenceNode);
        }**

> Provide a mini GitHub repository which can reproduce the issue.

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**:
- **Platform Version**:
- **Browser Version**:

**Comment by kuitos** [comment]
by design

style、script、link 等可能影响 UI 行为的 dom 的插入 qiankun 沙箱不会处理，因为如果盲目的插入到子应用的 container 中，可能会造成 UI 上不符合预期，比如弹框会被子应用 container 的 overflow 样式影响。

换个角度看，通常这类 dom 插入是由组件库完成的，一般比较完善的组件库会在组件卸载时自己清理插入到 body 的 dom，这个行为也会在应用 unmount 时自动触发。
而且，严格来说，即使 dom 没有被清理，这也只能算是 dom 泄露，不一定会造成「内存泄露」，是否内存泄露，跟他是否有未清理的 dom 不成正相关🤔
