### ISSUE TITLE
怎么获得子应用的window？

### ISSUE THREAD

**Issue by whereiscode** [umijs/qiankun#966]
子应用明明存在abc方法，但是在子应用里再去调用这个方法就提示不存在，或者在控制台打印window.abc也不存在

**Comment by MinweiShen** [comment]
试试在子应用里用`window.proxy.abc`

**Comment by whereiscode** [comment]
@MinweiShen 这样可以打印出来 🤩 好神奇，您是怎么知道的呢，还有请问如果是build部署后也是这么用吗？

**Comment by whereiscode** [comment]
不过这样打印还是存在bug，在控制台可以打印出来，在子应用中打印还是出不来，这可能是官方的一个bug

**Comment by gongshun** [comment]
你需要把全局的函数显式的挂载到 `window` 上：`window.abc = function () {}`，然后才可以调用 `window.abc()`。

如果你直接在某个文件使用 `function` 声明了一个全局函数，由于沙箱，这个函数不属于 `window`，也不是全局的。

**Comment by whereiscode** [comment]
@gongshun 谢谢您  这样可以调用到abc了，请问如何修改这个函数呢，我尝试在子应用里修改这个函数，好像没有效果

**Comment by whereiscode** [comment]
window.proxy.abc
window.abc 
我都尝试修改abc里面打印一个字符串，但是都木有运行

**Comment by gongshun** [comment]
> 请问如何修改这个函数呢，

子应用自己的全局函数，自己修改怎么会有问题呢，你是跨应用修改？

**Comment by whereiscode** [comment]
@gongshun 
我在做web的pc拖拽装修，用了一个iframe，我把pc拖拽装修做为了主后台的一个子应用，所以的装修、预览界面都从这个应用里走，装修为子应用的路由editor，预览为子应用的路由preview

我把editor通过如下方法引入：
```js
 <MicroAppWithMemoHistory
                name="app1"
                autoSetLoading
                url="/editor"
            />
```
editor里有个iframe引入的是preview，它俩的交互是通过我之前写的一个方法叫window.receiveDomData

子项目我单独运行没有问题
但是呢我发现window在qiankun下不是全局可用的
比如preview想调用editor的receiveDomData，我发现是不行的 提示undefined
我的调用代码是preview里window.parent.receiveDomData，在我脑海里我认为是可以调用到editor里我赋值的window.receiveDomData，但实际是没调用到，具体问题出在哪里，思路在哪我还没想到

**Comment by whereiscode** [comment]
没办法获得window  先临时处理下了   把window通过props赋值给子应用

**Comment by fantasyroot** [comment]
> @gongshun
> 我在做web的pc拖拽装修，用了一个iframe，我把pc拖拽装修做为了主后台的一个子应用，所有的装修、预览界面操作都从这个应用里走，装修为子应用的路由editor，预览为子应用的路由preview（我是把子应用引入到主项目的哈，地址访问都是主项目的路由）
> 
> 我把editor通过如下方法引入：
> 
> ```js
>  <MicroAppWithMemoHistory
>                 name="app1"
>                 autoSetLoading
>                 url="/editor"
>             />
> ```
> 
> editor里有个iframe引入的是preview，它俩的交互是通过我之前写的一个方法叫window.receiveDomData
> 
> 子项目我单独运行没有问题
> 但是呢我发现window在qiankun下不是全局可用的
> 比如preview想调用editor的receiveDomData，我发现是不行的 提示undefined
> 我的调用代码是preview里window.parent.receiveDomData，在我脑海里我认为是可以调用到editor里我赋值的window.receiveDomData，但实际是没调用到，具体问题出在哪里，思路在哪我还没想到

iframe 里面的 js 不在沙箱里执行，会读到外面真实的 window 上。而 receiveDomData 方法在沙箱里面。也就是方法实现写在沙箱里、方法调用读在沙箱外。
两个处理方案：1. 把 receiveDomData 做白名单处理，强制写在外面真实的 window 上   2. 用 window.parent.proxy. receiveDomData

**Comment by liunianyuying** [comment]
> > @gongshun
> > 我在做web的pc拖拽装修，用了一个iframe，我把pc拖拽装修做为了主后台的一个子应用，所有的装修、预览界面操作都从这个应用里走，装修为子应用的路由editor，预览为子应用的路由preview（我是把子应用引入到主项目的哈，地址访问都是主项目的路由）
> > 我把editor通过如下方法引入：
> > ```js
> >  <MicroAppWithMemoHistory
> >                 name="app1"
> >                 autoSetLoading
> >                 url="/editor"
> >             />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > editor里有个iframe引入的是preview，它俩的交互是通过我之前写的一个方法叫window.receiveDomData
> > 子项目我单独运行没有问题
> > 但是呢我发现window在qiankun下不是全局可用的
> > 比如preview想调用editor的receiveDomData，我发现是不行的 提示undefined
> > 我的调用代码是preview里window.parent.receiveDomData，在我脑海里我认为是可以调用到editor里我赋值的window.receiveDomData，但实际是没调用到，具体问题出在哪里，思路在哪我还没想到
> 
> iframe 里面的 js 不在沙箱里执行，会读到外面真实的 window 上。而 receiveDomData 方法在沙箱里面。也就是方法实现写在沙箱里、方法调用读在沙箱外。
> 两个处理方案：1. 把 receiveDomData 做白名单处理，强制写在外面真实的 window 上 2. 用 window.parent.proxy. receiveDomData

可以这样获取真实window：
const _window = new Function("return this")();
然后定义你的方法：
_window.receiveDomData = () => {};

**Comment by liuyingjie1130** [comment]
qiankun  window.proxy下可以获取子应用的window变量
