### ISSUE TITLE
主应用路由push时触发子应用正常 但是刷新主应用后 子应用无法加载到

### ISSUE THREAD

**Issue by GonyMaster** [umijs/qiankun#969]
## What happens?
主应用路由push时触发子应用正常 但是直接刷新主应用后 子应用加载失败 
## Context
![image](https://user-images.githubusercontent.com/14261751/94540310-e23e5900-0278-11eb-8828-5c24d3259aa2.png)

- **qiankun Version**:2.0.2
- **Platform Version**:win10
- **Browser Version**:chrome

**Comment by gongshun** [comment]
你需要等容器加载好了，才能加载子项目，注意下 `start()` 的调用时机。如果是 `Vue` 项目，可以在组件的 `mounted` 周期启动子项目。
