### ISSUE TITLE
使用 react-create-app 创建的项目，子应用只要修改了任何界面上的内容，都会报错

### ISSUE THREAD

**Issue by mannymu** [umijs/qiankun#971]
1、使用 react-create-app 创建了三个项目， 一个主，两个子，都使用了 yarn run  eject 。
2、按照文档，确实正确的将子应用加载进来了。
3、当修改子应用上面任何内容，如 div ，文本 等。
4、再次刷新主应用，就会报错。 子应用必须重启 webpack 或者 修改子页面的 index.js （在里面加空格）  才行

![image](https://user-images.githubusercontent.com/15630104/94658391-51798300-0335-11eb-994b-db4af38ff9ce.png)

报错如下：
loader.js:194 [qiankun] lifecycle not found from react app two entry exports, fallback to get from window['react app two']

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/340
