### ISSUE TITLE
子应用angular路由lazy load的问题

### ISSUE THREAD

**Issue by ycpaladin** [umijs/qiankun#988]
## What happens?

1. 在演示文件夹中的angular9里面添加了2个子路由，通过lazy的方式加载
2. 在app.component.html中放入了router-outlet 以及 2个 routerLink 分别指向2个路由
3. 点击routerLink后毫无反应
4. 检查network中请求的js文件地址为 http://localhost:7099/module2-module2-module.js，
![image](https://user-images.githubusercontent.com/3337028/95680459-9393a600-0c0c-11eb-92ec-464c9a4d4682.png)

    实际上应该是 http://localhost:7103/module2-module2-module.js
![image](https://user-images.githubusercontent.com/3337028/95680452-77900480-0c0c-11eb-851a-aa3f65c89830.png)

**顺便说一句: 在子应用 vue(3)和react(15,16)中的lazy load是能够正常加载到js文件的。**

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.

   https://github.com/ycpaladin/qiankun-ng-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **qiankun Version**: latest
- **Platform Version**: WIN 10, Node v12.14.1
- **Browser Version**: MS EDGE latest

**Comment by tommas3210** [comment]
package.json裡的"serve:qiankun"補上 **--deploy-url //localhost:7103/** 應該就行了。

**Comment by ycpaladin** [comment]
补上之后，点击routerLink 后 module.ts 倒是可以正确下载了， 但是路由不正确, 应该是 /angular9/module1 实际 最后的url是 /module1，

**Comment by tommas3210** [comment]
> 补上之后，点击routerLink 后 module.ts 倒是可以正确下载了， 但是路由不正确, 应该是 /angular9/module1 实际 最后的url是 /module1，

再加個--base-href angular9

**Comment by ycpaladin** [comment]
> > 补上之后，点击routerLink 后 module.ts 倒是可以正确下载了， 但是路由不正确, 应该是 /angular9/module1 实际 最后的url是 /module1，
> 
> 再加個--base-href angular9

谢谢回复！现在已经跟react和vue项目一样了!!

最后在angular项目中完整的命令参数如下

"serve:qiankun": "ng serve --deploy-url http://localhost:7103/ --disable-host-check --port 7103 --base-href angular9 --live-reload false"


另外需要在app-routing.module.ts中的provides中加入/修改为

{ provide: APP_BASE_HREF, useValue: '**/angular9**'
