### ISSUE TITLE
[Bug]请遵循下文模板提交问题，否则您的问题会被关闭

### ISSUE THREAD

**Issue by JonesAtom** [umijs/qiankun#989]
## What happens?
主应用懒加载子应用时，配置沙盒用以隔离样式，但是子用户的model弹窗、时间选择器等不显示
sandbox: {
          strictStyleIsolation: true
        }

## 相关环境信息

- **qiankun 版本**: 2.0.25
- **浏览器版本**：chorme
- **操作系统**：mac
- **UI库**：elementUI

**Comment by lijing666** [comment]
strictStyleIsolation: true 模式时比较严格的隔离，使用了shadow dom技术了，可查阅[https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/%E5%BD%B1%E5%AD%90_DOM](https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/%E5%BD%B1%E5%AD%90_DOM)这里了解一下，严格模式下由于modal等组件很多ui库比如viewUI、elementui等都是附加dom到body中的，由于子应用使用了严格隔离模式，只能附加到shadow dom中，导致组件使用出现问题，所以官方也说了strictStyleIsolation: true是有限制的，并不适合所有场景的，希望对你有帮助 @JonesAtom

**Comment by kuitos** [comment]
![image](https://user-images.githubusercontent.com/5206843/95720712-2af80800-0ca4-11eb-8ae4-2f8c32fddaca.png)
