### ISSUE TITLE
[Bug]dva和qiankun存在兼容问题

### ISSUE THREAD

**Issue by wangkai1995** [umijs/qiankun#994]
# 提问之前强烈建立您能先阅读一下[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

## What happens?

公用一个dva数据的时候的时候，其中sidebar使用了subscriptions routeWatch ,子应用切换的时候 routeWatch的hashchange被沙盒的global.removeEventListener卸载，导致hashchange丢失

## 复现步骤，错误日志以及相关配置

1: 公用一个dva数据的时候的时候，其中sidebar使用了subscriptions routeWatch
2：subscriptions -> routeWatch在 dva.start()的时候才开始注册hashchange,在qiankun的unmount生命周期中调用
3: 子应用切换的时候 routeWatch的hashchange被沙盒的global.removeEventListener卸载，导致hashchange丢失

## 相关环境信息

- **qiankun 版本**
- **浏览器版本**：
- **操作系统**：

**Comment by wangkai1995** [comment]
暂时处理的办法目前是 主应用也启动一个dva。来规避这个问题

**Comment by kuitos** [comment]
提供可复现仓库后可以自己 reopen
