### ISSUE TITLE
子应用状态被重置问题

### ISSUE THREAD

**Issue by Dahyzeng** [umijs/qiankun#997]
官方实例中，在主应用中使用setGlobalState后，能在主应用看到state的变化，但点击链接进入子应用，整个状态都被重置了。比如在主应用中有个登录功能，登录成功后，更新globalState的token,然后点击子应用链接后，globalstate又被重置了token为空

**Comment by Dahyzeng** [comment]
![image](https://user-images.githubusercontent.com/8120004/96072654-51ea5000-0ed7-11eb-9fea-9e00fbbca76c.png)
这是主应用目录结构，
![image](https://user-images.githubusercontent.com/8120004/96072702-721a0f00-0ed7-11eb-836c-2adca8473381.png)
在主应用模拟登录后setGlobalState，
![image](https://user-images.githubusercontent.com/8120004/96072925-f1a7de00-0ed7-11eb-9fc1-aff42847f43b.png)
登录后ke可以看到globalState的变化
![image](https://user-images.githubusercontent.com/8120004/96072980-0dab7f80-0ed8-11eb-8c32-eecb564ee908.png)
当进入react16子应用时，globalState被重置了，
![image](https://user-images.githubusercontent.com/8120004/96073055-329ff280-0ed8-11eb-98f1-299ebc0d54f0.png)
react16的代码和官方一样没动过

**Comment by kuitos** [comment]
官方 example 无法复现 https://github.com/umijs/qiankun/blob/master/examples/main/index.js#L95

提供最小可复现仓库

**Comment by kuitos** [comment]
closed via inactive
